### ISSUE TITLE
TypeError - no implicit conversion of nil into String

### ISSUE THREAD

**Issue by wangbaoshige** [CocoaPods/CocoaPods#10007]
# Report

## What did you do?

ℹ Please replace these two lines with what you did.  
 Run `bundle exec pod install --repo-update`

## What did you expect to happen?

ℹ Please replace these two lines with what you expected to happen.  
  Install all pod dependencies correctly.

## What happened instead?

ℹ Please replace these two lines with of what happened instead.  
e.g. Oh no, an error occurred.TypeError - no implicit conversion of nil into String

### Error

```
TypeError - no implicit conversion of nil into String
/Users/wangbao/.bd_pod_extension_scripts/bd_pod_extension_net.rb:3216:in `include?'
/Users/wangbao/.bd_pod_extension_scripts/bd_pod_extension_net.rb:3216:in `canTrans'
/Users/wangbao/.bd_pod_extension_scripts/bd_pod_extension_net.rb:3279:in `rescue in block in <class:Cache>'
/Users/wangbao/.bd_pod_extension_scripts/bd_pod_extension_net.rb:3276:in `block in <class:Cache>'
/var/folders/z3/vmvts2m110v1z3z2s4l60rrr0000gn/T/ConcurrentDownload.rb:189:in `download_pod'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/downloader.rb:42:in `download'
/var/folders/z3/vmvts2m110v1z3z2s4l60rrr0000gn/T/ConcurrentDownload.rb:120:in `download_source'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/pod_source_installer.rb:69:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:557:in `install_source_of_pod'
/var/folders/z3/vmvts2m110v1z3z2s4l60rrr0000gn/T/ConcurrentDownload.rb:103:in `block (2 levels) in install_pod_sources'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:86:in `titled_section'
/var/folders/z3/vmvts2m110v1z3z2s4l60rrr0000gn/T/ConcurrentDownload.rb:88:in `block in install_pod_sources'
/var/folders/z3/vmvts2m110v1z3z2s4l60rrr0000gn/T/ConcurrentDownload.rb:68:in `each'
/var/folders/z3/vmvts2m110v1z3z2s4l60rrr0000gn/T/ConcurrentDownload.rb:68:in `each_with_index'
/var/folders/z3/vmvts2m110v1z3z2s4l60rrr0000gn/T/ConcurrentDownload.rb:68:in `install_pod_sources'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:248:in `block in download_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:247:in `download_dependencies'
/Users/wangbao/.bd_pod_extension_scripts/bd_pod_extension_net.rb:3188:in `call'
/Users/wangbao/.bd_pod_extension_scripts/bd_pod_extension_net.rb:3188:in `block in <class:Installer>'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:157:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-bytedance-monitor-0.0.12/lib/cocoapods-bytedance-monitor/installer.rb:27:in `call'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-bytedance-monitor-0.0.12/lib/cocoapods-bytedance-monitor/installer.rb:27:in `block in <class:Installer>'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-toutiao-1.12.4/lib/cocoapods-toutiao/installer_hooks.rb:12:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<top (required)>'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=no+implicit+conversion+of+nil+into+String&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
 - undefined method `map' for nil:NilClass
   https://github.com/CocoaPods/CocoaPods/issues/9953 [closed] [1 comment]
   4 weeks ago

 - TypeError - no implicit conversion of nil into String
   https://github.com/CocoaPods/CocoaPods/issues/6381 [closed] [17 comments]
   21 Mar 2020

 - An error occurred when I just run "Pod init"
   https://github.com/CocoaPods/CocoaPods/issues/8705 [closed] [6 comments]
   24 Apr 2019

and 20 more at:
https://github.com/cocoapods/cocoapods/search?q=no%20implicit%20conversion%20of%20nil%20into%20String&type=Issues&utf8=✓

**Comment by wangbaoshige** [comment]
cocoapods version 1.8.4     Xcode version 12 beta5

**Comment by dnkoutso** [comment]
From the stacktrace looks like its a script of your own failing?
```
/Users/wangbao/.bd_pod_extension_scripts/bd_pod_extension_net.rb:3216:in `include?'
/Users/wangbao/.bd_pod_extension_scripts/bd_pod_extension_net.rb:3216:in `canTrans'
/Users/wangbao/.bd_pod_extension_scripts/bd_pod_extension_net.rb:3279:in `rescue in block in <class:Cache>'
/Users/wangbao/.bd_pod_extension_scripts/bd_pod_extension_net.rb:3276:in `block in <class:Cache>'
```

Can you please upload a sample app demonstrating the issue without any custom plugins or scripts? Also please update to latest version of CocoaPods.

**Comment by HsS-2019** [comment]
meet the same question

**Comment by HsS-2019** [comment]
> meet the same question

restart iterm2 and reoperate. it show the real reason for my script
