### ISSUE TITLE
URI::InvalidURIError - URI must be ascii only "\u2018https://gitee.com/ios_lib/utilityappwidgetspec.git"

### ISSUE THREAD

**Issue by zhaoxiaoga** [CocoaPods/CocoaPods#10050]
Hello, I want to upgrade my private library and perform a normal update. This error is reported after running this command. Please help me to check how to solve it?

```
pod lib lint --use-libraries --allow-warnings --no-clean --verbose --sources=‘https://gitee.com/iOS_Lib/UtilityAppWidgetSpec.git,https://github.com/jiangfangsheng/BMKLocationKit.git,https://github.com/CocoaPods/Specs.git‘
```

This is the execution log:

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/XGCoder/.rvm/rubies/ruby-2.6.3/bin/pod lib lint --use-libraries --allow-warnings --no-clean --verbose --sources=‘https://gitee.com/iOS_Lib/UtilityAppWidgetSpec.git,https://github.com/jiangfangsheng/BMKLocationKit.git,https://github.com/CocoaPods/Specs.git‘
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.9.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin19]
    RubyGems : 3.0.6
        Host : Mac OS X 10.15.6 (19G2021)
       Xcode : 11.7 (11E801a)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /Users/XGCoder/.rvm/rubies/ruby-2.6.3/lib
Repositories : artsy - git - https://github.com/Artsy/Specs.git @ d70f6d5de16e32f4d001a6b9753ba65d250aa866

               bytedance - git - https://github.com/bytedance/cocoapods_sdk_source_repo.git @ c83ca1f0e86dac83ac0750e1a0836726d148edbc

               gitee-ios_lib-utilityappwidgetspec - git - https://gitee.com/iOS_Lib/UtilityAppWidgetSpec.git @ a14df2b947a4519b4f2d0ee59c93e96d895beb74

               gitee-ios_lib-utilityconfigspec - git - https://gitee.com/iOS_Lib/UtilityConfigSpec.git @ 5557ec7220fe6d91c18990cab6820f6c0552238b

               gitee-ios_lib-utilityspec - git - https://gitee.com/iOS_Lib/UtilitySpec.git @ a652ef04ab0d71f5372648a03cb41f271c770a17

               gitee-ios_lib-wesdklibspec - git - https://gitee.com/iOS_Lib/WESDKLibSpec.git @ 9fc01b5fcd946ba73c0d481a2a01a5c5d73126c7

               jiangfangsheng - git - https://github.com/jiangfangsheng/BMKLocationKit.git @ d960345613d5537825bf41319e4963821699d31f

               master - git - https://github.com/CocoaPods/Specs.git @ 453e36c3297415a338874b8675c5a7643c95f99a

               UtilityAppWidgetSpec - git - https://gitee.com/iOS_Lib/UtilityAppWidgetSpec @ a14df2b947a4519b4f2d0ee59c93e96d895beb74

               UtilitySpec - git - https://gitee.com/iOS_Lib/UtilityConfigSpec @ 5557ec7220fe6d91c18990cab6820f6c0552238b

```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '9.0'
inhibit_all_warnings!
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
source 'https://gitee.com/iOS_Lib/UtilityAppWidgetSpec.git'
source 'https://github.com/jiangfangsheng/BMKLocationKit.git'

project 'UtilityConfig.xcodeproj'

target :UtilityConfig do

pod 'UtilityAppWidget/DefaultsConst'

pod 'MJExtension'
pod 'AMapLocation-NO-IDFA'
pod 'AFNetworking'

pod 'BMKLocationKit'

end
```

### Error

```
URI::InvalidURIError - URI must be ascii only "\u2018https://gitee.com/ios_lib/utilityappwidgetspec.git"
/Users/XGCoder/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/uri/rfc3986_parser.rb:21:in `split'
/Users/XGCoder/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/uri/rfc3986_parser.rb:73:in `parse'
/Users/XGCoder/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/uri/common.rb:234:in `parse'
/Users/XGCoder/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/uri/common.rb:737:in `URI'
/Users/XGCoder/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/source/manager.rb:440:in `name_for_url'
/Users/XGCoder/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/sources_manager.rb:36:in `create_source_with_url'
/Users/XGCoder/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/sources_manager.rb:22:in `find_or_create_source_with_url'
/Users/XGCoder/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/sources_manager.rb:96:in `source_with_name_or_url'
/Users/XGCoder/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/validator.rb:47:in `block in initialize'
/Users/XGCoder/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/validator.rb:47:in `map'
/Users/XGCoder/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/validator.rb:47:in `initialize'
/Users/XGCoder/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command/lib/lint.rb:70:in `new'
/Users/XGCoder/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command/lib/lint.rb:70:in `block in run'
/Users/XGCoder/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command/lib/lint.rb:69:in `each'
/Users/XGCoder/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command/lib/lint.rb:69:in `run'
/Users/XGCoder/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/XGCoder/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command.rb:52:in `run'
/Users/XGCoder/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/bin/pod:55:in `<top (required)>'
/Users/XGCoder/.rvm/rubies/ruby-2.6.3/bin/pod:23:in `load'
/Users/XGCoder/.rvm/rubies/ruby-2.6.3/bin/pod:23:in `<main>'
/Users/XGCoder/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
/Users/XGCoder/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=URI+must+be+ascii+only+%22%5Cu2018https%3A%2F%2Fgitee.com%2Fios_lib%2Futilityappwidgetspec.git%22&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Found no similar issues. To create a new issue, please visit:
https://github.com/cocoapods/cocoapods/issues/new

**Comment by dnkoutso** [comment]
Your URL ""\u2018https://gitee.com/ios_lib/utilityappwidgetspec.git"" seems to contain an invalid character. Please fix the URL and try again.

**Comment by dnkoutso** [comment]
The character is https://www.fileformat.info/info/unicode/char/2018/index.htm
