### ISSUE TITLE
mass errors on "pod setup"

### ISSUE THREAD

**Issue by Macmee** [CocoaPods/CocoaPods#1005]
```
David-millers-iMac:~ davemiller$ pod setup
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/fileutils.rb:243:in `mkdir': File exists - /Users/davemiller/Library/Caches (Errno::EEXIST)
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/fileutils.rb:243:in `fu_mkdir'
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/fileutils.rb:217:in `mkpath'
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/fileutils.rb:215:in `reverse_each'
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/fileutils.rb:215:in `mkpath'
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/fileutils.rb:201:in `each'
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/fileutils.rb:201:in `mkpath'
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/pathname.rb:1035:in `mkpath'
    from /Library/Ruby/Gems/1.8/gems/cocoapods-0.18.1/lib/cocoapods.rb:29
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
    from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `require'
    from /Library/Ruby/Gems/1.8/gems/cocoapods-0.18.1/bin/pod:14
    from /usr/bin/pod:19:in `load'
    from /usr/bin/pod:19
David-millers-iMac:~ davemiller$ 
```

**Comment by loretoparisi** [comment]
I have the same error
for the project https://github.com/bjtitus/mac-miniplayer

Downloading dependencies
Installing AFNetworking (2.5.0)
Installing MagicalRecord (2.2)
Generating Pods project
[!] Unable to load a specification for the plugin `/Library/Ruby/Gems/2.0.0/gems/cocoapods-try-release-fix-0.1.2`

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 0.34.2
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.4.2
        Host : Mac OS X 10.10 (14A389)
       Xcode : 6.1.1 (6A2008a)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 287533f2678b199a47a677c6c8c50d9c8b1e6989
```

### Plugins

```
cocoapods-plugins : 0.3.1
cocoapods-trunk   : 0.3.0
cocoapods-try     : 0.4.1
```

### Podfile

```ruby
platform :osx, '10.9'

xcodeproj 'MiniPlayer'

target :'MiniPlayer' do
	pod 'AFNetworking',   '~> 2.2'
	pod 'MagicalRecord',  '~> 2.2'
end

target :'MiniPlayer' do
	pod 'AFNetworking',   '~> 2.2'
	pod 'MagicalRecord',  '~> 2.2'
end
```

### Error

```
Errno::EEXIST - File exists - /Users/admin/Projects/Mac/mac-miniplayer/Pods/Target Support Files/Pods-MiniPlayer-AFNetworking
