### ISSUE TITLE
Error installing nanopb please help

### ISSUE THREAD

**Issue by fifewas** [CocoaPods/CocoaPods#10075]
please scroll down to "### Error" to see the error log thank you.

younesss-Mac:MarioIos_2_newXcode younessbouemama$ pod install 
Analyzing dependencies
Cloning spec repo `cocoapods` from `https://github.com/CocoaPods/Specs`
Downloading dependencies
Installing Google-Mobile-Ads-SDK (7.65.0)
Installing GoogleAppMeasurement (6.8.2)
Installing GoogleUserMessagingPlatform (1.2.0)
Installing GoogleUtilities (6.7.2)
Installing PromisesObjC (1.2.10)
Installing nanopb (1.30906.0)

[!] Error installing nanopb

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.9.3
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 3.1.4
        Host : Mac OS X 10.14.6 (18G103)
       Xcode : 11.3.1 (11C505)
         Git : git version 2.21.1 (Apple Git-122.3)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs @ 8b4ca833596fdb242cf634a43ac662b104051540

```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'Unity-iPhone' do
  pod 'Google-Mobile-Ads-SDK', '~> 7.63'
end
```

### Error

```
Errno::ENOENT - No such file or directory @ dir_s_mkdir - /Users/younessbouemama/Library/Caches/CocoaPods/Pods/Release/nanopb/1.30906.0-59317
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:1367:in `mkdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:1367:in `copy'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:473:in `block in copy_entry'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:1499:in `wrap_traverse'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:470:in `copy_entry'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:445:in `block in cp_r'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:1572:in `block in fu_each_src_dest'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:1588:in `fu_each_src_dest0'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:1570:in `fu_each_src_dest'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:444:in `cp_r'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.3/lib/cocoapods/downloader/cache.rb:201:in `copy_and_clean'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.3/lib/cocoapods/downloader/cache.rb:159:in `block (2 levels) in uncached_pod'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.3/lib/cocoapods/downloader/cache.rb:157:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.3/lib/cocoapods/downloader/cache.rb:157:in `block in uncached_pod'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.3/lib/cocoapods/downloader/cache.rb:181:in `in_tmpdir'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.3/lib/cocoapods/downloader/cache.rb:153:in `uncached_pod'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.3/lib/cocoapods/downloader/cache.rb:33:in `download_pod'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.3/lib/cocoapods/downloader.rb:42:in `download'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/pod_source_installer.rb:117:in `download_source'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/pod_source_installer.rb:69:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:557:in `install_source_of_pod'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:508:in `block (2 levels) in install_pod_sources'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.3/lib/cocoapods/user_interface.rb:86:in `titled_section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:507:in `block in install_pod_sources'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:490:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:490:in `install_pod_sources'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:249:in `block in download_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.3/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:248:in `download_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:157:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.3/lib/cocoapods/command/install.rb:52:in `run'
/Users/younessbouemama/.gem/ruby/2.3.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.3/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'

**Comment by dnkoutso** [comment]
Seems liked a borked cache. Try `pod cache clean --all` and try again?

**Comment by dnkoutso** [comment]
Actually see https://github.com/CocoaPods/CocoaPods/issues/10074 as a dup sort of. Closing this.
