### ISSUE TITLE
Nanaimo::Reader::ParseError - [!] Dictionary missing ';' after key-value pair for "CODE_SIGN_ENTITLEMENTS", found "\\"

### ISSUE THREAD

**Issue by popeating** [CocoaPods/CocoaPods#10081]
### Command

```
/usr/local/Cellar/cocoapods/1.9.3/libexec/bin/pod install
```

### Report

* What did you do? 
Initialize pod after installing modules

* What did you expect to happen?
pods installation and linkng

* What happened instead?
it didint go through and showed an error

### Stack

```
   CocoaPods : 1.9.3
        Ruby : ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin18]
    RubyGems : 3.1.2
        Host : Mac OS X 10.14.6 (18G103)
       Xcode : 11.2 (11B52)
         Git : git version 2.28.0
Ruby lib dir : /usr/local/Cellar/ruby/2.7.1_2/lib
Repositories : 
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
platform :ios, '10.0'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

def add_flipper_pods!(versions = {})
  versions['Flipper'] ||= '~> 0.33.1'
  versions['DoubleConversion'] ||= '1.1.7'
  versions['Flipper-Folly'] ||= '~> 2.1'
  versions['Flipper-Glog'] ||= '0.3.6'
  versions['Flipper-PeerTalk'] ||= '~> 0.0.4'
  versions['Flipper-RSocket'] ||= '~> 1.0'

  pod 'FlipperKit', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitLayoutPlugin', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/SKIOSNetworkPlugin', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitUserDefaultsPlugin', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitReactPlugin', versions['Flipper'], :configuration => 'Debug'

  # List all transitive dependencies for FlipperKit pods
  # to avoid them being linked in Release builds
  pod 'Flipper', versions['Flipper'], :configuration => 'Debug'
  pod 'Flipper-DoubleConversion', versions['DoubleConversion'], :configuration => 'Debug'
  pod 'Flipper-Folly', versions['Flipper-Folly'], :configuration => 'Debug'
  pod 'Flipper-Glog', versions['Flipper-Glog'], :configuration => 'Debug'
  pod 'Flipper-PeerTalk', versions['Flipper-PeerTalk'], :configuration => 'Debug'
  pod 'Flipper-RSocket', versions['Flipper-RSocket'], :configuration => 'Debug'
  pod 'FlipperKit/Core', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/CppBridge', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FBCxxFollyDynamicConvert', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FBDefines', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FKPortForwarding', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitHighlightOverlay', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitLayoutTextSearchable', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitNetworkPlugin', versions['Flipper'], :configuration => 'Debug'
end

# Post Install processing for Flipper
def flipper_post_install(installer)
  installer.pods_project.targets.each do |target|
    if target.name == 'YogaKit'
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.1'
      end
    end
  end
end

target 'firebase' do
  # Pods for firebase
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/callinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga', :modular_headers => true

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  use_unimodules!
  use_native_modules!

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  add_flipper_pods!
  post_install do |installer|
    flipper_post_install(installer)
  end
end
```

### Error

```
Nanaimo::Reader::ParseError - [!] Dictionary missing ';' after key-value pair for "CODE_SIGN_ENTITLEMENTS", found "\\"
   #  -------------------------------------------
   #  				VERSIONING_SYSTEM = "apple-generic";
   #  				TARGETED_DEVICE_FAMILY = "1,2";
299>  				CODE_SIGN_ENTITLEMENTS = C:\Users\lorenzo\firebase\ios\firebase\firebase.entitlements;
      				                           ^
   #  			};
   #  			name = Debug;
   #  -------------------------------------------

/usr/local/Cellar/cocoapods/1.9.3/libexec/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:284:in `raise_parser_error'
/usr/local/Cellar/cocoapods/1.9.3/libexec/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:199:in `parse_dictionary'
/usr/local/Cellar/cocoapods/1.9.3/libexec/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:132:in `parse_object'
/usr/local/Cellar/cocoapods/1.9.3/libexec/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:193:in `parse_dictionary'
/usr/local/Cellar/cocoapods/1.9.3/libexec/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:132:in `parse_object'
/usr/local/Cellar/cocoapods/1.9.3/libexec/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:193:in `parse_dictionary'
/usr/local/Cellar/cocoapods/1.9.3/libexec/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:132:in `parse_object'
/usr/local/Cellar/cocoapods/1.9.3/libexec/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:193:in `parse_dictionary'
/usr/local/Cellar/cocoapods/1.9.3/libexec/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:132:in `parse_object'
/usr/local/Cellar/cocoapods/1.9.3/libexec/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:107:in `parse!'
/usr/local/Cellar/cocoapods/1.9.3/libexec/gems/xcodeproj-1.16.0/lib/xcodeproj/plist.rb:27:in `read_from_path'
/usr/local/Cellar/cocoapods/1.9.3/libexec/gems/xcodeproj-1.16.0/lib/xcodeproj/project.rb:210:in `initialize_from_file'
/usr/local/Cellar/cocoapods/1.9.3/libexec/gems/xcodeproj-1.16.0/lib/xcodeproj/project.rb:112:in `open'
/usr/local/Cellar/cocoapods/1.9.3/libexec/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer.rb:1177:in `block (2 levels) in inspect_targets_to_integrate'
/usr/local/Cellar/cocoapods/1.9.3/libexec/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer.rb:1176:in `each'
/usr/local/Cellar/cocoapods/1.9.3/libexec/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer.rb:1176:in `block in inspect_targets_to_integrate'
/usr/local/Cellar/cocoapods/1.9.3/libexec/gems/cocoapods-1.9.3/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/Cellar/cocoapods/1.9.3/libexec/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer.rb:1171:in `inspect_targets_to_integrate'
/usr/local/Cellar/cocoapods/1.9.3/libexec/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer.rb:106:in `analyze'
/usr/local/Cellar/cocoapods/1.9.3/libexec/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:410:in `analyze'
/usr/local/Cellar/cocoapods/1.9.3/libexec/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:235:in `block in resolve_dependencies'
/usr/local/Cellar/cocoapods/1.9.3/libexec/gems/cocoapods-1.9.3/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/Cellar/cocoapods/1.9.3/libexec/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:234:in `resolve_dependencies'
/usr/local/Cellar/cocoapods/1.9.3/libexec/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:156:in `install!'
/usr/local/Cellar/cocoapods/1.9.3/libexec/gems/cocoapods-1.9.3/lib/cocoapods/command/install.rb:52:in `run'
/usr/local/Cellar/cocoapods/1.9.3/libexec/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/usr/local/Cellar/cocoapods/1.9.3/libexec/gems/cocoapods-1.9.3/lib/cocoapods/command.rb:52:in `run'
/usr/local/Cellar/cocoapods/1.9.3/libexec/gems/cocoapods-1.9.3/bin/pod:55:in `<top (required)>'
/usr/local/Cellar/cocoapods/1.9.3/libexec/bin/pod:23:in `load'
/usr/local/Cellar/cocoapods/1.9.3/libexec/bin/pod:23:in `<main>'

**Comment by popeating** [comment]
didnt notice the C:\, probably the project was passed to me from someone that generaated it on windows!
sorry!
