### ISSUE TITLE
[Xcodeproj] Consistency issue: build setting `ARCHS` has multiple values.

### ISSUE THREAD

**Issue by SuperMarioBean** [CocoaPods/CocoaPods#10138]
### Command

```
/usr/local/lib/ruby/gems/2.7.0/bin/pod install
```

### Report

* What did you do?

I create a project named it sample, and I change sample.xcodeproj build setting 'ARCHS' like this:
```
`{"Debug"=>"$(ARCHS_STANDARD)", "Release"=>"arm64"}`
```
> my release build will never submit to appstore, so with the aim to reduce package size, I only want it build with arm64
then I go to terminal and run "pod install"

* What did you expect to happen?

no error reported and I can archive sample.app in arm64

* What happened instead?

error reported

### Stack

```
   CocoaPods : 1.9.3
        Ruby : ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]
    RubyGems : 3.1.4
        Host : macOS 11.0 (20A5384c)
       Xcode : 12.0.1 (12A7300)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /usr/local/Cellar/ruby/2.7.2/lib
Repositories : 26-scm-sa-sepspecs - git - http://10.157.26.43:7990/scm/sa/sepspecs.git @ bb9327c8713978fe5f711ff85a32950af972c08f

               cocoapods - git - https://github.com/CocoaPods/Specs.git @ eee6352307ddd8bf4ed70a8164c7c127b7bce995

               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sample

  target 'sampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'sampleUITests' do
    # Pods for testing
  end

end
```

### Error

```
RuntimeError - [Xcodeproj] Consistency issue: build setting `ARCHS` has multiple values: `{"Debug"=>"$(ARCHS_STANDARD)", "Release"=>"arm64"}`
/usr/local/lib/ruby/gems/2.7.0/gems/xcodeproj-1.18.0/lib/xcodeproj/project/object/native_target.rb:95:in `common_resolved_build_setting'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer/target_inspector.rb:176:in `block in compute_archs'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer/target_inspector.rb:175:in `each'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer/target_inspector.rb:175:in `flat_map'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer/target_inspector.rb:175:in `compute_archs'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer/target_inspector.rb:44:in `compute_results'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer.rb:1180:in `block (3 levels) in inspect_targets_to_integrate'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer.rb:1178:in `each'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer.rb:1178:in `block (2 levels) in inspect_targets_to_integrate'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer.rb:1176:in `each'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer.rb:1176:in `block in inspect_targets_to_integrate'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.3/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer.rb:1171:in `inspect_targets_to_integrate'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer.rb:106:in `analyze'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:410:in `analyze'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:235:in `block in resolve_dependencies'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.3/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:234:in `resolve_dependencies'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:156:in `install!'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.3/lib/cocoapods/command/install.rb:52:in `run'
/usr/local/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.3/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.3/bin/pod:55:in `<top (required)>'
/usr/local/lib/ruby/gems/2.7.0/bin/pod:23:in `load'
/usr/local/lib/ruby/gems/2.7.0/bin/pod:23:in `<main>'
```

**Comment by SuperMarioBean** [comment]
any suggestions?

**Comment by SuperMarioBean** [comment]
Is there anyone can help me?

**Comment by leeeomaaax** [comment]
I'm facing the same issue. As a workaround, you can leave your archs consistent so everything works in development (eg. $(ARCHS_STANDARD) for both debug and release variants) and programatically replace your archs in your release deploy script/CI.

`
sed -i '' 's/\"$(ARCHS_STANDARD)\"/arm64/g' ../#{pbxproj_full_path}

**Comment by leeeomaaax** [comment]
I'm facing the same issue. As a workaround, you can leave your archs consistent so everything works in development (eg. $(ARCHS_STANDARD) for both debug and release variants) and programmatically replace your archs in your release deploy script/CI.

```
sed -i '' 's/\"$(ARCHS_STANDARD)\"/arm64/g' ./ios/YourApp.xcodeproj/project.pbxproj
```

For reference:
### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]
    RubyGems : 3.2.9
        Host : Mac OS X 10.15.7 (19H114)
       Xcode : 12.4 (12D4e)
         Git : git version 2.28.0
Ruby lib dir : /usr/local/Cellar/ruby/2.7.2/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

**Comment by cristianoccazinsp** [comment]
Same issue.
