### ISSUE TITLE
pod repo push - Unable to find the repo

### ISSUE THREAD

**Issue by JulesMoorhouse** [CocoaPods/CocoaPods#10157]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

`pod repo push mcl-specs mcl-core.podspec --allow-warnings --verbose
`
## What did you expect to happen?

To update my private pod spec repo.

## What happened instead?
```

Cloning spec repo `mcl-specs` from `mcl-specs`
[!] Unable to find the `mcl-specs` repo. If it has not yet been cloned, add it via `pod repo add`.

/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/command/repo/push.rb:67:in `validate!'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:333:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'

```
### Stack

```
   CocoaPods : 1.9.3
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.1.4
        Host : Mac OS X 10.15.7 (19H2)
       Xcode : 12.0.1 (12A7300)
         Git : git version 2.22.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
               visualstudio-pods-_git-mcl-specs - git - https://myrepo.visualstudio.com/Pods/_git/mcl-specs @ 

```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

## Project that demonstrates the issue
```

Pod::Spec.new do |s|
  s.name             = 'mcl-core'
  s.version          = '0.1.7'
  s.summary          = 'Common functionality'

  s.description      = <<-DESC
Some device detection functionality.
Will add some date functions etc too.
                       DESC

  s.homepage         = 'https://myrepo.visualstudio.com/Pods/_git/mcl-core'
  s.license          = { :type => 'MIT', :file => 'LICENSE' }
  s.author           = { 'myuserid' => 'myemail@gmail.com' }
  s.source           = { :git => 'https://myrepo.visualstudio.com/Pods/_git/mcl-core', :tag => s.version.to_s }

  s.ios.deployment_target = '9.3'

  s.swift_version = '5.0'

  s.source_files = 'mcl-core/Classes/**/*'
 
  s.public_header_files = 'mcl-core/**/*.h'
end

```

I've also tried the release candidate version of Cocoapods.
I did see the similar issue from 2018 but I couldn't find a fix there.

**Comment by dnkoutso** [comment]
Did you try to add the repo as the instructions say?

**Comment by JulesMoorhouse** [comment]
I already have the repo, I'm just trying to update it.

**Comment by dnkoutso** [comment]
Can you run `pod repo list` and see the name of your repo?

**Comment by JulesMoorhouse** [comment]
```
trunk
- Type: CDN
- URL:  https://cdn.cocoapods.org/
- Path: /Users/jm/.cocoapods/repos/trunk

visualstudio-pods-_git-mcl-specs
- Type: git (master)
- URL:  https://myrepo.visualstudio.com/Pods/_git/mcl-specs
- Path: /Users/jm/.cocoapods/repos/visualstudio-pods-_git-mcl-specs

2 repos
```

**Comment by dnkoutso** [comment]
Looks like you need to use

```pod repo push visualstudio-pods-_git-mcl-specs ...```

**Comment by JulesMoorhouse** [comment]
Thanks 👍
