### ISSUE TITLE
pod install failure with Realm

### ISSUE THREAD

**Issue by FrizzTheSnail** [CocoaPods/CocoaPods#10196]
### Command

```
/Users/david/.rvm/rubies/ruby-2.7.2/bin/pod install
```

### Report

* What did you do?

launched: pod install

* What did you expect to happen?

pods for my project to be configured

* What happened instead?

I got an error and this report
**This error happens when I include the REALM library in my cocoapods. If I take out realm everything works.
On a different machine I don't have such problem. Tried to update RUBY, Cocoapods, but to no avail**

### Stack

```
   CocoaPods : 1.10.0
        Ruby : ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]
    RubyGems : 3.1.4
        Host : Mac OS X 10.15.7 (19H2)
       Xcode : 12.1 (12A7403)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /Users/david/.rvm/rubies/ruby-2.7.2/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ db774ae593e719f48a4bf2b80f36f2fcb1b930a5

               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
use_frameworks! :linkage => :static

def shared_pods
   pod 'Realm'
end

target 'myprogram' do

    platform :ios, '11.0'

    # ignore all warnings from all pods
    inhibit_all_warnings!

    # Firebase
    pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'Firebase/Messaging'
    pod 'Firebase/Firestore'
    pod 'Firebase/Functions'
    pod 'Firebase/Storage'
    pod 'Firebase/Performance'
    pod 'Firebase/Crashlytics'
    pod 'Firebase/Analytics'

    # Google Places
    pod 'GooglePlaces'
    pod 'GooglePlacePicker'

    # GRAPHIC STUFF
    pod 'STPopup'
    pod 'TOCropViewController'

    shared_pods
end

target 'NotificationExtension' do

    platform :ios, '11.0'

    # ignore all warnings from all pods
    inhibit_all_warnings!

    #inherit! :search_paths
    shared_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
```

### Error

```
JSON::ParserError - 434: unexpected token at '"Realm/ObjectStore/src/sync/impl/app'
/Users/david/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/json/common.rb:156:in `parse'
/Users/david/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/json/common.rb:156:in `parse'
/Users/david/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/specification/json.rb:61:in `from_json'
/Users/david/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/specification.rb:742:in `from_string'
/Users/david/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/specification.rb:716:in `from_file'
/Users/david/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/source.rb:186:in `specification'
/Users/david/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/resolver/lazy_specification.rb:37:in `specification'
/Users/david/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/delegate.rb:342:in `block in delegating_block'
/Users/david/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/delegate.rb:343:in `block in delegating_block'
/Users/david/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/resolver.rb:178:in `dependencies_for'
/Users/david/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:18:in `block in dependencies_for'
/Users/david/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:70:in `with_no_such_dependency_error_handling'
/Users/david/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:17:in `dependencies_for'
/Users/david/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:807:in `block in group_possibilities'
/Users/david/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:806:in `reverse_each'
/Users/david/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:806:in `group_possibilities'
/Users/david/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:778:in `possibilities_for_requirement'
/Users/david/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:761:in `push_state_for_requirements'
/Users/david/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:746:in `require_nested_dependencies_for'
/Users/david/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:729:in `activate_new_spec'
/Users/david/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:686:in `attempt_to_activate'
/Users/david/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:254:in `process_topmost_state'
/Users/david/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
/Users/david/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
/Users/david/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/resolver.rb:94:in `resolve'
/Users/david/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:1074:in `block in resolve_dependencies'
/Users/david/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/user_interface.rb:64:in `section'
/Users/david/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:1072:in `resolve_dependencies'
/Users/david/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/Users/david/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:414:in `analyze'
/Users/david/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:239:in `block in resolve_dependencies'
/Users/david/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/user_interface.rb:64:in `section'
/Users/david/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:238:in `resolve_dependencies'
/Users/david/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:160:in `install!'
/Users/david/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/command/install.rb:52:in `run'
/Users/david/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/david/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/command.rb:52:in `run'
/Users/david/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/bin/pod:55:in `<top (required)>'
/Users/david/.rvm/rubies/ruby-2.7.2/bin/pod:23:in `load'
/Users/david/.rvm/rubies/ruby-2.7.2/bin/pod:23:in `<main>'
/Users/david/.rvm/rubies/ruby-2.7.2/bin/ruby_executable_hooks:24:in `eval'
/Users/david/.rvm/rubies/ruby-2.7.2/bin/ruby_executable_hooks:24:in `<main>'

**Comment by igor-makarov** [comment]
This sounds very similar to https://github.com/CocoaPods/CocoaPods/issues/10118 

Do you mind deleting the spec repo and retrying?

**Comment by FrizzTheSnail** [comment]
> This sounds very similar to #10118
> 
> Do you mind deleting the spec repo and retrying?

Yes, it did the job! Thank you so much!!!
