### ISSUE TITLE
CocoaPods not working, Gem ERROR

### ISSUE THREAD

**Issue by talezion** [CocoaPods/CocoaPods#10250]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Any pod command.

## What did you expect to happen?

To work

## What happened instead?

ℹ Please replace these two lines with of what happened instead.  
Not working

## CocoaPods Environment
Getting the same error

## Project that demonstrates the issue
it's only an issue with CocoaPods the tool.

- Tried RVM with different ruby versions
```
=* ruby-2.3.0 [ x86_64 ]
   ruby-2.6.3 [ x86_64 ]
   ruby-2.7.0 [ x86_64 ]
```
- Uninstall, install not working

Nothing seems to work. Thinking for resetting my mac. Can't seem to find the issue for over a month now. 

```
% pod --version
Traceback (most recent call last):
	12: from /usr/local/Cellar/cocoapods/1.9.3/libexec/bin/pod:23:in `<main>'
	11: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:303:in `activate_bin_path'
	10: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:303:in `synchronize'
	 9: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:304:in `block in activate_bin_path'
	 8: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1420:in `activate'
	 7: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `activate_dependencies'
	 6: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `each'
	 5: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1452:in `block in activate_dependencies'
	 4: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1420:in `activate'
	 3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `activate_dependencies'
	 2: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `each'
	 1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1449:in `block in activate_dependencies'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/dependency.rb:311:in `to_specs': Could not find 'CFPropertyList' (>= 2.3.3, < 4.0) among 74 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/Users/auser/.rvm/gems/ruby-2.3.0:/Users/auser/.rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0:/usr/local/Cellar/cocoapods/1.9.3/libexec', execute `gem env` for more information
```

Gem ENV:

```
RubyGems Environment:
  - RUBYGEMS VERSION: 3.0.8
  - RUBY VERSION: 2.3.0 (2015-12-25 patchlevel 0) [x86_64-darwin19]
  - INSTALLATION DIRECTORY: /Users/auser/.rvm/gems/ruby-2.3.0
  - USER INSTALLATION DIRECTORY: /Users/auser/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: /Users/auser/.rvm/rubies/ruby-2.3.0/bin/ruby
  - GIT EXECUTABLE: /usr/local/bin/git
  - EXECUTABLE DIRECTORY: /Users/auser/.rvm/gems/ruby-2.3.0/bin
  - SPEC CACHE DIRECTORY: /Users/auser/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/auser/.rvm/rubies/ruby-2.3.0/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-19
  - GEM PATHS:
     - /Users/auser/.rvm/gems/ruby-2.3.0
     - /Users/auser/.rvm/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/auser/.rvm/gems/ruby-2.3.0/bin
     - /Users/auser/.rvm/gems/ruby-2.3.0@global/bin
     - /Users/auser/.rvm/rubies/ruby-2.3.0/bin
     - /Users/auser/.rvm/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /Library/Apple/usr/bin
```

**Comment by dnkoutso** [comment]
This seems an environment issue with Ruby. Does not appear an issue with cocoapods.

**Comment by khedherinader** [comment]
@talezion did you found a solution for this issue ?
