### ISSUE TITLE
Cocoapods `pod update` error: Illformed requirement `"= "`

### ISSUE THREAD

**Issue by Fab1n** [CocoaPods/CocoaPods#10256]
I have a problem with updating Realm using cocoapods.
The error is `Illformed requirement` (check out below)

We're including Realm in another Pod that is local.

Podfile looks like that:
pod 'OurCustomPod', :path => '.' # podspec lives in the same dir
pod 'Realm', :source => 'git@our-pods.repo'
pod 'RealmSwift', :source => 'git@our-pods.repo'
.
.
.

We have a Realm repo on our servers. 
Also we host our own pods repo for our custom pods.

Also I always see a `sh: build.sh: No such file or directory` showing up, even when pod install and update are working.

#### Workaround:

When I remove 

```ruby
pod 'Realm', :source => 'git@our-pods.repo'
pod 'RealmSwift', :source => 'git@our-pods.repo'
```

from the `Podfile` it works IFF the realm version required is a unique version and is not there in the public specs repo (for example Realm 10.1.4 is a public spec and if we publish the same spec in our private specs repo cocoapods finds multiple specs that could match but does not know which one to prefer - thus we force to use our custom specs repo with the Realm pod dependencies). It work for example if we push a spec with the version 10.1.99 as this version is only present in our private specs repo.

How can this be managed correctly?

### Command

```
/usr/local/lib/ruby/gems/2.7.0/bin/pod update Realm RealmSwift
```

### Report

* What did you do?
`pod update Realm RealmSwift`

* What did you expect to happen?
Run through

* What happened instead?
This error below

### Stack

```
   CocoaPods : 1.10.0
        Ruby : ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]
    RubyGems : 3.1.2
        Host : Mac OS X 10.15.7 (19H2)
       Xcode : 12.0.1 (12A7300)
         Git : git version 2.25.0
Ruby lib dir : /usr/local/Cellar/ruby/2.7.1_2/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ fbbdc5e5895342816457e38f7466e425a429b0ab

               <Custom repo cut out here>

               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Error

```
ArgumentError - Illformed requirement `"= "`
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/requirement.rb:63:in `parse'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/requirement.rb:88:in `block in initialize'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/requirement.rb:88:in `map!'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/requirement.rb:88:in `initialize'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/requirement.rb:34:in `new'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/requirement.rb:34:in `create'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/dependency.rb:101:in `initialize'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/specification/consumer.rb:223:in `new'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/specification/consumer.rb:223:in `block in dependencies'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/specification/consumer.rb:222:in `each'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/specification/consumer.rb:222:in `map'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/specification/consumer.rb:222:in `dependencies'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/specification.rb:403:in `block in dependencies'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/specification.rb:402:in `map'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/specification.rb:402:in `dependencies'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/specification.rb:411:in `all_dependencies'
/usr/local/Cellar/ruby/2.7.1_2/lib/ruby/2.7.0/delegate.rb:343:in `block in delegating_block'
/usr/local/Cellar/ruby/2.7.1_2/lib/ruby/2.7.0/delegate.rb:343:in `block in delegating_block'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/resolver.rb:178:in `dependencies_for'
/usr/local/lib/ruby/gems/2.7.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:18:in `block in dependencies_for'
/usr/local/lib/ruby/gems/2.7.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:70:in `with_no_such_dependency_error_handling'
/usr/local/lib/ruby/gems/2.7.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:17:in `dependencies_for'
/usr/local/lib/ruby/gems/2.7.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:807:in `block in group_possibilities'
/usr/local/lib/ruby/gems/2.7.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:806:in `reverse_each'
/usr/local/lib/ruby/gems/2.7.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:806:in `group_possibilities'
/usr/local/lib/ruby/gems/2.7.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:778:in `possibilities_for_requirement'
/usr/local/lib/ruby/gems/2.7.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:761:in `push_state_for_requirements'
/usr/local/lib/ruby/gems/2.7.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:746:in `require_nested_dependencies_for'
/usr/local/lib/ruby/gems/2.7.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:729:in `activate_new_spec'
/usr/local/lib/ruby/gems/2.7.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:686:in `attempt_to_activate'
/usr/local/lib/ruby/gems/2.7.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:254:in `process_topmost_state'
/usr/local/lib/ruby/gems/2.7.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
/usr/local/lib/ruby/gems/2.7.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/resolver.rb:94:in `resolve'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:1074:in `block in resolve_dependencies'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:1072:in `resolve_dependencies'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:414:in `analyze'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:239:in `block in resolve_dependencies'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:238:in `resolve_dependencies'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:160:in `install!'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/command/update.rb:63:in `run'
/usr/local/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/bin/pod:55:in `<top (required)>'
/usr/local/lib/ruby/gems/2.7.0/bin/pod:23:in `load'
/usr/local/lib/ruby/gems/2.7.0/bin/pod:23:in `<main>'
```

**Comment by dnkoutso** [comment]
You will need to paste the custom Realm podspec you have in your private repo for us to diagnose this.

**Comment by dnkoutso** [comment]
Potentially upload a sample app that demonstrates the issue would be good.

**Comment by Fab1n** [comment]
Ok, thanks, as soon as I have some time I will post the podspec and I will try to put together a minimal failing project.
