### ISSUE TITLE
Cocoapod with optional subspecs is not installing, if subspecs in the Podfile and another dependent Cocoapod podspec doesn't match 

### ISSUE THREAD

**Issue by npamidisf** [CocoaPods/CocoaPods#10264]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

Hi, I am running into an issue while running `pod install` when one of the cocoapods in the Podfile has optional subspecs.

This is only happening, if the podfile has another cocoapod which also has the same dependency on the cocoapod with optional subspecs and if the subspec deps doesn't match with the list in podfile...

As you can see [here] (https://github.com/npamidisf/CocoapodSubspecSample/blob/main/Podfile#L6), i have mentioned the base pod and an optional subspec.. 

And here's the local cocoapod [link](https://github.com/npamidisf/CocoapodSubspecSample/blob/main/UITestsSDK.podspec#L30) which depends on the same cocoapod but without the optional subspec as listed in the Podfile.

`pod install` fails with the below error. But, if you uncomment this [line](https://github.com/npamidisf/CocoapodSubspecSample/blob/main/UITestsSDK.podspec#L30) .. `pod install` goes through fine. 

I am wondering if this expected.

# Report

## What did you do?

ℹ Please replace these two lines with what you did.  
Ran `pod install`

## What did you expect to happen?
Install all pod and its optional subspecs along with dependencies correctly.

### Stack

```
   CocoaPods : 1.10.0
        Ruby : ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin18]
    RubyGems : 3.0.6
        Host : Mac OS X 10.15.7 (19H15)
       Xcode : 12.2 (12B45b)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /Users/*/.rvm/rubies/ruby-2.4.2/lib
Repositories : * - file system
               master - git - https://github.com/CocoaPods/Specs.git @ 74df87cd2a4f78abb22d63f79b324507bed89230
             
               trunk - CDN - https://cdn.cocoapods.org/

```

### Plugins

```
claide-plugins        : 0.9.2
cocoapods-art         : 1.0.5
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-rome        : 1.0.1
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
slather               : 2.5.0
```

### Podfile

```ruby
platform :ios, '12.0'

workspace 'Example/CocoapodSubspecSample'
project 'Example/CocoapodSubspecSample.xcodeproj'

def dev_pods
  pod 'CocoapodSubspecSample', :path => 'CocoapodSubspecSample.podspec'
  pod 'CocoapodSubspecSample/FeatureTwo', :path => 'CocoapodSubspecSample.podspec'
end

def unit_test_pods
  pod 'OCMock', '3.4'
end

def ui_test_pods
  pod 'UITestsSDK', :path => 'UITestsSDK.podspec'
end

target 'CocoapodSubspecSample_Example' do
  use_frameworks!
  dev_pods
 
  target 'CocoapodSubspecSample_Tests' do
    inherit! :search_paths

    # Pods for testing
    unit_test_pods
  end

  target 'CocoapodSubspecSample_UITests' do
    inherit! :search_paths

    # Pods for testing
    ui_test_pods
  end
end
```

### Error

```
NoMethodError - undefined method `map' for :none:Symbol
Did you mean?  tap
/Users/npamidi/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer/pod_variant_set.rb:122:in `scope_by_specs'
/Users/npamidi/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer/pod_variant_set.rb:26:in `scope_suffixes'
/Users/npamidi/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:643:in `block in generate_pod_targets'
/Users/npamidi/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:639:in `each'
/Users/npamidi/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:639:in `flat_map'
/Users/npamidi/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:639:in `generate_pod_targets'
/Users/npamidi/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:431:in `generate_targets'
/Users/npamidi/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:127:in `analyze'
/Users/npamidi/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:414:in `analyze'
/Users/npamidi/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:239:in `block in resolve_dependencies'
/Users/npamidi/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.10.0/lib/cocoapods/user_interface.rb:64:in `section'
/Users/npamidi/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:238:in `resolve_dependencies'
/Users/npamidi/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:160:in `install!'
/Users/npamidi/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.10.0/lib/cocoapods/command/install.rb:52:in `run'
/Users/npamidi/.rvm/gems/ruby-2.4.2/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/npamidi/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.10.0/lib/cocoapods/command.rb:52:in `run'
/Users/npamidi/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.10.0/bin/pod:55:in `<top (required)>'
/Users/npamidi/.rvm/gems/ruby-2.4.2/bin/pod:23:in `load'
/Users/npamidi/.rvm/gems/ruby-2.4.2/bin/pod:23:in `<main>'
/Users/npamidi/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:24:in `eval'
/Users/npamidi/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:24:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

## CocoaPods Environment

/Users/npamidi/.cocoapods/repos-art/*/.artpodrc

### Stack

```
   CocoaPods : 1.10.0
        Ruby : ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin18]
    RubyGems : 3.0.6
        Host : Mac OS X 10.15.7 (19H15)
       Xcode : 12.2 (12B45b)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /Users/*/.rvm/rubies/ruby-2.4.2/lib
Repositories : 
               master - git - https://github.com/CocoaPods/Specs.git @ 74df87cd2a4f78abb22d63f79b324507bed89230
```

### Installation Source

```
Executable Path: /Users/*/.rvm/gems/ruby-2.4.2/bin/pod
```

### Plugins

```
claide-plugins        : 0.9.2
cocoapods-art         : 1.0.5
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-rome        : 1.0.1
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
slather               : 2.5.0
```

### Podfile

```ruby
platform :ios, '12.0'

workspace 'Example/CocoapodSubspecSample'
project 'Example/CocoapodSubspecSample.xcodeproj'

def dev_pods
  pod 'CocoapodSubspecSample', :path => 'CocoapodSubspecSample.podspec'
  pod 'CocoapodSubspecSample/FeatureTwo', :path => 'CocoapodSubspecSample.podspec'
end

def unit_test_pods
  pod 'OCMock', '3.4'
end

def ui_test_pods
  pod 'UITestsSDK', :path => 'UITestsSDK.podspec'
end

target 'CocoapodSubspecSample_Example' do
  use_frameworks!
  dev_pods
 
  target 'CocoapodSubspecSample_Tests' do
    inherit! :search_paths

    # Pods for testing
    unit_test_pods
  end

  target 'CocoapodSubspecSample_UITests' do
    inherit! :search_paths

    # Pods for testing
    ui_test_pods
  end
end
```

ℹ Please link to a project we can download that reproduces the issue.
https://github.com/npamidisf/CocoapodSubspecSample

**Comment by npamidisf** [comment]
Can someone look into this issuee?

**Comment by SergeyKovalenko** [comment]
Have the same issue with
`spec.default_subspecs = :none`

**Comment by timothyekl** [comment]
I'm hitting the same issue as well, and I don't think I have the same kind of additional dependency described above. Instead, I have two targets in my Podfile, which looks roughly like:

```
target 'CoreExample' do
    pod 'Example', :path => '../', :testspecs => ['Tests']
end

target 'FeatureExample' do
    pod 'Example/Feature', :path => '../'
end
```

My example podspec file does specify `default_subspec = :none`. 

If I comment out the second `target` block, the first one installs just fine. The presence of the second target makes the whole `pod install` fail, with an error matching the original report.

**Comment by haifengkao** [comment]
As @timothyekl  said, the workdaround:
don't specify two targets in Podfile
or
always have default subspec in podspec

**Comment by fontesrp** [comment]
Also happens in 1.11.3:

Stack

```
   CocoaPods : 1.11.3
        Ruby : ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [arm64-darwin21]
    RubyGems : 3.1.6
        Host : macOS 12.3.1 (21E258)
       Xcode : 13.3.1 (13E500a)
         Git : git version 2.32.0 (Apple Git-132)
Ruby lib dir : /Users/rfontes/.rvm/rubies/ruby-2.7.4/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ f04ba2b7b1880cee9ea0d363714bf23e6da465c1

               goinstant-pods-specs-public - git - https://github.com/goinstant/pods-specs-public @ 776464525fb37f7aca4ae0dd24ccedd755872447

               react-native-tvos-react-native-tvos-podspecs - git - https://github.com/react-native-tvos/react-native-tvos-podspecs.git @ 1046282d7d21301f4be1aa7329c9d44f97098855

               trunk - CDN - https://cdn.cocoapods.org/
```

**Comment by fontesrp** [comment]
As the logs suggest, the problem originates in [this concatenation](https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/installer/analyzer/pod_variant_set.rb#L119). Simply wrapping it in a conditional statement that will run the concatenation only if `root_spec.default_subspecs != :none` should fix this behavior. A PR is merited in this case since the documentation [explicitly says](https://guides.cocoapods.org/syntax/podspec.html#default_subspecs) that `spec.default_subspecs = :none` is supported. CocoaPod's [requirements for PRs](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md#pull-requests) are troublesome, though.
