### ISSUE TITLE
cocospod install报错

### ISSUE THREAD

**Issue by DarkYuanJs** [CocoaPods/CocoaPods#10269]
xteam@MacBook-Pro Merge Fun % pod install --repo-update
Updating local specs repositories
  $ /usr/bin/git -C /Users/xteam/.cocoapods/repos/cocoapods fetch origin --progress

  remote: Enumerating objects: 61, done.        
  remote: Counting objects: 100% (61/61), done.        
  remote: Compressing objects: 100% (41/41), done.        
  remote: Total 45 (delta 28), reused 0 (delta 0), pack-reused 0        
  From https://github.com/CocoaPods/Specs
     f085914d8be4..a2585d157b28  master     -> origin/master
  $ /usr/bin/git -C /Users/xteam/.cocoapods/repos/cocoapods rev-parse --abbrev-ref HEAD
  master
  $ /usr/bin/git -C /Users/xteam/.cocoapods/repos/cocoapods reset --hard origin/master

  HEAD is now at a2585d157b28 [Add] Mateen 1.1.0
Analyzing dependencies
Downloading dependencies
Generating Pods project

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/xteam/.rvm/gems/ruby-2.6.5/bin/pod install --repo-update
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.10.0
        Ruby : ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin19]
    RubyGems : 3.0.8
        Host : Mac OS X 10.15.7 (19H15)
       Xcode : 12.2 (12B45b)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /Users/xteam/.rvm/rubies/ruby-2.6.5/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ a2585d157b286d12e031812670ffa2e720354540

```

### Plugins

```
cocoapods-clean       : 0.0.1
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'Unity-iPhone' do
  pod 'AppsFlyerFramework', '6.0.7'
  pod 'FBSDKCoreKit'
  pod 'FBSDKGamingServicesKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'FCUUID'
  pod 'Firebase/Analytics', '7.0.0'
  pod 'Firebase/Core', '7.0.0'
  pod 'Firebase/Crashlytics', '7.0.0'
  pod 'Firebase/Messaging', '7.0.0'
  pod 'MoPub-AdColony-Adapters', '4.4.1.1.3', :subspecs => ['Network']
  pod 'MoPub-AdMob-Adapters', '7.68.0.2', :subspecs => ['Network']
  pod 'MoPub-Applovin-Adapters', '6.14.9.0', :subspecs => ['Network']
  pod 'MoPub-FacebookAudienceNetwork-Adapters', '6.2.0.2', :subspecs => ['Network']
  pod 'mopub-ios-sdk', '5.15.0', :subspecs => ['Core']
  pod 'MoPub-IronSource-Adapters', '7.0.3.0.3', :subspecs => ['Network']
  pod 'MoPub-SDK-Plugin', :path => '/Users/xteam/Desktop/Merge2DS/trunk/Assets/MoPub/Plugins/iOS'
  pod 'MoPub-TapJoy-Adapters', '12.7.1.2', :subspecs => ['Network']
  pod 'MoPub-UnityAds-Adapters', '3.5.1.2', :subspecs => ['Network']
end
```

### Error

```
ArgumentError - Malformed version number string ["5.0", "5"]
/Users/xteam/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/version.rb:47:in `initialize'
/Users/xteam/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/vendor/version.rb:199:in `new'
/Users/xteam/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/vendor/version.rb:199:in `new'
/Users/xteam/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/target/build_settings.rb:1296:in `block in <class:AggregateTargetSettings>'
/Users/xteam/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/target/build_settings.rb:120:in `block in define_build_settings_method'
/Users/xteam/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/target/build_settings.rb:1227:in `block in <class:AggregateTargetSettings>'
/Users/xteam/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/target/build_settings.rb:120:in `block in define_build_settings_method'
/Users/xteam/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/target/build_settings.rb:387:in `public_send'
/Users/xteam/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/target/build_settings.rb:387:in `block in to_h'
/Users/xteam/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/target/build_settings.rb:386:in `each'
/Users/xteam/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/target/build_settings.rb:386:in `to_h'
/Users/xteam/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/target/build_settings.rb:188:in `block in <class:BuildSettings>'
/Users/xteam/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/target/build_settings.rb:1101:in `block in <class:AggregateTargetSettings>'
/Users/xteam/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/target/build_settings.rb:120:in `block in define_build_settings_method'
/Users/xteam/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/xcode/pods_project_generator/target_installer_helper.rb:16:in `update_changed_file'
/Users/xteam/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:113:in `block in create_xcconfig_file'
/Users/xteam/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:109:in `each'
/Users/xteam/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:109:in `create_xcconfig_file'
/Users/xteam/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:22:in `block in install!'
/Users/xteam/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/user_interface.rb:145:in `message'
/Users/xteam/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:18:in `install!'
/Users/xteam/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/xcode/pods_project_generator.rb:131:in `block (2 levels) in install_aggregate_targets'
/Users/xteam/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/xcode/pods_project_generator.rb:129:in `map'
/Users/xteam/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/xcode/pods_project_generator.rb:129:in `block in install_aggregate_targets'
/Users/xteam/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/user_interface.rb:145:in `message'
/Users/xteam/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/xcode/pods_project_generator.rb:128:in `install_aggregate_targets'
/Users/xteam/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/xcode/single_pods_project_generator.rb:20:in `generate!'
/Users/xteam/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:312:in `block in create_and_save_projects'
/Users/xteam/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/user_interface.rb:64:in `section'
/Users/xteam/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:307:in `create_and_save_projects'
/Users/xteam/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:299:in `generate_pods_project'
/Users/xteam/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:178:in `integrate'
/Users/xteam/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:166:in `install!'
/Users/xteam/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/command/install.rb:52:in `run'
/Users/xteam/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/xteam/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/command.rb:52:in `run'
/Users/xteam/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.0/bin/pod:55:in `<top (required)>'
/Users/xteam/.rvm/gems/ruby-2.6.5/bin/pod:23:in `load'
/Users/xteam/.rvm/gems/ruby-2.6.5/bin/pod:23:in `<main>'
/Users/xteam/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
/Users/xteam/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=Malformed+version+number+string+%5B%225.0%22%2C+%225%22%5D&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
 - ArgumentError - Malformed version number string ~> 4.0
   https://github.com/CocoaPods/CocoaPods/issues/9667 [closed] [2 comments]
   10 Jul 2020

 - - ERROR | [iOS] unknown: Encountered an unknown error (Malformed version number string ) during validation.
   https://github.com/CocoaPods/CocoaPods/issues/8240 [closed] [19 comments]
   24 May 2019

 -     - ERROR | [iOS] unknown: Encountered an unknown error (Malformed version number string ) during validation.
   https://github.com/CocoaPods/CocoaPods/issues/8128 [closed] [4 comments]
   01 Nov 2018

and 5 more at:
https://github.com/cocoapods/cocoapods/search?q=Malformed%20version%20number%20string%20%5B%225.0%22%2C%20%225%22%5D&type=Issues&utf8=✓

[!] A license was specified in podspec `MoPub-SDK-Plugin` but the file does not exist - /Users/xteam/Desktop/Merge2DS/trunk/Assets/MoPub/Plugins/iOS/LICENSE

**Comment by DarkYuanJs** [comment]
https://forum.unity.com/threads/solved-xcode-argumenterror-malformed-version-number-string-5-1-5-0.973134/


问题解决了！

**Comment by DarkYuanJs** [comment]
问题已解决
