### ISSUE TITLE
NoMethodError - undefined method `size' for nil:NilClass

### ISSUE THREAD

**Issue by rafagan** [CocoaPods/CocoaPods#10273]
### Command

```
/usr/local/var/rbenv/versions/2.7.1/bin/pod install
```

### Report

After running pod install in a flutter project, the following error occurs:
Any help?

### Stack

```
   CocoaPods : 1.10.0
        Ruby : ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]
    RubyGems : 3.1.2
        Host : macOS 11.0.1 (20B29)
       Xcode : 12.2 (12B45b)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /usr/local/var/rbenv/versions/2.7.1/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ 8a475c93f460fc2af68805c25e2e03e585b6c8b1

               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
platform :ios, '10.0'
workspace 'Runner.xcworkspace'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
```

### Error

```
NoMethodError - undefined method `size' for nil:NilClass
/usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/ruby-macho-1.4.0/lib/macho/macho_file.rb:455:in `populate_mach_header'
/usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/ruby-macho-1.4.0/lib/macho/macho_file.rb:233:in `populate_fields'
/usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/ruby-macho-1.4.0/lib/macho/macho_file.rb:55:in `initialize_from_bin'
/usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/ruby-macho-1.4.0/lib/macho/macho_file.rb:33:in `new_from_bin'
/usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/ruby-macho-1.4.0/lib/macho/fat_file.rb:365:in `block in populate_machos'
/usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/ruby-macho-1.4.0/lib/macho/fat_file.rb:364:in `each'
/usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/ruby-macho-1.4.0/lib/macho/fat_file.rb:364:in `populate_machos'
/usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/ruby-macho-1.4.0/lib/macho/fat_file.rb:156:in `populate_fields'
/usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/ruby-macho-1.4.0/lib/macho/fat_file.rb:95:in `initialize'
/usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/ruby-macho-1.4.0/lib/macho.rb:31:in `new'
/usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/ruby-macho-1.4.0/lib/macho.rb:31:in `open'
/usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/xcode/linkage_analyzer.rb:16:in `dynamic_binary?'
/usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/sandbox/file_accessor.rb:171:in `block in vendored_dynamic_frameworks'
/usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/sandbox/file_accessor.rb:170:in `select'
/usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/sandbox/file_accessor.rb:170:in `vendored_dynamic_frameworks'
/usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/sandbox/file_accessor.rb:179:in `vendored_static_frameworks'
/usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/sandbox/file_accessor.rb:292:in `vendored_static_artifacts'
/usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/xcode/target_validator.rb:82:in `each'
/usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/xcode/target_validator.rb:82:in `flat_map'
/usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/xcode/target_validator.rb:82:in `block (2 levels) in verify_no_static_framework_transitive_dependencies'
/usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/xcode/target_validator.rb:74:in `each_key'
/usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/xcode/target_validator.rb:74:in `block in verify_no_static_framework_transitive_dependencies'
/usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/xcode/target_validator.rb:73:in `each'
/usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/xcode/target_validator.rb:73:in `verify_no_static_framework_transitive_dependencies'
/usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/xcode/target_validator.rb:38:in `validate!'
/usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:595:in `validate_targets'
/usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:162:in `install!'
/usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/command/install.rb:52:in `run'
/usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/command.rb:52:in `run'
/usr/local/var/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/bin/pod:55:in `<top (required)>'
/usr/local/var/rbenv/versions/2.7.1/bin/pod:23:in `load'
/usr/local/var/rbenv/versions/2.7.1/bin/pod:23:in `<main>'
```

**Comment by dnkoutso** [comment]
Can you please upload a sample app?

**Comment by jey-song** [comment]
1. flutter clean 
2. pod install

**Comment by justin-iteratively** [comment]
Same problem. Not using flutter.
