### ISSUE TITLE
NoMethodError - undefined method `new_file' for #<Xcodeproj::Project::Object::PBXFileReference:0x00007f8508254628>

### ISSUE THREAD

**Issue by a365344743s** [CocoaPods/CocoaPods#10275]
# Report

## What did you do?

pod install

## What did you expect to happen?

Install all pod dependencies correctly.

## What happened instead?

error occurred.
NoMethodError - undefined method `new_file' for #<Xcodeproj::Project::Object::PBXFileReference:0x00007f8508254628>

### Stack

```
   CocoaPods : 1.10.0
        Ruby : ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin18]
    RubyGems : 3.1.2
        Host : Mac OS X 10.15.7 (19H2)
       Xcode : 12.2 (12B45b)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /usr/local/Cellar/ruby/2.7.0/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'VoiceSocial' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for VoiceSocial

    pod 'DataCenter', :path => "DataCenter"
end
```

### DataCenter.podspec
```ruby
Pod::Spec.new do |spec|

  spec.name         = "DataCenter"
  spec.version      = "0.0.2"
  spec.summary      = "A short description of DataCenter."

  spec.description  = <<-DESC
  "A short description of DataCenter."
                   DESC

  spec.homepage     = "http://www.baidu.com"
  
  spec.license      = "LICENSE"

  spec.author             = { "xx" => "xx@qq.com" }
  
  spec.platform     = :ios
  spec.platform     = :ios, "10.0"

  spec.source       = { :git => "http://xx/datacenter.git", :tag => "#{spec.version}" }

  spec.source_files  = "Classes/*.{h,m}"
  spec.exclude_files = "Classes/Exclude"
  
  spec.subspec 'Api' do |ss|
    ss.ios.deployment_target = '9.0'
    ss.source_files = "Classes/Api/**/*"
  end
  
  spec.subspec 'DB' do |ss|
    ss.ios.deployment_target = '9.0'
    ss.source_files = "Classes/DB/**/*"
  end
  
  spec.subspec 'Manager' do |ss|
    ss.ios.deployment_target = '9.0'
    ss.source_files = "Classes/Manager/**/*"
  end
  
  spec.subspec 'MQTT' do |ss|
    ss.ios.deployment_target = '9.0'
    ss.source_files = "Classes/MQTT/**/*"
  end
  
  spec.subspec 'Notify' do |ss|
    ss.ios.deployment_target = '9.0'
    ss.source_files = "Classes/Notify/**/*"
  end
  
  spec.subspec 'Proxy' do |ss|
    ss.ios.deployment_target = '9.0'
    ss.source_files = "Classes/Proxy/**/*"
  end
  
  spec.subspec 'Repository' do |ss|
    ss.ios.deployment_target = '9.0'
    ss.source_files = "Classes/Repository/**/*"
  end
  
  spec.subspec 'Util' do |ss|
    ss.ios.deployment_target = '9.0'
    ss.source_files = "Classes/Util/**/*"
  end
  
  spec.resources = ['Assets/WHDC.bundle','Frameworks/APBToygerFacade.framework/APBToygerFacade.bundle','Frameworks/ToygerService.framework/ToygerService.bundle','Frameworks/BioAuthEngine.framework/BioAuthEngine.bundle','Frameworks/OCRDetectSDKForTech.framework/OCRXMedia.bundle']
    
  spec.frameworks = 'CoreGraphics','Accelerate','SystemConfiguration','AssetsLibrary','CoreTelephony','QuartzCore','CoreFoundation','CoreLocation','ImageIO','CoreMedia','CoreMotion','AVFoundation','WebKit','AudioToolbox','CFNetwork','MobileCoreServices','AdSupport'
  
  spec.vendored_frameworks = 'Frameworks/AliyunIdentityManager.framework','Frameworks/AliyunOSSiOS.framework','Frameworks/APBToygerFacade.framework','Frameworks/APPSecuritySDK.framework','Frameworks/BioAuthAPI.framework','Frameworks/BioAuthEngine.framework','Frameworks/deviceiOS.framework','Frameworks/MPRemoteLogging.framework','Frameworks/OCRDetectSDKForTech.framework','Frameworks/ToygerService.framework','Frameworks/ZolozIdentityManager.framework','Frameworks/ZolozMobileRPC.framework','Frameworks/ZolozOpenPlatformBuild.framework','Frameworks/ZolozSensorServices.framework','Frameworks/ZolozUtility.framework'
  
  spec.libraries = 'z','c++','resolv','c++.1','c++abi','z.1.2.8'

end
```

### Error

```
NoMethodError - undefined method `new_file' for #<Xcodeproj::Project::Object::PBXFileReference:0x00007f8508254628>
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/project.rb:274:in `add_file_reference'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:224:in `block (2 levels) in add_file_accessors_paths_to_pods_group'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:223:in `each'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:223:in `block in add_file_accessors_paths_to_pods_group'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:213:in `each'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:213:in `add_file_accessors_paths_to_pods_group'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:129:in `block in add_resources'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/user_interface.rb:145:in `message'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:128:in `add_resources'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:49:in `install!'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/xcode/pods_project_generator.rb:102:in `block in install_file_references'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/user_interface.rb:145:in `message'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/xcode/pods_project_generator.rb:100:in `install_file_references'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/xcode/single_pods_project_generator.rb:17:in `generate!'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:312:in `block in create_and_save_projects'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:307:in `create_and_save_projects'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:299:in `generate_pods_project'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:178:in `integrate'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:166:in `install!'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/command/install.rb:52:in `run'
/usr/local/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by dnkoutso** [comment]
Can you upload a sample app? This is probably a bug and a sample app would help with a potential fix.

**Comment by a365344743s** [comment]
[demo.zip](https://github.com/CocoaPods/CocoaPods/files/5677406/demo.zip)

**Comment by a365344743s** [comment]
any advice?

**Comment by a365344743s** [comment]
@dnkoutso any advice?

**Comment by dnkoutso** [comment]
It might be a bug yes in `./Frameworks/APBToygerFacade.framework/APBToygerFacade.bundle`

Do not include that in your `s.resources` its part of the framework already and it would be copied in your app bundle.

**Comment by nhaus12** [comment]
For anyone encountering the same error in future:

I got a similar error running `pod install` after upgrading to React Native version 0.72.15.

In my case, the error message and top of the stack trace:

```bash
undefined method `new_file' for #<Xcodeproj::Project::Object::PBXFileReference:0x000000013fe9de88>

~/workspace/blns-repos/react-native-blns-sdk/example/node_modules/react-native/scripts/cocoapods/privacy_manifest_utils.rb:96:in `ensure_reference'
```

`new_file` is a method of the `Xcodeproj::Project` class (see [docs for `xcodeproj` gem](https://www.rubydoc.info/gems/xcodeproj/Xcodeproj/Project)), but the script is trying to call it on a [`PBXFileReference` object](https://www.rubydoc.info/gems/xcodeproj/Xcodeproj/Project/Object/PBXFileReference), which does not have that method (and is clearly not the intended object on which such a method should be called).

In my case, the `privacy_manifest_utils.rb` script had a function with the lines:
```ruby
	file_root = user_project.root_object.main_group.children.first { |group| group.name == target.name } || user_project
	file_ref = file_root.new_file(file_path)
```

However, the first of the `children` in the `user_project.root_object.main_group` was an *ordinary file*, not the relevant *project*. I could delete this file from the project (NB: via the Xcode interface – it was not sufficient to delete the file from the repo as the reference must be removed from the project) as it was redundant. In other cases, I'm not sure whether it is possible to re-order the files/references in the Xcode project. 

Obviously anyone else struggling with something similar would need to look at the specific implementation of the script/function that is making the failing method call.

**Comment by TimMun** [comment]
I had a similar error to the previous comment. In my case, Xcode had generated a new file (`PrivacyInfo.xcprivacy`) but did not add the reference to the project file. Manually adding the file to the project via Xcode worked for me - afterwards `pod install` worked fine. 

From the below link, Apple says "You need to add the privacy manifest file to your target’s resources for Xcode to use it when you generate a privacy report."

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files

**Comment by zjkuang** [comment]
I had exactly the same error and I found a solution by
(From Xcode,)
(1) Deleting the reference to PrivacyInfo.xcprivacy (only delete the reference, do not remove to trash)
(2) Adding back the reference to PrivacyInfo.xcprivacy (drag PrivacyInfo.xcprivacy from Finder and drop it into Xcode, and choose "Create folder references")

**Comment by shyrynaz** [comment]
> I had exactly the same error and I found a solution by (From Xcode,) (1) Deleting the reference to PrivacyInfo.xcprivacy (only delete the reference, do not remove to trash) (2) Adding back the reference to PrivacyInfo.xcprivacy (drag PrivacyInfo.xcprivacy from Finder and drop it into Xcode, and choose "Create folder references")

For just adding the reference(point 2) worked. thanks @zjkuang

**Comment by omarsdev** [comment]
> I had exactly the same error and I found a solution by (From Xcode,) (1) Deleting the reference to PrivacyInfo.xcprivacy (only delete the reference, do not remove to trash) (2) Adding back the reference to PrivacyInfo.xcprivacy (drag PrivacyInfo.xcprivacy from Finder and drop it into Xcode, and choose "Create folder references")

That's worked from me, thanks @zjkuang

**Comment by IgorPRibeiro** [comment]
> I had exactly the same error and I found a solution by (From Xcode,) (1) Deleting the reference to PrivacyInfo.xcprivacy (only delete the reference, do not remove to trash) (2) Adding back the reference to PrivacyInfo.xcprivacy (drag PrivacyInfo.xcprivacy from Finder and drop it into Xcode, and choose "Create folder references")

That's worked for me, thanks @zjkuang. I just move the file to project folder in xcode.
