### ISSUE TITLE
Unable to run pod list

### ISSUE THREAD

**Issue by omatrot** [CocoaPods/CocoaPods#10297]
### Command

```
/usr/local/bin/pod list
```

### Report

* What did you do?

ran a simple `pod list`command.

* What did you expect to happen?

No error.

* What happened instead?

An error.

### Stack

```
   CocoaPods : 1.10.0
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
    RubyGems : 3.0.3
        Host : macOS 11.2 (20D5029f)
       Xcode : 12.3 (12C33)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Error

```
NoMethodError - undefined method `version' for nil:NilClass
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/user_interface.rb:214:in `pod'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/command/list.rb:24:in `block in run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/command/list.rb:24:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/command/list.rb:24:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by dnkoutso** [comment]
hmmm that looks weird indeed. Not sure what is going on exactly. Could appreciate some more debugging...

can you open `/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/user_interface.rb` and maybe add a `puts set` above line 214 perhaps?

Thanks!

**Comment by omatrot** [comment]
Sure, what do you want next ? The output of `pod list` ?

**Comment by dnkoutso** [comment]
Once you add this line save the file and re-run and then print out the additional debug statement that came out and hopefully will give us a clue.

**Comment by dnkoutso** [comment]
Ah looks like `ALOKeyboardAware` no longer exists which causes the issue I think.

This one throws a 404 https://cocoapods.org/pods/ALOKeyboardAware, perhaps because the pod was deleted. We could handle that better I think.

**Comment by omatrot** [comment]
That would be nice.
