### ISSUE TITLE
undefined method `map' for nil:NilClass

### ISSUE THREAD

**Issue by QionglinFu1024** [CocoaPods/CocoaPods#10301]
Hi Team,
When i try to install pods in my project i'm getting the following error.
I have tried deintegrate and install again, but it was not working.
even after updating/reinstalling the cocoapods also not working.
can you please help me to fix this one.

Thanks,

`pod search AFNetworking

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/bear/.rvm/rubies/ruby-2.7.2/bin/pod search AFNetworking
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.10.0
        Ruby : ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [arm64-darwin20]
    RubyGems : 3.2.3
        Host : macOS 11.1 (20C69)
       Xcode : 12.3 (12C33)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /Users/bear/.rvm/rubies/ruby-2.7.2/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Error

```
LoadError - dlopen(/Users/bear/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/ffi-1.14.2/lib/ffi_c.bundle, 9): no suitable image found.  Did find:
	/Users/bear/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/ffi-1.14.2/lib/ffi_c.bundle: mach-o, but wrong architecture
	/Users/bear/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/ffi-1.14.2/lib/ffi_c.bundle: mach-o, but wrong architecture - /Users/bear/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/ffi-1.14.2/lib/ffi_c.bundle
/Users/bear/.rvm/rubies/ruby-2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
/Users/bear/.rvm/rubies/ruby-2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
/Users/bear/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/ffi-1.14.2/lib/ffi.rb:6:in `rescue in <top (required)>'
/Users/bear/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/ffi-1.14.2/lib/ffi.rb:3:in `<top (required)>'
/Users/bear/.rvm/rubies/ruby-2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
/Users/bear/.rvm/rubies/ruby-2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
/Users/bear/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/ethon-0.12.0/lib/ethon.rb:2:in `<top (required)>'
/Users/bear/.rvm/rubies/ruby-2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
/Users/bear/.rvm/rubies/ruby-2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
/Users/bear/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
/Users/bear/.rvm/rubies/ruby-2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
/Users/bear/.rvm/rubies/ruby-2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
/Users/bear/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/cdn_source.rb:440:in `download_typhoeus_impl_async'
/Users/bear/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/cdn_source.rb:372:in `download_and_save_with_retries_async'
/Users/bear/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/cdn_source.rb:365:in `download_file_async'
/Users/bear/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/cdn_source.rb:338:in `download_file'
/Users/bear/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/cdn_source.rb:284:in `ensure_versions_file_loaded'
/Users/bear/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/cdn_source.rb:112:in `versions'
/Users/bear/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/specification/set.rb:99:in `block in versions_by_source'
/Users/bear/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/specification/set.rb:98:in `each'
/Users/bear/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/specification/set.rb:98:in `each_with_object'
/Users/bear/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/specification/set.rb:98:in `versions_by_source'
/Users/bear/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/specification/set.rb:75:in `versions'
/Users/bear/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/cdn_source.rb:237:in `block in search_by_name'
/Users/bear/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/cdn_source.rb:237:in `reject'
/Users/bear/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/cdn_source.rb:237:in `search_by_name'
/Users/bear/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/source/manager.rb:133:in `block in search_by_name'
/Users/bear/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/source/manager.rb:133:in `map'
/Users/bear/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/source/manager.rb:133:in `search_by_name'
/Users/bear/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-search-1.0.0/lib/cocoapods-search/command/search.rb:87:in `local_search'
/Users/bear/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-search-1.0.0/lib/cocoapods-search/command/search.rb:63:in `run'
/Users/bear/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/bear/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/command.rb:52:in `run'
/Users/bear/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/bin/pod:55:in `<top (required)>'
/Users/bear/.rvm/rubies/ruby-2.7.2/bin/pod:23:in `load'
/Users/bear/.rvm/rubies/ruby-2.7.2/bin/pod:23:in `<main>'
/Users/bear/.rvm/rubies/ruby-2.7.2/bin/ruby_executable_hooks:24:in `eval'
/Users/bear/.rvm/rubies/ruby-2.7.2/bin/ruby_executable_hooks:24:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=dlopen%28%2FUsers%2Fbear%2F.rvm%2Frubies%2Fruby-2.7.2%2Flib%2Fruby%2Fgems%2F2.7.0%2Fgems%2Fffi-1.14.2%2Flib%2Fffi_c.bundle%2C+9%29%3A+no+suitable+image+found.++Did+find%3A%0A%09%2FUsers%2Fbear%2F.rvm%2Frubies%2Fruby-2.7.2%2Flib%2Fruby%2Fgems%2F2.7.0%2Fgems%2Fffi-1.14.2%2Flib%2Fffi_c.bundle%3A+mach-o%2C+but+wrong+architecture%0A%09%2FUsers%2Fbear%2F.rvm%2Frubies%2Fruby-2.7.2%2Flib%2Fruby%2Fgems%2F2.7.0%2Fgems%2Fffi-1.14.2%2Flib%2Fffi_c.bundle%3A+mach-o%2C+but+wrong+architecture+-+%2FUsers%2Fbear%2F.rvm%2Frubies%2Fruby-2.7.2%2Flib%2Fruby%2Fgems%2F2.7.0%2Fgems%2Fffi-1.14.2%2Flib%2Fffi_c.bundle&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Searching for inspections failed: undefined method `map' for nil:NilClass
`

macOS Big Sur
v11.1
2020 M1

**Comment by dnkoutso** [comment]
This seems the same issue with installing `ffi` gem. Please see this issue https://github.com/CocoaPods/CocoaPods/issues/9907
