### ISSUE TITLE
Cannot install any pods (LoadError: no suitable image found)

### ISSUE THREAD

**Issue by jcush** [CocoaPods/CocoaPods#10307]
Hi,

I've been trying to find a solution to this for just... too long. Anyway, every time I try to run `pod install --repo-update` (I need the flag, as the regular `pod install` command just tells me to run that) in my project the error below occurs.

I saw a similar issue raised here and the author was told to go see FFI about it. While I do genuinely get why you'd say that, having talked to the author of that gem he says it's not something he thinks is related to the gem specifically and is more about the overall loading/signing process.

I have included the requested markdown template generated by `pod install --repo-update` below - any and all help will be appreciated as I have zero familiarity with CocoaPods, FFI or Ruby before any of this kicked off.

Thanks

James 

**Edit:** FYI, the issue I've been discussing with the author of FFI is [#836](https://github.com/ffi/ffi/issues/836) and there are a couple things we addressed there which *didn't* turn out to be the problem, such as mismatched Ruby versions etc.

**Edit 2:** I've spotted a couple issues dotted around the web of others having this issue and it would seem that it's not just an issue with FFI. For example, dart also seems to have [users reporting it](https://github.com/dart-lang/sdk/issues/38314)

# Markdown Template
### Command

```
pod install --repo-update
```

### Report

* What did you do?
Ran `pod install --repo-update`

* What did you expect to happen?
Successful build

* What happened instead?
Error thrown (see 'Error' below)

### Stack

```
   CocoaPods : 1.10.0
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [x86_64-darwin14]
    RubyGems : 2.5.2.3
        Host : macOS 11.1 (20C69)
       Xcode : 12.3 (12C33)
         Git : git version 2.26.2
Ruby lib dir : /Applications/MAMP/Library/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
platform :ios, '10.0'

require_relative '../node_modules/react-native-unimodules/cocoapods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'PodTest' do
  rnPrefix = "../node_modules/react-native"

  # React Native and its dependencies
  pod 'FBLazyVector', :path => "#{rnPrefix}/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "#{rnPrefix}/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "#{rnPrefix}/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "#{rnPrefix}/Libraries/TypeSafety"
  pod 'React', :path => "#{rnPrefix}/"
  pod 'React-Core', :path => "#{rnPrefix}/"
  pod 'React-CoreModules', :path => "#{rnPrefix}/React/CoreModules"
  pod 'React-RCTActionSheet', :path => "#{rnPrefix}/Libraries/ActionSheetIOS"
  pod 'React-RCTAnimation', :path => "#{rnPrefix}/Libraries/NativeAnimation"
  pod 'React-RCTBlob', :path => "#{rnPrefix}/Libraries/Blob"
  pod 'React-RCTImage', :path => "#{rnPrefix}/Libraries/Image"
  pod 'React-RCTLinking', :path => "#{rnPrefix}/Libraries/LinkingIOS"
  pod 'React-RCTNetwork', :path => "#{rnPrefix}/Libraries/Network"
  pod 'React-RCTSettings', :path => "#{rnPrefix}/Libraries/Settings"
  pod 'React-RCTText', :path => "#{rnPrefix}/Libraries/Text"
  pod 'React-RCTVibration', :path => "#{rnPrefix}/Libraries/Vibration"
  pod 'React-Core/RCTWebSocket', :path => "#{rnPrefix}/"
  pod 'React-Core/DevSupport', :path => "#{rnPrefix}/"
  pod 'React-cxxreact', :path => "#{rnPrefix}/ReactCommon/cxxreact"
  pod 'React-jsi', :path => "#{rnPrefix}/ReactCommon/jsi"
  pod 'React-jsiexecutor', :path => "#{rnPrefix}/ReactCommon/jsiexecutor"
  pod 'React-jsinspector', :path => "#{rnPrefix}/ReactCommon/jsinspector"
  pod 'ReactCommon/callinvoker', :path => "#{rnPrefix}/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "#{rnPrefix}/ReactCommon"
  pod 'Yoga', :path => "#{rnPrefix}/ReactCommon/yoga"
  pod 'DoubleConversion', :podspec => "#{rnPrefix}/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "#{rnPrefix}/third-party-podspecs/glog.podspec"
  pod 'Folly', :podspec => "#{rnPrefix}/third-party-podspecs/Folly.podspec"

  # Other native modules

  # Automatically detect installed unimodules
  use_unimodules!

  # react-native-cli autolinking
  use_native_modules!
end
```

### Error

```
LoadError - dlopen(/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/ffi-1.13.1/lib/ffi_c.bundle, 9): no suitable image found.  Did find:
	/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/ffi-1.13.1/lib/ffi_c.bundle: code signature in (/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/ffi-1.13.1/lib/ffi_c.bundle) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed. - /Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/ffi-1.13.1/lib/ffi_c.bundle
/Applications/MAMP/Library/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Applications/MAMP/Library/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/ffi-1.13.1/lib/ffi.rb:6:in `rescue in <top (required)>'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/ffi-1.13.1/lib/ffi.rb:3:in `<top (required)>'
/Applications/MAMP/Library/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Applications/MAMP/Library/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/ethon-0.12.0/lib/ethon.rb:2:in `<top (required)>'
/Applications/MAMP/Library/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Applications/MAMP/Library/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
/Applications/MAMP/Library/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Applications/MAMP/Library/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/cdn_source.rb:440:in `download_typhoeus_impl_async'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/cdn_source.rb:372:in `download_and_save_with_retries_async'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/cdn_source.rb:365:in `download_file_async'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/cdn_source.rb:338:in `download_file'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/cdn_source.rb:78:in `deprecated_local_podspecs'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/cdn_source.rb:60:in `preheat_existing_files'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/cdn_source.rb:257:in `update'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-1.10.0/lib/cocoapods/sources_manager.rb:135:in `block (3 levels) in update'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-1.10.0/lib/cocoapods/user_interface.rb:64:in `section'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-1.10.0/lib/cocoapods/sources_manager.rb:134:in `block (2 levels) in update'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-1.10.0/lib/cocoapods/sources_manager.rb:133:in `each'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-1.10.0/lib/cocoapods/sources_manager.rb:133:in `block in update'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-1.10.0/lib/cocoapods/sources_manager.rb:131:in `open'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-1.10.0/lib/cocoapods/sources_manager.rb:131:in `update'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:145:in `block in update_repositories'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:143:in `each'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:143:in `update_repositories'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:235:in `block in resolve_dependencies'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-1.10.0/lib/cocoapods/user_interface.rb:64:in `section'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:234:in `resolve_dependencies'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:160:in `install!'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-1.10.0/lib/cocoapods/command/install.rb:52:in `run'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-1.10.0/lib/cocoapods/command.rb:52:in `run'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-1.10.0/bin/pod:55:in `<top (required)>'
/Applications/MAMP/Library/bin/pod:22:in `load'
/Applications/MAMP/Library/bin/pod:22:in `<main>'

**Comment by dnkoutso** [comment]
please see https://github.com/CocoaPods/CocoaPods/issues/9907 and many other ffi reports. in this repo for workaround and solutions.

**Comment by jcush** [comment]
Hi @dnkoutso ,

FFI mentioned there is [libffi/libffi](https://github.com/libffi/libffi) but the ffi gem this issue is to do with is [ffi/ffi](https://github.com/ffi/ffi) - are these two the same?

Also my Mac is not a silicon-based Mac, but the solutions there seem to be to do with silicon-based Macs.

Thanks

**Comment by ab-ood44** [comment]
@

**Comment by lon9man** [comment]
Hi @jcush 
we are experiencing the same problem: https://github.com/CocoaPods/CocoaPods/issues/10519
symptoms are very similar to yours.

what is your current progress? 
did you find some useful since last atempts?

thanks!

**Comment by lon9man** [comment]
@jcush did you resolve own ffi's trouble?

**Comment by Xezolpl** [comment]
If anyone is still facing that issue please look up at that: https://stackoverflow.com/a/65334677 - worked for me ;)

**Comment by mivewi** [comment]
@jcush I'm facing the same issue. Can you share the solution with this email you are mentioning please?

**Comment by lon9man** [comment]
@mivewi jcush spoke about our mailing, which was related to solution, which helps to me. 
I described it here: https://github.com/ffi/ffi/issues/836#issuecomment-838122448
