### ISSUE TITLE
ArgumentError - Malformed version number string 5.0 5

### ISSUE THREAD

**Issue by agrobost** [CocoaPods/CocoaPods#10331]
# Report

## What did you do?

I do pod install on macOS Big Sur Version 11.1  

There is my result:  
```
alex@MacBook-Pro-de-alex Builds % pod install
Analyzing dependencies
Downloading dependencies
Installing AppLovinSDK (6.14.9)
Installing FBAudienceNetwork (6.2.0)
Installing FBSDKCoreKit (8.2.0)
Installing FBSDKGamingServicesKit (8.2.0)
Installing FBSDKLoginKit (8.2.0)
Installing FBSDKShareKit (8.2.0)
Installing Firebase (7.0.0)
Installing FirebaseABTesting (7.3.0)
Installing FirebaseAnalytics (7.0.0)
Installing FirebaseCore (7.0.0)
Installing FirebaseCoreDiagnostics (7.3.0)
Installing FirebaseCrashlytics (7.0.0)
Installing FirebaseInstallations (7.3.0)
Installing FirebaseInstanceID (7.3.0)
Installing FirebaseMessaging (7.0.0)
Installing FirebaseRemoteConfig (7.0.0)
Installing Google-Mobile-Ads-SDK (7.69.0)
Installing GoogleAppMeasurement (7.0.0)
Installing GoogleDataTransport (8.1.0)
Installing GoogleUserMessagingPlatform (1.4.0)
Installing GoogleUtilities (7.1.1)
Installing MoPub-AdMob-Adapters (7.69.0.1)
Installing MoPub-Applovin-Adapters (6.14.9.0)
Installing MoPub-FacebookAudienceNetwork-Adapters (6.2.0.2)
Installing MoPub-SDK-Plugin (5.15.0)
Installing MoPub-UnityAds-Adapters (3.6.0.0)
Installing PromisesObjC (1.2.12)
Installing UnityAds (3.6.0)
Installing mopub-ios-sdk (5.15.0)
Installing nanopb (2.30906.0)
Generating Pods project

error: ArgumentError - Malformed version number string 5.0 5  
```

## What did you expect to happen?

Success  

## What happened instead?

ArgumentError - Malformed version number string 5.0 5
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/version.rb:47:in `initialize'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/vendor/version.rb:199:in `new'
...

## CocoaPods Environment

```
   CocoaPods : 1.10.0
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
    RubyGems : 3.0.3
        Host : macOS 11.1 (20C69)
       Xcode : 12.3 (12C33)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ 10f3371a00efda7ce5e1c341125e72dffd2ce3c4

               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'

target 'UnityFramework' do
  pod 'FBSDKCoreKit', '~> 8.0'
  pod 'FBSDKGamingServicesKit', '~> 8.0'
  pod 'FBSDKLoginKit', '~> 8.0'
  pod 'FBSDKShareKit', '~> 8.0'
  pod 'Firebase/Analytics', '7.0.0'
  pod 'Firebase/Core', '7.0.0'
  pod 'Firebase/Crashlytics', '7.0.0'
  pod 'Firebase/Messaging', '7.0.0'
  pod 'Firebase/RemoteConfig', '7.0.0'
  pod 'MoPub-AdMob-Adapters', '7.69.0.1', :subspecs => ['Network']
  pod 'MoPub-Applovin-Adapters', '6.14.9.0', :subspecs => ['Network']
  pod 'MoPub-FacebookAudienceNetwork-Adapters', '6.2.0.2', :subspecs => ['Network']
  pod 'mopub-ios-sdk', '5.15.0', :subspecs => ['Core']
  pod 'MoPub-SDK-Plugin', :path => '/Users/alex/Documents/Unity/Sudoku/Assets/MoPub/Plugins/iOS'
  pod 'MoPub-UnityAds-Adapters', '3.6.0.0', :subspecs => ['Network']
end
target 'Unity-iPhone' do
end
use_frameworks!
```

**Comment by dnkoutso** [comment]
What does the podspec inside `/Users/alex/Documents/Unity/Sudoku/Assets/MoPub/Plugins/iOS` look like?

**Comment by agrobost** [comment]
Here it's:
```
Pod::Spec.new do |s|
  s.name                  = 'MoPub-SDK-Plugin'
  s.version               = '5.15.0'
  s.summary               = 'Unity wrapper for MoPub iOS SDK'
  s.homepage              = 'https://github.com/mopub/mopub-unity-sdk'
  s.license               = { :type => 'MoPub', :file => 'LICENSE' }
  s.author                = { 'MoPub' => 'support@mopub.com' }
  s.ios.deployment_target = '9.0'
  s.source                = { :git => 'https://github.com/mopub/mopub-unity-sdk.git', :tag => "v#{s.version}" }
  s.source_files          = '*.{h,m,mm,swift}'
  s.swift_version         = '5.0'
end

```

**Comment by dnkoutso** [comment]
You might have to `gem which cocoapods` and edit the sources and put some `puts` statements to debug from which podspec this failure is coming from.

I tried all of these podspecs that i was able to and it worked for me.

**Comment by agrobost** [comment]
When I change SWIFT_VERSION from 5.0 5 to 5.0 in xCode that works

**Comment by dnkoutso** [comment]
Why is your SWIFT_VERSION set to `5.0 5` and not` 5.0.5`? Does this even Swift version exist?

**Comment by agrobost** [comment]
I don't know.. My project is generated by Unity
When I start a build on xCode I have this error: MoPub.h file not found

**Comment by dnkoutso** [comment]
I recommend following up with Unity as so far this does not appear to be a CocoaPods issue.

It is possible though we can improve the error message to make this easier for us to diagnose the next time it happens. For now I am going to close.

**Comment by andymads** [comment]
> Why is your SWIFT_VERSION set to `5.0 5` and not `5.0`? Does the Swift version `5.0.5` even exist?

It's not 5.0.5, it's 5.0 5

This is likely happening because two different SWIFT_VERSION build properties are being added, "5.0" and "5". I am seeing the same thing and I replicated by adding the two different SWIFT_VERSION build properties.
