### ISSUE TITLE
invalid byte sequence in US-ASCII

### ISSUE THREAD

**Issue by judges** [CocoaPods/CocoaPods#1036]
### Report
- What did you do?
  Install Pods.
- What did you expect to happen?
  :-)
- What happened instead?
  :-(
### Stack

```
   CocoaPods : 0.19.1
        Ruby : ruby 1.9.2p320 (2012-04-20 revision 35421) [x86_64-darwin12.3.0]
    RubyGems : 2.0.3
        Host : Mac OS X 10.8.3 (12D78)
       Xcode : 4.6.2 (4H1003)
Ruby lib dir : /Users/drongous/.rvm/rubies/ruby-1.9.2-p320/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 1939cd432d24f4398bf571bc589e6b877b0feb1c
```
### Podfile

``` ruby
platform :ios, '6.0'
pod 'DejalActivityView',            '~> 1.0'
pod 'UAModalPanel',                 '~> 1.1.1'
pod 'GHSidebarNav',                 '~> 1.0.0'
pod 'IBAForms',                     '~> 1.1.0'
pod 'MagicalRecord',                '~> 2.1'
pod 'XCDFormInputAccessoryView',    '~> 1.0.0'
pod 'ActionSheetPicker2',           '~> 0.1'
pod 'ODRefreshControl',             '~> 1.1.0'
pod 'REComposeViewController',      '~> 2.0.3'
pod 'ABCalendarPicker',             '~> 1.0.0'
pod 'NSDate-TKExtensions',          '~>0.3'
pod 'AJNotificationView',           '~> 0.5'
pod 'Survey',                       '~> 0.1.0'
pod 'AFNetworking',                 '~>1.2.1'
pod 'gtm-oauth2',                   '~>0.0.1'
pod 'JSONKit',                      '~> 1.5pre'
pod 'Reachability',                 '~> 3.1.0'
pod 'GCNetworkReachability',        '~>1.3.0'
pod 'CocoaLumberjack',              '~>1.6'
pod 'TestFlightSDK',                '~>1.3.0.beta4'
pod 'TestFlightLogger'
```
### Error

```
ArgumentError - invalid byte sequence in US-ASCII
/Users/drongous/.rvm/rubies/ruby-1.9.2-p320/lib/ruby/1.9.1/pathname.rb:953:in `glob'
/Users/drongous/.rvm/rubies/ruby-1.9.2-p320/lib/ruby/1.9.1/pathname.rb:953:in `glob'
/Users/drongous/.rvm/gems/ruby-1.9.2-p320/gems/cocoapods-0.19.1/lib/cocoapods/installer/pod_source_installer.rb:252:in `clean_paths'
/Users/drongous/.rvm/gems/ruby-1.9.2-p320/gems/cocoapods-0.19.1/lib/cocoapods/installer/pod_source_installer.rb:144:in `clean_installation'
/Users/drongous/.rvm/gems/ruby-1.9.2-p320/gems/cocoapods-0.19.1/lib/cocoapods/installer/pod_source_installer.rb:88:in `clean!'
/Users/drongous/.rvm/gems/ruby-1.9.2-p320/gems/cocoapods-0.19.1/lib/cocoapods/installer.rb:272:in `block in clean_pod_sources'
/Users/drongous/.rvm/gems/ruby-1.9.2-p320/gems/cocoapods-0.19.1/lib/cocoapods/installer.rb:271:in `each'
/Users/drongous/.rvm/gems/ruby-1.9.2-p320/gems/cocoapods-0.19.1/lib/cocoapods/installer.rb:271:in `clean_pod_sources'
/Users/drongous/.rvm/gems/ruby-1.9.2-p320/gems/cocoapods-0.19.1/lib/cocoapods/installer.rb:103:in `block in download_dependencies'
/Users/drongous/.rvm/gems/ruby-1.9.2-p320/gems/cocoapods-0.19.1/lib/cocoapods/user_interface.rb:52:in `section'
/Users/drongous/.rvm/gems/ruby-1.9.2-p320/gems/cocoapods-0.19.1/lib/cocoapods/installer.rb:99:in `download_dependencies'
/Users/drongous/.rvm/gems/ruby-1.9.2-p320/gems/cocoapods-0.19.1/lib/cocoapods/installer.rb:85:in `install!'
/Users/drongous/.rvm/gems/ruby-1.9.2-p320/gems/cocoapods-0.19.1/lib/cocoapods/command/project.rb:40:in `run_install_with_update'
/Users/drongous/.rvm/gems/ruby-1.9.2-p320/gems/cocoapods-0.19.1/lib/cocoapods/command/project.rb:70:in `run'
/Users/drongous/.rvm/gems/ruby-1.9.2-p320/gems/claide-0.2.0/lib/claide.rb:535:in `run'
/Users/drongous/.rvm/gems/ruby-1.9.2-p320/gems/cocoapods-0.19.1/lib/cocoapods/command.rb:48:in `run'
/Users/drongous/.rvm/gems/ruby-1.9.2-p320/gems/cocoapods-0.19.1/bin/pod:16:in `<top (required)>'
/Users/drongous/.rvm/gems/ruby-1.9.2-p320/bin/pod:23:in `load'
/Users/drongous/.rvm/gems/ruby-1.9.2-p320/bin/pod:23:in `<main>'
```

**Comment by akhildave** [comment]
@alexrothenberg  your solution worked for me. I added it to ~/.bash_profile at the end. My ruby version is 2.2.2. Thanks

**Comment by alexrothenberg** [comment]
I think you meant to thank @alexeyshurygin :)

**Comment by alexeyshurygin** [comment]
@akhildave You're welcome)

**Comment by sharma1413** [comment]
Changing terminal settings to below solved my issue. Do restart the terminal
![screen shot 2017-06-08 at 6 46 56 pm](https://user-images.githubusercontent.com/25035656/26930534-57e22202-4c7b-11e7-90c3-e602487f1a7f.png)

**Comment by mshere9** [comment]
if [[ -z "$LC_ALL" ]]; then
  export LC_ALL='en_US.UTF-8'
fi

then check for locate, output should be : 
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"

then run flutter run

**Comment by aembleton** [comment]
In fish shell run `set -Ux LC_ALL en_US.UTF-8`
