### ISSUE TITLE
pod install failing on m1 / arm64 with ffi

### ISSUE THREAD

**Issue by SimonHausdorf** [CocoaPods/CocoaPods#10383]
### Command

```
/Users/sim/.rbenv/versions/3.0.0/bin/pod install
```

### Report

* What did you do?
I am trying to setup a flutter project. This is failing when `pod install` is called. ffi was installed with this command: `arch -x86_64 gem install ffi`

* What did you expect to happen?
No error

* What happened instead?
An error was thrown regarding wrong architecture

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [arm64-darwin20]
    RubyGems : 3.2.3
        Host : macOS 11.1 (20C69)
       Xcode : 12.4 (12D4e)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /Users/sim/.rbenv/versions/3.0.0/lib
Repositories : 
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
```

### Error

```
LoadError - dlopen(/Users/sim/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/ffi-1.14.2/lib/ffi_c.bundle, 9): no suitable image found.  Did find:
	/Users/sim/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/ffi-1.14.2/lib/ffi_c.bundle: mach-o, but wrong architecture
	/Users/sim/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/ffi-1.14.2/lib/ffi_c.bundle: mach-o, but wrong architecture - /Users/sim/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/ffi-1.14.2/lib/ffi_c.bundle
<internal:/Users/sim/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/Users/sim/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/Users/sim/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/ffi-1.14.2/lib/ffi.rb:6:in `rescue in <top (required)>'
/Users/sim/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/ffi-1.14.2/lib/ffi.rb:3:in `<top (required)>'
<internal:/Users/sim/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/Users/sim/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/Users/sim/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/ethon-0.12.0/lib/ethon.rb:2:in `<top (required)>'
<internal:/Users/sim/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/Users/sim/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/Users/sim/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
<internal:/Users/sim/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/Users/sim/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/Users/sim/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:74:in `cdn_url?'
/Users/sim/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:36:in `create_source_with_url'
/Users/sim/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:21:in `find_or_create_source_with_url'
/Users/sim/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:178:in `block in sources'
/Users/sim/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:177:in `map'
/Users/sim/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:177:in `sources'
/Users/sim/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:1073:in `block in resolve_dependencies'
/Users/sim/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/sim/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:1072:in `resolve_dependencies'
/Users/sim/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/Users/sim/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:414:in `analyze'
/Users/sim/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:239:in `block in resolve_dependencies'
/Users/sim/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/sim/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:238:in `resolve_dependencies'
/Users/sim/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:160:in `install!'
/Users/sim/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/command/install.rb:52:in `run'
/Users/sim/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/sim/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/Users/sim/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/Users/sim/.rbenv/versions/3.0.0/bin/pod:23:in `load'
/Users/sim/.rbenv/versions/3.0.0/bin/pod:23:in `<main>'
```

**Comment by SimonHausdorf** [comment]
Closed because of #9907
