### ISSUE TITLE
LoadError - cannot load such file -- rexml/document

### ISSUE THREAD

**Issue by qiqine** [CocoaPods/CocoaPods#10388]
### Command

```
/Users/xxx/.rvm/gems/ruby-2.7.0/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin19]
    RubyGems : 3.2.3
        Host : Mac OS X 10.15.7 (19H114)
       Xcode : 11.5 (11E608c)
         Git : git version 2.14.2
Ruby lib dir : /usr/local/Cellar/ruby/3.0.0_1/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'cloudeMusicRN' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'cloudeMusicRNTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'cloudeMusicRN-tvOS' do
  # Pods for cloudeMusicRN-tvOS

  target 'cloudeMusicRN-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
```

### Error

```
LoadError - cannot load such file -- rexml/document
<internal:/usr/local/Cellar/ruby/3.0.0_1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/usr/local/Cellar/ruby/3.0.0_1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/Users/xxx/.rvm/gems/ruby-2.7.0/gems/xcodeproj-1.19.0/lib/xcodeproj/scheme.rb:1:in `<top (required)>'
<internal:/usr/local/Cellar/ruby/3.0.0_1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/usr/local/Cellar/ruby/3.0.0_1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/Users/xxx/.rvm/gems/ruby-2.7.0/gems/xcodeproj-1.19.0/lib/xcodeproj/project.rb:840:in `recreate_user_schemes'
/Users/xxx/.rvm/gems/ruby-2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/xcode/pods_project_generator/pods_project_writer.rb:50:in `block in write!'
/Users/xxx/.rvm/gems/ruby-2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/xcode/pods_project_generator/pods_project_writer.rb:45:in `each'
/Users/xxx/.rvm/gems/ruby-2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/xcode/pods_project_generator/pods_project_writer.rb:45:in `write!'
/Users/xxx/.rvm/gems/ruby-2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:328:in `block in create_and_save_projects'
/Users/xxx/.rvm/gems/ruby-2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/xxx/.rvm/gems/ruby-2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:307:in `create_and_save_projects'
/Users/xxx/.rvm/gems/ruby-2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:299:in `generate_pods_project'
/Users/xxx/.rvm/gems/ruby-2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:178:in `integrate'
/Users/xxx/.rvm/gems/ruby-2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:166:in `install!'
/Users/xxx/.rvm/gems/ruby-2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/command/install.rb:52:in `run'
/Users/xxx/.rvm/gems/ruby-2.7.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/xxx/.rvm/gems/ruby-2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/Users/xxx/.rvm/gems/ruby-2.7.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/Users/xxx/.rvm/gems/ruby-2.7.0/bin/pod:23:in `load'
/Users/xxx/.rvm/gems/ruby-2.7.0/bin/pod:23:in `<main>'
```

**Comment by Nickolaevich** [comment]
same issue

### Error

```
LoadError - cannot load such file -- rexml/document
/Users/XXXXXXX/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/xcodeproj-1.19.0/lib/xcodeproj/scheme.rb:1:in `require'
/Users/XXXXXXX/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/xcodeproj-1.19.0/lib/xcodeproj/scheme.rb:1:in `<top (required)>'
/Users/XXXXXXX/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/xcodeproj-1.19.0/lib/xcodeproj/project.rb:840:in `require'
/Users/XXXXXXX/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/xcodeproj-1.19.0/lib/xcodeproj/project.rb:840:in `recreate_user_schemes'
/Users/XXXXXXX/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/xcode/pods_project_generator/pods_project_writer.rb:50:in `block in write!'
/Users/XXXXXXX/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/xcode/pods_project_generator/pods_project_writer.rb:45:in `each'
/Users/XXXXXXX/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/xcode/pods_project_generator/pods_project_writer.rb:45:in `write!'
/Users/XXXXXXX/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:328:in `block in create_and_save_projects'
/Users/XXXXXXX/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/XXXXXXX/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:307:in `create_and_save_projects'
/Users/XXXXXXX/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:299:in `generate_pods_project'
/Users/XXXXXXX/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:178:in `integrate'
/Users/XXXXXXX/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:166:in `install!'
/Users/XXXXXXX/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/command/install.rb:52:in `run'
/Users/XXXXXXX/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/XXXXXXX/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/Users/XXXXXXX/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/Users/XXXXXXX/.rvm/rubies/ruby-3.0.0/bin/pod:23:in `load'
/Users/XXXXXXX/.rvm/rubies/ruby-3.0.0/bin/pod:23:in `<main>'
/Users/XXXXXXX/.rvm/rubies/ruby-3.0.0/bin/ruby_executable_hooks:22:in `eval'
/Users/XXXXXXX/.rvm/rubies/ruby-3.0.0/bin/ruby_executable_hooks:22:in `<main>'
```

**Comment by reepz** [comment]
same issue with Rails 6

```
$ rails db:migrate RAILS_ENV=test --trace

rails aborted!
LoadError: cannot load such file -- rexml/document
/home/reepz/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/reepz/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/reepz/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:89:in `register'
```

**Comment by AkkeyLab** [comment]
This issue may be resolved by adding the following items to the Gemfile file:
```ruby
gem 'rexml'
```
https://stackoverflow.com/questions/65479863/rails-6-1-what-is-preventing-tests-from-running
This article was helpful. Thank you

**Comment by dnkoutso** [comment]
You are probably missing this gem so please install it via `gem install rexml`.

As it looks like this does not appear to be a cocoapods library issue.

**Comment by mobibob** [comment]
oops ... i was installing on a new server build-out and did not install cocoapods.  that was one of many issues .. hope that helps someone else.

**Comment by CFKevinRef** [comment]
Ruby 3 no longer includes the `rexml` gem by default. The CocoaPods component Xcodeproj uses `rexml`, but does not declare it as a dependency. Fixed in this unreleased commit: https://github.com/CocoaPods/Xcodeproj/commit/b43e655259f6e21b6e6db84fa3cef6b695a809f5

Based on that commit, I have added this line to my Gemfile - similar to the above suggestion, but with a matching version specifier:
```ruby
gem 'rexml', '~> 3.2.4'
```

**Comment by marcingalus** [comment]
`gem install rexml` did not help not its own, however adding `gem 'rexml', '~> 3.2.4'` to Gemfile (and running bundle install) did! Thanks @CFKevinRef ❤️

**Comment by DanSam5K** [comment]
I just added 
`gem 'rexml' ` to Gemfile 
Then run `bundle install` 
- And it was enough to fix the error.

**Comment by ankitacharya25** [comment]
> I just added
> `gem 'rexml' ` to Gemfile
> Then run `bundle install`
> 
> * And it was enough to fix the error.

Thanks @DanSam5K Worked for me
