### ISSUE TITLE
pod trunk push validation failing to build

### ISSUE THREAD

**Issue by simonmcl** [CocoaPods/CocoaPods#10405]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Tried to run `pod trunk push camlKit.podspec` to update a cocoapod that was previously just a placeholder

## What did you expect to happen?

For the version to publish

## What happened instead?

The validation is failing to build the app, despite the fact that the companion Example app is working fine. Looks like its complaining that one of the dependencies doesn't support arm64. I've tried modifying the podsepc based on many examples with such settings as:

```
s.xcconfig = {'VALID_ARCHS' =>  'x86_64' }
s.xcconfig = { 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64' }

s.pod_target_xcconfig = { 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64' }
s.user_target_xcconfig = { 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64' }
```

I've also tried using various flags to tell trunk to skip validating, allow warnings etc, but none seem to actually skip the process.
```
pod trunk push --skip-import-validation camlKit.podspec 

pod trunk push --skip-import-validation --skip-tests  camlKit.podspec

pod trunk push --allow-warnings camlKit.podspec
```

I've also tried modifying the podfile to include the above settings, as i'm not entirely sure how this validation process works and what is getting built. The library is open source and can been seen here if needed: https://gitlab.com/camlcase-dev/camlkit 

Theres also a warning about the simulator being set to iOS 8. I have nothing set to iOS 8 and also can't remove that warning despite multiple googles.

The verbose build output is:

```
...
...
...
    
    Ld /Users/simonmcloughlin/Library/Developer/Xcode/DerivedData/App-aaxollijpqfpncbwchpzhjgyaxbp/Build/Intermediates.noindex/Pods.build/Release-iphonesimulator/Sodium.build/Objects-normal/arm64/Binary/Sodium normal arm64 (in target 'Sodium' from project 'Pods')
        cd /var/folders/dg/10x8j_ld2ts35szl4178xzg80000gn/T/CocoaPods-Lint-20210204-57867-ml3xdf-camlKit/Pods
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target arm64-apple-ios8.0-simulator -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.3.sdk -L/Users/simonmcloughlin/Library/Developer/Xcode/DerivedData/App-aaxollijpqfpncbwchpzhjgyaxbp/Build/Products/Release-iphonesimulator/Sodium -L/var/folders/dg/10x8j_ld2ts35szl4178xzg80000gn/T/CocoaPods-Lint-20210204-57867-ml3xdf-camlKit/Pods/Sodium/Sodium/libsodium -F/Users/simonmcloughlin/Library/Developer/Xcode/DerivedData/App-aaxollijpqfpncbwchpzhjgyaxbp/Build/Products/Release-iphonesimulator/Sodium -filelist /Users/simonmcloughlin/Library/Developer/Xcode/DerivedData/App-aaxollijpqfpncbwchpzhjgyaxbp/Build/Intermediates.noindex/Pods.build/Release-iphonesimulator/Sodium.build/Objects-normal/arm64/Sodium.LinkFileList -install_name @rpath/Sodium.framework/Sodium -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/simonmcloughlin/Library/Developer/Xcode/DerivedData/App-aaxollijpqfpncbwchpzhjgyaxbp/Build/Intermediates.noindex/Pods.build/Release-iphonesimulator/Sodium.build/Objects-normal/arm64/Sodium_lto.o -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker /Users/simonmcloughlin/Library/Developer/Xcode/DerivedData/App-aaxollijpqfpncbwchpzhjgyaxbp/Build/Intermediates.noindex/Pods.build/Release-iphonesimulator/Sodium.build/Objects-normal/arm64/Sodium.swiftmodule -lsodium-ios -framework Foundation -Xlinker -no_adhoc_codesign -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/simonmcloughlin/Library/Developer/Xcode/DerivedData/App-aaxollijpqfpncbwchpzhjgyaxbp/Build/Intermediates.noindex/Pods.build/Release-iphonesimulator/Sodium.build/Objects-normal/arm64/Sodium_dependency_info.dat -o /Users/simonmcloughlin/Library/Developer/Xcode/DerivedData/App-aaxollijpqfpncbwchpzhjgyaxbp/Build/Intermediates.noindex/Pods.build/Release-iphonesimulator/Sodium.build/Objects-normal/arm64/Binary/Sodium
    ld: in /var/folders/dg/10x8j_ld2ts35szl4178xzg80000gn/T/CocoaPods-Lint-20210204-57867-ml3xdf-camlKit/Pods/Sodium/Sodium/libsodium/libsodium-ios.a(libsodium_la-aead_xchacha20poly1305.o), building for iOS Simulator, but linking in object file built for iOS, for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    
    Ld /Users/simonmcloughlin/Library/Developer/Xcode/DerivedData/App-aaxollijpqfpncbwchpzhjgyaxbp/Build/Intermediates.noindex/Pods.build/Release-iphonesimulator/Sodium.build/Objects-normal/x86_64/Binary/Sodium normal x86_64 (in target 'Sodium' from project 'Pods')
        cd /var/folders/dg/10x8j_ld2ts35szl4178xzg80000gn/T/CocoaPods-Lint-20210204-57867-ml3xdf-camlKit/Pods
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target x86_64-apple-ios8.0-simulator -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.3.sdk -L/Users/simonmcloughlin/Library/Developer/Xcode/DerivedData/App-aaxollijpqfpncbwchpzhjgyaxbp/Build/Products/Release-iphonesimulator/Sodium -L/var/folders/dg/10x8j_ld2ts35szl4178xzg80000gn/T/CocoaPods-Lint-20210204-57867-ml3xdf-camlKit/Pods/Sodium/Sodium/libsodium -F/Users/simonmcloughlin/Library/Developer/Xcode/DerivedData/App-aaxollijpqfpncbwchpzhjgyaxbp/Build/Products/Release-iphonesimulator/Sodium -filelist /Users/simonmcloughlin/Library/Developer/Xcode/DerivedData/App-aaxollijpqfpncbwchpzhjgyaxbp/Build/Intermediates.noindex/Pods.build/Release-iphonesimulator/Sodium.build/Objects-normal/x86_64/Sodium.LinkFileList -install_name @rpath/Sodium.framework/Sodium -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/simonmcloughlin/Library/Developer/Xcode/DerivedData/App-aaxollijpqfpncbwchpzhjgyaxbp/Build/Intermediates.noindex/Pods.build/Release-iphonesimulator/Sodium.build/Objects-normal/x86_64/Sodium_lto.o -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker /Users/simonmcloughlin/Library/Developer/Xcode/DerivedData/App-aaxollijpqfpncbwchpzhjgyaxbp/Build/Intermediates.noindex/Pods.build/Release-iphonesimulator/Sodium.build/Objects-normal/x86_64/Sodium.swiftmodule -lsodium-ios -framework Foundation -Xlinker -no_adhoc_codesign -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/simonmcloughlin/Library/Developer/Xcode/DerivedData/App-aaxollijpqfpncbwchpzhjgyaxbp/Build/Intermediates.noindex/Pods.build/Release-iphonesimulator/Sodium.build/Objects-normal/x86_64/Sodium_dependency_info.dat -o /Users/simonmcloughlin/Library/Developer/Xcode/DerivedData/App-aaxollijpqfpncbwchpzhjgyaxbp/Build/Intermediates.noindex/Pods.build/Release-iphonesimulator/Sodium.build/Objects-normal/x86_64/Binary/Sodium
    
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.3.99. (in target 'secp256k1.swift' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.3.99. (in target 'Sodium' from project 'Pods')
    ** BUILD FAILED **
    
    
    The following build commands failed:
    	CompileSwift normal x86_64
    	CompileSwift normal arm64
    	CompileSwift normal x86_64
    	CompileSwift normal arm64
    	Ld /Users/simonmcloughlin/Library/Developer/Xcode/DerivedData/App-aaxollijpqfpncbwchpzhjgyaxbp/Build/Intermediates.noindex/Pods.build/Release-iphonesimulator/Sodium.build/Objects-normal/arm64/Binary/Sodium normal arm64
    (5 failures)
   Testing with `xcodebuild`. 
 -> camlKit (0.2.0)
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code.
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | xcodebuild:  note: Building targets in parallel
    - NOTE  | xcodebuild:  note: Using codesigning identity override: -
    - NOTE  | [iOS] xcodebuild:  note: Planning build
    - NOTE  | [iOS] xcodebuild:  note: Constructing build description
    - NOTE  | [iOS] xcodebuild:  warning: Skipping code signing because the target does not have an Info.plist file and one is not being generated automatically. (in target 'App' from project 'App')
    - NOTE  | [iOS] xcodebuild:  warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.3.99. (in target 'BigInt' from project 'Pods')
    - NOTE  | [iOS] xcodebuild:  clang: error: linker command failed with exit code 1 (use -v to see invocation)
    - NOTE  | [iOS] xcodebuild:  warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.3.99. (in target 'secp256k1.swift' from project 'Pods')
    - NOTE  | [iOS] xcodebuild:  warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.3.99. (in target 'Sodium' from project 'Pods')

[!] camlKit did not pass validation, due to 1 error.
You can use the `--no-clean` option to inspect any issue.

/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command/lib/lint.rb:113:in `block in run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command/lib/lint.rb:75:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command/lib/lint.rb:75:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.7 (19H2)
       Xcode : 12.3 (12C33)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-keys        : 2.1.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
$minSupportedOS = '12.0'

platform :ios, $minSupportedOS

use_frameworks!
inhibit_all_warnings!

def shared_pods
  pod 'BigInt', '5.0.0'
	pod 'Sodium', '0.8.0'
  pod 'secp256k1.swift', '0.1.4'
  pod 'TrustWalletCore', '2.5.3'
end

target 'camlKit' do
  shared_pods
end

target 'camlKitTests' do
  shared_pods
end

target 'camlKit-Example' do
  shared_pods
end


# Hide all warnings from cocoapods
post_install do |installer|

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
        config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = "YES"

        # Stop a app store connect error "Too many symbols"
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = $minSupportedOS

        # Remove issue from Sodium pre-built library not supporting arm64
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end

  # Pod-Framework
  installer.pods_project.targets.each do |target|
      if target.name == 'Pod-Framework'
          target.build_configurations.each do |config|
              config.build_settings['WARNING_CFLAGS'] ||= ['"-Wno-nullability-completeness"']
          end
      end
  end

  # This removes the warning about swift conversion, hopefuly forever!
  installer.pods_project.root_object.attributes['LastSwiftMigration'] = 9999
  installer.pods_project.root_object.attributes['LastSwiftUpdateCheck'] = 9999
  installer.pods_project.root_object.attributes['LastUpgradeCheck'] = 9999
end
```

## Project that demonstrates the issue

https://gitlab.com/camlcase-dev/camlkit

**Comment by simonmcl** [comment]
I found 2 of the dependencies had provided new releases. Updating to the latest pods moved me on to a different error, complaining about lack of support for iPhoneSimulator arm64.

adding the below to the podspec, allowed me to move on, and I could also remove some of the podfile's post_installs:
```
s.xcconfig = { 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64' }
s.pod_target_xcconfig = { 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64' }
```
