### ISSUE TITLE
cocoapods 1.10.0  when pod update an error occurred.

### ISSUE THREAD

**Issue by yubingxing** [CocoaPods/CocoaPods#10413]
――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod update --no-repo-update
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.10.0
        Ruby : ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin20]
    RubyGems : 3.2.3
        Host : macOS 11.2 (20D64)
       Xcode : 12.4 (12D4e)
         Git : git version 2.30.0
Ruby lib dir : /usr/local/Cellar/ruby/3.0.0_1/lib
Repositories : 
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'

@tag = '4.5.0'
mytarget =  '银翼战机'

target mytarget do

  pod 'IvyiOSSdk/Core', :git => 'git@10.80.1.8:iossdk/IvyiOSSdk.git', :tag => @tag
  pod 'IvyiOSSdk/Umeng', :git => 'git@10.80.1.8:iossdk/IvyiOSSdk.git', :tag => @tag
  pod 'IvyiOSSdk/ThirdLogin', :git => 'git@10.80.1.8:iossdk/IvyiOSSdk.git', :tag => @tag
  pod 'IvyiOSSdk/Toutiao', :git => 'git@10.80.1.8:iossdk/IvyiOSSdk.git', :tag => @tag
  pod 'IvyiOSSdk/GDT', :git => 'git@10.80.1.8:iossdk/IvyiOSSdk.git', :tag => @tag

end
```

### Error

```
SyntaxError - /Users/icestar/.gem/gems/mime-types-3.1/lib/mime/types/logger.rb:28: _1 is reserved for numbered parameter
/Users/icestar/.gem/gems/mime-types-3.1/lib/mime/types/logger.rb:28: _2 is reserved for numbered parameter
/Users/icestar/.gem/gems/mime-types-3.1/lib/mime/types/logger.rb:28: _3 is reserved for numbered parameter
<internal:/usr/local/Cellar/ruby/3.0.0_1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/usr/local/Cellar/ruby/3.0.0_1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/Users/icestar/.gem/gems/mime-types-3.1/lib/mime/types.rb:226:in `<top (required)>'
<internal:/usr/local/Cellar/ruby/3.0.0_1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/usr/local/Cellar/ruby/3.0.0_1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/Users/icestar/.gem/gems/mime-types-3.1/lib/mime/types/columnar.rb:1:in `<top (required)>'
<internal:/usr/local/Cellar/ruby/3.0.0_1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:160:in `require'
<internal:/usr/local/Cellar/ruby/3.0.0_1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'
<internal:/usr/local/Cellar/ruby/3.0.0_1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:149:in `require'
/usr/local/lib/ruby/gems/3.0.0/gems/ethon-0.12.0/lib/ethon.rb:5:in `<top (required)>'
<internal:/usr/local/Cellar/ruby/3.0.0_1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/usr/local/Cellar/ruby/3.0.0_1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/usr/local/lib/ruby/gems/3.0.0/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
<internal:/usr/local/Cellar/ruby/3.0.0_1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/usr/local/Cellar/ruby/3.0.0_1/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.0/lib/cocoapods/sources_manager.rb:74:in `cdn_url?'
/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.0/lib/cocoapods/sources_manager.rb:36:in `create_source_with_url'
/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.0/lib/cocoapods/sources_manager.rb:21:in `find_or_create_source_with_url'
/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:178:in `block in sources'
/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:177:in `map'
/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:177:in `sources'
/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:1073:in `block in resolve_dependencies'
/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.0/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:1072:in `resolve_dependencies'
/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:414:in `analyze'
/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:239:in `block in resolve_dependencies'
/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.0/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:238:in `resolve_dependencies'
/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:160:in `install!'
/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.0/lib/cocoapods/command/update.rb:63:in `run'
/usr/local/lib/ruby/gems/3.0.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.0/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

**Comment by yubingxing** [comment]
I have reinstall cocoapods 1.10.0 many times, but the error still happen

**Comment by dnkoutso** [comment]
Can you try with using Ruby < 3.0?

**Comment by yubingxing** [comment]
I copy the .cocoapods folder from another to the mac, then fix it. The reason is pod setup can't correct fetch cdn url and catch the error.

**Comment by vasilybodnarchuk** [comment]
The same problem. Looks like cocoa pods not working with ruby 3.0

**Comment by dnkoutso** [comment]
It does not work with Ruby 3.x yet its true.

**Comment by Shafran123** [comment]
any fixes for this im also facing this issue
