### ISSUE TITLE
 NoMethodError - undefined method `size' for nil:NilClass

### ISSUE THREAD

**Issue by sumitrvi** [CocoaPods/CocoaPods#10426]
## Flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15 19A583 darwin-x64, locale en-IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.52.1)
[!] Connected device
    ! No devices available
    

### Stack

    ```
       CocoaPods : 1.8.0
            Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
        RubyGems : 3.0.3
            Host : Mac OS X 10.15 (19A583)
           Xcode : 11.1 (11A1027)
             Git : git version 2.21.0 (Apple Git-122)
    Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
    Repositories : master - git - https://github.com/CocoaPods/Specs.git @ 18caeb3ac1a32d3a36b4038556ef4ab0fb246cb2
                   trunk - CDN - https://cdn.cocoapods.org/

    


NoMethodError - undefined method `size' for nil:NilClass
    /Library/Ruby/Gems/2.6.0/gems/ruby-macho-1.4.0/lib/macho/macho_file.rb:455:in `populate_mach_header'
    /Library/Ruby/Gems/2.6.0/gems/ruby-macho-1.4.0/lib/macho/macho_file.rb:233:in `populate_fields'
    /Library/Ruby/Gems/2.6.0/gems/ruby-macho-1.4.0/lib/macho/macho_file.rb:55:in `initialize_from_bin'
    /Library/Ruby/Gems/2.6.0/gems/ruby-macho-1.4.0/lib/macho/macho_file.rb:33:in `new_from_bin'
    /Library/Ruby/Gems/2.6.0/gems/ruby-macho-1.4.0/lib/macho/fat_file.rb:365:in `block in populate_machos'
    /Library/Ruby/Gems/2.6.0/gems/ruby-macho-1.4.0/lib/macho/fat_file.rb:364:in `each'
    /Library/Ruby/Gems/2.6.0/gems/ruby-macho-1.4.0/lib/macho/fat_file.rb:364:in `populate_machos'
    /Library/Ruby/Gems/2.6.0/gems/ruby-macho-1.4.0/lib/macho/fat_file.rb:156:in `populate_fields'
    /Library/Ruby/Gems/2.6.0/gems/ruby-macho-1.4.0/lib/macho/fat_file.rb:95:in `initialize'
    /Library/Ruby/Gems/2.6.0/gems/ruby-macho-1.4.0/lib/macho.rb:31:in `new'
    /Library/Ruby/Gems/2.6.0/gems/ruby-macho-1.4.0/lib/macho.rb:31:in `open'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.0/lib/cocoapods/sandbox/file_accessor.rb:457:in `dynamic_binary?'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.0/lib/cocoapods/sandbox/file_accessor.rb:171:in `block in vendored_dynamic_frameworks'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.0/lib/cocoapods/sandbox/file_accessor.rb:170:in `select'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.0/lib/cocoapods/sandbox/file_accessor.rb:170:in `vendored_dynamic_frameworks'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.0/lib/cocoapods/sandbox/file_accessor.rb:179:in `vendored_static_frameworks'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.0/lib/cocoapods/sandbox/file_accessor.rb:266:in `vendored_static_artifacts'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.0/lib/cocoapods/installer/xcode/target_validator.rb:82:in `each'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.0/lib/cocoapods/installer/xcode/target_validator.rb:82:in `flat_map'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.0/lib/cocoapods/installer/xcode/target_validator.rb:82:in `block (2 levels) in verify_no_static_framework_transitive_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.0/lib/cocoapods/installer/xcode/target_validator.rb:74:in `each_key'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.0/lib/cocoapods/installer/xcode/target_validator.rb:74:in `block in verify_no_static_framework_transitive_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.0/lib/cocoapods/installer/xcode/target_validator.rb:73:in `each'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.0/lib/cocoapods/installer/xcode/target_validator.rb:73:in `verify_no_static_framework_transitive_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.0/lib/cocoapods/installer/xcode/target_validator.rb:38:in `validate!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.0/lib/cocoapods/installer.rb:590:in `validate_targets'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.0/lib/cocoapods/installer.rb:158:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.0/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.0/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.0/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'

   ――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

    [!] Oh no, an error occurred.

    Search for existing GitHub issues similar to yours:
    https://github.com/CocoaPods/CocoaPods/search?q=undefined+method+%60size%27+for+nil%3ANilClass&type=Issues

    If none exists, create a ticket, with the template displayed above, on:
    https://github.com/CocoaPods/CocoaPods/issues/new

    Be sure to first read the contributing guide for details on how to properly submit a ticket:
    https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

    Don't forget to anonymize any private data!

    Looking for related issues on cocoapods/cocoapods...
     - NoMethodError - undefined method `size' for nil:NilClass
       https://github.com/CocoaPods/CocoaPods/issues/10273 [closed] [3 comments]
       5 weeks ago

     - NoMethodError - undefined method `size' for nil:NilClass
       https://github.com/CocoaPods/CocoaPods/issues/8377 [closed] [24 comments]
       12 hours ago

     - NoMethodError - undefined method `each' for nil:NilClass
       https://github.com/CocoaPods/CocoaPods/issues/9239 [closed] [8 comments]
       07 Dec 2020

    and 7 more at:
    https://github.com/cocoapods/cocoapods/search?q=undefined%20method%20%60size%27%20for%20nil&type=Issues&utf8=✓

Error output from CocoaPods:
↳
    /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin19/rbconfig.rb:229: warning: Insecure world writable dir
    /Library/Java/JavaVirtualMachines/jdk1.8.0_251.jdk/Contents/Home/bin in PATH, mode 040777


Error running pod install

**Comment by dnkoutso** [comment]
Please upload a sample app.

**Comment by sumitrvi** [comment]
What kind of sample app.I trying to run flutter build ios command then i'm getting this issue.

**Comment by dnkoutso** [comment]
If you are using Flutter then file an issue at the Flutter repo. We need a sample app that shows an issue without Flutter since we do not own Flutter.
