### ISSUE TITLE
LoadError - incompatible library version - /Users/jenkins/.rvm/gems/ruby-2.7.2/gems/ffi-1.14.2/lib/ffi_c.bundle

### ISSUE THREAD

**Issue by zackrspv** [CocoaPods/CocoaPods#10437]
### Command
```
cd ../ios && /Users/jenkins/.rbenv/versions/2.7.2/bin/pod install --deployment --repo-update
```
### Report
* What did you do?
Ran `pod install`

* What did you expect to happen?
Install all the necessary dependencies from the Podfile

* What happened instead?
Gave the below error

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin20]
    RubyGems : 3.1.4
        Host : macOS 11.2.1 (20D74)
       Xcode : 12.4 (12D4e)
         Git : git version 2.30.1

Ruby lib dir : /Users/jenkins/.rbenv/versions/2.7.2/lib

Repositories : trunk - CDN - https://cdn.cocoapods.org/

```
### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

pod 'lottie-ios', '~> 3.1.8'
platform :ios, '10.0'
target 'OurApp-NotARealName' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
  target 'OurApp-NotARealNameTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'SoMeeSocial-tvOS' do

  # Pods for SoMeeSocial-tvOS

  target 'OurApp-NotARealName-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

```
### Error
```
LoadError - incompatible library version - /Users/jenkins/.rvm/gems/ruby-2.7.2/gems/ffi-1.14.2/lib/ffi_c.bundle
/Users/jenkins/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/Users/jenkins/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/Users/jenkins/.rvm/gems/ruby-2.7.2/gems/ffi-1.14.2/lib/ffi.rb:6:in `rescue in <top (required)>'
/Users/jenkins/.rvm/gems/ruby-2.7.2/gems/ffi-1.14.2/lib/ffi.rb:3:in `<top (required)>'
/Users/jenkins/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/Users/jenkins/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/Users/jenkins/.rvm/gems/ruby-2.7.2/gems/ethon-0.12.0/lib/ethon.rb:2:in `<top (required)>'
/Users/jenkins/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/Users/jenkins/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/Users/jenkins/.rvm/gems/ruby-2.7.2/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
/Users/jenkins/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/Users/jenkins/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/Users/jenkins/.rvm/gems/ruby-2.7.2/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:440:in `download_typhoeus_impl_async'
/Users/jenkins/.rvm/gems/ruby-2.7.2/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:372:in `download_and_save_with_retries_async'
/Users/jenkins/.rvm/gems/ruby-2.7.2/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:365:in `download_file_async'
/Users/jenkins/.rvm/gems/ruby-2.7.2/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:338:in `download_file'
/Users/jenkins/.rvm/gems/ruby-2.7.2/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:78:in `deprecated_local_podspecs'
/Users/jenkins/.rvm/gems/ruby-2.7.2/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:60:in `preheat_existing_files'
/Users/jenkins/.rvm/gems/ruby-2.7.2/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:257:in `update'
/Users/jenkins/.rvm/gems/ruby-2.7.2/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:135:in `block (3 levels) in update'
/Users/jenkins/.rvm/gems/ruby-2.7.2/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/jenkins/.rvm/gems/ruby-2.7.2/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:134:in `block (2 levels) in update'
/Users/jenkins/.rvm/gems/ruby-2.7.2/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:133:in `each'
/Users/jenkins/.rvm/gems/ruby-2.7.2/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:133:in `block in update'
/Users/jenkins/.rvm/gems/ruby-2.7.2/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:131:in `open'
/Users/jenkins/.rvm/gems/ruby-2.7.2/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:131:in `update'
/Users/jenkins/.rvm/gems/ruby-2.7.2/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:145:in `block in update_repositories'
/Users/jenkins/.rvm/gems/ruby-2.7.2/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:143:in `each'
/Users/jenkins/.rvm/gems/ruby-2.7.2/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:143:in `update_repositories'
/Users/jenkins/.rvm/gems/ruby-2.7.2/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:235:in `block in resolve_dependencies'
/Users/jenkins/.rvm/gems/ruby-2.7.2/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/jenkins/.rvm/gems/ruby-2.7.2/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:234:in `resolve_dependencies'
/Users/jenkins/.rvm/gems/ruby-2.7.2/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:160:in `install!'
/Users/jenkins/.rvm/gems/ruby-2.7.2/gems/cocoapods-1.10.1/lib/cocoapods/command/install.rb:52:in `run'
/Users/jenkins/.rvm/gems/ruby-2.7.2/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/jenkins/.rvm/gems/ruby-2.7.2/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/Users/jenkins/.rvm/gems/ruby-2.7.2/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/Users/jenkins/.rbenv/versions/2.7.2/bin/pod:23:in `load'
/Users/jenkins/.rbenv/versions/2.7.2/bin/pod:23:in `<main>'

```

**Comment by zackrspv** [comment]
Note we did try to remove and install the ffi lib again, but no matter what, we just cannot get it to do the `pod install`

**Comment by dnkoutso** [comment]
Try 
```
brew upgrade libffi
export LDFLAGS="-L/usr/local/opt/libffi/lib"
export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig"
```

**Comment by zackrspv** [comment]
So that worked, we had to remove ffi, then reinstall, t hen run your commands, and now it works as expected. Thank you.
