### ISSUE TITLE
RuntimeError - [Xcodeproj] Unknown object version

### ISSUE THREAD

**Issue by Vladyak** [CocoaPods/CocoaPods#10432]
### Command

```
/usr/local/bin/pod deintegrate
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.9.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
    RubyGems : 3.0.3
        Host : macOS 11.2.1 (20D74)
       Xcode : 12.4 (12D4e)
         Git : git version 2.26.2
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Catalog' do
 use_frameworks!

 pod 'Firebase/Auth'
 pod 'Firebase/Firestore'
 pod 'Firebase/Analytics'
 pod 'FirebaseCore'
 pod 'Firebase/Storage'
 pod 'GTMSessionFetcher', '~> 1.3'
 pod 'RealmSwift'
 pod 'Firebase/DynamicLinks'
 pod 'Firebase/Messaging'
 pod "XCDYouTubeKit", "~> 2.9"
end

target 'LCContentNotification' do
 use_frameworks!
 pod "XCDYouTubeKit", "~> 2.9"
end
```

### Error

```
RuntimeError - [Xcodeproj] Unknown object version.
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.14.0/lib/xcodeproj/project.rb:227:in `initialize_from_file'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.14.0/lib/xcodeproj/project.rb:112:in `open'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-deintegrate-1.0.4/lib/cocoapods/command/deintegrate.rb:40:in `validate!'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:333:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by dnkoutso** [comment]
Please update to latest xcodeproj gem version, `gem update xcodeproj`.

**Comment by Mor940k** [comment]
I've got the same issue.
ХCode Version 12.4 (12D4e)
pod version 1.5.2
gem version 3.2.11

**gem update xcodeproj** shows the next log:
Updating installed gems
Nothing to update

**Comment by mudilajaganios** [comment]
I don't know why the issue is being closed, but the we are struggling to resolve it.

**Comment by tpisto** [comment]
`sudo gem update xcodeproj ` fixed this for me

**Comment by mudilajaganios** [comment]
I re-installed macOS. Working fine now.

**Comment by luckcoding** [comment]
I update pod to 1.10.1，is working now
