### ISSUE TITLE
Running pod install gives me this error

### ISSUE THREAD

**Issue by kangpeter5** [CocoaPods/CocoaPods#10457]
### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
    RubyGems : 3.0.3
        Host : macOS 11.2.1 (20D74)
       Xcode : 12.4 (12D4e)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : 
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'


platform :ios, '10.0'


abstract_target 'KSxNYU' do
  
  # React Native Maps dependencies
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
  
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
  
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'

  post_install do |installer|
    flipper_post_install(installer)
  end
  
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications.podspec"
  
  pod 'RNInputMask', :path => '../node_modules/react-native-text-input-mask/ios/InputMask'
  
  
  target 'KSxNYU-Production' do
  end

  target 'KSxNYU-Staging' do
  end

end


#post_install do |installer|
#    installer.pods_project.targets.each do |target|
#        if target.name == 'RNInputMask'
#            target.build_configurations.each do |config|
#                config.build_settings['SWIFT_VERSION'] = '4.2.1'
#            end
#        end
#    end
#end



## Pods for Kettle
#  pod 'React', :path => '../node_modules/react-native/'
#  pod 'React-Core', :path => '../node_modules/react-native/React'
#  pod 'React-DevSupport', :path => '../node_modules/react-native/React'
#  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
#  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
#  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
#  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
#  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
#  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
#  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
#  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
#  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
#  pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'
#
#  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
#  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
#  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
#  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
#  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
#
#  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
#  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
#  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
#
#  use_native_modules!
#  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'
#  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
#  pod 'RNScreens', :path => '../node_modules/react-native-screens'
#  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'
#  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'
#  pod 'react-native-mapbox-gl', :path => '../node_modules/@mapbox/react-native-mapbox-gl'
#
#  pod 'react-native-geolocation', :path => '../node_modules/@react-native-community/geolocation'
#
#  pod 'RNInputMask', :path => '../node_modules/react-native-text-input-mask/ios/InputMask'
#
#  pod '@mauron85_react-native-background-geolocation', :path => '../node_modules/@mauron85/react-native-background-geolocation'
  
#  pod 'Firebase/Core', '~> 6.3.0'
#  pod 'Fabric', '~> 1.10.2'
#  pod 'Crashlytics', '~> 3.13.2'
```

### Error

```
LoadError - dlsym(0x7f9f35d3e470, Init_ffi_c): symbol not found - /Library/Ruby/Gems/2.6.0/gems/ffi-1.14.2/lib/ffi_c.bundle
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/ffi-1.14.2/lib/ffi.rb:6:in `rescue in <top (required)>'
/Library/Ruby/Gems/2.6.0/gems/ffi-1.14.2/lib/ffi.rb:3:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/ethon-0.12.0/lib/ethon.rb:2:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:74:in `cdn_url?'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:36:in `create_source_with_url'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:21:in `find_or_create_source_with_url'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:178:in `block in sources'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:177:in `map'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:177:in `sources'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:1073:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:1072:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:414:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:239:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:238:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:160:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by dnkoutso** [comment]
Please search for similar `ffi` gem installation issues in this repo.

Try 
```
brew upgrade libffi
export LDFLAGS="-L/usr/local/opt/libffi/lib"
export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig"
```

**Comment by kangpeter5** [comment]
@dnkoutso It seems I'm still getting an error even after adding libffi

### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
    RubyGems : 3.0.3
        Host : macOS 11.2.1 (20D74)
       Xcode : 12.4 (12D4e)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : 
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'


platform :ios, '10.0'


abstract_target 'KSxNYU' do
  
  # React Native Maps dependencies
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
  
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
  
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'

  post_install do |installer|
    flipper_post_install(installer)
  end
  
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications.podspec"
  
  pod 'RNInputMask', :path => '../node_modules/react-native-text-input-mask/ios/InputMask'
  
  
  target 'KSxNYU-Production' do
  end

  target 'KSxNYU-Staging' do
  end

end


#post_install do |installer|
#    installer.pods_project.targets.each do |target|
#        if target.name == 'RNInputMask'
#            target.build_configurations.each do |config|
#                config.build_settings['SWIFT_VERSION'] = '4.2.1'
#            end
#        end
#    end
#end



## Pods for Kettle
#  pod 'React', :path => '../node_modules/react-native/'
#  pod 'React-Core', :path => '../node_modules/react-native/React'
#  pod 'React-DevSupport', :path => '../node_modules/react-native/React'
#  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
#  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
#  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
#  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
#  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
#  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
#  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
#  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
#  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
#  pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'
#
#  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
#  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
#  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
#  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
#  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
#
#  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
#  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
#  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
#
#  use_native_modules!
#  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'
#  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
#  pod 'RNScreens', :path => '../node_modules/react-native-screens'
#  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'
#  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'
#  pod 'react-native-mapbox-gl', :path => '../node_modules/@mapbox/react-native-mapbox-gl'
#
#  pod 'react-native-geolocation', :path => '../node_modules/@react-native-community/geolocation'
#
#  pod 'RNInputMask', :path => '../node_modules/react-native-text-input-mask/ios/InputMask'
#
#  pod '@mauron85_react-native-background-geolocation', :path => '../node_modules/@mauron85/react-native-background-geolocation'
  
#  pod 'Firebase/Core', '~> 6.3.0'
#  pod 'Fabric', '~> 1.10.2'
#  pod 'Crashlytics', '~> 3.13.2'
```

### Error

```
LoadError - dlsym(0x7ffad06675e0, Init_ffi_c): symbol not found - /Library/Ruby/Gems/2.6.0/gems/ffi-1.14.2/lib/ffi_c.bundle
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/ffi-1.14.2/lib/ffi.rb:6:in `rescue in <top (required)>'
/Library/Ruby/Gems/2.6.0/gems/ffi-1.14.2/lib/ffi.rb:3:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/ethon-0.12.0/lib/ethon.rb:2:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:74:in `cdn_url?'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:36:in `create_source_with_url'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:21:in `find_or_create_source_with_url'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:178:in `block in sources'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:177:in `map'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:177:in `sources'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:1073:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:1072:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:414:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:239:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:238:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:160:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```
