### ISSUE TITLE
Library not loaded:@rpath/libffi.6.dylib

### ISSUE THREAD

**Issue by phil-zZ** [CocoaPods/CocoaPods#10480]
### Command
```
/Users/ccdoky/.rvm/gems/ruby-2.6.5/bin/pod install --verbose
```
### Report
* What did you do?
* What did you expect to happen?
* What happened instead?
### Stack
```
   CocoaPods : 1.10.1
        Ruby : ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin19]
    RubyGems : 3.1.4
        Host : macOS 11.2.1 (20D74)
       Xcode : 12.4 (12D4e)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /Users/ccdoky/.rvm/rubies/ruby-2.6.5/lib
Repositories : aliyun - git - https://github.com/aliyun/aliyun-specs.git @ 6578f80d440113c7bb47cc5f5946bc27d31b1c11
               cocoapods - git - https://github.com/CocoaPods/Specs.git @ d09752265a26ab870d55989b5640ec3f582f61ec
               master - git - https://gitee.com/mirrors/CocoaPods-Specs.git @ d6f63de6d4d1496040deeb93269aa2889e1b4be6
```
### Plugins
```
claide-plugins                        : 0.9.2
cocoapods-deintegrate                 : 1.0.4
cocoapods-disable-podfile-validations : 0.1.1
cocoapods-generate                    : 2.2.1
cocoapods-plugins                     : 1.0.0
cocoapods-search                      : 1.0.0
cocoapods-stats                       : 1.1.0
cocoapods-trunk                       : 1.5.0
cocoapods-try                         : 1.2.0
cocoapods-ybin                        : 0.0.3
```
### Podfile
```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'
project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}
def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed
    first"
  end
  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end
require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)
flutter_ios_podfile_setup
target 'Runner' do
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
```
### Error
```
LoadError - dlopen(/Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/ffi-1.14.2/lib/ffi_c.bundle, 9): Library not loaded:@rpath/libffi.6.dylib
  Referenced from: /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/ffi-1.14.2/lib/ffi_c.bundle
  Reason: image not found - /Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/ffi-1.14.2/lib/ffi_c.bundle
/Users/ccdoky/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/Users/ccdoky/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/ffi-1.14.2/lib/ffi.rb:6:in `rescue in <top (required)>'
/Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/ffi-1.14.2/lib/ffi.rb:3:in `<top (required)>'
/Users/ccdoky/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/Users/ccdoky/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/ethon-0.12.0/lib/ethon.rb:2:in `<top (required)>'
/Users/ccdoky/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/Users/ccdoky/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
/Users/ccdoky/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/Users/ccdoky/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/Users/ccdoky/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/sources_managerrb:74:in `cdn_url?'
/Users/ccdoky/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/sources_managerrb:36:in `create_source_with_url'
/Users/ccdoky/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/sources_managerrb:21:in
`find_or_create_source_with_url'
/Users/ccdoky/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzerrb:178:in `block in sources'
/Users/ccdoky/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzerrb:177:in `map'
/Users/ccdoky/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzerrb:177:in `sources'
/Users/ccdoky/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzerrb:1073:in `block in
resolve_dependencies'
/Users/ccdoky/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interfacerb:64:in `section'
/Users/ccdoky/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzerrb:1072:in
`resolve_dependencies'
/Users/ccdoky/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzerrb:124:in `analyze'
/Users/ccdoky/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:414:in`analyze'
/Users/ccdoky/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:239:in`block in
resolve_dependencies'
/Users/ccdoky/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interfacerb:64:in `section'
/Users/ccdoky/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:238:in`resolve_dependencies'
/Users/ccdoky/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:160:in`install!'
/Users/ccdoky/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command/installrb:52:in `run'
/Users/ccdoky/.rvm/gems/ruby-2.6.5/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/ccdoky/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/Users/ccdoky/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/Users/ccdoky/.rvm/gems/ruby-2.6.5/bin/pod:23:in `load'
/Users/ccdoky/.rvm/gems/ruby-2.6.5/bin/pod:23:in `<main>'
/Users/ccdoky/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
/Users/ccdoky/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
```

**Comment by dnkoutso** [comment]
Please search for similar issues around `ffi` gem installation. There are countless of them.


Try 
```
brew upgrade libffi
export LDFLAGS="-L/usr/local/opt/libffi/lib"
export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig"
```

**Comment by phil-zZ** [comment]
1. `sudo gem install ffi`
2. Copy FFI to the corresponding directory
![WX20210303-184813](https://user-images.githubusercontent.com/626401/109794664-0dc2d680-7c51-11eb-94d0-f210dad7fbff.png)
