### ISSUE TITLE
ArgumentError - no block given

### ISSUE THREAD

**Issue by troyzhao** [CocoaPods/CocoaPods#10497]
when i run 'pod install', following errors occur.

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.9.1
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.6 (18G87)
       Xcode : 11.3.1 (11C504)
         Git : git version 2.21.1 (Apple Git-122.3)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : edu-git-cocoapods-specs - git - https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git @ bc7a3594ffe2a0d8afad065d8f4f3feb5af1e82a

               master - git - https://git.coding.net/CocoaPods/Specs.git @ a4132a4e9de23c1ba0ffe9265bd5c3e23939edbd

               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby

```

### Error

```
ArgumentError - no block given
/Library/Ruby/Gems/2.3.0/gems/concurrent-ruby-1.1.4/lib/concurrent/promises.rb:1476:in `initialize'
/Library/Ruby/Gems/2.3.0/gems/concurrent-ruby-1.1.4/lib/concurrent/synchronization/object.rb:57:in `new'
/Library/Ruby/Gems/2.3.0/gems/concurrent-ruby-1.1.4/lib/concurrent/synchronization/object.rb:57:in `new'
/Library/Ruby/Gems/2.3.0/gems/concurrent-ruby-1.1.4/lib/concurrent/promises.rb:1383:in `new_blocked_by1'
/Library/Ruby/Gems/2.3.0/gems/concurrent-ruby-1.1.4/lib/concurrent/promises.rb:595:in `chain_on'
/Library/Ruby/Gems/2.3.0/gems/concurrent-ruby-1.1.4/lib/concurrent/promises.rb:577:in `chain'
/Library/Ruby/Gems/2.3.0/gems/concurrent-ruby-1.1.4/lib/concurrent/promises.rb:210:in `schedule_on'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/cdn_source.rb:430:in `sleep_async'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/cdn_source.rb:420:in `exponential_backoff_async'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/cdn_source.rb:404:in `block in download_and_save_with_retries_async'
/Library/Ruby/Gems/2.3.0/gems/concurrent-ruby-1.1.4/lib/concurrent/promises.rb:385:in `apply'
/Library/Ruby/Gems/2.3.0/gems/concurrent-ruby-1.1.4/lib/concurrent/promises.rb:1148:in `apply'
/Library/Ruby/Gems/2.3.0/gems/concurrent-ruby-1.1.4/lib/concurrent/promises.rb:1498:in `block (2 levels) in on_resolvable'
/Library/Ruby/Gems/2.3.0/gems/concurrent-ruby-1.1.4/lib/concurrent/promises.rb:1343:in `evaluate_to'
/Library/Ruby/Gems/2.3.0/gems/concurrent-ruby-1.1.4/lib/concurrent/promises.rb:1498:in `block in on_resolvable'
/Library/Ruby/Gems/2.3.0/gems/concurrent-ruby-1.1.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/Library/Ruby/Gems/2.3.0/gems/concurrent-ruby-1.1.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/Library/Ruby/Gems/2.3.0/gems/concurrent-ruby-1.1.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/Library/Ruby/Gems/2.3.0/gems/concurrent-ruby-1.1.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/Library/Ruby/Gems/2.3.0/gems/concurrent-ruby-1.1.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/Library/Ruby/Gems/2.3.0/gems/concurrent-ruby-1.1.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
/Library/Ruby/Gems/2.3.0/gems/concurrent-ruby-1.1.4/lib/concurrent/promises.rb:1179:in `raise'
/Library/Ruby/Gems/2.3.0/gems/concurrent-ruby-1.1.4/lib/concurrent/promises.rb:1179:in `wait_until_resolved!'
/Library/Ruby/Gems/2.3.0/gems/concurrent-ruby-1.1.4/lib/concurrent/promises.rb:940:in `wait!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/cdn_source.rb:144:in `block in versions'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/cdn_source.rb:471:in `concurrent_requests_catching_errors'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/cdn_source.rb:121:in `versions'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/specification/set.rb:99:in `block in versions_by_source'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/specification/set.rb:98:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/specification/set.rb:98:in `each_with_object'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/specification/set.rb:98:in `versions_by_source'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/specification/set.rb:56:in `specification_name'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/cdn_source.rb:216:in `search'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/source/aggregate.rb:83:in `block in search'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/source/aggregate.rb:83:in `select'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/source/aggregate.rb:83:in `search'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:416:in `create_set_from_sources'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:385:in `find_cached_set'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:360:in `specifications_for_dependency'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:165:in `search_for'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:274:in `block in sort_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:267:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:267:in `sort_by'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:267:in `sort_dependencies'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:53:in `block in sort_dependencies'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:70:in `with_no_such_dependency_error_handling'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:52:in `sort_dependencies'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:288:in `initial_state'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:210:in `start_resolution'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:168:in `resolve'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:94:in `resolve'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:1065:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:1063:in `resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:410:in `analyze'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:235:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:234:in `resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:156:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

**Comment by troyzhao** [comment]
it seems work well after i update the cocoapods to latest version and use a private specs in Podfile
