### ISSUE TITLE
Pod Install Error

### ISSUE THREAD

**Issue by JackTeicher** [CocoaPods/CocoaPods#10507]
When I ran pod install I got a huge error that I did not understand. Any idea how to fix it?

Adding a custom script phase for Pod RNFBApp: [RNFB] Core Configuration
Auto-linking React Native module for target `MenschApp`: RNFBApp
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `Folly` from `../node_modules/react-native/third-party-podspecs/Folly.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
C:/Ruby30-x64/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x64-mingw32]
    RubyGems : 3.2.3
        Host : Unable to find an executable (No such file or directory - sw_vers)  ()
       Xcode : -version) ()
         Git : git version 2.30.2.windows.1
Ruby lib dir : C:/Ruby30-x64/lib
Repositories :
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'MenschApp' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'MenschAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'MenschApp-tvOS' do
  # Pods for MenschApp-tvOS

  target 'MenschApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
```

### Error

```
LoadError - Could not open library 'libcurl': The specified module could not be found.
.
Could not open library 'libcurl.dll': The specified module could not be found.
.
Could not open library 'libcurl.so.4': The specified module could not be found.
.
Could not open library 'libcurl.so.4.dll': The specified module could not be found.

C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/ffi-1.15.0-x64-mingw32/lib/ffi/library.rb:145:in `block in ffi_lib'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/ffi-1.15.0-x64-mingw32/lib/ffi/library.rb:99:in `map'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/ffi-1.15.0-x64-mingw32/lib/ffi/library.rb:99:in `ffi_lib'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/ethon-0.12.0/lib/ethon/curls/settings.rb:7:in `<module:Curl>'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/ethon-0.12.0/lib/ethon/curls/settings.rb:2:in `<module:Ethon>'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/ethon-0.12.0/lib/ethon/curls/settings.rb:1:in `<top (required)>'
<internal:C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/ethon-0.12.0/lib/ethon/curl.rb:27:in `<module:Curl>'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/ethon-0.12.0/lib/ethon/curl.rb:13:in `<module:Ethon>'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/ethon-0.12.0/lib/ethon/curl.rb:8:in `<top (required)>'
<internal:C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/ethon-0.12.0/lib/ethon.rb:15:in `<top (required)>'
<internal:C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
<internal:C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:74:in `cdn_url?'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:36:in `create_source_with_url'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:21:in `find_or_create_source_with_url'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:178:in `block in sources'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:177:in `map'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:177:in `sources'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:1073:in `block in resolve_dependencies'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:1072:in `resolve_dependencies'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:414:in `analyze'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:239:in `block in resolve_dependencies'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:238:in `resolve_dependencies'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:160:in `install!'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/command/install.rb:52:in `run'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
C:/Ruby30-x64/bin/pod:23:in `load'
C:/Ruby30-x64/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=Could+not+open+library+%27libcurl%27%3A+The+specified+module+could+not+be+found.%0D%0A.%0ACould+not+open+library+%27libcurl.dll%27%3A+The+specified+module+could+not+be+found.%0D%0A.%0ACould+not+open+library+%27libcurl.so.4%27%3A+The+specified+module+could+not+be+found.%0D%0A.%0ACould+not+open+library+%27libcurl.so.4.dll%27%3A+The+specified+module+could+not+be+found.%0D%0A&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Searching for inspections failed: undefined method `map' for nil:NilClass

**Comment by dnkoutso** [comment]
Please see related issues around `ffi` gem installation within the issues here.
