### ISSUE TITLE
Encoding::CompatibilityError - incompatible character encodings: UTF-8 and ASCII-8BIT with pod install

### ISSUE THREAD

**Issue by 1039289948** [CocoaPods/CocoaPods#10516]
### Command

```
/Users/alexji/.rvm/gems/ruby-3.0.0/bin/pod install --verbose
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin19]
    RubyGems : 3.2.3
        Host : Mac OS X 10.15.7 (19H524)
       Xcode : 12.4 (12D4e)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /Users/alexji/.rvm/rubies/ruby-3.0.0/lib
Repositories : 240-mos-app-audi-ios-audispecs - git - http://10.160.240.157/mos/app/audi/ios/audispecs.git @ cff678f46401201f70e9c6618a8b07e15e07b03a

               master - git - https://github.com/CocoaPods/Specs.git @ 90ff8153de824a14d35af66b79dd337ff58b26d2

               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
#source 'https://github.com/CocoaPods/Specs'
source 'http://10.160.240.157/mos/app/audi/ios/audispecs.git'
source 'https://github.com/CocoaPods/Specs.git'
#source 'https://mirrors.bfsu.edu.cn/git/CocoaPods/Specs.git'

platform :ios, '11.0'
use_modular_headers!
#use_frameworks!
inhibit_all_warnings!

target 'ADMainProject' do
    pod 'Dollar', '9.0.0'
#    pod 'ADInformationModule', '2021.03.11.02'
    pod 'ADLogin'
    pod 'ADTools'
    pod 'SXTools'
    pod 'ADMallModule'
    pod 'SensorsAnalyticsSDK', :subspecs => ['Location']
end
```

### Error

```
Encoding::CompatibilityError - incompatible character encodings: UTF-8 and ASCII-8BIT
/Users/alexji/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/fileutils.rb:1564:in `join'
/Users/alexji/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/fileutils.rb:1564:in `join'
/Users/alexji/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/fileutils.rb:1224:in `path'
/Users/alexji/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/fileutils.rb:500:in `block in copy_entry'
/Users/alexji/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/fileutils.rb:1513:in `wrap_traverse'
/Users/alexji/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/fileutils.rb:1516:in `block in wrap_traverse'
/Users/alexji/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/fileutils.rb:1515:in `each'
/Users/alexji/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/fileutils.rb:1515:in `wrap_traverse'
/Users/alexji/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/fileutils.rb:1516:in `block in wrap_traverse'
/Users/alexji/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/fileutils.rb:1515:in `each'
/Users/alexji/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/fileutils.rb:1515:in `wrap_traverse'
/Users/alexji/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/fileutils.rb:1516:in `block in wrap_traverse'
/Users/alexji/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/fileutils.rb:1515:in `each'
/Users/alexji/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/fileutils.rb:1515:in `wrap_traverse'
/Users/alexji/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/fileutils.rb:1516:in `block in wrap_traverse'
/Users/alexji/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/fileutils.rb:1515:in `each'
/Users/alexji/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/fileutils.rb:1515:in `wrap_traverse'
/Users/alexji/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/fileutils.rb:497:in `copy_entry'
/Users/alexji/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/fileutils.rb:471:in `block in cp_r'
/Users/alexji/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/fileutils.rb:1597:in `block in fu_each_src_dest'
/Users/alexji/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/fileutils.rb:1613:in `fu_each_src_dest0'
/Users/alexji/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/fileutils.rb:1595:in `fu_each_src_dest'
/Users/alexji/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/fileutils.rb:470:in `cp_r'
/Users/alexji/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/downloader.rb:54:in `block in download'
/Users/alexji/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:145:in `message'
/Users/alexji/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/downloader.rb:52:in `download'
/Users/alexji/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/pod_source_installer.rb:118:in `download_source'
/Users/alexji/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/pod_source_installer.rb:69:in `install!'
/Users/alexji/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:561:in `install_source_of_pod'
/Users/alexji/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:512:in `block (2 levels) in install_pod_sources'
/Users/alexji/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:86:in `titled_section'
/Users/alexji/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:511:in `block in install_pod_sources'
/Users/alexji/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:494:in `each'
/Users/alexji/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:494:in `install_pod_sources'
/Users/alexji/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:253:in `block in download_dependencies'
/Users/alexji/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/alexji/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:252:in `download_dependencies'
/Users/alexji/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:161:in `install!'
/Users/alexji/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/command/install.rb:52:in `run'
/Users/alexji/.rvm/gems/ruby-3.0.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/alexji/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/Users/alexji/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/Users/alexji/.rvm/gems/ruby-3.0.0/bin/pod:23:in `load'
/Users/alexji/.rvm/gems/ruby-3.0.0/bin/pod:23:in `<main>'
```

**Comment by Horse888** [comment]
So how to fix this issue, I hit the same issue.

**Comment by dnkoutso** [comment]
Have you tried using Ruby 2.x?

**Comment by Famzy** [comment]
Facing same issue, any one with a valid solution?

**Comment by rinsuki** [comment]
I have same issue, and it was resolved by prefer ruby@2.7 in $PATH and re-bundle install and pod install, so I think this seems to ruby 3.x specific issue.

also after successfly installs pod once, then it was cached and issue was gone (but if `rm -rf ~/Library/Caches/CocoaPods` then issue will reoccur).

<details><summary>my error</summary>


### Command

```
/opt/homebrew/lib/ruby/gems/3.0.0/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.11.2
        Ruby : ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [arm64-darwin21]
    RubyGems : 3.2.32
        Host : macOS 12.1 (21C52)
       Xcode : 13.2.1 (13C100)
         Git : git version 2.32.0 (Apple Git-132)
Ruby lib dir : /opt/homebrew/Cellar/ruby/3.0.3/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
source 'https://cdn.cocoapods.org/'

abstract_target 'iMastShared' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftLint', '~> 0.40.3'
  pod 'Alamofire', '~> 4.9.1'
  pod 'GRDB.swift', '~> 4.6.2'
  pod 'SwiftyJSON', '~> 5.0.0'
  pod 'HydraAsync', '~> 2.0.6'
  pod 'SDWebImage', '~> 5.9.1'
  pod 'Fuzi', '~> 3.1.2'
  pod 'SnapKit', '~> 5.0.1'
  pod '※ikemen', '~> 0.6.0'
  pod 'KeychainAccess', '~> 4.2.1'
  pod 'SwiftGen', '~> 6.3.0'
  pod "STRegex", "~> 2.1.1"

  abstract_target 'iOS' do
    platform :ios, '14.0'

    pod 'Mew', :git => 'https://github.com/rinsuki/Mew.git', :branch => "fix/podspec"

    target 'iMast iOS' do
      # Pods for iMast
      pod 'Crossroad', '~> 3.2.0'
      pod 'Starscream', '~> 3.1.1'
      pod 'ReachabilitySwift', '~> 4.3.1'
      pod 'Eureka', '~> 5.3.0'
      pod 'EurekaFormBuilder', '~> 0.2.2'
      pod 'EurekaTwolineSliderRow'
      pod 'SVProgressHUD'
      pod 'LicensePlist', '~> 2.16.0'

      target 'iMastTests' do
        # Pods for testing
      end

      target 'iMastUITests' do
        # Pods for testing
      end
    end


    target 'iMastShare' do
    end

    target 'iMastNotifyService' do
    end

    target 'iMastIntents' do
    end

    target 'iMastiOSCore' do
    end
  end

  abstract_target 'Mac' do
    platform :osx, '10.15'
    target 'iMast Mac (App Store)' do
    end

    target 'iMast Mac (with Sparkle)' do
    end

    target 'iMastMacCore' do
    end
  end
end
```

### Error

```
Encoding::CompatibilityError - incompatible character encodings: UTF-8 and ASCII-8BIT
/opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/fileutils.rb:1564:in `join'
/opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/fileutils.rb:1564:in `join'
/opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/fileutils.rb:1224:in `path'
/opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/fileutils.rb:500:in `block in copy_entry'
/opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/fileutils.rb:1513:in `wrap_traverse'
/opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/fileutils.rb:1516:in `block in wrap_traverse'
/opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/fileutils.rb:1515:in `each'
/opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/fileutils.rb:1515:in `wrap_traverse'
/opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/fileutils.rb:1516:in `block in wrap_traverse'
/opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/fileutils.rb:1515:in `each'
/opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/fileutils.rb:1515:in `wrap_traverse'
/opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/fileutils.rb:1516:in `block in wrap_traverse'
/opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/fileutils.rb:1515:in `each'
/opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/fileutils.rb:1515:in `wrap_traverse'
/opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/fileutils.rb:497:in `copy_entry'
/opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/fileutils.rb:471:in `block in cp_r'
/opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/fileutils.rb:1597:in `block in fu_each_src_dest'
/opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/fileutils.rb:1613:in `fu_each_src_dest0'
/opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/fileutils.rb:1595:in `fu_each_src_dest'
/opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/fileutils.rb:470:in `cp_r'
/opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/downloader/cache.rb:287:in `block in copy_and_clean'
/opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/downloader/cache.rb:128:in `lock'
/opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/downloader/cache.rb:99:in `write_lock'
/opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/downloader/cache.rb:285:in `copy_and_clean'
/opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/downloader/cache.rb:244:in `block (2 levels) in uncached_pod'
/opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/downloader/cache.rb:242:in `each'
/opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/downloader/cache.rb:242:in `block in uncached_pod'
/opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/downloader/cache.rb:266:in `in_tmpdir'
/opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/downloader/cache.rb:238:in `uncached_pod'
/opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/downloader/cache.rb:33:in `download_pod'
/opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/downloader.rb:42:in `download'
/opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/pod_source_installer.rb:118:in `download_source'
/opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/pod_source_installer.rb:69:in `install!'
/opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:563:in `install_source_of_pod'
/opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:514:in `block (2 levels) in install_pod_sources'
/opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:86:in `titled_section'
/opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:513:in `block in install_pod_sources'
/opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:496:in `each'
/opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:496:in `install_pod_sources'
/opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:255:in `block in download_dependencies'
/opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:64:in `section'
/opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:254:in `download_dependencies'
/opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:162:in `install!'
/opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/command/install.rb:52:in `run'
/opt/homebrew/lib/ruby/gems/3.0.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in `run'
/opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/bin/pod:55:in `<top (required)>'
/opt/homebrew/lib/ruby/gems/3.0.0/bin/pod:25:in `load'
/opt/homebrew/lib/ruby/gems/3.0.0/bin/pod:25:in `<top (required)>'
/opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/bundler/cli/exec.rb:58:in `load'
/opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/bundler/cli/exec.rb:58:in `kernel_load'
/opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/bundler/cli/exec.rb:23:in `run'
/opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/bundler/cli.rb:478:in `exec'
/opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/bundler/cli.rb:31:in `dispatch'
/opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/bundler/cli.rb:25:in `start'
/opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/exe/bundle:49:in `block in <top (required)>'
/opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/bundler/friendly_errors.rb:103:in `with_friendly_errors'
/opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/exe/bundle:37:in `<top (required)>'
/opt/homebrew/bin/bundle:23:in `load'
/opt/homebrew/bin/bundle:23:in `<main>'
```

</details>

@dnkoutso can you reopen this?

**Comment by jate** [comment]
Resolved the problem.

Just change your project absolutely directory to fully ascii characters.

**Comment by parulgarg004** [comment]
@jate where and how to change, kindly reply

**Comment by easyhaipi** [comment]
cd  你的项目路径 然后pod install
你的项目路径里包含了汉字  也会报这个错误，把项目整个路径里都去掉汉字
