### ISSUE TITLE
problem during cordova plugin add

### ISSUE THREAD

**Issue by giorgiobeggiorasoprasteria** [CocoaPods/CocoaPods#10522]
### Command

```
/usr/local/bin/pod install --verbose
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.4.0
        Ruby : ruby 2.1.0p0 (2013-12-25 revision 44422) [x86_64-darwin16.0]
    RubyGems : 2.2.0
        Host : Mac OS X 10.15.7 (19H524)
       Xcode : 12.0 (12A7209)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /Users/gbeggiora/.rbenv/versions/2.1.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 0588d425d1870bb5fb5a10b2af40c6ac2957fcf2
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# DO NOT MODIFY -- auto-generated by Apache Cordova
source 'https://cdn.cocoapods.org/'
platform :ios, '10.0'
use_frameworks!
target 'Click U2' do
        project 'Click U2.xcodeproj'
        pod 'ZXingObjC', '3.2.2'
        pod 'OneSignal', '2.12.6'
        pod 'Firebase/Auth', '6.19.0'
        pod 'Firebase/Messaging', '6.19.0'
        pod 'Firebase/Performance', '6.19.0'
        pod 'Firebase/RemoteConfig', '6.19.0'
        pod 'Firebase/DynamicLinks', '6.19.0'
        pod 'Firebase/Analytics', '6.19.0'
        pod 'Fabric', '~> 1.10.2'
        pod 'Crashlytics', '~> 3.14.0'
        pod 'FBSDKCoreKit', '$FACEBOOK_IOS_SDK_VERSION'
        pod 'FBSDKLoginKit', '$FACEBOOK_IOS_SDK_VERSION'
        pod 'FBSDKShareKit', '$FACEBOOK_IOS_SDK_VERSION'
end
```

### Error

```
ArgumentError - Illformed requirement `"$FACEBOOK_IOS_SDK_VERSION"`
/Users/gbeggiora/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/cocoapods-core-1.4.0/lib/cocoapods-core/requirement.rb:63:in `parse'
/Users/gbeggiora/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/cocoapods-core-1.4.0/lib/cocoapods-core/requirement.rb:88:in `block in initialize'
/Users/gbeggiora/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/cocoapods-core-1.4.0/lib/cocoapods-core/requirement.rb:88:in `map!'
/Users/gbeggiora/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/cocoapods-core-1.4.0/lib/cocoapods-core/requirement.rb:88:in `initialize'
/Users/gbeggiora/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/cocoapods-core-1.4.0/lib/cocoapods-core/requirement.rb:34:in `new'
/Users/gbeggiora/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/cocoapods-core-1.4.0/lib/cocoapods-core/requirement.rb:34:in `create'
/Users/gbeggiora/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/cocoapods-core-1.4.0/lib/cocoapods-core/dependency.rb:116:in `initialize'
/Users/gbeggiora/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/cocoapods-core-1.4.0/lib/cocoapods-core/podfile/target_definition.rb:796:in `new'
/Users/gbeggiora/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/cocoapods-core-1.4.0/lib/cocoapods-core/podfile/target_definition.rb:796:in `block in pod_dependencies'
/Users/gbeggiora/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/cocoapods-core-1.4.0/lib/cocoapods-core/podfile/target_definition.rb:792:in `map'
/Users/gbeggiora/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/cocoapods-core-1.4.0/lib/cocoapods-core/podfile/target_definition.rb:792:in `pod_dependencies'
/Users/gbeggiora/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/cocoapods-core-1.4.0/lib/cocoapods-core/podfile/target_definition.rb:96:in `non_inherited_dependencies'
/Users/gbeggiora/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/cocoapods-core-1.4.0/lib/cocoapods-core/podfile/target_definition.rb:74:in `dependencies'
/Users/gbeggiora/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/podfile_validator.rb:71:in `block in validate_pod_directives'
/Users/gbeggiora/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/podfile_validator.rb:70:in `each'
/Users/gbeggiora/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/podfile_validator.rb:70:in `flat_map'
/Users/gbeggiora/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/podfile_validator.rb:70:in `validate_pod_directives'
/Users/gbeggiora/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/podfile_validator.rb:34:in `validate'
/Users/gbeggiora/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/analyzer.rb:188:in `validate_podfile!'
/Users/gbeggiora/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/analyzer.rb:71:in `analyze'
/Users/gbeggiora/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:243:in `analyze'
/Users/gbeggiora/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:154:in `block in resolve_dependencies'
/Users/gbeggiora/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/cocoapods-1.4.0/lib/cocoapods/user_interface.rb:64:in `section'
/Users/gbeggiora/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:153:in `resolve_dependencies'
/Users/gbeggiora/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:116:in `install!'
/Users/gbeggiora/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/cocoapods-1.4.0/lib/cocoapods/command/install.rb:41:in `run'
/Users/gbeggiora/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/gbeggiora/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/cocoapods-1.4.0/lib/cocoapods/command.rb:52:in `run'
/Users/gbeggiora/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/cocoapods-1.4.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

(I have only ios platform) cordova plugin add cordova-plugin-facebook-connect --save --variable APP_ID="......" --variable APP_NAME="......"

## What did you expect to happen?

plugin installs without errors

## What happened instead?

Plugin installs with errors

### Stack

```
   CocoaPods : 1.4.0
        Ruby : ruby 2.1.0p0 (2013-12-25 revision 44422) [x86_64-darwin16.0]
    RubyGems : 2.2.0
        Host : Mac OS X 10.15.7 (19H524)
       Xcode : 12.0 (12A7209)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /Users/gbeggiora/.rbenv/versions/2.1.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 0588d425d1870bb5fb5a10b2af40c6ac2957fcf2
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# DO NOT MODIFY -- auto-generated by Apache Cordova
source 'https://cdn.cocoapods.org/'
platform :ios, '10.0'
use_frameworks!
target 'Click U2' do
        project 'Click U2.xcodeproj'
        pod 'ZXingObjC', '3.2.2'
        pod 'OneSignal', '2.12.6'
        pod 'Firebase/Auth', '6.19.0'
        pod 'Firebase/Messaging', '6.19.0'
        pod 'Firebase/Performance', '6.19.0'
        pod 'Firebase/RemoteConfig', '6.19.0'
        pod 'Firebase/DynamicLinks', '6.19.0'
        pod 'Firebase/Analytics', '6.19.0'
        pod 'Fabric', '~> 1.10.2'
        pod 'Crashlytics', '~> 3.14.0'
        pod 'FBSDKCoreKit', '$FACEBOOK_IOS_SDK_VERSION'
        pod 'FBSDKLoginKit', '$FACEBOOK_IOS_SDK_VERSION'
        pod 'FBSDKShareKit', '$FACEBOOK_IOS_SDK_VERSION'
end
```

## Project that demonstrates the issue

<img width="650" alt="Schermata 2021-03-16 alle 12 16 22" src="https://user-images.githubusercontent.com/26274034/111300503-7185d000-8651-11eb-878c-7a8b3ff48711.png">

**Comment by paulb777** [comment]
This looks like a problem with the Cordova Facebook integration creating an invalid Podfile. Likely, a Cordova channel would be a better place to investigate.

**Comment by ptmceldowney** [comment]
Were you able to figure this problem out? I just run into this error on existing project that hasn't had this issue before.

**Comment by giorgiobeggiorasoprasteria** [comment]
sorry, I don't remember how I did it, someone helped me.
