### ISSUE TITLE
Errno::ENOENT - No such file or directory @ rb_sysopen

### ISSUE THREAD

**Issue by barisferah** [CocoaPods/CocoaPods#10553]
### Command

```
C:/Ruby27-x64/bin/pod install --repo-update
```

### Report

* What did you do?
https://airtdave.medium.com/using-cocoapods-on-windows-dec471735f51

By following this article I have managed to install Cocoapods on Windows 10. After I figured out a couple of error by simple Googling I got stuck at this part. I have tried other solutions that are mentioned on similar problems however, none of them has worked. 

* What did you expect to happen?
I was expecting to add pods on Windows side (I'm a Unity Developer) There is only one main pod dependency and that is Google Mobile Ads SDK.

* What happened instead?
It is failing with this error message;

_Errno::ENOENT - No such file or directory @ rb_sysopen - C:/Users/baris/Library/Caches/CocoaPods/Pods/Release/Google-Mobile-Ads-SDK/7.68.0-29bbd/Frameworks/GoogleMobileAdsFramework-Current/GoogleMobileAds.xcframework/ios-armv7_arm64/GoogleMobileAds.framework/Headers/Mediation/GADMediatedUnifiedNativeAdNotificationSource.h_

I can confirm that this file isn't present at the expected location and when I compare it with Google's binary stored on their server, there are more missing files. When I build the project on Mac OS X everything happens as expected.

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x64-mingw32]
    RubyGems : 3.1.4
        Host : Unable to find an executable (No such file or directory - sw_vers)  ()
       Xcode : -version) ()
         Git : git version 2.31.1.windows.1
Ruby lib dir : C:/Ruby27-x64/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ 8a068b124acaaa32a07abef15b4bf102e9ca00ab

```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'

target 'UnityFramework' do
  pod 'Google-Mobile-Ads-SDK', '= 7.68'
end
target 'Unity-iPhone' do
end
use_frameworks!
```

### Error

```
Errno::ENOENT - No such file or directory @ rb_sysopen - C:/Users/baris/Library/Caches/CocoaPods/Pods/Release/Google-Mobile-Ads-SDK/7.68.0-29bbd/Frameworks/GoogleMobileAdsFramework-Current/GoogleMobileAds.xcframework/ios-armv7_arm64/GoogleMobileAds.framework/Headers/Mediation/GADMediatedUnifiedNativeAdNotificationSource.h
C:/Ruby27-x64/lib/ruby/2.7.0/fileutils.rb:1415:in `initialize'
C:/Ruby27-x64/lib/ruby/2.7.0/fileutils.rb:1415:in `open'
C:/Ruby27-x64/lib/ruby/2.7.0/fileutils.rb:1415:in `block in copy_file'
C:/Ruby27-x64/lib/ruby/2.7.0/fileutils.rb:1414:in `open'
C:/Ruby27-x64/lib/ruby/2.7.0/fileutils.rb:1414:in `copy_file'
C:/Ruby27-x64/lib/ruby/2.7.0/fileutils.rb:1379:in `copy'
C:/Ruby27-x64/lib/ruby/2.7.0/fileutils.rb:497:in `block in copy_entry'
C:/Ruby27-x64/lib/ruby/2.7.0/fileutils.rb:1513:in `wrap_traverse'
C:/Ruby27-x64/lib/ruby/2.7.0/fileutils.rb:1516:in `block in wrap_traverse'
C:/Ruby27-x64/lib/ruby/2.7.0/fileutils.rb:1515:in `each'
C:/Ruby27-x64/lib/ruby/2.7.0/fileutils.rb:1515:in `wrap_traverse'
C:/Ruby27-x64/lib/ruby/2.7.0/fileutils.rb:1516:in `block in wrap_traverse'
C:/Ruby27-x64/lib/ruby/2.7.0/fileutils.rb:1515:in `each'
C:/Ruby27-x64/lib/ruby/2.7.0/fileutils.rb:1515:in `wrap_traverse'
C:/Ruby27-x64/lib/ruby/2.7.0/fileutils.rb:1516:in `block in wrap_traverse'
C:/Ruby27-x64/lib/ruby/2.7.0/fileutils.rb:1515:in `each'
C:/Ruby27-x64/lib/ruby/2.7.0/fileutils.rb:1515:in `wrap_traverse'
C:/Ruby27-x64/lib/ruby/2.7.0/fileutils.rb:1516:in `block in wrap_traverse'
C:/Ruby27-x64/lib/ruby/2.7.0/fileutils.rb:1515:in `each'
C:/Ruby27-x64/lib/ruby/2.7.0/fileutils.rb:1515:in `wrap_traverse'
C:/Ruby27-x64/lib/ruby/2.7.0/fileutils.rb:1516:in `block in wrap_traverse'
C:/Ruby27-x64/lib/ruby/2.7.0/fileutils.rb:1515:in `each'
C:/Ruby27-x64/lib/ruby/2.7.0/fileutils.rb:1515:in `wrap_traverse'
C:/Ruby27-x64/lib/ruby/2.7.0/fileutils.rb:1516:in `block in wrap_traverse'
C:/Ruby27-x64/lib/ruby/2.7.0/fileutils.rb:1515:in `each'
C:/Ruby27-x64/lib/ruby/2.7.0/fileutils.rb:1515:in `wrap_traverse'
C:/Ruby27-x64/lib/ruby/2.7.0/fileutils.rb:1516:in `block in wrap_traverse'
C:/Ruby27-x64/lib/ruby/2.7.0/fileutils.rb:1515:in `each'
C:/Ruby27-x64/lib/ruby/2.7.0/fileutils.rb:1515:in `wrap_traverse'
C:/Ruby27-x64/lib/ruby/2.7.0/fileutils.rb:1516:in `block in wrap_traverse'
C:/Ruby27-x64/lib/ruby/2.7.0/fileutils.rb:1515:in `each'
C:/Ruby27-x64/lib/ruby/2.7.0/fileutils.rb:1515:in `wrap_traverse'
C:/Ruby27-x64/lib/ruby/2.7.0/fileutils.rb:494:in `copy_entry'
C:/Ruby27-x64/lib/ruby/2.7.0/fileutils.rb:468:in `block in cp_r'
C:/Ruby27-x64/lib/ruby/2.7.0/fileutils.rb:1589:in `block in fu_each_src_dest'
C:/Ruby27-x64/lib/ruby/2.7.0/fileutils.rb:1605:in `fu_each_src_dest0'
C:/Ruby27-x64/lib/ruby/2.7.0/fileutils.rb:1587:in `fu_each_src_dest'
C:/Ruby27-x64/lib/ruby/2.7.0/fileutils.rb:467:in `cp_r'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/downloader/cache.rb:201:in `copy_and_clean'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/downloader/cache.rb:159:in `block (2 levels) in uncached_pod'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/downloader/cache.rb:157:in `each'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/downloader/cache.rb:157:in `block in uncached_pod'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/downloader/cache.rb:181:in `in_tmpdir'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/downloader/cache.rb:153:in `uncached_pod'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/downloader/cache.rb:33:in `download_pod'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/downloader.rb:42:in `download'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/pod_source_installer.rb:118:in `download_source'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/pod_source_installer.rb:69:in `install!'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:561:in `install_source_of_pod'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:512:in `block (2 levels) in install_pod_sources'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:86:in `titled_section'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:511:in `block in install_pod_sources'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:494:in `each'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:494:in `install_pod_sources'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:253:in `block in download_dependencies'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:252:in `download_dependencies'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:161:in `install!'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/command/install.rb:52:in `run'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
C:/Ruby27-x64/bin/pod:23:in `load'
C:/Ruby27-x64/bin/pod:23:in `<main>'
```

**Comment by barisferah** [comment]
As far as I understand the issue that I'm facing at the moment is the same with the one at the 

https://github.com/CocoaPods/CocoaPods/issues/8959

and hasn't been solved yet. The error is occurring only after encountering a path string that has more than ~260 characters in it. Since the issue has been reported before I'm closing this one.
