### ISSUE TITLE
I got error when doing pod install, something to do with M1 chip

### ISSUE THREAD

**Issue by kenjichanhkg** [CocoaPods/CocoaPods#10569]
I got error when doing pod install with the following libraries

- react-native-fbsdk-next
- react-native-mapbox-gl/maps

I think it's something to do with the M1 chip.

### Command

```
/Users/kenji/.rvm/gems/ruby-3.0.0/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.arm64e-darwin20]
    RubyGems : 3.0.3
        Host : macOS 11.2.3 (20D91)
       Xcode : 12.4 (12D4e)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

# We ingore warning except for RNMBGL
INHIBIT_WARNING_BY_DEFAULT = true

if INHIBIT_WARNING_BY_DEFAULT
  ORIG_POD = method(:pod)

  # Override pods so we default to disbling all warnings
  def pod(name, *requirements)
    options = requirements.last
    if options.is_a?(Hash)
      options[:inhibit_warnings] = true unless options.has_key?(:inhibit_warnings)
    else
      requirements.push({inhibit_warnings: true})
    end
    ORIG_POD[name, *requirements]
  end
end

target 'RNMapboxGLExample' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  # default version
  pod 'react-native-mapbox-gl', :path => '../../', :inhibit_warnings => false

  target 'RNMapboxGLExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  use_native_modules!

  pre_install do |installer|
    $RNMBGL.pre_install(installer)
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  if !ENV['CI']
    # local configuration
    use_flipper!({ 'Flipper-Folly' => '2.3.0' })
    post_install do |installer|
      flipper_post_install(installer)
      $RNMBGL.post_install(installer)
    end
  else
    # CI configuration
    post_install do |installer|
    $RNMBGL.post_install(installer)
    end
  end
end

target 'RNMapboxGLExample-tvOS' do
  # Pods for RNMapboxGLExample-tvOS

  target 'RNMapboxGLExample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

### Error

```
LoadError - dlopen(/Users/kenji/.rvm/gems/ruby-3.0.0/gems/ffi-1.15.0/lib/ffi_c.bundle, 0x0009): missing compatible arch in /Users/kenji/.rvm/gems/ruby-3.0.0/gems/ffi-1.15.0/lib/ffi_c.bundle - /Users/kenji/.rvm/gems/ruby-3.0.0/gems/ffi-1.15.0/lib/ffi_c.bundle
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/kenji/.rvm/gems/ruby-3.0.0/gems/ffi-1.15.0/lib/ffi.rb:6:in `rescue in <top (required)>'
/Users/kenji/.rvm/gems/ruby-3.0.0/gems/ffi-1.15.0/lib/ffi.rb:3:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/kenji/.rvm/gems/ruby-3.0.0/gems/ethon-0.12.0/lib/ethon.rb:2:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/kenji/.rvm/gems/ruby-3.0.0/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/kenji/.rvm/gems/ruby-3.0.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:440:in `download_typhoeus_impl_async'
/Users/kenji/.rvm/gems/ruby-3.0.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:372:in `download_and_save_with_retries_async'
/Users/kenji/.rvm/gems/ruby-3.0.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:365:in `download_file_async'
/Users/kenji/.rvm/gems/ruby-3.0.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:338:in `download_file'
/Users/kenji/.rvm/gems/ruby-3.0.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:284:in `ensure_versions_file_loaded'
/Users/kenji/.rvm/gems/ruby-3.0.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:208:in `search'
/Users/kenji/.rvm/gems/ruby-3.0.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/source/aggregate.rb:83:in `block in search'
/Users/kenji/.rvm/gems/ruby-3.0.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/source/aggregate.rb:83:in `select'
/Users/kenji/.rvm/gems/ruby-3.0.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/source/aggregate.rb:83:in `search'
/Users/kenji/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:416:in `create_set_from_sources'
/Users/kenji/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:385:in `find_cached_set'
/Users/kenji/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:360:in `specifications_for_dependency'
/Users/kenji/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:165:in `search_for'
/Users/kenji/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:274:in `block in sort_dependencies'
/Users/kenji/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:267:in `each'
/Users/kenji/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:267:in `sort_by'
/Users/kenji/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:267:in `sort_dependencies'
/Users/kenji/.rvm/gems/ruby-3.0.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:53:in `block in sort_dependencies'
/Users/kenji/.rvm/gems/ruby-3.0.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:70:in `with_no_such_dependency_error_handling'
/Users/kenji/.rvm/gems/ruby-3.0.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:52:in `sort_dependencies'
/Users/kenji/.rvm/gems/ruby-3.0.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:754:in `push_state_for_requirements'
/Users/kenji/.rvm/gems/ruby-3.0.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:746:in `require_nested_dependencies_for'
/Users/kenji/.rvm/gems/ruby-3.0.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:729:in `activate_new_spec'
/Users/kenji/.rvm/gems/ruby-3.0.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:686:in `attempt_to_activate'
/Users/kenji/.rvm/gems/ruby-3.0.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:254:in `process_topmost_state'
/Users/kenji/.rvm/gems/ruby-3.0.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
/Users/kenji/.rvm/gems/ruby-3.0.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
/Users/kenji/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:94:in `resolve'
/Users/kenji/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:1074:in `block in resolve_dependencies'
/Users/kenji/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/kenji/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:1072:in `resolve_dependencies'
/Users/kenji/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/Users/kenji/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:414:in `analyze'
/Users/kenji/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:239:in `block in resolve_dependencies'
/Users/kenji/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/kenji/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:238:in `resolve_dependencies'
/Users/kenji/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:160:in `install!'
/Users/kenji/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/command/install.rb:52:in `run'
/Users/kenji/.rvm/gems/ruby-3.0.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/kenji/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/Users/kenji/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/Users/kenji/.rvm/gems/ruby-3.0.0/bin/pod:23:in `load'
/Users/kenji/.rvm/gems/ruby-3.0.0/bin/pod:23:in `<main>'
```

**Comment by JOSERIDER** [comment]
I've the same issue, please how to solve this ???

**Comment by JuanGuana** [comment]
Check this #10518

**Comment by AlexbabuNaico** [comment]
I had similar issues and finally got it fixed. Select the project in xcode > go to build settings > search excluded architectures > Already there will be Debug and Release add another one param inside of both debug and release and select "Any iOS simulator SDK" and add "arm64" to it. Note that if you give it completely to debug and release then it will cause the build made for debug and release to fail. Thanks and Happy coding :)
