### ISSUE TITLE
LoadError - incompatible library version

### ISSUE THREAD

**Issue by mradeybee** [CocoaPods/CocoaPods#10573]
### Command

```
/usr/local/Cellar/cocoapods/1.10.1/libexec/bin/pod install
```

#### What did you do?
- npx pod install

#### What did you expect to happen?
- pod install shold run successfully 

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.7 (19H524)
       Xcode : 10.2.1 (10E1001)
         Git : git version 2.20.1
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : 
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'AppName' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'
  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  target 'ErrandsDashTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end
end
```

### Error

```
LoadError - incompatible library version - /Users/adepojuadebayo/.rvm/gems/ruby-2.6.5/gems/ffi-1.15.0/lib/ffi_c.bundle
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/adepojuadebayo/.rvm/gems/ruby-2.6.5/gems/ffi-1.15.0/lib/ffi.rb:6:in `rescue in <top (required)>'
/Users/adepojuadebayo/.rvm/gems/ruby-2.6.5/gems/ffi-1.15.0/lib/ffi.rb:3:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Cellar/cocoapods/1.10.1/libexec/gems/ethon-0.12.0/lib/ethon.rb:2:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Cellar/cocoapods/1.10.1/libexec/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:74:in `cdn_url?'
/usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:36:in `create_source_with_url'
/usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:21:in `find_or_create_source_with_url'
/usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:178:in `block in sources'
/usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:177:in `map'
/usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:177:in `sources'
/usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:1073:in `block in resolve_dependencies'
/usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:1072:in `resolve_dependencies'
/usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:414:in `analyze'
/usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:239:in `block in resolve_dependencies'
/usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:238:in `resolve_dependencies'
/usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:160:in `install!'
/usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/command/install.rb:52:in `run'
/usr/local/Cellar/cocoapods/1.10.1/libexec/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/usr/local/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/usr/local/Cellar/cocoapods/1.10.1/libexec/bin/pod:23:in `load'
/usr/local/Cellar/cocoapods/1.10.1/libexec/bin/pod:23:in `<main>'
```

**Comment by schornon** [comment]
Have the same issue with _ffi-1.15.0_

**Comment by schornon** [comment]
I fixed it 🍻.
I think this solution only for arm macs.
What I did:
            - update ffi (1.15.0) and install ethon (0.13.0)
            - install latest ruby (3.0.0p0) `rvm install ruby@latest` and set it as default `rvm use ruby-3.0.0 --default`
            - **A few times** install cocoapods `gem install cocoapods`
As a result, I can run `pod install` without prefix `arch -x86_64`.

**Comment by felix-lambert** [comment]
I have this problem with `pod install --repo-update` but not with `pod install` 

I'm using a M1 mac so i can't downgrade ruby. I have to use version 3. Is there a way to keep this version of ruby ?

**Comment by andyabarnard** [comment]
> I fixed it 🍻.
> I think this solution only for arm macs.
> What I did:
> - update ffi (1.15.0) and install ethon (0.13.0)
> - install latest ruby (3.0.0p0) `rvm install ruby@latest` and set it as default `rvm use ruby-3.0.0 --default`
> - **A few times** install cocoapods `gem install cocoapods`
> As a result, I can run `pod install` without prefix `arch -x86_64`.

After hours and hours of debugging I finally find this comment.  It worked perfectly.  Thank you so much.  I was about to pour lava all over my Mac mini in hopes that the volcano gods might have better luck getting Flutter to build on an ARM processor.

**Comment by chinomnsoawazie** [comment]
This solution didn't work for me after I started adding libraries to a react native project. However, [this](https://stackoverflow.com/a/63146658/14172691) solution worked. i.e

- execute `gem pristine --all`

- in my project's directory, execute `rm -rf vendor` (removes the project specific gem folder)

- and run `bundle update`

**Comment by puniker** [comment]
> > I fixed it 🍻.
> > I think this solution only for arm macs.
> > What I did:
> > 
> > * update ffi (1.15.0) and install ethon (0.13.0)
> > * install latest ruby (3.0.0p0) rvm install ruby@latest and set it as default rvm use ruby-3.0.0 --default
> > * A few times install cocoapods gem install cocoapods
> >   As a result, I can run pod install without prefix arch -x86_64.
> 
> This solution didn't work for me after I started adding libraries to a react native project. However, [this](https://stackoverflow.com/a/63146658/14172691) solution worked. i.e
> 
> * execute `gem pristine --all`
> * in my project's directory, execute `rm -rf vendor` (removes the project specific gem folder)
> * and run `bundle update`
> 
> Project is using `react-native 0.70.1` and `react 18.1.0`

Its worked for me

**Comment by nc-hung** [comment]
> I fixed it 🍻. I think this solution only for arm macs. What I did: - update ffi (1.15.0) and install ethon (0.13.0) - install latest ruby (3.0.0p0) `rvm install ruby@latest` and set it as default `rvm use ruby-3.0.0 --default` - **A few times** install cocoapods `gem install cocoapods` As a result, I can run `pod install` without prefix `arch -x86_64`.

Its worked for me
