### ISSUE TITLE
CocoaPods 1.9.3 update 1.10.1 error

### ISSUE THREAD

**Issue by boai** [CocoaPods/CocoaPods#10595]
――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/boai/.rvm/gems/ruby-2.6.6/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-darwin20]
    RubyGems : 3.0.9
        Host : macOS 11.2.3 (20D91)
       Xcode : 12.4 (12D4e)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /Users/boai/.rvm/rubies/ruby-2.6.6/lib
Repositories : edu-git-cocoapods-specs - git - https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git @ 80ee29403d0dbea2360660cd89a1c398cd8962df

```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
#install! 'cocoapods', :generate_multiple_pod_projects = > true

platform :ios,'11.0'

source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

inhibit_all_warnings!


target '***' do
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!

  pod 'wbServer', :path => "../wbServer"
  
end
```

### Error

```
NoMethodError - undefined method `children' for #<Xcodeproj::Project::Object::PBXFileReference:0x00007f86b5383068>
/Users/boai/.rvm/gems/ruby-2.6.6/gems/cocoapods-1.10.1/lib/cocoapods/project.rb:465:in `block in group_for_path_in_group'
/Users/boai/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/pathname.rb:263:in `block in each_filename'
/Users/boai/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/pathname.rb:263:in `each'
/Users/boai/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/pathname.rb:263:in `each_filename'
/Users/boai/.rvm/gems/ruby-2.6.6/gems/cocoapods-1.10.1/lib/cocoapods/project.rb:459:in `group_for_path_in_group'
/Users/boai/.rvm/gems/ruby-2.6.6/gems/cocoapods-1.10.1/lib/cocoapods/project.rb:273:in `add_file_reference'
/Users/boai/.rvm/gems/ruby-2.6.6/gems/cocoapods-1.10.1/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:224:in `block (2 levels) in add_file_accessors_paths_to_pods_group'
/Users/boai/.rvm/gems/ruby-2.6.6/gems/cocoapods-1.10.1/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:223:in `each'
/Users/boai/.rvm/gems/ruby-2.6.6/gems/cocoapods-1.10.1/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:223:in `block in add_file_accessors_paths_to_pods_group'
/Users/boai/.rvm/gems/ruby-2.6.6/gems/cocoapods-1.10.1/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:213:in `each'
/Users/boai/.rvm/gems/ruby-2.6.6/gems/cocoapods-1.10.1/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:213:in `add_file_accessors_paths_to_pods_group'
/Users/boai/.rvm/gems/ruby-2.6.6/gems/cocoapods-1.10.1/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:130:in `block in add_resources'
/Users/boai/.rvm/gems/ruby-2.6.6/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:145:in `message'
/Users/boai/.rvm/gems/ruby-2.6.6/gems/cocoapods-1.10.1/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:128:in `add_resources'
/Users/boai/.rvm/gems/ruby-2.6.6/gems/cocoapods-1.10.1/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:49:in `install!'
/Users/boai/.rvm/gems/ruby-2.6.6/gems/cocoapods-1.10.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:102:in `block in install_file_references'
/Users/boai/.rvm/gems/ruby-2.6.6/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:145:in `message'
/Users/boai/.rvm/gems/ruby-2.6.6/gems/cocoapods-1.10.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:100:in `install_file_references'
/Users/boai/.rvm/gems/ruby-2.6.6/gems/cocoapods-1.10.1/lib/cocoapods/installer/xcode/single_pods_project_generator.rb:17:in `generate!'
/Users/boai/.rvm/gems/ruby-2.6.6/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:312:in `block in create_and_save_projects'
/Users/boai/.rvm/gems/ruby-2.6.6/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/boai/.rvm/gems/ruby-2.6.6/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:307:in `create_and_save_projects'
/Users/boai/.rvm/gems/ruby-2.6.6/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:299:in `generate_pods_project'
/Users/boai/.rvm/gems/ruby-2.6.6/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:178:in `integrate'
/Users/boai/.rvm/gems/ruby-2.6.6/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:166:in `install!'
/Users/boai/.rvm/gems/ruby-2.6.6/gems/cocoapods-1.10.1/lib/cocoapods/command/install.rb:52:in `run'
/Users/boai/.rvm/gems/ruby-2.6.6/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/boai/.rvm/gems/ruby-2.6.6/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/Users/boai/.rvm/gems/ruby-2.6.6/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/Users/boai/.rvm/gems/ruby-2.6.6/bin/pod:23:in `load'
/Users/boai/.rvm/gems/ruby-2.6.6/bin/pod:23:in `<main>'
/Users/boai/.rvm/gems/ruby-2.6.6/bin/ruby_executable_hooks:22:in `eval'
/Users/boai/.rvm/gems/ruby-2.6.6/bin/ruby_executable_hooks:22:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=undefined+method+%60children%27+for+%23%3CXcodeproj%3A%3AProject%3A%3AObject%3A%3APBXFileReference%3A0x00007f86b5383068%3E&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
 - Pod install fails after installing Xcode 7.0 Beta
   https://github.com/CocoaPods/CocoaPods/issues/3720 [closed] [26 comments]
   16 Dec 2020

 - NoMethodError - undefined method `real_path' for nil:NilClass
   https://github.com/CocoaPods/CocoaPods/issues/8126 [closed] [9 comments]
   06 Nov 2018

 - undefined method `name' for #<UUID: `15A87B67164165FB00BF3E4D', isa: `PBXReferenceProxy'>
   https://github.com/CocoaPods/CocoaPods/issues/626 [closed] [4 comments]
   04 Nov 2012

CocoaPods 1.9.3 update 1.10.1 error

**Comment by dnkoutso** [comment]
Can you please upload a sample app that demonstrates the issue?

**Comment by dnkoutso** [comment]
Closing due to inactivity.
