### ISSUE TITLE
[Xcodeproj] Unknown object version.  Help Please

### ISSUE THREAD

**Issue by Runnlin** [CocoaPods/CocoaPods#10604]
### Command

```
/Applications/CocoaPods.app/Contents/Resources/bundle/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.5.2
        Ruby : ruby 2.2.6p396 (2016-11-15 revision 56800) [x86_64-darwin15]
    RubyGems : 2.6.8
        Host : macOS 11.2.3 (20D91)
       Xcode : 12.4 (12D4e)
         Git : git version 2.6.2
Ruby lib dir : /Applications/CocoaPods.app/Contents/Resources/bundle/lib
Repositories : flowever-component-specs - http://git.flowever.net/component/Specs.git @ 527e5f41d0c071c858638167583dd5040e1b02ec
               master - https://github.com/CocoaPods/Specs.git @ 484f2f245c2dae8264e7dbb3671c68ac1188ef7b
```

### Plugins

```
cocoapods-check           : 1.0.0
cocoapods-deintegrate     : 1.0.2
cocoapods-plugins         : 1.0.0
cocoapods-plugins-install : 0.0.1
cocoapods-search          : 1.0.0
cocoapods-stats           : 1.0.0
cocoapods-trunk           : 1.3.0
cocoapods-try             : 1.1.0
```

### Podfile

```ruby
source 'http://git.flowever.net/component/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '12.0'
use_frameworks!


def marketing
    pod 'AdLib'
    pod 'MarketingHelper'

    pod 'UMCCommon'
    pod 'UMCPush'
end

target 'SuperCleaner' do
  pod 'SnapKit'
  pod 'Toolkit'
  pod 'CocoaAsyncSocket'
  pod 'SDWebImage'
  
  pod 'LookinServer', :configurations => ['Debug']
#  marketing
  
end
```

### Error

```
RuntimeError - [Xcodeproj] Unknown object version.
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.8/lib/xcodeproj/project.rb:218:in `initialize_from_file'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.8/lib/xcodeproj/project.rb:103:in `open'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/analyzer.rb:918:in `block (2 levels) in inspect_targets_to_integrate'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/analyzer.rb:917:in `each'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/analyzer.rb:917:in `block in inspect_targets_to_integrate'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/user_interface.rb:64:in `section'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/analyzer.rb:912:in `inspect_targets_to_integrate'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/analyzer.rb:78:in `analyze'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/installer.rb:243:in `analyze'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/installer.rb:154:in `block in resolve_dependencies'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/user_interface.rb:64:in `section'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/installer.rb:153:in `resolve_dependencies'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/installer.rb:116:in `install!'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/command/install.rb:41:in `run'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/command.rb:52:in `run'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/bin/pod:55:in `<top (required)>'
/Applications/CocoaPods.app/Contents/Resources/bundle/bin/pod:22:in `load'
/Applications/CocoaPods.app/Contents/Resources/bundle/bin/pod:22:in `<main>'
```

I had try all solution in issue with same question, but did't work..   Can anybody help?

**Comment by LoKiLyn** [comment]
Update cocoapod version solved my problem. plz have a try.

**Comment by ravindranpandu** [comment]
If your cocoapod is on latest version and you also did `gem update xcodeproj` and still face this issue, just uninstall and install the xcodeproj again and it will work like a charm, this is mainly due to permission issue from the gem level and this happens mostly after you upgrade your xcode or iOS sdk version.

`gem uninstall xcodeproj`
`gem install xcodeproj`

Hope this might save someone's day.

**Comment by vishalkalola1** [comment]
I have same error into macOS Monterey. Is there anyway to solve? I tried all command above one but not getting success. I get error when I init pod for my project.

**Comment by elemanhillary** [comment]
@vishalkalola1 change project format, had the issue but this worked as charm
<img width="254" alt="Screen Shot 2021-06-11 at 1 00 05 PM" src="https://user-images.githubusercontent.com/14273401/121669405-f3509280-cab4-11eb-8f5b-56067af1a91a.png">

**Comment by freak4pc** [comment]
> @vishalkalola1 change project format, had the issue but this worked as charm
> <img alt="Screen Shot 2021-06-11 at 1 00 05 PM" width="254" src="https://user-images.githubusercontent.com/14273401/121669405-f3509280-cab4-11eb-8f5b-56067af1a91a.png">

Thanks, this was it for me!

**Comment by bwake2012** [comment]
### Command

```
/Users/Bob/.rvm/rubies/ruby-3.0.1/bin/pod init
```

### Report

* What did you do?

I tried to pod init

* What did you expect to happen?

I thought I would get an empty pod file in the current format

* What happened instead?

I got the following error message above the markdown template

objc[31686]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libauthinstall.dylib (0x1fbf22c10) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1122f02b8). One of the two will be used. Which one is undefined.
objc[31686]: Class AMSupportURLSession is implemented in both /usr/lib/libauthinstall.dylib (0x1fbf22c60) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1122f0308). One of the two will be used. Which one is undefined.

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [arm64-darwin20]
    RubyGems : 3.2.15
        Host : macOS 11.4 (20F71)
       Xcode : 13.0 (13A5154h)
         Git : git version 2.30.1 (Apple Git-130)
Ruby lib dir : /Users/Bob/.rvm/rubies/ruby-3.0.1/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ 61aacf77cc2b92640bdac3eb04c8e53c7a179eae

               trunk - CDN - https://cdn.cocoapods.org/
               twilio - git - https://github.com/twilio/cocoapod-specs @ 9bf659ed7246ba34625b81754031fbd5ac20fe68

```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Error

```
RuntimeError - [Xcodeproj] Unknown object version.
/Users/Bob/.rvm/rubies/ruby-3.0.1/lib/ruby/gems/3.0.0/gems/xcodeproj-1.19.0/lib/xcodeproj/project.rb:227:in `initialize_from_file'
/Users/Bob/.rvm/rubies/ruby-3.0.1/lib/ruby/gems/3.0.0/gems/xcodeproj-1.19.0/lib/xcodeproj/project.rb:112:in `open'
/Users/Bob/.rvm/rubies/ruby-3.0.1/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/command/init.rb:41:in `validate!'
/Users/Bob/.rvm/rubies/ruby-3.0.1/lib/ruby/gems/3.0.0/gems/claide-1.0.3/lib/claide/command.rb:333:in `run'
/Users/Bob/.rvm/rubies/ruby-3.0.1/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/Users/Bob/.rvm/rubies/ruby-3.0.1/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/Users/Bob/.rvm/rubies/ruby-3.0.1/bin/pod:23:in `load'
/Users/Bob/.rvm/rubies/ruby-3.0.1/bin/pod:23:in `<main>'
/Users/Bob/.rvm/rubies/ruby-3.0.1/bin/ruby_executable_hooks:22:in `eval'
/Users/Bob/.rvm/rubies/ruby-3.0.1/bin/ruby_executable_hooks:22:in `<main>'
```

**Comment by dnkoutso** [comment]
use `gem update xcodeproj` and if you are on xcode 13 then follow this issue: https://github.com/CocoaPods/CocoaPods/issues/10713

**Comment by gupta163** [comment]
I am getting error
――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Applications/CocoaPods.app/Contents/Resources/bundle/bin/pod init
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.5.2
        Ruby : ruby 2.2.6p396 (2016-11-15 revision 56800) [x86_64-darwin15]
    RubyGems : 2.6.8
        Host : macOS 12.4 (21F79)
       Xcode : 13.4.1 (13F100)
         Git : git version 2.6.2
Ruby lib dir : /Applications/CocoaPods.app/Contents/Resources/bundle/lib
Repositories : 
```

### Plugins

```
cocoapods-check           : 1.0.0
cocoapods-deintegrate     : 1.0.2
cocoapods-plugins         : 1.0.0
cocoapods-plugins-install : 0.0.1
cocoapods-search          : 1.0.0
cocoapods-stats           : 1.0.0
cocoapods-trunk           : 1.3.0
cocoapods-try             : 1.1.0
```

### Error

```
RuntimeError - [Xcodeproj] Unknown object version.
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.8/lib/xcodeproj/project.rb:218:in `initialize_from_file'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.8/lib/xcodeproj/project.rb:103:in `open'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/command/init.rb:41:in `validate!'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/claide-1.0.2/lib/claide/command.rb:333:in `run'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/command.rb:52:in `run'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/bin/pod:55:in `<top (required)>'
/Applications/CocoaPods.app/Contents/Resources/bundle/bin/pod:22:in `load'
/Applications/CocoaPods.app/Contents/Resources/bundle/bin/pod:22:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=%5BXcodeproj%5D+Unknown+object+version.&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
 - RuntimeError - [Xcodeproj] Unknown object version.
   https://github.com/CocoaPods/CocoaPods/issues/7458 [closed] [24 comments]
   25 Jun 2022

 - An error occurred when executing pod init
   https://github.com/CocoaPods/CocoaPods/issues/11434 [closed] [2 comments]
   3 days ago

 - CMake generated project is unable to find Pods framework during linkage
   https://github.com/CocoaPods/CocoaPods/issues/10676 [open] [23 comments]
   25 Jan 2022

and 77 more at:
https://github.com/cocoapods/cocoapods/search?q=%5BXcodeproj%5D%20Unknown%20object%20version.&type=Issues&utf8=✓
