### ISSUE TITLE
Searching for inspections failed: undefined method `map' for nil:NilClass - while installing react-native-maps

### ISSUE THREAD

**Issue by aghiad-90** [CocoaPods/CocoaPods#10648]
I am trying to install react-native-maps on ios , I follow the instructions and here the steps that I follow:

1- yarn add react-native-maps -E
2- pod install (all fine )
3- insert these two lines in podfile  as per the documentation : 
   `rn_maps_path = '../node_modules/react-native-maps'`
   `pod 'react-native-google-maps', :path => rn_maps_path`

4- when I ran pod install I got the following error: 
`  at Object.spawnAsync [as default] (/Users/aghiadmonier/.npm/_npx/7cf525d1e16b4e35/node_modules/pod-install/build/index.js:2:558)
      at CocoaPodsPackageManager._runAsync (/Users/aghiadmonier/.npm/_npx/7cf525d1e16b4e35/node_modules/pod-install/build/index.js:2:92928)
      at CocoaPodsPackageManager._installAsync (/Users/aghiadmonier/.npm/_npx/7cf525d1e16b4e35/node_modules/pod-install/build/index.js:2:90432)
      at CocoaPodsPackageManager.installAsync (/Users/aghiadmonier/.npm/_npx/7cf525d1e16b4e35/node_modules/pod-install/build/index.js:2:90120)
      at runAsync (/Users/aghiadmonier/.npm/_npx/7cf525d1e16b4e35/node_modules/pod-install/build/index.js:2:106090)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async /Users/aghiadmonier/.npm/_npx/7cf525d1e16b4e35/node_modules/pod-install/build/index.js:2:106168 {
    pid: 31054,
    output: [
      '',
      "Searching for inspections failed: undefined method `map' for nil:NilClass\n"
    ],
    stdout: '',
    stderr: "Searching for inspections failed: undefined method `map' for nil:NilClass\n",
    status: 1,
    signal: null
  },
  isPackageManagerError: true`

## CocoaPods Environment

cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0

I am using macbook air 2020 (M1 Chip), 

please  any idea why this is happen and who to solve this issue !

**Comment by dnkoutso** [comment]
Please file issue with react-native or re-open a new issue here _without_ ReactNative in your project to demonstrate the issue with a sample app.
