### ISSUE TITLE
deadlock; recursive locking (ThreadError)

### ISSUE THREAD

**Issue by psrcek** [CocoaPods/CocoaPods#10653]
* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Any pod command e.g. `pod install` or `pod update`

## What did you expect to happen?

I just wanted to run pod commands.

## What happened instead?

```
$ pod install                      
Resolving dependencies...
Traceback (most recent call last):
	12: from /Users/buildmachine/.rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:22:in `<main>'
	11: from /Users/buildmachine/.rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:22:in `eval'
	10: from /Users/buildmachine/.rvm/gems/ruby-2.7.2/bin/pod:23:in `<main>'
	 9: from /Users/buildmachine/.rvm/rubies/ruby-2.7.2/lib/ruby/site_ruby/2.7.0/rubygems.rb:304:in `activate_bin_path'
	 8: from /Users/buildmachine/.rvm/rubies/ruby-2.7.2/lib/ruby/site_ruby/2.7.0/rubygems.rb:304:in `synchronize'
	 7: from /Users/buildmachine/.rvm/rubies/ruby-2.7.2/lib/ruby/site_ruby/2.7.0/rubygems.rb:306:in `block in activate_bin_path'
	 6: from /Users/buildmachine/.rvm/rubies/ruby-2.7.2/lib/ruby/site_ruby/2.7.0/rubygems.rb:243:in `finish_resolve'
	 5: from /Users/buildmachine/.rvm/rubies/ruby-2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/request_set.rb:435:in `resolve_current'
	 4: from /Users/buildmachine/.rvm/rubies/ruby-2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/request_set.rb:435:in `new'
	 3: from /Users/buildmachine/.rvm/rubies/ruby-2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/resolver/set.rb:24:in `initialize'
	 2: from /Users/buildmachine/.rvm/rubies/ruby-2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:42:in `require'
	 1: from /Users/buildmachine/.rvm/rubies/ruby-2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_gem.rb:67:in `gem'
/Users/buildmachine/.rvm/rubies/ruby-2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_gem.rb:67:in `synchronize': deadlock; recursive locking (ThreadError)
```

## CocoaPods Environment

```
$ pod env
Resolving dependencies...
Traceback (most recent call last):
	12: from /Users/buildmachine/.rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:22:in `<main>'
	11: from /Users/buildmachine/.rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:22:in `eval'
	10: from /Users/buildmachine/.rvm/gems/ruby-2.7.2/bin/pod:23:in `<main>'
	 9: from /Users/buildmachine/.rvm/rubies/ruby-2.7.2/lib/ruby/site_ruby/2.7.0/rubygems.rb:304:in `activate_bin_path'
	 8: from /Users/buildmachine/.rvm/rubies/ruby-2.7.2/lib/ruby/site_ruby/2.7.0/rubygems.rb:304:in `synchronize'
	 7: from /Users/buildmachine/.rvm/rubies/ruby-2.7.2/lib/ruby/site_ruby/2.7.0/rubygems.rb:306:in `block in activate_bin_path'
	 6: from /Users/buildmachine/.rvm/rubies/ruby-2.7.2/lib/ruby/site_ruby/2.7.0/rubygems.rb:243:in `finish_resolve'
	 5: from /Users/buildmachine/.rvm/rubies/ruby-2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/request_set.rb:435:in `resolve_current'
	 4: from /Users/buildmachine/.rvm/rubies/ruby-2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/request_set.rb:435:in `new'
	 3: from /Users/buildmachine/.rvm/rubies/ruby-2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/resolver/set.rb:24:in `initialize'
	 2: from /Users/buildmachine/.rvm/rubies/ruby-2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:42:in `require'
	 1: from /Users/buildmachine/.rvm/rubies/ruby-2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_gem.rb:67:in `gem'
/Users/buildmachine/.rvm/rubies/ruby-2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_gem.rb:67:in `synchronize': deadlock; recursive locking (ThreadError)
```

**Comment by psrcek** [comment]
Solved by downgrading to ruby 2.7.0 with rvm and reinstalling cocoapods.
