### ISSUE TITLE
LoadError - cannot load such file -- rexml/document even after installing rexml gem

### ISSUE THREAD

**Issue by raf-wtag** [CocoaPods/CocoaPods#10686]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Want to install pods in Xcode project. So I run `pod init` then added the pod list in the Podfile and run `pod install`

## What did you expect to happen?

The libraries are installed in project.

## What happened instead?

It gives **`LoadError - cannot load such file -- rexml/document`**. I've followed [this issue](https://github.com/CocoaPods/CocoaPods/issues/10388). Then after running ->

`gem 'rexml', '~> 3.2.4'`
It gives -
```
ERROR:  While executing gem ... (Gem::CommandLineError)
    Unknown command rexml,
```
Then I run -
`gem install rexml`
and I got -
```
Fetching rexml-3.2.5.gem
Successfully installed rexml-3.2.5
Parsing documentation for rexml-3.2.5
Installing ri documentation for rexml-3.2.5
Done installing documentation for rexml after 2 seconds
1 gem installed
```
But same error appears.

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin19]
    RubyGems : 3.2.3
        Host : Mac OS X 10.15.7 (19H1217)
       Xcode : 12.4 (12D4e)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /Users/fahimrahman/.rvm/rubies/ruby-3.0.0/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ 5e7f29abf5bafede7297dd40f8f060447b8eb9ea

```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-keys        : 2.2.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
platform :ios, '11.1'
inhibit_all_warnings!

target 'MyProject' do
  
  pod 'IQKeyboardManagerSwift'
  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
end
```

### Error

```
LoadError - cannot load such file -- rexml/document
/Users/fahimrahman/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/CFPropertyList-3.0.3/lib/cfpropertylist/rbREXMLParser.rb:3:in `require'
/Users/fahimrahman/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/CFPropertyList-3.0.3/lib/cfpropertylist/rbREXMLParser.rb:3:in `<top (required)>'
/Users/fahimrahman/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/CFPropertyList-3.0.3/lib/cfpropertylist/rbCFPropertyList.rb:96:in `require'
/Users/fahimrahman/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/CFPropertyList-3.0.3/lib/cfpropertylist/rbCFPropertyList.rb:96:in `rescue in <top (required)>'
/Users/fahimrahman/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/CFPropertyList-3.0.3/lib/cfpropertylist/rbCFPropertyList.rb:92:in `<top (required)>'
/Users/fahimrahman/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/CFPropertyList-3.0.3/lib/cfpropertylist.rb:3:in `require'
/Users/fahimrahman/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/CFPropertyList-3.0.3/lib/cfpropertylist.rb:3:in `<top (required)>'
/Users/fahimrahman/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/xcodeproj-1.19.0/lib/xcodeproj/plist.rb:25:in `require'
/Users/fahimrahman/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/xcodeproj-1.19.0/lib/xcodeproj/plist.rb:25:in `read_from_path'
/Users/fahimrahman/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/xcode/xcframework.rb:36:in `initialize'
/Users/fahimrahman/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/target/build_settings.rb:508:in `new'
/Users/fahimrahman/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/target/build_settings.rb:508:in `load_xcframework'
/Users/fahimrahman/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/target/build_settings.rb:724:in `block (2 levels) in <class:PodTargetSettings>'
/Users/fahimrahman/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/target/build_settings.rb:724:in `map'
/Users/fahimrahman/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/target/build_settings.rb:724:in `block in <class:PodTargetSettings>'
/Users/fahimrahman/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/target/build_settings.rb:120:in `block in define_build_settings_method'
/Users/fahimrahman/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/target/build_settings.rb:646:in `block in <class:PodTargetSettings>'
/Users/fahimrahman/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/target/build_settings.rb:120:in `block in define_build_settings_method'
/Users/fahimrahman/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/target/build_settings.rb:621:in `block (2 levels) in <class:PodTargetSettings>'
/Users/fahimrahman/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/target/build_settings.rb:621:in `each'
/Users/fahimrahman/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/target/build_settings.rb:621:in `flat_map'
/Users/fahimrahman/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/target/build_settings.rb:621:in `block in <class:PodTargetSettings>'
/Users/fahimrahman/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/target/build_settings.rb:120:in `block in define_build_settings_method'
/Users/fahimrahman/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/target/build_settings.rb:257:in `block in <class:BuildSettings>'
/Users/fahimrahman/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/target/build_settings.rb:676:in `block in <class:PodTargetSettings>'
/Users/fahimrahman/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/target/build_settings.rb:120:in `block in define_build_settings_method'
/Users/fahimrahman/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/target/build_settings.rb:387:in `public_send'
/Users/fahimrahman/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/target/build_settings.rb:387:in `block in to_h'
/Users/fahimrahman/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/target/build_settings.rb:386:in `each'
/Users/fahimrahman/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/target/build_settings.rb:386:in `to_h'
/Users/fahimrahman/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/target/build_settings.rb:188:in `block in <class:BuildSettings>'
/Users/fahimrahman/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/target/build_settings.rb:577:in `block in <class:PodTargetSettings>'
/Users/fahimrahman/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/target/build_settings.rb:120:in `block in define_build_settings_method'
/Users/fahimrahman/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/target/build_settings.rb:204:in `save_as'
/Users/fahimrahman/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/xcode/pods_project_generator/target_installer_helper.rb:24:in `update_changed_file'
/Users/fahimrahman/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:624:in `block in create_xcconfig_file'
/Users/fahimrahman/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:622:in `each'
/Users/fahimrahman/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:622:in `create_xcconfig_file'
/Users/fahimrahman/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:53:in `block in install!'
/Users/fahimrahman/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:145:in `message'
/Users/fahimrahman/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:40:in `install!'
/Users/fahimrahman/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:115:in `block in install_pod_targets'
/Users/fahimrahman/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:112:in `map'
/Users/fahimrahman/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:112:in `install_pod_targets'
/Users/fahimrahman/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/xcode/single_pods_project_generator.rb:32:in `block in install_all_pod_targets'
/Users/fahimrahman/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:145:in `message'
/Users/fahimrahman/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/xcode/single_pods_project_generator.rb:31:in `install_all_pod_targets'
/Users/fahimrahman/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/xcode/single_pods_project_generator.rb:19:in `generate!'
/Users/fahimrahman/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:312:in `block in create_and_save_projects'
/Users/fahimrahman/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/fahimrahman/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:307:in `create_and_save_projects'
/Users/fahimrahman/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:299:in `generate_pods_project'
/Users/fahimrahman/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:178:in `integrate'
/Users/fahimrahman/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:166:in `install!'
/Users/fahimrahman/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/command/install.rb:52:in `run'
/Users/fahimrahman/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/fahimrahman/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/Users/fahimrahman/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/Users/fahimrahman/.rvm/rubies/ruby-3.0.0/bin/pod:23:in `load'
/Users/fahimrahman/.rvm/rubies/ruby-3.0.0/bin/pod:23:in `<main>'
/Users/fahimrahman/.rvm/gems/ruby-3.0.0/bin/ruby_executable_hooks:22:in `eval'
/Users/fahimrahman/.rvm/gems/ruby-3.0.0/bin/ruby_executable_hooks:22:in `<main>'
```

**Comment by raf-wtag** [comment]
issue #10388 is described the solution of this problem. @Author you can delete this issue. Its may be a redundant one.

**Comment by godlikejoke** [comment]
where i run: gem install rexml

`ERROR:  Loading command: install (LoadError)
	dlopen(/Users/xianghuawei/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/x86_64-darwin15/openssl.bundle, 9): Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /Users/xianghuawei/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/x86_64-darwin15/openssl.bundle
  Reason: image not found - /Users/xianghuawei/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/x86_64-darwin15/openssl.bundle
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass`

**Comment by raf-wtag** [comment]
I think if you update your ruby version then it will not cause Error

**Comment by godlikejoke** [comment]
There is a problem with my openssl, just reinstall it。Thank！
