### ISSUE TITLE
Xcode-beta 13.0 can't init project

### ISSUE THREAD

**Issue by lizhaobomb** [CocoaPods/CocoaPods#10713]
### Command

```
/usr/local/bin/pod init
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
    RubyGems : 3.0.3
        Host : macOS 11.4 (20F71)
       Xcode : 13.0 (13A5154h)
         Git : git version 2.30.1 (Apple Git-130)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ fcfffe741bb15fbbd923008ba33fe07c6bc33dc4

               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Error

```
RuntimeError - [Xcodeproj] Unknown object version.
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.19.0/lib/xcodeproj/project.rb:227:in `initialize_from_file'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.19.0/lib/xcodeproj/project.rb:112:in `open'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command/init.rb:41:in `validate!'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:333:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by brandonplank** [comment]
same

**Comment by hillis** [comment]
Same on Intel Macbook Pro 13"

**Comment by yasaemre** [comment]
same any solution for it ?

**Comment by kyaw-codes** [comment]
Same here.

**Comment by SMH-7** [comment]
Same :(

**Comment by LeonardoXUI** [comment]
Same here.

**Comment by AndrewUshakov000** [comment]
Same problem (

**Comment by itsLollo1000** [comment]
I was able to init my project after I changed the Project Format to Xcode 12.0-compatible.
Hope this helps.

<img width="252" alt="Bildschirmfoto 2021-06-21 um 17 48 46" src="https://user-images.githubusercontent.com/10349466/122790826-fa4b8200-d2b8-11eb-9657-8f39c11da258.png">

**Comment by dnkoutso** [comment]
Yes this is confirmed. I will keep this as the primary issue and close remaining issues as duplicates and link to this.

**Comment by dnkoutso** [comment]
Fixed by https://github.com/CocoaPods/Xcodeproj/pull/825

**Comment by leftskidlow** [comment]
Same error now on 13.5 beta

**Comment by herbertvuijk** [comment]
Please tell me how to do this, a screenshot doesnt help, can't find where to change is...
