### ISSUE TITLE
Pod Install command not working when installing React native maps for Google

### ISSUE THREAD

**Issue by Irongade** [CocoaPods/CocoaPods#10720]
――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
    RubyGems : 3.0.3
        Host : macOS 11.1 (20C69)
       Xcode : 12.5 (12E262)
         Git : git version 2.23.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'FastMoversHaulageDriversApp' do
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'FastMoversHaulageDriversAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end
end
```

### Error

```
JSON::ParserError - 416: unexpected token at '{
      "name": "M4B'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-core-1.10.1/lib/cocoapods-core/specification/json.rb:61:in `from_json'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-core-1.10.1/lib/cocoapods-core/specification.rb:742:in `from_string'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-core-1.10.1/lib/cocoapods-core/specification.rb:716:in `from_file'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-core-1.10.1/lib/cocoapods-core/source.rb:186:in `specification'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/resolver/lazy_specification.rb:37:in `specification'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:348:in `block in delegating_block'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:349:in `block in delegating_block'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:178:in `dependencies_for'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:18:in `block in dependencies_for'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:70:in `with_no_such_dependency_error_handling'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:17:in `dependencies_for'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:807:in `block in group_possibilities'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:806:in `reverse_each'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:806:in `group_possibilities'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:778:in `possibilities_for_requirement'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:761:in `push_state_for_requirements'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:746:in `require_nested_dependencies_for'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:729:in `activate_new_spec'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:686:in `attempt_to_activate'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:254:in `process_topmost_state'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:94:in `resolve'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:1074:in `block in resolve_dependencies'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:1072:in `resolve_dependencies'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:414:in `analyze'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:239:in `block in resolve_dependencies'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:238:in `resolve_dependencies'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:160:in `install!'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/command/install.rb:52:in `run'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/bin/pod:23:in `load'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/bin/pod:23:in `<main>'
```

# Report

## What did you do?
I tried to install dependencies for using google maps on ios

ℹ Please replace these two lines with what you did.  
Run `pod install` after following appropriate steps

## What did you expect to happen?
ℹ e.g. Install all pod dependencies correctly.

## What happened instead?

ℹ Please replace these two lines with of what happened instead.  
Look at the error message displayed above

Welp!

**Comment by AndreCosta101** [comment]
Any luck with that? Same issue here...

**Comment by Irongade** [comment]
> Any luck with that? Same issue here...

None! I tried severally, but for some reason it fails every time i try to install the pods, I think it might have something to do with the node module path for the react native map package. Its a huge bug and I dont understand why many people aren't experiencing this. 

For now, I have stuck to using Apple's default map for my project.

**Comment by AndreCosta101** [comment]
Just got lucky with:

`sudo gem install -n /usr/local/bin cocoapods`

and then 

`pod install`

 within project/ios folder.

You might give it a shot.

**Comment by Irongade** [comment]
Hello @AndreCosta101 , 

It didnt work for me, can you shed more light into how you set the installation up for your project.

**Comment by dnkoutso** [comment]
Can you try `rm -rf ~/.cocoapods/repos` and `pod install` again? This used to be an old issue regarding CDN. Also use `pod cache clean --all`.

**Comment by Irongade** [comment]
@dnkoutso Hey, Thanks! this fixed the issue for me. Please kindly explain your earlier reply in more detail so myself and everyone else can fully understand what the problem was, Also thanks to @AndreCosta101 for your input on this issue. Cheers.

**Comment by dnkoutso** [comment]
its probably a bad version of a podspec that was stored once in your repos. Cocoapods would re-use it and fail to parse it.

removing the repo forced cocoapods to redownload the json podspec correctly this time around. we have fixed various issues around this but you were probably in a stale version.
