### ISSUE TITLE
Pod install - Compilation error generating constants

### ISSUE THREAD

**Issue by Gabsys** [CocoaPods/CocoaPods#10754]
# Report

## What did you do?
Ran pod install

## What did you expect to happen?
 Install all pod dependencies correctly.

## What happened instead?
Showing long list of errors

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.7 (19H524)
       Xcode : 12.4 (12D4e)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ a884445ccab796a0d0f41219d32691db10f7c77b

               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/Cellar/cocoapods/1.10.1_1/libexec/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'JHood' do
  # React Native Maps dependencies
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'JHoodTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end
end
```

### Error
```
RuntimeError - Compilation error generating constants :
	In file included from /var/folders/wh/dtc169_91t36bj8395_9zwkh0000gn/T/.const_generator20210704-48426-k682g9:1:
	In file included from /usr/local/include/stdio.h:64:
	/usr/local/include/_stdio.h:93:16: error: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Werror,-Wnullability-completeness]
	        unsigned char   *_base;
	                        ^
	/usr/local/include/_stdio.h:93:16: note: insert '_Nullable' if the pointer may be null
	        unsigned char   *_base;
	                        ^
	                          _Nullable 
	/usr/local/include/_stdio.h:93:16: note: insert '_Nonnull' if the pointer should never be null
	        unsigned char   *_base;
	                        ^
	                          _Nonnull 
	/usr/local/include/_stdio.h:138:32: error: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Werror,-Wnullability-completeness]
	        int     (* _Nullable _read) (void *, char *, int);
	                                          ^
	/usr/local/include/_stdio.h:138:32: note: insert '_Nullable' if the pointer may be null
	        int     (* _Nullable _read) (void *, char *, int);
	                                          ^
	                                           _Nullable
	/usr/local/include/_stdio.h:138:32: note: insert '_Nonnull' if the pointer should never be null
	        int     (* _Nullable _read) (void *, char *, int);
	                                          ^
	                                           _Nonnull
	/usr/local/include/_stdio.h:138:40: error: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Werror,-Wnullability-completeness]
	        int     (* _Nullable _read) (void *, char *, int);
	                                                  ^
	/usr/local/include/_stdio.h:138:40: note: insert '_Nullable' if the pointer may be null
	        int     (* _Nullable _read) (void *, char *, int);
	                                                  ^
	                                                   _Nullable
	/usr/local/include/_stdio.h:138:40: note: insert '_Nonnull' if the pointer should never be null
	        int     (* _Nullable _read) (void *, char *, int);
	                                                  ^
	                                                   _Nonnull
	/usr/local/include/_stdio.h:139:35: error: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Werror,-Wnullability-completeness]
	        fpos_t  (* _Nullable _seek) (void *, fpos_t, int);
	                                          ^
	/usr/local/include/_stdio.h:139:35: note: insert '_Nullable' if the pointer may be null
	        fpos_t  (* _Nullable _seek) (void *, fpos_t, int);
	                                          ^
	                                           _Nullable
	/usr/local/include/_stdio.h:139:35: note: insert '_Nonnull' if the pointer should never be null
	        fpos_t  (* _Nullable _seek) (void *, fpos_t, int);
	                                          ^
	                                           _Nonnull
	/usr/local/include/_stdio.h:140:32: error: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Werror,-Wnullability-completeness]
	        int     (* _Nullable _write)(void *, const char *, int);
	                                          ^
	/usr/local/include/_stdio.h:140:32: note: insert '_Nullable' if the pointer may be null
	        int     (* _Nullable _write)(void *, const char *, int);
	                                          ^
	                                           _Nullable
	/usr/local/include/_stdio.h:140:32: note: insert '_Nonnull' if the pointer should never be null
	        int     (* _Nullable _write)(void *, const char *, int);
	                                          ^
	                                           _Nonnull
	/usr/local/include/_stdio.h:140:46: error: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Werror,-Wnullability-completeness]
	        int     (* _Nullable _write)(void *, const char *, int);
	                                                        ^
	/usr/local/include/_stdio.h:140:46: note: insert '_Nullable' if the pointer may be null
	        int     (* _Nullable _write)(void *, const char *, int);
	                                                        ^
	                                                         _Nullable
	/usr/local/include/_stdio.h:140:46: note: insert '_Nonnull' if the pointer should never be null
	        int     (* _Nullable _write)(void *, const char *, int);
	                                                        ^
	                                                         _Nonnull
	/usr/local/include/_stdio.h:144:18: error: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Werror,-Wnullability-completeness]
	        struct __sFILEX *_extra; /* additions to FILE to not break ABI */
	                        ^
	/usr/local/include/_stdio.h:144:18: note: insert '_Nullable' if the pointer may be null
	        struct __sFILEX *_extra; /* additions to FILE to not break ABI */
	                        ^
	                          _Nullable 
	/usr/local/include/_stdio.h:144:18: note: insert '_Nonnull' if the pointer should never be null
	        struct __sFILEX *_extra; /* additions to FILE to not break ABI */
	                        ^
	                          _Nonnull 
	In file included from /var/folders/wh/dtc169_91t36bj8395_9zwkh0000gn/T/.const_generator20210704-48426-k682g9:1:
	/usr/local/include/stdio.h:67:13: error: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Werror,-Wnullability-completeness]
	extern FILE *__stdinp;
	            ^
	/usr/local/include/stdio.h:67:13: note: insert '_Nullable' if the pointer may be null
	extern FILE *__stdinp;
	            ^
	              _Nullable 
	/usr/local/include/stdio.h:67:13: note: insert '_Nonnull' if the pointer should never be null
	extern FILE *__stdinp;
	            ^
	              _Nonnull 
	/usr/local/include/stdio.h:386:41: error: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Werror,-Wnullability-completeness]
	                 int (* _Nullable)(void *, const char *, int),
	                                        ^
	/usr/local/include/stdio.h:386:41: note: insert '_Nullable' if the pointer may be null
	                 int (* _Nullable)(void *, const char *, int),
	                                        ^
	                                         _Nullable
	/usr/local/include/stdio.h:386:41: note: insert '_Nonnull' if the pointer should never be null
	                 int (* _Nullable)(void *, const char *, int),
	                                        ^
	                                         _Nonnull
	/usr/local/include/stdio.h:386:55: error: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Werror,-Wnullability-completeness]
	                 int (* _Nullable)(void *, const char *, int),
	                                                      ^
	/usr/local/include/stdio.h:386:55: note: insert '_Nullable' if the pointer may be null
	                 int (* _Nullable)(void *, const char *, int),
	                                                      ^
	                                                       _Nullable
	/usr/local/include/stdio.h:386:55: note: insert '_Nonnull' if the pointer should never be null
	                 int (* _Nullable)(void *, const char *, int),
	                                                      ^
	                                                       _Nonnull
	/usr/local/include/stdio.h:387:44: error: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Werror,-Wnullability-completeness]
	                 fpos_t (* _Nullable)(void *, fpos_t, int),
	                                           ^
	/usr/local/include/stdio.h:387:44: note: insert '_Nullable' if the pointer may be null
	                 fpos_t (* _Nullable)(void *, fpos_t, int),
	                                           ^
	                                            _Nullable
	/usr/local/include/stdio.h:387:44: note: insert '_Nonnull' if the pointer should never be null
	                 fpos_t (* _Nullable)(void *, fpos_t, int),
	                                           ^
	                                            _Nonnull
	/usr/local/include/stdio.h:388:41: error: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Werror,-Wnullability-completeness]
	                 int (* _Nullable)(void *));
	                                        ^
	/usr/local/include/stdio.h:388:41: note: insert '_Nullable' if the pointer may be null
	                 int (* _Nullable)(void *));
	                                        ^
	                                         _Nullable
	/usr/local/include/stdio.h:388:41: note: insert '_Nonnull' if the pointer should never be null
	                 int (* _Nullable)(void *));
	                                        ^
	                                         _Nonnull
	/usr/local/include/stdio.h:384:6: error: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Werror,-Wnullability-completeness]
	FILE    *funopen(const void *,
	        ^
	/usr/local/include/stdio.h:384:6: note: insert '_Nullable' if the pointer may be null
	FILE    *funopen(const void *,
	        ^
	          _Nullable 
	/usr/local/include/stdio.h:384:6: note: insert '_Nonnull' if the pointer should never be null
	FILE    *funopen(const void *,
	        ^
	          _Nonnull 
	13 errors generated.
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/ffi-1.15.0/lib/ffi/tools/const_generator.rb:131:in `block in calculate'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tempfile.rb:295:in `open'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/ffi-1.15.0/lib/ffi/tools/const_generator.rb:110:in `calculate'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/ffi-1.15.0/lib/ffi/tools/const_generator.rb:49:in `initialize'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/ethon-0.13.0/lib/ethon/libc.rb:17:in `new'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/ethon-0.13.0/lib/ethon/libc.rb:17:in `<module:Libc>'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/ethon-0.13.0/lib/ethon/libc.rb:7:in `<module:Ethon>'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/ethon-0.13.0/lib/ethon/libc.rb:2:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/ethon-0.13.0/lib/ethon.rb:16:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:440:in `download_typhoeus_impl_async'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:372:in `download_and_save_with_retries_async'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:365:in `download_file_async'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:131:in `block (2 levels) in versions'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:124:in `map'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:124:in `block in versions'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:479:in `concurrent_requests_catching_errors'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:121:in `versions'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-core-1.10.1/lib/cocoapods-core/specification/set.rb:99:in `block in versions_by_source'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-core-1.10.1/lib/cocoapods-core/specification/set.rb:98:in `each'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-core-1.10.1/lib/cocoapods-core/specification/set.rb:98:in `each_with_object'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-core-1.10.1/lib/cocoapods-core/specification/set.rb:98:in `versions_by_source'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-core-1.10.1/lib/cocoapods-core/specification/set.rb:56:in `specification_name'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:216:in `search'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-core-1.10.1/lib/cocoapods-core/source/aggregate.rb:83:in `block in search'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-core-1.10.1/lib/cocoapods-core/source/aggregate.rb:83:in `select'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-core-1.10.1/lib/cocoapods-core/source/aggregate.rb:83:in `search'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:416:in `create_set_from_sources'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:385:in `find_cached_set'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:360:in `specifications_for_dependency'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:165:in `search_for'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:274:in `block in sort_dependencies'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:267:in `each'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:267:in `sort_by'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:267:in `sort_dependencies'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:53:in `block in sort_dependencies'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:70:in `with_no_such_dependency_error_handling'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:52:in `sort_dependencies'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:754:in `push_state_for_requirements'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:746:in `require_nested_dependencies_for'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:729:in `activate_new_spec'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:686:in `attempt_to_activate'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:254:in `process_topmost_state'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:94:in `resolve'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:1074:in `block in resolve_dependencies'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:1072:in `resolve_dependencies'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:414:in `analyze'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:239:in `block in resolve_dependencies'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:238:in `resolve_dependencies'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:160:in `install!'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/bin/pod:23:in `load'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

**Comment by Gabsys** [comment]
Solved after running `sudo gem install -n /usr/local/bin cocoapods`
Not sure why I still need to install cocoapods with gem if I have already installed it with Homebrew O.O
