### ISSUE TITLE
"Multiple commands produce" error in "[CP] Copy XCFrameworks" phase

### ISSUE THREAD

**Issue by hatsunem** [CocoaPods/CocoaPods#10777]
🌈

* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I installed the same pod to a target with platform iOS9.0 and another target with platform iOS10.0
```ruby
use_frameworks! :linkage => :static

target :SampleA do
  platform :ios, '10.0'
  pod 'Google-Mobile-Ads-SDK', '8.6.0'
end

target :SampleB do
  platform :ios, '9.0'
  pod 'Google-Mobile-Ads-SDK', '8.6.0'
end
```

## What did you expect to happen?

Pod creates `Google-Mobile-Ads-SDK-iOS9.0` and `Google-Mobile-Ads-SDK-iOS10.0` targets on the Pods project.
`Google-Mobile-Ads-SDK` depends on other libraries, then some targets like `GoogleAppMeasurement-iOS9.0` and `GoogleAppMeasurement-iOS10.0` are created too.

I expect `Google-Mobile-Ads-SDK-iOS9.0` has `GoogleAppMeasurement-iOS9.0` in Dependencies in Build Phases and `Google-Mobile-Ads-SDK-iOS10.0` has `GoogleAppMeasurement-iOS10.0` as well.

## What happened instead?

`Google-Mobile-Ads-SDK-iOS10.0` depends on  `GoogleAppMeasurement-iOS10.0`  correctly, 
but `Google-Mobile-Ads-SDK-iOS9.0` depends on `GoogleAppMeasurement-iOS10.0` too!

Probably because of that, building SampleB causes duplicate errors below.

```
❌ error: Multiple commands produce '/Users/hatsunem/Library/Developer/Xcode/DerivedData/Sample-gvfrkczkljetzrdiccgypeeeidly/Build/Intermediates.noindex/ArchiveIntermediates/SampleB/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/GoogleAppMeasurement':

duplicate output file '/Users/hatsunem/Library/Developer/Xcode/DerivedData/Sample-gvfrkczkljetzrdiccgypeeeidly/Build/Intermediates.noindex/ArchiveIntermediates/SampleB/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/GoogleAppMeasurement' on task: PhaseScriptExecution [CP] Copy XCFrameworks /Users/hatsunem/Library/Developer/Xcode/DerivedData/Sample-gvfrkczkljetzrdiccgypeeeidly/Build/Intermediates.noindex/ArchiveIntermediates/SampleB/IntermediateBuildFilesPath/AdMobMediationAdapter/Pods.build/Release-iphoneos/GoogleAppMeasurement-iOS9.0.build/Script-E27CC066ED893A90CC446DEDA9D33D09.sh (in target 'GoogleAppMeasurement-iOS9.0' from project 'Pods')
```

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
    RubyGems : 3.0.3
        Host : macOS 11.4 (20F71)
       Xcode : 12.5.1 (12E507)
         Git : git version 2.30.2
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

## Project that demonstrates the issue

I created a new project for verification and the same problem happened.
https://github.com/hatsunem/Pod-Sample

**Comment by dnkoutso** [comment]
thanks for the great issue report, will have to investigate.

**Comment by dnkoutso** [comment]
yes this is clearly a bug. The dependencies list included here seem wrong.

**Comment by dnkoutso** [comment]
@hatsunem fixed here https://github.com/CocoaPods/CocoaPods/pull/10794, verified in your sample app that I can compile successfully! Thank you so much for the report.

**Comment by hatsunem** [comment]
The master branch doesn't work and I got an error below.

```
% bundle exec pod install
Analyzing dependencies
Downloading dependencies
[!] An error occurred while processing the pre-integrate hook of the Podfile.

undefined method `pre_integrate!' for #<Pod::Podfile:0x00007fc446e607a0>
Did you mean?  post_integrate!
               post_integrate

/Users/h-mineta/Documents/Sample/vendor/bundle/ruby/2.6.0/bundler/gems/CocoaPods-804eed538505/lib/cocoapods/installer.rb:917:in `run_podfile_pre_integrate_hook'
/Users/h-mineta/Documents/Sample/vendor/bundle/ruby/2.6.0/bundler/gems/CocoaPods-804eed538505/lib/cocoapods/installer.rb:905:in `block in run_podfile_pre_integrate_hooks'
/Users/h-mineta/Documents/Sample/vendor/bundle/ruby/2.6.0/bundler/gems/CocoaPods-804eed538505/lib/cocoapods/user_interface.rb:149:in `message'
/Users/h-mineta/Documents/Sample/vendor/bundle/ruby/2.6.0/bundler/gems/CocoaPods-804eed538505/lib/cocoapods/installer.rb:904:in `run_podfile_pre_integrate_hooks'
/Users/h-mineta/Documents/Sample/vendor/bundle/ruby/2.6.0/bundler/gems/CocoaPods-804eed538505/lib/cocoapods/installer.rb:179:in `integrate'
/Users/h-mineta/Documents/Sample/vendor/bundle/ruby/2.6.0/bundler/gems/CocoaPods-804eed538505/lib/cocoapods/installer.rb:167:in `install!'
/Users/h-mineta/Documents/Sample/vendor/bundle/ruby/2.6.0/bundler/gems/CocoaPods-804eed538505/lib/cocoapods/command/install.rb:52:in `run'
/Users/h-mineta/Documents/Sample/vendor/bundle/ruby/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/h-mineta/Documents/Sample/vendor/bundle/ruby/2.6.0/bundler/gems/CocoaPods-804eed538505/lib/cocoapods/command.rb:52:in `run'
/Users/h-mineta/Documents/Sample/vendor/bundle/ruby/2.6.0/bundler/gems/CocoaPods-804eed538505/bin/pod:55:in `<top (required)>'
/Users/h-mineta/Documents/Sample/vendor/bundle/ruby/2.6.0/bin/pod:23:in `load'
/Users/h-mineta/Documents/Sample/vendor/bundle/ruby/2.6.0/bin/pod:23:in `<top (required)>'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
```

So I added cocoapods-core to Gemfile  by reference to https://github.com/CocoaPods/CocoaPods/issues/9697
```
gem 'cocoapods-core', :git => 'https://github.com/CocoaPods/Core.git'
```

Then I made it! Thank you so much!

**Comment by dnkoutso** [comment]
Yeap both these gems are in lockstep

**Comment by aklee** [comment]
Still got same problem. @hatsunem  @dnkoutso 
➜  ~ pod --version
1.12.1

**Comment by aklee** [comment]
got the error when SampleA embd SampleB
<img width="545" alt="截屏2023-07-03 10 41 03" src="https://github.com/CocoaPods/CocoaPods/assets/5477917/08e406d9-d120-40e2-86db-67b933d5a818">

<img width="818" alt="截屏2023-07-03 10 43 57" src="https://github.com/CocoaPods/CocoaPods/assets/5477917/cce13119-712b-4cfa-ba86-dfc699fd15f8">

@dnkoutso
