### ISSUE TITLE
RangeError - integer 4294967288 too big to convert to `int'

### ISSUE THREAD

**Issue by mustafakameldev** [CocoaPods/CocoaPods#10781]
### Error

```
RangeError - integer 4294967288 too big to convert to `int'
/opt/homebrew/Cellar/cocoapods/1.10.1_1/libexec/gems/ffi-1.15.0/lib/ffi/struct_layout_builder.rb:171:in `initialize'
/opt/homebrew/Cellar/cocoapods/1.10.1_1/libexec/gems/ffi-1.15.0/lib/ffi/struct_layout_builder.rb:171:in `new'
/opt/homebrew/Cellar/cocoapods/1.10.1_1/libexec/gems/ffi-1.15.0/lib/ffi/struct_layout_builder.rb:171:in `build'
/opt/homebrew/Cellar/cocoapods/1.10.1_1/libexec/gems/ffi-1.15.0/lib/ffi/struct.rb:220:in `layout'
/opt/homebrew/Cellar/cocoapods/1.10.1_1/libexec/gems/ethon-0.13.0/lib/ethon/curls/classes.rb:37:in `<class:FDSet>'
/opt/homebrew/Cellar/cocoapods/1.10.1_1/libexec/gems/ethon-0.13.0/lib/ethon/curls/classes.rb:27:in `<module:Curl>'
/opt/homebrew/Cellar/cocoapods/1.10.1_1/libexec/gems/ethon-0.13.0/lib/ethon/curls/classes.rb:3:in `<module:Ethon>'
/opt/homebrew/Cellar/cocoapods/1.10.1_1/libexec/gems/ethon-0.13.0/lib/ethon/curls/classes.rb:2:in `<top (required)>'
<internal:/opt/homebrew/Cellar/ruby/3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/opt/homebrew/Cellar/ruby/3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/opt/homebrew/Cellar/cocoapods/1.10.1_1/libexec/gems/ethon-0.13.0/lib/ethon/curl.rb:29:in `<module:Curl>'
/opt/homebrew/Cellar/cocoapods/1.10.1_1/libexec/gems/ethon-0.13.0/lib/ethon/curl.rb:14:in `<module:Ethon>'
/opt/homebrew/Cellar/cocoapods/1.10.1_1/libexec/gems/ethon-0.13.0/lib/ethon/curl.rb:9:in `<top (required)>'
<internal:/opt/homebrew/Cellar/ruby/3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/opt/homebrew/Cellar/ruby/3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/opt/homebrew/Cellar/cocoapods/1.10.1_1/libexec/gems/ethon-0.13.0/lib/ethon.rb:17:in `<top (required)>'
<internal:/opt/homebrew/Cellar/ruby/3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/opt/homebrew/Cellar/ruby/3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/opt/homebrew/Cellar/cocoapods/1.10.1_1/libexec/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
<internal:/opt/homebrew/Cellar/ruby/3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/opt/homebrew/Cellar/ruby/3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/opt/homebrew/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:440:in `download_typhoeus_impl_async'
/opt/homebrew/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:372:in `download_and_save_with_retries_async'
/opt/homebrew/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:365:in `download_file_async'
/opt/homebrew/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:338:in `download_file'
/opt/homebrew/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:284:in `ensure_versions_file_loaded'
/opt/homebrew/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:208:in `search'
/opt/homebrew/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-core-1.10.1/lib/cocoapods-core/source/aggregate.rb:83:in `block in search'
/opt/homebrew/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-core-1.10.1/lib/cocoapods-core/source/aggregate.rb:83:in `select'
/opt/homebrew/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-core-1.10.1/lib/cocoapods-core/source/aggregate.rb:83:in `search'
/opt/homebrew/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:416:in `create_set_from_sources'
/opt/homebrew/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:385:in `find_cached_set'
/opt/homebrew/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:360:in `specifications_for_dependency'
/opt/homebrew/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:165:in `search_for'
/opt/homebrew/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:274:in `block in sort_dependencies'
/opt/homebrew/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:267:in `each'
/opt/homebrew/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:267:in `sort_by'
/opt/homebrew/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:267:in `sort_dependencies'
/opt/homebrew/Cellar/cocoapods/1.10.1_1/libexec/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:53:in `block in sort_dependencies'
/opt/homebrew/Cellar/cocoapods/1.10.1_1/libexec/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:70:in `with_no_such_dependency_error_handling'
/opt/homebrew/Cellar/cocoapods/1.10.1_1/libexec/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:52:in `sort_dependencies'
/opt/homebrew/Cellar/cocoapods/1.10.1_1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:754:in `push_state_for_requirements'
/opt/homebrew/Cellar/cocoapods/1.10.1_1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:746:in `require_nested_dependencies_for'
/opt/homebrew/Cellar/cocoapods/1.10.1_1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:729:in `activate_new_spec'
/opt/homebrew/Cellar/cocoapods/1.10.1_1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:686:in `attempt_to_activate'
/opt/homebrew/Cellar/cocoapods/1.10.1_1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:254:in `process_topmost_state'
/opt/homebrew/Cellar/cocoapods/1.10.1_1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
/opt/homebrew/Cellar/cocoapods/1.10.1_1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
/opt/homebrew/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:94:in `resolve'
/opt/homebrew/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:1074:in `block in resolve_dependencies'
/opt/homebrew/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/opt/homebrew/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:1072:in `resolve_dependencies'
/opt/homebrew/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/opt/homebrew/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:414:in `analyze'
/opt/homebrew/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:239:in `block in resolve_dependencies'
/opt/homebrew/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/opt/homebrew/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:238:in `resolve_dependencies'
/opt/homebrew/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:160:in `install!'
/opt/homebrew/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/command/install.rb:52:in `run'
/opt/homebrew/Cellar/cocoapods/1.10.1_1/libexec/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/opt/homebrew/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/opt/homebrew/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/opt/homebrew/Cellar/cocoapods/1.10.1_1/libexec/bin/pod:23:in `load'
/opt/homebrew/Cellar/cocoapods/1.10.1_1/libexec/bin/pod:23:in `<main>'
```

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [arm64-darwin20]
    RubyGems : 3.2.22
        Host : macOS 11.4 (20F71)
       Xcode : 12.5.1 (12E507)
         Git : git version 2.30.1 (Apple Git-130)
Ruby lib dir : /opt/homebrew/Cellar/ruby/3.0.2/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

**Comment by dnkoutso** [comment]
please provide a sample app and podfile that demonstrates the issue. Its hard to diagnose this.

**Comment by velevtzvetlin** [comment]
same issue

**Comment by dnkoutso** [comment]
Closing due to inactivity. For others a wild guess `pod cache clean --all` and `rm -rf ~/.cocoapods/repos`.

**Comment by syedamirali14** [comment]
i fixed it by quitting my terminal completely and reopening it
