### ISSUE TITLE
pod install doesn't work

### ISSUE THREAD

**Issue by amanchik** [CocoaPods/CocoaPods#10783]
Analyzing dependencies

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/anil/.rbenv/versions/3.0.2/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-darwin20]
    RubyGems : 3.2.22
        Host : macOS 11.4 (20F71)
       Xcode : 12.5.1 (12E507)
         Git : git version 2.30.1 (Apple Git-130)
Ruby lib dir : /Users/anil/.rbenv/versions/3.0.2/lib
Repositories : 
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Task Tracker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Task Tracker
  pod 'RealmSwift', '~> 10'
end
```

### Error

```
LoadError - dlopen(/Users/anil/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/ffi-1.15.3/lib/ffi_c.bundle, 9): Library not loaded: @rpath/libffi.7.dylib
  Referenced from: /Users/anil/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/ffi-1.15.3/lib/ffi_c.bundle
  Reason: image not found - /Users/anil/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/ffi-1.15.3/lib/ffi_c.bundle
<internal:/Users/anil/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/Users/anil/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/Users/anil/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/ffi-1.15.3/lib/ffi.rb:5:in `rescue in <top (required)>'
/Users/anil/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/ffi-1.15.3/lib/ffi.rb:2:in `<top (required)>'
<internal:/Users/anil/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/Users/anil/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/Users/anil/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/ethon-0.14.0/lib/ethon.rb:3:in `<top (required)>'
<internal:/Users/anil/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/Users/anil/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/Users/anil/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
<internal:/Users/anil/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/Users/anil/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/Users/anil/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:74:in `cdn_url?'
/Users/anil/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:36:in `create_source_with_url'
/Users/anil/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:21:in `find_or_create_source_with_url'
/Users/anil/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:178:in `block in sources'
/Users/anil/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:177:in `map'
/Users/anil/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:177:in `sources'
/Users/anil/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:1073:in `block in resolve_dependencies'
/Users/anil/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/anil/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:1072:in `resolve_dependencies'
/Users/anil/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/Users/anil/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:414:in `analyze'
/Users/anil/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:239:in `block in resolve_dependencies'
/Users/anil/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/anil/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:238:in `resolve_dependencies'
/Users/anil/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:160:in `install!'
/Users/anil/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/command/install.rb:52:in `run'
/Users/anil/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/anil/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/Users/anil/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/Users/anil/.rbenv/versions/3.0.2/bin/pod:23:in `load'
/Users/anil/.rbenv/versions/3.0.2/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=dlopen%28%2FUsers%2Fanil%2F.rbenv%2Fversions%2F3.0.2%2Flib%2Fruby%2Fgems%2F3.0.0%2Fgems%2Fffi-1.15.3%2Flib%2Fffi_c.bundle%2C+9%29%3A+Library+not+loaded%3A+%40rpath%2Flibffi.7.dylib%0A++Referenced+from%3A+%2FUsers%2Fanil%2F.rbenv%2Fversions%2F3.0.2%2Flib%2Fruby%2Fgems%2F3.0.0%2Fgems%2Fffi-1.15.3%2Flib%2Fffi_c.bundle%0A++Reason%3A+image+not+found+-+%2FUsers%2Fanil%2F.rbenv%2Fversions%2F3.0.2%2Flib%2Fruby%2Fgems%2F3.0.0%2Fgems%2Fffi-1.15.3%2Flib%2Fffi_c.bundle&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Searching for inspections failed: undefined method `map' for nil:NilClass

**Comment by paulb777** [comment]
See #9907, https://betterprogramming.pub/ruby-on-apple-silicon-m1-macs-fb159849b2f5, and other issues in this repo related to the ff1 issue and CocoaPods on M1 Macs.
