### ISSUE TITLE
when pod install 

### ISSUE THREAD

**Issue by 757273750** [CocoaPods/CocoaPods#10799]
### Command

```
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
    RubyGems : 3.0.3
        Host : macOS 11.2.3 (20D91)
       Xcode : 12.5.1 (12E507)
         Git : git version 2.30.1 (Apple Git-130)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'MenteeApp' do
  use_unimodules!
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # Uncomment the code below to enable Flipper.
  #
  # You should not install Flipper in CI environments when creating release
  # builds, this will lead to significantly slower build times.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work.
  #
  #  use_flipper!
  #  post_install do |installer|
  #    flipper_post_install(installer)
  #  end

  pod 'SSZipArchive', '2.1.3'
  pod 'Masonry', '1.1.0'
  pod 'Bugly', '2.5.0'
  pod 'MJRefresh'
  pod 'UMCommon', '7.2.5'
  pod 'UMDevice'
  pod 'UMAPM'
  pod 'UMPush'
  pod 'UMCSecurityPlugins'
  pod 'IQKeyboardManager'

end
```

### Error

```
RuntimeError - Compilation error generating constants :
	In file included from /var/folders/x1/fp3ln6jj6hb8qzzm339m1g0c0000gn/T/.const_generator20210722-33262-1raxz0a:1:
	In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk/usr/include/stdio.h:64:
	In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk/usr/include/_stdio.h:68:
	/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk/usr/include/sys/cdefs.h:816:2: error: Unsupported architecture
	#error Unsupported architecture
	 ^
	In file included from /var/folders/x1/fp3ln6jj6hb8qzzm339m1g0c0000gn/T/.const_generator20210722-33262-1raxz0a:1:
	In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk/usr/include/stdio.h:64:
	In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk/usr/include/_stdio.h:71:
	In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk/usr/include/_types.h:27:
	In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk/usr/include/sys/_types.h:33:
	/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk/usr/include/machine/_types.h:34:2: error: architecture not supported
	#error architecture not supported
	 ^
	In file included from /var/folders/x1/fp3ln6jj6hb8qzzm339m1g0c0000gn/T/.const_generator20210722-33262-1raxz0a:1:
	In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk/usr/include/stdio.h:64:
	In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk/usr/include/_stdio.h:71:
	In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk/usr/include/_types.h:27:
	/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk/usr/include/sys/_types.h:55:9: error: unknown type name '__int64_t'; did you mean '__int128_t'?
	typedef __int64_t       __darwin_blkcnt_t;      /* total blocks */
	        ^
	note: '__int128_t' declared here
	/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk/usr/include/sys/_types.h:56:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?
	typedef __int32_t       __darwin_blksize_t;     /* preferred block size */
	        ^
	note: '__int128_t' declared here
	/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk/usr/include/sys/_types.h:57:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?
	typedef __int32_t       __darwin_dev_t;         /* dev_t */
	        ^
	note: '__int128_t' declared here
	/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk/usr/include/sys/_types.h:60:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
	typedef __uint32_t      __darwin_gid_t;         /* [???] process and group IDs */
	        ^
	note: '__uint128_t' declared here
	/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk/usr/include/sys/_types.h:61:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
	typedef __uint32_t      __darwin_id_t;          /* [XSI] pid_t, uid_t, or gid_t*/
	        ^
	note: '__uint128_t' declared here
	/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk/usr/include/sys/_types.h:62:9: error: unknown type name '__uint64_t'; did you mean '__uint128_t'?
	typedef __uint64_t      __darwin_ino64_t;       /* [???] Used for 64 bit inodes */
	        ^
	note: '__uint128_t' declared here
	/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk/usr/include/sys/_types.h:68:9: error: unknown type name '__darwin_natural_t'
	typedef __darwin_natural_t __darwin_mach_port_name_t; /* Used by mach */
	        ^
	/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk/usr/include/sys/_types.h:70:9: error: unknown type name '__uint16_t'; did you mean '__uint128_t'?
	typedef __uint16_t      __darwin_mode_t;        /* [???] Some file attributes */
	        ^
	note: '__uint128_t' declared here
	/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk/usr/include/sys/_types.h:71:9: error: unknown type name '__int64_t'; did you mean '__int128_t'?
	typedef __int64_t       __darwin_off_t;         /* [???] Used for file sizes */
	        ^
	note: '__int128_t' declared here
	/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk/usr/include/sys/_types.h:72:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?
	typedef __int32_t       __darwin_pid_t;         /* [???] process and group IDs */
	        ^
	note: '__int128_t' declared here
	/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk/usr/include/sys/_types.h:73:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
	typedef __uint32_t      __darwin_sigset_t;      /* [???] signal set */
	        ^
	note: '__uint128_t' declared here
	/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk/usr/include/sys/_types.h:74:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?
	typedef __int32_t       __darwin_suseconds_t;   /* [???] microseconds */
	        ^
	note: '__int128_t' declared here
	/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk/usr/include/sys/_types.h:75:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
	typedef __uint32_t      __darwin_uid_t;         /* [???] user IDs */
	        ^
	note: '__uint128_t' declared here
	/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk/usr/include/sys/_types.h:76:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
	typedef __uint32_t      __darwin_useconds_t;    /* [???] microseconds */
	        ^
	note: '__uint128_t' declared here
	In file included from /var/folders/x1/fp3ln6jj6hb8qzzm339m1g0c0000gn/T/.const_generator20210722-33262-1raxz0a:1:
	In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk/usr/include/stdio.h:64:
	In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk/usr/include/_stdio.h:71:
	/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk/usr/include/_types.h:43:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
	typedef __uint32_t      __darwin_wctype_t;
	        ^
	note: '__uint128_t' declared here
	In file included from /var/folders/x1/fp3ln6jj6hb8qzzm339m1g0c0000gn/T/.const_generator20210722-33262-1raxz0a:1:
	In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk/usr/include/stdio.h:64:
	In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk/usr/include/_stdio.h:75:
	In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk/usr/include/sys/_types/_va_list.h:31:
	/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk/usr/include/machine/types.h:37:2: error: architecture not supported
	#error architecture not supported
	 ^
	In file included from /var/folders/x1/fp3ln6jj6hb8qzzm339m1g0c0000gn/T/.const_generator20210722-33262-1raxz0a:1:
	In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk/usr/include/stdio.h:64:
	In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk/usr/include/_stdio.h:75:
	/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk/usr/include/sys/_types/_va_list.h:32:9: error: unknown type name '__darwin_va_list'
	typedef __darwin_va_list va_list;
	        ^
	fatal error: too many errors emitted, stopping now [-ferror-limit=]
	20 errors generated.
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/ffi-1.15.0/lib/ffi/tools/const_generator.rb:131:in `block in calculate'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tempfile.rb:295:in `open'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/ffi-1.15.0/lib/ffi/tools/const_generator.rb:110:in `calculate'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/ffi-1.15.0/lib/ffi/tools/const_generator.rb:49:in `initialize'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/ethon-0.13.0/lib/ethon/libc.rb:17:in `new'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/ethon-0.13.0/lib/ethon/libc.rb:17:in `<module:Libc>'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/ethon-0.13.0/lib/ethon/libc.rb:7:in `<module:Ethon>'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/ethon-0.13.0/lib/ethon/libc.rb:2:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/ethon-0.13.0/lib/ethon.rb:16:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:440:in `download_typhoeus_impl_async'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:372:in `download_and_save_with_retries_async'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:365:in `download_file_async'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:338:in `download_file'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:284:in `ensure_versions_file_loaded'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:208:in `search'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-core-1.10.1/lib/cocoapods-core/source/aggregate.rb:83:in `block in search'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-core-1.10.1/lib/cocoapods-core/source/aggregate.rb:83:in `select'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-core-1.10.1/lib/cocoapods-core/source/aggregate.rb:83:in `search'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:416:in `create_set_from_sources'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:385:in `find_cached_set'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:360:in `specifications_for_dependency'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:165:in `search_for'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:274:in `block in sort_dependencies'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:267:in `each'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:267:in `sort_by'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:267:in `sort_dependencies'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:53:in `block in sort_dependencies'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:70:in `with_no_such_dependency_error_handling'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:52:in `sort_dependencies'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:288:in `initial_state'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:210:in `start_resolution'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:168:in `resolve'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:94:in `resolve'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:1074:in `block in resolve_dependencies'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:1072:in `resolve_dependencies'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:414:in `analyze'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:239:in `block in resolve_dependencies'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:238:in `resolve_dependencies'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:160:in `install!'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/command/install.rb:52:in `run'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/bin/pod:23:in `load'
/usr/local/Cellar/cocoapods/1.10.1_1/libexec/bin/pod:23:in `<main>'
```

**Comment by dnkoutso** [comment]
This looks like an `ffi` gem isntallation issue. Please ask in stackoverflow or search for other issues in this repo related to `ffi` gem installation.
