### ISSUE TITLE
 LoadError - cannot load such file -- cocoapods/installer/podfile_validator

### ISSUE THREAD

**Issue by franciscoamado** [CocoaPods/CocoaPods#10833]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

Hi there :wave: 

We've been seeing sporadic errors happening when running `pod install --repo-update`.
This is happening in several different working environments, with the same configurations and not every time the command is executed.
We can't understand why this is occurring.

We've also tried with the latest patch of cocoapods (1.10.2) without success.

Thank you 🙏🏻 

## What did you do?

1. Run `bundle exec pod install --repo-update`

## What did you expect to happen?

Updated local repos and Installed all pod dependencies correctly.

### Error

 ```
 LoadError - cannot load such file -- cocoapods/installer/podfile_validator
 /Users/<redacted>/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:223:in `require'
 /Users/<redacted>/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:223:in `validate_podfile!'
 /Users/<redacted>/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:103:in `analyze'
 /Users/<redacted>/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:414:in `analyze'
 /Users/<redacted>/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:239:in `block in resolve_dependencies'
 /Users/<redacted>/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
 /Users/<redacted>/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:238:in `resolve_dependencies'
 /Users/<redacted>/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:160:in `install!'
 /Users/<redacted>/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/command/install.rb:52:in `run'
 /Users/<redacted>/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
 /Users/<redacted>/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
 /Users/<redacted>/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
 /Users/<redacted>/.rbenv/versions/3.0.1/bin/pod:23:in `load'
 /Users/<redacted>/.rbenv/versions/3.0.1/bin/pod:23:in `<top (required)>'
 /Users/<redacted>/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/cli/exec.rb:63:in `load'
 /Users/<redacted>/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/cli/exec.rb:63:in `kernel_load'
 /Users/<redacted>/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/cli/exec.rb:28:in `run'
 /Users/<redacted>/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/cli.rb:494:in `exec'
 /Users/<redacted>/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
 /Users/<redacted>/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
 /Users/<redacted>/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
 /Users/<redacted>/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/cli.rb:30:in `dispatch'
 /Users/<redacted>/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
 /Users/<redacted>/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/cli.rb:24:in `start'
 /Users/<redacted>/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.15/libexec/bundle:49:in `block in <top (required)>'
 /Users/<redacted>/.rbenv/versions/3.0.1/lib/ruby/3.0.0/bundler/friendly_errors.rb:130:in `with_friendly_errors'
 /Users/<redacted>/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.15/libexec/bundle:37:in `<top (required)>'
 /Users/<redacted>/.rbenv/versions/3.0.1/bin/bundle:23:in `load'
 /Users/<redacted>/.rbenv/versions/3.0.1/bin/bundle:23:in `<main>'
 ```

### Stack

 ```
    CocoaPods : 1.10.1
         Ruby : ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-darwin20]
     RubyGems : 3.2.15
         Host : macOS 11.2.3 (20D91)
        Xcode : 12.2 (12B45b)
          Git : git version 2.24.3 (Apple Git-128)
 Ruby lib dir : /Users/<redacted>/.rbenv/versions/3.0.1/lib
 Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ 963747fdff00a68e7e31a8b07aef33fd3e5c1efd

                trunk - CDN - https://cdn.cocoapods.org/
 ```

 ### Plugins

 ```
 claide-plugins        : 0.9.2
 cocoapods-deintegrate : 1.0.4
 cocoapods-plugins     : 1.0.0
 cocoapods-search      : 1.0.0
 cocoapods-trunk       : 1.5.0
 cocoapods-try         : 1.2.0
 ```

**Comment by dnkoutso** [comment]
From first glance this looks like an environment issue? 

I just landed CI support for Ruby 3.0 and it passed https://github.com/CocoaPods/CocoaPods/pull/8980

**Comment by dnkoutso** [comment]
Try updating `bundler` maybe some different versions of gems being picked up?

**Comment by dnkoutso** [comment]
hm maybe we could add an `autoload`, if you edit the sources on a machine that is failing and add 

```ruby
autoload :PodfileValidator,          'cocoapods/installer/podfile_validator'
```

does it make it work?

**Comment by franciscoamado** [comment]
👋🏻  Thanks for such a fast response.



> From first glance this looks like an environment issue?
> 
> I just landed CI support for Ruby 3.0 and it passed #8980

> Try updating bundler maybe some different versions of gems being picked up?

I was expecting this but we don't see any changes between machines where this command is failing and other machines where it doesn't.

Ruby and bundler reinstallations also didn't help.

**Comment by dnkoutso** [comment]
closing due to inactivity.

**Comment by franciscoamado** [comment]
👋🏻  Sorry for letting this go inactive.

Only thing that ended up being the common variable among CI and Developer machines with this problem was the OS version (11.2.3).

After an update to the most recent version this problem was fixed.

Thank you for the support!
