### ISSUE TITLE
On demand resource crash on master

### ISSUE THREAD

**Issue by paulb777** [CocoaPods/CocoaPods#10840]
`git clone https://github.com/firebase/firebase-ios-sdk.git`
```
diff --git a/Gemfile b/Gemfile
index 10ed8e493..5f9159bba 100644
--- a/Gemfile
+++ b/Gemfile
@@ -2,7 +2,7 @@
 # commit Gemfile and Gemfile.lock.
 source 'https://rubygems.org'

-gem 'cocoapods', '1.10.2'
+gem 'cocoapods', git: "https://github.com/CocoaPods/CocoaPods.git", ref: "c89bfd9a4c394071e24fa3746022ee8a2b3c356e"

 gem 'cocoapods-generate', '2.0.1'
 gem 'danger', '6.1.0'
```
cd SymbolCollisionTest

```
 $ bundle exec pod install
Analyzing dependencies
Downloading dependencies
Installing AppAuth (1.4.0)

[!] Error installing AppAuth

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/paulbeusterien/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.10.2
        Ruby : ruby 2.7.3p183 (2021-04-05 revision 6847ee089d) [x86_64-darwin20]
    RubyGems : 3.1.6
        Host : macOS 11.5.1 (20G80)
       Xcode : 12.5 (12E262)
         Git : git version 2.32.0.554.ge1b32706d8-goog
Ruby lib dir : /Users/paulbeusterien/.rbenv/versions/2.7.3/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ 9b77ba80bdd6e1aac83b912a0390b12c4c4ba75e

               firebase - git - https://github.com/firebase/SpecsDev.git @ 2069b08b8015390bda20644f4f05fce821ab0dda

               firebase-1 - git - https://github.com/firebase/SpecsStaging.git @ 7674bfcba4fe64fc487412b0c5b25e2af3c2113a

               paulb777 - git - https://github.com/paulb777/cocoapod.git @ 083cff897f65dbf8d8c581372c4e325fab4081bb

               specs-testing - git - git@github.com:firebase/SpecsTesting.git @ 54cb2e3099402c836cf492a53360ccdb15a27625

               staging - git - git@github.com:firebase/SpecsStaging.git @ 989f3fda603c0b2f05b0b3ecfabab674a6f6cadf

               trunk - CDN - https://cdn.cocoapods.org/

```

### Plugins

```
claide-plugins                        : 0.9.2
cocoapods-deintegrate                 : 1.0.4
cocoapods-disable-podfile-validations : 0.1.1
cocoapods-generate                    : 2.0.1
cocoapods-plugins                     : 1.0.0
cocoapods-search                      : 1.0.0
cocoapods-trunk                       : 1.5.0
cocoapods-try                         : 1.2.0
```

### Podfile

```ruby
platform :ios, '10.0'

source 'https://github.com/firebase/SpecsDev.git'
source 'https://github.com/firebase/SpecsStaging.git'
source 'https://cdn.cocoapods.org/'

target 'SymbolCollisionTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Firebase Pods
    pod 'Firebase', :path => '../'
    pod 'FirebaseABTesting', :path => '../'
    pod 'FirebaseAppDistribution', :path => '../'
    pod 'FirebaseAnalytics'
    pod 'FirebaseAuth', :path => '../'
    pod 'FirebaseCore', :path => '../'
    pod 'FirebaseCoreDiagnostics', :path => '../'
    pod 'FirebaseCrashlytics', :path => '../'
    pod 'FirebaseDatabase', :path => '../'
    pod 'FirebaseDynamicLinks', :path => '../'
    pod 'FirebaseFirestore', :path => '../'
    pod 'FirebaseFunctions', :path => '../'
    pod 'FirebaseInAppMessaging', :path => '../'
    pod 'FirebaseInstallations', :path => '../'
    pod 'FirebaseMessaging', :path => '../'
    pod 'FirebasePerformance', :path => '../'
    pod 'FirebaseRemoteConfig', :path => '../'
    pod 'FirebaseStorage', :path => '../'
    pod 'GoogleUtilitiesComponents', :path => '../'

#    pod 'FirebaseUI'. - requires use_frameworks!

    # Google Pods depending on a Firebase or GDT major version
    pod 'GoogleMLKit'

  # Other Google Pods
#    pod 'ARCore' Conflicts with FirebasePerformance via Clearcut and google-cast-sdk
#    pod 'Blockly' This is a Swift Pod and requires usage of use_frameworks!
    pod 'DigitsMigrationHelper'
    pod 'EarlGrey'
#    pod 'GeoFire' -- requires Firebase/Database 4.0
#    pod 'google-cast-sdk' -- abseil
    pod 'Google-Mobile-Ads-SDK'
    pod 'GoogleAnalytics'
    pod 'GoogleAppIndexing'
    pod 'GoogleAppUtilities'
    pod 'GoogleAuthUtilities'
    pod 'GoogleConversionTracking'
    pod 'GoogleDataTransport'
    pod 'GoogleIDFASupport'
    pod 'GoogleInterchangeUtilities'
    pod 'GoogleMaps'

#    pod 'GoogleMobileVision' # After Firebase 6.8.0, conflicts with FirebaseML
    pod 'GoogleNetworkingUtilities'
    pod 'GoogleParsingUtilities'
    pod 'GooglePlacePicker'
    pod 'GooglePlaces'
    pod 'GooglePlusUtilities'
    pod 'GoogleSignIn'
    pod 'GoogleSymbolUtilities'
    pod 'GoogleTagManager'
    pod 'GoogleToolboxForMac'
    pod 'GoogleUtilities'
    pod 'GTMAppAuth'
#    pod 'GTMHTTPFetcher' - conflicts with GTMSessionFetcher
    pod 'GTMSessionFetcher'
#    pod 'GVRSDK' -- absl and protobuf duplicates
    pod 'leveldb-library'
#    pod 'MDFTextAccessibility' - conflicts with GVRSDK
    pod 'nanopb'
#    pod 'NearbyMessages' # - conflicts with google-cast-sdk
    pod 'Protobuf'

  # Non-Google Pods

end
```

### Error

```
NoMethodError - undefined method `on_demand_resources' for #<Pod::Specification::Consumer:0x00007fc6dda22f00>
/Users/paulbeusterien/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/bundler/gems/CocoaPods-c89bfd9a4c39/lib/cocoapods/sandbox/file_accessor.rb:342:in `on_demand_resources'
/Users/paulbeusterien/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/bundler/gems/CocoaPods-c89bfd9a4c39/lib/cocoapods/sandbox/file_accessor.rb:222:in `block in all_files'
/Users/paulbeusterien/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/bundler/gems/CocoaPods-c89bfd9a4c39/lib/cocoapods/sandbox/file_accessor.rb:222:in `each'
/Users/paulbeusterien/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/bundler/gems/CocoaPods-c89bfd9a4c39/lib/cocoapods/sandbox/file_accessor.rb:222:in `flat_map'
/Users/paulbeusterien/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/bundler/gems/CocoaPods-c89bfd9a4c39/lib/cocoapods/sandbox/file_accessor.rb:222:in `all_files'
/Users/paulbeusterien/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/bundler/gems/CocoaPods-c89bfd9a4c39/lib/cocoapods/sandbox/pod_dir_cleaner.rb:67:in `used_files'
/Users/paulbeusterien/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/bundler/gems/CocoaPods-c89bfd9a4c39/lib/cocoapods/sandbox/pod_dir_cleaner.rb:51:in `clean_paths'
/Users/paulbeusterien/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/bundler/gems/CocoaPods-c89bfd9a4c39/lib/cocoapods/sandbox/pod_dir_cleaner.rb:18:in `clean!'
/Users/paulbeusterien/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/bundler/gems/CocoaPods-c89bfd9a4c39/lib/cocoapods/downloader/cache.rb:289:in `block in copy_and_clean'
/Users/paulbeusterien/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/bundler/gems/CocoaPods-c89bfd9a4c39/lib/cocoapods/downloader/cache.rb:128:in `lock'
/Users/paulbeusterien/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/bundler/gems/CocoaPods-c89bfd9a4c39/lib/cocoapods/downloader/cache.rb:99:in `write_lock'
/Users/paulbeusterien/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/bundler/gems/CocoaPods-c89bfd9a4c39/lib/cocoapods/downloader/cache.rb:285:in `copy_and_clean'
/Users/paulbeusterien/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/bundler/gems/CocoaPods-c89bfd9a4c39/lib/cocoapods/downloader/cache.rb:244:in `block (2 levels) in uncached_pod'
/Users/paulbeusterien/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/bundler/gems/CocoaPods-c89bfd9a4c39/lib/cocoapods/downloader/cache.rb:242:in `each'
/Users/paulbeusterien/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/bundler/gems/CocoaPods-c89bfd9a4c39/lib/cocoapods/downloader/cache.rb:242:in `block in uncached_pod'
/Users/paulbeusterien/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/bundler/gems/CocoaPods-c89bfd9a4c39/lib/cocoapods/downloader/cache.rb:266:in `in_tmpdir'
/Users/paulbeusterien/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/bundler/gems/CocoaPods-c89bfd9a4c39/lib/cocoapods/downloader/cache.rb:238:in `uncached_pod'
/Users/paulbeusterien/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/bundler/gems/CocoaPods-c89bfd9a4c39/lib/cocoapods/downloader/cache.rb:33:in `download_pod'
/Users/paulbeusterien/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/bundler/gems/CocoaPods-c89bfd9a4c39/lib/cocoapods/downloader.rb:42:in `download'
/Users/paulbeusterien/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/bundler/gems/CocoaPods-c89bfd9a4c39/lib/cocoapods/installer/pod_source_installer.rb:118:in `download_source'
/Users/paulbeusterien/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/bundler/gems/CocoaPods-c89bfd9a4c39/lib/cocoapods/installer/pod_source_installer.rb:69:in `install!'
/Users/paulbeusterien/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/bundler/gems/CocoaPods-c89bfd9a4c39/lib/cocoapods/installer.rb:563:in `install_source_of_pod'
/Users/paulbeusterien/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/bundler/gems/CocoaPods-c89bfd9a4c39/lib/cocoapods/installer.rb:514:in `block (2 levels) in install_pod_sources'
/Users/paulbeusterien/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/bundler/gems/CocoaPods-c89bfd9a4c39/lib/cocoapods/user_interface.rb:86:in `titled_section'
/Users/paulbeusterien/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/bundler/gems/CocoaPods-c89bfd9a4c39/lib/cocoapods/installer.rb:513:in `block in install_pod_sources'
/Users/paulbeusterien/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/bundler/gems/CocoaPods-c89bfd9a4c39/lib/cocoapods/installer.rb:496:in `each'
/Users/paulbeusterien/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/bundler/gems/CocoaPods-c89bfd9a4c39/lib/cocoapods/installer.rb:496:in `install_pod_sources'
/Users/paulbeusterien/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/bundler/gems/CocoaPods-c89bfd9a4c39/lib/cocoapods/installer.rb:255:in `block in download_dependencies'
/Users/paulbeusterien/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/bundler/gems/CocoaPods-c89bfd9a4c39/lib/cocoapods/user_interface.rb:64:in `section'
/Users/paulbeusterien/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/bundler/gems/CocoaPods-c89bfd9a4c39/lib/cocoapods/installer.rb:254:in `download_dependencies'
/Users/paulbeusterien/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/bundler/gems/CocoaPods-c89bfd9a4c39/lib/cocoapods/installer.rb:162:in `install!'
/Users/paulbeusterien/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/bundler/gems/CocoaPods-c89bfd9a4c39/lib/cocoapods/command/install.rb:52:in `run'
/Users/paulbeusterien/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/paulbeusterien/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/bundler/gems/CocoaPods-c89bfd9a4c39/lib/cocoapods/command.rb:52:in `run'
/Users/paulbeusterien/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/bundler/gems/CocoaPods-c89bfd9a4c39/bin/pod:55:in `<top (required)>'
/Users/paulbeusterien/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/bin/pod:23:in `load'
/Users/paulbeusterien/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/bin/pod:23:in `<top (required)>'
/Users/paulbeusterien/.rbenv/versions/2.7.3/lib/ruby/2.7.0/bundler/cli/exec.rb:63:in `load'
/Users/paulbeusterien/.rbenv/versions/2.7.3/lib/ruby/2.7.0/bundler/cli/exec.rb:63:in `kernel_load'
/Users/paulbeusterien/.rbenv/versions/2.7.3/lib/ruby/2.7.0/bundler/cli/exec.rb:28:in `run'
/Users/paulbeusterien/.rbenv/versions/2.7.3/lib/ruby/2.7.0/bundler/cli.rb:476:in `exec'
/Users/paulbeusterien/.rbenv/versions/2.7.3/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/paulbeusterien/.rbenv/versions/2.7.3/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/Users/paulbeusterien/.rbenv/versions/2.7.3/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
/Users/paulbeusterien/.rbenv/versions/2.7.3/lib/ruby/2.7.0/bundler/cli.rb:30:in `dispatch'
/Users/paulbeusterien/.rbenv/versions/2.7.3/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
/Users/paulbeusterien/.rbenv/versions/2.7.3/lib/ruby/2.7.0/bundler/cli.rb:24:in `start'
/Users/paulbeusterien/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/libexec/bundle:46:in `block in <top (required)>'
/Users/paulbeusterien/.rbenv/versions/2.7.3/lib/ruby/2.7.0/bundler/friendly_errors.rb:123:in `with_friendly_errors'
/Users/paulbeusterien/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/libexec/bundle:34:in `<top (required)>'
/Users/paulbeusterien/.rbenv/versions/2.7.3/bin/bundle:23:in `load'
/Users/paulbeusterien/.rbenv/versions/2.7.3/bin/bundle:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=undefined+method+%60on_demand_resources%27+for+%23%3CPod%3A%3ASpecification%3A%3AConsumer%3A0x00007fc6dda22f00%3E&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Found no similar issues. To create a new issue, please visit:
https://github.com/cocoapods/cocoapods/issues/new
```

**Comment by dnkoutso** [comment]
You also need to update cocoapods-core gem.

**Comment by paulb777** [comment]
Oops. thanks!
