### ISSUE TITLE
Pod Init Failing - Slather

### ISSUE THREAD

**Issue by justdan0227** [CocoaPods/CocoaPods#10871]
Don't know this is an XCode13 issue or not.   (I issued sudo gem update xcodeproj with no change)

```
pod init

---------------------------------------------
Error loading the plugin `slather-2.4.9`.

Gem::ConflictError - Unable to activate slather-2.4.9, because activesupport-5.2.6 conflicts with activesupport (>= 4.0.2, < 5)
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:2302:in `raise_if_conflicts'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1418:in `activate'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:93:in `safe_activate_and_require'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:31:in `block in load_plugins'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:30:in `map'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:30:in `load_plugins'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:326:in `block in run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:325:in `each'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:325:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
---------------------------------------------
```

**Comment by dnkoutso** [comment]
This seems like a gem/environment issue. We do not see in CI or in other multiple reports. Recommend asking in StackOverflow and also use Bundler instead to setup gems in order to avoid such conflicts.
