### ISSUE TITLE
Create a pod from static framework without source code. Getting error 'No such module 'MySDK' 

### ISSUE THREAD

**Issue by AshwinkumarDa** [CocoaPods/CocoaPods#10881]
We have to create a pod from static framework without source code. This static framework created using Objective C language. Lipo command shows `armv7 arm64 i386 x86_64` architectures. 
Using above pod as dependency we wanted to create a new pod with additional functionalities.

This framework shared by our vendors time to time. We thinking to create a pod and maintain all versions in a repo and use it this way.

**1. Initially we are not able to create a pod from static objective c framework.
We are facing below error from `pod spec lint` command. We are not able to push due to error.**

POD validation was failing with below error- 
```
** BUILD FAILED **
    
   
    The following build commands failed:
    	Ld /Users/username/Library/Developer/Xcode/DerivedData/App-fsaogzopfrnvnddcwfdtbzzcizpv/Build/Intermediates.noindex/App.build/Release-iphonesimulator/App.build/Objects-normal/x86_64/Binary/App normal x86_64
    (1 failure)
   Testing with `xcodebuild`. 
 -> MySDKPod (0.0.9)
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code.
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | [iOS] xcodebuild:  note: Planning build
    - NOTE  | [iOS] xcodebuild:  note: Constructing build description
    - NOTE  | [iOS] xcodebuild:  warning: Skipping code signing because the target does not have an Info.plist file and one is not being generated automatically. (in target 'App' from project 'App')
    - NOTE  | [iOS] xcodebuild:  note: Execution policy exception registration failed and was skipped: Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted" (in target 'Pods-App' from project 'Pods')
    - NOTE  | [iOS] xcodebuild:  clang: error: linker command failed with exit code 1 (use -v to see invocation)

Analyzed 1 podspec.

[!] The spec did not pass validation, due to 1 error.

/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command/spec/lint.rb:104:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
username@Usernames-iMac MySDKPod % 


```
**1.1 Workaround to create pod from static framework.**

We created a repository for pod in remote git and uploaded framework file with readme.md, podspec and module.map.

1.1.1 Podspec has below content-
```
#
# Be sure to run `pod lib lint MySDK.podspec' to ensure this is a
# valid spec before submitting.
#
# Any lines starting with a # are optional, but their use is encouraged
# To learn more about a Podspec see https://guides.cocoapods.org/syntax/podspec.html
#

Pod::Spec.new do |s|
  s.name             = 'MySDK'
  s.version          = ‘0.1.0’
  s.summary          = 'A short description of MySDK.'
  s.description      = <<-DESC
Description of the MySDK here.
                       DESC

  s.homepage         = 'https://git.private_url/groupName/mysdk'
  s.license          = { :type => 'LicenseType’, :file => 'LICENSE' }
  s.author           = { ‘FirstName LastName’ => ‘email@domain.com’ }
  s.source           = { :git => "git@git.domainName.net:groupName/mysdk.git" }
  s.ios.deployment_target = '9.0'
  s.vendored_frameworks = 'MySDK.framework'

  s.source_files = 'MySDK.framework/Headers/*.h'
  s.public_header_files = 'MySDK.framework/Headers/*.h'
  s.frameworks = 'MediaPlayer', 'SystemConfiguration', 'AudioToolbox', 'AVfoundation','CoreLocation'
  s.library = 'sqlite3'
  s.module_map = 'module.map'
  s.preserve_path = 'module.map'


  s.pod_target_xcconfig = {
    'SWIFT_INCLUDE_PATHS' => '\$(PODS_ROOT)/MySDK/MySDK.framework \$(PODS_ROOT)/module.map',
    'OTHER_LDFLAGS' => '-framework "MySDK"'
  }

  s.user_target_xcconfig = {
    'SWIFT_INCLUDE_PATHS' => '\$(PODS_ROOT)/MySDK/MySDK.framework \$(PODS_ROOT)/module.map',
    'OTHER_LDFLAGS' => '-framework "MySDK"'
  }
end

```

1.1.2 module.map file has below content-
```

module MySDK {
header "MySDK.framework/Headers/MySDKFramework.h"
export *
link framework "CoreLocation"
link framework "AVFoundation"
link framework "AudioToolbox"
link framework "SystemConfiguration"
link framework "MediaPlayer"
link "sqlite3"
}


```
2. We have to create another pod by adding more features using above MySDK pod as dependency.
It is failing with module not found error from pod repo push command in podspec validation.

`pod repo push repo_name AnotherSDK.podspec --verbose`
Above command is failing with below error-
```

 Command CompileSwift failed with a nonzero exit code
        ** BUILD FAILED **
        The following build commands failed:
    CompileSwift normal x86_64
    CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
    CompileSwift normal i386
    (3 failures)
   Testing with `xcodebuild`. 
 -> AnotherSDK (0.0.5)
	•	ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code.
	•	NOTE  | xcodebuild:  note: Using new build system
	•	NOTE  | [iOS] xcodebuild:  note: Planning build
	•	NOTE  | [iOS] xcodebuild:  note: Constructing build description
	•	ERROR | [iOS] xcodebuild:  AnotherSDK/AnotherSDK/Classes/ClassName.swift:11:8: error: no such module 'MySDK'
	•	
[!] The `AnotherSDK.podspec` specification does not validate.
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/command/repo/push.rb:150:in `block in validate_podspec_files'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/command/repo/push.rb:135:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/command/repo/push.rb:135:in `validate_podspec_files'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/command/repo/push.rb:76:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'

```

**3. We created a module.map file from above step 1.1.2 is not getting downloaded from pod update or install command.
We are getting no such module 'MySDK' error**

To run the application we did below changes.
3.1 Mention pod repo link with tag name.

  pod ‘MyAnotherSDK’, :git => 'git@git.domainName.net:groupName/myanothersdk.git’, :tag => '0.0.5'
  pod ‘MySDK’, :git => 'git@git.domainName.net:groupName/mysdk.git', :tag => ‘0.1.0’

When we manually add pod link of MyAnotherSDK pod with tag or branch name in podfile in example application, remove -Objc and $(inherited) from other linker flag. Application runs successfully.

IPA fails to compile when we mention only pod name in podfile with error **no such module ‘MySDK’**

**Comment by dnkoutso** [comment]
If possible, please upload a sample app or repo demonstrating the issue. It will make it much easier to diagnose and follow.
