### ISSUE TITLE
pod install Report an error

### ISSUE THREAD

**Issue by GetemJay** [CocoaPods/CocoaPods#10915]
# Report

## What did you do?

Run `pod install`

## What did you expect to happen?

Install all pod dependencies correctly.

## What happened instead?

CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `connectivity` from `.symlinks/plugins/connectivity/ios`
    -> Fetching podspec for `device_info` from `.symlinks/plugins/device_info/ios`
    -> Fetching podspec for `jsc` from `.symlinks/plugins/jsc/ios`
    -> Fetching podspec for `kraken` from `.symlinks/plugins/kraken/ios`
    -> Fetching podspec for `kraken_devtools` from `.symlinks/plugins/kraken_devtools/ios`
    -> Fetching podspec for `kraken_websocket` from `.symlinks/plugins/kraken_websocket/ios`
    -> Fetching podspec for `shared_preferences` from `.symlinks/plugins/shared_preferences/ios`
    -> Fetching podspec for `vibration` from `.symlinks/plugins/vibration/ios`

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_c_7_9.txt exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/c/7/9/Reachability/3.2/Reachability.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/c/7/9/Reachability/3.2/Reachability.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/c/7/9/Reachability/3.1.1/Reachability.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/c/7/9/Reachability/3.1.0/Reachability.podspec.json exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/c/7/9/Reachability/3.0.0/Reachability.podspec.json exists! Returning local because checking is only performed in repo update

    Comparing resolved specification to the sandbox manifest
      A Flutter
      A Reachability
      A connectivity
      A device_info
      A jsc
      A kraken
      A kraken_devtools
      A kraken_websocket
      A shared_preferences
      A vibration

    Downloading dependencies

    -> Installing Flutter (1.0.0)

    -> Installing Reachability (3.2)
      > Copying Reachability from `/Users/GetemJay/Library/Caches/CocoaPods/Pods/Release/Reachability/3.2-33e18` to `Pods/Reachability`

    -> Installing connectivity (0.0.1)

    -> Installing device_info (0.0.1)

    -> Installing jsc (0.0.1)

    -> Installing kraken (0.6.3)
     > Running prepare command
       $ /bin/bash -c  set -e bash prepare.sh

    -> Installing kraken_devtools (0.0.1)

    -> Installing kraken_websocket (0.0.1)

    -> Installing shared_preferences (0.0.1)

    -> Installing vibration (1.7.4-nullsafety.0)
      - Running pre install hooks
      - Running pre integrate hooks

    Generating Pods project
      - Creating Pods project
      - Installing files into Pods project
        - Adding source files
        - Adding frameworks
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only performed in repo update

    ――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

    ### Command

    ```
    /Users/GetemJay/.rvm/gems/ruby-3.0.0/bin/pod install --verbose
    ```

    ### Report

    * What did you do?

    * What did you expect to happen?

    * What happened instead?

    ### Stack

    ```
       CocoaPods : 1.11.0
            Ruby : ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin20]
        RubyGems : 3.2.3
            Host : macOS 11.4 (20F71)
           Xcode : 13.0 (13A5192j)
             Git : git version 2.31.1
    Ruby lib dir : /Users/GetemJay/.rvm/rubies/ruby-3.0.0/lib
    Repositories : trunk - CDN - https://cdn.cocoapods.org/
    ```

    ### Plugins

    ```
    cocoapods-deintegrate : 1.0.4
    cocoapods-plugins     : 1.0.0
    cocoapods-search      : 1.0.0
    cocoapods-trunk       : 1.5.0
    cocoapods-try         : 1.2.0
    ```

    ### Podfile

    ```ruby
    # Uncomment this line to define a global platform for your project
    platform :ios, '10.0'

    # CocoaPods analytics sends network stats synchronously affecting flutter build latency.
    ENV['COCOAPODS_DISABLE_STATS'] = 'true'

    project 'Runner', {
      'Debug' => :debug,
      'Profile' => :release,
      'Release' => :release,
    }

    def flutter_root
      generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
      unless File.exist?(generated_xcode_build_settings_path)
        raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
      end

      File.foreach(generated_xcode_build_settings_path) do |line|
        matches = line.match(/FLUTTER_ROOT\=(.*)/)
        return matches[1].strip if matches
      end
      raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
    end

    require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

    flutter_ios_podfile_setup

    target 'Runner' do
      use_frameworks!
      use_modular_headers!

      flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
    end

    post_install do |installer|
      installer.pods_project.targets.each do |target|
        flutter_additional_ios_build_settings(target)
      end
    end
    ```

    ### Error

    ```
    Errno::ENOENT - No such file or directory @ rb_check_realpath_internal - /Users/GetemJay/Mine/kraken/kraken/example/ios/.symlinks/plugins/kraken/ios/kraken_bridge.framework
    /Users/GetemJay/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.0/lib/cocoapods/project.rb:326:in `realpath'
    /Users/GetemJay/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.0/lib/cocoapods/project.rb:326:in `realpath'
    /Users/GetemJay/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.0/lib/cocoapods/project.rb:326:in `reference_for_path'
    /Users/GetemJay/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.0/lib/cocoapods/project.rb:269:in `add_file_reference'
    /Users/GetemJay/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.0/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:228:in `block (2 levels) in add_file_accessors_paths_to_pods_group'
    /Users/GetemJay/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.0/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:227:in `map'
    /Users/GetemJay/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.0/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:227:in `block in add_file_accessors_paths_to_pods_group'
    /Users/GetemJay/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.0/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:217:in `each'
    /Users/GetemJay/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.0/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:217:in `flat_map'
    /Users/GetemJay/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.0/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:217:in `add_file_accessors_paths_to_pods_group'
    /Users/GetemJay/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.0/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:109:in `block in add_frameworks_bundles'
    /Users/GetemJay/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.0/lib/cocoapods/user_interface.rb:149:in `message'
    /Users/GetemJay/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.0/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:108:in `add_frameworks_bundles'
    /Users/GetemJay/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.0/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:50:in `install!'
    /Users/GetemJay/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.0/lib/cocoapods/installer/xcode/pods_project_generator.rb:102:in `block in install_file_references'
    /Users/GetemJay/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.0/lib/cocoapods/user_interface.rb:149:in `message'
    /Users/GetemJay/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.0/lib/cocoapods/installer/xcode/pods_project_generator.rb:100:in `install_file_references'
    /Users/GetemJay/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.0/lib/cocoapods/installer/xcode/single_pods_project_generator.rb:17:in `generate!'
    /Users/GetemJay/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.0/lib/cocoapods/installer.rb:314:in `block in create_and_save_projects'
    /Users/GetemJay/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.0/lib/cocoapods/user_interface.rb:64:in `section'
    /Users/GetemJay/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.0/lib/cocoapods/installer.rb:309:in `create_and_save_projects'
    /Users/GetemJay/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.0/lib/cocoapods/installer.rb:301:in `generate_pods_project'
    /Users/GetemJay/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.0/lib/cocoapods/installer.rb:180:in `integrate'
    /Users/GetemJay/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.0/lib/cocoapods/installer.rb:167:in `install!'
    /Users/GetemJay/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.0/lib/cocoapods/command/install.rb:52:in `run'
    /Users/GetemJay/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Users/GetemJay/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.0/lib/cocoapods/command.rb:52:in `run'
    /Users/GetemJay/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.0/bin/pod:55:in `<top (required)>'
    /Users/GetemJay/.rvm/gems/ruby-3.0.0/bin/pod:23:in `load'
    /Users/GetemJay/.rvm/gems/ruby-3.0.0/bin/pod:23:in `<main>'
    ```

### Stack

```
   CocoaPods : 1.11.0
        Ruby : ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin20]
    RubyGems : 3.2.3
        Host : macOS 11.4 (20F71)
       Xcode : 13.0 (13A5192j)
         Git : git version 2.31.1
Ruby lib dir : /Users/GetemJay/.rvm/rubies/ruby-3.0.0/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /Users/GetemJay/.rvm/gems/ruby-3.0.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
platform :ios, '10.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
```

**Comment by dnkoutso** [comment]
Please file an issue on the Flutter github repo as it seems related to Flutter integration.

Alternatively please remove Flutter and provide a sample app that demonstrates the issue.
