### ISSUE TITLE
pod install error with cocoa pods keys in Pod file

### ISSUE THREAD

**Issue by subhajit-dine** [CocoaPods/CocoaPods#10917]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace these two lines with what you did.  
e.g. Run `pod install`

## What did you expect to happen?

ℹ Please replace these two lines with what you expected to happen.  
e.g. Install all pod dependencies correctly.

### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.11.0
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.2.26
        Host : Mac OS X 10.15.6 (19G2021)
       Xcode : 12.4 (12D4e)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-keys        : 2.2.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0

NoMethodError - undefined method `[]' for false:FalseClass
/Library/Ruby/Gems/2.6.0/gems/cocoapods-keys-2.2.1/lib/keyring.rb:14:in `from_hash'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-keys-2.2.1/lib/keyring_liberator.rb:66:in `get_keyring_at_path'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-keys-2.2.1/lib/keyring_liberator.rb:60:in `block in get_all_keyrings'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-keys-2.2.1/lib/keyring_liberator.rb:59:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-keys-2.2.1/lib/keyring_liberator.rb:59:in `get_all_keyrings'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-keys-2.2.1/lib/keyring_liberator.rb:28:in `get_current_keyring'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-keys-2.2.1/lib/preinstaller.rb:23:in `setup'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-keys-2.2.1/lib/plugin.rb:17:in `setup'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-keys-2.2.1/lib/plugin.rb:11:in `block in singleton class'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/hooks_manager.rb:122:in `block (3 levels) in run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/user_interface.rb:149:in `message'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/hooks_manager.rb:116:in `block (2 levels) in run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/hooks_manager.rb:115:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/hooks_manager.rb:115:in `block in run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/user_interface.rb:149:in `message'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/hooks_manager.rb:114:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/installer.rb:606:in `run_plugins_pre_install_hooks'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/installer.rb:226:in `block in prepare'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/user_interface.rb:149:in `message'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/installer.rb:222:in `prepare'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/installer.rb:160:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:25:in `load'
/usr/local/bin/pod:25:in `<main>'


ℹ Please replace these two lines with of what happened instead.  
error. Pod not installed

## CocoaPods Environment

ℹ Please replace these two lines with the output of `pod env`.


## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

**Comment by dnkoutso** [comment]
Seems like an issue with cocoapods-keys plugin and latest cocoapods release (maybe even 1.10.x). Transferring there.

**Comment by dnkoutso** [comment]
Oh I cant transfer due to it being in a separate org. Can you file an issue in https://github.com/orta/cocoapods-keys and then close this one?

**Comment by subhajit-dine** [comment]
Can you please let me know what can be the possible solution for this. I have filed the issue at https://github.com/orta/cocoapods-keys .

**Comment by dnkoutso** [comment]
I am not sure unfortunately. Looks like a bug or something that the plugin does not handle properly, particularly to your keychain.

I looked at the stacktrace more closely and to be honest this doesn't look like an integration issue of the plugin with cocoapods.

You'll have to dig into the sources of the plugin to perhaps debug it and open a PR in that repo to fix it or workaround it.
