### ISSUE TITLE
cocoapods 1.11.0 throws Unicode Normalization not appropriate for ASCII-8BIT on pod install'

### ISSUE THREAD

**Issue by vkormushkin** [CocoaPods/CocoaPods#10939]
## What did you do?

1. Do not have any pod with non Ascii symbols in the name in the Podfile
2. Set some ascii locale: 'export LC_ALL=C'
3. run 'pod install'

## What did you expect to happen?

pod install running successfully 

## What happened instead?

WARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
    Consider adding the following to ~/.profile:

    export LANG=en_US.UTF-8

Traceback (most recent call last):
	11: from /usr/local/bin/pod:23:in `<main>'
	10: from /usr/local/bin/pod:23:in `load'
	 9: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/bin/pod:55:in `<top (required)>'
	 8: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/command.rb:52:in `run'
	 7: from /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
	 6: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/command/install.rb:46:in `run'
	 5: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/command.rb:160:in `verify_podfile_exists!'
	 4: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/config.rb:205:in `podfile'
	 3: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/config.rb:226:in `podfile_path'
	 2: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/config.rb:166:in `installation_root'
	 1: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/config.rb:166:in `unicode_normalize'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/unicode_normalize/normalize.rb:141:in `normalize': Unicode Normalization not appropriate for ASCII-8BIT (Encoding::CompatibilityError)
	13: from /usr/local/bin/pod:23:in `<main>'
	12: from /usr/local/bin/pod:23:in `load'
	11: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/bin/pod:55:in `<top (required)>'
	10: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/command.rb:52:in `run'
	 9: from /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:324:in `run'
	 8: from /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:337:in `rescue in run'
	 7: from /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:396:in `handle_exception'
	 6: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/command.rb:66:in `report_error'
	 5: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/user_interface/error_report.rb:30:in `report'
	 4: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/user_interface/error_report.rb:105:in `markdown_podfile'
	 3: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/config.rb:226:in `podfile_path'
	 2: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/config.rb:166:in `installation_root'
	 1: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/config.rb:166:in `unicode_normalize'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/unicode_normalize/normalize.rb:141:in `normalize': Unicode Normalization not appropriate for ASCII-8BIT (Encoding::CompatibilityError)

## CocoaPods Environment

pod env also fails with the above error.

##Comments

I do understand that cocoapods warns that UTF-8 locale is required but as per my understanding it is required for non-ascii pod name (Chinese for example). So if Podfile does not contain such dependencies all pod commands should work even with ascii locale being set. And it was true in cocoapods 1.10.2 but starting 1.11 literally all pod commands fail with the above exception.

It seems like such change may cause by this PR but exact reason is not clear for me - https://github.com/CocoaPods/CocoaPods/pull/10364/ 

I came across this issue while investigating failing integration test on CI, so it may affect other people who invoke pod commands as part of their CI pipeline.

**Comment by dnkoutso** [comment]
cc @igor-makarov any thoughts here?

**Comment by dnkoutso** [comment]
I can definitely reproduce, its possible that this error more strict now and maybe it shouldnt be.

**Comment by dnkoutso** [comment]
yeah I am not quite sure what to do for this issue. CocoaPods seems to now require UTF8 encoding.

It "used" to work but now its more strict. Will let this one sit for a bit and see if anyone can weigh in.

**Comment by ihopeyouwin** [comment]
got the same issue, after upgrading 1.10.2 -> 1.11.2 . Downgrading afterwards helped though

**Comment by apple-ihack-geek** [comment]
I'm having this issue now too on a brand new install.  I tried adding a bunch of stuff to my build script too and I still am having the issue, what's going on?

> 	LANG=en_US.UTF-8			# for cocoapods
	LANGUAGE=en_US.UFT-8
	LC_ALL=en_US.UFT-8

**Comment by chris-hatton** [comment]
Blocked in this for hours... I can try setting these locales but on my M1 Mac Xcode does not respect `.zshrc`, `.zprofile` or `.profile`... so I'm not sure how anyone is using Cocoapods with Xcode 13.4 on an M1 Mac/Monterey at all.

**Comment by chris-hatton** [comment]
🙅  The hardening of this requirements breaks [Kotlin Multiplatform](https://kotlinlang.org/docs/multiplatform.html)'s [Cocoapods integration](https://kotlinlang.org/docs/native-cocoapods.html), in a hard to resolve way:

The way this integration works, involves calling `pod install` from within an Xcode run-script build phase.  It's notoriously awkward to control environment variables from inside Xcode's script shell, and it doesn't set these `LANG` variables.

Hence, the integration breaks.  I don't see the benefit of hardening this requirement; indeed, it seems like an irresponsible maintenance decision that causes more problems for users than it resolves.  Burned a day and counting so far...

**Comment by Jozott00** [comment]
Probably not the most common case, but I was using GraalVM's truffleruby as ruby runtime. After switching to another one, it worked.

**Comment by jayptl-me** [comment]
I am having the same issue since last one year now!! Havn't found a way out...Need Help!!!!
`pod install     
    WARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
    Consider adding the following to ~/.profile:

    export LANG=en_US.UTF-8
    
/Users/jayptl/src/homebrew/Cellar/ruby/3.3.3/lib/ruby/3.3.0/unicode_normalize/normalize.rb:141:in `normalize': Unicode Normalization not appropriate for ASCII-8BIT (Encoding::CompatibilityError)
        from /Users/jayptl/src/homebrew/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/config.rb:167:in `unicode_normalize'
        from /Users/jayptl/src/homebrew/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/config.rb:167:in `installation_root'
        from /Users/jayptl/src/homebrew/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/config.rb:227:in `podfile_path'
        from /Users/jayptl/src/homebrew/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/user_interface/error_report.rb:105:in `markdown_podfile'
        from /Users/jayptl/src/homebrew/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/user_interface/error_report.rb:30:in `report'
        from /Users/jayptl/src/homebrew/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:66:in `report_error'
        from /Users/jayptl/src/homebrew/lib/ruby/gems/3.3.0/gems/claide-1.1.0/lib/claide/command.rb:396:in `handle_exception'
        from /Users/jayptl/src/homebrew/lib/ruby/gems/3.3.0/gems/claide-1.1.0/lib/claide/command.rb:337:in `rescue in run'
        from /Users/jayptl/src/homebrew/lib/ruby/gems/3.3.0/gems/claide-1.1.0/lib/claide/command.rb:324:in `run'
        from /Users/jayptl/src/homebrew/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:52:in `run'
        from /Users/jayptl/src/homebrew/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/bin/pod:55:in `<top (required)>'
        from /Users/jayptl/src/homebrew/lib/ruby/gems/3.3.0/bin/pod:25:in `load'
        from /Users/jayptl/src/homebrew/lib/ruby/gems/3.3.0/bin/pod:25:in `<main>'
/Users/jayptl/src/homebrew/Cellar/ruby/3.3.3/lib/ruby/3.3.0/unicode_normalize/normalize.rb:141:in `normalize': Unicode Normalization not appropriate for ASCII-8BIT (Encoding::CompatibilityError)
        from /Users/jayptl/src/homebrew/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/config.rb:167:in `unicode_normalize'
        from /Users/jayptl/src/homebrew/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/config.rb:167:in `installation_root'
        from /Users/jayptl/src/homebrew/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/config.rb:227:in `podfile_path'
        from /Users/jayptl/src/homebrew/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/config.rb:206:in `podfile'
        from /Users/jayptl/src/homebrew/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:160:in `verify_podfile_exists!'
        from /Users/jayptl/src/homebrew/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/command/install.rb:46:in `run'
        from /Users/jayptl/src/homebrew/lib/ruby/gems/3.3.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
        from /Users/jayptl/src/homebrew/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:52:in `run'
        from /Users/jayptl/src/homebrew/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/bin/pod:55:in `<top (required)>'
        from /Users/jayptl/src/homebrew/lib/ruby/gems/3.3.0/bin/pod:25:in `load'
        from /Users/jayptl/src/homebrew/lib/ruby/gems/3.3.0/bin/pod:25:in `<main>'`
        
        even while running the project on ios throw same error!!

**Comment by monfresh** [comment]
What is the result of this command in your terminal:

```
echo $LANG
```

If it is not `en_US.UTF-8`, then it sounds like something is setting it to `ASCII-8BIT`. Perhaps you have a line such as  `export LANG=en_US.ASCII-8BIT` in one of your shell startup files? Look in these files:

~/.bash_profile
~/.profile
~/.bashrc
~/.zshrc
~/.zprofile
~/.zlogin

**Comment by monfresh** [comment]
Also, your Homebrew location is very odd. On a Mac, it should either be in `/usr/local` for Intel Macs, or in `opt/homebrew` for Apple SIlicon Macs. But yours is in `~/src/homebrew/`. I recommend uninstalling and reinstalling Homebrew the normal way.

**Comment by jayptl-me** [comment]
src is a custom path I chose tk install homebrew...and even trying to install it via gem throws the same error it's not about the path I am sure bout that!

**Comment by HereIsNils** [comment]
The issue is still present in cocoapods 1.15.2 and 1.15.2_1.
I encountered it, when trying to use capacitor.js to create an iOS project. 

` pod install
    WARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
    Consider adding the following to ~/.profile:

    export LANG=en_US.UTF-8
    
/opt/homebrew/Cellar/ruby/3.3.5/lib/ruby/3.3.0/unicode_normalize/normalize.rb:141:in `normalize': Unicode Normalization not appropriate for ASCII-8BIT (Encoding::CompatibilityError)
	from /opt/homebrew/Cellar/cocoapods/1.15.2_1/libexec/gems/cocoapods-1.15.2/lib/cocoapods/config.rb:167:in `unicode_normalize'
	from /opt/homebrew/Cellar/cocoapods/1.15.2_1/libexec/gems/cocoapods-1.15.2/lib/cocoapods/config.rb:167:in `installation_root'
	from /opt/homebrew/Cellar/cocoapods/1.15.2_1/libexec/gems/cocoapods-1.15.2/lib/cocoapods/config.rb:227:in `podfile_path'
	from /opt/homebrew/Cellar/cocoapods/1.15.2_1/libexec/gems/cocoapods-1.15.2/lib/cocoapods/user_interface/error_report.rb:105:in `markdown_podfile'
	from /opt/homebrew/Cellar/cocoapods/1.15.2_1/libexec/gems/cocoapods-1.15.2/lib/cocoapods/user_interface/error_report.rb:30:in `report'
	from /opt/homebrew/Cellar/cocoapods/1.15.2_1/libexec/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:66:in `report_error'
	from /opt/homebrew/Cellar/cocoapods/1.15.2_1/libexec/gems/claide-1.1.0/lib/claide/command.rb:396:in `handle_exception'
	from /opt/homebrew/Cellar/cocoapods/1.15.2_1/libexec/gems/claide-1.1.0/lib/claide/command.rb:337:in `rescue in run'
	from /opt/homebrew/Cellar/cocoapods/1.15.2_1/libexec/gems/claide-1.1.0/lib/claide/command.rb:324:in `run'
	from /opt/homebrew/Cellar/cocoapods/1.15.2_1/libexec/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:52:in `run'
	from /opt/homebrew/Cellar/cocoapods/1.15.2_1/libexec/gems/cocoapods-1.15.2/bin/pod:55:in `<top (required)>'
	from /opt/homebrew/Cellar/cocoapods/1.15.2_1/libexec/bin/pod:25:in `load'
	from /opt/homebrew/Cellar/cocoapods/1.15.2_1/libexec/bin/pod:25:in `<main>'
/opt/homebrew/Cellar/ruby/3.3.5/lib/ruby/3.3.0/unicode_normalize/normalize.rb:141:in `normalize': Unicode Normalization not appropriate for ASCII-8BIT (Encoding::CompatibilityError)
	from /opt/homebrew/Cellar/cocoapods/1.15.2_1/libexec/gems/cocoapods-1.15.2/lib/cocoapods/config.rb:167:in `unicode_normalize'
	from /opt/homebrew/Cellar/cocoapods/1.15.2_1/libexec/gems/cocoapods-1.15.2/lib/cocoapods/config.rb:167:in `installation_root'
	from /opt/homebrew/Cellar/cocoapods/1.15.2_1/libexec/gems/cocoapods-1.15.2/lib/cocoapods/config.rb:227:in `podfile_path'
	from /opt/homebrew/Cellar/cocoapods/1.15.2_1/libexec/gems/cocoapods-1.15.2/lib/cocoapods/config.rb:206:in `podfile'
	from /opt/homebrew/Cellar/cocoapods/1.15.2_1/libexec/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:160:in `verify_podfile_exists!'
	from /opt/homebrew/Cellar/cocoapods/1.15.2_1/libexec/gems/cocoapods-1.15.2/lib/cocoapods/command/install.rb:46:in `run'
	from /opt/homebrew/Cellar/cocoapods/1.15.2_1/libexec/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
	from /opt/homebrew/Cellar/cocoapods/1.15.2_1/libexec/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:52:in `run'
	from /opt/homebrew/Cellar/cocoapods/1.15.2_1/libexec/gems/cocoapods-1.15.2/bin/pod:55:in `<top (required)>'
	from /opt/homebrew/Cellar/cocoapods/1.15.2_1/libexec/bin/pod:25:in `load'
	from /opt/homebrew/Cellar/cocoapods/1.15.2_1/libexec/bin/pod:25:in `<main>'
`

The output of `echo @LANG` is en_US.UTF-8
