### ISSUE TITLE
M1 - Can't install pods after updating cocoapods version

### ISSUE THREAD

**Issue by iarmankhan** [CocoaPods/CocoaPods#11008]
### Command

```
/usr/local/bin/pod install --repo-update
```

### Report

* What did you do?
-- Updated cocoapods version from 1.10 to 1.11.2
-- I've already installed ffi package using this comman
`sudo arch -x86_64 gem install ffi`

* running pods like this gives me following error

```
arch -x86_64 pod install

arch: posix_spawnp: pod: Bad CPU type in executable
```

* What did you expect to happen?
-- to install pods

* What happened instead?
-- Got this error

### Stack

```
   CocoaPods : 1.11.2
        Ruby : ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [arm64-darwin20]
    RubyGems : 3.1.4
        Host : macOS 11.6 (20G165)
       Xcode : 13.0 (13A233)
         Git : git version 2.30.1 (Apple Git-130)
Ruby lib dir : /Users/yash/.asdf/installs/ruby/2.7.2/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'TilesMart' do

  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'TilesMartTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
#   use_flipper!({ 'Flipper' => '0.87.0', 'Flipper-Folly' => '2.5.3', 'Flipper-RSocket' => '1.3.1' })
    use_flipper!()

  # pods for icons

  post_install do |installer|
     react_native_post_install(installer)

     # Apple Silicon builds require a library path tweak for Swift library discovery or "symbol not found" for swift things
     installer.aggregate_targets.each do |aggregate_target|
         aggregate_target.user_project.native_targets.each do |target|
            target.build_configurations.each do |config|
              config.build_settings['LIBRARY_SEARCH_PATHS'] = ['$(SDKROOT)/usr/lib/swift', '$(inherited)']
            end
         end
         aggregate_target.user_project.save
     end

     # exclude arm64 arch - only if you're building in m1
     # Flipper requires a crude patch to bump up iOS deployment target, or "error: thread-local storage is not supported for the current target"
     # I'm not aware of any other way to fix this one other than bumping iOS deployment target to match react-native (iOS 11 now)
     installer.pods_project.targets.each do |target|
         target.build_configurations.each do |config|
             config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
             config.build_settings["ONLY_ACTIVE_ARCH"] = "NO"
         end
     end

      # ...but if you bump iOS deployment target, Flipper barfs again "Time.h:52:17: error: typedef redefinition with different types"
      # We need to make one crude patch to RCT-Folly - set `__IPHONE_10_0` to our iOS target + 1
      # https://github.com/facebook/flipper/issues/834 - 84 comments and still going...
      `sed -i -e  $'s/__IPHONE_10_0/__IPHONE_12_0/' Pods/RCT-Folly/folly/portability/Time.h`
   end
end
```

### Error

```
LoadError - dlopen(/Users/yash/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/ffi-1.15.4/lib/ffi_c.bundle, 9): no suitable image found.  Did find:
	/Users/yash/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/ffi-1.15.4/lib/ffi_c.bundle: mach-o, but wrong architecture
	/Users/yash/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/ffi-1.15.4/lib/ffi_c.bundle: mach-o, but wrong architecture - /Users/yash/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/ffi-1.15.4/lib/ffi_c.bundle
/Users/yash/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/Users/yash/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/Users/yash/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/ffi-1.15.4/lib/ffi.rb:5:in `rescue in <top (required)>'
/Users/yash/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/ffi-1.15.4/lib/ffi.rb:2:in `<top (required)>'
/Users/yash/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/Users/yash/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/Users/yash/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/ethon-0.14.0/lib/ethon.rb:3:in `<top (required)>'
/Users/yash/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/Users/yash/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/Users/yash/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
/Users/yash/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/Users/yash/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/Users/yash/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/cdn_source.rb:440:in `download_typhoeus_impl_async'
/Users/yash/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/cdn_source.rb:372:in `download_and_save_with_retries_async'
/Users/yash/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/cdn_source.rb:365:in `download_file_async'
/Users/yash/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/cdn_source.rb:338:in `download_file'
/Users/yash/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/cdn_source.rb:78:in `deprecated_local_podspecs'
/Users/yash/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/cdn_source.rb:60:in `preheat_existing_files'
/Users/yash/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/cdn_source.rb:257:in `update'
/Users/yash/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/lib/cocoapods/sources_manager.rb:144:in `block (3 levels) in update'
/Users/yash/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:64:in `section'
/Users/yash/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/lib/cocoapods/sources_manager.rb:143:in `block (2 levels) in update'
/Users/yash/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/lib/cocoapods/sources_manager.rb:142:in `each'
/Users/yash/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/lib/cocoapods/sources_manager.rb:142:in `block in update'
/Users/yash/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/lib/cocoapods/sources_manager.rb:140:in `open'
/Users/yash/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/lib/cocoapods/sources_manager.rb:140:in `update'
/Users/yash/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:145:in `block in update_repositories'
/Users/yash/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:143:in `each'
/Users/yash/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:143:in `update_repositories'
/Users/yash/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:237:in `block in resolve_dependencies'
/Users/yash/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:64:in `section'
/Users/yash/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:236:in `resolve_dependencies'
/Users/yash/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:161:in `install!'
/Users/yash/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/lib/cocoapods/command/install.rb:52:in `run'
/Users/yash/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/yash/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in `run'
/Users/yash/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by dnkoutso** [comment]
Please see https://stackoverflow.com/questions/64901180/running-cocoapods-on-apple-silicon-m1

This is not an issue we can generally fix and seems like a gem installatione/execution environment issue.
