### ISSUE TITLE
pod install crashes with weird html (react native)

### ISSUE THREAD

**Issue by Abhishek12345679** [CocoaPods/CocoaPods#11187]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

run
```
pod install
```
and

```
pod install --repo-update
```

## What did you expect to happen?

Install all the dependencies from the podfile successfully.

## What happened instead?

```
Using Expo modules
Adding a custom script phase for Pod RNFBApp: [RNFB] Core Configuration
Auto-linking React Native modules for target `HelloWorld`: RNBootSplash, RNCAsyncStorage, RNCMaskedView, RNFBApp, RNFBAuth, RNFBFirestore, RNFBStorage, RNGestureHandler, RNScreens, react-native-document-picker, react-native-geolocation-service, react-native-razorpay, react-native-safe-area-context, react-native-segmented-control, and react-native-webview
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `RCT-Folly` from `../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`
Fetching podspec for `boost` from `../node_modules/react-native/third-party-podspecs/boost.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`

[!] NPM package '@react-native-firebase/storage' depends on '@react-native-firebase/app' v10.8.1 but found v14.3.0, this might cause build issues or runtime crashes.

[!] NPM package '@react-native-firebase/storage' depends on '@react-native-firebase/app' v10.8.1 but found v14.3.0, this might cause build issues or runtime crashes.
/opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/source/metadata.rb:15:in `initialize': undefined method `with_indifferent_access' for "<meta name=\\"viewport\\" content=\\"width=device-width,initial-scale=1.0,maximum-scale=1.0\\" /><style>body{margin:0px;padding:0px;}iframe{width:100%;height:100%}</style><iframe src=\\"http://www.airtel.in/dot/\\" width=\\"100%\\" height=\\"100%\\" frameborder=0></iframe>":String (NoMethodError)
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/source/metadata.rb:28:in `new'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/source/metadata.rb:28:in `from_file'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/source.rb:441:in `refresh_metadata'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/cdn_source.rb:56:in `refresh_metadata'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/source.rb:31:in `initialize'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/cdn_source.rb:30:in `initialize'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/source/manager.rb:315:in `new'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/source/manager.rb:315:in `block in source_from_path'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/source/manager.rb:322:in `source_from_path'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/source/manager.rb:331:in `block in aggregate_with_repos'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/source/manager.rb:331:in `map'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/source/manager.rb:331:in `aggregate_with_repos'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/source/manager.rb:26:in `aggregate'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/source/manager.rb:60:in `all'
	from /opt/homebrew/Cellar/cocoapods/1.11.2_1/libexec/gems/cocoapods-1.11.2/lib/cocoapods/user_interface/error_report.rb:173:in `repo_information'
	from /opt/homebrew/Cellar/cocoapods/1.11.2_1/libexec/gems/cocoapods-1.11.2/lib/cocoapods/user_interface/error_report.rb:77:in `stack'
	from /opt/homebrew/Cellar/cocoapods/1.11.2_1/libexec/gems/cocoapods-1.11.2/lib/cocoapods/user_interface/error_report.rb:24:in `report'
	from /opt/homebrew/Cellar/cocoapods/1.11.2_1/libexec/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:66:in `report_error'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/claide-1.1.0/lib/claide/command.rb:396:in `handle_exception'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/claide-1.1.0/lib/claide/command.rb:337:in `rescue in run'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/claide-1.1.0/lib/claide/command.rb:324:in `run'
	from /opt/homebrew/Cellar/cocoapods/1.11.2_1/libexec/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in `run'
	from /opt/homebrew/Cellar/cocoapods/1.11.2_1/libexec/gems/cocoapods-1.11.2/bin/pod:55:in `<top (required)>'
	from /opt/homebrew/Cellar/cocoapods/1.11.2_1/libexec/bin/pod:23:in `load'
	from /opt/homebrew/Cellar/cocoapods/1.11.2_1/libexec/bin/pod:23:in `<main>'
/opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/source/metadata.rb:15:in `initialize': undefined method `with_indifferent_access' for "<meta name=\\"viewport\\" content=\\"width=device-width,initial-scale=1.0,maximum-scale=1.0\\" /><style>body{margin:0px;padding:0px;}iframe{width:100%;height:100%}</style><iframe src=\\"http://www.airtel.in/dot/\\" width=\\"100%\\" height=\\"100%\\" frameborder=0></iframe>":String (NoMethodError)
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/source/metadata.rb:28:in `new'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/source/metadata.rb:28:in `from_file'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/source.rb:441:in `refresh_metadata'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/cdn_source.rb:56:in `refresh_metadata'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/source.rb:31:in `initialize'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/cdn_source.rb:30:in `initialize'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/source/manager.rb:315:in `new'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/source/manager.rb:315:in `block in source_from_path'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/source/manager.rb:322:in `source_from_path'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/source/manager.rb:331:in `block in aggregate_with_repos'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/source/manager.rb:331:in `map'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/source/manager.rb:331:in `aggregate_with_repos'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/source/manager.rb:26:in `aggregate'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/source/manager.rb:60:in `all'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/source/manager.rb:393:in `source_with_url'
	from /opt/homebrew/Cellar/cocoapods/1.11.2_1/libexec/gems/cocoapods-1.11.2/lib/cocoapods/sources_manager.rb:22:in `find_or_create_source_with_url'
	from /opt/homebrew/Cellar/cocoapods/1.11.2_1/libexec/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:178:in `block in sources'
	from /opt/homebrew/Cellar/cocoapods/1.11.2_1/libexec/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:177:in `map'
	from /opt/homebrew/Cellar/cocoapods/1.11.2_1/libexec/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:177:in `sources'
	from /opt/homebrew/Cellar/cocoapods/1.11.2_1/libexec/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:1077:in `block in resolve_dependencies'
	from /opt/homebrew/Cellar/cocoapods/1.11.2_1/libexec/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:64:in `section'
	from /opt/homebrew/Cellar/cocoapods/1.11.2_1/libexec/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:1076:in `resolve_dependencies'
	from /opt/homebrew/Cellar/cocoapods/1.11.2_1/libexec/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
	from /opt/homebrew/Cellar/cocoapods/1.11.2_1/libexec/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:416:in `analyze'
	from /opt/homebrew/Cellar/cocoapods/1.11.2_1/libexec/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:241:in `block in resolve_dependencies'
	from /opt/homebrew/Cellar/cocoapods/1.11.2_1/libexec/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:64:in `section'
	from /opt/homebrew/Cellar/cocoapods/1.11.2_1/libexec/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:240:in `resolve_dependencies'
	from /opt/homebrew/Cellar/cocoapods/1.11.2_1/libexec/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:161:in `install!'
	from /opt/homebrew/Cellar/cocoapods/1.11.2_1/libexec/gems/cocoapods-1.11.2/lib/cocoapods/command/install.rb:52:in `run'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
	from /opt/homebrew/Cellar/cocoapods/1.11.2_1/libexec/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in `run'
	from /opt/homebrew/Cellar/cocoapods/1.11.2_1/libexec/gems/cocoapods-1.11.2/bin/pod:55:in `<top (required)>'
	from /opt/homebrew/Cellar/cocoapods/1.11.2_1/libexec/bin/pod:23:in `load'
	from /opt/homebrew/Cellar/cocoapods/1.11.2_1/libexec/bin/pod:23:in `<main>'

```

## CocoaPods Environment

Running the `pod env` results in the same error as above

**Comment by dnkoutso** [comment]
Please file a bug with ReactNative repo or produce a sample app without ReactNative.
