### ISSUE TITLE
Error on adding swift package to project with cocoapods `post_install` hook

### ISSUE THREAD

**Issue by soumyamahunt** [CocoaPods/CocoaPods#11198]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I tried to add swift packages to pods project in `post_install` hook but got the following error on running `pod install`:
```
Analyzing dependencies
Downloading dependencies
Generating Pods project

[!] Automatically assigning platform `iOS` with version `15.2` on target `Example` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface/error_report.rb:34:in `force_encoding': can't modify frozen String (FrozenError)
        from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface/error_report.rb:34:in `report'
        from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:66:in `report_error'
        from /Library/Ruby/Gems/2.6.0/gems/claide-1.1.0/lib/claide/command.rb:396:in `handle_exception'
        from /Library/Ruby/Gems/2.6.0/gems/claide-1.1.0/lib/claide/command.rb:337:in `rescue in run'
        from /Library/Ruby/Gems/2.6.0/gems/claide-1.1.0/lib/claide/command.rb:324:in `run'
        from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in `run'
        from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/bin/pod:55:in `<top (required)>'
        from /usr/local/bin/pod:23:in `load'
        from /usr/local/bin/pod:23:in `<main>'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.21.0/lib/xcodeproj/project/object/helpers/groupable_helper.rb:19:in `parent': [Xcodeproj] Consistency issue: no parent for object `Algorithms`: `` (RuntimeError)
        from /Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.21.0/lib/xcodeproj/project/object/build_file.rb:77:in `ascii_plist_annotation'
        from /Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.21.0/lib/xcodeproj/project/object.rb:410:in `nested_object_for_hash'
        from /Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.21.0/lib/xcodeproj/project/object.rb:395:in `block (2 levels) in to_hash_as'
        from /Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.21.0/lib/xcodeproj/project/object.rb:395:in `map'
        from /Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.21.0/lib/xcodeproj/project/object.rb:395:in `block in to_hash_as'
        from /Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.21.0/lib/xcodeproj/project/object.rb:393:in `each'
        from /Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.21.0/lib/xcodeproj/project/object.rb:393:in `to_hash_as'
        from /Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.21.0/lib/xcodeproj/project/object.rb:421:in `to_ascii_plist'
        from /Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.21.0/lib/xcodeproj/project.rb:298:in `block in to_ascii_plist'
        from /Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.21.0/lib/xcodeproj/project.rb:296:in `each'
        from /Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.21.0/lib/xcodeproj/project.rb:296:in `to_ascii_plist'
        from /Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.21.0/lib/xcodeproj/project.rb:365:in `block in save'
        from /Library/Ruby/Gems/2.6.0/gems/atomos-0.1.3/lib/atomos.rb:21:in `block in atomic_write'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tempfile.rb:295:in `open'
        from /Library/Ruby/Gems/2.6.0/gems/atomos-0.1.3/lib/atomos.rb:17:in `atomic_write'
        from /Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.21.0/lib/xcodeproj/project.rb:364:in `save'
        from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/xcode/pods_project_generator/pods_project_writer.rb:83:in `block (2 levels) in save_projects'
        from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:149:in `message'
        from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/xcode/pods_project_generator/pods_project_writer.rb:82:in `block in save_projects'
        from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/xcode/pods_project_generator/pods_project_writer.rb:80:in `each'
        from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/xcode/pods_project_generator/pods_project_writer.rb:80:in `save_projects'
        from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/xcode/pods_project_generator/pods_project_writer.rb:63:in `write!'
        from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:330:in `block in create_and_save_projects'
        from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:64:in `section'
        from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:309:in `create_and_save_projects'
        from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:301:in `generate_pods_project'
        from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:180:in `integrate'
        from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:167:in `install!'
        from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command/install.rb:52:in `run'
        from /Library/Ruby/Gems/2.6.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
        from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in `run'
        from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/bin/pod:55:in `<top (required)>'
        from /usr/local/bin/pod:23:in `load'
        from /usr/local/bin/pod:23:in `<main>'
```

## What did you expect to happen?

I expected the swift package will be added to all the pod targets.

## What happened instead?

`pod install` gave error for line: `target.frameworks_build_phase.files.append swift_package_build_file`, I am using this line to add swift package linking to target framework build phases. Removing this line does make `pod install` run successfully without the swift package linking  phase.

### Stack

```
   CocoaPods : 1.11.2
        Ruby : ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.x86_64-darwin21]
    RubyGems : 3.0.3.1
        Host : macOS 12.2.1 (21D62)
       Xcode : 13.2.1 (13C100)
         Git : git version 2.32.0 (Apple Git-132)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ 473d7cf434dea6626d2a9c5667d078b05fb65753

               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-archive                  : 0.0.2
cocoapods-deintegrate              : 1.0.5
cocoapods-packager                 : 1.5.0
cocoapods-plugins                  : 1.0.0
cocoapods-rome                     : 1.0.1
cocoapods-search                   : 1.0.1
cocoapods-stats                    : 1.1.0
cocoapods-trunk                    : 1.6.0
cocoapods-try                      : 1.2.0
cocoapods-user-defined-build-types : 0.0.7
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example
  pod 'Alamofire'
end

post_install do |installer|
  swift_package = installer.pods_project.new Xcodeproj::Project::Object::XCRemoteSwiftPackageReference.isa
  swift_package.repositoryURL = "https://github.com/apple/swift-algorithms.git"
  swift_package.requirement = {
    "kind" => "upToNextMajorVersion",
    "minimumVersion" => "1.0.0"
  }

  swift_package_product = installer.pods_project.new Xcodeproj::Project::Object::XCSwiftPackageProductDependency.isa
  swift_package_product.package = swift_package
  swift_package_product.product_name = "Algorithms"

  swift_package_build_file = installer.pods_project.new Xcodeproj::Project::Object::PBXBuildFile.isa
  swift_package_build_file.product_ref = swift_package_product

  installer.pods_project.root_object.package_references.append swift_package
  installer.pods_project.native_targets.each do |target|
    target.frameworks_build_phase.files.append swift_package_build_file
    target.package_product_dependencies.append swift_package_product
  end
end
```

## Project that demonstrates the issue

Sample project is hosted in [this](https://github.com/soumyamahunt/coacoapods_swift_package) repo in `Example` directory.

**Comment by soumyamahunt** [comment]
Adding a referrer of `PBXGroup` type to the build file resolved this issue, however I am still unable to build the project. Closing this issue and created #11214 with all the details.
