### ISSUE TITLE
Error on installing pod

### ISSUE THREAD

**Issue by jackcsk** [CocoaPods/CocoaPods#1123]
### Stack

```
   CocoaPods : 0.19.1
        Ruby : ruby 1.8.7 (2012-02-08 patchlevel 358) [universal-darwin12.0]
    RubyGems : 1.3.6
        Host : Mac OS X 10.8.4 (12E55)
       Xcode : 4.6.3 (4H1503)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 52ea6fe5ea0c75e678c819122b1ac5a073f00a59
```
### Podfile

``` ruby
platform :ios
pod 'ASIHTTPRequest', '~1.8.1'
pod 'JSONKit', '~1.4'
pod 'Reachability', '~> 3.0.0'
```
### Error

```
ArgumentError - Illformed requirement `"~1.8.1"`
/Library/Ruby/Gems/1.8/gems/cocoapods-core-0.19.1/lib/cocoapods-core/requirement.rb:63:in `parse'
/Library/Ruby/Gems/1.8/gems/cocoapods-core-0.19.1/lib/cocoapods-core/vendor/requirement.rb:108:in `initialize'
/Library/Ruby/Gems/1.8/gems/cocoapods-core-0.19.1/lib/cocoapods-core/vendor/requirement.rb:108:in `map!'
/Library/Ruby/Gems/1.8/gems/cocoapods-core-0.19.1/lib/cocoapods-core/vendor/requirement.rb:108:in `initialize'
/Library/Ruby/Gems/1.8/gems/cocoapods-core-0.19.1/lib/cocoapods-core/requirement.rb:34:in `new'
/Library/Ruby/Gems/1.8/gems/cocoapods-core-0.19.1/lib/cocoapods-core/requirement.rb:34:in `create'
/Library/Ruby/Gems/1.8/gems/cocoapods-core-0.19.1/lib/cocoapods-core/dependency.rb:91:in `initialize'
/Library/Ruby/Gems/1.8/gems/cocoapods-core-0.19.1/lib/cocoapods-core/podfile/target_definition.rb:532:in `new'
/Library/Ruby/Gems/1.8/gems/cocoapods-core-0.19.1/lib/cocoapods-core/podfile/target_definition.rb:532:in `pod_dependencies'
/Library/Ruby/Gems/1.8/gems/cocoapods-core-0.19.1/lib/cocoapods-core/podfile/target_definition.rb:528:in `map'
/Library/Ruby/Gems/1.8/gems/cocoapods-core-0.19.1/lib/cocoapods-core/podfile/target_definition.rb:528:in `pod_dependencies'
/Library/Ruby/Gems/1.8/gems/cocoapods-core-0.19.1/lib/cocoapods-core/podfile/target_definition.rb:85:in `non_inherited_dependencies'
/Library/Ruby/Gems/1.8/gems/cocoapods-core-0.19.1/lib/cocoapods-core/podfile/target_definition.rb:78:in `dependencies'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `to_proc'
/Library/Ruby/Gems/1.8/gems/cocoapods-core-0.19.1/lib/cocoapods-core/podfile.rb:91:in `map'
/Library/Ruby/Gems/1.8/gems/cocoapods-core-0.19.1/lib/cocoapods-core/podfile.rb:91:in `dependencies'
/Library/Ruby/Gems/1.8/gems/cocoapods-0.19.1/lib/cocoapods/installer/analyzer.rb:142:in `generate_podfile_state'
/Library/Ruby/Gems/1.8/gems/cocoapods-0.19.1/lib/cocoapods/installer/analyzer.rb:51:in `analyze'
/Library/Ruby/Gems/1.8/gems/cocoapods-0.19.1/lib/cocoapods/installer.rb:167:in `analyze'
/Library/Ruby/Gems/1.8/gems/cocoapods-0.19.1/lib/cocoapods/installer.rb:92:in `resolve_dependencies'
/Library/Ruby/Gems/1.8/gems/cocoapods-0.19.1/lib/cocoapods/user_interface.rb:52:in `section'
/Library/Ruby/Gems/1.8/gems/cocoapods-0.19.1/lib/cocoapods/installer.rb:91:in `resolve_dependencies'
/Library/Ruby/Gems/1.8/gems/cocoapods-0.19.1/lib/cocoapods/installer.rb:84:in `install!'
/Library/Ruby/Gems/1.8/gems/cocoapods-0.19.1/lib/cocoapods/command/project.rb:40:in `run_install_with_update'
/Library/Ruby/Gems/1.8/gems/cocoapods-0.19.1/lib/cocoapods/command/project.rb:70:in `run'
/Library/Ruby/Gems/1.8/gems/claide-0.2.0/lib/claide.rb:535:in `run'
/Library/Ruby/Gems/1.8/gems/cocoapods-0.19.1/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/1.8/gems/cocoapods-0.19.1/bin/pod:16
/usr/bin/pod:19:in `load'
/usr/bin/pod:19
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing github issues similar to yours:
https://github.com/CocoaPods/CocoaPods/issues/search?q=Illformed+requirement+%60%22%7E1.8.1%22%60

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Don't forget to anonymize any private data!

**Comment by OleksiiPidgornyi** [comment]
instead of   pod 'ASIHTTPRequest', '~1.8.1' probably use pod 'ASIHTTPRequest', '~>1.8.1'

**Comment by OleksiiPidgornyi** [comment]
instead of ~ use ~>
