### ISSUE TITLE
arch -x86_64 pod update Error

### ISSUE THREAD

**Issue by ZexiFangkong** [CocoaPods/CocoaPods#11247]
Pre-downloading: `YYKit` from `https://git.hellotalk8.com/bitbucket/scm/ioslib/yykit.git`
Pre-downloading: `mopub-ios-sdk` from `https://git.hellotalk8.com/bitbucket/scm/ioslib/mopub-ios-sdk.git`, branch `version5.18.2`

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod update
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.11.2
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
    RubyGems : 3.0.3
        Host : macOS 11.6 (20G165)
       Xcode : 13.2.1 (13C100)
         Git : git version 2.32.0 (Apple Git-132)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ 0b166cd7f4c5a47e4b871d60d27fe05f225eb174

               hellotalk8-bitbucket-scm-ios-hello_specs - git - https://git.hellotalk8.com/bitbucket/scm/ios/hello_specs.git @ bd37e25aac8312bbcd1ae821ca3da2a01d0dbfbc

               hellotalk8-bitbucket-scm-ioslib-hello_specs - git - https://git.hellotalk8.com/bitbucket/scm/ioslib/hello_specs.git @ bd37e25aac8312bbcd1ae821ca3da2a01d0dbfbc

               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-binary-ht   : 1.0.0
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-pod-linkage : 0.0.1
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
source 'https://git.hellotalk8.com/bitbucket/scm/ioslib/hello_specs.git'
source 'https://cdn.cocoapods.org/'

platform :ios, '11.0'
use_frameworks! :linkage => :static
# 用于修改:linkage => :dynamic，灵动课堂SDK需要动态库链接
plugin 'cocoapods-pod-linkage'

# https://www.jianshu.com/p/1e46bf6c48eb
install! 'cocoapods', :disable_input_output_paths => true

inhibit_all_warnings!

# 调试依赖
def debugPods
  # 沙盒文件浏览
  pod "GCDWebServer/WebUploader", "~> 3.0", :configurations => ['Debug']
  # UI 调试
  pod 'LookinServer', '1.0.4', :configurations => ['Debug', 'Release']
end

# HelloTalk 组件
def helloPods
  pod 'HelloFAAC', '0.0.1'
  pod 'HelloFLAC', '0.0.2'
  pod 'HelloNSBKeyframeAnimation', '0.0.2'
  pod 'HelloDiffMatch', '0.0.3'
  pod 'HelloGCDObjC', '0.0.1'
  pod 'HelloSystemServices', '0.0.2'
  pod 'HelloKeychainUtils', '0.0.2'
  pod 'HelloAMRLibrary', '0.0.2'
  pod 'HelloFourSquare', '0.0.2'

  pod 'HelloExtensions', :git => 'https://git.hellotalk8.com/bitbucket/scm/ioslib/helloextensions.git', :branch => 'master'
 #     pod 'HelloExtensions', :path => '../iOSLib/helloextensions'

  pod 'HelloLog', :git => 'https://git.hellotalk8.com/bitbucket/scm/ioslib/hellolog.git', :branch => 'master'
  #    pod 'HelloLog', :path => '../iOSLib/hellolog'

  pod 'UserComponent', :git => 'https://git.hellotalk8.com/bitbucket/scm/ioslib/usercomponent.git', :branch => 'master'
  #    pod 'UserComponent', :path => '../iOSLib/usercomponent' #'0.0.2'

  pod 'HelloCategory', :git => 'https://git.hellotalk8.com/bitbucket/scm/ioslib/hellocategory.git', :branch => 'develop/4.5.2'
#      pod 'HelloCategory', :path => '../iOSLib/HelloCategory'

  pod 'HelloURLNavigator', :git => 'https://git.hellotalk8.com/bitbucket/scm/ioslib/hellourlnavigator.git', :branch => 'master'
  #    pod 'HelloURLNavigator', :path => '../iOSLib/hellourlnavigator' #'0.0.9'

  pod 'HelloSDCycleScrollView', :git => 'https://git.hellotalk8.com/bitbucket/scm/ioslib/hellosdcyclescrollview.git', :tag => 'cs_1'

  pod 'HelloTrack', :git => 'https://git.hellotalk8.com/bitbucket/scm/ioslib/hellotrack.git', :branch => 'develop/4.5.2'
#      pod 'HelloTrack', :path => '../iOSLib/hellotrack'

  pod 'HelloOpenUDID', :git => 'https://git.hellotalk8.com/bitbucket/scm/ioslib/helloopenudid.git', :branch => 'master'
  #    pod 'HelloOpenUDID', :path => '../iOSLib/helloopenudid'

  pod 'HelloCommon', :git => 'https://git.hellotalk8.com/bitbucket/scm/ioslib/hellocommon.git', :branch => 'develop/4.5.2'
  #      pod 'HelloCommon', :path => '../iOSLib/hellocommon'

  pod 'HelloCache', :git => 'https://git.hellotalk8.com/bitbucket/scm/ioslib/hellocache.git', :branch => 'master'
  # pod 'HelloCache', :path => '../iOSLib/helloCache'

  pod 'HelloMessage', :git => 'https://git.hellotalk8.com/bitbucket/scm/ioslib/hellomessage.git', :branch => 'develop/4.5.2'
#      pod 'HelloMessage', :path => '../iOSLib/hellomessage'

  pod 'HelloMessageLayer', :git => 'https://git.hellotalk8.com/bitbucket/scm/ioslib/hellomessagelayer.git', :branch => 'develop/4.5.2'
#      pod 'HelloMessageLayer', :path => '../iOSLib/hellomessagelayer'

  # pod 'HelloMediator', :git => 'https://git.hellotalk8.com/bitbucket/scm/ioslib/hellomediator.git', :branch => 'develop/4.5.2'
   pod 'HelloMediator', :path => '../iOSLib/hellomediator'

  pod 'HelloLanguageCountryUtils', :git => 'https://git.hellotalk8.com/bitbucket/scm/ioslib/hellolanguagecountryutils2.git', :branch => 'master'
  #    pod 'HelloLanguageCountryUtils', :path => '../iOSLib/hellolanguagecountryutils'

  pod 'HelloImagePicker', :git => 'https://git.hellotalk8.com/bitbucket/scm/ioslib/helloimagepicker.git', :branch => 'master'
  #    pod 'HelloImagePicker', :path => '../iOSLib/helloimagepicker'

  pod 'HelloTencentSDK', :git => 'https://git.hellotalk8.com/bitbucket/scm/ioslib/hellotencentsdk.git', :branch => 'master'
  #    pod 'HelloTencentSDK', :path => '../iOSLib/HelloTencentSDK'

  pod 'HelloMultilingual', :git => 'https://git.hellotalk8.com/bitbucket/scm/ioslib/hellomultilingual.git', :branch => 'master'
  #    pod 'HelloMultilingual', :path => '../iOSLib/HelloMultilingual'

  pod 'HelloImageViewer', :git => 'https://git.hellotalk8.com/bitbucket/scm/ioslib/helloimageviewer.git', :branch => 'master'
  #    pod 'HelloImageViewer', :path => '../iOSLib/HelloImageViewer' #

  pod 'HelloObjective-Zip',  :git => 'https://git.hellotalk8.com/bitbucket/scm/ioslib/helloobjective-zip.git', :branch => 'master'
  #    pod 'HelloObjective-Zip', :path => '../iOSLib/helloobjective-zip'

  pod 'HelloASIHttpRequest', :git => 'https://git.hellotalk8.com/bitbucket/scm/ioslib/helloasihttprequest.git', :branch => 'master'
  #    pod 'HelloASIHttpRequest', :path => '../iOSLib/helloasihttprequest'

  pod 'HelloWebImage', :git => 'https://git.hellotalk8.com/bitbucket/scm/ioslib/hellowebimage.git', :branch => 'master'
  #    pod 'HelloWebImage', :path => '../iOSLib/hellowebimage'

  pod 'HelloGuardianSDK', :git => 'https://git.hellotalk8.com/bitbucket/scm/ioslib/helloguardiansdk.git', :branch => 'master'
  #    pod 'HelloGuardianSDK', :path => '../iOSLib/helloguardiansdk'

  pod 'HelloNetwork', :git => 'https://git.hellotalk8.com/bitbucket/scm/ioslib/hellonetwork.git', :branch => 'master'
  #    pod 'HelloNetwork', :path => '../iOSLib/hellonetwork'

  pod 'HelloCommonUI', :git => 'https://git.hellotalk8.com/bitbucket/scm/ioslib/hellocommonui.git',  :branch => 'develop/4.5.2'
   # pod 'HelloCommonUI', :path => '../iOSLib/hellocommonui'

  pod 'HelloChat', :git => 'https://git.hellotalk8.com/bitbucket/scm/ioslib/hellochat.git', :branch => 'master'
  #    pod 'HelloChat', :path => '../iOSLib/hellochat'

  pod 'HelloPay', :git => 'https://git.hellotalk8.com/bitbucket/scm/ioslib/hellopay.git', :branch => 'develop/4.5.2'
#      pod 'HelloPay', :path => '../iOSLib/hellopay'

  pod 'HelloTalkMeditor', :git => 'https://git.hellotalk8.com/bitbucket/scm/ios/hellotalkmediator.git', :branch => 'develop/4.5.2'
#      pod 'HelloTalkMeditor', :path => '../iOSLib/hellotalkmediator'

  pod 'HelloVoiceRoom', :git => 'ssh://git@git.hellotalk8.com:7999/ios/hellovoiceroom.git', :branch => 'develop/4.5.2'
 # pod 'HelloVoiceRoom', :path => '../ioslib/hellovoiceroom'

  pod 'HelloLive', :git => 'https://git.hellotalk8.com/bitbucket/scm/ios/hellolive2.git', :branch => 'develop/4.5.2'
#      pod 'HelloLive', :path => '../iOSLib/hellolive2'

  pod 'HelloZegoSDK', :git => 'ssh://git@office.hellotalk.net:7999/ioslib/hellozegosdk.git', :branch => 'develop/4.5.2'

  pod 'HelloUserCenter', :git => 'https://git.hellotalk8.com/bitbucket/scm/ios/hellousercenter.git', :branch => 'develop/4.5.2'
#      pod 'HelloUserCenter', :path => '../iOSLib/hellousercenter'

  pod 'HelloLogin', :git => 'https://git.hellotalk8.com/bitbucket/scm/ios/hellologin.git', :branch => 'develop/4.5.2'
#   pod 'HelloLogin', :path => '../iOSLib/hellologin'

  pod 'HelloAuth', :git => 'https://git.hellotalk8.com/bitbucket/scm/ioslib/helloauth2.git'
  #    pod 'HelloAuth', :path => '../iOSLib/HelloAuth'

  pod 'HelloNoviceGuideTask', :git => 'https://git.hellotalk8.com/bitbucket/scm/ioslib/hellonoviceguidetask2.git'
  #    pod 'HelloNoviceGuideTask', :path => '../iOSLib/HelloNoviceGuideTask'

  pod 'HelloCrossPlatform/Weex', :git => 'ssh://git@office.hellotalk.net:7999/ioslib/hellocrossplatform.git'
#      pod 'HelloCrossPlatform/Weex', :path => '../iOSLib/HelloCrossPlatform'

  pod 'AudioTransform', :git => 'ssh://git@git.hellotalk8.com:7999/ioslib/audiotransform.git'

  pod 'HelloReport', :git => 'ssh://git@office.hellotalk.net:7999/ioslib/helloreport.git', :branch => 'master'
  # pod 'HelloReport', :path => '../iOSLib/HelloReport'

  pod 'HelloLiveVoiceHomePage', :git => 'ssh://git@git.hellotalk8.com:7999/ios/hellolivevoicehomepage.git', :branch => 'master'

end

def agoraPods

  # Third-party libs
  pod 'OpenSSL-Universal', '1.0.2.17', :linkage => :dynamic
  pod 'CocoaLumberjack', '3.6.1', :linkage => :dynamic
  pod 'Armin',  '1.0.9', :linkage => :dynamic
  pod 'SwifterSwift', '5.2.0', :linkage => :dynamic
  pod 'WHToast', '0.0.7', :linkage => :dynamic
  pod 'FLAnimatedImage', '1.0.16', :linkage => :dynamic
  pod 'YYModel', '1.0.4', :linkage => :dynamic
  pod 'dsBridge', '3.0.6', :linkage => :dynamic
  pod 'AgoraRtcEngine_iOS', '3.4.8', :linkage => :dynamic
  pod 'AliyunOSSiOS', '2.10.7', :linkage => :dynamic
  pod 'Alamofire',  '4.7.3', :linkage => :dynamic
  pod 'SSZipArchive', :git => 'https://git.hellotalk8.com/bitbucket/scm/ioslib/ssziparchive.git', :linkage => :dynamic # 0.3.2
  pod 'Masonry', :git => 'https://git.hellotalk8.com/bitbucket/scm/ioslib/masonry.git', :linkage => :dynamic

  # Agora libs
  pod 'AgoraRtm_iOS', '1.4.8', :linkage => :dynamic
  pod 'Whiteboard', '2.15.18', :linkage => :dynamic
  pod 'HyphenateChat', '3.8.6', :linkage => :dynamic
  pod 'AgoraWidgets', :git => 'ssh://git@office.hellotalk.net:7999/ioslib/agorawidgets.git', :linkage => :dynamic

  # close source libs
  pod 'AgoraEduCore', '2.1.101', :linkage => :dynamic
  pod 'AgoraUIBaseViews', '2.1.0', :linkage => :dynamic
  pod 'AgoraExtApp', '2.1.0', :linkage => :dynamic
  pod 'AgoraLog', '1.0.2', :linkage => :dynamic
  pod 'AgoraWidget', '2.1.0', :linkage => :dynamic

  # open source libs
  pod 'AgoraClassroomSDK_iOS', '2.1.0', :linkage => :dynamic
  pod 'AgoraEduContext', '2.1.0', :linkage => :dynamic
  pod 'AgoraEduUI', '2.1.0', :linkage => :dynamic
  pod 'AgoraExtApps', '2.1.0', :linkage => :dynamic
end

target 'HelloTalk_Binary' do
  debugPods
  helloPods
  agoraPods
  pod 'ProtocolBuffers', '1.9.9.2'
  pod 'Branch', '1.39.4'
  pod 'Firebase/Analytics', '7.7.0'
  pod 'Firebase/Crashlytics', '7.7.0'
  pod 'Google-Mobile-Ads-SDK', '8.13.0' # 从8.1.0升级，看能否解决sdk内部的崩溃问题
  pod 'AppsFlyerFramework', '6.4.0', :modular_headers => false # 上个版本 6.2.3
  pod 'AFNetworking', '4.0.1'
  pod 'GoogleSignIn', '4.4.0'
  pod 'TradPlusAdSDK', '6.9.10' #广告聚合平台
  pod 'TradPlusAdSDK/FacebookAdapter', '6.9.10'
  pod 'TradPlusAdSDK/AdMobAdapter', '6.9.10'
  pod 'TradPlusAdSDK/GDTMobAdapter', '6.9.10'
  pod 'TradPlusAdSDK/PangleAdapter', '6.9.10'
  pod 'TradPlusAdSDK/MoPubAdapter', '6.9.10'
  pod 'FBAudienceNetwork','6.9.0'
  pod 'FBSDKLoginKit', '8.0.0'
  pod 'FBSDKShareKit', '8.0.0'
  pod 'KVOController', '1.2.0'
  pod 'DateTools', '2.0.0'
  pod 'MJRefresh', '3.7.5'
  pod 'WeexSDK', :git => 'https://git.hellotalk8.com/bitbucket/scm/ioslib/weexsdk.git', :branch => 'ht_0.28.0_wkwebview'
  pod 'SocketRocket', '0.5.1'
  pod 'KissXML', '5.2.3'
  pod 'BraintreeDropIn','6.1.0'#添加信用卡页面用的dropIn的
  pod 'Braintree','4.11.0'#包括paypal和信用卡
  pod 'Braintree/Apple-Pay', '4.11.0'
  pod 'StreamingKit', '0.1.30'
  pod 'SensorsAnalyticsSDK', '2.1.12'
  pod 'RxSwift', '5.1.1'
  pod 'RxCocoa', '5.1.1'
  pod 'SnapKit', '4.0.1'
  pod 'RxGesture', '3.0.2'
  pod 'RxDataSources', '4.0.1'
  pod 'SwiftProtobuf', '1.5.0'
  pod 'AlipaySDK-iOS','15.5.9', :modular_headers => false
  pod 'Starscream', :git => 'https://git.hellotalk8.com/bitbucket/scm/ioslib/starscream.git', :tag => '4.0.12'
  pod 'xxtea', '1.0.1'
  pod 'Ads-CN', '4.2.0.2', :subspecs => ['BUAdSDK', 'International']  # 穿山甲国内流量sdk
  pod 'HTFlutterSDK/Release', :git => 'ssh://git@office.hellotalk.net:7999/ioslib/htfluttersdk.git', :tag => '4.5.2.7'
  pod 'GDTMobSDK', '4.13.41'
  pod 'lottie-ios', '3.2.1'
  pod 'libpag', '3.2.7.34'
  pod 'VisualEffectView', '4.1.0'
  pod 'MMKV', '1.2.7'
  pod 'JXPagingView', '2.0.12'
  pod 'JXSegmentedView', :git => 'https://git.hellotalk8.com/bitbucket/scm/ioslib/jxsegmentedview.git'
  pod 'SwiftyStoreKit', :git => 'https://github.com/KorolZhu/SwiftyStoreKit.git', :branch => '0.16.1_ht'
  pod 'mopub-ios-sdk', :git => 'https://git.hellotalk8.com/bitbucket/scm/ioslib/mopub-ios-sdk.git', :branch => 'version5.18.2'
  pod 'NTESQuickPass', :git => 'https://git.hellotalk8.com/bitbucket/scm/ioslib/ntesquickpass.git', :branch => '3.2.6'
  pod 'YYKit', :git => 'https://git.hellotalk8.com/bitbucket/scm/ioslib/yykit.git' # '1.0.9'
  pod 'ReactiveObjC', :git => 'https://git.hellotalk8.com/bitbucket/scm/ioslib/reactiveobjc.git'
  pod 'HelloMBProgressHUD', :git => 'https://git.hellotalk8.com/bitbucket/scm/ioslib/hellombprogresshud.git'
  pod 'NNLHashids', :git => 'https://git.hellotalk8.com/bitbucket/scm/ioslib/nnlhashids.git'
  pod 'BindingX', :git => 'https://git.hellotalk8.com/bitbucket/scm/ioslib/bindingx.git'
  pod 'Leanplum-iOS-Location', :git => 'https://git.hellotalk8.com/bitbucket/scm/ioslib/leanplum-ios-location.git'#'3.0.0'
  pod 'TXIMSDK_Smart_iOS', '5.1.138'
  pod 'MicrosoftCognitiveServicesSpeech-iOS', '1.19.0'
  pod 'FSTextView', '1.8'
  pod 'UserLeapKit', '4.3.0'  # 调查问卷
  pod 'tingyunApp', '2.15.8'   # 听云 sdk
  pod 'FMDB', '2.7.5'
  pod 'sqlite3', '3.36.0'
  pod 'LuaScriptCore', '2.3.2'
  pod 'Waver', '0.3.0'  # 声浪的动画效果
end

# 灵动课堂涉及的组件
need_distribution_libs = ['Armin', 'AgoraClassroomSDK_iOS', 'AgoraEduContext', 'AgoraEduCore', 'AgoraEduUI', 'AgoraExtApp', 'AgoraExtApps', 'AgoraLog', 'AgoraRtcEngine_iOS', 'AgoraRtm_iOS', 'AgoraUIBaseViews', 'AgoraWidget', 'AgoraWidgets', 'AgoraEduUI-AgoraEduUI', 'AgoraExtApps-AgoraExtApps', 'AgoraWidgets-AgoraWidgets']
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|

      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['EXCLUDED_ARCHS'] = 'armv7 armv7s'
      config.build_settings['DEFINE_MODULE'] = 'YES'

      # 灵动课堂的SDK需要开启 ABI 稳定特性
      # https://www.swift.org/blog/abi-stability-and-more/
      if need_distribution_libs.include?(target.name)
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      else
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'NO'
      end
      if target.name == 'StreamingKit'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
  end
end

pre_install do |installer|
  # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end
```

### Error

```
JSON::ParserError - 767: unexpected token at '{
  "name": "FirebaseCoreDiagnostics",
  "version": "7.9.0",
  "summary": "Firebase Core Diagnostics",
  "description": "Firebase Core Diagnostics collects diagnostic data to help improve and provide Firebase services.\nThis SDK is integrated using a 'soft-link' mechanism and the bits be omitted by using a\nnon-Cocoapod integration. This library also respects the Firebase global data collection flag.",
  "homepage": "https://firebase.google.com",
  "license": {
    "type": "Apache",
    "file": "LICENSE"
  },
  "authors": "Google, Inc.",
  "source": {
    "git": "https://github.com/firebase/firebase-ios-sdk.git",
    "tag": "CocoaPods-7.9.0"
  },
  "social_media_url": "https://twitter.com/Firebase",
  "platforms": {
    "ios": "9.0",
    "osx": "10.12",
    "tvos": "10.0",
    "watchos": "6.0"
  },
  "cocoapods_version": ">= 1.4.0",
  "prefix_header_file": false,
  "pod_target_xcconfig": {
    "GCC_C_LANGUAGE_STANDARD": "c99",
    "GCC_TREAT_WARNINGS_AS_ERRORS": "YES",
    "CLANG_UNDEFINED_BEHAVIOR_SANITIZER_NULLABILITY": "YES",
    "GCC_PREPROCESSOR_DEFINITIONS": "PB_FIELD_32BIT=1 PB_NO_PACKED_STRUCTS=1 PB_ENABLE_MALLOC=1",
    "HEADER_SEARCH_PATHS": "\"${PODS_TARGET_SRCROOT}\""
  },
  "source_files": [
    "Firebase/CoreDiagnostics/FIRCDLibrary/**/*.[cmh]",
    "Interop/CoreDiagnostics/Public/*.h"
  ],
  "public_header_files": "Firebase/CoreDiagnostics/FIRCDLibrary/Public/*.h",
  "frameworks": "Foundation'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/specification/json.rb:61:in `from_json'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/specification.rb:748:in `from_string'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/specification.rb:722:in `from_file'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/source.rb:188:in `specification'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/resolver/lazy_specification.rb:37:in `specification'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:348:in `block in delegating_block'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:349:in `block in delegating_block'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/resolver.rb:178:in `dependencies_for'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:18:in `block in dependencies_for'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:77:in `with_no_such_dependency_error_handling'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:17:in `dependencies_for'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:809:in `block in group_possibilities'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:808:in `reverse_each'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:808:in `group_possibilities'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:779:in `possibilities_for_requirement'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:761:in `push_state_for_requirements'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:744:in `require_nested_dependencies_for'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:727:in `activate_new_spec'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:684:in `attempt_to_activate'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:254:in `process_topmost_state'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:182:in `resolve'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in `resolve'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/resolver.rb:94:in `resolve'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:1078:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:1076:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:416:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:241:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:240:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:161:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command/update.rb:63:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

**Comment by dnkoutso** [comment]
Not sure the issue here try `rm -rf ~./.cocoapdos/repos` and then `pod install` again.
