### ISSUE TITLE
pod trunk register throwing internal server error

### ISSUE THREAD

**Issue by tahirmt** [CocoaPods/CocoaPods#11271]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Ran `pod trunk register 'EMAIL' 'NAME' --description="DESCRIPTION"

## What did you expect to happen?

The link from the email should validate my session and let me push to trunk

## What happened instead?

I received a link that upon clicking took me to a page that simply said internal server error

## CocoaPods Environment

I don't think it's relevant. I used cocoa pods `1.11.3`

## Project that demonstrates the issue

The project is irrelevant since it's an issue with cocoa pods trunk register itself.

**Comment by joaquinsfy** [comment]
I have the same Problem

https://trunk.cocoapods.org/sessions/verify/72f3e0f1

This link causes the internal server error.

**Comment by tahirmt** [comment]
@joaquinsfy it looks like it does still register so nothing is really broken.

**Comment by joaquinsfy** [comment]
@tahirmt , true, the library has been released,  pod trunk push xxxxx.podspec --allow-warnings, so nothing is broken, just the web-page with the confirmation link.

**Comment by orta** [comment]
You likely have an email validator checking the links and accepting the session for you

**Comment by joaquinsfy** [comment]
@orta , I don't have any email validator, last week , I do the same. process few times, but yesterday started with the internal server error, if you  try to verify https://trunk.cocoapods.org/sessions/verify/72f3e0f1, you will get the error, and days ago, the message was "you already autorizad... or something like this.

**Comment by hllGitHub** [comment]
+1 Same issue here

**Comment by orta** [comment]
Confirmed in the logs, it's that the 404 page isn't found

```
2022-03-28T15:36:07.652213+00:00 app[web.1]: Unexpected error while processing request: No such file or directory @ rb_sysopen - /app/app/views/session_verification/html/not_found.slim

2022-03-28T15:36:07.652214+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.5.0/gems/tilt-1.4.1/lib/tilt/template.rb:91:in `initialize'

2022-03-28T15:36:07.652214+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.5.0/gems/tilt-1.4.1/lib/tilt/template.rb:91:in `open'

2022-03-28T15:36:07.652214+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.5.0/gems/tilt-1.4.1/lib/tilt/template.rb:91:in `read_template_file'`
```

Which means the link would already have been clicked by some automation  👍🏻

**Comment by HMSPushKit** [comment]
i have the same question :(.
https://trunk.cocoapods.org/sessions/verify/3e588d9e

**Comment by zydeico** [comment]
+2 same issue here, and also when I type `pod trunk push MyPod.podspec --allow-warnings`, I get `[!] You (mail) are not allowed to push new versions for this pod. The owners of this pod are 1042480866@qq.com.` error :(

**Comment by jurajantas** [comment]
same issue here. registering returns "internal server error". However, it seems that cookie is set and registering library works.

**Comment by ivandortulov** [comment]
This is still happening.

**Comment by xiaoxiaowesley** [comment]
Any update? Registration is still no working?

**Comment by rexmas** [comment]
Internal Server Error
