### ISSUE TITLE
pod repo update  failed

### ISSUE THREAD

**Issue by SirOlaoluwani** [CocoaPods/CocoaPods#11287]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
Run `pod repo update`

## What did you expect to happen?
ℹ update all pods in my project

## What happened instead?

ℹ I got the following error

Ignoring executable-hooks-1.6.1 because its extensions are not built. Try: gem pristine executable-hooks --version 1.6.1
Ignoring ffi-1.15.4 because its extensions are not built. Try: gem pristine ffi --version 1.15.4
Ignoring ffi-1.15.1 because its extensions are not built. Try: gem pristine ffi --version 1.15.1
Ignoring ffi-1.15.0 because its extensions are not built. Try: gem pristine ffi --version 1.15.0
Ignoring gem-wrappers-1.4.0 because its extensions are not built. Try: gem pristine gem-wrappers --version 1.4.0
Ignoring ffi-1.15.4 because its extensions are not built. Try: gem pristine ffi --version 1.15.4
Ignoring ffi-1.15.1 because its extensions are not built. Try: gem pristine ffi --version 1.15.1
Ignoring ffi-1.15.0 because its extensions are not built. Try: gem pristine ffi --version 1.15.0
Updating spec repo `trunk`

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/olaoluwanionafowope/.rvm/rubies/ruby-3.0.0/bin/pod repo update
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x86_64-darwin21]
    RubyGems : 3.3.7
        Host : macOS 12.0.1 (21A559)
       Xcode : 13.1 (13A1030d)
         Git : git version 2.30.1 (Apple Git-130)
Ruby lib dir : /usr/local/Cellar/ruby/3.1.1/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'EbanqoCustomerServiceApp' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNSharedElement', :path => '../node_modules/react-native-shared-element'

  pod 'RNFS', :path => '../node_modules/react-native-fs'
  
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'


  target 'EbanqoCustomerServiceAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

target 'EbanqoCustomerServiceApp-tvOS' do
  # Pods for EbanqoCustomerServiceApp-tvOS

  target 'EbanqoCustomerServiceApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
```

### Error

```
LoadError - dlopen(/Users/olaoluwanionafowope/.rvm/gems/ruby-3.0.0/gems/ffi-1.15.4/lib/ffi_c.bundle, 0x0009): Library not loaded: /usr/local/opt/ruby/lib/libruby.3.0.dylib
  Referenced from: /Users/olaoluwanionafowope/.rvm/gems/ruby-3.0.0/gems/ffi-1.15.4/lib/ffi_c.bundle
  Reason: tried: '/usr/local/opt/ruby/lib/libruby.3.0.dylib' (no such file), '/usr/local/lib/libruby.3.0.dylib' (no such file), '/usr/lib/libruby.3.0.dylib' (no such file), '/usr/local/Cellar/ruby/3.1.1/lib/libruby.3.0.dylib' (no such file), '/usr/local/lib/libruby.3.0.dylib' (no such file), '/usr/lib/libruby.3.0.dylib' (no such file) - /Users/olaoluwanionafowope/.rvm/gems/ruby-3.0.0/gems/ffi-1.15.4/lib/ffi_c.bundle
<internal:/usr/local/Cellar/ruby/3.1.1/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/usr/local/Cellar/ruby/3.1.1/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/Users/olaoluwanionafowope/.rvm/gems/ruby-3.0.0/gems/ffi-1.15.4/lib/ffi.rb:5:in `rescue in <top (required)>'
/Users/olaoluwanionafowope/.rvm/gems/ruby-3.0.0/gems/ffi-1.15.4/lib/ffi.rb:2:in `<top (required)>'
<internal:/usr/local/Cellar/ruby/3.1.1/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/usr/local/Cellar/ruby/3.1.1/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/Users/olaoluwanionafowope/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/ethon-0.13.0/lib/ethon.rb:3:in `<top (required)>'
<internal:/usr/local/Cellar/ruby/3.1.1/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/usr/local/Cellar/ruby/3.1.1/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/Users/olaoluwanionafowope/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
<internal:/usr/local/Cellar/ruby/3.1.1/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/usr/local/Cellar/ruby/3.1.1/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/Users/olaoluwanionafowope/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:440:in `download_typhoeus_impl_async'
/Users/olaoluwanionafowope/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:372:in `download_and_save_with_retries_async'
/Users/olaoluwanionafowope/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:365:in `download_file_async'
/Users/olaoluwanionafowope/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:338:in `download_file'
/Users/olaoluwanionafowope/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:78:in `deprecated_local_podspecs'
/Users/olaoluwanionafowope/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:60:in `preheat_existing_files'
/Users/olaoluwanionafowope/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:257:in `update'
/Users/olaoluwanionafowope/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:135:in `block (3 levels) in update'
/Users/olaoluwanionafowope/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/olaoluwanionafowope/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:134:in `block (2 levels) in update'
/Users/olaoluwanionafowope/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:133:in `each'
/Users/olaoluwanionafowope/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:133:in `block in update'
/Users/olaoluwanionafowope/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:131:in `open'
/Users/olaoluwanionafowope/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:131:in `update'
/Users/olaoluwanionafowope/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/command/repo/update.rb:23:in `run'
/Users/olaoluwanionafowope/.rvm/gems/ruby-3.0.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Users/olaoluwanionafowope/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/Users/olaoluwanionafowope/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/Users/olaoluwanionafowope/.rvm/rubies/ruby-3.0.0/bin/pod:23:in `load'
/Users/olaoluwanionafowope/.rvm/rubies/ruby-3.0.0/bin/pod:23:in `<main>'
/Users/olaoluwanionafowope/.rvm/gems/ruby-3.0.0/bin/ruby_executable_hooks:22:in `eval'
/Users/olaoluwanionafowope/.rvm/gems/ruby-3.0.0/bin/ruby_executable_hooks:22:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=dlopen%28%2FUsers%2Folaoluwanionafowope%2F.rvm%2Fgems%2Fruby-3.0.0%2Fgems%2Fffi-1.15.4%2Flib%2Fffi_c.bundle%2C+0x0009%29%3A+Library+not+loaded%3A+%2Fusr%2Flocal%2Fopt%2Fruby%2Flib%2Flibruby.3.0.dylib%0A++Referenced+from%3A+%2FUsers%2Folaoluwanionafowope%2F.rvm%2Fgems%2Fruby-3.0.0%2Fgems%2Fffi-1.15.4%2Flib%2Fffi_c.bundle%0A++Reason%3A+tried%3A+%27%2Fusr%2Flocal%2Fopt%2Fruby%2Flib%2Flibruby.3.0.dylib%27+%28no+such+file%29%2C+%27%2Fusr%2Flocal%2Flib%2Flibruby.3.0.dylib%27+%28no+such+file%29%2C+%27%2Fusr%2Flib%2Flibruby.3.0.dylib%27+%28no+such+file%29%2C+%27%2Fusr%2Flocal%2FCellar%2Fruby%2F3.1.1%2Flib%2Flibruby.3.0.dylib%27+%28no+such+file%29%2C+%27%2Fusr%2Flocal%2Flib%2Flibruby.3.0.dylib%27+%28no+such+file%29%2C+%27%2Fusr%2Flib%2Flibruby.3.0.dylib%27+%28no+such+file%29+-+%2FUsers%2Folaoluwanionafowope%2F.rvm%2Fgems%2Fruby-3.0.0%2Fgems%2Fffi-1.15.4%2Flib%2Fffi_c.bundle&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Searching for inspections failed: undefined method `map' for nil:NilClass

      report.issues = results['items'].map { |item| Issue.new(item) }

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x86_64-darwin21]
    RubyGems : 3.3.7
        Host : macOS 12.0.1 (21A559)
       Xcode : 13.1 (13A1030d)
         Git : git version 2.30.1 (Apple Git-130)
Ruby lib dir : /usr/local/Cellar/ruby/3.1.1/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /Users/olaoluwanionafowope/.rvm/rubies/ruby-3.0.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'EbanqoCustomerServiceApp' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNSharedElement', :path => '../node_modules/react-native-shared-element'

  pod 'RNFS', :path => '../node_modules/react-native-fs'
  
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'


  target 'EbanqoCustomerServiceAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

target 'EbanqoCustomerServiceApp-tvOS' do
  # Pods for EbanqoCustomerServiceApp-tvOS

  target 'EbanqoCustomerServiceApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
```

## Project that demonstrates the issue

it's only an issue with CocoaPods the tool

**Comment by dnkoutso** [comment]
Please search for other `ffi` gem installation issues everywhere in this repo and stackoverflow.

**Comment by SirOlaoluwani** [comment]
solved this by running gem pristine executable-hooks --version 1.6.1 and following instructions that came after it
