### ISSUE TITLE
error npx react-native run-ios

### ISSUE THREAD

**Issue by AlexDjNett** [CocoaPods/CocoaPods#11306]
### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.5.0
        Ruby : ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.x86_64-darwin21]
    RubyGems : 3.0.3.1
        Host : macOS 12.3.1 (21E258)
       Xcode : 13.3.1 (13E500a)
         Git : git version 2.32.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ d2b51235d9be97ce24fe87b16247df8667e92ac4
               trunk -  @ fatal: not a git repository (or any of the parent directories): .git
```

### Plugins

```
cocoapods-clean       : 0.0.1
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'

target 'squeezeimg' do
  config = use_native_modules!
  
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"

  pod 'FBSDKLoginKit'
  $RNAdMobAsStaticFramework = true
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true
  )


  # target 'squeezeimgTests' do
  #   inherit! :complete
  #   # Pods for testing
  # end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
  end
end
```

### Error

```
Errno::ENOSPC - No space left on device @ fptr_finalize_flush - /Users/DjNett/Desktop/Projects /squeezeimg-react-native/ios/Pods/Local Podspecs/DoubleConversion.podspec.json
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.5.0/lib/cocoapods/sandbox.rb:257:in `close'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.5.0/lib/cocoapods/sandbox.rb:257:in `open'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.5.0/lib/cocoapods/sandbox.rb:257:in `open'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.5.0/lib/cocoapods/sandbox.rb:257:in `store_podspec'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.5.0/lib/cocoapods/external_sources/abstract_external_source.rb:174:in `store_podspec'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.5.0/lib/cocoapods/external_sources/podspec_source.rb:15:in `block in fetch'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.5.0/lib/cocoapods/user_interface.rb:85:in `titled_section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.5.0/lib/cocoapods/external_sources/podspec_source.rb:11:in `fetch'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.5.0/lib/cocoapods/installer/analyzer.rb:697:in `fetch_external_source'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.5.0/lib/cocoapods/installer/analyzer.rb:673:in `block (2 levels) in fetch_external_sources'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.5.0/lib/cocoapods/installer/analyzer.rb:672:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.5.0/lib/cocoapods/installer/analyzer.rb:672:in `block in fetch_external_sources'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.5.0/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.5.0/lib/cocoapods/installer/analyzer.rb:671:in `fetch_external_sources'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.5.0/lib/cocoapods/installer/analyzer.rb:85:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.5.0/lib/cocoapods/installer.rb:243:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.5.0/lib/cocoapods/installer.rb:154:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.5.0/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.5.0/lib/cocoapods/installer.rb:153:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.5.0/lib/cocoapods/installer.rb:116:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.5.0/lib/cocoapods/command/install.rb:41:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.5.0/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.5.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by orta** [comment]
Did you investigate this error? 

> Errno::ENOSPC - No space left on device @ fptr_finalize_flush - /Users/DjNett/Desktop/Projects /squeezeimg-react-native/ios/Pods/Local Podspecs/DoubleConversion.podspec.json

**Comment by AlexDjNett** [comment]
no

**Comment by dnkoutso** [comment]
This seems a react native issue. Please upload a sample app demonstrating the issue _without_ ReactNative.
