### ISSUE TITLE
Pod Install Fails - MAC Book Pro M1 Machine

### ISSUE THREAD

**Issue by SportApps** [CocoaPods/CocoaPods#11356]
Hey guys, I can not make Cocoapods work on my Mac M1 Machine.

**What did you do?**

`timknogel@Tims-MacBook-Pro ios % pod install`
 
**What did you expect to happen?**

Install all pod dependencies correctly.

## What happened instead?

ERROR - Error log attached in text file

```
POD ENV
Error - attached in text file
Attached in Text File

[Crash Report pod install.txt](https://github.com/CocoaPods/CocoaPods/files/8670630/Crash.Report.pod.install.txt)


```

```
timknogel@Tims-MacBook-Pro ios % which ruby
/usr/bin/ruby
```

```
timknogel@Tims-MacBook-Pro ios % ruby -v
ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.arm64e-darwin21]
```

```
timknogel@Tims-MacBook-Pro multiculturalapp % git --version
git version 2.36.0
```

 Xcode - develop for iOS and macOS (Xcode 13.3.1)

Does someone know why pod install won't work?

**Comment by matinzd** [comment]
Did you check to see if it's related to #11355?

**Comment by SportApps** [comment]
> Did you check to see if it's related to #11355?

Hi Martin, Thanks for your answer!

I already have this issue since more than a year. https://github.com/CocoaPods/CocoaPods/issues/11355? seems to be recent.

But I tried out the suggested solution:

1.) Add to the Beginning of the PodFile:
source 'https://github.com/CocoaPods/Specs.git'

2.) run pod install
`
timknogel@Tims-MacBook-Pro multiculturalapp % pod install`


Result 

```
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:128:in `git_version': Failed to extract git version from `git --version` ("") (RuntimeError)
        from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:140:in `verify_minimum_git_version!'
        from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:49:in `run'
        from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
        from /usr/local/bin/pod:23:in `load'
        from /usr/local/bin/pod:23:in `<main>'
```

**Comment by matinzd** [comment]
Try updating your dependencies on your m1 machine since it’s changed a lot over last year.

**Comment by SportApps** [comment]
Hey ! What does updating dependencies mean? I updated Xcode and all packages, tried to update CocoaPods and should have updated everything up to date. 
I even updated Ruby and Git as you can see in my inicial post.

**Comment by matinzd** [comment]
> Hey ! What does updating dependencies mean? I updated Xcode and all packages, tried to update CocoaPods and should have updated everything up to date.
> I even updated Ruby and Git as you can see in my inicial post.

Have you updated xcode command line?

**Comment by SportApps** [comment]
> > Hey ! What does updating dependencies mean? I updated Xcode and all packages, tried to update CocoaPods and should have updated everything up to date.
> > I even updated Ruby and Git as you can see in my inicial post.
> 
> Have you updated xcode command line?

Yes

```
timknogel@Tims-MacBook-Pro ~ % softwareupdate --list
Software Update Tool

Finding available software
No new software available.
timknogel@Tims-MacBook-Pro ~ % 
```

Just in case I run:

```
sudo rm -rf /Library/Developer/CommandLineTools
xcode-select --install

```



Then I entered back into Android studio and:

`timknogel@Tims-MacBook-Pro ios % pod install`


`timknogel@Tims-MacBook-Pro ios % pod install
Analyzing dependencies
cloud_firestore: Using Firebase SDK version '8.15.0' defined in 'firebase_core'
cloud_functions: Using Firebase SDK version '8.15.0' defined in 'firebase_core'
firebase_auth: Using Firebase SDK version '8.15.0' defined in 'firebase_core'
firebase_core: Using Firebase SDK version '8.15.0' defined in 'firebase_core'
firebase_dynamic_links: Using Firebase SDK version '8.15.0' defined in 'firebase_core'
firebase_messaging: Using Firebase SDK version '8.15.0' defined in 'firebase_core'
firebase_storage: Using Firebase SDK version '8.15.0' defined in 'firebase_core'
/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.3/lib/ffi/library.rb:275: [BUG] Bus Error at 0x0000000100f80000
ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.arm64e-darwin21]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:                    
     * ~/Library/Logs/DiagnosticReports                                     
     * /Library/Logs/DiagnosticReports                                      
   for more details.                                                        
Don't forget to include the above Crash Report log file in bug reports.     

-- Control frame information -----------------------------------------------
c:0049 p:---- s:0307 e:000306 CFUNC  :attach
c:0048 p:0258 s:0301 e:000300 METHOD /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.3/lib/ffi/library.rb:275
c:0047 p:0050 s:0281 e:000280 CLASS  /Library/Ruby/Gems/2.6.0/gems/ethon-0.14.0/lib/ethon/libc.rb:17
c:0046 p:0007 s:0278 e:000277 CLASS  /Library/Ruby/Gems/2.6.0/gems/ethon-0.14.0/lib/ethon/libc.rb:7
c:0045 p:0007 s:0275 e:000274 TOP    /Library/Ruby/Gems/2.6.0/gems/ethon-0.14.0/lib/ethon/libc.rb:2 [FINISH]
c:0044 p:---- s:0272 e:000271 CFUNC  :require
c:0043 p:0110 s:0267 e:000266 METHOD /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54
c:0042 p:0042 s:0255 e:000254 TOP    /Library/Ruby/Gems/2.6.0/gems/ethon-0.14.0/lib/ethon.rb:15 [FINISH]
c:0041 p:---- s:0252 e:000251 CFUNC  :require
c:0040 p:0110 s:0247 e:000246 METHOD /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54
c:0039 p:0013 s:0235 e:000234 TOP    /Library/Ruby/Gems/2.6.0/gems/typhoeus-1.4.0/lib/typhoeus.rb:2 [FINISH]
c:0038 p:---- s:0232 e:000231 CFUNC  :require
c:0037 p:0110 s:0227 e:000226 METHOD /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54
c:0036 p:0006 s:0215 e:000214 METHOD /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:440
c:0035 p:0045 s:0207 e:000206 METHOD /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:372
c:0034 p:0318 s:0196 e:000195 METHOD /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:365
c:0033 p:0006 s:0186 e:000185 METHOD /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:338
c:0032 p:0059 s:0181 e:000180 METHOD /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:53
c:0031 p:0021 s:0177 e:000176 METHOD /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/source.rb:31
c:0030 p:0030 s:0172 e:000171 METHOD /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:30 [FINISH]
c:0029 p:---- s:0167 e:000166 CFUNC  :new
c:0028 p:0068 s:0162 e:000158 BLOCK  /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/source/manager.rb:315 [FINISH]
c:0027 p:0039 s:0154 E:000668 METHOD /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/source/manager.rb:322
c:0026 p:0007 s:0147 e:000146 BLOCK  /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/source/manager.rb:331 [FINISH]
c:0025 p:---- s:0143 e:000142 CFUNC  :map


--> Just a little extract....
`

**Comment by dnkoutso** [comment]
This so far does not appear to be a cocoapods issue or enhancement we can make. Going to close as an environment setup issue.

**Comment by SportApps** [comment]
Good evening,

how is this a setup issue if I have even rebooted my whole Mac and ran into the exact same issue again? 

Please leave this issue open.

**Comment by dnkoutso** [comment]
Hmmm I saw the report again and I see

```
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:128:in `git_version': Failed to extract git version from `git --version` ("") (RuntimeError)
```

is `git`

**Comment by SportApps** [comment]
> Hmmm I saw the report again and I see
> 
> ```
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:128:in `git_version': Failed to extract git version from `git --version` ("") (RuntimeError)
> ```
> 
> what does `git --version` output?

When I open it from the terminal inside Android studio:

```
timknogel@Tims-MacBook-Pro ios % git --version
git version 2.36.0
```

**Comment by SportApps** [comment]
Hey ! I tried now this:

https://stackoverflow.com/questions/64901180/how-to-run-cocoapods-on-apple-silicon-m1


```
# STEP 1: Install ffi
sudo arch -x86_64 gem install ffi

# STEP 2: Re-install dependencies
arch -x86_64 pod install
```

And the pod installs. But the CocoaPods still don't work. So I am back to 0...
