### ISSUE TITLE
m1 pod install error

### ISSUE THREAD

**Issue by loveyoubaby5120** [CocoaPods/CocoaPods#11360]
――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/pankai/.rbenv/versions/2.7.5/bin/pod install --project-directory=ios --repo-update
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.11.3
        Ruby : ruby 2.7.5p203 (2021-11-24 revision f69aeb8314) [arm64-darwin21]
    RubyGems : 3.1.6
        Host : macOS 12.3.1 (21E258)
       Xcode : 13.3.1 (13E500a)
         Git : git version 2.32.0 (Apple Git-132)
Ruby lib dir : /Users/pankai/.rbenv/versions/2.7.5/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")
require File.join(File.dirname(`node --print "require.resolve('@react-native-community/cli-platform-ios/package.json')"`), "native_modules")

platform :ios, '12.0'
install! 'cocoapods',
  :deterministic_uuids => false

$RNFirebaseAnalyticsWithoutAdIdSupport=true
$FirebaseSDKVersion = '8.15.0'

require 'json'
podfile_properties = JSON.parse(File.read('./Podfile.properties.json')) rescue {}

target 'popshoplive' do
  use_expo_modules!
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
#     :hermes_enabled => flags[:hermes_enabled] || podfile_properties['expo.jsEngine'] == 'hermes',
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Dir.pwd}/.."
  )


#   pod 'Segment-Firebase', git: 'git@github.com:popshoplive/analytics-ios-integration-firebase'
  pod 'SDWebImage', :modular_headers => true
  pod 'react-native-psl-qiao', path: '../RNQiao'

  pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '8.15.0'

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)

    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64 i386"
    end

  end

  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end

end
```

### Error

```
LoadError - dlopen(/Users/pankai/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/lib/ffi_c.bundle, 0x0009): tried: '/Users/pankai/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/lib/ffi_c.bundle' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')) - /Users/pankai/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/lib/ffi_c.bundle
/Users/pankai/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/lib/ffi.rb:5:in `require'
/Users/pankai/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/lib/ffi.rb:5:in `rescue in <top (required)>'
/Users/pankai/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/lib/ffi.rb:2:in `<top (required)>'
/Users/pankai/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/ethon-0.15.0/lib/ethon.rb:3:in `require'
/Users/pankai/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/ethon-0.15.0/lib/ethon.rb:3:in `<top (required)>'
/Users/pankai/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `require'
/Users/pankai/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
/Users/pankai/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:440:in `require'
/Users/pankai/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:440:in `download_typhoeus_impl_async'
/Users/pankai/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:372:in `download_and_save_with_retries_async'
/Users/pankai/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:365:in `download_file_async'
/Users/pankai/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:338:in `download_file'
/Users/pankai/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:78:in `deprecated_local_podspecs'
/Users/pankai/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:60:in `preheat_existing_files'
/Users/pankai/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:257:in `update'
/Users/pankai/.gem/ruby/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/sources_manager.rb:144:in `block (3 levels) in update'
/Users/pankai/.gem/ruby/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
/Users/pankai/.gem/ruby/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/sources_manager.rb:143:in `block (2 levels) in update'
/Users/pankai/.gem/ruby/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/sources_manager.rb:142:in `each'
/Users/pankai/.gem/ruby/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/sources_manager.rb:142:in `block in update'
/Users/pankai/.gem/ruby/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/sources_manager.rb:140:in `open'
/Users/pankai/.gem/ruby/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/sources_manager.rb:140:in `update'
/Users/pankai/.gem/ruby/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:145:in `block in update_repositories'
/Users/pankai/.gem/ruby/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:143:in `each'
/Users/pankai/.gem/ruby/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:143:in `update_repositories'
/Users/pankai/.gem/ruby/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:237:in `block in resolve_dependencies'
/Users/pankai/.gem/ruby/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
/Users/pankai/.gem/ruby/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:236:in `resolve_dependencies'
/Users/pankai/.gem/ruby/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:161:in `install!'
/Users/pankai/.gem/ruby/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/command/install.rb:52:in `run'
/Users/pankai/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/pankai/.gem/ruby/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:52:in `run'
/Users/pankai/.gem/ruby/2.7.0/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
/Users/pankai/.rbenv/versions/2.7.5/bin/pod:23:in `load'
/Users/pankai/.rbenv/versions/2.7.5/bin/pod:23:in `<top (required)>'
/Users/pankai/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.13/lib/bundler/cli/exec.rb:58:in `load'
/Users/pankai/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.13/lib/bundler/cli/exec.rb:58:in `kernel_load'
/Users/pankai/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.13/lib/bundler/cli/exec.rb:23:in `run'
/Users/pankai/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.13/lib/bundler/cli.rb:483:in `exec'
/Users/pankai/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.13/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/pankai/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.13/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/Users/pankai/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.13/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/Users/pankai/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.13/lib/bundler/cli.rb:31:in `dispatch'
/Users/pankai/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.13/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/Users/pankai/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.13/lib/bundler/cli.rb:25:in `start'
/Users/pankai/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.13/exe/bundle:48:in `block in <top (required)>'
/Users/pankai/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.13/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
/Users/pankai/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bundler-2.3.13/exe/bundle:36:in `<top (required)>'
/Users/pankai/.rbenv/versions/2.7.5/bin/bundle:23:in `load'
/Users/pankai/.rbenv/versions/2.7.5/bin/bundle:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

**Comment by dnkoutso** [comment]
Please see related ffi gem installation issue scattered throughout this repo and online.
