### ISSUE TITLE
Pod init fails miserably on M1 mac

### ISSUE THREAD

**Issue by KatkayApps** [CocoaPods/CocoaPods#11376]
typing `pod init` on a blank project gives me this error:

```
Ignoring bigdecimal-1.4.4 because its extensions are not built. Try: gem pristine bigdecimal --version 1.4.4
Ignoring io-console-0.4.8 because its extensions are not built. Try: gem pristine io-console --version 0.4.8
Ignoring nokogiri-1.10.5 because its extensions are not built. Try: gem pristine nokogiri --version 1.10.5
Ignoring sqlite3-1.4.1 because its extensions are not built. Try: gem pristine sqlite3 --version 1.4.1
Ignoring strscan-1.0.3 because its extensions are not built. Try: gem pristine strscan --version 1.0.3
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': dlopen(/Library/Ruby/Gems/2.6.0/gems/bigdecimal-1.4.4/lib/bigdecimal.bundle, 0x0009): tried: '/Library/Ruby/Gems/2.6.0/gems/bigdecimal-1.4.4/lib/bigdecimal.bundle' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')) - /Library/Ruby/Gems/2.6.0/gems/bigdecimal-1.4.4/lib/bigdecimal.bundle (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/bigdecimal-1.4.4/lib/bigdecimal.rb:4:in `rescue in <top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/bigdecimal-1.4.4/lib/bigdecimal.rb:1:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/Cellar/cocoapods/1.11.3/libexec/gems/activesupport-6.1.5/lib/active_support/xml_mini.rb:5:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/Cellar/cocoapods/1.11.3/libexec/gems/activesupport-6.1.5/lib/active_support/core_ext/array/conversions.rb:3:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods.rb:9:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/bin/pod:36:in `<top (required)>'
	from /usr/local/Cellar/cocoapods/1.11.3/libexec/bin/pod:23:in `load'
	from /usr/local/Cellar/cocoapods/1.11.3/libexec/bin/pod:23:in `<main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- 2.6/bigdecimal.so (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Gems/2.6.0/gems/bigdecimal-1.4.4/lib/bigdecimal.rb:2:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/Cellar/cocoapods/1.11.3/libexec/gems/activesupport-6.1.5/lib/active_support/xml_mini.rb:5:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/Cellar/cocoapods/1.11.3/libexec/gems/activesupport-6.1.5/lib/active_support/core_ext/array/conversions.rb:3:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods.rb:9:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/bin/pod:36:in `<top (required)>'
	from /usr/local/Cellar/cocoapods/1.11.3/libexec/bin/pod:23:in `load'
	from /usr/local/Cellar/cocoapods/1.11.3/libexec/bin/pod:23:in `<main>'

```

I have tried to uninstall and install cocoapods using gem, install ruby 2.6.0, and also tried as the error message suggests, to do a `gem pristine --all` which will not install anything to pristine condition on a mac and give me this error:

```
Restoring gems to pristine condition...
Skipped error_highlight-0.3.0, it is a default gem
Skipped did_you_mean-1.6.1, it is a default gem
Skipped etc-1.3.0, it is a default gem
Skipped stringio-3.0.1, it is a default gem
Skipped psych-4.0.3, it is a default gem
Skipped strscan-3.0.1, it is a default gem
Skipped forwardable-1.3.2, it is a default gem
Skipped timeout-0.2.0, it is a default gem
Skipped openssl-3.0.0, it is a default gem
Skipped digest-3.1.0, it is a default gem
Skipped io-nonblock-0.1.0, it is a default gem
Skipped ipaddr-1.2.4, it is a default gem
Skipped io-wait-0.2.1, it is a default gem
Skipped abbrev-0.1.0, it is a default gem
Skipped base64-0.1.1, it is a default gem
Skipped benchmark-0.2.0, it is a default gem
Building native extensions. This could take a while...
Restored bigdecimal-3.1.2
Skipped bigdecimal-3.1.1, it is a default gem
Restored bundler-2.3.14
Skipped bundler-2.3.11, it is a default gem
Skipped cgi-0.3.1, it is a default gem
Skipped csv-3.2.2, it is a default gem
Skipped date-3.2.2, it is a default gem
Skipped delegate-0.2.0, it is a default gem
Skipped drb-2.1.0, it is a default gem
Skipped english-0.7.1, it is a default gem
Skipped erb-2.2.3, it is a default gem
Skipped fcntl-1.0.1, it is a default gem
Skipped fiddle-1.1.0, it is a default gem
Skipped fileutils-1.6.0, it is a default gem
Skipped find-0.1.1, it is a default gem
Skipped getoptlong-0.1.1, it is a default gem
Building native extensions. This could take a while...
Restored io-console-0.5.11
Skipped irb-1.4.1, it is a default gem
Skipped json-2.6.1, it is a default gem
Skipped logger-1.5.0, it is a default gem
Restored minitest-5.15.0
Skipped mutex_m-0.1.1, it is a default gem
Skipped net-http-0.2.0, it is a default gem
Skipped net-protocol-0.1.2, it is a default gem
Skipped nkf-0.1.1, it is a default gem
Skipped observer-0.1.1, it is a default gem
Skipped open-uri-0.2.0, it is a default gem
Skipped open3-0.1.1, it is a default gem
Skipped optparse-0.2.0, it is a default gem
Skipped ostruct-0.5.2, it is a default gem
Skipped pathname-0.2.0, it is a default gem
Skipped pp-0.3.0, it is a default gem
Skipped prettyprint-0.1.1, it is a default gem
Skipped pstore-0.1.1, it is a default gem
Skipped racc-1.6.0, it is a default gem
Skipped rdoc-6.4.0, it is a default gem
Skipped readline-0.0.3, it is a default gem
Skipped readline-ext-0.1.4, it is a default gem
Skipped reline-0.3.0, it is a default gem
Skipped resolv-0.2.1, it is a default gem
Skipped resolv-replace-0.1.0, it is a default gem
Skipped rinda-0.1.1, it is a default gem
Skipped ruby2_keywords-0.0.5, it is a default gem
Skipped securerandom-0.1.1, it is a default gem
Skipped set-1.0.2, it is a default gem
Skipped shellwords-0.1.0, it is a default gem
Skipped singleton-0.1.1, it is a default gem
Skipped syslog-0.1.0, it is a default gem
Skipped tempfile-0.1.2, it is a default gem
Skipped time-0.2.0, it is a default gem
Skipped tmpdir-0.1.2, it is a default gem
Skipped tsort-0.1.0, it is a default gem
Skipped un-0.2.0, it is a default gem
Skipped uri-0.11.0, it is a default gem
Skipped weakref-0.1.1, it is a default gem
Skipped yaml-0.2.0, it is a default gem
Skipped zlib-2.1.1, it is a default gem
```

`pod env` will also fail with this message:

```
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/dependency.rb:311:in `to_specs': Could not find 'CFPropertyList' (>= 2.3.3, < 4.0) among 74 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/Users/mars/.rvm/gems/ruby-2.6.0:/Users/mars/.rvm/gems/ruby-2.6.0@global:/usr/local/Cellar/cocoapods/1.11.3/libexec', execute `gem env` for more information
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1449:in `block in activate_dependencies'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `activate_dependencies'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1420:in `activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1452:in `block in activate_dependencies'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `activate_dependencies'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1420:in `activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:304:in `block in activate_bin_path'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:303:in `synchronize'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:303:in `activate_bin_path'
	from /usr/local/Cellar/cocoapods/1.11.3/libexec/bin/pod:23:in `<main>'
```

**Comment by jjazzme** [comment]
+1
same problem when applying flutter packages google_maps_flutter and sentry_flutter
