### ISSUE TITLE
I installed npm -i react-native-splash-screen --save and when I run pod install I get this error.

### ISSUE THREAD

**Issue by zalvarez23** [CocoaPods/CocoaPods#11377]
Ignoring ffi-1.15.5 because its extensions are not built. Try: gem pristine ffi --version 1.15.5
Auto-linking React Native modules for target `MyNewGym`: RNGestureHandler, RNVectorIcons, react-native-safe-area-context, react-native-splash-screen, and react-native-webview
[Codegen] Generating ./build/generated/ios/React-Codegen.podspec.json
Analyzing dependencies
[Codegen] Found FBReactNativeSpec
/Users/kevinsalazar/Desktop/Gym/MyNewGym/node_modules/react-native/scripts/react_native_pods_utils/script_phases.rb:50: warning: Passing safe_level with the 2nd argument of ERB.new is deprecated. Do not use it, and specify other arguments as keyword arguments.
/Users/kevinsalazar/Desktop/Gym/MyNewGym/node_modules/react-native/scripts/react_native_pods_utils/script_phases.rb:50: warning: Passing trim_mode with the 3rd argument of ERB.new is deprecated. Use keyword argument like ERB.new(str, trim_mode: ...) instead.
Downloading dependencies
Generating Pods project
/Users/kevinsalazar/Desktop/Gym/MyNewGym/ios/Pods/Target Support Files/Pods-MyNewGym/Pods-MyNewGym.release.xcconfig
/Users/kevinsalazar/Desktop/Gym/MyNewGym/ios/Pods/Target Support Files/Pods-MyNewGym/Pods-MyNewGym.debug.xcconfig
/Users/kevinsalazar/Desktop/Gym/MyNewGym/ios/Pods/Target Support Files/Pods-MyNewGym-MyNewGymTests/Pods-MyNewGym-MyNewGymTests.release.xcconfig
/Users/kevinsalazar/Desktop/Gym/MyNewGym/ios/Pods/Target Support Files/Pods-MyNewGym-MyNewGymTests/Pods-MyNewGym-MyNewGymTests.debug.xcconfig
React-Core
Integrating client project

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.11.3
        Ruby : ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin20]
    RubyGems : 3.3.11
        Host : macOS 12.3.1 (21E258)
       Xcode : 13.4 (13F17a)
         Git : git version 2.15.0
Ruby lib dir : /opt/homebrew/Cellar/ruby/3.1.2/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'
install! 'cocoapods', :deterministic_uuids => false

target 'MyNewGym' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'MyNewGymTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  #use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
```

### Error

```
Errno::EPERM - Operation not permitted @ apply2files - /Users/kevinsalazar/Desktop/Gym/MyNewGym/ios/Pods/DoubleConversion/double-conversion/bignum-dtoa.cc
/opt/homebrew/Cellar/ruby/3.1.2/lib/ruby/3.1.0/fileutils.rb:1326:in `chmod'
/opt/homebrew/Cellar/ruby/3.1.2/lib/ruby/3.1.0/fileutils.rb:1326:in `chmod'
/opt/homebrew/Cellar/ruby/3.1.2/lib/ruby/3.1.0/fileutils.rb:1002:in `block in chmod'
/opt/homebrew/Cellar/ruby/3.1.2/lib/ruby/3.1.0/fileutils.rb:1001:in `each'
/opt/homebrew/Cellar/ruby/3.1.2/lib/ruby/3.1.0/fileutils.rb:1001:in `chmod'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer/pod_source_installer.rb:94:in `lock_files!'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:591:in `block in lock_pod_sources'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:589:in `each'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:589:in `lock_pod_sources'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:652:in `run_plugins_post_install_hooks'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:614:in `perform_post_install_actions'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:170:in `install!'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/command/install.rb:52:in `run'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:52:in `run'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/bin/pod:25:in `load'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/bin/pod:25:in `<main>'

**Comment by zalvarez23** [comment]
@dnkoutso Any comments on a solution?

**Comment by dnkoutso** [comment]
Oops sorry I filled in response and never pressed "Comment". We do not accept issues with ReactNative or Flutter. Please remove either and file a new issue with out them showing a cocoapods bug.
