### ISSUE TITLE
Fail to perform `pod repo update` nor `pod install --repo-update`

### ISSUE THREAD

**Issue by cupidchan** [CocoaPods/CocoaPods#11410]
### Command

```
/opt/homebrew/lib/ruby/gems/2.7.0/bin/pod install --repo-update
```

### Report

* What did you do?
Try to run `pod repo update` or `pod install --repo-update` to resolve an issue of 
[!] CocoaPods could not find compatible versions for pod "Firebase/Auth":
  In Podfile:
    Firebase/Auth (~> 9.0)

* What did you expect to happen?
If will install the compatible version for pod "Firebase/Auth"

* What happened instead?
It throws the following error.

### Stack

```
   CocoaPods : 1.11.3
        Ruby : ruby 2.7.6p219 (2022-04-12 revision c9c2245c0a) [arm64-darwin21]
    RubyGems : 3.3.11
        Host : macOS 12.4 (21F79)
       Xcode : 13.4.1 (13F100)
         Git : git version 2.32.1 (Apple Git-133)
Ruby lib dir : /opt/homebrew/Cellar/ruby@2.7/2.7.6/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```

```

### Podfile

```ruby
use_frameworks!

target "nativeScriptProject" do
# Begin Podfile - /Users/user/Documents/GitHub/gitRepo/nativeScriptProject/node_modules/@nativescript/firebase-auth/platforms/ios/Podfile
pod 'Firebase/Auth','~>9.0'
# End Podfile

post_install do |installer|
  post_install_nativescript_firebase_core_0 installer
  post_installNSPodfileBase_0 installer
  post_installNativeScript_CLI_Architecture_Exclusions_0 installer
end

# NativeScriptPlatformSection /Users/user/Documents/GitHub/gitRepo/nativeScriptProject/App_Resources/iOS/Podfile with 12.0
platform :ios, '12.0'
# End NativeScriptPlatformSection

# Begin Podfile - /Users/user/Documents/GitHub/gitRepo/nativeScriptProject/node_modules/@nativescript/firebase-core/platforms/ios/Podfile
use_frameworks!
# platform :ios, '10.0'
#pod 'Firebase/CoreOnly'


def post_install_nativescript_firebase_core_0 (installer)
    installer.pods_project.targets.each do |target|
     target.build_configurations.each do |config|
        config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
       end
    end
  end

# End Podfile

# Begin Podfile - /Users/user/Documents/GitHub/gitRepo/nativeScriptProject/node_modules/@nativescript/firebase-functions/platforms/ios/Podfile
pod 'Firebase/Functions','~>9.0'

# End Podfile

# Begin Podfile - /Users/user/Documents/GitHub/gitRepo/nativeScriptProject/node_modules/@nativescript/google-signin/platforms/ios/Podfile
pod 'GoogleSignIn', '~> 6.0'
# End Podfile

# Begin Podfile - /Users/user/Documents/GitHub/gitRepo/nativeScriptProject/node_modules/@nativescript/secure-storage/platforms/ios/Podfile
pod 'SAMKeychain', '~> 1.5.3'
# End Podfile

# Begin Podfile - /Users/user/Documents/GitHub/gitRepo/nativeScriptProject/App_Resources/iOS/Podfile
# Firebase AppCheck requires minumum iOS 11.0
# platform :ios, '12.0'

# We cannot add FirebaseAppCheck now because it requires 'Firebase/Core', '~>8.0', which contradicts to @nativescript/firebase as it requires ~>6.34.0
# Either we find a way to update @nativescript/firebase package on the fly using Webpack, we need to wait until @nativescript/firebase new release before using AppCheck
# pod 'FirebaseAppCheck', '8.0.0-beta'
def post_installNSPodfileBase_0 (installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end

# End Podfile

# Begin Podfile - /Users/user/Documents/GitHub/gitRepo/nativeScriptProject/platforms/ios/Podfile-exclusions
def post_installNativeScript_CLI_Architecture_Exclusions_0 (installer)
  installer.pods_project.build_configurations.each do |config|
    config.build_settings.delete "VALID_ARCHS"
    config.build_settings["EXCLUDED_ARCHS_x86_64"] = "arm64 arm64e"
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "i386 armv6 armv7 armv7s armv8 $(EXCLUDED_ARCHS_$(NATIVE_ARCH_64_BIT))"
    config.build_settings["EXCLUDED_ARCHS[sdk=iphoneos*]"] = "i386 armv6 armv7 armv7s armv8 x86_64"
  end
end
# End Podfile
end
```

### Error

```
LoadError - dlopen(/opt/homebrew/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/lib/ffi_c.bundle, 0x0009): tried: '/opt/homebrew/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/lib/ffi_c.bundle' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')) - /opt/homebrew/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/lib/ffi_c.bundle
/opt/homebrew/Cellar/ruby@2.7/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
/opt/homebrew/Cellar/ruby@2.7/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/lib/ffi.rb:5:in `rescue in <top (required)>'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/ffi-1.15.5/lib/ffi.rb:2:in `<top (required)>'
/opt/homebrew/Cellar/ruby@2.7/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
/opt/homebrew/Cellar/ruby@2.7/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/ethon-0.15.0/lib/ethon.rb:3:in `<top (required)>'
/opt/homebrew/Cellar/ruby@2.7/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
/opt/homebrew/Cellar/ruby@2.7/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
/opt/homebrew/Cellar/ruby@2.7/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
/opt/homebrew/Cellar/ruby@2.7/2.7.6/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:440:in `download_typhoeus_impl_async'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:372:in `download_and_save_with_retries_async'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:365:in `download_file_async'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:338:in `download_file'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:78:in `deprecated_local_podspecs'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:60:in `preheat_existing_files'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:257:in `update'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/sources_manager.rb:144:in `block (3 levels) in update'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/sources_manager.rb:143:in `block (2 levels) in update'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/sources_manager.rb:142:in `each'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/sources_manager.rb:142:in `block in update'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/sources_manager.rb:140:in `open'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/sources_manager.rb:140:in `update'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:145:in `block in update_repositories'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:143:in `each'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:143:in `update_repositories'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:237:in `block in resolve_dependencies'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:236:in `resolve_dependencies'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:161:in `install!'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/command/install.rb:52:in `run'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:52:in `run'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
/opt/homebrew/lib/ruby/gems/2.7.0/bin/pod:25:in `load'
/opt/homebrew/lib/ruby/gems/2.7.0/bin/pod:25:in `<main>'

**Comment by cupidchan** [comment]
This issue is because I used an M1 Mac and ran `sudo arch -x86_64 gem install ffi`. To fix this problem, run `gem install ffi` instead which will install the correct version for M1 machine.
