### ISSUE TITLE
pod repo push failed

### ISSUE THREAD

**Issue by cqhcqhcqh** [CocoaPods/CocoaPods#11414]
### Command

```
/usr/local/bin/pod repo push versa-ai-ios-versa-specs VSShareConfig.podspec --allow-warnings --verbose --use-libraries --skip-tests --use-modular-headers --skip-import-validation
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.11.3
        Ruby : ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-darwin20]
    RubyGems : 3.3.15
        Host : macOS 12.0.1 (21A559)
       Xcode : 13.4 (13F17a)
         Git : git version 2.32.1 (Apple Git-133)
Ruby lib dir : /usr/local/Cellar/ruby/3.0.1/lib
Repositories : aliyun - git - https://github.com/aliyun/aliyun-specs.git @ cc1d635db2e2befde9dfd2883745f34522e9a835

               master - git - https://github.com/CocoaPods/Specs.git @ d1984b7bfe3502e015b5967a53603a995be112d0

               taobao-baichuansdk-alibcspecs - git - http://repo.baichuan-ios.taobao.com/baichuanSDK/AliBCSpecs.git @ 3a5d6a75d9ac5067ce5b8375949119755755ee0a

               trunk - CDN - https://cdn.cocoapods.org/
               versa-ai-ios-versa-specs - git - https://git.versa-ai.com/ios/Versa-Specs.git @ 5e94404238937e56ebdbe1c6b3af15cbbe3dce44

               vmovier-scm-nsm-specs - git - https://git.vmovier.cc/scm/nsm/specs.git @ 4c39ddb18690d821e454900cf7b89057768f4b74

```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Error

```
SyntaxError - /Users/caitou/.gems/gems/mime-types-3.3/lib/mime/types/logger.rb:30: _1 is reserved for numbered parameter
/Users/caitou/.gems/gems/mime-types-3.3/lib/mime/types/logger.rb:30: _2 is reserved for numbered parameter
/Users/caitou/.gems/gems/mime-types-3.3/lib/mime/types/logger.rb:30: _3 is reserved for numbered parameter
<internal:/usr/local/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/usr/local/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/Users/caitou/.gems/gems/mime-types-3.3/lib/mime/types.rb:229:in `<top (required)>'
<internal:/usr/local/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/usr/local/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/Users/caitou/.gems/gems/mime-types-3.3/lib/mime/types/columnar.rb:3:in `<top (required)>'
<internal:/usr/local/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:160:in `require'
<internal:/usr/local/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'
<internal:/usr/local/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:149:in `require'
/Users/caitou/.gems/gems/ethon-0.12.0/lib/ethon.rb:5:in `<top (required)>'
<internal:/usr/local/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/usr/local/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/Users/caitou/.gems/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
<internal:/usr/local/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/usr/local/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/Users/caitou/.gems/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:440:in `download_typhoeus_impl_async'
/Users/caitou/.gems/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:372:in `download_and_save_with_retries_async'
/Users/caitou/.gems/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:365:in `download_file_async'
/Users/caitou/.gems/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:338:in `download_file'
/Users/caitou/.gems/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:284:in `ensure_versions_file_loaded'
/Users/caitou/.gems/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:208:in `search'
/Users/caitou/.gems/gems/cocoapods-core-1.11.3/lib/cocoapods-core/source/aggregate.rb:83:in `block in search'
/Users/caitou/.gems/gems/cocoapods-core-1.11.3/lib/cocoapods-core/source/aggregate.rb:83:in `select'
/Users/caitou/.gems/gems/cocoapods-core-1.11.3/lib/cocoapods-core/source/aggregate.rb:83:in `search'
/Users/caitou/.gems/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:416:in `create_set_from_sources'
/Users/caitou/.gems/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:385:in `find_cached_set'
/Users/caitou/.gems/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:360:in `specifications_for_dependency'
/Users/caitou/.gems/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:165:in `search_for'
/Users/caitou/.gems/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:274:in `block in sort_dependencies'
/Users/caitou/.gems/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:267:in `each'
/Users/caitou/.gems/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:267:in `sort_by'
/Users/caitou/.gems/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:267:in `sort_by!'
/Users/caitou/.gems/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:267:in `sort_dependencies'
/Users/caitou/.gems/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:60:in `block in sort_dependencies'
/Users/caitou/.gems/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:77:in `with_no_such_dependency_error_handling'
/Users/caitou/.gems/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:59:in `sort_dependencies'
/Users/caitou/.gems/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:754:in `push_state_for_requirements'
/Users/caitou/.gems/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:744:in `require_nested_dependencies_for'
/Users/caitou/.gems/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:727:in `activate_new_spec'
/Users/caitou/.gems/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:684:in `attempt_to_activate'
/Users/caitou/.gems/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:254:in `process_topmost_state'
/Users/caitou/.gems/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:182:in `resolve'
/Users/caitou/.gems/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in `resolve'
/Users/caitou/.gems/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:94:in `resolve'
/Users/caitou/.gems/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:1078:in `block in resolve_dependencies'
/Users/caitou/.gems/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
/Users/caitou/.gems/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:1076:in `resolve_dependencies'
/Users/caitou/.gems/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/Users/caitou/.gems/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:416:in `analyze'
/Users/caitou/.gems/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:241:in `block in resolve_dependencies'
/Users/caitou/.gems/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
/Users/caitou/.gems/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:240:in `resolve_dependencies'
/Users/caitou/.gems/gems/cocoapods-1.11.3/lib/cocoapods/validator.rb:577:in `block in download_pod'
/Users/caitou/.gems/gems/cocoapods-1.11.3/lib/cocoapods/validator.rb:577:in `each'
/Users/caitou/.gems/gems/cocoapods-1.11.3/lib/cocoapods/validator.rb:577:in `download_pod'
/Users/caitou/.gems/gems/cocoapods-1.11.3/lib/cocoapods/validator.rb:399:in `block in perform_extensive_analysis'
/Users/caitou/.gems/gems/cocoapods-1.11.3/lib/cocoapods/validator.rb:393:in `each'
/Users/caitou/.gems/gems/cocoapods-1.11.3/lib/cocoapods/validator.rb:393:in `perform_extensive_analysis'
/Users/caitou/.gems/gems/cocoapods-1.11.3/lib/cocoapods/validator.rb:130:in `validate'
/Users/caitou/.gems/gems/cocoapods-1.11.3/lib/cocoapods/command/repo/push.rb:148:in `block in validate_podspec_files'
/Users/caitou/.gems/gems/cocoapods-1.11.3/lib/cocoapods/command/repo/push.rb:138:in `each'
/Users/caitou/.gems/gems/cocoapods-1.11.3/lib/cocoapods/command/repo/push.rb:138:in `validate_podspec_files'
/Users/caitou/.gems/gems/cocoapods-1.11.3/lib/cocoapods/command/repo/push.rb:79:in `run'
/Users/caitou/.gems/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Users/caitou/.gems/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:52:in `run'
/Users/caitou/.gems/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:25:in `load'
/usr/local/bin/pod:25:in `<main>'
```

**Comment by cqhcqhcqh** [comment]
solved by pod push spec --specs ''
