### ISSUE TITLE
An error occurred when executing pod init

### ISSUE THREAD

**Issue by sunimp** [CocoaPods/CocoaPods#11434]
### Device&System
Device:  M1 Pro MacBook Pro 16"
ProductName:	macOS
ProductVersion:	12.4
BuildVersion:	21F79

### Command

```
/Users/sun/.rvm/gems/ruby-3.0.0/bin/pod init
```

### Report

* What did you do?
exec `pod init`

* What did you expect to happen?
Generate Podfile, initialize successful.
* What happened instead?
I don't know

### Stack

```
   CocoaPods : 1.11.3
        Ruby : ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [arm64-darwin21]
    RubyGems : 3.2.3
        Host : macOS 12.4 (21F79)
       Xcode : 14.0 (14A5228q)
         Git : git version 2.36.1
Ruby lib dir : /Users/sun/.rvm/rubies/ruby-3.0.0/lib
Repositories : 189-cocoapods-specsacc - git - http://10.0.189.5:10080/CocoaPods/SpecsAcc.git @ 5304afc40ff9cc52a14952075a4323ae507ce8a9

               cocoapods - git - https://github.com/CocoaPods/Specs.git @ 6d5d3168b8c38b84e26d23d9ce7474d4f09174c1

               trunk - CDN - https://cdn.cocoapods.org/
               ustock-stocks - git - https://gitlab.ustock.cc:5253/stocks/Specs.git @ f444b9a4753f049a4686f9be56c5ab05e33a216c

               ustock-stocks-1 - git - ssh://git@gitlab.ustock.cc:5153/stocks/Specs.git @ a95a6c003edc978b2ffe47631baaf9fa3d102403

```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Error

```
RuntimeError - [Xcodeproj] Unknown object version (56).
/Users/sun/.rvm/gems/ruby-3.0.0/gems/xcodeproj-1.21.0/lib/xcodeproj/project.rb:228:in `initialize_from_file'
/Users/sun/.rvm/gems/ruby-3.0.0/gems/xcodeproj-1.21.0/lib/xcodeproj/project.rb:113:in `open'
/Users/sun/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.3/lib/cocoapods/command/init.rb:41:in `validate!'
/Users/sun/.rvm/gems/ruby-3.0.0/gems/claide-1.1.0/lib/claide/command.rb:333:in `run'
/Users/sun/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:52:in `run'
/Users/sun/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
/Users/sun/.rvm/gems/ruby-3.0.0/bin/pod:23:in `load'
/Users/sun/.rvm/gems/ruby-3.0.0/bin/pod:23:in `<main>'

**Comment by dnkoutso** [comment]
Please try `gem update xcodeproj`.

**Comment by kashif1akhtar** [comment]
Its giving me 
gem update xcodeproj
Updating installed gems
Updating xcodeproj
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.6.0 directory.
