### ISSUE TITLE
Keep getting "Permission denied @ rb_file_s_rename"

### ISSUE THREAD

**Issue by Chris854** [CocoaPods/CocoaPods#11460]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod install`

## What did you expect to happen?

Install all pod dependencies correctly.

Permission denied @ rb_file_s_rename

Getting error Permission denied @ rb_file_s_rename

### Stack

```
   CocoaPods : 1.11.3
        Ruby : ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin21]
    RubyGems : 3.2.3
        Host : macOS 12.4 (21F79)
       Xcode : 13.4.1 (13F100)
         Git : git version 2.32.1 (Apple Git-133)
Ruby lib dir : /Users/user/.rvm/rubies/ruby-3.0.0/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
source 'https://cdn.cocoapods.org/'
platform :ios, '11.0'

target 'UnityFramework' do
  pod 'AppLovinMediationGoogleAdapter', '9.6.0.1'
  pod 'AppLovinMediationUnityAdsAdapter', '4.2.1.0'
  pod 'AppLovinSDK', '11.4.3'
  pod 'FBSDKCoreKit', '~> 13.2'
  pod 'FBSDKCoreKit_Basics', '~> 13.2'
  pod 'FBSDKGamingServicesKit', '~> 13.2'
  pod 'FBSDKLoginKit', '~> 13.2'
  pod 'FBSDKShareKit', '~> 13.2'
end
target 'Unity-iPhone' do
end
use_frameworks! :linkage => :static
use_frameworks!
```

## Full error

```
Errno::EACCES - Permission denied @ rb_file_s_rename - (/var/folders/29/ljn38xc95zs4wvs1j16vmtjw0000gn/T/.atomos.project.pbxproj20220711-50014-l8ubgg, /Users/user/Desktop/buildManagement/iosBuild/Unity-iPhone.xcodeproj/project.pbxproj)
/Users/user/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/atomos-0.1.3/lib/atomos.rb:26:in `rename'
/Users/user/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/atomos-0.1.3/lib/atomos.rb:26:in `block in atomic_write'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tempfile.rb:295:in `open'
/Users/user/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/atomos-0.1.3/lib/atomos.rb:17:in `atomic_write'
/Users/user/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project.rb:364:in `save'
/usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer/user_project_integrator.rb:158:in `block in save_projects'
/usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer/user_project_integrator.rb:156:in `each'
/usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer/user_project_integrator.rb:156:in `save_projects'
/usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer/user_project_integrator.rb:76:in `integrate!'
/usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:860:in `block in integrate_user_project'
/usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:856:in `integrate_user_project'
/usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:182:in `integrate'
/usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:167:in `install!'
/usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/command/install.rb:52:in `run'
/Users/user/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:52:in `run'
/usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
/usr/local/Cellar/cocoapods/1.11.3/libexec/bin/pod:23:in `load'
/usr/local/Cellar/cocoapods/1.11.3/libexec/bin/pod:23:in `<main>'
```

**Comment by xygkevin** [comment]
我也遇到了同样的问题，求解
