### ISSUE TITLE
Run pod try mParticle-Apple-SDK and see this error: Searching for inspections failed: undefined method `map' for nil:NilClass        report.issues = results['items'].map { |item| Issue.new(item) }

### ISSUE THREAD

**Issue by JorgeAriasArg-Globant** [CocoaPods/CocoaPods#11569]
I'm using a M1 machine and I'm following this docs
- https://cocoapods.org/pods/mParticle-Apple-SDK
- https://cocoapods.org/pods/mParticle-Appboy
- https://cocoapods.org/pods/mParticle-BranchMetrics

to try upgrade:
- mParticle-Apple-SDK: 8.3.0 to 8.8.0
- mParticle-BranchMetrics-Kit: 8.0.5 to 8.0.6
- mParticle-Appboy-Kit: 8.0.4 to 8.0.16

### Command

```
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/bin/pod try mParticle-Apple-SDK
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.11.3
        Ruby : ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]
    RubyGems : 3.3.11
        Host : macOS 12.5.1 (21G83)
       Xcode : 14.0 (14A309)
         Git : git version 2.37.0 (Apple Git-136)
Ruby lib dir : /opt/homebrew/Cellar/ruby/3.1.2_1/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ aa4f1011d5ad28098fc06a6f3018ada240ca1161

               trunk - CDN - https://cdn.cocoapods.org/
               turnercode-prism-pod-specs - git - https://github.com/turnercode/prism-pod-specs.git @ 5f9b0099266f72464866bfb09bad05b080c0e183

```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
source ...
source ...

# Comment the next line if you don't want to use dynamic frameworks
# use_frameworks!

def shared_pods
  # Pods for WME
  pod 'React', :path => '../node_modules/react-native', subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket',
    'RCTImage',
  ], :modular_headers => true

  # the following dependencies are dependencies of React native itself.
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  #Third party libraries
  pod 'RNPsmBridge', :path => '../node_modules/@turnercode/react-native-psm-bridge/ios', :modular_headers => true
  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'
  pod 'react-native-mparticle', :path => '../node_modules/react-native-mparticle'
  pod 'mParticle-Apple-SDK', '~> 8.8'
  pod 'RNSentry', :path => '../node_modules/@sentry/react-native'
  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'
  # Adobe Analytics
  pod 'RCTACPCore', :path => '../node_modules/@adobe/react-native-acpcore'
  pod 'RCTACPUserProfile', :path => '../node_modules/@adobe/react-native-acpuserprofile'
  pod 'RCTACPAnalytics', :path => '../node_modules/@adobe/react-native-acpanalytics'
  pod 'RCTACPMedia', :path => '../node_modules/@adobe/react-native-acpmedia'
end

target 'WME' do
  platform :ios, '13.0'
  shared_pods
  pod 'mParticle-Appboy', '~> 8.0.16'
  pod 'mParticle-BranchMetrics', '~> 8.0.6'
  pod 'RNHelpshift', :path => '../node_modules/react-native-gethelpschwifty/ios'
  pod 'react-native-geolocation-service', path: '../node_modules/react-native-geolocation-service'
end

# The following is needed to ensure the "archive" step works in XCode.
# It removes React & Yoga from the Pods project, as it is already included in the main project.
post_install do |installer|
  installer.pods_project.targets.each do |target|
    targets_to_ignore = %w(React yoga)

    if targets_to_ignore.include? target.name
      target.remove_from_project
    end
  end
end
```

### Error

```
LoadError - dlopen(/opt/homebrew/lib/ruby/gems/3.1.0/gems/ffi-1.15.5/lib/ffi_c.bundle, 0x0009): tried: '/opt/homebrew/lib/ruby/gems/3.1.0/gems/ffi-1.15.5/lib/ffi_c.bundle' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e))) - /opt/homebrew/lib/ruby/gems/3.1.0/gems/ffi-1.15.5/lib/ffi_c.bundle
<internal:/opt/homebrew/Cellar/ruby/3.1.2_1/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/opt/homebrew/Cellar/ruby/3.1.2_1/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/opt/homebrew/lib/ruby/gems/3.1.0/gems/ffi-1.15.5/lib/ffi.rb:5:in `rescue in <top (required)>'
/opt/homebrew/lib/ruby/gems/3.1.0/gems/ffi-1.15.5/lib/ffi.rb:2:in `<top (required)>'
<internal:/opt/homebrew/Cellar/ruby/3.1.2_1/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/opt/homebrew/Cellar/ruby/3.1.2_1/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/opt/homebrew/lib/ruby/gems/3.1.0/gems/ethon-0.15.0/lib/ethon.rb:3:in `<top (required)>'
<internal:/opt/homebrew/Cellar/ruby/3.1.2_1/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/opt/homebrew/Cellar/ruby/3.1.2_1/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/opt/homebrew/lib/ruby/gems/3.1.0/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
<internal:/opt/homebrew/Cellar/ruby/3.1.2_1/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/opt/homebrew/Cellar/ruby/3.1.2_1/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/opt/homebrew/lib/ruby/gems/3.1.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:440:in `download_typhoeus_impl_async'
/opt/homebrew/lib/ruby/gems/3.1.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:372:in `download_and_save_with_retries_async'
/opt/homebrew/lib/ruby/gems/3.1.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:365:in `download_file_async'
/opt/homebrew/lib/ruby/gems/3.1.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:338:in `download_file'
/opt/homebrew/lib/ruby/gems/3.1.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:78:in `deprecated_local_podspecs'
/opt/homebrew/lib/ruby/gems/3.1.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:60:in `preheat_existing_files'
/opt/homebrew/lib/ruby/gems/3.1.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:257:in `update'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/sources_manager.rb:144:in `block (3 levels) in update'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/sources_manager.rb:143:in `block (2 levels) in update'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/sources_manager.rb:142:in `each'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/sources_manager.rb:142:in `block in update'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/sources_manager.rb:140:in `open'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/sources_manager.rb:140:in `update'
/opt/homebrew/lib/ruby/gems/3.1.0/gems/cocoapods-try-1.2.0/lib/pod/command/try.rb:223:in `block in update_specs_repos'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
/opt/homebrew/lib/ruby/gems/3.1.0/gems/cocoapods-try-1.2.0/lib/pod/command/try.rb:222:in `update_specs_repos'
/opt/homebrew/lib/ruby/gems/3.1.0/gems/cocoapods-try-1.2.0/lib/pod/command/try.rb:79:in `setup_spec_in_sandbox'
/opt/homebrew/lib/ruby/gems/3.1.0/gems/cocoapods-try-1.2.0/lib/pod/command/try.rb:47:in `run'
/opt/homebrew/lib/ruby/gems/3.1.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:52:in `run'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/bin/pod:25:in `load'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/bin/pod:25:in `<main>'
```

and finally I see this:

[!] Oh no, an error occurred.

Looking for related issues on cocoapods/cocoapods...
Searching for inspections failed: undefined method `map' for nil:NilClass

      report.issues = results['items'].map { |item| Issue.new(item) }
                                      ^^^^

**Comment by JorgeAriasArg-Globant** [comment]
error related mParticle not cocoapods
