### ISSUE TITLE
XCFramework linkage incorrect when MacCatalyst first slice in framework plist

### ISSUE THREAD

**Issue by seanreinhardtapps** [CocoaPods/CocoaPods#11608]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
Setup:
- dynamic library XCFramework
- plist lists ios-arm64_x86_64-maccatalyst as first slice (example added below)

Command:
`pod install`

## What did you expect to happen?
[CP] Embed Pods Frameworks Build Phase added to target

## What happened instead?
Build phase not added

Found that on some machines (haven't narrowed down specifics yet) ruby-macho raises an error when evaluating a Mac Catalyst slice:
> Traceback (most recent call last):
       16: from /Users/sreinhardt/.rvm/rubies/ruby-2.7.3/bin/irb:23:in `load'
       15: from /Users/sreinhardt/.rvm/rubies/ruby-2.7.3/lib/ruby/gems/2.7.0/gems/irb-1.2.6/exe/irb:11:in `<top (required)>'
       14: from (irb):4
       13: from /Users/sreinhardt/.rvm/gems/ruby-2.7.3/gems/ruby-macho-1.4.0/lib/macho.rb:31:in `open'
       12: from /Users/sreinhardt/.rvm/gems/ruby-2.7.3/gems/ruby-macho-1.4.0/lib/macho.rb:31:in `new'
       11: from /Users/sreinhardt/.rvm/gems/ruby-2.7.3/gems/ruby-macho-1.4.0/lib/macho/fat_file.rb:95:in `initialize'
       10: from /Users/sreinhardt/.rvm/gems/ruby-2.7.3/gems/ruby-macho-1.4.0/lib/macho/fat_file.rb:156:in `populate_fields'
        9: from /Users/sreinhardt/.rvm/gems/ruby-2.7.3/gems/ruby-macho-1.4.0/lib/macho/fat_file.rb:364:in `populate_machos'
        8: from /Users/sreinhardt/.rvm/gems/ruby-2.7.3/gems/ruby-macho-1.4.0/lib/macho/fat_file.rb:364:in `each'
        7: from /Users/sreinhardt/.rvm/gems/ruby-2.7.3/gems/ruby-macho-1.4.0/lib/macho/fat_file.rb:365:in `block in populate_machos'
        6: from /Users/sreinhardt/.rvm/gems/ruby-2.7.3/gems/ruby-macho-1.4.0/lib/macho/macho_file.rb:33:in `new_from_bin'
        5: from /Users/sreinhardt/.rvm/gems/ruby-2.7.3/gems/ruby-macho-1.4.0/lib/macho/macho_file.rb:55:in `initialize_from_bin'
        4: from /Users/sreinhardt/.rvm/gems/ruby-2.7.3/gems/ruby-macho-1.4.0/lib/macho/macho_file.rb:234:in `populate_fields'
        3: from /Users/sreinhardt/.rvm/gems/ruby-2.7.3/gems/ruby-macho-1.4.0/lib/macho/macho_file.rb:517:in `populate_load_commands'
        2: from /Users/sreinhardt/.rvm/gems/ruby-2.7.3/gems/ruby-macho-1.4.0/lib/macho/macho_file.rb:517:in `times'
        1: from /Users/sreinhardt/.rvm/gems/ruby-2.7.3/gems/ruby-macho-1.4.0/lib/macho/macho_file.rb:522:in `block in populate_load_commands'
MachO::LoadCommandError (Unrecognized Mach-O load command: 0x80000034)

This causes the `dynamic_binary?` check to fall into the catch block here: https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/xcode/linkage_analyzer.rb#L17 and cache the framework as non dynamic linkage.  Issue was mitigated by manually re-arranging the plist that was generated for the xcframework so that another slice is evaluated first.

Not reproducible on all laptop/OS, originally occurred on

> MacBook Pro (13-inch, M1, 2020), macOS 12.6 (21G115), Apple M1

### Stack

```
   CocoaPods : 1.11.3
        Ruby : ruby 2.7.3p183 (2021-04-05 revision 6847ee089d) [arm64-darwin20]
    RubyGems : 3.1.6
        Host : macOS 12.6 (21G115)
       Xcode : 14.0 (14A309)
         Git : git version 2.37.0 (Apple Git-136)
Ruby lib dir : /Users/sreinhardt/.rvm/rubies/ruby-2.7.3/lib
Repositories : jungroupproductions-private-cocoapod-specs - git - git@github.com:JunGroupProductions/Private-Cocoapod-Specs.git @ 7e50dd7db8821a1748f26d229becf90088fa5fc1

```

### Installation Source

```
Executable Path: /Users/sreinhardt/.rvm/gems/ruby-2.7.3/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

Example Framework Plist:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>AvailableLibraries</key>
	<array>
		<dict>
			<key>LibraryIdentifier</key>
			<string>ios-arm64_x86_64-maccatalyst</string>
			<key>LibraryPath</key>
			<string>HyprMX.framework</string>
			<key>SupportedArchitectures</key>
			<array>
				<string>arm64</string>
				<string>x86_64</string>
			</array>
			<key>SupportedPlatform</key>
			<string>ios</string>
			<key>SupportedPlatformVariant</key>
			<string>maccatalyst</string>
		</dict>
		<dict>
			<key>LibraryIdentifier</key>
			<string>ios-arm64</string>
			<key>LibraryPath</key>
			<string>HyprMX.framework</string>
			<key>SupportedArchitectures</key>
			<array>
				<string>arm64</string>
			</array>
			<key>SupportedPlatform</key>
			<string>ios</string>
		</dict>
		<dict>
			<key>LibraryIdentifier</key>
			<string>ios-arm64_x86_64-simulator</string>
			<key>LibraryPath</key>
			<string>HyprMX.framework</string>
			<key>SupportedArchitectures</key>
			<array>
				<string>arm64</string>
				<string>x86_64</string>
			</array>
			<key>SupportedPlatform</key>
			<string>ios</string>
			<key>SupportedPlatformVariant</key>
			<string>simulator</string>
		</dict>
	</array>
	<key>CFBundlePackageType</key>
	<string>XFWK</string>
	<key>XCFrameworkFormatVersion</key>
	<string>1.0</string>
</dict>
</plist>
```

**Comment by misakatao** [comment]
The .framework file directory structure on macos is:
```
├── xxx.framework
│   ├── Headers
│   ├── Modules
│   ├── Resources
│   └── Versions
│       └── Current
│           ├── Headers
│           ├── Modules
│           ├── xxx
│           └── Resources
```
which is different from ios is:
```
├── xxx.framework
│   ├── Headers
│   ├── Modules
│   ├── Resources
│   └── xxx
```
so, the "path + name" was empty
https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/xcode/xcframework/xcframework_slice.rb#L127

**Comment by guzuqing** [comment]
same question like #10390  You can upgrade 'ruby-macho' to solve the problem
