### ISSUE TITLE
Pod Install Error

### ISSUE THREAD

**Issue by joshua-matchala** [CocoaPods/CocoaPods#11615]
――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/lib/ruby/gems/3.1.0/bin/pod install
```

### Report

* What did you do?
Built from Unity Version 2020.1.20 and then ran a pod install in the built folder.

* What did you expect to happen?
Pods successfully installed
* What happened instead?
The below error.

### Stack

```
   CocoaPods : 1.11.3
        Ruby : ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-darwin21]
    RubyGems : 3.3.24
        Host : macOS 12.6 (21G115)
       Xcode : 14.0.1 (14A400)
         Git : git version 2.37.0 (Apple Git-136)
Ruby lib dir : /usr/local/Cellar/ruby/3.1.2_1/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ cf097ed86578107ee79a8a765f319b2d40e99f88

               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
source 'https://cdn.cocoapods.org/'
platform :ios, '12.0'

target 'UnityFramework' do
  pod 'AppLovinMediationFacebookAdapter', '6.12.0.0'
  pod 'AppLovinMediationGoogleAdapter', '9.11.0.3'
  pod 'AppLovinMediationUnityAdsAdapter', '4.4.1.0'
  pod 'AppLovinSDK', '11.5.3'
  pod 'AppsFlyerFramework', '6.1.1'
  pod 'FBSDKCoreKit', '~> 8.0'
  pod 'FBSDKGamingServicesKit', '~> 8.0'
  pod 'FBSDKLoginKit', '~> 8.0'
  pod 'FBSDKShareKit', '~> 8.0'
  pod 'Firebase/Analytics', '10.0.0'
  pod 'Firebase/Auth', '10.0.0'
  pod 'Firebase/Core', '10.0.0'
  pod 'Firebase/Crashlytics', '10.0.0'
  pod 'Firebase/Messaging', '10.0.0'
  pod 'Firebase/RemoteConfig', '10.0.0'
  pod 'FirebaseInstallations'
end
target 'Unity-iPhone' do
end
use_frameworks! :linkage => :static
```

### Error

```
RuntimeError - [Xcodeproj] Consistency issue: no parent for object `libiPhone-lib.dylib`: `FrameworksBuildPhase`, `Copy Shared Libraries`
/usr/local/lib/ruby/gems/3.1.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project/object/helpers/groupable_helper.rb:19:in `parent'
/usr/local/lib/ruby/gems/3.1.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project/object/build_file.rb:77:in `ascii_plist_annotation'
/usr/local/lib/ruby/gems/3.1.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project.rb:297:in `block in to_ascii_plist'
/usr/local/lib/ruby/gems/3.1.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project.rb:296:in `each'
/usr/local/lib/ruby/gems/3.1.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project.rb:296:in `to_ascii_plist'
/usr/local/lib/ruby/gems/3.1.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project.rb:365:in `block in save'
/usr/local/lib/ruby/gems/3.1.0/gems/atomos-0.1.3/lib/atomos.rb:21:in `block in atomic_write'
/usr/local/Cellar/ruby/3.1.2_1/lib/ruby/3.1.0/tempfile.rb:317:in `open'
/usr/local/lib/ruby/gems/3.1.0/gems/atomos-0.1.3/lib/atomos.rb:17:in `atomic_write'
/usr/local/lib/ruby/gems/3.1.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project.rb:364:in `save'
/usr/local/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/user_project_integrator.rb:158:in `block in save_projects'
/usr/local/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/user_project_integrator.rb:156:in `each'
/usr/local/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/user_project_integrator.rb:156:in `save_projects'
/usr/local/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/user_project_integrator.rb:76:in `integrate!'
/usr/local/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:860:in `block in integrate_user_project'
/usr/local/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:856:in `integrate_user_project'
/usr/local/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:182:in `integrate'
/usr/local/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:167:in `install!'
/usr/local/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/command/install.rb:52:in `run'
/usr/local/lib/ruby/gems/3.1.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
/usr/local/lib/ruby/gems/3.1.0/bin/pod:25:in `load'
/usr/local/lib/ruby/gems/3.1.0/bin/pod:25:in `<main>'
```

――― TEMPLATE END

**Comment by jakerobb** [comment]
Cocoapods officially supports Ruby 3.0. IDK if it is expected to work with 3.1 (or 3.2?).
