### ISSUE TITLE
ffi issue when running pod repo update  on macOS Ventura

### ISSUE THREAD

**Issue by DargonLee** [CocoaPods/CocoaPods#11628]
/Library/Ruby/Site/2.6.0/rubygems/specification.rb:1404:in `rescue in block in activate_dependencies': Could not find 'ffi' (>= 1.15.0) among 91 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/Users/apple/.gem/ruby/2.6.0:/Library/Ruby/Gems/2.6.0:/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0' at: /Library/Ruby/Gems/2.6.0/specifications/ethon-0.14.0.gemspec, execute `gem env` for more information
	from /Library/Ruby/Site/2.6.0/rubygems/specification.rb:1401:in `block in activate_dependencies'
	from /Library/Ruby/Site/2.6.0/rubygems/specification.rb:1390:in `each'
	from /Library/Ruby/Site/2.6.0/rubygems/specification.rb:1390:in `activate_dependencies'
	from /Library/Ruby/Site/2.6.0/rubygems/specification.rb:1372:in `activate'
	from /Library/Ruby/Site/2.6.0/rubygems/specification.rb:1408:in `block in activate_dependencies'
	from /Library/Ruby/Site/2.6.0/rubygems/specification.rb:1390:in `each'
	from /Library/Ruby/Site/2.6.0/rubygems/specification.rb:1390:in `activate_dependencies'
	from /Library/Ruby/Site/2.6.0/rubygems/specification.rb:1372:in `activate'
	from /Library/Ruby/Site/2.6.0/rubygems/specification.rb:1408:in `block in activate_dependencies'
	from /Library/Ruby/Site/2.6.0/rubygems/specification.rb:1390:in `each'
	from /Library/Ruby/Site/2.6.0/rubygems/specification.rb:1390:in `activate_dependencies'
	from /Library/Ruby/Site/2.6.0/rubygems/specification.rb:1372:in `activate'
	from /Library/Ruby/Site/2.6.0/rubygems/specification.rb:1408:in `block in activate_dependencies'
	from /Library/Ruby/Site/2.6.0/rubygems/specification.rb:1390:in `each'
	from /Library/Ruby/Site/2.6.0/rubygems/specification.rb:1390:in `activate_dependencies'
	from /Library/Ruby/Site/2.6.0/rubygems/specification.rb:1372:in `activate'
	from /Library/Ruby/Site/2.6.0/rubygems.rb:299:in `block in activate_bin_path'
	from /Library/Ruby/Site/2.6.0/rubygems.rb:298:in `synchronize'
	from /Library/Ruby/Site/2.6.0/rubygems.rb:298:in `activate_bin_path'
	from /usr/local/bin/pod:25:in `<main>'
/Library/Ruby/Site/2.6.0/rubygems/dependency.rb:311:in `to_specs': Could not find 'ffi' (>= 1.15.0) among 91 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/Users/apple/.gem/ruby/2.6.0:/Library/Ruby/Gems/2.6.0:/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0' , execute `gem env` for more information
	from /Library/Ruby/Site/2.6.0/rubygems/specification.rb:1402:in `block in activate_dependencies'
	from /Library/Ruby/Site/2.6.0/rubygems/specification.rb:1390:in `each'
	from /Library/Ruby/Site/2.6.0/rubygems/specification.rb:1390:in `activate_dependencies'
	from /Library/Ruby/Site/2.6.0/rubygems/specification.rb:1372:in `activate'
	from /Library/Ruby/Site/2.6.0/rubygems/specification.rb:1408:in `block in activate_dependencies'
	from /Library/Ruby/Site/2.6.0/rubygems/specification.rb:1390:in `each'
	from /Library/Ruby/Site/2.6.0/rubygems/specification.rb:1390:in `activate_dependencies'
	from /Library/Ruby/Site/2.6.0/rubygems/specification.rb:1372:in `activate'
	from /Library/Ruby/Site/2.6.0/rubygems/specification.rb:1408:in `block in activate_dependencies'
	from /Library/Ruby/Site/2.6.0/rubygems/specification.rb:1390:in `each'
	from /Library/Ruby/Site/2.6.0/rubygems/specification.rb:1390:in `activate_dependencies'
	from /Library/Ruby/Site/2.6.0/rubygems/specification.rb:1372:in `activate'
	from /Library/Ruby/Site/2.6.0/rubygems/specification.rb:1408:in `block in activate_dependencies'
	from /Library/Ruby/Site/2.6.0/rubygems/specification.rb:1390:in `each'
	from /Library/Ruby/Site/2.6.0/rubygems/specification.rb:1390:in `activate_dependencies'
	from /Library/Ruby/Site/2.6.0/rubygems/specification.rb:1372:in `activate'
	from /Library/Ruby/Site/2.6.0/rubygems.rb:299:in `block in activate_bin_path'
	from /Library/Ruby/Site/2.6.0/rubygems.rb:298:in `synchronize'
	from /Library/Ruby/Site/2.6.0/rubygems.rb:298:in `activate_bin_path'
	from /usr/local/bin/pod:25:in `<main>'

**Comment by DargonLee** [comment]
fix it with :
1、sudo gem uninstall cocoapods
2、brew cleanup -d -v 
3、brew install cocoapods
4、brew link cocoapods
5、Done
it's work for me

**Comment by onkar-13** [comment]
https://stackoverflow.com/a/74223086

**Comment by onkar-13** [comment]
https://stackoverflow.com/a/74223086

this worked for me

**Comment by git4jwb** [comment]
> 修复它： 1、sudo gem uninstall cocoapods 2、brew cleanup -d -v 3、brew install cocoapods 4、brew link cocoapods 5、 对我有用

重新安装时，会安装一个ventura M1专用的版本：1.11.3.arm64_ventura
🎉🎉🎉

**Comment by ZainaliSyed** [comment]
> brew link cocoapods

Thank you so much , You saved my Day 👍

**Comment by hafiz-mohsin-confiz** [comment]
Not worked for me

**Comment by KonvisarovAlexandr** [comment]
> fix it with : 1、sudo gem uninstall cocoapods 2、brew cleanup -d -v 3、brew install cocoapods 4、brew link cocoapods 5、Done it's work for me

Worked for me , but with 

3.brew reinstall cocoapods
4.brew unlink cocoapods && brew link cocoapods

**Comment by Makivskyi** [comment]
> fix it with : 1、sudo gem uninstall cocoapods 2、brew cleanup -d -v 3、brew install cocoapods 4、brew link cocoapods 5、Done it's work for me

Thank you for short guide. Worked for me.
