### ISSUE TITLE
When install some_pod,error: ArgumentError - too long unix socket path (115bytes given but 104bytes max)

### ISSUE THREAD

**Issue by Juice007** [CocoaPods/CocoaPods#11640]
# Report

## What did you do?

Run `pod install`

## What did you expect to happen?

Install all pod dependencies correctly.

## What happened instead?

Error installing some_pod
ArgumentError - too long unix socket path (115bytes given but 104bytes max)

## CocoaPods Environment

   CocoaPods : 1.11.2
        Ruby : ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin21]
    RubyGems : 3.1.4
        Host : macOS 13.0 (22A380)
       Xcode : 14.1 (14B47b)
         Git : git version 2.38.1
Ruby lib dir : /Users/juice/.rvm/rubies/ruby-2.7.2/lib

**Comment by fkoner** [comment]
The same happens with this configuration:

**CocoaPods** : 1.11.3
**Ruby** : ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]
**RubyGems** : 3.3.25
**Host** : macOS 12.6.1 (21G217)
**Xcode** : 13.2.1 (13C100)
**Git** : git version 2.38.1
**Ruby lib dir** : /Users/username/.rbenv/versions/3.1.2/lib

**Comment by fkoner** [comment]
It seems the error is in the fileutils lib, in this [fileutils#1381](https://github.com/ruby/fileutils/blob/v1.6.0/lib/fileutils.rb#L1381).

```bash
/Users/username/.rbenv/versions/3.1.2/lib/ruby/3.1.0/fileutils.rb:1384:in `initialize'
/Users/username/.rbenv/versions/3.1.2/lib/ruby/3.1.0/fileutils.rb:1384:in `new'
/Users/username/.rbenv/versions/3.1.2/lib/ruby/3.1.0/fileutils.rb:1384:in `copy'
/Users/username/.rbenv/versions/3.1.2/lib/ruby/3.1.0/fileutils.rb:490:in `block in copy_entry'
/Users/username/.rbenv/versions/3.1.2/lib/ruby/3.1.0/fileutils.rb:1496:in `wrap_traverse'
/Users/username/.rbenv/versions/3.1.2/lib/ruby/3.1.0/fileutils.rb:1499:in `block in wrap_traverse'
/Users/username/.rbenv/versions/3.1.2/lib/ruby/3.1.0/fileutils.rb:1498:in `each'
/Users/username/.rbenv/versions/3.1.2/lib/ruby/3.1.0/fileutils.rb:1498:in `wrap_traverse'
/Users/username/.rbenv/versions/3.1.2/lib/ruby/3.1.0/fileutils.rb:1499:in `block in wrap_traverse'
/Users/username/.rbenv/versions/3.1.2/lib/ruby/3.1.0/fileutils.rb:1498:in `each'
/Users/username/.rbenv/versions/3.1.2/lib/ruby/3.1.0/fileutils.rb:1498:in `wrap_traverse'
/Users/username/.rbenv/versions/3.1.2/lib/ruby/3.1.0/fileutils.rb:487:in `copy_entry'
/Users/username/.rbenv/versions/3.1.2/lib/ruby/3.1.0/fileutils.rb:461:in `block in cp_r'
/Users/username/.rbenv/versions/3.1.2/lib/ruby/3.1.0/fileutils.rb:1580:in `block in fu_each_src_dest'
/Users/username/.rbenv/versions/3.1.2/lib/ruby/3.1.0/fileutils.rb:1596:in `fu_each_src_dest0'
/Users/username/.rbenv/versions/3.1.2/lib/ruby/3.1.0/fileutils.rb:1578:in `fu_each_src_dest'
/Users/username/.rbenv/versions/3.1.2/lib/ruby/3.1.0/fileutils.rb:460:in `cp_r'
/Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/downloader/cache.rb:298:in `block in copy_and_clean'
/Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/downloader/cache.rb:132:in `lock'
/Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/downloader/cache.rb:99:in `write_lock'
/Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/downloader/cache.rb:294:in `copy_and_clean'
/Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/downloader/cache.rb:247:in `block (2 levels) in uncached_pod'
/Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/downloader/cache.rb:245:in `each'
/Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/downloader/cache.rb:245:in `block in uncached_pod'
/Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/downloader/cache.rb:269:in `in_tmpdir'
/Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/downloader/cache.rb:241:in `uncached_pod'
/Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/downloader/cache.rb:33:in `download_pod'
/Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/downloader.rb:42:in `download'
/Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/external_sources/abstract_external_source.rb:116:in `block in pre_download'
/Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:86:in `titled_section'
/Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/external_sources/abstract_external_source.rb:113:in `pre_download'
/Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/external_sources/downloader_source.rb:13:in `fetch'
/Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:993:in `fetch_external_source'
/Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:972:in `block (2 levels) in fetch_external_sources'
/Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:971:in `each'
/Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:971:in `block in fetch_external_sources'
/Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
/Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:970:in `fetch_external_sources'
/Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:117:in `analyze'
/Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:416:in `analyze'
/Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:241:in `block in resolve_dependencies'
/Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
/Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:240:in `resolve_dependencies'
/Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:161:in `install!'
/Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/command/install.rb:52:in `run'
/Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:52:in `run'
/Users/username/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
/Users/username/.rbenv/versions/3.1.2/bin/pod:25:in `load'
/Users/username/.rbenv/versions/3.1.2/bin/pod:25:in `<main>'
```

**Comment by fkoner** [comment]
It seems that this path is too long:

```bash
/Users/username/Library/Caches/CocoaPods/Pods/External/POD-NAME/383e2d8dbad244b946c707aec67c52c9/.git/fsmonitor--daemon.ipc
```

**Comment by fkoner** [comment]
Related to ruby's socket implementation 
https://github.com/ruby/ruby/blob/v3_1_2/ext/socket/socket.c#L1440

**Comment by fkoner** [comment]
Hi @Juice007 
In my case, it was related to the git version (same as yours `2.38.1`) and this global configuration `core.fsmonitor` it was set to `true` [more info](https://github.blog/2022-06-27-highlights-from-git-2-37/#a-builtin-filesystem-monitor-for-windows-and-macos)

`~/.gitconfig` file

```bash
[core]
        fsmonitor = true
```

When I disabled it, it ran smoothly

You can disable like this

```bash
git config --global core.fsmonitor false
```

Or modifying the `~/.gitconfig` file

```bash
[core]
        fsmonitor = false
```

IDK if you have the same git configuration as mine.

I am wondering if there is a way `cocoapods` can deal with this.

**Comment by Juice007** [comment]
@fkoner Thanks a lot,It works!!!

**Comment by lptr** [comment]
Disabling `fsmonitor` fixed it for me, too!

**Comment by justinseanmartin** [comment]
There is still an underlying problem here in CocoaPods. I narrowed this down in my case to [this line](https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/downloader/cache.rb#L311). When I halt just before this and try to reproduce it manually from the command line, I get a more descriptive error back from `cp`:

```
/tmp/foo > cp -r src ~/Library/Caches/CocoaPods/Pods/External/repo/abcd1234abcd1234abcd1234abcd1234
cp: src/.git/fsmonitor--daemon.ipc is a socket (not copied).
```

This indicates an issue with this one specific file that `FileUtils.cp_r` is trying to copy one file. This issue was obviated for podspecs without a `prepare_command` by [this change](https://github.com/CocoaPods/CocoaPods/commit/61ecb4151436807579dda2157c1e3ae928822161) that @dnkoutso landed yesterday, but it could still happen for podspecs with `prepare_command`. I'll put up a proposal for a fix for this issue shortly.
