### ISSUE TITLE
Malformed version number string swift-5.6.2-RELEASE

### ISSUE THREAD

**Issue by yndu13** [CocoaPods/CocoaPods#11677]
# Report

## What did you do?

ℹ Please replace these two lines with what you did.  
Run `pod lib lint --verbose --allow-warnings`

## What did you expect to happen?

`    - ERROR | [iOS] unknown: Encountered an unknown error (Malformed version number string swift-5.6.2-RELEASE
/usr/local/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/version.rb:47:in `initialize'
/usr/local/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/vendor/version.rb:199:in `new'
/usr/local/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/vendor/version.rb:199:in `new'
/usr/local/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/target/build_settings.rb:1323:in `block in <class:AggregateTargetSettings>'
/usr/local/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/target/build_settings.rb:120:in `block in define_build_settings_method'
/usr/local/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/target/build_settings.rb:1253:in `block in <class:AggregateTargetSettings>'
/usr/local/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/target/build_settings.rb:120:in `block in define_build_settings_method'
/usr/local/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/target/build_settings.rb:395:in `public_send'
/usr/local/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/target/build_settings.rb:395:in `block in to_h'
/usr/local/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/target/build_settings.rb:394:in `each'
/usr/local/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/target/build_settings.rb:394:in `to_h'
/usr/local/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/target/build_settings.rb:188:in `block in <class:BuildSettings>'
/usr/local/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/target/build_settings.rb:1127:in `block in <class:AggregateTargetSettings>'
/usr/local/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/target/build_settings.rb:120:in `block in define_build_settings_method'
/usr/local/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/target/build_settings.rb:204:in `save_as'
/usr/local/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/pods_project_generator/target_installer_helper.rb:24:in `update_changed_file'
/usr/local/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:113:in `block in create_xcconfig_file'
/usr/local/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:109:in `each'
/usr/local/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:109:in `create_xcconfig_file'
/usr/local/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:22:in `block in install!'
/usr/local/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:149:in `message'
/usr/local/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:18:in `install!'
/usr/local/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/pods_project_generator.rb:131:in `block (2 levels) in install_aggregate_targets'
/usr/local/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/pods_project_generator.rb:129:in `map'
/usr/local/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/pods_project_generator.rb:129:in `block in install_aggregate_targets'
/usr/local/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:149:in `message'
/usr/local/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/pods_project_generator.rb:128:in `install_aggregate_targets'
/usr/local/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/single_pods_project_generator.rb:20:in `generate!'
/usr/local/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:314:in `block in create_and_save_projects'
/usr/local/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:309:in `create_and_save_projects'
/usr/local/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:301:in `generate_pods_project'
/usr/local/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/validator.rb:630:in `block in install_pod'
/usr/local/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/validator.rb:630:in `each'
/usr/local/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/validator.rb:630:in `install_pod'
/usr/local/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/validator.rb:401:in `block in perform_extensive_analysis'
/usr/local/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/validator.rb:393:in `each'
/usr/local/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/validator.rb:393:in `perform_extensive_analysis'
/usr/local/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/validator.rb:130:in `validate'
/usr/local/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/command/lib/lint.rb:96:in `block in run'
/usr/local/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/command/lib/lint.rb:75:in `each'
/usr/local/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/command/lib/lint.rb:75:in `run'
/usr/local/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/usr/local/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:52:in `run'
/usr/local/ruby/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
) during validation.`

## CocoaPods Environment

`### Stack

```
   CocoaPods : 1.11.3
        Ruby : ruby 2.7.6p219 (2022-04-12 revision c9c2245c0a) [x86_64-linux]
    RubyGems : 3.1.6
        Host : Unable to find an executable (No such file or directory - sw_vers)  ()
       Xcode : xcodebuild) ()
         Git : git version 2.38.1
Ruby lib dir : /usr/local/ruby/2.7.6/lib
Repositories : 
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0`

**OS: Linux**
_We need to push podspecs on Linux Server_
`pod trunk push xxx`

**Comment by grigorye** [comment]
Just in case, I'm getting this when trying to do `pod install` on Linux. Investigating. It looks like cocoapods is trying to figure out the current version of "swift" to check the requirements specified in pods, and then it does not parse it properly.

Compare `swift --version` output on macOS:
```
swift-driver version: 1.62.15 Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)
Target: arm64-apple-macosx13.0
```

and Linux:
```
Swift version 5.7.3 (swift-5.7.3-RELEASE)
Target: aarch64-unknown-linux-gnu
```

Trying to investigate it further/figure out the exact place.

```
# bundle exec pod install --allow-root
    WARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
    Consider adding the following to ~/.profile:

    export LANG=en_US.UTF-8

Analyzing dependencies
Downloading dependencies
Generating Pods project

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod install --allow-root
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.11.3
        Ruby : ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [aarch64-linux-gnu]
    RubyGems : 3.3.5
        Host : Unable to find an executable (No such file or directory - sw_vers)  ()
       Xcode : xcodebuild) ()
         Git : git version 2.34.1
Ruby lib dir : /usr/lib
Repositories : ecg-ecg-mobile-cocoapod-specs - git - https://github.es.ecg.tools/eCG-Mobile/cocoapod-specs.git @ 9aa1640a1ae6808b25e1a4209ef34a4549195237

               ecg-ecg-mobile-cocoapod-specs-binaries - git - https://github.es.ecg.tools/eCG-Mobile/cocoapod-specs-binaries.git @ 56921d6174980be7872ad407981e4af16c6d5588

               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
claide-plugins                        : 0.9.2
cocoapods-deintegrate                 : 1.0.5
cocoapods-disable-podfile-validations : 0.2.0
cocoapods-generate                    : 2.2.3
cocoapods-plugins                     : 1.0.0
cocoapods-search                      : 1.0.1
cocoapods-trunk                       : 1.6.0
cocoapods-try                         : 1.2.0
slather                               : 2.7.4
```

### Podfile

```ruby
[OMITTED]
```

### Error

```
ArgumentError - Malformed version number string swift-5.7.3-RELEASE
/var/lib/gems/3.0.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/version.rb:47:in `initialize'
/var/lib/gems/3.0.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/vendor/version.rb:199:in `new'
/var/lib/gems/3.0.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/vendor/version.rb:199:in `new'
/var/lib/gems/3.0.0/gems/cocoapods-1.11.3/lib/cocoapods/target/build_settings.rb:1323:in `block in <class:AggregateTargetSettings>'
/var/lib/gems/3.0.0/gems/cocoapods-1.11.3/lib/cocoapods/target/build_settings.rb:120:in `block in define_build_settings_method'
/var/lib/gems/3.0.0/gems/cocoapods-1.11.3/lib/cocoapods/target/build_settings.rb:1253:in `block in <class:AggregateTargetSettings>'
/var/lib/gems/3.0.0/gems/cocoapods-1.11.3/lib/cocoapods/target/build_settings.rb:120:in `block in define_build_settings_method'
/var/lib/gems/3.0.0/gems/cocoapods-1.11.3/lib/cocoapods/target/build_settings.rb:395:in `public_send'
/var/lib/gems/3.0.0/gems/cocoapods-1.11.3/lib/cocoapods/target/build_settings.rb:395:in `block in to_h'
/var/lib/gems/3.0.0/gems/cocoapods-1.11.3/lib/cocoapods/target/build_settings.rb:394:in `each'
/var/lib/gems/3.0.0/gems/cocoapods-1.11.3/lib/cocoapods/target/build_settings.rb:394:in `to_h'
/var/lib/gems/3.0.0/gems/cocoapods-1.11.3/lib/cocoapods/target/build_settings.rb:188:in `block in <class:BuildSettings>'
/var/lib/gems/3.0.0/gems/cocoapods-1.11.3/lib/cocoapods/target/build_settings.rb:1127:in `block in <class:AggregateTargetSettings>'
/var/lib/gems/3.0.0/gems/cocoapods-1.11.3/lib/cocoapods/target/build_settings.rb:120:in `block in define_build_settings_method'
/var/lib/gems/3.0.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/pods_project_generator/target_installer_helper.rb:16:in `update_changed_file'
/var/lib/gems/3.0.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:113:in `block in create_xcconfig_file'
/var/lib/gems/3.0.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:109:in `each'
/var/lib/gems/3.0.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:109:in `create_xcconfig_file'
/var/lib/gems/3.0.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:22:in `block in install!'
/var/lib/gems/3.0.0/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:149:in `message'
/var/lib/gems/3.0.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:18:in `install!'
/var/lib/gems/3.0.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/pods_project_generator.rb:131:in `block (2 levels) in install_aggregate_targets'
/var/lib/gems/3.0.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/pods_project_generator.rb:129:in `map'
/var/lib/gems/3.0.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/pods_project_generator.rb:129:in `block in install_aggregate_targets'
/var/lib/gems/3.0.0/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:149:in `message'
/var/lib/gems/3.0.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/pods_project_generator.rb:128:in `install_aggregate_targets'
/var/lib/gems/3.0.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/single_pods_project_generator.rb:20:in `generate!'
/var/lib/gems/3.0.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:314:in `block in create_and_save_projects'
/var/lib/gems/3.0.0/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
/var/lib/gems/3.0.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:309:in `create_and_save_projects'
/var/lib/gems/3.0.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:301:in `generate_pods_project'
/var/lib/gems/3.0.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:180:in `integrate'
/var/lib/gems/3.0.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:167:in `install!'
/var/lib/gems/3.0.0/gems/cocoapods-1.11.3/lib/cocoapods/command/install.rb:52:in `run'
/var/lib/gems/3.0.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/var/lib/gems/3.0.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:52:in `run'
/var/lib/gems/3.0.0/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:25:in `load'
/usr/local/bin/pod:25:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=Malformed+version+number+string+swift-5.7.3-RELEASE&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Found no similar issues. To create a new issue, please visit:
https://github.com/cocoapods/cocoapods/issues/new
#
```

**Comment by grigorye** [comment]
Update: it turns out that on Linux with *Docker* version of Swift (https://hub.docker.com/_/swift), there's `SWIFT_VERSION` predefined in the environment, that chokes CocoaPods as above. In my case, overriding the environment variable with "proper" version, makes `pod install` work as expected.

I.e. if you face the issue, it's worth checking SWIFT_VERSION in the current environment, and if it's swift-N.N.N-RELEASE, just invoke `pod xxx` as below:

```
env SWIFT_VERSION=N.N.N pod xxx
```

**Comment by grigorye** [comment]
A small follow-up, it may be worth using SWIFT_VERSION=5.0 in the above workaround to align with https://github.com/CocoaPods/CocoaPods/issues/8876.

**Comment by joshuarendora1** [comment]
Hi Good Day before we begin can i ask a little favor to Subscribe these
Youtube chanel?

Please click Link Below. 👇👇


https://youtube.com/shorts/va3bZK4wiKU?feature=share



YOU'RE SUBSCRIPTION IS REALLY A BIG HELP TO THE CHARITY WE CHOSEN TO
RECEIVED 75% OF THE SALLARY WE MAKE IN THE FUTURE.

WE ARE EXPECTING THAT YOU ARE ALSO IN LINE AND 1 OF THOSE PEOPLE ALSO WHO
SUPPORT WHAT WE MAKE AND PLAN IN THE FUTURE IN HELPING OTHERS ♥️♥️♥️

THANK YOU SO MUCH ♥️
