### ISSUE TITLE
Pod::StandardError - [Bug] Unable to find the specification for ` (from `../node_modules/expo-modules-core/ios`)`.

### ISSUE THREAD

**Issue by Gnash-Obial** [CocoaPods/CocoaPods#11691]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
Run `pod install --repo-update`

## What did you expect to happen?
Install all pod dependencies correctly.

## What happened instead?
```
Pod::StandardError - [Bug] Unable to find the specification for ` (from `../node_modules/expo-modules-core/ios`)`.
/Users/kk48/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:380:in `find_cached_set'
/Users/kk48/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:360:in `specifications_for_dependency'
/Users/kk48/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:165:in `search_for'
/Users/kk48/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:274:in `block in sort_dependencies'
/Users/kk48/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:267:in `each'
/Users/kk48/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:267:in `sort_by'
/Users/kk48/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:267:in `sort_by!'
/Users/kk48/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:267:in `sort_dependencies'
/Users/kk48/.rvm/gems/ruby-3.0.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:60:in `block in sort_dependencies'
/Users/kk48/.rvm/gems/ruby-3.0.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:77:in `with_no_such_dependency_error_handling'
/Users/kk48/.rvm/gems/ruby-3.0.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:59:in `sort_dependencies'
/Users/kk48/.rvm/gems/ruby-3.0.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:754:in `push_state_for_requirements'
/Users/kk48/.rvm/gems/ruby-3.0.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:288:in `push_initial_state'
/Users/kk48/.rvm/gems/ruby-3.0.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:210:in `start_resolution'
/Users/kk48/.rvm/gems/ruby-3.0.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:168:in `resolve'
/Users/kk48/.rvm/gems/ruby-3.0.0/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in `resolve'
/Users/kk48/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:94:in `resolve'
/Users/kk48/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:1078:in `block in resolve_dependencies'
/Users/kk48/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
/Users/kk48/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:1076:in `resolve_dependencies'
/Users/kk48/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/Users/kk48/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:416:in `analyze'
/Users/kk48/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:241:in `block in resolve_dependencies'
/Users/kk48/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
/Users/kk48/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:240:in `resolve_dependencies'
/Users/kk48/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:161:in `install!'
/Users/kk48/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.3/lib/cocoapods/command/install.rb:52:in `run'
/Users/kk48/.rvm/gems/ruby-3.0.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Users/kk48/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:52:in `run'
/Users/kk48/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

### Stack

```
   CocoaPods : 1.11.3
        Ruby : ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin21]
    RubyGems : 3.2.3
        Host : macOS 12.4 (21F79)
       Xcode : 13.4 (13F17a)
         Git : git version 2.36.1
Ruby lib dir : /Users/kk48/.rvm/rubies/ruby-3.0.0/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

platform :ios, '11.0'

target 'lightawake' do
  use_unimodules!
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :flipper_configuration => FlipperConfiguration.enabled(["Debug"], { 'Flipper' => '0.176.1.0' }),
    )
  
  pod 'RNSound', :path => '../node_modules/react-native-sound'
  pod 'UMPermissionsInterface', :path => '../node_modules/unimodules-permissions-interface/ios'
  pod 'react-native-geolocation', :path => '../node_modules/@react-native-community/geolocation'
  pod 'RNWifi', :path => '../node_modules/react-native-wifi-reborn'
  pod "TuyaSmartHomeKit"
  pod 'GoogleSignIn', '~> 6.1.0'

  pod 'react-native-background-timer', :path => '../node_modules/react-native-background-timer'

  pod 'RNIap', :path => '../node_modules/react-native-iap'

  pod 'react-native-blob-util', :path => '../node_modules/react-native-blob-util'

  target 'lightawakeTests' do
    inherit! :complete
    # Pods for testing
  end
end

target 'lightawake-tvOS' do
  # Pods for lightawake-tvOS

  target 'lightawake-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
```

**Comment by Oleg-Pasternak** [comment]
Also encountered this error

**Comment by sultandelux** [comment]
also encountered this

**Comment by erodriguezvesti** [comment]
same here

**Comment by sultandelux** [comment]
solved by upgrading expo 46, rn 0.69, and all expo modules should be around 5 months ago version on npm versions, remove ~,

while updating don't forget to merge those ios (including podfile) and android files when you create a new expo project (you take ios and android files from there)

my podfile here:

`require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")
require File.join(File.dirname(`node --print "require.resolve('@react-native-community/cli-platform-ios/package.json')"`), "native_modules")

require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

platform :ios, '12.4'
install! 'cocoapods',
  :deterministic_uuids => false

target 'IsmetKz' do
  use_expo_modules!
  config = use_native_modules!

  # use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
  use_flipper!({ 'Flipper-Folly' => '2.6.10', 'Flipper' => '0.175.0', 'Flipper-RSocket' => '1.4.3' })

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'] == 'hermes',
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    #
    # Uncomment to opt-in to using Flipper
    # Note that if you have use_frameworks! enabled, Flipper will not work
    # :flipper_configuration => !ENV['CI'] ? FlipperConfiguration.enabled : FlipperConfiguration.disabled,
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      # :mac_catalyst_enabled => false
    )
    # __apply_Xcode_12_5_M1_post_install_workaround(installer)

    # This is necessary for Xcode 14, because it signs resource bundles by default
    # when building for devices.
    fix_deployment_target(installer)

    installer.target_installation_results.pod_target_installation_results
      .each do |pod_name, target_installation_result|
      target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
        resource_bundle_target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
  end

  def fix_deployment_target(installer)
    return if !installer
    project = installer.pods_project
    project_deployment_target = project.build_configurations.first.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
  
    puts "Make sure all pods deployment target is #{project_deployment_target.green}"
    project.targets.each do |target|
      puts "  #{target.name}".blue
      target.build_configurations.each do |config|
        old_target = config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
        new_target = project_deployment_target
        next if old_target == new_target
        puts "    #{config.name}: #{old_target.yellow} -> #{new_target.green}"
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = new_target
      end
    end
  end

  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end
end
`

**Comment by restoredtemecula** [comment]
I am having this issue as well... Trying to run pod install after upgrade to SDK 47... Have no idea why this issue is occurring... Anyone have an idea?

**Comment by glukomania** [comment]
> I am having this issue as well... Trying to run pod install after upgrade to SDK 47... Have no idea why this issue is occurring... Anyone have an idea?

Have you found the solution?

**Comment by restoredtemecula** [comment]
> > I am having this issue as well... Trying to run pod install after upgrade to SDK 47... Have no idea why this issue is occurring... Anyone have an idea?
> 
> Have you found the solution?

No. Nothing, and not even sure where to begin... I am kinda stuck to be honest.

**Comment by glukomania** [comment]
> > > I am having this issue as well... Trying to run pod install after upgrade to SDK 47... Have no idea why this issue is occurring... Anyone have an idea?
> > 
> > 
> > Have you found the solution?
> 
> No. Nothing, and not even sure where to begin... I am kinda stuck to be honest.

me too, all the same. Reinstalled modules, upgraded everything possible, just nothing. I'm thinking about trying to downgrade expo

**Comment by glukomania** [comment]
> honest

I've tried to reduce verion of expo and RN, like it wass described before, and it lets me to build with expo build: ios, but the new way through eas works as well, but I've got a new problem: Error: Cannot find native module 'ExpoVideoView'. And I even can't find any mentions of this module in google =(

**Comment by restoredtemecula** [comment]
> > honest
> 
> I've tried to reduce verion of expo and RN, like it wass described before, and it lets me to build with expo build: ios, but the new way through eas works as well, but I've got a new problem: Error: Cannot find native module 'ExpoVideoView'. And I even can't find any mentions of this module in google =(

I just tried to downgrade as well, using `expo upgrade 46` (expo CLI). I then had the following issue, which I was able to correct by getting rid of App-Loading. `npm uninstall expo-app-loading`

`[!] There are multiple dependencies with different sources for `EXSplashScreen` in `Podfile`:

- EXSplashScreen (from `../node_modules/expo-splash-screen/ios`)
- EXSplashScreen (from `../node_modules/expo-app-loading/node_modules/expo-splash-screen/ios`)`

It would appear as though downgrading has resolved this error i was getting, but its more of a bandaid fix... If this doesn't get addressed, upgrading to new SDK's will not be possible and we'll lose support for projects that we might need to keep current. 

That said, you might simply try installing that module using expo cli? `expo install expo-av` might work, as I believe that module would be that...? or maybe try seeing if you can install `expo install ExpoVideoView`... That or, if you can be certain you don't need that module for you project/application, then maybe try uninstalling it? Hope this helps! 

Again, though, regardless, this doesn't necessarily help us with trying to upgrade to SDK 47, so still would like to see some support/resolution for this bug...
