### ISSUE TITLE
pod install failure

### ISSUE THREAD

**Issue by Sadow32** [CocoaPods/CocoaPods#11709]
# Report

## What did you do?

Run `pod install`

## What did you expect to happen?

Installation failure, an error occurred.

### Command

```
/usr/local/Cellar/cocoapods/1.11.3/libexec/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.11.3
        Ruby : ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.x86_64-darwin22]
    RubyGems : 3.0.3.1
        Host : macOS 13.0.1 (22A400)
       Xcode : 14.2 (14C18)
         Git : git version 2.37.1 (Apple Git-137.1)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
platform :ios, '15.0'
use_frameworks!

target 'ProjectTest' do
  pod 'WechatOpenSDK', '1.9.9'
  pod 'SnapKit'
end
```

### Error

```
LoadError - incompatible library version - /Users/wuyueyang/.rvm/gems/ruby-3.0.0/gems/ffi-1.15.5/lib/ffi_c.bundle
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/wuyueyang/.rvm/gems/ruby-3.0.0/gems/ffi-1.15.5/lib/ffi.rb:5:in `rescue in <top (required)>'
/Users/wuyueyang/.rvm/gems/ruby-3.0.0/gems/ffi-1.15.5/lib/ffi.rb:2:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Cellar/cocoapods/1.11.3/libexec/gems/ethon-0.16.0/lib/ethon.rb:3:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Cellar/cocoapods/1.11.3/libexec/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:440:in `download_typhoeus_impl_async'
/usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:372:in `download_and_save_with_retries_async'
/usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:365:in `download_file_async'
/usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:338:in `download_file'
/usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:284:in `ensure_versions_file_loaded'
/usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:208:in `search'
/usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-core-1.11.3/lib/cocoapods-core/source/aggregate.rb:83:in `block in search'
/usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-core-1.11.3/lib/cocoapods-core/source/aggregate.rb:83:in `select'
/usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-core-1.11.3/lib/cocoapods-core/source/aggregate.rb:83:in `search'
/usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:416:in `create_set_from_sources'
/usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:385:in `find_cached_set'
/usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:360:in `specifications_for_dependency'
/usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:165:in `search_for'
/usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:274:in `block in sort_dependencies'
/usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:267:in `each'
/usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:267:in `sort_by'
/usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:267:in `sort_by!'
/usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:267:in `sort_dependencies'
/usr/local/Cellar/cocoapods/1.11.3/libexec/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:60:in `block in sort_dependencies'
/usr/local/Cellar/cocoapods/1.11.3/libexec/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:77:in `with_no_such_dependency_error_handling'
/usr/local/Cellar/cocoapods/1.11.3/libexec/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:59:in `sort_dependencies'
/usr/local/Cellar/cocoapods/1.11.3/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:754:in `push_state_for_requirements'
/usr/local/Cellar/cocoapods/1.11.3/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:288:in `push_initial_state'
/usr/local/Cellar/cocoapods/1.11.3/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:210:in `start_resolution'
/usr/local/Cellar/cocoapods/1.11.3/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:168:in `resolve'
/usr/local/Cellar/cocoapods/1.11.3/libexec/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in `resolve'
/usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:94:in `resolve'
/usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:1078:in `block in resolve_dependencies'
/usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:1076:in `resolve_dependencies'
/usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:416:in `analyze'
/usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:241:in `block in resolve_dependencies'
/usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:240:in `resolve_dependencies'
/usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:161:in `install!'
/usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/command/install.rb:52:in `run'
/Users/wuyueyang/.rvm/gems/ruby-3.0.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:52:in `run'
/usr/local/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
/usr/local/Cellar/cocoapods/1.11.3/libexec/bin/pod:23:in `load'
/usr/local/Cellar/cocoapods/1.11.3/libexec/bin/pod:23:in `<main>'
```

**Comment by ThiagoFerreira12** [comment]
Same problem here

**Comment by thomnico** [comment]
I got the same issue in this file gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/target/build_settings.rb:446:in `block (2 levels) in merged_xcconfigs' installing with gem 
ruby 3.2.0 
replacing "=~" by "==" seems to work but no idea if it has side effects I am just using this thing

**Comment by ThiagoFerreira12** [comment]
It works for me, but what side effects will appear?!

**Comment by jhonsabowsla** [comment]
that seems to have solved it for me, but how did you find out ?

**Comment by thomnico** [comment]
Not saying it is a fix, someone who knows at least ruby should have a look. It is a workaround that seems stable so far...

**Comment by kusu108** [comment]
> I got the same issue in this file gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/target/build_settings.rb:446:in `block (2 levels) in merged_xcconfigs' installing with gem ruby 3.2.0 replacing "=~" by "==" seems to work but no idea if it has side effects I am just using this thing

Where do i find this file????

**Comment by nielsenko** [comment]
Same problem. I don't know much about pod or ruby, but I don't think the workaround is correct. Why is a Pod::Version even being compared with 
```ruby
def merged_xcconfigs(xcconfig_values_by_consumer_by_key, attribute, overriding: {}) 
           xcconfig_values_by_consumer_by_key.each_with_object(overriding.dup) do |(key, values_by_consumer), xcconfig| 
           uniq_values = values_by_consumer.values.uniq
           values_are_bools = uniq_values.all? { |v| v =~ /\A(yes|no)\z/i } # <-- here 
           if values_are_bools
```
`/opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/gems/cocoapods-1.11.3/lib/cocoapods/target/build_settings.rb:443-447`

**Comment by devon** [comment]
Find the `cocoapods` gem location with the command:

```shell
gem which cocoapods
```

And then locate the `build_settings.rb` in the folder.

The error line is:

```dart
values_are_bools = uniq_values.all? { |v| v.to_s =~ /\A(yes|no)\z/i }
```

It assumes uniq_values is an array of strings, but in the new config, it may be an array of arrays:

```ruby
// Normal uniq_values
["YES"]
["NO"]

// Causes problems uniq_values
[[["PICKER_MEDIA=1"], ["PICKER_AUDIO=1"], ["PICKER_DOCUMENT=1"]]]
```

The `=~` operator matches the regular expression against a string. 

```ruby
# Detect v is "yes" or "no"
values_are_bools = uniq_values.all? { |v| v =~ /\A(yes|no)\z/i }
```

Without future investigation, the solution may be one of these:

```ruby
# Flatten the array (so, there is always an array of strings)
values_are_bools = uniq_values.flatten.all? { |v| v =~ /\A(yes|no)\z/i }

# Convert the v from an Array to string
values_are_bools = uniq_values.all? { |v| v.to_s =~ /\A(yes|no)\z/i }
```

**Comment by tejassharma96** [comment]
Also having this issue, though it seems to only happen on ruby 3.2.0 for me - I tried 3.1.2 and 3.1.3 and they both worked fine. Same error:
```
cocoapods-1.11.3/lib/cocoapods/target/build_settings.rb:446:in `block (2 levels) in merged_xcconfigs'
```

**Comment by kopianan** [comment]
> Find the `cocoapods` gem location with the command:
> 
> ```shell
> gem which cocoapods
> ```
> 
> And then locate the `build_settings.rb` in the folder.
> 
> The error line is:
> 
> ```dart
> values_are_bools = uniq_values.all? { |v| v =~ /\A(yes|no)\z/i }
> ```
> 
> It assumes uniq_values is an array of strings, but in the new config, it may be an array of arrays:
> 
> ```ruby
> # Normal uniq_values
> ["YES"]
> ["NO"]
> 
> # Causes problems uniq_values
> [[["PICKER_MEDIA=1"], ["PICKER_AUDIO=1"], ["PICKER_DOCUMENT=1"]]]
> ```
> 
> The `=~` operator matches the regular expression against a string.
> 
> ```ruby
> # Detect v is "yes" or "no"
> values_are_bools = uniq_values.all? { |v| v =~ /\A(yes|no)\z/i }
> ```
> 
> Without future investigation, the solution may be one of these:
> 
> ```ruby
> # Flatten the array (so, there is always an array of strings)
> values_are_bools = uniq_values.flatten.all? { |v| v =~ /\A(yes|no)\z/i }
> 
> # Convert the v from an Array to string
> values_are_bools = uniq_values.all? { |v| v.to_s =~ /\A(yes|no)\z/i }
> ```

for me the last line work

**Comment by tejassharma96** [comment]
what's sad is that this is already fixed in master with this PR: https://github.com/CocoaPods/CocoaPods/pull/11723  
there just hasn't been a release since march of last year. created an issue for it (https://github.com/CocoaPods/CocoaPods/pull/11723) but no reply there :'(
