### ISSUE TITLE
Install stalled for Lottie 4.0.1

### ISSUE THREAD

**Issue by khoogheem** [CocoaPods/CocoaPods#11711]
trying to update to 4.0.1 and it never installs/downloads

this Is on a M1.. have not tested with intel

stuck at:
```
-> Installing lottie-ios 4.0.1 (was 3.5.0)
 > Git download
 > Git download
     $ /usr/bin/git clone https://github.com/airbnb/lottie-ios.git
     /var/folders/ck/j34wj3q54js1p0vlgvr2rkch0000gn/T/d20230105-85079-vo7hjm --template= --single-branch --depth 1 --branch
     4.0.1
     Cloning into '/var/folders/ck/j34wj3q54js1p0vlgvr2rkch0000gn/T/d20230105-85079-vo7hjm'...
```

There is no more output after this...

if I control-c to kill it then I get:
```
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/executable.rb:180:in `value': Interrupt
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/executable.rb:180:in `block in popen3'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open3.rb:219:in `popen_run'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open3.rb:101:in `popen3'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/executable.rb:175:in `popen3'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/executable.rb:67:in `execute_command'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/downloader.rb:142:in `execute_command'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-downloader-1.6.3/lib/cocoapods-downloader/base.rb:175:in `block in executable'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-downloader-1.6.3/lib/cocoapods-downloader/git.rb:107:in `block in clone'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/downloader.rb:175:in `block in ui_sub_action'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/downloader.rb:174:in `ui_sub_action'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-downloader-1.6.3/lib/cocoapods-downloader/git.rb:105:in `clone'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-downloader-1.6.3/lib/cocoapods-downloader/git.rb:73:in `download!'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-downloader-1.6.3/lib/cocoapods-downloader/base.rb:83:in `block in download'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/downloader.rb:159:in `block in ui_action'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/downloader.rb:158:in `ui_action'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-downloader-1.6.3/lib/cocoapods-downloader/base.rb:81:in `download'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/downloader.rb:110:in `download_source'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/downloader.rb:77:in `download_request'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/downloader/cache.rb:256:in `download'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/downloader/cache.rb:239:in `block in uncached_pod'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/downloader/cache.rb:266:in `in_tmpdir'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/downloader/cache.rb:238:in `uncached_pod'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/downloader/cache.rb:33:in `download_pod'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/downloader.rb:42:in `download'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/pod_source_installer.rb:118:in `download_source'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/pod_source_installer.rb:69:in `install!'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:563:in `install_source_of_pod'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:514:in `block (2 levels) in install_pod_sources'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:86:in `titled_section'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:513:in `block in install_pod_sources'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:496:in `each'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:496:in `install_pod_sources'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:255:in `block in download_dependencies'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:254:in `download_dependencies'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:162:in `install!'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/command/update.rb:63:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:52:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
	from /usr/local/bin/pod:23:in `load'
	from /usr/local/bin/pod:23:in `<main>'
```

**Comment by orta** [comment]
I'd recommend running with `--verbose` to see the git progress, it's likely just a massive repo.

**Comment by khoogheem** [comment]
that was a --verbose.. 
it never gets to where you see it actually downloading

**Comment by paulb777** [comment]
Try the failing git command from the command line.

**Comment by khoogheem** [comment]
if I just `git clone https://github.com/airbnb/lottie-ios.git /var/folders/ck/j34wj3q54js1p0vlgvr2rkch0000gn/T/d20230105-85079-vo7hjm --template= --single-branch --depth 1 --branch 4.0.1` in terminal it works fine:

```
Cloning into '/var/folders/ck/j34wj3q54js1p0vlgvr2rkch0000gn/T/d20230105-85079-vo7hjm'...
remote: Enumerating objects: 1361, done.
remote: Counting objects: 100% (1361/1361), done.
remote: Compressing objects: 100% (1121/1121), done.
remote: Total 1361 (delta 268), reused 1096 (delta 213), pack-reused 0
Receiving objects: 100% (1361/1361), 66.12 MiB | 266.00 KiB/s, done.
Resolving deltas: 100% (268/268), done.
Note: switching to 'a4622b4d6fdbe76cc5487bc27e84029abaf07217'.
```

after running it manually the pods seem to also update.. so who knows..

**Comment by paulb777** [comment]
Perhaps a temporary network glitch ...
