### ISSUE TITLE
Unable to deintegrate cocopods from iOS

### ISSUE THREAD

**Issue by sandeepkhade1989** [CocoaPods/CocoaPods#11727]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

e.g. Run ` pod deintegrate`

## What did you expect to happen?

e.g. deintegrate all pod dependencies correctly.

### Error

```
NoMethodError - undefined method `build_files' for nil:NilClass
/Library/Ruby/Gems/2.6.0/gems/cocoapods-deintegrate-1.0.5/lib/cocoapods/deintegrator.rb:57:in `block (2 levels) in deintegrate_pods_libraries'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-deintegrate-1.0.5/lib/cocoapods/deintegrator.rb:55:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-deintegrate-1.0.5/lib/cocoapods/deintegrator.rb:55:in `block in deintegrate_pods_libraries'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-deintegrate-1.0.5/lib/cocoapods/deintegrator.rb:54:in `deintegrate_pods_libraries'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-deintegrate-1.0.5/lib/cocoapods/deintegrator.rb:29:in `block in deintegrate_target'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-deintegrate-1.0.5/lib/cocoapods/deintegrator.rb:24:in `deintegrate_target'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-deintegrate-1.0.5/lib/cocoapods/deintegrator.rb:11:in `block (2 levels) in deintegrate_project'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-deintegrate-1.0.5/lib/cocoapods/deintegrator.rb:10:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-deintegrate-1.0.5/lib/cocoapods/deintegrator.rb:10:in `block in deintegrate_project'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-deintegrate-1.0.5/lib/cocoapods/deintegrator.rb:9:in `deintegrate_project'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-deintegrate-1.0.5/lib/cocoapods/command/deintegrate.rb:48:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.
## CocoaPods Environment

e.g. via `pod version-1.11.2`

**Comment by sandeepkhade1989** [comment]
This issue was caused because of Gemfile contain in the project repo and Ruby/Gems/2.6.0  after removing these files I am able to uninstall the cocoa pods.
