### ISSUE TITLE
NoMethodError - undefined method `downcase' for nil:NilClass

### ISSUE THREAD

**Issue by chtnsngh** [CocoaPods/CocoaPods#11733]
### Error

```
NoMethodError - undefined method `downcase' for nil:NilClass
/Users/ec2-user/.rvm/gems/ruby-2.6.3/gems/cocoapods-core-1.10.0.rc.1/lib/cocoapods-core/specification.rb:330:in `subspec_by_name'
/Users/ec2-user/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.10.0.rc.1/lib/cocoapods/resolver/lazy_specification.rb:29:in `subspec_by_name'
/Users/ec2-user/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.10.0.rc.1/lib/cocoapods/resolver.rb:362:in `block in specifications_for_dependency'
/Users/ec2-user/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.10.0.rc.1/lib/cocoapods/resolver.rb:362:in `map'
/Users/ec2-user/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.10.0.rc.1/lib/cocoapods/resolver.rb:362:in `specifications_for_dependency'
/Users/ec2-user/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.10.0.rc.1/lib/cocoapods/resolver.rb:165:in `search_for'
/Users/ec2-user/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.10.0.rc.1/lib/cocoapods/resolver.rb:274:in `block in sort_dependencies'
/Users/ec2-user/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.10.0.rc.1/lib/cocoapods/resolver.rb:267:in `each'
/Users/ec2-user/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.10.0.rc.1/lib/cocoapods/resolver.rb:267:in `sort_by'
/Users/ec2-user/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.10.0.rc.1/lib/cocoapods/resolver.rb:267:in `sort_dependencies'
/Users/ec2-user/.rvm/gems/ruby-2.6.3/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:53:in `block in sort_dependencies'
/Users/ec2-user/.rvm/gems/ruby-2.6.3/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:70:in `with_no_such_dependency_error_handling'
/Users/ec2-user/.rvm/gems/ruby-2.6.3/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:52:in `sort_dependencies'
/Users/ec2-user/.rvm/gems/ruby-2.6.3/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:754:in `push_state_for_requirements'
/Users/ec2-user/.rvm/gems/ruby-2.6.3/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:746:in `require_nested_dependencies_for'
/Users/ec2-user/.rvm/gems/ruby-2.6.3/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:729:in `activate_new_spec'
/Users/ec2-user/.rvm/gems/ruby-2.6.3/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:686:in `attempt_to_activate'
/Users/ec2-user/.rvm/gems/ruby-2.6.3/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:254:in `process_topmost_state'
/Users/ec2-user/.rvm/gems/ruby-2.6.3/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
/Users/ec2-user/.rvm/gems/ruby-2.6.3/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
/Users/ec2-user/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.10.0.rc.1/lib/cocoapods/resolver.rb:94:in `resolve'
/Users/ec2-user/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.10.0.rc.1/lib/cocoapods/installer/analyzer.rb:1074:in `block in resolve_dependencies'
/Users/ec2-user/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.10.0.rc.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/ec2-user/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.10.0.rc.1/lib/cocoapods/installer/analyzer.rb:1072:in `resolve_dependencies'
/Users/ec2-user/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.10.0.rc.1/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/Users/ec2-user/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.10.0.rc.1/lib/cocoapods/installer.rb:414:in `analyze'
/Users/ec2-user/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.10.0.rc.1/lib/cocoapods/installer.rb:239:in `block in resolve_dependencies'
/Users/ec2-user/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.10.0.rc.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/ec2-user/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.10.0.rc.1/lib/cocoapods/installer.rb:238:in `resolve_dependencies'
/Users/ec2-user/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.10.0.rc.1/lib/cocoapods/installer.rb:160:in `install!'
/Users/ec2-user/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.10.0.rc.1/lib/cocoapods/command/install.rb:52:in `run'
/Users/ec2-user/.rvm/gems/ruby-2.6.3/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/ec2-user/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.10.0.rc.1/lib/cocoapods/command.rb:52:in `run'
/Users/ec2-user/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.10.0.rc.1/bin/pod:55:in `<top (required)>'
/Users/ec2-user/.rvm/gems/ruby-2.6.3/bin/pod:25:in `load'
/Users/ec2-user/.rvm/gems/ruby-2.6.3/bin/pod:25:in `<main>'
/Users/ec2-user/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:22:in `eval'
/Users/ec2-user/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:22:in `<main>'
```

**Comment by turkcankeskin** [comment]
Can you please respond? We can't understand what the issue is, the error message is meaningless :(

**Comment by WeiCongcong** [comment]
Same issue. How did you resolve it? @chtnsngh

**Comment by chtnsngh** [comment]
@WeiCongcong This issue comes when cocoapods is not able to resolve all the dependencies. By all I mean transitive dependencies too. 
You can either provide a correct Podfile.lock along with Podfile to resolve all dependencies or directly mention the all the pod versions in Podfile.

**Comment by WeiCongcong** [comment]
Thanks for reply. @chtnsngh  In my case, I can locate the root dependency which leads to this issue, but still can't resolve it. It's hard to detect which transitive dependency introduced the issue.

**Comment by respan** [comment]
Do you use AFNetworking? They updated something and now pod outdated / or pod lib lint not working

**Comment by Yagimutsu** [comment]
In our case with @turkcankeskin we use AFNetworking. So if we use a specific version of AFNetworking do you think we might solve this issue ?

**Comment by respan** [comment]
@Yagimutsu yes, specify AFNetworking version (e.g. '~> 3.2.1') in Podfile in your project and/or every pod spec your project depends on and it should fix it. 

In our case, we had to specify in our project, and we have several private pods, so it took some time..

**Comment by Yagimutsu** [comment]
After we specified the version, our issue has been resolved.

Thanks for your help @respan 🚀
