### ISSUE TITLE
Errno::ENOENT - No such file or directory @ rb_sysopen - AlgoliaSearch.yml

### ISSUE THREAD

**Issue by nscribble** [CocoaPods/CocoaPods#11732]
# Report

## What did you do?

Run `pod search SnapKit` or search anything.

This happens in my Intel MacBookPro which just setup environments recently.

I've reinstall CocoaPods, but nothing changed.

## What did you expect to happen?

Search from all the repos(with some private pod spec repos) to find out all pod-repo matching that name(SnapKit).

## What happened instead?

Error!
### Error

```
**Errno::ENOENT - No such file or directory @ rb_sysopen - /Users/jason/.cocoapods/repos/aRepo/AlgoliaSearch.yml**
/Users/jason/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:325:in `initialize'
/Users/jason/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:325:in `open'
/Users/jason/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:325:in `local_file'
/Users/jason/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:301:in `algolia_search_index'
/Users/jason/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:235:in `search_by_name'
/Users/jason/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/source/manager.rb:135:in `block in search_by_name'
/Users/jason/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/source/manager.rb:135:in `map'
/Users/jason/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/source/manager.rb:135:in `search_by_name'
/Users/jason/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/cocoapods-search-1.0.1/lib/cocoapods-search/command/search.rb:87:in `local_search'
/Users/jason/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/cocoapods-search-1.0.1/lib/cocoapods-search/command/search.rb:63:in `run'
/Users/jason/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Users/jason/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:52:in `run'
/Users/jason/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
/Users/jason/.rbenv/versions/3.1.3/bin/pod:25:in `load'
/Users/jason/.rbenv/versions/3.1.3/bin/pod:25:in `<main>'

## CocoaPods Environment

Environment: 
```
   CocoaPods : 1.11.3
        Ruby : ruby 3.1.3p185 (2022-11-24 revision 1a6b16756e) [x86_64-darwin21]
    RubyGems : 3.3.26
        Host : macOS 13.1 (22C65), MacBook Pro (Intel)
       Xcode : 14.2 (14C18)
         Git : git version 2.37.1 (Apple Git-137.1)
Ruby lib dir : /Users/jason/.rbenv/versions/3.1.3/lib

Executable Path: /Users/jason/.rbenv/versions/3.1.3/bin/pod
```
And ruby gems is managed with rbenv.

Podfile:
```ruby
source 'http://aSpecs.git'
source 'http://bSpecs.git'
source 'http://cSpecs.git'

# use_frameworks!

platform :ios, '10.0'

target 'LSCModule_Example' do

  pod 'LSCModule', :path => '../'
  pod 'Masonry'

end
```

## Project that demonstrates the issue

it seems is only an issue with CocoaPods the tool. 

AlgoliaSearch.yml is not found in the /Users/jason/.cocoapods/repos/aRepo/ directory, or any other public/private pod spec repo.

ls in  /Users/jason/.cocoapods/repos/aRepo/:
```
drwxr-xr-x  11 jason  staff    352  1 18 15:37 .
drwxr-xr-x@ 21 jason  staff    672  1 18 15:37 ..
-rw-r--r--@  1 jason  staff   6148  1 18 15:48 .DS_Store
-rw-r--r--   1 jason  staff     81  1 12 09:48 .url
-rw-r--r--   1 jason  staff     50  1 19 15:08 CocoaPods-version.yml
-rw-r--r--   1 jason  staff     64  1 19 15:08 CocoaPods-version.yml.etag
drwxr-xr-x   4 jason  staff    128  1 18 15:37 Specs
-rw-r--r--   1 jason  staff  13036  1 19 15:08 all_pods_versions_.txt
-rw-r--r--   1 jason  staff     64  1 19 15:08 all_pods_versions_.txt.etag
-rw-r--r--   1 jason  staff      0  1 19 15:08 deprecated_podspecs.txt
-rw-r--r--   1 jason  staff     64  1 19 15:08 deprecated_podspecs.txt.etag
```

**Comment by nscribble** [comment]
It could be a bug since it is not a cdn repo source.

But it could workaround with a `--simple` option, like this:
```
pod search --simple SnapKit
```

**Comment by nscribble** [comment]
Let us talk about it, maybe something more could be done here.

`pod search` makes the `local_search` here, and we have several private repo source here. 

Maybe some private repo do have a `.url` file in the repo, for which CocoaPods take these repo as `CDNSource`. 

And these `CDNSource` was made non-indexable. So the searching goes to the algoliasearch. Algolia-searching will download the `AlgoliaSearch.yml` file from the mirroring CDN.

That is why `pod search` failed in my case since one of the private source repo DO have a `.url` file but DO NOT have a `AlgoliaSearch.yml` in the remote CDN website.

**For these circumstance, maybe CocoaPods could take these repo as a normal source repo, and do the local search instead.**
 
```
def algolia_search_index
      @index ||= begin
        require 'algoliasearch'

        raise Informative, "Cannot perform full-text search in repo #{name} because it's missing Algolia config" if download_file('AlgoliaSearch.yml').nil?
        algolia_config = YAMLHelper.load_string(local_file('AlgoliaSearch.yml', &:read))

        client = Algolia::Client.new(:application_id => algolia_config['application_id'], :api_key => algolia_config['api_key'])
        Algolia::Index.new(algolia_config['index'], client)
      end
    end
```

**Comment by nscribble** [comment]
But it could workaround with a --simple option, like this:
```
pod search --simple SnapKit
```

or maybe cocoapods should take option `--simple` as default, and provide `--algolia` option support.
