### ISSUE TITLE
Stuck at "generating deterministic UUIDs", causing kernel panic

### ISSUE THREAD

**Issue by radex** [CocoaPods/CocoaPods#11753]
Hi, I don't have a reproducible project, and I know that React Native-related CocoaPods issues aren't covered here. I understand this, and I don't expect maintainers to do anything other than close this issue…

… still, I think someone else might find it helpful if they also encounter this issue, so I decided to post it anyway ;)

## What happened

in this project: https://github.com/Nozbe/WatermelonDB/commit/d9be088f1a44632c9433ed68fbc24d63cce0823e , running cocoapods would get stuck here for minutes:

```
Integrating target `hermes-engine`
    Adding Build Phase '[CP] Copy XCFrameworks' to project.
  - Generating deterministic UUIDs
```

This worked for me just yesterday, could not be replicated by a coworker, but I could reliably hit this.

If I `^C`, this is the traceback:

<details>

```
	28: from /Users/radex/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project.rb:413:in `predictabilize_uuids'
	27: from /Users/radex/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project/uuid_generator.rb:12:in `generate!'
	26: from /Users/radex/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project/uuid_generator.rb:64:in `generate_all_paths_by_objects'
	25: from /Users/radex/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project/uuid_generator.rb:64:in `each'
	24: from /Users/radex/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project/uuid_generator.rb:64:in `block in generate_all_paths_by_objects'
	23: from /Users/radex/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project/uuid_generator.rb:72:in `generate_paths'
	22: from /Users/radex/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project/uuid_generator.rb:72:in `each'
	21: from /Users/radex/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project/uuid_generator.rb:74:in `block in generate_paths'
	20: from /Users/radex/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project/uuid_generator.rb:77:in `generate_paths'
	19: from /Users/radex/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project/uuid_generator.rb:77:in `each'
	18: from /Users/radex/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project/uuid_generator.rb:78:in `block in generate_paths'
	17: from /Users/radex/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project/uuid_generator.rb:78:in `each'
	16: from /Users/radex/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project/uuid_generator.rb:79:in `block (2 levels) in generate_paths'
	15: from /Users/radex/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project/uuid_generator.rb:77:in `generate_paths'
	14: from /Users/radex/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project/uuid_generator.rb:77:in `each'
	13: from /Users/radex/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project/uuid_generator.rb:78:in `block in generate_paths'
	12: from /Users/radex/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project/uuid_generator.rb:78:in `each'
	11: from /Users/radex/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project/uuid_generator.rb:79:in `block (2 levels) in generate_paths'
	10: from /Users/radex/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project/uuid_generator.rb:77:in `generate_paths'
	 9: from /Users/radex/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project/uuid_generator.rb:77:in `each'
	 8: from /Users/radex/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project/uuid_generator.rb:78:in `block in generate_paths'
	 7: from /Users/radex/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project/uuid_generator.rb:78:in `each'
	 6: from /Users/radex/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project/uuid_generator.rb:79:in `block (2 levels) in generate_paths'
	 5: from /Users/radex/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project/uuid_generator.rb:77:in `generate_paths'
	 4: from /Users/radex/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project/uuid_generator.rb:77:in `each'
	 3: from /Users/radex/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project/uuid_generator.rb:78:in `block in generate_paths'
	 2: from /Users/radex/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project/uuid_generator.rb:78:in `each'
	 1: from /Users/radex/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project/uuid_generator.rb:79:in `block (2 levels) in generate_paths'
/Users/radex/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project/uuid_generator.rb:79:in `+': Interrupt
```

</details>

If I don't then after a few minutes, then "Your system has ran out of application memory" appears (interestingly, it doesn't appear that there actually isn't any memory left at all), and if you don't react within seconds by ^C'ing `pod install`, then **kernel hangs so hard that the computer gets rebooted by watchdog after 60s of inactivity.**

This appears similar to #10506 #6290 #10623

## My setup

- macOS 13.2
- M1 Pro, 32GB RAM
- Ruby 2.7.2p137 (also reproduced on 2.7.7)
- CocoaPods 1.11.2
- Node 16.13.2, 16-latest
- main pod dependency: React Native 0.71.1

## What I tried doing

- Check pod install at previous commits (earlier RN versions)
- Delete `Pods`, `build` (RN puts some Pod stuff there), `node_modules` (ditto, some Pods are vendored via NPM in RN)
- Kill all conceivable forms of cache, including gems, cocoapods, npm caches, `~/Library/Caches`
- upgrade Ruby and Node
- … downgrade Ruby and Node to a known-good version
- … cleanly reinstall Ruby and Node
- enable/disable Hermes pod (it would get stuck at UUID generation somewhere else)
- No, I'm not using flipper - this is different from https://github.com/facebook/flipper/issues/2248#issuecomment-830060572
- `COCOAPODS_DISABLE_DETERMINISTIC_UUIDS=YES`
- kill all of my homebrew packages
- pull all my hair out, scream at the computer
- reboot, install macOS update

After 5 wasted hours, I noticed that a clean git cloned repo `pod install`s correctly. I don't think it's as simple as me having a dirty repo, given multiple attempts at deleting and re-installing all known sources of CocoaPods-related state. Maybe something somewhere in the system npm/ruby/cocoapods was corrupted and only after that a clean re-install could succeed… I don't know. Or maybe I'm an idiot and should've tried clean `git clone` first, but I ran diff between the two repos (one broken, one fixed), and then again after one more attempt at reinstalling all dependencies on the old repo + deleting some files that are different (but should not impact cocoapods). In case that's helpful to anyone here's the first diff: https://gist.github.com/radex/b2932e805ca55f3371b2df424be688ca and here's the second diff (once the old repo started working again): https://gist.github.com/radex/d697d1d02be35d1efa0f61b6b4f4f2ab

## Is this CocoaPods or React Native issue?

I don't really know and don't really care. It seems likely that the unusual CP setup used by RN did something to trigger the issue.

Still, it shouldn't be possible to get `uuid_generator.rb` stuck so hard it consumes all kernel resources and causes system to crash.

**Comment by orta** [comment]
If I had to guess, from the looking at the stack and these descriptions, I'd say somehow that xcodeproj has an infinite loop in it's in-memory representations of _some pod_. 

If this hits you again, I'd manually edit `/Users/radex/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project/uuid_generator.rb:78` to start logging out what it is looping through to try find some commonality

**Comment by radex** [comment]
It happened again so this time I did what I should've done at the start and tried to actually debug the issue on CP side, which would've saved me many hours if I did this the first time ;)

I traced down the issue:

- I have a `docs-website` folder at the repo root, which is a sibling to `WatermelonDB.podspec`
- `docs-website` is its own sub-project, so if initialized, it will have a `node_modules`
- I have a Podfile which references the podspec `pod 'WatermelonDB', path: '../../'`
- as a development pod, `PodsProjectGenerator` will try to add `FileAccessor#developer_files`, which includes all `'doc{s}{*,.*}/**/*'`
- I don't think there's an infinite loop, I think `UUIDGenerator` is genuinely attempting to go over 31619 files until it exhausts all system resources 🤦 

AFAICT, there's no public API to disable adding of `developer_files` or changing the `docs` glob. I could monkey patch this, or rename `docs-website/` or move the `Podfile`.

Still, I don't think that adding to xcodeproj docs in dev pods was meant to be anything more than a simple convenience - for sure shouldn't attempt to add tens of thousands of files there.

@orta I propose that `FileAccessor#docs` should limit its glob results to, say, 100 files, and show a warning if it's exceeded to avoid accidentally bloating xcodeproj with junk. WDYT?

**Comment by orta** [comment]
This all makes sense to me (without knowing everything what's going on in the internals), and I think that makes sense as a thing to warn - 100 might be very low though, unless that's per pod in which case that's pretty reasonable

That said, again, I don't know the internals but it does make me wonder if there's some computer science that can be applied here also - 30k files isn't _that much_  on the scale of things (and the amount of RAM computers have) for CP to be tracking for whether they clash

**Comment by radex** [comment]
> That said, again, I don't know the internals but it does make me wonder if there's some computer science that can be applied here also - 30k files isn't that much on the scale of things (and the amount of RAM computers have) for CP to be tracking for whether they clash

True, but the problem is also that it's trying to actually add references to these 30k files to the .xcodeproj, which seems like a very bad idea, even if processing them in CP was more efficient
