### ISSUE TITLE
Unable to install pod BluesnapSDK

### ISSUE THREAD

**Issue by andrii-lisovskiy** [CocoaPods/CocoaPods#11752]
### Command

```
/Users/xxxxxxxxxx/.rvm/gems/ruby-2.7.2/bin/pod install
```

### Report

* What did you do?
pod install/pod update

* What did you expect to happen?
cocoa pods successfully installed

* What happened instead?
an error occurred

### Stack

```
   CocoaPods : 1.11.3
        Ruby : ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin22]
    RubyGems : 3.1.4
        Host : macOS 13.1 (22C65)
       Xcode : 14.1 (14B47b)
         Git : git version 2.37.1 (Apple Git-137.1)
Ruby lib dir : /Users/xxxxxxxxxx/.rvm/rubies/ruby-2.7.2/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ 57df884d3ecf988679d76703b1fb34a03cd82aec

               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

# ignore all warnings from all pods
inhibit_all_warnings!

target 'XXXXX' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Moya'
  pod 'FloatingPanel'
  pod 'SVProgressHUD'
  pod 'SwiftMessages'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  pod 'SwiftLint'
  pod 'SwiftGen', '~> 6.0'
  pod 'KeychainSwift'
  pod 'PhoneNumberKit', '~> 3.1'
  pod 'Kingfisher', '~> 5.0'
  pod 'Chatto', '= 4.0.0'
  pod 'ChattoAdditions', '= 4.0.0' # if you want to use the cells or the input component
  pod "StompClientLib"
  pod 'RealmSwift'
  pod 'SwipeCellKit'
  pod 'Lokalise', '~> 0.10.0'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'BluesnapSDK'
  pod 'CocoaLumberjack/Swift'
  pod 'Firebase/RemoteConfig'
  # Pods for XXXX

  target 'XXXXTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'XXXXUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'

      config.build_settings.delete 'ARCHS'

      # temporary fix for this issue to suppress a ton of warnings
      # https://github.com/CocoaPods/CocoaPods/issues/7314
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end

#  installer.generated_projects.each do |project|
#      project.targets.each do |target|
#        target.build_configurations.each do |config|
#          config.build_settings["DEVELOPMENT_TEAM"] = "XXXXXX"
#        end
#      end
#    end
end
```

### Error

```
Errno::ENOENT - No such file or directory @ rb_file_s_lstat - /private/var/folders/24/wd9s0zgs05n7zyds_g32d35c0000gn/T/d20230203-14875-1q5sprl/BluesnapSDK/BSApiManager.swift
/Users/xxxxxxxxxx/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/fileutils.rb:1332:in `lstat'
/Users/xxxxxxxxxx/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/fileutils.rb:1332:in `lstat'
/Users/xxxxxxxxxx/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/fileutils.rb:1376:in `copy'
/Users/xxxxxxxxxx/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/fileutils.rb:497:in `block in copy_entry'
/Users/xxxxxxxxxx/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/fileutils.rb:1513:in `wrap_traverse'
/Users/xxxxxxxxxx/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/fileutils.rb:1516:in `block in wrap_traverse'
/Users/xxxxxxxxxx/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/fileutils.rb:1515:in `each'
/Users/xxxxxxxxxx/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/fileutils.rb:1515:in `wrap_traverse'
/Users/xxxxxxxxxx/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/fileutils.rb:1516:in `block in wrap_traverse'
/Users/xxxxxxxxxx/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/fileutils.rb:1515:in `each'
/Users/xxxxxxxxxx/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/fileutils.rb:1515:in `wrap_traverse'
/Users/xxxxxxxxxx/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/fileutils.rb:494:in `copy_entry'
/Users/xxxxxxxxxx/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/fileutils.rb:468:in `block in cp_r'
/Users/xxxxxxxxxx/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/fileutils.rb:1589:in `block in fu_each_src_dest'
/Users/xxxxxxxxxx/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/fileutils.rb:1605:in `fu_each_src_dest0'
/Users/xxxxxxxxxx/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/fileutils.rb:1587:in `fu_each_src_dest'
/Users/xxxxxxxxxx/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/fileutils.rb:467:in `cp_r'
/Users/xxxxxxxxxx/.rvm/gems/ruby-2.7.2/gems/cocoapods-1.11.3/lib/cocoapods/downloader/cache.rb:287:in `block in copy_and_clean'
/Users/xxxxxxxxxx/.rvm/gems/ruby-2.7.2/gems/cocoapods-1.11.3/lib/cocoapods/downloader/cache.rb:128:in `lock'
/Users/xxxxxxxxxx/.rvm/gems/ruby-2.7.2/gems/cocoapods-1.11.3/lib/cocoapods/downloader/cache.rb:99:in `write_lock'
/Users/xxxxxxxxxx/.rvm/gems/ruby-2.7.2/gems/cocoapods-1.11.3/lib/cocoapods/downloader/cache.rb:285:in `copy_and_clean'
/Users/xxxxxxxxxx/.rvm/gems/ruby-2.7.2/gems/cocoapods-1.11.3/lib/cocoapods/downloader/cache.rb:244:in `block (2 levels) in uncached_pod'
/Users/xxxxxxxxxx/.rvm/gems/ruby-2.7.2/gems/cocoapods-1.11.3/lib/cocoapods/downloader/cache.rb:242:in `each'
/Users/xxxxxxxxxx/.rvm/gems/ruby-2.7.2/gems/cocoapods-1.11.3/lib/cocoapods/downloader/cache.rb:242:in `block in uncached_pod'
/Users/xxxxxxxxxx/.rvm/gems/ruby-2.7.2/gems/cocoapods-1.11.3/lib/cocoapods/downloader/cache.rb:266:in `in_tmpdir'
/Users/xxxxxxxxxx/.rvm/gems/ruby-2.7.2/gems/cocoapods-1.11.3/lib/cocoapods/downloader/cache.rb:238:in `uncached_pod'
/Users/xxxxxxxxxx/.rvm/gems/ruby-2.7.2/gems/cocoapods-1.11.3/lib/cocoapods/downloader/cache.rb:33:in `download_pod'
/Users/xxxxxxxxxx/.rvm/gems/ruby-2.7.2/gems/cocoapods-1.11.3/lib/cocoapods/downloader.rb:42:in `download'
/Users/xxxxxxxxxx/.rvm/gems/ruby-2.7.2/gems/cocoapods-1.11.3/lib/cocoapods/installer/pod_source_installer.rb:118:in `download_source'
/Users/xxxxxxxxxx/.rvm/gems/ruby-2.7.2/gems/cocoapods-1.11.3/lib/cocoapods/installer/pod_source_installer.rb:69:in `install!'
/Users/xxxxxxxxxx/.rvm/gems/ruby-2.7.2/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:563:in `install_source_of_pod'
/Users/xxxxxxxxxx/.rvm/gems/ruby-2.7.2/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:514:in `block (2 levels) in install_pod_sources'
/Users/xxxxxxxxxx/.rvm/gems/ruby-2.7.2/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:86:in `titled_section'
/Users/xxxxxxxxxx/.rvm/gems/ruby-2.7.2/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:513:in `block in install_pod_sources'
/Users/xxxxxxxxxx/.rvm/gems/ruby-2.7.2/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:496:in `each'
/Users/xxxxxxxxxx/.rvm/gems/ruby-2.7.2/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:496:in `install_pod_sources'
/Users/xxxxxxxxxx/.rvm/gems/ruby-2.7.2/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:255:in `block in download_dependencies'
/Users/xxxxxxxxxx/.rvm/gems/ruby-2.7.2/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
/Users/xxxxxxxxxx/.rvm/gems/ruby-2.7.2/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:254:in `download_dependencies'
/Users/xxxxxxxxxx/.rvm/gems/ruby-2.7.2/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:162:in `install!'
/Users/xxxxxxxxxx/.rvm/gems/ruby-2.7.2/gems/cocoapods-1.11.3/lib/cocoapods/command/install.rb:52:in `run'
/Users/xxxxxxxxxx/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Users/xxxxxxxxxx/.rvm/gems/ruby-2.7.2/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:52:in `run'
/Users/xxxxxxxxxx/.rvm/gems/ruby-2.7.2/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
/Users/xxxxxxxxxx/.rvm/gems/ruby-2.7.2/bin/pod:23:in `load'
/Users/xxxxxxxxxx/.rvm/gems/ruby-2.7.2/bin/pod:23:in `<main>'
/Users/xxxxxxxxxx/.rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:22:in `eval'
/Users/xxxxxxxxxx/.rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:22:in `<main>'
```

**Comment by paulb777** [comment]
This is unlikely to be a CocoaPods issue. Please report to the Bluesnap SDK maintainers.
