### ISSUE TITLE
Pod install results in JSON::ParserError - 416: unexpected token at '"src/core/ext/transport/chttp2/transport/bin_decoder.'

### ISSUE THREAD

**Issue by Guuuud** [CocoaPods/CocoaPods#11771]
### Command

```
/Users/lee/.rvm/rubies/ruby-2.6.6/bin/pod install
```

### What did you do?
  Run `pod install`

### What did you expect to happen?
 Install all pod dependencies correctly.

### Error

```
JSON::ParserError - 416: unexpected token at '"src/core/ext/transport/chttp2/transport/bin_decoder.'
/Users/lee/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/Users/lee/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/Users/lee/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/specification/json.rb:61:in `from_json'
/Users/lee/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/specification.rb:748:in `from_string'
/Users/lee/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/specification.rb:722:in `from_file'
/Users/lee/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/source.rb:188:in `specification'
/Users/lee/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/specification/set.rb:58:in `block in specification_name'
/Users/lee/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/specification/set.rb:56:in `each'
/Users/lee/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/specification/set.rb:56:in `specification_name'
/Users/lee/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:216:in `search'
/Users/lee/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/source/aggregate.rb:83:in `block in search'
/Users/lee/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/source/aggregate.rb:83:in `select'
/Users/lee/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/source/aggregate.rb:83:in `search'
/Users/lee/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:416:in `create_set_from_sources'
/Users/lee/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:385:in `find_cached_set'
/Users/lee/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:360:in `specifications_for_dependency'
/Users/lee/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:165:in `search_for'
/Users/lee/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:274:in `block in sort_dependencies'
/Users/lee/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:267:in `each'
/Users/lee/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:267:in `sort_by'
/Users/lee/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:267:in `sort_by!'
/Users/lee/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:267:in `sort_dependencies'
/Users/lee/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:60:in `block in sort_dependencies'
/Users/lee/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:77:in `with_no_such_dependency_error_handling'
/Users/lee/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:59:in `sort_dependencies'
/Users/lee/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:754:in `push_state_for_requirements'
/Users/lee/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:744:in `require_nested_dependencies_for'
/Users/lee/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:727:in `activate_new_spec'
/Users/lee/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:684:in `attempt_to_activate'
/Users/lee/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:254:in `process_topmost_state'
/Users/lee/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:182:in `resolve'
/Users/lee/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in `resolve'
/Users/lee/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:94:in `resolve'
/Users/lee/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:1078:in `block in resolve_dependencies'
/Users/lee/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
/Users/lee/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:1076:in `resolve_dependencies'
/Users/lee/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/Users/lee/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:416:in `analyze'
/Users/lee/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:241:in `block in resolve_dependencies'
/Users/lee/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
/Users/lee/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:240:in `resolve_dependencies'
/Users/lee/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:161:in `install!'
/Users/lee/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/command/install.rb:52:in `run'
/Users/lee/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Users/lee/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:52:in `run'
/Users/lee/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
/Users/lee/.rvm/rubies/ruby-2.6.6/bin/pod:23:in `load'
/Users/lee/.rvm/rubies/ruby-2.6.6/bin/pod:23:in `<main>'
/Users/lee/.rvm/rubies/ruby-2.6.6/bin/ruby_executable_hooks:22:in `eval'
/Users/lee/.rvm/rubies/ruby-2.6.6/bin/ruby_executable_hooks:22:in `<main>'
```

### Stack

```
   CocoaPods : 1.11.3
        Ruby : ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-darwin21]
    RubyGems : 3.0.9
        Host : macOS 12.6 (21G115)
       Xcode : 14.1 (14B47b)
         Git : git version 2.37.1 (Apple Git-137.1)
Ruby lib dir : /Users/lee/.rvm/rubies/ruby-2.6.6/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '12.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {

  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!



  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
```

### Dependencies in my pubspec.yaml
```
dependencies:
  cloud_firestore: ^4.3.1
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  firebase_storage: ^11.0.10
  flutter:
    sdk: flutter
  
  flutter_staggered_grid_view: ^0.4.1
  flutter_svg: ^1.1.6
  image_picker: ^0.8.6
  provider: ^6.0.5
  uuid: ^3.0.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
```
Hey guys, I've used nearly every way that I found on the internet and all of them fails, I don't know if it is caused by the Great Fire Wall, I've used the VPN. Could somebody help with this, I'm really appreciated, I think this problem was caused by the dependency `cloud_firestore`, cause after I delete it the pod install can run( at least some green text would show), if I keep it, command `pod install` would immediately failed

**Comment by KeonwooKo** [comment]
@Guuuud 
hey, hi
did you fix the bug?
now i am in china troubling same issue
