### ISSUE TITLE
xcode 14.2 pod install error:NoMethodError - undefined method `=~' for ["-ObjC", "-w"]:Array

### ISSUE THREAD

**Issue by 1234hui** [CocoaPods/CocoaPods#11788]
――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.11.3
        Ruby : ruby 3.2.1 (2023-02-08 revision 31819e82c8) [x86_64-darwin21]
    RubyGems : 3.4.7
        Host : macOS 12.6.3 (21G419)
       Xcode : 14.2 (14C18)
         Git : git version 2.37.1 (Apple Git-137.1)
Ruby lib dir : /usr/local/Cellar/ruby/3.2.1/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
platform:ios,'9.0'
target 'Rider' do
inhibit_all_warnings!

pod 'SDWebImage'
pod 'Masonry'
pod 'Bugly'
pod 'FDFullscreenPopGesture'
pod 'LYEmptyView'
pod 'MJRefresh'
pod 'MBProgressHUD'
pod 'IQKeyboardManager'
pod 'YYModel'
pod 'YYText'
pod 'YYCache'
pod 'YYCategories'
pod 'BMKLocationKit'
pod 'BaiduMapKit'
pod 'TZImagePickerController'
pod 'SGPagingView'
pod 'KSPhotoBrowser'
pod 'AlipaySDK-iOS'
pod 'WechatOpenSDK'
pod 'AFNetworking'
pod 'JCore'
pod 'JPush'
pod 'SCIndexView'


end

post_install do |installer|       
   installer.pods_project.targets.each do |target| 
     puts target.name 
   end
end
```

### Error

```
NoMethodError - undefined method `=~' for ["-ObjC", "-w"]:Array
/usr/local/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/target/build_settings.rb:446:in `block (2 levels) in merged_xcconfigs'
/usr/local/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/target/build_settings.rb:446:in `all?'
/usr/local/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/target/build_settings.rb:446:in `block in merged_xcconfigs'
/usr/local/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/target/build_settings.rb:444:in `each'
/usr/local/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/target/build_settings.rb:444:in `each_with_object'
/usr/local/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/target/build_settings.rb:444:in `merged_xcconfigs'
/usr/local/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/target/build_settings.rb:1378:in `block in <class:AggregateTargetSettings>'
/usr/local/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/target/build_settings.rb:120:in `block in define_build_settings_method'
/usr/local/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/target/build_settings.rb:1128:in `block in <class:AggregateTargetSettings>'
/usr/local/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/target/build_settings.rb:120:in `block in define_build_settings_method'
/usr/local/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/pods_project_generator/target_installer_helper.rb:16:in `update_changed_file'
/usr/local/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:113:in `block in create_xcconfig_file'
/usr/local/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:109:in `each'
/usr/local/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:109:in `create_xcconfig_file'
/usr/local/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:22:in `block in install!'
/usr/local/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:149:in `message'
/usr/local/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:18:in `install!'
/usr/local/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/pods_project_generator.rb:131:in `block (2 levels) in install_aggregate_targets'
/usr/local/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/pods_project_generator.rb:129:in `map'
/usr/local/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/pods_project_generator.rb:129:in `block in install_aggregate_targets'
/usr/local/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:149:in `message'
/usr/local/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/pods_project_generator.rb:128:in `install_aggregate_targets'
/usr/local/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/single_pods_project_generator.rb:20:in `generate!'
/usr/local/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:314:in `block in create_and_save_projects'
/usr/local/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:309:in `create_and_save_projects'
/usr/local/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:301:in `generate_pods_project'
/usr/local/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:180:in `integrate'
/usr/local/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:167:in `install!'
/usr/local/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/command/install.rb:52:in `run'
/usr/local/lib/ruby/gems/3.2.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:25:in `load'
/usr/local/bin/pod:25:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=undefined+method+%60%3D~%27+for+%5B%22-ObjC%22%2C+%22-w%22%5D%3AArray&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
 - Duplicate symbols when framework target has a static dependency
   https://github.com/CocoaPods/CocoaPods/issues/7126 [closed] [33 comments]
   04 Nov 2021

**Comment by CrazyFanFan** [comment]
Ruby 3.2 removed `=~`: [Remove `Object#=~`](https://bugs.ruby-lang.org/issues/15231). 
You can either choose to downgrade your Ruby version to below 3.2 or upgrade to Cocoapods 1.12.0.

**Comment by guess** [comment]
Here's how you can upgrade your Cocapods to fix the issue:

```
gem uninstall cocoapods
gem install cocoapods -v 1.12.1
```

Here are the list of versions: https://rubygems.org/gems/cocoapods/versions

**Comment by FauziFerdiansyah** [comment]
> Here's how you can upgrade your Cocapods to fix the issue:
> 
> ```
> gem uninstall cocoapods
> gem install cocoapods -v 1.12.1
> ```
> 
> Here are the list of versions: https://rubygems.org/gems/cocoapods/versions

Can you show the version of ruby ?

**Comment by Vinaum8** [comment]
we use bitrise, delete the podfile.lock file, run the command "pod install cocoapods" and install the latest version of cocoapods.

After that, the podfile.lock was generated with the latest version and the ci-cd pipeline ran normally, without the error:

NoMethodError - undefined method `=~' for ["-ObjC", "-w"]:Array

Note: we do not change the ruby version

**Comment by facilitoPr** [comment]
[!] Oh no, an error occurred.
Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=undefined+method+%60%3D~%27+for+%5B%5D%3AArray&type=Issues
If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new
Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md
Don't forget to anonymize any private data!
Looking for related issues on cocoapods/cocoapods...
 - xcode 14.2 pod install error:NoMethodError - undefined method `=~' for ["-ObjC", "-w"]:Array
   https://github.com/CocoaPods/CocoaPods/issues/11788 [open] [6 comments]
   28 Jan 2024
 - Cocoapods Error when I run: pod search realm
   https://github.com/CocoaPods/CocoaPods/issues/12161 [open] [1 comment]
   09 Jan 2024
 - pod install failure
   https://github.com/CocoaPods/CocoaPods/issues/11709 [open] [11 comments]
   27 Feb 2023
and 38 more at:
https://github.com/cocoapods/cocoapods/search?q=undefined%20method%20%60%3D~%27%20for%20%5B%5D%3AArray&type=Issues&utf8=✓
[stderr] 

[!] [Codegen] warn: using experimental new codegen integration
[stderr] 

[!] `<PBXResourcesBuildPhase UUID=`13B07F8E1A680F5B00A75B9A`>` attempted to initialize an object with an unknown UUID. `1B54C83A4FF3488D8F8B8915` for attribute: `files`. This can be the result of a merge and the unknown UUID is being discarded.
pod install exited with non-zero code: 1

**Comment by facilitoPr** [comment]
Estoy usando Expo y al hacer el build me aparece esto

[!] Oh no, an error occurred.
Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=undefined+method+%60%3D~%27+for+%5B%5D%3AArray&type=Issues
If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new
Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md
Don't forget to anonymize any private data!
Looking for related issues on cocoapods/cocoapods...
 - xcode 14.2 pod install error:NoMethodError - undefined method `=~' for ["-ObjC", "-w"]:Array
   https://github.com/CocoaPods/CocoaPods/issues/11788 [open] [6 comments]
   28 Jan 2024
 - Cocoapods Error when I run: pod search realm
   https://github.com/CocoaPods/CocoaPods/issues/12161 [open] [1 comment]
   09 Jan 2024
 - pod install failure
   https://github.com/CocoaPods/CocoaPods/issues/11709 [open] [11 comments]
   27 Feb 2023
and 38 more at:
https://github.com/cocoapods/cocoapods/search?q=undefined%20method%20%60%3D~%27%20for%20%5B%5D%3AArray&type=Issues&utf8=✓
[stderr] 

[!] [Codegen] warn: using experimental new codegen integration
[stderr] 

[!] `<PBXResourcesBuildPhase UUID=`13B07F8E1A680F5B00A75B9A`>` attempted to initialize an object with an unknown UUID. `1B54C83A4FF3488D8F8B8915` for attribute: `files`. This can be the result of a merge and the unknown UUID is being discarded.
pod install exited with non-zero code: 1
