### ISSUE TITLE
ArgumentError - wrong number of arguments (given 1, expected 0) when i did pod install 

### ISSUE THREAD

**Issue by iwalben** [CocoaPods/CocoaPods#11786]
### Command

```
/Users/xxx/.rvm/gems/ruby-2.5.1/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.7.4
        Ruby : ruby 3.2.1 (2023-02-08 revision 31819e82c8) [x86_64-darwin20]
    RubyGems : 3.4.6
        Host : macOS 11.6.5 (20G527)
       Xcode : 13.2.1 (13C100)
         Git : git version 2.32.0 (Apple Git-132)
Ruby lib dir : /usr/local/Cellar/ruby/3.2.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ e685fa7287b10eb734bc2408ce6ebb6bbea4f688
```

### Plugins

```

```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project

platform :ios, '9.0'
inhibit_all_warnings!

target 'Project' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for Project
pod 'AFNetworking'

end
```

### Error

```
ArgumentError - wrong number of arguments (given 1, expected 0)
/Users/xxx/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.4/lib/cocoapods/downloader/request.rb:61:in `slug'
/Users/xxx/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.4/lib/cocoapods/downloader/cache.rb:114:in `path_for_spec'
/Users/xxx/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.4/lib/cocoapods/downloader/cache.rb:140:in `cached_spec'
/Users/xxx/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.4/lib/cocoapods/downloader/cache.rb:125:in `cached_pod'
/Users/xxx/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.4/lib/cocoapods/downloader/cache.rb:33:in `download_pod'
/Users/xxx/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.4/lib/cocoapods/downloader.rb:42:in `download'
/Users/xxx/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.4/lib/cocoapods/installer/pod_source_installer.rb:109:in `download_source'
/Users/xxx/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.4/lib/cocoapods/installer/pod_source_installer.rb:62:in `install!'
/Users/xxx/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.4/lib/cocoapods/installer.rb:545:in `install_source_of_pod'
/Users/xxx/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.4/lib/cocoapods/installer.rb:496:in `block (2 levels) in install_pod_sources'
/Users/xxx/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.4/lib/cocoapods/user_interface.rb:86:in `titled_section'
/Users/xxx/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.4/lib/cocoapods/installer.rb:495:in `block in install_pod_sources'
/Users/xxx/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.4/lib/cocoapods/installer.rb:478:in `each'
/Users/xxx/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.4/lib/cocoapods/installer.rb:478:in `install_pod_sources'
/Users/xxx/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.4/lib/cocoapods/installer.rb:235:in `block in download_dependencies'
/Users/xxx/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.4/lib/cocoapods/user_interface.rb:64:in `section'
/Users/xxx/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.4/lib/cocoapods/installer.rb:234:in `download_dependencies'
/Users/xxx/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.4/lib/cocoapods/installer.rb:157:in `install!'
/Users/xxx/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.4/lib/cocoapods/command/install.rb:51:in `run'
/Users/xxx/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/xxx/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.4/lib/cocoapods/command.rb:52:in `run'
/Users/xxx/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.4/bin/pod:55:in `<top (required)>'
/Users/xxx/.rvm/gems/ruby-2.5.1/bin/pod:25:in `load'
/Users/xxx/.rvm/gems/ruby-2.5.1/bin/pod:25:in `<main>'
```

**Comment by dnkoutso** [comment]
Very old version of CocoaPods please update as those are no longer maintained.
