### ISSUE TITLE
[!] CocoaPods could not find compatible versions for pod "stripe-react-native":   In Podfile:     stripe-react-native (from `../node_modules/@stripe/stripe-react-native`)  Specs satisfying the `stripe-react-native (from `../node_modules/@stripe/stripe-react-native`)` dependency were found, but they required a higher minimum deployment target.

### ISSUE THREAD

**Issue by 5ylvino** [CocoaPods/CocoaPods#11830]
### Command

```
/Users/mac/.gem/bin/pod install --repo-update --ansi
```

### Report

I am developing an app on react native for ios and android and was tasked with integrating stripe payment. so I follow the guide on stripe docs on the setups. Thus at the point of installing the running pod-install for the just installed library (yarn add @stripe/stripe-react-native). An error popped up that says `CocoaPods could not find compatible versions for pod "stripe-react-native":`.
So I looked up similar issues online (https://github.com/stripe/stripe-react-native/issues/1116#:~:text=I%20have%20similar%20type%20of%20issue.%20I%20follow%20these%202%20step%20to%20resolve%20my%20issue.) and try to resolve it which says :
1. update the ios version on the pod file - (mine is 12.4 then update 13 - not work and even try 14)
2. on the second issue to come run `sudo gem uninstall ffi && sudo gem install ffi -- --enable-libffi-alloc`
then expecting all to work fine, but it fails again instead with this current error.

Please help me out, I am most thankful for your help in advance,

### Stack

```
   CocoaPods : 1.12.0
        Ruby : ruby 2.7.5p203 (2021-11-24 revision f69aeb8314) [x86_64-darwin20]
    RubyGems : 3.1.6
        Host : macOS 11.6.4 (20G417)
       Xcode : 13.2.1 (13C100)
         Git : git version 2.32.0 (Apple Git-132)
Ruby lib dir : /Users/mac/.rvm/rubies/ruby-2.7.5/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-search      : 1.0.1
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13'
install! 'cocoapods', :deterministic_uuids => false

target 'MillTicket' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => true,
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => FlipperConfiguration.enabled,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'MillTicketTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
```

### Error

```
LoadError - cannot load such file -- ethon/easy/http/actionable
/Applications/MAMP/htdocs/MillTicket/vendor/bundle/ruby/2.7.0/gems/ethon-0.16.0/lib/ethon/easy/http.rb:2:in `require'
/Applications/MAMP/htdocs/MillTicket/vendor/bundle/ruby/2.7.0/gems/ethon-0.16.0/lib/ethon/easy/http.rb:2:in `<top (required)>'
/Applications/MAMP/htdocs/MillTicket/vendor/bundle/ruby/2.7.0/gems/ethon-0.16.0/lib/ethon/easy.rb:10:in `require'
/Applications/MAMP/htdocs/MillTicket/vendor/bundle/ruby/2.7.0/gems/ethon-0.16.0/lib/ethon/easy.rb:10:in `<top (required)>'
/Applications/MAMP/htdocs/MillTicket/vendor/bundle/ruby/2.7.0/gems/ethon-0.16.0/lib/ethon.rb:17:in `require'
/Applications/MAMP/htdocs/MillTicket/vendor/bundle/ruby/2.7.0/gems/ethon-0.16.0/lib/ethon.rb:17:in `<top (required)>'
/Applications/MAMP/htdocs/MillTicket/vendor/bundle/ruby/2.7.0/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `require'
/Applications/MAMP/htdocs/MillTicket/vendor/bundle/ruby/2.7.0/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
/Applications/MAMP/htdocs/MillTicket/vendor/bundle/ruby/2.7.0/gems/cocoapods-core-1.12.0/lib/cocoapods-core/cdn_source.rb:440:in `require'
/Applications/MAMP/htdocs/MillTicket/vendor/bundle/ruby/2.7.0/gems/cocoapods-core-1.12.0/lib/cocoapods-core/cdn_source.rb:440:in `download_typhoeus_impl_async'
/Applications/MAMP/htdocs/MillTicket/vendor/bundle/ruby/2.7.0/gems/cocoapods-core-1.12.0/lib/cocoapods-core/cdn_source.rb:372:in `download_and_save_with_retries_async'
/Applications/MAMP/htdocs/MillTicket/vendor/bundle/ruby/2.7.0/gems/cocoapods-core-1.12.0/lib/cocoapods-core/cdn_source.rb:365:in `download_file_async'
/Applications/MAMP/htdocs/MillTicket/vendor/bundle/ruby/2.7.0/gems/cocoapods-core-1.12.0/lib/cocoapods-core/cdn_source.rb:338:in `download_file'
/Applications/MAMP/htdocs/MillTicket/vendor/bundle/ruby/2.7.0/gems/cocoapods-core-1.12.0/lib/cocoapods-core/cdn_source.rb:78:in `deprecated_local_podspecs'
/Applications/MAMP/htdocs/MillTicket/vendor/bundle/ruby/2.7.0/gems/cocoapods-core-1.12.0/lib/cocoapods-core/cdn_source.rb:60:in `preheat_existing_files'
/Applications/MAMP/htdocs/MillTicket/vendor/bundle/ruby/2.7.0/gems/cocoapods-core-1.12.0/lib/cocoapods-core/cdn_source.rb:257:in `update'
/Applications/MAMP/htdocs/MillTicket/vendor/bundle/ruby/2.7.0/gems/cocoapods-1.12.0/lib/cocoapods/sources_manager.rb:144:in `block (3 levels) in update'
/Applications/MAMP/htdocs/MillTicket/vendor/bundle/ruby/2.7.0/gems/cocoapods-1.12.0/lib/cocoapods/user_interface.rb:64:in `section'
/Applications/MAMP/htdocs/MillTicket/vendor/bundle/ruby/2.7.0/gems/cocoapods-1.12.0/lib/cocoapods/sources_manager.rb:143:in `block (2 levels) in update'
/Applications/MAMP/htdocs/MillTicket/vendor/bundle/ruby/2.7.0/gems/cocoapods-1.12.0/lib/cocoapods/sources_manager.rb:142:in `each'
/Applications/MAMP/htdocs/MillTicket/vendor/bundle/ruby/2.7.0/gems/cocoapods-1.12.0/lib/cocoapods/sources_manager.rb:142:in `block in update'
/Applications/MAMP/htdocs/MillTicket/vendor/bundle/ruby/2.7.0/gems/cocoapods-1.12.0/lib/cocoapods/sources_manager.rb:140:in `open'
/Applications/MAMP/htdocs/MillTicket/vendor/bundle/ruby/2.7.0/gems/cocoapods-1.12.0/lib/cocoapods/sources_manager.rb:140:in `update'
/Applications/MAMP/htdocs/MillTicket/vendor/bundle/ruby/2.7.0/gems/cocoapods-1.12.0/lib/cocoapods/installer/analyzer.rb:146:in `block in update_repositories'
/Applications/MAMP/htdocs/MillTicket/vendor/bundle/ruby/2.7.0/gems/cocoapods-1.12.0/lib/cocoapods/installer/analyzer.rb:144:in `each'
/Applications/MAMP/htdocs/MillTicket/vendor/bundle/ruby/2.7.0/gems/cocoapods-1.12.0/lib/cocoapods/installer/analyzer.rb:144:in `update_repositories'
/Applications/MAMP/htdocs/MillTicket/vendor/bundle/ruby/2.7.0/gems/cocoapods-1.12.0/lib/cocoapods/installer.rb:240:in `block in resolve_dependencies'
/Applications/MAMP/htdocs/MillTicket/vendor/bundle/ruby/2.7.0/gems/cocoapods-1.12.0/lib/cocoapods/user_interface.rb:64:in `section'
/Applications/MAMP/htdocs/MillTicket/vendor/bundle/ruby/2.7.0/gems/cocoapods-1.12.0/lib/cocoapods/installer.rb:239:in `resolve_dependencies'
/Applications/MAMP/htdocs/MillTicket/vendor/bundle/ruby/2.7.0/gems/cocoapods-1.12.0/lib/cocoapods/installer.rb:162:in `install!'
/Applications/MAMP/htdocs/MillTicket/vendor/bundle/ruby/2.7.0/gems/cocoapods-1.12.0/lib/cocoapods/command/install.rb:52:in `run'
/Applications/MAMP/htdocs/MillTicket/vendor/bundle/ruby/2.7.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Applications/MAMP/htdocs/MillTicket/vendor/bundle/ruby/2.7.0/gems/cocoapods-1.12.0/lib/cocoapods/command.rb:52:in `run'
/Applications/MAMP/htdocs/MillTicket/vendor/bundle/ruby/2.7.0/gems/cocoapods-1.12.0/bin/pod:55:in `<top (required)>'
/Users/mac/.gem/bin/pod:23:in `load'
/Users/mac/.gem/bin/pod:23:in `<main>'
/Users/mac/.gem/bin/ruby_executable_hooks:22:in `eval'
/Users/mac/.gem/bin/ruby_executable_hooks:22:in `<main>'
```

**Comment by 5ylvino** [comment]
resolve by reverting to the old pods and update again
