### ISSUE TITLE
flutter project run pod install, some file broken in trunk, pod install fail

### ISSUE THREAD

**Issue by flyuqian** [CocoaPods/CocoaPods#11870]
➜  ios git:(master) ✗ pod install
Analyzing dependencies
cloud_firestore: Using Firebase SDK version '10.7.0' defined in 'firebase_core'
firebase_analytics: Using Firebase SDK version '10.7.0' defined in 'firebase_core'
firebase_auth: Using Firebase SDK version '10.7.0' defined in 'firebase_core'
firebase_core: Using Firebase SDK version '10.7.0' defined in 'firebase_core'
firebase_database: Using Firebase SDK version '10.7.0' defined in 'firebase_core'
firebase_dynamic_links: Using Firebase SDK version '10.7.0' defined in 'firebase_core'
firebase_messaging: Using Firebase SDK version '10.7.0' defined in 'firebase_core'
firebase_remote_config: Using Firebase SDK version '10.7.0' defined in 'firebase_core'
firebase_storage: Using Firebase SDK version '10.7.0' defined in 'firebase_core'

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/flyu/.rvm/gems/ruby-3.0.0/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.12.1
        Ruby : ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [arm64-darwin21]
    RubyGems : 3.3.10
        Host : macOS 13.0.1 (22A400)
       Xcode : 14.1 (14B47b)
         Git : git version 2.37.1 (Apple Git-137.1)
Ruby lib dir : /Users/flyu/.rvm/rubies/ruby-3.0.0/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ 36e72352229e2979bc89f1ead4230ee87a8bbc91

               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
platform :ios, '11.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
```

### Error

```
JSON::ParserError - Failed to parse JSON at file: '/Users/flyu/.cocoapods/repos/trunk/Specs/c/8/7/gRPC-C++/1.53.0/gRPC-C++.podspec.json'.

439: unexpected token at '"src/core/ext/transport/binder/transport/binder_'
/Users/flyu/.rvm/gems/ruby-3.0.0/gems/cocoapods-core-1.12.1/lib/cocoapods-core/specification/json.rb:66:in `rescue in from_json'
/Users/flyu/.rvm/gems/ruby-3.0.0/gems/cocoapods-core-1.12.1/lib/cocoapods-core/specification/json.rb:61:in `from_json'
/Users/flyu/.rvm/gems/ruby-3.0.0/gems/cocoapods-core-1.12.1/lib/cocoapods-core/specification.rb:752:in `from_string'
/Users/flyu/.rvm/gems/ruby-3.0.0/gems/cocoapods-core-1.12.1/lib/cocoapods-core/specification.rb:726:in `from_file'
/Users/flyu/.rvm/gems/ruby-3.0.0/gems/cocoapods-core-1.12.1/lib/cocoapods-core/source.rb:188:in `specification'
/Users/flyu/.rvm/gems/ruby-3.0.0/gems/cocoapods-core-1.12.1/lib/cocoapods-core/specification/set.rb:58:in `block in specification_name'
/Users/flyu/.rvm/gems/ruby-3.0.0/gems/cocoapods-core-1.12.1/lib/cocoapods-core/specification/set.rb:56:in `each'
/Users/flyu/.rvm/gems/ruby-3.0.0/gems/cocoapods-core-1.12.1/lib/cocoapods-core/specification/set.rb:56:in `specification_name'
/Users/flyu/.rvm/gems/ruby-3.0.0/gems/cocoapods-core-1.12.1/lib/cocoapods-core/cdn_source.rb:216:in `search'
/Users/flyu/.rvm/gems/ruby-3.0.0/gems/cocoapods-core-1.12.1/lib/cocoapods-core/source/aggregate.rb:83:in `block in search'
/Users/flyu/.rvm/gems/ruby-3.0.0/gems/cocoapods-core-1.12.1/lib/cocoapods-core/source/aggregate.rb:83:in `select'
/Users/flyu/.rvm/gems/ruby-3.0.0/gems/cocoapods-core-1.12.1/lib/cocoapods-core/source/aggregate.rb:83:in `search'
/Users/flyu/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.12.1/lib/cocoapods/resolver.rb:416:in `create_set_from_sources'
/Users/flyu/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.12.1/lib/cocoapods/resolver.rb:385:in `find_cached_set'
/Users/flyu/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.12.1/lib/cocoapods/resolver.rb:360:in `specifications_for_dependency'
/Users/flyu/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.12.1/lib/cocoapods/resolver.rb:165:in `search_for'
/Users/flyu/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.12.1/lib/cocoapods/resolver.rb:274:in `block in sort_dependencies'
/Users/flyu/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.12.1/lib/cocoapods/resolver.rb:267:in `each'
/Users/flyu/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.12.1/lib/cocoapods/resolver.rb:267:in `sort_by'
/Users/flyu/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.12.1/lib/cocoapods/resolver.rb:267:in `sort_by!'
/Users/flyu/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.12.1/lib/cocoapods/resolver.rb:267:in `sort_dependencies'
/Users/flyu/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:60:in `block in sort_dependencies'
/Users/flyu/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:77:in `with_no_such_dependency_error_handling'
/Users/flyu/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:59:in `sort_dependencies'
/Users/flyu/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:754:in `push_state_for_requirements'
/Users/flyu/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:744:in `require_nested_dependencies_for'
/Users/flyu/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:727:in `activate_new_spec'
/Users/flyu/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:684:in `attempt_to_activate'
/Users/flyu/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:254:in `process_topmost_state'
/Users/flyu/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:182:in `resolve'
/Users/flyu/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in `resolve'
/Users/flyu/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.12.1/lib/cocoapods/resolver.rb:94:in `resolve'
/Users/flyu/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.12.1/lib/cocoapods/installer/analyzer.rb:1082:in `block in resolve_dependencies'
/Users/flyu/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.12.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/flyu/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.12.1/lib/cocoapods/installer/analyzer.rb:1080:in `resolve_dependencies'
/Users/flyu/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.12.1/lib/cocoapods/installer/analyzer.rb:125:in `analyze'
/Users/flyu/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:422:in `analyze'
/Users/flyu/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:244:in `block in resolve_dependencies'
/Users/flyu/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.12.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/flyu/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:243:in `resolve_dependencies'
/Users/flyu/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:162:in `install!'
/Users/flyu/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.12.1/lib/cocoapods/command/install.rb:52:in `run'
/Users/flyu/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Users/flyu/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.12.1/lib/cocoapods/command.rb:52:in `run'
/Users/flyu/.rvm/gems/ruby-3.0.0/gems/cocoapods-1.12.1/bin/pod:55:in `<top (required)>'
/Users/flyu/.rvm/gems/ruby-3.0.0/bin/pod:25:in `load'
/Users/flyu/.rvm/gems/ruby-3.0.0/bin/pod:25:in `<main>'
/Users/flyu/.rvm/gems/ruby-3.0.0/bin/ruby_executable_hooks:22:in `eval'
/Users/flyu/.rvm/gems/ruby-3.0.0/bin/ruby_executable_hooks:22:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=Failed+to+parse+JSON+at+file%3A+%27%2FUsers%2Fflyu%2F.cocoapods%2Frepos%2Ftrunk%2FSpecs%2Fc%2F8%2F7%2FgRPC-C%2B%2B%2F1.53.0%2FgRPC-C%2B%2B.podspec.json%27.%0A%0A439%3A+unexpected+token+at+%27%22src%2Fcore%2Fext%2Ftransport%2Fbinder%2Ftransport%2Fbinder_%27&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
 - `xcode-select: Error: unknown command option '-p'.` in v0.36.3
   https://github.com/CocoaPods/CocoaPods/issues/3387 [closed] [6 comments]
   14 Apr 2015

 - Add spec version numbers to acknowledgements plist
   https://github.com/CocoaPods/CocoaPods/issues/3391 [closed] [2 comments]
   13 Apr 2015

 - Error validating podspec when resource bundle is used
   https://github.com/CocoaPods/CocoaPods/issues/3380 [closed] [9 comments]
   03 Jul 2015

and 11690 more at:
https://github.com/cocoapods/cocoapods/search?q=Failed%20to%20parse%20JSON%20at%20file%3A%20%27%2FUsers%2Fflyu%2F.cocoapods%2Frepos%2Ftrunk%2FSpecs%2Fc%2F8%2F7%2FgRPC-C%2B%2B%2F1.53.0%2FgRPC-C%2B%2B.podspec.json%27.%0A%0A439%3A%20unexpected%20token%20at%20%27%22src%2Fcore%2Fext%2Ftransport%2Fbinder%2Ftransport%2Fbinder_%27&type=Issues&utf8=✓

**Comment by tomtaila** [comment]
Im suddenly getting this too - Any update?

**Comment by tomtaila** [comment]
Run
`rm -rf ~/.cocoapods/repos/trunk/`

Then go to /project/ios/

Run:
`rm -rf pods`
Then
`rm podfile.lock`
then
and run `pod install --repo-update`

**Comment by wafa3067** [comment]
> Run `rm -rf ~/.cocoapods/repos/trunk/`
> 
> Then go to /project/ios/
> 
> Run: `rm -rf pods` Then `rm podfile.lock` then and run `pod install --repo-update`

Yes! This Work Correcctly Thank You Man

**Comment by mnadeems** [comment]
> Run `rm -rf ~/.cocoapods/repos/trunk/`
> 
> Then go to /project/ios/
> 
> Run: `rm -rf pods` Then `rm podfile.lock` then and run `pod install --repo-update`

This did not work for me for similar error , still trying to search solution , I am using M2 macbook pro with latest os and apps tried almost everything but stuck on 


### Error

```
JSON::ParserError - Failed to parse JSON at file: '/Users/******/.cocoapods/repos/trunk/Specs/3/8/6/abseil/1.20230802.0/abseil.podspec.json'.

and 

- `xcode-select: Error: unknown command option '-p'.` in v0.36.3

Please help if any solution ?

**Comment by osman0simsek** [comment]
> pod install --repo-update
did you solve the problem? I'm having the same problem?

**Comment by mnadeems** [comment]
> > pod install --repo-update
> > did you solve the problem? I'm having the same problem?

No it did not , I tried multiple commands including this one also but nothing worked till now ,

Always get error like:

JSON::ParserError - Failed to parse JSON at file: '/Users/******/.cocoapods/repos/trunk/Specs/3/8/6/abseil/1.20230802.0/abseil.podspec.json'.

and 

- `xcode-select: Error: unknown command option '-p'.` in v0.36.3

Please help if any solution ?

**Comment by mnadeems** [comment]
I edited the file `'/Users/******/.cocoapods/repos/trunk/Specs/3/8/6/abseil/1.20230802.0/abseil.podspec.json'`  it was empty so I added the code taking from another folder like from 1.20****** under abseil folder (dont know what was the code ) 

and the pod installation resumed , surely this is not the right solution but for now process resumed and it started pod install without error  for now

dont know if there will be any issue in app however.

**Comment by tomtaila** [comment]
@mnadeems 

Check xcode-select Version:
It's a bit strange for the -p option to not be recognized. Run xcode-select --version to check the version. You should see something like xcode-select version 2354 or similar.

Print the Active Developer Directory:
Run the command without any other option: xcode-select -p. If this gives the same error, there might be an issue with your Xcode or Command Line Tools installation.

Install/Reinstall Command Line Tools:
If you suspect the Command Line Tools might be the issue:

Install: If you've never installed them, you can do so with xcode-select --install.

Reinstall: If they're already installed and you suspect they might be corrupted or outdated:

Remove the existing Command Line Tools with sudo rm -rf /Library/Developer/CommandLineTools.
Install them again with xcode-select --install.
Set the Correct Path:
If you have multiple Xcode installations or have moved it, ensure xcode-select is pointing to the right path:

sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

Update Xcode:
Ensure your Xcode is updated to the latest stable version. Outdated versions might have bugs or compatibility issues.

Check the Source of the Error:
The error message mentions v0.36.3. This looks like a version number, possibly from a tool or script you're using. Check if this tool or script has known issues with Xcode or xcode-select and see if there's an update available for it.

If after trying the above steps the issue persists then I dunno bro
