### ISSUE TITLE
Syntax error on `pod repo update`

### ISSUE THREAD

**Issue by gisborne** [CocoaPods/CocoaPods#11909]
### Command

```
/Users/gisborne/.rbenv/versions/3.1.3/bin/pod repo update
```

### Report

* What did you do?
`pod repo update`

* What did you expect to happen?
Execute without error 

* What happened instead?
Syntax error

### Stack

```
   CocoaPods : 1.12.1
        Ruby : ruby 3.1.3p185 (2022-11-24 revision 1a6b16756e) [arm64-darwin22]
    RubyGems : 3.3.26
        Host : macOS 13.2.1 (22D68)
       Xcode : 14.3 (14E222b)
         Git : git version 2.33.0
Ruby lib dir : /Users/gisborne/.rbenv/versions/3.1.3/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '11.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  # share_handler addition start
  target 'ShareExtension' do
    inherit! :search_paths
    pod "share_handler_ios_models", :path => ".symlinks/plugins/share_handler_ios/ios/Models"
  end
  # share_handler addition end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
```

### Error

```
SyntaxError - /Users/gisborne/.gem/gems/mime-types-3.3/lib/mime/types/logger.rb:30: _1 is reserved for numbered parameter
/Users/gisborne/.gem/gems/mime-types-3.3/lib/mime/types/logger.rb:30: _2 is reserved for numbered parameter
/Users/gisborne/.gem/gems/mime-types-3.3/lib/mime/types/logger.rb:30: _3 is reserved for numbered parameter
<internal:/Users/gisborne/.rbenv/versions/3.1.3/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/Users/gisborne/.rbenv/versions/3.1.3/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/Users/gisborne/.gem/gems/mime-types-3.3/lib/mime/types.rb:229:in `<top (required)>'
<internal:/Users/gisborne/.rbenv/versions/3.1.3/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/Users/gisborne/.rbenv/versions/3.1.3/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/Users/gisborne/.gem/gems/mime-types-3.3/lib/mime/types/columnar.rb:3:in `<top (required)>'
<internal:/Users/gisborne/.rbenv/versions/3.1.3/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `require'
<internal:/Users/gisborne/.rbenv/versions/3.1.3/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'
<internal:/Users/gisborne/.rbenv/versions/3.1.3/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:149:in `require'
/Users/gisborne/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/ethon-0.16.0/lib/ethon.rb:6:in `<top (required)>'
<internal:/Users/gisborne/.rbenv/versions/3.1.3/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/Users/gisborne/.rbenv/versions/3.1.3/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/Users/gisborne/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
<internal:/Users/gisborne/.rbenv/versions/3.1.3/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/Users/gisborne/.rbenv/versions/3.1.3/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/Users/gisborne/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/cocoapods-core-1.12.1/lib/cocoapods-core/cdn_source.rb:440:in `download_typhoeus_impl_async'
/Users/gisborne/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/cocoapods-core-1.12.1/lib/cocoapods-core/cdn_source.rb:372:in `download_and_save_with_retries_async'
/Users/gisborne/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/cocoapods-core-1.12.1/lib/cocoapods-core/cdn_source.rb:365:in `download_file_async'
/Users/gisborne/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/cocoapods-core-1.12.1/lib/cocoapods-core/cdn_source.rb:338:in `download_file'
/Users/gisborne/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/cocoapods-core-1.12.1/lib/cocoapods-core/cdn_source.rb:78:in `deprecated_local_podspecs'
/Users/gisborne/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/cocoapods-core-1.12.1/lib/cocoapods-core/cdn_source.rb:60:in `preheat_existing_files'
/Users/gisborne/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/cocoapods-core-1.12.1/lib/cocoapods-core/cdn_source.rb:257:in `update'
/Users/gisborne/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/cocoapods-1.12.1/lib/cocoapods/sources_manager.rb:144:in `block (3 levels) in update'
/Users/gisborne/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/cocoapods-1.12.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/gisborne/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/cocoapods-1.12.1/lib/cocoapods/sources_manager.rb:143:in `block (2 levels) in update'
/Users/gisborne/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/cocoapods-1.12.1/lib/cocoapods/sources_manager.rb:142:in `each'
/Users/gisborne/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/cocoapods-1.12.1/lib/cocoapods/sources_manager.rb:142:in `block in update'
/Users/gisborne/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/cocoapods-1.12.1/lib/cocoapods/sources_manager.rb:140:in `open'
/Users/gisborne/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/cocoapods-1.12.1/lib/cocoapods/sources_manager.rb:140:in `update'
/Users/gisborne/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/cocoapods-1.12.1/lib/cocoapods/command/repo/update.rb:23:in `run'
/Users/gisborne/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Users/gisborne/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/cocoapods-1.12.1/lib/cocoapods/command.rb:52:in `run'
/Users/gisborne/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/cocoapods-1.12.1/bin/pod:55:in `<top (required)>'
/Users/gisborne/.rbenv/versions/3.1.3/bin/pod:25:in `load'
/Users/gisborne/.rbenv/versions/3.1.3/bin/pod:25:in `<main>'
```

**Comment by gisborne** [comment]
1.11.3 works fine; no syntax error

**Comment by gisborne** [comment]
Happened after deleting PodFile.lock
