### ISSUE TITLE
Error Symbol not found: _rb_cFalseClass

### ISSUE THREAD

**Issue by Zey-Uzh** [CocoaPods/CocoaPods#11925]
### Command

```
/usr/local/Cellar/cocoapods/1.12.1/libexec/bin/pod repo update
```

### Report

* What did you do?
I print command "pod repo update"

* What did you expect to happen?
Updated repo.

* What happened instead?
I got an error.

### Stack

```
   CocoaPods : 1.12.1
        Ruby : ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-darwin22]
    RubyGems : 3.4.10
        Host : macOS 13.3.1 (22E261)
       Xcode : 14.3 (14E222b)
         Git : git version 2.40.0
Ruby lib dir : /usr/local/Cellar/ruby/3.2.2/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
platform :ios, '12.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
         end
    end
end
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
```

### Error

```
LoadError - dlopen(/opt/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/ffi-1.15.5/lib/ffi_c.bundle, 0x0009): Symbol not found: _rb_cFalseClass
  Referenced from: <383D802E-71E5-3BE1-9759-A7D8ED1DCF40> /opt/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/ffi-1.15.5/lib/ffi_c.bundle
  Expected in:     <1667076C-AC34-34D3-899D-BD8E212CC56D> /usr/local/Cellar/ruby/3.2.2/bin/ruby - /opt/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/ffi-1.15.5/lib/ffi_c.bundle
<internal:/usr/local/Cellar/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/usr/local/Cellar/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/opt/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/ffi-1.15.5/lib/ffi.rb:5:in `rescue in <top (required)>'
/opt/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/ffi-1.15.5/lib/ffi.rb:2:in `<top (required)>'
<internal:/usr/local/Cellar/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/usr/local/Cellar/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/opt/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/ethon-0.16.0/lib/ethon.rb:3:in `<top (required)>'
<internal:/usr/local/Cellar/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/usr/local/Cellar/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/opt/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
<internal:/usr/local/Cellar/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/usr/local/Cellar/ruby/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/opt/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-core-1.12.1/lib/cocoapods-core/cdn_source.rb:440:in `download_typhoeus_impl_async'
/opt/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-core-1.12.1/lib/cocoapods-core/cdn_source.rb:372:in `download_and_save_with_retries_async'
/opt/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-core-1.12.1/lib/cocoapods-core/cdn_source.rb:365:in `download_file_async'
/opt/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-core-1.12.1/lib/cocoapods-core/cdn_source.rb:338:in `download_file'
/opt/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-core-1.12.1/lib/cocoapods-core/cdn_source.rb:78:in `deprecated_local_podspecs'
/opt/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-core-1.12.1/lib/cocoapods-core/cdn_source.rb:60:in `preheat_existing_files'
/opt/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-core-1.12.1/lib/cocoapods-core/cdn_source.rb:257:in `update'
/opt/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.12.1/lib/cocoapods/sources_manager.rb:144:in `block (3 levels) in update'
/opt/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.12.1/lib/cocoapods/user_interface.rb:64:in `section'
/opt/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.12.1/lib/cocoapods/sources_manager.rb:143:in `block (2 levels) in update'
/opt/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.12.1/lib/cocoapods/sources_manager.rb:142:in `each'
/opt/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.12.1/lib/cocoapods/sources_manager.rb:142:in `block in update'
/opt/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.12.1/lib/cocoapods/sources_manager.rb:140:in `open'
/opt/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.12.1/lib/cocoapods/sources_manager.rb:140:in `update'
/opt/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.12.1/lib/cocoapods/command/repo/update.rb:23:in `run'
/opt/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/opt/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.12.1/lib/cocoapods/command.rb:52:in `run'
/opt/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.12.1/bin/pod:55:in `<top (required)>'
/usr/local/Cellar/cocoapods/1.12.1/libexec/bin/pod:25:in `load'
/usr/local/Cellar/cocoapods/1.12.1/libexec/bin/pod:25:in `<main>'
```

**Comment by Zey-Uzh** [comment]
I figured out the problem. Reinstalling ruby and the ffi helped. I also had to specify a GEM_HOME and GEM_PATH.
