### ISSUE TITLE
JSON::ParserError - unexpected token at ''   [!] Oh no, an error occurred.

### ISSUE THREAD

**Issue by chengssir** [CocoaPods/CocoaPods#11928]
### Command

```
/usr/local/opt/ruby/bin/pod trunk push XCStickerBundle.podspec --allow-warnings --verbose --skip-import-validation
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.12.1
        Ruby : ruby 3.2.1 (2023-02-08 revision 31819e82c8) [x86_64-darwin22]
    RubyGems : 3.4.9
        Host : macOS 13.2.1 (22D68)
       Xcode : 14.0 (14A309)
         Git : git version 2.37.0 (Apple Git-136)
Ruby lib dir : /usr/local/Cellar/ruby/3.2.1/lib
Repositories : bytedance-cocoapods_sdk_source_repo - git - https://github.com/bytedance/cocoapods_sdk_source_repo.git @ f24bcdb3e1b4fc0c8814839fbeb77dd7053ce7f4

               gitee-lw_ios_project-mylibrepo - git - https://gitee.com/lw_ios_project/mylibrepo.git @ 33ffe392309d1dcf2d07cc8acab977539a1f255f

               Specs - git - https://github.com/CocoaPods/Specs.git @ a40bf89437c158fe6e5c4803ab6b15314383a7a1

               trunk - CDN - https://cdn.cocoapods.org/
               volcengine-volcengine-specs - git - https://github.com/volcengine/volcengine-specs.git @ c5c65c3147f89ded56d5bd35d6d58b38694cb380

```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
cocoapods-xcframework : 0.2.4
```

### Error

```
JSON::ParserError - unexpected token at ''
/usr/local/Cellar/ruby/3.2.1/lib/ruby/3.2.0/json/common.rb:216:in `parse'
/usr/local/Cellar/ruby/3.2.1/lib/ruby/3.2.0/json/common.rb:216:in `parse'
/usr/local/lib/ruby/gems/3.2.0/gems/cocoapods-trunk-1.6.0/lib/pod/command/trunk.rb:102:in `json'
/usr/local/lib/ruby/gems/3.2.0/gems/cocoapods-trunk-1.6.0/lib/pod/command/trunk/push.rb:92:in `push_to_trunk'
/usr/local/lib/ruby/gems/3.2.0/gems/cocoapods-trunk-1.6.0/lib/pod/command/trunk/push.rb:73:in `run'
/usr/local/lib/ruby/gems/3.2.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/3.2.0/gems/cocoapods-1.12.1/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/3.2.0/gems/cocoapods-1.12.1/bin/pod:55:in `<top (required)>'
/usr/local/opt/ruby/bin/pod:25:in `load'
/usr/local/opt/ruby/bin/pod:25:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

**Comment by adriancarrera31** [comment]
same issue here. I can not execute any command related with pod binary, all commands show this error.
