### ISSUE TITLE
JSON::ParserError - 767: unexpected token at

### ISSUE THREAD

**Issue by maheshbijapur** [CocoaPods/CocoaPods#11927]
pod trunk register your-email@example.com 

`pod --version
1.12.1
`

`### Stack

```
   CocoaPods : 1.12.1
        Ruby : ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.arm64e-darwin22]
    RubyGems : 3.0.3.1
        Host : macOS 13.4 (22F66)
       Xcode : 14.3 (14E222b)
         Git : git version 2.39.2 (Apple Git-143)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : 
```

### Plugins

```
cocoapods-deintegrate              : 1.0.4
cocoapods-plugins                  : 1.0.0
cocoapods-search                   : 1.0.1
cocoapods-stats                    : 1.1.0
cocoapods-trunk                    : 1.6.0
cocoapods-try                      : 1.2.0
cocoapods-user-defined-build-types : 0.0.7
```

### Error

```
JSON::ParserError - 767: unexpected token at ''
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-trunk-1.6.0/lib/pod/command/trunk.rb:102:in `json'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-trunk-1.6.0/lib/pod/command/trunk/register.rb:61:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```
`

**Comment by chengssir** [comment]
### Command

```
/usr/local/opt/ruby/bin/pod trunk push XCStickerBundle.podspec --allow-warnings --verbose --skip-import-validation
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.12.1
        Ruby : ruby 3.2.1 (2023-02-08 revision 31819e82c8) [x86_64-darwin22]
    RubyGems : 3.4.9
        Host : macOS 13.2.1 (22D68)
       Xcode : 14.0 (14A309)
         Git : git version 2.37.0 (Apple Git-136)
Ruby lib dir : /usr/local/Cellar/ruby/3.2.1/lib
Repositories : bytedance-cocoapods_sdk_source_repo - git - https://github.com/bytedance/cocoapods_sdk_source_repo.git @ f24bcdb3e1b4fc0c8814839fbeb77dd7053ce7f4

               gitee-lw_ios_project-mylibrepo - git - https://gitee.com/lw_ios_project/mylibrepo.git @ 33ffe392309d1dcf2d07cc8acab977539a1f255f

               Specs - git - https://github.com/CocoaPods/Specs.git @ a40bf89437c158fe6e5c4803ab6b15314383a7a1

               trunk - CDN - https://cdn.cocoapods.org/
               volcengine-volcengine-specs - git - https://github.com/volcengine/volcengine-specs.git @ c5c65c3147f89ded56d5bd35d6d58b38694cb380

```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
cocoapods-xcframework : 0.2.4
```

### Error

```
JSON::ParserError - unexpected token at ''
/usr/local/Cellar/ruby/3.2.1/lib/ruby/3.2.0/json/common.rb:216:in `parse'
/usr/local/Cellar/ruby/3.2.1/lib/ruby/3.2.0/json/common.rb:216:in `parse'
/usr/local/lib/ruby/gems/3.2.0/gems/cocoapods-trunk-1.6.0/lib/pod/command/trunk.rb:102:in `json'
/usr/local/lib/ruby/gems/3.2.0/gems/cocoapods-trunk-1.6.0/lib/pod/command/trunk/push.rb:92:in `push_to_trunk'
/usr/local/lib/ruby/gems/3.2.0/gems/cocoapods-trunk-1.6.0/lib/pod/command/trunk/push.rb:73:in `run'
/usr/local/lib/ruby/gems/3.2.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/3.2.0/gems/cocoapods-1.12.1/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/3.2.0/gems/cocoapods-1.12.1/bin/pod:55:in `<top (required)>'
/usr/local/opt/ruby/bin/pod:25:in `load'
/usr/local/opt/ruby/bin/pod:25:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

**Comment by shywoody** [comment]
i had same issue 😫 by runing 'pod trunk push' command
be like:
### Command

```
/usr/local/bin/pod trunk push MYSDK.podspec --verbose
```

### Report

* What did you do?
trunk push mysdk
* What did you expect to happen?
show congratulations
* What happened instead?
show `[!] Oh no, an error occurred.`

### Stack

```
   CocoaPods : 1.12.1
        Ruby : ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.x86_64-darwin21]
    RubyGems : 3.2.31
        Host : macOS 12.0.1 (21A559)
       Xcode : 13.3 (13E113)
         Git : git version 2.34.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Error

```
JSON::ParserError - 767: unexpected token at ''
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-trunk-1.6.0/lib/pod/command/trunk.rb:102:in `json'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-trunk-1.6.0/lib/pod/command/trunk/push.rb:92:in `push_to_trunk'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-trunk-1.6.0/lib/pod/command/trunk/push.rb:73:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:25:in `load'
/usr/local/bin/pod:25:in `<main>'
```
podspec file 
```

Pod::Spec.new do |spec|
  spec.name         = "xxxx"
  spec.version      = "1.3.1"
  spec.summary      = "be happy,my friend"
  spec.description  = <<-DESC
be happy,my friend
                   DESC

  spec.homepage     = "https://github.com/xxx"
  spec.license      = { :type => "MIT", :file => "LICENSE" }
  spec.author             = { "xxx" => "xxx.com" }
  spec.platform     = :ios, "9.0"
  spec.ios.deployment_target = "9.0"
  spec.source       = { :git => "xxxx", :tag => "#{spec.version}" }
  spec.resources = "Resource/xx.bundle"
  spec.source_files = 'Exx/Ecxx.framework/Headers/*.{h}'
  spec.ios.vendored_frameworks = 'Ecxx/Ecxx.framework'
  spec.public_header_files = 'Ecxx/Ecxx.framework/Headers/Ecxxx.h'
  spec.frameworks = "CoreFoundation","QuartzCore","Security","PhotosUI"
  spec.libraries = "sqlite3","z","iconv"
  spec.pod_target_xcconfig = {
        'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64'
    }
  spec.user_target_xcconfig = { 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64' }
  spec.requires_arc = true
end
```

**Comment by orta** [comment]
We've been trying to sort out some trunk issues with the DNS https://github.com/CocoaPods/trunk.cocoapods.org/issues/445 - but not got it yet, disabled the CDN for trunk.cocoapods.org

**Comment by chengssir** [comment]
How do I use it now?

**Comment by chengssir** [comment]
@orta

**Comment by shywoody** [comment]
> How do I use it now?

Service works now, you can have try
