### ISSUE TITLE
pod install --repo-update command fails

### ISSUE THREAD

**Issue by gsudhanshu** [CocoaPods/CocoaPods#11944]
### Command

```
/Users/imagine/.rvm/gems/ruby-2.7.6/bin/pod install --repo-update
```

### Report

* What did you do? I ran ```pod install --repo-update```

* What did you expect to happen? I expected success

* What happened instead? I got load error. So I did ```gem install ffi ``` on project root. Still same error 

### Stack

```
   CocoaPods : 1.12.1
        Ruby : ruby 2.7.6p219 (2022-04-12 revision c9c2245c0a) [arm64-darwin22]
    RubyGems : 3.1.6
        Host : macOS 13.1 (22C65)
       Xcode : 14.3.1 (14E300c)
         Git : git version 2.39.2 (Apple Git-143)
Ruby lib dir : /Users/imagine/.rvm/rubies/ruby-2.7.6/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'
prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
#flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'tersApp' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    #:hermes_enabled => flags[:hermes_enabled],
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    # :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'tersAppTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'RNSound', :path => '../node_modules/react-native-sound'
  pod 'RNAudioRecorderPlayer', :path => '../node_modules/react-native-audio-recorder-player'
  pod 'OpenSSL-Universal', '~>1.0.2.20'
end
```

### Error

```
LoadError - dlopen(/Users/imagine/ws/Timor/ters-mobile-app/tersApp/vendor/bundle/ruby/2.7.0/gems/ffi-1.15.5/lib/ffi_c.bundle, 0x0009): tried: '/Users/imagine/ws/Timor/ters-mobile-app/tersApp/vendor/bundle/ruby/2.7.0/gems/ffi-1.15.5/lib/ffi_c.bundle' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/imagine/ws/Timor/ters-mobile-app/tersApp/vendor/bundle/ruby/2.7.0/gems/ffi-1.15.5/lib/ffi_c.bundle' (no such file), '/Users/imagine/ws/Timor/ters-mobile-app/tersApp/vendor/bundle/ruby/2.7.0/gems/ffi-1.15.5/lib/ffi_c.bundle' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')) - /Users/imagine/ws/Timor/ters-mobile-app/tersApp/vendor/bundle/ruby/2.7.0/gems/ffi-1.15.5/lib/ffi_c.bundle
/Users/imagine/ws/Timor/ters-mobile-app/tersApp/vendor/bundle/ruby/2.7.0/gems/ffi-1.15.5/lib/ffi.rb:5:in `require'
/Users/imagine/ws/Timor/ters-mobile-app/tersApp/vendor/bundle/ruby/2.7.0/gems/ffi-1.15.5/lib/ffi.rb:5:in `rescue in <top (required)>'
/Users/imagine/ws/Timor/ters-mobile-app/tersApp/vendor/bundle/ruby/2.7.0/gems/ffi-1.15.5/lib/ffi.rb:2:in `<top (required)>'
/Users/imagine/ws/Timor/ters-mobile-app/tersApp/vendor/bundle/ruby/2.7.0/gems/ethon-0.16.0/lib/ethon.rb:3:in `require'
/Users/imagine/ws/Timor/ters-mobile-app/tersApp/vendor/bundle/ruby/2.7.0/gems/ethon-0.16.0/lib/ethon.rb:3:in `<top (required)>'
/Users/imagine/ws/Timor/ters-mobile-app/tersApp/vendor/bundle/ruby/2.7.0/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `require'
/Users/imagine/ws/Timor/ters-mobile-app/tersApp/vendor/bundle/ruby/2.7.0/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
/Users/imagine/ws/Timor/ters-mobile-app/tersApp/vendor/bundle/ruby/2.7.0/gems/cocoapods-core-1.12.1/lib/cocoapods-core/cdn_source.rb:440:in `require'
/Users/imagine/ws/Timor/ters-mobile-app/tersApp/vendor/bundle/ruby/2.7.0/gems/cocoapods-core-1.12.1/lib/cocoapods-core/cdn_source.rb:440:in `download_typhoeus_impl_async'
/Users/imagine/ws/Timor/ters-mobile-app/tersApp/vendor/bundle/ruby/2.7.0/gems/cocoapods-core-1.12.1/lib/cocoapods-core/cdn_source.rb:372:in `download_and_save_with_retries_async'
/Users/imagine/ws/Timor/ters-mobile-app/tersApp/vendor/bundle/ruby/2.7.0/gems/cocoapods-core-1.12.1/lib/cocoapods-core/cdn_source.rb:365:in `download_file_async'
/Users/imagine/ws/Timor/ters-mobile-app/tersApp/vendor/bundle/ruby/2.7.0/gems/cocoapods-core-1.12.1/lib/cocoapods-core/cdn_source.rb:338:in `download_file'
/Users/imagine/ws/Timor/ters-mobile-app/tersApp/vendor/bundle/ruby/2.7.0/gems/cocoapods-core-1.12.1/lib/cocoapods-core/cdn_source.rb:78:in `deprecated_local_podspecs'
/Users/imagine/ws/Timor/ters-mobile-app/tersApp/vendor/bundle/ruby/2.7.0/gems/cocoapods-core-1.12.1/lib/cocoapods-core/cdn_source.rb:60:in `preheat_existing_files'
/Users/imagine/ws/Timor/ters-mobile-app/tersApp/vendor/bundle/ruby/2.7.0/gems/cocoapods-core-1.12.1/lib/cocoapods-core/cdn_source.rb:257:in `update'
/Users/imagine/ws/Timor/ters-mobile-app/tersApp/vendor/bundle/ruby/2.7.0/gems/cocoapods-1.12.1/lib/cocoapods/sources_manager.rb:144:in `block (3 levels) in update'
/Users/imagine/ws/Timor/ters-mobile-app/tersApp/vendor/bundle/ruby/2.7.0/gems/cocoapods-1.12.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/imagine/ws/Timor/ters-mobile-app/tersApp/vendor/bundle/ruby/2.7.0/gems/cocoapods-1.12.1/lib/cocoapods/sources_manager.rb:143:in `block (2 levels) in update'
/Users/imagine/ws/Timor/ters-mobile-app/tersApp/vendor/bundle/ruby/2.7.0/gems/cocoapods-1.12.1/lib/cocoapods/sources_manager.rb:142:in `each'
/Users/imagine/ws/Timor/ters-mobile-app/tersApp/vendor/bundle/ruby/2.7.0/gems/cocoapods-1.12.1/lib/cocoapods/sources_manager.rb:142:in `block in update'
/Users/imagine/ws/Timor/ters-mobile-app/tersApp/vendor/bundle/ruby/2.7.0/gems/cocoapods-1.12.1/lib/cocoapods/sources_manager.rb:140:in `open'
/Users/imagine/ws/Timor/ters-mobile-app/tersApp/vendor/bundle/ruby/2.7.0/gems/cocoapods-1.12.1/lib/cocoapods/sources_manager.rb:140:in `update'
/Users/imagine/ws/Timor/ters-mobile-app/tersApp/vendor/bundle/ruby/2.7.0/gems/cocoapods-1.12.1/lib/cocoapods/installer/analyzer.rb:146:in `block in update_repositories'
/Users/imagine/ws/Timor/ters-mobile-app/tersApp/vendor/bundle/ruby/2.7.0/gems/cocoapods-1.12.1/lib/cocoapods/installer/analyzer.rb:144:in `each'
/Users/imagine/ws/Timor/ters-mobile-app/tersApp/vendor/bundle/ruby/2.7.0/gems/cocoapods-1.12.1/lib/cocoapods/installer/analyzer.rb:144:in `update_repositories'
/Users/imagine/ws/Timor/ters-mobile-app/tersApp/vendor/bundle/ruby/2.7.0/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:240:in `block in resolve_dependencies'
/Users/imagine/ws/Timor/ters-mobile-app/tersApp/vendor/bundle/ruby/2.7.0/gems/cocoapods-1.12.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/imagine/ws/Timor/ters-mobile-app/tersApp/vendor/bundle/ruby/2.7.0/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:239:in `resolve_dependencies'
/Users/imagine/ws/Timor/ters-mobile-app/tersApp/vendor/bundle/ruby/2.7.0/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:162:in `install!'
/Users/imagine/ws/Timor/ters-mobile-app/tersApp/vendor/bundle/ruby/2.7.0/gems/cocoapods-1.12.1/lib/cocoapods/command/install.rb:52:in `run'
/Users/imagine/ws/Timor/ters-mobile-app/tersApp/vendor/bundle/ruby/2.7.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Users/imagine/ws/Timor/ters-mobile-app/tersApp/vendor/bundle/ruby/2.7.0/gems/cocoapods-1.12.1/lib/cocoapods/command.rb:52:in `run'
/Users/imagine/ws/Timor/ters-mobile-app/tersApp/vendor/bundle/ruby/2.7.0/gems/cocoapods-1.12.1/bin/pod:55:in `<top (required)>'
/Users/imagine/.rvm/gems/ruby-2.7.6/bin/pod:23:in `load'
/Users/imagine/.rvm/gems/ruby-2.7.6/bin/pod:23:in `<main>'
/Users/imagine/.rvm/gems/ruby-2.7.6/bin/ruby_executable_hooks:22:in `eval'
/Users/imagine/.rvm/gems/ruby-2.7.6/bin/ruby_executable_hooks:22:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=dlopen%28%2FUsers%2Fimagine%2Fws%2FTimor%2Fters-mobile-app%2FtersApp%2Fvendor%2Fbundle%2Fruby%2F2.7.0%2Fgems%2Fffi-1.15.5%2Flib%2Fffi_c.bundle%2C+0x0009%29%3A+tried%3A+%27%2FUsers%2Fimagine%2Fws%2FTimor%2Fters-mobile-app%2FtersApp%2Fvendor%2Fbundle%2Fruby%2F2.7.0%2Fgems%2Fffi-1.15.5%2Flib%2Fffi_c.bundle%27+%28mach-o+file%2C+but+is+an+incompatible+architecture+%28have+%27x86_64%27%2C+need+%27arm64%27%29%29%2C+%27%2FSystem%2FVolumes%2FPreboot%2FCryptexes%2FOS%2FUsers%2Fimagine%2Fws%2FTimor%2Fters-mobile-app%2FtersApp%2Fvendor%2Fbundle%2Fruby%2F2.7.0%2Fgems%2Fffi-1.15.5%2Flib%2Fffi_c.bundle%27+%28no+such+file%29%2C+%27%2FUsers%2Fimagine%2Fws%2FTimor%2Fters-mobile-app%2FtersApp%2Fvendor%2Fbundle%2Fruby%2F2.7.0%2Fgems%2Fffi-1.15.5%2Flib%2Fffi_c.bundle%27+%28mach-o+file%2C+but+is+an+incompatible+architecture+%28have+%27x86_64%27%2C+need+%27arm64%27%29%29+-+%2FUsers%2Fimagine%2Fws%2FTimor%2Fters-mobile-app%2FtersApp%2Fvendor%2Fbundle%2Fruby%2F2.7.0%2Fgems%2Fffi-1.15.5%2Flib%2Fffi_c.bundle&type=Issues

**Comment by hooman-test** [comment]
Same error for me, I have also reverted the cocoapods to version 1.12.0, still no chance.

**Comment by zahid502** [comment]
@hooman-test @gsudhanshu 
This error occurred due to cocapods caches, in some case our pods are caches with our previous projects.
So clear the caches of cocapods and reinstall it.
It will worked.

to clear the cocapods, this article will help you [Clear CocoaPods cache, re-download and re-install all pods](https://gist.github.com/mbinna/4202236)

during clear cocapods, if you get permission denied issue then follow this article [cocoapods-pod-install-permission-denied](https://stackoverflow.com/questions/16049335/cocoapods-pod-install-permission-denied)
