### ISSUE TITLE
- ERROR | [iOS] unknown: Encountered an unknown error (Pod::DSLError) during validation.

### ISSUE THREAD

**Issue by nzeakokosi7** [CocoaPods/CocoaPods#11949]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Run pod spec lint okraIosOfficial.podspec

## What did you expect to happen?

ℹ Pass validation as did pod lib lint okraIosOfficial.podspec

## What happened instead?

ℹ Got this error     - ERROR | [iOS] unknown: Encountered an unknown error (Pod::DSLError) during validation.

## CocoaPods Environment

ℹ
 ### Stack

```
   CocoaPods : 1.12.1
        Ruby : ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin22]
    RubyGems : 3.4.14
        Host : macOS 13.2 (22D49)
       Xcode : 14.3 (14E222b)
         Git : git version 2.39.2 (Apple Git-143)
Ruby lib dir : /Users/okra/.rubies/ruby-3.2.2/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /Users/okra/.gem/ruby/3.2.2/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

## Project that demonstrates the issue

ℹ[ Link to project](https://github.com/okraHQ/okra-ios-official)

**Comment by orta** [comment]
What is the full stack trace? At a glance the Podspec looks fine

**Comment by nzeakokosi7** [comment]
Here it is:

 - ERROR | [iOS] unknown: Encountered an unknown error (Pod::DSLError
/Users/okra/.rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-core-1.12.1/lib/cocoapods-core/specification.rb:845:in `rescue in _eval_podspec'
/Users/okra/.rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-core-1.12.1/lib/cocoapods-core/specification.rb:836:in `_eval_podspec'
/Users/okra/.rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-core-1.12.1/lib/cocoapods-core/specification.rb:746:in `block in from_string'
/Users/okra/.rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-core-1.12.1/lib/cocoapods-core/specification.rb:745:in `chdir'
/Users/okra/.rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-core-1.12.1/lib/cocoapods-core/specification.rb:745:in `from_string'
/Users/okra/.rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-core-1.12.1/lib/cocoapods-core/specification.rb:726:in `from_file'
/Users/okra/.gem/ruby/3.2.2/gems/cocoapods-1.12.1/lib/cocoapods/sandbox/podspec_finder.rb:15:in `block in podspecs'
/Users/okra/.gem/ruby/3.2.2/gems/cocoapods-1.12.1/lib/cocoapods/sandbox/podspec_finder.rb:14:in `each'
/Users/okra/.gem/ruby/3.2.2/gems/cocoapods-1.12.1/lib/cocoapods/sandbox/podspec_finder.rb:14:in `podspecs'
/Users/okra/.gem/ruby/3.2.2/gems/cocoapods-1.12.1/lib/cocoapods/downloader.rb:84:in `download_request'
/Users/okra/.gem/ruby/3.2.2/gems/cocoapods-1.12.1/lib/cocoapods/downloader/cache.rb:256:in `download'
/Users/okra/.gem/ruby/3.2.2/gems/cocoapods-1.12.1/lib/cocoapods/downloader/cache.rb:239:in `block in uncached_pod'
/Users/okra/.gem/ruby/3.2.2/gems/cocoapods-1.12.1/lib/cocoapods/downloader/cache.rb:266:in `in_tmpdir'
/Users/okra/.gem/ruby/3.2.2/gems/cocoapods-1.12.1/lib/cocoapods/downloader/cache.rb:238:in `uncached_pod'
/Users/okra/.gem/ruby/3.2.2/gems/cocoapods-1.12.1/lib/cocoapods/downloader/cache.rb:33:in `download_pod'
/Users/okra/.gem/ruby/3.2.2/gems/cocoapods-1.12.1/lib/cocoapods/downloader.rb:42:in `download'
/Users/okra/.gem/ruby/3.2.2/gems/cocoapods-1.12.1/lib/cocoapods/installer/pod_source_downloader.rb:69:in `download!'
/Users/okra/.gem/ruby/3.2.2/gems/cocoapods-1.12.1/lib/cocoapods/installer/pod_source_installer.rb:117:in `download_source'
/Users/okra/.gem/ruby/3.2.2/gems/cocoapods-1.12.1/lib/cocoapods/installer/pod_source_installer.rb:67:in `install!'
/Users/okra/.gem/ruby/3.2.2/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:621:in `install_source_of_pod'
/Users/okra/.gem/ruby/3.2.2/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:539:in `block (2 levels) in install_pod_sources'
/Users/okra/.gem/ruby/3.2.2/gems/cocoapods-1.12.1/lib/cocoapods/user_interface.rb:86:in `titled_section'
/Users/okra/.gem/ruby/3.2.2/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:538:in `block in install_pod_sources'
/Users/okra/.gem/ruby/3.2.2/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:535:in `each'
/Users/okra/.gem/ruby/3.2.2/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:535:in `install_pod_sources'
/Users/okra/.gem/ruby/3.2.2/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:258:in `block in download_dependencies'
/Users/okra/.gem/ruby/3.2.2/gems/cocoapods-1.12.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/okra/.gem/ruby/3.2.2/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:257:in `download_dependencies'
/Users/okra/.gem/ruby/3.2.2/gems/cocoapods-1.12.1/lib/cocoapods/validator.rb:580:in `block in download_pod'
/Users/okra/.gem/ruby/3.2.2/gems/cocoapods-1.12.1/lib/cocoapods/validator.rb:580:in `each'
/Users/okra/.gem/ruby/3.2.2/gems/cocoapods-1.12.1/lib/cocoapods/validator.rb:580:in `download_pod'
/Users/okra/.gem/ruby/3.2.2/gems/cocoapods-1.12.1/lib/cocoapods/validator.rb:402:in `block in perform_extensive_analysis'
/Users/okra/.gem/ruby/3.2.2/gems/cocoapods-1.12.1/lib/cocoapods/validator.rb:396:in `each'
/Users/okra/.gem/ruby/3.2.2/gems/cocoapods-1.12.1/lib/cocoapods/validator.rb:396:in `perform_extensive_analysis'
/Users/okra/.gem/ruby/3.2.2/gems/cocoapods-1.12.1/lib/cocoapods/validator.rb:129:in `validate'
/Users/okra/.gem/ruby/3.2.2/gems/cocoapods-1.12.1/lib/cocoapods/command/spec/lint.rb:90:in `block in run'
/Users/okra/.gem/ruby/3.2.2/gems/cocoapods-1.12.1/lib/cocoapods/command/spec/lint.rb:71:in `each'
/Users/okra/.gem/ruby/3.2.2/gems/cocoapods-1.12.1/lib/cocoapods/command/spec/lint.rb:71:in `run'
/Users/okra/.rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Users/okra/.gem/ruby/3.2.2/gems/cocoapods-1.12.1/lib/cocoapods/command.rb:52:in `run'
/Users/okra/.gem/ruby/3.2.2/gems/cocoapods-1.12.1/bin/pod:55:in `<top (required)>'
/Users/okra/.gem/ruby/3.2.2/bin/pod:25:in `load'
/Users/okra/.gem/ruby/3.2.2/bin/pod:25:in `<main>'
) during validation.

Analyzed 1 podspec.

[!] The spec did not pass validation, due to 1 error.

/Users/okra/.gem/ruby/3.2.2/gems/cocoapods-1.12.1/lib/cocoapods/command/spec/lint.rb:107:in `run'
/Users/okra/.rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Users/okra/.gem/ruby/3.2.2/gems/cocoapods-1.12.1/lib/cocoapods/command.rb:52:in `run'
/Users/okra/.gem/ruby/3.2.2/gems/cocoapods-1.12.1/bin/pod:55:in `<top (required)>'
/Users/okra/.gem/ruby/3.2.2/bin/pod:25:in `load'
/Users/okra/.gem/ruby/3.2.2/bin/pod:25:in `<main>'

**Comment by nzeakokosi7** [comment]
Hello @orta , just checking in to know if there's any update on this. Really appreciate the great work, Thanks.
