### ISSUE TITLE
Pod install not working (Library not loaded)

### ISSUE THREAD

**Issue by elabayoub** [CocoaPods/CocoaPods#11979]
### Command

```
/Users/luci/.rvm/gems/ruby-2.6.1/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.12.1
        Ruby : ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-darwin22]
    RubyGems : 3.4.10
        Host : macOS 13.1 (22C65)
       Xcode : 14.2 (14C18)
         Git : git version 2.37.1 (Apple Git-137.1)
Ruby lib dir : /usr/local/Cellar/ruby/3.2.2_1/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ 31e806081b752282e45367cf8cb6726dac95d4af

               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# Disable Ad ID for Firebase (since it's not needed)
$RNFirebaseAnalyticsWithoutAdIdSupport = true

platform :ios, '13.0'

target 'Whateva' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true
  )

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  ### Custom dependencies
  # Adobe AEP

  # Google Maps

  # Google Tag Manager

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)

    # fix Mac M1 debug build issue
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.1'
    end

    # fix Xcode 14 CocoaPods error on build
    # https://github.com/CocoaPods/CocoaPods/issues/8891
    installer.pods_project.targets.each do |target|
      if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
        target.build_configurations.each do |config|
            config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
  end
end
```

### Error

```
LoadError - dlopen(/Users/luci/.rvm/gems/ruby-2.6.1/gems/ffi-1.15.5/lib/ffi_c.bundle, 0x0009): Library not loaded: /usr/local/opt/ruby/lib/libruby.3.0.dylib
  Referenced from: <7D9D1AE7-32C3-3DE5-AC9E-1360E3C32C44> /Users/luci/.rvm/gems/ruby-2.6.1/gems/ffi-1.15.5/lib/ffi_c.bundle
  Reason: tried: '/usr/local/opt/ruby/lib/libruby.3.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/ruby/lib/libruby.3.0.dylib' (no such file), '/usr/local/opt/ruby/lib/libruby.3.0.dylib' (no such file), '/usr/local/lib/libruby.3.0.dylib' (no such file), '/usr/lib/libruby.3.0.dylib' (no such file, not in dyld cache), '/usr/local/Cellar/ruby/3.2.2_1/lib/libruby.3.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/Cellar/ruby/3.2.2_1/lib/libruby.3.0.dylib' (no such file), '/usr/local/Cellar/ruby/3.2.2_1/lib/libruby.3.0.dylib' (no such file), '/usr/local/lib/libruby.3.0.dylib' (no such file), '/usr/lib/libruby.3.0.dylib' (no such file, not in dyld cache) - /Users/luci/.rvm/gems/ruby-2.6.1/gems/ffi-1.15.5/lib/ffi_c.bundle
<internal:/usr/local/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/usr/local/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/Users/luci/.rvm/gems/ruby-2.6.1/gems/ffi-1.15.5/lib/ffi.rb:5:in `rescue in <top (required)>'
/Users/luci/.rvm/gems/ruby-2.6.1/gems/ffi-1.15.5/lib/ffi.rb:2:in `<top (required)>'
<internal:/usr/local/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/usr/local/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/Users/luci/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/ethon-0.15.0/lib/ethon.rb:3:in `<top (required)>'
<internal:/usr/local/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/usr/local/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/Users/luci/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
<internal:/usr/local/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/usr/local/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/Users/luci/.rvm/gems/ruby-2.6.1/gems/cocoapods-core-1.12.1/lib/cocoapods-core/cdn_source.rb:440:in `download_typhoeus_impl_async'
/Users/luci/.rvm/gems/ruby-2.6.1/gems/cocoapods-core-1.12.1/lib/cocoapods-core/cdn_source.rb:372:in `download_and_save_with_retries_async'
/Users/luci/.rvm/gems/ruby-2.6.1/gems/cocoapods-core-1.12.1/lib/cocoapods-core/cdn_source.rb:365:in `download_file_async'
/Users/luci/.rvm/gems/ruby-2.6.1/gems/cocoapods-core-1.12.1/lib/cocoapods-core/cdn_source.rb:338:in `download_file'
/Users/luci/.rvm/gems/ruby-2.6.1/gems/cocoapods-core-1.12.1/lib/cocoapods-core/cdn_source.rb:284:in `ensure_versions_file_loaded'
/Users/luci/.rvm/gems/ruby-2.6.1/gems/cocoapods-core-1.12.1/lib/cocoapods-core/cdn_source.rb:208:in `search'
/Users/luci/.rvm/gems/ruby-2.6.1/gems/cocoapods-core-1.12.1/lib/cocoapods-core/source/aggregate.rb:83:in `block in search'
/Users/luci/.rvm/gems/ruby-2.6.1/gems/cocoapods-core-1.12.1/lib/cocoapods-core/source/aggregate.rb:83:in `select'
/Users/luci/.rvm/gems/ruby-2.6.1/gems/cocoapods-core-1.12.1/lib/cocoapods-core/source/aggregate.rb:83:in `search'
/Users/luci/.rvm/gems/ruby-2.6.1/gems/cocoapods-1.12.1/lib/cocoapods/resolver.rb:416:in `create_set_from_sources'
/Users/luci/.rvm/gems/ruby-2.6.1/gems/cocoapods-1.12.1/lib/cocoapods/resolver.rb:385:in `find_cached_set'
/Users/luci/.rvm/gems/ruby-2.6.1/gems/cocoapods-1.12.1/lib/cocoapods/resolver.rb:360:in `specifications_for_dependency'
/Users/luci/.rvm/gems/ruby-2.6.1/gems/cocoapods-1.12.1/lib/cocoapods/resolver.rb:165:in `search_for'
/Users/luci/.rvm/gems/ruby-2.6.1/gems/cocoapods-1.12.1/lib/cocoapods/resolver.rb:274:in `block in sort_dependencies'
/Users/luci/.rvm/gems/ruby-2.6.1/gems/cocoapods-1.12.1/lib/cocoapods/resolver.rb:267:in `each'
/Users/luci/.rvm/gems/ruby-2.6.1/gems/cocoapods-1.12.1/lib/cocoapods/resolver.rb:267:in `sort_by'
/Users/luci/.rvm/gems/ruby-2.6.1/gems/cocoapods-1.12.1/lib/cocoapods/resolver.rb:267:in `sort_by!'
/Users/luci/.rvm/gems/ruby-2.6.1/gems/cocoapods-1.12.1/lib/cocoapods/resolver.rb:267:in `sort_dependencies'
/Users/luci/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:60:in `block in sort_dependencies'
/Users/luci/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:77:in `with_no_such_dependency_error_handling'
/Users/luci/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:59:in `sort_dependencies'
/Users/luci/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:754:in `push_state_for_requirements'
/Users/luci/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:288:in `push_initial_state'
/Users/luci/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:210:in `start_resolution'
/Users/luci/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:168:in `resolve'
/Users/luci/.rvm/rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in `resolve'
/Users/luci/.rvm/gems/ruby-2.6.1/gems/cocoapods-1.12.1/lib/cocoapods/resolver.rb:94:in `resolve'
/Users/luci/.rvm/gems/ruby-2.6.1/gems/cocoapods-1.12.1/lib/cocoapods/installer/analyzer.rb:1082:in `block in resolve_dependencies'
/Users/luci/.rvm/gems/ruby-2.6.1/gems/cocoapods-1.12.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/luci/.rvm/gems/ruby-2.6.1/gems/cocoapods-1.12.1/lib/cocoapods/installer/analyzer.rb:1080:in `resolve_dependencies'
/Users/luci/.rvm/gems/ruby-2.6.1/gems/cocoapods-1.12.1/lib/cocoapods/installer/analyzer.rb:125:in `analyze'
/Users/luci/.rvm/gems/ruby-2.6.1/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:422:in `analyze'
/Users/luci/.rvm/gems/ruby-2.6.1/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:244:in `block in resolve_dependencies'
/Users/luci/.rvm/gems/ruby-2.6.1/gems/cocoapods-1.12.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/luci/.rvm/gems/ruby-2.6.1/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:243:in `resolve_dependencies'
/Users/luci/.rvm/gems/ruby-2.6.1/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:162:in `install!'
/Users/luci/.rvm/gems/ruby-2.6.1/gems/cocoapods-1.12.1/lib/cocoapods/command/install.rb:52:in `run'
/Users/luci/.rvm/gems/ruby-2.6.1/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Users/luci/.rvm/gems/ruby-2.6.1/gems/cocoapods-1.12.1/lib/cocoapods/command.rb:52:in `run'
/Users/luci/.rvm/gems/ruby-2.6.1/gems/cocoapods-1.12.1/bin/pod:55:in `<top (required)>'
/Users/luci/.rvm/gems/ruby-2.6.1/bin/pod:23:in `load'
/Users/luci/.rvm/gems/ruby-2.6.1/bin/pod:23:in `<main>'
/Users/luci/.rvm/gems/ruby-2.6.1/bin/ruby_executable_hooks:22:in `eval'
/Users/luci/.rvm/gems/ruby-2.6.1/bin/ruby_executable_hooks:22:in `<main>'
```

**Comment by dnkoutso** [comment]
Please search for ffi related issues.

**Comment by elabayoub** [comment]
> Please search for ffi related issues.

I have already, and installed it, but still have same issue

**Comment by dnkoutso** [comment]
This is not an issue related to cocoapods but the installation of ffi gem in your environment. Try different version of Ruby or re-installing ffi gem.

**Comment by elabayoub** [comment]
I tried `gem install ffi` or `arch -x86_64 gem install ffi` with no luck, for ruby i use rvm, and i've already tried different versions

**Comment by elabayoub** [comment]
Problem solved:

1- `bundle install` in project root
2- `brew install libffi`
3- `gem install ffi`
4- `pod install` in project's `ios` directory

Thanks @dnkoutso for your help

**Comment by n1kitka** [comment]
@elabayoub Hi! 
Please could you help me, I have the same issue as you.
So, when I run "bundle install" I received "Could not locate Gemfile".
How I can fix this?

**Comment by elabayoub** [comment]
> 

Hi, probably you are running `bundle install` from a directory (path) where there isn't a Gemfile, for example in my case; i have Gemfile in project's root path.
