### ISSUE TITLE
ArgumentError - Malformed version number string None

### ISSUE THREAD

**Issue by chandramouliraju** [CocoaPods/CocoaPods#11993]
# Report

## What did you do?
`pod install`

## What did you expect to happen?

Install all pod dependencies correctly.

## What happened instead?
```
   CocoaPods : 1.12.1
        Ruby : ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.x86_64-darwin22]
    RubyGems : 3.0.3.1
        Host : macOS 13.4.1 (22F82)
       Xcode : 14.3.1 (14E300c)
         Git : git version 2.39.2 (Apple Git-143)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KonyJS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KonyJS
  pod 'Firebase/Analytics'

end

target 'KonyWidgetExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KonyWidgetExtension

end

target 'KProtected' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KProtected
  pod 'Firebase/Analytics'

end

target 'KRelease' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KRelease
  pod 'Firebase/Analytics'

end

target 'KWatchOS2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KWatchOS2

end

target 'KWatchOS2 Extension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KWatchOS2 Extension

end

target 'NFILoader' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NFILoader

end

target 'Preview' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Preview

end
```

### Error

```
ArgumentError - Malformed version number string None
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.12.1/lib/cocoapods-core/version.rb:47:in `initialize'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.12.1/lib/cocoapods-core/vendor/version.rb:199:in `new'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.12.1/lib/cocoapods-core/vendor/version.rb:199:in `new'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/installer/analyzer/target_inspector.rb:150:in `block in compute_platform'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/installer/analyzer/target_inspector.rb:146:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/installer/analyzer/target_inspector.rb:146:in `compute_platform'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/installer/analyzer/target_inspector.rb:43:in `compute_results'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/installer/analyzer.rb:1197:in `block (3 levels) in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/installer/analyzer.rb:1195:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/installer/analyzer.rb:1195:in `block (2 levels) in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/installer/analyzer.rb:1193:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/installer/analyzer.rb:1193:in `block in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/installer/analyzer.rb:1188:in `inspect_targets_to_integrate'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/installer/analyzer.rb:107:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:422:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:244:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:243:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:162:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=Malformed+version+number+string+None&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
 - cocospod install报错
   https://github.com/CocoaPods/CocoaPods/issues/10269 [closed] [2 comments]
   09 Dec 2020

 - Malformed version number string
   https://github.com/CocoaPods/CocoaPods/issues/7765 [closed] [48 comments]
   11 May 2020

 - Trying to run flutter App on ios simulator give me this Error
   https://github.com/CocoaPods/CocoaPods/issues/10127 [closed] [6 comments]
   12 Oct 2020

and 9 more at:
https://github.com/cocoapods/cocoapods/search?q=Malformed%20version%20number%20string%20None&type=Issues&utf8=✓

[!] Automatically assigning platform `iOS` with version `9.0` on target `KonyJS` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

[!] Automatically assigning platform `iOS` with version `14.2` on target `KonyWidgetExtension` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

[!] Automatically assigning platform `iOS` with version `9.0` on target `KProtected` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

[!] Automatically assigning platform `iOS` with version `9.0` on target `KRelease` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

**Comment by orta** [comment]
I think you might need to figure out what podspec has an incorrect semver in your tree. You could send a PR to cocoapods-core which catches this error and gives context like the podspec it was looking at too 👍🏻

**Comment by segunabiodun** [comment]
It is weird that cocoapods can output an error but wouldn't give information about the source of the error
