### ISSUE TITLE
Error While Executing 'pod list'

### ISSUE THREAD

**Issue by UbySoft** [CocoaPods/CocoaPods#12037]
Hello,

I hope you are all doing well. I am encountering an error while executing the 'pod list' command in my development environment. I would like to report this problem and provide some detailed information to help resolve it.

Development Environment Details:
- Operating System: MacOS Ventura:  Versione 13.5 (22G74)
- Ruby Version: ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.x86_64-darwin22]
- CocoaPods Version: 1.12.1
- Error Details: 
### Podfile

```ruby
# DO NOT MODIFY -- auto-generated by Apache Cordova
source 'https://cdn.cocoapods.org/'
platform :ios, '11.0'
use_frameworks!
target 'OneSignalCleanTest' do
	project 'OneSignalCleanTest.xcodeproj'
	pod 'OneSignalXCFramework', '5.0.0-beta-04'
end
```

### Error

```
NoMethodError - undefined method `version' for nil:NilClass
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/user_interface.rb:218:in `pod'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/command/list.rb:24:in `block in run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/command/list.rb:24:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/command/list.rb:24:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

Problem Description:
I am encountering the "NoMethodError - undefined method `version' for nil:NilClass" error while executing the 'pod list' command. This error seems to affect the display of the list of CocoaPods dependencies.

Error Messages:
NoMethodError - undefined method `version' for nil:NilClass

Steps to Reproduce:
1. Execute the 'pod list' command.
2. Encounter the "NoMethodError - undefined method `version' for nil:NilClass" error.

I hope this information is helpful in resolving the issue. I am looking forward to your support and I thank you in advance for your assistance.

Best regards,
Ubaldo Formichetti

**Comment by Vyazovoy** [comment]
@UbySoft, I would recommend to migrate your Ruby version at least to `2.7` but better to `>=3.2`. As you can see [here](https://endoflife.date/ruby) Ruby <3.0 has reached its end of life.
