### ISSUE TITLE
[error report] pod install /w m1 pro macbook

### ISSUE THREAD

**Issue by VestaCute** [CocoaPods/CocoaPods#12121]
### Command

```
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/bin/pod install
```

### Stack

```
   CocoaPods : 1.14.2
        Ruby : ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin23]
    RubyGems : 3.4.10
        Host : macOS 14.0 (23A344)
       Xcode : 15.0.1 (15A507)
         Git : git version 2.39.3 (Apple Git-145)
Ruby lib dir : /opt/homebrew/Cellar/ruby/3.2.2_1/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
platform :ios, '14.0'

use_frameworks!
inhibit_all_warnings!

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f == 8.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      end
    end
  end
end

def common_pods
  pod 'SnapKit'
  pod 'RxCocoa'
  pod 'RxSwift'
  pod 'RxRelay'
  pod 'R.swift'
  pod 'Alamofire'
  pod 'Kingfisher'
  pod 'ObjectMapper'
  pod 'IQKeyboardManagerSwift'
  pod 'PhoneNumberKit'
  pod 'BottomSheet', :git => 'https://github.com/joomcode/BottomSheet'
  pod 'DropDown', :git => 'https://github.com/VestaCute/DropDown'
  pod 'Firebase/Messaging'
  pod 'YandexMobileMetrica/Dynamic', '4.5.0'
  pod 'TinkoffASDKCore'
  pod 'TinkoffASDKUI'
  pod 'TinkoffID'
end

target 'Pineapple' do
  common_pods
end
```

### Error

```
JSON::ParserError - Failed to parse JSON at file: '/Users/alexandrakondratjeva/.cocoapods/repos/trunk/Specs/0/3/5/Firebase/1.0.5/Firebase.podspec.json'.

unexpected token at ''
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-core-1.14.2/lib/cocoapods-core/specification/json.rb:66:in `rescue in from_json'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-core-1.14.2/lib/cocoapods-core/specification/json.rb:61:in `from_json'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-core-1.14.2/lib/cocoapods-core/specification.rb:752:in `from_string'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-core-1.14.2/lib/cocoapods-core/specification.rb:726:in `from_file'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-core-1.14.2/lib/cocoapods-core/source.rb:188:in `specification'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-1.14.2/lib/cocoapods/resolver/lazy_specification.rb:37:in `specification'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-1.14.2/lib/cocoapods/resolver/lazy_specification.rb:29:in `subspec_by_name'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-1.14.2/lib/cocoapods/resolver.rb:362:in `block in specifications_for_dependency'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-1.14.2/lib/cocoapods/resolver.rb:362:in `map'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-1.14.2/lib/cocoapods/resolver.rb:362:in `specifications_for_dependency'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-1.14.2/lib/cocoapods/resolver.rb:165:in `search_for'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-1.14.2/lib/cocoapods/resolver.rb:274:in `block in sort_dependencies'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-1.14.2/lib/cocoapods/resolver.rb:267:in `each'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-1.14.2/lib/cocoapods/resolver.rb:267:in `sort_by'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-1.14.2/lib/cocoapods/resolver.rb:267:in `sort_by!'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-1.14.2/lib/cocoapods/resolver.rb:267:in `sort_dependencies'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:60:in `block in sort_dependencies'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:77:in `with_no_such_dependency_error_handling'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:59:in `sort_dependencies'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:754:in `push_state_for_requirements'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:288:in `push_initial_state'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:210:in `start_resolution'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:168:in `resolve'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in `resolve'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-1.14.2/lib/cocoapods/resolver.rb:94:in `resolve'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-1.14.2/lib/cocoapods/installer/analyzer.rb:1082:in `block in resolve_dependencies'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-1.14.2/lib/cocoapods/user_interface.rb:64:in `section'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-1.14.2/lib/cocoapods/installer/analyzer.rb:1080:in `resolve_dependencies'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-1.14.2/lib/cocoapods/installer/analyzer.rb:125:in `analyze'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-1.14.2/lib/cocoapods/installer.rb:422:in `analyze'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-1.14.2/lib/cocoapods/installer.rb:244:in `block in resolve_dependencies'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-1.14.2/lib/cocoapods/user_interface.rb:64:in `section'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-1.14.2/lib/cocoapods/installer.rb:243:in `resolve_dependencies'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-1.14.2/lib/cocoapods/installer.rb:162:in `install!'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-1.14.2/lib/cocoapods/command/install.rb:52:in `run'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-1.14.2/lib/cocoapods/command.rb:52:in `run'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-1.14.2/bin/pod:55:in `<top (required)>'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/bin/pod:25:in `load'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/bin/pod:25:in `<main>'
```

Has anyone encountered this problem? For some reason I have all pods installed except for the firebase pods

**Comment by mlazari** [comment]
Looks like a duplicate of https://github.com/CocoaPods/CocoaPods/issues/12110

**Comment by sergeimikhan** [comment]
@VestaCute could you please try to remove trunk repo and try again?

```
rm -rf ~/.cocoapods/repos/trunk
```

**Comment by VestaCute** [comment]
> @VestaCute could you please try to remove trunk repo and try again?
> 
> ```
> rm -rf ~/.cocoapods/repos/trunk
> ```

No, that doesn't work, nor does using this:

rm -rf ~/Library/Caches/CocoaPods
rm -rf ~/.cocoapods
rm -rf Pods
pod install

**Comment by kengres** [comment]
> 0/3/5/Firebase/1.0.5/Firebase.podspec.json

AS A SHORT-TERM SOLUTION:
Try manually copying this file: https://github.com/CocoaPods/Specs/blob/master/Specs/0/3/5/Firebase/1.0.5/Firebase.podspec.json to the file that is causing the error. It worked for me.

**Comment by Facel3ssR0nin** [comment]
Thanks @kengres , you helped a lot. For some reason after github fetch 2 pods jsons ( are empty instead of expected scheme. Issue happenes for us only on fresh installed Sonoma without cached files
Issue with files:
trunk/Specs/6/1/e/nanopb/2.30909.0/nanopb.podspec.json
trunk/Specs/e/2/1/FirebaseAnalytics/10.11.0/FirebaseAnalytics.podspec.json
cocoapods version: 1.12.1

**Comment by mlazari** [comment]
@Facel3ssR0nin Are these 2 commands showing `content-encoding: br` for you?
```
mihai@Mihais-Mac-mini ~ % curl -I "https://cdn.jsdelivr.net/cocoa/Specs/6/1/e/nanopb/2.30909.0/nanopb.podspec.json" -H 'Accept-Encoding: gzip'
HTTP/2 200 
date: Sat, 28 Oct 2023 14:05:30 GMT
content-type: application/json; charset=utf-8
content-length: 613
access-control-allow-origin: *
access-control-expose-headers: *
timing-allow-origin: *
cache-control: public, max-age=3600
cross-origin-resource-policy: cross-origin
x-content-type-options: nosniff
strict-transport-security: max-age=31536000; includeSubDomains; preload
etag: W/"5b2-tVLM4xK2yEhBgO9HFZvA9lofBDE"
content-encoding: gzip
x-served-by: cache-fra-etou8220083-FRA, cache-yyz4520-YYZ
x-cache: HIT, HIT
vary: Accept-Encoding
alt-svc: h3=":443"; ma=86400
cf-cache-status: HIT
accept-ranges: bytes
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=21fk6BxX2Rh72XJnjlNyQuOp6ZfUUWXSIk4klAsowfAZWqctsBSSkyNcmY%2FSXfPPllyZG7eblzA6QEs95jIn9Uno0xfjAsUhDs4ss2N2Uwm5eWsSwrWuTLcgpd9dPJepFTM%3D"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0.01,"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 81d3bbe8299822fb-KBP

mihai@Mihais-Mac-mini ~ % curl -I "https://cdn.jsdelivr.net/cocoa/Specs/e/2/1/FirebaseAnalytics/10.11.0/FirebaseAnalytics.podspec.json" -H 'Accept-Encoding: gzip'
HTTP/2 200 
date: Sat, 28 Oct 2023 14:05:59 GMT
content-type: application/json; charset=utf-8
content-length: 661
access-control-allow-origin: *
access-control-expose-headers: *
timing-allow-origin: *
cache-control: public, max-age=3600
cross-origin-resource-policy: cross-origin
x-content-type-options: nosniff
strict-transport-security: max-age=31536000; includeSubDomains; preload
etag: W/"6dc-bGv5nohUR1vx+jQgKIQb6OzSNto"
content-encoding: gzip
x-served-by: cache-fra-eddf8230133-FRA, cache-yyz4583-YYZ
x-cache: HIT, HIT
```

**Comment by giorgio79** [comment]
dupe of https://github.com/CocoaPods/CocoaPods/issues/12115

**Comment by shinewanna** [comment]
+1, Having same issue on m1 pro machine after update my machine to Sonoma 14.0.

`JSON::ParserError - Failed to parse JSON at file: '/Users/shine/.cocoapods/repos/trunk/Specs/e/3/b/GoogleAppMeasurement/10.16.0/GoogleAppMeasurement.podspec.json'.`

**Comment by shinewanna** [comment]
`JSON::ParserError - Failed to parse JSON at file: '/Users/shine/.cocoapods/repos/trunk/Specs/e/3/b/GoogleAppMeasurement/10.16.0/GoogleAppMeasurement.podspec.json'.`

I'm able to troubleshoot with the following way. In my case, it is failing on parsing this(**GoogleAppMeasurement.podspec.json**) json file. So, I've checked that file in my machine and I found out that file has nothing inside, so something is wrong while downloading the code or json. To troubleshoot that we need to find our missing files in CocoaPods Github project. Here is the link for my missing file in CocoaPods Github project [https://github.com/CocoaPods/Specs/tree/master/Specs/e/3/b/GoogleAppMeasurement/10.16.0](https://github.com/CocoaPods/Specs/tree/master/Specs/e/3/b/GoogleAppMeasurement/10.16.0). Copy the json code from there and paste it in your project's file and pod install again and run again. It worked for me.

**Comment by ikevin127** [comment]
Confirm that using VPN with USA ip fixes the issue.
I'm on a mac and I used **Urban VPN Desktop** from AppStore because it's free.

**Comment by PAVUNRAJ** [comment]
> @VestaCute could you please try to remove trunk repo and try again?
> 
> ```
> rm -rf ~/.cocoapods/repos/trunk
> ```

I used the command its working for me, MacBook Air M1 chip
