### ISSUE TITLE
Spec Linting Fails when test_specs are added

### ISSUE THREAD

**Issue by omaRaad** [CocoaPods/CocoaPods#12139]
🌈   
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

I added one Unit **test_spec** and one UI **test_spec** to the PodSpec. Testing everything manually, they all work. The Tests succeed. However, spec linting fails.

### Worth to know

1. If I comment out the **test_specs**, linting works fine. If I comment only one **test_spec** and leave the other, it still does the same regardless of which **test_spec**
2. The UI **test_spec** is run on an **app_spec**. This spec doesn't have a default Main Storyboard, so after I run `pod install`, I have to assign the it manually(no idea how to assign it from the PodSpec file). 
3. Running `pod lib lint` doesn't  give the same error as `pod spec lint`. It seems to work fine, but UI Tests fail. I am assuming because of point (2) above.

## What did you do?

Add **test_specs** to the PodSpec file. Run `pod spec lint --verbose`

## What did you expect to happen?

Validation Succeeds. And therefore the `trunk push` shall succeed as well.

## What happened instead?

Validation Failed with error:  
```
 CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local
  because checking is only performed in repo update
    BitLabs (3.1.9) - Analyzing on iOS 11.0 platform.
  - Generating Info.plist file at
  `../../../../var/folders/j2/vl81r6c96f986cc4vmpdrcn00000gn/T/CocoaPods-Lint-20231103-96750-1htifqf-BitLabs/App/App-Info.plist`
  Preparing

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-App`: (``)

Fetching external sources
-> Fetching podspec for `BitLabs` from `/Users/omaraad/XCode/bitlabs-ios-sdk/BitLabs.podspec`

Resolving dependencies of 
  CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path: all_pods_versions_d_a_2.txt exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path: Specs/d/a/2/Alamofire/5.8.0/Alamofire.podspec.json
  exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path: all_pods_versions_2_8_b.txt exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/9.1.0/OHHTTPStubs.podspec.json exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/1.0.1/OHHTTPStubs.podspec.json exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/1.1.0/OHHTTPStubs.podspec.json exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/1.1.1/OHHTTPStubs.podspec.json exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/1.1.2/OHHTTPStubs.podspec.json exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/1.2.0/OHHTTPStubs.podspec.json exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/1.2.1/OHHTTPStubs.podspec.json exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/1.2.2/OHHTTPStubs.podspec.json exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/2.0.0/OHHTTPStubs.podspec.json exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/2.1.0-RC/OHHTTPStubs.podspec.json exists! Returning
  local because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/2.1.0-rc.1/OHHTTPStubs.podspec.json exists! Returning
  local because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/2.2.0-RC/OHHTTPStubs.podspec.json exists! Returning
  local because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/2.2.1-RC/OHHTTPStubs.podspec.json exists! Returning
  local because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/2.2.1/OHHTTPStubs.podspec.json exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/2.3.0/OHHTTPStubs.podspec.json exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/2.3.1/OHHTTPStubs.podspec.json exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/2.4.0/OHHTTPStubs.podspec.json exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/3.0.0/OHHTTPStubs.podspec.json exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/3.0.1/OHHTTPStubs.podspec.json exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/3.0.2/OHHTTPStubs.podspec.json exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/3.0.3/OHHTTPStubs.podspec.json exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/3.0.4/OHHTTPStubs.podspec.json exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/3.1.0/OHHTTPStubs.podspec.json exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/3.1.1/OHHTTPStubs.podspec.json exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/3.1.2/OHHTTPStubs.podspec.json exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/3.1.3/OHHTTPStubs.podspec.json exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/3.1.4/OHHTTPStubs.podspec.json exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/3.1.5/OHHTTPStubs.podspec.json exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/3.1.6/OHHTTPStubs.podspec.json exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/3.1.7/OHHTTPStubs.podspec.json exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/3.1.8/OHHTTPStubs.podspec.json exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/3.1.9/OHHTTPStubs.podspec.json exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/3.1.10/OHHTTPStubs.podspec.json exists! Returning
  local because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/3.1.11/OHHTTPStubs.podspec.json exists! Returning
  local because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/3.1.12/OHHTTPStubs.podspec.json exists! Returning
  local because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/4.0.0/OHHTTPStubs.podspec.json exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/4.0.1/OHHTTPStubs.podspec.json exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/4.0.2/OHHTTPStubs.podspec.json exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/4.1.0/OHHTTPStubs.podspec.json exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/4.2.0/OHHTTPStubs.podspec.json exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/4.2.1/OHHTTPStubs.podspec.json exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/4.3.0/OHHTTPStubs.podspec.json exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/4.4.0/OHHTTPStubs.podspec.json exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/4.5.0/OHHTTPStubs.podspec.json exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/4.5.1/OHHTTPStubs.podspec.json exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/4.6.0/OHHTTPStubs.podspec.json exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/4.7.0/OHHTTPStubs.podspec.json exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/4.7.1/OHHTTPStubs.podspec.json exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/4.8.0/OHHTTPStubs.podspec.json exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/5.0.0/OHHTTPStubs.podspec.json exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/5.1.0/OHHTTPStubs.podspec.json exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/5.2.0/OHHTTPStubs.podspec.json exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/5.2.1/OHHTTPStubs.podspec.json exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/5.2.2/OHHTTPStubs.podspec.json exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/5.2.3/OHHTTPStubs.podspec.json exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/6.0.0/OHHTTPStubs.podspec.json exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/6.1.0/OHHTTPStubs.podspec.json exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/6.2.0/OHHTTPStubs.podspec.json exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/7.0.0/OHHTTPStubs.podspec.json exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/8.0.0/OHHTTPStubs.podspec.json exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/9.0.0/OHHTTPStubs.podspec.json exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/9.1.0/OHHTTPStubs.podspec.json exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path: Specs/d/a/2/Alamofire/5.8.0/Alamofire.podspec.json
  exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path: Specs/d/a/2/Alamofire/5.7.1/Alamofire.podspec.json
  exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path: Specs/d/a/2/Alamofire/5.7.0/Alamofire.podspec.json
  exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path: Specs/d/a/2/Alamofire/5.6.4/Alamofire.podspec.json
  exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path: Specs/d/a/2/Alamofire/5.6.3/Alamofire.podspec.json
  exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path: Specs/d/a/2/Alamofire/5.6.2/Alamofire.podspec.json
  exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path: Specs/d/a/2/Alamofire/5.6.1/Alamofire.podspec.json
  exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path: Specs/d/a/2/Alamofire/5.6.0/Alamofire.podspec.json
  exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path: Specs/d/a/2/Alamofire/5.5.0/Alamofire.podspec.json
  exists! Returning local because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/9.1.0/OHHTTPStubs.podspec.json exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/9.1.0/OHHTTPStubs.podspec.json exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/9.1.0/OHHTTPStubs.podspec.json exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/9.1.0/OHHTTPStubs.podspec.json exists! Returning local
  because checking is only performed in repo update
  CDN: trunk Relative path:
  Specs/2/8/b/OHHTTPStubs/9.1.0/OHHTTPStubs.podspec.json exists! Returning local
  because checking is only performed in repo update

Comparing resolved specification to the sandbox manifest
  A Alamofire
  A BitLabs
  A OHHTTPStubs

Downloading dependencies

-> Installing Alamofire (5.8.0)
  > Copying Alamofire from
  `/Users/omaraad/Library/Caches/CocoaPods/Pods/Release/Alamofire/5.8.0-0e92e`
  to
  `../../../../private/var/folders/j2/vl81r6c96f986cc4vmpdrcn00000gn/T/CocoaPods-Lint-20231103-96750-1htifqf-BitLabs/Pods/Alamofire`

-> Installing BitLabs (3.1.9)
  > Copying BitLabs from
  `/Users/omaraad/Library/Caches/CocoaPods/Pods/External/BitLabs/9f7bb52e300534146668f1a4ad801343-2f9d3`
  to
  `../../../../private/var/folders/j2/vl81r6c96f986cc4vmpdrcn00000gn/T/CocoaPods-Lint-20231103-96750-1htifqf-BitLabs/Pods/BitLabs`

-> Installing OHHTTPStubs (9.1.0)
  > Copying OHHTTPStubs from
  `/Users/omaraad/Library/Caches/CocoaPods/Pods/Release/OHHTTPStubs/9.1.0-90eac`
  to
  `../../../../private/var/folders/j2/vl81r6c96f986cc4vmpdrcn00000gn/T/CocoaPods-Lint-20231103-96750-1htifqf-BitLabs/Pods/OHHTTPStubs`
  - Running pre install hooks
  - Writing Lockfile in
  `../../../../var/folders/j2/vl81r6c96f986cc4vmpdrcn00000gn/T/CocoaPods-Lint-20231103-96750-1htifqf-BitLabs/Podfile.lock`
  - Writing Manifest in
  `../../../../private/var/folders/j2/vl81r6c96f986cc4vmpdrcn00000gn/T/CocoaPods-Lint-20231103-96750-1htifqf-BitLabs/Pods/Manifest.lock`

Generating Pods project
  - Creating Pods project
  - Installing files into Pods project
    - Adding source files
    - Adding frameworks
    - Adding libraries
    - Adding resources
    - Linking headers
  - Installing Pod Targets
    - Installing target `Alamofire` iOS 10.0
      - Generating module map file at
      `../../../../private/var/folders/j2/vl81r6c96f986cc4vmpdrcn00000gn/T/CocoaPods-Lint-20231103-96750-1htifqf-BitLabs/Pods/Target
      Support Files/Alamofire/Alamofire.modulemap`
      - Generating umbrella header at
      `../../../../private/var/folders/j2/vl81r6c96f986cc4vmpdrcn00000gn/T/CocoaPods-Lint-20231103-96750-1htifqf-BitLabs/Pods/Target
      Support Files/Alamofire/Alamofire-umbrella.h`
      - Generating Info.plist file at
      `../../../../private/var/folders/j2/vl81r6c96f986cc4vmpdrcn00000gn/T/CocoaPods-Lint-20231103-96750-1htifqf-BitLabs/Pods/Target
      Support Files/Alamofire/Alamofire-Info.plist`
      - Generating dummy source at
      `../../../../private/var/folders/j2/vl81r6c96f986cc4vmpdrcn00000gn/T/CocoaPods-Lint-20231103-96750-1htifqf-BitLabs/Pods/Target
      Support Files/Alamofire/Alamofire-dummy.m`
    - Installing target `BitLabs` iOS 11.0
      - Generating Info.plist file at
      `../../../../private/var/folders/j2/vl81r6c96f986cc4vmpdrcn00000gn/T/CocoaPods-Lint-20231103-96750-1htifqf-BitLabs/Pods/Target
      Support Files/BitLabs/BitLabs-UI-UITests-Info.plist`
      - Generating Info.plist file at
      `../../../../private/var/folders/j2/vl81r6c96f986cc4vmpdrcn00000gn/T/CocoaPods-Lint-20231103-96750-1htifqf-BitLabs/Pods/Target
      Support Files/BitLabs/BitLabs-Unit-UnitTests-Info.plist`
      - Generating Info.plist file at
      `../../../../private/var/folders/j2/vl81r6c96f986cc4vmpdrcn00000gn/T/CocoaPods-Lint-20231103-96750-1htifqf-BitLabs/Pods/AppHost/BitLabs-AppHost-Info.plist`
 -> BitLabs (3.1.9)
    - ERROR | [iOS] unknown: Encountered an unknown error (Unable to install the `BitLabs` pod, because the `BitLabs-UI-UITests` target in Xcode would have no sources to compile.
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:1159:in `block in validate_targets_contain_sources'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:1157:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:1157:in `validate_targets_contain_sources'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:66:in `block in install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/user_interface.rb:149:in `message'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:40:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:115:in `block in install_pod_targets'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:112:in `map'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:112:in `install_pod_targets'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/installer/xcode/single_pods_project_generator.rb:32:in `block in install_all_pod_targets'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/user_interface.rb:149:in `message'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/installer/xcode/single_pods_project_generator.rb:31:in `install_all_pod_targets'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/installer/xcode/single_pods_project_generator.rb:19:in `generate!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:320:in `block in create_and_save_projects'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:315:in `create_and_save_projects'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:307:in `generate_pods_project'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/validator.rb:633:in `block in install_pod'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/validator.rb:633:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/validator.rb:633:in `install_pod'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/validator.rb:404:in `block in perform_extensive_analysis'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/validator.rb:396:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/validator.rb:396:in `perform_extensive_analysis'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/validator.rb:129:in `validate'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/command/spec/lint.rb:90:in `block in run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/command/spec/lint.rb:71:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/command/spec/lint.rb:71:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
) during validation.

Analyzed 1 podspec.

[!] The spec did not pass validation, due to 1 error.

/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/command/spec/lint.rb:107:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.12.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

### Stack

```
   CocoaPods : 1.12.1
        Ruby : ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.arm64e-darwin21]
    RubyGems : 3.0.3.1
        Host : macOS 12.2.1 (21D62)
       Xcode : 13.3.1 (13E500a)
         Git : git version 2.32.0 (Apple Git-132)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

## Project that demonstrates the issue

You can find the same project I work on [here](https://github.com/BitBurst-GmbH/bitlabs-ios-sdk/tree/feature/pro-549-unit-testing).

**Comment by omaRaad** [comment]
Any Idea about this?

**Comment by omaRaad** [comment]
I posted the question in [StackOverflow](https://stackoverflow.com/questions/77556058/spec-linting-fails-when-test-specs-are-added) and found the solution.

I assumed that `pod spec lint` is run creating a new release, because creating a new release would entail that everything works. Alas, I was wrong, as `pod spec lint` checks for the files in the repo.

So, the solution is to release a new version(with a new tag version equals to that in the Podspec file) which includes the test files.
