### ISSUE TITLE
Errno::EACCES - Permission denied @ rb_sysopen - /Users/luojx/crossEndPro/AwesomeProject/ios/AwesomeProject.xcodeproj/project.pbxproj

### ISSUE THREAD

**Issue by ujfjntevtee28230** [CocoaPods/CocoaPods#12153]
### Error

```
Errno::EACCES - Permission denied @ rb_sysopen - /Users/luojx/crossEndPro/AwesomeProject/ios/AwesomeProject.xcodeproj/project.pbxproj
/opt/homebrew/lib/ruby/gems/3.2.0/gems/xcodeproj-1.23.0/lib/xcodeproj/plist.rb:19:in `read'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/xcodeproj-1.23.0/lib/xcodeproj/plist.rb:19:in `read_from_path'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/xcodeproj-1.23.0/lib/xcodeproj/project.rb:211:in `initialize_from_file'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/xcodeproj-1.23.0/lib/xcodeproj/project.rb:113:in `open'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.2/lib/cocoapods/installer/analyzer.rb:1194:in `block (2 levels) in inspect_targets_to_integrate'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.2/lib/cocoapods/installer/analyzer.rb:1193:in `each'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.2/lib/cocoapods/installer/analyzer.rb:1193:in `block in inspect_targets_to_integrate'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.2/lib/cocoapods/user_interface.rb:64:in `section'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.2/lib/cocoapods/installer/analyzer.rb:1188:in `inspect_targets_to_integrate'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.2/lib/cocoapods/installer/analyzer.rb:107:in `analyze'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.2/lib/cocoapods/installer.rb:422:in `analyze'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.2/lib/cocoapods/installer.rb:244:in `block in resolve_dependencies'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.2/lib/cocoapods/user_interface.rb:64:in `section'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.2/lib/cocoapods/installer.rb:243:in `resolve_dependencies'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.2/lib/cocoapods/installer.rb:162:in `install!'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.2/lib/cocoapods/command/install.rb:52:in `run'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.2/lib/cocoapods/command.rb:52:in `run'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:25:in `load'
/usr/local/bin/pod:25:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.
### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.14.2
        Ruby : ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin22]
    RubyGems : 3.4.10
        Host : macOS 13.5.1 (22G90)
       Xcode : 15.0.1 (15A507)
         Git : git version 2.42.1
Ruby lib dir : /opt/homebrew/Cellar/ruby/3.2.2_1/lib
Repositories : master - git - https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git @ f4e83d4a80c347900a1f8740e64933eaef082a38

               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git';
# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

**Comment by orta** [comment]
Work from the error: `Errno::EACCES - Permission denied @ rb_sysopen` - you have a permissions issue

**Comment by mic-automed** [comment]
NO SHIT there is a permission issue - the question is WHY??? WHY does cocoapods NEED TO BE RUN AS ROOT in order to not have this error??
