### ISSUE TITLE
Cocoapods Error when I run: pod search realm

### ISSUE THREAD

**Issue by cyrex81** [CocoaPods/CocoaPods#12161]
Creating search index for spec repo 'cocoapods'.. Done!

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/bin/pod search realm
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.14.2
        Ruby : ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin22]
    RubyGems : 3.4.10
        Host : macOS 13.5.1 (22G90)
       Xcode : 15.0.1 (15A507)
         Git : git version 2.39.3 (Apple Git-145)
Ruby lib dir : /opt/homebrew/Cellar/ruby/3.2.2_1/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs @ 3fd9dc0228a2bab832fd1a074341cf689d9808e8

               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Error

```
NoMethodError - undefined method `=~' for ["christophe.azemar@orange.com", "francois.suc@orange.com"]:Array
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-core-1.14.2/lib/cocoapods-core/source/manager.rb:128:in `block (3 levels) in search_by_name'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-core-1.14.2/lib/cocoapods-core/source/manager.rb:126:in `each'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-core-1.14.2/lib/cocoapods-core/source/manager.rb:126:in `block (2 levels) in search_by_name'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-core-1.14.2/lib/cocoapods-core/source/manager.rb:125:in `each_pair'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-core-1.14.2/lib/cocoapods-core/source/manager.rb:125:in `block in search_by_name'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-core-1.14.2/lib/cocoapods-core/source/manager.rb:124:in `each_value'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-core-1.14.2/lib/cocoapods-core/source/manager.rb:124:in `search_by_name'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-search-1.0.1/lib/cocoapods-search/command/search.rb:87:in `local_search'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-search-1.0.1/lib/cocoapods-search/command/search.rb:63:in `run'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-1.14.2/lib/cocoapods/command.rb:52:in `run'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/gems/cocoapods-1.14.2/bin/pod:55:in `<top (required)>'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/bin/pod:25:in `load'
/opt/homebrew/Cellar/cocoapods/1.14.2/libexec/bin/pod:25:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=undefined+method+%60%3D~%27+for+%5B%22christophe.azemar%40orange.com%22%2C+%22francois.suc%40orange.com%22%5D%3AArray&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Found no similar issues. To create a new issue, please visit:
https://github.com/cocoapods/cocoapods/issues/new

**Comment by iNewOne** [comment]
Did you find a solution for this?
