### ISSUE TITLE
Undefined method files for PBXFileReference path=Pods OSX

### ISSUE THREAD

**Issue by freeone3000** [CocoaPods/CocoaPods#12197]
### Command

```
/opt/homebrew/opt/ruby/bin/pod install
```

### Report

* What did you do?
    1. Created a podfile with the contents:
    ```ruby
use_frameworks!

platform :ios, '17.2'
 
target 'Agendum' do
  pod 'MSAL'
end
```
   2. Ran `pod install`

* What did you expect to happen?
For MSAL to be installed as a dependency of my project

* What happened instead?
The following error happened instead.

### Stack

```
   CocoaPods : 1.14.3
        Ruby : ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin23]
    RubyGems : 3.5.3
        Host : macOS 14.2.1 (23C71)
       Xcode :  ()
         Git : git version 2.39.3 (Apple Git-145)
Ruby lib dir : /opt/homebrew/Cellar/ruby/3.2.2_1/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
use_frameworks!

platform :ios, '11.0'
 
target 'Agendum' do
  pod 'MSAL'
end
```

### Error

```
NoMethodError - undefined method `files' for <PBXFileReference path=`Pods` UUID=`DC1B91E52B3C15160094040E`>:Xcodeproj::Project::Object::PBXFileReference
/Users/jasmine/.gem/ruby/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:165:in `create_xcconfig_ref'
/Users/jasmine/.gem/ruby/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:45:in `set_target_xcconfig'
/Users/jasmine/.gem/ruby/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:21:in `block (2 levels) in integrate'
/Users/jasmine/.gem/ruby/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:20:in `each'
/Users/jasmine/.gem/ruby/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:20:in `block in integrate'
/Users/jasmine/.gem/ruby/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:19:in `each'
/Users/jasmine/.gem/ruby/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:19:in `integrate'
/Users/jasmine/.gem/ruby/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/installer/user_project_integrator/target_integrator.rb:561:in `block in integrate!'
/Users/jasmine/.gem/ruby/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/user_interface.rb:64:in `section'
/Users/jasmine/.gem/ruby/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/installer/user_project_integrator/target_integrator.rb:560:in `integrate!'
/Users/jasmine/.gem/ruby/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/installer/user_project_integrator.rb:146:in `each'
/Users/jasmine/.gem/ruby/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/installer/user_project_integrator.rb:146:in `integrate_user_targets'
/Users/jasmine/.gem/ruby/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/installer/user_project_integrator.rb:73:in `integrate!'
/Users/jasmine/.gem/ruby/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:929:in `block in integrate_user_project'
/Users/jasmine/.gem/ruby/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/user_interface.rb:64:in `section'
/Users/jasmine/.gem/ruby/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:925:in `integrate_user_project'
/Users/jasmine/.gem/ruby/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:185:in `integrate'
/Users/jasmine/.gem/ruby/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:170:in `install!'
/Users/jasmine/.gem/ruby/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/command/install.rb:52:in `run'
/Users/jasmine/.gem/ruby/3.2.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Users/jasmine/.gem/ruby/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/command.rb:52:in `run'
/Users/jasmine/.gem/ruby/3.2.0/gems/cocoapods-1.14.3/bin/pod:55:in `<top (required)>'
/opt/homebrew/opt/ruby/bin/pod:25:in `load'
/opt/homebrew/opt/ruby/bin/pod:25:in `<main>'
```

**Comment by freeone3000** [comment]
nope! I moved the project to flutter.
