### ISSUE TITLE
Error while running application in iOS

### ISSUE THREAD

**Issue by oza-27** [CocoaPods/CocoaPods#12200]
### Command

```
/Users/revords/.rbenv/versions/3.2.2/bin/pod update
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.14.3
        Ruby : ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin23]
    RubyGems : 3.5.3
        Host : macOS 14.1.2 (23B92)
       Xcode : 15.1 (15C65)
         Git : git version 2.39.3 (Apple Git-145)
Ruby lib dir : /Users/revords/.rbenv/versions/3.2.2/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

ENV['RCT_NEW_ARCH_ENABLED'] = podfile_properties['newArchEnabled'] == 'true' ? '1' : '0'
ENV['EX_DEV_CLIENT_NETWORK_INSPECTOR'] = podfile_properties['EX_DEV_CLIENT_NETWORK_INSPECTOR']

platform :ios, podfile_properties['ios.deploymentTarget'] || '13.0'
install! 'cocoapods',
  :deterministic_uuids => false

prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...), which will be excluded. To fix this,
# you can also exclude `react-native-flipper` in `react-native.config.js`
#
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
#   }
# }
# ```
flipper_config = FlipperConfiguration.disabled
if ENV['NO_FLIPPER'] == '1' then
  # Explicitly disabled through environment variables
  flipper_config = FlipperConfiguration.disabled
elsif podfile_properties.key?('ios.flipper') then
  # Configure Flipper in Podfile.properties.json
  if podfile_properties['ios.flipper'] == 'true' then
    flipper_config = FlipperConfiguration.enabled(["Debug", "Release"])
  elsif podfile_properties['ios.flipper'] != 'false' then
    flipper_config = FlipperConfiguration.enabled(["Debug", "Release"], { 'Flipper' => podfile_properties['ios.flipper'] })
  end
end

target 'myapp' do
  use_expo_modules!
  config = use_native_modules!

  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
  use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym if ENV['USE_FRAMEWORKS']

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'] == nil || podfile_properties['expo.jsEngine'] == 'hermes',
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    # Note that if you have use_frameworks! enabled, Flipper will not work if enabled
    :flipper_configuration => flipper_config
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)

    # This is necessary for Xcode 14, because it signs resource bundles by default
    # when building for devices.
    installer.target_installation_results.pod_target_installation_results
      .each do |pod_name, target_installation_result|
      target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
        resource_bundle_target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
  end

  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end
end
```

### Error

```
LoadError - dlopen(/Users/revords/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/ffi-1.16.3/lib/ffi_c.bundle, 0x0009): tried: '/Users/revords/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/ffi-1.16.3/lib/ffi_c.bundle' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/revords/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/ffi-1.16.3/lib/ffi_c.bundle' (no such file), '/Users/revords/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/ffi-1.16.3/lib/ffi_c.bundle' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')) - /Users/revords/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/ffi-1.16.3/lib/ffi_c.bundle
<internal:/Users/revords/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
<internal:/Users/revords/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
/Users/revords/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/ffi-1.16.3/lib/ffi.rb:5:in `rescue in <top (required)>'
/Users/revords/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/ffi-1.16.3/lib/ffi.rb:2:in `<top (required)>'
<internal:/Users/revords/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
<internal:/Users/revords/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
/Users/revords/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/ethon-0.16.0/lib/ethon.rb:3:in `<top (required)>'
<internal:/Users/revords/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
<internal:/Users/revords/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
/Users/revords/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/typhoeus-1.4.1/lib/typhoeus.rb:2:in `<top (required)>'
<internal:/Users/revords/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
<internal:/Users/revords/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
/Users/revords/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-core-1.14.3/lib/cocoapods-core/cdn_source.rb:440:in `download_typhoeus_impl_async'
/Users/revords/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-core-1.14.3/lib/cocoapods-core/cdn_source.rb:372:in `download_and_save_with_retries_async'
/Users/revords/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-core-1.14.3/lib/cocoapods-core/cdn_source.rb:365:in `download_file_async'
/Users/revords/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-core-1.14.3/lib/cocoapods-core/cdn_source.rb:338:in `download_file'
/Users/revords/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-core-1.14.3/lib/cocoapods-core/cdn_source.rb:78:in `deprecated_local_podspecs'
/Users/revords/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-core-1.14.3/lib/cocoapods-core/cdn_source.rb:60:in `preheat_existing_files'
/Users/revords/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-core-1.14.3/lib/cocoapods-core/cdn_source.rb:257:in `update'
/Users/revords/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/sources_manager.rb:144:in `block (3 levels) in update'
/Users/revords/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/user_interface.rb:64:in `section'
/Users/revords/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/sources_manager.rb:143:in `block (2 levels) in update'
/Users/revords/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/sources_manager.rb:142:in `each'
/Users/revords/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/sources_manager.rb:142:in `block in update'
/Users/revords/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/sources_manager.rb:140:in `open'
/Users/revords/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/sources_manager.rb:140:in `update'
/Users/revords/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/installer/analyzer.rb:146:in `block in update_repositories'
/Users/revords/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/installer/analyzer.rb:144:in `each'
/Users/revords/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/installer/analyzer.rb:144:in `update_repositories'
/Users/revords/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:240:in `block in resolve_dependencies'
/Users/revords/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/user_interface.rb:64:in `section'
/Users/revords/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:239:in `resolve_dependencies'
/Users/revords/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:162:in `install!'
/Users/revords/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/command/update.rb:63:in `run'
/Users/revords/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Users/revords/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/command.rb:52:in `run'
/Users/revords/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/bin/pod:55:in `<top (required)>'
/Users/revords/.rbenv/versions/3.2.2/bin/pod:25:in `load'
/Users/revords/.rbenv/versions/3.2.2/bin/pod:25:in `<main>'
```

**Comment by orta** [comment]
I'd recommend following internet searches for 

> (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')),

This is about your local setup, not CocoaPods
