### ISSUE TITLE
Error on pod install or pod update (Flutter related maybe?)

### ISSUE THREAD

**Issue by blk-raffy** [CocoaPods/CocoaPods#12221]
### Command

```
/opt/homebrew/opt/ruby/bin/pod update
```

### Report

* What did you do?
Running pod install to build a flutter app

* What did you expect to happen?
just to work (?)

* What happened instead?
"On no, an error occurred"

### Stack

```
   CocoaPods : 1.14.3
        Ruby : ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin22]
    RubyGems : 3.4.22
        Host : macOS 14.3 (23D56)
       Xcode : 15.0.1 (15A507)
         Git : git version 2.40.1
Ruby lib dir : /opt/homebrew/Cellar/ruby/3.2.2_1/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ 23576355fb1cd826d24e310698528c43d0eb66ea

               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end
```

### Error

```
LoadError - dlopen(/opt/homebrew/lib/ruby/gems/3.2.0/gems/ffi-1.16.3/lib/ffi_c.bundle, 0x0009): tried: '/opt/homebrew/lib/ruby/gems/3.2.0/gems/ffi-1.16.3/lib/ffi_c.bundle' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/ruby/gems/3.2.0/gems/ffi-1.16.3/lib/ffi_c.bundle' (no such file), '/opt/homebrew/lib/ruby/gems/3.2.0/gems/ffi-1.16.3/lib/ffi_c.bundle' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')) - /opt/homebrew/lib/ruby/gems/3.2.0/gems/ffi-1.16.3/lib/ffi_c.bundle
<internal:/opt/homebrew/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
<internal:/opt/homebrew/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/ffi-1.16.3/lib/ffi.rb:5:in `rescue in <top (required)>'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/ffi-1.16.3/lib/ffi.rb:2:in `<top (required)>'
<internal:/opt/homebrew/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
<internal:/opt/homebrew/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/ethon-0.16.0/lib/ethon.rb:3:in `<top (required)>'
<internal:/opt/homebrew/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
<internal:/opt/homebrew/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
<internal:/opt/homebrew/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
<internal:/opt/homebrew/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/cocoapods-core-1.14.3/lib/cocoapods-core/cdn_source.rb:440:in `download_typhoeus_impl_async'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/cocoapods-core-1.14.3/lib/cocoapods-core/cdn_source.rb:372:in `download_and_save_with_retries_async'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/cocoapods-core-1.14.3/lib/cocoapods-core/cdn_source.rb:365:in `download_file_async'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/cocoapods-core-1.14.3/lib/cocoapods-core/cdn_source.rb:338:in `download_file'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/cocoapods-core-1.14.3/lib/cocoapods-core/cdn_source.rb:78:in `deprecated_local_podspecs'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/cocoapods-core-1.14.3/lib/cocoapods-core/cdn_source.rb:60:in `preheat_existing_files'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/cocoapods-core-1.14.3/lib/cocoapods-core/cdn_source.rb:257:in `update'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/sources_manager.rb:144:in `block (3 levels) in update'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/user_interface.rb:64:in `section'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/sources_manager.rb:143:in `block (2 levels) in update'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/sources_manager.rb:142:in `each'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/sources_manager.rb:142:in `block in update'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/sources_manager.rb:140:in `open'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/sources_manager.rb:140:in `update'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/installer/analyzer.rb:146:in `block in update_repositories'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/installer/analyzer.rb:144:in `each'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/installer/analyzer.rb:144:in `update_repositories'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:240:in `block in resolve_dependencies'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/user_interface.rb:64:in `section'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:239:in `resolve_dependencies'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:162:in `install!'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/command/update.rb:63:in `run'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/command.rb:52:in `run'
/opt/homebrew/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/bin/pod:55:in `<top (required)>'
/opt/homebrew/opt/ruby/bin/pod:25:in `load'
/opt/homebrew/opt/ruby/bin/pod:25:in `<main>'
```

**Comment by monfresh** [comment]
This is neither a Flutter nor a Cocoapods issue. This specific error is due to your Mac not having a proper Ruby development setup. Even more specifically, the issue is that the `ffi` gem was installed while your Terminal was using Rosetta (or via the command line with `arch -x86_64`), but Cocoapods and/or Ruby were installed in the native arm64 architecture that Apple Silicon Macs use.

You cannot mix and match architectures! Rosetta (or `arch -x86_64`) is not needed to work with the latest Ruby and Cocoapods.

To fix this, you will need to uninstall everything related to Ruby, and reinstall everything properly. I recommend using a Ruby version manager to install Ruby. I do not recommend installing Ruby or Cocoapods with Homebrew. Here's a [step-by-step guide for installing Ruby on a Mac](https://www.moncefbelyamani.com/how-to-install-xcode-homebrew-git-rvm-ruby-on-mac/).
