### ISSUE TITLE
Pod installation Failed on M3 Chip

### ISSUE THREAD

**Issue by ajsanjay** [CocoaPods/CocoaPods#12220]
――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.14.3
        Ruby : ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [arm64-darwin22]
    RubyGems : 3.5.4
        Host : macOS 13.5 (22G2074)
       Xcode : 15.2 (15C500b)
         Git : git version 2.39.3 (Apple Git-145)
Ruby lib dir : /opt/homebrew/Cellar/ruby/3.3.0/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'GCBProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GCBProject
  
pod 'GoogleMaps'
pod 'GoogleSignIn'
pod "MBCircularProgressBar"
pod 'YYCalendar'
pod 'GooglePlaces'
pod 'Stripe'
pod 'Toast-Swift', '~> 5.0.1'
pod 'SVProgressHUD'
pod 'SDWebImage'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = "13.0"
    end
  end
end

end
```

### Error

```
LoadError - linked to incompatible /Users/jayasabeen/.rvm/rubies/ruby-3.2.0/lib/libruby.3.2.dylib - /Users/jayasabeen/.rvm/rubies/ruby-3.2.0/lib/ruby/gems/3.2.0/gems/ffi-1.16.3/lib/ffi_c.bundle
<internal:/opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
<internal:/opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
/Users/jayasabeen/.rvm/rubies/ruby-3.2.0/lib/ruby/gems/3.2.0/gems/ffi-1.16.3/lib/ffi.rb:5:in `rescue in <top (required)>'
/Users/jayasabeen/.rvm/rubies/ruby-3.2.0/lib/ruby/gems/3.2.0/gems/ffi-1.16.3/lib/ffi.rb:2:in `<top (required)>'
<internal:/opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
<internal:/opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
/opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/ethon-0.16.0/lib/ethon.rb:3:in `<top (required)>'
<internal:/opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
<internal:/opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
/opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/typhoeus-1.4.1/lib/typhoeus.rb:2:in `<top (required)>'
<internal:/opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
<internal:/opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
/opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/cocoapods-core-1.14.3/lib/cocoapods-core/cdn_source.rb:440:in `download_typhoeus_impl_async'
/opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/cocoapods-core-1.14.3/lib/cocoapods-core/cdn_source.rb:372:in `download_and_save_with_retries_async'
/opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/cocoapods-core-1.14.3/lib/cocoapods-core/cdn_source.rb:365:in `download_file_async'
/opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/cocoapods-core-1.14.3/lib/cocoapods-core/cdn_source.rb:338:in `download_file'
/opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/cocoapods-core-1.14.3/lib/cocoapods-core/cdn_source.rb:284:in `ensure_versions_file_loaded'
/opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/cocoapods-core-1.14.3/lib/cocoapods-core/cdn_source.rb:208:in `search'
/opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/cocoapods-core-1.14.3/lib/cocoapods-core/source/aggregate.rb:83:in `block in search'
/opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/cocoapods-core-1.14.3/lib/cocoapods-core/source/aggregate.rb:83:in `select'
/opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/cocoapods-core-1.14.3/lib/cocoapods-core/source/aggregate.rb:83:in `search'
/opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/cocoapods-1.14.3/lib/cocoapods/resolver.rb:416:in `create_set_from_sources'
/opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/cocoapods-1.14.3/lib/cocoapods/resolver.rb:385:in `find_cached_set'
/opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/cocoapods-1.14.3/lib/cocoapods/resolver.rb:360:in `specifications_for_dependency'
/opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/cocoapods-1.14.3/lib/cocoapods/resolver.rb:165:in `search_for'
/opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/cocoapods-1.14.3/lib/cocoapods/resolver.rb:274:in `block in sort_dependencies'
/opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/cocoapods-1.14.3/lib/cocoapods/resolver.rb:267:in `each'
/opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/cocoapods-1.14.3/lib/cocoapods/resolver.rb:267:in `sort_by'
/opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/cocoapods-1.14.3/lib/cocoapods/resolver.rb:267:in `sort_by!'
/opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/cocoapods-1.14.3/lib/cocoapods/resolver.rb:267:in `sort_dependencies'
/opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:60:in `block in sort_dependencies'
/opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:77:in `with_no_such_dependency_error_handling'
/opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:59:in `sort_dependencies'
/opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:754:in `push_state_for_requirements'
/opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:288:in `push_initial_state'
/opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:210:in `start_resolution'
/opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:168:in `resolve'
/opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in `resolve'
/opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/cocoapods-1.14.3/lib/cocoapods/resolver.rb:94:in `resolve'
/opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/cocoapods-1.14.3/lib/cocoapods/installer/analyzer.rb:1082:in `block in resolve_dependencies'
/opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/cocoapods-1.14.3/lib/cocoapods/user_interface.rb:64:in `section'
/opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/cocoapods-1.14.3/lib/cocoapods/installer/analyzer.rb:1080:in `resolve_dependencies'
/opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/cocoapods-1.14.3/lib/cocoapods/installer/analyzer.rb:125:in `analyze'
/opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:422:in `analyze'
/opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:244:in `block in resolve_dependencies'
/opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/cocoapods-1.14.3/lib/cocoapods/user_interface.rb:64:in `section'
/opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:243:in `resolve_dependencies'
/opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:162:in `install!'
/opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/cocoapods-1.14.3/lib/cocoapods/command/install.rb:52:in `run'
/opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/cocoapods-1.14.3/lib/cocoapods/command.rb:52:in `run'
/opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/cocoapods-1.14.3/bin/pod:55:in `<top (required)>'
/opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/bin/pod:25:in `load'
/opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/bin/pod:25:in `<main>'
```

**Comment by monfresh** [comment]
What is the output of this command?

```
file /Users/jayasabeen/.rvm/rubies/ruby-3.2.0/lib/ruby/gems/3.2.0/gems/ffi-1.16.3/lib/ffi_c.bundle
```

**Comment by ajsanjay** [comment]
The contents Below the error is the response

**Comment by ajsanjay** [comment]
```
LoadError - linked to incompatible /Users/jayasabeen/.rvm/rubies/ruby-3.2.0/lib/libruby.3.2.dylib - /Users/jayasabeen/.rvm/rubies/ruby-3.2.0/lib/ruby/gems/3.2.0/gems/ffi-1.16.3/lib/ffi_c.bundle
<internal:/opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
<internal:/opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
/Users/jayasabeen/.rvm/rubies/ruby-3.2.0/lib/ruby/gems/3.2.0/gems/ffi-1.16.3/lib/ffi.rb:5:in `rescue in <top (required)>'
/Users/jayasabeen/.rvm/rubies/ruby-3.2.0/lib/ruby/gems/3.2.0/gems/ffi-1.16.3/lib/ffi.rb:2:in `<top (required)>'
<internal:/opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
<internal:/opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
/opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/ethon-0.16.0/lib/ethon.rb:3:in `<top (required)>'
<internal:/opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
<internal:/opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
/opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/typhoeus-1.4.1/lib/typhoeus.rb:2:in `<top (required)>'
<internal:/opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
<internal:/opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
/Users/jayasabeen/.rvm/rubies/ruby-3.2.0/lib/ruby/gems/3.2.0/gems/cocoapods-core-1.14.3/lib/cocoapods-core/cdn_source.rb:440:in `download_typhoeus_impl_async'
/Users/jayasabeen/.rvm/rubies/ruby-3.2.0/lib/ruby/gems/3.2.0/gems/cocoapods-core-1.14.3/lib/cocoapods-core/cdn_source.rb:372:in `download_and_save_with_retries_async'
/Users/jayasabeen/.rvm/rubies/ruby-3.2.0/lib/ruby/gems/3.2.0/gems/cocoapods-core-1.14.3/lib/cocoapods-core/cdn_source.rb:365:in `download_file_async'
/Users/jayasabeen/.rvm/rubies/ruby-3.2.0/lib/ruby/gems/3.2.0/gems/cocoapods-core-1.14.3/lib/cocoapods-core/cdn_source.rb:338:in `download_file'
/Users/jayasabeen/.rvm/rubies/ruby-3.2.0/lib/ruby/gems/3.2.0/gems/cocoapods-core-1.14.3/lib/cocoapods-core/cdn_source.rb:284:in `ensure_versions_file_loaded'
/Users/jayasabeen/.rvm/rubies/ruby-3.2.0/lib/ruby/gems/3.2.0/gems/cocoapods-core-1.14.3/lib/cocoapods-core/cdn_source.rb:208:in `search'
/Users/jayasabeen/.rvm/rubies/ruby-3.2.0/lib/ruby/gems/3.2.0/gems/cocoapods-core-1.14.3/lib/cocoapods-core/source/aggregate.rb:83:in `block in search'
/Users/jayasabeen/.rvm/rubies/ruby-3.2.0/lib/ruby/gems/3.2.0/gems/cocoapods-core-1.14.3/lib/cocoapods-core/source/aggregate.rb:83:in `select'
/Users/jayasabeen/.rvm/rubies/ruby-3.2.0/lib/ruby/gems/3.2.0/gems/cocoapods-core-1.14.3/lib/cocoapods-core/source/aggregate.rb:83:in `search'
/Users/jayasabeen/.rvm/rubies/ruby-3.2.0/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/resolver.rb:416:in `create_set_from_sources'
/Users/jayasabeen/.rvm/rubies/ruby-3.2.0/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/resolver.rb:385:in `find_cached_set'
/Users/jayasabeen/.rvm/rubies/ruby-3.2.0/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/resolver.rb:360:in `specifications_for_dependency'
/Users/jayasabeen/.rvm/rubies/ruby-3.2.0/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/resolver.rb:165:in `search_for'
/Users/jayasabeen/.rvm/rubies/ruby-3.2.0/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/resolver.rb:274:in `block in sort_dependencies'
/Users/jayasabeen/.rvm/rubies/ruby-3.2.0/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/resolver.rb:267:in `each'
/Users/jayasabeen/.rvm/rubies/ruby-3.2.0/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/resolver.rb:267:in `sort_by'
/Users/jayasabeen/.rvm/rubies/ruby-3.2.0/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/resolver.rb:267:in `sort_by!'
/Users/jayasabeen/.rvm/rubies/ruby-3.2.0/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/resolver.rb:267:in `sort_dependencies'
/opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:60:in `block in sort_dependencies'
/opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:77:in `with_no_such_dependency_error_handling'
/opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:59:in `sort_dependencies'
/opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:754:in `push_state_for_requirements'
/opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:288:in `push_initial_state'
/opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:210:in `start_resolution'
/opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:168:in `resolve'
/opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in `resolve'
/Users/jayasabeen/.rvm/rubies/ruby-3.2.0/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/resolver.rb:94:in `resolve'
/Users/jayasabeen/.rvm/rubies/ruby-3.2.0/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/installer/analyzer.rb:1082:in `block in resolve_dependencies'
/Users/jayasabeen/.rvm/rubies/ruby-3.2.0/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/user_interface.rb:64:in `section'
/Users/jayasabeen/.rvm/rubies/ruby-3.2.0/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/installer/analyzer.rb:1080:in `resolve_dependencies'
/Users/jayasabeen/.rvm/rubies/ruby-3.2.0/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/installer/analyzer.rb:125:in `analyze'
/Users/jayasabeen/.rvm/rubies/ruby-3.2.0/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:422:in `analyze'
/Users/jayasabeen/.rvm/rubies/ruby-3.2.0/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:244:in `block in resolve_dependencies'
/Users/jayasabeen/.rvm/rubies/ruby-3.2.0/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/user_interface.rb:64:in `section'
/Users/jayasabeen/.rvm/rubies/ruby-3.2.0/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:243:in `resolve_dependencies'
/Users/jayasabeen/.rvm/rubies/ruby-3.2.0/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/installer.rb:162:in `install!'
/Users/jayasabeen/.rvm/rubies/ruby-3.2.0/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/command/install.rb:52:in `run'
/opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Users/jayasabeen/.rvm/rubies/ruby-3.2.0/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/lib/cocoapods/command.rb:52:in `run'
/Users/jayasabeen/.rvm/rubies/ruby-3.2.0/lib/ruby/gems/3.2.0/gems/cocoapods-1.14.3/bin/pod:55:in `<top (required)>'
/opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/bin/pod:25:in `load'
/opt/homebrew/Cellar/cocoapods/1.14.3_1/libexec/bin/pod:25:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=linked+to+incompatible+%2FUsers%2Fjayasabeen%2F.rvm%2Frubies%2Fruby-3.2.0%2Flib%2Flibruby.3.2.dylib+-+%2FUsers%2Fjayasabeen%2F.rvm%2Frubies%2Fruby-3.2.0%2Flib%2Fruby%2Fgems%2F3.2.0%2Fgems%2Fffi-1.16.3%2Flib%2Fffi_c.bundle&type=Issues

**Comment by monfresh** [comment]
What I mean is that if you copy and paste this line into your Terminal, and then press return, what is the result?

```
file /Users/jayasabeen/.rvm/rubies/ruby-3.2.0/lib/ruby/gems/3.2.0/gems/ffi-1.16.3/lib/ffi_c.bundle
```

**Comment by monfresh** [comment]
If I had to guess, it will say something like `Mach-O 64-bit executable x86_64` at the end, which means that the `ffi` gem was installed using Rosetta or by adding `arch -x86_64` in the terminal. Do you remember if you installed anything while using Rosetta or with `arch -x86_64`? On an Apple Silicon Mac, you don't need Rosetta or `arch -x86_64` to use newer Ruby versions like 3.2. 

Unfortunately, there is still bad advice out there saying to use Rosetta to install Ruby and/or gems. If you install some things with Rosetta, and other things without, it can cause all kinds of issues, like the one you're seeing. To fix this, you'll need to uninstall everything related to Ruby, then reinstall everything with a clean slate and making sure never to use Rosetta or `arch -x86_64`.

Also, I noticed you installed Cocoapods with Homebrew. I recommend installing it with `gem install cocoapods` while using your desired Ruby version using your preferred version manager (it looks like you're using RVM). Here's a [step-by-step guide for setting up a proper Ruby dev environment on a Mac](https://www.moncefbelyamani.com/how-to-install-xcode-homebrew-git-rvm-ruby-on-mac/).

**Comment by ajsanjay** [comment]
Thanks @monfresh I fixed this by following the step by step guide now pod installation was successful. These are the pages I followed when I got errors from step buy step installation
https://superuser.com/questions/686317/how-to-fully-uninstall-the-cocoapods-from-the-mac-machine
https://stackoverflow.com/questions/64698820/ignoring-ffi-1-13-1-because-its-extensions-are-not-built-try-gem-pristine-ffi
https://stackoverflow.com/questions/53979362/you-dont-have-path-in-your-path-gem-executables-will-not-run-while-using

**Comment by ajsanjay** [comment]
`brew uninstall --force ruby`
Then, uninstalled cocoapods
`brew uninstall --force cocoapods`
`gem pristine ffi --version 1.15.3`
`rm -rf ~/.local`
`brew install cocoapods`
`pod install`

**Comment by onions-ui** [comment]
@ajsanjay  was this issue closed?

**Comment by ajsanjay** [comment]
@mustafa-boorenie Are you still facing the issue

**Comment by ajsanjay** [comment]
brew uninstall --force ruby
Then, uninstalled cocoapods
brew uninstall --force cocoapods
gem pristine ffi --version 1.15.3
rm -rf ~/.local
brew install cocoapods
pod install
