### ISSUE TITLE
[DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead. (Use `node --trace-deprecation ...` to show where the warning was created)

### ISSUE THREAD

**Issue by ankitdnasit** [CocoaPods/CocoaPods#12247]
Framework build type is static library
[Codegen] Generating ./build/generated/ios/React-Codegen.podspec.json
[Codegen] generating an empty RCTThirdPartyFabricComponentsProvider
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
[Codegen] Found FBReactNativeSpec
Fetching podspec for `RCT-Folly` from `../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`
[Codegen] Found rncore
Fetching podspec for `boost` from `../node_modules/react-native/third-party-podspecs/boost.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
Fetching podspec for `hermes-engine` from `../node_modules/react-native/sdks/hermes-engine/hermes-engine.podspec`
[Hermes] Using release tarball from URL: https://repo1.maven.org/maven2/com/facebook/react/react-native-artifacts/0.73.3/react-native-artifacts-0.73.3-hermes-ios-debug.tar.gz
Downloading dependencies
Installing CocoaAsyncSocket (7.6.5)

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.15.0
        Ruby : ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.x86_64-darwin23]
    RubyGems : 3.0.3.1
        Host : macOS 14.3 (23D56)
       Xcode : 15.2 (15C500b)
         Git : git version 2.39.3 (Apple Git-145)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ aca23cf54e4aaae1c947b0a90bbb11535419152f

               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-clean       : 0.0.1
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'MyFirstProject' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'MyFirstProjectTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
```

### Error

```
Errno::EACCES - Permission denied @ apply2files - /Users/mac/Library/Caches/CocoaPods/Pods/External/hermes-engine/b2b1988548902dba4b3f6eb5169320f7-3f423/destroot/include/jsi/jsi-inl.h
/Library/Ruby/Gems/2.6.0/gems/fileutils-1.7.2/lib/fileutils.rb:2330:in `unlink'
/Library/Ruby/Gems/2.6.0/gems/fileutils-1.7.2/lib/fileutils.rb:2330:in `block in remove_file'
/Library/Ruby/Gems/2.6.0/gems/fileutils-1.7.2/lib/fileutils.rb:2335:in `platform_support'
/Library/Ruby/Gems/2.6.0/gems/fileutils-1.7.2/lib/fileutils.rb:2329:in `remove_file'
/Library/Ruby/Gems/2.6.0/gems/fileutils-1.7.2/lib/fileutils.rb:2318:in `remove'
/Library/Ruby/Gems/2.6.0/gems/fileutils-1.7.2/lib/fileutils.rb:1452:in `block in remove_entry'
/Library/Ruby/Gems/2.6.0/gems/fileutils-1.7.2/lib/fileutils.rb:2377:in `block (2 levels) in postorder_traverse'
/Library/Ruby/Gems/2.6.0/gems/fileutils-1.7.2/lib/fileutils.rb:2377:in `block (2 levels) in postorder_traverse'
/Library/Ruby/Gems/2.6.0/gems/fileutils-1.7.2/lib/fileutils.rb:2377:in `block (2 levels) in postorder_traverse'
/Library/Ruby/Gems/2.6.0/gems/fileutils-1.7.2/lib/fileutils.rb:2377:in `block (2 levels) in postorder_traverse'
/Library/Ruby/Gems/2.6.0/gems/fileutils-1.7.2/lib/fileutils.rb:2377:in `block (2 levels) in postorder_traverse'
/Library/Ruby/Gems/2.6.0/gems/fileutils-1.7.2/lib/fileutils.rb:2377:in `block (2 levels) in postorder_traverse'
/Library/Ruby/Gems/2.6.0/gems/fileutils-1.7.2/lib/fileutils.rb:2377:in `block (2 levels) in postorder_traverse'
/Library/Ruby/Gems/2.6.0/gems/fileutils-1.7.2/lib/fileutils.rb:2381:in `postorder_traverse'
/Library/Ruby/Gems/2.6.0/gems/fileutils-1.7.2/lib/fileutils.rb:2376:in `block in postorder_traverse'
/Library/Ruby/Gems/2.6.0/gems/fileutils-1.7.2/lib/fileutils.rb:2375:in `each'
/Library/Ruby/Gems/2.6.0/gems/fileutils-1.7.2/lib/fileutils.rb:2375:in `postorder_traverse'
/Library/Ruby/Gems/2.6.0/gems/fileutils-1.7.2/lib/fileutils.rb:2376:in `block in postorder_traverse'
/Library/Ruby/Gems/2.6.0/gems/fileutils-1.7.2/lib/fileutils.rb:2375:in `each'
/Library/Ruby/Gems/2.6.0/gems/fileutils-1.7.2/lib/fileutils.rb:2375:in `postorder_traverse'
/Library/Ruby/Gems/2.6.0/gems/fileutils-1.7.2/lib/fileutils.rb:2376:in `block in postorder_traverse'
/Library/Ruby/Gems/2.6.0/gems/fileutils-1.7.2/lib/fileutils.rb:2375:in `each'
/Library/Ruby/Gems/2.6.0/gems/fileutils-1.7.2/lib/fileutils.rb:2375:in `postorder_traverse'
/Library/Ruby/Gems/2.6.0/gems/fileutils-1.7.2/lib/fileutils.rb:2376:in `block in postorder_traverse'
/Library/Ruby/Gems/2.6.0/gems/fileutils-1.7.2/lib/fileutils.rb:2375:in `each'
/Library/Ruby/Gems/2.6.0/gems/fileutils-1.7.2/lib/fileutils.rb:2375:in `postorder_traverse'
/Library/Ruby/Gems/2.6.0/gems/fileutils-1.7.2/lib/fileutils.rb:2376:in `block in postorder_traverse'
/Library/Ruby/Gems/2.6.0/gems/fileutils-1.7.2/lib/fileutils.rb:2375:in `each'
/Library/Ruby/Gems/2.6.0/gems/fileutils-1.7.2/lib/fileutils.rb:2375:in `postorder_traverse'
/Library/Ruby/Gems/2.6.0/gems/fileutils-1.7.2/lib/fileutils.rb:2376:in `block in postorder_traverse'
/Library/Ruby/Gems/2.6.0/gems/fileutils-1.7.2/lib/fileutils.rb:2375:in `each'
/Library/Ruby/Gems/2.6.0/gems/fileutils-1.7.2/lib/fileutils.rb:2375:in `postorder_traverse'
/Library/Ruby/Gems/2.6.0/gems/fileutils-1.7.2/lib/fileutils.rb:2376:in `block in postorder_traverse'
/Library/Ruby/Gems/2.6.0/gems/fileutils-1.7.2/lib/fileutils.rb:2375:in `each'
/Library/Ruby/Gems/2.6.0/gems/fileutils-1.7.2/lib/fileutils.rb:2375:in `postorder_traverse'
/Library/Ruby/Gems/2.6.0/gems/fileutils-1.7.2/lib/fileutils.rb:1450:in `remove_entry'
/Library/Ruby/Gems/2.6.0/gems/fileutils-1.7.2/lib/fileutils.rb:1307:in `block in rm_r'
/Library/Ruby/Gems/2.6.0/gems/fileutils-1.7.2/lib/fileutils.rb:1303:in `each'
/Library/Ruby/Gems/2.6.0/gems/fileutils-1.7.2/lib/fileutils.rb:1303:in `rm_r'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/pathname.rb:589:in `rmtree'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.0/lib/cocoapods/downloader/cache.rb:168:in `ensure_matching_version'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.0/lib/cocoapods/downloader/cache.rb:22:in `initialize'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.0/lib/cocoapods/downloader.rb:41:in `new'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.0/lib/cocoapods/downloader.rb:41:in `download'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.0/lib/cocoapods/installer/pod_source_downloader.rb:69:in `download!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.0/lib/cocoapods/installer/pod_source_installer.rb:117:in `download_source'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.0/lib/cocoapods/installer/pod_source_installer.rb:67:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.0/lib/cocoapods/installer.rb:621:in `install_source_of_pod'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.0/lib/cocoapods/installer.rb:539:in `block (2 levels) in install_pod_sources'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.0/lib/cocoapods/user_interface.rb:86:in `titled_section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.0/lib/cocoapods/installer.rb:538:in `block in install_pod_sources'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.0/lib/cocoapods/installer.rb:535:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.0/lib/cocoapods/installer.rb:535:in `install_pod_sources'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.0/lib/cocoapods/installer.rb:258:in `block in download_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.0/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.0/lib/cocoapods/installer.rb:257:in `download_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.0/lib/cocoapods/installer.rb:163:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.0/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.0/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by ankitdnasit** [comment]
If you've installed cocoapods via homebrew then the steps I followed to downgrade to 1.14.3 were

Uninstall version 1.15: brew uninstall cocoapods
Download [this version of cocoapods.rb](https://github.com/Homebrew/homebrew-core/blob/1364b74ebeedb2eab300d62c99e12f2a6f344277/Formula/c/cocoapods.rb) from github
Navigate to the folder you saved that file (e.g. cd ~/Downloads)
brew install using that downloaded file: brew install ./cocoapods.rb
Source: https://stackoverflow.com/questions/58373704/how-do-you-specify-a-version-using-brew-cask
