### ISSUE TITLE
ArgumentError - comparison of NilClass with String failed

### ISSUE THREAD

**Issue by radarcontact** [CocoaPods/CocoaPods#12292]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod install`

## What did you expect to happen?

Install all pod dependencies correctly

## What happened instead?

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/opt/homebrew/Cellar/cocoapods/1.12.1/libexec/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.12.1
        Ruby : ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin22]
    RubyGems : 3.4.10
        Host : macOS 14.2.1 (23C71)
       Xcode : 15.2 (15C500b)
         Git : git version 2.39.3 (Apple Git-145)
Ruby lib dir : /opt/homebrew/Cellar/ruby/3.2.2/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'ShinePay' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for Shine
  pod 'Firebase/Core'
  pod 'AFNetworking', '~> 1.1.0'
  pod 'Stripe', '~> 22.8.4'
  pod 'Firebase/Core'
  pod 'Firebase/Functions'
  pod 'Firebase/Performance'
  pod 'FirebaseCrashlytics'
  pod 'Firebase/Auth'
  pod 'Reachability'
  pod 'Firebase/Database'
  pod 'CardIO'
  pod 'SAMKeychain'
  pod 'Bolts'
  
  


  target 'ShinePayTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ShinePayUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

### Error

```
ArgumentError - comparison of NilClass with String failed
/opt/homebrew/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/installer/analyzer/specs_state.rb:100:in `sort'
/opt/homebrew/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/installer/analyzer/specs_state.rb:100:in `block in lines'
/opt/homebrew/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/installer/analyzer/specs_state.rb:99:in `each'
/opt/homebrew/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/installer/analyzer/specs_state.rb:99:in `flat_map'
/opt/homebrew/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/installer/analyzer/specs_state.rb:99:in `lines'
/opt/homebrew/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/installer/analyzer/specs_state.rb:63:in `print'
/opt/homebrew/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/installer/analyzer.rb:1128:in `block in generate_sandbox_state'
/opt/homebrew/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/user_interface.rb:64:in `section'
/opt/homebrew/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/installer/analyzer.rb:1125:in `generate_sandbox_state'
/opt/homebrew/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/installer/analyzer.rb:129:in `analyze'
/opt/homebrew/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:422:in `analyze'
/opt/homebrew/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:244:in `block in resolve_dependencies'
/opt/homebrew/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/user_interface.rb:64:in `section'
/opt/homebrew/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:243:in `resolve_dependencies'
/opt/homebrew/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:162:in `install!'
/opt/homebrew/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/command/install.rb:52:in `run'
/opt/homebrew/Cellar/cocoapods/1.12.1/libexec/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/opt/homebrew/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/command.rb:52:in `run'
/opt/homebrew/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/bin/pod:55:in `<top (required)>'
/opt/homebrew/Cellar/cocoapods/1.12.1/libexec/bin/pod:25:in `load'
/opt/homebrew/Cellar/cocoapods/1.12.1/libexec/bin/pod:25:in `<main>'
```

――― TEMPLATE END ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Stack

```
   CocoaPods : 1.12.1
        Ruby : ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin22]
    RubyGems : 3.4.10
        Host : macOS 14.2.1 (23C71)
       Xcode : 15.2 (15C500b)
         Git : git version 2.39.3 (Apple Git-145)
Ruby lib dir : /opt/homebrew/Cellar/ruby/3.2.2/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /opt/homebrew/Cellar/cocoapods/1.12.1/libexec/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'ShinePay' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for Shine
  pod 'Firebase/Core'
  pod 'AFNetworking', '~> 1.1.0'
  pod 'Stripe', '~> 22.8.4'
  pod 'Firebase/Core'
  pod 'Firebase/Functions'
  pod 'Firebase/Performance'
  pod 'FirebaseCrashlytics'
  pod 'Firebase/Auth'
  pod 'Reachability'
  pod 'Firebase/Database'
  pod 'CardIO'
  pod 'SAMKeychain'
  pod 'Bolts'
  
  


  target 'ShinePayTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ShinePayUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

## Project that demonstrates the issue

I'd prefer not. It's sensitive. I would have to comb through it to make sure it has no sensitive information. If this is an issue can someone reach out to me?

**Comment by paulb777** [comment]
Updating to a more recent CocoaPods might help. 1.15.2 is the current version

**Comment by radarcontact** [comment]
@paulb777  Is there anyway I could get some additional help from the Firebase team on this? The code buils fine on previous versions of Xcode. But does not build on newer versions of Xcode, 15+. I can't release an app update as a result of this. I think it has something to do with the Firebase SDKs.

**Comment by paulb777** [comment]
@radarcontact The problem described in the original post is a CocoaPods crash and I don't see anything related to Xcode or Firebase versions.

If you have a Firebase issue, it can be reported at https://github.com/firebase/firebase-ios-sdk/issues 

For both CocoaPods and Firebase, you'll likely need to provide a reproducible example to get help.

**Comment by radarcontact** [comment]
@neonichu  Can you help with this?

**Comment by radarcontact** [comment]
@mk  Can you or someone on your team look into this?
