### ISSUE TITLE
Pod command don't find git even if present 

### ISSUE THREAD

**Issue by andreastambazzi** [CocoaPods/CocoaPods#12306]
# Report

## What did you do?

pod install
or
pod --help

or whatelse command with pod i try ...  result is ever the same:

/Users/andreastambazzi/.gem/ruby/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/executable.rb:97:in `expand_path': user Library doesn't exist (ArgumentError)

        bin = File.expand_path(program, path)
                               ^^^^^^^^^^^^^
	from /Users/andreastambazzi/.gem/ruby/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/executable.rb:97:in `block in which'
	from /Users/andreastambazzi/.gem/ruby/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/executable.rb:96:in `each'
	from /Users/andreastambazzi/.gem/ruby/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/executable.rb:96:in `which'
	from /Users/andreastambazzi/.gem/ruby/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/executable.rb:117:in `which!'
	from /Users/andreastambazzi/.gem/ruby/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/executable.rb:143:in `capture_command'
	from /Users/andreastambazzi/.gem/ruby/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:126:in `git_version'
	from /Users/andreastambazzi/.gem/ruby/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:140:in `verify_minimum_git_version!'
	from /Users/andreastambazzi/.gem/ruby/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:49:in `run'
	from /Users/andreastambazzi/.gem/ruby/3.3.0/gems/cocoapods-1.15.2/bin/pod:55:in `<top (required)>'
	from /Users/andreastambazzi/.gem/ruby/3.3.0/bin/pod:25:in `load'
	from /Users/andreastambazzi/.gem/ruby/3.3.0/bin/pod:25:in `<main>'

andreastambazzi@Logos ~ $ which git
/usr/local/bin/git

andreastambazzi@Logos ~ $ git -v
git version 2.44.0

cocoapod seem not found git command even if it is present.

## CocoaPods Environment
I'm unable to see the environment rtesult too cause the pod env command is afflicted by the same issue

andreastambazzi@Logos ~ $ pod env
/Users/andreastambazzi/.gem/ruby/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/executable.rb:97:in `expand_path': user Library doesn't exist (ArgumentError)

        bin = File.expand_path(program, path)
                               ^^^^^^^^^^^^^
	from /Users/andreastambazzi/.gem/ruby/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/executable.rb:97:in `block in which'
	from /Users/andreastambazzi/.gem/ruby/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/executable.rb:96:in `each'
	from /Users/andreastambazzi/.gem/ruby/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/executable.rb:96:in `which'
	from /Users/andreastambazzi/.gem/ruby/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/executable.rb:117:in `which!'
	from /Users/andreastambazzi/.gem/ruby/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/executable.rb:143:in `capture_command'
	from /Users/andreastambazzi/.gem/ruby/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:126:in `git_version'
	from /Users/andreastambazzi/.gem/ruby/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:140:in `verify_minimum_git_version!'
	from /Users/andreastambazzi/.gem/ruby/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:49:in `run'
	from /Users/andreastambazzi/.gem/ruby/3.3.0/gems/cocoapods-1.15.2/bin/pod:55:in `<top (required)>'
	from /Users/andreastambazzi/.gem/ruby/3.3.0/bin/pod:25:in `load'
	from /Users/andreastambazzi/.gem/ruby/3.3.0/bin/pod:25:in `<main>'

i've installed cocoapods with gem install command

gem enviroment is:

andreastambazzi@Logos ~ $ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 3.5.3
  - RUBY VERSION: 3.3.0 (2023-12-25 patchlevel 0) [x86_64-darwin22]
  - INSTALLATION DIRECTORY: /Users/andreastambazzi/.gem/ruby/3.3.0
  - USER INSTALLATION DIRECTORY: /Users/andreastambazzi/.gem/ruby/3.3.0
  - RUBY EXECUTABLE: /Users/andreastambazzi/.rubies/ruby-3.3.0/bin/ruby
  - GIT EXECUTABLE: /usr/local/bin/git
  - EXECUTABLE DIRECTORY: /Users/andreastambazzi/.gem/ruby/3.3.0/bin
  - SPEC CACHE DIRECTORY: /Users/andreastambazzi/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/andreastambazzi/.rubies/ruby-3.3.0/etc
  - RUBYGEMS PLATFORMS:
     - ruby
     - x86_64-darwin-22
  - GEM PATHS:
     - /Users/andreastambazzi/.gem/ruby/3.3.0
     - /Users/andreastambazzi/.rubies/ruby-3.3.0/lib/ruby/gems/3.3.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => true
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/andreastambazzi/work/scripts/
     - ~/Projects/flutter/bin
     - /opt/local/bin
     - /opt/local/sbin
     - /Users/andreastambazzi/.nvm/versions/node/v21.1.0/bin
     - /Users/andreastambazzi/.gem/ruby/3.3.0/bin
     - /Users/andreastambazzi/.rubies/ruby-3.3.0/lib/ruby/gems/3.3.0/bin
     - /Users/andreastambazzi/.rubies/ruby-3.3.0/bin
     - /Users/andreastambazzi/flutter/bin
     - /usr/local/opt/mysql-client/bin/
     - /usr/local/Cellar/maven/3.9.5/bin/
     - ~Library/Python/3.7/bin/
     - /Users/andreastambazzi/.fastlane/bin/
     - /usr/local/bin
     - /System/Cryptexes/App/usr/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /usr/local/share/dotnet
     - ~/.dotnet/tools
     - /Library/Apple/usr/bin
     - /Library/Frameworks/Mono.framework/Versions/Current/Commands
     - /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin
     - /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin
     - /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin
     - /Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin

**Comment by andreastambazzi** [comment]
Hi guys 

anybody have a idea about this issue? 

I have used a trick making a sim link to git command inside the directory where i run pod command ... 
but is a very ugly solution, i think the coccoapods need a fix that implement a search of git comamnd inside the environemt PATH variable.

Please can someone make this fix?

Waiting for a answer i wish you a good work.
