### ISSUE TITLE
CDN: trunk URL couldn't be downloaded

### ISSUE THREAD

**Issue by khoogheem** [CocoaPods/CocoaPods#12304]
Running 1.15.2 via home-brew..

starting to see more and more `CDN: trunk URL couldn't be downloaded` issues..
each time I see this I can open directly in browser without issue.

Remove trunk pointed to CDN.. and redo a pod outdated does seem to clear it up

```
  CDN: trunk Relative path: all_pods_versions_d_c_1.txt modified during this run! Returning local
  CDN: trunk URL couldn't be downloaded:
  https://cdn.cocoapods.org/Specs/d/c/1/FirebaseABTesting/10.22.0/FirebaseABTesting.podspec.json Response:
  Failure when receiving data from the peer, retries: 4
  CDN: trunk URL couldn't be downloaded:
  https://cdn.cocoapods.org/Specs/d/c/1/FirebaseABTesting/10.22.0/FirebaseABTesting.podspec.json Response:
  Failure when receiving data from the peer, retries: 3
  CDN: trunk URL couldn't be downloaded:
  https://cdn.cocoapods.org/Specs/d/c/1/FirebaseABTesting/10.22.0/FirebaseABTesting.podspec.json Response:
  Failure when receiving data from the peer, retries: 2
  CDN: trunk URL couldn't be downloaded:
  https://cdn.cocoapods.org/Specs/d/c/1/FirebaseABTesting/10.22.0/FirebaseABTesting.podspec.json Response:
  Failure when receiving data from the peer, retries: 1
[!] CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/d/c/1/FirebaseABTesting/10.22.0/FirebaseABTesting.podspec.json Response: Failure when receiving data from the peer

/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-core-1.15.2/lib/cocoapods-core/cdn_source.rb:407:in `block in download_and_save_with_retries_async'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/promises.rb:408:in `apply'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/promises.rb:1216:in `apply'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/promises.rb:1740:in `block (2 levels) in on_resolvable'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/promises.rb:1593:in `evaluate_to'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/promises.rb:1740:in `block in on_resolvable'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:359:in `run_task'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:350:in `block (3 levels) in create_worker'
<internal:kernel>:187:in `loop'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:341:in `block (2 levels) in create_worker'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in `catch'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in `block in create_worker'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/promises.rb:1268:in `raise'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/promises.rb:1268:in `wait_until_resolved!'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/promises.rb:988:in `wait!'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-core-1.15.2/lib/cocoapods-core/cdn_source.rb:144:in `block in versions'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-core-1.15.2/lib/cocoapods-core/cdn_source.rb:479:in `concurrent_requests_catching_errors'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-core-1.15.2/lib/cocoapods-core/cdn_source.rb:121:in `versions'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-core-1.15.2/lib/cocoapods-core/specification/set.rb:99:in `block in versions_by_source'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-core-1.15.2/lib/cocoapods-core/specification/set.rb:98:in `each'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-core-1.15.2/lib/cocoapods-core/specification/set.rb:98:in `each_with_object'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-core-1.15.2/lib/cocoapods-core/specification/set.rb:98:in `versions_by_source'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-core-1.15.2/lib/cocoapods-core/specification/set.rb:56:in `specification_name'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-core-1.15.2/lib/cocoapods-core/cdn_source.rb:216:in `search'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-core-1.15.2/lib/cocoapods-core/source/aggregate.rb:83:in `block in search'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-core-1.15.2/lib/cocoapods-core/source/aggregate.rb:83:in `select'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-core-1.15.2/lib/cocoapods-core/source/aggregate.rb:83:in `search'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/command/outdated.rb:119:in `block in spec_sets'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/command/outdated.rb:118:in `map'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/command/outdated.rb:118:in `spec_sets'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/command/outdated.rb:79:in `updates'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/command/outdated.rb:28:in `run'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:52:in `run'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/bin/pod:55:in `<top (required)>'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/bin/pod:25:in `load'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/bin/pod:25:in `<main>'
```

**Comment by 2sem** [comment]
it is solved by removing ~/.cocoapods/repos/trunk/Specs...
and updating Pods

**Comment by stianjensen** [comment]
Seeing the same issue more and more now. On 1.13.0

Is removing the trunk Specs folder just a temporary workaround?

What is the permanent fix for this issue?

**Comment by 2sem** [comment]
pod repo remove cocoapods
is same to remove ~/.cocoapods/repos/trunk/Specs...

**Comment by henrikemota** [comment]
I have exactly the same problem, each time with each frequency. Even removing the trunk
       CocoaPods : 1.15.2
       Ruby : ruby 3.1.4 (2023-12-25 revision 5124f9ac75) [arm64-darwin23]
       Xcode : 14+/ 15+
       Repositories : trunk - CDN - https://cdn.cocoapods.org/

**Comment by pmanuelli** [comment]
I'm also experiencing this error more often.  I'm on cocoapods 1.15.2.

Deleting the specs repo is just a temporary workaround for me. And after deleting it it takes longer for the pod install to complete.

Instead of deleting the entire repo, I use the next command, replacing `PodToRemove` with the name of the pod that fails to download:

`find ~/.cocoapods -type d -name "PodToRemove" -exec rm -rf {} +`

This will find and delete only the pod that fails.

**Comment by KevinColemanInc** [comment]
I updated to 1.15.2 and started experiencing this issue too

**Comment by ignindra** [comment]
I got this as well on the version below:
```
1.16.2 (HomeBrew)
cocoapods-deintegrate: 1.0.5
cocoapods-plugins: 1.0.0
cocoapods-search: 1.0.1
cocoapods-trunk: 1.6.0
cocoapods-try: 1.2.0
```
I managed to 'fix' it by deleting the project's `Podfile.lock` right after executing `pod deintegrate`.

---
I don't think `pod deintegrate` is necessary though.

**Comment by HarelM** [comment]
I'm getting a similar error in my CI when trying to sync capacitor.
It might be related to a recent GitHub changes network traffic, I don't know:
https://github.com/IsraelHikingMap/Site/actions/runs/25791539940/job/75758086396?pr=2512

Looks like it fails due to github 429 too many requests error.
Let me know if there's a need to open a different issue for this.
