### ISSUE TITLE
ERROR | xcodebuild: Returned an unsuccessful exit code

### ISSUE THREAD

**Issue by micky-apester** [CocoaPods/CocoaPods#12308]
# Report

## What did you do?
- run pod install - completed succesfully
- pod cache --clean-all 
-pod lib lint ApesterKit.podspec 
```
 -> ApesterKit (3.3.15)
    - NOTE  | [ApesterKit/Content_Core, ApesterKit/ContentAdmob, ApesterKit/ContentPubmatic, and more...] xcodebuild:  note: Using codesigning identity override: -
    - NOTE  | [ApesterKit/Content_Core, ApesterKit/ContentAdmob, ApesterKit/ContentPubmatic, and more...] xcodebuild:  note: Building targets in dependency order
    - NOTE  | [ApesterKit/ContentAmazon,ApesterKit/Content] xcodebuild:  note: Target dependency graph (10 targets)
    - NOTE  | [ApesterKit/Content_Core, ApesterKit/ContentAdmob, ApesterKit/ContentPubmatic, and more...] xcodebuild:  note: Signing static framework with --generate-pre-encrypt-hashes (in target 'ApesterObjcBridging' from project 'Pods')
    - NOTE  | [ApesterKit/ContentAmazon,ApesterKit/Content] xcodebuild:  Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 12.0 to 17.2.99. (in target 'OpenWrapHandlerDFP' from project 'Pods')
    - NOTE  | [ApesterKit/Content_Core, ApesterKit/ContentAdmob, ApesterKit/ContentPubmatic, and more...] xcodebuild:  note: Signing static framework with --generate-pre-encrypt-hashes (in target 'ApesterKit' from project 'Pods')
    - NOTE  | [ApesterKit/Content_Core, ApesterKit/ContentAdmob, ApesterKit/ContentPubmatic, and more...] xcodebuild:  note: Signing static framework with --generate-pre-encrypt-hashes (in target 'Pods-App' from project 'Pods')
    - NOTE  | [ApesterKit/Content_Core, ApesterKit/ContentAdmob, ApesterKit/ContentPubmatic, and more...] xcodebuild:  note: Metadata extraction skipped. No AppIntents.framework dependency found. (in target 'App' from project 'App')
    - NOTE  | [ApesterKit/Content_Core, ApesterKit/ContentAdmob, ApesterKit/ContentPubmatic, and more...] xcodebuild:  Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 12.0 to 17.2.99. (in target 'DTBiOSSDK' from project 'Pods')
    - NOTE  | [ApesterKit/Content_Core, ApesterKit/ContentAdmob, ApesterKit/ContentPubmatic, and more...] xcodebuild:  Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 12.0 to 17.2.99. (in target 'OpenWrapSDK' from project 'Pods')
    - ERROR | xcodebuild: Returned an unsuccessful exit code.
    - NOTE  | xcodebuild:  note: Target dependency graph (14 targets)
    - NOTE  | xcodebuild:  Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 12.0 to 17.2.99. (in target 'EzImageLoader' from project 'Pods')
    - NOTE  | xcodebuild:  Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 12.0 to 17.2.99. (in target 'XCGLogger' from project 'Pods')
    - NOTE  | xcodebuild:  clang: error: SDK does not contain 'libarclite' at the path '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_iphonesimulator.a'; try increasing the minimum deployment target
    - NOTE  | xcodebuild:  Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 12.0 to 17.2.99. (in target 'EzHTTP' from project 'Pods')
    - NOTE  | xcodebuild:  Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 12.0 to 17.2.99. (in target 'ObjcExceptionBridging' from project 'Pods')
    - NOTE  | [iOS] xcodebuild:  rsync error: received SIGINT, SIGTERM, or SIGHUP (code 20) at /AppleInternal/Library/BuildRoots/11aa8fb2-5f4b-11ee-bc7f-926038f30c31/Library/Caches/com.apple.xbs/Sources/rsync/rsync/rsync.c(244) [sender=2.6.9]
    - NOTE  | [ApesterKit/Content_Core,ApesterKit/ContentPubmatic] xcodebuild:  note: Target dependency graph (6 targets)
    - NOTE  | [iOS] [ApesterKit/ContentAdmob] xcodebuild:  note: Target dependency graph (8 targets)

Pods workspace available at `/var/folders/9g/h5_gqgjs30n11p7w8l_q1lzc0000gp/T/CocoaPods-Lint-20240307-5239-gcdhdl-ApesterKit/App.xcworkspace` for inspection.

[!] ApesterKit did not pass validation, due to 1 error.

/usr/local/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/command/lib/lint.rb:116:in `block in run'
/usr/local/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/command/lib/lint.rb:77:in `each'
/usr/local/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/command/lib/lint.rb:77:in `run'
/usr/local/Cellar/cocoapods/1.15.2/libexec/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/usr/local/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:52:in `run'
/usr/local/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/bin/pod:55:in `<top (required)>'
/usr/local/Cellar/cocoapods/1.15.2/libexec/bin/pod:25:in `load'
/usr/local/Cellar/cocoapods/1.15.2/libexec/bin/pod:25:in `<main>'
```

### Stack

```
   CocoaPods : 1.15.2
        Ruby : ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [x86_64-darwin23]
    RubyGems : 3.5.4
        Host : macOS 14.1.1 (23B81)
       Xcode : 15.2 (15C500b)
         Git : git version 2.39.3 (Apple Git-145)
Ruby lib dir : /usr/local/Cellar/ruby/3.3.0/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/Cellar/cocoapods/1.15.2/libexec/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

## Project that demonstrates the issue

https://cocoapods.org/pods/ApesterKit
https://github.com/apester-dev/ios-sdk.

**Comment by evan802399** [comment]
I have the same issue.  Have you solved it ? @micky-apester

**Comment by sanhue0302** [comment]
if you see "... SDK does not contain 'libarclite' at...",
try to upgrade your `ios.deployment_target` to 11.0 or `osx.deployment_target` to 10.11.
this  should fix this problem
