### ISSUE TITLE
[!] Unable to add a source with url https://github.com/CocoaPods/Specs.git named cocoapods. You can try adding it manually in /Users/fanxianchao/.cocoapods/repos or via pod repo add. 

### ISSUE THREAD

**Issue by Haoxin903** [CocoaPods/CocoaPods#12329]
a1@192 ~ % pod search YYModel

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/a1/.rvm/rubies/ruby-3.3.0/bin/pod search YYModel
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.15.2
        Ruby : ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [arm64-darwin23]
    RubyGems : 3.5.7
        Host : macOS 14.4 (23E214)
       Xcode : 15.3 (15E204a)
         Git : git version 2.44.0
Ruby lib dir : /Users/a1/.rvm/rubies/ruby-3.3.0/lib
Repositories : master - file system
               Specs-master - file system
               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Error

```
Errno::EACCES - Permission denied @ rb_sysopen - /Users/a1/.cocoapods/repos/trunk/all_pods_versions_2_7_4.txt
/Users/a1/.rvm/rubies/ruby-3.3.0/lib/ruby/gems/3.3.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/cdn_source.rb:385:in `initialize'
/Users/a1/.rvm/rubies/ruby-3.3.0/lib/ruby/gems/3.3.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/cdn_source.rb:385:in `open'
/Users/a1/.rvm/rubies/ruby-3.3.0/lib/ruby/gems/3.3.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/cdn_source.rb:385:in `block in download_and_save_with_retries_async'
/Users/a1/.rvm/rubies/ruby-3.3.0/lib/ruby/gems/3.3.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/promises.rb:408:in `apply'
/Users/a1/.rvm/rubies/ruby-3.3.0/lib/ruby/gems/3.3.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/promises.rb:1216:in `apply'
/Users/a1/.rvm/rubies/ruby-3.3.0/lib/ruby/gems/3.3.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/promises.rb:1740:in `block (2 levels) in on_resolvable'
/Users/a1/.rvm/rubies/ruby-3.3.0/lib/ruby/gems/3.3.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/promises.rb:1593:in `evaluate_to'
/Users/a1/.rvm/rubies/ruby-3.3.0/lib/ruby/gems/3.3.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/promises.rb:1740:in `block in on_resolvable'
/Users/a1/.rvm/rubies/ruby-3.3.0/lib/ruby/gems/3.3.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:359:in `run_task'
/Users/a1/.rvm/rubies/ruby-3.3.0/lib/ruby/gems/3.3.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:350:in `block (3 levels) in create_worker'
<internal:kernel>:187:in `loop'
/Users/a1/.rvm/rubies/ruby-3.3.0/lib/ruby/gems/3.3.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:341:in `block (2 levels) in create_worker'
/Users/a1/.rvm/rubies/ruby-3.3.0/lib/ruby/gems/3.3.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in `catch'
/Users/a1/.rvm/rubies/ruby-3.3.0/lib/ruby/gems/3.3.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in `block in create_worker'
/Users/a1/.rvm/rubies/ruby-3.3.0/lib/ruby/gems/3.3.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/promises.rb:1268:in `raise'
/Users/a1/.rvm/rubies/ruby-3.3.0/lib/ruby/gems/3.3.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/promises.rb:1268:in `wait_until_resolved!'
/Users/a1/.rvm/rubies/ruby-3.3.0/lib/ruby/gems/3.3.0/gems/concurrent-ruby-1.2.3/lib/concurrent-ruby/concurrent/promises.rb:988:in `wait!'
/Users/a1/.rvm/rubies/ruby-3.3.0/lib/ruby/gems/3.3.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/cdn_source.rb:338:in `download_file'
/Users/a1/.rvm/rubies/ruby-3.3.0/lib/ruby/gems/3.3.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/cdn_source.rb:284:in `ensure_versions_file_loaded'
/Users/a1/.rvm/rubies/ruby-3.3.0/lib/ruby/gems/3.3.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/cdn_source.rb:112:in `versions'
/Users/a1/.rvm/rubies/ruby-3.3.0/lib/ruby/gems/3.3.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/specification/set.rb:99:in `block in versions_by_source'
/Users/a1/.rvm/rubies/ruby-3.3.0/lib/ruby/gems/3.3.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/specification/set.rb:98:in `each'
/Users/a1/.rvm/rubies/ruby-3.3.0/lib/ruby/gems/3.3.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/specification/set.rb:98:in `each_with_object'
/Users/a1/.rvm/rubies/ruby-3.3.0/lib/ruby/gems/3.3.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/specification/set.rb:98:in `versions_by_source'
/Users/a1/.rvm/rubies/ruby-3.3.0/lib/ruby/gems/3.3.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/specification/set.rb:75:in `versions'
/Users/a1/.rvm/rubies/ruby-3.3.0/lib/ruby/gems/3.3.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/cdn_source.rb:237:in `block in search_by_name'
/Users/a1/.rvm/rubies/ruby-3.3.0/lib/ruby/gems/3.3.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/cdn_source.rb:237:in `reject'
/Users/a1/.rvm/rubies/ruby-3.3.0/lib/ruby/gems/3.3.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/cdn_source.rb:237:in `search_by_name'
/Users/a1/.rvm/rubies/ruby-3.3.0/lib/ruby/gems/3.3.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/source/manager.rb:135:in `block in search_by_name'
/Users/a1/.rvm/rubies/ruby-3.3.0/lib/ruby/gems/3.3.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/source/manager.rb:135:in `map'
/Users/a1/.rvm/rubies/ruby-3.3.0/lib/ruby/gems/3.3.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/source/manager.rb:135:in `search_by_name'
/Users/a1/.rvm/rubies/ruby-3.3.0/lib/ruby/gems/3.3.0/gems/cocoapods-search-1.0.1/lib/cocoapods-search/command/search.rb:87:in `local_search'
/Users/a1/.rvm/rubies/ruby-3.3.0/lib/ruby/gems/3.3.0/gems/cocoapods-search-1.0.1/lib/cocoapods-search/command/search.rb:63:in `run'
/Users/a1/.rvm/rubies/ruby-3.3.0/lib/ruby/gems/3.3.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Users/a1/.rvm/rubies/ruby-3.3.0/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:52:in `run'
/Users/a1/.rvm/rubies/ruby-3.3.0/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/bin/pod:55:in `<top (required)>'
/Users/a1/.rvm/rubies/ruby-3.3.0/bin/pod:25:in `load'
/Users/a1/.rvm/rubies/ruby-3.3.0/bin/pod:25:in `<main>'
/Users/a1/.rvm/rubies/ruby-3.3.0/bin/ruby_executable_hooks:22:in `eval'
/Users/a1/.rvm/rubies/ruby-3.3.0/bin/ruby_executable_hooks:22:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
Apple M2 芯片  macOS 14.4   

a1@192 ~ % cd /Users/a1/Desktop/01tiyu/01tiyu 
a1@192 01tiyu % pod init
[!] Existing Podfile found in directory
a1@192 01tiyu % pod install
Analyzing dependencies
Cloning spec repo `cocoapods` from `https://github.com/CocoaPods/Specs.git`
[!] Unable to add a source with url `https://github.com/CocoaPods/Specs.git` named `cocoapods`.
You can try adding it manually in `/Users/a1/.cocoapods/repos` or via `pod repo add`.
a1@192 01tiyu % 

我目前还不知道 哪里出了问题  brew  ruby 都升级到最新了

**Comment by Haoxin903** [comment]
下面那个错误 没显示出来

a1@192 ~ % cd /Users/a1/Desktop/01tiyu/01tiyu 
a1@192 01tiyu % pod init
[!] Existing Podfile found in directory
a1@192 01tiyu % pod install
Analyzing dependencies
Cloning spec repo `cocoapods` from `https://github.com/CocoaPods/Specs.git`
[!] Unable to add a source with url `https://github.com/CocoaPods/Specs.git` named `cocoapods`.
You can try adding it manually in `/Users/a1/.cocoapods/repos` or via `pod repo add`.

**Comment by Haoxin903** [comment]
有大佬能回复一下我的问题吗
