### ISSUE TITLE
Error Cocoapods Install: JSON::ParserError - Failed to parse JSON at file: '/Users/lucassilva/.cocoapods/repos/trunk/Specs/9/1/0/gRPC-Core/1.63.0/gRPC-Core.podspec.json'.

### ISSUE THREAD

**Issue by lucassilva82** [CocoaPods/CocoaPods#12377]
――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

    ### Command

    ```
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/bin/pod install --verbose
    ```

    ### Report

    * What did you do?

    * What did you expect to happen?

    * What happened instead?

    ### Stack

    ```
       CocoaPods : 1.15.2
            Ruby : ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [arm64-darwin23]
        RubyGems : 3.5.4
            Host : macOS 14.3 (23D56)
           Xcode : 15.3 (15E204a)
             Git : git version 2.41.0
    Ruby lib dir : /opt/homebrew/Cellar/ruby/3.3.0/lib
    Repositories : trunk - CDN - https://cdn.cocoapods.org/
    ```

    ### Plugins

    ```
    cocoapods-deintegrate : 1.0.5
    cocoapods-plugins     : 1.0.0
    cocoapods-search      : 1.0.1
    cocoapods-trunk       : 1.6.0
    cocoapods-try         : 1.2.0
    ```

    ### Podfile

    ```ruby
    # Uncomment this line to define a global platform for your project
    # platform :ios, '12.0'

    # CocoaPods analytics sends network stats synchronously affecting flutter build latency.
    ENV['COCOAPODS_DISABLE_STATS'] = 'true'

    project 'Runner', {
      'Debug' => :debug,
      'Profile' => :release,
      'Release' => :release,
    }

    def flutter_root
      generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
      unless File.exist?(generated_xcode_build_settings_path)
        raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
      end

      File.foreach(generated_xcode_build_settings_path) do |line|
        matches = line.match(/FLUTTER_ROOT\=(.*)/)
        return matches[1].strip if matches
      end
      raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
    end

    require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

    flutter_ios_podfile_setup

    target 'Runner' do
      use_frameworks!
      use_modular_headers!

      flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
      target 'RunnerTests' do
        inherit! :search_paths
      end
    end

    post_install do |installer|
      installer.pods_project.targets.each do |target|
        flutter_additional_ios_build_settings(target)
        target.build_configurations.each do |config|
          xcconfig_path = config.base_configuration_reference.real_path
          xcconfig = File.read(xcconfig_path)
          xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
          File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
        end
      end
    end
    ```

    ### Error

    ```
    JSON::ParserError - Failed to parse JSON at file: '/Users/lucassilva/.cocoapods/repos/trunk/Specs/9/1/0/gRPC-Core/1.63.0/gRPC-Core.podspec.json'.

    unexpected token at '"src/core/ext/upb-gen/envoy/config/trace/v3/skywalking.upb_minitable.'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-core-1.15.2/lib/cocoapods-core/specification/json.rb:66:in `rescue in from_json'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-core-1.15.2/lib/cocoapods-core/specification/json.rb:61:in `from_json'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-core-1.15.2/lib/cocoapods-core/specification.rb:759:in `from_string'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-core-1.15.2/lib/cocoapods-core/specification.rb:733:in `from_file'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-core-1.15.2/lib/cocoapods-core/source.rb:188:in `specification'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-core-1.15.2/lib/cocoapods-core/specification/set.rb:58:in `block in specification_name'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-core-1.15.2/lib/cocoapods-core/specification/set.rb:56:in `each'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-core-1.15.2/lib/cocoapods-core/specification/set.rb:56:in `specification_name'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-core-1.15.2/lib/cocoapods-core/cdn_source.rb:216:in `search'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-core-1.15.2/lib/cocoapods-core/source/aggregate.rb:83:in `block in search'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-core-1.15.2/lib/cocoapods-core/source/aggregate.rb:83:in `select'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-core-1.15.2/lib/cocoapods-core/source/aggregate.rb:83:in `search'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/resolver.rb:416:in `create_set_from_sources'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/resolver.rb:385:in `find_cached_set'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/resolver.rb:360:in `specifications_for_dependency'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/resolver.rb:165:in `search_for'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/resolver.rb:274:in `block in sort_dependencies'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/resolver.rb:267:in `each'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/resolver.rb:267:in `sort_by'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/resolver.rb:267:in `sort_by!'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/resolver.rb:267:in `sort_dependencies'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:60:in `block in
    sort_dependencies'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:77:in
    `with_no_such_dependency_error_handling'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:59:in `sort_dependencies'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:754:in `push_state_for_requirements'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:744:in `require_nested_dependencies_for'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:727:in `activate_new_spec'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:684:in `attempt_to_activate'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:254:in `process_topmost_state'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:182:in `resolve'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in `resolve'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/resolver.rb:94:in `resolve'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/installer/analyzer.rb:1082:in `block in resolve_dependencies'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/user_interface.rb:64:in `section'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/installer/analyzer.rb:1080:in `resolve_dependencies'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/installer/analyzer.rb:125:in `analyze'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:422:in `analyze'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:244:in `block in resolve_dependencies'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/user_interface.rb:64:in `section'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:243:in `resolve_dependencies'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:162:in `install!'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/command/install.rb:52:in `run'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:52:in `run'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/bin/pod:55:in `<top (required)>'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/bin/pod:25:in `load'
    /opt/homebrew/Cellar/cocoapods/1.15.2/libexec/bin/pod:25:in `<main>'
    ```

    ――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

    [!] Oh no, an error occurred.

    Search for existing GitHub issues similar to yours:
    https://github.com/CocoaPods/CocoaPods/search?q=Failed+to+parse+JSON+at+file%3A+%27%2FUsers%2Flucassilva%2F.cocoapods%2Frepos%2Ftrunk%2FSpecs%2F9%2F1%
    2F0%2FgRPC-Core%2F1.63.0%2FgRPC-Core.podspec.json%27.%0A%0Aunexpected+token+at+%27%22src%2Fcore%2Fext%2Fupb-gen%2Fenvoy%2Fconfig%2Ftrace%2Fv3%2Fskywal
    king.upb_minitable.%27&type=Issues

    If none exists, create a ticket, with the template displayed above, on:
    https://github.com/CocoaPods/CocoaPods/issues/new

    Be sure to first read the contributing guide for details on how to properly submit a ticket:
    https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

    Don't forget to anonymize any private data!

    Looking for related issues on cocoapods/cocoapods...
     - Pods-resources.sh badly generated during pod install
       https://github.com/CocoaPods/CocoaPods/issues/3739 [closed] [7 comments]
       02 Aug 2015

     - Xcode 7 Archive Build rsync resources path not found
       https://github.com/CocoaPods/CocoaPods/issues/3738 [closed] [5 comments]
       11 Jul 2015

     - allow specifying CLANG_CXX_LANGUAGE_STANDARD for a single pod
       https://github.com/CocoaPods/CocoaPods/issues/3733 [closed] [2 comments]
       25 Jun 2015

    and 12190 more at:
    https://github.com/cocoapods/cocoapods/search?q=Failed%20to%20parse%20JSON%20at%20file%3A%20%27%2FUsers%2Flucassilva%2F.cocoapods%2Frepos%2Ftrunk%2FSp
    ecs%2F9%2F1%2F0%2FgRPC-Core%2F1.63.0%2FgRPC-Core.podspec.json%27.%0A%0Aunexpected%20token%20at%20%27%22src%2Fcore%2Fext%2Fupb-gen%2Fenvoy%2Fconfig%2Ft
    race%2Fv3%2Fskywalking.upb_minitable.%27&type=Issues&utf8=✓

Error output from CocoaPods:
↳

    [!] Automatically assigning platform `iOS` with version `12.0` on target `Runner` because no platform was specified. Please specify a platform for
    this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Error running pod install
Error launching application on iPhone 15 Pro Max.

**Comment by lucassilva82** [comment]
Por favor me ajudem, ja tentei de tudo, limpar todo o cache do cocoapods, limpar o cache do app, reinstalar tudo. So tenho esse problema ao usar o firebase Message e Firebase Core, mas preciso utilizar para implementar algumas solucoes.

**Comment by kirillnepomiluev** [comment]
i have the same problem. everythig the Same ### Error

```
JSON::ParserError - Failed to parse JSON at file: '/Users/kirillnepomiluev/.cocoapods/repos/trunk/Specs/9/1/0/gRPC-Core/1.62.1/gRPC-Core.podspec.json'.

**Comment by lucassilva82** [comment]
> i have the same problem. everythig the Same ### Error
> 
> ```
> JSON::ParserError - Failed to parse JSON at file: '/Users/kirillnepomiluev/.cocoapods/repos/trunk/Specs/9/1/0/gRPC-Core/1.62.1/gRPC-Core.podspec.json'.
> ```

any solution?

**Comment by kirillnepomiluev** [comment]
> > i have the same problem. everythig the Same ### Error
> > ```
> > JSON::ParserError - Failed to parse JSON at file: '/Users/kirillnepomiluev/.cocoapods/repos/trunk/Specs/9/1/0/gRPC-Core/1.62.1/gRPC-Core.podspec.json'.
> > ```
> 
> any solution?

no solution yet

**Comment by CheddersGroup** [comment]
i have the same problem. everythig the Same ### Error

JSON::ParserError - Failed to parse JSON at file: '/Users/kirillnepomiluev/.cocoapods/repos/trunk/Specs/9/1/0/gRPC-Core/1.62.1/gRPC-Core.podspec.json'.

**Comment by lucassilva82** [comment]
good morning guys
I managed to solve the problem, pod install was executed successfully.
I just ran the flutter pub outdated command which brought up all the libraries that needed to be updated or were discontinued, updated everything and ran pod install. everything worked.

**Comment by AjeemPearl** [comment]
Analyzing dependencies
cloud_firestore: Using Firebase SDK version '10.25.0' defined in 'firebase_core'
firebase_auth: Using Firebase SDK version '10.25.0' defined in 'firebase_core'
firebase_core: Using Firebase SDK version '10.25.0' defined in 'firebase_core'
firebase_messaging: Using Firebase SDK version '10.25.0' defined in 'firebase_core'
[!] CocoaPods could not find compatible versions for pod "google_maps_flutter_ios":
  In Podfile:
    google_maps_flutter_ios (from `.symlinks/plugins/google_maps_flutter_ios/ios`)

Specs satisfying the `google_maps_flutter_ios (from `.symlinks/plugins/google_maps_flutter_ios/ios`)` dependency were found, but they required a higher minimum deployment target.

**Comment by AjeemPearl** [comment]
> good morning guys I managed to solve the problem, pod install was executed successfully. I just ran the flutter pub outdated command which brought up all the libraries that needed to be updated or were discontinued, updated everything and ran pod install. everything worked.

I tried the same but got this Analyzing dependencies
cloud_firestore: Using Firebase SDK version '10.25.0' defined in 'firebase_core'
firebase_auth: Using Firebase SDK version '10.25.0' defined in 'firebase_core'
firebase_core: Using Firebase SDK version '10.25.0' defined in 'firebase_core'
firebase_messaging: Using Firebase SDK version '10.25.0' defined in 'firebase_core'
[!] CocoaPods could not find compatible versions for pod "google_maps_flutter_ios":
  In Podfile:
    google_maps_flutter_ios (from `.symlinks/plugins/google_maps_flutter_ios/ios`)

Specs satisfying the `google_maps_flutter_ios (from `.symlinks/plugins/google_maps_flutter_ios/ios`)` dependency were found, but they required a higher minimum deployment target.

**Comment by kirillnepomiluev** [comment]
I found woringing solution for me/ 
1. flutter upgrade
2. update in pubspec versions of the main libs
3. update cocoa pods by this instructions https://stackoverflow.com/questions/71013091/flutter-ios-pod-install-failed-after-upgrading-xcode-and-flutter-version/71014492#71014492 
4. flutter clean 
5. flutter build ios

**Comment by Mrhammaddev** [comment]
Try the following commands
1-Refresh local cocoapods trunk 
   `rm -rf ~/.cocoapods/repos/trunk/`
2-pod install
