### ISSUE TITLE
NOT Installing POD

### ISSUE THREAD

**Issue by mukulsharma211** [CocoaPods/CocoaPods#12419]
``
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/bin/pod deintegrate
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.15.2
        Ruby : ruby 3.3.2 (2024-05-30 revision e5a195edf6) [arm64-darwin23]
    RubyGems : 3.5.11
        Host : macOS 14.5 (23F79)
       Xcode : 15.4 (15F31d)
         Git : git version 2.39.3 (Apple Git-146)
Ruby lib dir : /opt/homebrew/Cellar/ruby/3.3.2/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HTMediaProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HTMediaProject
  pod 'FirebaseCore'
  pod 'SDWebImage'
  pod 'MoEngage-iOS-SDK', '8.2.0'
  pod 'Alamofire'
  pod 'FirebaseAnalytics'
  pod 'FirebaseCrashlytics'
  pod 'SkeletonView'
  pod 'GoogleAds-IMA-tvOS-SDK'
  pod 'Mux-Stats-AVPlayer'
  pod 'Mux-Stats-Google-IMA'

  target 'HTMediaProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HTMediaProjectUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  installer.aggregate_targets.each do |target|
    target.xcconfigs.each do |variant, xcconfig|
      xcconfig_path = target.client_root + target.xcconfig_relative_path(variant)
      IO.write(xcconfig_path, IO.read(xcconfig_path).gsub("DT_TOOLCHAIN_DIR", "TOOLCHAIN_DIR"))
    end
  end
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.base_configuration_reference.is_a? Xcodeproj::Project::Object::PBXFileReference
        xcconfig_path = config.base_configuration_reference.real_path
        IO.write(xcconfig_path, IO.read(xcconfig_path).gsub("DT_TOOLCHAIN_DIR", "TOOLCHAIN_DIR"))
      end
    end
  end
end
```

### Error

```
Nanaimo::Reader::ParseError - [!] Dictionary missing ';' after key-value pair for "93BDFDAE037DA89CB54E2B2D", found ""
    #  -------------------------------------------
    #  	rootObject = 1442BB3C28F67D9700CED56B /* Project object */;
    #  }
4225>  
       ^
    #  -------------------------------------------

/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/nanaimo-0.3.0/lib/nanaimo/reader.rb:284:in `raise_parser_error'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/nanaimo-0.3.0/lib/nanaimo/reader.rb:199:in `parse_dictionary'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/nanaimo-0.3.0/lib/nanaimo/reader.rb:132:in `parse_object'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/nanaimo-0.3.0/lib/nanaimo/reader.rb:193:in `parse_dictionary'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/nanaimo-0.3.0/lib/nanaimo/reader.rb:132:in `parse_object'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/nanaimo-0.3.0/lib/nanaimo/reader.rb:193:in `parse_dictionary'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/nanaimo-0.3.0/lib/nanaimo/reader.rb:132:in `parse_object'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/nanaimo-0.3.0/lib/nanaimo/reader.rb:193:in `parse_dictionary'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/nanaimo-0.3.0/lib/nanaimo/reader.rb:132:in `parse_object'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/nanaimo-0.3.0/lib/nanaimo/reader.rb:107:in `parse!'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/xcodeproj-1.24.0/lib/xcodeproj/plist.rb:27:in `read_from_path'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/xcodeproj-1.24.0/lib/xcodeproj/project.rb:211:in `initialize_from_file'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/xcodeproj-1.24.0/lib/xcodeproj/project.rb:113:in `open'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-deintegrate-1.0.5/lib/cocoapods/command/deintegrate.rb:40:in `validate!'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/claide-1.1.0/lib/claide/command.rb:333:in `run'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:52:in `run'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/bin/pod:55:in `<top (required)>'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/bin/pod:25:in `load'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/bin/pod:25:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=%5B%21%5D+Dictionary+missing+%27%3B%27+after+key-value+pair+for+%2293BDFDAE037DA89CB54E2B2D%22%2C+found+%22%22%0A++++%23++-------------------------------------------%0A++++%23++%09rootObject+%3D+1442BB3C28F67D9700CED56B+%2F%2A+Project+object+%2A%2F%3B%0A++++%23++%7D%0A4225%3E++%0A+++++++%5E%0A++++%23++-------------------------------------------%0A&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Searching for inspections failed: undefined method `map' for nil

**Comment by again-this-coder** [comment]
facing same issue

**Comment by mukulsharma211** [comment]
can you please try to uninstall pod and then run.

**Comment by again-this-coder** [comment]
Just did it. The issue remains

I have used the expo prebuild command and tried to do pod install and I get this issue

**Comment by mukulsharma211** [comment]
I have faced this issue in two way :- 
1. first because the ruby install in m1 is the install of intel chip.
2. second because of the pod file and their dependency is pushed in the repo.
