### ISSUE TITLE
pod install fails on prepared_command with no such file error on macOS Sonoma but works before upgrade

### ISSUE THREAD

**Issue by ivanbogomoloff** [CocoaPods/CocoaPods#12499]
* [+] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod install`

## What did you expect to happen?

Install all pod dependencies correctly.

## What happened instead?

No such file or directory.

```bash
Downloading dependencies

-> Installing Flutter (1.0.0)

-> Installing WireGuardKit (0.3)
 > Git download
 > Git download
     $ /usr/bin/git clone https://github.com/mysteriumnetwork/wireguard-apple.git /var/folders/q5/mwv6149j579clflwdykprrgh0000gn/T/d20240726-75244-gk13r0 --template=
     --single-branch --depth 1 --branch 0.3
     Cloning into '/var/folders/q5/mwv6149j579clflwdykprrgh0000gn/T/d20240726-75244-gk13r0'...
 > Running prepare command
   $ /bin/bash -c  set -e ./build-libwg.sh
   /bin/bash: line 2: ./build-libwg.sh: No such file or directory
[!] /bin/bash -c 
set -e
./build-libwg.sh

/bin/bash: line 2: ./build-libwg.sh: No such file or directory


/Users/ivanb/.rvm/gems/ruby-3.2.2/gems/cocoapods-1.15.2/lib/cocoapods/executable.rb:73:in `execute_command'
/Users/ivanb/.rvm/gems/ruby-3.2.2/gems/cocoapods-1.15.2/lib/cocoapods/executable.rb:27:in `block in executable'
/Users/ivanb/.rvm/gems/ruby-3.2.2/gems/cocoapods-1.15.2/lib/cocoapods/installer/pod_source_preparer.rb:66:in `block (2 levels) in run_prepare_command'
/Users/ivanb/.rvm/gems/ruby-3.2.2/gems/cocoapods-1.15.2/lib/cocoapods/installer/pod_source_preparer.rb:60:in `chdir'
/Users/ivanb/.rvm/gems/ruby-3.2.2/gems/cocoapods-1.15.2/lib/cocoapods/installer/pod_source_preparer.rb:60:in `block in run_prepare_command'
/Users/ivanb/.rvm/gems/ruby-3.2.2/gems/cocoapods-1.15.2/lib/cocoapods/user_interface.rb:64:in `section'
/Users/ivanb/.rvm/gems/ruby-3.2.2/gems/cocoapods-1.15.2/lib/cocoapods/installer/pod_source_preparer.rb:59:in `run_prepare_command'
/Users/ivanb/.rvm/gems/ruby-3.2.2/gems/cocoapods-1.15.2/lib/cocoapods/installer/pod_source_preparer.rb:37:in `prepare!'
/Users/ivanb/.rvm/gems/ruby-3.2.2/gems/cocoapods-1.15.2/lib/cocoapods/downloader/cache.rb:288:in `block in copy_and_clean'
/Users/ivanb/.rvm/gems/ruby-3.2.2/gems/cocoapods-1.15.2/lib/cocoapods/downloader/cache.rb:128:in `lock'
/Users/ivanb/.rvm/gems/ruby-3.2.2/gems/cocoapods-1.15.2/lib/cocoapods/downloader/cache.rb:99:in `write_lock'
/Users/ivanb/.rvm/gems/ruby-3.2.2/gems/cocoapods-1.15.2/lib/cocoapods/downloader/cache.rb:285:in `copy_and_clean'
/Users/ivanb/.rvm/gems/ruby-3.2.2/gems/cocoapods-1.15.2/lib/cocoapods/downloader/cache.rb:244:in `block (2 levels) in uncached_pod'
/Users/ivanb/.rvm/gems/ruby-3.2.2/gems/cocoapods-1.15.2/lib/cocoapods/downloader/cache.rb:242:in `each'
/Users/ivanb/.rvm/gems/ruby-3.2.2/gems/cocoapods-1.15.2/lib/cocoapods/downloader/cache.rb:242:in `block in uncached_pod'
/Users/ivanb/.rvm/gems/ruby-3.2.2/gems/cocoapods-1.15.2/lib/cocoapods/downloader/cache.rb:266:in `in_tmpdir'
/Users/ivanb/.rvm/gems/ruby-3.2.2/gems/cocoapods-1.15.2/lib/cocoapods/downloader/cache.rb:238:in `uncached_pod'
/Users/ivanb/.rvm/gems/ruby-3.2.2/gems/cocoapods-1.15.2/lib/cocoapods/downloader/cache.rb:33:in `download_pod'
/Users/ivanb/.rvm/gems/ruby-3.2.2/gems/cocoapods-1.15.2/lib/cocoapods/downloader.rb:42:in `download'
/Users/ivanb/.rvm/gems/ruby-3.2.2/gems/cocoapods-1.15.2/lib/cocoapods/installer/pod_source_downloader.rb:69:in `download!'
```

## CocoaPods Environment

```
   CocoaPods : 1.15.2
        Ruby : ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-darwin23]
    RubyGems : 3.4.10
        Host : macOS 14.4.1 (23E224)
       Xcode : 15.4 (15F31d)
         Git : git version 2.39.3 (Apple Git-146)
Ruby lib dir : /Users/ivanb/.rvm/rubies/ruby-3.2.2/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

## Project that demonstrates the issue

Just clone this project https://github.com/mysteriumnetwork/wireguard_dart

and to to `example/ios` and run `pod install`

Before i use macOS 12 and it `pod install` works find. After upgrade to macOS Sonoma i cant build this project.

**Comment by ivanbogomoloff** [comment]
I fixed it and this proble doesn't related to cocapods directly.
First for debug i wrote code to `pod_source_preparer.rb` i add ` UI.message("> path = #{path}")` becuase in verbose mode cocoapods not show what is path dir.

```ruby
 def run_prepare_command
        return unless spec.prepare_command
        UI.section(' > Running prepare command', '', 1) do
          Dir.chdir(path) do
            begin
             UI.message("> path = #{path}")
```
then i got path and i did remove existing dir it was

```
rm -rf /Users/ivanb/Library/Caches/CocoaPods/Pods/Release/WireGuardKit/0.3-8b9e7
```

then i run `pod install` again and it works. I don't know why. But works for me. Then pod installed success.
