### ISSUE TITLE
Running pod install in a PWABuilder Xcode app failed

### ISSUE THREAD

**Issue by aadishsamir123** [CocoaPods/CocoaPods#12537]
### Command

```
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/bin/pod install
```

### Report

* What did you do?
Ran pod install

* What did you expect to happen?
Expected it to finish installing successfully

* What happened instead?
It failed

### Stack

```
   CocoaPods : 1.15.2
        Ruby : ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [arm64-darwin23]
    RubyGems : 3.5.4
        Host : macOS 15.0 (24A5309e)
       Xcode : 16.0 (16A5211f)
         Git : git version 2.39.5 (Apple Git-154)
Ruby lib dir : /opt/homebrew/Cellar/ruby/3.3.0/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Add the pod for Firebase Cloud Messaging
  pod 'Firebase/Messaging'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
```

### Error

```
LoadError - dlopen(/Users/aadishsamir/.gem/ruby/3.3.0/gems/ffi-1.16.3/lib/ffi_c.bundle, 0x0009): Symbol not found: _rb_cFalseClass
  Referenced from: <6A1DA7CC-CC67-30DC-B212-8A53536B419C> /Users/aadishsamir/.gem/ruby/3.3.0/gems/ffi-1.16.3/lib/ffi_c.bundle
  Expected in:     <3E71A3C4-46A2-3806-A17C-30BEDEE3C6A3> /opt/homebrew/Cellar/ruby/3.3.0/bin/ruby - /Users/aadishsamir/.gem/ruby/3.3.0/gems/ffi-1.16.3/lib/ffi_c.bundle
<internal:/opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
<internal:/opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
/Users/aadishsamir/.gem/ruby/3.3.0/gems/ffi-1.16.3/lib/ffi.rb:5:in `rescue in <top (required)>'
/Users/aadishsamir/.gem/ruby/3.3.0/gems/ffi-1.16.3/lib/ffi.rb:2:in `<top (required)>'
<internal:/opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
<internal:/opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
/Users/aadishsamir/.gem/ruby/3.3.0/gems/ethon-0.16.0/lib/ethon.rb:3:in `<top (required)>'
<internal:/opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
<internal:/opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
/Users/aadishsamir/.gem/ruby/3.3.0/gems/typhoeus-1.4.1/lib/typhoeus.rb:2:in `<top (required)>'
<internal:/opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
<internal:/opt/homebrew/Cellar/ruby/3.3.0/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:127:in `require'
/Users/aadishsamir/.gem/ruby/3.3.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/cdn_source.rb:440:in `download_typhoeus_impl_async'
/Users/aadishsamir/.gem/ruby/3.3.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/cdn_source.rb:372:in `download_and_save_with_retries_async'
/Users/aadishsamir/.gem/ruby/3.3.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/cdn_source.rb:365:in `download_file_async'
/Users/aadishsamir/.gem/ruby/3.3.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/cdn_source.rb:338:in `download_file'
/Users/aadishsamir/.gem/ruby/3.3.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/cdn_source.rb:284:in `ensure_versions_file_loaded'
/Users/aadishsamir/.gem/ruby/3.3.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/cdn_source.rb:208:in `search'
/Users/aadishsamir/.gem/ruby/3.3.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/source/aggregate.rb:83:in `block in search'
/Users/aadishsamir/.gem/ruby/3.3.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/source/aggregate.rb:83:in `select'
/Users/aadishsamir/.gem/ruby/3.3.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/source/aggregate.rb:83:in `search'
/Users/aadishsamir/.gem/ruby/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/resolver.rb:416:in `create_set_from_sources'
/Users/aadishsamir/.gem/ruby/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/resolver.rb:385:in `find_cached_set'
/Users/aadishsamir/.gem/ruby/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/resolver.rb:360:in `specifications_for_dependency'
/Users/aadishsamir/.gem/ruby/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/resolver.rb:165:in `search_for'
/Users/aadishsamir/.gem/ruby/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/resolver.rb:274:in `block in sort_dependencies'
/Users/aadishsamir/.gem/ruby/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/resolver.rb:267:in `each'
/Users/aadishsamir/.gem/ruby/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/resolver.rb:267:in `sort_by'
/Users/aadishsamir/.gem/ruby/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/resolver.rb:267:in `sort_by!'
/Users/aadishsamir/.gem/ruby/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/resolver.rb:267:in `sort_dependencies'
/Users/aadishsamir/.gem/ruby/3.3.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:60:in `block in sort_dependencies'
/Users/aadishsamir/.gem/ruby/3.3.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:77:in `with_no_such_dependency_error_handling'
/Users/aadishsamir/.gem/ruby/3.3.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:59:in `sort_dependencies'
/Users/aadishsamir/.gem/ruby/3.3.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:754:in `push_state_for_requirements'
/Users/aadishsamir/.gem/ruby/3.3.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:288:in `push_initial_state'
/Users/aadishsamir/.gem/ruby/3.3.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:210:in `start_resolution'
/Users/aadishsamir/.gem/ruby/3.3.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:168:in `resolve'
/Users/aadishsamir/.gem/ruby/3.3.0/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in `resolve'
/Users/aadishsamir/.gem/ruby/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/resolver.rb:94:in `resolve'
/Users/aadishsamir/.gem/ruby/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/installer/analyzer.rb:1082:in `block in resolve_dependencies'
/Users/aadishsamir/.gem/ruby/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/user_interface.rb:64:in `section'
/Users/aadishsamir/.gem/ruby/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/installer/analyzer.rb:1080:in `resolve_dependencies'
/Users/aadishsamir/.gem/ruby/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/installer/analyzer.rb:125:in `analyze'
/Users/aadishsamir/.gem/ruby/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:422:in `analyze'
/Users/aadishsamir/.gem/ruby/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:244:in `block in resolve_dependencies'
/Users/aadishsamir/.gem/ruby/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/user_interface.rb:64:in `section'
/Users/aadishsamir/.gem/ruby/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:243:in `resolve_dependencies'
/Users/aadishsamir/.gem/ruby/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:162:in `install!'
/Users/aadishsamir/.gem/ruby/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/command/install.rb:52:in `run'
/Users/aadishsamir/.gem/ruby/3.3.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Users/aadishsamir/.gem/ruby/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:52:in `run'
/Users/aadishsamir/.gem/ruby/3.3.0/gems/cocoapods-1.15.2/bin/pod:55:in `<top (required)>'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/bin/pod:25:in `load'
/opt/homebrew/Cellar/cocoapods/1.15.2/libexec/bin/pod:25:in `<main>'
```

**Comment by org-codetribe** [comment]
I have This Issue 
_____________________________________________________________________________________________
```
   CocoaPods : 1.15.2
        Ruby : ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.arm64e-darwin23]
    RubyGems : 3.0.3.1
        Host : macOS 14.3.1 (23D60)
       Xcode : 15.4 (15F31d)
         Git : git version 2.39.3 (Apple Git-146)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
platform :ios, '14.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

target 'RunnerDev' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

target 'RunnerDevTest' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    # Start of the permission_handler configuration
          target.build_configurations.each do |config|
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
              '$(inherited)',
              ## dart: PermissionGroup.calendar
              # 'PERMISSION_EVENTS=1',
              ## dart: PermissionGroup.reminders
              # 'PERMISSION_REMINDERS=1',
              ## dart: PermissionGroup.contacts
               'PERMISSION_CONTACTS=1',
              ## dart: PermissionGroup.camera
              'PERMISSION_CAMERA=1',
              ## dart: PermissionGroup.microphone
              # 'PERMISSION_MICROPHONE=1',
              ## dart: PermissionGroup.speech
              # 'PERMISSION_SPEECH_RECOGNIZER=1',
              ## dart: PermissionGroup.photos
              'PERMISSION_PHOTOS=1',
              ## dart: [PermissionGroup.location, PermissionGroup.locationAlways, PermissionGroup.locationWhenInUse]
              # 'PERMISSION_LOCATION=1',
              ## dart: PermissionGroup.notification
              'PERMISSION_NOTIFICATIONS=1',
              ## dart: PermissionGroup.mediaLibrary
              # 'PERMISSION_MEDIA_LIBRARY=1',
              ## dart: PermissionGroup.sensors
              # 'PERMISSION_SENSORS=1',
              ## dart: PermissionGroup.bluetooth
              # 'PERMISSION_BLUETOOTH=1',
              ## dart: PermissionGroup.appTrackingTransparency
              # 'PERMISSION_APP_TRACKING_TRANSPARENCY=1',
              ## dart: PermissionGroup.criticalAlerts
              # 'PERMISSION_CRITICAL_ALERTS=1'
             ]
            end
            # End of the permission_handler configuration
            
  end
end
```

### Error

```
REXML::ParseException - #<TypeError: wrong argument type String (expected Regexp)>
/Library/Ruby/Gems/2.6.0/gems/rexml-3.2.9/lib/rexml/source.rb:220:in `scan'
/Library/Ruby/Gems/2.6.0/gems/rexml-3.2.9/lib/rexml/source.rb:220:in `match'
/Library/Ruby/Gems/2.6.0/gems/rexml-3.2.9/lib/rexml/parsers/baseparser.rb:227:in `pull_event'
/Library/Ruby/Gems/2.6.0/gems/rexml-3.2.9/lib/rexml/parsers/baseparser.rb:207:in `pull'
/Library/Ruby/Gems/2.6.0/gems/rexml-3.2.9/lib/rexml/parsers/treeparser.rb:23:in `parse'
/Library/Ruby/Gems/2.6.0/gems/rexml-3.2.9/lib/rexml/document.rb:448:in `build'
/Library/Ruby/Gems/2.6.0/gems/rexml-3.2.9/lib/rexml/document.rb:101:in `initialize'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.24.0/lib/xcodeproj/workspace.rb:83:in `new'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.24.0/lib/xcodeproj/workspace.rb:83:in `from_s'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.24.0/lib/xcodeproj/workspace.rb:66:in `new_from_xcworkspace'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/installer/user_project_integrator.rb:102:in `create_workspace'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/installer/user_project_integrator.rb:71:in `integrate!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:929:in `block in integrate_user_project'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:925:in `integrate_user_project'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:185:in `integrate'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:170:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
...
wrong argument type String (expected Regexp)
Line: 1
Position: 38
Last 80 unconsumed characters:
<?xml version="1.0" encoding="UTF-8"?>
/Library/Ruby/Gems/2.6.0/gems/rexml-3.2.9/lib/rexml/parsers/treeparser.rb:96:in `rescue in parse'
/Library/Ruby/Gems/2.6.0/gems/rexml-3.2.9/lib/rexml/parsers/treeparser.rb:21:in `parse'
/Library/Ruby/Gems/2.6.0/gems/rexml-3.2.9/lib/rexml/document.rb:448:in `build'
/Library/Ruby/Gems/2.6.0/gems/rexml-3.2.9/lib/rexml/document.rb:101:in `initialize'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.24.0/lib/xcodeproj/workspace.rb:83:in `new'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.24.0/lib/xcodeproj/workspace.rb:83:in `from_s'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.24.0/lib/xcodeproj/workspace.rb:66:in `new_from_xcworkspace'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/installer/user_project_integrator.rb:102:in `create_workspace'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/installer/user_project_integrator.rb:71:in `integrate!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:929:in `block in integrate_user_project'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:925:in `integrate_user_project'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:185:in `integrate'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:170:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=%23%3CTypeError%3A+wrong+argument+type+String+%28expected+Regexp%29%3E%0A%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Frexml-3.2.9%2Flib%2Frexml%2Fsource.rb%3A220%3Ain+%60scan%27%0A%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Frexml-3.2.9%2Flib%2Frexml%2Fsource.rb%3A220%3Ain+%60match%27%0A%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Frexml-3.2.9%2Flib%2Frexml%2Fparsers%2Fbaseparser.rb%3A227%3Ain+%60pull_event%27%0A%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Frexml-3.2.9%2Flib%2Frexml%2Fparsers%2Fbaseparser.rb%3A207%3Ain+%60pull%27%0A%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Frexml-3.2.9%2Flib%2Frexml%2Fparsers%2Ftreeparser.rb%3A23%3Ain+%60parse%27%0A%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Frexml-3.2.9%2Flib%2Frexml%2Fdocument.rb%3A448%3Ain+%60build%27%0A%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Frexml-3.2.9%2Flib%2Frexml%2Fdocument.rb%3A101%3Ain+%60initialize%27%0A%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Fxcodeproj-1.24.0%2Flib%2Fxcodeproj%2Fworkspace.rb%3A83%3Ain+%60new%27%0A%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Fxcodeproj-1.24.0%2Flib%2Fxcodeproj%2Fworkspace.rb%3A83%3Ain+%60from_s%27%0A%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Fxcodeproj-1.24.0%2Flib%2Fxcodeproj%2Fworkspace.rb%3A66%3Ain+%60new_from_xcworkspace%27%0A%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Fcocoapods-1.15.2%2Flib%2Fcocoapods%2Finstaller%2Fuser_project_integrator.rb%3A102%3Ain+%60create_workspace%27%0A%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Fcocoapods-1.15.2%2Flib%2Fcocoapods%2Finstaller%2Fuser_project_integrator.rb%3A71%3Ain+%60integrate%21%27%0A%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Fcocoapods-1.15.2%2Flib%2Fcocoapods%2Finstaller.rb%3A929%3Ain+%60block+in+integrate_user_project%27%0A%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Fcocoapods-1.15.2%2Flib%2Fcocoapods%2Fuser_interface.rb%3A64%3Ain+%60section%27%0A%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Fcocoapods-1.15.2%2Flib%2Fcocoapods%2Finstaller.rb%3A925%3Ain+%60integrate_user_project%27%0A%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Fcocoapods-1.15.2%2Flib%2Fcocoapods%2Finstaller.rb%3A185%3Ain+%60integrate%27%0A%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Fcocoapods-1.15.2%2Flib%2Fcocoapods%2Finstaller.rb%3A170%3Ain+%60install%21%27%0A%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Fcocoapods-1.15.2%2Flib%2Fcocoapods%2Fcommand%2Finstall.rb%3A52%3Ain+%60run%27%0A%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Fclaide-1.1.0%2Flib%2Fclaide%2Fcommand.rb%3A334%3Ain+%60run%27%0A%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Fcocoapods-1.15.2%2Flib%2Fcocoapods%2Fcommand.rb%3A52%3Ain+%60run%27%0A%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Fcocoapods-1.15.2%2Fbin%2Fpod%3A55%3Ain+%60%3Ctop+%28required%29%3E%27%0A%2Fusr%2Flocal%2Fbin%2Fpod%3A23%3Ain+%60load%27%0A%2Fusr%2Flocal%2Fbin%2Fpod%3A23%3Ain+%60%3Cmain%3E%27%0A...%0Awrong+argument+type+String+%28expected+Regexp%29%0ALine%3A+1%0APosition%3A+38%0ALast+80+unconsumed+characters%3A%0A%3C%3Fxml+version%3D%221.0%22+encoding%3D%22UTF-8%22%3F%3E&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Searching for inspections failed: undefined method `map' for nil:NilClass

**Comment by aadishsamir123** [comment]
The above is an entirely different issue. I am experiencing LoadError, you are experiencing TypeError.
