### ISSUE TITLE
Xcode16.0 pod init is error

### ISSUE THREAD

**Issue by BestiOSDev** [CocoaPods/CocoaPods#12573]
When I create a new xcode project, then Execute the pod init command.
I think the reason for this error is that xcode16.0 is not supported on cocoapods

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/dzb0409/.rvm/gems/ruby-3.3.0/bin/pod init
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.15.2
        Ruby : ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [arm64-darwin23]
    RubyGems : 3.5.7
        Host : macOS 15.1 (24B5035e)
       Xcode : 16.0 (16A242)
         Git : git version 2.39.5 (Apple Git-154)
Ruby lib dir : /Users/dzb0409/.rvm/rubies/ruby-3.3.0/lib
Repositories : aliyun-aliyun-specs - git - https://github.com/aliyun/aliyun-specs.git @ 5457ee2ee49f94e5687ec53c008f29ed4714d9fc

               immotors-capp-ios-l-app-ios-podspecs - git - ssh://git@gitlab-ha.immotors.com:1122/capp/iOS/l-app-ios-podspecs @ 821dfc23dc1886c84553f6baf7036c0c1ebfdfd1

               immotors-capp-ios-venderspecs - git - ssh://git@gitlab-ha.immotors.com:1122/capp/iOS/venderSpecs/Specs.git @ 7bf39b526ab5da00d61c4c96b459cb90f068e4a4

               trunk - CDN - https://cdn.cocoapods.org/
               volcengine-volcengine-specs - git - https://github.com/volcengine/volcengine-specs.git @ 60d32f378206b0a1a18f4427323e509f661c3758

```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-ppbuild     : 1.0.9
cocoapods-search      : 1.0.1
cocoapods-sled        : 0.0.2
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
cocoapods-zjbinary    : 1.0.0
```

### Error

```
RuntimeError - `PBXGroup` attempted to initialize an object with unknown ISA `PBXFileSystemSynchronizedRootGroup` from attributes: `{"isa"=>"PBXFileSystemSynchronizedRootGroup", "exceptions"=>["7BE5D4042C941DBE00029FDF"], "path"=>"LGExample", "sourceTree"=>"<group>"}`
If this ISA was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new
/Users/dzb0409/.rvm/gems/ruby-3.3.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:359:in `rescue in object_with_uuid'
/Users/dzb0409/.rvm/gems/ruby-3.3.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:349:in `object_with_uuid'
/Users/dzb0409/.rvm/gems/ruby-3.3.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:300:in `block (2 levels) in configure_with_plist'
/Users/dzb0409/.rvm/gems/ruby-3.3.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:299:in `each'
/Users/dzb0409/.rvm/gems/ruby-3.3.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:299:in `block in configure_with_plist'
/Users/dzb0409/.rvm/gems/ruby-3.3.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:296:in `each'
/Users/dzb0409/.rvm/gems/ruby-3.3.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:296:in `configure_with_plist'
/Users/dzb0409/.rvm/gems/ruby-3.3.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project.rb:272:in `new_from_plist'
/Users/dzb0409/.rvm/gems/ruby-3.3.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:350:in `object_with_uuid'
/Users/dzb0409/.rvm/gems/ruby-3.3.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:290:in `block in configure_with_plist'
/Users/dzb0409/.rvm/gems/ruby-3.3.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:287:in `each'
/Users/dzb0409/.rvm/gems/ruby-3.3.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:287:in `configure_with_plist'
/Users/dzb0409/.rvm/gems/ruby-3.3.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project.rb:272:in `new_from_plist'
/Users/dzb0409/.rvm/gems/ruby-3.3.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project.rb:213:in `initialize_from_file'
/Users/dzb0409/.rvm/gems/ruby-3.3.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project.rb:113:in `open'
/Users/dzb0409/.rvm/gems/ruby-3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/command/init.rb:41:in `validate!'
/Users/dzb0409/.rvm/gems/ruby-3.3.0/gems/claide-1.1.0/lib/claide/command.rb:333:in `run'
/Users/dzb0409/.rvm/gems/ruby-3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:52:in `run'
/Users/dzb0409/.rvm/gems/ruby-3.3.0/gems/cocoapods-1.15.2/bin/pod:55:in `<top (required)>'
/Users/dzb0409/.rvm/gems/ruby-3.3.0/bin/pod:25:in `load'
/Users/dzb0409/.rvm/gems/ruby-3.3.0/bin/pod:25:in `<main>'
/Users/dzb0409/.rvm/gems/ruby-3.3.0/bin/ruby_executable_hooks:22:in `eval'
/Users/dzb0409/.rvm/gems/ruby-3.3.0/bin/ruby_executable_hooks:22:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=%60PBXGroup%60+attempted+to+initialize+an+object+with+unknown+ISA+%60PBXFileSystemSynchronizedRootGroup%60+from+attributes%3A+%60%7B%22isa%22%3D%3E%22PBXFileSystemSynchronizedRootGroup%22%2C+%22exceptions%22%3D%3E%5B%227BE5D4042C941DBE00029FDF%22%5D%2C+%22path%22%3D%3E%22LGExample%22%2C+%22sourceTree%22%3D%3E%22%3Cgroup%3E%22%7D%60%0AIf+this+ISA+was+generated+by+Xcode+please+file+an+issue%3A+https%3A%2F%2Fgithub.com%2FCocoaPods%2FXcodeproj%2Fissues%2Fnew&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Searching for inspections failed: undefined method `map' for nil

**Comment by iramons** [comment]
+ 1

**Comment by manikandanprabhur** [comment]
https://github.com/CocoaPods/CocoaPods/issues/12583#issuecomment-2357470707
