### ISSUE TITLE
f none exists, create a ticket, with the template displayed above, on: https://github.com/CocoaPods/CocoaPods/issues/new  Be sure to first read the contributing guide for details on how to properly submit a ticket: https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md  Don't forget to anonymize any private data!  Looking for related issues on cocoapods/cocoapods... Searching for inspections failed: undefined method `map' for nil

### ISSUE THREAD

**Issue by KingSering** [CocoaPods/CocoaPods#12585]
Last login: Wed Sep 18 11:25:51 on ttys000
mac@MacdeMacBook-Pro ~ % cd /Users/mac/Downloads/QianXunDemo 
mac@MacdeMacBook-Pro QianXunDemo % pod install
Analyzing dependencies
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/Cellar/cocoapods/1.15.2_1/libexec/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.15.2
        Ruby : ruby 3.3.5 (2024-09-03 revision ef084cc8f4) [x86_64-darwin23]
    RubyGems : 3.5.18
        Host : macOS 14.4.1 (23E224)
       Xcode :  ()
         Git : git version 2.39.3 (Apple Git-146)
Ruby lib dir : /usr/local/Cellar/ruby/3.3.5/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'QianXunDemo' do
# Comment the next line if you don't want to use dynamic frameworks
use_frameworks!
pod 'KRProgressHUD'
pod 'SnapKit'
pod 'Toast-Swift', '~> 5.0.1'
pod 'PullToRefreshKit'
pod 'HandyJSON'
pod 'Alamofire'
pod 'IQKeyboardManagerSwift'
pod 'RxSwift'
pod 'RxCocoa'
pod 'lottie-ios'
pod 'Google-Mobile-Ads-SDK'
pod 'FirebaseRemoteConfig'
pod 'FBSDKCoreKit'
pod 'Kingfisher'
target 'QianXunDemoTests' do
inherit! :search_paths
# Pods for testing
end
target 'QianXunDemoUITests' do
# Pods for testing
end

end


post_install do |installer|
installer.pods_project.targets.each do |target|
target.build_configurations.each do |config|
config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
end
end
end
```

### Error

```
JSON::ParserError - Failed to parse JSON at file: '/Users/mac/.cocoapods/repos/trunk/Specs/a/a/6/Kingfisher/5.13.0/Kingfisher.podspec.json'.

unexpected token at '{
  "name": "Kingfisher",
  "version": "5.13.0",
  "summary": "A lightweight and pure Swift implemented library for downloading and cacheing image from the web.",
  "description": "Kingfisher is a powerful and pure Swift implemented library for downloading and cacheing image from the web. It provides you a chance to use pure Swift alternation in your next app.\n\n* Everything in Kingfisher goes asynchronously, not only downloading, but also caching. That means you can never worry about blocking your UI thread.\n* Multiple-layer cache. Downloaded image will be cached in both memory and disk. So there is no need to download it again and this could boost your app dramatically.\n* Cache management. You can set the max duration or size the cache could take. And the cache will also be cleaned automatically to prevent taking too much resource.\n* Modern framework. Kingfisher uses `NSURLSession` and the latest technology of GCD, which makes it a strong and swift framework. It also provides you easy APIs to use.\n* Cancellable processing task. You can cancel the downloading or retriving image process if it is not needed anymore.\n* Independent components. You can use the downloader or caching system separately. Or even create your own cache based on Kingfisher's code.\n* Options to decompress the image in background before render it, which could improve the UI performance.\n* A category over `UIImageView` for setting image from an url directly.",
  "homepage": "https://github.com/onevcat/Kingfisher",
  "scree'
/usr/local/Cellar/cocoapods/1.15.2_1/libexec/gems/cocoapods-core-1.15.2/lib/cocoapods-core/specification/json.rb:66:in `rescue in from_json'
/usr/local/Cellar/cocoapods/1.15.2_1/libexec/gems/cocoapods-core-1.15.2/lib/cocoapods-core/specification/json.rb:61:in `from_json'
/usr/local/Cellar/cocoapods/1.15.2_1/libexec/gems/cocoapods-core-1.15.2/lib/cocoapods-core/specification.rb:759:in `from_string'
/usr/local/Cellar/cocoapods/1.15.2_1/libexec/gems/cocoapods-core-1.15.2/lib/cocoapods-core/specification.rb:733:in `from_file'
/usr/local/Cellar/cocoapods/1.15.2_1/libexec/gems/cocoapods-core-1.15.2/lib/cocoapods-core/source.rb:188:in `specification'
/usr/local/Cellar/cocoapods/1.15.2_1/libexec/gems/cocoapods-1.15.2/lib/cocoapods/resolver/lazy_specification.rb:37:in `specification'
/usr/local/Cellar/ruby/3.3.5/lib/ruby/3.3.0/delegate.rb:348:in `block in delegating_block'
/usr/local/Cellar/ruby/3.3.5/lib/ruby/3.3.0/delegate.rb:349:in `block in delegating_block'
/usr/local/Cellar/cocoapods/1.15.2_1/libexec/gems/cocoapods-1.15.2/lib/cocoapods/resolver.rb:178:in `dependencies_for'
/usr/local/Cellar/cocoapods/1.15.2_1/libexec/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:18:in `block in dependencies_for'
/usr/local/Cellar/cocoapods/1.15.2_1/libexec/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:77:in `with_no_such_dependency_error_handling'
/usr/local/Cellar/cocoapods/1.15.2_1/libexec/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:17:in `dependencies_for'
/usr/local/Cellar/cocoapods/1.15.2_1/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:809:in `block in group_possibilities'
/usr/local/Cellar/cocoapods/1.15.2_1/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:808:in `reverse_each'
/usr/local/Cellar/cocoapods/1.15.2_1/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:808:in `group_possibilities'
/usr/local/Cellar/cocoapods/1.15.2_1/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:779:in `possibilities_for_requirement'
/usr/local/Cellar/cocoapods/1.15.2_1/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:761:in `push_state_for_requirements'
/usr/local/Cellar/cocoapods/1.15.2_1/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:696:in `attempt_to_filter_existing_spec'
/usr/local/Cellar/cocoapods/1.15.2_1/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:672:in `attempt_to_activate'
/usr/local/Cellar/cocoapods/1.15.2_1/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:254:in `process_topmost_state'
/usr/local/Cellar/cocoapods/1.15.2_1/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:182:in `resolve'
/usr/local/Cellar/cocoapods/1.15.2_1/libexec/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in `resolve'
/usr/local/Cellar/cocoapods/1.15.2_1/libexec/gems/cocoapods-1.15.2/lib/cocoapods/resolver.rb:94:in `resolve'
/usr/local/Cellar/cocoapods/1.15.2_1/libexec/gems/cocoapods-1.15.2/lib/cocoapods/installer/analyzer.rb:1082:in `block in resolve_dependencies'
/usr/local/Cellar/cocoapods/1.15.2_1/libexec/gems/cocoapods-1.15.2/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/Cellar/cocoapods/1.15.2_1/libexec/gems/cocoapods-1.15.2/lib/cocoapods/installer/analyzer.rb:1080:in `resolve_dependencies'
/usr/local/Cellar/cocoapods/1.15.2_1/libexec/gems/cocoapods-1.15.2/lib/cocoapods/installer/analyzer.rb:125:in `analyze'
/usr/local/Cellar/cocoapods/1.15.2_1/libexec/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:422:in `analyze'
/usr/local/Cellar/cocoapods/1.15.2_1/libexec/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:244:in `block in resolve_dependencies'
/usr/local/Cellar/cocoapods/1.15.2_1/libexec/gems/cocoapods-1.15.2/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/Cellar/cocoapods/1.15.2_1/libexec/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:243:in `resolve_dependencies'
/usr/local/Cellar/cocoapods/1.15.2_1/libexec/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:162:in `install!'
/usr/local/Cellar/cocoapods/1.15.2_1/libexec/gems/cocoapods-1.15.2/lib/cocoapods/command/install.rb:52:in `run'
/usr/local/Cellar/cocoapods/1.15.2_1/libexec/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/usr/local/Cellar/cocoapods/1.15.2_1/libexec/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:52:in `run'
/usr/local/Cellar/cocoapods/1.15.2_1/libexec/gems/cocoapods-1.15.2/bin/pod:55:in `<top (required)>'
/usr/local/Cellar/cocoapods/1.15.2_1/libexec/bin/pod:25:in `load'
/usr/local/Cellar/cocoapods/1.15.2_1/libexec/bin/pod:25:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=Failed+to+parse+JSON+at+file%3A+%27%2FUsers%2Fmac%2F.cocoapods%2Frepos%2Ftrunk%2FSpecs%2Fa%2Fa%2F6%2FKingfisher%2F5.13.0%2FKingfisher.podspec.json%27.%0A%0Aunexpected+token+at+%27%7B%0A++%22name%22%3A+%22Kingfisher%22%2C%0A++%22version%22%3A+%225.13.0%22%2C%0A++%22summary%22%3A+%22A+lightweight+and+pure+Swift+implemented+library+for+downloading+and+cacheing+image+from+the+web.%22%2C%0A++%22description%22%3A+%22Kingfisher+is+a+powerful+and+pure+Swift+implemented+library+for+downloading+and+cacheing+image+from+the+web.+It+provides+you+a+chance+to+use+pure+Swift+alternation+in+your+next+app.%5Cn%5Cn%2A+Everything+in+Kingfisher+goes+asynchronously%2C+not+only+downloading%2C+but+also+caching.+That+means+you+can+never+worry+about+blocking+your+UI+thread.%5Cn%2A+Multiple-layer+cache.+Downloaded+image+will+be+cached+in+both+memory+and+disk.+So+there+is+no+need+to+download+it+again+and+this+could+boost+your+app+dramatically.%5Cn%2A+Cache+management.+You+can+set+the+max+duration+or+size+the+cache+could+take.+And+the+cache+will+also+be+cleaned+automatically+to+prevent+taking+too+much+resource.%5Cn%2A+Modern+framework.+Kingfisher+uses+%60NSURLSession%60+and+the+latest+technology+of+GCD%2C+which+makes+it+a+strong+and+swift+framework.+It+also+provides+you+easy+APIs+to+use.%5Cn%2A+Cancellable+processing+task.+You+can+cancel+the+downloading+or+retriving+image+process+if+it+is+not+needed+anymore.%5Cn%2A+Independent+components.+You+can+use+the+downloader+or+caching+system+separately.+Or+even+create+your+own+cache+based+on+Kingfisher%27s+code.%5Cn%2A+Options+to+decompress+the+image+in+background+before+render+it%2C+which+could+improve+the+UI+performance.%5Cn%2A+A+category+over+%60UIImageView%60+for+setting+image+from+an+url+directly.%22%2C%0A++%22homepage%22%3A+%22https%3A%2F%2Fgithub.com%2Fonevcat%2FKingfisher%22%2C%0A++%22scree%27&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Searching for inspections failed: undefined method `map' for nil
mac@MacdeMacBook-Pro QianXunDemo %

**Comment by XiangyuBi0519** [comment]
Same Issue, are you using Xcode beta?

**Comment by TanjimaKothiya** [comment]
https://github.com/CocoaPods/CocoaPods/issues/12583#issuecomment-2357470707
