### ISSUE TITLE
pod init failed in Xcode 16

### ISSUE THREAD

**Issue by manikandanprabhur** [CocoaPods/CocoaPods#12583]
――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod init
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.15.2
        Ruby : ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.arm64e-darwin23]
    RubyGems : 3.0.3.1
        Host : macOS 14.6.1 (23G93)
       Xcode : 16.0 (16A242d)
         Git : git version 2.39.5 (Apple Git-154)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Error

```
RuntimeError - `PBXGroup` attempted to initialize an object with unknown ISA `PBXFileSystemSynchronizedRootGroup` from attributes: `{"isa"=>"PBXFileSystemSynchronizedRootGroup", "exceptions"=>["2AB3B2832C995E4700273321"], "explicitFileTypes"=>{}, "explicitFolders"=>[], "path"=>"DemoSample", "sourceTree"=>"<group>"}`
If this ISA was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.23.0/lib/xcodeproj/project/object.rb:359:in `rescue in object_with_uuid'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.23.0/lib/xcodeproj/project/object.rb:349:in `object_with_uuid'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.23.0/lib/xcodeproj/project/object.rb:300:in `block (2 levels) in configure_with_plist'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.23.0/lib/xcodeproj/project/object.rb:299:in `each'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.23.0/lib/xcodeproj/project/object.rb:299:in `block in configure_with_plist'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.23.0/lib/xcodeproj/project/object.rb:296:in `each'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.23.0/lib/xcodeproj/project/object.rb:296:in `configure_with_plist'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.23.0/lib/xcodeproj/project.rb:272:in `new_from_plist'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.23.0/lib/xcodeproj/project/object.rb:350:in `object_with_uuid'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.23.0/lib/xcodeproj/project/object.rb:290:in `block in configure_with_plist'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.23.0/lib/xcodeproj/project/object.rb:287:in `each'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.23.0/lib/xcodeproj/project/object.rb:287:in `configure_with_plist'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.23.0/lib/xcodeproj/project.rb:272:in `new_from_plist'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.23.0/lib/xcodeproj/project.rb:213:in `initialize_from_file'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.23.0/lib/xcodeproj/project.rb:113:in `open'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/command/init.rb:41:in `validate!'
/Library/Ruby/Gems/2.6.0/gems/claide-1.1.0/lib/claide/command.rb:333:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=%60PBXGroup%60+attempted+to+initialize+an+object+with+unknown+ISA+%60PBXFileSystemSynchronizedRootGroup%60+from+attributes%3A+%60%7B%22isa%22%3D%3E%22PBXFileSystemSynchronizedRootGroup%22%2C+%22exceptions%22%3D%3E%5B%222AB3B2832C995E4700273321%22%5D%2C+%22explicitFileTypes%22%3D%3E%7B%7D%2C+%22explicitFolders%22%3D%3E%5B%5D%2C+%22path%22%3D%3E%22DemoSample%22%2C+%22sourceTree%22%3D%3E%22%3Cgroup%3E%22%7D%60%0AIf+this+ISA+was+generated+by+Xcode+please+file+an+issue%3A+https%3A%2F%2Fgithub.com%2FCocoaPods%2FXcodeproj%2Fissues%2Fnew&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Searching for inspections failed: undefined method `map' for nil:NilClass

**Comment by iramzyy** [comment]
Same error

**Comment by amovexu** [comment]
waiting for update

**Comment by manikandanprabhur** [comment]
Please follow the below steps to fix this issue

**Step 1**: Right click project Folder in Xcode and convert to group

<img width="360" alt="Screenshot 2024-09-18 at 9 50 46 AM" src="https://github.com/user-attachments/assets/3d65c826-e427-4750-a56b-fc8e6635603a">

**Step 2**: right click **projectname.xcodeproj** file and select Show Package Contents
you can see the file **project.pbxproj** and open with texteditor

Remove the following lines in this file
**minimizedProjectReferenceProxies = 1;
preferredProjectObjectVersion = 77;**

Also update the below version
objectVersion = 77; to objectVersion = 56;

Now you can pod init and install with your project

**Comment by GengJian** [comment]
> Please follow the below steps to fix this issue
> 
> **Step 1**: Right click project Folder in Xcode and convert to group
> 
> <img alt="Screenshot 2024-09-18 at 9 50 46 AM" width="360" src="https://private-user-images.githubusercontent.com/49630957/368419739-3d65c826-e427-4750-a56b-fc8e6635603a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MTM3MDIsIm5iZiI6MTcyNjcxMzQwMiwicGF0aCI6Ii80OTYzMDk1Ny8zNjg0MTk3MzktM2Q2NWM4MjYtZTQyNy00NzUwLWE1NmItZmM4ZTY2MzU2MDNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDAyMzY0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhN2FjNzEzNzBlNjI4MDJjOTk0YjA2MGY1ZTMxZmQ2MmUwOTY0ZWQwNTIyYzc2YzBiYzQwMjYyMTRlNmQ0M2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QvaIbTE6n9d0cLiXtYR4YvQHoQfbFY3ufqFsXJil1F0">
> **Step 2**: right click **projectname.xcodeproj** file and select Show Package Contents you can see the file **project.pbxproj** and open with texteditor
> 
> Remove the following lines in this file **minimizedProjectReferenceProxies = 1; preferredProjectObjectVersion = 77;**
> 
> Also update the below version objectVersion = 77; to objectVersion = 56;
> 
> Now you can pod init and install with your project

It's working.

**Comment by WM520** [comment]
不能解决

**Comment by WM520** [comment]
> Please follow the below steps to fix this issue
> 
> **Step 1**: Right click project Folder in Xcode and convert to group
> 
> <img alt="Screenshot 2024-09-18 at 9 50 46 AM" width="360" src="https://private-user-images.githubusercontent.com/49630957/368419739-3d65c826-e427-4750-a56b-fc8e6635603a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MjMwMTIsIm5iZiI6MTcyNjgyMjcxMiwicGF0aCI6Ii80OTYzMDk1Ny8zNjg0MTk3MzktM2Q2NWM4MjYtZTQyNy00NzUwLWE1NmItZmM4ZTY2MzU2MDNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDA4NTgzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmZWY2OTNkMjBjNTUxYjU1Yjg1NDM4M2E0NTUzNzFjODgwMzM5MzEzYjQwYzRhMWJmN2QwYmNjODk4YzlkNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vArdsdR0v0GuOE_-3Gxu1x8o2Msvgpoe111a7Jh1we8">
> **Step 2**: right click **projectname.xcodeproj** file and select Show Package Contents you can see the file **project.pbxproj** and open with texteditor
> 
> Remove the following lines in this file **minimizedProjectReferenceProxies = 1; preferredProjectObjectVersion = 77;**
> 
> Also update the below version objectVersion = 77; to objectVersion = 56;
> 
> Now you can pod init and install with your project

hi ， sorry，I can't slove

**Comment by dulifu** [comment]
> 不能解决

我按照上面的方法解决了，你看看是不是步骤错了，或者也可以看看我的解决步骤：https://juejin.cn/post/7416270933789900815

**Comment by yingFormJiang** [comment]
same error

**Comment by androbotech** [comment]
Same error here, did nothing but just pod init on a fresh xcode project, and I tried editing the lines / converting to groups.

**Comment by axel-stig-andersson** [comment]
> Same error here, did nothing but just pod init on a fresh xcode project, and I tried editing the lines / converting to groups.

Same here, modifying the pbxproj file further by removing the mentioned ISA PBXFileSystemSynchronizedRootGroup block like others have suggested allows me to init Pods (with warnings), but generates further errors on build. Editing the pbxproj file is not a stable workaround, waiting for CocoaPods to address it further.

**Comment by kundancodelab** [comment]
I am also getting the same error .

**Comment by Amdian** [comment]
> Please follow the below steps to fix this issue
> 
> **Step 1**: Right click project Folder in Xcode and convert to group
> 
> <img alt="Screenshot 2024-09-18 at 9 50 46 AM" width="360" src="https://private-user-images.githubusercontent.com/49630957/368419739-3d65c826-e427-4750-a56b-fc8e6635603a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNjEzMjMsIm5iZiI6MTcyNzE2MTAyMywicGF0aCI6Ii80OTYzMDk1Ny8zNjg0MTk3MzktM2Q2NWM4MjYtZTQyNy00NzUwLWE1NmItZmM4ZTY2MzU2MDNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDA2NTcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5Mjc4NTk0NTUxY2JkZTdkODU2MTg3ZWY0MjcxMzNhNDQyMGJmMzE2MjY4ZjUyNWFjNTBjOGM3NWI4ZjhmZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.l-gcW66sb6eSICmL5_vT7ZAPGIEprRJvKXzxBulkcOY">
> **Step 2**: right click **projectname.xcodeproj** file and select Show Package Contents you can see the file **project.pbxproj** and open with texteditor
> 
> Remove the following lines in this file **minimizedProjectReferenceProxies = 1; preferredProjectObjectVersion = 77;**
> 
> Also update the below version objectVersion = 77; to objectVersion = 56;
> 
> Now you can pod init and install with your project

well, after I did this, it worked

**Comment by peterpaulis** [comment]
+1 would love for this to be fixed

**Comment by im12345dev** [comment]
Any news about this issue?

**Comment by twototwoto** [comment]
我遇到了类似问题，执行本文的操作步骤后，又遇到如下问题。(本地CocoaPods版本号为：1.15.2)

> RuntimeError - `PBXGroup` attempted to initialize an object with unknown ISA `PBXFileSystemSynchronizedRootGroup` from attributes: `{"isa"=>"PBXFileSystemSynchronizedRootGroup", "path"=>"XXXTests", "sourceTree"=>"<group>"}`

按https://stackoverflow.com/questions/78984326/cocoapods-pod-init-fails-with-unknown-isa-pbxfilesystemsynchronizedrootgroup-e 中的如下步骤解决了问题。

> I am facing same issue in iOS 18.0 and XCode 16
Try this step by step it will be resolved.
Close Xcode
Go to your project folder remove Pods & Podfile.lock
Right Click on YOUR_PROJECT_NAME.xcodeproj Show Package Contents then open project.pbxproj
Replace every PBXFileSystemSynchronizedRootGroup with PBXGroup
Search for objectVersion should be like that objectVersion = 56; if not replace by 56
Pod install
Enjoy:)

**Comment by iOSDevDipesh** [comment]
Fixing Pod Init Failure in Xcode 16.0 | Step-by-Step Guide#Xcode16 #pod #podinit

https://youtu.be/DfxEByfscfk

**Comment by robert-f-woodward** [comment]
Hi, it still failed with me. I was building a framework and had SwiftTesting selected. I changed it to XCTest and it worked

**Comment by iOSDevDipesh** [comment]
Can you please send me a log in detail.

**Comment by robert-f-woodward** [comment]
Dipesh, 

also: MacBook Pro M3 Max, Sequoia 16.0

here is my log output

pod init

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/Cellar/cocoapods/1.15.2/libexec/bin/pod init
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.15.2
        Ruby : ruby 3.3.2 (2024-05-30 revision e5a195edf6) [x86_64-darwin22]
    RubyGems : 3.5.11
        Host : macOS 15.0 (24A335)
       Xcode : 16.0 (16A242d)
         Git : git version 2.39.5 (Apple Git-154)
Ruby lib dir : /usr/local/Cellar/ruby/3.3.2/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ b21f24314e124b547cd90d0ca7aa59ea974ba023

               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Error

```
RuntimeError - `PBXGroup` attempted to initialize an object with unknown ISA `PBXFileSystemSynchronizedRootGroup` from attributes: `{"isa"=>"PBXFileSystemSynchronizedRootGroup", "exceptions"=>["35FEAD582CA827B0003A8B06"], "path"=>"***", "sourceTree"=>"<group>"}`
If this ISA was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new
/usr/local/Cellar/cocoapods/1.15.2/libexec/gems/xcodeproj-1.24.0/lib/xcodeproj/project/object.rb:359:in `rescue in object_with_uuid'
/usr/local/Cellar/cocoapods/1.15.2/libexec/gems/xcodeproj-1.24.0/lib/xcodeproj/project/object.rb:349:in `object_with_uuid'
/usr/local/Cellar/cocoapods/1.15.2/libexec/gems/xcodeproj-1.24.0/lib/xcodeproj/project/object.rb:300:in `block (2 levels) in configure_with_plist'
/usr/local/Cellar/cocoapods/1.15.2/libexec/gems/xcodeproj-1.24.0/lib/xcodeproj/project/object.rb:299:in `each'
/usr/local/Cellar/cocoapods/1.15.2/libexec/gems/xcodeproj-1.24.0/lib/xcodeproj/project/object.rb:299:in `block in configure_with_plist'
/usr/local/Cellar/cocoapods/1.15.2/libexec/gems/xcodeproj-1.24.0/lib/xcodeproj/project/object.rb:296:in `each'
/usr/local/Cellar/cocoapods/1.15.2/libexec/gems/xcodeproj-1.24.0/lib/xcodeproj/project/object.rb:296:in `configure_with_plist'
/usr/local/Cellar/cocoapods/1.15.2/libexec/gems/xcodeproj-1.24.0/lib/xcodeproj/project.rb:272:in `new_from_plist'
/usr/local/Cellar/cocoapods/1.15.2/libexec/gems/xcodeproj-1.24.0/lib/xcodeproj/project/object.rb:350:in `object_with_uuid'
/usr/local/Cellar/cocoapods/1.15.2/libexec/gems/xcodeproj-1.24.0/lib/xcodeproj/project/object.rb:290:in `block in configure_with_plist'
/usr/local/Cellar/cocoapods/1.15.2/libexec/gems/xcodeproj-1.24.0/lib/xcodeproj/project/object.rb:287:in `each'
/usr/local/Cellar/cocoapods/1.15.2/libexec/gems/xcodeproj-1.24.0/lib/xcodeproj/project/object.rb:287:in `configure_with_plist'
/usr/local/Cellar/cocoapods/1.15.2/libexec/gems/xcodeproj-1.24.0/lib/xcodeproj/project.rb:272:in `new_from_plist'
/usr/local/Cellar/cocoapods/1.15.2/libexec/gems/xcodeproj-1.24.0/lib/xcodeproj/project.rb:213:in `initialize_from_file'
/usr/local/Cellar/cocoapods/1.15.2/libexec/gems/xcodeproj-1.24.0/lib/xcodeproj/project.rb:113:in `open'
/usr/local/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/command/init.rb:41:in `validate!'
/usr/local/Cellar/cocoapods/1.15.2/libexec/gems/claide-1.1.0/lib/claide/command.rb:333:in `run'
/usr/local/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:52:in `run'
/usr/local/Cellar/cocoapods/1.15.2/libexec/gems/cocoapods-1.15.2/bin/pod:55:in `<top (required)>'
/usr/local/Cellar/cocoapods/1.15.2/libexec/bin/pod:25:in `load'
/usr/local/Cellar/cocoapods/1.15.2/libexec/bin/pod:25:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=%60PBXGroup%60+attempted+to+initialize+an+object+with+unknown+ISA+%60PBXFileSystemSynchronizedRootGroup%60+from+attributes%3A+%60%7B%22isa%22%3D%3E%22PBXFileSystemSynchronizedRootGroup%22%2C+%22exceptions%22%3D%3E%5B%2235FEAD582CA827B0003A8B06%22%5D%2C+%22path%22%3D%3E%22***%22%2C+%22sourceTree%22%3D%3E%22%3Cgroup%3E%22%7D%60%0AIf+this+ISA+was+generated+by+Xcode+please+file+an+issue%3A+https%3A%2F%2Fgithub.com%2FCocoaPods%2FXcodeproj%2Fissues%2Fnew&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Searching for inspections failed: undefined method `map' for nil

**Comment by vmsilva** [comment]
same problem here with onesignal on react-native

**Comment by BinGoBinBin** [comment]
You need to perform the "Convert to group" operation on all directories, including the Test directory.

**Comment by MMSuperD** [comment]
> I am also getting the same error .

delete Tests and UITests  ，TestsTarget and UITestsTarget,  pod init success

**Comment by martg3** [comment]
The method functions correctly, but issues arise when attempting to run or build the project, preventing it from executing or compiling successfully.

```
error: Sandbox: bash(84265) deny(1) file-write-create Pods/resources-Pods/resources-to-copy-app.txt: Operation not permitted
realpath: illegal option -- m
usage: realpath [-q] [path ...]
:20: error: Unexpected failure

```

**Comment by gabe-push** [comment]
> You need to perform the "Convert to group" operation on all directories, including the Test directory.

thank you so much!! This works ^

**Comment by elite-mob** [comment]
> Please follow the below steps to fix this issue
> 
> **Step 1**: Right click project Folder in Xcode and convert to group
> 
> <img alt="Screenshot 2024-09-18 at 9 50 46 AM" width="360" src="https://private-user-images.githubusercontent.com/49630957/368419739-3d65c826-e427-4750-a56b-fc8e6635603a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5NjA4MDQsIm5iZiI6MTcyODk2MDUwNCwicGF0aCI6Ii80OTYzMDk1Ny8zNjg0MTk3MzktM2Q2NWM4MjYtZTQyNy00NzUwLWE1NmItZmM4ZTY2MzU2MDNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDAyNDgyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0MTk2N2RiNGJhNDNkMDczNzU4MjI4YzU5YjIzZjg4YzNkMWJiZWFhMDIxOWY0MzZmOWRmMTBmYTk5YjcyMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mH7Z89TADinSJizn0y7VnTnEF0m-vCh02O3DjxxMi3Y">
> **Step 2**: right click **projectname.xcodeproj** file and select Show Package Contents you can see the file **project.pbxproj** and open with texteditor
> 
> Remove the following lines in this file **minimizedProjectReferenceProxies = 1; preferredProjectObjectVersion = 77;**
> 
> Also update the below version objectVersion = 77; to objectVersion = 56;
> 
> Now you can pod init and install with your project

@manikandanprabhur Bingo! You saved my day! Thanks!

**Comment by shafqat-muneer** [comment]
> Please follow the below steps to fix this issue
> 
> **Step 1**: Right click project Folder in Xcode and convert to group
> 
> <img alt="Screenshot 2024-09-18 at 9 50 46 AM" width="360" src="https://private-user-images.githubusercontent.com/49630957/368419739-3d65c826-e427-4750-a56b-fc8e6635603a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MjE5NTYsIm5iZiI6MTcyOTUyMTY1NiwicGF0aCI6Ii80OTYzMDk1Ny8zNjg0MTk3MzktM2Q2NWM4MjYtZTQyNy00NzUwLWE1NmItZmM4ZTY2MzU2MDNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDE0NDA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViZjkwNjIxMmMyZDVlYjQyMjdmMWQyMzk2N2ZjODdjMjQyZmM3YWQ2ODEzZGM0MmYyMjRkY2JiN2Q0ZmU0ZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PwA1bcNB6CWslteQkB7nlgOlMD54CuBR9oyOSHHO6gU">
> **Step 2**: right click **projectname.xcodeproj** file and select Show Package Contents you can see the file **project.pbxproj** and open with texteditor
> 
> Remove the following lines in this file **minimizedProjectReferenceProxies = 1; preferredProjectObjectVersion = 77;**
> 
> Also update the below version objectVersion = 77; to objectVersion = 56;
> 
> Now you can pod init and install with your project

We also need to select `convert to group` option for `[Project_Name]Tests` and `[Project_Name]UITests` folders.

**Comment by Chrishyh** [comment]
Thank you very much, but it seems like what I found is【minimizedProjectReferenceProxies】

**Comment by Fatemeh-Balaei** [comment]
This approach worked for me:

step 1: changing the Testing system from default value to None like shown in the image when defining the project.

<img width="713" alt="Screenshot 2024-10-26 at 6 20 57 PM" src="https://github.com/user-attachments/assets/283a2cd9-11de-42e6-ba0f-48d2bf224b3d">

step 2: follow the procedure explained above:

https://github.com/CocoaPods/CocoaPods/issues/12583#issuecomment-2357470707

or

 if you want to keep the default setting (Swift Testing with XCTest UI Tests) add the extra step: 'convert to group' for [Project_Name]Tests and [Project_Name]UITests folders.' as mentioned in 

https://github.com/CocoaPods/CocoaPods/issues/12583#issuecomment-2426932838

**Comment by adampei** [comment]
> Please follow the below steps to fix this issue
> 
> **Step 1**: Right click project Folder in Xcode and convert to group
> 
> <img alt="Screenshot 2024-09-18 at 9 50 46 AM" width="360" src="https://private-user-images.githubusercontent.com/49630957/368419739-3d65c826-e427-4750-a56b-fc8e6635603a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NTM2MTYsIm5iZiI6MTczMDQ1MzMxNiwicGF0aCI6Ii80OTYzMDk1Ny8zNjg0MTk3MzktM2Q2NWM4MjYtZTQyNy00NzUwLWE1NmItZmM4ZTY2MzU2MDNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDA5MjgzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmNDFjN2E3MWNlMDQ0MjZlNzcxNDgyYTQzNGJjMzcwMzc2YWQ0ODAxYmJhOGUxZjVmYTUwMjA2OTA2NDgyMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6Xu5WhXjQD-WkWFqYBuBOQ0wZe2yMU2tmP6LZjvznzk">
> **Step 2**: right click **projectname.xcodeproj** file and select Show Package Contents you can see the file **project.pbxproj** and open with texteditor
> 
> Remove the following lines in this file **minimizedProjectReferenceProxies = 1; preferredProjectObjectVersion = 77;**
> 
> Also update the below version objectVersion = 77; to objectVersion = 56;
> 
> Now you can pod init and install with your project

finally open build settings and search `ENABLE_USER_SCRIPT_SANDBOXING ` set `User Script Sandboxing` to `NO`


<img width="538" alt="image" src="https://github.com/user-attachments/assets/7d86aba5-5157-47b6-8b52-27b0a7366fed">

It works again.

**Comment by iOSDevDipesh** [comment]
Fixing Pod Init Failure in Xcode 16.0 | Step-by-Step Guide#Xcode16 #pod #podinit

https://youtu.be/DfxEByfscfk

**Comment by trickyc0d3r** [comment]
Nice... Ebanutsa kakoy fix blyad. Pryam vot zaebis.

**Comment by akshayAtThareja** [comment]
Try this step by step it will be resolved.

```
- Close XCode
- Go to your project folder remove Pods & Podfile.lock
- Right Click on YOUR_PROJECT_NAME.xcodeproj Show Package Contents then open project.pbxproj
- Replace every PBXFileSystemSynchronizedRootGroup with PBXGroup
- Search for objectVersion should be like that objectVersion = 56; if not replace by 56
- Pod install
```

**Comment by yuioo1748** [comment]
Update CocoaPods:
```
brew update
brew install cocoapods
pod repo update
pod --version
```

**Comment by sagarpatel1137** [comment]
https://youtu.be/DfxEByfscfk?si=YZz6IQ2iaCXm_Kw6

**Comment by WeichengZhang777** [comment]
> Try this step by step it will be resolved.
> 
> ```
> - Close XCode
> - Go to your project folder remove Pods & Podfile.lock
> - Right Click on YOUR_PROJECT_NAME.xcodeproj Show Package Contents then open project.pbxproj
> - Replace every PBXFileSystemSynchronizedRootGroup with PBXGroup
> - Search for objectVersion should be like that objectVersion = 56; if not replace by 56
> - Pod install
> ```

It's working!
