### ISSUE TITLE
Pod init failed on fresh new project

### ISSUE THREAD

**Issue by androbotech** [CocoaPods/CocoaPods#12593]
Just start a new project on XCode, cd to the folder, pod init and you'll get:

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod init
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.15.2
        Ruby : ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.arm64e-darwin24]
    RubyGems : 3.0.3.1
        Host : macOS 15.0 (24A335)
       Xcode : 16.0 (16A242d)
         Git : git version 2.39.5 (Apple Git-154)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Error

```
RuntimeError - `PBXGroup` attempted to initialize an object with unknown ISA `PBXFileSystemSynchronizedRootGroup` from attributes: `{"isa"=>"PBXFileSystemSynchronizedRootGroup", "path"=>"LangeMapTests", "sourceTree"=>"<group>"}`
If this ISA was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:359:in `rescue in object_with_uuid'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:349:in `object_with_uuid'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:300:in `block (2 levels) in configure_with_plist'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:299:in `each'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:299:in `block in configure_with_plist'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:296:in `each'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:296:in `configure_with_plist'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project.rb:272:in `new_from_plist'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:350:in `object_with_uuid'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:290:in `block in configure_with_plist'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:287:in `each'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project/object.rb:287:in `configure_with_plist'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project.rb:272:in `new_from_plist'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project.rb:213:in `initialize_from_file'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.25.0/lib/xcodeproj/project.rb:113:in `open'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/command/init.rb:41:in `validate!'
/Library/Ruby/Gems/2.6.0/gems/claide-1.1.0/lib/claide/command.rb:333:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=%60PBXGroup%60+attempted+to+initialize+an+object+with+unknown+ISA+%60PBXFileSystemSynchronizedRootGroup%60+from+attributes%3A+%60%7B%22isa%22%3D%3E%22PBXFileSystemSynchronizedRootGroup%22%2C+%22path%22%3D%3E%22LangeMapTests%22%2C+%22sourceTree%22%3D%3E%22%3Cgroup%3E%22%7D%60%0AIf+this+ISA+was+generated+by+Xcode+please+file+an+issue%3A+https%3A%2F%2Fgithub.com%2FCocoaPods%2FXcodeproj%2Fissues%2Fnew&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Searching for inspections failed: undefined method `map' for nil:NilClass

**Comment by BestiOSDev** [comment]
https://github.com/CocoaPods/CocoaPods/issues/12583#issuecomment-2357470707 麻烦提 issue 之前 看看别人有没有提过相同的问题

**Comment by yingFormJiang** [comment]
> [#12583 (comment)](https://github.com/CocoaPods/CocoaPods/issues/12583#issuecomment-2357470707) 麻烦提 issue 之前 看看别人有没有提过相同的问题

就不能还是无法解决？我就是同样问题，按照修改，还是有问题

**Comment by BestiOSDev** [comment]
> > [#12583 (comment)](https://github.com/CocoaPods/CocoaPods/issues/12583#issuecomment-2357470707) 麻烦提 issue 之前 看看别人有没有提过相同的问题
> 
> 就不能还是无法解决？我就是同样问题，按照修改，还是有问题

等官方适配 xcode16.0 吧

**Comment by ios-grebennikov** [comment]
I have the same problem

**Comment by melihcelik09** [comment]
i got too this is so annoying...

**Comment by rahulj004** [comment]
if anyone has solution please provide

**Comment by zlfyuan** [comment]
https://github.com/CocoaPods/CocoaPods/issues/12583#issuecomment-2357470707 按照这个方法可行，但是你需要把项目内的所有文件夹都convert成folder！
