### ISSUE TITLE
pod init issue

### ISSUE THREAD

**Issue by ashemag** [CocoaPods/CocoaPods#12611]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace these two lines with what you did.  
`pod init` 

## What did you expect to happen?

ℹ Please replace these two lines with what you expected to happen.  
Init pods 

## What happened instead?

```
RuntimeError - `PBXGroup` attempted to initialize an object with unknown ISA `PBXFileSystemSynchronizedRootGroup` from attributes: `{"isa"=>"PBXFileSystemSynchronizedRootGroup", "exceptions"=>["D524BE2A2CACFFA400B86F5C"], "path"=>"hearth", "sourceTree"=>"<group>"}`
If this ISA was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new
/Users/ashemagalhaes/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/xcodeproj-1.25.1/lib/xcodeproj/project/object.rb:359:in `rescue in object_with_uuid'
/Users/ashemagalhaes/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/xcodeproj-1.25.1/lib/xcodeproj/project/object.rb:349:in `object_with_uuid'
/Users/ashemagalhaes/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/xcodeproj-1.25.1/lib/xcodeproj/project/object.rb:300:in `block (2 levels) in configure_with_plist'
/Users/ashemagalhaes/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/xcodeproj-1.25.1/lib/xcodeproj/project/object.rb:299:in `each'
/Users/ashemagalhaes/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/xcodeproj-1.25.1/lib/xcodeproj/project/object.rb:299:in `block in configure_with_plist'
/Users/ashemagalhaes/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/xcodeproj-1.25.1/lib/xcodeproj/project/object.rb:296:in `each'
/Users/ashemagalhaes/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/xcodeproj-1.25.1/lib/xcodeproj/project/object.rb:296:in `configure_with_plist'
/Users/ashemagalhaes/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/xcodeproj-1.25.1/lib/xcodeproj/project.rb:272:in `new_from_plist'
/Users/ashemagalhaes/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/xcodeproj-1.25.1/lib/xcodeproj/project/object.rb:350:in `object_with_uuid'
/Users/ashemagalhaes/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/xcodeproj-1.25.1/lib/xcodeproj/project/object.rb:290:in `block in configure_with_plist'
/Users/ashemagalhaes/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/xcodeproj-1.25.1/lib/xcodeproj/project/object.rb:287:in `each'
/Users/ashemagalhaes/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/xcodeproj-1.25.1/lib/xcodeproj/project/object.rb:287:in `configure_with_plist'
/Users/ashemagalhaes/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/xcodeproj-1.25.1/lib/xcodeproj/project.rb:272:in `new_from_plist'
/Users/ashemagalhaes/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/xcodeproj-1.25.1/lib/xcodeproj/project.rb:213:in `initialize_from_file'
/Users/ashemagalhaes/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/xcodeproj-1.25.1/lib/xcodeproj/project.rb:113:in `open'
/Users/ashemagalhaes/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-1.15.2/lib/cocoapods/command/init.rb:41:in `validate!'
/Users/ashemagalhaes/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/claide-1.1.0/lib/claide/command.rb:333:in `run'
/Users/ashemagalhaes/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:52:in `run'
/Users/ashemagalhaes/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-1.15.2/bin/pod:55:in `<top (required)>'
/Users/ashemagalhaes/.rbenv/versions/3.1.2/bin/pod:25:in `load'
/Users/ashemagalhaes/.rbenv/versions/3.1.2/bin/pod:25:in `<main>'
```

## CocoaPods Environment

ℹ Please replace these two lines with the output of `pod env`.
### Stack

```
   CocoaPods : 1.15.2
        Ruby : ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin23]
    RubyGems : 3.3.7
        Host : macOS 14.5 (23F79)
       Xcode : 16.0 (16A242d)
         Git : git version 2.39.5 (Apple Git-154)
Ruby lib dir : /Users/ashemagalhaes/.rbenv/versions/3.1.2/lib
Repositories :
```

### Installation Source

```
Executable Path: /Users/ashemagalhaes/.rbenv/versions/3.1.2/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

**Comment by infinigent-solutions** [comment]
@ashemag I got the same issue. Do let me know if any other way works

**Comment by infinigent-solutions** [comment]
@ashemag This work -> [Link](https://github.com/CocoaPods/CocoaPods/issues/12583#issuecomment-2357470707)
