### ISSUE TITLE
pod init not working in xcode 16.0

### ISSUE THREAD

**Issue by arjavYellowPanther** [CocoaPods/CocoaPods#12618]
ast login: Mon Oct  7 20:13:54 on ttys000
arjav@Arjavs-MacBook-Air test % pod init

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/arjav/.rbenv/versions/3.1.2/bin/pod init
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.15.2
        Ruby : ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin23]
    RubyGems : 3.3.7
        Host : macOS 14.5 (23F79)
       Xcode : 16.0 (16A242d)
         Git : git version 2.39.5 (Apple Git-154)
Ruby lib dir : /Users/arjav/.rbenv/versions/3.1.2/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Error

```
RuntimeError - `PBXGroup` attempted to initialize an object with unknown ISA `PBXFileSystemSynchronizedRootGroup` from attributes: `{"isa"=>"PBXFileSystemSynchronizedRootGroup", "path"=>"test", "sourceTree"=>"<group>"}`
If this ISA was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new
/Users/arjav/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/xcodeproj-1.25.1/lib/xcodeproj/project/object.rb:359:in `rescue in object_with_uuid'
/Users/arjav/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/xcodeproj-1.25.1/lib/xcodeproj/project/object.rb:349:in `object_with_uuid'
/Users/arjav/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/xcodeproj-1.25.1/lib/xcodeproj/project/object.rb:300:in `block (2 levels) in configure_with_plist'
/Users/arjav/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/xcodeproj-1.25.1/lib/xcodeproj/project/object.rb:299:in `each'
/Users/arjav/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/xcodeproj-1.25.1/lib/xcodeproj/project/object.rb:299:in `block in configure_with_plist'
/Users/arjav/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/xcodeproj-1.25.1/lib/xcodeproj/project/object.rb:296:in `each'
/Users/arjav/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/xcodeproj-1.25.1/lib/xcodeproj/project/object.rb:296:in `configure_with_plist'
/Users/arjav/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/xcodeproj-1.25.1/lib/xcodeproj/project.rb:272:in `new_from_plist'
/Users/arjav/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/xcodeproj-1.25.1/lib/xcodeproj/project/object.rb:350:in `object_with_uuid'
/Users/arjav/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/xcodeproj-1.25.1/lib/xcodeproj/project/object.rb:290:in `block in configure_with_plist'
/Users/arjav/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/xcodeproj-1.25.1/lib/xcodeproj/project/object.rb:287:in `each'
/Users/arjav/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/xcodeproj-1.25.1/lib/xcodeproj/project/object.rb:287:in `configure_with_plist'
/Users/arjav/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/xcodeproj-1.25.1/lib/xcodeproj/project.rb:272:in `new_from_plist'
/Users/arjav/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/xcodeproj-1.25.1/lib/xcodeproj/project.rb:213:in `initialize_from_file'
/Users/arjav/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/xcodeproj-1.25.1/lib/xcodeproj/project.rb:113:in `open'
/Users/arjav/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-1.15.2/lib/cocoapods/command/init.rb:41:in `validate!'
/Users/arjav/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/claide-1.1.0/lib/claide/command.rb:333:in `run'
/Users/arjav/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:52:in `run'
/Users/arjav/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/cocoapods-1.15.2/bin/pod:55:in `<top (required)>'
/Users/arjav/.rbenv/versions/3.1.2/bin/pod:25:in `load'
/Users/arjav/.rbenv/versions/3.1.2/bin/pod:25:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=%60PBXGroup%60+attempted+to+initialize+an+object+with+unknown+ISA+%60PBXFileSystemSynchronizedRootGroup%60+from+attributes%3A+%60%7B%22isa%22%3D%3E%22PBXFileSystemSynchronizedRootGroup%22%2C+%22path%22%3D%3E%22test%22%2C+%22sourceTree%22%3D%3E%22%3Cgroup%3E%22%7D%60%0AIf+this+ISA+was+generated+by+Xcode+please+file+an+issue%3A+https%3A%2F%2Fgithub.com%2FCocoaPods%2FXcodeproj%2Fissues%2Fnew&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Searching for inspections failed: undefined method `map' for nil:NilClass

      report.issues = results['items'].map { |item| Issue.new(item) }
                                      ^^^^
arjav@Arjavs-MacBook-Air test %

**Comment by Quchangqing** [comment]
Because the folder created by xcode16 is different from the previous one, it is a blue folder.
So it will give you an error in pod install.
Just select the blue folder, right click on it.
There will be a column “Convert to Group”.
After clicking on it, you will see the folder change to the old color, so you can pod normally!

**Comment by arjavYellowPanther** [comment]
Still facing same issue

**Comment by Gustavo0033** [comment]
i'm with the same error here, any solution?

**Comment by eomonteiro** [comment]
#12627

**Comment by dppeak** [comment]
Cocoapods does not support Xcode 16 project format.  If you change the format to Xcode 15.3, everything works.  The objectVersion = 77 is Xcode 16 and objectVersion = 63 is Xcode 15.3.

![image](https://github.com/user-attachments/assets/2ff8eb16-96d9-4a26-9f1e-2b58264a15d9)

**Comment by ryan3721** [comment]
俺也一样

**Comment by longbow007** [comment]
Open your project, click the project file, on the upper right conner, click the Inspector button, change project format to Xcode 15.3, uncheck the "Minimize Project References".
Then click your project target, select "build settings", select "All", search for "enable_user", you'll see "User Script Sandboxing", set it to "No"
This worked for me.

**Comment by swiftymf** [comment]
For anyone coming here later, if you created a new directory in your project by choosing "New Folder", right click on those and "Convert to Group". Took me over an hour to find that answer here: https://stackoverflow.com/questions/79203974/cocoapods-error-unable-to-find-compatibility-version-string-for-object-version

**Comment by swiftymf** [comment]
> Because the folder created by xcode16 is different from the previous one, it is a blue folder. So it will give you an error in pod install. Just select the blue folder, right click on it. There will be a column “Convert to Group”. After clicking on it, you will see the folder change to the old color, so you can pod normally!

This solved it for me, but wasn't totally clear so even after reading this I spent more time trying to find the issue. My main misunderstanding was this applies to folders you've created in your project. Instead of choosing "New Folder" you should choose "New Group". If you have created new folders, right click on those and choose "Convert to Group". Everything worked for me after this.
