### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by FinghtX** [CocoaPods/CocoaPods#12638]
This is my problem :

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/opt/homebrew/opt/ruby/bin/pod init
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.13.0
        Ruby : ruby 3.3.5 (2024-09-03 revision ef084cc8f4) [arm64-darwin24]
    RubyGems : 3.5.21
        Host : macOS 15.0.1 (24A348)
       Xcode : 16.0 (16A242d)
         Git : git version 2.39.5 (Apple Git-154)
Ruby lib dir : /opt/homebrew/Cellar/ruby/3.3.5/lib
Repositories : 
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Error

```
RuntimeError - `PBXGroup` attempted to initialize an object with unknown ISA `PBXFileSystemSynchronizedRootGroup` from attributes: `{"isa"=>"PBXFileSystemSynchronizedRootGroup", "exceptions"=>["6516B9B12CC0309800AF2BA1"], "path"=>"Monde", "sourceTree"=>"<group>"}`
If this ISA was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new
/opt/homebrew/lib/ruby/gems/3.3.0/gems/xcodeproj-1.25.1/lib/xcodeproj/project/object.rb:359:in `rescue in object_with_uuid'
/opt/homebrew/lib/ruby/gems/3.3.0/gems/xcodeproj-1.25.1/lib/xcodeproj/project/object.rb:349:in `object_with_uuid'
/opt/homebrew/lib/ruby/gems/3.3.0/gems/xcodeproj-1.25.1/lib/xcodeproj/project/object.rb:300:in `block (2 levels) in configure_with_plist'
/opt/homebrew/lib/ruby/gems/3.3.0/gems/xcodeproj-1.25.1/lib/xcodeproj/project/object.rb:299:in `each'
/opt/homebrew/lib/ruby/gems/3.3.0/gems/xcodeproj-1.25.1/lib/xcodeproj/project/object.rb:299:in `block in configure_with_plist'
/opt/homebrew/lib/ruby/gems/3.3.0/gems/xcodeproj-1.25.1/lib/xcodeproj/project/object.rb:296:in `each'
/opt/homebrew/lib/ruby/gems/3.3.0/gems/xcodeproj-1.25.1/lib/xcodeproj/project/object.rb:296:in `configure_with_plist'
/opt/homebrew/lib/ruby/gems/3.3.0/gems/xcodeproj-1.25.1/lib/xcodeproj/project.rb:272:in `new_from_plist'
/opt/homebrew/lib/ruby/gems/3.3.0/gems/xcodeproj-1.25.1/lib/xcodeproj/project/object.rb:350:in `object_with_uuid'
/opt/homebrew/lib/ruby/gems/3.3.0/gems/xcodeproj-1.25.1/lib/xcodeproj/project/object.rb:290:in `block in configure_with_plist'
/opt/homebrew/lib/ruby/gems/3.3.0/gems/xcodeproj-1.25.1/lib/xcodeproj/project/object.rb:287:in `each'
/opt/homebrew/lib/ruby/gems/3.3.0/gems/xcodeproj-1.25.1/lib/xcodeproj/project/object.rb:287:in `configure_with_plist'
/opt/homebrew/lib/ruby/gems/3.3.0/gems/xcodeproj-1.25.1/lib/xcodeproj/project.rb:272:in `new_from_plist'
/opt/homebrew/lib/ruby/gems/3.3.0/gems/xcodeproj-1.25.1/lib/xcodeproj/project.rb:213:in `initialize_from_file'
/opt/homebrew/lib/ruby/gems/3.3.0/gems/xcodeproj-1.25.1/lib/xcodeproj/project.rb:113:in `open'
/opt/homebrew/lib/ruby/gems/3.3.0/gems/cocoapods-1.13.0/lib/cocoapods/command/init.rb:41:in `validate!'
/opt/homebrew/lib/ruby/gems/3.3.0/gems/claide-1.1.0/lib/claide/command.rb:333:in `run'
/opt/homebrew/lib/ruby/gems/3.3.0/gems/cocoapods-1.13.0/lib/cocoapods/command.rb:52:in `run'
/opt/homebrew/lib/ruby/gems/3.3.0/gems/cocoapods-1.13.0/bin/pod:55:in `<top (required)>'
/opt/homebrew/opt/ruby/bin/pod:25:in `load'
/opt/homebrew/opt/ruby/bin/pod:25:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=%60PBXGroup%60+attempted+to+initialize+an+object+with+unknown+ISA+%60PBXFileSystemSynchronizedRootGroup%60+from+attributes%3A+%60%7B%22isa%22%3D%3E%22PBXFileSystemSynchronizedRootGroup%22%2C+%22exceptions%22%3D%3E%5B%226516B9B12CC0309800AF2BA1%22%5D%2C+%22path%22%3D%3E%22Monde%22%2C+%22sourceTree%22%3D%3E%22%3Cgroup%3E%22%7D%60%0AIf+this+ISA+was+generated+by+Xcode+please+file+an+issue%3A+https%3A%2F%2Fgithub.com%2FCocoaPods%2FXcodeproj%2Fissues%2Fnew&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Searching for inspections failed: undefined method `map' for nil

**Comment by YvnCde81** [comment]
Hi, 
I have the exact same issue. When I try to "pod init" the exact same message show up in the terminal
<img width="1512" alt="Capture d’écran 2024-10-17 à 09 55 08" src="https://github.com/user-attachments/assets/3c57be56-6f5b-4dfe-8e69-cd1cbed2242f">
.

**Comment by FinghtX** [comment]
What do we do in this situation?

**Comment by YvnCde81** [comment]
I do not know what the source of that problem I'm trying to learn more about it to figure out a solution so far I tried several things so far it didn't work.

**Comment by YvnCde81** [comment]
Did you installed it with Homebrew ?

**Comment by YvnCde81** [comment]
Just to let you know after a day of extensive reacher as to why those error occur. I understand that Xcode 16 is no yes fully supported withe cocoapods just yet. So I'll be working around that until it is fully operational. It should be fixed by a update or something ...😉

**Comment by YvnCde81** [comment]
You're welcome... Sure I let you know.

**Comment by reddytocode** [comment]
Right click >> convert to group on every root folder
