### ISSUE TITLE
pod update results in 'Could not find rexml (>= 3.3.2, < 4.0) - did find: [rexml-3.2.5,rexml-3.1.9.1]

### ISSUE THREAD

**Issue by arnoutvandervorst** [CocoaPods/CocoaPods#12650]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

pod update

## What did you expect to happen?

I expected the pods to update without gem error messages

## What happened instead?

Update all pods
Updating local specs repositories
Analyzing dependencies
Pre-downloading: `FirebaseFirestore` from `https://github.com/invertase/firestore-ios-sdk-frameworks.git`, tag `11.2.0`
cloud_firestore: Using Firebase SDK version '11.2.0' defined in 'firebase_core'
firebase_app_check: Using Firebase SDK version '11.2.0' defined in 'firebase_core'
firebase_auth: Using Firebase SDK version '11.2.0' defined in 'firebase_core'
firebase_core: Using Firebase SDK version '11.2.0' defined in 'firebase_core'
Ignoring ffi-1.12.2 because its extensions are not built. Try: gem pristine ffi --version 1.12.2
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/dependency.rb:313:in `to_specs': Could not find 'rexml' (>= 3.3.2, < 4.0) - did find: [rexml-3.2.5,rexml-3.1.9.1] (Gem::MissingSpecVersionError)
Checked in 'GEM_PATH=/Users/arnoutvandervorst/.gem/ruby/2.6.0:/Library/Ruby/Gems/2.6.0:/opt/homebrew/Cellar/cocoapods/1.15.2_1/libexec:/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0', execute `gem env` for more information
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1449:in `block in activate_dependencies'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `each'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `activate_dependencies'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1420:in `activate'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:223:in `rescue in try_activate'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:216:in `try_activate'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:123:in `rescue in require'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
        from /Users/arnoutvandervorst/.pub-cache/hosted/pub.dev/firebase_crashlytics-4.1.3/ios/crashlytics_add_upload_symbols:1:in `<main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/dependency.rb:313:in `to_specs': Could not find 'rexml' (>= 3.3.2, < 4.0) - did find: [rexml-3.2.5,rexml-3.1.9.1] (Gem::MissingSpecVersionError)
Checked in 'GEM_PATH=/Users/arnoutvandervorst/.gem/ruby/2.6.0:/Library/Ruby/Gems/2.6.0:/opt/homebrew/Cellar/cocoapods/1.15.2_1/libexec:/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0', execute `gem env` for more information
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1449:in `block in activate_dependencies'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `each'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `activate_dependencies'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1420:in `activate'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:217:in `try_activate'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:123:in `rescue in require'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
        from /Users/arnoutvandervorst/.pub-cache/hosted/pub.dev/firebase_crashlytics-4.1.3/ios/crashlytics_add_upload_symbols:1:in `<main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- xcodeproj (LoadError)
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /Users/arnoutvandervorst/.pub-cache/hosted/pub.dev/firebase_crashlytics-4.1.3/ios/crashlytics_add_upload_symbols:1:in `<main>'
firebase_crashlytics: Using Firebase SDK version '11.2.0' defined in 'firebase_core'
firebase_messaging: Using Firebase SDK version '11.2.0' defined in 'firebase_core'
firebase_remote_config: Using Firebase SDK version '11.2.0' defined in 'firebase_core'
firebase_storage: Using Firebase SDK version '11.2.0' defined in 'firebase_core'
Downloading dependencies
Installing FirebaseFirestore 11.2.0
Generating Pods project
Integrating client project
Pod installation complete! There are 22 dependencies from the Podfile and 57 total pods installed.

## CocoaPods Environment

CocoaPods : 1.15.2
        Ruby : ruby 3.3.5 (2024-09-03 revision ef084cc8f4) [arm64-darwin24]
    RubyGems : 3.5.18
        Host : macOS 15.0.1 (24A348)
       Xcode : 16.0 (16A242d)
         Git : git version 2.39.5 (Apple Git-154)
Ruby lib dir : /opt/homebrew/Cellar/ruby/3.3.5/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/

**Comment by arnoutvandervorst** [comment]
Solved by:

sudo gem install rexml -v 3.3.3
