### ISSUE TITLE
pod install bug

### ISSUE THREAD

**Issue by JunkyTang** [CocoaPods/CocoaPods#12697]
――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.16.2
        Ruby : ruby 3.3.5 (2024-09-03 revision ef084cc8f4) [arm64-darwin24]
    RubyGems : 3.5.18
        Host : macOS 15.0.1 (24A348)
       Xcode : 16.1 (16B40)
         Git : git version 2.39.5 (Apple Git-154)
Ruby lib dir : /opt/homebrew/Cellar/ruby/3.3.5/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
use_frameworks!
pod 'Firebase/Analytics'

pod 'URLNavigator'
pod 'PromiseKit', '1.7.7'
pod 'Masonry'
pod 'SVProgressHUD'
pod 'SDWebImage'
pod 'MJExtension'
pod 'RealmSwift', '~> 10.54'
pod 'IQKeyboardManager', '6.5.17'
pod 'YYText'
pod 'SDCycleScrollView'
pod 'JXCategoryView'
pod 'ZXingObjC'
pod 'AFNetworking'
pod 'MJRefresh'
pod 'TZImagePickerController', '3.8.8'
pod 'Qiniu', '7.3.5'
pod 'PGDatePicker'
pod 'YYImage'
pod 'YYWebImage'
pod 'YYCategories'

pod 'JXPhotoBrowser'
pod 'SnapKit'
pod 'TOCropViewController'

pod "CollectionViewWaterfallLayout"

pod 'SnapKit'
pod 'Alamofire'
pod 'AlamofireNetworkActivityIndicator'
pod 'AlamofireImage'
pod 'Disk'
pod 'DeviceKit'
pod 'SwifterSwift/Foundation'
pod 'SwifterSwift/SwiftStdlib'
pod 'NVActivityIndicatorView'
pod 'YPImagePicker'
pod 'EmptyDataSet-Swift'
pod 'ESPullToRefresh'


pod 'ZIPFoundation'
pod 'GPUImage'

#abstract_target 'SharedPods' do
#  
#end

target 'Commom' do
  
  
end

target 'HomeModule' do
  
end

target 'MaterialModule' do
  
end




target 'Luis Link' do
  
end


post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
               end
          end
   end
end
```

### Error

```
NoMethodError - undefined method `name' for an instance of Xcodeproj::Project::Object::PBXSourcesBuildPhase
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/xcodeproj-1.27.0/lib/xcodeproj/project/object/file_system_synchronized_exception_set.rb:57:in `display_name'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/xcodeproj-1.27.0/lib/xcodeproj/project/object.rb:417:in `ascii_plist_annotation'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/xcodeproj-1.27.0/lib/xcodeproj/project.rb:297:in `block in to_ascii_plist'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/xcodeproj-1.27.0/lib/xcodeproj/project.rb:296:in `each'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/xcodeproj-1.27.0/lib/xcodeproj/project.rb:296:in `to_ascii_plist'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/xcodeproj-1.27.0/lib/xcodeproj/project.rb:365:in `block in save'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/atomos-0.1.3/lib/atomos.rb:21:in `block in atomic_write'
/opt/homebrew/Cellar/ruby/3.3.5/lib/ruby/3.3.0/tempfile.rb:371:in `open'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/atomos-0.1.3/lib/atomos.rb:17:in `atomic_write'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/xcodeproj-1.27.0/lib/xcodeproj/project.rb:364:in `save'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/installer/user_project_integrator.rb:158:in `block in save_projects'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/installer/user_project_integrator.rb:156:in `each'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/installer/user_project_integrator.rb:156:in `save_projects'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/installer/user_project_integrator.rb:76:in `integrate!'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:929:in `block in integrate_user_project'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/user_interface.rb:64:in `section'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:925:in `integrate_user_project'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:185:in `integrate'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:170:in `install!'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/command/install.rb:52:in `run'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/command.rb:52:in `run'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/bin/pod:55:in `<top (required)>'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/bin/pod:25:in `load'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/bin/pod:25:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

**Comment by JunkyTang** [comment]
When I created a new framework target, MaterialModule, in the project and ran pod install, an issue occurred. After removing target 'MaterialModule' do, it returned to normal.

Can someone help me?

**Comment by sergiocampama** [comment]
what I did as a workaround is run this command: 

```
sed -i -e 's/build_phase.name/build_phase.display_name/g' "$(gem info xcodeproj --version 1.27.0  | grep 'Installed at:' | cut -d':' -f 2 | xargs)/gems/xcodeproj-1.27.0/lib/xcodeproj/project/object/file_system_synchronized_exception_set.rb" 
```

this fixes the wrong use of `name` to `display_name`, and builds work now

**Comment by helinyu** [comment]
How fix?

**Comment by NealWills** [comment]
I encountered the same problem, but successfully solved it using the following steps

**Comment by xygkevin** [comment]
> ## 我遇到了同样的问题，但使用以下步骤成功解决了它
> 
> ### Step
> 
> ```
> brew install ruby 
> echo 'export PATH="/opt/homebrew/opt/ruby/bin:$PATH"' >> ~/.zshrc
> source ~/.zshrc 
> ```
> 
>  ```
> gem install xcodeproj
> gem update --system 3.6.5 
> ```
> 
>  ```
> sed -i -e 's/build_phase.name/build_phase.display_name/g' "$(gem info xcodeproj --version 1.27.0  | grep 'Installed at:' | cut -d':' -f 2 | xargs)/gems/xcodeproj-1.27.0/lib/xcodeproj/project/object/file_system_synchronized_exception_set.rb"
> ```
> 
> ```
> pod install
> ```
> 
> ### Error
> 
> ```
> NoMethodError - undefined method 'name' for an instance of Xcodeproj::Project::Object::PBXSourcesBuildPhase
> ```
> 
> ### Stack
> 
> ```
>    CocoaPods : 1.16.2
>         Ruby : ruby 3.4.2 (2025-02-15 revision d2930f8e7a) +PRISM [arm64-darwin24]
>     RubyGems : 3.6.5
>         Host : macOS 15.1.1 (24B91)
>        Xcode : 16.1 (16B40)
>          Git : git version 2.45.1
> Ruby lib dir : /opt/homebrew/Cellar/ruby/3.4.2/lib
> Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ e91cabfb9c79b3fbeb6ca3e81c5416a8306b7f10
> 
>                trunk - CDN - https://cdn.cocoapods.org/
> ```
> 
> ### Plugins
> 
> ```
> cocoapods-deintegrate : 1.0.5
> cocoapods-plugins     : 1.0.0
> cocoapods-search      : 1.0.1
> cocoapods-trunk       : 1.6.0
> cocoapods-try         : 1.2.0
> ```

work for me！
