### ISSUE TITLE
IT ONLY WORKS IF I RUN AS ROOT

### ISSUE THREAD

**Issue by mic-automed** [CocoaPods/CocoaPods#12726]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

npm install @react-native-firebase/messaging --save
cd ios
pod deintegrate
pod repo update
pod install

(note: this is AFTER just doing a pod install - which gave the exact same error)

## What did you expect to happen?

Install all pod dependencies correctly.

### Error

```
Errno::EACCES - Permission denied @ rb_sysopen - /Users/hendrikputter/code/ams_care/ios/ams_care.xcodeproj/project.pbxproj
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/xcodeproj-1.27.0/lib/xcodeproj/plist.rb:19:in `read'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/xcodeproj-1.27.0/lib/xcodeproj/plist.rb:19:in `read_from_path'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/xcodeproj-1.27.0/lib/xcodeproj/project.rb:211:in `initialize_from_file'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/xcodeproj-1.27.0/lib/xcodeproj/project.rb:113:in `open'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/installer/analyzer.rb:1194:in `block (2 levels) in inspect_targets_to_integrate'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/installer/analyzer.rb:1193:in `each'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/installer/analyzer.rb:1193:in `block in inspect_targets_to_integrate'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/user_interface.rb:64:in `section'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/installer/analyzer.rb:1188:in `inspect_targets_to_integrate'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/installer/analyzer.rb:107:in `analyze'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:422:in `analyze'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:244:in `block in resolve_dependencies'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/user_interface.rb:64:in `section'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:243:in `resolve_dependencies'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:162:in `install!'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/command/install.rb:52:in `run'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/lib/cocoapods/command.rb:52:in `run'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/gems/cocoapods-1.16.2/bin/pod:55:in `<top (required)>'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/bin/pod:25:in `load'
/opt/homebrew/Cellar/cocoapods/1.16.2/libexec/bin/pod:25:in `<main>'

## CocoaPods Environment

### Stack

```
   CocoaPods : 1.16.2
        Ruby : ruby 3.3.6 (2024-11-05 revision 75015d4c1f) [arm64-darwin23]
    RubyGems : 3.5.23
        Host : macOS 14.5 (23F79)
       Xcode : 15.0.1 (15A507)
         Git : git version 2.39.3 (Apple Git-145)
Ruby lib dir : /opt/homebrew/Cellar/ruby/3.3.6/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /opt/homebrew/Cellar/cocoapods/1.16.2/libexec/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'ams_care' do
  use_expo_modules!

  pod 'FirebaseCore', :modular_headers => true;
  pod 'GoogleUtilities', :modular_headers => true;

  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'ams_careTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
```

**Comment by mic-automed** [comment]
as per the title, if I - instead of running `pod install` try `sudo pod install --allow-root` then it DOES in fact install all the pods - but only in a way that is quite problematic, creating more problems than it solves

I *should* be able to install all pods just as a normal user, with `pod install`
