### ISSUE TITLE
 undefined method `map' for nil

### ISSUE THREAD

**Issue by wccttt** [CocoaPods/CocoaPods#12724]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace these two lines with what you did.  
e.g. Run `pod install`

## What did you expect to happen?

ℹ Please replace these two lines with what you expected to happen.  
e.g. Install all pod dependencies correctly.

## What happened instead?

ℹ Please replace these two lines with of what happened instead.  
e.g. Pod A is missing the subspec B for target C.f'

## CocoaPods Environment

ℹ Please replace these two lines with the output of `pod env`.
  CocoaPods : 1.16.2
        Ruby : ruby 3.3.6 (2024-11-05 revision 75015d4c1f) [x86_64-darwin24]
    RubyGems : 3.5.22
        Host : macOS 15.2 (24C101)
       Xcode : 16.2 (16C5032a)
         Git : git version 2.42.0
Ruby lib dir : /usr/local/lib
Repositories :

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

**Comment by wccttt** [comment]
RuntimeError - `PBXTargetDependency` attempted to initialize an object with unknown ISA `PBXNativeTarget` from attributes: `{"isa"=>"PBXNativeTarget", "buildConfigurationList"=>"726878962D02A472002FABF9", "buildPhases"=>["726878852D02A472002FABF9", "726878862D02A472002FABF9", "726878872D02A472002FABF9"], "buildRules"=>[], "dependencies"=>[], "fileSystemSynchronizedGroups"=>["7268788A2D02A472002FABF9"], "name"=>"SerealPushService", "packageProductDependencies"=>[], "productName"=>"SerealPushService", "productReference"=>"726878892D02A472002FABF9", "productType"=>"com.apple.product-type.app-extension"}`
If this ISA was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new
/usr/local/lib/ruby/gems/3.3.0/gems/xcodeproj-1.27.0/lib/xcodeproj/project/object.rb:359:in `rescue in object_with_uuid'
/usr/local/lib/ruby/gems/3.3.0/gems/xcodeproj-1.27.0/lib/xcodeproj/project/object.rb:349:in `object_with_uuid'
/usr/local/lib/ruby/gems/3.3.0/gems/xcodeproj-1.27.0/lib/xcodeproj/project/object.rb:290:in `block in configure_with_plist'
/usr/local/lib/ruby/gems/3.3.0/gems/xcodeproj-1.27.0/lib/xcodeproj/project/object.rb:287:in `each'
/usr/local/lib/ruby/gems/3.3.0/gems/xcodeproj-1.27.0/lib/xcodeproj/project/object.rb:287:in `configure_with_plist'
/usr/local/lib/ruby/gems/3.3.0/gems/xcodeproj-1.27.0/lib/xcodeproj/project.rb:272:in `new_from_plist'
/usr/local/lib/ruby/gems/3.3.0/gems/xcodeproj-1.27.0/lib/xcodeproj/project/object.rb:350:in `object_with_uuid'
/usr/local/lib/ruby/gems/3.3.0/gems/xcodeproj-1.27.0/lib/xcodeproj/project/object.rb:300:in `block (2 levels) in configure_with_plist'
/usr/local/lib/ruby/gems/3.3.0/gems/xcodeproj-1.27.0/lib/xcodeproj/project/object.rb:299:in `each'
/usr/local/lib/ruby/gems/3.3.0/gems/xcodeproj-1.27.0/lib/xcodeproj/project/object.rb:299:in `block in configure_with_plist'
/usr/local/lib/ruby/gems/3.3.0/gems/xcodeproj-1.27.0/lib/xcodeproj/project/object.rb:296:in `each'
/usr/local/lib/ruby/gems/3.3.0/gems/xcodeproj-1.27.0/lib/xcodeproj/project/object.rb:296:in `configure_with_plist'
/usr/local/lib/ruby/gems/3.3.0/gems/xcodeproj-1.27.0/lib/xcodeproj/project.rb:272:in `new_from_plist'
/usr/local/lib/ruby/gems/3.3.0/gems/xcodeproj-1.27.0/lib/xcodeproj/project/object.rb:350:in `object_with_uuid'
/usr/local/lib/ruby/gems/3.3.0/gems/xcodeproj-1.27.0/lib/xcodeproj/project/object.rb:300:in `block (2 levels) in configure_with_plist'
/usr/local/lib/ruby/gems/3.3.0/gems/xcodeproj-1.27.0/lib/xcodeproj/project/object.rb:299:in `each'
/usr/local/lib/ruby/gems/3.3.0/gems/xcodeproj-1.27.0/lib/xcodeproj/project/object.rb:299:in `block in configure_with_plist'
/usr/local/lib/ruby/gems/3.3.0/gems/xcodeproj-1.27.0/lib/xcodeproj/project/object.rb:296:in `each'
/usr/local/lib/ruby/gems/3.3.0/gems/xcodeproj-1.27.0/lib/xcodeproj/project/object.rb:296:in `configure_with_plist'
/usr/local/lib/ruby/gems/3.3.0/gems/xcodeproj-1.27.0/lib/xcodeproj/project.rb:272:in `new_from_plist'
/usr/local/lib/ruby/gems/3.3.0/gems/xcodeproj-1.27.0/lib/xcodeproj/project.rb:213:in `initialize_from_file'
/usr/local/lib/ruby/gems/3.3.0/gems/xcodeproj-1.27.0/lib/xcodeproj/project.rb:113:in `open'
/usr/local/lib/ruby/gems/3.3.0/gems/cocoapods-1.16.2/lib/cocoapods/installer/analyzer.rb:1194:in `block (2 levels) in inspect_targets_to_integrate'
/usr/local/lib/ruby/gems/3.3.0/gems/cocoapods-1.16.2/lib/cocoapods/installer/analyzer.rb:1193:in `each'
/usr/local/lib/ruby/gems/3.3.0/gems/cocoapods-1.16.2/lib/cocoapods/installer/analyzer.rb:1193:in `block in inspect_targets_to_integrate'
/usr/local/lib/ruby/gems/3.3.0/gems/cocoapods-1.16.2/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/3.3.0/gems/cocoapods-1.16.2/lib/cocoapods/installer/analyzer.rb:1188:in `inspect_targets_to_integrate'
/usr/local/lib/ruby/gems/3.3.0/gems/cocoapods-1.16.2/lib/cocoapods/installer/analyzer.rb:107:in `analyze'
/usr/local/lib/ruby/gems/3.3.0/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:422:in `analyze'
/usr/local/lib/ruby/gems/3.3.0/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:244:in `block in resolve_dependencies'
/usr/local/lib/ruby/gems/3.3.0/gems/cocoapods-1.16.2/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/3.3.0/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:243:in `resolve_dependencies'
/usr/local/lib/ruby/gems/3.3.0/gems/cocoapods-1.16.2/lib/cocoapods/installer.rb:162:in `install!'
/usr/local/lib/ruby/gems/3.3.0/gems/cocoapods-1.16.2/lib/cocoapods/command/install.rb:52:in `run'
/usr/local/lib/ruby/gems/3.3.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/3.3.0/gems/cocoapods-1.16.2/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/3.3.0/gems/cocoapods-1.16.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:25:in `load'
/usr/local/bin/pod:25:in `<main>'
