### ISSUE TITLE
ArgumentError - invalid byte sequence in GB2312

### ISSUE THREAD

**Issue by wangtao2014** [CocoaPods/CocoaPods#1528]
Hello

```
   CocoaPods : 0.27.1
        Ruby : ruby 2.0.0p247 (2013-06-27 revision 41674) [universal.x86_64-darwin13]
    RubyGems : 2.1.10
        Host : Mac OS X 10.9 (13A603)
       Xcode : 5.0 (5A1413)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 807c3784cdacdcfa977a61e18e934e83caabbdb2
```
### Podfile

``` ruby
pod 'JSONKit'
```
### Error

```
ArgumentError - invalid byte sequence in GB2312
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.27.1/lib/cocoapods/installer/pod_source_installer.rb:236:in `glob'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.27.1/lib/cocoapods/installer/pod_source_installer.rb:236:in `glob'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.27.1/lib/cocoapods/installer/pod_source_installer.rb:236:in `clean_paths'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.27.1/lib/cocoapods/installer/pod_source_installer.rb:136:in `clean_installation'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.27.1/lib/cocoapods/installer/pod_source_installer.rb:76:in `clean!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.27.1/lib/cocoapods/installer.rb:276:in `block in clean_pod_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.27.1/lib/cocoapods/installer.rb:275:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.27.1/lib/cocoapods/installer.rb:275:in `clean_pod_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.27.1/lib/cocoapods/installer.rb:105:in `block in download_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.27.1/lib/cocoapods/user_interface.rb:52:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.27.1/lib/cocoapods/installer.rb:101:in `download_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.27.1/lib/cocoapods/installer.rb:87:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.27.1/lib/cocoapods/command/project.rb:38:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.27.1/lib/cocoapods/command/project.rb:68:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.3.2/lib/claide/command.rb:206:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.27.1/lib/cocoapods/command.rb:51:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.27.1/bin/pod:19:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

**Comment by Young1993** [comment]
how to change my mac  terminal’s encoding to utf-8 ?
