### ISSUE TITLE
Malformed version number string >= 1.0.0

### ISSUE THREAD

**Issue by chadwilken** [CocoaPods/CocoaPods#1829]
### Report
- What did you do?
  I went to add a new pod and ran `pod install`, I got the issue with the broken specs so I `rm -rf ~/.cocoapods` and then ran `pod install` again. It keeps giving me the error below about a _malformed version number_.
### Stack

```
   CocoaPods : 0.29.0
        Ruby : ruby 2.0.0p353 (2013-11-22 revision 43784) [x86_64-darwin12.5.0]
    RubyGems : 2.2.1
        Host : Mac OS X 10.9.1 (13B42)
       Xcode : 5.0.2 (5A3005)
Ruby lib dir : /Users/chadwilken/.rvm/rubies/ruby-2.0.0-p353/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 600c649aa4d5043c5fc0cfb4e8d05538b1e8b462
```
### Podfile

``` ruby
platform :ios, '7.0'
pod 'AFNetworking', '1.3.3'
pod 'SignalR-ObjC', '~> 1.0.1'
pod 'DDURLParser'
pod 'Block-KVO'
pod 'RESideMenu', '~> 3.4'
```
### Error

```
ArgumentError - Malformed version number string >= 1.0.0
/Users/chadwilken/.rvm/gems/ruby-2.0.0-p353/gems/cocoapods-core-0.29.0/lib/cocoapods-core/vendor/version.rb:191:in `initialize'
/Users/chadwilken/.rvm/gems/ruby-2.0.0-p353/gems/cocoapods-core-0.29.0/lib/cocoapods-core/version.rb:62:in `initialize'
/Users/chadwilken/.rvm/gems/ruby-2.0.0-p353/gems/cocoapods-core-0.29.0/lib/cocoapods-core/specification.rb:135:in `new'
/Users/chadwilken/.rvm/gems/ruby-2.0.0-p353/gems/cocoapods-core-0.29.0/lib/cocoapods-core/specification.rb:135:in `name_and_version_from_string'
/Users/chadwilken/.rvm/gems/ruby-2.0.0-p353/gems/cocoapods-core-0.29.0/lib/cocoapods-core/lockfile.rb:176:in `block in generate_pod_names_and_versions'
/Users/chadwilken/.rvm/gems/ruby-2.0.0-p353/gems/cocoapods-core-0.29.0/lib/cocoapods-core/lockfile.rb:174:in `each'
/Users/chadwilken/.rvm/gems/ruby-2.0.0-p353/gems/cocoapods-core-0.29.0/lib/cocoapods-core/lockfile.rb:174:in `generate_pod_names_and_versions'
/Users/chadwilken/.rvm/gems/ruby-2.0.0-p353/gems/cocoapods-core-0.29.0/lib/cocoapods-core/lockfile.rb:77:in `pod_names'
/Users/chadwilken/.rvm/gems/ruby-2.0.0-p353/gems/cocoapods-0.29.0/lib/cocoapods/installer/analyzer/sandbox_analyzer.rb:184:in `sandbox_pods'
/Users/chadwilken/.rvm/gems/ruby-2.0.0-p353/gems/cocoapods-0.29.0/lib/cocoapods/installer/analyzer/sandbox_analyzer.rb:74:in `analyze'
/Users/chadwilken/.rvm/gems/ruby-2.0.0-p353/gems/cocoapods-0.29.0/lib/cocoapods/installer/analyzer.rb:320:in `block in generate_sandbox_state'
/Users/chadwilken/.rvm/gems/ruby-2.0.0-p353/gems/cocoapods-0.29.0/lib/cocoapods/user_interface.rb:52:in `section'
/Users/chadwilken/.rvm/gems/ruby-2.0.0-p353/gems/cocoapods-0.29.0/lib/cocoapods/installer/analyzer.rb:318:in `generate_sandbox_state'
/Users/chadwilken/.rvm/gems/ruby-2.0.0-p353/gems/cocoapods-0.29.0/lib/cocoapods/installer/analyzer.rb:60:in `analyze'
/Users/chadwilken/.rvm/gems/ruby-2.0.0-p353/gems/cocoapods-0.29.0/lib/cocoapods/installer.rb:171:in `analyze'
/Users/chadwilken/.rvm/gems/ruby-2.0.0-p353/gems/cocoapods-0.29.0/lib/cocoapods/installer.rb:94:in `block in resolve_dependencies'
/Users/chadwilken/.rvm/gems/ruby-2.0.0-p353/gems/cocoapods-0.29.0/lib/cocoapods/user_interface.rb:52:in `section'
/Users/chadwilken/.rvm/gems/ruby-2.0.0-p353/gems/cocoapods-0.29.0/lib/cocoapods/installer.rb:93:in `resolve_dependencies'
/Users/chadwilken/.rvm/gems/ruby-2.0.0-p353/gems/cocoapods-0.29.0/lib/cocoapods/installer.rb:86:in `install!'
/Users/chadwilken/.rvm/gems/ruby-2.0.0-p353/gems/cocoapods-0.29.0/lib/cocoapods/command/project.rb:38:in `run_install_with_update'
/Users/chadwilken/.rvm/gems/ruby-2.0.0-p353/gems/cocoapods-0.29.0/lib/cocoapods/command/project.rb:68:in `run'
/Users/chadwilken/.rvm/gems/ruby-2.0.0-p353/gems/claide-0.4.0/lib/claide/command.rb:213:in `run'
/Users/chadwilken/.rvm/gems/ruby-2.0.0-p353/gems/cocoapods-0.29.0/lib/cocoapods/command.rb:51:in `run'
/Users/chadwilken/.rvm/gems/ruby-2.0.0-p353/gems/cocoapods-0.29.0/bin/pod:24:in `<top (required)>'
/Users/chadwilken/.rvm/gems/ruby-2.0.0-p353/bin/pod:23:in `load'
/Users/chadwilken/.rvm/gems/ruby-2.0.0-p353/bin/pod:23:in `<main>'
/Users/chadwilken/.rvm/gems/ruby-2.0.0-p353/bin/ruby_executable_hooks:15:in `eval'
/Users/chadwilken/.rvm/gems/ruby-2.0.0-p353/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by SandeepAggarwal** [comment]
@alloy Thanks Man, this also solves my problem.
