### ISSUE TITLE
LoadError - no such file to load

### ISSUE THREAD

**Issue by fuxiaohui** [CocoaPods/CocoaPods#1863]
### Stack

```
   CocoaPods : 0.29.0
        Ruby : ruby 1.8.7 (2012-02-08 patchlevel 358) [universal-darwin13.0]
    RubyGems : 2.2.1
        Host : Mac OS X 10.9.2 (13C64)
       Xcode : 5.0.2 (5A3005)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 0f36f3006e2fdb730ce470a5a3415d35abfdddd3
```
### Error

```
LoadError - no such file to load -- xcodeproj/prebuilt/universal-darwin13.0-1.8.7/xcodeproj_ext
/Library/Ruby/Site/1.8/rubygems/core_ext/kernel_require.rb:55:in `gem_original_require'
/Library/Ruby/Site/1.8/rubygems/core_ext/kernel_require.rb:55:in `require'
/Library/Ruby/Gems/1.8/gems/xcodeproj-0.14.1/lib/xcodeproj/ext.rb:6
/Library/Ruby/Site/1.8/rubygems/core_ext/kernel_require.rb:55:in `gem_original_require'
/Library/Ruby/Site/1.8/rubygems/core_ext/kernel_require.rb:55:in `require'
/Library/Ruby/Gems/1.8/gems/xcodeproj-0.14.1/lib/xcodeproj/project.rb:4
/Library/Ruby/Gems/1.8/gems/cocoapods-0.29.0/lib/cocoapods/command/init.rb:39:in `validate!'
/Library/Ruby/Gems/1.8/gems/claide-0.4.0/lib/claide/command.rb:212:in `run'
/Library/Ruby/Gems/1.8/gems/cocoapods-0.29.0/lib/cocoapods/command.rb:51:in `run'
/Library/Ruby/Gems/1.8/gems/cocoapods-0.29.0/bin/pod:24
/usr/bin/pod:23:in `load'
/usr/bin/pod:23
```

**Comment by Gigha** [comment]
Removing the pod binary (in `/usr/bin/pod`) and uninstalling cocoapods (`sudo gem uninstall cocoapods`) and reinstalling cocoapods (`sudo gem install cocoapods`) worked for me.
