### ISSUE TITLE
Fallback to HTTPS

### ISSUE THREAD

**Issue by DaleLJefferson** [CocoaPods/CocoaPods#204]
At my place of work we have a very restrictive firewall and the git:// port is blocked.

HTTPS is available so it would be great that if git:// fails, https:// should be tried.

```
pod setup --verbose
Cloning spec repo `master' from `git://github.com/CocoaPods/Specs.git'
/usr/bin/git clone 'git://github.com/CocoaPods/Specs.git' master
Cloning into 'master'...
fatal: unable to connect to github.com:
github.com[0: 207.97.227.239]: errno=Operation timed out

Oh no, an error occurred. Please run with `--verbose' and report on https://github.com/CocoaPods/CocoaPods/issues.

No such file or directory - /Users/dale/.cocoapods/master/.git/hooks/pre-commit
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/pathname.rb:812:in `initialize'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/pathname.rb:812:in `open'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/pathname.rb:812:in `open'
/Library/Ruby/Gems/1.8/gems/cocoapods-0.5.1/lib/cocoapods/command/setup.rb:45:in `run'
/Library/Ruby/Gems/1.8/gems/cocoapods-0.5.1/lib/cocoapods/command.rb:53:in `run'
/Library/Ruby/Gems/1.8/gems/cocoapods-0.5.1/bin/pod:11
/usr/bin/pod:19:in `load'
/usr/bin/pod:19
```

Simple clone

```
git clone git://github.com/CocoaPods/Specs.git
Cloning into 'Specs'...
fatal: unable to connect to github.com:
github.com[0: 207.97.227.239]: errno=Operation timed out
```

**Comment by kprofic** [comment]
To solve the problem on client side you can force git to use https:

git config --global url."https://".insteadOf git://
