### ISSUE TITLE
Failed to register trunk user

### ISSUE THREAD

**Issue by JackShi** [CocoaPods/CocoaPods#2174]
I received the following messages when I tried to register a pod trunk user. Can someone please help? Thanks. 

opening connection to trunk.cocoapods.org:443...

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
### Report
- What did you do?
- What did you expect to happen?
- What happened instead?
### Stack

```
   CocoaPods : 0.33.1
        Ruby : ruby 2.0.0p451 (2014-02-24 revision 45167) [universal.x86_64-darwin13]
    RubyGems : 2.0.14
        Host : Mac OS X 10.9.2 (13C1021)
       Xcode : 5.1.1 (5B1008)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ b8f790fee0a2df2e68aa6207c1667f375dcbe1d1
```
### Error

```
SocketError - getaddrinfo: nodename nor servname provided, or not known
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:878:in `initialize'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:878:in `open'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:878:in `block in connect'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:877:in `connect'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:851:in `start'
/Library/Ruby/Gems/2.0.0/gems/nap-0.7.0/lib/rest/request.rb:187:in `perform'
/Library/Ruby/Gems/2.0.0/gems/nap-0.7.0/lib/rest/request.rb:199:in `perform'
/Library/Ruby/Gems/2.0.0/gems/nap-0.7.0/lib/rest.rb:100:in `post'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-0.1.1/lib/pod/command/trunk.rb:323:in `create_request'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-0.1.1/lib/pod/command/trunk.rb:310:in `request_url'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-0.1.1/lib/pod/command/trunk.rb:318:in `request_path'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-0.1.1/lib/pod/command/trunk.rb:70:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.6.1/lib/claide/command.rb:281:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/bin/pod:33:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing github issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=getaddrinfo%3A+nodename+nor+servname+provided%2C+or+not+known&type=Issues

**Comment by nfl404** [comment]
ThanksI met the same error of you, then I changed the DNS, now it success.
