### ISSUE TITLE
Permission denied on `pod install` after completing troubleshooting steps

### ISSUE THREAD

**Issue by lanephillips** [CocoaPods/CocoaPods#2192]
### Report
- What did you do?

I was getting permission errors when I tried to run `pod install`, so I did the following:

```
sudo rm -fr ~/Library/Caches/CocoaPods/
sudo rm -fr ~/.cocoapods/repos/master/
sudo rm -fr Pods/
sudo gem uninstall cocoapods
sudo gem install cocoapods
pod install
```
- What did you expect to happen?

I expected CocoaPods to create the workspace and update the projects.
- What happened instead?

I got the error below.
### Stack

```
   CocoaPods : 0.33.1
        Ruby : ruby 2.0.0p451 (2014-02-24 revision 45167) [universal.x86_64-darwin13]
    RubyGems : 2.0.14
        Host : Mac OS X 10.9.3 (13D65)
       Xcode : 5.1.1 (5B1008)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : 
```
### Podfile

``` ruby
platform :ios, '7.0'

# ignore all warnings from all pods
inhibit_all_warnings!

pod 'Facebook-iOS-SDK', '3.5.3'
pod 'CrittercismSDK', '4.3.1'
pod 'GoogleAnalytics-iOS-SDK', '3.0.1'
pod 'PDKeychainBindingsController', '0.0.1'
pod 'AFNetworking', '1.3.1'
pod 'Reachability', '3.1.1'
pod 'CocoaLumberjack', '1.6.2'
pod 'iVersion', '~> 1.10.6'
pod 'MendeleySDK', '~> 1.5.0'
pod 'AFOAuth1Client', '~> 0.3.1'
pod 'WebViewJavascriptBridge', '~> 4.1.0'
pod 'SLObjectiveCRuntimeAdditions', '~> 1.1.2'
pod 'Mantle', '~> 1.4.1'
pod 'UIColor+Additions', '~> 1.0'
```
### Error

```
Errno::EACCES - Permission denied - /Users/work/.cocoapods/repos
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:245:in `mkdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:245:in `fu_mkdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:219:in `block (2 levels) in mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:217:in `reverse_each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:217:in `block in mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:203:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:203:in `mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:556:in `mkpath'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/command/repo.rb:49:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/user_interface.rb:52:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/command/repo.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/command/setup.rb:86:in `add_master_repo'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/command/setup.rb:42:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/user_interface.rb:52:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/command/setup.rb:34:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/command.rb:41:in `parse'
/Library/Ruby/Gems/2.0.0/gems/claide-0.6.1/lib/claide/command.rb:276:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/bin/pod:33:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

**Comment by VladimirAmiorkov** [comment]
Having the same issues and cannot resolve them, what can I do step by step I am new to cocoapods

**Comment by realmadrid2727** [comment]
I was having this issue after upgrading from 1.0.1 to 1.4.0, and the fix for my particular case was simply renaming the "pods" directory to "Pods".
