### ISSUE TITLE
One workspace with two projects which have different IPHONEOS_DEPLOYMENT_TARGET

### ISSUE THREAD

**Issue by iwill** [CocoaPods/CocoaPods#2234]
### Report

`pod install` to install AFNetworking into ProjectA, but not into ProjectB.
The IPHONEOS_DEPLOYMENT_TARGET -s of ProjectA and ProjectB are different.

```
$ pod install
Analyzing dependencies
Downloading dependencies
Installing AFNetworking (2.2.4)
Generating Pods project
....
[!] Oh no, an error occurred.
```

### Stack

```
   CocoaPods : 0.33.1
        Ruby : ruby 2.0.0p451 (2014-02-24 revision 45167) [universal.x86_64-darwin13]
    RubyGems : 2.0.14
        Host : Mac OS X 10.9.3 (13D65)
       Xcode : 5.1.1 (5B1008)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 0c8207a255595beff8c11e70043da738be3aabee
```

### Podfile

```ruby
workspace 'AllInOne.xcworkspace'
xcodeproj 'ProjectA/ProjectA.xcodeproj'
xcodeproj 'ProjectB/ProjectB.xcodeproj'

target 'ProjectA' do
  platform :ios, '6.0'
  xcodeproj 'ProjectA/ProjectA.xcodeproj'
  pod 'AFNetworking', '~> 2.2'
end

target 'ProjectB' do
  platform :ios, '5.0'
  xcodeproj 'ProjectB/ProjectB.xcodeproj'
end
```

### Error

```
RuntimeError - [Xcodeproj] Consistency issue: build setting `IPHONEOS_DEPLOYMENT_TARGET` has multiple values: `{"Release"=>"6.0", "Debug"=>"6.0", "Distribution"=>"5.0", "AppStore"=>"5.0"}`
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.17.0/lib/xcodeproj/project/object/native_target.rb:82:in `common_resolved_build_setting'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.17.0/lib/xcodeproj/project/object/native_target.rb:113:in `deployment_target'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.17.0/lib/xcodeproj/project/object/native_target.rb:149:in `add_build_configuration'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/installer/target_installer.rb:47:in `block in add_target'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/installer/target_installer.rb:46:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/installer/target_installer.rb:46:in `add_target'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/installer/target_installer/pod_target_installer.rb:15:in `block in install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/user_interface.rb:113:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/installer/target_installer/pod_target_installer.rb:14:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/installer.rb:378:in `block (2 levels) in install_libraries'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/installer.rb:375:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/installer.rb:375:in `block in install_libraries'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/user_interface.rb:113:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/installer.rb:374:in `install_libraries'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/installer.rb:117:in `block in generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/user_interface.rb:52:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/installer.rb:114:in `generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/installer.rb:91:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/command/project.rb:40:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/command/project.rb:70:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.6.1/lib/claide/command.rb:281:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/bin/pod:33:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

**Comment by segiddins** [comment]
Closing this, as this is a scenario we don't necessarily intend to support -- deployment target is one of the settings that must be consistent across different build configurations for a given target.
