### ISSUE TITLE
RuntimeError - [Xcodeproj] Consistency issue: build setting `ARCHS` has multiple values

### ISSUE THREAD

**Issue by DrummerB** [CocoaPods/CocoaPods#2305]
### Report
- What did you do? <br>
  Running `pod install`
- What did you expect to happen?<br>
  No error, installed pods
- What happened instead?<br>
  Error, no installed pods
### Stack

```
   CocoaPods : 0.33.1
        Ruby : ruby 2.0.0p247 (2013-06-27 revision 41674) [universal.x86_64-darwin13]
    RubyGems : 2.2.0
        Host : Mac OS X 10.9.2 (13C64)
       Xcode : 5.1.1 (5B1008)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 1490275daf09f1914bc710b731f584d30e0001e6
```
### Podfile

``` ruby

link_with 'MyTarget'

pod 'CocoaSoundCloudUI', :git => ***
pod 'CocoaSoundCloudAPI', '1.0.2'
pod 'BFKit', :git => ***
pod 'BFNavigationBarDrawer', :git => ***
pod 'BFUpdateManager', :git => ***
```
### Error

```
RuntimeError - [Xcodeproj] Consistency issue: build setting `ARCHS` has multiple values: `{"Debug"=>["armv7", "armv7s"], "Release"=>"$(ARCHS_STANDARD)", "AppStore"=>"$(ARCHS_STANDARD)"}`
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.17.0/lib/xcodeproj/project/object/native_target.rb:82:in `common_resolved_build_setting'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/installer/analyzer.rb:492:in `block in compute_archs_for_target_definition'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/installer/analyzer.rb:491:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/installer/analyzer.rb:491:in `compute_archs_for_target_definition'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/installer/analyzer.rb:520:in `block in compute_target_platforms'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/installer/analyzer.rb:514:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/installer/analyzer.rb:514:in `compute_target_platforms'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/installer/analyzer.rb:55:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/installer.rb:176:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/installer.rb:98:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/user_interface.rb:52:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/installer.rb:97:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/installer.rb:89:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/command/project.rb:40:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/command/project.rb:70:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.6.1/lib/claide/command.rb:281:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/bin/pod:33:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

**Comment by TZXZ** [comment]
I change the Architectures Debug&Release value to the same, in target project_t&project_tTests, then pod install, solve the problem. Like this.
<img width="944" alt="截屏2021-05-28 下午5 44 26" src="https://user-images.githubusercontent.com/16027496/119965677-1bcc8d00-bfdd-11eb-9f2b-7943c28ccc8b.png">
