### ISSUE TITLE
Operation not permitted

### ISSUE THREAD

**Issue by leapfrog-bishalghimire** [CocoaPods/CocoaPods#2365]
### Report
- What did you do?

I have tried following 
http://stackoverflow.com/questions/16049335/cocoapods-pod-install-permission-denied

sudo chown -R username ~/Library/Caches/CocoaPods
sudo chown -R username ~/.cocoapods

which didnt work and also did 
sudo rm -R  ~/Library/Caches/CocoaPods
sudo rm -R  ~/.cocoapods/repos

Also didi,
sudo chmod go-w /usr/local/bin

sudo chmod o-w /usr/local
- What did you expect to happen?
  install pod without permission issue
- What happened instead?

but nothing works and keep on getting 

pod install
Analyzing dependencies
Downloading dependencies
Using AFNetworking (2.3.1)
Using Appboy-iOS-SDK (2.3.1)
Using AviarySDK (3.3.0)
Installing Bolts 1.1.1 (was 1.1.0)
Using CocoaLumberjack (1.6)
Using CrashlyticsFramework (2.2.1)
Using DIYAV (0.2.0)
Using DIYCam (1.3.0)
Using Facebook-iOS-SDK (3.15.1)
Using FlurrySDK (4.3.2)
Using GCPlaceholderTextView (1.0.1)
Using HPGrowingTextView (1.0.1)
Using HockeySDK (3.5.6)
Using MFCache (0.0.1)
Using NewRelicAgent (1.396)
Using PRTween (0.0.1)
Using Routable (0.0.2)
Using SDWebImage (3.7.1)
Using SIAlertView (1.2)
Using SVPullToRefresh (0.4.1)
Using TPKeyboardAvoiding (1.2.3)
Using TSMiniWebBrowser (1.0.1)
Using Underscore.m (0.2.1)
Using apptentive-ios (1.5.3)
Generating Pods project
### Stack

```
   CocoaPods : 0.33.1
        Ruby : ruby 2.0.0p451 (2014-02-24 revision 45167) [universal.x86_64-darwin13]
    RubyGems : 2.4.1
        Host : Mac OS X 10.9.4 (13E28)
       Xcode : 6.0 (6A254o)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ e18f7348d5b296fe75490a1022f93b9b91e81fbb
```
### Podfile

``` ruby
platform :ios, '6.0'
xcodeproj 'Momentage.xcodeproj'

pod 'CocoaLumberjack', '1.6'
pod 'SIAlertView', '1.2'
pod 'TSMiniWebBrowser', '1.0.1'
pod 'DIYCam', '1.3.0'
pod 'Routable', '0.0.2'
pod 'GCPlaceholderTextView', '1.0.1'
pod 'AviarySDK', '3.3.0'
pod 'PRTween', '0.0.1'
pod 'FlurrySDK', '4.3.2'
pod 'Appboy-iOS-SDK', '2.3.1'
pod 'NewRelicAgent', '~> 1.354'
pod 'CrashlyticsFramework', '~> 2.2.1'
pod 'Facebook-iOS-SDK'
pod 'apptentive-ios', '~>1.5.3'
pod 'TPKeyboardAvoiding', '~> 1.2.3'
pod 'AFNetworking', '~> 2.3.1'
pod 'SDWebImage', '~> 3.7.1'
pod 'HockeySDK', '~> 3.5.6'
```
### Error

```
Errno::EPERM - Operation not permitted - /Volumes/Backup/Work/LeapFrog/momentage-ios/Momentage/Pods/Pods-resources.sh
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/generator/copy_resources_script.rb:34:in `chmod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/generator/copy_resources_script.rb:34:in `save_as'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/installer/target_installer/aggregate_target_installer.rb:100:in `block in create_copy_resources_script'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/user_interface.rb:113:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/installer/target_installer/aggregate_target_installer.rb:91:in `create_copy_resources_script'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/installer/target_installer/aggregate_target_installer.rb:20:in `block in install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/user_interface.rb:113:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/installer/target_installer/aggregate_target_installer.rb:14:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/installer.rb:384:in `block (2 levels) in install_libraries'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/installer.rb:381:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/installer.rb:381:in `block in install_libraries'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/user_interface.rb:113:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/installer.rb:374:in `install_libraries'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/installer.rb:117:in `block in generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/user_interface.rb:52:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/installer.rb:114:in `generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/installer.rb:91:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/command/project.rb:40:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/command/project.rb:70:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.6.1/lib/claide/command.rb:281:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/bin/pod:33:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

**Comment by amirr-dotcom** [comment]
How to change permission of project folder?
