### ISSUE TITLE
Crash when reading Xcode project during intergration

### ISSUE THREAD

**Issue by kylef** [CocoaPods/CocoaPods#2483]
This is a reproducible issue, which doesn't happen every time, but it happens often enough when running `pod install --no-repo-update`. The issue appears to be something wrong with the garbage collector in **Apple's** Ruby in this specific context.

This is only reproducible on system ruby. I compiled this version of Ruby myself with debug symbols and it doesn't exhibit the same issue.

Myself and @alloy have tried creating a smaller version of this code to reproduce with no success. Calling the following works fine:

``` ruby
Xcodeproj::PlistHelper.read('/Users/kylef/Projects/cocode/palaver/Palaver.xcodeproj/project.pbxproj')
```

However it's the exact thing that is called during the CocoaPods integration. We have then saved the output of this method to Marshal'ed to disk and then stubbed out `Xcodeproj::PlistHelper.read` to return the marshal'ed version and it also works.

Specifically, it's calling `load_xml_str` on `CFPropertyList::List` which seems to trigger the process of crashing. To be clear, it's not necessarily something that CFPropertyList is doing. But somehow the ruby process is getting into a state where it is crashing in this code path.

``` bash
$ ruby --version
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
```

```
Users/kylef/gems/gems/xcodeproj-0.19.1/lib/xcodeproj/project.rb:175:in `initialize_from_file'
/Users/kylef/gems/gems/xcodeproj-0.19.1/lib/xcodeproj/project.rb:92:in `open'
/Users/kylef/gems/gems/cocoapods-0.34.0.rc2/lib/cocoapods/target/aggregate_target.rb:50:in `user_targets'
/Users/kylef/gems/gems/cocoapods-0.34.0.rc2/lib/cocoapods/installer/user_project_integrator.rb:141:in `block in warn_about_xcconfig_overrides'
/Users/kylef/gems/gems/cocoapods-0.34.0.rc2/lib/cocoapods/installer/user_project_integrator.rb:140:in `each'
/Users/kylef/gems/gems/cocoapods-0.34.0.rc2/lib/cocoapods/installer/user_project_integrator.rb:140:in `warn_about_xcconfig_overrides'
/Users/kylef/gems/gems/cocoapods-0.34.0.rc2/lib/cocoapods/installer/user_project_integrator.rb:63:in `integrate!'
/Users/kylef/gems/gems/cocoapods-0.34.0.rc2/lib/cocoapods/installer.rb:496:in `block in integrate_user_project'
/Users/kylef/gems/gems/cocoapods-0.34.0.rc2/lib/cocoapods/user_interface.rb:49:in `section'
/Users/kylef/gems/gems/cocoapods-0.34.0.rc2/lib/cocoapods/installer.rb:493:in `integrate_user_project'
/Users/kylef/gems/gems/cocoapods-0.34.0.rc2/lib/cocoapods/installer.rb:93:in `install!'
/Users/kylef/gems/gems/cocoapods-0.34.0.rc2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/kylef/gems/gems/cocoapods-0.34.0.rc2/lib/cocoapods/command/project.rb:101:in `run'
/Users/kylef/gems/gems/claide-0.7.0/lib/claide/command.rb:271:in `run'
/Users/kylef/gems/gems/cocoapods-0.34.0.rc2/lib/cocoapods/command.rb:48:in `run'
/Users/kylef/gems/gems/cocoapods-0.34.0.rc2/bin/pod:33:in `<top (required)>'
```

```
(lldb) bt all
* thread #1: tid = 0x2ddee, 0x0000000100049ce9 libruby.2.0.0.dylib`___lldb_unnamed_function877$$libruby.2.0.0.dylib + 178, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
  * frame #0: 0x0000000100049ce9 libruby.2.0.0.dylib`___lldb_unnamed_function877$$libruby.2.0.0.dylib + 178
    frame #1: 0x0000000100044d42 libruby.2.0.0.dylib`rb_gc_finalize_deferred + 74
    frame #2: 0x000000010013a868 libruby.2.0.0.dylib`rb_threadptr_execute_interrupts + 852
    frame #3: 0x0000000100123436 libruby.2.0.0.dylib`___lldb_unnamed_function2527$$libruby.2.0.0.dylib + 15017
    frame #4: 0x000000010012d062 libruby.2.0.0.dylib`___lldb_unnamed_function2579$$libruby.2.0.0.dylib + 139
    frame #5: 0x000000010013265f libruby.2.0.0.dylib`___lldb_unnamed_function2627$$libruby.2.0.0.dylib + 713
    frame #6: 0x0000000100127b5b libruby.2.0.0.dylib`rb_funcall2 + 337
    frame #7: 0x0000000100075b41 libruby.2.0.0.dylib`rb_class_new_instance + 41
    frame #8: 0x0000000100135376 libruby.2.0.0.dylib`___lldb_unnamed_function2664$$libruby.2.0.0.dylib + 814
    frame #9: 0x0000000100122577 libruby.2.0.0.dylib`___lldb_unnamed_function2527$$libruby.2.0.0.dylib + 11242
    frame #10: 0x000000010012d062 libruby.2.0.0.dylib`___lldb_unnamed_function2579$$libruby.2.0.0.dylib + 139
    frame #11: 0x000000010012a86d libruby.2.0.0.dylib`rb_yield + 216
    frame #12: 0x000000010000b38f libruby.2.0.0.dylib`rb_ary_each + 72
    frame #13: 0x0000000100135376 libruby.2.0.0.dylib`___lldb_unnamed_function2664$$libruby.2.0.0.dylib + 814
    frame #14: 0x0000000100134d55 libruby.2.0.0.dylib`___lldb_unnamed_function2663$$libruby.2.0.0.dylib + 614
    frame #15: 0x00000001001224c9 libruby.2.0.0.dylib`___lldb_unnamed_function2527$$libruby.2.0.0.dylib + 11068
    frame #16: 0x000000010012d062 libruby.2.0.0.dylib`___lldb_unnamed_function2579$$libruby.2.0.0.dylib + 139
    frame #17: 0x000000010012cfc4 libruby.2.0.0.dylib`rb_iseq_eval + 366
    frame #18: 0x00000001000384fc libruby.2.0.0.dylib`___lldb_unnamed_function600$$libruby.2.0.0.dylib + 317
    frame #19: 0x000000010003936d libruby.2.0.0.dylib`___lldb_unnamed_function605$$libruby.2.0.0.dylib + 177
    frame #20: 0x0000000100135376 libruby.2.0.0.dylib`___lldb_unnamed_function2664$$libruby.2.0.0.dylib + 814
    frame #21: 0x0000000100134d55 libruby.2.0.0.dylib`___lldb_unnamed_function2663$$libruby.2.0.0.dylib + 614
    frame #22: 0x0000000100122577 libruby.2.0.0.dylib`___lldb_unnamed_function2527$$libruby.2.0.0.dylib + 11242
    frame #23: 0x000000010012d062 libruby.2.0.0.dylib`___lldb_unnamed_function2579$$libruby.2.0.0.dylib + 139
    frame #24: 0x000000010012dbe2 libruby.2.0.0.dylib`rb_iseq_eval_main + 138
    frame #25: 0x00000001000353fc libruby.2.0.0.dylib`___lldb_unnamed_function568$$libruby.2.0.0.dylib + 128
    frame #26: 0x000000010003534d libruby.2.0.0.dylib`ruby_run_node + 78
    frame #27: 0x0000000100000e5a ruby`main + 91
    frame #28: 0x00007fff8b1055c9 libdyld.dylib`start + 1
    frame #29: 0x00007fff8b1055c9 libdyld.dylib`start + 1
```

**Comment by brunojppb** [comment]
@alloy Thanks! works for me too!
