### ISSUE TITLE
Cocoapods 0.34.1 Podspec ssh source

### ISSUE THREAD

**Issue by xavierjurado** [CocoaPods/CocoaPods#2534]
### Report

We are using a private pod repo with a ssh git URI. Prior to the 0.34.1 release, we manually added our private specs repo to our systems via the `pod repo add` command. With the latest release, as recommended, we tried to migrate to the new explicit format of adding the source repo in our Podfiles, but unfortunately cocoapods doesn't seem to be able to parse the URI and fails with the attached error. 

Thanks!
### Stack

```
   CocoaPods : 0.34.1
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin13]
    RubyGems : 2.0.14
        Host : Mac OS X 10.9.5 (13F34)
       Xcode : 6.0.1 (6A317)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ ee50aea4c64e55a09d1cd1b0afe347caf208e5db
```
### Plugins

```
cocoapods-plugins : 0.3.1
cocoapods-trunk   : 0.2.0
cocoapods-try     : 0.4.1
```
### Podfile

``` ruby
source 'git@gitlab.ourcompany.com:ios/specs.git'
source 'https://github.com/CocoaPods/Specs.git'

# edited, if you need more details of our podspec feel free to ask
```
### Error

```
URI::InvalidURIError - bad URI(is not URI?): git@gitlab.ourcompany.com:ios/specs.git
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/common.rb:176:in `split'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/common.rb:211:in `parse'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/common.rb:747:in `parse'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/common.rb:996:in `URI'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/sources_manager.rb:416:in `name_for_url'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/sources_manager.rb:38:in `find_or_create_source_with_url'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/installer/analyzer.rb:385:in `block in sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/installer/analyzer.rb:384:in `map'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/installer/analyzer.rb:384:in `sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/installer/analyzer.rb:172:in `block in update_repositories_if_needed'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/user_interface.rb:49:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/installer/analyzer.rb:171:in `update_repositories_if_needed'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/installer/analyzer.rb:48:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/installer.rb:184:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/installer.rb:106:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/user_interface.rb:49:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/installer.rb:105:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/installer.rb:90:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.7.0/lib/claide/command.rb:271:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/bin/pod:33:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

**Comment by malhal** [comment]
: should be for relative path and / for absolute. Relative paths are not working for me e.g.

`pod 'DefaultGroupedTable', :git => 'ssh://git@git.myhost.com:DefaultGroupedTable.git'`

Fails with:

```
ssh: Could not resolve hostname git.myhost.com:defaultgroupedtable.git: nodename nor servname provided, or not known
fatal: Could not read from remote repository.
```

The only way it would work is with an absolute path:

  `pod 'DefaultGroupedTable', :git => 'ssh://git@git.myhost.com/home/git/DefaultGroupedTable.git'`
