### ISSUE TITLE
[pod update failed]: After upgrading to the latest version (0.34) 

### ISSUE THREAD

**Issue by Aranir** [CocoaPods/CocoaPods#2573]
[!] Unable to load a specification for the plugin `/usr/local/lib/ruby/gems/2.1.0/gems/cocoapods-try-release-fix-0.1.2`
### Report
- What did you do?

pod updated 
- What did you expect to happen?

it would update my pods
- What happened instead?

Got stuck a long time on Analyzing dependencies and ultimatley failed
### Stack

```
   CocoaPods : 0.34.1
        Ruby : ruby 2.1.3p242 (2014-09-19 revision 47630) [x86_64-darwin14.0]
    RubyGems : 2.2.2
        Host : Mac OS X 10.10 (14A379a)
       Xcode : 6.1 (6A1042b)
Ruby lib dir : /usr/local/Cellar/ruby/2.1.3/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ fdbe0831c290e3d319cbd39d15d71fb264e3d916
```
### Plugins

```
cocoapods-plugins : 0.3.1
cocoapods-trunk   : 0.2.0
cocoapods-try     : 0.4.1
```
### Podfile

``` ruby
platform :ios, '7.1'


xcodeproj '....xcodeproj'


target :'...', :exclusive => true do
    pod 'RestKit', :inhibit_warnings => true
    pod 'LibComponentLogging-pods'
    pod 'LibComponentLogging-LogFile'
    pod 'LibComponentLogging-qlog'
end

target :..., :exclusive => true do
    pod 'Kiwi', :inhibit_warnings => true
    pod 'RestKit/Testing'
end

target '...', :exclusive => true do
  pod 'KIF', :inhibit_warnings => true
end
```
### Error

```
Gem::Ext::BuildError - ERROR: Failed to build gem native extension.

    /usr/local/Cellar/ruby/2.1.3/bin/ruby extconf.rb
/usr/local/lib/ruby/site_ruby/2.1.0/rubygems/ext/builder.rb:89:in `run': ERROR: Failed to build gem native extension. (Gem::Ext::BuildError)

    /usr/local/Cellar/ruby/2.1.3/bin/ruby extconf.rb
/usr/local/lib/ruby/site_ruby/2.1.0/rubygems/ext/builder.rb:89:in `run': ERROR: Failed to build gem native extension. (Gem::Ext::BuildError)

    /usr/local/Cellar/ruby/2.1.3/bin/ruby extconf.rb
/usr/local/lib/ruby/site_ruby/2.1.0/rubygems/ext/builder.rb:89:in `run': ERROR: Failed to build gem native extension. (Gem::Ext::BuildError)

    /usr/local/Cellar/ruby/2.1.3/bin/ruby extconf.rb
/usr/local/lib/ruby/site_ruby/2.1.0/rubygems/ext/builder.rb:89:in `run': ERROR: Failed to build gem native extension. (Gem::Ext::BuildError)
```

**Comment by bonebox** [comment]
I'm using system ruby gems (2.0.14) and get this same error when running 'pod update' since updating to CocoaPods 0.36.0.beta.1:

```[!] Unable to load a specification for the plugin `/Library/Ruby/Gems/2.0.0/gems/cocoapods-try-release-fix-0.1.````
  
I reverted back to 0.35.0 and the error went away.  Possibly unrelated, but I've also been getting the following error after running any pod command since several version ago.  I removed CocoaPods completely and reinstalled and it still persists.

```[!] The specification of arguments as a string has been deprecated Pod::Command::Browse: `[NAME]````
