### ISSUE TITLE
pod install returning error

### ISSUE THREAD

**Issue by vineeth615213** [CocoaPods/CocoaPods#2617]
I am using cocoapods for the first time.I got the following error when i tried to run pod install in the project root folder

Setup completed
Analyzing dependencies
usage: git ls-remote [--heads] [--tags]  [-u <exec> | --upload-pack <exec>]
                     [-q|--quiet] [<repository> [<refs>...]]

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
### Report
- What did you do?
- What did you expect to happen?
- What happened instead?
### Stack

```
   CocoaPods : 0.34.1
        Ruby : ruby 2.0.0p451 (2014-02-24 revision 45167) [universal.x86_64-darwin13]
    RubyGems : 2.4.2
        Host : Mac OS X 10.9.4 (13E28)
       Xcode : 6.0.1 (6A317)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ ceb5499ce899073b1768fa59c06b13b1359f5035
```
### Plugins

```
cocoapods-plugins : 0.3.1
cocoapods-trunk   : 0.2.0
cocoapods-try     : 0.4.1
```
### Podfile

``` ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

pod 'AFNetworking', '~> 1.3.4'
pod 'TestFlightSDK', '3.0.2'
pod 'NewRelicAgent'
pod 'CrashlyticsFramework', '~> 2.2'
pod "DRImageHelpers", :git => "https://github.com/darrarski/DRImageHelpers-iOS", :branch => "v1.x"
pod 'MMDrawerController', '0.5.6'
pod 'LookbackSafe'
pod 'KeepLayout', git: 'https://github.com/iMartinKiss/KeepLayout.git', commit: '9641ab993c8261ce7b10ae3c42f8c173c853ef7c'
pod 'Underscore.m'
pod 'GVGoogleBannerView', '~> 1.4'
pod 'GoogleConversionTracking'
pod 'Facebook-iOS-SDK'

link_with 'F1RST-INT', 'F1RST-STAGING', 'F1RST-PROD'
```
### Error

```
NoMethodError - undefined method `downcase' for nil:NilClass
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/sources_manager.rb:385:in `block in source_with_url'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/sources_manager.rb:385:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/sources_manager.rb:385:in `find'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/sources_manager.rb:385:in `source_with_url'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/sources_manager.rb:37:in `find_or_create_source_with_url'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/installer/analyzer.rb:385:in `block in sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/installer/analyzer.rb:384:in `map'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/installer/analyzer.rb:384:in `sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/installer/analyzer.rb:172:in `block in update_repositories_if_needed'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/user_interface.rb:49:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/installer/analyzer.rb:171:in `update_repositories_if_needed'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/installer/analyzer.rb:48:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/installer.rb:184:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/installer.rb:106:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/user_interface.rb:49:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/installer.rb:105:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/installer.rb:90:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.7.0/lib/claide/command.rb:271:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/bin/pod:33:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing github issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=undefined+method+%60downcase%27+for+nil%3ANilClass&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Don't forget to anonymize any private data!

Vineeths-iMacnew:iOS-App vineeth$ pod update
Update all pods
Analyzing dependencies
usage: git ls-remote [--heads] [--tags]  [-u <exec> | --upload-pack <exec>]
                     [-q|--quiet] [<repository> [<refs>...]]

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
### Report
- What did you do?
- What did you expect to happen?
- What happened instead?
### Stack

```
   CocoaPods : 0.34.1
        Ruby : ruby 2.0.0p451 (2014-02-24 revision 45167) [universal.x86_64-darwin13]
    RubyGems : 2.4.2
        Host : Mac OS X 10.9.4 (13E28)
       Xcode : 6.0.1 (6A317)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ ceb5499ce899073b1768fa59c06b13b1359f5035
```
### Plugins

```
cocoapods-plugins : 0.3.1
cocoapods-trunk   : 0.2.0
cocoapods-try     : 0.4.1
```
### Podfile

``` ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

pod 'AFNetworking', '~> 1.3.4'
pod 'TestFlightSDK', '3.0.2'
pod 'NewRelicAgent'
pod 'CrashlyticsFramework', '~> 2.2'
pod "DRImageHelpers", :git => "https://github.com/darrarski/DRImageHelpers-iOS", :branch => "v1.x"
pod 'MMDrawerController', '0.5.6'
pod 'LookbackSafe'
pod 'KeepLayout', git: 'https://github.com/iMartinKiss/KeepLayout.git', commit: '9641ab993c8261ce7b10ae3c42f8c173c853ef7c'
pod 'Underscore.m'
pod 'GVGoogleBannerView', '~> 1.4'
pod 'GoogleConversionTracking'
pod 'Facebook-iOS-SDK'

link_with 'F1RST-INT', 'F1RST-STAGING', 'F1RST-PROD'
```
### Error

```
NoMethodError - undefined method `downcase' for nil:NilClass
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/sources_manager.rb:385:in `block in source_with_url'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/sources_manager.rb:385:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/sources_manager.rb:385:in `find'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/sources_manager.rb:385:in `source_with_url'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/sources_manager.rb:37:in `find_or_create_source_with_url'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/installer/analyzer.rb:385:in `block in sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/installer/analyzer.rb:384:in `map'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/installer/analyzer.rb:384:in `sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/installer/analyzer.rb:172:in `block in update_repositories_if_needed'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/user_interface.rb:49:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/installer/analyzer.rb:171:in `update_repositories_if_needed'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/installer/analyzer.rb:48:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/installer.rb:184:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/installer.rb:106:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/user_interface.rb:49:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/installer.rb:105:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/installer.rb:90:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/command/project.rb:155:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.7.0/lib/claide/command.rb:271:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/bin/pod:33:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing github issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=undefined+method+%60downcase%27+for+nil%3ANilClass&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Don't forget to anonymize any private data!

**Comment by carguezu** [comment]
+1 with the same issue on 0.35.0

**Comment by chenHongbin** [comment]
with the same issue on 0.36.2

**Comment by Rix1212** [comment]
How to resolve this any update ?

**Comment by MickeyHub** [comment]
#4845  `reinstall the cocoapods` works

**Comment by Rix1212** [comment]
ok

**Comment by Rix1212** [comment]
still does not work ?can anyone help ?

**Comment by carguezu** [comment]
@rix1212 unistall previous pods on your machine before install the latest one works for me

**Comment by Rix1212** [comment]
how to do that ?
Can you elaborate in steps?

**Comment by carguezu** [comment]
$ gem uninstall cocoapods

**Comment by Rix1212** [comment]
how to install latest one

**Comment by shanyimin** [comment]
Make sure your `podfile` contains the following information 
```
Pod::Spec.new do |s|
s.name = "DDEBusiness"
s.version = "0.0.1"
s.platform = :ios, "7.0"
s.authors = "dingdone"
s.license = "dingdone"
s.homepage = "http://www.dingdone.com"
s.summary = "dingdone"
s.source = { :git => "http://git.hoge.cn/dingdone_ios_spec/DDEBusiness.git", :tag => "0.0.1" }
```

**Comment by Triffort123** [comment]
Please Uninstall the all cocoa pod file if there via :
for i in $(sudo gem list --local --no-version | grep cocoapods ); do     sudo gem uninstall $i;  done

And install latest via:
gem install cocoapods (if not works then try : sudo gem install cocoapods
Enter admin password. This could take a while.)

**Comment by sathishvgs** [comment]
HI @Rix1212, Did you fixed this issue.

**Comment by harpreetsandc** [comment]
Facing same issue, any leads?
