### ISSUE TITLE
pod install error: NoMethodError - undefined method `files' 

### ISSUE THREAD

**Issue by ivawzh** [CocoaPods/CocoaPods#2662]
I was trying to install `pod 'Firebase', '~> 1.2'` in Cocoapods.

After I ran `pod install`, the following appears:

```
NoMethodError - undefined method `files' for <PBXFileReference path=`Pods` UUID=`3EF9F14519ECB92800667158`>:Xcodeproj::Project::Object::PBXFileReference
/Users/ivawzh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.34.2/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:89:in `set_target_xcconfig'
/Users/ivawzh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.34.2/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:25:in `block (2 levels) in integrate'
/Users/ivawzh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.34.2/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:23:in `each'
/Users/ivawzh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.34.2/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:23:in `block in integrate'
/Users/ivawzh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.34.2/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:22:in `each'
/Users/ivawzh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.34.2/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:22:in `integrate'
/Users/ivawzh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.34.2/lib/cocoapods/installer/user_project_integrator/target_integrator.rb:30:in `block in integrate!'
/Users/ivawzh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.34.2/lib/cocoapods/user_interface.rb:49:in `section'
/Users/ivawzh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.34.2/lib/cocoapods/installer/user_project_integrator/target_integrator.rb:29:in `integrate!'
/Users/ivawzh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.34.2/lib/cocoapods/installer/user_project_integrator.rb:114:in `block in integrate_user_targets'
/Users/ivawzh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.34.2/lib/cocoapods/installer/user_project_integrator.rb:113:in `each'
/Users/ivawzh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.34.2/lib/cocoapods/installer/user_project_integrator.rb:113:in `integrate_user_targets'
/Users/ivawzh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.34.2/lib/cocoapods/installer/user_project_integrator.rb:61:in `integrate!'
/Users/ivawzh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.34.2/lib/cocoapods/installer.rb:496:in `block in integrate_user_project'
/Users/ivawzh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.34.2/lib/cocoapods/user_interface.rb:49:in `section'
/Users/ivawzh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.34.2/lib/cocoapods/installer.rb:493:in `integrate_user_project'
/Users/ivawzh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.34.2/lib/cocoapods/installer.rb:93:in `install!'
/Users/ivawzh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.34.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/ivawzh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.34.2/lib/cocoapods/command/project.rb:101:in `run'
/Users/ivawzh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/claide-0.7.0/lib/claide/command.rb:271:in `run'
/Users/ivawzh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.34.2/lib/cocoapods/command.rb:48:in `run'
/Users/ivawzh/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.34.2/bin/pod:33:in `<top (required)>'
/Users/ivawzh/.rbenv/versions/2.1.2/bin/pod:23:in `load'
/Users/ivawzh/.rbenv/versions/2.1.2/bin/pod:23:in `<main>'
```

**Comment by kylef** [comment]
Closing due to lack of activity, please re-open if you can provide steps to reproduce or an example project as previously requested.

**Comment by pwatts001** [comment]
Hi Guys,

I have this exact same issue.

@ivawzh were you able to resolve it?

Cheers,
Phil

**Comment by JasonGreenAmerica** [comment]
+1

**Comment by themightyoarfish** [comment]
I have a similar problem, not sure if it's the same
```
NoMethodError - undefined method `files' for #<Xcodeproj::Project::Object::PBXFileReference:0x007ff94b356460>
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.4/lib/cocoapods/installer/user_project_integrator/target_integrator.rb:75:in `block in add_pods_library'
```
