### ISSUE TITLE
"pod install" always attempts to clone spec repo to "/cocoapods" for which it has no permission

### ISSUE THREAD

**Issue by reidmain** [CocoaPods/CocoaPods#2723]
### Report
- What did you do?
  Ran "pod install"
- What did you expect to happen?
  Have my pods installed.
- What happened instead?
  It attempted to clone the spec repo (which it shouldn't because I already had it up to date with "pod setup") to "/cocoapods" and error'd out because it doesn't have permission.
### Stack

```
   CocoaPods : 0.34.4
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.0.14
        Host : Mac OS X 10.10 (14A389)
       Xcode : 6.1 (6A1052d)
         Git : git version 1.9.3 (Apple Git-50)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 107f096125437b6688d04942c88c30419eecfe42
```
### Plugins

```
cocoapods-plugins : 0.3.1
cocoapods-trunk   : 0.3.1
cocoapods-try     : 0.4.1
```
### Podfile

``` ruby
source 'git@github.com:/CocoaPods/Specs.git'

platform :ios, '7.0'

pod 'FDModel'
```
### Error

```
pod install --verbose
  Preparing

Analyzing dependencies

Updating spec repositories

Cloning spec repo `/cocoapods` from `git@github.com:/CocoaPods/Specs.git`
  $ /usr/bin/git clone 'git@github.com:/CocoaPods/Specs.git' /cocoapods
  fatal: could not create work tree dir '/cocoapods'.: Permission denied
[!] Unable to add a source with url `git@github.com:/CocoaPods/Specs.git` named `/cocoapods`.
You can try adding it manually in `~/.cocoapods/repos` or via `pod repo add`.

/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/sources_manager.rb:47:in `rescue in find_or_create_source_with_url'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/sources_manager.rb:52:in `find_or_create_source_with_url'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/installer/analyzer.rb:385:in `block in sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/installer/analyzer.rb:384:in `map'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/installer/analyzer.rb:384:in `sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/installer/analyzer.rb:172:in `block in update_repositories_if_needed'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/user_interface.rb:49:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/installer/analyzer.rb:171:in `update_repositories_if_needed'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/installer/analyzer.rb:48:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/installer.rb:184:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/installer.rb:106:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/user_interface.rb:49:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/installer.rb:105:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/installer.rb:90:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.7.0/lib/claide/command.rb:271:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/bin/pod:33:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

**Comment by tuxwearingtux** [comment]
ok i was having that problem

**Comment by tuxwearingtux** [comment]
i need help on macos 11.6.2
