### ISSUE TITLE
"pod install" fails on 0.34.4 with "source 'https://github.com/CocoaPods/Specs.git'" in Podfile

### ISSUE THREAD

**Issue by reidmain** [CocoaPods/CocoaPods#2724]
### Report
- What did you do?
  Ran "pod install"
- What did you expect to happen?
  Have my pods installed.
- What happened instead?
  CocoaPods cloned the spec repo unnecessarily, because I already had it up to date with "pod setup", and then blew up inside a Ruby script.
### Stack

```
   CocoaPods : 0.34.4
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.0.14
        Host : Mac OS X 10.10 (14A389)
       Xcode : 6.1 (6A1052d)
         Git : git version 1.9.3 (Apple Git-50)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ d5592c9332005dacf0900be003d7df1102c8ca91
               master-1 - https://github.com/CocoaPods/Specs.git @ d5592c9332005dacf0900be003d7df1102c8ca91
```
### Plugins

```
cocoapods-plugins : 0.3.1
cocoapods-trunk   : 0.3.1
cocoapods-try     : 0.4.1
```
### Podfile

``` ruby
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'

pod 'FDModel'
```
### Error

```
NoMethodError - undefined method `name' for nil:NilClass
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/installer/analyzer.rb:172:in `block (2 levels) in update_repositories_if_needed'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/installer/analyzer.rb:172:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/installer/analyzer.rb:172:in `block in update_repositories_if_needed'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/user_interface.rb:49:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/installer/analyzer.rb:171:in `update_repositories_if_needed'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/installer/analyzer.rb:48:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/installer.rb:184:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/installer.rb:106:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/user_interface.rb:49:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/installer.rb:105:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/installer.rb:90:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.7.0/lib/claide/command.rb:271:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/bin/pod:33:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

I saw that @alloy wanted some feedback on a similar crash (https://github.com/CocoaPods/CocoaPods/issues/2696#issuecomment-59913567) and I made the change he requested and got the output:

```
pod install
Analyzing dependencies
ORIGINAL URL: https://github.com/CocoaPods/Specs.git
NORMALISED URL TO FIND: https://github.com/cocoapods/specs
NORMALISED SOURCE URL: ssh://git@github.com/cocoapods/specs
Creating shallow clone of spec repo `master-1` from `https://github.com/CocoaPods/Specs.git`
ORIGINAL URL: https://github.com/CocoaPods/Specs.git
NORMALISED URL TO FIND: https://github.com/cocoapods/specs
NORMALISED SOURCE URL: ssh://git@github.com/cocoapods/specs
NORMALISED SOURCE URL: ssh://git@github.com/cocoapods/specs
```

also here is the output of "pod repo":

```
pod repo

master
- Type: git (origin)
- URL:  https://github.com/CocoaPods/Specs.git
- Path: /Users/reid/.cocoapods/repos/master

master-1
- Type: git (origin)
- URL:  https://github.com/CocoaPods/Specs.git
- Path: /Users/reid/.cocoapods/repos/master-1
```

**Comment by SureshBalusu** [comment]
Why does cocoapods Cloning spec repo not coming overtime?

When I say pod install, all files are being installed only if I am able to see the message clone spec repo.... But if I dont see the message(clone spec repo...) in pod install some files are being missed.

**Comment by nathanandersen** [comment]
This issue is still a problem.

**Comment by orta** [comment]
Please don't comment on old threads when there are active issues around the thing you're looking for: #4989
