### ISSUE TITLE
Get error when push to remote with private pod

### ISSUE THREAD

**Issue by khanghoang** [CocoaPods/CocoaPods#2744]
Hi guys, I got this error when I try to push this spec to my remote
### Report
- What did you do?
  I tried this spec to push to my remote.
- What did you expect to happen?
  Push successfully.
- What happened instead?
  I got this error.
### Stack

```
   CocoaPods : 0.34.4
        Ruby : ruby 2.1.1p76 (2014-02-24 revision 45161) [x86_64-darwin12.0]
    RubyGems : 2.2.2
        Host : Mac OS X 10.10 (14A389)
       Xcode : 6.0.1 (6A317)
         Git : git version 1.8.3.4
Ruby lib dir : /Users/hoangtrieukhang/.rvm/rubies/ruby-2.1.1/lib
Repositories : 2359PrivateSpecs - git@github.com:2359media/PrivateSpecs.git @ bcbb2842c05a8c69340a1a07a354e388c1733d55
               khanghoang - https://github.com/khanghoang/MyCocoaPodRepo.git @ 6738b541343cf26965e820b0c6ddf998823dbea8
               master - https://github.com/CocoaPods/Specs.git @ 145fe1ef0cd39a6b6aa476ec1e064ee9f5ad56b4
               MyCocoaPodRepo - git@github.com:khanghoang/MyCocoaPodRepo.git @ 6738b541343cf26965e820b0c6ddf998823dbea8
               PrivateSpecs - https://hoangtrieukhang@bitbucket.org/hoangtrieukhang/privatespecs.git @ 9ad7bba50dd895bb26f490c2ab40c48278726d91
```
### Plugins

```
cocoapods-plugins : 0.3.1
cocoapods-trunk   : 0.3.1
cocoapods-try     : 0.4.1
```
### Error

```
ArgumentError - same file: Specs/KHTableViewController/0.1.1/KHTableViewController.podspec and /Users/hoangtrieukhang/.cocoapods/repos/khanghoang/Specs/KHTableViewController/0.1.1/KHTableViewController.podspec
/Users/hoangtrieukhang/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/fileutils.rb:1572:in `block in fu_each_src_dest'
/Users/hoangtrieukhang/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/fileutils.rb:1587:in `fu_each_src_dest0'
/Users/hoangtrieukhang/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/fileutils.rb:1571:in `fu_each_src_dest'
/Users/hoangtrieukhang/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/fileutils.rb:399:in `cp'
/Users/hoangtrieukhang/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-0.34.4/lib/cocoapods/command/repo/push.rb:142:in `block in add_specs_to_repo'
/Users/hoangtrieukhang/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-0.34.4/lib/cocoapods/command/repo/push.rb:130:in `each'
/Users/hoangtrieukhang/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-0.34.4/lib/cocoapods/command/repo/push.rb:130:in `add_specs_to_repo'
/Users/hoangtrieukhang/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-0.34.4/lib/cocoapods/command/repo/push.rb:45:in `run'
/Users/hoangtrieukhang/.rvm/gems/ruby-2.1.1/gems/claide-0.7.0/lib/claide/command.rb:271:in `run'
/Users/hoangtrieukhang/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-0.34.4/lib/cocoapods/command.rb:50:in `run'
/Users/hoangtrieukhang/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-0.34.4/bin/pod:33:in `<top (required)>'
/Users/hoangtrieukhang/.rvm/gems/ruby-2.1.1/bin/pod:23:in `load'
/Users/hoangtrieukhang/.rvm/gems/ruby-2.1.1/bin/pod:23:in `<main>'
/Users/hoangtrieukhang/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
/Users/hoangtrieukhang/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'
```

I have no idea why it happened 

```
ArgumentError - same file: Specs/KHTableViewController/0.1.1/KHTableViewController.podspec and /Users/hoangtrieukhang/.cocoapods/repos/khanghoang/Specs/KHTableViewController/0.1.1/KHTableViewController.podspec
```

Thanks.

**Comment by aubada-taljo** [comment]
@khanghoang What did you do exactly cause I have the same exact problem, when I try to install pods in my iOS project, it doesn't recognize my private pod and when I try to push it using pod push repo, it gives me the same error you had.

Thank you

**Comment by khanghoang** [comment]
@aubada-taljo when you tried to update the pod or when you created new one?

**Comment by aubada-taljo** [comment]
Adding a new private pod

**Comment by kylef** [comment]
@aubada-taljo did you include the pod repository in your Podfile? https://guides.cocoapods.org/syntax/podfile.html#source

**Comment by premprakash0961988** [comment]
Hi khanghoang, I am also having same issue. This happended to me when I tried to push my private pod for the very first time. 

For one of the private pod, it worked for the first time but now If I am trying to push new version. its giving me ArgumentError - same file:

Can you please let me know what exactly was the issue and how did you fix it.
