### ISSUE TITLE
Errno::EACCES - Permission denied - /Library/Ruby/Gems/2.0.0/extensions/universal-darwin-14

### ISSUE THREAD

**Issue by brennanMKE** [CocoaPods/CocoaPods#2762]
### Report
- What did you do?

I just ran `sudo gem update cocoapods` and then tried running `pod update` on a project which was working with the previous version of CocoaPods.
- What did you expect to happen?

It should just update the current pod dependencies like usual.
- What happened instead?

It got a nasty permissions exception.
### Stack

```
   CocoaPods : 0.34.4
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.2.0
        Host : Mac OS X 10.10 (14A389)
       Xcode : 6.1 (6A1052d)
         Git : git version 1.9.3 (Apple Git-50)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 2c791f78d3d54fec59bd29dae6fc5816fd9c9158
```
### Plugins

```

```
### Podfile

``` ruby
platform :ios, '7.1'

source 'https://github.com/CocoaPods/Specs.git'

def import_pods
    pod 'AFNetworking', '~> 2.4'
    pod 'UIView-Autolayout', '~> 0.2.0'
    pod 'TTTAttributedLabel', '~> 1.10'
    pod 'Haneke', '~> 1.0'
    pod 'CrashlyticsFramework', '~> 2.2'
    pod 'Facebook-iOS-SDK', '~> 3.0'
    pod 'Parse', '~> 1.4'
    pod 'Mixpanel', '~> 2.5'
end

target "AppStaging" do
    import_pods

    # Debugging UI
    pod 'Reveal-iOS-SDK'
end

target "AppProduction" do
    import_pods
end
```
### Error

```
Errno::EACCES - Permission denied - /Library/Ruby/Gems/2.0.0/extensions/universal-darwin-14
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:245:in `mkdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:245:in `fu_mkdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:219:in `block (2 levels) in mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:217:in `reverse_each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:217:in `block in mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:203:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:203:in `mkdir_p'
/Library/Ruby/Site/2.0.0/rubygems/ext/builder.rb:210:in `write_gem_make_out'
/Library/Ruby/Site/2.0.0/rubygems/ext/builder.rb:132:in `build_error'
/Library/Ruby/Site/2.0.0/rubygems/ext/builder.rb:171:in `rescue in build_extension'
/Library/Ruby/Site/2.0.0/rubygems/ext/builder.rb:156:in `build_extension'
/Library/Ruby/Site/2.0.0/rubygems/ext/builder.rb:198:in `block in build_extensions'
/Library/Ruby/Site/2.0.0/rubygems/ext/builder.rb:195:in `each'
/Library/Ruby/Site/2.0.0/rubygems/ext/builder.rb:195:in `build_extensions'
/Library/Ruby/Site/2.0.0/rubygems/specification.rb:1436:in `block in build_extensions'
/Library/Ruby/Site/2.0.0/rubygems/user_interaction.rb:45:in `use_ui'
/Library/Ruby/Site/2.0.0/rubygems/specification.rb:1434:in `build_extensions'
/Library/Ruby/Site/2.0.0/rubygems/stub_specification.rb:60:in `build_extensions'
/Library/Ruby/Site/2.0.0/rubygems/basic_specification.rb:56:in `contains_requirable_file?'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:68:in `block in require'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:67:in `each'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:67:in `find'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:67:in `require'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/sources_manager.rb:310:in `version_information'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/sources_manager.rb:273:in `repo_compatible?'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/sources_manager.rb:337:in `master_repo_functional?'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/command.rb:40:in `parse'
/Library/Ruby/Gems/2.0.0/gems/claide-0.7.0/lib/claide/command.rb:266:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/bin/pod:33:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

**Comment by krummler** [comment]
For people using RVM, update your RVM, that fixed it for me :)

`rum get head`

**Comment by WANGNEWMAN** [comment]
@kylef tks
