### ISSUE TITLE
Error "Errno::ENOENT - No such file or directory"

### ISSUE THREAD

**Issue by djfitz** [CocoaPods/CocoaPods#2767]
### Report
- What did you do?
  Ran pod install on my project.
- What did you expect to happen?
  pods would update and I can build my project.
- What happened instead?
  I got the error below and pod install failed.
- Pertinent Info
  The error happens when I add a new build configuration in Xcode that has a '/' character in it.
  My build configuration is called 

hockey/enterprise staging
### Stack

```
   CocoaPods : 0.34.4
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.0.14
        Host : Mac OS X 10.10 (14A389)
       Xcode : 6.1 (6A1052d)
         Git : git version 1.9.3 (Apple Git-50)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ c08c2a92d8bd1b56a7dd4f60f0bd8909238e0a91
```
### Plugins

```
cocoapods-plugins : 0.3.1
cocoapods-trunk   : 0.3.1
cocoapods-try     : 0.4.1
```
### Podfile

``` ruby
source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!

pod 'AFNetworking', '~> 2.3'
pod 'GoogleAnalytics-iOS-SDK', '~> 3.0.3'
pod 'Apptimize', '~> 1.5.11'
pod 'UIAlertView+Blocks', '~> 0.8'
pod 'Dropbox-iOS-SDK', '~> 1.3.10'
pod 'MagicalRecord', '~> 2.2'
pod 'APAddressBook', '~> 0.1'
pod 'HockeySDK', '~> 3.5.5'
pod 'uservoice-iphone-sdk'
pod 'Tapstream', '~> 2.8'
pod 'CWStatusBarNotification', '~> 2.1'
pod 'MZFormSheetController', '~> 2.4.1'
```
### Error

```
Errno::ENOENT - No such file or directory - /Users/buildserver/Projects/ChartCube/sources/chartcube-ios/Pods/Target Support Files/Pods/Pods.hockey/enterprise staging.xcconfig
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.19.4/lib/xcodeproj/config.rb:82:in `initialize'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.19.4/lib/xcodeproj/config.rb:82:in `open'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.19.4/lib/xcodeproj/config.rb:82:in `open'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.19.4/lib/xcodeproj/config.rb:82:in `save_as'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb:34:in `save_as'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/installer/target_installer/aggregate_target_installer.rb:49:in `block in create_xcconfig_file'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/installer/target_installer/aggregate_target_installer.rb:46:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/installer/target_installer/aggregate_target_installer.rb:46:in `create_xcconfig_file'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/installer/target_installer/aggregate_target_installer.rb:16:in `block in install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/user_interface.rb:110:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/installer/target_installer/aggregate_target_installer.rb:12:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/installer.rb:413:in `block (2 levels) in install_libraries'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/installer.rb:410:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/installer.rb:410:in `block in install_libraries'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/user_interface.rb:110:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/installer.rb:403:in `install_libraries'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/installer.rb:126:in `block in generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/user_interface.rb:49:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/installer.rb:123:in `generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/installer.rb:92:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.7.0/lib/claide/command.rb:271:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/bin/pod:33:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

**Comment by Usipov** [comment]
It sometimes occur when using a wrong apostrophe character
like that http://monosnap.com/image/Q20jjiw5XsP4H0GoeOm78uNHxRe6Sg
