### ISSUE TITLE
Unable to load a specification for the plugin

### ISSUE THREAD

**Issue by objectiveSee** [CocoaPods/CocoaPods#2787]
Trying to update a cocoapod and down the rabbit hole.  I updated to `0.35.0.rc1` and did the `gem install xcodeproj` suggestion.  now I am stuck here.  Any help appreciated

```
$ pod update
Update all pods
Analyzing dependencies
[!] Unable to load a specification for the plugin `/Library/Ruby/Gems/2.0.0/gems/cocoapods-try-release-fix-0.1.2`
/Users/danny/.gem/ruby/2.0.0/gems/cocoapods-0.35.0.rc1/lib/cocoapods/user_interface/error_report.rb:13:in `report': incompatible character encodings: UTF-8 and ASCII-8BIT (Encoding::CompatibilityError)
    from /Users/danny/.gem/ruby/2.0.0/gems/cocoapods-0.35.0.rc1/lib/cocoapods/command.rb:59:in `report_error'
    from /Library/Ruby/Gems/2.0.0/gems/claide-0.7.0/lib/claide/command.rb:300:in `handle_exception'
    from /Library/Ruby/Gems/2.0.0/gems/claide-0.7.0/lib/claide/command.rb:274:in `rescue in run'
    from /Library/Ruby/Gems/2.0.0/gems/claide-0.7.0/lib/claide/command.rb:264:in `run'
    from /Users/danny/.gem/ruby/2.0.0/gems/cocoapods-0.35.0.rc1/lib/cocoapods/command.rb:46:in `run'
    from /Users/danny/.gem/ruby/2.0.0/gems/cocoapods-0.35.0.rc1/bin/pod:50:in `<top (required)>'
    from /Users/danny/bin/pod:23:in `load'
    from /Users/danny/bin/pod:23:in `<main>'
```

Perhaps related to location of `gem`.  I re-installed cocoapods and did the `--user-install` option. Gem path is a symbolic link to `~/.gem/ruby/2.0.0/bin/pod`

```
$ which gem
/usr/bin/gem
```

**Comment by Usipov** [comment]
Seek for a bad comma in a Podfile or a local Podspec
example is attached
![0-](https://cloud.githubusercontent.com/assets/1080247/5722337/540b753a-9b4c-11e4-9e69-f0db3789cd09.png)
