### ISSUE TITLE
 Unable to load a specification for the plugin `/Library/Ruby/Gems/2.0.0/gems/cocoapods-try-release-fix-0.1.2`

### ISSUE THREAD

**Issue by codestack123** [CocoaPods/CocoaPods#2823]
I have issue when run pod install
: 
――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 0.34.4
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.4.3
        Host : Mac OS X 10.10 (14A389)
       Xcode : 6.1 (6A1052d)
         Git : git version 1.9.3 (Apple Git-50)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ d04980231ad2030487386d08f501725c52bab046
```

### Plugins

```
cocoapods-plugins : 0.3.2
cocoapods-trunk   : 0.3.1
cocoapods-try     : 0.4.2
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

inhibit_all_warnings!

#Mandatory

pod 'HockeySDK', '3.5.5'
pod 'MMDrawerController', '~> 0.5.6'
pod 'AFNetworking', '2.4.1'
pod 'CocoaLumberjack', '1.7'
pod 'CocoaAsyncSocket', '~> 7.3.2'
pod 'Mantle', '~> 1.3.1'
pod 'ReactiveCocoa', '~> 2.3.0'
pod 'ARAnalytics/GoogleAnalytics', '~> 2.8.0'
pod 'ARAnalytics/Mixpanel', '~> 2.8.0'
pod 'ARAnalytics/HockeyApp', '~> 2.8.0' 
pod 'Facebook-iOS-SDK', '3.17.0'
pod 'BlocksKit', '2.2.5'
pod 'socket.IO', '~> 0.5.2'

pod 'FormatterKit', '1.1.1'
pod 'TTTAttributedLabel', '1.8.1'
pod 'CustomBadge', '2.0'
pod 'OBShapedButton', '1.0.1'
pod 'SOCKit', "1.1"
pod 'MBProgressHUD', '0.6'
pod 'SSKeychain', '1.0.2'
pod 'Base64nl', '~> 1.2'

#Work to get rid of
pod 'UIGlossyButton', '0.0.7'
pod 'ISRefreshControl', '1.0.2'
pod 'ActionSheetPicker-3.0', '~> 1.1.2'
pod 'PrettyKit', '0.2.0'
pod 'StackBluriOS', '0.0.1'
pod 'TPKeyboardAvoiding', '0.0.1'
pod 'DEFacebookComposeViewController', '1.0'
pod 'TTSwitch', '0.0.4'
pod 'REComposeViewController', '2.2'
pod 'PagedFlowView', '0.0.1'
pod 'libextobjc/EXTScope', '0.2.5'
pod 'KGModal', '~> 0.0.1'
#pod 'TSMessages', :head
pod 'TSMessages', :podspec => 'https://github.com/username/TSMessages/TSMessages.podspec'
pod 'MKMapView-ZoomLevel', '~> 1.1.0'
pod 'CMPopTipView', '~> 2.0.0'
pod 'JVFloatLabeledTextField', '0.0.5'
pod 'iRate', '~> 1.8.3'
pod 'InstagramKit-afn2', :podspec => 'https://raw.github.com/ptwohig/InstagramKit/0.1.1/InstagramKit.podspec'
pod 'HockeySDK', '~> 3.5.0'
pod 'HPGrowingTextView', '1.1'
pod 'NMRangeSlider', '1.2.1'
pod 'Reveal-iOS-SDK', :configuration => ['Debug']

target :Tests do

pod 'Specta'
pod 'Expecta'
pod 'OCMockito'

end
```

### Error

```
OpenURI::HTTPError - 404 Not Found
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:353:in `open_http'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:709:in `buffer_open'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:210:in `block in open_loop'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `open_loop'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:149:in `open_uri'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:689:in `open'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:34:in `open'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/external_sources/podspec_source.rb:14:in `block in fetch'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/user_interface.rb:70:in `titled_section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/external_sources/podspec_source.rb:11:in `fetch'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/installer/analyzer.rb:293:in `block (2 levels) in fetch_external_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/installer/analyzer.rb:291:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/installer/analyzer.rb:291:in `block in fetch_external_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/user_interface.rb:49:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/installer/analyzer.rb:290:in `fetch_external_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/installer/analyzer.rb:54:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/installer.rb:184:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/installer.rb:106:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/user_interface.rb:49:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/installer.rb:105:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/installer.rb:90:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.7.0/lib/claide/command.rb:271:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/bin/pod:33:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

**Comment by kylef** [comment]
Fixed by 6f547d2a2e8d75b4b85f3dedf9c84d9d5b658287.
