### ISSUE TITLE
pod trunk push -> getaddrinfo: nodename nor servname provided, or not known

### ISSUE THREAD

**Issue by dgoldman-pdx** [CocoaPods/CocoaPods#2897]
### Report
- What did you do?

Updated a podspec, and then tried to push it:

> pod trunk push CardIO.podspec 
- What did you expect to happen?

Success. :)
- What happened instead?

Error as copied/pasted below.

I tried changing my DNS settings, but that didn't help.
### Stack

```
   CocoaPods : 0.33.1
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin13]
    RubyGems : 2.0.14
        Host : Mac OS X 10.9.5 (13F34)
       Xcode : 6.1 (6A1052d)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ c3c2c9c8d09851baee83bec377a2e60856ad6a5e
```
### Error

```
SocketError - getaddrinfo: nodename nor servname provided, or not known
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:878:in `initialize'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:878:in `open'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:878:in `block in connect'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:877:in `connect'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:851:in `start'
/Library/Ruby/Gems/2.0.0/gems/nap-0.8.0/lib/rest/request.rb:188:in `perform'
/Library/Ruby/Gems/2.0.0/gems/nap-0.8.0/lib/rest/request.rb:200:in `perform'
/Library/Ruby/Gems/2.0.0/gems/nap-0.8.0/lib/rest.rb:103:in `post'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-0.1.3/lib/pod/command/trunk.rb:330:in `create_request'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-0.1.3/lib/pod/command/trunk.rb:313:in `request_url'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-0.1.3/lib/pod/command/trunk.rb:321:in `request_path'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-0.1.3/lib/pod/command/trunk.rb:265:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.6.1/lib/claide/command.rb:281:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/bin/pod:33:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

**Comment by Legoless** [comment]
$ pod --version         
0.36.0.beta.2

[!] Found podspec `Haystack.podspec`
Validating podspec
 -> Haystack (0.7.9)

[!] There was an error pushing a new version to trunk: getaddrinfo: nodename nor servname provided, or not known

This error still appears sometimes. Not sure if it is tied to network, because it worked after a few minutes.
