### ISSUE TITLE
NoMethodError - undefined method `native_target' for nil:NilClass

### ISSUE THREAD

**Issue by brightredchilli** [CocoaPods/CocoaPods#2910]
### Report

* What did you do?
pod install. Along the way, many hopeful signs as indicated by the verbose flag

````
Activated: BTGraphicsLibrary, Eigen, boost/numeric-includes, boost/preprocessor-includes

Comparing resolved specification to the sandbox manifest
  A BTGraphicsLibrary
  A boost
  A eigen
````

* What did you expect to happen?

* What happened instead?

Got this exception. From what digging I can do, it is being triggered from the last line:

installer.rb
```` 
              # TODO remove me
              unless pod_dependency_target
                puts "[BUG] DEP: #{dep}"
              end
              pod_target.native_target.add_dependency(pod_dependency_target.native_target)
````
Because pod_dependency_target is somehow nil(I get the print out BUG] DEP: Eigen)....but how?

Podfile looks like this:

````
platform :ios                                                               
pod 'BTGraphicsLibrary', :git => 'git@github.com:xxx/graphics.git', :branch => 'ying/podspec'
````

The podspec for BTGraphicsLibrary looks like this:

````
{
  "name": "BTGraphicsLibrary",
  "summary": "...",
  "version": "1.0.0",
  "source": {
    "git": "git@github.com:xxx/graphics.git"
  },
  "platform" : "ios",
  "deployment_target" : {
    "ios" : "7.0"
  },
  "dependencies" : {
    "Eigen" : ["~> 3.2"]
  },

  "source_files" : ["include/**/*", "src/**/*", "glm/**/*"],
  "preserve_paths" : "*",
  "xcconfig" : {
    "USER_HEADER_SEARCH_PATHS" : "$(SRCROOT)/BTGraphicsLibrary"
  }
}
````

### Stack

```
   CocoaPods : 0.35.0
        Ruby : ruby 2.1.1p76 (2014-02-24 revision 45161) [x86_64-darwin13.0]
    RubyGems : 2.2.2
        Host : Mac OS X 10.10 (14A389)
       Xcode : 6.1 (6A1052c)
         Git : git version 1.9.3 (Apple Git-50)
Ruby lib dir : /Users/ying/.rvm/rubies/ruby-2.1.1/lib
Repositories : ip-internal-library - gitlabscm@yyy.com:library/internal-podspecs.git @ d19d49e8232c50ebf5280ce742d6f7c788987b24
               master - https://github.com/CocoaPods/Specs.git @ 9227350ae7605691c8c3833171a14a206175af49
```

### Plugins

```
cocoapods-plugins : 0.3.1
cocoapods-trunk   : 0.4.1
cocoapods-try     : 0.4.2
```

### Podfile

```ruby
platform :ios
pod 'BTGraphicsLibrary', :git => 'git@github.com:xxx/graphics.git', :branch => 'ying/podspec'
```

### Error

```
NoMethodError - undefined method `native_target' for nil:NilClass
/Users/ying/.rvm/gems/ruby-2.1.1/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:442:in `block (3 levels) in set_target_dependencies'
/Users/ying/.rvm/gems/ruby-2.1.1/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:435:in `each'
/Users/ying/.rvm/gems/ruby-2.1.1/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:435:in `block (2 levels) in set_target_dependencies'
/Users/ying/.rvm/gems/ruby-2.1.1/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:433:in `each'
/Users/ying/.rvm/gems/ruby-2.1.1/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:433:in `block in set_target_dependencies'
/Users/ying/.rvm/gems/ruby-2.1.1/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:431:in `each'
/Users/ying/.rvm/gems/ruby-2.1.1/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:431:in `set_target_dependencies'
/Users/ying/.rvm/gems/ruby-2.1.1/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:128:in `block in generate_pods_project'
/Users/ying/.rvm/gems/ruby-2.1.1/gems/cocoapods-0.35.0/lib/cocoapods/user_interface.rb:49:in `section'
/Users/ying/.rvm/gems/ruby-2.1.1/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:124:in `generate_pods_project'
/Users/ying/.rvm/gems/ruby-2.1.1/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:93:in `install!'
/Users/ying/.rvm/gems/ruby-2.1.1/gems/cocoapods-0.35.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/ying/.rvm/gems/ruby-2.1.1/gems/cocoapods-0.35.0/lib/cocoapods/command/project.rb:101:in `run'
/Users/ying/.rvm/gems/ruby-2.1.1/gems/claide-0.7.0/lib/claide/command.rb:271:in `run'
/Users/ying/.rvm/gems/ruby-2.1.1/gems/cocoapods-0.35.0/lib/cocoapods/command.rb:45:in `run'
/Users/ying/.rvm/gems/ruby-2.1.1/gems/cocoapods-0.35.0/bin/pod:43:in `<top (required)>'
/Users/ying/.rvm/gems/ruby-2.1.1/bin/pod:23:in `load'
/Users/ying/.rvm/gems/ruby-2.1.1/bin/pod:23:in `<main>'
/Users/ying/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
/Users/ying/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by vanderneut** [comment]
Thanks brightredchilli -- I had the exact same problem. Fixed by changing 'Cocos2D' to 'cocos2d' in my podspec.

**Comment by kylef** [comment]
@segiddins seems like this is another cause from https://github.com/CocoaPods/Core/pull/231 ?

**Comment by segiddins** [comment]
Yup, looks like it :(

-Samuel E. Giddins

On Mar 30, 2015, at 8:42 PM, Kyle Fuller <notifications@github.com> wrote:

@segiddins seems like this is another cause from CocoaPods/Core#231 ?
