### ISSUE TITLE
Incompatible character encodings

### ISSUE THREAD

**Issue by darkFunction** [CocoaPods/CocoaPods#2956]
`pod install` :

```
Analyzing dependencies
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/user_interface/error_report.rb:13:in `report': incompatible character encodings: UTF-8 and ASCII-8BIT (Encoding::CompatibilityError)
    from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/command.rb:58:in `report_error'
    from /Library/Ruby/Gems/2.0.0/gems/claide-0.7.0/lib/claide/command.rb:300:in `handle_exception'
    from /Library/Ruby/Gems/2.0.0/gems/claide-0.7.0/lib/claide/command.rb:274:in `rescue in run'
    from /Library/Ruby/Gems/2.0.0/gems/claide-0.7.0/lib/claide/command.rb:264:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/command.rb:45:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/bin/pod:43:in `<top (required)>'
    from /usr/bin/pod:23:in `load'
    from /usr/bin/pod:23:in `<main>'
```

`env` :

```
LC_CTYPE=en_US.UTF-8
LC_ALL=en_US.UTF-8
LANG=en_US.UTF-8
```

`pod --version` :

```
0.35.0
```

`gem environment` :

```
RubyGems Environment:
  - RUBYGEMS VERSION: 2.4.5
  - RUBY VERSION: 2.0.0 (2014-05-08 patchlevel 481) [universal.x86_64-darwin14]
  - INSTALLATION DIRECTORY: /Library/Ruby/Gems/2.0.0
  - RUBY EXECUTABLE: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
  - EXECUTABLE DIRECTORY: /usr/bin
  - SPEC CACHE DIRECTORY: /Users/Sam/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Library/Ruby/Site
  - RUBYGEMS PLATFORMS:
    - ruby
    - universal-darwin-14
  - GEM PATHS:
     - /Library/Ruby/Gems/2.0.0
     - /Users/Sam/.gem/ruby/2.0.0
     - /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/gems/2.0.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /opt/X11/bin
     - /usr/local/MacGPG2/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /usr/X11/bin
```

Tried in _zsh_ and _bash_ in _iTerm2_ and _Terminal_.

Any ideas? Thanks

Edit: if I try using an older Cocoapods (0.34.2) I see this output:

```
NoMethodError - undefined method `CFAutoRelease' for #<Fiddle::Pointer:0x007ff50b330970>
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.19.4/lib/xcodeproj/plist_helper.rb:338:in `ptr'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.19.4/lib/xcodeproj/plist_helper.rb:166:in `RubyHashPropertyListRead'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.19.4/lib/xcodeproj/plist_helper.rb:55:in `read'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.19.4/lib/xcodeproj/plist_helper.rb:6:in `read_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.19.4/lib/xcodeproj/project.rb:175:in `initialize_from_file'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.19.4/lib/xcodeproj/project.rb:92:in `open'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.2/lib/cocoapods/installer/analyzer.rb:542:in `block (2 levels) in compute_target_platforms'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.2/lib/cocoapods/installer/analyzer.rb:539:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.2/lib/cocoapods/installer/analyzer.rb:539:in `block in compute_target_platforms'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.2/lib/cocoapods/user_interface.rb:49:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.2/lib/cocoapods/installer/analyzer.rb:538:in `compute_target_platforms'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.2/lib/cocoapods/installer/analyzer.rb:50:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.2/lib/cocoapods/installer.rb:184:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.2/lib/cocoapods/installer.rb:106:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.2/lib/cocoapods/user_interface.rb:49:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.2/lib/cocoapods/installer.rb:105:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.2/lib/cocoapods/installer.rb:90:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.2/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.7.0/lib/claide/command.rb:271:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.2/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.2/bin/pod:33:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

**Comment by sidan5** [comment]
Same issue here. Xcode 6.2
