### ISSUE TITLE
NoMethodError - undefined method `downcase' for nil:NilClass

### ISSUE THREAD

**Issue by JarhomChen** [CocoaPods/CocoaPods#2965]
### Stack

```
   CocoaPods : 0.35.0
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.4.4
        Host : Mac OS X 10.10.1 (14B25)
       Xcode : 6.1 (6A1052c)
         Git : git version 1.9.3 (Apple Git-50)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : .git -  @ HEAD
               master - https://github.com/CocoaPods/Specs.git @ 986d6b5f3b9fd2a9686a81feab4eaa661350776b
```
### Plugins

```
cocoapods-plugins : 0.3.1
cocoapods-trunk   : 0.4.1
cocoapods-try     : 0.4.2
```
### Podfile

``` ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '6.0'
inhibit_all_warnings!

pod 'AFNetworking', '~> 2.5.0'
pod 'FMDB', '~> 2.3'
pod 'SDWebImage', '~> 3.7.1'
pod 'TPKeyboardAvoiding', '~> 1.2.4'
pod 'SVProgressHUD', '<= 1.0'
pod 'UI7Kit', '~> 0.9.19'
pod 'ImagePlayerView'
```
### Error

```
NoMethodError - undefined method `downcase' for nil:NilClass
/Users/Jarhom/.gem/ruby/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/sources_manager.rb:396:in `block in source_with_url'
/Users/Jarhom/.gem/ruby/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/sources_manager.rb:396:in `each'
/Users/Jarhom/.gem/ruby/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/sources_manager.rb:396:in `find'
/Users/Jarhom/.gem/ruby/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/sources_manager.rb:396:in `source_with_url'
/Users/Jarhom/.gem/ruby/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/sources_manager.rb:37:in `find_or_create_source_with_url'
/Users/Jarhom/.gem/ruby/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer/analyzer.rb:435:in `block in sources'
/Users/Jarhom/.gem/ruby/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer/analyzer.rb:434:in `map'
/Users/Jarhom/.gem/ruby/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer/analyzer.rb:434:in `sources'
/Users/Jarhom/.gem/ruby/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer/analyzer.rb:171:in `block in update_repositories_if_needed'
/Users/Jarhom/.gem/ruby/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/user_interface.rb:49:in `section'
/Users/Jarhom/.gem/ruby/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer/analyzer.rb:170:in `update_repositories_if_needed'
/Users/Jarhom/.gem/ruby/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer/analyzer.rb:50:in `analyze'
/Users/Jarhom/.gem/ruby/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:184:in `analyze'
/Users/Jarhom/.gem/ruby/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:106:in `block in resolve_dependencies'
/Users/Jarhom/.gem/ruby/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/user_interface.rb:49:in `section'
/Users/Jarhom/.gem/ruby/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:105:in `resolve_dependencies'
/Users/Jarhom/.gem/ruby/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:90:in `install!'
/Users/Jarhom/.gem/ruby/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/Jarhom/.gem/ruby/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.7.0/lib/claide/command.rb:271:in `run'
/Users/Jarhom/.gem/ruby/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/command.rb:45:in `run'
/Users/Jarhom/.gem/ruby/2.0.0/gems/cocoapods-0.35.0/bin/pod:43:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

**Comment by walter211** [comment]
I update to 0.36.0, still get this error
