### ISSUE TITLE
pod setup problem osx 10.10

### ISSUE THREAD

**Issue by romin991** [CocoaPods/CocoaPods#3012]
### Report

* What did you do?
I can't run pod setup
* What did you expect to happen?
i can run it
* What happened instead?
this error shows up

### Stack

```
   CocoaPods : 0.35.0
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.0.14
        Host : Mac OS X 10.10 (14A389)
       Xcode : 6.1.1 (6A2008a)
         Git : git version 1.9.3 (Apple Git-50)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : 
```

### Plugins

```
cocoapods-plugins : 0.3.2
cocoapods-trunk   : 0.3.1
cocoapods-try     : 0.4.2
```

### Error

```
Errno::EACCES - Permission denied - (/Users/Romin/.cocoapods/master, /Users/Romin/.cocoapods/repos/master)
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:519:in `rename'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:519:in `block in mv'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1552:in `block in fu_each_src_dest'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1568:in `fu_each_src_dest0'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1550:in `fu_each_src_dest'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:508:in `mv'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/command/setup.rb:62:in `block in migrate_repos'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/command/setup.rb:58:in `foreach'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/command/setup.rb:58:in `migrate_repos'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/command/setup.rb:38:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/user_interface.rb:49:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/command/setup.rb:32:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.7.0/lib/claide/command.rb:271:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/command.rb:45:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/bin/pod:43:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

**Comment by neonichu** [comment]
> Errno::EACCES - Permission denied - (/Users/Romin/.cocoapods/master, /Users/Romin/.cocoapods/repos/master)

You have insufficient permissions on that directory.

**Comment by romin991** [comment]
@neonichu  if i use sudo... then it got another error since cocoapods doesn't allow to use sudo

**Comment by kylef** [comment]
@romin991 Please see our troubleshooting guide covering this: http://guides.cocoapods.org/using/troubleshooting.html#im-getting-permission-errors-while-running-pod-commands

**Comment by cijianzy** [comment]
I meet some trouble ...
