### ISSUE TITLE
Error trying to push podspec

### ISSUE THREAD

**Issue by gabriel** [CocoaPods/CocoaPods#3024]
### Report

* What did you do?

Trying to pod trunk push KBKeybase.podpsec at https://github.com/gabriel/KBKeybase

* What did you expect to happen?

Push podspec.

* What happened instead?

It errored.

### Stack

```
   CocoaPods : 0.36.0.beta.1
        Ruby : ruby 2.1.1p76 (2014-02-24 revision 45161) [x86_64-darwin12.0]
    RubyGems : 2.2.2
        Host : Mac OS X 10.10.1 (14B25)
       Xcode : 6.1.1 (6A2008a)
         Git : git version 2.2.1
Ruby lib dir : /Users/gabe/.rvm/rubies/ruby-2.1.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 23dc4d9001a0e48d0016aaafbd93ef4cff4c9982
```

### Plugins

```
cocoapods-plugins : 0.4.0
cocoapods-trunk   : 0.5.0
cocoapods-try     : 0.4.3
```

### Error

```
NoMethodError - undefined method `should_build?' for nil:NilClass
/Users/gabe/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/installer.rb:490:in `block (3 levels) in set_target_dependencies'
/Users/gabe/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/installer.rb:481:in `each'
/Users/gabe/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/installer.rb:481:in `block (2 levels) in set_target_dependencies'
/Users/gabe/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/installer.rb:471:in `each'
/Users/gabe/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/installer.rb:471:in `block in set_target_dependencies'
/Users/gabe/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/installer.rb:470:in `each'
/Users/gabe/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/installer.rb:470:in `set_target_dependencies'
/Users/gabe/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/installer.rb:129:in `block in generate_pods_project'
/Users/gabe/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/user_interface.rb:49:in `section'
/Users/gabe/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/installer.rb:125:in `generate_pods_project'
/Users/gabe/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/installer.rb:93:in `install!'
/Users/gabe/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/validator.rb:309:in `install_pod'
/Users/gabe/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/validator.rb:214:in `block in perform_extensive_analysis'
/Users/gabe/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/validator.rb:210:in `each'
/Users/gabe/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/validator.rb:210:in `perform_extensive_analysis'
/Users/gabe/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/validator.rb:73:in `validate'
/Users/gabe/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-trunk-0.5.0/lib/pod/command/trunk/push.rb:106:in `validate_podspec'
/Users/gabe/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-trunk-0.5.0/lib/pod/command/trunk/push.rb:56:in `run'
/Users/gabe/.rvm/gems/ruby-2.1.1@global/gems/claide-0.8.0/lib/claide/command.rb:312:in `run'
/Users/gabe/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/command.rb:45:in `run'
/Users/gabe/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-0.36.0.beta.1/bin/pod:43:in `<top (required)>'
/Users/gabe/.rvm/gems/ruby-2.1.1/bin/pod:23:in `load'
/Users/gabe/.rvm/gems/ruby-2.1.1/bin/pod:23:in `<main>'
/Users/gabe/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
/Users/gabe/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by segiddins** [comment]
@neonichu can you please take a look at this?

**Comment by gabriel** [comment]
Ahhh! I see.... I wonder if its possible for cocoapods to give an error
telling the user they have a typo (case sensitivity) issue for the pod
name? If possible.

**Comment by segiddins** [comment]
@neonichu yeah...

**Comment by Legoless** [comment]
This is still an issue, it appears if dependency in podspec is specified with wrong, especially in case sensitivity cases. The pod is downloaded and installed correctly, but generating Pods project fails.

```
Update all pods
Analyzing dependencies
Fetching podspec for `AuthKit` from `../AuthKit.podspec`
Downloading dependencies
Installing AFNetworking (2.5.1)
Installing AKPickerView (0.2.4)
Installing AuthKit (0.5.0)
Installing Bolts (1.1.4)
Installing Facebook-iOS-SDK (3.23.2)
Installing Haystack (0.8.0)
Installing JSONModel (1.0.2)
Installing PureLayout (2.0.5)
Installing googleplus-ios-sdk (1.7.1)
Generating Pods project
[BUG] DEP: GooglePlus-iOS-SDK
```

### Stack

```
   CocoaPods : 0.36.0
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.0.14
        Host : Mac OS X 10.10.2 (14C1514)
       Xcode : 6.2 (6C131e)
         Git : git version 1.8.4
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 888f8055922cfcbdb4902d790c2cacdc11646c25
```

### Plugins

```
cocoapods-plugins : 0.4.1
cocoapods-trunk   : 0.4.0
cocoapods-try     : 0.4.3
```

### Podfile

```ruby
platform :ios, '7.0'

source 'https://github.com/CocoaPods/Specs.git'

pod 'AuthKit', :path => '../AuthKit.podspec'
```

### Error

```
NoMethodError - undefined method `should_build?' for nil:NilClass
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/installer.rb:554:in `block (3 levels) in set_target_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/installer.rb:546:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/installer.rb:546:in `block (2 levels) in set_target_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/installer.rb:532:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/installer.rb:532:in `block in set_target_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/installer.rb:528:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/installer.rb:528:in `set_target_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/installer.rb:132:in `block in generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/user_interface.rb:49:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/installer.rb:128:in `generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/installer.rb:96:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/command/project.rb:155:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/command.rb:46:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```
