### ISSUE TITLE
Error running pod_update (undefined method `new_file')

### ISSUE THREAD

**Issue by dougmcbride** [CocoaPods/CocoaPods#3054]
:rainbow:

### Report

* What did you do?

Ran `pod update` in an existing project with pods

* What did you expect to happen?

some of the pods should have been updated

* What happened instead?

the crash below at the end, after it looked like all the pods had been downloaded / processed

### Stack

```
   CocoaPods : 0.36.0.beta.1
        Ruby : ruby 2.1.3p242 (2014-09-19 revision 47630) [x86_64-darwin13.0]
    RubyGems : 2.2.2
        Host : Mac OS X 10.9.5 (13F34)
       Xcode : 6.1.1 (6A2008a)
         Git : git version 1.9.3 (Apple Git-50)
Ruby lib dir : /Users/username/lib
Repositories : companyname-companynameid-cocoapods - https://github.companyname.com/companynameID/Cocoapods.git @ 2a35e3da2d46259314b621483b3be3ae5afd97a4
               master - https://github.com/CocoaPods/Specs.git @ 91bc84e50740a0e52162edee0a71829946337899
               wdig-username2-cocoapods - https://github.wdig.com/username2/CocoaPods.git @ 6c5561ccbf57864ecd29744c325c5bd19f14a77f
```

### Plugins

```
cocoapods-plugins : 0.4.0
cocoapods-trunk   : 0.5.0
cocoapods-try     : 0.4.3
```

### Podfile

```ruby
source 'https://github.companyname.com/companynameID/Cocoapods.git'
source 'https://github.wdig.com/username2/CocoaPods.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'

#lets hide all compiler warnings from Pods since we can't fix them anyway
inhibit_all_warnings!

pod 'AFNetworking', '~> 2.0'
pod 'DTCoreText'
pod 'SVPullToRefresh'
pod 'GPUImage'
pod 'HTMLReader'
pod 'ReactiveCocoa', '2.3.1'
pod 'AFNetworking-RACExtensions'
pod 'libextobjc/EXTScope'
pod 'Masonry'
pod 'youtube-ios-player-helper'
pod 'FLAnimatedImage'
pod 'CocoaLumberjack'

pod 'FormatterKit', '~> 1.7.2'
#the following removes extra localizations of FormatterKit so you don't trip up the App Store sensors
pre_install do |installer|
    supported_locales = ['base', 'en']

    installer.pods.each do |pod|
        if (pod.name == 'FormatterKit')
            Dir.glob(File.join(pod.root, '**', '*.lproj')).each do |bundle|
                if (!supported_locales.include?(File.basename(bundle, ".lproj").downcase))
                    puts "Removing #{bundle}"
                    FileUtils.rm_rf(bundle)
                end
            end
        end
    end
end

# companynameID
# pod repo add companynameID https://github.companyname.com/companynameID/Cocoapods.git
# pod repo remove companynameID
# "FRAMEWORK_SEARCH_PATHS" => '"$(PODS_ROOT)/companynameIdSDK"'
pod 'companynameIdSDK', '~> 2.0.7.0'
```

### Error

```
NoMethodError - undefined method `new_file' for #<Xcodeproj::Project::Object::PBXFileReference:0x007fb55cd0bc90>
/Users/username/lib/ruby/gems/2.1.0/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/project.rb:175:in `add_file_reference'
/Users/username/lib/ruby/gems/2.1.0/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/installer/file_references_installer.rb:168:in `block (2 levels) in add_file_accessors_paths_to_pods_group'
/Users/username/lib/ruby/gems/2.1.0/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/installer/file_references_installer.rb:166:in `each'
/Users/username/lib/ruby/gems/2.1.0/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/installer/file_references_installer.rb:166:in `block in add_file_accessors_paths_to_pods_group'
/Users/username/lib/ruby/gems/2.1.0/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/installer/file_references_installer.rb:162:in `each'
/Users/username/lib/ruby/gems/2.1.0/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/installer/file_references_installer.rb:162:in `add_file_accessors_paths_to_pods_group'
/Users/username/lib/ruby/gems/2.1.0/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/installer/file_references_installer.rb:103:in `block in add_resources'
/Users/username/lib/ruby/gems/2.1.0/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/user_interface.rb:110:in `message'
/Users/username/lib/ruby/gems/2.1.0/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/installer/file_references_installer.rb:102:in `add_resources'
/Users/username/lib/ruby/gems/2.1.0/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/installer/file_references_installer.rb:38:in `install!'
/Users/username/lib/ruby/gems/2.1.0/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/installer.rb:427:in `install_file_references'
/Users/username/lib/ruby/gems/2.1.0/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/installer.rb:127:in `block in generate_pods_project'
/Users/username/lib/ruby/gems/2.1.0/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/user_interface.rb:49:in `section'
/Users/username/lib/ruby/gems/2.1.0/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/installer.rb:125:in `generate_pods_project'
/Users/username/lib/ruby/gems/2.1.0/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/installer.rb:93:in `install!'
/Users/username/lib/ruby/gems/2.1.0/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/username/lib/ruby/gems/2.1.0/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/command/project.rb:155:in `run'
/Users/username/lib/ruby/gems/2.1.0/gems/claide-0.8.0/lib/claide/command.rb:312:in `run'
/Users/username/lib/ruby/gems/2.1.0/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/command.rb:45:in `run'
/Users/username/lib/ruby/gems/2.1.0/gems/cocoapods-0.36.0.beta.1/bin/pod:43:in `<top (required)>'
/Users/username/bin/pod:23:in `load'
/Users/username/bin/pod:23:in `<main>'
```

**Comment by orta** [comment]
Do you know if this still happens without the pre-install hook?

**Comment by dougmcbride** [comment]
I removed it and got the same error, so yes.

**Comment by dougmcbride** [comment]
Hey, I was playing around with this and if I comment out the last pod in the Podfile it works fine. The same pod used to work fine, but since that's one of ours I'll investigate.

**Comment by dougmcbride** [comment]
Ok, there's a newer version of that pod internally that works fine. I'm happy to close this unless you'd like me to dig more to find the source of the error.

Thanks for the quick response.

**Comment by orta** [comment]
I'd be interested in seeing a redacted version of the Podspec that broke? Something is odd with CocoaPods here.

**Comment by dougmcbride** [comment]
Here you go:

```
Pod::Spec.new do |s|
  s.name             = "companyIdSDK"
  s.version          = "2.0.7.1"
  s.summary          = "CompanyPod iOS Library"
  s.description      = <<-DESC
                        iOS CompanyPod Integration
                       DESC
  s.homepage         = "https://devcentraldocs.company.com/display/public/DI/IOS+2.0+SDK+Home+Page"
  s.license          = {
                        :type => "PROPRIETARY",
                        :text =>  <<-LICENSE
                                  Copyright 2014 company. All rights reserved.
                                  company PROPRIETARY/CONFIDENTIAL.
                                  LICENSE
                      }
  s.authors          = {  "Punch Rockgroin" => "user1@company.com", 
                          "Smash Lampjaw" => "user2@company.com" ,
                          "Thick McRunFast" => "user3@company.com" ,
                          "Punt Speedchunk" => "user4@company.com",
                          "Lump Beefbroth" => "user5@company.com"}
  s.platform         = :ios, "6.0"
  s.source           =  { 
                          :http => "https://nexus.company.com/nexus/content/repositories/path/mobile/ios/CompanyPod/2.0.7.1/CompanyPod-2.0.7.1.zip"                          
                        }
  s.source_files     = [ "CompanyPod.framework/*" ]
  s.resources        = [ "CompanyPod.bundle" ]
  s.frameworks       = [ "CompanyPod", "SystemConfiguration", "UIKit", "Foundation", "CoreGraphics" ]
  s.preserve_paths   = [ "CompanyPod.framework", "CompanyPod.bundle" ]
  s.requires_arc     = true
  s.xcconfig         =  {
                          "OTHER_LDFLAGS" => "-ObjC  -framework CompanyPod -all_load" ,                         
                          "FRAMEWORK_SEARCH_PATHS" => '"$(PODS_ROOT)/companyIdSDK"'
                        }
end
```

**Comment by segiddins** [comment]
That framework should be a `vendored_framework`

**Comment by dougmcbride** [comment]
It looks like the pod authors figured that out in their new version. Thank you! Not sure if you want to keep this open for any code change.

**Comment by orta** [comment]
Is there a way _we_ can tell if it should be vendored?
If not, let's close.

**Comment by neonichu** [comment]
It should be possible to fail with a less obtuse error, so I'd say let's keep this open.

**Comment by kylef** [comment]
Agreed, the underlying cause is tracked by this issue: #3091. Closing as a dupe.
