### ISSUE TITLE
Err: "NameError - uninitialized constant Pod::Command::Trunk::Push::REST"

### ISSUE THREAD

**Issue by cvasilak** [CocoaPods/CocoaPods#3064]
Hi all,

I am using ```cocoapods -pre``` release (with support for swift projects). Not sure what happened, possible an error with my ruby gems and started getting the following error. I would glad if someone shed some light on it. 

```
NameError - uninitialized constant Pod::Command::Trunk::Push::REST
/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-0.5.0/lib/pod/command/trunk/push.rb:70:in `rescue in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-0.5.0/lib/pod/command/trunk/push.rb:56:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.8.0/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/command.rb:45:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0.beta.1/bin/pod:43:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

Here is a list of the versions of some installed programs, let me know if you need more

```
$ sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.10.1
BuildVersion:	14B25

$ ruby --version
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]

$ sudo gem list | grep cocoapods
Password:
cocoapods (0.36.0.beta.1)
cocoapods-core (0.36.0.beta.1)
cocoapods-downloader (0.8.1)
cocoapods-plugins (0.4.0)
cocoapods-trunk (0.5.0)
cocoapods-try (0.4.3)

$ sudo gem list | grep rest
rest (3.0.3)
```

**Comment by segiddins** [comment]
Seems like we're missing a `require`

**Comment by segiddins** [comment]
Ah damn. Looks like it's an issue with having the `rest` gem installed, since our `rest` comes from the `nap` gem.

**Comment by cvasilak** [comment]
thank you @segiddins, after removing ```rest``` and installing ```nap``` gem, worked great from then on

feel free to close this issue.
