### ISSUE TITLE
ArgumentError - Illformed requirement `"= "` crash

### ISSUE THREAD

**Issue by fatuhoku** [CocoaPods/CocoaPods#3066]
### Report

* What did you do?

Tried to set up my Xcode project up in a modular way as shown in: http://www.supermar.in/modular-objective-c/.
Ran `pod install` **straight after declaring that `MyProjKit` is a dependency of `MyProjKitTests`**.

I have tried this with Cocoapods version 0.36.0-beta1 as well, but I get the same result.

* What did you expect to happen?

I expected the command to succeed and now the project understands that the `MyProjKitTests` pod requires `MyProjKit`

* What happened instead?

Error got thrown:

### Stack

```
   CocoaPods : 0.
   34.4
        Ruby : ruby 1.9.3p392 (2013-02-22 revision 39386) [x86_64-darwin12.3.0]
    RubyGems : 1.8.23
        Host : Mac OS X 10.10 (14A389)
       Xcode : 6.1.1 (6A2008a)
         Git : git version 2.2.0
Ruby lib dir : /Users/fushunpoon/.rbenv/versions/1.9.3-p392/lib
Repositories : bitbucket-fushunpoon-hspcocoapodsrepository - https://bitbucket.org/fushunpoon/hspcocoapodsrepository @ 1bd4d16719df94e75fba8ddcedb8d4ed056ae081
               master - https://github.com/CocoaPods/Specs.git @ 51f7c538329c5b175f2fc87f098cef9900310635
               private - git@bitbucket.org:fushunpoon/hspcocoapodsrepository.git @ 1bd4d16719df94e75fba8ddcedb8d4ed056ae081
```

### Plugins

```
cocoapods-plugins : 0.3.1
cocoapods-trunk   : 0.3.1
cocoapods-try     : 0.4.3
```

### Podfile

```ruby
platform :ios, '7.1'

inhibit_all_warnings!

def common_pods
  pod 'CocoaLumberjack'
  pod 'Typhoon'
  pod 'Parse', '~> 1.6.0'
end

target 'MyProj' do
  common_pods

  pod 'MyProjKit', :path => '../MyProjKit.podspec'

  pod 'AMBCircularButton'
  pod 'ASValueTrackingSlider'
  pod 'AXWireButton'
  pod 'Analytics/Mixpanel'
  pod 'BFNavigationBarDrawer'
  pod 'BOString'
  pod 'CHCSVParser'
  pod 'CHDataStructures'
  pod 'CHTCollectionViewWaterfallLayout'
  pod 'DProperty'
  pod 'FXBlurView'
  pod 'FlatButtons'
  pod 'FormatterKit'
  pod 'Functional.m'
  pod 'HexColors'
  pod 'InflectorKit'
  pod 'JREnum'
  pod 'KCOrderedAccessorFix'
  pod 'LoremIpsum'
  pod 'M13OrderedDictionary'
  pod 'MBProgressHUD'
  pod 'MGImageUtilities'
  pod 'MKUnits'
  pod 'MagicalRecord', :git => 'https://github.com/magicalpanda/MagicalRecord', :tag => 'v2.3.0-beta.3'
  pod 'Masonry'
  pod 'NSAttributedString+CCLFormat'
  pod 'NSObject+Singleton'
  pod 'NZCircularImageView'
  pod 'OSCache'
  pod 'Overline-BlocksKit'
  pod 'RBStoryboardLinkTyphoon', :git => 'https://github.com/papcio28/RBStoryboardLink'
  pod 'RKValueTransformers'
  pod 'ReactiveCocoa', '~> 2.3.0'
  pod 'RegExCategories'
  pod 'SAMGradientView'
  pod 'SDWebImage'
  pod 'STMReactiveReachability'
  pod 'SZTextView'
  pod 'SharedInstanceGCD'
  pod 'StackBluriOS'
  pod 'StoryboardXibController'
  pod 'TLIndexPathTools'
  pod 'TPKeyboardAvoiding'
  pod 'Toast'
  pod 'TransformerKit'
  pod 'Tweaks'
  pod 'UIActionSheet+Blocks'
  pod 'UIAlertView+Blocks'
  pod 'UIImage+Additions'
  pod 'libPusher'
  pod 'libPusher/ReactiveExtensions'
  pod 'CrashlyticsFramework'
  pod 'Instabug'
  pod 'Facebook-iOS-SDK'
  pod 'ParseFacebookUtils', '~> 1.6.0'
  pod 'ParseUI'
end

target 'MyProjLogicSpecs' do
  pod 'Specta', :git => 'https://github.com/specta/specta', :commit => '9371f3a3a2a4316efae04ebc135cdcf89086e975'
  pod 'Expecta'
  pod 'OCHamcrest'
  pod 'OCMockito'
  pod 'OCMock'

  pod 'MyProjKitTests', :path => '../MyProjKitTests.podspec'

  common_pods
end
```

### Error

```
ArgumentError - Illformed requirement `"= "`
/Users/fushunpoon/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/cocoapods-core-0.34.4/lib/cocoapods-core/requirement.rb:61:in `parse'
/Users/fushunpoon/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/cocoapods-core-0.34.4/lib/cocoapods-core/vendor/requirement.rb:108:in `block in initialize'
/Users/fushunpoon/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/cocoapods-core-0.34.4/lib/cocoapods-core/vendor/requirement.rb:108:in `map!'
/Users/fushunpoon/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/cocoapods-core-0.34.4/lib/cocoapods-core/vendor/requirement.rb:108:in `initialize'
/Users/fushunpoon/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/cocoapods-core-0.34.4/lib/cocoapods-core/requirement.rb:32:in `new'
/Users/fushunpoon/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/cocoapods-core-0.34.4/lib/cocoapods-core/requirement.rb:32:in `create'
/Users/fushunpoon/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/cocoapods-core-0.34.4/lib/cocoapods-core/dependency.rb:91:in `initialize'
/Users/fushunpoon/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/cocoapods-core-0.34.4/lib/cocoapods-core/dependency.rb:238:in `new'
/Users/fushunpoon/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/cocoapods-core-0.34.4/lib/cocoapods-core/dependency.rb:238:in `merge'
/Users/fushunpoon/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/cocoapods-core-0.34.4/lib/cocoapods-core/specification/set.rb:78:in `block in dependency'
/Users/fushunpoon/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/cocoapods-core-0.34.4/lib/cocoapods-core/specification/set.rb:77:in `each'
/Users/fushunpoon/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/cocoapods-core-0.34.4/lib/cocoapods-core/specification/set.rb:77:in `reduce'
/Users/fushunpoon/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/cocoapods-core-0.34.4/lib/cocoapods-core/specification/set.rb:77:in `dependency'
/Users/fushunpoon/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/cocoapods-core-0.34.4/lib/cocoapods-core/specification/set.rb:120:in `block in acceptable_versions'
/Users/fushunpoon/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/cocoapods-core-0.34.4/lib/cocoapods-core/specification/set.rb:120:in `select'
/Users/fushunpoon/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/cocoapods-core-0.34.4/lib/cocoapods-core/specification/set.rb:120:in `acceptable_versions'
/Users/fushunpoon/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/cocoapods-core-0.34.4/lib/cocoapods-core/specification/set.rb:62:in `required_by'
/Users/fushunpoon/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/cocoapods-0.34.4/lib/cocoapods/resolver.rb:151:in `block (2 levels) in find_dependency_specs'
/Users/fushunpoon/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/cocoapods-0.34.4/lib/cocoapods/user_interface.rb:110:in `message'
/Users/fushunpoon/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/cocoapods-0.34.4/lib/cocoapods/resolver.rb:149:in `block in find_dependency_specs'
/Users/fushunpoon/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/cocoapods-0.34.4/lib/cocoapods/resolver.rb:145:in `each'
/Users/fushunpoon/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/cocoapods-0.34.4/lib/cocoapods/resolver.rb:145:in `find_dependency_specs'
/Users/fushunpoon/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/cocoapods-0.34.4/lib/cocoapods/resolver.rb:169:in `block (2 levels) in find_dependency_specs'
/Users/fushunpoon/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/cocoapods-0.34.4/lib/cocoapods/user_interface.rb:110:in `message'
/Users/fushunpoon/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/cocoapods-0.34.4/lib/cocoapods/resolver.rb:149:in `block in find_dependency_specs'
/Users/fushunpoon/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/cocoapods-0.34.4/lib/cocoapods/resolver.rb:145:in `each'
/Users/fushunpoon/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/cocoapods-0.34.4/lib/cocoapods/resolver.rb:145:in `find_dependency_specs'
/Users/fushunpoon/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/cocoapods-0.34.4/lib/cocoapods/resolver.rb:71:in `block (2 levels) in resolve'
/Users/fushunpoon/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/cocoapods-0.34.4/lib/cocoapods/user_interface.rb:49:in `section'
/Users/fushunpoon/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/cocoapods-0.34.4/lib/cocoapods/resolver.rb:69:in `block in resolve'
/Users/fushunpoon/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/cocoapods-0.34.4/lib/cocoapods/resolver.rb:66:in `each'
/Users/fushunpoon/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/cocoapods-0.34.4/lib/cocoapods/resolver.rb:66:in `resolve'
/Users/fushunpoon/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/cocoapods-0.34.4/lib/cocoapods/installer/analyzer.rb:322:in `block in resolve_dependencies'
/Users/fushunpoon/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/cocoapods-0.34.4/lib/cocoapods/user_interface.rb:49:in `section'
/Users/fushunpoon/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/cocoapods-0.34.4/lib/cocoapods/installer/analyzer.rb:320:in `resolve_dependencies'
/Users/fushunpoon/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/cocoapods-0.34.4/lib/cocoapods/installer/analyzer.rb:55:in `analyze'
/Users/fushunpoon/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/cocoapods-0.34.4/lib/cocoapods/installer.rb:184:in `analyze'
/Users/fushunpoon/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/cocoapods-0.34.4/lib/cocoapods/installer.rb:106:in `block in resolve_dependencies'
/Users/fushunpoon/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/cocoapods-0.34.4/lib/cocoapods/user_interface.rb:49:in `section'
/Users/fushunpoon/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/cocoapods-0.34.4/lib/cocoapods/installer.rb:105:in `resolve_dependencies'
/Users/fushunpoon/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/cocoapods-0.34.4/lib/cocoapods/installer.rb:90:in `install!'
/Users/fushunpoon/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/cocoapods-0.34.4/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/fushunpoon/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/cocoapods-0.34.4/lib/cocoapods/command/project.rb:101:in `run'
/Users/fushunpoon/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/claide-0.7.0/lib/claide/command.rb:271:in `run'
/Users/fushunpoon/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/cocoapods-0.34.4/lib/cocoapods/command.rb:50:in `run'
/Users/fushunpoon/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/cocoapods-0.34.4/bin/pod:33:in `<top (required)>'
/Users/fushunpoon/.rbenv/versions/1.9.3-p392/bin/pod:23:in `load'
/Users/fushunpoon/.rbenv/versions/1.9.3-p392/bin/pod:23:in `<main>'
```

**Comment by fatuhoku** [comment]
In fact, I couldn't find a good way of structuring my Podfile such that all dependencies are linked to my test target, **without setting the main application target as test host**. If anybody has any idea of how to do this in the most painless way please let me know.

**Comment by neonichu** [comment]
I am unable to reproduce your error with CP 0.36, so my assumption is that one of your two private Pods might contain a syntax error? Do they lint?

**Comment by fatuhoku** [comment]
@neonichu Thanks for your response.

No they certainly don't lint. For completeness, here are my podspecs:

`MyProjKit.podspec`: 
```
Pod::Spec.new do |s|
  s.name = 'MyProjKit'
  s.platform = :ios
  s.subspec 'CoreData' do |ss|
    ss.source_files = 'MyProjKit/CoreData/**/*.{h,m}'
    ss.resources = 'MyProjKit/CoreData/**/*.{xcdatamodel}'
    ss.frameworks = 'CoreData'
    ss.dependency 'CocoaLumberjack'
    ss.dependency 'MyProjKit/Parse'
    ss.dependency 'MagicalRecord'
    ss.dependency 'Overline-BlocksKit'
  end
  s.subspec 'Parse' do |ss|
    ss.source_files = 'MyProjKit/Parse/**/*.{h,m}'
    ss.dependency 'Parse'
  end
end
```

`MyProjKitTests.podspec`: 
```
Pod::Spec.new do |s|
  s.name = 'MyProjKitTests'
  s.platform = :ios
  s.source_files = 'MyProjKit/Test/**/*.{h,m}'
  s.frameworks = 'XCTest'
  s.dependency 'Specta'
  s.dependency 'Expecta'
  s.dependency 'MyProjKit'   # the error happened after adding THIS LINE
end
```

As you can see, I have omitted `version` and `source`. According to http://www.supermar.in/modular-objective-c/ apparently they can be omitted, but `pod lint` will definitely complain about them.

If there were syntax errors, I would expect Cocoapods to pick those up and report them to me rather than spew out the error I received.

**Comment by neonichu** [comment]
I agree that the error message could be much better, but the problem is indeed the missing `version` attribute of "MyProjKit".

**Comment by fatuhoku** [comment]
Okay – adding the versions does seem to have helped — the error no longer occurs. I'm sure I tried it before though and the outcome was different!

Thanks for now. I think the error message **must** be improved.

**Comment by segiddins** [comment]
This is what `pod lib lint` is for -- I don't think it's the responsibility of the code path of `pod install` to verify this sort of thing.

**Comment by fatuhoku** [comment]
I must disagree with you about code path. Cocoapods is a tool by developers for developers: i.e. I'm an end user:  I don't particular care that Cocoapods internally *has* particular code paths at all. The question is, on this occasion, has Cocoapods **solved my problem**?

Funnily enough, @segiddins's suggestion is exactly what the error message should say: "Did you do run `pod lib lint`?". Now that would have gotten me closer to where I wanted to be.

**Comment by segiddins** [comment]
As a developer creating a podspec, I _personally_ think it's your responsibility to lint it before attempting to integrate the pod into another project.

**Comment by fatuhoku** [comment]
@segiddins thanks for the suggestion. I'll be using `pod lib lint` from now on. I never knew about it!
