### ISSUE TITLE
pod trunk me NoMethodError - undefined method `last' in version 0.33.1

### ISSUE THREAD

**Issue by CoderMJLee** [CocoaPods/CocoaPods#3080]
pod --version  :  0.33.1
gem list | grep netrc : netrc (0.10.2)
When I finished register, 'pod trunk me' results in an error

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 0.33.1
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.1.11
        Host : Mac OS X 10.10.2 (14C106a)
       Xcode : 6.1 (6A1052d)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 6d5a00c072b19034f9e6b3f7fd3821c5ac9eba3d
```

### Error

```
NoMethodError - undefined method `last' for #<Netrc::Entry:0x007fc59c246378>
/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-0.1.4/lib/pod/command/trunk.rb:390:in `token'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-0.1.4/lib/pod/command/trunk.rb:95:in `validate!'
/Library/Ruby/Gems/2.0.0/gems/claide-0.6.1/lib/claide/command.rb:280:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.33.1/bin/pod:33:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

**Comment by CoderMJLee** [comment]
After I call gem update, that problem had beed fixed
