### ISSUE TITLE
Bundles inside Bundles

### ISSUE THREAD

**Issue by KrauseFx** [CocoaPods/CocoaPods#3091]
:rainbow:

Running `pod install` with the latest release:
### Stack

```
   CocoaPods : 0.36.0.beta.1
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [x86_64-darwin13.1.0]
    RubyGems : 2.2.2
        Host : Mac OS X 10.10.1 (14B25)
       Xcode : 6.1.1 (6A2008a)
         Git : git version 2.2.1
Ruby lib dir : /Users/felixkrause/.rvm/rubies/ruby-2.0.0-p481/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 52a5b86c95ff99d6233d3f7b214f15b21bcc0201
```

### Plugins

```
cocoapods-plugins : 0.4.0
cocoapods-trunk   : 0.5.0
cocoapods-try     : 0.4.3
```

### Error

```
NoMethodError - undefined method `new_file' for #<Xcodeproj::Project::Object::PBXFileReference:0x007f7fc98b1a78>
/Users/felixkrause/.rvm/gems/ruby-2.0.0-p481/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/project.rb:173:in `add_file_reference'
/Users/felixkrause/.rvm/gems/ruby-2.0.0-p481/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/installer/file_references_installer.rb:168:in `block (2 levels) in add_file_accessors_paths_to_pods_group'
/Users/felixkrause/.rvm/gems/ruby-2.0.0-p481/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/installer/file_references_installer.rb:166:in `each'
/Users/felixkrause/.rvm/gems/ruby-2.0.0-p481/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/installer/file_references_installer.rb:166:in `block in add_file_accessors_paths_to_pods_group'
/Users/felixkrause/.rvm/gems/ruby-2.0.0-p481/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/installer/file_references_installer.rb:162:in `each'
/Users/felixkrause/.rvm/gems/ruby-2.0.0-p481/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/installer/file_references_installer.rb:162:in `add_file_accessors_paths_to_pods_group'
/Users/felixkrause/.rvm/gems/ruby-2.0.0-p481/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/installer/file_references_installer.rb:104:in `block in add_resources'
/Users/felixkrause/.rvm/gems/ruby-2.0.0-p481/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/user_interface.rb:110:in `message'
/Users/felixkrause/.rvm/gems/ruby-2.0.0-p481/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/installer/file_references_installer.rb:102:in `add_resources'
/Users/felixkrause/.rvm/gems/ruby-2.0.0-p481/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/installer/file_references_installer.rb:38:in `install!'
/Users/felixkrause/.rvm/gems/ruby-2.0.0-p481/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/installer.rb:427:in `install_file_references'
/Users/felixkrause/.rvm/gems/ruby-2.0.0-p481/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/installer.rb:127:in `block in generate_pods_project'
/Users/felixkrause/.rvm/gems/ruby-2.0.0-p481/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/user_interface.rb:49:in `section'
/Users/felixkrause/.rvm/gems/ruby-2.0.0-p481/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/installer.rb:125:in `generate_pods_project'
/Users/felixkrause/.rvm/gems/ruby-2.0.0-p481/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/installer.rb:93:in `install!'
/Users/felixkrause/.rvm/gems/ruby-2.0.0-p481/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/felixkrause/.rvm/gems/ruby-2.0.0-p481/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/command/project.rb:101:in `run'
/Users/felixkrause/.rvm/gems/ruby-2.0.0-p481/gems/claide-0.8.0/lib/claide/command.rb:312:in `run'
/Users/felixkrause/.rvm/gems/ruby-2.0.0-p481/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/command.rb:45:in `run'
/Users/felixkrause/.rvm/gems/ruby-2.0.0-p481/gems/cocoapods-0.36.0.beta.1/bin/pod:43:in `<top (required)>'
/Users/felixkrause/.rvm/gems/ruby-2.0.0-p481/bin/pod:23:in `load'
/Users/felixkrause/.rvm/gems/ruby-2.0.0-p481/bin/pod:23:in `<main>'

```

### My Podfile:
```ruby
Pod::Spec.new do |s|
  s.name         = "Core"
  s.version      = "1.0"
  s.homepage     = "http://sunapps.net"

  s.platform     = :ios, '7.0'
  
  s.requires_arc = true

  s.subspec 'Core' do |core|
    # Resources
    core.resource_bundles = {
      'GCCore' => [
        "Resources/**/*.{lproj,png,jpg,zip,json,html,plist,sql}"
      ]
    }
   core.source_files = 'Classes/**/*.{h,m}', 
                          'Views/**/*.{h,m}', 
                          "AppSpecific/#{app_id.to_s}/*"

   core.frameworks = 'QuartzCore', 'MessageUI', 'CoreLocation', 'SystemConfiguration'
   core.xcconfig = { 'FRAMEWORK_SEARCH_PATHS' => '"$(PODS_ROOT)/../.." "$(PODS_ROOT)/.." "$(SRCROOT)/.."' }
   core.xcconfig = { 'OTHER_LDFLAGS' => '-all_load' }

   core.resources = [ "Resources/**/*.bundle" ]
end
```

The line causing this problem is:
```ruby
    core.resource_bundles = {
      'GCCore' => [
        "Resources/**/*.{lproj,png,jpg,zip,json,html,plist,sql}"
      ]
    }
```

Inside `Resources` is a `bundle` named `Settings.bundle`, containing the app's settings. If I remove the `bundle` or remove this line from my `Podfile`, it works just fine.

The `Settings.bundle` looks like this: 
![screenshot 2015-01-30 12 05 37](https://cloud.githubusercontent.com/assets/869950/5975411/5ecc13a6-a878-11e4-8bc2-5a1eb4cf9cab.png)

It has been working until now, and broke just recently. It probably makes sense, not having the bundle inside a bundle (not sure if that's even possible) but the error message is cryptic and should probably state a problem with bundles containing bundles. 

What do you think?

**Comment by neonichu** [comment]
> It has been working until now, and broke just recently.

I am assuming this worked with CP 0.35 then?

**Comment by KrauseFx** [comment]
I haven't changed anything on the project the last 5 months. Just recently tried to run `pod install` again. 
Should I try installing previous versions and let you know from which version on it broke?

**Comment by kylef** [comment]
@KrauseFx I think it would be more time effective to build an example podspec/project which reproduces this issue than trying various CocoaPods versions.

**Comment by spitfire2903** [comment]
I had the same error, but I cant find another bundle inside my lib
Doing pod repo push REPO ViewLib.podspec with --use-libraries works, but without this arguments have the same error, I put my podspec file below

### Command

```
/Users/ricardomiranda/.rvm/gems/ruby-2.1.3/bin/pod install
```

### Report

* What did you do?
I try to install the lib (pod install)

* What did you expect to happen?
Install this ViewLib in an Example project

* What happened instead?
Crashed, with the error below

### Stack

```
   CocoaPods : 0.37.1
        Ruby : ruby 2.1.3p242 (2014-09-19 revision 47630) [x86_64-darwin14.0]
    RubyGems : 2.2.2
        Host : Mac OS X 10.10.3 (14D136)
       Xcode : 6.3.1 (6D1002)
         Git : git version 2.3.2 (Apple Git-55)
Ruby lib dir : /Users/ricardomiranda/.rvm/rubies/ruby-2.1.3/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 38af63d04055b058e78e28fdfa2abcf424bb23a0
               Specs - http://192.168.0.161/Bonobo.Git.Server/Specs.git @ 396301dd3b87381503b3938adda8b8152cc1a66f
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-trunk   : 0.6.0
cocoapods-try     : 0.4.4
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
source 'http://192.168.0.161/Bonobo.Git.Server/Specs.git'

# inhibit_all_warnings!

pod 'iOSLib', :path => "../../iOSLib/"
pod 'ConnectorsLib', :path => "../../ConnectorsLib/"

# pod 'SVProgressHUD'

target 'ViewLib', :exclusive => true do
  pod "ViewLib", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "ViewLib", :path => "../"
end
```

### Error

```
NoMethodError - undefined method `new_file' for #<Xcodeproj::Project::Object::PBXFileReference:0x007fd04c552ef8>
/Users/ricardomiranda/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.1/lib/cocoapods/project.rb:196:in `add_file_reference'
/Users/ricardomiranda/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.1/lib/cocoapods/installer/file_references_installer.rb:168:in `block (2 levels) in add_file_accessors_paths_to_pods_group'
/Users/ricardomiranda/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.1/lib/cocoapods/installer/file_references_installer.rb:166:in `each'
/Users/ricardomiranda/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.1/lib/cocoapods/installer/file_references_installer.rb:166:in `block in add_file_accessors_paths_to_pods_group'
/Users/ricardomiranda/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.1/lib/cocoapods/installer/file_references_installer.rb:162:in `each'
/Users/ricardomiranda/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.1/lib/cocoapods/installer/file_references_installer.rb:162:in `add_file_accessors_paths_to_pods_group'
/Users/ricardomiranda/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.1/lib/cocoapods/installer/file_references_installer.rb:104:in `block in add_resources'
/Users/ricardomiranda/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.1/lib/cocoapods/user_interface.rb:110:in `message'
/Users/ricardomiranda/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.1/lib/cocoapods/installer/file_references_installer.rb:102:in `add_resources'
/Users/ricardomiranda/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.1/lib/cocoapods/installer/file_references_installer.rb:38:in `install!'
/Users/ricardomiranda/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.1/lib/cocoapods/installer.rb:495:in `install_file_references'
/Users/ricardomiranda/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.1/lib/cocoapods/installer.rb:131:in `block in generate_pods_project'
/Users/ricardomiranda/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.1/lib/cocoapods/user_interface.rb:49:in `section'
/Users/ricardomiranda/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.1/lib/cocoapods/installer.rb:129:in `generate_pods_project'
/Users/ricardomiranda/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.1/lib/cocoapods/installer.rb:97:in `install!'
/Users/ricardomiranda/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.1/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/ricardomiranda/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.1/lib/cocoapods/command/project.rb:101:in `run'
/Users/ricardomiranda/.rvm/gems/ruby-2.1.3/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Users/ricardomiranda/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.1/lib/cocoapods/command.rb:46:in `run'
/Users/ricardomiranda/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.1/bin/pod:44:in `<top (required)>'
/Users/ricardomiranda/.rvm/gems/ruby-2.1.3/bin/pod:23:in `load'
/Users/ricardomiranda/.rvm/gems/ruby-2.1.3/bin/pod:23:in `<main>'
/Users/ricardomiranda/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `eval'
/Users/ricardomiranda/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `<main>'
```

### Podspec

```ruby
Pod::Spec.new do |s|
  s.name             = "ViewLib"
  s.version          = "0.1.0"
  s.summary          = "View library
  s.description      = <<-DESC
                       View iOS library
                       DESC
  s.homepage         = "http://www.com.br/"
  s.license          = 'None'
  s.author           = { "Ricardo" => "email@com.br" }
  s.source           = { :svn => "svn_path" }

  s.platform     = :ios, '7.0'
  s.requires_arc = true

  s.source_files = 'Pod/Classes/**/*.{h,m}'

  s.public_header_files = 'Pod/Classes/**/*.h'
  s.resource_bundles = {
    'ViewLibResources' => ['Pod/Assets/Resources/*', 'Pod/Assets/Resources/**/*']
  }

  s.frameworks = 'Foundation', 'UIKit', 'MapKit', 'QuartzCore', 'CoreGraphics', 'CoreLocation', 'CoreText', 'SystemConfiguration'
  s.vendored_frameworks = 'Pod/Frameworks/GoogleMaps.framework'

  s.dependency 'ConnectorsLib'
  s.dependency 'iOSLib'
end
```

**Comment by spitfire2903** [comment]
With cocoapods 0.36 i got the same error

**Comment by mave99a** [comment]
Hit the same issue with 0.37.2

**Comment by skyline75489** [comment]
Same with 0.38.2. But it's OK in 0.35.0. 

Will anyone look into this?

**Comment by segiddins** [comment]
If you want us to be able to look into this, we need an example project that demonstrates the issue.

**Comment by skyline75489** [comment]
The info provided by @KrauseFx is not suffice?

I'm having this problem with company project, which I can not open source. But if you need more info, I'm willing to try to make some demo.

**Comment by mm188200** [comment]
Not sure why (on 0.38.2), but the order of the paths in the resource bundle was the issue for me:
`'ResourceBundle' => ['Pod/Assets/*', 'Pod/Assets/UIAssets/*' ]` 
through this error
`'OUSCommonLibrary' => [ 'Pod/Assets/UIAssets/*,'Pod/Assets/*']`
Worked fine - imagine it has to do with how it builds out the directories

**Comment by adriantofan** [comment]
I am having the same issue here. As @mm188200 noted it works by changing order of bundle resources. Please let me know if I can help somehow.

**Comment by neonichu** [comment]
This issue has been inactive for a long time and will be closed because we want to move forward with a clean slate after our 1.0 release. If you believe this is still relevant, please retest with the 1.0 release candidate and comment with a reproducible project in order for this to become actionable again. Thanks!
