### ISSUE TITLE
UnsupportedFileTypeError when pushing podspec

### ISSUE THREAD

**Issue by krohling** [CocoaPods/CocoaPods#3124]
First, since this is my first custom CocoaPod it's entirely possible that I'm doing something terribly wrong here.  Either way, a bit of help would be appreciated.

The issue is that when I run 'pod lib lint' my Podspec successfully passes validation.  However, when I try to call 'pod trunk push <Name>.podspec' I get the error below.

Also, here is my Podspec: https://github.com/emberlight/sible/blob/master/Sible.podspec

Thanks in advance!

### Report

* What did you do?
pod trunk push Sible.podspec

* What did you expect to happen?
Push pod into trunk.

* What happened instead?
This error message.

### Stack

```
   CocoaPods : 0.35.0
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.0.14
        Host : Mac OS X 10.10.1 (14B25)
       Xcode : 6.1.1 (6A2008a)
         Git : git version 2.0.1
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ d86b1f4a8373a4c17eb0a347a5e298cfff42b520
```

### Plugins

```
cocoapods-plugins : 0.3.2
cocoapods-trunk   : 0.1.4
cocoapods-try     : 0.4.3
```

### Error

```
Pod::Downloader::Http::UnsupportedFileTypeError - Unsupported file type: 
/Library/Ruby/Gems/2.0.0/gems/cocoapods-downloader-0.8.1/lib/cocoapods-downloader/http.rb:83:in `filename_with_type'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-downloader-0.8.1/lib/cocoapods-downloader/http.rb:21:in `download!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-downloader-0.8.1/lib/cocoapods-downloader/base.rb:80:in `block in download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/downloader.rb:29:in `block in ui_action'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/user_interface.rb:49:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/downloader.rb:28:in `ui_action'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-downloader-0.8.1/lib/cocoapods-downloader/base.rb:78:in `download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer/pod_source_installer.rb:98:in `download_source'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer/pod_source_installer.rb:45:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:298:in `install_source_of_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:273:in `block (2 levels) in install_pod_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/user_interface.rb:70:in `titled_section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:272:in `block in install_pod_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:264:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:264:in `install_pod_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:116:in `block in download_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/user_interface.rb:49:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:114:in `download_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:91:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/validator.rb:304:in `install_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/validator.rb:210:in `block in perform_extensive_analysis'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/validator.rb:206:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/validator.rb:206:in `perform_extensive_analysis'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/validator.rb:73:in `validate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-0.4.1/lib/pod/command/trunk/push.rb:106:in `validate_podspec'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-0.4.1/lib/pod/command/trunk/push.rb:56:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.7.0/lib/claide/command.rb:271:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/command.rb:45:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/bin/pod:43:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

**Comment by segiddins** [comment]
Your error is exactly what CocoaPods reported. The key in your source hash should be `git` instead of `http`.

**Comment by krohling** [comment]
Definitely my fault.  That fixed it and thanks for the help.
