### ISSUE TITLE
Ruby 2.2.0: pathname.rb:430:in `open': No such file or directory @ dir_initialize

### ISSUE THREAD

**Issue by jasperblues** [CocoaPods/CocoaPods#3126]
When using CocoaPods with Ruby 2.2.0, I get the follow error on `pod update`

```text
/Users/jblues/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/pathname.rb:430:in `open': No such file or directory @ dir_initialize - /Users/jblues/.cocoapods/repos (Errno::ENOENT)
	from /Users/jblues/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/pathname.rb:430:in `foreach'
	from /Users/jblues/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/pathname.rb:430:in `children'
	from /Users/jblues/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.35.0/lib/cocoapods/sources_manager.rb:63:in `all'
	from /Users/jblues/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.35.0/lib/cocoapods/user_interface/error_report.rb:130:in `repo_information'
	from /Users/jblues/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.35.0/lib/cocoapods/user_interface/error_report.rb:34:in `report'
	from /Users/jblues/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.35.0/lib/cocoapods/command.rb:58:in `report_error'
	from /Users/jblues/.rvm/gems/ruby-2.2.0/gems/claide-0.7.0/lib/claide/command.rb:300:in `handle_exception'
	from /Users/jblues/.rvm/gems/ruby-2.2.0/gems/claide-0.7.0/lib/claide/command.rb:274:in `rescue in run'
	from /Users/jblues/.rvm/gems/ruby-2.2.0/gems/claide-0.7.0/lib/claide/command.rb:264:in `run'
	from /Users/jblues/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.35.0/lib/cocoapods/command.rb:45:in `run'
	from /Users/jblues/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.35.0/bin/pod:43:in `<top (required)>'
	from /Users/jblues/.rvm/gems/ruby-2.2.0/bin/pod:23:in `load'
	from /Users/jblues/.rvm/gems/ruby-2.2.0/bin/pod:23:in `<main>'
	from /Users/jblues/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/jblues/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

I installed Ruby 2.2.0 using rvm, with MacPorts as the underlying package manager.

**Comment by jasperblues** [comment]
Ah looks like I needed to run `pod setup`

**Comment by jasperblues** [comment]
Let's leave this open actually. Better outcome would be: 

```
CocaPods repo environment not detected. Run 'pod setup' to initialize.
``` 

. . . or something to that effect.

**Comment by segiddins** [comment]
@jasperblues already been done in 0.36

**Comment by jasperblues** [comment]
@segiddins Awesome.
