### ISSUE TITLE
NoMethodError - undefined method `strip_heredoc' for Array

### ISSUE THREAD

**Issue by hoha** [CocoaPods/CocoaPods#3134]
### Command

```
/usr/bin/pod ipc list
```

### Notes

Also affects integration with JetBrains AppCode - https://youtrack.jetbrains.com/issue/OC-11579 .

### Stack

```
   CocoaPods : 0.36.0.beta.2
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin13]
    RubyGems : 2.4.5
        Host : Mac OS X 10.9.5 (13F34)
       Xcode : 6.1 (6A1046a)
         Git : git version 1.9.3 (Apple Git-50)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 100d5c8722cac0a697bef73b6fa3c99c5dbc567c
```

### Plugins

```
cocoapods-plugins : 0.4.0
cocoapods-trunk   : 0.5.0
cocoapods-try     : 0.4.3
```

### Error

```
NoMethodError - undefined method `strip_heredoc' for #<Array:0x007fe7ac1030d8>
/Users/hoha/.gem/ruby/2.0.0/gems/cocoapods-core-0.36.0.beta.2/lib/cocoapods-core/specification/root_attribute_accessors.rb:114:in `summary'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0.beta.2/lib/cocoapods/command/inter_process_communication.rb:87:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0.beta.2/lib/cocoapods/command/inter_process_communication.rb:82:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0.beta.2/lib/cocoapods/command/inter_process_communication.rb:82:in `run'
/Users/hoha/.gem/ruby/2.0.0/gems/claide-0.8.0/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0.beta.2/lib/cocoapods/command.rb:45:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0.beta.2/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

**Comment by neonichu** [comment]
Seems like this is caused by a problematic spec in the repo, which the linter didn't catch. There's an extra `,` in <https://github.com/cemolcay/PullToRefreshCoreText/blob/master/PullToRefreshCoreText.podspec#L20> which let to it becoming an array on trunk: <https://github.com/CocoaPods/Specs/blob/master/Specs/PullToRefreshCoreText/0.2/PullToRefreshCoreText.podspec.json>

**Comment by orta** [comment]
Done https://github.com/CocoaPods/Specs/blob/master/Specs/PullToRefreshCoreText/0.2/PullToRefreshCoreText.podspec.json

**Comment by hoha** [comment]
I can confirm that the original error is gone after `pod repo update`. Now it's 

### Error

```
NoMethodError - undefined method `to_yaml' for #<Hash:0x007fee058e7a60>
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0.beta.2/lib/cocoapods/command/inter_process_communication.rb:95:in `run'
/Users/hoha/.gem/ruby/2.0.0/gems/claide-0.8.0/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0.beta.2/lib/cocoapods/command.rb:45:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0.beta.2/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

:)

**Comment by hoha** [comment]
It works again. Thank you guys!

**Comment by luohaiquan** [comment]
。。
