### ISSUE TITLE
CocoaPods should catch the ArgumentError from Xcodeproj loading a project in a merge conflict

### ISSUE THREAD

**Issue by kylef** [CocoaPods/CocoaPods#3158]
We should catch and re-raise as informative (or find some other solution).

Currently it will use the markdown template.

```
ArgumentError - The file `/Users/kyle/Projects/cocode/palaver/Palaver.xcodeproj/project.pbxproj` is in a merge conflict
/Users/kyle/gems/gems/xcodeproj-0.21.2/lib/xcodeproj/plist_helper.rb:57:in `read'
/Users/kyle/gems/gems/xcodeproj-0.21.2/lib/xcodeproj/plist_helper.rb:6:in `read_plist'
/Users/kyle/gems/gems/xcodeproj-0.21.2/lib/xcodeproj/project.rb:201:in `initialize_from_file'
/Users/kyle/gems/gems/xcodeproj-0.21.2/lib/xcodeproj/project.rb:93:in `open'
/Users/kyle/gems/gems/cocoapods-0.36.0.beta.2/lib/cocoapods/installer/analyzer.rb:676:in `block (2 levels) in compute_target_platforms'
/Users/kyle/gems/gems/cocoapods-0.36.0.beta.2/lib/cocoapods/installer/analyzer.rb:673:in `each'
/Users/kyle/gems/gems/cocoapods-0.36.0.beta.2/lib/cocoapods/installer/analyzer.rb:673:in `block in compute_target_platforms'
/Users/kyle/gems/gems/cocoapods-0.36.0.beta.2/lib/cocoapods/user_interface.rb:49:in `section'
/Users/kyle/gems/gems/cocoapods-0.36.0.beta.2/lib/cocoapods/installer/analyzer.rb:672:in `compute_target_platforms'
/Users/kyle/gems/gems/cocoapods-0.36.0.beta.2/lib/cocoapods/installer/analyzer.rb:52:in `analyze'
/Users/kyle/gems/gems/cocoapods-0.36.0.beta.2/lib/cocoapods/installer.rb:186:in `analyze'
/Users/kyle/gems/gems/cocoapods-0.36.0.beta.2/lib/cocoapods/installer.rb:108:in `block in resolve_dependencies'
/Users/kyle/gems/gems/cocoapods-0.36.0.beta.2/lib/cocoapods/user_interface.rb:49:in `section'
/Users/kyle/gems/gems/cocoapods-0.36.0.beta.2/lib/cocoapods/installer.rb:107:in `resolve_dependencies'
/Users/kyle/gems/gems/cocoapods-0.36.0.beta.2/lib/cocoapods/installer.rb:90:in `install!'
/Users/kyle/gems/gems/cocoapods-0.36.0.beta.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/kyle/gems/gems/cocoapods-0.36.0.beta.2/lib/cocoapods/command/project.rb:101:in `run'
/Users/kyle/gems/gems/claide-0.8.0/lib/claide/command.rb:312:in `run'
/Users/kyle/gems/gems/cocoapods-0.36.0.beta.2/lib/cocoapods/command.rb:45:in `run'
/Users/kyle/gems/gems/cocoapods-0.36.0.beta.2/bin/pod:44:in `<top (required)>'
/Users/kyle/gems/bin/pod:23:in `load'
/Users/kyle/gems/bin/pod:23:in `<main>'
```

Originally from: https://github.com/CocoaPods/Xcodeproj/issues/238

**Comment by segiddins** [comment]
catch + re-raise would be the best bet

**Comment by segiddins** [comment]
Went another route.
