### ISSUE TITLE
Permission denied @ unlink_internal

### ISSUE THREAD

**Issue by lukeharries** [CocoaPods/CocoaPods#3187]
### Report

Already tried removing and rebuilding the master repo and re-setting the ownership of ~/.cocoapods.

I get this error when running pod install. 

### Stack

```
   CocoaPods : 0.35.0
        Ruby : ruby 2.1.3p242 (2014-09-19 revision 47630) [x86_64-darwin14.0]
    RubyGems : 2.2.2
        Host : Mac OS X 10.10.2 (14C109)
       Xcode : 6.1.1 (6A2008a)
         Git : git version 1.9.3 (Apple Git-50)
Ruby lib dir : /usr/local/Cellar/ruby/2.1.3/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ d3b2e259c0526716023d50074ea63add1fb27193
```

### Plugins

```
cocoapods-plugins : 0.3.2
cocoapods-trunk   : 0.4.1
cocoapods-try     : 0.4.2
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project

platform :ios, '8.0'

target 'SafeCurveSpeed' do

pod 'GBVersionTracking'
pod 'TSMessages'
pod 'CocoaLumberjack'
pod 'Instabug'

end

target 'SafeCurveSpeedTests' do

end
```

### Error

```
Errno::EACCES - Permission denied @ unlink_internal - /Users/lukeharries/TDG/Ball Bank Meter Project/SafeCurveSpeed V1/SafeCurveSpeed/Pods/Headers/Public/CocoaLumberjack/DDAbstractDatabaseLogger.h
/usr/local/Cellar/ruby/2.1.3/lib/ruby/2.1.0/fileutils.rb:1454:in `unlink'
/usr/local/Cellar/ruby/2.1.3/lib/ruby/2.1.0/fileutils.rb:1454:in `block in remove_file'
/usr/local/Cellar/ruby/2.1.3/lib/ruby/2.1.0/fileutils.rb:1459:in `platform_support'
/usr/local/Cellar/ruby/2.1.3/lib/ruby/2.1.0/fileutils.rb:1453:in `remove_file'
/usr/local/Cellar/ruby/2.1.3/lib/ruby/2.1.0/fileutils.rb:1442:in `remove'
/usr/local/Cellar/ruby/2.1.3/lib/ruby/2.1.0/fileutils.rb:776:in `block in remove_entry'
/usr/local/Cellar/ruby/2.1.3/lib/ruby/2.1.0/fileutils.rb:1492:in `block (2 levels) in postorder_traverse'
/usr/local/Cellar/ruby/2.1.3/lib/ruby/2.1.0/fileutils.rb:1492:in `block (2 levels) in postorder_traverse'
/usr/local/Cellar/ruby/2.1.3/lib/ruby/2.1.0/fileutils.rb:1496:in `postorder_traverse'
/usr/local/Cellar/ruby/2.1.3/lib/ruby/2.1.0/fileutils.rb:1491:in `block in postorder_traverse'
/usr/local/Cellar/ruby/2.1.3/lib/ruby/2.1.0/fileutils.rb:1490:in `each'
/usr/local/Cellar/ruby/2.1.3/lib/ruby/2.1.0/fileutils.rb:1490:in `postorder_traverse'
/usr/local/Cellar/ruby/2.1.3/lib/ruby/2.1.0/fileutils.rb:1491:in `block in postorder_traverse'
/usr/local/Cellar/ruby/2.1.3/lib/ruby/2.1.0/fileutils.rb:1490:in `each'
/usr/local/Cellar/ruby/2.1.3/lib/ruby/2.1.0/fileutils.rb:1490:in `postorder_traverse'
/usr/local/Cellar/ruby/2.1.3/lib/ruby/2.1.0/fileutils.rb:774:in `remove_entry'
/usr/local/Cellar/ruby/2.1.3/lib/ruby/2.1.0/fileutils.rb:632:in `block in rm_r'
/usr/local/Cellar/ruby/2.1.3/lib/ruby/2.1.0/fileutils.rb:628:in `each'
/usr/local/Cellar/ruby/2.1.3/lib/ruby/2.1.0/fileutils.rb:628:in `rm_r'
/usr/local/Cellar/ruby/2.1.3/lib/ruby/2.1.0/pathname.rb:570:in `rmtree'
/usr/local/lib/ruby/gems/2.1.0/gems/cocoapods-0.35.0/lib/cocoapods/sandbox/headers_store.rb:46:in `implode!'
/usr/local/lib/ruby/gems/2.1.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:223:in `clean_sandbox'
/usr/local/lib/ruby/gems/2.1.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:109:in `block in resolve_dependencies'
/usr/local/lib/ruby/gems/2.1.0/gems/cocoapods-0.35.0/lib/cocoapods/user_interface.rb:49:in `section'
/usr/local/lib/ruby/gems/2.1.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:105:in `resolve_dependencies'
/usr/local/lib/ruby/gems/2.1.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:90:in `install!'
/usr/local/lib/ruby/gems/2.1.0/gems/cocoapods-0.35.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/usr/local/lib/ruby/gems/2.1.0/gems/cocoapods-0.35.0/lib/cocoapods/command/project.rb:101:in `run'
/usr/local/lib/ruby/gems/2.1.0/gems/claide-0.7.0/lib/claide/command.rb:271:in `run'
/usr/local/lib/ruby/gems/2.1.0/gems/cocoapods-0.35.0/lib/cocoapods/command.rb:45:in `run'
/usr/local/lib/ruby/gems/2.1.0/gems/cocoapods-0.35.0/bin/pod:43:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by lukeharries** [comment]
Finally fixed this by recursively applying the right permissions to everything in the Pods folder
