### ISSUE TITLE
NoMethodError - undefined method `repo' for nil:NilClass

### ISSUE THREAD

**Issue by AnthonyMDev** [CocoaPods/CocoaPods#3189]
### Command

```
/Users/Anthony/.rvm/gems/ruby-2.1.2/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 0.36.0.beta.2
        Ruby : ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin13.0]
    RubyGems : 2.2.2
        Host : Mac OS X 10.10.2 (14C109)
       Xcode : 6.1.1 (6A2008a)
         Git : git version 1.9.3 (Apple Git-50)
Ruby lib dir : /Users/Anthony/.rvm/rubies/ruby-2.1.2/lib
Repositories : AO-Private-CocoaPods - https://AnthonyMDev@bitbucket.org/app-order/ao-private-cocoapods.git @ 9e4265f78371e7858b70ee12d37b509818377696
               ao-private-cocoapods-1 - /Users/Anthony/.cocoapods/repos/AO-Private-CocoaPods @ 9e4265f78371e7858b70ee12d37b509818377696
               master - https://github.com/CocoaPods/Specs.git @ 65a32dcf3130457c7fb83e949efc85a3f60fc983
               master-1 - /Users/Anthony/.cocoapods/repos/master @ 65a32dcf3130457c7fb83e949efc85a3f60fc983
```

### Plugins

```
cocoapods-plugins : 0.4.0
cocoapods-trunk   : 0.5.0
cocoapods-try     : 0.4.3
```

### Podfile

```ruby
platform :ios, '8.0'

use_frameworks!
inhibit_all_warnings!

source 'AO-Private-CocoaPods'
source 'master'

pod 'ZRLoginControllers', :path => '../ZRLoginControllers'
pod 'ZRAPI', :path => '../ZRAPI'
pod 'ZRModels', :path => '../ZRModels'
pod 'ZRUserAuthenticationManager', :path => '../ZRUserAuthenticationManager'

target :Zorts do
  pod 'MMDrawerController', '~> 0.5'
  pod 'AOCollectionTabController', '~> 0.1'
end

target :ZortsTests do
  
end
```

### Error

```
NoMethodError - undefined method `repo' for nil:NilClass
/Users/Anthony/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.36.0.beta.2/lib/cocoapods/installer/analyzer.rb:172:in `block (2 levels) in update_repositories_if_needed'
/Users/Anthony/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.36.0.beta.2/lib/cocoapods/installer/analyzer.rb:171:in `each'
/Users/Anthony/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.36.0.beta.2/lib/cocoapods/installer/analyzer.rb:171:in `block in update_repositories_if_needed'
/Users/Anthony/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.36.0.beta.2/lib/cocoapods/user_interface.rb:49:in `section'
/Users/Anthony/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.36.0.beta.2/lib/cocoapods/installer/analyzer.rb:170:in `update_repositories_if_needed'
/Users/Anthony/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.36.0.beta.2/lib/cocoapods/installer/analyzer.rb:50:in `analyze'
/Users/Anthony/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.36.0.beta.2/lib/cocoapods/installer.rb:186:in `analyze'
/Users/Anthony/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.36.0.beta.2/lib/cocoapods/installer.rb:108:in `block in resolve_dependencies'
/Users/Anthony/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.36.0.beta.2/lib/cocoapods/user_interface.rb:49:in `section'
/Users/Anthony/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.36.0.beta.2/lib/cocoapods/installer.rb:107:in `resolve_dependencies'
/Users/Anthony/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.36.0.beta.2/lib/cocoapods/installer.rb:90:in `install!'
/Users/Anthony/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.36.0.beta.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/Anthony/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.36.0.beta.2/lib/cocoapods/command/project.rb:101:in `run'
/Users/Anthony/.rvm/gems/ruby-2.1.2@global/gems/claide-0.8.0/lib/claide/command.rb:312:in `run'
/Users/Anthony/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.36.0.beta.2/lib/cocoapods/command.rb:45:in `run'
/Users/Anthony/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.36.0.beta.2/bin/pod:44:in `<top (required)>'
/Users/Anthony/.rvm/gems/ruby-2.1.2/bin/pod:23:in `load'
/Users/Anthony/.rvm/gems/ruby-2.1.2/bin/pod:23:in `<main>'
/Users/Anthony/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
/Users/Anthony/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by segiddins** [comment]
You need to specify URLs to the `source` flag.

**Comment by AnthonyMDev** [comment]
Testing that now. I read somewhere that you could provide just the names for repos that you have added to your `pod repo list`. Guess now.

**Comment by AnthonyMDev** [comment]
In 0.36.0 beta-2, is it required that I specify sources for private repositories? I used to be able to access them without listing any sources.

**Comment by segiddins** [comment]
That is a change in 0.36, please consult the CHANGELOG.

**Comment by AnthonyMDev** [comment]
Thank you.
