### ISSUE TITLE
Unable to find the specification EstimoteSDK (2.4.0) in the master source.

### ISSUE THREAD

**Issue by ostatnicky** [CocoaPods/CocoaPods#3203]
### Report

* I tried to update my pods.

* Until now everything works but now I can't install this pod (and version is the same)

### Stack

```
   CocoaPods : 0.35.0
        Ruby : ruby 2.0.0p247 (2013-06-27 revision 41674) [x86_64-darwin12.3.0]
    RubyGems : 2.2.2
        Host : Mac OS X 10.10.1 (14B25)
       Xcode : 6.1.1 (6A2008a)
         Git : git version 1.8.4
Ruby lib dir : /Users/ostatnickyjiri/.rvm/rubies/ruby-2.0.0-p247/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ d68ef606d6dca28978018903da19eb8f12b10c63
```

### Plugins

```
cocoapods-plugins : 0.3.1
cocoapods-trunk   : 0.4.1
cocoapods-try     : 0.4.2
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'
pod 'EstimoteSDK'
```

### Error

```
Pod::StandardError - Unable to find the specification EstimoteSDK (2.4.0) in the master source.
/Users/ostatnickyjiri/.rvm/gems/ruby-2.0.0-p247@global/gems/cocoapods-core-0.35.0/lib/cocoapods-core/source.rb:146:in `specification_path'
/Users/ostatnickyjiri/.rvm/gems/ruby-2.0.0-p247@global/gems/cocoapods-core-0.35.0/lib/cocoapods-core/source.rb:124:in `specification'
/Users/ostatnickyjiri/.rvm/gems/ruby-2.0.0-p247@global/gems/cocoapods-0.35.0/lib/cocoapods/resolver/lazy_specification.rb:26:in `specification'
/Users/ostatnickyjiri/.rvm/gems/ruby-2.0.0-p247@global/gems/cocoapods-0.35.0/lib/cocoapods/resolver/lazy_specification.rb:14:in `method_missing'
/Users/ostatnickyjiri/.rvm/gems/ruby-2.0.0-p247@global/gems/cocoapods-0.35.0/lib/cocoapods/resolver.rb:126:in `dependencies_for'
/Users/ostatnickyjiri/.rvm/gems/ruby-2.0.0-p247@global/gems/molinillo-0.1.2/lib/molinillo/resolution.rb:118:in `block (2 levels) in <class:Resolution>'
/Users/ostatnickyjiri/.rvm/gems/ruby-2.0.0-p247@global/gems/molinillo-0.1.2/lib/molinillo/resolution.rb:315:in `require_nested_dependencies_for'
/Users/ostatnickyjiri/.rvm/gems/ruby-2.0.0-p247@global/gems/molinillo-0.1.2/lib/molinillo/resolution.rb:307:in `activate_spec'
/Users/ostatnickyjiri/.rvm/gems/ruby-2.0.0-p247@global/gems/molinillo-0.1.2/lib/molinillo/resolution.rb:284:in `attempt_to_activate_new_spec'
/Users/ostatnickyjiri/.rvm/gems/ruby-2.0.0-p247@global/gems/molinillo-0.1.2/lib/molinillo/resolution.rb:251:in `attempt_to_activate'
/Users/ostatnickyjiri/.rvm/gems/ruby-2.0.0-p247@global/gems/molinillo-0.1.2/lib/molinillo/resolution.rb:134:in `process_topmost_state'
/Users/ostatnickyjiri/.rvm/gems/ruby-2.0.0-p247@global/gems/molinillo-0.1.2/lib/molinillo/resolution.rb:63:in `resolve'
/Users/ostatnickyjiri/.rvm/gems/ruby-2.0.0-p247@global/gems/molinillo-0.1.2/lib/molinillo/resolver.rb:40:in `resolve'
/Users/ostatnickyjiri/.rvm/gems/ruby-2.0.0-p247@global/gems/cocoapods-0.35.0/lib/cocoapods/resolver.rb:55:in `resolve'
/Users/ostatnickyjiri/.rvm/gems/ruby-2.0.0-p247@global/gems/cocoapods-0.35.0/lib/cocoapods/installer/analyzer.rb:377:in `block in resolve_dependencies'
/Users/ostatnickyjiri/.rvm/gems/ruby-2.0.0-p247@global/gems/cocoapods-0.35.0/lib/cocoapods/user_interface.rb:49:in `section'
/Users/ostatnickyjiri/.rvm/gems/ruby-2.0.0-p247@global/gems/cocoapods-0.35.0/lib/cocoapods/installer/analyzer.rb:375:in `resolve_dependencies'
/Users/ostatnickyjiri/.rvm/gems/ruby-2.0.0-p247@global/gems/cocoapods-0.35.0/lib/cocoapods/installer/analyzer.rb:58:in `analyze'
/Users/ostatnickyjiri/.rvm/gems/ruby-2.0.0-p247@global/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:184:in `analyze'
/Users/ostatnickyjiri/.rvm/gems/ruby-2.0.0-p247@global/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:106:in `block in resolve_dependencies'
/Users/ostatnickyjiri/.rvm/gems/ruby-2.0.0-p247@global/gems/cocoapods-0.35.0/lib/cocoapods/user_interface.rb:49:in `section'
/Users/ostatnickyjiri/.rvm/gems/ruby-2.0.0-p247@global/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:105:in `resolve_dependencies'
/Users/ostatnickyjiri/.rvm/gems/ruby-2.0.0-p247@global/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:90:in `install!'
/Users/ostatnickyjiri/.rvm/gems/ruby-2.0.0-p247@global/gems/cocoapods-0.35.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/ostatnickyjiri/.rvm/gems/ruby-2.0.0-p247@global/gems/cocoapods-0.35.0/lib/cocoapods/command/project.rb:101:in `run'
/Users/ostatnickyjiri/.rvm/gems/ruby-2.0.0-p247@global/gems/claide-0.7.0/lib/claide/command.rb:271:in `run'
/Users/ostatnickyjiri/.rvm/gems/ruby-2.0.0-p247@global/gems/cocoapods-0.35.0/lib/cocoapods/command.rb:45:in `run'
/Users/ostatnickyjiri/.rvm/gems/ruby-2.0.0-p247@global/gems/cocoapods-0.35.0/bin/pod:43:in `<top (required)>'
/Users/ostatnickyjiri/.rvm/gems/ruby-2.0.0-p247/bin/pod:23:in `load'
/Users/ostatnickyjiri/.rvm/gems/ruby-2.0.0-p247/bin/pod:23:in `<main>'
/Users/ostatnickyjiri/.rvm/gems/ruby-2.0.0-p247/bin/ruby_executable_hooks:15:in `eval'
/Users/ostatnickyjiri/.rvm/gems/ruby-2.0.0-p247/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by ostatnicky** [comment]
Hey, I found that
`pod repo remove master`
`pod setup`
resolved this prolem.

**Comment by kylef** [comment]
Thanks, I think this is a known issue (and fixed in CocoaPods 0.36.0).

**Comment by segiddins** [comment]
@kylef what issue do you think this is?

**Comment by kylef** [comment]
I though it was https://github.com/CocoaPods/CocoaPods/commit/0994612ebb65ad1aa221f384235e4702560df7d2 but just realised I was wrong.

**Comment by segiddins** [comment]
@ostatnicky if you come across this again, please share the output of `pod search EstimoteSDK`?

**Comment by kylef** [comment]
along with `pod repo list`

**Comment by OliverLetterer** [comment]
I just came across the same problem after upgrade to CocoaPods 0.36.0. `pod install` yields

```
Analyzing dependencies
[!] Unable to find a specification for `CCVFly (~> 0.3.2)`
```

```
pod repo list

master
- Type: git (origin)
- URL:  https://github.com/CocoaPods/Specs.git
- Path: /Users/oliver/.cocoapods/repos/master

sparrow-labs
- Type: git (origin)
- URL:  git@github.com:Sparrow-Labs/Specs.git
- Path: /Users/oliver/.cocoapods/repos/sparrow-labs

2 repos
```

```
pod search CCVFly


-> CCVFly (0.3.2)
   CCV Fly SDK.
   pod 'CCVFly', '~> 0.3.2'
   - Homepage: https://bitbucket.org/sparrowlabsde/ccvfly
   - Source:   git@bitbucket.org:sparrowlabsde/ccvfly.git
   - Versions: 0.3.2, 0.3.1, 0.3.0, 0.2.1, 0.2.0, 0.1.0 [sparrow-labs repo]
```

Completely removing and reinstalling CocoaPods and wiping `~/.cocoapods` didn't help :S

**Comment by OliverLetterer** [comment]
My bad, adding a `source` to my Podfile did the trick.
