### ISSUE TITLE
Working with new subspecs in development

### ISSUE THREAD

**Issue by mickeyreiss** [CocoaPods/CocoaPods#3210]
It seems that it is not possible to work with new subspecs in development the way I'd expect.

Steps to reproduce:
1. Fork a pod that currently has no subspecs
2. Modify your Podfile to point to the fork: `pod 'Something', :git => 'https://github.com/mickeyreiss/something.git', :branch => :master`
3. Modify your fork to add a new subspec
4. Modify your Podfile to point to the new subspec: `pod 'Something/Subspec', :git => 'https://github.com/mickeyreiss/something.git', :branch => :master`
5. `pod install`

During the "Resolving dependencies of `Podfile`" phase of `pod install`, I receive an error message:
   [!] Unable to find a specification named `coinbase-official/OAuth` in `coinbase-official (2.0.1)`.

#### Stacktrace

```
[redacted rvm dir]/gems/cocoapods-core-0.34.2/lib/cocoapods-core/specification.rb:208:in `subspec_by_name'
[redacted rvm dir]/gems/cocoapods-0.34.2/lib/cocoapods/resolver.rb:159:in `block (2 levels) in find_dependency_specs'
[redacted rvm dir]/gems/cocoapods-0.34.2/lib/cocoapods/user_interface.rb:110:in `message'
[redacted rvm dir]/gems/cocoapods-0.34.2/lib/cocoapods/resolver.rb:149:in `block in find_dependency_specs'
[redacted rvm dir]/gems/cocoapods-0.34.2/lib/cocoapods/resolver.rb:145:in `each'
[redacted rvm dir]/gems/cocoapods-0.34.2/lib/cocoapods/resolver.rb:145:in `find_dependency_specs'
[redacted rvm dir]/gems/cocoapods-0.34.2/lib/cocoapods/resolver.rb:71:in `block (2 levels) in resolve'
[redacted rvm dir]/gems/cocoapods-0.34.2/lib/cocoapods/user_interface.rb:49:in `section'
[redacted rvm dir]/gems/cocoapods-0.34.2/lib/cocoapods/resolver.rb:69:in `block in resolve'
[redacted rvm dir]/gems/cocoapods-0.34.2/lib/cocoapods/resolver.rb:66:in `each'
[redacted rvm dir]/gems/cocoapods-0.34.2/lib/cocoapods/resolver.rb:66:in `resolve'
[redacted rvm dir]/gems/cocoapods-0.34.2/lib/cocoapods/installer/analyzer.rb:322:in `block in resolve_dependencies'
[redacted rvm dir]/gems/cocoapods-0.34.2/lib/cocoapods/user_interface.rb:49:in `section'
[redacted rvm dir]/gems/cocoapods-0.34.2/lib/cocoapods/installer/analyzer.rb:320:in `resolve_dependencies'
[redacted rvm dir]/gems/cocoapods-0.34.2/lib/cocoapods/installer/analyzer.rb:55:in `analyze'
[redacted rvm dir]/gems/cocoapods-0.34.2/lib/cocoapods/installer.rb:184:in `analyze'
[redacted rvm dir]/gems/cocoapods-0.34.2/lib/cocoapods/installer.rb:106:in `block in resolve_dependencies'
[redacted rvm dir]/gems/cocoapods-0.34.2/lib/cocoapods/user_interface.rb:49:in `section'
[redacted rvm dir]/gems/cocoapods-0.34.2/lib/cocoapods/installer.rb:105:in `resolve_dependencies'
[redacted rvm dir]/gems/cocoapods-0.34.2/lib/cocoapods/installer.rb:90:in `install!'
[redacted rvm dir]/gems/cocoapods-0.34.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
[redacted rvm dir]/gems/cocoapods-0.34.2/lib/cocoapods/command/project.rb:101:in `run'
[redacted rvm dir]/gems/claide-0.7.0/lib/claide/command.rb:271:in `run'
[redacted rvm dir]/gems/cocoapods-0.34.2/lib/cocoapods/command.rb:48:in `run'
[redacted rvm dir]/gems/cocoapods-0.34.2/bin/pod:33:in `<top (required)>'
[redacted rvm dir]/bin/pod:23:in `load'
[redacted rvm dir]/bin/pod:23:in `<main>'
[redacted rvm dir]/bin/ruby_executable_hooks:15:in `eval'
[redacted rvm dir]/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by segiddins** [comment]
Does `pod update coinbase-official` work?

**Comment by kylef** [comment]
@mickeyreiss, can you try the command @segiddins mentioned?

**Comment by kylef** [comment]
@mickeyreiss ping.

**Comment by segiddins** [comment]
Closing due to lack of response.
