### ISSUE TITLE
NoMethodError - undefined method `[]' for nil:NilClass Xcode 6.2 Cocoapods 0.36.0

### ISSUE THREAD

**Issue by Alak** [CocoaPods/CocoaPods#3250]
### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?
pod install

* What did you expect to happen?
install my pod

* What happened instead?
error below

### Stack

```
   CocoaPods : 0.36.0
        Ruby : ruby 2.1.3p242 (2014-09-19 revision 47630) [x86_64-darwin14.0]
    RubyGems : 2.4.5
        Host : Mac OS X 10.10.2 (14C1510)
       Xcode : 6.2 (6C131e)
         Git : git version 2.1.2
Ruby lib dir : /usr/local/Cellar/ruby/2.1.3_1/lib
Repositories : artsy - https://github.com/artsy/Specs.git @ 0ac451b4b5ad3b6251c77663014b51a0048dde7e
               master - https://github.com/CocoaPods/Specs.git @ 327ab300c48400f6fd83b038527c082cb640e661
```

### Plugins

```
cocoapods-keys    : 1.0.0
cocoapods-plugins : 0.4.1
cocoapods-trunk   : 0.6.0
cocoapods-try     : 0.4.3
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Alamofire'
```

### Error

```
NoMethodError - undefined method `[]' for nil:NilClass
/usr/local/lib/ruby/gems/2.1.0/gems/cocoapods-keys-1.0.0/lib/preinstaller.rb:13:in `setup'
/usr/local/lib/ruby/gems/2.1.0/gems/cocoapods-keys-1.0.0/lib/plugin.rb:17:in `setup'
/usr/local/lib/ruby/gems/2.1.0/gems/cocoapods-keys-1.0.0/lib/plugin.rb:39:in `install!'
/usr/local/lib/ruby/gems/2.1.0/gems/cocoapods-0.36.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/usr/local/lib/ruby/gems/2.1.0/gems/cocoapods-0.36.0/lib/cocoapods/command/project.rb:101:in `run'
/usr/local/lib/ruby/gems/2.1.0/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/usr/local/lib/ruby/gems/2.1.0/gems/cocoapods-0.36.0/lib/cocoapods/command.rb:46:in `run'
/usr/local/lib/ruby/gems/2.1.0/gems/cocoapods-0.36.0/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by neonichu** [comment]
The stack trace shows that this is an issue with the [cocoapods-keys](https://github.com/orta/cocoapods-keys) plugin, not CocoaPods itself. Please open an appropriate issue there.
