### ISSUE TITLE
Crash on Pod Install With Xcode 6.2

### ISSUE THREAD

**Issue by esetnik** [CocoaPods/CocoaPods#3259]
### Command

```
/usr/local/opt/rbenv/versions/2.2.1/bin/pod install
```

### Report

* What did you do?
Tried to pod install

* What did you expect to happen?
I expected to install the local X podspec and it's dependencies

* What happened instead?
Crash

### Stack

```
   CocoaPods : 0.36.0
        Ruby : ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
    RubyGems : 2.4.5
        Host : Mac OS X 10.10.2 (14C1510)
       Xcode : 6.2 (6C131e)
         Git : git version 2.3.2
Ruby lib dir : /usr/local/opt/rbenv/versions/2.2.1/lib
Repositories : bitbucket-specs - ssh://git@bitbucket.org/<anonymized>/specs.git @ <anonymized>
               master - https://github.com/CocoaPods/Specs.git @ 1169df0fe16c341b9cfc8625e1b63f9f6e10c834
```

### Plugins

```
cocoapods-plugins : 0.4.1
cocoapods-trunk   : 0.6.0
cocoapods-try     : 0.4.3
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
pod 'X', :path => './'
```

### Local X.podspec

```
Pod::Spec.new do |s|

  s.name         = 'X'
  s.version      = '5.0.0'
  s.summary      = '<anonymized>'
  s.homepage     = '<anonymized>'
  s.description  = <<-DESC
                   <anonymized>
                   DESC

  s.license      = 'MIT'
  s.author       = { "<anonymized>" => "<anonymized>" }
  s.platform     = :ios, '7.0'
  s.source       = { :git => 'git@bitbucket.org:<anonymized>/<anonymized>.git', :tag => s.version }

  s.source_files = 'X/*.{h,m}'
  s.resources    = 'X/*.xcdatamodeld'
  s.frameworks   = 'SystemConfiguration','Foundation','CoreData'

  s.dependency 'CocoaLumberjack', '~> 2.0.0-rc'
  s.dependency 'AFNetworking', '~> 2.5.1'
  s.dependency 'MagicalRecord', '~> 2.2'

end
```

### Error

```
RuntimeError - [Xcodeproj] Type checking error: got `Fixnum` for attribute: Attribute `runOnlyForDeploymentPostprocessing` (type: `simple`, classes: `[String]`, owner class: `AbstractBuildPhase`)
/usr/local/opt/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/xcodeproj-0.23.0/lib/xcodeproj/project/object_attributes.rb:141:in `validate_value'
/usr/local/opt/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/xcodeproj-0.23.0/lib/xcodeproj/project/object_attributes.rb:318:in `block in attribute'
/usr/local/opt/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/xcodeproj-0.23.0/lib/xcodeproj/project/object_attributes.rb:106:in `set_value'
/usr/local/opt/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/xcodeproj-0.23.0/lib/xcodeproj/project/object.rb:270:in `block in configure_with_plist'
/usr/local/opt/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/xcodeproj-0.23.0/lib/xcodeproj/project/object.rb:269:in `each'
/usr/local/opt/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/xcodeproj-0.23.0/lib/xcodeproj/project/object.rb:269:in `configure_with_plist'
/usr/local/opt/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/xcodeproj-0.23.0/lib/xcodeproj/project.rb:246:in `new_from_plist'
/usr/local/opt/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/xcodeproj-0.23.0/lib/xcodeproj/project/object.rb:337:in `object_with_uuid'
/usr/local/opt/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/xcodeproj-0.23.0/lib/xcodeproj/project/object.rb:287:in `block (2 levels) in configure_with_plist'
/usr/local/opt/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/xcodeproj-0.23.0/lib/xcodeproj/project/object.rb:286:in `each'
/usr/local/opt/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/xcodeproj-0.23.0/lib/xcodeproj/project/object.rb:286:in `block in configure_with_plist'
/usr/local/opt/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/xcodeproj-0.23.0/lib/xcodeproj/project/object.rb:283:in `each'
/usr/local/opt/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/xcodeproj-0.23.0/lib/xcodeproj/project/object.rb:283:in `configure_with_plist'
/usr/local/opt/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/xcodeproj-0.23.0/lib/xcodeproj/project.rb:246:in `new_from_plist'
/usr/local/opt/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/xcodeproj-0.23.0/lib/xcodeproj/project/object.rb:337:in `object_with_uuid'
/usr/local/opt/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/xcodeproj-0.23.0/lib/xcodeproj/project/object.rb:287:in `block (2 levels) in configure_with_plist'
/usr/local/opt/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/xcodeproj-0.23.0/lib/xcodeproj/project/object.rb:286:in `each'
/usr/local/opt/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/xcodeproj-0.23.0/lib/xcodeproj/project/object.rb:286:in `block in configure_with_plist'
/usr/local/opt/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/xcodeproj-0.23.0/lib/xcodeproj/project/object.rb:283:in `each'
/usr/local/opt/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/xcodeproj-0.23.0/lib/xcodeproj/project/object.rb:283:in `configure_with_plist'
/usr/local/opt/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/xcodeproj-0.23.0/lib/xcodeproj/project.rb:246:in `new_from_plist'
/usr/local/opt/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/xcodeproj-0.23.0/lib/xcodeproj/project.rb:192:in `initialize_from_file'
/usr/local/opt/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/xcodeproj-0.23.0/lib/xcodeproj/project.rb:91:in `open'
/usr/local/opt/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/installer/analyzer.rb:676:in `block (2 levels) in compute_target_platforms'
/usr/local/opt/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/installer/analyzer.rb:673:in `each'
/usr/local/opt/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/installer/analyzer.rb:673:in `block in compute_target_platforms'
/usr/local/opt/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/user_interface.rb:49:in `section'
/usr/local/opt/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/installer/analyzer.rb:672:in `compute_target_platforms'
/usr/local/opt/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/installer/analyzer.rb:52:in `analyze'
/usr/local/opt/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/installer.rb:189:in `analyze'
/usr/local/opt/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/installer.rb:111:in `block in resolve_dependencies'
/usr/local/opt/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/user_interface.rb:49:in `section'
/usr/local/opt/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/installer.rb:110:in `resolve_dependencies'
/usr/local/opt/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/installer.rb:90:in `install!'
/usr/local/opt/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/usr/local/opt/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/command/project.rb:101:in `run'
/usr/local/opt/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/usr/local/opt/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/cocoapods-0.36.0/lib/cocoapods/command.rb:46:in `run'
/usr/local/opt/rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/cocoapods-0.36.0/bin/pod:44:in `<top (required)>'
/usr/local/opt/rbenv/versions/2.2.1/bin/pod:23:in `load'
/usr/local/opt/rbenv/versions/2.2.1/bin/pod:23:in `<main>'
```

**Comment by intrepidmatt** [comment]
I also got this error. Did you find a workaround?

**Comment by esetnik** [comment]
It turns out that this is an incompatibility between Cocoapods and a tool I was using called [ObjClean](http://objclean.com/index.php). ObjClean creates a run script that, once removed caused the Xcodeproj errors to go away.

**Comment by segiddins** [comment]
@esetnik can you please share the diff that made the errors go away?

**Comment by raulrea** [comment]
Removed the Objective-Clean script from the build phases of my project and the pods installed without issues!
Thanks for the tip @esetnik

**Comment by intrepidmatt** [comment]
We are also using ObjClean. Seems like this incompatibility was introduced in Cocoapods 0.36

**Comment by neonichu** [comment]
Looks like a bug in ObjClean's own Xcode project serialisation. It writes the project as XML, but uses the wrong type for one of the values:

```
<key>runOnlyForDeploymentPostprocessing</key>
<integer>0</integer>
```

You can either change that `integer` to `string` manually, toggle something inside Xcode to trigger a rewrite or use `xcproj touch` as a workaround - all of those will create a correct project file again.

Would be nice if someone reported it as a bug to the author so that they can fix it in a future version.

**Comment by esetnik** [comment]
They don't have a github repo or issue tracker but i'm going to report it to the author of ObjClean on twitter. Thanks for your help!
