### ISSUE TITLE
Cannot lib lint my pod. Validation fails on 0.36.0

### ISSUE THREAD

**Issue by guidomb** [CocoaPods/CocoaPods#3261]
I updated from cocoapods 0.35.0 to 0.36.0 in https://github.com/Wolox/WLXBluetoothDevice and now I cannot pass lib lint validation.
```
WLXBluetoothDevice (0.2.0-alpha)
    - ERROR | [iOS] Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - WARN  | [WLXBluetoothDevice/Core,WLXBluetoothDevice/ReactiveCocoa]  WLXBluetoothDevice/Pod/Classes/Core/WLXBluetoothDeviceDiscoverer.m:166:16: warning: unused variable 'errorMessage' [-Wunused-variable]
    - WARN  | [WLXBluetoothDevice/Core,WLXBluetoothDevice/ReactiveCocoa]  WLXBluetoothDevice/Pod/Classes/Core/WLXCentralManagerDelegate.m:41:16: warning: unused variable 'message' [-Wunused-variable]
    - WARN  | [WLXBluetoothDevice/Core,WLXBluetoothDevice/ReactiveCocoa]  WLXBluetoothDevice/Pod/Classes/Core/WLXCentralManagerDelegate.m:43:37: warning: unused variable 'previousConnectionManager' [-Wunused-variable]
    - NOTE  | [iOS]  error: make directory /var/folders/gf/dslbq4t94zg44sz7wnk2lg2r0000gp/T/CocoaPods/Lint/build/Release-iphonesimulator/Pods/WLXBluetoothDevice.framework/WLXBluetoothDevice.bundle: File exists
```

I deleted /var/folders/gf but the error remains. Any ideas?

**Comment by neonichu** [comment]
Seems like you're duplicating the resource bundle by including it in both of your subspecs: <https://github.com/Wolox/WLXBluetoothDevice/blob/master/WLXBluetoothDevice.podspec#L43-L45>

**Comment by guidomb** [comment]
I've just fixed that but the `pod lib lint` validation is not passing. Before deleting the duplicated resource bundle, when I ran `pod lib lint --verbose` the build was not passing. Now the build passes but the validation still fails.

The weird thing is that is working fine on 0.35.0 and Travis CI builds are passing https://travis-ci.org/Wolox/WLXBluetoothDevice/builds.

This is the output (trimmed) I get from `pod lib lint --verbose`:

```
** BUILD SUCCEEDED **

 -> WLXBluetoothDevice (0.2.0-alpha)
    - WARN  | [WLXBluetoothDevice/Core,WLXBluetoothDevice/ReactiveCocoa]  /Users/guidomb/Documents/projects/wolox/WLXBluetoothDevice/Pod/Classes/Core/WLXBluetoothDeviceDiscoverer.m:166:16: warning: unused variable 'errorMessage' [-Wunused-variable]
    - WARN  | [WLXBluetoothDevice/Core,WLXBluetoothDevice/ReactiveCocoa]  /Users/guidomb/Documents/projects/wolox/WLXBluetoothDevice/Pod/Classes/Core/WLXCentralManagerDelegate.m:41:16: warning: unused variable 'message' [-Wunused-variable]
    - WARN  | [WLXBluetoothDevice/Core,WLXBluetoothDevice/ReactiveCocoa]  /Users/guidomb/Documents/projects/wolox/WLXBluetoothDevice/Pod/Classes/Core/WLXCentralManagerDelegate.m:43:37: warning: unused variable 'previousConnectionManager' [-Wunused-variable]

Pods project available at `/var/folders/gf/dslbq4t94zg44sz7wnk2lg2r0000gp/T/CocoaPods/Lint/Pods/Pods.xcodeproj` for inspection.

[!] WLXBluetoothDevice did not pass validation.

/Users/guidomb/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.36.0/lib/cocoapods/command/lib.rb:166:in `block in run'
/Users/guidomb/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.36.0/lib/cocoapods/command/lib.rb:140:in `each'
/Users/guidomb/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.36.0/lib/cocoapods/command/lib.rb:140:in `run'
/Users/guidomb/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Users/guidomb/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.36.0/lib/cocoapods/command.rb:46:in `run'
/Users/guidomb/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.36.0/bin/pod:44:in `<top (required)>'
/Users/guidomb/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bin/pod:23:in `load'
/Users/guidomb/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bin/pod:23:in `<main>'
```

**Comment by neonichu** [comment]
It does not pass validation because there are compiler warnings, that's intended behaviour.

**Comment by guidomb** [comment]
OK but that is new behavior introduced in 0.36.0 isn't it?

**Comment by guidomb** [comment]
OK I've just checked the Changelog and in 0.36.0-beta2 Xcodebuild warnings are reported as warnings in pod lint instead of note. Time to kill thoese warnings. Thanks for your help @neonichu !!
