### ISSUE TITLE
[!] Oh no, an error occurred.

### ISSUE THREAD

**Issue by zhtut** [CocoaPods/CocoaPods#3271]
### Command

```
/usr/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 0.36.0
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.0.14
        Host : Mac OS X 10.10.2 (14C1510)
       Xcode : 6.2 (6C131e)
         Git : git version 1.9.5 (Apple Git-50.3)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : facebook - https://github.com/facebook/pop.git @ c1d4761386430c9849862707a14bc8347095bc30
               master - https://github.com/CocoaPods/Specs.git @ c03edfa4d2da3c40a7cf1007211dac76706ccff1
```

### Plugins

```
cocoapods-plugins : 0.4.1
cocoapods-trunk   : 0.4.0
cocoapods-try     : 0.4.3
```

### Podfile

```ruby
source ‘https://github.com/robbiehanson/XMPPFramework.git’
pod 'XMPPFramework', '~> 3.6.4’
```

### Error

```
SyntaxError - /Users/zhoutuguang/Desktop/My/TestXmpp/Podfile:2: unknown regexp options - gthb
/Users/zhoutuguang/Desktop/My/TestXmpp/Podfile:3: unterminated string meets end of file
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.36.0/lib/cocoapods-core/podfile.rb:254:in `eval'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.36.0/lib/cocoapods-core/podfile.rb:254:in `block in from_ruby'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.36.0/lib/cocoapods-core/podfile.rb:51:in `instance_eval'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.36.0/lib/cocoapods-core/podfile.rb:51:in `initialize'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.36.0/lib/cocoapods-core/podfile.rb:251:in `new'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.36.0/lib/cocoapods-core/podfile.rb:251:in `from_ruby'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.36.0/lib/cocoapods-core/podfile.rb:227:in `from_file'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/config.rb:176:in `podfile'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/command.rb:109:in `verify_podfile_exists!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/command/project.rb:100:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/command.rb:46:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'

**Comment by neonichu** [comment]
The issue is that you are using quote characters different from the single quote `'`. 

Also note that the repo you are defining as `source` is not a spec repo. You might want to take a look at the guides <http://guides.cocoapods.org/using/the-podfile.html>
