### ISSUE TITLE
NoMethodError - undefined method `[]' for #<Xcodeproj::Project::Object::PBXFileReference:0x007fdbaa3f8df0>

### ISSUE THREAD

**Issue by cooler333** [CocoaPods/CocoaPods#3272]
### Command

```
/usr/bin/pod install
```

### Report

* What did you do?
pod install

* What did you expect to happen?
installed

* What happened instead?
error

### Stack

```
   CocoaPods : 0.36.0
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.0.14
        Host : Mac OS X 10.10.2 (14C1510)
       Xcode : 6.2 (6C131e)
         Git : git version 1.9.5 (Apple Git-50.3)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 202fbf2ba33ec1fcd0508d4da83142ab87106db3
```

### Plugins

```
cocoapods-plugins : 0.4.1
cocoapods-trunk   : 0.3.0
cocoapods-try     : 0.4.3
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs'

xcodeproj 'DCClass Tests'
workspace '../DCClass'
inhibit_all_warnings!

platform :ios, '7.0'

target 'iOS Tests' do

pod 'OCMock', '~> 2.1.1'
pod 'Expecta', '~> 0.2.1'
pod 'DCClass', :path => '../'

end

target 'iOS UI Tests' do

pod 'OCMock', '~> 2.1.1'
pod 'Expecta', '~> 0.2.1'
pod 'DCClass', :path => '../'

end

post_install do |installer|
  installer.project.targets.each do |target|
    puts "#{target.name}"
  end
end
```

### Error

```
NoMethodError - undefined method `[]' for #<Xcodeproj::Project::Object::PBXFileReference:0x007fdbaa3f8df0>
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/project.rb:186:in `block in add_file_reference'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:263:in `block in each_filename'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:263:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:263:in `each_filename'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/project.rb:184:in `add_file_reference'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/installer/file_references_installer.rb:168:in `block (2 levels) in add_file_accessors_paths_to_pods_group'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/installer/file_references_installer.rb:166:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/installer/file_references_installer.rb:166:in `block in add_file_accessors_paths_to_pods_group'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/installer/file_references_installer.rb:162:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/installer/file_references_installer.rb:162:in `add_file_accessors_paths_to_pods_group'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/installer/file_references_installer.rb:104:in `block in add_resources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/user_interface.rb:110:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/installer/file_references_installer.rb:102:in `add_resources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/installer/file_references_installer.rb:38:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/installer.rb:486:in `install_file_references'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/installer.rb:130:in `block in generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/user_interface.rb:49:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/installer.rb:128:in `generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/installer.rb:96:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/command.rb:46:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'

**Comment by DanielTomlinson** [comment]
Hey @cooler333, Could you please post the podspec for DCClass?

**Comment by cooler333** [comment]
I've been fixed this. This was because of image.xcasset in podspec

**Comment by lazerwalker** [comment]
@cooler333 Would you mind explaining what you did to fix this? I'm seeing the same error with a project of my own.

(https://github.com/intentkit/IntentKit/blob/master/Podfile / https://github.com/intentkit/IntentKit/blob/master/IntentKit.podspec)

**Comment by cooler333** [comment]
@lazerwalker i just delete image.xcassets and move file out of xcassets catalogue to folders. 

```
s.subspec 'DCBundleHelper' do |ss|
    ss.ios.frameworks   = 'UIKit'
    ss.dependency 'DCClass/Log'

    ss.resource_bundle = {
      'ImageBundle' => [
        'DCClass/Resources/*.png'
      ]
    }
    ss.source_files     = 'DCClass/DCBundleHelper.{h,m}'
  end
```

**Comment by lazerwalker** [comment]
Hmm, my project isn't using an asset catalog anywhere in it. I'll just open a separate issue since you've closed this one.

Thanks for sharing!

**Comment by lazerwalker** [comment]
Or, rather, it appears this is already being tracked at #3195.

**Comment by gauravthummar** [comment]
There is nothing duplicate in my code. i just create fresh project. and also delete the image.xcassets file. but still it give same error. nothing workout.

With cocoapods 0.37.1 I got the same error
