### ISSUE TITLE
:parameters in Podfile not taken into account in 0.36

### ISSUE THREAD

**Issue by FredericJacobs** [CocoaPods/CocoaPods#3299]
Hi,
I had to downgrade to 0.35 because on 0.36 running `pod install` doesn't take into account the `:git`, `commit` and `:branch` parameter being passed.

These are some entries of my `Podfile` that are being installed but without respecting the extra parameters.

```
pod 'SocketRocket',               :git => 'https://github.com/FredericJacobs/SocketRocket.git', :commit => '73d8a19'
pod 'JSQMessagesViewController',  :git => 'https://github.com/WhisperSystems/JSQMessagesViewController', :branch => 'JSignalQ'
pod 'APDropDownNavToolbar',       :git => 'https://github.com/corbett/APDropDownNavToolbar.git', :branch => 'master'
pod 'EZAudio',                    :git => 'https://github.com/jackflips/EZAudio', :commit => '1620f19'
```

(Quickly looked through issues but couldn't find another instance of this)

**Comment by FredericJacobs** [comment]
I think however that #3292 is a consequence of this.

**Comment by segiddins** [comment]
@FredericJacobs I'm unable to reproduce the issue. Could you please share a runnable script that reliably reproduces it on 0.36?

**Comment by tarbrain** [comment]
Hi @segiddins,

you probably won't be able to find the error inside the Podfile.lock.
As far as I know the Podfile.lock looks ok. But the source code downloaded into the Pods project will be different from the code at the specified tag, branch, commit hash etc.

**Comment by segiddins** [comment]
Just following up on my request for a reproduction script?

**Comment by Benuuu** [comment]
I believe I'm also seeing this issue.  I'm investigating a reproduction case right now.

**Comment by Benuuu** [comment]
Reproduction case

Podfile has only the contents:
pod 'KIF', :git => 'git@github.com:onshape/KIF.git', :tag=>'v3.0.8-belmont-4'

1. Using cocoapods 0.35.0 run `pod install`
2. Commit the pods directory for the sake of viewing the diff.
3. Using cocoapods 0.36.1 run `pod install`
4. Observe many changed files from `git diff`

**Comment by segiddins** [comment]
OK I can reproduce this, thanks so much for the case @Benuuu! I'm going to see if I can fix it now...

**Comment by segiddins** [comment]
I'm fairly confident this is related to the change in the checksum due to the local podspec being converted to JSON

**Comment by segiddins** [comment]
This is fixed in 0.36.2.

**Comment by FredericJacobs** [comment]
Great! When will 0.36.2 be released on RubyGems?

**Comment by segiddins** [comment]
Just pushed the release to RubyGems!

**Comment by FredericJacobs** [comment]
Great. I'll give it a shot and keep you posted.

**Comment by FredericJacobs** [comment]
I'm getting the following output
### Stack

```
   CocoaPods : 0.36.2
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.0.14
        Host : Mac OS X 10.10.2 (14C1514)
       Xcode : 6.2 (6C131e)
         Git : git version 2.3.4
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 59c6745f97145796b74baeab8e3e8df5a7b2a736
```

### Plugins

```
cocoapods-plugins : 0.4.1
cocoapods-trunk   : 0.3.1
cocoapods-try     : 0.4.3
```

### Podfile

```ruby
platform :ios, '7.0'
source 'https://github.com/CocoaPods/Specs.git'
inhibit_all_warnings!

link_with ["Signal", "SignalTests"]

pod 'OpenSSL',                    '~> 1.0.201'
pod 'libPhoneNumber-iOS',         '~> 0.8.2'
pod 'AxolotlKit',                 '~> 0.6.2'
pod 'PastelogKit',                '~> 1.2'
pod 'TwistedOakCollapsingFutures','~> 1.0'
pod 'AFNetworking',               '~> 2.5.1'
pod 'Mantle',                     '~> 1.5'
pod 'FFCircularProgressView',     '>= 0.1'
pod 'SCWaveformView',             '~> 1.0'
pod 'YapDatabase/SQLCipher'
pod 'SSKeychain'
pod 'DJWActionSheet'

pod 'SocketRocket',               :git => 'https://github.com/FredericJacobs/SocketRocket.git', :commit => '73d8a19'
pod 'JSQMessagesViewController',  :git => 'https://github.com/WhisperSystems/JSQMessagesViewController', :commit => '9be8f6ed65eb55368a5ff767f055158cf585065f'
pod 'APDropDownNavToolbar',       :git => 'https://github.com/corbett/APDropDownNavToolbar.git', :branch => 'master'
pod 'UICKeyChainStore',           :podspec => 'Podspecs/UICKeyChainStore.podspec'
```

### Error

```
NoMethodError - undefined method `map' for #<String:0x007fcb790e2f08>
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.2/lib/cocoapods/executable.rb:57:in `execute_command'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.2/lib/cocoapods/downloader.rb:11:in `execute_command'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-downloader-0.8.1/lib/cocoapods-downloader/base.rb:152:in `block in executable'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-downloader-0.8.1/lib/cocoapods-downloader/git.rb:65:in `block in clone'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.2/lib/cocoapods/downloader.rb:44:in `block in ui_sub_action'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.2/lib/cocoapods/user_interface.rb:49:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.2/lib/cocoapods/downloader.rb:43:in `ui_sub_action'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-downloader-0.8.1/lib/cocoapods-downloader/git.rb:63:in `clone'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-downloader-0.8.1/lib/cocoapods-downloader/git.rb:29:in `download!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-downloader-0.8.1/lib/cocoapods-downloader/base.rb:80:in `block in download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.2/lib/cocoapods/downloader.rb:28:in `block in ui_action'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.2/lib/cocoapods/user_interface.rb:49:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.2/lib/cocoapods/downloader.rb:27:in `ui_action'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-downloader-0.8.1/lib/cocoapods-downloader/base.rb:78:in `download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.2/lib/cocoapods/external_sources/abstract_external_source.rb:103:in `block in pre_download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.2/lib/cocoapods/user_interface.rb:70:in `titled_section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.2/lib/cocoapods/external_sources/abstract_external_source.rb:99:in `pre_download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.2/lib/cocoapods/external_sources/downloader_source.rb:13:in `fetch'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.2/lib/cocoapods/installer/analyzer.rb:347:in `fetch_external_source'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.2/lib/cocoapods/installer/analyzer.rb:324:in `block (2 levels) in fetch_external_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.2/lib/cocoapods/installer/analyzer.rb:323:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.2/lib/cocoapods/installer/analyzer.rb:323:in `block in fetch_external_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.2/lib/cocoapods/user_interface.rb:49:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.2/lib/cocoapods/installer/analyzer.rb:322:in `fetch_external_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.2/lib/cocoapods/installer/analyzer.rb:57:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.2/lib/cocoapods/installer.rb:189:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.2/lib/cocoapods/installer.rb:111:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.2/lib/cocoapods/user_interface.rb:49:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.2/lib/cocoapods/installer.rb:110:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.2/lib/cocoapods/installer.rb:90:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.2/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.2/lib/cocoapods/command.rb:46:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.2/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

**Comment by segiddins** [comment]
Yup @FredericJacobs fix incoming, will land as 0.36.3.

**Comment by FredericJacobs** [comment]
Looks good to me in 0.36.3

**Comment by Benuuu** [comment]
Looks good to me in 0.36.3.

It does look like between 0.35.0 and 0.36.3 some files are being moved into a different directory (Build -> Private) is this expected?

**Comment by segiddins** [comment]
@Benuuu yes, that is expected.

**Comment by kylef** [comment]
@Benuuu Yes, please see the CHANGELOG:

![screen shot 2015-04-01 at 15 49 08](https://cloud.githubusercontent.com/assets/44164/6943553/afeb248c-d886-11e4-90ed-9c92dd5d0b8b.png)

**Comment by Benuuu** [comment]
@segiddins, it looks like your change addresses the issue where it was incorrectly calculating whether install needed to fetch or not, but it doesn't quite address the issue of why it was downloading the wrong source files (ignoring parameters provided in `Podfile`).  Is there potentially still an issue with this?

**Comment by segiddins** [comment]
What do you mean? Please open a new issue.

**Comment by Benuuu** [comment]
That is this issue.  My reproduction case has a Podfile with a specific repo and tag associated with it and at step 3 (0.36.1 pod install) it fetches from the wrong repository.  I expect it to fetch from the repository defined in the podfile (onshape/KIF) but it fetches from the original parent repository (kif-framework/KIF).

I suspect it has to do with the fact that the podspec defines kif-framework/KIF as its repository.

**Comment by segiddins** [comment]
Ah yeah there's no recovering from the damage done by installing with 0.36.1 except wiping out your `Pods` directory and installing from scratch, but the issue won't happen again since 0.36.3 was released.
