### ISSUE TITLE
[!] An unexpected error ocurred: <!DOCTYPE html>

### ISSUE THREAD

**Issue by bfeher** [CocoaPods/CocoaPods#3332]
Hi,

I keep encountering a pod spec submission error when using trunk. I'm not sure what's going on:

```
$ pod trunk push BFRadialWaveView.podspec --verbose
```

After a successful validation and build, the spec errors out when submitting:
```
** BUILD SUCCEEDED **

 -> BFRadialWaveView (1.4.3)

opening connection to trunk.cocoapods.org:443...
opened
starting SSL for trunk.cocoapods.org:443...
SSL established
<- "POST /api/v1/pods HTTP/1.1\r\nContent-Type: application/json; charset=utf-8\r\nAccept: application/json; charset=utf-8\r\nAuthorization: Token 5b22ee76d6df131d1407531b9613971c\r\nAccept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3\r\nUser-Agent: Ruby\r\nHost: trunk.cocoapods.org\r\nContent-Length: 527\r\n\r\n"
<- "{\"name\":\"BFRadialWaveView\",\"version\":\"1.4.3\",\"summary\":\"A mesmerizing view with lots of options. It is meant to be used with BFRadialWaveHUD, but you are free to take it :)\",\"homepage\":\"https://github.com/bfeher/BFRadialWaveView\",\"license\":{\"type\":\"MIT\",\"file\":\"LICENSE.md\"},\"authors\":{\"Bence Feher\":\"ben.feher@gmail.com\"},\"source\":{\"git\":\"https://github.com/bfeher/BFRadialWaveView.git\",\"tag\":\"1.4.3\"},\"platforms\":{\"ios\":\"7.0\"},\"dependencies\":{\"UIColor+BFPaperColors\":[]},\"source_files\":\"Classes/*.{h,m}\",\"requires_arc\":true}\n"
-> "HTTP/1.1 503 Service Unavailable\r\n"
-> "Connection: keep-alive\r\n"
-> "Server: Cowboy\r\n"
-> "Date: Mon, 30 Mar 2015 01:10:37 GMT\r\n"
-> "Content-Length: 484\r\n"
-> "Content-Type: text/html; charset=utf-8\r\n"
-> "Cache-Control: no-cache, no-store\r\n"
-> "\r\n"
reading 484 bytes...
-> "<!DOCTYPE html>\n    <html>\n    <head>\n      <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n      <style type=\"text/css\">\n        html, body, iframe { margin: 0; padding: 0; height: 100%; }\n        iframe { display: block; width: 100%; border: none; }\n      </style>\n    <title>Application Error</title>\n    </head>\n    <body>\n      <iframe src=\"//s3.amazonaws.com/heroku_pages/error.html\">\n        <p>Application Error</p>\n      </iframe>\n    </body>\n    </html>"
read 484 bytes
Conn keep-alive
[!] An unexpected error ocurred: <!DOCTYPE html>
    <html>
    <head>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <style type="text/css">
        html, body, iframe { margin: 0; padding: 0; height: 100%; }
        iframe { display: block; width: 100%; border: none; }
      </style>
    <title>Application Error</title>
    </head>
    <body>
      <iframe src="//s3.amazonaws.com/heroku_pages/error.html">
        <p>Application Error</p>
      </iframe>
    </body>
    </html>

/Users/bence/.rvm/gems/ruby-2.1.3@global/gems/cocoapods-trunk-0.4.1/lib/pod/command/trunk.rb:67:in `print_error'
/Users/bence/.rvm/gems/ruby-2.1.3@global/gems/cocoapods-trunk-0.4.1/lib/pod/command/trunk.rb:26:in `request_url'
/Users/bence/.rvm/gems/ruby-2.1.3@global/gems/cocoapods-trunk-0.4.1/lib/pod/command/trunk.rb:32:in `request_path'
/Users/bence/.rvm/gems/ruby-2.1.3@global/gems/cocoapods-trunk-0.4.1/lib/pod/command/trunk/push.rb:57:in `run'
/Users/bence/.rvm/gems/ruby-2.1.3@global/gems/claide-0.7.0/lib/claide/command.rb:271:in `run'
/Users/bence/.rvm/gems/ruby-2.1.3@global/gems/cocoapods-0.35.0/lib/cocoapods/command.rb:45:in `run'
/Users/bence/.rvm/gems/ruby-2.1.3@global/gems/cocoapods-0.35.0/bin/pod:43:in `<top (required)>'
/Users/bence/.rvm/gems/ruby-2.1.3/bin/pod:23:in `load'
/Users/bence/.rvm/gems/ruby-2.1.3/bin/pod:23:in `<main>'
/Users/bence/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `eval'
/Users/bence/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `<main>'
```

Version:
```
$ pod --version
0.35.0
```

Any ideas? Sorry that I couldn't be of more help! If you need anymore info please ask.
Thanks!

**Comment by bfeher** [comment]
I tried again 15 minutes later and it went though. I wonder if it was network error on my end or perhaps maintenance on yours? Anyways, it seems to be going through now, thanks!

**Comment by skywinder** [comment]
Hi! I've got this probem for my 2 pods. What the reason of this problem?
