### ISSUE TITLE
pod update fails with RuntimeError - [Xcodeproj] Unknown object version.

### ISSUE THREAD

**Issue by andstdout** [CocoaPods/CocoaPods#3339]
Below you'll find the logged output from "pod update" command. 
I've the same error with another Podfiles in the same Xcode- Project.

### Command

```
/usr/bin/pod update
```

### Report

* What did you do?
Tried to install or update any Pods within my Xcode 6.3 beta 4 project.

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 0.36.1
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.4.6
        Host : Mac OS X 10.10.2 (14C1514)
       Xcode : 6.3 (6D543q)
         Git : git version 2.3.0 (Apple Git-54)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ a5251334ef1d7345d5f3812e710eea45cbdef662
```

### Plugins

```
cocoapods-plugins : 0.4.1
cocoapods-trunk   : 0.6.0
cocoapods-try     : 0.4.3
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'xcode-6.3'
use_frameworks!
```

### Error

```
RuntimeError - [Xcodeproj] Unknown object version.
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.23.1/lib/xcodeproj/project.rb:206:in `initialize_from_file'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.23.1/lib/xcodeproj/project.rb:91:in `open'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.1/lib/cocoapods/installer/analyzer.rb:676:in `block (2 levels) in compute_target_platforms'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.1/lib/cocoapods/installer/analyzer.rb:673:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.1/lib/cocoapods/installer/analyzer.rb:673:in `block in compute_target_platforms'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.1/lib/cocoapods/user_interface.rb:49:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.1/lib/cocoapods/installer/analyzer.rb:672:in `compute_target_platforms'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.1/lib/cocoapods/installer/analyzer.rb:52:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.1/lib/cocoapods/installer.rb:189:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.1/lib/cocoapods/installer.rb:111:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.1/lib/cocoapods/user_interface.rb:49:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.1/lib/cocoapods/installer.rb:110:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.1/lib/cocoapods/installer.rb:90:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.1/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.1/lib/cocoapods/command/project.rb:155:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.1/lib/cocoapods/command.rb:46:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.1/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

**Comment by neonichu** [comment]
See CocoaPods/Xcodeproj#253

You can probably get around it by saving the project in the 3.2 compatible format.
