### ISSUE TITLE
can not "pod install" or "pod update"

### ISSUE THREAD

**Issue by minhochoi** [CocoaPods/CocoaPods#3345]
――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 0.36.2
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.0.14
        Host : Mac OS X 10.10 (14A389)
       Xcode : 6.2 (6C131e)
         Git : git version 1.9.5 (Apple Git-50.3)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ b1877d90e59f3b33d81817c11765984af39f8562
```

### Plugins

```
cocoapods-plugins : 0.4.1
cocoapods-trunk   : 0.6.0
cocoapods-try     : 0.4.3
```

### Podfile

```ruby
platform :ios, '7.0'

pod 'AFNetworking', '~> 2.4.1'
pod 'MBProgressHUD'
pod 'PDKeychainBindingsController'
pod 'BlocksKit'
pod 'SMPageControl'
pod 'FLKAutoLayout'
```

### Error

```
NoMethodError - undefined method `map' for #<String:0x007fa951bf2910>
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.2/lib/cocoapods/executable.rb:57:in `execute_command'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.2/lib/cocoapods/downloader.rb:11:in `execute_command'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-downloader-0.8.1/lib/cocoapods-downloader/base.rb:152:in `block in executable'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-downloader-0.8.1/lib/cocoapods-downloader/git.rb:65:in `block in clone'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.2/lib/cocoapods/downloader.rb:44:in `block in ui_sub_action'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.2/lib/cocoapods/user_interface.rb:49:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.2/lib/cocoapods/downloader.rb:43:in `ui_sub_action'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-downloader-0.8.1/lib/cocoapods-downloader/git.rb:63:in `clone'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-downloader-0.8.1/lib/cocoapods-downloader/git.rb:29:in `download!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-downloader-0.8.1/lib/cocoapods-downloader/base.rb:80:in `block in download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.2/lib/cocoapods/downloader.rb:28:in `block in ui_action'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.2/lib/cocoapods/user_interface.rb:49:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.2/lib/cocoapods/downloader.rb:27:in `ui_action'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-downloader-0.8.1/lib/cocoapods-downloader/base.rb:78:in `download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.2/lib/cocoapods/installer/pod_source_installer.rb:98:in `download_source'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.2/lib/cocoapods/installer/pod_source_installer.rb:45:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.2/lib/cocoapods/installer.rb:303:in `install_source_of_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.2/lib/cocoapods/installer.rb:278:in `block (2 levels) in install_pod_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.2/lib/cocoapods/user_interface.rb:70:in `titled_section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.2/lib/cocoapods/installer.rb:277:in `block in install_pod_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.2/lib/cocoapods/installer.rb:269:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.2/lib/cocoapods/installer.rb:269:in `install_pod_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.2/lib/cocoapods/installer.rb:121:in `block in download_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.2/lib/cocoapods/user_interface.rb:49:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.2/lib/cocoapods/installer.rb:119:in `download_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.2/lib/cocoapods/installer.rb:91:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.2/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.2/lib/cocoapods/command.rb:46:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.2/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

**Comment by segiddins** [comment]
This should be fixed now in 0.36.3.
