### ISSUE TITLE
 pod repo push

### ISSUE THREAD

**Issue by congni** [CocoaPods/CocoaPods#3370]
haojuconideiMac:IOSFrameLibrary haoju-congni$ pod repo push IOSFrameLibrary IOSFrameLibrary.podspec

Validating spec

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/bin/pod repo push IOSFrameLibrary IOSFrameLibrary.podspec
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 0.36.1
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.4.6
        Host : Mac OS X 10.10 (14A389)
       Xcode : 6.2 (6C131e)
         Git : git version 1.9.5 (Apple Git-50.3)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : IOSFrameLibrary - git@git.oschina.net:congni/IOSFrameLibrary.git @ f50e4d7504f0908098caa478f9ac6a896d4a1441
               master -  @ fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
HEAD
               master-1 - https://github.com/CocoaPods/Specs.git @ 762b6a2d621dafd002792979c32e1b10bc0d6eb3
```

### Plugins

```
cocoapods-packager : 1.1.1
cocoapods-plugins  : 0.4.1
cocoapods-trunk    : 0.6.0
cocoapods-try      : 0.4.3
```

### Error

```
NoMethodError - undefined method `downcase' for nil:NilClass
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.1/lib/cocoapods/sources_manager.rb:412:in `source_with_url'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.1/lib/cocoapods/sources_manager.rb:38:in `find_or_create_source_with_url'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.1/lib/cocoapods/sources_manager.rb:71:in `source_with_name_or_url'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.1/lib/cocoapods/validator.rb:26:in `block in initialize'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.1/lib/cocoapods/validator.rb:26:in `map'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.1/lib/cocoapods/validator.rb:26:in `initialize'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.1/lib/cocoapods/command/repo/push.rb:87:in `new'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.1/lib/cocoapods/command/repo/push.rb:87:in `block in validate_podspec_files'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.1/lib/cocoapods/command/repo/push.rb:86:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.1/lib/cocoapods/command/repo/push.rb:86:in `validate_podspec_files'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.1/lib/cocoapods/command/repo/push.rb:44:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.1/lib/cocoapods/command.rb:46:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.1/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=undefined+method+%60downcase%27+for+nil%3ANilClass&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

**Comment by orta** [comment]
Looks like you have an odd private pods `repo`, running `pod repo remove IOSFrameLibrary` should get you back to normal.

**Comment by orta** [comment]
I'd recommend going through this guide: https://guides.cocoapods.org/making/private-cocoapods.html
