### ISSUE TITLE
Doesn't work on Yosemite 10.10.3

### ISSUE THREAD

**Issue by brightsider** [CocoaPods/CocoaPods#3378]
Hello. I'm upgrade Yosemite to 10.10.3 and CocoaPods stop install and update pods.
Log:

### Stack
```
   CocoaPods : 0.36.3
        Ruby : rubinius 2.2.10 (2.1.0 bf61ae2e 2014-06-27 JI) [x86_64-darwin14.1.0]
    RubyGems : 2.2.2
        Host : Mac OS X 10.10.3 (14D131)
       Xcode : 6.3 (6D570)
         Git : git version 2.3.2 (Apple Git-55)
Ruby lib dir : /Users/User/.rbenv/versions/rbx-2.2.10/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 5bbc868df0632cc464e252e70029506c195e8751
```

### Plugins

```
cocoapods-plugins : 0.4.1
cocoapods-trunk   : 0.6.0
cocoapods-try     : 0.4.3
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'


//pods
```

### Error

```
LoadError - no such file to load -- fiddle
kernel/common/code_loader.rb:441:in `load_error'
kernel/common/code_loader.rb:425:in `resolve_require_path'
kernel/common/code_loader.rb:103:in `require'
kernel/bootstrap/rubinius.rb:137:in `synchronize'
kernel/common/code_loader.rb:102:in `require'
kernel/common/code_loader.rb:237:in `require'
kernel/common/kernel.rb:705:in `gem_original_require (require)'
/Users/User/.rbenv/versions/rbx-2.2.10/library/rubygems/core_ext/kernel_require.rb:126:in `require'
/Users/User/.rbenv/versions/rbx-2.2.10/gems/gems/xcodeproj-0.23.1/lib/xcodeproj/plist_helper.rb:1:in `__script__'
kernel/common/code_loader.rb:243:in `require'
kernel/common/kernel.rb:705:in `gem_original_require (require)'
/Users/User/.rbenv/versions/rbx-2.2.10/library/rubygems/core_ext/kernel_require.rb:73:in `require'
/Users/User/.rbenv/versions/rbx-2.2.10/gems/gems/xcodeproj-0.23.1/lib/xcodeproj/project.rb:6:in `__script__'
kernel/common/code_loader.rb:243:in `require'
kernel/common/autoload.rb:55:in `resolve'
/Users/User/.rbenv/versions/rbx-2.2.10/gems/gems/cocoapods-0.36.3/lib/cocoapods/installer/analyzer.rb:676:in `compute_target_platforms'
kernel/bootstrap/array.rb:76:in `each'
/Users/User/.rbenv/versions/rbx-2.2.10/gems/gems/cocoapods-0.36.3/lib/cocoapods/installer/analyzer.rb:673:in `compute_target_platforms'
/Users/User/.rbenv/versions/rbx-2.2.10/gems/gems/cocoapods-0.36.3/lib/cocoapods/user_interface.rb:49:in `section'
/Users/User/.rbenv/versions/rbx-2.2.10/gems/gems/cocoapods-0.36.3/lib/cocoapods/installer/analyzer.rb:672:in `compute_target_platforms'
/Users/User/.rbenv/versions/rbx-2.2.10/gems/gems/cocoapods-0.36.3/lib/cocoapods/installer/analyzer.rb:52:in `analyze'
/Users/User/.rbenv/versions/rbx-2.2.10/gems/gems/cocoapods-0.36.3/lib/cocoapods/installer.rb:189:in `analyze'
/Users/User/.rbenv/versions/rbx-2.2.10/gems/gems/cocoapods-0.36.3/lib/cocoapods/installer.rb:111:in `resolve_dependencies'
/Users/User/.rbenv/versions/rbx-2.2.10/gems/gems/cocoapods-0.36.3/lib/cocoapods/user_interface.rb:49:in `section'
/Users/User/.rbenv/versions/rbx-2.2.10/gems/gems/cocoapods-0.36.3/lib/cocoapods/installer.rb:110:in `resolve_dependencies'
/Users/User/.rbenv/versions/rbx-2.2.10/gems/gems/cocoapods-0.36.3/lib/cocoapods/installer.rb:90:in `install!'
/Users/User/.rbenv/versions/rbx-2.2.10/gems/gems/cocoapods-0.36.3/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/User/.rbenv/versions/rbx-2.2.10/gems/gems/cocoapods-0.36.3/lib/cocoapods/command/project.rb:101:in `run'
/Users/User/.rbenv/versions/rbx-2.2.10/gems/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Users/User/.rbenv/versions/rbx-2.2.10/gems/gems/cocoapods-0.36.3/lib/cocoapods/command.rb:46:in `run'
/Users/User/.rbenv/versions/rbx-2.2.10/gems/gems/cocoapods-0.36.3/bin/pod:44:in `__script__'
kernel/common/kernel.rb:447:in `load'
/Users/User/.rbenv/versions/rbx-2.2.10/bin/pod:23:in `__script__'
kernel/common/block_environment.rb:53:in `call_on_instance'
kernel/common/eval.rb:176:in `eval'
/Users/User/.rbenv/versions/rbx-2.2.10/bin/ruby_executable_hooks:15:in `__script__'
kernel/delta/code_loader.rb:66:in `load_script'
kernel/delta/code_loader.rb:152:in `load_script'
kernel/loader.rb:649:in `script'
kernel/loader.rb:825:in `main'

**Comment by neonichu** [comment]
You are using a custom-build Ruby which does not have the fiddle gem. Please revert to system Ruby or a custom one that does have fiddle.

**Comment by segiddins** [comment]
@neonichu should we rescue that load error and raise an informative?

**Comment by neonichu** [comment]
Wouldn’t say so, it's part of MRI. Anything could be theoretically missing from crazy Rubies :)

**Comment by segiddins** [comment]
@neonichu sure it ships in MRI, but I don't think its technically part of the stdlib?

**Comment by neonichu** [comment]
Not sure, probably not.
