### ISSUE TITLE
XCode6.3-compatible project document crashes the pod install process

### ISSUE THREAD

**Issue by bontoJR** [CocoaPods/CocoaPods#3379]
I was trying the new XCode 6.3 switching to the new project document format and is actually crashing the process. I guess the problem is that some code doesn't recognize the new format.

Here's the template:

### Command

```
/Users/bontoJR/.rvm/gems/ruby-2.2.1/bin/pod install
```

### Report

* What did you do?
Switched the project format from 3.2-compatible to 6.3-compatible.
Performed  `pod install`

* What did you expect to happen?
To either complete the workspace with pods generation or an error about the currently missing support for the 6.3 project structure.

* What happened instead?
Crash.

### Stack

```
   CocoaPods : 0.36.3
        Ruby : ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
    RubyGems : 2.4.6
        Host : Mac OS X 10.10.3 (14D131)
       Xcode : 6.3 (6D570)
         Git : git version 2.3.2 (Apple Git-55)
Ruby lib dir : /Users/bontoJR/.rvm/rubies/ruby-2.2.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ ee66c4d1d397885bbee394041dcb69a8338181db
               obviousengineering - https://github.com/obviousengineering/OEPodSpecs.git @ d662ddb86e51ee1e85836a530d53a26d838cc7fb
```

### Plugins

```
cocoapods-plugins : 0.4.1
cocoapods-trunk   : 0.6.0
cocoapods-try     : 0.4.3
```

### Podfile

```ruby
platform :ios, '7.0'

pod 'RestKit', '~> 0.24.0'
pod 'Facebook-iOS-SDK', '~> 3.21.1'
pod 'libextobjc/EXTScope', '~> 0.4.1'
pod 'SDWebImage', '~> 3.7'
pod 'DZNSegmentedControl', '~> 1.1.0'
pod 'ARAnalytics/NewRelic'
pod 'ARAnalytics/GoogleAnalytics'
pod 'ARAnalytics/HeapAnalytics'
pod 'CrashlyticsFramework'
pod 'ARAnalytics/Crashlytics'
pod 'PromiseKit'
pod 'PSTAlertController'
pod 'MobihelpSDK'
pod 'WEPopover'

# Git pods
pod 'ELFixSecureTextFieldFont', :git => 'https://github.com/elegion/ELFixSecureTextFieldFont.git'

#pod 'ARAnalytics/HockeyApp'

### Error

RuntimeError - [Xcodeproj] Unknown object version.
/Users/bontoJR/.rvm/gems/ruby-2.2.1/gems/xcodeproj-0.23.1/lib/xcodeproj/project.rb:206:in `initialize_from_file'
/Users/bontoJR/.rvm/gems/ruby-2.2.1/gems/xcodeproj-0.23.1/lib/xcodeproj/project.rb:91:in `open'
/Users/bontoJR/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.36.3/lib/cocoapods/installer/analyzer.rb:676:in `block (2 levels) in compute_target_platforms'
/Users/bontoJR/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.36.3/lib/cocoapods/installer/analyzer.rb:673:in `each'
/Users/bontoJR/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.36.3/lib/cocoapods/installer/analyzer.rb:673:in `block in compute_target_platforms'
/Users/bontoJR/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.36.3/lib/cocoapods/user_interface.rb:49:in `section'
/Users/bontoJR/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.36.3/lib/cocoapods/installer/analyzer.rb:672:in `compute_target_platforms'
/Users/bontoJR/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.36.3/lib/cocoapods/installer/analyzer.rb:52:in `analyze'
/Users/bontoJR/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.36.3/lib/cocoapods/installer.rb:189:in `analyze'
/Users/bontoJR/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.36.3/lib/cocoapods/installer.rb:111:in `block in resolve_dependencies'
/Users/bontoJR/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.36.3/lib/cocoapods/user_interface.rb:49:in `section'
/Users/bontoJR/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.36.3/lib/cocoapods/installer.rb:110:in `resolve_dependencies'
/Users/bontoJR/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.36.3/lib/cocoapods/installer.rb:90:in `install!'
/Users/bontoJR/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.36.3/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/bontoJR/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.36.3/lib/cocoapods/command/project.rb:101:in `run'
/Users/bontoJR/.rvm/gems/ruby-2.2.1/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Users/bontoJR/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.36.3/lib/cocoapods/command.rb:46:in `run'
/Users/bontoJR/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.36.3/bin/pod:44:in `<top (required)>'
/Users/bontoJR/.rvm/gems/ruby-2.2.1/bin/pod:23:in `load'
/Users/bontoJR/.rvm/gems/ruby-2.2.1/bin/pod:23:in `<main>'
/Users/bontoJR/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
/Users/bontoJR/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by neonichu** [comment]
Thanks, this is a known issue: CocoaPods/Xcodeproj#253
