### ISSUE TITLE
Error validating podspec when resource bundle is used

### ISSUE THREAD

**Issue by mjholgate** [CocoaPods/CocoaPods#3380]
I'm getting a really odd error when validating one of my podspecs, since updating from 0.36.0.beta.1 to 0.36.0. I recently upgraded to 0.36.3, and the problem still persists.

It seems to be something to do with the use of a resource bundle - if I comment this out of the podspec, then verification succeeds. Weirdly, it looks like it is trying to delete a Localizable.strings file which doesn't exist - in fact, the "SKYSinaWeiboProviderResource.bundle" folder isn't present at all!

```
pod lib lint --no-clean --verbose --allow-warnings --sources=https://....Skyscanner.Specs.iOS.git,https://github.com/CocoaPods/Specs.git

[snip large amounts of successful build output]

    ** BUILD SUCCEEDED **

     -> Skyscanner.TravellerIdentity.iOS (0.17.2)
        - WARN  | The URL (https://......Skyscanner.TravellerIdentity.iOS) is not reachable.
        - ERROR | [Skyscanner.TravellerIdentity.iOS/SKYSinaWeiboProvider] Returned an unsuccessful exit code.
        - NOTE  | [Skyscanner.TravellerIdentity.iOS/SKYSinaWeiboProvider]  error: failed to remove /var/folders/r5/0x4c1z9x5j5fgt_vcs0l09dn0m3mjh/T/CocoaPods/Lint/build/Release-iphonesimulator/Pods/SKYSinaWeiboProviderResource.bundle/Localizable.strings: “Localizable.strings” couldn’t be removed.
        - NOTE  | [iOS]  error: couldn't remove '/var/folders/r5/0x4c1z9x5j5fgt_vcs0l09dn0m3mjh/T/CocoaPods/Lint/build/Release iphonesimulator/Pods/SKYSinaWeiboProviderResource.bundle/Localizable.strings' after command failed: No such file or directory

    Pods project available at `/var/folders/r5/0x4c1z9x5j5fgt_vcs0l09dn0m3mjh/T/CocoaPods/Lint/Pods/Pods.xcodeproj` for inspection.

    [!] Skyscanner.TravellerIdentity.iOS did not pass validation.

    /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.3/lib/cocoapods/command/lib.rb:166:in `block in run'
    /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.3/lib/cocoapods/command/lib.rb:140:in `each'
    /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.3/lib/cocoapods/command/lib.rb:140:in `run'
    /Library/Ruby/Gems/2.0.0/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
    /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.3/lib/cocoapods/command.rb:46:in `run'
    /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.3/bin/pod:44:in `<top (required)>'
    /usr/bin/pod:23:in `load'
    /usr/bin/pod:23:in `<main>'```
```

The podspec looks like:

```
Pod::Spec.new do |s|
  s.name             = "Skyscanner.TravellerIdentity.iOS"
  s.version          = "0.17.2"
  s.summary          = "TravellerIdentity iOS library."
  s.description      = <<-DESC
                       The TravellerIdentity library...
                       DESC
  s.homepage         = "...."
  s.license          = 'MIT'
  s.author           = { "Matthew Holgate" => "...@..." }
  s.source           = { :git => ".....", :tag => s.version.to_s }

  s.platform     = :ios, '7.0'
  s.requires_arc = true

  s.subspec 'SKYAuthentication' do |sub|
    sub.source_files = 'Pod/Classes/SKYAuthentication/**/*.{h,m}'
    sub.dependency 'Skyscanner.Foundation.iOS'
  end

  s.subspec 'SKYFacebookProvider' do |sub|
    sub.source_files = 'Pod/Classes/SKYFacebookProvider/**/*.{h,m}'
    sub.dependency 'Facebook-iOS-SDK', '~> 3.0'
    sub.dependency 'Skyscanner.TravellerIdentity.iOS/SKYAuthentication'
  end

  s.subspec 'SKYOrchestration' do |sub|
    sub.source_files = 'Pod/Classes/SKYOrchestration/**/*.{h,m}'
    sub.dependency 'Skyscanner.Foundation.iOS'
    sub.dependency 'Skyscanner.TravellerIdentity.iOS/SKYAuthentication'
 end

  s.subspec 'SKYPushNotification' do |sub|
    sub.source_files = 'Pod/Classes/SKYPushNotification/**/*.{h,m}'
    sub.dependency 'Skyscanner.TravellerIdentity.iOS/SKYAuthentication'
  end

  s.subspec 'SKYSinaWeiboProvider' do |sub|
    sub.source_files = 'Pod/Classes/SKYSinaWeiboProvider/**/*.{h,m}'
    sub.dependency 'Skyscanner.TravellerIdentity.iOS/SKYAuthentication'
    sub.dependency 'Reachability'
    sub.dependency 'Weibo', '~> 2.0'
    sub.resource_bundles = {
        'SKYSinaWeiboProviderResource' => ['Pod/Classes/SKYSinaWeiboProvider/Resources/**/*']
    }

  end

  s.subspec 'SKYSocial' do |sub|
    sub.source_files = 'Pod/Classes/SKYSocial/**/*.{h,m}'
    sub.dependency 'Skyscanner.TravellerIdentity.iOS/SKYAuthentication'
    sub.dependency 'Skyscanner.TravellerIdentity.iOS/SKYOrchestration'
    sub.dependency 'Skyscanner.TravellerIdentity.iOS/SKYPushNotification'
  end
 
  # s.public_header_files = 'Pod/Classes/**/*.h'
  # s.frameworks = 'UIKit', 'MapKit'

end
```

I wondered at first if this was because the resource bundle had been added to a sub-spec, but moving it into the main spec didn't help either.

Do you have any ideas what I'm doing wrong here, or if this is a bug in CocoaPods? Please let me know if you need any more information. Many thanks in advance!

**Comment by ajmccall** [comment]
I can confirm that this is present in 0.36.x. Iteratively downgraded Cocoapods until 0.35 at which point podsepc validation started working again.

**Comment by neonichu** [comment]
Could you try linting with `--use-libraries`?

**Comment by mjholgate** [comment]
I get the same error with --use-libraries.

When I tried earlier today, I think --use-libraries fixed the issue, but I think at that point I hadn't migrated my podspec from using plain resource files to using resource bundles instead.

**Comment by mjholgate** [comment]
In the latest release (0.37.0.rc.2), I now get:

[!] The 'Pods' target has transitive dependencies that include static binaries: (/private/var/folders/r5/0x4c1z9x5j5fgt_vcs0l09dn0m3mjh/T/CocoaPods/Lint/Pods/Weibo/libWeiboSDK/libWeiboSDK.a)

And adding --use-libraries fixes the problem.

I wonder if this means the bug has been fixed?

**Comment by neonichu** [comment]
Seems like it.

The transitive dependency error is deliberate, see #2926 for discussion.

**Comment by mjholgate** [comment]
Thanks @neonichu

**Comment by champo** [comment]
I'm getting this issue randomly on 0.37.2 when running on travis. I can't seem to reproduce this locally, so I might open a bug report on travis too. Since these are private repos I've redacted any sensitive names, but the essence is the same.

Output:
```
$ pod lib lint <...>Questions.podspec --allow-warnings --use-libraries --sources='git@github.com:<...>/mobile-ios_specs.git,https://github.com/CocoaPods/Specs'



 -> <...>Questions
   -> <...>Questions (0.1.0)

    - WARN  | Git SSH URLs will NOT work for people behind firewalls configured to only allow HTTP, therefore HTTPS is preferred.

    - ERROR | [iOS] Returned an unsuccessful exit code. You can use `--verbose` for more information.

    - WARN  | [iOS]  libwebp/src/utils/bit_writer.c:262:11: warning: code will never be executed [-Wunreachable-code]

    - NOTE  | [iOS]  libwebp/src/utils/bit_writer.c:261:29: note: silence by adding parentheses to mark code as explicitly dead

    - NOTE  | [iOS]  error: failed to remove /var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/CocoaPods/Lint/build/Release-iphonesimulator/<...>QLocalization.bundle/<...>QLocalizable.strings: <...>QLocalizable.strings couldn't be removed.



[!] <...>Questions did not pass validation.

You can use the `--no-clean` option to inspect any issue.
```

Podspec:
```
Pod::Spec.new do |s|
  s.name         = "<...>Questions"
  s.version      = "0.1.0"
  s.summary      = "... Questions & Answers module for iOS."
  s.homepage     = "http://www.....com.ar"
  s.license      = "none"
  
  s.author       = { "mobile @ <...>" => "mobile@<...>com" }
  s.source       = { :git => "git@github:<...>/mobile-ios_questions.git", :tag => s.version.to_s }

  s.platform     = :ios, '7.0'
  s.requires_arc = true

  s.prefix_header_contents = <<-PCH
#define UNUSED(x) ((void) (x))

#define OCLINT_UNUSED __attribute__((annotate("oclint:suppress[unused method parameter]")))
PCH


  s.source_files = "LibraryComponents/Classes/**/*.{h,m}"
  s.resources    = "LibraryComponents/Classes/**/*.xib", "LibraryComponents/Resources/Media.xcassets"
  s.resource_bundle = { '<...>QLocalization' => 'LibraryComponents/Resources/*/*.lproj/*' }

  s.dependency 'PureLayout', '~> 2.0.5'
  s.dependency '<...>SDK'
end
```

**Comment by segiddins** [comment]
@champo the issue there is that actually attempting to compile your pod is failing

**Comment by champo** [comment]
@segiddins the next step in travis is running unit tests on a simulator, and that always passes without issue. This is failling randomly (1 in 2 builds fail, rerunning a failed build usually passes). I'm gonna add a `--verbose` to the build to see if I can't get anything else, but the strange behaviour is tied to pod lib lint.
