### ISSUE TITLE
Pod::StandardError - Unsupported class for YAML conversion Float

### ISSUE THREAD

**Issue by jpaas** [CocoaPods/CocoaPods#3431]
### Command

```
/Users/jpaas/.rvm/gems/ruby-2.2.0/bin/pod install
```

### Report

* What did you do?

I upgraded cocoapods to 0.36.4 and tried a pod install on a project for the first time in a couple of months. I need to upgrade one of the pods.

* What did you expect to happen?

pods would install

* What happened instead?

Error below

### Stack

```
   CocoaPods : 0.36.4
        Ruby : ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]
    RubyGems : 2.4.5
        Host : Mac OS X 10.10.3 (14D131)
       Xcode : 6.3 (6D570)
         Git : git version 2.3.2 (Apple Git-55)
Ruby lib dir : /Users/jpaas/.rvm/rubies/ruby-2.2.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ e8cbe6095e1c3bec768a32b0d192adc4b2c8ef52
```

### Plugins

```
cocoapods-plugins : 0.4.1
cocoapods-trunk   : 0.6.0
cocoapods-try     : 0.4.3
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
link_with 'selfpay (development)', 'selfpay (staging)', 'selfpay (production)' 

pod 'AFNetworking', '2.3.1'
pod 'AFNetworkActivityLogger', '2.0.3'
pod 'APPinViewController', '1.0.2'
pod 'EAIntroView', '2.6.4'
pod 'iVersion', '1.11.4'

# This should come from libselfpay, but has to wait until cocoapods updated
pod 'KNSemiModalViewController', git: 'https://github.com/kentnguyen/KNSemiModalViewController.git', tag: '0.4'

pod 'MRProgress', git: 'https://github.com/mrackwitz/MRProgress.git'
pod 'libselfpay-ios', path: '../libselfpay-ios'
```

### Error

```
Pod::StandardError - Unsupported class for YAML conversion Float
/Users/jpaas/.rvm/gems/ruby-2.2.0/gems/cocoapods-core-0.36.4/lib/cocoapods-core/yaml_helper.rb:104:in `process_according_to_class'
/Users/jpaas/.rvm/gems/ruby-2.2.0/gems/cocoapods-core-0.36.4/lib/cocoapods-core/yaml_helper.rb:144:in `block in process_hash'
/Users/jpaas/.rvm/gems/ruby-2.2.0/gems/cocoapods-core-0.36.4/lib/cocoapods-core/yaml_helper.rb:142:in `each'
/Users/jpaas/.rvm/gems/ruby-2.2.0/gems/cocoapods-core-0.36.4/lib/cocoapods-core/yaml_helper.rb:142:in `process_hash'
/Users/jpaas/.rvm/gems/ruby-2.2.0/gems/cocoapods-core-0.36.4/lib/cocoapods-core/yaml_helper.rb:102:in `process_according_to_class'
/Users/jpaas/.rvm/gems/ruby-2.2.0/gems/cocoapods-core-0.36.4/lib/cocoapods-core/yaml_helper.rb:144:in `block in process_hash'
/Users/jpaas/.rvm/gems/ruby-2.2.0/gems/cocoapods-core-0.36.4/lib/cocoapods-core/yaml_helper.rb:142:in `each'
/Users/jpaas/.rvm/gems/ruby-2.2.0/gems/cocoapods-core-0.36.4/lib/cocoapods-core/yaml_helper.rb:142:in `process_hash'
/Users/jpaas/.rvm/gems/ruby-2.2.0/gems/cocoapods-core-0.36.4/lib/cocoapods-core/yaml_helper.rb:102:in `process_according_to_class'
/Users/jpaas/.rvm/gems/ruby-2.2.0/gems/cocoapods-core-0.36.4/lib/cocoapods-core/yaml_helper.rb:144:in `block in process_hash'
/Users/jpaas/.rvm/gems/ruby-2.2.0/gems/cocoapods-core-0.36.4/lib/cocoapods-core/yaml_helper.rb:142:in `each'
/Users/jpaas/.rvm/gems/ruby-2.2.0/gems/cocoapods-core-0.36.4/lib/cocoapods-core/yaml_helper.rb:142:in `process_hash'
/Users/jpaas/.rvm/gems/ruby-2.2.0/gems/cocoapods-core-0.36.4/lib/cocoapods-core/yaml_helper.rb:41:in `convert_hash'
/Users/jpaas/.rvm/gems/ruby-2.2.0/gems/cocoapods-core-0.36.4/lib/cocoapods-core/lockfile.rb:338:in `to_yaml'
/Users/jpaas/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.4/lib/cocoapods/installer/migrator.rb:66:in `block (2 levels) in migrate_to_0_36'
/Users/jpaas/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.4/lib/cocoapods/installer/migrator.rb:66:in `open'
/Users/jpaas/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.4/lib/cocoapods/installer/migrator.rb:66:in `block in migrate_to_0_36'
/Users/jpaas/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.4/lib/cocoapods/user_interface.rb:110:in `message'
/Users/jpaas/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.4/lib/cocoapods/installer/migrator.rb:53:in `migrate_to_0_36'
/Users/jpaas/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.4/lib/cocoapods/installer/migrator.rb:16:in `migrate'
/Users/jpaas/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.4/lib/cocoapods/installer.rb:105:in `block in prepare'
/Users/jpaas/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.4/lib/cocoapods/user_interface.rb:110:in `message'
/Users/jpaas/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.4/lib/cocoapods/installer.rb:102:in `prepare'
/Users/jpaas/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.4/lib/cocoapods/installer.rb:89:in `install!'
/Users/jpaas/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.4/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/jpaas/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.4/lib/cocoapods/command/project.rb:101:in `run'
/Users/jpaas/.rvm/gems/ruby-2.2.0/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Users/jpaas/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.4/lib/cocoapods/command.rb:46:in `run'
/Users/jpaas/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.4/bin/pod:44:in `<top (required)>'
/Users/jpaas/.rvm/gems/ruby-2.2.0/bin/pod:23:in `load'
/Users/jpaas/.rvm/gems/ruby-2.2.0/bin/pod:23:in `<main>'
/Users/jpaas/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
/Users/jpaas/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by cyvoit** [comment]
I also have this issue.I update pod to `0.37.0` but `pod --version` shows `0.35.0` .Then I find a Gemfile in the Podfile folder:
```
source 'http://rubygems.org'   
gem 'cocoapods' , '035.0'
```  

And i have two cocoapods version. So I delete the Gemfile and `gem uninstall cocoapods`,`gem install cocoapods`,everything is OK.
