### ISSUE TITLE
Downloader should say if it cannot find the correct podspec with git:

### ISSUE THREAD

**Issue by orta** [CocoaPods/CocoaPods#3433]
I used:
```
  pod "Artsy_Authentication", :git => "git@github.com:artsy/Artsy_Authentication.git"
```

instead of 
```
  pod "Artsy+Authentication", :git => "git@github.com:artsy/Artsy_Authentication.git"
```

Which caused this crash:
```
TypeError - no implicit conversion of nil into String
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/2.1.0/fileutils.rb:1585:in `path'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/2.1.0/fileutils.rb:1585:in `fu_each_src_dest0'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/2.1.0/fileutils.rb:1571:in `fu_each_src_dest'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/2.1.0/fileutils.rb:440:in `cp_r'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-0.37.0.beta.1/lib/cocoapods/downloader.rb:38:in `block in download'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-0.37.0.beta.1/lib/cocoapods/user_interface.rb:110:in `message'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-0.37.0.beta.1/lib/cocoapods/downloader.rb:36:in `download'
```

Which I believe is because it could't find the Podspec with the right name. Adding a check somewhere in CocoaPods to exit out nicely would improve the experience. This is probably a nice first step for someone looking to contribute.

**Comment by segiddins** [comment]
AbstractExternalSource already has code to handle the podspec in the response being nil, but obviously I'm calling a method on it before then.

**Comment by orta** [comment]
Thanks Sir
