### ISSUE TITLE
The spec did not pass validation, but no errors

### ISSUE THREAD

**Issue by huhuanming** [CocoaPods/CocoaPods#3458]
** BUILD SUCCEEDED **

 -> QiniuUpload (1.0.1)
    - WARN  | [iOS]  QiniuUpload/Classes/QiniuFile.m:45:34: warning: implicit conversion loses integer precision: 'long long' to 'unsigned long' [-Wshorten-64-to-32]
    - WARN  | [iOS]  QiniuUpload/Classes/QiniuFile.m:46:81: warning: implicit conversion loses integer precision: 'long long' to 'NSUInteger' (aka 'unsigned int') [-Wshorten-64-to-32]
    - WARN  | [iOS]  QiniuUpload/Classes/QiniuToken.m:104:19: warning: implicit conversion loses integer precision: 'unsigned long' to 'CC_LONG' (aka 'unsigned int') [-Wshorten-64-to-32]

Analyzed 1 podspec.

[!] The spec did not pass validation.

/Users/hu/.rvm/gems/ruby-2.1.1/gems/cocoapods-0.36.4/lib/cocoapods/command/spec/lint.rb:67:in `run'
/Users/hu/.rvm/gems/ruby-2.1.1/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Users/hu/.rvm/gems/ruby-2.1.1/gems/cocoapods-0.36.4/lib/cocoapods/command.rb:46:in `run'
/Users/hu/.rvm/gems/ruby-2.1.1/gems/cocoapods-0.36.4/bin/pod:44:in `<top (required)>'
/Users/hu/.rvm/gems/ruby-2.1.1/bin/pod:23:in `load'
/Users/hu/.rvm/gems/ruby-2.1.1/bin/pod:23:in `<main>'
/Users/hu/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
/Users/hu/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'

My podspec like this:

Pod::Spec.new do |s|
  s.name         = "QiniuUpload"
  s.version      = "1.0.1"
  s.summary      = "支持批量上传的七牛上传sdk，音频、视频、图片都是支持滴"
  s.description  = <<-DESC
                   A longer description of QiniuUpload in Markdown format.

                   * Think: Why did you write this? What is the focus? What does it do?
                   * CocoaPods will be using this to generate tags, and improve search results.
                   * Try to keep it short, snappy and to the point.
                   * Finally, don't worry about the indent, CocoaPods strips it!
                   DESC
  s.homepage     = "https://github.com/huhuanming/qiniu_upload"
  s.license      = "MIT"
  s.platform     = :ios, "6.0"
  s.source       = { :git => "https://github.com/huhuanming/qiniu_upload.git", :tag => "1.0.1" }
  s.source_files  = "Classes", "Classes/**/*.{h,m}"
  s.exclude_files = "Classes/Exclude"
  s.frameworks = 'Foundation', 'UIKit'
  s.requires_arc = true
  s.dependency "AFNetworking", ">= 2.0"
end

please help me , I cannot push my spec but I don't know why

**Comment by huhuanming** [comment]
=  皿 = --allow-warnings.. 
I m too naive... LOL!
