### ISSUE TITLE
Linting fails on 0.36.4, not 0.35

### ISSUE THREAD

**Issue by jshier** [CocoaPods/CocoaPods#3475]
I'm currently seeing linting failures for a private pod using 0.36.4. The same spec lints fine on 0.35.

Here's the podspec:
```
Pod::Spec.new do |s|
  s.name         = "Private"
  s.version      = "0.0.4"
  s.summary      = "Library for Private."
  s.homepage     = "https://www.private.com"
  s.license      = { :type => 'Proprietary', :file => 'LICENSE.txt' }
  s.authors      = { "Private" => "private@private.com" }
  s.source       = { :git => "ssh://git@private/private.git", :tag => s.version.to_s}
  s.platform     = :ios, '7.0'
  s.source_files = 'Private', 'Private/Private/*.{h,m}'
  s.public_header_files = 'Private/Private/*.h'
  s.framework  = 'Foundation'
  s.requires_arc = true
  
  s.dependency 'PrivatePod', '0.1.78'
  s.dependency 'AFNetworking', '~> 2.5.2'
  s.dependency 'OtherPrivatePod', '0.0.239'
  s.dependency 'Mantle', '~> 1.5.4'
  s.dependency 'libPhoneNumber-iOS', '~> 0.8.1'
end
```

Using the command:
```
pod spec lint --verbose --sources="ssh://git@private/private.git,https://github.com/CocoaPods/Specs.git" --use-libraries Private.podspec
```

Results in:
```
-> OnStarServices (0.0.437)
    - WARN  |  OtherPrivatePod/OtherPrivatePod/OtherPrivatePod/NSData+Base64.m:17:32: warning: 'initWithBase64Encoding:' is deprecated: first deprecated in iOS 7.0 [-Wdeprecated-declarations]
    - NOTE  |  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSData.h:152:1: note: 'initWithBase64Encoding:' has been explicitly marked deprecated here
    - WARN  |  OtherPrivatePod/OtherPrivatePod/OtherPrivatePod/NSData+Base64.m:32:18: warning: 'base64Encoding' is deprecated: first deprecated in iOS 7.0 [-Wdeprecated-declarations]
    - NOTE  |  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSData.h:153:1: note: 'base64Encoding' has been explicitly marked deprecated here
    - WARN  |  RNCryptor/RNCryptor/RNOpenSSLCryptor.m:80:9: warning: incompatible pointer types assigning to 'NSMutableData *' from 'NSData *' [-Wincompatible-pointer-types]
    - NOTE  |  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.3.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSData.h:103:1: note: class method 'dataWithBytes:length:' is assumed to return an instance of its receiver type ('NSData *')
    - WARN  |  PrivatePod/PrivatePod/PrivatePod/PrivatePodThing.m:197:18: warning: unused variable 'validResponse' [-Wunused-variable]

Analyzed 1 podspec.

[!] The spec did not pass validation.

/Users/jshier/.rvm/gems/ruby-2.1.4@remotelink/gems/cocoapods-0.36.4/lib/cocoapods/command/spec/lint.rb:67:in `run'
/Users/jshier/.rvm/gems/ruby-2.1.4@remotelink/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Users/jshier/.rvm/gems/ruby-2.1.4@remotelink/gems/cocoapods-0.36.4/lib/cocoapods/command.rb:46:in `run'
/Users/jshier/.rvm/gems/ruby-2.1.4@remotelink/gems/cocoapods-0.36.4/bin/pod:44:in `<top (required)>'
/Users/jshier/.rvm/gems/ruby-2.1.4@remotelink/bin/pod:23:in `load'
/Users/jshier/.rvm/gems/ruby-2.1.4@remotelink/bin/pod:23:in `<main>'
```

The project itself builds and tests fine, so I'm sort of at a loss here.

**Comment by neonichu** [comment]
The linting fails because of the "WARN" messages you are seeing. Compiler warnings are no longer just notices due to an intentional change in #2978. You can pass `--allow-warnings` to ignore the warnings.

**Comment by jshier** [comment]
Thanks, figured it was a change I didn't remember.
