### ISSUE TITLE
Nice DSL Error when Podfile Dependency is malformed

### ISSUE THREAD

**Issue by Summerjw** [CocoaPods/CocoaPods#3478]
――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/bin/pod install
```

### Report

* What did you do?
From the  Terminal:
$ sudo gem install cocoapods
$ pod setup
$ cd /path/to/CoffeeKit
$ touch Podfile
$ [edit] Podfile (using your preferred editor; vim, nano, etc)
platform :ios, '5.0'
pod 'RestKit', '~> 0.20.0'
^X
$ pod install
* What did you expect to happen?
Install RESTkit
* What happened instead?
The following error occurred

### Stack

```
   CocoaPods : 0.36.4
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin13]
    RubyGems : 2.0.14
        Host : Mac OS X 10.9.5 (13F1077)
       Xcode : 6.2 (6C131e)
         Git : git version 1.9.5 (Apple Git-50.3)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ b951ebdfe2abac8fedfd759cc326e3c4db74308d
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-trunk   : 0.6.0
cocoapods-try     : 0.4.3
```

### Podfile

```ruby
platform :ios,'5.0'
pod 'RestKit', '-> 0.20.0'
```

### Error

```
ArgumentError - Illformed requirement `"-> 0.20.0"`
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.36.4/lib/cocoapods-core/requirement.rb:61:in `parse'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.36.4/lib/cocoapods-core/vendor/requirement.rb:132:in `block in initialize'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.36.4/lib/cocoapods-core/vendor/requirement.rb:132:in `map!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.36.4/lib/cocoapods-core/vendor/requirement.rb:132:in `initialize'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.36.4/lib/cocoapods-core/requirement.rb:32:in `new'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.36.4/lib/cocoapods-core/requirement.rb:32:in `create'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.36.4/lib/cocoapods-core/dependency.rb:92:in `initialize'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.36.4/lib/cocoapods-core/podfile/target_definition.rb:647:in `new'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.36.4/lib/cocoapods-core/podfile/target_definition.rb:647:in `block in pod_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.36.4/lib/cocoapods-core/podfile/target_definition.rb:643:in `map'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.36.4/lib/cocoapods-core/podfile/target_definition.rb:643:in `pod_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.36.4/lib/cocoapods-core/podfile/target_definition.rb:87:in `non_inherited_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.36.4/lib/cocoapods-core/podfile/target_definition.rb:77:in `dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.36.4/lib/cocoapods-core/podfile.rb:89:in `map'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.36.4/lib/cocoapods-core/podfile.rb:89:in `dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.4/lib/cocoapods/installer/analyzer.rb:161:in `generate_podfile_state'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.4/lib/cocoapods/installer/analyzer.rb:53:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.4/lib/cocoapods/installer.rb:189:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.4/lib/cocoapods/installer.rb:111:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.4/lib/cocoapods/user_interface.rb:49:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.4/lib/cocoapods/installer.rb:110:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.4/lib/cocoapods/installer.rb:90:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.4/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.4/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.4/lib/cocoapods/command.rb:46:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.4/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

**Comment by kylef** [comment]
As this error message has pointed out, you've entered an illformed requirement for RestKit `-> 0.20.0`.

Did you perhaps mean `~> 0.20.0` or `> 0.20.0`?

**Comment by Summerjw** [comment]
Wow, what an easy fix.  Pretty silly of me to not look at the error message more thoroughly...Thanks

**Comment by segiddins** [comment]
This should raise a river DSL error

**Comment by Summerjw** [comment]
How so? I'm actually somewhat new in this area an explanation would help a lot.

**Comment by segiddins** [comment]
Oh don't worry, I'll handle it :) 

-Samuel E. Giddins

On Apr 30, 2015, at 8:55 AM, Summerjw <notifications@github.com> wrote:

How so? I'm actually somewhat new in this area an explanation would help a lot.

**Comment by segiddins** [comment]
Hmmm, I don't know how to fix this since the Podfile DSL lazily creates Dependency objects...

**Comment by kylef** [comment]
If there isn't a good reason to keep these lazily loaded, it might make sense to explicitly create them earlier.

**Comment by orta** [comment]
This might not be worth doing if it's hard.
