### ISSUE TITLE
pod setup breaks in 0.37.0

### ISSUE THREAD

**Issue by chakrit** [CocoaPods/CocoaPods#3490]
```
$ uname -a
Darwin CX22 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64
$ pod --version
0.37.0
$ gem --version
2.4.5
$ ruby --version
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]
```

The command I used is `cd ~ && rm -rf .cocoapods && pod setup --verbose`

```
$ cd ~ && rm -rf .cocoapods && pod setup --verbose

Setting up CocoaPods master repo

Creating shallow clone of spec repo `master` from `https://github.com/CocoaPods/Specs.git` (branch `master`)
  $ /usr/local/bin/git clone https://github.com/CocoaPods/Specs.git master --depth\=1
  Cloning into 'master'...
Checking out files: 100% (36965/36965), done.
  $ /usr/local/bin/git checkout master
  Already on 'master'
  Your branch is up-to-date with 'origin/master'.
[!] There was an error reading '/Users/chakrit/.cocoapods/repos/master/CocoaPods-version.yml'.
Please consult http://blog.cocoapods.org/Repairing-Our-Broken-Specs-Repository/ for more information.

/Users/chakrit/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoapods-0.37.0/lib/cocoapods/sources_manager.rb:333:in `rescue in version_information'
/Users/chakrit/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoapods-0.37.0/lib/cocoapods/sources_manager.rb:330:in `version_information'
/Users/chakrit/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoapods-0.37.0/lib/cocoapods/sources_manager.rb:251:in `check_version_information'
/Users/chakrit/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoapods-0.37.0/lib/cocoapods/command/repo/add.rb:47:in `block in run'
/Users/chakrit/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoapods-0.37.0/lib/cocoapods/user_interface.rb:49:in `section'
/Users/chakrit/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoapods-0.37.0/lib/cocoapods/command/repo/add.rb:39:in `run'
/Users/chakrit/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoapods-0.37.0/lib/cocoapods/command/setup.rb:84:in `add_master_repo'
/Users/chakrit/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoapods-0.37.0/lib/cocoapods/command/setup.rb:40:in `block in run'
/Users/chakrit/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoapods-0.37.0/lib/cocoapods/user_interface.rb:49:in `section'
/Users/chakrit/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoapods-0.37.0/lib/cocoapods/command/setup.rb:32:in `run'
/Users/chakrit/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Users/chakrit/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoapods-0.37.0/lib/cocoapods/command.rb:46:in `run'
/Users/chakrit/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoapods-0.37.0/bin/pod:44:in `<top (required)>'
/Users/chakrit/.rbenv/versions/2.2.0/bin/pod:23:in `load'
/Users/chakrit/.rbenv/versions/2.2.0/bin/pod:23:in `<main>'
```

**Comment by segiddins** [comment]
What's the output of `cat /Users/chakrit/.cocoapods/repos/master/CocoaPods-version.yml`?

**Comment by chakrit** [comment]
```
---
min: 0.32.1
last: 0.37.0
```

@segiddins  ^

**Comment by chakrit** [comment]
Downgraded to `0.36.4` and, unfortunately, this still happens. Something with the specs repo?!

Logs here: https://gist.github.com/chakrit/eee60bdad5722275d602 (same error)

**Comment by chakrit** [comment]
I managed to get `pod setup --verbose` to finish by commenting the following lines in `sources_manager.rb`:

```
326       def version_information(dir)                                                         
327         require 'yaml'                                                                     
328         yaml_file  = dir + 'CocoaPods-version.yml'                                         
329         return {} unless yaml_file.exist?                                                  
330         # begin                                                                            
331         YAMLHelper.load_file(yaml_file)                                                                                                                                                                                            
332         # rescue Informative                                                               
333         #   raise Informative, "There was an error reading '#{yaml_file}'.\n" \            
334         #     'Please consult http://blog.cocoapods.org/' \                                
335         #     'Repairing-Our-Broken-Specs-Repository/ ' \                                  
336         #     'for more information.'                                                      
337         # end                                                                              
338       end                                                                                  
```

This is rather weird.

**Comment by kylef** [comment]
@chakrit That's really odd, removing the `rescue` should just mean a different exception is shown instead of the different exception we re-raise. Can you do some more digging and see if this is still a problem? Getting hold of the underlying exception would be great since it would contain the actual yaml error.

**Comment by chakrit** [comment]
@kylef I'm not a ruby expert but I don't mind digging around a bit more. What should I do?

**Comment by chakrit** [comment]
@kylef I just tried again with 0.37.1 and now I'm consistently getting the YAML parse error now:

```
[!] ERROR: Parsing unable to continue due to parsing error:
contained in the file located at /Users/chakrit/.cocoapods/repos/master/CocoaPods-version.yml
---
min: 0.32.1
last: 0.37.1


/Users/chakrit/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-core-0.37.1/lib/cocoapods-core/yaml_helper.rb:62:in `rescue in load_string'
```

No idea how it succeed previously. But I think this is the root cause of the issue. Somehow the file just failed to load. It looks like valid YAML to me.

**Comment by chakrit** [comment]
Thinking this might be related to #2908

**Comment by chakrit** [comment]
Yep, that was correct. So it was a `psych` gem issue. This fixed it for me:

![2015-05-08 at 5 27 pm](https://cloud.githubusercontent.com/assets/45545/7534724/884ed764-f5a7-11e4-982f-7becabf1d8d5.png)

Sorry didn't dig hard enough into previous issues. There are wayyy too many issues w/ setup.

**Comment by chakrit** [comment]
Maybe put a warning in the README or something? As I'm not a daytime ruby dev this problem is kinda hard me to search/dig around.

**Comment by kylef** [comment]
@chakrit Filed #3539 so we can try and fix this from happening.

If you're not a Ruby dev then you probably don't need to use rbenv, the system ruby should be sufficient and usually means you won't come into these kinds of problems.

**Comment by chakrit** [comment]
thanks : )

unfortunately I still have to work with ruby folks / ruby stuff so I sometimes needed this.

**Comment by wwju** [comment]
I had the same error.
I resolved it, using:

```
rbenv use system
# now it will use *system* ruby version (as mentioned @kylef before) 
# in your application folder.
# But, you can still use *rbenv* for other applications

sudo gem install cocoapods
# yes, sudo is needed, because of *system* ruby version will install all gems in
# system folder, which user does not have permissions.
```

**Comment by srayhunter** [comment]
Ran into the same issue with psych 2.0.13. I have the following installed:
psych (2.0.13, 2.0.8)

Removed 2.0.13 and ran pod setup with no issues. psych 2.0.8 is the system default.

**Comment by espiegel** [comment]
I ran into the same issue and resolve it using:

`gem uninstall psych
pod setup --verbose`

**Comment by alejandrod** [comment]
Same problem here. I fixed it removing psych 2.0.15 (and leaving 2.0.8)

**Comment by va3093** [comment]
Removing psyche worked for me as well. 
```
gem uninstall psych
pod setup --verbose
```

**Comment by davidenglishmusic** [comment]
+1 for uninstalling psych to complete the pod setup

**Comment by corydolphin** [comment]
I hit the same issue on 0.39.0, and resolved it by uninstalling psych.

**Comment by chrismanahan** [comment]
Uninstalling psych worked for me too for v0.39.0

**Comment by gaaamii** [comment]
Me too.
