### ISSUE TITLE
undefined method `plugins' for nil:NilClass

### ISSUE THREAD

**Issue by dkhamsing** [CocoaPods/CocoaPods#3535]
:confused: 

```
pod repo push daniel CloudStorageKit.podspec 

Validating spec
[!] The `CloudStorageKit.podspec` specification does not validate.

undefined method `plugins' for nil:NilClass
```

here's the podspec
```
cat CloudStorageKit.podspec 
Pod::Spec.new do |s|

  s.name         = "CloudStorageKit"

  s.version      = "0.0.6"

  s.summary      = "Cloud storage library for iOS."

  s.description  = "--" 

  s.homepage     = "https://github.com"

  s.license      = "MIT"

  s.authors            = [{ "dkhamsing" => "d@y.com" }, { "j" => "j@y.com" }]
  
  s.social_media_url   = "http://twitter.com/dkhamsing"

  s.platform     = :ios, "8.0"

  s.source       = { :git => "https://github.com/dkhamsing/cloud-storage-wrapper.git", :tag => s.version.to_s }

  s.ios.vendored_frameworks = "CloudStorageKit.framework"

  s.ios.resource = "CloudStorageKit.framework"
  
  s.ios.xcconfig = { 'LD_RUNPATH_SEARCH_PATHS' => '@executable_path/Frameworks' }

end
```

fyi I was able to push 0.0.5 previously.. currently running cocoapods-0.37.1

does this error have to do with cocoapods-plugins ?? recently installed cocoapods-plugins 0.4.2

**Comment by segiddins** [comment]
Can you please share the output of `pod repo push --verbose`?

**Comment by dkhamsing** [comment]
```
pod repo push --verbose CloudStorageKit.podspec 
[!] `CloudStorageKit.podspec` repo not found either in /Users/danielkhamsing/.cocoapods/repos/CloudStorageKit.podspec/Specs or /Users/danielkhamsing/.cocoapods/repos/CloudStorageKit.podspec

/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/command/repo/push.rb:185:in `repo_dir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/command/repo/push.rb:64:in `check_if_master_repo'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/command/repo/push.rb:43:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/command.rb:46:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

**Comment by dkhamsing** [comment]
oh and i meant cocoapods-keys is what i installed recently

**Comment by dkhamsing** [comment]
uninstalling keys solved this.. :cry:

**Comment by orta** [comment]
or updating, think I added some protection against that in the later versions

**Comment by lazerwalker** [comment]
This is still happening for me (and @mergesort, independently), with the latest cocoapods-keys and CP 0.37.1. 

Temporarily uninstalling cocoapods-keys works, but that's a nasty workaround.

**Comment by mergesort** [comment]
Can confirm, still happening for me when trying to run `pod spec lint`.

### Stack

```
   CocoaPods : 0.37.1
        Ruby : ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin13.0]
    RubyGems : 2.2.2
        Host : Mac OS X 10.10.3 (14D136)
       Xcode : 6.3.1 (6D1002)
         Git : git version 2.2.1
Ruby lib dir : /Users/mergesort/.rvm/rubies/ruby-2.1.2/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 0fc1f4f08b96537f0001c243bd2e1d95a23356d0
```

### Plugins

```
cocoapods-keys    : 1.2.0
cocoapods-plugins : 0.4.2
cocoapods-trunk   : 0.6.0
cocoapods-try     : 0.4.4
```

### Error

```
NoMethodError - undefined method `plugins' for nil:NilClass
/Users/mergesort/.rvm/gems/ruby-2.1.2/gems/cocoapods-keys-1.2.0/lib/plugin.rb:77:in `validates_for_keys'
/Users/mergesort/.rvm/gems/ruby-2.1.2/gems/cocoapods-keys-1.2.0/lib/plugin.rb:72:in `install!'
/Users/mergesort/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.37.1/lib/cocoapods/validator.rb:319:in `install_pod'
/Users/mergesort/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.37.1/lib/cocoapods/validator.rb:221:in `block in perform_extensive_analysis'
/Users/mergesort/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.37.1/lib/cocoapods/validator.rb:217:in `each'
/Users/mergesort/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.37.1/lib/cocoapods/validator.rb:217:in `perform_extensive_analysis'
/Users/mergesort/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.37.1/lib/cocoapods/validator.rb:73:in `validate'
/Users/mergesort/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.37.1/lib/cocoapods/command/spec/lint.rb:55:in `block in run'
/Users/mergesort/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.37.1/lib/cocoapods/command/spec/lint.rb:46:in `each'
/Users/mergesort/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.37.1/lib/cocoapods/command/spec/lint.rb:46:in `run'
/Users/mergesort/.rvm/gems/ruby-2.1.2/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Users/mergesort/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.37.1/lib/cocoapods/command.rb:46:in `run'
/Users/mergesort/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.37.1/bin/pod:44:in `<top (required)>'
/Users/mergesort/.rvm/gems/ruby-2.1.2/bin/pod:23:in `load'
/Users/mergesort/.rvm/gems/ruby-2.1.2/bin/pod:23:in `<main>'
/Users/mergesort/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
/Users/mergesort/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by nebiros** [comment]
Same issue, https://github.com/CocoaPods/CocoaPods/issues/3619#issuecomment-108117269, `cocoapods-keys: 1.2.1`.

**Comment by kylef** [comment]
This was fixed in https://github.com/orta/cocoapods-keys/commit/5b16687a30191ebef8d0db54786159d6fc3cbc19 @orta maybe you can release an update to CocoaPods-keys?

**Comment by mergesort** [comment]
@orta Would love a new release with the fix when you get a chance.
