### ISSUE TITLE
Ruby segfault in gets in Executable

### ISSUE THREAD

**Issue by segiddins** [CocoaPods/CocoaPods#3556]
```
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]

-- Ruby level backtrace information ----------------------------------------
~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-0.37.1/lib/cocoapods/executable.rb:83:in `block (2 levels) in popen3'
~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-0.37.1/lib/cocoapods/executable.rb:83:in `gets'
```

**Comment by segiddins** [comment]
Likely root cause is https://bugs.ruby-lang.org/issues/10804

**Comment by segiddins** [comment]
Filed at https://bugs.ruby-lang.org/issues/11147

**Comment by soffes** [comment]
Everything works fine if you downgrade to Ruby 2.1.3.
