### ISSUE TITLE
Pod::StandardError - Unsupported class for YAML conversion Float

### ISSUE THREAD

**Issue by stefanidi** [CocoaPods/CocoaPods#3558]
### Command

```
/usr/bin/pod update
```

### Report

* What did you do?
Just installed pods using "sudo gem install cocoapods" then "pod setup". After I went to directory of an existing project that already had some pods that I need to update. Ran "pod update" in the root of the project (where the Pods folder is) and got this error. I tried this one two machines with the same result.

* What did you expect to happen?
Pods in the existing project get updated

* What happened instead?
Got this error

### Stack

```
   CocoaPods : 0.37.1
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.0.14
        Host : Mac OS X 10.10.3 (14D136)
       Xcode : 6.3 (6D570)
         Git : git version 1.8.4
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ c2c553cb076c6a96c3cdd9091e3dee0e0dd12679
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-trunk   : 0.6.0
cocoapods-try     : 0.4.4
```

### Podfile

```ruby
# Default workspace
workspace 'Sputnik.xcworkspace'

# Default project
xcodeproj 'Sputnik/Sputnik.xcodeproj'

# Applications
apps_targets = [:'Vega Alpha', :'Vega Beta', :'Vega Live']

apps_targets.each do |app_target|
  target app_target do
    pod 'AFNetworking'
    pod 'Facebook-iOS-SDK'
    pod 'HockeySDK'
    pod 'JASidePanels', '~> 1'
    pod 'KNSemiModalViewController', :git =>'https://github.com/kentnguyen/KNSemiModalViewController.git', :tag => '0.4'
    pod 'MagicalRecord'
    pod 'LDProgressView'
    # Used in SPHTMLParser
    # Remove, since iOS 6 UILabel can manage attributed text, and we are not support iOS 5 any more
    pod 'OHAttributedLabel', '~> 3'
    pod 'SDWebImage', '~> 3'
    pod 'SVProgressHUD'
    pod 'SVPullToRefresh'
    pod 'SVSegmentedControl'
  end
end

app_tests_targets = [:'Vega Alpha Tests', :'Vega Beta Tests', :'Vega Live Tests']
app_tests_targets.each do |app_tests_target|
  target app_tests_target do
    pod 'OCMock'
  end
end

# Tests
tests_targets = [:'Tests']

tests_targets.each do |test_target|
  target test_target do
    pod 'AFNetworking'
    pod 'Facebook-iOS-SDK'
    pod 'GHUnitIOS'
    pod 'JASidePanels', '~> 1'
    pod 'KNSemiModalViewController', :git =>'https://github.com/kentnguyen/KNSemiModalViewController.git', :tag => '0.4'
    pod 'MagicalRecord'
    pod 'LDProgressView'
    pod 'OHAttributedLabel', '~> 3'
    pod 'OHHTTPStubs', '~> 1' # Update and refactor tests
    pod 'SDWebImage', '~> 3'
    pod 'SVProgressHUD'
  end
end

post_install do |installer|
  installer.project.targets.each do |target|
    target.build_configurations.each do |config|
      # Disable all warnings on Pod project
      config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
      # Disable MagicalRecord logging
      if target.to_s.end_with?('-MagicalRecord')
        s = config.build_settings['GCC_PREPROCESSOR_DEFINITIONS']
        s = [ '$(inherited)' ] if s == nil;
        s.push('MR_ENABLE_ACTIVE_RECORD_LOGGING=0');
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = s
      end
    end
  end
end
```

### Error

```
Pod::StandardError - Unsupported class for YAML conversion Float
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.37.1/lib/cocoapods-core/yaml_helper.rb:104:in `process_according_to_class'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.37.1/lib/cocoapods-core/yaml_helper.rb:144:in `block in process_hash'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.37.1/lib/cocoapods-core/yaml_helper.rb:142:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.37.1/lib/cocoapods-core/yaml_helper.rb:142:in `process_hash'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.37.1/lib/cocoapods-core/yaml_helper.rb:102:in `process_according_to_class'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.37.1/lib/cocoapods-core/yaml_helper.rb:144:in `block in process_hash'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.37.1/lib/cocoapods-core/yaml_helper.rb:142:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.37.1/lib/cocoapods-core/yaml_helper.rb:142:in `process_hash'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.37.1/lib/cocoapods-core/yaml_helper.rb:102:in `process_according_to_class'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.37.1/lib/cocoapods-core/yaml_helper.rb:144:in `block in process_hash'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.37.1/lib/cocoapods-core/yaml_helper.rb:142:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.37.1/lib/cocoapods-core/yaml_helper.rb:142:in `process_hash'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.37.1/lib/cocoapods-core/yaml_helper.rb:41:in `convert_hash'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.37.1/lib/cocoapods-core/lockfile.rb:347:in `to_yaml'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.37.1/lib/cocoapods-core/lockfile.rb:300:in `block in write_to_disk'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.37.1/lib/cocoapods-core/lockfile.rb:300:in `open'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.37.1/lib/cocoapods-core/lockfile.rb:300:in `open'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.37.1/lib/cocoapods-core/lockfile.rb:300:in `write_to_disk'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer/migrator.rb:66:in `block in migrate_to_0_36'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/user_interface.rb:110:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer/migrator.rb:53:in `migrate_to_0_36'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer/migrator.rb:16:in `migrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer.rb:106:in `block in prepare'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/user_interface.rb:110:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer.rb:103:in `prepare'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer.rb:90:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/command/project.rb:155:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/command.rb:46:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

**Comment by segiddins** [comment]
This is an issue reading in the lockfile, 0.36+ won't generate broken lockfile any more.

**Comment by stefanidi** [comment]
Any Way I can fix this? Sorry I am pretty new to this.
Appreciate your help

**Comment by segiddins** [comment]
If you share your POdfile.lock, I can do a one-time fix of it

-Samuel E. Giddins

On May 13, 2015, at 4:26 PM, stefanidi <notifications@github.com> wrote:

Any Way I can fix this? Sorry I am pretty new to this.
Appreciate your help

**Comment by stefanidi** [comment]
Thank you very much, really appreciate it. This is the Podfile.lock:


PODS:
  - AFNetworking (2.3.1):
    - AFNetworking/NSURLConnection
    - AFNetworking/NSURLSession
    - AFNetworking/Reachability
    - AFNetworking/Security
    - AFNetworking/Serialization
    - AFNetworking/UIKit
  - AFNetworking/NSURLConnection (2.3.1):
    - AFNetworking/Reachability
    - AFNetworking/Security
    - AFNetworking/Serialization
  - AFNetworking/NSURLSession (2.3.1):
    - AFNetworking/Reachability
    - AFNetworking/Security
    - AFNetworking/Serialization
  - AFNetworking/Reachability (2.3.1)
  - AFNetworking/Security (2.3.1)
  - AFNetworking/Serialization (2.3.1)
  - AFNetworking/UIKit (2.3.1):
    - AFNetworking/NSURLConnection
    - AFNetworking/NSURLSession
  - Bolts (1.1.1)
  - Facebook-iOS-SDK (3.16.2):
    - Bolts
  - GHUnitIOS (0.5.8)
  - HockeySDK (3.5.6)
  - JASidePanels (1.3.2)
  - KNSemiModalViewController (0.3.1)
  - LDProgressView (1.2.1)
  - MagicalRecord (2.2):
    - MagicalRecord/Core
  - MagicalRecord/Core (2.2)
  - OCMock (3.0.2)
  - OHAttributedLabel (3.5.4)
  - OHHTTPStubs (1.2.2)
  - SDWebImage (3.7.1):
    - SDWebImage/Core
  - SDWebImage/Core (3.7.1)
  - SVProgressHUD (1.0)
  - SVPullToRefresh (0.4.1)
  - SVSegmentedControl (0.2)

DEPENDENCIES:
  - AFNetworking
  - Facebook-iOS-SDK
  - GHUnitIOS
  - HockeySDK
  - JASidePanels (~> 1)
  - KNSemiModalViewController (from `https://github.com/kentnguyen/KNSemiModalViewController.git`, tag `0.4`)
  - LDProgressView
  - MagicalRecord
  - OCMock
  - OHAttributedLabel (~> 3)
  - OHHTTPStubs (~> 1)
  - SDWebImage (~> 3)
  - SVProgressHUD
  - SVPullToRefresh
  - SVSegmentedControl

EXTERNAL SOURCES:
  KNSemiModalViewController:
    :git: https://github.com/kentnguyen/KNSemiModalViewController.git
    :tag: 0.4

SPEC CHECKSUMS:
  AFNetworking: 6d7b76aa5d04c8c37daad3eef4b7e3f2a7620da3
  Bolts: 0ca796081c3e7c139bd86d6903c27f1b83036a5d
  Facebook-iOS-SDK: 34eef640c2cc4c8618ba0f574ad2b290e07f1b4e
  GHUnitIOS: 0fe5a01896673a7768ee76158fbae02ad8fde853
  HockeySDK: 27d8b411208f9d3f70c8f6695a8defa2a3465721
  JASidePanels: ca943907d88a0738c80755204c6098969d43e4e9
  KNSemiModalViewController: 505b7cba88b7c9b49324b48662de722f1eb81332
  LDProgressView: e0ee70a7cd858ac8c04b319ef87854e7250fb357
  MagicalRecord: 2b471584fc9e3137f3d0a56967917baa4979e224
  OCMock: b9836ab89d8d5e66cbe6333f93857037c310ee62
  OHAttributedLabel: fcf1d1245b4c8d2df94da91369b1474901d7fb14
  OHHTTPStubs: c71ea45184442339dafb97946ddca284a8b3aab5
  SDWebImage: 116e88633b5b416ea0ca4b334a4ac59cf72dd38d
  SVProgressHUD: 5034c6e22b8c2ca3e09402e48d41ed0340aa1c50
  SVPullToRefresh: d5161ebc833a38b465364412e5e307ca80bbb190
  SVSegmentedControl: 755a9721054734a77841147de3cc8babf09ba7f1

COCOAPODS: 0.33.1

**Comment by segiddins** [comment]
```yaml
PODS:
  - AFNetworking (2.3.1):
    - AFNetworking/NSURLConnection
    - AFNetworking/NSURLSession
    - AFNetworking/Reachability
    - AFNetworking/Security
    - AFNetworking/Serialization
    - AFNetworking/UIKit
  - AFNetworking/NSURLConnection (2.3.1):
    - AFNetworking/Reachability
    - AFNetworking/Security
    - AFNetworking/Serialization
  - AFNetworking/NSURLSession (2.3.1):
    - AFNetworking/Reachability
    - AFNetworking/Security
    - AFNetworking/Serialization
  - AFNetworking/Reachability (2.3.1)
  - AFNetworking/Security (2.3.1)
  - AFNetworking/Serialization (2.3.1)
  - AFNetworking/UIKit (2.3.1):
    - AFNetworking/NSURLConnection
    - AFNetworking/NSURLSession
  - Bolts (1.1.1)
  - Facebook-iOS-SDK (3.16.2):
    - Bolts
  - GHUnitIOS (0.5.8)
  - HockeySDK (3.5.6)
  - JASidePanels (1.3.2)
  - KNSemiModalViewController (0.3.1)
  - LDProgressView (1.2.1)
  - MagicalRecord (2.2):
    - MagicalRecord/Core
  - MagicalRecord/Core (2.2)
  - OCMock (3.0.2)
  - OHAttributedLabel (3.5.4)
  - OHHTTPStubs (1.2.2)
  - SDWebImage (3.7.1):
    - SDWebImage/Core
  - SDWebImage/Core (3.7.1)
  - SVProgressHUD (1.0)
  - SVPullToRefresh (0.4.1)
  - SVSegmentedControl (0.2)

DEPENDENCIES:
  - AFNetworking
  - Facebook-iOS-SDK
  - GHUnitIOS
  - HockeySDK
  - JASidePanels (~> 1)
  - KNSemiModalViewController (from `https://github.com/kentnguyen/KNSemiModalViewController.git`, tag `0.4`)
  - LDProgressView
  - MagicalRecord
  - OCMock
  - OHAttributedLabel (~> 3)
  - OHHTTPStubs (~> 1)
  - SDWebImage (~> 3)
  - SVProgressHUD
  - SVPullToRefresh
  - SVSegmentedControl

EXTERNAL SOURCES:
  KNSemiModalViewController:
    :git: https://github.com/kentnguyen/KNSemiModalViewController.git
    :tag: "0.4"

SPEC CHECKSUMS:
  AFNetworking: 6d7b76aa5d04c8c37daad3eef4b7e3f2a7620da3
  Bolts: 0ca796081c3e7c139bd86d6903c27f1b83036a5d
  Facebook-iOS-SDK: 34eef640c2cc4c8618ba0f574ad2b290e07f1b4e
  GHUnitIOS: 0fe5a01896673a7768ee76158fbae02ad8fde853
  HockeySDK: 27d8b411208f9d3f70c8f6695a8defa2a3465721
  JASidePanels: ca943907d88a0738c80755204c6098969d43e4e9
  KNSemiModalViewController: 505b7cba88b7c9b49324b48662de722f1eb81332
  LDProgressView: e0ee70a7cd858ac8c04b319ef87854e7250fb357
  MagicalRecord: 2b471584fc9e3137f3d0a56967917baa4979e224
  OCMock: b9836ab89d8d5e66cbe6333f93857037c310ee62
  OHAttributedLabel: fcf1d1245b4c8d2df94da91369b1474901d7fb14
  OHHTTPStubs: c71ea45184442339dafb97946ddca284a8b3aab5
  SDWebImage: 116e88633b5b416ea0ca4b334a4ac59cf72dd38d
  SVProgressHUD: 5034c6e22b8c2ca3e09402e48d41ed0340aa1c50
  SVPullToRefresh: d5161ebc833a38b465364412e5e307ca80bbb190
  SVSegmentedControl: 755a9721054734a77841147de3cc8babf09ba7f1

COCOAPODS: 0.33.1
```
