### ISSUE TITLE
Error on `pod install` - error occurred around fiddle.

### ISSUE THREAD

**Issue by komlow** [CocoaPods/CocoaPods#3571]
When I run `pod install`, then I got following error.
I installed ruby with rbenv.

### Command

```
/usr/local/opt/rbenv/versions/2.2.2/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 0.37.1
        Ruby : ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
    RubyGems : 2.4.5
        Host : Mac OS X 10.10.2 (14C1510)
       Xcode : 6.3.1 (6D1002)
         Git : git version 2.1.3
Ruby lib dir : /usr/local/opt/rbenv/versions/2.2.2/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 05da79d961342f4194cf10dbfd5210af041c0291
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-trunk   : 0.6.0
cocoapods-try     : 0.4.4
```

### Podfile

```ruby
pod 'Nimble'
pod 'Quick'
```

### Error

```
LoadError - dlopen(/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/x86_64-darwin14/fiddle.bundle, 9): Symbol not found: _ffi_type_double
  Referenced from: /usr/local/opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/x86_64-darwin14/fiddle.bundle
  Expected in: flat namespace
 in /usr/local/opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/x86_64-darwin14/fiddle.bundle - /usr/local/opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/x86_64-darwin14/fiddle.bundle
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/fiddle.rb:1:in `<top (required)>'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/xcodeproj-0.24.1/lib/xcodeproj/plist_helper.rb:1:in `<top (required)>'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/xcodeproj-0.24.1/lib/xcodeproj/project.rb:6:in `<top (required)>'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-0.37.1/lib/cocoapods/installer/analyzer.rb:696:in `block (2 levels) in compute_target_platforms'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-0.37.1/lib/cocoapods/installer/analyzer.rb:693:in `each'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-0.37.1/lib/cocoapods/installer/analyzer.rb:693:in `block in compute_target_platforms'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-0.37.1/lib/cocoapods/user_interface.rb:49:in `section'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-0.37.1/lib/cocoapods/installer/analyzer.rb:692:in `compute_target_platforms'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-0.37.1/lib/cocoapods/installer/analyzer.rb:52:in `analyze'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-0.37.1/lib/cocoapods/installer.rb:190:in `analyze'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-0.37.1/lib/cocoapods/installer.rb:112:in `block in resolve_dependencies'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-0.37.1/lib/cocoapods/user_interface.rb:49:in `section'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-0.37.1/lib/cocoapods/installer.rb:111:in `resolve_dependencies'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-0.37.1/lib/cocoapods/installer.rb:91:in `install!'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-0.37.1/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-0.37.1/lib/cocoapods/command/project.rb:101:in `run'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-0.37.1/lib/cocoapods/command.rb:46:in `run'
/usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-0.37.1/bin/pod:44:in `<top (required)>'
/usr/local/opt/rbenv/versions/2.2.2/bin/pod:23:in `load'
/usr/local/opt/rbenv/versions/2.2.2/bin/pod:23:in `<main>'
```

**Comment by komlow** [comment]
I resolved this problem by building ruby with following options:
`RUBY_CONFIGURE_OPTS="--enable-pthread --enable-shared --with-readline-dir=`brew --prefix readline` --with-openssl-dir=`brew --prefix openssl` --with-opt-dir=`brew --prefix libffi`" rbenv install 2.2.2`

So I close this issue.

**Comment by trejkaz** [comment]
I get this same error, but my Ruby is 2.1.2 straight from rbenv install. Does this mean I should nag ruby-build about the problem? :/
