### ISSUE TITLE
can't push the lib : "[!] The podspec does not validate."

### ISSUE THREAD

**Issue by yishuiliunian** [CocoaPods/CocoaPods#3584]
when i push my lib , it occurs an error.  but it do not show any error message. so i can not locate the error.

and i use the command
```
pod spec lint DZCamera.podspec --allow-warnings
```
it said :  "DZCamera.podspec passed validation."

and the error message is 
```
** BUILD SUCCEEDED **

 -> DZCamera (0.1.3)
    - WARN  |  GPUImage/framework/Source/iOS/GPUImageMovieWriter.m:202:13: warning: unused variable 'videoCodec' [-Wunused-variable]
    - WARN  |  GPUImage/framework/Source/iOS/GPUImageMovieWriter.m:203:13: warning: unused variable 'width' [-Wunused-variable]
    - WARN  |  GPUImage/framework/Source/iOS/GPUImageMovieWriter.m:204:13: warning: unused variable 'height' [-Wunused-variable]
    - WARN  |  GPUImage/framework/Source/iOS/GPUImageMovieWriter.m:569:9: warning: unused variable 'status' [-Wunused-variable]
    - WARN  |  GPUImage/framework/Source/GPUImageOutput.m:22:9: warning: 'dispatch_get_current_queue' is deprecated: first deprecated in iOS 6.0 [-Wdeprecated-declarations]
    - NOTE  |  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.3.sdk/usr/include/dispatch/queue.h:301:1: note: 'dispatch_get_current_queue' has been explicitly marked deprecated here
    - WARN  |  GPUImage/framework/Source/GPUImageOutput.m:39:9: warning: 'dispatch_get_current_queue' is deprecated: first deprecated in iOS 6.0 [-Wdeprecated-declarations]
    - WARN  |  GPUImage/framework/Source/GPUImageOutput.m:55:9: warning: 'dispatch_get_current_queue' is deprecated: first deprecated in iOS 6.0 [-Wdeprecated-declarations]
    - WARN  |  GPUImage/framework/Source/GPUImageOutput.m:72:9: warning: 'dispatch_get_current_queue' is deprecated: first deprecated in iOS 6.0 [-Wdeprecated-declarations]
    - WARN  |  GPUImage/framework/Source/iOS/GPUImageView.m:187:12: warning: unused variable 'framebufferCreationStatus' [-Wunused-variable]

[!] The podspec does not validate.

/Users/stonedong/.rvm/gems/ruby-2.1.3@global/gems/cocoapods-trunk-0.6.0/lib/pod/command/trunk/push.rb:111:in `validate_podspec'
/Users/stonedong/.rvm/gems/ruby-2.1.3@global/gems/cocoapods-trunk-0.6.0/lib/pod/command/trunk/push.rb:58:in `run'
/Users/stonedong/.rvm/gems/ruby-2.1.3@global/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Users/stonedong/.rvm/gems/ruby-2.1.3@global/gems/cocoapods-0.37.1/lib/cocoapods/command.rb:46:in `run'
/Users/stonedong/.rvm/gems/ruby-2.1.3@global/gems/cocoapods-0.37.1/bin/pod:44:in `<top (required)>'
/Users/stonedong/.rvm/rubies/ruby-2.1.3/bin/pod:23:in `load'
/Users/stonedong/.rvm/rubies/ruby-2.1.3/bin/pod:23:in `<main>'
/Users/stonedong/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `eval'
/Users/stonedong/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by orta** [comment]
if you add ``--verbose` does it add anything extra?

**Comment by yishuiliunian** [comment]
the text that i paste upside is the output

```
pod trunk push --verbose
```

this command occurs  the last error.

**Comment by yishuiliunian** [comment]
but check use this command ,  it pass
```
pod spec lint DZCamera.podspec --allow-warnings
```

**Comment by orta** [comment]
Have you warn it with allow warnings in trunk too, `pod trunk push --allow-warnings --verbose` ?

**Comment by orta** [comment]
I think we could definitely add something here around `[!] The podspec does not validate.` - that this option exists anyway.

**Comment by yishuiliunian** [comment]
it works.  i can push my pod when adding ```--allow-warnings```, why?

**Comment by neonichu** [comment]
`--allow-warnings` lets you push despite warnings, see the various `WARN` messages lint shows you. This works as intended.

We already have #3476 as a ticket to clarify the linter message.
