### ISSUE TITLE
NoMethodError - undefined method `[]' for #<Xcodeproj::Project::Object::PBXFileReference:0x007fb12b393f08>

### ISSUE THREAD

**Issue by kidzss** [CocoaPods/CocoaPods#3590]
### Command

```
/usr/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 0.37.1
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin13]
    RubyGems : 2.4.7
        Host : Mac OS X 10.9.5 (13F1077)
       Xcode : 6.2 (6C131e)
         Git : git version 1.9.5 (Apple Git-50.3)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master-1 - https://github.com/CocoaPods/Specs.git @ 3d6bf3e65934a12a52f1f6897cc5ed9fcdaa1ca2
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-trunk   : 0.6.0
cocoapods-try     : 0.4.4
```

### Podfile

```ruby
#Uncomment this line to define a global platform for your project
#platform :ios, ‘7.0’

target 'BPMTask' do
inhibit_all_warnings!

pod 'NativeSDK', :path => "~/SAP/MobileSDK3/NativeSDK/NativeSDK.podspec"

end

target 'BPMTaskTests' do

pod 'NativeSDK', :path => "~/SAP/MobileSDK3/NativeSDK/NativeSDK.podspec"

end
```

### Error

```
NoMethodError - undefined method `[]' for #<Xcodeproj::Project::Object::PBXFileReference:0x007fb12b393f08>
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/project.rb:189:in `block in add_file_reference'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:263:in `block in each_filename'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:263:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:263:in `each_filename'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/project.rb:187:in `add_file_reference'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer/file_references_installer.rb:168:in `block (2 levels) in add_file_accessors_paths_to_pods_group'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer/file_references_installer.rb:166:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer/file_references_installer.rb:166:in `block in add_file_accessors_paths_to_pods_group'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer/file_references_installer.rb:162:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer/file_references_installer.rb:162:in `add_file_accessors_paths_to_pods_group'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer/file_references_installer.rb:103:in `block in add_resources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/user_interface.rb:110:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer/file_references_installer.rb:102:in `add_resources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer/file_references_installer.rb:38:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer.rb:495:in `install_file_references'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer.rb:131:in `block in generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/user_interface.rb:49:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer.rb:129:in `generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer.rb:97:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/command.rb:46:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=undefined+method+%60%5B%5D%27+for+%23%3CXcodeproj%3A%3AProject%3A%3AObject%3A%3APBXFileReference%3A0x007fb12b393f08%3E&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

zhougangtaodeMacBook-Pro-2:BPMTask gtzhou$ xcodeproj target-diff
Target 1 by name `' not found in the project.
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.24.1/lib/xcodeproj/helper.rb:9:in `initialize'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.24.1/lib/xcodeproj/command/target_diff.rb:29:in `new'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.24.1/lib/xcodeproj/command/target_diff.rb:29:in `run'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.24.1/lib/xcodeproj/command.rb:77:in `run'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.24.1/bin/xcodeproj:13:in `<top (required)>'
/usr/bin/xcodeproj:23:in `load'
/usr/bin/xcodeproj:23:in `<main>'

**Comment by neonichu** [comment]
This issue has been inactive for a long time and will be closed because we want to move forward with a clean slate after our 1.0 release. If you believe this is still relevant, please retest with the 1.0 release candidate and comment with a reproducible project in order for this to become actionable again. Thanks!
