### ISSUE TITLE
Crash when trying to generate the Pods project

### ISSUE THREAD

**Issue by oferRounds** [CocoaPods/CocoaPods#3596]
### Command

```
/usr/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 0.37.1
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.4.7
        Host : Mac OS X 10.10.4 (14E11f)
       Xcode : 6.3.1 (6D1002)
         Git : git version 2.3.2 (Apple Git-55)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 7d771270f5ca5f60f845ace2edfa4caa9352aef3
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-trunk   : 0.6.0
cocoapods-try     : 0.4.4
```

### Podfile

```ruby
platform :ios, '7.0'

pod 'ZLSwipeableView'
pod 'ParseUI'
pod 'SVProgressHUD'
pod 'THSegmentedControl', :git => 'https://github.com/tayhalla/THSegmentedControl.git'
pod 'NSDate+TimeAgo'
pod 'KVOController'
pod 'Atlas', :git => 'https://github.com/layerhq/Atlas-iOS.git'
pod 'Facebook-iOS-SDK'
pod 'ParseFacebookUtils'
pod 'REFrostedViewController', '~> 2.4'

target 'MyApp' do

end

target 'MyApp' do

end
```

### Error

```
Errno::EEXIST - File exists - /Users/ofermoragbrin/Desktop/DatingApp/Pods/Target Support Files/Pods-DatingApp-Atlas
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer/target_installer.rb:86:in `mkdir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer/target_installer.rb:86:in `mkdir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer/target_installer.rb:86:in `create_support_files_dir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer/target_installer/pod_target_installer.rb:19:in `block in install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/user_interface.rb:110:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer/target_installer/pod_target_installer.rb:17:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer.rb:508:in `block (2 levels) in install_libraries'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer.rb:505:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer.rb:505:in `block in install_libraries'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/user_interface.rb:110:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer.rb:504:in `install_libraries'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer.rb:132:in `block in generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/user_interface.rb:49:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer.rb:129:in `generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer.rb:97:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/command.rb:46:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

**Comment by oferRounds** [comment]
Reproducible also on Xcode 6.3.2.

**Comment by oferRounds** [comment]
Ok, thanks to a Friend I found it. This is a duplicate of this issue:
https://github.com/CocoaPods/CocoaPods/pull/3260

I had duplicated by mistake the lines:

target 'MyApp' do

end

**Comment by orta** [comment]
I wonder if we can protect against this crash?
