### ISSUE TITLE
When I update my framework , do I need to pod trunk push again?

### ISSUE THREAD

**Issue by SarielTang** [CocoaPods/CocoaPods#3608]
When I pod trunk push again , I met the following situation.
```
[!] Found podspec `CycleView.podspec`
Validating podspec
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/user_interface/error_report.rb:13:in `report': incompatible character encodings: UTF-8 and ASCII-8BIT (Encoding::CompatibilityError)
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/command.rb:59:in `report_error'
	from /Library/Ruby/Gems/2.0.0/gems/claide-0.8.1/lib/claide/command.rb:374:in `handle_exception'
	from /Library/Ruby/Gems/2.0.0/gems/claide-0.8.1/lib/claide/command.rb:315:in `rescue in run'
	from /Library/Ruby/Gems/2.0.0/gems/claide-0.8.1/lib/claide/command.rb:303:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/command.rb:46:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/bin/pod:44:in `<top (required)>'
	from /usr/bin/pod:23:in `load'
	from /usr/bin/pod:23:in `<main>'
```

**Comment by segiddins** [comment]
Ah so the issue here is that your terminal's encoding isn't `UTF-8`

**Comment by SarielTang** [comment]
thank you~
