### ISSUE TITLE
pod lib create without demo application issue

### ISSUE THREAD

**Issue by jwutke** [CocoaPods/CocoaPods#3609]
Trying to create a pod without a demo application causes an error. I have tried with both Swift and Obj-C.

```
pod --version
0.37.1
```

```
pod lib create test

Cloning `https://github.com/CocoaPods/pod-template.git` into `test`.
  $ /usr/local/bin/git clone https://github.com/CocoaPods/pod-template.git test
  Cloning into 'test'...

Configuring test template.

------------------------------

To get you started we need to ask a few questions, this should only take a minute.

If this is your first time we recommend running through with the guide: 
 - http://guides.cocoapods.org/making/using-pod-lib-create.html
 ( hold cmd and double click links to open in a browser. )


What language do you want to use?? [ ObjC / Swift ]
 > Swift

Would you like to include a demo application with your library? [ Yes / No ]
 > No

Which testing frameworks will you use? [ Quick / None ]
 > Quick

Would you like to do view based testing? [ Yes / No ]
 > No
/Users/jwutke/test/setup/ProjectManipulator.rb:63:in `remove_demo_project': undefined method `remove_from_project' for nil:NilClass (NoMethodError)
	from /Users/jwutke/test/setup/ProjectManipulator.rb:32:in `run'
	from /Users/jwutke/test/setup/ConfigureSwift.rb:49:in `perform'
	from /Users/jwutke/test/setup/ConfigureSwift.rb:7:in `perform'
	from /Users/jwutke/test/setup/TemplateConfigurator.rb:76:in `run'
	from ./configure:9:in `<main>'

To learn more about the template see `https://github.com/CocoaPods/pod-template.git`.
To learn more about creating a new pod, see `http://guides.cocoapods.org/making/making-a-cocoapod`.
```

**Comment by segiddins** [comment]
@jwutke could you please move this over to https://github.com/CocoaPods/pod-template?

**Comment by jwutke** [comment]
Yeah for sure. 
https://github.com/CocoaPods/pod-template/issues/108
