### ISSUE TITLE
NoMethodError - undefined method `plugins' for nil:NilClass

### ISSUE THREAD

**Issue by ricardopereira** [CocoaPods/CocoaPods#3619]
### Command

```
/usr/bin/pod spec lint
```

### Report

* What did you do?
Check if the new Podspec lints correctly.

### Stack

```
   CocoaPods : 0.37.2
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.0.14
        Host : Mac OS X 10.10.3 (14D98g)
       Xcode : 6.3.2 (6D2105)
         Git : git version 2.2.1
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 2a55a1e79dbfa1447450c7b3a29578f2f5487fd7
```

### Plugins

```
cocoapods-deintegrate : 0.2.1
cocoapods-keys        : 1.2.1
cocoapods-plugins     : 0.4.2
cocoapods-trunk       : 0.1.4
cocoapods-try         : 0.4.5
```

### Error

```
NoMethodError - undefined method `plugins' for nil:NilClass
/Library/Ruby/Gems/2.0.0/gems/cocoapods-keys-1.2.1/lib/plugin.rb:77:in `validates_for_keys'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-keys-1.2.1/lib/plugin.rb:72:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/validator.rb:323:in `install_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/validator.rb:225:in `block in perform_extensive_analysis'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/validator.rb:221:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/validator.rb:221:in `perform_extensive_analysis'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/validator.rb:75:in `validate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/command/spec/lint.rb:55:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/command/spec/lint.rb:46:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/command/spec/lint.rb:46:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/command.rb:46:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

**Comment by segiddins** [comment]
This is a bug in CocoaPods-keys that I believe I fixed recently.

**Comment by ricardopereira** [comment]
But I have the latest version.

**Comment by nebiros** [comment]
Same issue.

### Stack

```
   CocoaPods : 0.37.2
        Ruby : ruby 2.1.3p242 (2014-09-19 revision 47630) [x86_64-darwin14.0]
    RubyGems : 2.2.2
        Host : Mac OS X 10.10.3 (14D136)
       Xcode : 6.3.2 (6D2105)
         Git : git version 2.4.2
Ruby lib dir : /Users/nebiros/.rbenv/versions/2.1.3/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 62b4dc4ba99599f0274c0b4165d2dff28104d988
```

### Plugins

```
cocoapods-deintegrate : 0.2.1
cocoapods-keys        : 1.2.1
cocoapods-plugins     : 0.4.2
cocoapods-trunk       : 0.6.1
cocoapods-try         : 0.4.5
```

### Error

```
NoMethodError - undefined method `plugins' for nil:NilClass
/Users/nebiros/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-keys-1.2.1/lib/plugin.rb:77:in `validates_for_keys'
/Users/nebiros/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-keys-1.2.1/lib/plugin.rb:72:in `install!'
/Users/nebiros/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-0.37.2/lib/cocoapods/validator.rb:323:in `install_pod'
/Users/nebiros/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-0.37.2/lib/cocoapods/validator.rb:225:in `block in perform_extensive_analysis'
/Users/nebiros/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-0.37.2/lib/cocoapods/validator.rb:221:in `each'
/Users/nebiros/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-0.37.2/lib/cocoapods/validator.rb:221:in `perform_extensive_analysis'
/Users/nebiros/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-0.37.2/lib/cocoapods/validator.rb:75:in `validate'
/Users/nebiros/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-0.37.2/lib/cocoapods/command/spec/lint.rb:55:in `block in run'
/Users/nebiros/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-0.37.2/lib/cocoapods/command/spec/lint.rb:46:in `each'
/Users/nebiros/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-0.37.2/lib/cocoapods/command/spec/lint.rb:46:in `run'
/Users/nebiros/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Users/nebiros/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-0.37.2/lib/cocoapods/command.rb:46:in `run'
/Users/nebiros/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-0.37.2/bin/pod:44:in `<top (required)>'
/Users/nebiros/.rbenv/versions/2.1.3/bin/pod:23:in `load'
/Users/nebiros/.rbenv/versions/2.1.3/bin/pod:23:in `<main>'
```

**Comment by kylef** [comment]
Fixed by https://github.com/orta/cocoapods-keys/commit/5b16687a30191ebef8d0db54786159d6fc3cbc19. /c @orta to do cocoapods-keys release.
