### ISSUE TITLE
pod linter executing prepare_command of a dependency in the wrong folder

### ISSUE THREAD

**Issue by andreacremaschi** [CocoaPods/CocoaPods#3683]
hi,

I am creating a new pod spec (with CocoaPods 0.37.2) that looks like this:

```ruby
Pod::Spec.new do |s|

  s.name         = "GEOSwift"
  s.version      = "0.1"
  s.summary      = "The Swift Geographic Engine."

  <!-- stripping unrelevant part --->

  s.dependency "geos", "~> 3.4.2"

end
```

It has a single dependency named `geos` that was already published and lints correctly.
`geos` is a GNU autoconf project, so it runs a complex `prepare_command` step.

When I try to run `pod spec lint` on my new `GEOSwift.podspec` it fails with this error:

```bash
$ pod spec lint --verbose GEOSwift.podspec

    GEOS.swift (0.1) - Analyzing on iOS 7.0 platform.
  Preparing

Analyzing dependencies

Inspecting targets to integrate

Fetching external sources
-> Fetching podspec for `GEOS.swift` from `/Users/andreacremaschi/Developing/MySource/GEOSwift-Swift1.2/GEOSwift.podspec`

Resolving dependencies of 
Starting resolution (2015-06-14 19:16:58 +0200)
Creating possibility state for GEOS.swift (from `/Users/andreacremaschi/Developing/MySource/GEOSwift-Swift1.2/GEOSwift.podspec`) (1 remaining)
  Attempting to activate GEOS.swift (0.1)
  Activated GEOS.swift at GEOS.swift (0.1)
  Requiring nested dependencies (geos (~> 3.4.2))
  Creating possibility state for geos (~> 3.4.2) (1 remaining)
    Attempting to activate geos (3.4.2)
    Activated geos at geos (3.4.2)
    Requiring nested dependencies ()
Finished resolution (2 steps) (Took 0.100702 seconds) (2015-06-14 19:16:58 +0200)
Unactivated: 
Activated: GEOS.swift, geos

Comparing resolved specification to the sandbox manifest
  A GEOS.swift
  A geos

Downloading dependencies

-> Installing GEOS.swift (0.1)
 > Git download
 > Git download
     $ /usr/local/bin/git clone https://github.com/andreacremaschi/GEOSwift.git
     /var/folders/qr/tvdnmtvx0fsbx_994p8fk8dm0000gn/T/d20150614-10020-1ui64so --single-branch --depth 1
     --branch 0.1
     Cloning into '/var/folders/qr/tvdnmtvx0fsbx_994p8fk8dm0000gn/T/d20150614-10020-1ui64so'...
     Note: checking out '3d6a9ffbd6f82f695041d372b16dcff7af8aa9fd'.
     
     You are in 'detached HEAD' state. You can look around, make experimental
     changes and commit them, and you can discard any commits you make in this
     state without impacting any branches by performing another checkout.
     
     If you want to create a new branch to retain commits you create, you may
     do so (now or later) by using -b with the checkout command again. Example:
     
       git checkout -b new_branch_name
     
 > Running prepare command
   $ /bin/bash -c  set -e  type -P autoconf &>/dev/null || alias autoconf 'xcrun autoconf' type -P autoheader
   &>/dev/null || alias autoheader 'xcrun autoheader' type -P aclocal &>/dev/null || alias aclocal 'xcrun
   aclocal' type -P automake &>/dev/null || alias automake 'xcrun automake' type -P glibtool &>/dev/null ||
   alias glibtool 'xcrun glibtool' type -P glibtoolize &>/dev/null || alias glibtoolize 'xcrun glibtoolize' 
   sh autogen.sh ./configure ./tools/svn_repo_revision.sh  sed -i "" "s/\/\* #undef HAVE_INT64_T_64
   \*\//#define HAVE_INT64_T_64 1/" include/geos/platform.h sed -i "" "s/#define HAVE_LONG_INT_64 1/\/\*
   #undef HAVE_LONG_INT_64 \*\//" include/geos/platform.h  cat <<EOT >> include/geos/platform.h   #undef ISNAN
   #define ISNAN(x) (std::isnan(x)) EOT
   sh: autogen.sh: No such file or directory
[!] /bin/bash -c 
set -e

type -P autoconf &>/dev/null || alias autoconf 'xcrun autoconf'
type -P autoheader &>/dev/null || alias autoheader 'xcrun autoheader'
type -P aclocal &>/dev/null || alias aclocal 'xcrun aclocal'
type -P automake &>/dev/null || alias automake 'xcrun automake'
type -P glibtool &>/dev/null || alias glibtool 'xcrun glibtool'
type -P glibtoolize &>/dev/null || alias glibtoolize 'xcrun glibtoolize'

sh autogen.sh
./configure
./tools/svn_repo_revision.sh

sed -i "" "s/\/\* #undef HAVE_INT64_T_64 \*\//#define HAVE_INT64_T_64 1/" include/geos/platform.h
sed -i "" "s/#define HAVE_LONG_INT_64 1/\/\* #undef HAVE_LONG_INT_64 \*\//" include/geos/platform.h

cat <<EOT >> include/geos/platform.h
  #undef ISNAN
  #define ISNAN(x) (std::isnan(x))
EOT

sh: autogen.sh: No such file or directory


/Users/andreacremaschi/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.2/lib/cocoapods/executable.rb:70:in `execute_command'
/Users/andreacremaschi/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.2/lib/cocoapods/executable.rb:27:in `block in executable'
/Users/andreacremaschi/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.2/lib/cocoapods/installer/pod_source_preparer.rb:64:in `block (2 levels) in run_prepare_command'
/Users/andreacremaschi/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.2/lib/cocoapods/installer/pod_source_preparer.rb:60:in `chdir'
/Users/andreacremaschi/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.2/lib/cocoapods/installer/pod_source_preparer.rb:60:in `block in run_prepare_command'
/Users/andreacremaschi/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.2/lib/cocoapods/user_interface.rb:59:in `section'
/Users/andreacremaschi/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.2/lib/cocoapods/installer/pod_source_preparer.rb:59:in `run_prepare_command'
/Users/andreacremaschi/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.2/lib/cocoapods/installer/pod_source_preparer.rb:37:in `prepare!'
/Users/andreacremaschi/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.2/lib/cocoapods/downloader/cache.rb:154:in `copy_and_clean'
/Users/andreacremaschi/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.2/lib/cocoapods/downloader/cache.rb:111:in `block (2 levels) in uncached_pod'
/Users/andreacremaschi/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.2/lib/cocoapods/downloader/cache.rb:109:in `each'
/Users/andreacremaschi/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.2/lib/cocoapods/downloader/cache.rb:109:in `block in uncached_pod'
/Users/andreacremaschi/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.2/lib/cocoapods/downloader/cache.rb:133:in `call'
/Users/andreacremaschi/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.2/lib/cocoapods/downloader/cache.rb:133:in `in_tmpdir'
/Users/andreacremaschi/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.2/lib/cocoapods/downloader/cache.rb:106:in `uncached_pod'
/Users/andreacremaschi/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.2/lib/cocoapods/downloader/cache.rb:33:in `download_pod'
/Users/andreacremaschi/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.2/lib/cocoapods/downloader.rb:34:in `download'
/Users/andreacremaschi/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.2/lib/cocoapods/installer/pod_source_installer.rb:90:in `download_source'
/Users/andreacremaschi/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.2/lib/cocoapods/installer/pod_source_installer.rb:47:in `install!'
/Users/andreacremaschi/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.2/lib/cocoapods/installer.rb:310:in `install_source_of_pod'
/Users/andreacremaschi/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.2/lib/cocoapods/installer.rb:285:in `block (2 levels) in install_pod_sources'
/Users/andreacremaschi/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.2/lib/cocoapods/user_interface.rb:80:in `titled_section'
/Users/andreacremaschi/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.2/lib/cocoapods/installer.rb:284:in `block in install_pod_sources'
/Users/andreacremaschi/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.2/lib/cocoapods/installer.rb:276:in `each'
/Users/andreacremaschi/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.2/lib/cocoapods/installer.rb:276:in `install_pod_sources'
/Users/andreacremaschi/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.2/lib/cocoapods/installer.rb:124:in `block in download_dependencies'
/Users/andreacremaschi/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.2/lib/cocoapods/user_interface.rb:59:in `section'
/Users/andreacremaschi/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.2/lib/cocoapods/installer.rb:122:in `download_dependencies'
/Users/andreacremaschi/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.2/lib/cocoapods/installer.rb:94:in `install!'
/Users/andreacremaschi/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.2/lib/cocoapods/validator.rb:323:in `install_pod'
/Users/andreacremaschi/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.2/lib/cocoapods/validator.rb:225:in `block in perform_extensive_analysis'
/Users/andreacremaschi/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.2/lib/cocoapods/validator.rb:221:in `each'
/Users/andreacremaschi/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.2/lib/cocoapods/validator.rb:221:in `perform_extensive_analysis'
/Users/andreacremaschi/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.2/lib/cocoapods/validator.rb:75:in `validate'
/Users/andreacremaschi/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.2/lib/cocoapods/command/spec/lint.rb:55:in `block in run'
/Users/andreacremaschi/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.2/lib/cocoapods/command/spec/lint.rb:46:in `each'
/Users/andreacremaschi/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.2/lib/cocoapods/command/spec/lint.rb:46:in `run'
/Users/andreacremaschi/.rvm/gems/ruby-2.1.3/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Users/andreacremaschi/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.2/lib/cocoapods/command.rb:46:in `run'
/Users/andreacremaschi/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.2/bin/pod:44:in `<top (required)>'
/Users/andreacremaschi/.rvm/gems/ruby-2.1.3/bin/pod:23:in `load'
/Users/andreacremaschi/.rvm/gems/ruby-2.1.3/bin/pod:23:in `<main>'
/Users/andreacremaschi/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `eval'
/Users/andreacremaschi/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `<main>'
```

As far as I understand it, it is trying to execute the `prepare_command` in the wrong folder.

This is the repository (the correct .podspec is in the `develop` branch): https://github.com/andreacremaschi/GEOSwift

**Comment by andreacremaschi** [comment]
I tried to configure a `Podfile` referring to a local .podspec and I encounter the same issue:

```ruby
target 'GEOSwift-test' do
pod 'GEOSwift', :podspec => './GEOSwift.podspec'
end
```

```bash
$ pod install
Analyzing dependencies
Fetching podspec for `GEOSwift` from `./GEOSwift.podspec`
Downloading dependencies
Installing GEOSwift (0.1)
[!] /bin/bash -c 
set -e

type -P autoconf &>/dev/null || alias autoconf 'xcrun autoconf'
type -P autoheader &>/dev/null || alias autoheader 'xcrun autoheader'
type -P aclocal &>/dev/null || alias aclocal 'xcrun aclocal'
type -P automake &>/dev/null || alias automake 'xcrun automake'
type -P glibtool &>/dev/null || alias glibtool 'xcrun glibtool'
type -P glibtoolize &>/dev/null || alias glibtoolize 'xcrun glibtoolize'

sh autogen.sh
./configure
./tools/svn_repo_revision.sh

sed -i "" "s/\/\* #undef HAVE_INT64_T_64 \*\//#define HAVE_INT64_T_64 1/" include/geos/platform.h
sed -i "" "s/#define HAVE_LONG_INT_64 1/\/\* #undef HAVE_LONG_INT_64 \*\//" include/geos/platform.h

cat <<EOT >> include/geos/platform.h
  #undef ISNAN
  #define ISNAN(x) (std::isnan(x))
EOT

sh: autogen.sh: No such file or directory
```

**Comment by segiddins** [comment]
I'm not seeing `autogen.sh` in https://github.com/andreacremaschi/GEOSwift/tree/develop ?

**Comment by andreacremaschi** [comment]
That's correct and that is actually the issue: `autogen.sh` is in the `geos` dependency source tree, NOT in my GEOSwift pod source tree..

**Comment by segiddins** [comment]
Then why is your podspec referencing it?

**Comment by andreacremaschi** [comment]
It is not! This is why I think the error is in CocoaPods. Here is the full .podspec:

```ruby
Pod::Spec.new do |s|

  s.name         = "GEOSwift"
  s.version      = "0.1"
  s.summary      = "The Swift Geographic Engine."

  s.description  = <<-DESC
Easily handle a geographical object model (points, linestrings, polygons etc.) and related topographical operations (intersections, overlapping etc.). 
A type-safe, MIT-licensed Swift interface to the OSGeo's GEOS library routines, nicely integrated with MapKit and Quicklook.
DESC

  s.homepage     = "https://github.com/andreacremaschi/GEOSwift"
  # s.screenshots  = "www.example.com/screenshots_1.gif", "www.example.com/screenshots_2.gif"
  s.license      = { :type => "MIT", :file => "LICENSE" }
  s.author       = { "Andrea Cremaschi" => "andreacremaschi@libero.it" }
  s.social_media_url   = "http://twitter.com/andreacremaschi"
  s.platform     = :ios, "7.0"
  s.source       = { :git => "https://github.com/andreacremaschi/GEOSwift.git", :tag => "0.1" }
  s.source_files = "GEOSwift"
  s.dependency "geos", "~> 3.4.2"

end
```

**Comment by andreacremaschi** [comment]
Sorry @segiddins I read once again my question and it wasn't clear! :) My fault.  
I forgot to say that `autogen.sh` is part of the autoconf process invoked in the `prepare_command` step of the _dependency_ pod `geos`. No need to say that the dependency correctly lints and compiles with any project if integrated by itself.

**Comment by andreacremaschi** [comment]
Apparently the issue is due to the fact that my repo contained a second .podspec in a subfolder, i.e.:

```
/
  GEOSwift.podspec
  geos/
    geos.podspec
```

CocoaPods was probably trying to validate all the .podspecs in the folder hierarchy. Two weird things:

1. to make the pod lint I had to remove `geos.podspec`not from my local working copy but __from the remote repository__. Shouldn't CocoaPods validate the local podspecs instead?
2. I was specifying the .podspec to validate in my command. Shouldn't CocoaPods validate only the specified pod spec without searching in the folder hierarchy?

```bash
$ pod spec lint --verbose GEOSwift.podspec
```

**Comment by segiddins** [comment]
It did only _validate_ the specified podspec, but the cache attempted to cache all the podpecs it encountered. Maybe we should only search for the top-level podspec? Thought, CocoaPods/Core?

**Comment by orta** [comment]
> Maybe we should only search for the top-level pod spec

I think this is a good assumption :+1:

**Comment by andreacremaschi** [comment]
:beers:
