### ISSUE TITLE
Error while running "pod install Errno::ENOENT - No such file or directory @ rb_file_s_stat"

### ISSUE THREAD

**Issue by mirkoflpvc** [CocoaPods/CocoaPods#3695]
* What did you do?

I ran pod install.

* What did you expect to happen?

I expected my xcode project to be updated according to the Podfile

* What happened instead?

I got the following error

### Stack

```
   CocoaPods : 0.37.2
        Ruby : ruby 2.1.1p76 (2014-02-24 revision 45161) [x86_64-darwin12.0]
    RubyGems : 2.2.2
        Host : Mac OS X 10.10.3 (14D136)
       Xcode : 6.3.1 (6D1002)
         Git : git version 2.3.2 (Apple Git-55)
Ruby lib dir : /Users/federico/.rvm/rubies/ruby-2.1.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 7cf8f7e3bce7bd610bc4dbada0bffe4edc9bafaa
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-trunk   : 0.6.1
cocoapods-try     : 0.4.5
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
pod 'SDWebImage', '~> 3.6'
pod 'xxxPrivate1', :git => 'git@private:shared/xxxPrivate1.git', :tag => '2.1.11'
pod 'xxxPrivate2', :git => 'git@private:shared/xxxPrivate2.git', :tag => '1.0.4'
pod 'xxxPrivate3', :git => 'git@private:shared/xxxPrivate3.git', :tag => '1.1.1'
pod 'Reachability', '~> 3.2'
pod 'xxxPrivate4', :git => 'git@private:shared/xxxPrivate4.git', :tag =>'1.3.1'
pod 'AWSCore'
pod 'Facebook-iOS-SDK', '~> 3.23.2'
```

### Error

```
Errno::ENOENT - No such file or directory @ rb_file_s_stat - /var/folders/ft/1pdf1x4124s3nx1nggv8twdh0000gn/T/d20150617-35674-1i3gk2k
/Users/federico/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/fileutils.rb:1573:in `stat'
/Users/federico/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/fileutils.rb:1573:in `block in fu_each_src_dest'
/Users/federico/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/fileutils.rb:1589:in `fu_each_src_dest0'
/Users/federico/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/fileutils.rb:1571:in `fu_each_src_dest'
/Users/federico/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/fileutils.rb:440:in `cp_r'
/Users/federico/.rvm/gems/ruby-2.1.1/gems/cocoapods-0.37.2/lib/cocoapods/downloader.rb:42:in `block in download'
/Users/federico/.rvm/gems/ruby-2.1.1/gems/cocoapods-0.37.2/lib/cocoapods/user_interface.rb:140:in `message'
/Users/federico/.rvm/gems/ruby-2.1.1/gems/cocoapods-0.37.2/lib/cocoapods/downloader.rb:40:in `download'
/Users/federico/.rvm/gems/ruby-2.1.1/gems/cocoapods-0.37.2/lib/cocoapods/external_sources/abstract_external_source.rb:108:in `block in pre_download'
/Users/federico/.rvm/gems/ruby-2.1.1/gems/cocoapods-0.37.2/lib/cocoapods/user_interface.rb:80:in `titled_section'
/Users/federico/.rvm/gems/ruby-2.1.1/gems/cocoapods-0.37.2/lib/cocoapods/external_sources/abstract_external_source.rb:106:in `pre_download'
/Users/federico/.rvm/gems/ruby-2.1.1/gems/cocoapods-0.37.2/lib/cocoapods/external_sources/downloader_source.rb:13:in `fetch'
/Users/federico/.rvm/gems/ruby-2.1.1/gems/cocoapods-0.37.2/lib/cocoapods/installer/analyzer.rb:358:in `fetch_external_source'
/Users/federico/.rvm/gems/ruby-2.1.1/gems/cocoapods-0.37.2/lib/cocoapods/installer/analyzer.rb:335:in `block (2 levels) in fetch_external_sources'
/Users/federico/.rvm/gems/ruby-2.1.1/gems/cocoapods-0.37.2/lib/cocoapods/installer/analyzer.rb:334:in `each'
/Users/federico/.rvm/gems/ruby-2.1.1/gems/cocoapods-0.37.2/lib/cocoapods/installer/analyzer.rb:334:in `block in fetch_external_sources'
/Users/federico/.rvm/gems/ruby-2.1.1/gems/cocoapods-0.37.2/lib/cocoapods/user_interface.rb:59:in `section'
/Users/federico/.rvm/gems/ruby-2.1.1/gems/cocoapods-0.37.2/lib/cocoapods/installer/analyzer.rb:333:in `fetch_external_sources'
/Users/federico/.rvm/gems/ruby-2.1.1/gems/cocoapods-0.37.2/lib/cocoapods/installer/analyzer.rb:62:in `analyze'
/Users/federico/.rvm/gems/ruby-2.1.1/gems/cocoapods-0.37.2/lib/cocoapods/installer.rb:196:in `analyze'
/Users/federico/.rvm/gems/ruby-2.1.1/gems/cocoapods-0.37.2/lib/cocoapods/installer.rb:114:in `block in resolve_dependencies'
/Users/federico/.rvm/gems/ruby-2.1.1/gems/cocoapods-0.37.2/lib/cocoapods/user_interface.rb:59:in `section'
/Users/federico/.rvm/gems/ruby-2.1.1/gems/cocoapods-0.37.2/lib/cocoapods/installer.rb:113:in `resolve_dependencies'
/Users/federico/.rvm/gems/ruby-2.1.1/gems/cocoapods-0.37.2/lib/cocoapods/installer.rb:93:in `install!'
/Users/federico/.rvm/gems/ruby-2.1.1/gems/cocoapods-0.37.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/federico/.rvm/gems/ruby-2.1.1/gems/cocoapods-0.37.2/lib/cocoapods/command/project.rb:101:in `run'
/Users/federico/.rvm/gems/ruby-2.1.1/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Users/federico/.rvm/gems/ruby-2.1.1/gems/cocoapods-0.37.2/lib/cocoapods/command.rb:46:in `run'
/Users/federico/.rvm/gems/ruby-2.1.1/gems/cocoapods-0.37.2/bin/pod:44:in `<top (required)>'
/Users/federico/.rvm/gems/ruby-2.1.1/bin/pod:23:in `load'
/Users/federico/.rvm/gems/ruby-2.1.1/bin/pod:23:in `<main>'
/Users/federico/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
/Users/federico/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by mirkoflpvc** [comment]
Ok, no cocoapods issue. Someone had declared a dependency incorrectly in one of the private repositories. I don't know why this was the error message though.

**Comment by yoiang** [comment]
I'm getting this error as well and it isn't clear whether someone declared a dependency incorrectly or not. It would be great to have an obvious error message here if possible.

**Comment by danyalaytekin** [comment]
A similar error is also caused when trying to use CocoaPods < 0.38 to install a pod that has declared support for watchOS.

e.g. `s.watchos.deployment_target = '2.0'`

**Comment by Palleas** [comment]
I'm still having this issue from time to time. I have to wipe the Pods folder before running `pod install` to make it work.

**Comment by liweihan** [comment]
+1

**Comment by LeandroHub** [comment]
Hi! I had the same error. @Palleas solution worked for me: you saved my day. Thanks!

**Comment by srosmd** [comment]
Just wanted to add that @Palleas solution worked for me! I got this after running "pod update" after deleting a file I thought other classes weren't depending on. The deletion was indeed an accident, but worth pointing out the cause in the event someone else made the same mistake as I.

**Comment by srosmd** [comment]
Felt compelled to report that I ran into this issue again today on another repository I had. In addition to deleting the Pods directory and the Podfile.lock, I had to delete the workspace that it created and run `pod install` again.

**Comment by lihaiyin88** [comment]
YES! @Palleas solution worked. Thanks!

**Comment by a-vlad** [comment]
I had same error @mirkoflpvc Error was complete gibberish and provided no clues. I am on pod 0.37.2 My issue was  s.name value did not match the pod name i had in my podfile.

**Comment by segiddins** [comment]
@a-vlad please open a new issue with steps to reproduce

**Comment by AndyZhaoHe** [comment]
@Palleas solution worked for me! Thanks
