### ISSUE TITLE
Pod update failed with error - error remained after reinstalling ruby and cocoapods

### ISSUE THREAD

**Issue by vsehrawat** [CocoaPods/CocoaPods#3712]
### Report

* What did you do?
pod update
* What did you expect to happen?
updated library projects
* What happened instead?
gave error below

### Stack

```
   CocoaPods : 0.35.0
        Ruby : ruby 2.1.0p0 (2013-12-25 revision 44422) [x86_64-darwin13.0]
    RubyGems : 2.2.2
        Host : Mac OS X 10.10.3 (14D136)
       Xcode : 6.3.2 (6D2105)
         Git : git version 2.3.2 (Apple Git-55)
Ruby lib dir : /Users/virendra.sehrawat/.rvm/rubies/ruby-2.1.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ a2dd6229d634d18d0333b06085c719ae22d03573
```

### Plugins

```
cocoapods-plugins : 0.3.2
cocoapods-trunk   : 0.4.1
cocoapods-try     : 0.4.2
```

### Podfile

```ruby
platform :ios, '8.0'

pod "AFNetworking", "~> 2.0"
pod 'AsyncDisplayKit'
```

### Error

```
LoadError - dlopen(/Users/virendra.sehrawat/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/x86_64-darwin13.0/psych.bundle, 9): Library not loaded: /usr/local/lib/libyaml-0.2.dylib
  Referenced from: /Users/virendra.sehrawat/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/x86_64-darwin13.0/psych.bundle
  Reason: image not found - /Users/virendra.sehrawat/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/x86_64-darwin13.0/psych.bundle
/Users/virendra.sehrawat/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `require'
/Users/virendra.sehrawat/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `require'
/Users/virendra.sehrawat/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/psych.rb:1:in `<top (required)>'
/Users/virendra.sehrawat/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `require'
/Users/virendra.sehrawat/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `require'
/Users/virendra.sehrawat/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/yaml.rb:5:in `<top (required)>'
/Users/virendra.sehrawat/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `require'
/Users/virendra.sehrawat/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `require'
/Users/virendra.sehrawat/.rvm/gems/ruby-2.1.0/gems/cocoapods-core-0.35.0/lib/cocoapods-core/lockfile.rb:40:in `from_file'
/Users/virendra.sehrawat/.rvm/gems/ruby-2.1.0/gems/cocoapods-0.35.0/lib/cocoapods/config.rb:184:in `lockfile'
/Users/virendra.sehrawat/.rvm/gems/ruby-2.1.0/gems/cocoapods-0.35.0/lib/cocoapods/command/project.rb:69:in `run_install_with_update'
/Users/virendra.sehrawat/.rvm/gems/ruby-2.1.0/gems/cocoapods-0.35.0/lib/cocoapods/command/project.rb:155:in `run'
/Users/virendra.sehrawat/.rvm/gems/ruby-2.1.0/gems/claide-0.7.0/lib/claide/command.rb:271:in `run'
/Users/virendra.sehrawat/.rvm/gems/ruby-2.1.0/gems/cocoapods-0.35.0/lib/cocoapods/command.rb:45:in `run'
/Users/virendra.sehrawat/.rvm/gems/ruby-2.1.0/gems/cocoapods-0.35.0/bin/pod:43:in `<top (required)>'
/Users/virendra.sehrawat/.rvm/gems/ruby-2.1.0/bin/pod:23:in `load'
/Users/virendra.sehrawat/.rvm/gems/ruby-2.1.0/bin/pod:23:in `<main>'
/Users/virendra.sehrawat/.rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `eval'
/Users/virendra.sehrawat/.rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by segiddins** [comment]
Hm, that's interesting. It seems psych is having trouble loading libyaml, which I believe is bundled by default on OS X?

**Comment by neonichu** [comment]
I don't think it is available as a system-wide dylib on OS X, note how it is being loaded from `/usr/local/lib`. Also a manually installed Ruby is used as well, so I don't think this has anything to do with CocoaPods.

@vsehrawat You should reinstall / rebuild your custom Ruby so that its psych module actually works. Or you might want to consider using [CocoaPods.app](https://github.com/CocoaPods/CocoaPods-app/releases) to avoid such issues entirely :).
