### ISSUE TITLE
Unable to load a specification for the plugin `/Library/Ruby/Gems/2.0.0/gems/cocoapods-plugins-0.4.1`

### ISSUE THREAD

**Issue by confile** [CocoaPods/CocoaPods#3719]
I get the following error when I try to run cocoapods: 

```
[33mWARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
Consider adding the following to ~/.profile:

export LANG=en_US.UTF-8
[0m
[!] Unable to load a specification for the plugin `/Library/Ruby/Gems/2.0.0/gems/cocoapods-plugins-0.4.1`
[!] Unable to load a specification for the plugin `/Library/Ruby/Gems/2.0.0/gems/cocoapods-try-0.4.3`
[!] Unable to load a specification for the plugin `/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-0.6.0`
[!] The version of CocoaPods used to generate the lockfile (0.37.2) is higher than the version of the current executable (0.36.0). Incompatibility issues may arise.
Analyzing dependencies
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/user_interface/error_report.rb:119:in ``': No such file or directory - git (Errno::ENOENT)
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/user_interface/error_report.rb:119:in `git_information'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/user_interface/error_report.rb:38:in `report'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/command.rb:59:in `report_error'
	from /Library/Ruby/Gems/2.0.0/gems/claide-0.8.1/lib/claide/command.rb:374:in `handle_exception'
	from /Library/Ruby/Gems/2.0.0/gems/claide-0.8.1/lib/claide/command.rb:315:in `rescue in run'
	from /Library/Ruby/Gems/2.0.0/gems/claide-0.8.1/lib/claide/command.rb:303:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/lib/cocoapods/command.rb:46:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.0/bin/pod:44:in `<top (required)>'
	from /usr/bin/pod:23:in `load'
	from /usr/bin/pod:23:in `<main>'


 FAILED

FAILURE: Build failed with an exception.

```

**Comment by segiddins** [comment]
Do you have `git` in your `PATH`?

**Comment by confile** [comment]
I have the following in ``.bash_profile``:

```
export COCOAPODS_HOME=/usr/local/Cellar/ruby/2.2.0/lib/ruby/gems/2.2.0/gems/cocoapods-0.37.2
export PATH=$PATH:$COCOAPODS_HOME/bin
```

Could you post an example what you mean or what I have changed?

**Comment by segiddins** [comment]
Can you run `which git` and share the output of that?

**Comment by confile** [comment]
Sure: 

```
which git
/usr/local/git/bin/git
```

**Comment by segiddins** [comment]
and also `echo "$PATH"` ?

**Comment by confile** [comment]
echo "$PATH":
```
/Users/mg/.gvm/vertx/current/bin:/Users/mg/.gvm/springboot/current/bin:/Users/mg/.gvm/lazybones/current/bin:/Users/mg/.gvm/jbake/current/bin:/Users/mg/.gvm/groovyserv/current/bin:/Users/mg/.gvm/groovy/current/bin:/Users/mg/.gvm/griffon/current/bin:/Users/mg/.gvm/grails/current/bin:/Users/mg/.gvm/gradle/current/bin:/Users/mg/.gvm/glide/current/bin:/Users/mg/.gvm/gaiden/current/bin:/Users/mg/.gvm/crash/current/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/git/bin:/usr/local/MacGPG2/bin:/Applications/grails/grails-2.4.4/bin:/Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/bin:/Applications/J2Objc/j2objc-0.9.7b:/Applications/Gradle/gradle-2.4/bin:/usr/local/Cellar/ruby/2.2.0/lib/ruby/gems/2.2.0/gems/cocoapods-0.37.2/bin:/usr/local/mysql/bin:/Applications/adt-bundle-mac-x86_64-20140321/sdk/platform-tools:/Applications/adt-bundle-mac-x86_64-20140321/sdk/tools:/Applications/gwt/gwt-2.6.1:/Applications/apache-ant-1.9.2/bin:/Applications/apache-maven-3.1.1/bin
```

**Comment by segiddins** [comment]
Hm, thats odd. In that case, I think I'll just try and make the error report more robust so we can see what the underlying error is.

**Comment by confile** [comment]
Okay what should I do?

**Comment by segiddins** [comment]
I'll make a PR in a few minutes.

**Comment by confile** [comment]
@segiddins How can I install the new version?

**Comment by segiddins** [comment]
We have a guide at https://guides.cocoapods.org/using/unreleased-features.html that walks through using unreleased CocoaPods versions
