### ISSUE TITLE
Errno::ENOENT - No such file or directory

### ISSUE THREAD

**Issue by Skornos** [CocoaPods/CocoaPods#3726]
### Command

```
/usr/bin/pod install
```

### Report

* What did you do?
I was installing new pod CBZSplashView from the fork https://github.com/aldrincb/CBZSplashView

* What did you expect to happen?
I was expecting a new pod to be installed

* What happened instead?
This error. Installing from :head works but it doesn't provide the necessary functionality.

### Stack

```
   CocoaPods : 0.37.2
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.0.14
        Host : Mac OS X 10.10.3 (14D136)
       Xcode : 6.3.2 (6D2105)
         Git : git version 2.3.2 (Apple Git-55)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : bitbucket-touchartsro-cocoapods-specs - https://bitbucket.org/touchartsro/cocoapods-specs.git @ b96cadb138ce458cf115b37b058ad37e690e50d8
               master - https://github.com/CocoaPods/Specs.git @ 2bb8266155c444a87bd718ac94c416302b41cf5e
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-trunk   : 0.6.1
cocoapods-try     : 0.4.5
```

### Podfile

```ruby
source 'https://bitbucket.org/touchartsro/cocoapods-specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.1'

xcodeproj 'XXXXXX'

pod 'AFNetworking'
pod 'SSKeychain'
pod 'Facebook-iOS-SDK', '~> 3.23.2'
pod 'RETableViewManager'
pod 'NMRangeSlider', :git => 'https://github.com/muZZkat/NMRangeSlider.git'
pod 'IDMPhotoBrowser'
pod 'MRProgress', '~> 0.7.0'
pod 'MGSwipeTableCell'
pod 'SwipeView'
pod 'GoogleAnalytics'
pod 'ActionSheetPicker-3.0'
pod 'CocoaLumberjack'
pod 'Masonry'
pod 'DZNEmptyDataSet', :head
pod 'CBZSplashView', :git => 'https://github.com/aldrincb/CBZSplashView'
```

### Error

```
Errno::ENOENT - No such file or directory - /var/folders/06/jnn0hsn54xx0qq_08nc2lhtw0000gn/T/d20150624-40728-1k5cv6h
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1552:in `stat'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1552:in `block in fu_each_src_dest'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1568:in `fu_each_src_dest0'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1550:in `fu_each_src_dest'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:434:in `cp_r'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/downloader.rb:42:in `block in download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/user_interface.rb:140:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/downloader.rb:40:in `download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/external_sources/abstract_external_source.rb:108:in `block in pre_download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/user_interface.rb:80:in `titled_section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/external_sources/abstract_external_source.rb:106:in `pre_download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/external_sources/downloader_source.rb:13:in `fetch'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer/analyzer.rb:358:in `fetch_external_source'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer/analyzer.rb:335:in `block (2 levels) in fetch_external_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer/analyzer.rb:334:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer/analyzer.rb:334:in `block in fetch_external_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer/analyzer.rb:333:in `fetch_external_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer/analyzer.rb:62:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer.rb:196:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer.rb:114:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer.rb:113:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer.rb:93:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/command.rb:46:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

**Comment by segiddins** [comment]
This is likely fixed by https://github.com/CocoaPods/CocoaPods/commit/ef5f9a4fe0b5772909312ec31e994269e5e9a330 ?

**Comment by adison** [comment]
For someone looking for solution for this issue later.

This happened to me days ago, and no luck with cache clean or kind of regular solution.
My solution is kill the Pods folder under project, and it works like a charm.
May the sudo with you.
