### ISSUE TITLE
Pod install fails, if use xcode 7 beta for server

### ISSUE THREAD

**Issue by glassoff** [CocoaPods/CocoaPods#3740]
Hello.

I installed xcode 7 beta 2 and setted it use for server.
But pod install executes with errors:
```
Generating Pods project
2015-06-26 12:39:02.809 ruby[51831:1865631] [MT] DVTAssertions: ASSERTION FAILURE in /Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-8123.33/IDEFoundation/Initialization/IDEInitialization.m:590
Details:  Assertion failed: _initializationCompletedSuccessfully
Function: BOOL IDEIsInitializedForUserInteraction()
Thread:   <NSThread: 0x7f864ba10550>{number = 1, name = main}
Hints: None
Backtrace:
  0  0x0000000105efe047 -[DVTAssertionHandler handleFailureInFunction:fileName:lineNumber:assertionSignature:messageFormat:arguments:] (in DVTFoundation)
  1  0x0000000105efd7d4 _DVTAssertionHandler (in DVTFoundation)
  2  0x0000000105efda40 _DVTAssertionFailureHandler (in DVTFoundation)
  3  0x0000000105efd9a2 _DVTAssertionFailureHandler (in DVTFoundation)
  4  0x00000001072c51a9 IDEIsInitializedForUserInteraction (in IDEFoundation)
  5  0x000000010b234a5d +[PBXProject projectWithFile:errorHandler:readOnly:] (in DevToolsCore)
  6  0x000000010b2365e2 +[PBXProject projectWithFile:errorHandler:] (in DevToolsCore)
  7  0x00007fff896c0f44 ffi_call_unix64 (in libffi.dylib)
Abort trap: 6
```
### Command

```
/usr/bin/pod install
```

### Report

* What did you do?
Run 'pod install' after installing the Xcode 7.0 beta 2 and using this xcode for server
* What did you expect to happen?
Cocoapods to update all pods in my settings successfully

* What happened instead?
server bot stops with errors

### Stack

```
   CocoaPods : 0.37.2
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.0.14
        Host : Mac OS X 10.10.3 (14D136)
       Xcode : 7.0 (7A121l)
         Git : git version 2.3.7 (Apple Git-57)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ ad7d388e4a51617bab6c8269c81f66466a8eaa18
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-trunk   : 0.6.1
cocoapods-try     : 0.4.5
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, :deployment_target => '7.0'
workspace './Aviasales iOS Apps.xcworkspace'
inhibit_all_warnings!

link_with ['aviasales', 'jetradar', 'tests']

pod 'AppsFlyer-SDK',            '~> 2.5'
pod 'AutoCoding',               '~> 2.2'
pod 'BZipCompression',          '~> 1.0',       :inhibit_warnings => true
pod 'CrashlyticsFramework',     '~> 2.2'
pod 'Facebook-iOS-SDK',         '~> 3.14',      :inhibit_warnings => true
pod 'FlurrySDK',                '~> 5.0'
pod 'FXBlurView',               '~> 1.6'
pod 'FXPageControl',            '~> 1.3'
pod 'GoogleConversionTracking', '~> 3.0'
pod 'GoogleTagManager',         '~> 3.09'
pod 'GRMustache',               '~> 7.0',       :inhibit_warnings => true
pod 'JVFloatLabeledTextField',  '~> 1.0'
pod 'MagicalRecord',            '~> 2.2',       :inhibit_warnings => true
pod 'MKMapView-ZoomLevel',      '~> 1.1'
pod 'MMDrawerController',       '~> 0.5'
pod 'NMRangeSlider',            '~> 1.2'
pod 'NSURL+ParseQuery',         '~> 0.1'
pod 'OCMapView',                '~> 0.1',       :inhibit_warnings => true
pod 'OCRSDKClient',             '~> 0.2'
pod 'Reachability',             '~> 3.1'
pod 'SDWebImage',               '~> 3.7'
pod 'Smartling.i18n',           '~> 1.0'
pod 'UIDevice-Hardware',        '~> 0.1'
pod 'RMStore',                  '~> 0.7'
#pod 'RMStore/AppReceiptVerificator','~> 0.7'
pod 'YandexSpeechKit',          '~> 2.2'
pod 'CCHDarwinNotificationCenter', '~> 1.0'

target :speech_kit do
    link_with ['aviasales']
    pod 'YandexSpeechKit',          '~> 2.2'
end

target 'tests' do
    pod 'OCMock', '~> 3.0'
    pod 'OHHTTPStubs', '~> 3.1'
    pod 'FBSnapshotTestCase', '~> 1.5'
end

target 'aviasaleswidget', :exclusive => true do
    pod 'AutoCoding',                   '~> 2.2'
    pod 'Reachability',                 '~> 3.1'
    pod 'Smartling.i18n',               '~> 1.0'
    pod 'CCHDarwinNotificationCenter',  '~> 1.0'
end

target 'AviasalesWatchKitExtension', :exclusive => true do
    pod 'Smartling.i18n',               '~> 1.0'
    pod 'FXBlurView',                   '~> 1.6'
    pod 'CCHDarwinNotificationCenter',  '~> 1.0'
end

post_install do |installer|
    installer.project.targets.each do |target|
        folder_path = "Pods/Target\\ Support\\ Files/#{target.name}/#{target.name}"
        
        %x~ if [ -f #{folder_path}-resources.sh ];
        then
        
        sed '/WRAPPER_EXTENSION/,/fi\\n/d' #{folder_path}-resources.sh > #{folder_path}-resources.sh.temp;
        sed '/*.xcassets)/,/;;/d' #{folder_path}-resources.sh.temp > #{folder_path}-resources.sh;
        rm #{folder_path}-resources.sh.temp;
        
        fi ~
        
        
        
    end
end
```

### Error

```
SignalException - SIGTERM
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/executable.rb:86:in `value'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/executable.rb:86:in `block in popen3'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open3.rb:217:in `popen_run'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open3.rb:99:in `popen3'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/executable.rb:82:in `popen3'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/executable.rb:66:in `execute_command'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/executable.rb:27:in `block in executable'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/sources_manager.rb:215:in `block (3 levels) in update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/sources_manager.rb:213:in `chdir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/sources_manager.rb:213:in `block (2 levels) in update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/sources_manager.rb:212:in `block in update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/sources_manager.rb:211:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/sources_manager.rb:211:in `update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer/analyzer.rb:184:in `block (2 levels) in update_repositories_if_needed'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer/analyzer.rb:182:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer/analyzer.rb:182:in `block in update_repositories_if_needed'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer/analyzer.rb:181:in `update_repositories_if_needed'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer/analyzer.rb:55:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer.rb:196:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer.rb:114:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer.rb:113:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer.rb:93:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/command.rb:46:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

**Comment by neonichu** [comment]
This is a know issue, see #275

**Comment by glassoff** [comment]
@neonichu I do not understand what is the relation to this problem and what should I do

**Comment by alloy** [comment]
@glassoff He probably meant https://github.com/CocoaPods/Xcodeproj/pull/275

**Comment by neonichu** [comment]
Oh right, sorry - thanks for clearing this up, @alloy :+1:

**Comment by jtdavid** [comment]
I'm facing the same issue... what should I do in this case? Build the last CocoaPods/Xcodeproj and install it?

**Comment by neonichu** [comment]
@jtdavid you just need the latest Xcodeproj, no changes to CocoaPods are required

**Comment by jtdavid** [comment]
@neonichu Thanks! Actually I'm able to pod install without any errors if I use terminal but during the xcode bot execution (_xcsbuildd) I'm still getting the issue while doing 'pod setup' for the first time:

### Error

```
SignalException - SIGTERM
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/executable.rb:86:in `value'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/executable.rb:86:in `block in popen3'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open3.rb:217:in `popen_run'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open3.rb:99:in `popen3'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/executable.rb:82:in `popen3'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/executable.rb:66:in `execute_command'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/executable.rb:27:in `block in executable'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/command/repo/add.rb:44:in `block (2 levels) in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/command/repo/add.rb:41:in `chdir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/command/repo/add.rb:41:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/command/repo/add.rb:39:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/command/setup.rb:84:in `add_master_repo'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/command/setup.rb:40:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/command/setup.rb:32:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/command.rb:46:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

**Comment by neonichu** [comment]
@jtdavid that looks like a different issue - could you run `pod setup --verbose` and then see if the command that fails also does so outside of CocoaPods?

**Comment by jtdavid** [comment]
It runs perfectly. Only crashes within bot environment...

**Comment by jtdavid** [comment]
I've already reset the xcode server and still the same. I have a private git repo in my podfile specs but it doesn't seem to be related...

**Comment by jtdavid** [comment]
SIGTERM is a generic ruby error? We don't have much detail within bot log but in terminal we can grab more detail in gem error. Why is this?

**Comment by neonichu** [comment]
`SIGTERM` is a signal which apparently in this case an external process executed by CP receives. Did `--verbose` tell you which executable is run?

**Comment by jtdavid** [comment]
@neonichu That's the weird point. When I connect to the OS X Server through SSH, everything goes seamlessly (pod setup, updade or install). Running those commands in a trigger on the new Xcode 7 config at OS X Server results in the above output (with --verbose), though.

Any idea so I can try some new approachs?

**Comment by jtdavid** [comment]
@glassoff you only got the SIGTERM output in your pre integration script, right? The 'ASSERTION FAILURE' you found it when running it in a terminal or was part of your bot log output? Just asking cause I'm only getting that in the terminal before installing the latestest CP/Xcodeproj...
