### ISSUE TITLE
Pod install/update or setup under Xcode Bots with Xcode 7 beta (1 or 2) is not working.

### ISSUE THREAD

**Issue by jtdavid** [CocoaPods/CocoaPods#3745]
Can anyone has experienced with an issue similar to this one? 

Since I've changed to Xcode 7 on my OS X Server I can't pod install within a bot pre-integration script. Curiously, I can do it in the terminal with any user account different from the _xcsbuildd user (the xcode bots background user).

This turns out to be a blocker on my CI pipeline to take advantage of all new features of Xcode 7.

Any help will be much appreciated.

The report below is my bot pre-integration script output.

### Command

```
/usr/bin/pod install --verbose
```

### Report

* What did you do?
  
  I've added an before integration script trigger to Xcode Bot as shown below as I usually do with Xcode 6.3 running on server.

``` 
export LANG=en_US.UTF-8

if [ ! -e "$HOME/.cocoapods/repos" ]
then
    pod setup
fi

cd sample-ios

if [ -e "Pods" ]
then
    pod update --verbose
else
    pod install --verbose
fi

cd ..
```
* What did you expect to happen?

To do a simple pod install / update to my dependencies.

* What happened instead?

The Bot returns de following error. I can actually do a pod install / update in the terminal with a user different from _xcsbuildd (the one used in background by xcode bots).

### Stack

```
   CocoaPods : 0.37.2
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.0.14
        Host : Mac OS X 10.10.3 (14D2134)
       Xcode : 7.0 (7A121l)
         Git : git version 2.3.7 (Apple Git-57)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : sample - git@github.com:Sample/Specs.git @ 51204a387e1659e60b576e1c5193d0eee7f04719
               master - https://github.com/CocoaPods/Specs.git @ fb605132173ff354945aabeca98b3457b5408d60
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-trunk   : 0.6.1
cocoapods-try     : 0.4.5
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
source 'git@github.com:Sample/Specs.git'

platform :ios, :deployment_target => '8.0'
inhibit_all_warnings!

use_frameworks!

xcodeproj 'SampleShop'

pod 'Sample', '~> 0.4.0'

post_install do |installer|
    installer.project.targets.each do |target|
        puts target.name
        target.build_configurations.each do |config|
            config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
        end
    end
end
```

### Error

```
SignalException - SIGTERM
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/executable.rb:86:in `value'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/executable.rb:86:in `block in popen3'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open3.rb:217:in `popen_run'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open3.rb:99:in `popen3'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/executable.rb:82:in `popen3'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/executable.rb:66:in `execute_command'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/executable.rb:27:in `block in executable'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/sources_manager.rb:215:in `block (3 levels) in update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/sources_manager.rb:213:in `chdir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/sources_manager.rb:213:in `block (2 levels) in update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/sources_manager.rb:212:in `block in update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/sources_manager.rb:211:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/sources_manager.rb:211:in `update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer/analyzer.rb:184:in `block (2 levels) in update_repositories_if_needed'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer/analyzer.rb:182:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer/analyzer.rb:182:in `block in update_repositories_if_needed'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer/analyzer.rb:181:in `update_repositories_if_needed'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer/analyzer.rb:55:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer.rb:196:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer.rb:114:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer.rb:113:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer.rb:93:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/command.rb:46:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

**Comment by neonichu** [comment]
As asked [here](https://github.com/CocoaPods/CocoaPods/issues/3740#issuecomment-116076901), please share your `--verbose` output, so that we can find out which command is actually failing.

**Comment by jtdavid** [comment]
Thanks for the reply @neonichu. That's everything I got from a `pod update --verbose`.

Update all pods
  Preparing

Analyzing dependencies

Updating spec repositories

Creating shallow clone of spec repo `master` from `https://github.com/CocoaPods/Specs.git`
  $ /Applications/Xcode-beta.app/Contents/Developer/usr/bin/git clone https://github.com/CocoaPods/Specs.git master --depth=1

### Command

```
/usr/bin/pod update --verbose
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 0.37.2
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.0.14
        Host : Mac OS X 10.10.3 (14D2134)
       Xcode : 7.0 (7A121l)
         Git : git version 2.3.7 (Apple Git-57)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : 
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-trunk   : 0.6.1
cocoapods-try     : 0.4.5
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
source 'git@github.com:Farfetch/Specs.git'

platform :ios, :deployment_target => '8.0'
inhibit_all_warnings!

use_frameworks!

xcodeproj 'FarfetchShop'

pod 'Farfetch', '0.4.0'

post_install do |installer|
    installer.project.targets.each do |target|
        puts target.name
        target.build_configurations.each do |config|
            config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
        end
    end
end
```

### Error

```
SignalException - SIGTERM
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/executable.rb:86:in `value'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/executable.rb:86:in `block in popen3'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open3.rb:217:in `popen_run'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open3.rb:99:in `popen3'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/executable.rb:82:in `popen3'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/executable.rb:66:in `execute_command'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/executable.rb:27:in `block in executable'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/command/repo/add.rb:44:in `block (2 levels) in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/command/repo/add.rb:41:in `chdir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/command/repo/add.rb:41:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/command/repo/add.rb:39:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/sources_manager.rb:46:in `find_or_create_source_with_url'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer/analyzer.rb:520:in `block in sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer/analyzer.rb:519:in `map'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer/analyzer.rb:519:in `sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer/analyzer.rb:182:in `block in update_repositories_if_needed'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer/analyzer.rb:181:in `update_repositories_if_needed'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer/analyzer.rb:55:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer.rb:196:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer.rb:114:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer.rb:113:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer.rb:93:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/command/project.rb:155:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/command.rb:46:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

```
[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=SIGTERM&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

  Cloning into 'master'...
```


I did find that xcode bot is running a different environment comparing to the terminal's one, running `gem list --local`:

##Xcode bot
```
activesupport (4.2.1)
bigdecimal (1.2.0)
CFPropertyList (2.2.8)
claide (0.8.1)
cocoapods (0.37.2)
cocoapods-core (0.37.2)
cocoapods-downloader (0.9.0)
cocoapods-plugins (0.4.2)
cocoapods-trunk (0.6.1)
cocoapods-try (0.4.5)
colored (1.2)
escape (0.0.4)
fuzzy_match (2.0.4)
i18n (0.7.0)
io-console (0.4.2)
json (1.7.7)
libxml-ruby (2.6.0)
minitest (5.7.0, 4.3.2)
molinillo (0.2.3)
nap (0.8.0)
netrc (0.7.8)
nokogiri (1.5.6)
psych (2.0.0)
rake (0.9.6)
rdoc (4.0.0)
sqlite3 (1.3.7)
test-unit (2.0.0.0)
thread_safe (0.3.5)
tzinfo (1.2.2)
xcodeproj (0.24.2)
```

##Terminal
```
cocoapods (0.37.2)
cocoapods-core (0.37.2)
cocoapods-downloader (0.9.1)
cocoapods-plugins (0.4.2)
cocoapods-trunk (0.6.1)
cocoapods-try (0.4.5)
colored (1.2)
..
xcodeproj (0.24.3)
```

The terminal is using xcodeproj (0.24.3)...

**Comment by jtdavid** [comment]
Basically I can't control gems installed in the background user /var/_xcsbuildd (used for xcode bots and created automatically by xcode server).

I've noticed that under `/var/_xcsbuildd/.gem/specs/rubygems.org%443/quick/Marshal.4.8` were:

cocoapods-0.37.2.gemspec
cocoapods-core-0.37.2.gemspec
claide-0.8.1.gemspec

How? I don't really know why and how this gemspecs dropped there...

**Comment by segiddins** [comment]
@jtdavid those gemspecs I believe are just artifacts of rubygems' installation process. And xcodeproj 0.24.2 vs 0.24.3 would make a difference in running `git clone`. Is it at all possible that bots don't like you spawning subprocesses?

**Comment by jtdavid** [comment]
@segiddins, regarding spawning subprocesses... with Xcode 6.3.2 within xcode server everything went seamlessly. Are we having a different behaviour with Xcode 7? That would be really bad.. That's the whole idea of pre and post scripts triggers in Xcode bots...

**Comment by neonichu** [comment]
so what happens if you directly call `/Applications/Xcode-beta.app/Contents/Developer/usr/bin/git clone https://github.com/CocoaPods/Specs.git master --depth=1` from your script running via bots?

**Comment by jtdavid** [comment]
### With Xcode 7 beta 2
(/Applications/Xcode-beta.app/Contents/Developer/usr/bin/git clone https://github.com/CocoaPods/Specs.git master --depth=1)
```
Cloning into 'master'...
Trigger script exited with code: 15 Cloning into 'master'...
```

### With Xcode 6.3.2
(/Applications/Xcode.app/Contents/Developer/usr/bin/git clone https://github.com/CocoaPods/Specs.git master --depth=1)
```
Cloning into 'master'...
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

**Comment by neonichu** [comment]
OK, so you're getting the `SIGTERM` regardless of CocoaPods when using Xcode 7. Sounds more like a case for `http://bugreport.apple.com/` :satellite:

**Comment by jtdavid** [comment]
@segiddins and @segiddins, I will fill in a radar. You're both right in my opinion. Seems like the new environment are ill-prepared for subprocess (like cocoapods). I will keep you posted about it.

**Comment by jtdavid** [comment]
@segiddins, @neonichu... a small heads up. Just adding & (send execution to a background process) solves the issue.
So basically:

```pod install &```

**Comment by czechboy0** [comment]
@jtdavid Wouldn't sending it to another process basically make it a race condition? If the script doesn't wait for `pod install` to finish, Xcode Server might start building your code before it pods have finished. This doesn't sound like a fix to me.

**Comment by yakubbaev** [comment]
@czechboy0 Have you found workaround for this?

**Comment by czechboy0** [comment]
Everything has worked fine for me for a while. Pre-built scripts work as expected in Xcode Server from my experience.
