### ISSUE TITLE
`pod install` fails due to cocoapod-stats

### ISSUE THREAD

**Issue by zadr** [CocoaPods/CocoaPods#3848]
### Command

```
/usr/bin/pod install
```

### Report

* What did you do?
ran `pod install`

* What did you expect to happen?
my pod to be updated

* What happened instead?
my pod was not updated

### Stack

```
   CocoaPods : 0.38.0
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.0.14
        Host : Mac OS X 10.10.4 (14E46)
       Xcode : 6.4 (6E35b)
         Git : git version 2.3.2 (Apple Git-55)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ d2e9a880c6ee3d0250bf1009c5724f1057d7ee33
               Medium - git@github.com:Medium/medium-pod-specs.git @ 2f20000ae3e4d6e1c9852dd50dcf74ef9d0b87ad
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-stats   : 0.5.3
cocoapods-trunk   : 0.6.1
cocoapods-try     : 0.4.5
```

### Podfile

```ruby
platform :ios, '7.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'git@github.com:Medium/medium-pod-specs.git'

inhibit_all_warnings!

xcodeproj 'hangtag.xcodeproj'

pod 'CocoaLumberjack', '~> 1.8.1'
pod 'Facebook-iOS-SDK', '~> 4.0'
pod 'Google/SignIn', '~> 1.0.7'
pod 'Groot', '~> 0.1.1'
pod 'KMCGeigerCounter', '~> 0.2.0'
pod 'Mantle', '~> 1.5.4'
pod 'MBProgressHUD', '~> 0.9'
pod 'Reachability', '~> 3.0'
pod 'SDWebImage', '3.7.2'
pod 'varys', '~> 0.3.0'
pod 'UrbanAirship-iOS-SDK', '~> 6.1.2'
pod 'WYPopoverController', git: 'git@custom.repo', commit: '658842cb46263bcf71c5ad71effb3e51210a2e0f'
pod 'PSTAlertController', '~> 1.1.0'
pod 'KVOController', '~> 1.0.3'
pod 'FormatterKit/TimeIntervalFormatter', '~> 1.8.0'
pod 'KSDeferred', git: 'git@github.com:kseebaldt/deferred', commit: '91e43a39b724897affa20ae5db42a7ac23ef3d83'

target 'Tests' do
  pod 'OCMock', '~> 3.1.2'
  pod 'PivotalCoreKit/UIKit/SpecHelper/Extensions'
  pod 'PivotalCoreKit/UIKit/SpecHelper/Stubs'
end

prepare_command = <<-CMD
    SUPPORTED_LOCALES="['base', 'en']"
    find . -type d ! -name "*$SUPPORTED_LOCALES.lproj" | grep .lproj | xargs rm -rf
CMD
```

### Error

```
NoMethodError - undefined method `include?' for nil:NilClass
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.26.2/lib/xcodeproj/project/object/native_target.rb:92:in `platform_name'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-stats-0.5.3/lib/cocoapods_stats/target_mapper.rb:36:in `block (2 levels) in pods_from_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-stats-0.5.3/lib/cocoapods_stats/target_mapper.rb:27:in `map'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-stats-0.5.3/lib/cocoapods_stats/target_mapper.rb:27:in `block in pods_from_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-stats-0.5.3/lib/cocoapods_stats/target_mapper.rb:9:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-stats-0.5.3/lib/cocoapods_stats/target_mapper.rb:9:in `flat_map'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-stats-0.5.3/lib/cocoapods_stats/target_mapper.rb:9:in `pods_from_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-stats-0.5.3/lib/cocoapods_plugin.rb:31:in `block (2 levels) in <module:CocoaPodsStats>'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/user_interface.rb:80:in `titled_section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-stats-0.5.3/lib/cocoapods_plugin.rb:27:in `block in <module:CocoaPodsStats>'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/hooks_manager.rb:115:in `call'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/hooks_manager.rb:115:in `block (3 levels) in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/user_interface.rb:140:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/hooks_manager.rb:111:in `block (2 levels) in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/hooks_manager.rb:109:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/hooks_manager.rb:109:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/user_interface.rb:140:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/hooks_manager.rb:108:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/installer.rb:448:in `run_plugins_post_install_hooks'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/installer.rb:440:in `perform_post_install_actions'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/installer.rb:111:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

**Comment by segiddins** [comment]
@zadr this should be fixed in 0.38.2? Please reopen if it isn't.
