### ISSUE TITLE
[0.38] [Regression] RuntimeError - [Xcodeproj] Generated duplicate UUIDs

### ISSUE THREAD

**Issue by chrisballinger** [CocoaPods/CocoaPods#3850]
https://github.com/ChatSecure/XMPPFramework/blob/release/XMPPFramework.podspec.json

Worked fine for 0.37. I'm investigating simplifying the podspec to see if that fixes the issue.

```
RuntimeError - [Xcodeproj] Generated duplicate UUIDs:

PBXFileReference -- /mainGroup/children/children:children:|,displayName:|,isa:|,name:|,path:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,path:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,path:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,path:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,path:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,path:|,sourceTree:|,,displayName:Development Pods,isa:PBXGroup,name:Development Pods,sourceTree:<group>,/children/children:children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,path:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,displayName:XMPPFramework,isa:PBXGroup,name:XMPPFramework,path:../Submodules/XMPPFramework,sourceTree:<group>,/children/children:children:|,displayName:|,isa:|,name:|,path:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,path:|,sourceTree:|,,displayName:Resources,isa:PBXGroup,name:Resources,sourceTree:<group>,/children/children:children:|,displayName:|,isa:|,name:|,path:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,path:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,path:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,path:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,path:|,sourceTree:|,,displayName:Extensions,isa:PBXGroup,name:Extensions,path:Extensions,sourceTree:<group>,/children/children:children:|,displayName:|,isa:|,name:|,path:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,path:|,sourceTree:|,,displayName:XEP-0045,isa:PBXGroup,name:XEP-0045,path:XEP-0045,sourceTree:<group>,/children/children:children:|,currentVersion:|,displayName:|,isa:|,path:|,sourceTree:|,versionGroupType:|,,displayName:CoreDataStorage,isa:PBXGroup,name:CoreDataStorage,path:CoreDataStorage,sourceTree:<group>,/children/children:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,currentVersion:displayName:XMPPRoom.xcdatamodel,includeInIndex:1,isa:PBXFileReference,lastKnownFileType:wrapper.xcdatamodel,path:XMPPRoom.xcdatamodel,sourceTree:<group>,,displayName:XMPPRoom.xcdatamodeld,isa:XCVersionGroup,path:XMPPRoom.xcdatamodeld,sourceTree:<group>,versionGroupType:wrapper.xcdatamodel,/children/displayName:XMPPRoom.xcdatamodel,includeInIndex:1,isa:PBXFileReference,lastKnownFileType:wrapper.xcdatamodel,path:XMPPRoom.xcdatamodel,sourceTree:<group>,
PBXFileReference -- /mainGroup/children/children:children:|,displayName:|,isa:|,name:|,path:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,path:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,path:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,path:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,path:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,path:|,sourceTree:|,,displayName:Development Pods,isa:PBXGroup,name:Development Pods,sourceTree:<group>,/children/children:children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,path:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,displayName:XMPPFramework,isa:PBXGroup,name:XMPPFramework,path:../Submodules/XMPPFramework,sourceTree:<group>,/children/children:children:|,displayName:|,isa:|,name:|,path:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,path:|,sourceTree:|,,displayName:Resources,isa:PBXGroup,name:Resources,sourceTree:<group>,/children/children:children:|,displayName:|,isa:|,name:|,path:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,path:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,path:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,path:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,path:|,sourceTree:|,,displayName:Extensions,isa:PBXGroup,name:Extensions,path:Extensions,sourceTree:<group>,/children/children:children:|,displayName:|,isa:|,name:|,path:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,path:|,sourceTree:|,,displayName:XEP-0045,isa:PBXGroup,name:XEP-0045,path:XEP-0045,sourceTree:<group>,/children/children:children:|,currentVersion:|,displayName:|,isa:|,path:|,sourceTree:|,versionGroupType:|,,displayName:HybridStorage,isa:PBXGroup,name:HybridStorage,path:HybridStorage,sourceTree:<group>,/children/children:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,currentVersion:displayName:XMPPRoomHybrid.xcdatamodel,includeInIndex:1,isa:PBXFileReference,lastKnownFileType:wrapper.xcdatamodel,path:XMPPRoomHybrid.xcdatamodel,sourceTree:<group>,,displayName:XMPPRoomHybrid.xcdatamodeld,isa:XCVersionGroup,path:XMPPRoomHybrid.xcdatamodeld,sourceTree:<group>,versionGroupType:wrapper.xcdatamodel,/children/displayName:XMPPRoomHybrid.xcdatamodel,includeInIndex:1,isa:PBXFileReference,lastKnownFileType:wrapper.xcdatamodel,path:XMPPRoomHybrid.xcdatamodel,sourceTree:<group>,
PBXFileReference -- /mainGroup/children/children:children:|,displayName:|,isa:|,name:|,path:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,path:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,path:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,path:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,path:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,path:|,sourceTree:|,,displayName:Development Pods,isa:PBXGroup,name:Development Pods,sourceTree:<group>,/children/children:children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,path:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,displayName:XMPPFramework,isa:PBXGroup,name:XMPPFramework,path:../Submodules/XMPPFramework,sourceTree:<group>,/children/children:children:|,displayName:|,isa:|,name:|,path:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,path:|,sourceTree:|,,displayName:Resources,isa:PBXGroup,name:Resources,sourceTree:<group>,/children/children:children:|,displayName:|,isa:|,name:|,path:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,path:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,path:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,path:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,path:|,sourceTree:|,,displayName:Extensions,isa:PBXGroup,name:Extensions,path:Extensions,sourceTree:<group>,/children/children:children:|,displayName:|,isa:|,name:|,path:|,sourceTree:|,,displayName:XEP-0054,isa:PBXGroup,name:XEP-0054,path:XEP-0054,sourceTree:<group>,/children/children:children:|,currentVersion:|,displayName:|,isa:|,path:|,sourceTree:|,versionGroupType:|,,displayName:CoreDataStorage,isa:PBXGroup,name:CoreDataStorage,path:CoreDataStorage,sourceTree:<group>,/children/children:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,currentVersion:displayName:XMPPvCard.xcdatamodel,includeInIndex:1,isa:PBXFileReference,lastKnownFileType:wrapper.xcdatamodel,path:XMPPvCard.xcdatamodel,sourceTree:<group>,,displayName:XMPPvCard.xcdatamodeld,isa:XCVersionGroup,path:XMPPvCard.xcdatamodeld,sourceTree:<group>,versionGroupType:wrapper.xcdatamodel,/children/displayName:XMPPvCard.xcdatamodel,includeInIndex:1,isa:PBXFileReference,lastKnownFileType:wrapper.xcdatamodel,path:XMPPvCard.xcdatamodel,sourceTree:<group>,
PBXFileReference -- /mainGroup/children/children:children:|,displayName:|,isa:|,name:|,path:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,path:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,path:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,path:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,path:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,path:|,sourceTree:|,,displayName:Development Pods,isa:PBXGroup,name:Development Pods,sourceTree:<group>,/children/children:children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,path:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,sourceTree:|,,displayName:XMPPFramework,isa:PBXGroup,name:XMPPFramework,path:../Submodules/XMPPFramework,sourceTree:<group>,/children/children:children:|,displayName:|,isa:|,name:|,path:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,path:|,sourceTree:|,,displayName:Resources,isa:PBXGroup,name:Resources,sourceTree:<group>,/children/children:children:|,displayName:|,isa:|,name:|,path:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,path:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,path:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,path:|,sourceTree:|,,children:|,displayName:|,isa:|,name:|,path:|,sourceTree:|,,displayName:Extensions,isa:PBXGroup,name:Extensions,path:Extensions,sourceTree:<group>,/children/children:children:|,displayName:|,isa:|,name:|,path:|,sourceTree:|,,displayName:XEP-0136,isa:PBXGroup,name:XEP-0136,path:XEP-0136,sourceTree:<group>,/children/children:children:|,currentVersion:|,displayName:|,isa:|,path:|,sourceTree:|,versionGroupType:|,,displayName:CoreDataStorage,isa:PBXGroup,name:CoreDataStorage,path:CoreDataStorage,sourceTree:<group>,/children/children:displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,displayName:|,includeInIndex:|,isa:|,lastKnownFileType:|,path:|,sourceTree:|,,currentVersion:displayName:XMPPMessageArchiving.xcdatamodel,includeInIndex:1,isa:PBXFileReference,lastKnownFileType:wrapper.xcdatamodel,path:XMPPMessageArchiving.xcdatamodel,sourceTree:<group>,,displayName:XMPPMessageArchiving.xcdatamodeld,isa:XCVersionGroup,path:XMPPMessageArchiving.xcdatamodeld,sourceTree:<group>,versionGroupType:wrapper.xcdatamodel,/children/displayName:XMPPMessageArchiving.xcdatamodel,includeInIndex:1,isa:PBXFileReference,lastKnownFileType:wrapper.xcdatamodel,path:XMPPMessageArchiving.xcdatamodel,sourceTree:<group>,
/usr/local/lib/ruby/gems/2.0.0/gems/xcodeproj-0.26.2/lib/xcodeproj/project/uuid_generator.rb:24:in `verify_no_duplicates!'
/usr/local/lib/ruby/gems/2.0.0/gems/xcodeproj-0.26.2/lib/xcodeproj/project/uuid_generator.rb:14:in `generate!'
/usr/local/lib/ruby/gems/2.0.0/gems/xcodeproj-0.26.2/lib/xcodeproj/project.rb:337:in `predictabilize_uuids'
/usr/local/lib/ruby/gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/installer.rb:650:in `block in write_pod_project'
/usr/local/lib/ruby/gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/user_interface.rb:140:in `message'
/usr/local/lib/ruby/gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/installer.rb:645:in `write_pod_project'
/usr/local/lib/ruby/gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/installer.rb:155:in `block in generate_pods_project'
/usr/local/lib/ruby/gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/user_interface.rb:59:in `section'
/usr/local/lib/ruby/gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/installer.rb:149:in `generate_pods_project'
/usr/local/lib/ruby/gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/installer.rb:109:in `install!'
/usr/local/lib/ruby/gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/usr/local/lib/ruby/gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/command/project.rb:156:in `run'
/usr/local/lib/ruby/gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/usr/local/lib/ruby/gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/command.rb:48:in `run'
/usr/local/lib/ruby/gems/2.0.0/gems/cocoapods-0.38.0/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by segiddins** [comment]
Thanks! In the meantime, you can set the environment variable `COCOAPODS_DISABLE_DETERMINISTIC_UUIDS` to work around the exception

**Comment by chrisballinger** [comment]
@segiddins Thank you!

**Comment by pnc** [comment]
@chrisballinger Here's a minimal repro (at least for one particular trigger of this error) where two headers (one private and one public) have the same name, but are in different directories in the pod source. 

https://github.com/pnc/cocoapods-duplicate

There's also a patch for `uuid_generator.rb` in the README that catches the error earlier and gives you an opportunity to set a debugger breakpoint.

If you (or someone else) investigates and it looks like something totally different from this issue (e.g., it's related specifically to `xcdatamodel`s, I can make another issue.

Sorry this isn't a breaking test—it's late Friday and I can't get the `json` gem to build for the `xcodeproj` gem. 😁

**Comment by pnc** [comment]
This commit has the specific changes on top of a plain `pod lib create dupe` to reproduce the error:

    https://github.com/pnc/cocoapods-duplicate/commit/38851f34c816906026bbdb270778130a62703854
