### ISSUE TITLE
Cocoapods 0.38.0 Can't Satisfy Requirements

### ISSUE THREAD

**Issue by hirad** [CocoaPods/CocoaPods#3851]
I just upgraded my cocoapods gem from 0.35 to 0.38 and now I'm trying to do a `pod install` in a new all Swift project and I keep getting `Unable to satisfy the following requirements`. This is my podfile: 

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
inhibit_all_warnings!
xcodeproj 'CnDr'

pod 'KeychainAccess', '~> 1.2.0'
pod "Alamofire", '~> 1.2.1'
pod "SVProgressHUD", '~> 1.1.3'
```

I haven't found any other issues about this. Am I missing something?

**Comment by segiddins** [comment]
Can you please paste the full output of `pod install --verbose` ?

**Comment by hirad** [comment]
```
  Preparing

Updating local specs repositories

Updating spec repo `master`
  $ /usr/local/bin/git pull --ff-only
  Already up-to-date.

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods`: (``)

Resolving dependencies of `Podfile`
[!] Unable to satisfy the following requirements:

- `KeychainAccess (= 1.2.0)` required by `Podfile`

/Users/hiradmotamed/.rvm/gems/ruby-2.1.4/gems/cocoapods-0.38.0/lib/cocoapods/resolver.rb:388:in `handle_resolver_error'
/Users/hiradmotamed/.rvm/gems/ruby-2.1.4/gems/cocoapods-0.38.0/lib/cocoapods/resolver.rb:69:in `rescue in resolve'
/Users/hiradmotamed/.rvm/gems/ruby-2.1.4/gems/cocoapods-0.38.0/lib/cocoapods/resolver.rb:56:in `resolve'
/Users/hiradmotamed/.rvm/gems/ruby-2.1.4/gems/cocoapods-0.38.0/lib/cocoapods/installer/analyzer.rb:535:in `block in resolve_dependencies'
/Users/hiradmotamed/.rvm/gems/ruby-2.1.4/gems/cocoapods-0.38.0/lib/cocoapods/user_interface.rb:59:in `section'
/Users/hiradmotamed/.rvm/gems/ruby-2.1.4/gems/cocoapods-0.38.0/lib/cocoapods/installer/analyzer.rb:533:in `resolve_dependencies'
/Users/hiradmotamed/.rvm/gems/ruby-2.1.4/gems/cocoapods-0.38.0/lib/cocoapods/installer/analyzer.rb:70:in `analyze'
/Users/hiradmotamed/.rvm/gems/ruby-2.1.4/gems/cocoapods-0.38.0/lib/cocoapods/installer.rb:209:in `analyze'
/Users/hiradmotamed/.rvm/gems/ruby-2.1.4/gems/cocoapods-0.38.0/lib/cocoapods/installer.rb:131:in `block in resolve_dependencies'
/Users/hiradmotamed/.rvm/gems/ruby-2.1.4/gems/cocoapods-0.38.0/lib/cocoapods/user_interface.rb:59:in `section'
/Users/hiradmotamed/.rvm/gems/ruby-2.1.4/gems/cocoapods-0.38.0/lib/cocoapods/installer.rb:130:in `resolve_dependencies'
/Users/hiradmotamed/.rvm/gems/ruby-2.1.4/gems/cocoapods-0.38.0/lib/cocoapods/installer.rb:103:in `install!'
/Users/hiradmotamed/.rvm/gems/ruby-2.1.4/gems/cocoapods-0.38.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/hiradmotamed/.rvm/gems/ruby-2.1.4/gems/cocoapods-0.38.0/lib/cocoapods/command/project.rb:101:in `run'
/Users/hiradmotamed/.rvm/gems/ruby-2.1.4/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Users/hiradmotamed/.rvm/gems/ruby-2.1.4/gems/cocoapods-0.38.0/lib/cocoapods/command.rb:48:in `run'
/Users/hiradmotamed/.rvm/gems/ruby-2.1.4/gems/cocoapods-0.38.0/bin/pod:44:in `<top (required)>'
/Users/hiradmotamed/.rvm/gems/ruby-2.1.4/bin/pod:23:in `load'
/Users/hiradmotamed/.rvm/gems/ruby-2.1.4/bin/pod:23:in `<main>'
/Users/hiradmotamed/.rvm/gems/ruby-2.1.4/bin/ruby_executable_hooks:15:in `eval'
/Users/hiradmotamed/.rvm/gems/ruby-2.1.4/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by segiddins** [comment]
Hm odd. What's your Podfile?

**Comment by hirad** [comment]
My podfile was in the original post.

**Comment by segiddins** [comment]
My bad, missed that. So the issue here is that there are no versions of either `KeychainAccess` or `Alamofire` that are compatible with iOS 7 -- if you change the platform to iOS 8, it resolves fine.

**Comment by hirad** [comment]
Ah... thank you!

**Comment by i-schuetz** [comment]
Hi, I have a similar problem with my library, see https://github.com/i-schuetz/SwiftCharts/issues/22
(there is also the log from `pod install --verbose`)

I was able to fix it by adding 

```ruby
platform :ios, '8.0'
```

to the podfile but the target is 7.1, if I use 7.1 I get the same error. what's the problem?
