### ISSUE TITLE
When 'Pod install'  Error occur!

### ISSUE THREAD

**Issue by xingjun** [CocoaPods/CocoaPods#3861]
――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 0.37.2
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.0.14
        Host : Mac OS X 10.10.4 (14E46)
       Xcode : 6.4 (6E35b)
         Git : git version 2.3.2 (Apple Git-55)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ d9642a8d5c55342ca5e06e2e7b7efb87a69023ee
               mogujie-ios-team-cocoapods-official-specs-mirror - http://gitlab.mogujie.org/ios-team/cocoapods-official-specs-mirror.git @ fd0b93bdaee4a2eb60150889e3460ce75b5c0709
               mogujie-ios-team-mgjpodspecs - http://gitlab.mogujie.org/ios-team/mgjpodspecs.git @ d9f9278fdec92bcc07480ed08e226331071adf55
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-trunk   : 0.6.1
cocoapods-try     : 0.4.5
```

### Podfile

```ruby
#source 'https://github.com/CocoaPods/Specs.git'
source "http://gitlab.mogujie.org/ios-team/mgjpodspecs.git"
source 'http://gitlab.mogujie.org/ios-team/cocoapods-official-specs-mirror.git'
platform = :osx, '10.8'
pod 'FMDB', '~> 2.3'
pod 'AFNetworking', '~> 2.5.0'
pod 'ProtocolBuffers', '~> 1.9.4'
pod 'IMNetworkLib', '~>0.2
.0'
```

### Error

```
ArgumentError - Illformed requirement `"~>0.2\n.0"`
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.37.2/lib/cocoapods-core/requirement.rb:61:in `parse'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.37.2/lib/cocoapods-core/vendor/requirement.rb:132:in `block in initialize'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.37.2/lib/cocoapods-core/vendor/requirement.rb:132:in `map!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.37.2/lib/cocoapods-core/vendor/requirement.rb:132:in `initialize'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.37.2/lib/cocoapods-core/requirement.rb:32:in `new'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.37.2/lib/cocoapods-core/requirement.rb:32:in `create'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.37.2/lib/cocoapods-core/dependency.rb:92:in `initialize'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.37.2/lib/cocoapods-core/podfile/target_definition.rb:648:in `new'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.37.2/lib/cocoapods-core/podfile/target_definition.rb:648:in `block in pod_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.37.2/lib/cocoapods-core/podfile/target_definition.rb:644:in `map'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.37.2/lib/cocoapods-core/podfile/target_definition.rb:644:in `pod_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.37.2/lib/cocoapods-core/podfile/target_definition.rb:87:in `non_inherited_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.37.2/lib/cocoapods-core/podfile/target_definition.rb:77:in `dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.37.2/lib/cocoapods-core/podfile.rb:89:in `map'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.37.2/lib/cocoapods-core/podfile.rb:89:in `dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.37.2/lib/cocoapods-core/lockfile.rb:262:in `detect_changes_with_podfile'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer/analyzer.rb:165:in `block in generate_podfile_state'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer/analyzer.rb:164:in `generate_podfile_state'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer/analyzer.rb:58:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer.rb:196:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer.rb:114:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer.rb:113:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer.rb:93:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.8.2/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/command.rb:46:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

**Comment by segiddins** [comment]
You need to get rid of the newline in the line `pod 'IMNetworkLib', '~>0.2.0'`.

**Comment by xingjun** [comment]
Thank you～，I find this new line

**Comment by xingjun** [comment]
Thank you,
	I find this mistake,as you see,the ‘new line’  ^_^
－－－－－－－－－－－－－－－－－－－－－－－－－
杏菌
蘑菇街研发部-平台技术-客户端  http://www.mogujie.com <http://www.mogujie.com/>
Mobile: 18500048073
Email:   xingjun@mogujie.com <mailto:shanzhu@mogujie.com>
Add:     杭州市西湖区古墩路99号浙商财富中心一号
