### ISSUE TITLE
Local podspecs not working correctly on 0.38.0

### ISSUE THREAD

**Issue by hfossli** [CocoaPods/CocoaPods#3863]
Did anything change between 0.37.0 and 0.38.0 when it comes to local podspecs? I'm not able to reproduce this in a smaller testproject.. Most of the pods mentioned here are private, sorry, but maybe some bells are ringing from the output here?

##### $ pod install --verbose
(version 0.38.0)
```
(...omitted)

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods`: (``)

Finding Podfile changes
  - ALERT
  - AgensLayoutEngine
  - Rhea

Fetching external sources
-> Fetching podspec for `ALERT` from `../../ALERT.podspec`
-> Fetching podspec for `AgensLayoutEngine` from `../../../ALE/AgensLayoutEngine.podspec`
-> Fetching podspec for `Rhea` from `../../../Rhea/Rhea.podspec`

Resolving dependencies of `Podfile`
[!] Unable to satisfy the following requirements:

- `AgensLayoutEngine (from `../../../ALE/AgensLayoutEngine.podspec`)` required by `Podfile`
- `AgensLayoutEngine (= 2.0)` required by `Podfile.lock`
- `AgensLayoutEngine (~> 2.0)` required by `ALERT (0.2)`

/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/resolver.rb:388:in `handle_resolver_error'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/resolver.rb:69:in `rescue in resolve'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/resolver.rb:56:in `resolve'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/installer/analyzer.rb:535:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/installer/analyzer.rb:533:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/installer/analyzer.rb:70:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/installer.rb:209:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/installer.rb:131:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/installer.rb:130:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/installer.rb:103:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

##### $ pod install --verbose
(version 0.37.0)
```
(...omitted)
Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods`: (``)

Finding Podfile changes
  - ALERT
  - AgensLayoutEngine
  - Rhea

Fetching external sources
-> Fetching podspec for `ALERT` from `../../ALERT.podspec`
-> Fetching podspec for `AgensLayoutEngine` from `../../../ALE/AgensLayoutEngine.podspec`
-> Fetching podspec for `Rhea` from `../../../Rhea/Rhea.podspec`

Resolving dependencies of `Podfile`
Starting resolution (2015-07-22 11:15:29 +0200)
Creating possibility state for ALERT (from `../../ALERT.podspec`) (1 remaining)
  Attempting to activate ALERT (0.2)
  Activated ALERT at ALERT (0.2)
  Requiring nested dependencies (AgensLayoutEngine (~> 2.0), ReactiveCocoa (~> 2.4), CocoaAsyncSocket (~> 7.4), SocketIO-Client-CPP (~> 1.5.0))
  Creating possibility state for Rhea (from `../../../Rhea/Rhea.podspec`) (1 remaining)
    Attempting to activate Rhea (0.2.4)
    Activated Rhea at Rhea (0.2.4)
    Requiring nested dependencies (Rhea/Default (= 0.2.4))
    Creating possibility state for AgensLayoutEngine (from `../../../ALE/AgensLayoutEngine.podspec`) (1 remaining)
      Attempting to activate AgensLayoutEngine (2.0)
      Activated AgensLayoutEngine at AgensLayoutEngine (2.0)
      Requiring nested dependencies (IVYTextDrawing (~> 0.5.7), FLOP (~> 0.1.1), Rhea (~> 0.2.4), SaneNSError (~> 1.0), MPColorTools (~> 1.6), BlocksKit (~> 2.2), ReactiveCocoa (~> 2.4))
      Creating possibility state for AgensLayoutEngine (~> 2.0) (1 remaining)
        Attempting to activate AgensLayoutEngine (2.0)
        Found existing spec (AgensLayoutEngine (2.0))
        Creating possibility state for Rhea (~> 0.2.4) (1 remaining)
          Attempting to activate Rhea (0.2.4)
          Found existing spec (Rhea (0.2.4))
          Creating possibility state for FLOP (~> 0.1.1) (1 remaining)
(omitted...)
```

##### My Podfile
```
source 'https://bitbucket.org/agens/agenspodspec.git'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '6.0'

pod 'ALERT', :path => '../../ALERT.podspec'
pod 'Rhea', :path => '../../../Rhea/Rhea.podspec'
pod 'AgensLayoutEngine', :path => '../../../ALE/AgensLayoutEngine.podspec'
```

##### ALERT.podspec
```
Pod::Spec.new do |s|

    s.name          = "ALERT"
    s.version       = "0.2"
    s.summary       = "Agens Layout Engine Realtime Templating"
    s.homepage      = "https://bitbucket.org/agens/alert"
    s.license       = {
        :type => 'MIT',
        :file => 'LICENSE'
        }
    s.platform      = :ios, '6.0'
    s.requires_arc  = true
    s.authors       = {
        "Håvard Fossli" => "hfossli@agens.no",
        }
    s.source        = {
        :git => "git@bitbucket.org:agens/alert.git",
        :tag => s.version.to_s
        }
    s.frameworks    = 'CoreGraphics', 'UIKit', 'QuartzCore', 'ImageIO'
    s.source_files  = 'iOS/Source/**/*.{h,m,mm,hpp,cpp,c}'
    s.resources     = 'iOS/Resources/**/*.{storyboard,xib,png}'

    s.dependency      'AgensLayoutEngine', '~> 2.0'
    s.dependency      'ReactiveCocoa', '~> 2.4'
    s.dependency      'CocoaAsyncSocket', '~> 7.4'
    s.dependency      'SocketIO-Client-CPP', '~> 1.5.0'

end
```

##### AgensLayoutEngine.podspec
```
Pod::Spec.new do |s|

    s.name         = "AgensLayoutEngine"
    s.version      = "2.0"
    s.summary      = "Async constraints layout and rendering."
    s.homepage     = "https://bitbucket.org/agens/layout-engine-ios"
    s.license = {
    	:type => 'MIT',
    	:file => 'LICENSE'
    	}
    s.platform      = :ios, '7.0'
    s.requires_arc  = true
    s.authors      = {
    	"Håvard Fossli" => "hfossli@agens.no",
    	}
    s.source       = {
        :git => "git@bitbucket.org:agens/layout-engine-ios.git",
        :tag => s.version.to_s
        }
    s.frameworks      = 'CoreGraphics', 'UIKit', 'QuartzCore', 'ImageIO'
    s.source_files    = 'Source/**/*.{h,m,mm,hpp,cpp,c}'

    s.dependency      'IVYTextDrawing', '~> 0.5.7'
    s.dependency      'FLOP', '~> 0.1.1'
    s.dependency      'Rhea', '~> 0.2.4'
    s.dependency      'SaneNSError', '~> 1.0'
    s.dependency      'MPColorTools', '~> 1.6'
    s.dependency      'BlocksKit', '~> 2.2'
    s.dependency      'ReactiveCocoa', '~> 2.4'

end

```

**Comment by martoche9** [comment]
Since 0.38.0 I have the same error.

see issue #3865

**Comment by segiddins** [comment]
`AgensLayoutEngine` requires iOS 7, but your Podfile specifies iOS 6.

**Comment by hfossli** [comment]
Well, we should see that in the error output, shouldn't we? Is there an open ticket for this?
