### ISSUE TITLE
'pod spec lint' fails with crash when name of podspec is omitted.

### ISSUE THREAD

**Issue by tarbrain** [CocoaPods/CocoaPods#3869]
When running `pod spec lint` on my podspec cocoapods crashes with the following message:

### Command

```
/Users/juliankrumow/.rvm/gems/ruby-2.0.0-p247/bin/pod spec lint
```

### Report

* What did you do?

I ran `pod spec lint`.

* What did you expect to happen?

Cocoapods to lint the podspec in the working directory and telling me wether it is valid or not.

* What happened instead?

Cocoapods crashed.

### Stack

```
   CocoaPods : 0.38.0
        Ruby : ruby 2.0.0p247 (2013-06-27 revision 41674) [x86_64-darwin13.4.0]
    RubyGems : 2.2.2
        Host : Mac OS X 10.10.4 (14E46)
       Xcode : 7.0 (7A152u)
         Git : git version 2.3.8 (Apple Git-58)
Ruby lib dir : /Users/juliankrumow/.rvm/rubies/ruby-2.0.0-p247/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 33685bc23a8489789af72c34af39e04de08f588c
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-stats   : 0.5.3
cocoapods-trunk   : 0.6.1
cocoapods-try     : 0.4.5
```

### Error

```
NameError - undefined local variable or method `invalid_count' for #<Pod::Command::Spec::Lint:0x007fd3fc0bc278>
/Users/juliankrumow/.rvm/gems/ruby-2.0.0-p247/gems/cocoapods-0.38.0/lib/cocoapods/command/spec/lint.rb:75:in `run'
/Users/juliankrumow/.rvm/gems/ruby-2.0.0-p247/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Users/juliankrumow/.rvm/gems/ruby-2.0.0-p247/gems/cocoapods-0.38.0/lib/cocoapods/command.rb:48:in `run'
/Users/juliankrumow/.rvm/gems/ruby-2.0.0-p247/gems/cocoapods-0.38.0/bin/pod:44:in `<top (required)>'
/Users/juliankrumow/.rvm/gems/ruby-2.0.0-p247/bin/pod:23:in `load'
/Users/juliankrumow/.rvm/gems/ruby-2.0.0-p247/bin/pod:23:in `<main>'
/Users/juliankrumow/.rvm/gems/ruby-2.0.0-p247/bin/ruby_executable_hooks:15:in `eval'
/Users/juliankrumow/.rvm/gems/ruby-2.0.0-p247/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by segiddins** [comment]
Can you please also share the podspec in question? Thanks!

**Comment by tarbrain** [comment]
Hi @segiddins,
Here it is:

https://github.com/tarbrain/TBStateMachine/blob/master/TBStateMachine.podspec

**Comment by tarbrain** [comment]
When calling

`pod spec lint TBStatemachine.podspec`

The podspec is successfully linted without errors.
