### ISSUE TITLE
EACCES - Permission denied @ rb_sysopen - v0.38.1

### ISSUE THREAD

**Issue by Zyphrax** [CocoaPods/CocoaPods#3879]
### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?
I tried to install pods. This worked in 0.38.
FYI: my main project is Obj-C only.

* What did you expect to happen?
CocoaPods to be happy

* What happened instead?
CocoaPods throwing errors about modulemap

### Stack

```
   CocoaPods : 0.38.1
        Ruby : ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
    RubyGems : 2.4.6
        Host : Mac OS X 10.10.4 (14E46)
       Xcode : 6.4 (6E35b)
         Git : git version 2.4.6
Ruby lib dir : /usr/local/Cellar/ruby/2.2.2/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 703686185c9c170c91e2748aca224b774916b726
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-stats   : 0.5.3
cocoapods-trunk   : 0.6.1
cocoapods-try     : 0.4.5
```

### Podfile

```ruby
platform :ios, '7.0'
inhibit_all_warnings!

pod 'BKMoneyKit', '0.0.1'
pod 'CocoaAsyncSocket'
pod 'CocoaHTTPServer'
pod 'CocoaLumberjack'
pod 'FormatterKit'
pod 'GRMustache'
pod 'MBProgressHUD'
pod 'PNChart', '0.8'
pod 'RoutingHTTPServer'
pod 'SSZipArchive'
pod 'ZBarSDK'

link_with 'X', 'X Lab'
```

### Error

```
Errno::EACCES - Permission denied @ rb_sysopen - /Users/X/Projects/X/Pods/Target Support Files/CocoaLumberjack/CocoaLumberjack.modulemap
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.1/lib/cocoapods/installer/target_installer/pod_target_installer.rb:309:in `initialize'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.1/lib/cocoapods/installer/target_installer/pod_target_installer.rb:309:in `open'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.1/lib/cocoapods/installer/target_installer/pod_target_installer.rb:309:in `open'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.1/lib/cocoapods/installer/target_installer/pod_target_installer.rb:309:in `block in create_module_map'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.1/lib/cocoapods/user_interface.rb:140:in `message'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.1/lib/cocoapods/installer/target_installer/pod_target_installer.rb:302:in `create_module_map'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.1/lib/cocoapods/installer/target_installer/pod_target_installer.rb:26:in `block in install!'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.1/lib/cocoapods/user_interface.rb:140:in `message'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.1/lib/cocoapods/installer/target_installer/pod_target_installer.rb:17:in `install!'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.1/lib/cocoapods/installer.rb:573:in `block (2 levels) in install_libraries'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.1/lib/cocoapods/installer.rb:570:in `each'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.1/lib/cocoapods/installer.rb:570:in `block in install_libraries'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.1/lib/cocoapods/user_interface.rb:140:in `message'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.1/lib/cocoapods/installer.rb:569:in `install_libraries'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.1/lib/cocoapods/installer.rb:152:in `block in generate_pods_project'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.1/lib/cocoapods/user_interface.rb:59:in `section'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.1/lib/cocoapods/installer.rb:149:in `generate_pods_project'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.1/lib/cocoapods/installer.rb:109:in `install!'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.1/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.1/lib/cocoapods/command/project.rb:101:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.1/lib/cocoapods/command.rb:48:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.1/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by x2on** [comment]
I had the same problem - deleting the `Pods` folder and run `pod install` again solved the problem

**Comment by eytanbiala** [comment]
I had the same error, and removing the Pods folder also worked for me.

**Comment by neonichu** [comment]
The changes in #3878 are probably causing this, as the error happens during writing the new module maps.

**Comment by GSatko** [comment]
I had a very similar issue.

As @x2on said, deleting my Pods folder and running pod install worked just fine

**Comment by Zyphrax** [comment]
I've just tested removing the Pods folder under 0.38.1 and that indeed seems to work.

**Comment by danpe** [comment]
Yup was the same here, running
```rm -rf ./Pods/``` and then ```pod install``` worked :+1:

**Comment by rsun-babu** [comment]
**sudo pod install --allow-root** worked for me

This was found in [stackoverflow.com ](https://stackoverflow.com/questions/51180534/cocoapods-permission-denied-errnoeacces-permission-denied-dir-s-mkdir)
