### ISSUE TITLE
Unsupported class for YAML conversion NilClass

### ISSUE THREAD

**Issue by Rakk4403** [CocoaPods/CocoaPods#3907]
### Command

```
/usr/bin/pod update --verbose
```

### Report

* What did you do?
I use pods for making library. Just using "myApp" as front-end project, other machine ( mac mini, etc ) does pod update successfully.
* What did you expect to happen?
To be built pods as a library.
* What happened instead?
"Unsupported class for YAML conversion NilClass" Message occurred and stopped. Additionally, Podfile.lock was empty. this happened while "Writing Lockfile in `Podfile.lock`"

### Stack

```
   CocoaPods : 0.38.2
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.0.14
        Host : Mac OS X 10.10.4 (14E46)
       Xcode : 6.4 (6E35b)
         Git : git version 2.3.2 (Apple Git-55)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ c5b524ea068c78f09a3087db4e1066aedd3ede7b
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-stats   : 0.5.3
cocoapods-trunk   : 0.6.1
cocoapods-try     : 0.4.5
```

### Podfile

```ruby
platform:ios, '7.0'

xcodeproj 'myApp/myApp'

pod 'mykit', svn: 'svn://svn.mine/myKit/branches/test'
```

### Error

```
Pod::StandardError - Unsupported class for YAML conversion NilClass
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.38.2/lib/cocoapods-core/yaml_helper.rb:104:in `process_according_to_class'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.38.2/lib/cocoapods-core/yaml_helper.rb:144:in `block in process_hash'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.38.2/lib/cocoapods-core/yaml_helper.rb:142:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.38.2/lib/cocoapods-core/yaml_helper.rb:142:in `process_hash'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.38.2/lib/cocoapods-core/yaml_helper.rb:102:in `process_according_to_class'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.38.2/lib/cocoapods-core/yaml_helper.rb:144:in `block in process_hash'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.38.2/lib/cocoapods-core/yaml_helper.rb:142:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.38.2/lib/cocoapods-core/yaml_helper.rb:142:in `process_hash'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.38.2/lib/cocoapods-core/yaml_helper.rb:102:in `process_according_to_class'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.38.2/lib/cocoapods-core/yaml_helper.rb:144:in `block in process_hash'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.38.2/lib/cocoapods-core/yaml_helper.rb:142:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.38.2/lib/cocoapods-core/yaml_helper.rb:142:in `process_hash'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.38.2/lib/cocoapods-core/yaml_helper.rb:41:in `convert_hash'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.38.2/lib/cocoapods-core/lockfile.rb:347:in `to_yaml'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.38.2/lib/cocoapods-core/lockfile.rb:300:in `block in write_to_disk'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.38.2/lib/cocoapods-core/lockfile.rb:300:in `open'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.38.2/lib/cocoapods-core/lockfile.rb:300:in `open'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.38.2/lib/cocoapods-core/lockfile.rb:300:in `write_to_disk'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:682:in `block in write_lockfiles'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:140:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:681:in `write_lockfiles'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:158:in `block in generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:150:in `generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:110:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:156:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

**Comment by segiddins** [comment]
Can you please share the contents of `Podfile.lock`?

**Comment by Rakk4403** [comment]
thanks for rapid reply.
There is nothing in it. the file was empty. Do you need more info?
