### ISSUE TITLE
Problem using RxSwift

### ISSUE THREAD

**Issue by kzaher** [CocoaPods/CocoaPods#3915]
Hi,

I'm having troubles using RxSwift through CocoaPods. I've tried

 rm -rf ~/Library/Caches/CocoaPods

This is podfile
```
#Podfile

use_frameworks!

pod 'RxSwift' #, :git => "git@github.com:kzaher/RxSwift.git", :tag => 'develop'
#pod 'RxCocoa' #, :git => "git@github.com:kzaher/RxSwift.git", :tag => 'develop'
#pod 'RxBlocking' #, :git => "git@github.com:kzaher/RxSwift.git", :tag => 'develop'

```
I've tried all commented combinations. It stopped working today. I've tried update the gem also.

This is the output.

```
[kzaher@Krunoslavs-MacBook-Pro-2 RxCocoaPodTest]$ pod update --verbose
Update all pods
  Preparing

Updating local specs repositories

Updating spec repo `master`
  $ /usr/bin/git pull --ff-only
  Already up-to-date.

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods`: (``)

Resolving dependencies of `Podfile`
[!] Unable to satisfy the following requirements:

- `RxSwift` required by `Podfile`

/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/resolver.rb:388:in `handle_resolver_error'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/resolver.rb:69:in `rescue in resolve'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/resolver.rb:56:in `resolve'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/analyzer.rb:535:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/analyzer.rb:533:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/analyzer.rb:70:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:210:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:133:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:132:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:104:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:156:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

**Comment by kzaher** [comment]
I've also tried

```
rm -rf Pods
rm -rf RxCocoaPodTest.xcworkspace
```

**Comment by segiddins** [comment]
RxSwift requires iOS 8 / OS X 10.9, are those the minimum deployment targets of your targets in your xcodeproject?

**Comment by kzaher** [comment]
Ah, damn it, you are right. I was testing some bug reports, and changed architecture to iOS 7 :(

Thnx!!!!

Maybe it would be a good idea to change error message.
```
[!] Unable to satisfy the following requirements:

- `RxSwift` required by `Podfile`
```

Couldn't understand what was wrong.

Thnx again.

**Comment by alloy** [comment]
@segiddins Yeah, would be nicer if that error had mentioned the deployment target not satisfying. Does your recent Molinillo work allow for that?

**Comment by segiddins** [comment]
@alloy not specifically, but it should be possible to walk the requirement tree and see if there are indeed spec versions that satisfy the plain requirement, and if so advising that it's caused by a version mismatch. Could you make a separate issue for that?

**Comment by alloy** [comment]
@segiddins Right so you are: https://github.com/CocoaPods/CocoaPods/issues/3926
