### ISSUE TITLE
Fatal error when using `podspec` in Podfile when podspec doesn't exist.

### ISSUE THREAD

**Issue by fatuhoku** [CocoaPods/CocoaPods#3919]
### Command

```
/Users/myusername/.rbenv/versions/2.1.5/bin/pod install
```

### Report

* What did you do?

Ran `pod install` against `Podfile` that reads:

```ruby
use_frameworks!
inhibit_all_warnings!

podspec
```

... intentionally when no `*.podspec` is present in the file directory.

* What did you expect to happen?

I expected to get a graceful error from Cocoapods telling me that the `.podspec` is missing and I had better write one!

Note that the `Podfile` is legal, according to the docs.
 
![screen shot 2015-07-28 at 16 19 51](https://cloud.githubusercontent.com/assets/430233/8935397/80247e7c-3544-11e5-90f5-595094a267b7.png)

* What happened instead?

The following error occurred.

### Stack

```
   CocoaPods : 0.38.2
        Ruby : ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin14.0]
    RubyGems : 2.2.2
        Host : Mac OS X 10.10.3 (14D136)
       Xcode : 6.4 (6E35b)
         Git : git version 2.2.0
Ruby lib dir : /Users/myusername/.rbenv/versions/2.1.5/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ bdc7aa08f041c28fa3dbdfa03b0a789cfc00aca3
```

### Plugins

```
cocoapods-deintegrate : 0.2.1
cocoapods-plugins     : 0.4.2
cocoapods-stats       : 0.5.3
cocoapods-trunk       : 0.6.1
cocoapods-try         : 0.4.5
```

### Podfile

```ruby
use_frameworks!
inhibit_all_warnings!

podspec
```

### Error

```
TypeError - no implicit conversion of nil into String
/Users/myusername/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-core-0.38.2/lib/cocoapods-core/specification.rb:528:in `initialize'
/Users/myusername/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-core-0.38.2/lib/cocoapods-core/specification.rb:528:in `new'
/Users/myusername/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-core-0.38.2/lib/cocoapods-core/specification.rb:528:in `from_file'
/Users/myusername/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-core-0.38.2/lib/cocoapods-core/podfile/target_definition.rb:669:in `block in podspec_dependencies'
/Users/myusername/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-core-0.38.2/lib/cocoapods-core/podfile/target_definition.rb:667:in `map'
/Users/myusername/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-core-0.38.2/lib/cocoapods-core/podfile/target_definition.rb:667:in `podspec_dependencies'
/Users/myusername/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-core-0.38.2/lib/cocoapods-core/podfile/target_definition.rb:87:in `non_inherited_dependencies'
/Users/myusername/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-core-0.38.2/lib/cocoapods-core/podfile/target_definition.rb:77:in `dependencies'
/Users/myusername/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/podfile_validator.rb:59:in `block in validate_pod_directives'
/Users/myusername/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/podfile_validator.rb:58:in `each'
/Users/myusername/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/podfile_validator.rb:58:in `flat_map'
/Users/myusername/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/podfile_validator.rb:58:in `validate_pod_directives'
/Users/myusername/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/podfile_validator.rb:29:in `validate'
/Users/myusername/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/analyzer.rb:155:in `validate_podfile!'
/Users/myusername/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/analyzer.rb:57:in `analyze'
/Users/myusername/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:210:in `analyze'
/Users/myusername/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:133:in `block in resolve_dependencies'
/Users/myusername/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:59:in `section'
/Users/myusername/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:132:in `resolve_dependencies'
/Users/myusername/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:104:in `install!'
/Users/myusername/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/myusername/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:101:in `run'
/Users/myusername/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Users/myusername/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/Users/myusername/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
/Users/myusername/.rbenv/versions/2.1.5/bin/pod:23:in `load'
/Users/myusername/.rbenv/versions/2.1.5/bin/pod:23:in `<main>'
```

**Comment by segiddins** [comment]
\c @k0nserv this is happening in podfile validation

**Comment by k0nserv** [comment]
Fixing it right away, until then an explicit `path` will solve the problem

**Comment by segiddins** [comment]
This was just fixed in https://github.com/CocoaPods/Core/pull/257.
