### ISSUE TITLE
Gem::ConflictError - Unable to activate slather-1.7.1, because xcodeproj-0.26.3 conflicts with xcodeproj (~> 0.24.1)

### ISSUE THREAD

**Issue by asalom** [CocoaPods/CocoaPods#3935]
Hello,
I recently updated to cocoapods 0.38.2 and now every time I run a command, like for example ```pod --version``` I get the following error:

```
$ pod --version
---------------------------------------------
Error loading the plugin with path `/Users/asalom/.rvm/gems/ruby-2.0.0-p481/gems/slather-1.7.1/lib/cocoapods_plugin.rb`.

Gem::ConflictError - Unable to activate slather-1.7.1, because xcodeproj-0.26.3 conflicts with xcodeproj (~> 0.24.1)
/Users/asalom/.rvm/rubies/ruby-2.0.0-p481/lib/ruby/site_ruby/2.0.0/rubygems/specification.rb:2112:in `raise_if_conflicts'
/Users/asalom/.rvm/rubies/ruby-2.0.0-p481/lib/ruby/site_ruby/2.0.0/rubygems/specification.rb:1280:in `activate'
/Users/asalom/.rvm/rubies/ruby-2.0.0-p481/lib/ruby/site_ruby/2.0.0/rubygems.rb:198:in `rescue in try_activate'
/Users/asalom/.rvm/rubies/ruby-2.0.0-p481/lib/ruby/site_ruby/2.0.0/rubygems.rb:195:in `try_activate'
/Users/asalom/.rvm/rubies/ruby-2.0.0-p481/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
/Users/asalom/.rvm/rubies/ruby-2.0.0-p481/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:39:in `require'
/Users/asalom/.rvm/gems/ruby-2.0.0-p481/gems/slather-1.7.1/lib/cocoapods_plugin.rb:1:in `<top (required)>'
/Users/asalom/.rvm/rubies/ruby-2.0.0-p481/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/asalom/.rvm/rubies/ruby-2.0.0-p481/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/asalom/.rvm/gems/ruby-2.0.0-p481/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:106:in `safe_require'
/Users/asalom/.rvm/gems/ruby-2.0.0-p481/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:32:in `block in load_plugins'
/Users/asalom/.rvm/gems/ruby-2.0.0-p481/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:31:in `each'
/Users/asalom/.rvm/gems/ruby-2.0.0-p481/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:31:in `load_plugins'
/Users/asalom/.rvm/gems/ruby-2.0.0-p481/gems/claide-0.9.1/lib/claide/command.rb:304:in `block in run'
/Users/asalom/.rvm/gems/ruby-2.0.0-p481/gems/claide-0.9.1/lib/claide/command.rb:303:in `each'
/Users/asalom/.rvm/gems/ruby-2.0.0-p481/gems/claide-0.9.1/lib/claide/command.rb:303:in `run'
/Users/asalom/.rvm/gems/ruby-2.0.0-p481/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/Users/asalom/.rvm/gems/ruby-2.0.0-p481/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
/Users/asalom/.rvm/gems/ruby-2.0.0-p481/bin/pod:23:in `load'
/Users/asalom/.rvm/gems/ruby-2.0.0-p481/bin/pod:23:in `<main>'
/Users/asalom/.rvm/gems/ruby-2.0.0-p481/bin/ruby_executable_hooks:15:in `eval'
/Users/asalom/.rvm/gems/ruby-2.0.0-p481/bin/ruby_executable_hooks:15:in `<main>'
---------------------------------------------

0.38.2
```

Please note that after the error log the command works properly. I tried ```pod install```, ```pod --version``` and ```pod --help```. All of them threw the error and worked.

**Comment by neonichu** [comment]
This is an error message because the dependencies of the slather plugin you have installed are incompatible with the CocoaPods version you are using.
