### ISSUE TITLE
NameError - undefined local variable or method `installer_rep'

### ISSUE THREAD

**Issue by westerlund** [CocoaPods/CocoaPods#3945]
### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?
I run `pod install` after updating to `38.2` and it crashes

### Stack

```
   CocoaPods : 0.38.2
        Ruby : ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin14.0]
    RubyGems : 2.2.2
        Host : Mac OS X 10.10.4 (14E46)
       Xcode : 6.3.2 (6D2102)
         Git : git version 2.3.2 (Apple Git-55)
Ruby lib dir : /usr/local/Cellar/ruby/2.1.2_3/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ dfd915a94dd0a5ab9595d456476772a82058a014
```

### Plugins

```
cocoapods-dependencies : 0.4.1
cocoapods-plugins      : 0.4.2
cocoapods-podfile_info : 1.0.0
cocoapods-stats        : 0.5.3
cocoapods-trunk        : 0.6.1
cocoapods-try          : 0.4.5
```

### Podfile

```ruby
use_frameworks!
platform :ios, '8.0'
pod 'Mantle', '~> 1.5.4'
pod 'MBProgressHUD', '~> 0.9'
pod "AFNetworking", '~> 2.5.1'
pod "AFNetworkActivityLogger", '~> 2.0.3'
pod 'Mixpanel', '~> 2.7.3'
pod 'pop'
```

### Error

```
NameError - undefined local variable or method `installer_rep' for #<Pod::Installer:0x007fe3adba99b8>
/usr/local/lib/ruby/gems/2.1.0/gems/cocoapods-readonly-1.0.1/lib/cocoapods-readonly/toggle_readonly.rb:4:in `_set_permissions'
/usr/local/lib/ruby/gems/2.1.0/gems/cocoapods-readonly-1.0.1/lib/cocoapods-readonly/toggle_readonly.rb:18:in `perform_post_install_actions'
/usr/local/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:112:in `install!'
/usr/local/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/usr/local/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:101:in `run'
/usr/local/lib/ruby/gems/2.1.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/usr/local/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/usr/local/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

Also, I get the following error before it fails:

```
---------------------------------------------
Error loading the plugin with path `/usr/local/lib/ruby/gems/2.1.0/gems/cocoapods-readonly-1.0.1/lib/cocoapods_plugin.rb`.

NameError - undefined method `run_pre_install_hooks' for class `Pod::Installer'
/usr/local/lib/ruby/gems/2.1.0/gems/cocoapods-readonly-1.0.1/lib/cocoapods-readonly/toggle_readonly.rb:21:in `alias_method'
/usr/local/lib/ruby/gems/2.1.0/gems/cocoapods-readonly-1.0.1/lib/cocoapods-readonly/toggle_readonly.rb:21:in `<class:Installer>'
/usr/local/lib/ruby/gems/2.1.0/gems/cocoapods-readonly-1.0.1/lib/cocoapods-readonly/toggle_readonly.rb:2:in `<module:Pod>'
/usr/local/lib/ruby/gems/2.1.0/gems/cocoapods-readonly-1.0.1/lib/cocoapods-readonly/toggle_readonly.rb:1:in `<top (required)>'
/usr/local/Cellar/ruby/2.1.2_3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `require'
/usr/local/Cellar/ruby/2.1.2_3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
/usr/local/Cellar/ruby/2.1.2_3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144:in `require'
/usr/local/lib/ruby/gems/2.1.0/gems/cocoapods-readonly-1.0.1/lib/cocoapods_plugin.rb:1:in `<top (required)>'
/usr/local/Cellar/ruby/2.1.2_3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Cellar/ruby/2.1.2_3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/lib/ruby/gems/2.1.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:106:in `safe_require'
/usr/local/lib/ruby/gems/2.1.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:32:in `block in load_plugins'
/usr/local/lib/ruby/gems/2.1.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:31:in `each'
/usr/local/lib/ruby/gems/2.1.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:31:in `load_plugins'
/usr/local/lib/ruby/gems/2.1.0/gems/claide-0.9.1/lib/claide/command.rb:304:in `block in run'
/usr/local/lib/ruby/gems/2.1.0/gems/claide-0.9.1/lib/claide/command.rb:303:in `each'
/usr/local/lib/ruby/gems/2.1.0/gems/claide-0.9.1/lib/claide/command.rb:303:in `run'
/usr/local/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/usr/local/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
---------------------------------------------
```

**Comment by neonichu** [comment]
These are issues in the cocoapods-readonly plugin which you have installed. You should check if there's a newer version of it which is compatible with CP 0.38.2 or uninstall it until there is.

**Comment by westerlund** [comment]
that was quick, thanks @neonichu
