### ISSUE TITLE
Gracefully handle invalid value for resource_bundle

### ISSUE THREAD

**Issue by fatuhoku** [CocoaPods/CocoaPods#3955]
### Report

* What did you do?

Ran `pod install` with a slightly incorrect podspec. I normally create pods with `pod lib create`. The  default resource handling section of the `podspec` reads like this:

```ruby
  // BEFORE
  s.resource_bundles = {
    'MyProj' => ['Pod/Assets/*.png']
  }
```

Since I'm not writing a library and I actually wanted to include XIB assets rather than PNGs, I figured that I could just replace `resource_bundles` with `resources` things would just work:

```ruby
   // AFTER
  s.resources = {
    'MyProj' => ['Pod/Assets/**/*']
  }
``` 

* What did you expect to happen?

I should get a graceful error telling me that `s.resources` was expecting an array, not a dictionary.

* What happened instead?

Cocoapods crashed horribly with the following stack trace.

### Stack

```
   CocoaPods : 0.38.2
        Ruby : ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin14.0]
    RubyGems : 2.2.2
        Host : Mac OS X 10.10.3 (14D136)
       Xcode : 6.4 (6E35b)
         Git : git version 2.2.0
Ruby lib dir : /Users/myusername/.rbenv/versions/2.1.5/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 876f4eff74f97d7affb511be904cb9bfc84be68b
```

### Plugins

```
cocoapods-deintegrate : 0.2.1
cocoapods-plugins     : 0.4.2
cocoapods-stats       : 0.5.3
cocoapods-trunk       : 0.6.1
cocoapods-try         : 0.4.5
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MakeEatSeeUI_Example', :exclusive => true do
  pod "MakeEatSeeUI", :path => "../"
end

target 'MakeEatSeeUI_Tests', :exclusive => true do
  pod "MakeEatSeeUI", :path => "../"

  pod 'Quick', '~> 0.3.1'
  pod 'Nimble'
end
```

### Error

```
NoMethodError - undefined method `gsub' for ["MakeEatSeeUI", ["Pod/Assets/**/*"]]:Array
/Users/myusername/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.2/lib/cocoapods/sandbox/path_list.rb:178:in `dir_glob_equivalent_patterns'
/Users/myusername/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.2/lib/cocoapods/sandbox/path_list.rb:125:in `block in relative_glob'
/Users/myusername/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.2/lib/cocoapods/sandbox/path_list.rb:120:in `map'
/Users/myusername/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.2/lib/cocoapods/sandbox/path_list.rb:120:in `relative_glob'
/Users/myusername/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.2/lib/cocoapods/sandbox/path_list.rb:79:in `glob'
/Users/myusername/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.2/lib/cocoapods/sandbox/file_accessor.rb:314:in `expanded_paths'
/Users/myusername/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.2/lib/cocoapods/sandbox/file_accessor.rb:285:in `paths_for_attribute'
/Users/myusername/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.2/lib/cocoapods/sandbox/file_accessor.rb:139:in `resources'
/Users/myusername/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:181:in `block in add_file_accessors_paths_to_pods_group'
/Users/myusername/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:178:in `each'
/Users/myusername/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:178:in `add_file_accessors_paths_to_pods_group'
/Users/myusername/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:105:in `block in add_resources'
/Users/myusername/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:140:in `message'
/Users/myusername/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:104:in `add_resources'
/Users/myusername/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:40:in `install!'
/Users/myusername/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:562:in `install_file_references'
/Users/myusername/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:152:in `block in generate_pods_project'
/Users/myusername/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:59:in `section'
/Users/myusername/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:150:in `generate_pods_project'
/Users/myusername/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:110:in `install!'
/Users/myusername/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/myusername/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:101:in `run'
/Users/myusername/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Users/myusername/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/Users/myusername/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
/Users/myusername/.rbenv/versions/2.1.5/bin/pod:23:in `load'
/Users/myusername/.rbenv/versions/2.1.5/bin/pod:23:in `<main>'
```

**Comment by segiddins** [comment]
Could you please share the `MakeEatSeeUI` podspec?

**Comment by fatuhoku** [comment]
Here:

```
# MakeEatSeeUI.podspec
#
# Be sure to run `pod lib lint MakeEatSeeUI.podspec' to ensure this is a
# valid spec and remove all comments before submitting the spec.
#
# Any lines starting with a # are optional, but encouraged
#
# To learn more about a Podspec see http://guides.cocoapods.org/syntax/podspec.html
#

Pod::Spec.new do |s|
  s.name             = "MakeEatSeeUI"
  s.version          = "0.1.0"
  s.summary          = "A short description of MakeEatSeeUI."
  s.description      = <<-DESC
                       An optional longer description of MakeEatSeeUI

                       * Markdown format.
                       * Don't worry about the indent, we strip it!
                       DESC
  s.homepage         = "https://github.com/<GITHUB_USERNAME>/MakeEatSeeUI"
  # s.screenshots     = "www.example.com/screenshots_1", "www.example.com/screenshots_2"
  s.license          = 'MIT'
  s.author           = { "Hok Shun Poon" => "hok@hokshunpoon.me" }
  s.source           = { :git => "https://github.com/<GITHUB_USERNAME>/MakeEatSeeUI.git", :tag => s.version.to_s }
  # s.social_media_url = 'https://twitter.com/<TWITTER_USERNAME>'

  s.platform     = :ios, '8.0'
  s.requires_arc = true

  s.source_files = 'Pod/Classes/**/*.{h,m,swift}'
  s.resources = {
    'MyProj' => ['Pod/Assets/**/*']
  }

  # s.public_header_files = 'Pod/Classes/**/*.h'
  # s.frameworks = 'UIKit', 'MapKit'
  s.dependency 'SDWebImage'
end
```

**Comment by yimingtang** [comment]
If you're using `resources`, you should pass an array.

``` ruby
s.resources = ['your/resources/path', 'another/resource/path']
```

**Comment by fatuhoku** [comment]
@yimingtang thanks, I know that.  I'm saying that Cocoapods should basically print out an error that says what you just said.

**Comment by kylef** [comment]
@fatuhoku I believe it does:

```
$ pod lib lint MakeEatSeeUI.podspec --quick

 -> MakeEatSeeUI (0.1.0)
    - WARN  | The summary is not meaningful.
    - WARN  | The description is not meaningful.
    - ERROR | [iOS] Unacceptable type `Hash` for `resources`. Allowed values: `[String, Array]`.
```

It's clearly told you that a hash is an invalid value for resources, and a string or an array is acceptable.

**Comment by jbarros35** [comment]
Doesn't look clear to me
