### ISSUE TITLE
Resolving dependencies, Unable to satisfy the following requirements

### ISSUE THREAD

**Issue by gautamMoEngage** [CocoaPods/CocoaPods#3964]
Along the lines of this issue - https://github.com/CocoaPods/CocoaPods/issues/2768.

Here's the Podfile:

```
PODS:
  - Amplitude-iOS (2.4.0)
  - AppsFlyer-SDK (2.5.3.10)
  - Apptimize (2.10.0.1)
  - Bugsnag (4.0.3):
    - Bugsnag/no-arc (= 4.0.3)
  - Bugsnag/no-arc (4.0.3)
  - Countly (1.0.0)
  - CrittercismSDK (5.2.0)
  - Expecta (0.3.2)
  - FlurrySDK (4.4.0):
    - FlurrySDK/FlurrySDK (= 4.4.0)
  - FlurrySDK/FlurrySDK (4.4.0)
  - GoogleAnalytics-iOS-SDK (3.10):
    - GoogleAnalytics-iOS-SDK/Core (= 3.10)
  - GoogleAnalytics-iOS-SDK/Core (3.10)
  - GoogleAnalytics-iOS-SDK/IDFA (3.10):
    - GoogleAnalytics-iOS-SDK/Core
  - KahunaSDK (1.0.570)
  - Localytics (3.1.0)
  - Mixpanel (2.6.0):
    - Mixpanel/MPCategoryHelpers (= 2.6.0)
  - Mixpanel/MPCategoryHelpers (2.6.0)
  - MoEngage-iOS-SDK (1.4.3)
  - OCMock (2.2.4)
  - Optimizely-iOS-SDK (1.0.81)
  - Quantcast-Measure (1.4.6):
    - Quantcast-Measure/Core (= 1.4.6)
  - Quantcast-Measure/Core (1.4.6)
  - Taplytics (2.1.88)
  - Tapstream (2.8.3)
  - TRVSDictionaryWithCaseInsensitivity (0.0.2)
  - TRVSKit/TRVSAssertions (0.0.9):
    - Expecta (~> 0.3.0)

DEPENDENCIES:
  - Amplitude-iOS (= 2.4.0)
  - AppsFlyer-SDK (= 2.5.3.10)
  - Apptimize (= 2.10.0.1)
  - Bugsnag (= 4.0.3)
  - Countly (= 1.0.0)
  - CrittercismSDK (= 5.2.0)
  - Expecta (~> 0.3.0)
  - FlurrySDK (= 4.4.0)
  - GoogleAnalytics-iOS-SDK (= 3.10)
  - GoogleAnalytics-iOS-SDK/IDFA (= 3.10)
  - KahunaSDK (= 1.0.570)
  - Localytics (= 3.1.0)
  - Mixpanel (= 2.6.0)
  - MoEngage-iOS-SDK (= 1.4.3)
  - OCMock (~> 2.2.4)
  - Optimizely-iOS-SDK (= 1.0.81)
  - Quantcast-Measure (= 1.4.6)
  - Taplytics (= 2.1.88)
  - Tapstream (= 2.8.3)
  - TRVSDictionaryWithCaseInsensitivity (= 0.0.2)
  - TRVSKit/TRVSAssertions (~> 0.0.8)

SPEC CHECKSUMS:
  Amplitude-iOS: b5a2643ed7ce861cc65c8de437c7b4d9bc1708eb
  AppsFlyer-SDK: f83ad2e0821c57852512ea0bb8d3b207c64ef698
  Apptimize: c180b9833f3a83498475cda9e52d67282280b0e5
  Bugsnag: 7267951d92ac48ff264b605cf65b42208dfde905
  Countly: 61e8a4518699221846db98f09a5d6f2b38267a25
  CrittercismSDK: a8f09d8f1d9fea3bc0714a954a079062c5c9d914
  Expecta: 8c507baf13211207b1e9d0a741480600e6b4ed15
  FlurrySDK: 68f1952f3d04a82cfcfbf00ed3435e81317c2946
  GoogleAnalytics-iOS-SDK: 4f98a376c1d61e6ac4ca47951655820314856eef
  KahunaSDK: ea15fdf9757c4d9bf639bf190888e20b688a30ed
  Localytics: 87268a820c285f6f5ed3fa505a176c049ed07462
  Mixpanel: 488567f7138408f360377dd46e1d189655f8b435
  MoEngage-iOS-SDK: 81be7a433349a7d535c905a08629359eeefe0952
  OCMock: a6a7dc0e3997fb9f35d99f72528698ebf60d64f2
  Optimizely-iOS-SDK: 33b0580735808a876f0b91a53ab25c7501bad082
  Quantcast-Measure: 415d204ee4010b27493369e131cec09de1b5acf5
  Taplytics: cca59691ece9738acfa153a07c02d823c77f1be2
  Tapstream: 37f7339a7d8aa8cc92b045edbacc91ef7f4090c5
  TRVSDictionaryWithCaseInsensitivity: 51d2ccf52c6d645d27b63467a98fa02c556e01b0
  TRVSKit: cbc09d442ce631c6b0f9e4ee4fb666a96146e4b3

COCOAPODS: 0.37.2
```

I tried removing the Podfile.lock. That worked with 0.37.2, but doesn't work with 0.38.2. 
Here's the error in detail:
```
Resolving dependencies of `Podfile`
[!] Unable to satisfy the following requirements:

- `MoEngage-iOS-SDK (= 1.4.3)` required by `Podfile`
- `MoEngage-iOS-SDK (= 1.4.3)` required by `Podfile`
- `MoEngage-iOS-SDK (= 1.4.3)` required by `Podfile.lock`

/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/resolver.rb:388:in `handle_resolver_error'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/resolver.rb:69:in `rescue in resolve'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/resolver.rb:56:in `resolve'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/analyzer.rb:535:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/analyzer.rb:533:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/analyzer.rb:70:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:210:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:133:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:132:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:104:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

**Comment by segiddins** [comment]
My guess is that it's a minimum deployment target mismatch. I have a PR up that gives a better error message.

**Comment by adib** [comment]
@segiddins Yes, I had a similar problem too and setting a global `platform` directive solved it:

    platform :ios, '9.0'

**Comment by orta** [comment]
:+1: - this is cool, and we have better error messages in the next release https://github.com/CocoaPods/CocoaPods/pull/3953

**Comment by gautamMoEngage** [comment]
Yup. Possibly it's a minimum deployment mismatch. The parent SDK supports iOS6+ , while the dependent one supports iOS7+ . This used to give a proper warning before, but now gives this weird error. Making both same should resolve it. I'll check.

**Comment by HasanSawaed** [comment]
👍🏼, Thanks

**Comment by derrickstaten** [comment]
:+1: thanks
