### ISSUE TITLE
Pod install not working on new Xcode project with 0.38.2

### ISSUE THREAD

**Issue by robmontesinos** [CocoaPods/CocoaPods#3966]
――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/xxxxxx/.rvm/gems/ruby-2.2.0/bin/pod install
```

### Report

* What did you do?
sudo gem install cocoapods  --> 0.38.2
pod install

* What did you expect to happen?
install pods

* What happened instead?
ArgumentError - comparison of NilClass with String failed  etc.

### Stack

```
   CocoaPods : 0.38.2
        Ruby : ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]
    RubyGems : 2.4.8
        Host : Mac OS X 10.10.4 (14E46)
       Xcode : 6.4 (6E35b)
         Git : git version 2.3.2 (Apple Git-55)
Ruby lib dir : /Users/xxxxxx/.rvm/rubies/ruby-2.2.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 5b6a7f6d9ee002d3cf257ffb4d75bcfd062bd61e
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-stats   : 0.5.3
cocoapods-trunk   : 0.6.1
cocoapods-try     : 0.4.5
```

### Podfile

```ruby
platform :ios, '8.0'

pod 'pop', '~> 1.0'
pod 'ChameleonFramework'
pod 'AMWaveTransition'
pod 'DACircularProgress'
pod 'EAIntroView', '~> 2.6.0'
pod 'SDWebImage', '~>3.6'
pod 'DAAppsViewController'
pod 'DateTools'
pod 'Nimble-CoreData'
pod 'AFNetworking', '~> 2.0'
pod 'DZNWebViewController'
pod 'YKMediaPlayerKit'
pod 'ionicons'
```

### Error

```
ArgumentError - comparison of NilClass with String failed
/Users/xxxxxx/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-0.38.2/lib/cocoapods/installer/analyzer/specs_state.rb:54:in `sort'
/Users/xxxxxx/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-0.38.2/lib/cocoapods/installer/analyzer/specs_state.rb:54:in `print'
/Users/xxxxxx/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-0.38.2/lib/cocoapods/installer/analyzer.rb:580:in `block in generate_sandbox_state'
/Users/xxxxxx/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:59:in `section'
/Users/xxxxxx/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-0.38.2/lib/cocoapods/installer/analyzer.rb:577:in `generate_sandbox_state'
/Users/xxxxxx/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-0.38.2/lib/cocoapods/installer/analyzer.rb:73:in `analyze'
/Users/xxxxxx/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:210:in `analyze'
/Users/xxxxxx/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:133:in `block in resolve_dependencies'
/Users/xxxxxx/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:59:in `section'
/Users/xxxxxx/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:132:in `resolve_dependencies'
/Users/xxxxxx/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:104:in `install!'
/Users/xxxxxx/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/xxxxxx/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:101:in `run'
/Users/xxxxxx/.rvm/gems/ruby-2.2.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Users/xxxxxx/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/Users/xxxxxx/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
/Users/xxxxxx/.rvm/gems/ruby-2.2.0/bin/pod:23:in `load'
/Users/xxxxxx/.rvm/gems/ruby-2.2.0/bin/pod:23:in `<main>'
/Users/xxxxxx/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
/Users/xxxxxx/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=comparison+of+NilClass+with+String+failed&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

**Comment by robmontesinos** [comment]
Turns out 'ionicons' was the culprit - I removed it from Podfile and pod install worked as expected - thank you

**Comment by Iamparth7069** [comment]
Or undo this operation with:

           git switch -

         Turn off this advice by setting config variable advice.detachedHead to false

    Searching for inspections failed: undefined method `map' for nil:NilClass
 Solve this Error
