### ISSUE TITLE
No such file or directory, /Pods/AppMonitorBundle/AppMonitorBundle.framework/Headers

### ISSUE THREAD

**Issue by christyuj** [CocoaPods/CocoaPods#3967]
hello
  when i use a framework without any headers in 0.38.2, it happened. when i use 0.35 it works. because our project use plist to describe classname and use classname to init , so our project has a lot of framework without headers. how can i do for it , Waiting for your reply，thank you very much。

### Stack

```
   CocoaPods : 0.38.2
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.4.2
        Host : Mac OS X 10.10.4 (14E46)
       Xcode : 6.4 (6E35b)
         Git : git version 2.3.2 (Apple Git-55)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib

```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-stats   : 0.5.3
cocoapods-trunk   : 0.6.1
cocoapods-try     : 0.4.5
```
### Error

```
Errno::ENOENT - No such file or directory - /Pods/AppMonitorBundle/AppMonitorBundle.framework/Headers
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/sandbox/file_accessor.rb:161:in `realpath'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/sandbox/file_accessor.rb:161:in `realpath'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/sandbox/file_accessor.rb:161:in `vendored_frameworks_headers_dir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:239:in `block in vendored_frameworks_header_mappings'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:238:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:238:in `vendored_frameworks_header_mappings'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:140:in `block (3 levels) in link_headers'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:117:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:117:in `block (2 levels) in link_headers'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:116:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:116:in `block in link_headers'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:140:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:115:in `link_headers'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:41:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:562:in `install_file_references'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:152:in `block in generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:150:in `generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:110:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:156:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

**Comment by christyuj** [comment]
i debug it in local and i write some code to avoid frameworks'heads  crash. it works and i will commit later
...

**Comment by segiddins** [comment]
This is fixed on `master`.

**Comment by christyuj** [comment]
great thanks for segiddins ~！

**Comment by segiddins** [comment]
Ah sorry, misread this issue. It's not fixed.

**Comment by christyuj** [comment]
segiddins，i do not know how to fork the master by using rainforest， I just fork cocoapods in local and debug， so the envrionment maybe not as same as yours。 At last I use ruby-plugin like this to fix it , you can try:

module Pod
  class Sandbox
    class FileAccessor
      # @param  [Pathname] framework
      #         The vendored framework to search into.
      # @return [Pathname] The path of the header directory of the
      #         vendored framework.
      #
      def self.vendored_frameworks_headers_dir(framework)
        headers_dir = framework + 'Headers'
        if headers_dir.exist?
          headers_dir.realpath
        else
          headers_dir
        end
      end
    end
  end
end
