### ISSUE TITLE
Error after use pod install (or update)

### ISSUE THREAD

**Issue by prlnze** [CocoaPods/CocoaPods#3976]
### Command

```
/usr/bin/pod update
```

### Report

* What did you do?

Merged file in source tree (some using TextEditor) after the project can open successfully run pod install (also update)

// I tried to remove pod files and init again but not work at all too

* What did you expect to happen?
pod install / update successfully 

* What happened instead?
the error come out

### Stack

```
   CocoaPods : 0.38.2
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.0.14
        Host : Mac OS X 10.10.1 (14B25)
       Xcode : 6.3.2 (6D2105)
         Git : git version 2.3.2 (Apple Git-55)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 14f639646bec579017cec59294c67ab5d2e4d95a
```

### Plugins

```
cocoapods-deintegrate : 0.2.1
cocoapods-plugins     : 0.4.2
cocoapods-stats       : 0.5.3
cocoapods-trunk       : 0.6.1
cocoapods-try         : 0.4.5
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

platform :ios, '7.0'
pod 'ZXingObjC'
pod 'MWPhotoBrowser', '~> 1.4'
pod 'GoogleMaps'
```

### Error

```
NoMethodError - undefined method `source_tree' for #<Xcodeproj::Project::Object::XCBuildConfiguration:0x007fbab67c54e8>
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.26.3/lib/xcodeproj/project/object/helpers/groupable_helper.rb:116:in `source_tree_real_path'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.26.3/lib/xcodeproj/project/object/helpers/groupable_helper.rb:100:in `real_path'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.26.3/lib/xcodeproj/project/object/helpers/groupable_helper.rb:121:in `source_tree_real_path'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.26.3/lib/xcodeproj/project/object/helpers/groupable_helper.rb:100:in `real_path'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.26.3/lib/xcodeproj/project/object/file_reference.rb:163:in `real_path'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:56:in `block (2 levels) in update_to_cocoapods_0_34'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:53:in `select'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:53:in `block in update_to_cocoapods_0_34'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:52:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:52:in `update_to_cocoapods_0_34'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:24:in `block (2 levels) in integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:23:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:23:in `block in integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:22:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:22:in `integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/user_project_integrator/target_integrator.rb:39:in `block in integrate!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/user_project_integrator/target_integrator.rb:36:in `integrate!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/user_project_integrator.rb:116:in `block in integrate_user_targets'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/user_project_integrator.rb:115:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/user_project_integrator.rb:115:in `integrate_user_targets'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/user_project_integrator.rb:63:in `integrate!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:708:in `block in integrate_user_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:705:in `integrate_user_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:111:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:156:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

**Comment by segiddins** [comment]
@prlnze does the merged Xcode project still open in Xcode?

**Comment by prlnze** [comment]
@segiddins yes, it is

**Comment by segiddins** [comment]
In that case, could you post the project file so someone can look into debugging? Thanks!

**Comment by prlnze** [comment]
so did you mean xcodeproject file right ?

**Comment by segiddins** [comment]
yes please

**Comment by prlnze** [comment]
I think I cannot give you an project file due to the privacy of the company i work for.

FYI, I reset merge and added file manually. now it can use pod again
