### ISSUE TITLE
Couldn't update pods when using http/https_proxy in terminal

### ISSUE THREAD

**Issue by Cee** [CocoaPods/CocoaPods#3990]
Used to work, but now it can't. :(

### Command

```
/usr/local/bin/pod update
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 0.38.2
        Ruby : ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
    RubyGems : 2.4.5
        Host : Mac OS X 10.10.4 (14E46)
       Xcode : 6.4 (6E35b)
         Git : git version 2.3.2 (Apple Git-55)
Ruby lib dir : /usr/local/Cellar/ruby/2.2.2/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ a9e79fcba3fa93321695b3fb604965d123da43da
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-stats   : 0.5.3
cocoapods-trunk   : 0.6.1
cocoapods-try     : 0.4.5
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

target 'neptune' do
pod 'AFNetworking'
pod 'YTKNetwork'
pod 'SDWebImage'
pod 'MJExtension'
pod 'MJRefresh'
pod 'libextobjc'
pod 'MBProgressHUD'
pod 'Masonry'
end
```

### Error

```
URI::InvalidURIError - bad URI(is not URI?): 127.0.0.1:20145
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/uri/rfc3986_parser.rb:66:in `split'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/uri/rfc3986_parser.rb:72:in `parse'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/uri/common.rb:226:in `parse'
/usr/local/lib/ruby/gems/2.2.0/gems/nap-0.8.0/lib/rest/request.rb:93:in `proxy_settings'
/usr/local/lib/ruby/gems/2.2.0/gems/nap-0.8.0/lib/rest/request.rb:97:in `http_proxy'
/usr/local/lib/ruby/gems/2.2.0/gems/nap-0.8.0/lib/rest/request.rb:104:in `http_request'
/usr/local/lib/ruby/gems/2.2.0/gems/nap-0.8.0/lib/rest/request.rb:185:in `perform'
/usr/local/lib/ruby/gems/2.2.0/gems/nap-0.8.0/lib/rest/request.rb:200:in `perform'
/usr/local/lib/ruby/gems/2.2.0/gems/nap-0.8.0/lib/rest.rb:103:in `post'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-stats-0.5.3/lib/cocoapods_stats/sender.rb:8:in `send'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-stats-0.5.3/lib/cocoapods_plugin.rb:42:in `block (2 levels) in <module:CocoaPodsStats>'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:80:in `titled_section'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-stats-0.5.3/lib/cocoapods_plugin.rb:27:in `block in <module:CocoaPodsStats>'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/hooks_manager.rb:115:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/hooks_manager.rb:115:in `block (3 levels) in run'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:140:in `message'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/hooks_manager.rb:111:in `block (2 levels) in run'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/hooks_manager.rb:109:in `each'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/hooks_manager.rb:109:in `block in run'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:140:in `message'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/hooks_manager.rb:108:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:453:in `run_plugins_post_install_hooks'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:444:in `perform_post_install_actions'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:112:in `install!'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:156:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by segiddins** [comment]
@Cee what are your HTTP proxy settings?

**Comment by orta** [comment]
Could your proxy need a `http://` before the `127.0.0.1:20145`?

**Comment by Cee** [comment]
@segiddins @orta 
I set my proxy in `.zshrc` like this below:
```
export http_proxy=127.0.0.1:20145
export https_proxy=127.0.0.1:20145
```

**Comment by segiddins** [comment]
So the issue there is that's not an HTTP nor HTTPS URL

**Comment by Cee** [comment]
After changing my proxy:
```
export http_proxy=http://127.0.0.1:20145
export https_proxy=https://127.0.0.1:20145
```

It works now! 😊
