### ISSUE TITLE
Errno::EPERM - Operation not permitted - /Users/Shared/Code/MyApp/Pods

### ISSUE THREAD

**Issue by stuffmc** [CocoaPods/CocoaPods#4005]
### Command

```
/usr/bin/pod update
```

### Report

* What did you do?
`pod update`

* What did you expect to happen?
update...

* What happened instead?
error...

### Stack

```
   CocoaPods : 0.38.2
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.0.14
        Host : Mac OS X 10.10.4 (14E46)
       Xcode : 6.4 (6E35b)
         Git : git version 2.3.2 (Apple Git-55)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : artsy - https://github.com/artsy/Specs.git @ 645efcc8ecbd3fcfc44770e265b8436a7664f1bf
               master - https://github.com/CocoaPods/Specs.git @ 4c8f8b7e5878cfb61cc87b68f9a67ab48bb6223d
```

### Plugins

```
cocoapods-deintegrate : 0.2.1
cocoapods-plugins     : 0.4.2
cocoapods-stats       : 0.5.3
cocoapods-trunk       : 0.4.0
cocoapods-try         : 0.4.5
```

### Podfile

```ruby
source 'https://github.com/artsy/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'

target 'foo' do    
	pod 'ZBarSDK'
	pod 'AFNetworking','1.3.3'
	pod 'RestKit', '~>  0.20.0'
	pod 'MBProgressHUD'
	pod 'JASidePanels', '~> 1.3.2'
	pod 'PDKeychainBindingsController', '~> 0.0.1'
	pod 'OpenSSL'
	pod 'FlurrySDK'
end
```

### Error

```
Errno::EPERM - Operation not permitted - /Users/Shared/Code/MyApp/Pods
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1327:in `chmod'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1327:in `chmod'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1000:in `block (2 levels) in chmod_R'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1460:in `preorder_traverse'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:998:in `block in chmod_R'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:997:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:997:in `chmod_R'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:117:in `block in prepare'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:140:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:116:in `prepare'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:103:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:156:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

**Comment by orta** [comment]
Any further context? Did it work on version `x` etc. From just the stack trace I'm not quite sure.

 We have a [contributing guide](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md) that offers ways to provide more useful feedback.

**Comment by kylef** [comment]
@stuffmc What's the file permissions for `/Users/Shared/Code/MyApp/Pods`?

```
$ ls -lead /Users/Shared/Code/MyApp/Pods
```

**Comment by stuffmc** [comment]
@kylef ` 0: group:admin allow list,add_file,search,add_subdirectory,delete_child,readattr,writeattr,readextattr,writeextattr,read security`

**Comment by stuffmc** [comment]
@orta AFAIR worked fine on the 0.38 betas — I have 0.38.2   (and what's up with that numbering.... worst than Chrome — but it's another subject).  Thanks for helping, guys! 🌈

**Comment by stuffmc** [comment]
FYI @orta @kylef: It has definitely something to do with `/Users/Shared/` I moved back the project to `~/` and I have no problems.

**Comment by neonichu** [comment]
@stuffmc could you paste the full output of `ls -lead`? Yours is missing the first line.

**Comment by stuffmc** [comment]
@neonichu @orta @kylef 

```
drwxrwxrwx+ 18 root  wheel  612 Aug 11 11:52 Pods
0: group:admin allow list,add_file,search,add_subdirectory,delete_child,
readattr,writeattr,readextattr,writeextattr,read security
```

**Comment by neonichu** [comment]
OK, so you don't own it, that's why you can't change permissions — I wonder if we should skip the locking of the sandbox in that case, as this is separate from being able to write it. Kinda an edge case, though.

**Comment by segiddins** [comment]
I definitely think this is an edge case we don't really need to handle.
