### ISSUE TITLE
Can't push pod after refactoring

### ISSUE THREAD

**Issue by Dreddik** [CocoaPods/CocoaPods#4068]
Trying to push or at least validate pod:
```
pod spec lint --verbose

 -> VK-ios-sdk (1.2.0)
    - ERROR | Encountered an unknown error (end of file reached) during validation.

Analyzed 1 podspec.

[!] The spec did not pass validation, due to 1 error.

/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/spec/lint.rb:72:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

I don't understand, which file is ended.

Pod location: https://github.com/VKCOM/vk-ios-sdk

**Comment by neonichu** [comment]
This seems to be the same issue as #4066:

```bash
$ curl -I https://vk.com/dev/ios_sdk
curl: (52) Empty reply from server```

The server you have specified for `homepage` acts unexpectedly to HEAD requests.
