### ISSUE TITLE
Pod Install failure ArgumentError - Illformed requirement `"= "`

### ISSUE THREAD

**Issue by wraithseeker** [CocoaPods/CocoaPods#4157]
### Report

* What did you do?
Reinstalled Cocoapods and ran pod install on my xcodj project folder

* What did you expect to happen?
To install all the necessary pod files 
* What happened instead?
Came up with ArgumentError - Illformed requirement `"= "`

### Stack

```
   CocoaPods : 0.38.2
        Ruby : ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
    RubyGems : 2.4.8
        Host : Mac OS X 10.10.5 (14F27)
       Xcode : 6.4 (6E35b)
         Git : git version 2.5.1
Ruby lib dir : /Users/wraithseeker/.rvm/rubies/ruby-2.2.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ ec19bdd16e7e1be48d47689932c597ed9f0d91ee
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-stats   : 0.5.3
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.4.5
```

### Podfile

```ruby
platform :ios, '8.0'

pod 'SVProgressHUD'
pod 'MWFeedParser'
pod 'AFNetworking'
pod 'HTMLReader'
pod 'SVWebViewController', :headn
pod 'MBProgressHUD', '~> 0.9.1'
```

### Error

```
ArgumentError - Illformed requirement `:headn`
/Users/wraithseeker/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-core-0.38.2/lib/cocoapods-core/requirement.rb:61:in `parse'
/Users/wraithseeker/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-core-0.38.2/lib/cocoapods-core/vendor/requirement.rb:132:in `block in initialize'
/Users/wraithseeker/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-core-0.38.2/lib/cocoapods-core/vendor/requirement.rb:132:in `map!'
/Users/wraithseeker/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-core-0.38.2/lib/cocoapods-core/vendor/requirement.rb:132:in `initialize'
/Users/wraithseeker/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-core-0.38.2/lib/cocoapods-core/requirement.rb:32:in `new'
/Users/wraithseeker/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-core-0.38.2/lib/cocoapods-core/requirement.rb:32:in `create'
/Users/wraithseeker/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-core-0.38.2/lib/cocoapods-core/dependency.rb:92:in `initialize'
/Users/wraithseeker/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-core-0.38.2/lib/cocoapods-core/podfile/target_definition.rb:650:in `new'
/Users/wraithseeker/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-core-0.38.2/lib/cocoapods-core/podfile/target_definition.rb:650:in `block in pod_dependencies'
/Users/wraithseeker/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-core-0.38.2/lib/cocoapods-core/podfile/target_definition.rb:646:in `map'
/Users/wraithseeker/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-core-0.38.2/lib/cocoapods-core/podfile/target_definition.rb:646:in `pod_dependencies'
/Users/wraithseeker/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-core-0.38.2/lib/cocoapods-core/podfile/target_definition.rb:87:in `non_inherited_dependencies'
/Users/wraithseeker/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-core-0.38.2/lib/cocoapods-core/podfile/target_definition.rb:77:in `dependencies'
/Users/wraithseeker/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/installer/podfile_validator.rb:59:in `block in validate_pod_directives'
/Users/wraithseeker/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/installer/podfile_validator.rb:58:in `each'
/Users/wraithseeker/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/installer/podfile_validator.rb:58:in `flat_map'
/Users/wraithseeker/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/installer/podfile_validator.rb:58:in `validate_pod_directives'
/Users/wraithseeker/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/installer/podfile_validator.rb:29:in `validate'
/Users/wraithseeker/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/installer/analyzer.rb:155:in `validate_podfile!'
/Users/wraithseeker/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/installer/analyzer.rb:57:in `analyze'
/Users/wraithseeker/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:210:in `analyze'
/Users/wraithseeker/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:133:in `block in resolve_dependencies'
/Users/wraithseeker/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:59:in `section'
/Users/wraithseeker/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:132:in `resolve_dependencies'
/Users/wraithseeker/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:104:in `install!'
/Users/wraithseeker/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/wraithseeker/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:101:in `run'
/Users/wraithseeker/.rvm/gems/ruby-2.2.1@global/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Users/wraithseeker/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/Users/wraithseeker/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
/Users/wraithseeker/.rvm/rubies/ruby-2.2.1/bin/pod:23:in `load'
/Users/wraithseeker/.rvm/rubies/ruby-2.2.1/bin/pod:23:in `<main>'
/Users/wraithseeker/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
/Users/wraithseeker/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by neonichu** [comment]
The error message is correct here, there's no option `:headn` — you probably meant to use `:head`.
