### ISSUE TITLE
[!] An error occurred while processing the post-install hook of the Podfile.

### ISSUE THREAD

**Issue by Jules2010** [CocoaPods/CocoaPods#4164]
I saw this other issue https://github.com/CocoaPods/CocoaPods/issues/3747  but this didn't help me

I updated to the pre release version of cocoapods and hadn't made any changes to my pod file.
I've since uninstalled the pre release version and the problem still occurs, help !!

```
pod install
Updating local specs repositories

CocoaPods 0.39.0.beta.4 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
Downloading dependencies
Using Bolts (1.1.5)
Using CustomIOSAlertView (0.9.3)
Using Dropbox-iOS-SDK (1.3.13)
Using FlurrySDK (4.3.2)
Using Google-Mobile-Ads-SDK (6.12.2)
Using JTCalendar (1.2.3)
Using LARSAdController (3.0.7)
Using MZAppearance (1.1.5)
Using MZFormSheetController (3.1.0)
Using Parse (1.4.2)
Using RESideMenu (4.0.7)
Using SDiPhoneVersion (1.1.2)
Using UIDeviceIdentifier (0.4.4)
Using WSLViewAutoDismiss (1.0.1)
Installing WYPopoverController 0.3.8 (was 0.3.8)
Generating Pods project
[!] An error occurred while processing the post-install hook of the Podfile.

undefined method `project' for #<Pod::Installer:0x007fdb4d885498>

/Users/jm/Dropbox/Code_ObjC/BalanceGuide/Podfile:70:in `block (2 levels) in from_ruby'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.38.2/lib/cocoapods-core/podfile.rb:170:in `call'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.38.2/lib/cocoapods-core/podfile.rb:170:in `post_install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:764:in `run_podfile_post_install_hook'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:752:in `block in run_podfile_post_install_hooks'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:140:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:751:in `run_podfile_post_install_hooks'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:155:in `block in generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:150:in `generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:110:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

Here's my pod file

```
source 'https://github.com/CocoaPods/Specs.git'

#use_frameworks! - DON'T !!!
platform :ios, :deployment_target => "7.1"

target :MyApp do
    pod 'UIDeviceIdentifier', :git => 'https://github.com/squarefrog/UIDeviceIdentifier.git' #'~> 0.4.4',
    #pod 'MFSideMenu', '~> 0.4.8', :inhibit_warnings => true #was 0.4.8
    pod 'RESideMenu', '~> 4.0.7'
    #pod 'CrashlyticsFramework', '~> 2.2.2'
    pod 'Parse', '~> 1.4.0'
    #pod 'Facebook-iOS-SDK', '~> 3.23.2', :inhibit_warnings => true #3.11.1' - version before cocoapods
    pod 'FlurrySDK', '~> 4.3.2'
    pod 'Dropbox-iOS-SDK', '~> 1.3.13'
    pod 'CustomIOSAlertView', '~> 0.9.3'
    #pod 'MZFormSheetController', '~> 3.0.3'
    pod 'MZFormSheetController', '~> 3.1.0'
    pod 'WYPopoverController', :git => 'https://github.com/sammcewan/WYPopoverController.git', :inhibit_warnings => true  #'~>0.3.7'
    
    #pod 'WYPopoverController', :git => 'https://github.com/tomhamming/WYPopoverController.git', :inhibit_warnings => true  #6e6d6535c218335e5ccfea375f2fee48eff4fb6c
    
    #pod  'ChimpKit', '~> 3.1.1'
    pod 'JTCalendar', '~> 1.2.3'
    pod 'SDiPhoneVersion', '~> 1.1.2'
    pod 'WSLViewAutoDismiss', '~> 1.0'
end

target :MyAppFree do
    link_with 'BGFree'
    pod 'UIDeviceIdentifier', :git => 'https://github.com/squarefrog/UIDeviceIdentifier.git' #'~> 0.4.4',
    #pod 'MFSideMenu', '~> 0.4.8', :inhibit_warnings => true #was 0.4.8
    pod 'RESideMenu', '~> 4.0.7'
    #pod 'CrashlyticsFramework', '~> 2.2.2'
    pod 'Parse', '~> 1.4.0'
    #pod 'Facebook-iOS-SDK', '~> 3.23.2', :inhibit_warnings => true #3.11.1' - version before cocoapods
    pod 'FlurrySDK', '~> 4.3.2'
    pod 'Dropbox-iOS-SDK', '~> 1.3.13'
    pod 'CustomIOSAlertView', '~> 0.9.3'
    #pod 'MZFormSheetController', '~> 3.0.3'
    pod 'MZFormSheetController', '~> 3.1.0'
    pod 'WYPopoverController', :git => 'https://github.com/sammcewan/WYPopoverController.git', :inhibit_warnings => true  #'~>0.3.7'
    
    #pod 'WYPopoverController', :git => 'https://github.com/tomhamming/WYPopoverController.git', :inhibit_warnings => true  #6e6d6535c218335e5ccfea375f2fee48eff4fb6c
    
    #pod  'ChimpKit', '~> 3.1.1'
    pod 'JTCalendar', '~> 1.2.3'
    pod 'LARSAdController', '~> 3.0.7'
    pod 'Google-Mobile-Ads-SDK', '~> 6.0'#'~> 7.2.2' #6.12.2'
    #pod 'IAPValidation', :git => 'https://github.com/williamlocke/IAPValidation.git', :commit => '5042d42d6801707dc286c549238f5bf39e741702'
    pod 'SDiPhoneVersion', '~> 1.1.2'
    pod 'WSLViewAutoDismiss', '~> 1.0'
end

post_install do |installer_representation|
    installer_representation.project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
            #config.build_settings['MACH_O_TYPE'] = 'staticlib'
        end
    end
end
```

**Comment by neonichu** [comment]
See "Breaking changes to the Hooks API" in http://blog.cocoapods.org/CocoaPods-0.38/
