### ISSUE TITLE
Pod Update leads to ENOENT - No such file or directory

### ISSUE THREAD

**Issue by hertanu** [CocoaPods/CocoaPods#4186]
### Command

```
/usr/bin/pod install
```

### Report

* What did you do?
Ran pod install or pod update
* What did you expect to happen?
pods getting udpated
* What happened instead?
Error as listed below

### Stack

```
   CocoaPods : 0.38.2
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.0.14
        Host : Mac OS X 10.10.5 (14F27)
       Xcode : 6.4 (6E35b)
         Git : git version 2.3.2 (Apple Git-55)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ bf957b2a0f3ae25115f66272b3b5854136bcfd16
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-stats   : 0.5.3
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.4.5
```

### Podfile

```ruby
platform :ios, '7.0'

link_with '24me', '24me WatchKit Extension'

pod 'AFNetworking',		'~> 2.4'
pod 'GoogleAnalytics-iOS-SDK', '~> 3.10'
pod 'SDWebImage', '~> 3.7'
pod 'FMDB', '2.2'
pod 'OBShapedButton', '1.0.1'
pod 'TPKeyboardAvoiding', '0.0.1'
pod 'UIDeviceIdentifier', '0.1'
pod 'UIDeviceAddition', '1.0'
target '24me' do
    pod 'Mixpanel'
end

target '24me WatchKit Extension' do
    pod 'Mixpanel/AppExtension'
end

pod 'RESideMenu', '~> 4.0.4'
pod 'MZTimerLabel', '~> 0.1'
pod 'PBJVision', '~>0.3.3'
pod 'FLEX', '~> 1.1'
pod 'WebViewJavascriptBridge', '~>4.1.0'
pod 'Facebook-iOS-SDK', '3.24'
pod 'TGJSBridge'
pod 'Amplitude-iOS', '~> 2.2'
pod 'JSONKit', '= 1.5pre'
pod 'DTRichTextEditor'
pod 'CMPopTipView'
pod 'RHAddressBook'
```

### Error

```
Errno::ENOENT - No such file or directory - /Users/giladhertanu/iphone_app/Pods/BuildHeaders/MMWormhole/MMWormhole.h
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:905:in `stat'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:905:in `symbolic_modes_to_i'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:926:in `fu_mode'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1000:in `block (2 levels) in chmod_R'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1460:in `preorder_traverse'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:998:in `block in chmod_R'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:997:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:997:in `chmod_R'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:117:in `block in prepare'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:140:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:116:in `prepare'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:103:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'

**Comment by maciekish** [comment]
What caused this?

**Comment by dreese** [comment]
Looks like a dup of #4227?
