### ISSUE TITLE
Cannot define platform per target

### ISSUE THREAD

**Issue by kernandreas** [CocoaPods/CocoaPods#4201]
This worked until the update to version 0.38.2. Is there a different way to use a podfile across multiple platforms?

### Command

```
/usr/bin/pod update
```

### Stack

```
   CocoaPods : 0.38.2
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.0.14
        Host : Mac OS X 10.10.5 (14F27)
       Xcode : 6.4 (6E35b)
         Git : git version 2.4.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : cocoapod-specs - scm.iplabs.de:/git/mac/cocoapod-specs.git @ e3c3a481c86cd927ed2dff1434acb7339b831239
               master - https://github.com/CocoaPods/Specs.git @ d8856241ae9549636695c3669fccde8dc9b42551
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-stats   : 0.5.3
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.4.5
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'

target 'Target OSX' do
	platform :osx, '10.7.0'

	pod 'HockeySDK-Mac'
	pod 'CocoaLumberjack', '~> 2.0'
	pod 'AFNetworking', '~> 1.0'
	pod 'SSZipArchive'
	pod 'yajl', :inhibit_warnings => true
	pod 'yajl-objc', :inhibit_warnings => true
	pod 'Sparkle', '~> 1.10.1-alpha', :configurations => ['Sparkle']
	pod 'GCDWebServer'
end

target 'Target iOS' do
	platform :ios, '7.0'

	pod 'HockeySDK'
	pod 'CocoaLumberjack', '~> 2.0'
	pod 'AFNetworking', '~> 1.0'
	pod 'SSZipArchive'
	pod 'yajl', :inhibit_warnings => true
	pod 'yajl-objc', :inhibit_warnings => true
	pod 'SVProgressHUD'
	pod 'GCDWebServer'
end
```

### Error

```
Pod::Podfile::StandardError - Unsupported platform ``. Platform must be `:ios`, `:osx`, or `:watchos`.
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.38.2/lib/cocoapods-core/podfile/target_definition.rb:441:in `set_platform'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/analyzer/target_inspector.rb:153:in `compute_platform'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/analyzer/target_inspector.rb:40:in `compute_results'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/analyzer.rb:655:in `block (2 levels) in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/analyzer.rb:653:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/analyzer.rb:653:in `block in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/analyzer.rb:652:in `inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/analyzer.rb:61:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:210:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:133:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:132:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:104:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:156:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

**Comment by segiddins** [comment]
I actually can't reproduce this with `master` and the given Podfile... Are there any further steps necessary to reproduce the issue?

**Comment by kernandreas** [comment]
I have found the problem. I am setting the Base SDK in a xcconfig file and therefore removed the Base SDK setting at project level. Selecting any Base SDK at project level, which will be overridden by the xcconfig, fixed my problem.

**Comment by segiddins** [comment]
Awesome, glad you figured it out!
