### ISSUE TITLE
cannot infer basepath

### ISSUE THREAD

**Issue by ferranvila** [CocoaPods/CocoaPods#4210]
### Command

```
/Users/administrator/.rvm/gems/ruby-2.1.2/bin/pod install
```

### Stack

```
   CocoaPods : 0.37.1
        Ruby : ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin13.0]
    RubyGems : 2.4.5
        Host : Mac OS X 10.10.5 (14F27)
       Xcode : 7.0 (7A220)
         Git : git version 2.3.8 (Apple Git-58)
Ruby lib dir : /Users/administrator/.rvm/rubies/ruby-2.1.2/lib
Repositories : adaptiveme - https://github.com/AdaptiveMe/adaptive-arp-darwin.git @ 6dcd976fc7b4161404a0232fcaca556081598470
               master - https://github.com/CocoaPods/Specs.git @ bbaa5192998a0b16bd353885e38e2e0570e759fc
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-trunk   : 0.6.0
cocoapods-try     : 0.4.4
```

### Podfile

```ruby
xcodeproj 'adaptive-arp-rt.xcodeproj'
platform :ios, '8.0'
use_frameworks!
pod 'AdaptiveArpApi', '2.2.14'
pod 'CryptoSwift', '0.0.10'
pod 'SQLite.swift', git: 'https://github.com/stephencelis/SQLite.swift.git', branch: 'swift-2'
```

### Error

```
LoadError - cannot infer basepath
/var/folders/st/l41vm26n1n7f20p86nzs2kgm0000gn/T/d20150918-12427-1uy6uub/SQLite.swift.podspec:1:in `require_relative'
/var/folders/st/l41vm26n1n7f20p86nzs2kgm0000gn/T/d20150918-12427-1uy6uub/SQLite.swift.podspec:1:in `_eval_podspec'
/Users/administrator/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-core-0.37.1/lib/cocoapods-core/specification.rb:607:in `eval'
/Users/administrator/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-core-0.37.1/lib/cocoapods-core/specification.rb:607:in `_eval_podspec'
/Users/administrator/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-core-0.37.1/lib/cocoapods-core/specification.rb:556:in `block in from_string'
/Users/administrator/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-core-0.37.1/lib/cocoapods-core/specification.rb:553:in `chdir'
/Users/administrator/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-core-0.37.1/lib/cocoapods-core/specification.rb:553:in `from_string'
/Users/administrator/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-core-0.37.1/lib/cocoapods-core/specification.rb:536:in `from_file'
/Users/administrator/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.37.1/lib/cocoapods/sandbox/podspec_finder.rb:16:in `block in podspecs'
/Users/administrator/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.37.1/lib/cocoapods/sandbox/podspec_finder.rb:14:in `each'
/Users/administrator/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.37.1/lib/cocoapods/sandbox/podspec_finder.rb:14:in `podspecs'
/Users/administrator/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.37.1/lib/cocoapods/downloader.rb:70:in `download_request'
/Users/administrator/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.37.1/lib/cocoapods/downloader/cache.rb:118:in `download'
/Users/administrator/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.37.1/lib/cocoapods/downloader/cache.rb:102:in `block in uncached_pod'
/Users/administrator/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.37.1/lib/cocoapods/downloader/cache.rb:128:in `call'
/Users/administrator/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.37.1/lib/cocoapods/downloader/cache.rb:128:in `in_tmpdir'
/Users/administrator/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.37.1/lib/cocoapods/downloader/cache.rb:101:in `uncached_pod'
/Users/administrator/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.37.1/lib/cocoapods/downloader/cache.rb:31:in `download_pod'
/Users/administrator/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.37.1/lib/cocoapods/downloader.rb:34:in `download'
/Users/administrator/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.37.1/lib/cocoapods/external_sources/abstract_external_source.rb:101:in `block in pre_download'
/Users/administrator/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.37.1/lib/cocoapods/user_interface.rb:70:in `titled_section'
/Users/administrator/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.37.1/lib/cocoapods/external_sources/abstract_external_source.rb:99:in `pre_download'
/Users/administrator/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.37.1/lib/cocoapods/external_sources/downloader_source.rb:13:in `fetch'
/Users/administrator/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.37.1/lib/cocoapods/installer/analyzer.rb:347:in `fetch_external_source'
/Users/administrator/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.37.1/lib/cocoapods/installer/analyzer.rb:324:in `block (2 levels) in fetch_external_sources'
/Users/administrator/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.37.1/lib/cocoapods/installer/analyzer.rb:323:in `each'
/Users/administrator/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.37.1/lib/cocoapods/installer/analyzer.rb:323:in `block in fetch_external_sources'
/Users/administrator/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.37.1/lib/cocoapods/user_interface.rb:49:in `section'
/Users/administrator/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.37.1/lib/cocoapods/installer/analyzer.rb:322:in `fetch_external_sources'
/Users/administrator/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.37.1/lib/cocoapods/installer/analyzer.rb:57:in `analyze'
/Users/administrator/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.37.1/lib/cocoapods/installer.rb:190:in `analyze'
/Users/administrator/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.37.1/lib/cocoapods/installer.rb:112:in `block in resolve_dependencies'
/Users/administrator/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.37.1/lib/cocoapods/user_interface.rb:49:in `section'
/Users/administrator/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.37.1/lib/cocoapods/installer.rb:111:in `resolve_dependencies'
/Users/administrator/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.37.1/lib/cocoapods/installer.rb:91:in `install!'
/Users/administrator/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.37.1/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/administrator/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.37.1/lib/cocoapods/command/project.rb:101:in `run'
/Users/administrator/.rvm/gems/ruby-2.1.2@global/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Users/administrator/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.37.1/lib/cocoapods/command.rb:46:in `run'
/Users/administrator/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-0.37.1/bin/pod:44:in `<top (required)>'
/Users/administrator/.rvm/gems/ruby-2.1.2/bin/pod:23:in `load'
/Users/administrator/.rvm/gems/ruby-2.1.2/bin/pod:23:in `<main>'
/Users/administrator/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
/Users/administrator/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by segiddins** [comment]
Interesting... Thanks for reporting this!

**Comment by neonichu** [comment]
@segiddins could you repro it? Seems to work fine for me.

**Comment by segiddins** [comment]
No, haven't repro'd. Just figured I would be able to with the given Podfile.

**Comment by segiddins** [comment]
I can't reproduce this either. Please share a project we can use to debug the issue, thanks!

**Comment by ferranvila** [comment]
I've updated Cocoapods to the last stable version and the error has disappeared. Now I have an error on the podspec of the library 😅
