### ISSUE TITLE
running "pod install" or "pod update" gives this error

### ISSUE THREAD

**Issue by takdol** [CocoaPods/CocoaPods#4214]
Hi! Cocoapods is just awesome. 

On to the point. After running "pod install" for the first time in a project, I can't add, remove or update my pods again. Here's the template:

### Command

```
/usr/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 0.38.2
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.0.14
        Host : Mac OS X 10.10.5 (14F27)
       Xcode : 7.0 (7A220)
         Git : git version 2.3.8 (Apple Git-58)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 9dbaf3db5794dd86c5690ff1fd4f548417504860
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-stats   : 0.5.3
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.4.5
```

### Podfile

```ruby
platform :ios, "8.0"
use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

pod 'AFNetworking', '~> 2.5'
#pod 'HockeySDK', '~> 3.6'
#pod 'Socket.IO-Client-Swift', '~> 2.3'
pod 'CocoaHTTPServer', '~> 2.3'
pod 'LDProgressView', '~> 1.2'
pod 'OBSlider', '~> 1.1'
pod 'CocoaLumberjack', '~> 2.0'
pod 'SSKeychain', '~> 1.2'
pod 'MBProgressHUD', '~> 0.9'
pod 'RTLabel', '~> 1.0'
pod 'UIAlertView-Blocks', '~> 1.0'
pod 'MKStoreKit', :head
pod 'Pushwoosh', '~> 2.13'
pod 'IQKeyboardManager'
```

### Error

```
Errno::ENOENT - No such file or directory - /Users/spuul/Desktop/iOS/spuul-ios-v3/Spuul/Pods/Pushwoosh/Framework/Pushwoosh.framework/Resources
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:905:in `stat'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:905:in `symbolic_modes_to_i'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:926:in `fu_mode'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1000:in `block (2 levels) in chmod_R'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1460:in `preorder_traverse'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:998:in `block in chmod_R'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:997:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:997:in `chmod_R'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:117:in `block in prepare'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:140:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:116:in `prepare'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:103:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

Tried understanding it, and I THINK the Pushwoosh framework is to be "blamed" here. 

Running pod version: 0.38.2
xcodeproj version: (0.27.2, 0.26.3, 0.24.3, 0.24.2, 0.23.0)

**Comment by segiddins** [comment]
This has been resolved in the 0.39 betas
