### ISSUE TITLE
Installing podfile fails.

### ISSUE THREAD

**Issue by jaybakshi89** [CocoaPods/CocoaPods#4227]
### Command
```
/Users/vagrant/.rvm/gems/ruby-2.1.5/bin/pod install --verbose
```
### Report
* What did you do?
Just executed a regular UnitTest plan, with a step of CocoaPod installation which failed. Below are the marked-down logs for the same.
* What did you expect to happen?
For the Podfile to get installed, so plan progresses and executes correctly.
* What happened instead?
ThePodfile isn't getting installed, seems with some conflict related to New Relic. This cause my execution plan to exit prematurely at this step.
### Stack
```
   CocoaPods : 0.38.2
        Ruby : ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin14.0]
    RubyGems : 2.4.8
        Host : Mac OS X 10.10.5 (14F27)
       Xcode : 6.4 (6E35b)
         Git : git version 2.5.2
Ruby lib dir : /Users/vagrant/.rvm/rubies/ruby-2.1.5/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ ce6b68ec7b3209880768aba651fd75f40a29f03b
```
### Plugins
```
cocoapods-plugins : 0.4.2
cocoapods-stats   : 0.5.3
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.4.5
```
### Podfile
```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
target 'Sportkix' do
pod 'RestKit'
pod 'RestKit/Testing'
pod 'RestKit/Search'
platform :ios, '6.1'
pod 'SDWebImage', '~>3.7'
pod 'ICViewPager', :git => 'https://github.com/vinitam/ICViewPager.git'
pod 'MBProgressHUD', '~> 0.9'
pod 'TestFairy', '~> 1.3'
pod 'TBXML+NSDictionary', '0.0.1'
pod 'NewRelicAgent-Beta', '~>5.2.1-dev.147'
platform :ios, '7.0'
pod 'Google-Mobile-Ads-SDK', '~> 7.0'
pod 'GoogleAnalytics'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
end
target 'SportkixTests' do
end
```
### Error
```
Errno::ENOENT - No such file or directory @ rb_file_s_stat - /Users/vagrant/git/Sportkix/Pods/NewRelicAgent/NewRelic_iOS_Agent_5.2.1/NewRelicAgent.framework/Versions/Current
/Users/vagrant/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/fileutils.rb:902:in `stat'
/Users/vagrant/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/fileutils.rb:902:in `symbolic_modes_to_i'
/Users/vagrant/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/fileutils.rb:949:in `fu_mode'
/Users/vagrant/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/fileutils.rb:1023:in `block (2 levels) in chmod_R'
/Users/vagrant/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/fileutils.rb:1487:in `preorder_traverse'
/Users/vagrant/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/fileutils.rb:1021:in `block in chmod_R'
/Users/vagrant/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/fileutils.rb:1020:in `each'
/Users/vagrant/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/fileutils.rb:1020:in `chmod_R'
/Users/vagrant/.rvm/gems/ruby-2.1.5/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:117:in `block in prepare'
/Users/vagrant/.rvm/gems/ruby-2.1.5/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:140:in `message'
/Users/vagrant/.rvm/gems/ruby-2.1.5/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:116:in `prepare'
/Users/vagrant/.rvm/gems/ruby-2.1.5/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:103:in `install!'
/Users/vagrant/.rvm/gems/ruby-2.1.5/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/vagrant/.rvm/gems/ruby-2.1.5/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:101:in `run'
/Users/vagrant/.rvm/gems/ruby-2.1.5/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Users/vagrant/.rvm/gems/ruby-2.1.5/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/Users/vagrant/.rvm/gems/ruby-2.1.5/gems/cocoapods-0.38.2/bin/pod:44:in `'
/Users/vagrant/.rvm/gems/ruby-2.1.5/bin/pod:23:in `load'
/Users/vagrant/.rvm/gems/ruby-2.1.5/bin/pod:23:in `
'
/Users/vagrant/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/Users/vagrant/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `

**Comment by segiddins** [comment]
This is a big that's been fixed in the 0.39 betas.
