### ISSUE TITLE
Show informative error on EPERM for the Pods directory

### ISSUE THREAD

**Issue by inzinga** [CocoaPods/CocoaPods#4276]
### Command

```
/usr/bin/pod install
```
### Report
- What did you do?

During Continuous Integration process using Mac Yosemite (OS X 10.10.5), XCodeServer (Version 5.0.4), Xcode (7.0).  During Before Integration phase of Xcode bot, the following script is run to fetch latest pods:

```
export LC_ALL="en_US.UTF-8"
# Put the git repo name instead of “reponame” variable
cd DWC-NH-Jambo
# Remove the following line if there is no submodules in the project
git submodule update --init --recursive
# If podfile is not in the root folder uncomment the following line
# and replace with the real folder name
# cd FolderName
pod install
```
- What did you expect to happen?

Expected the various pods to be updated.  Seems to be a permission issue now.  The bot is run under the _xcsbuildd user, I believe.  This workflow worked prior with prior Xcode version and/or prior CocoaPods version.
- What happened instead?

Looks like pods installation process ran into permission issues.

Any and/all guidance is sincerely appreciated.
### Stack

```
   CocoaPods : 0.38.2
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.0.14
        Host : Mac OS X 10.10.5 (14F27)
       Xcode : 7.0 (7A220)
         Git : git version 2.3.8 (Apple Git-58)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 4a8ada829ea29c21b521a33dcc49a20f566c5805
```
### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-stats   : 0.5.3
cocoapods-trunk   : 0.3.1
cocoapods-try     : 0.4.5
```
### Podfile

``` ruby
# Uncomment this line to define a global platform for your project.
platform :ios, '8.0'

# Uncomment this line to remove build warnings associated with pod dependencies
inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'

xcodeproj 'NH Jambo'
workspace 'NH Jambo'

target 'NH Jambo' do

pod 'AWSiOSSDKv2', '~> 2.0'
pod 'AWSCognito', '~> 2.2', :inhibit_warnings => true
pod 'GoogleAnalytics', '~> 3.13'
pod 'iRate', '~> 1.11'
pod 'Fabric', '~> 1.5'
pod 'TwitterCore', '~> 1.11'
pod 'TwitterKit', '~> 1.11'
pod 'STTwitter'
pod 'Reveal-iOS-SDK', :configurations => ['Debug']
pod 'objective-zip', '~> 0.8'
pod 'GoogleMaps', '~> 1.10'
pod 'ECSlidingViewController', '~> 2.0.3'
### pod 'vfrReader', '>= 2.7.3'
pod 'vfrReader', '~> 2.8'

end

target 'NH JamboTests' do

end
```
### Error

```
Errno::EPERM - Operation not permitted - /Library/Developer/XcodeServer/Integrations/Caches/b72b92bac6dd69e33659d28e600022aa/Source/DWC-NH-Jambo/Pods
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1327:in `chmod'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1327:in `chmod'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1000:in `block (2 levels) in chmod_R'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1460:in `preorder_traverse'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:998:in `block in chmod_R'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:997:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:997:in `chmod_R'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:117:in `block in prepare'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:140:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:116:in `prepare'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:103:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

**Comment by segiddins** [comment]
You'll need to make sure whichever user is running the command has permissions for the pods directory, there's not really much we can do about that besides improving the error.

**Comment by neonichu** [comment]
IMO, the error is fairly clear already.

**Comment by segiddins** [comment]
@neonichu but we should never show the error report

**Comment by lyp944** [comment]
my podfile :
platform :ios, '8.0'
inhibit_all_warnings!
source 'https://github.com/CocoaPods/Specs.git'
#target:'20100923Test' do
pod 'AFNetworking', '~> 3.0'
pod 'SDWebImage'
pod 'UIActivityIndicator-for-SDWebImage'
pod 'Mantle'
pod 'Aspects'
pod 'ReactiveCocoa','~> 2.0'
pod 'WebViewJavascriptBridge'
pod 'pop'
pod 'SSKeychain'
pod 'SVPullToRefresh'
pod 'FDFullscreenPopGesture'
pod 'YYKit'
pod 'Masonry'
pod 'MJRefresh'
#end

then:
$pod install

terminal print:

### Error

```
NoMethodError - undefined method `user_targets' for #<Pod::Installer::PostInstallHooksContext::UmbrellaTargetDescription:0x007f96e350a678>
