### ISSUE TITLE
Unable to pod install with CocoaPods Beta

### ISSUE THREAD

**Issue by brianmichel** [CocoaPods/CocoaPods#4291]
### Command

```
/Users/brianmichel/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bin/pod install
```

### Report

* What did you do?

Ran `bundle exec pod install`

* What did you expect to happen?

My pods project to get updated, and be integrated into Xcode

* What happened instead?

CocoaPods failed to generate a project, and crashed instead.

### Stack

```
   CocoaPods : 0.39.0.beta.4
        Ruby : ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin14.0]
    RubyGems : 2.2.2
        Host : Mac OS X 10.11 (15A279b)
       Xcode : 7.0 (7A218)
         Git : git version 2.3.1
Ruby lib dir : /Users/brianmichel/.rbenv/versions/2.1.5/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ c605ac873605a21d33c11c1aff55c081c5e6c804
               tumblr-podspecs - redacted
               tumblr-tumblrmobile-podspecs - redacted
               yahoo-pod-specs - redacted
```

### Plugins

```
cocoapods-git_url_rewriter : 1.0.0
cocoapods-plugins          : 0.4.2
cocoapods-stats            : 0.6.1
cocoapods-trunk            : 0.6.4
cocoapods-try              : 0.5.1
```

### Podfile

```ruby
Redacted Podfile. 
```

### Error

```
NoMethodError - undefined method `strip' for true:TrueClass
/Users/brianmichel/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/xcodeproj-0.27.2/lib/xcodeproj/config.rb:134:in `block (2 levels) in to_hash'
/Users/brianmichel/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/xcodeproj-0.27.2/lib/xcodeproj/config.rb:134:in `each'
/Users/brianmichel/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/xcodeproj-0.27.2/lib/xcodeproj/config.rb:134:in `any?'
/Users/brianmichel/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/xcodeproj-0.27.2/lib/xcodeproj/config.rb:134:in `block in to_hash'
/Users/brianmichel/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/xcodeproj-0.27.2/lib/xcodeproj/config.rb:134:in `reject!'
/Users/brianmichel/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/xcodeproj-0.27.2/lib/xcodeproj/config.rb:134:in `to_hash'
/Users/brianmichel/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/xcodeproj-0.27.2/lib/xcodeproj/config.rb:84:in `to_s'
/Users/brianmichel/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/xcodeproj-0.27.2/lib/xcodeproj/config.rb:101:in `block in save_as'
/Users/brianmichel/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/xcodeproj-0.27.2/lib/xcodeproj/config.rb:101:in `open'
/Users/brianmichel/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/xcodeproj-0.27.2/lib/xcodeproj/config.rb:101:in `open'
/Users/brianmichel/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/xcodeproj-0.27.2/lib/xcodeproj/config.rb:101:in `save_as'
/Users/brianmichel/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-0.39.0.beta.4/lib/cocoapods/generator/xcconfig/pod_xcconfig.rb:35:in `save_as'
/Users/brianmichel/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-0.39.0.beta.4/lib/cocoapods/installer/target_installer/pod_target_installer.rb:165:in `create_xcconfig_file'
/Users/brianmichel/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-0.39.0.beta.4/lib/cocoapods/installer/target_installer/pod_target_installer.rb:22:in `block in install!'
/Users/brianmichel/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-0.39.0.beta.4/lib/cocoapods/user_interface.rb:140:in `message'
/Users/brianmichel/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-0.39.0.beta.4/lib/cocoapods/installer/target_installer/pod_target_installer.rb:17:in `install!'
/Users/brianmichel/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-0.39.0.beta.4/lib/cocoapods/installer.rb:603:in `block (2 levels) in install_libraries'
/Users/brianmichel/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-0.39.0.beta.4/lib/cocoapods/installer.rb:600:in `each'
/Users/brianmichel/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-0.39.0.beta.4/lib/cocoapods/installer.rb:600:in `block in install_libraries'
/Users/brianmichel/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-0.39.0.beta.4/lib/cocoapods/user_interface.rb:140:in `message'
/Users/brianmichel/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-0.39.0.beta.4/lib/cocoapods/installer.rb:599:in `install_libraries'
/Users/brianmichel/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-0.39.0.beta.4/lib/cocoapods/installer.rb:156:in `block in generate_pods_project'
/Users/brianmichel/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-0.39.0.beta.4/lib/cocoapods/user_interface.rb:59:in `section'
/Users/brianmichel/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-0.39.0.beta.4/lib/cocoapods/installer.rb:153:in `generate_pods_project'
/Users/brianmichel/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-0.39.0.beta.4/lib/cocoapods/installer.rb:111:in `install!'
/Users/brianmichel/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-0.39.0.beta.4/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/brianmichel/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-0.39.0.beta.4/lib/cocoapods/command/project.rb:101:in `run'
/Users/brianmichel/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Users/brianmichel/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-0.39.0.beta.4/lib/cocoapods/command.rb:48:in `run'
/Users/brianmichel/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/cocoapods-0.39.0.beta.4/bin/pod:44:in `<top (required)>'
/Users/brianmichel/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bin/pod:23:in `load'
/Users/brianmichel/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bin/pod:23:in `<main>'
```

**Comment by segiddins** [comment]
Thanks, were probably just missing a `to_s` in xcodeproj. Should be a one line fix.

**Comment by brianmichel** [comment]
> Thanks, were probably just missing a to_s in xcodeproj. Should be a one line fix.

:+1:
