### ISSUE TITLE
trying pod update getting the below error

### ISSUE THREAD

**Issue by HanumanKachwa** [CocoaPods/CocoaPods#4296]
――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/bin/pod update
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 0.38.2
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.4.8
        Host : Mac OS X 10.10.5 (14F27)
       Xcode : 7.0 (7A220)
         Git : git version 2.3.8 (Apple Git-58)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 8f1cba3268e40e0e3a4a825575ba950618d8b6cb
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-stats   : 0.5.3
cocoapods-trunk   : 0.6.1
cocoapods-try     : 0.4.5
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '7.0'

target 'ProjectName' do
    pod 'TPKeyboardAvoiding', '~> 1.2'
    pod 'AFNetworking', '~> 2.5'
    pod 'MagicalRecord', '~> 2.2'
    pod 'FLAnimatedImage', '~> 1.0'
    pod 'Localytics', '~> 3.5.0'
    pod 'GoogleMaps'
    #pod 'Google-Maps-iOS-Utils-QuadTree', '0.1'
    pod 'AFNetworkActivityLogger', '~> 2.0'
    pod 'UIImage-Helpers'
    pod 'iCarousel', '~> 1.8.1'
    pod 'THLabel', '~> 1.4.6'
    pod 'MBProgressHUD', '~> 0.9.1'
    pod 'SMPageControl', '~> 1.2'
    pod 'SDWebImage', '~> 3.7.2'
    pod 'WSCoachMarksView'
    pod 'ZendeskSDK', :git => 'https://github.com/zendesk/zendesk_sdk_ios.git'
    #pod 'Lock', '~> 1.12'
    pod 'ZDCChat', :git => 'https://github.com/zendesk/zendesk_sdk_chat_ios.git'
    pod 'FBSDKCoreKit', '4.4.0'
    pod 'FBSDKLoginKit', '4.4.0'
    pod 'google-plus-ios-sdk', '1.7.1'
end
```

### Error

```
Errno::ENOENT - No such file or directory - /iOS/ProjectName/src_v2/Pods/ZDCChat/ZDCChat.framework/Resources
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:905:in `stat'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:905:in `symbolic_modes_to_i'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:926:in `fu_mode'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1000:in `block (2 levels) in chmod_R'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1460:in `preorder_traverse'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:998:in `block in chmod_R'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:997:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:997:in `chmod_R'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:117:in `block in prepare'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:140:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:116:in `prepare'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:103:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:156:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

**Comment by neonichu** [comment]
I believe this has been fixed in the 0.39 betas

**Comment by stephengazzard** [comment]
I am getting the same thing right now.

**Comment by orta** [comment]
on the beta?

**Comment by stephengazzard** [comment]
On `0.38.2` - was able to get pod install to work using 0.37.

**Comment by segiddins** [comment]
Closing since this was fixed in the 0.39 betas.
