### ISSUE TITLE
[El Capitan] - NoMethodError - undefined method `end_with?' for nil:NilClassi

### ISSUE THREAD

**Issue by ezefranca** [CocoaPods/CocoaPods#4311]
### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 0.38.2
        Ruby : ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]
    RubyGems : 2.0.14
        Host : Mac OS X 10.11 (15A284)
       Xcode : 7.0.1 (7A1001)
         Git : git version 2.3.8 (Apple Git-58)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master -  @ fatal: Not a git repository (or any of the parent directories): .git
               master-1 - https://github.com/CocoaPods/Specs.git @ def472b3514c213ccba06c97ad1a1dbc5b1e3327
```

### Plugins

```
cocoapods-dependencies : 0.4.0
cocoapods-plugins      : 0.4.2
cocoapods-search       : 0.1.0
cocoapods-stats        : 0.5.3
cocoapods-trunk        : 0.6.4
cocoapods-try          : 0.4.5
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
platform :ios, '7.1'

pod 'Harpy'
pod 'UIDeviceUtil'
pod 'Google/Analytics', '~> 1.0.0'
pod 'SDWebImage'
pod 'DateTools'
pod 'ZFTokenField'
pod 'IQKeyboardManager'
pod 'WEPopover'
pod 'RATreeView', '~> 1.0.3'
pod 'Bolts'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
pod 'AFNetworking'
pod 'RKNotificationHub'
pod 'PHFComposeBarView'
pod 'FMDB'
pod 'MSCircleProgressBar'
pod 'TNKRefreshControl'
pod 'QuickDialog'
pod 'WCFastCell'
pod 'Appirater'
#Fabric
pod 'Fabric'
pod 'Crashlytics'

# pod 'MaterialKit' # Uses Swift
# pod 'Google/AdMob', '~> 1.0.0'
```

### Error

```
NoMethodError - undefined method `end_with?' for nil:NilClass
/Library/Ruby/Gems/2.0.0/gems/cocoapods-stats-0.6.1/lib/cocoapods_plugin.rb:4:in `validates?'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-stats-0.5.3/lib/cocoapods_plugin.rb:25:in `block in <module:CocoaPodsStats>'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/hooks_manager.rb:115:in `call'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/hooks_manager.rb:115:in `block (3 levels) in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:140:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/hooks_manager.rb:111:in `block (2 levels) in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/hooks_manager.rb:109:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/hooks_manager.rb:109:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:140:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/hooks_manager.rb:108:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:453:in `run_plugins_post_install_hooks'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:444:in `perform_post_install_actions'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:112:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by segiddins** [comment]
This should be fixed by https://github.com/CocoaPods/cocoapods-stats/pull/24.
