### ISSUE TITLE
RunetimeError unknown file type on pod install

### ISSUE THREAD

**Issue by eliasbagley** [CocoaPods/CocoaPods#4324]
Sometimes when I run pod install, I get the following error. It seems to be breaking from not recognizing a tag file in the format of tag.xxxx where x is some number. This seems to only happen periodically when I'm on very slow internet. Is it possible that the slow connection is downloading partial files by appending .xxxx to it, and that's causing the exception?

### Command

```
/Users/eliasbagley/.rvm/rubies/ruby-2.1.4/bin/pod install
```

### Stack

```
   CocoaPods : 0.38.2
        Ruby : ruby 2.1.4p265 (2014-10-27 revision 48166) [x86_64-darwin14.0]
    RubyGems : 2.4.6
        Host : Mac OS X 10.10.3 (14D136)
       Xcode : 6.4 (6E35b)
         Git : git version 2.4.0
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-stats   : 0.5.3
cocoapods-trunk   : 0.6.1
cocoapods-try     : 0.4.5
```

```
RuntimeError - unknown file type: /var/folders/qh/gwvvd3vn63n61my_4y7ch4wh0000gn/T/d20151006-38483-15jv54m/.git/tags.39664
/Users/eliasbagley/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/fileutils.rb:1396:in `copy'
/Users/eliasbagley/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/fileutils.rb:469:in `block in copy_entry'
/Users/eliasbagley/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/fileutils.rb:1506:in `call'
/Users/eliasbagley/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/fileutils.rb:1506:in `wrap_traverse'
/Users/eliasbagley/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
/Users/eliasbagley/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
/Users/eliasbagley/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
/Users/eliasbagley/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
/Users/eliasbagley/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
/Users/eliasbagley/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
/Users/eliasbagley/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/fileutils.rb:466:in `copy_entry'
/Users/eliasbagley/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/fileutils.rb:441:in `block in cp_r'
/Users/eliasbagley/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/fileutils.rb:1579:in `block in fu_each_src_dest'
/Users/eliasbagley/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/fileutils.rb:1595:in `fu_each_src_dest0'
/Users/eliasbagley/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/fileutils.rb:1577:in `fu_each_src_dest'
/Users/eliasbagley/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/fileutils.rb:440:in `cp_r'
/Users/eliasbagley/.rvm/gems/ruby-2.1.4@global/gems/cocoapods-0.38.2/lib/cocoapods/downloader/cache.rb:200:in `copy_and_clean'
/Users/eliasbagley/.rvm/gems/ruby-2.1.4@global/gems/cocoapods-0.38.2/lib/cocoapods/downloader/cache.rb:158:in `block (2 levels) in uncached_pod'
/Users/eliasbagley/.rvm/gems/ruby-2.1.4@global/gems/cocoapods-0.38.2/lib/cocoapods/downloader/cache.rb:156:in `each'
/Users/eliasbagley/.rvm/gems/ruby-2.1.4@global/gems/cocoapods-0.38.2/lib/cocoapods/downloader/cache.rb:156:in `block in uncached_pod'
/Users/eliasbagley/.rvm/gems/ruby-2.1.4@global/gems/cocoapods-0.38.2/lib/cocoapods/downloader/cache.rb:180:in `call'
/Users/eliasbagley/.rvm/gems/ruby-2.1.4@global/gems/cocoapods-0.38.2/lib/cocoapods/downloader/cache.rb:180:in `in_tmpdir'
/Users/eliasbagley/.rvm/gems/ruby-2.1.4@global/gems/cocoapods-0.38.2/lib/cocoapods/downloader/cache.rb:152:in `uncached_pod'
/Users/eliasbagley/.rvm/gems/ruby-2.1.4@global/gems/cocoapods-0.38.2/lib/cocoapods/downloader/cache.rb:33:in `download_pod'
/Users/eliasbagley/.rvm/gems/ruby-2.1.4@global/gems/cocoapods-0.38.2/lib/cocoapods/downloader.rb:34:in `download'
/Users/eliasbagley/.rvm/gems/ruby-2.1.4@global/gems/cocoapods-0.38.2/lib/cocoapods/installer/pod_source_installer.rb:103:in `download_source'
/Users/eliasbagley/.rvm/gems/ruby-2.1.4@global/gems/cocoapods-0.38.2/lib/cocoapods/installer/pod_source_installer.rb:53:in `install!'
/Users/eliasbagley/.rvm/gems/ruby-2.1.4@global/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:328:in `install_source_of_pod'
/Users/eliasbagley/.rvm/gems/ruby-2.1.4@global/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:303:in `block (2 levels) in install_pod_sources'
/Users/eliasbagley/.rvm/gems/ruby-2.1.4@global/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:80:in `titled_section'
/Users/eliasbagley/.rvm/gems/ruby-2.1.4@global/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:302:in `block in install_pod_sources'
/Users/eliasbagley/.rvm/gems/ruby-2.1.4@global/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:294:in `each'
/Users/eliasbagley/.rvm/gems/ruby-2.1.4@global/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:294:in `install_pod_sources'
/Users/eliasbagley/.rvm/gems/ruby-2.1.4@global/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:143:in `block in download_dependencies'
/Users/eliasbagley/.rvm/gems/ruby-2.1.4@global/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:59:in `section'
/Users/eliasbagley/.rvm/gems/ruby-2.1.4@global/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:141:in `download_dependencies'
/Users/eliasbagley/.rvm/gems/ruby-2.1.4@global/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:105:in `install!'
/Users/eliasbagley/.rvm/gems/ruby-2.1.4@global/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/eliasbagley/.rvm/gems/ruby-2.1.4@global/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:101:in `run'
/Users/eliasbagley/.rvm/gems/ruby-2.1.4/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Users/eliasbagley/.rvm/gems/ruby-2.1.4@global/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/Users/eliasbagley/.rvm/gems/ruby-2.1.4@global/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
/Users/eliasbagley/.rvm/rubies/ruby-2.1.4/bin/pod:23:in `load'
/Users/eliasbagley/.rvm/rubies/ruby-2.1.4/bin/pod:23:in `<main>'
/Users/eliasbagley/.rvm/gems/ruby-2.1.4/bin/ruby_executable_hooks:15:in `eval'
/Users/eliasbagley/.rvm/gems/ruby-2.1.4/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by segiddins** [comment]
That sounds like a good guess, but it's hard to know for sure unless we can reproduce it.

**Comment by neonichu** [comment]
If it is, it's probably more a git thing, though — is there way to check the integrity of a git checkout before we cache it?

**Comment by segiddins** [comment]
The git invocation succeeding should be sufficient for that...

**Comment by neonichu** [comment]
If we assume git has no bugs ;)

**Comment by mrackwitz** [comment]
This is weird because the file path pattern `.git/tags.xxxxxx` is very unusual for Git. Tags are hosted in the `.git/refs` dir.

**Comment by boxofrad** [comment]
I also have this problem (see information below) but should note that I used to intermittently have the same issue with [librarian-chef](https://github.com/applicationsonline/librarian-chef) which also uses git to manage dependencies.

### Stack

```
   CocoaPods : 0.38.2
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.0.14
        Host : Mac OS X 10.10.3 (14D136)
       Xcode : 6.4 (6E35b)
         Git : git version 2.6.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 71b175f8c43c20771705b96a1019a6318865bd9f
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-stats   : 0.5.3
cocoapods-trunk   : 0.6.1
cocoapods-try     : 0.4.5
```

### Podfile

```ruby
platform :ios, '7.0'

pod 'AFNetworking', '~> 1.3'
pod 'libPusher', '~> 1.6'
pod 'Mantle', '~> 1.3'
pod 'Mixpanel', '~> 2.3'
pod 'NVSlideMenuController', '~> 1.5.3'
pod 'Intercom', :path => "Vendor/Intercom"
pod 'SSKeychain', '~> 1.2.0'
pod '1PasswordExtension', '~> 1.2'

target 'GeckoboardTests' do
  pod 'Specta',  '~> 1.0'
  pod 'Expecta', '~> 0.2.2'
  pod 'OCMock',  '~> 2.2.1'
end
```

### Error

```
RuntimeError - unknown file type: /var/folders/7b/kqd2sr5n76l4yl088lqybgb40000gn/T/d20151007-1106-y2nsr9/.git/tags.1147
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1369:in `copy'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:463:in `block in copy_entry'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1479:in `call'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1479:in `wrap_traverse'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1482:in `block in wrap_traverse'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1481:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1481:in `wrap_traverse'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1482:in `block in wrap_traverse'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1481:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1481:in `wrap_traverse'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:460:in `copy_entry'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:435:in `block in cp_r'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1552:in `block in fu_each_src_dest'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1568:in `fu_each_src_dest0'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1550:in `fu_each_src_dest'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:434:in `cp_r'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/downloader/cache.rb:200:in `copy_and_clean'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/downloader/cache.rb:158:in `block (2 levels) in uncached_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/downloader/cache.rb:156:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/downloader/cache.rb:156:in `block in uncached_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/downloader/cache.rb:180:in `call'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/downloader/cache.rb:180:in `in_tmpdir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/downloader/cache.rb:152:in `uncached_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/downloader/cache.rb:33:in `download_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/downloader.rb:34:in `download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/pod_source_installer.rb:103:in `download_source'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/pod_source_installer.rb:53:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:328:in `install_source_of_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:303:in `block (2 levels) in install_pod_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:80:in `titled_section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:302:in `block in install_pod_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:294:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:294:in `install_pod_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:143:in `block in download_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:141:in `download_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:105:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

**Comment by boxofrad** [comment]
A very naughty workaround, which you probably shouldn't do is to manually edit `fileutils.rb` to simply ignore the error! :worried:

**Comment by neonichu** [comment]
@boxofrad maybe you could share such a broken checkout? Would be interesting to see if there's an easy way to check it and possibly throw a nicer error.

**Comment by segiddins** [comment]
Closing due to lack of response.
