### ISSUE TITLE
Errno::EPERM - Operation not permitted

### ISSUE THREAD

**Issue by talisk** [CocoaPods/CocoaPods#4354]
### Command

```
/usr/local/bin/pod install
```

### Report

I  run the pod install in Terminal, but it tell me Errno::EPERM - Operation not permitted.

My Xcode version is 7.0, and OS X version is 10.11 (15A284).

### Stack

```
   CocoaPods : 0.38.2
        Ruby : ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]
    RubyGems : 2.4.8
        Host : Mac OS X 10.11 (15A284)
       Xcode : 7.0 (7A220)
         Git : git version 2.3.8 (Apple Git-58)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 743ba1c87f00ecbd18814af8bf9acded7ecd2f7f
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-stats   : 0.5.3
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.4.5
```

### Podfile

```ruby
platform:ios,'9.0'
pod 'AFNetworking'
pod 'Mantle'
pod 'IQKeyboardManager'
pod 'FXBlurView'
```

### Error

```
Errno::EPERM - Operation not permitted - /Users/sunkai/XcodeProjects/iHBNU/Pods/Pods.xcodeproj/xcuserdata/root.xcuserdatad
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1333:in `chmod'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1333:in `chmod'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1001:in `block (2 levels) in chmod_R'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1466:in `preorder_traverse'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:999:in `block in chmod_R'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:998:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:998:in `chmod_R'
/Users/sunkai/Software/ruby/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:117:in `block in prepare'
/Users/sunkai/Software/ruby/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:140:in `message'
/Users/sunkai/Software/ruby/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:116:in `prepare'
/Users/sunkai/Software/ruby/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:103:in `install!'
/Users/sunkai/Software/ruby/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/sunkai/Software/ruby/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Users/sunkai/Software/ruby/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/Users/sunkai/Software/ruby/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by segiddins** [comment]
You need to have ownership permissions for the `Pods` directory, and I believe we already have an issue open for making this a nicer error.

**Comment by vgorloff** [comment]
Im my case there were probably something wrong with "extended attributes" after copying Git-repo (via Finder.app) to another SSD drive. Removing `Pods` dir resolved issue.
