### ISSUE TITLE
"pod install" error

### ISSUE THREAD

**Issue by Sandeep-Manchikanti** [CocoaPods/CocoaPods#4371]
Trying to add the Specs repo to my iOS project for Chat Secure. Initially was not able to run "Pod Install" so I first ran manual add repo then tried "Pod Install" which resulted in below error:

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```

/usr/bin/pod install

```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```

   CocoaPods : 0.39.0

        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]

    RubyGems : 2.0.14

        Host : Mac OS X 10.10.4 (14E46)

       Xcode : 7.0.1 (7A1001)

         Git : git version 2.3.8 (Apple Git-58)

Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib

Repositories : Specs - https://github.com/CocoaPods/Specs.git @ 31398e88ce706dd00c58c2f4617ccc030e0f9a9c

```

### Plugins

```

cocoapods-plugins : 0.4.2

cocoapods-search  : 0.1.0

cocoapods-stats   : 0.6.2

cocoapods-trunk   : 0.6.4

cocoapods-try     : 0.5.1

```

### Podfile

```ruby

# Disable CocoaPods deterministic UUIDs as Pods are not checked in

ENV["COCOAPODS_DISABLE_DETERMINISTIC_UUIDS"] = "true"



# Disable Bitcode for all targets http://stackoverflow.com/a/32685434/805882

post_install do |installer|

  installer.pods_project.targets.each do |target|

    target.build_configurations.each do |config|

      config.build_settings['ENABLE_BITCODE'] = 'NO'

    end

  end

end



platform :ios, "9.0"



use_frameworks!

inhibit_all_warnings!



source 'https://github.com/CocoaPods/Specs.git'



link_with 'ChatSecureCore'



pod 'AFNetworking', '~> 2.6'

pod "Appirater", '~> 2.0'

pod 'OpenInChrome', '~> 0.0'

pod 'MWFeedParser', '~> 1.0'

pod "CocoaLumberjack", '~> 1.9'

pod "HockeySDK-Source", '~> 3.7'

pod 'MBProgressHUD', '~> 0.9'

pod "SSKeychain", '~> 1.2'

pod "UIAlertView-Blocks", '~> 1.0'

# pod 'gtm-oauth2', '~> 0.1.0' # Trunk is outdated, using local podspec

pod 'JTTargetActionBlock', '~> 1.0'

# pod 'YapDatabase/SQLCipher', '~> 2.5' # We need to use fork for sqlite3_rekey support

pod 'Mantle', '~> 2.0'

pod 'Navajo', '~> 0.0'

# wating on 8.0 https://github.com/jessesquires/JSQMessagesViewController/pull/840

# using for in meantime

# pod 'JSQMessagesViewController', '~> 8.0'

pod 'BBlock', '~> 1.2'

pod 'JVFloatLabeledTextField', '~> 1.0'

pod 'TTTAttributedLabel', '~> 1.10'

pod 'VTAcknowledgementsViewController', '~> 0.15'

pod 'PureLayout', '~> 3.0'

pod 'BButton', '~> 4.0'

pod 'uservoice-iphone-sdk', '~> 3.2'

pod 'TUSafariActivity', '~> 1.0'

pod 'ARChromeActivity', '~> 1.0'

pod 'CocoaAsyncSocket', '~> 7.4'

pod 'JTSImageViewController', '~> 1.4'

pod 'KVOController', '~> 1.0'

pod 'CRToast', '~> 0.0.8'

# pod 'XLForm', '~> 3.0' # Need to use bundle fork

# pod 'ParkedTextField', '~> 0.1' # Need to use Swift 2.0 fork



# QR Codes

pod 'QRCodeReaderViewController', '~> 3.5.0'

pod 'ZXingObjC', '~> 3.0'





# Local Podspecs

pod 'gtm-http-fetcher', :podspec => 'Podspecs/gtm-http-fetcher.podspec'

pod 'gtm-oauth2', :podspec => 'Podspecs/gtm-oauth2.podspec'

pod 'SQLCipher/fts', :podspec => 'Podspecs/SQLCipher.podspec.json'





# Forks

pod 'SIAlertView', :git => 'https://github.com/ChatSecure/SIAlertView.git', :branch => 'attributedText'

pod 'JSQMessagesViewController', :git => 'https://github.com/ChatSecure/JSQMessagesViewController', :branch => '7.1.0-send_button'



# Submodules

pod 'ProxyKit/Client', :path => 'Submodules/ProxyKit/ProxyKit.podspec'

pod 'OTRKit', :path => 'Submodules/OTRKit/OTRKit.podspec'

pod 'CPAProxy', :path => 'Submodules/CPAProxy/CPAProxy.podspec'

pod 'XMPPFramework', :path => 'Submodules/XMPPFramework/XMPPFramework.podspec'

pod 'YapDatabase/SQLCipher', :path => 'Submodules/YapDatabase/YapDatabase.podspec'

pod 'IOCipher/GCDWebServer', :path => 'Submodules/IOCipher/IOCipher.podspec'

pod 'ParkedTextField', :path => 'Submodules/ParkedTextField/ParkedTextField.podspec'

pod 'XLForm', :path => 'Submodules/XLForm/XLForm.podspec'

```

### Error

```

Errno::ENOENT - No such file or directory - /Users/sandeepmanchikanti/.cocoapods/repos/master

/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.39.0/lib/cocoapods-core/source.rb:41:in `chdir'

/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.39.0/lib/cocoapods-core/source.rb:41:in `url'

/Library/Ruby/Gems/2.0.0/gems/cocoapods-stats-0.6.2/lib/cocoapods_plugin.rb:4:in `validates?'

/Library/Ruby/Gems/2.0.0/gems/cocoapods-stats-0.6.2/lib/cocoapods_plugin.rb:25:in `block in <module:CocoaPodsStats>'

/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:117:in `call'

/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:117:in `block (3 levels) in run'

/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:140:in `message'

/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:111:in `block (2 levels) in run'

/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:109:in `each'

/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:109:in `block in run'

/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:140:in `message'

/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:108:in `run'

/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:481:in `run_plugins_post_install_hooks'

/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:462:in `perform_post_install_actions'

/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:113:in `install!'

/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'

/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:101:in `run'

/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'

/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'

/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'

/usr/bin/pod:23:in `load'

/usr/bin/pod:23:in `<main>'

```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

**Comment by Sandeep-Manchikanti** [comment]
Fixed the same. when I looked at the actual error looks like a folder was missing.

**Comment by jsambuo** [comment]
I had the same issue after deleting `~/.cocoapods` (which I probably should not have done).

The main issue was `No such file or directory - /Users/blah/.cocoapods/repos/master`
`pod setup` fixed it for me.

Adding it here for future reference.
