### ISSUE TITLE
NoMethodError - undefined method `to_ary' for Pod EAIntroView

### ISSUE THREAD

**Issue by mathmatrix828** [CocoaPods/CocoaPods#4391]
### Command

```
/Users/***/.rvm/gems/ruby-head/bin/pod update
```

### Report

Attempted to update Pods

Update Pods

Threw undefined method error

### Stack

```
   CocoaPods : 0.39.0
        Ruby : ruby 2.3.0dev (2015-10-13 trunk 52118) [x86_64-darwin15]
    RubyGems : 2.5.0
        Host : Mac OS X 10.11 (15A284)
       Xcode : 7.0.1 (7A1001)
         Git : git version 2.3.8 (Apple Git-58)
Ruby lib dir : /Users/***/.rvm/rubies/ruby-head/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 71a0dd01f8a2a56fc2651fcbf6d8bb251700b4e8
```

### Plugins

```
cocoapods-deintegrate : 0.2.1
cocoapods-plugins     : 0.4.2
cocoapods-search      : 0.1.0
cocoapods-stats       : 0.6.2
cocoapods-trunk       : 0.6.4
cocoapods-try         : 0.5.1
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'rStatDB' do

pod 'SWRevealViewController'
pod 'Parse'
pod 'ParseUI'
pod 'ParseCrashReporting'
pod 'SWRevealTableViewCell'
pod 'FontAwesome.swift'
pod 'MBProgressHUD'
pod 'MarqueeLabel'
pod 'EAIntroView'
# Legacy
pod 'XLForm'
# Replacement -> XLForm
pod 'Eureka'

end
```

### Error

```
NoMethodError - undefined method `to_ary' for #<Pod::Specification name="EAIntroView">
/Users/***/.rvm/gems/ruby-head/gems/cocoapods-0.39.0/lib/cocoapods/resolver/lazy_specification.rb:14:in `method_missing'
/Users/***/.rvm/gems/ruby-head/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:64:in `flatten'
/Users/***/.rvm/gems/ruby-head/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:64:in `block in resolve'
/Users/***/.rvm/gems/ruby-head/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:63:in `tap'
/Users/***/.rvm/gems/ruby-head/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:63:in `resolve'
/Users/***/.rvm/gems/ruby-head/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:539:in `block in resolve_dependencies'
/Users/***/.rvm/gems/ruby-head/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Users/***/.rvm/gems/ruby-head/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:537:in `resolve_dependencies'
/Users/***/.rvm/gems/ruby-head/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:70:in `analyze'
/Users/***/.rvm/gems/ruby-head/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:213:in `analyze'
/Users/***/.rvm/gems/ruby-head/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:136:in `block in resolve_dependencies'
/Users/***/.rvm/gems/ruby-head/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Users/***/.rvm/gems/ruby-head/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:135:in `resolve_dependencies'
/Users/***/.rvm/gems/ruby-head/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:105:in `install!'
/Users/***/.rvm/gems/ruby-head/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/***/.rvm/gems/ruby-head/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:156:in `run'
/Users/***/.rvm/gems/ruby-head/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Users/***/.rvm/gems/ruby-head/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Users/***/.rvm/gems/ruby-head/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/Users/***/.rvm/gems/ruby-head/bin/pod:23:in `load'
/Users/***/.rvm/gems/ruby-head/bin/pod:23:in `<main>'
/Users/***/.rvm/gems/ruby-head/bin/ruby_executable_hooks:15:in `eval'
/Users/***/.rvm/gems/ruby-head/bin/ruby_executable_hooks:15:in `<main>'
```

This error changes when I remove EAIntroView, and throws on Eureka

**Comment by mathmatrix828** [comment]
Appears to be a duplicate issue from #4345

**Comment by segiddins** [comment]
Yup, duplicate. It's fixed on master.

**Comment by mathmatrix828** [comment]
Awesome. I’ll try updating

**Comment by mathmatrix828** [comment]
Still has not been fixed

I used RVM to install the latest version of Ruby

**Comment by segiddins** [comment]
This is fixed on master.

**Comment by pardel** [comment]
This bug has returned when using ruby-2.3.0 with CocoaPods 1.0.0.beta.1.
Everything is ok if ruby-2.2.x is used.

**Comment by ltfschoen** [comment]
I also get this bug with ruby-2.3.0 using CocoaPods v0.39.0.
Reverting back to ruby-2.2.0 overcomes the error.

**Comment by segiddins** [comment]
@ltfschoen it should be fixed in 1.0.0.beta.1
@pardel can you please open a new issue with the output of `pod env` so we can investigate? Thanks!

**Comment by Bodacious** [comment]
+1 seeing this isuse in ruby-2.3.0 but not ruby-2.2.3

**Comment by squidpunch** [comment]
+1 @Bodacious same here. for 2.3

**Comment by segiddins** [comment]
On what CocoaPods versions? Again, this should be fixed in the 1.0.0 betas.

**Comment by cheunghy** [comment]
Same for ruby 2.3.0

**Comment by scottphc** [comment]
+1 same for ruby 2.3.0

**Comment by MOPineyro** [comment]
also getting this error on ruby 2.3 with cocoapods 1.0.0.beta.2

**Comment by segiddins** [comment]
I'm going to lock this issue for now. If you're still experiencing issue on Ruby 2.3 with the 1.0 beta, please open up a new issue (a single one) that includes the error report and any other necessary steps to reproduce. thanks!

**Comment by orta** [comment]
Alternative is to use the [CP Mac app](https://cocoapods.org/app) too, which uses the beta.
