### ISSUE TITLE
errors from ruby after 0.39 update

### ISSUE THREAD

**Issue by romk1n** [CocoaPods/CocoaPods#4394]
```
Error loading the plugin with path `/usr/local/lib/ruby/gems/2.2.0/gems/slather-1.8.1/lib/cocoapods_plugin.rb`.

Gem::ConflictError - Unable to activate slather-1.8.1, because xcodeproj-0.28.2 conflicts with xcodeproj (~> 0.26.2)
/usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/specification.rb:2112:in `raise_if_conflicts'
/usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/specification.rb:1280:in `activate'
/usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems.rb:198:in `rescue in try_activate'
/usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems.rb:195:in `try_activate'
/usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
/usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
/usr/local/lib/ruby/gems/2.2.0/gems/slather-1.8.1/lib/cocoapods_plugin.rb:1:in `<top (required)>'
/usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/lib/ruby/gems/2.2.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:106:in `safe_require'
/usr/local/lib/ruby/gems/2.2.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:32:in `block in load_plugins'
/usr/local/lib/ruby/gems/2.2.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:31:in `each'
/usr/local/lib/ruby/gems/2.2.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:31:in `load_plugins'
/usr/local/lib/ruby/gems/2.2.0/gems/claide-0.9.1/lib/claide/command.rb:304:in `block in run'
/usr/local/lib/ruby/gems/2.2.0/gems/claide-0.9.1/lib/claide/command.rb:303:in `each'
/usr/local/lib/ruby/gems/2.2.0/gems/claide-0.9.1/lib/claide/command.rb:303:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
---------------------------------------------
```

**Comment by neonichu** [comment]
The CP plugin inside slather requires an older version of the Xcodeproj gem. You have to either update slather to a newer version or uninstall it.

**Comment by romk1n** [comment]
@neonichu 1.8.1 is the latest slather version

**Comment by segiddins** [comment]
Then slather needs to update :)

**Comment by rad182** [comment]
i too encounter this problem. i have slather 1.8.1 installed but still get this messages

**Comment by sprynmr** [comment]
Until then: https://github.com/venmo/slather/issues/104#issuecomment-152707209
