### ISSUE TITLE
CP displays wrong error when it can't find a podspec for a newer specific version

### ISSUE THREAD

**Issue by mtitolo** [CocoaPods/CocoaPods#4430]
We've been doing a lot of updates to our internal pods. Because the work network is slow, we often run with `--no-repo-update` to speed up our installs.

When I ran `pod install --no-repo-update` without the new version podspec already downloaded, I got a resolver error instead of an error saying the version did not exist.

If the local specs repo does not have a particular version it should throw an error that it can't find the specified version, not that it cannot resolve the version requirements.

This is on 0.39.0.
```
[!] Unable to satisfy the following requirements:

- `Lib (= 4.0.0)` required by `Podfile`
- `Lib (= 4.0.0)` required by `Podfile.lock`

.../.gem/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:411:in `handle_resolver_error'
.../.gem/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:69:in `rescue in resolve'
.../.gem/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:57:in `resolve'
.../.gem/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:539:in `block in resolve_dependencies'
.../.gem/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
.../.gem/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:537:in `resolve_dependencies'
.../.gem/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:70:in `analyze'
.../.gem/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:213:in `analyze'
.../.gem/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:136:in `block in resolve_dependencies'
.../.gem/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
.../.gem/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:135:in `resolve_dependencies'
.../.gem/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:105:in `install!'
.../.gem/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
.../.gem/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:101:in `run'
.../.gem/ruby/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
.../.gem/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
.../.gem/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
.../.gem/bin/pod:23:in `load'
.../.gem/bin/pod:23:in `<main>'
```

**Comment by neonichu** [comment]
Fixed by #4443
