### ISSUE TITLE
[bug] frozen object (JSON::Ext::Generator::State) allocated

### ISSUE THREAD

**Issue by chrisallick** [CocoaPods/CocoaPods#4438]
### Stack

```
   CocoaPods : 0.39.0
        Ruby : ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
    RubyGems : 2.4.5
        Host : Mac OS X 10.10.5 (14F27)
       Xcode : 6.4 (6E35b)
         Git : git version 2.3.2 (Apple Git-55)
Ruby lib dir : /usr/local/Cellar/ruby/2.2.2/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 26da7869de9264bdf72e7af6024b68be40bd4fc7
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-search  : 0.1.0
cocoapods-stats   : 0.6.2
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.5.1
```

### Podfile

```ruby
platform :osx, '10.6'
```

### Error

```
TypeError - [bug] frozen object (JSON::Ext::Generator::State) allocated
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/gems/cocoapods-stats-0.6.2/lib/cocoapods_stats/sender.rb:24:in `dup'
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/gems/cocoapods-stats-0.6.2/lib/cocoapods_stats/sender.rb:24:in `to_json'
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/gems/cocoapods-stats-0.6.2/lib/cocoapods_stats/sender.rb:24:in `curl'
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/gems/cocoapods-stats-0.6.2/lib/cocoapods_stats/sender.rb:17:in `send'
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/gems/cocoapods-stats-0.6.2/lib/cocoapods_plugin.rb:43:in `block (2 levels) in <module:CocoaPodsStats>'
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:80:in `titled_section'
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/gems/cocoapods-stats-0.6.2/lib/cocoapods_plugin.rb:27:in `block in <module:CocoaPodsStats>'
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:117:in `call'
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:117:in `block (3 levels) in run'
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:140:in `message'
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:111:in `block (2 levels) in run'
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:109:in `each'
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:109:in `block in run'
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:140:in `message'
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:108:in `run'
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:481:in `run_plugins_post_install_hooks'
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:462:in `perform_post_install_actions'
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:113:in `install!'
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:101:in `run'
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/bin/pod:23:in `load'
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/bin/pod:23:in `<main>'
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/bin/ruby_noexec_wrapper:14:in `eval'
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/bin/ruby_noexec_wrapper:14:in `<main>'

**Comment by chrisallick** [comment]
things tried:

rm -rf ~/.cocoapods
uninstalled all gems and installed 39

**Comment by segiddins** [comment]
This is a bug in cocoapods stats.

**Comment by chrisallick** [comment]
Ok, any work around?

**Comment by segiddins** [comment]
Nope, haven't ever seen it before.

**Comment by chrisallick** [comment]
damn...

**Comment by orta** [comment]
You can work around it by disabling stats for the project, add this to your Podfile.

`env["COCOAPODS_DISABLE_STATS"] = "true"`

Can you make me an issue on cocoapods/cocoapods-stats please?

**Comment by chrisallick** [comment]
That didn't work, it complained that that Podfile was invalid, found this somewhere else

ENV["COCOAPODS_DISABLE_STATS"] = "1"

Which I think worked, but still cannot execute

pod install

### Command

```
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 0.39.0
        Ruby : ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
    RubyGems : 2.4.5
        Host : Mac OS X 10.10.5 (14F27)
       Xcode : 6.4 (6E35b)
         Git : git version 2.3.2 (Apple Git-55)
Ruby lib dir : /usr/local/Cellar/ruby/2.2.2/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ cb5d785d7d529af8d1dfed0e107415739564721e
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-search  : 0.1.0
cocoapods-stats   : 0.6.2
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.5.1
```

### Podfile

```ruby
platform :osx, '10.10'

ENV["COCOAPODS_DISABLE_STATS"] = "true"

pod 'AFNetworking', :head
```

### Error

```
TypeError - [bug] frozen object (JSON::Ext::Generator::State) allocated
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/gems/json-1.8.3/lib/json/common.rb:273:in `dup'
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/gems/json-1.8.3/lib/json/common.rb:273:in `pretty_generate'
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/gems/cocoapods-core-0.39.0/lib/cocoapods-core/specification/json.rb:15:in `to_pretty_json'
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/gems/cocoapods-0.39.0/lib/cocoapods/downloader/cache.rb:228:in `block in write_spec'
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/gems/cocoapods-0.39.0/lib/cocoapods/downloader/cache.rb:228:in `open'
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/gems/cocoapods-0.39.0/lib/cocoapods/downloader/cache.rb:228:in `open'
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/gems/cocoapods-0.39.0/lib/cocoapods/downloader/cache.rb:228:in `write_spec'
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/gems/cocoapods-0.39.0/lib/cocoapods/downloader/cache.rb:159:in `block (2 levels) in uncached_pod'
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/gems/cocoapods-0.39.0/lib/cocoapods/downloader/cache.rb:156:in `each'
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/gems/cocoapods-0.39.0/lib/cocoapods/downloader/cache.rb:156:in `block in uncached_pod'
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/gems/cocoapods-0.39.0/lib/cocoapods/downloader/cache.rb:180:in `call'
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/gems/cocoapods-0.39.0/lib/cocoapods/downloader/cache.rb:180:in `in_tmpdir'
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/gems/cocoapods-0.39.0/lib/cocoapods/downloader/cache.rb:152:in `uncached_pod'
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/gems/cocoapods-0.39.0/lib/cocoapods/downloader/cache.rb:33:in `download_pod'
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/gems/cocoapods-0.39.0/lib/cocoapods/downloader.rb:34:in `download'
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/gems/cocoapods-0.39.0/lib/cocoapods/installer/pod_source_installer.rb:113:in `download_source'
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/gems/cocoapods-0.39.0/lib/cocoapods/installer/pod_source_installer.rb:53:in `install!'
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:339:in `install_source_of_pod'
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:306:in `block (2 levels) in install_pod_sources'
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:80:in `titled_section'
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:305:in `block in install_pod_sources'
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:297:in `each'
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:297:in `install_pod_sources'
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:146:in `block in download_dependencies'
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:144:in `download_dependencies'
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:106:in `install!'
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:101:in `run'
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/bin/pod:23:in `load'
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/bin/pod:23:in `<main>'
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/bin/ruby_noexec_wrapper:14:in `eval'
/Users/christopherallick/.rvm/gems/ruby-2.0.0-p247/bin/ruby_noexec_wrapper:14:in `<main>'
```

**Comment by chrisallick** [comment]
I'm on 10.10.5 can you guys give me a ruby version + cocoapods that works? I've never had any problem before. Not sure what even changed on my computer.

**Comment by segiddins** [comment]
I personally use 2.2.3, as it's the latest version, but I'll install `ruby-2.0.0-p247` to check this out -- it looks like a bug in the JSON gem to me.

**Comment by chrisallick** [comment]
Ok, so @segiddins here is an update. Do with it what you will, I was working on another ruby project and got a json error. Simply ran:

gem install json

and the problem was fixed. went back and tried:

pod install

and everything worked. a real head scratcher, but I'm not an expert.

**Comment by segiddins** [comment]
Yeah, sounds like the built in version of JSON you were using was broken 😔
Anyways, thanks for the update!

**Comment by orta** [comment]
Also, FWIW, It wasn't a built in version of json: `ruby 2.2.2p95` isn't native to any OS X :+1: - glad you got it fixed @chrisallick
