### ISSUE TITLE
unknown file type ... tags | works after repeated retries

### ISSUE THREAD

**Issue by subdigital** [CocoaPods/CocoaPods#4461]
Started seeing this yesterday on a different project.  Added a new pod in my project today and saw it again.

I'm using https://github.com/orta/cocoapods-expert-difficulty, not sure if it's related (not using this on the other project I mentioned though)

Repeated `pod install`s makes the error go away (yay?)

### Command

```
/Users/ben/.rbenv/versions/2.1.4/bin/pod install
```

### Report

* What did you do?

Added `pod "Analytics"` to the podfile.

* What happened instead?

:boom: 

### Stack

```
   CocoaPods : 0.39.0
        Ruby : ruby 2.1.4p265 (2014-10-27 revision 48166) [x86_64-darwin14.0]
    RubyGems : 2.2.2
        Host : Mac OS X 10.10.5 (14F27)
       Xcode : 7.1 (7B85)
         Git : git version 2.2.1
Ruby lib dir : /Users/ben/.rbenv/versions/2.1.4/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ ef67f58d424838776f8024e5115bf6da972d6030
```

### Plugins

```
cocoapods-expert-difficulty : 1.0.0
cocoapods-plugins           : 0.4.2
cocoapods-search            : 0.1.0
cocoapods-stats             : 0.6.2
cocoapods-trunk             : 0.6.4
cocoapods-try               : 0.5.1
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

plugin "cocoapods-expert-difficulty"

target 'NSScreencastKit-iOS' do
  platform :ios, '9.0'
  pod 'SSKeychain'
  pod 'Colorkit'
  pod 'AttributedMarkdown', git: "https://github.com/dreamwieber/AttributedMarkdown.git"
  pod 'Argo', podspec: 'Podspecs/Argo.podspec'
  pod 'FXReachability'
end

target 'nsscreencast-tvos' do
  platform :tvos
  pod 'Argo', podspec: 'Podspecs/Argo.podspec'
  pod 'SDWebImage', podspec: 'Podspecs/SDWebImage.podspec'
  pod 'Analytics'
end
```

### Error

```
RuntimeError - unknown file type: /var/folders/15/0gwrjngn0lvb32wrgdf4yz6r0000gn/T/d20151028-48505-1y4biif/.git/tags.48769
/Users/ben/.rbenv/versions/2.1.4/lib/ruby/2.1.0/fileutils.rb:1396:in `copy'
/Users/ben/.rbenv/versions/2.1.4/lib/ruby/2.1.0/fileutils.rb:469:in `block in copy_entry'
/Users/ben/.rbenv/versions/2.1.4/lib/ruby/2.1.0/fileutils.rb:1506:in `call'
/Users/ben/.rbenv/versions/2.1.4/lib/ruby/2.1.0/fileutils.rb:1506:in `wrap_traverse'
/Users/ben/.rbenv/versions/2.1.4/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
/Users/ben/.rbenv/versions/2.1.4/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
/Users/ben/.rbenv/versions/2.1.4/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
/Users/ben/.rbenv/versions/2.1.4/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
/Users/ben/.rbenv/versions/2.1.4/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
/Users/ben/.rbenv/versions/2.1.4/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
/Users/ben/.rbenv/versions/2.1.4/lib/ruby/2.1.0/fileutils.rb:466:in `copy_entry'
/Users/ben/.rbenv/versions/2.1.4/lib/ruby/2.1.0/fileutils.rb:441:in `block in cp_r'
/Users/ben/.rbenv/versions/2.1.4/lib/ruby/2.1.0/fileutils.rb:1579:in `block in fu_each_src_dest'
/Users/ben/.rbenv/versions/2.1.4/lib/ruby/2.1.0/fileutils.rb:1595:in `fu_each_src_dest0'
/Users/ben/.rbenv/versions/2.1.4/lib/ruby/2.1.0/fileutils.rb:1577:in `fu_each_src_dest'
/Users/ben/.rbenv/versions/2.1.4/lib/ruby/2.1.0/fileutils.rb:440:in `cp_r'
/Users/ben/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/cocoapods-0.39.0/lib/cocoapods/downloader/cache.rb:200:in `copy_and_clean'
/Users/ben/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/cocoapods-0.39.0/lib/cocoapods/downloader/cache.rb:158:in `block (2 levels) in uncached_pod'
/Users/ben/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/cocoapods-0.39.0/lib/cocoapods/downloader/cache.rb:156:in `each'
/Users/ben/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/cocoapods-0.39.0/lib/cocoapods/downloader/cache.rb:156:in `block in uncached_pod'
/Users/ben/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/cocoapods-0.39.0/lib/cocoapods/downloader/cache.rb:180:in `call'
/Users/ben/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/cocoapods-0.39.0/lib/cocoapods/downloader/cache.rb:180:in `in_tmpdir'
/Users/ben/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/cocoapods-0.39.0/lib/cocoapods/downloader/cache.rb:152:in `uncached_pod'
/Users/ben/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/cocoapods-0.39.0/lib/cocoapods/downloader/cache.rb:33:in `download_pod'
/Users/ben/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/cocoapods-0.39.0/lib/cocoapods/downloader.rb:34:in `download'
/Users/ben/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/pod_source_installer.rb:113:in `download_source'
/Users/ben/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/pod_source_installer.rb:53:in `install!'
/Users/ben/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:339:in `install_source_of_pod'
/Users/ben/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:306:in `block (2 levels) in install_pod_sources'
/Users/ben/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:80:in `titled_section'
/Users/ben/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:305:in `block in install_pod_sources'
/Users/ben/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:297:in `each'
/Users/ben/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:297:in `install_pod_sources'
/Users/ben/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:146:in `block in download_dependencies'
/Users/ben/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Users/ben/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:144:in `download_dependencies'
/Users/ben/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:106:in `install!'
/Users/ben/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/ben/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:101:in `run'
/Users/ben/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Users/ben/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Users/ben/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/Users/ben/.rbenv/versions/2.1.4/bin/pod:23:in `load'
/Users/ben/.rbenv/versions/2.1.4/bin/pod:23:in `<main>'
```

**Comment by segiddins** [comment]
Do you have a git hook that would be creating those files?
