### ISSUE TITLE
Unable to add a source with url

### ISSUE THREAD

**Issue by danipralea** [CocoaPods/CocoaPods#4471]
System information : 
Mac OS El Capitan 10.11.1
Xcode version - 7.1
Command line tools 7.1 (7B91b)

```
pod install --verbose
  Preparing

Creating shallow clone of spec repo `master` from `https://github.com/CocoaPods/Specs.git`
  $ /usr/bin/git clone https://github.com/CocoaPods/Specs.git master --depth=1
  2015-10-31 00:57:43.541 xcodebuild[14346:419623] [MT] PluginLoading: Skipping plug-in at path '/Users/praleadanut/Library/Application Support/Developer/Shared/Xcode/Plug-ins/SuggestedColors.xcplugin' because it is not compatible with this version of Xcode.
  2015-10-31 00:57:43.541 xcodebuild[14346:419623] Failed to load plugin at: /Users/praleadanut/Library/Application Support/Developer/Shared/Xcode/Plug-ins/SuggestedColors.xcplugin, skipping.  Reason for failure: *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]
  2015-10-31 00:57:43.542 xcodebuild[14346:419623] [MT] PluginLoading: Required plug-in compatibility UUID 7265231C-39B4-402C-89E1-16167C4CC990 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/RealmPlugin.xcplugin' not present in DVTPlugInCompatibilityUUIDs
  2015-10-31 00:57:43.542 xcodebuild[14346:419623] [MT] PluginLoading: Required plug-in compatibility UUID 7265231C-39B4-402C-89E1-16167C4CC990 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/RealmBrowser.xcplugin' not present in DVTPlugInCompatibilityUUIDs
  2015-10-31 00:57:43.543 xcodebuild[14346:419623] [MT] PluginLoading: Required plug-in compatibility UUID 7265231C-39B4-402C-89E1-16167C4CC990 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/OMColorSense.xcplugin' not present in DVTPlugInCompatibilityUUIDs
  2015-10-31 00:57:43.543 xcodebuild[14346:419623] [MT] PluginLoading: Required plug-in compatibility UUID 7265231C-39B4-402C-89E1-16167C4CC990 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/KSImageNamed.xcplugin' not present in DVTPlugInCompatibilityUUIDs
  2015-10-31 00:57:43.544 xcodebuild[14346:419623] [MT] PluginLoading: Required plug-in compatibility UUID 7265231C-39B4-402C-89E1-16167C4CC990 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/CodePilot3.xcplugin' not present in DVTPlugInCompatibilityUUIDs
  2015-10-31 00:57:43.544 xcodebuild[14346:419623] [MT] PluginLoading: Required plug-in compatibility UUID 7265231C-39B4-402C-89E1-16167C4CC990 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/BBUFullIssueNavigator.xcplugin' not present in DVTPlugInCompatibilityUUIDs
  sh: line 1: 14350 Segmentation fault: 11  /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -sdk macosx -find git 2> /dev/null
  git: error: unable to find utility "git", not a developer tool or in PATH
[!] Unable to add a source with url `https://github.com/CocoaPods/Specs.git` named `master`.
You can try adding it manually in `~/.cocoapods/repos` or via `pod repo add`.

/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/sources_manager.rb:48:in `rescue in find_or_create_source_with_url'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/sources_manager.rb:53:in `find_or_create_source_with_url'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:620:in `block in sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:619:in `map'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:619:in `sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:129:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:105:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by segiddins** [comment]
Have you accepted the Xcode license?

**Comment by danipralea** [comment]
yes, I did.

**Comment by segiddins** [comment]
What's the output of `xcrun git --version`?

**Comment by danipralea** [comment]
```
xcrun git --version
2015-10-31 01:05:48.086 xcodebuild[14669:426994] [MT] PluginLoading: Skipping plug-in at path '/Users/praleadanut/Library/Application Support/Developer/Shared/Xcode/Plug-ins/SuggestedColors.xcplugin' because it is not compatible with this version of Xcode.
2015-10-31 01:05:48.087 xcodebuild[14669:426994] Failed to load plugin at: /Users/praleadanut/Library/Application Support/Developer/Shared/Xcode/Plug-ins/SuggestedColors.xcplugin, skipping.  Reason for failure: *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]
2015-10-31 01:05:48.088 xcodebuild[14669:426994] [MT] PluginLoading: Required plug-in compatibility UUID 7265231C-39B4-402C-89E1-16167C4CC990 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/RealmPlugin.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-10-31 01:05:48.088 xcodebuild[14669:426994] [MT] PluginLoading: Required plug-in compatibility UUID 7265231C-39B4-402C-89E1-16167C4CC990 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/RealmBrowser.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-10-31 01:05:48.088 xcodebuild[14669:426994] [MT] PluginLoading: Required plug-in compatibility UUID 7265231C-39B4-402C-89E1-16167C4CC990 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/OMColorSense.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-10-31 01:05:48.089 xcodebuild[14669:426994] [MT] PluginLoading: Required plug-in compatibility UUID 7265231C-39B4-402C-89E1-16167C4CC990 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/KSImageNamed.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-10-31 01:05:48.090 xcodebuild[14669:426994] [MT] PluginLoading: Required plug-in compatibility UUID 7265231C-39B4-402C-89E1-16167C4CC990 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/CodePilot3.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-10-31 01:05:48.090 xcodebuild[14669:426994] [MT] PluginLoading: Required plug-in compatibility UUID 7265231C-39B4-402C-89E1-16167C4CC990 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/BBUFullIssueNavigator.xcplugin' not present in DVTPlugInCompatibilityUUIDs
sh: line 1: 14672 Segmentation fault: 11  /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -sdk macosx -find git 2> /dev/null
xcrun: error: unable to find utility "git", not a developer tool or in PATH
```

**Comment by segiddins** [comment]
This is an issue with your installation of the developer tools, then, and not a CocoaPods issue.

**Comment by danipralea** [comment]
ok, thanks... I guess... :smiley:

**Comment by istx25** [comment]
@segiddins What's the cause then? I'm experiencing something similar. With Carthage. 

`$ carthage update --platform ios`

```
*** Fetching SAMTextView
*** Fetching stripe-ios
*** Downloading stripe-ios at "v5.0.0"
*** Checking out stripe-ios at "v5.0.0"
*** Checking out SAMTextView at "d94fe8d45484d33c917064535fdc0adb66d228bb"
*** xcodebuild output can be found in /var/folders/n0/b6cmfvs16676c09sswtw51kr0000gn/T/carthage-xcodebuild.akCkv6.log
*** Building scheme "SAMTextView" in SAMTextView.xcodeproj
2015-11-29 19:25:51.760 xcodebuild[12855:4527958] [MT] PluginLoading: Required plug-in compatibility UUID 7265231C-39B4-402C-89E1-16167C4CC990 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/RealmPlugin.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-11-29 19:25:53.932 xcodebuild[12958:4528337] [MT] PluginLoading: Required plug-in compatibility UUID 7265231C-39B4-402C-89E1-16167C4CC990 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/RealmPlugin.xcplugin' not present in DVTPlugInCompatibilityUUIDs
*** Building scheme "StripeiOS" in Stripe.xcworkspace
2015-11-29 19:26:05.305 xcodebuild[13147:4529713] [MT] PluginLoading: Required plug-in compatibility UUID 7265231C-39B4-402C-89E1-16167C4CC990 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/RealmPlugin.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-11-29 19:26:06.807 xcodebuild[13181:4529806] [MT] PluginLoading: Required plug-in compatibility UUID 7265231C-39B4-402C-89E1-16167C4CC990 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/RealmPlugin.xcplugin' not present in DVTPlugInCompatibilityUUIDs
> willow ~/Workspace/projects/linehop $ 
```
and 

`$ xcrun git —version`
returns `git version 2.4.9 (Apple Git-60)`

Any ideas?
