### ISSUE TITLE
[command not found: pod]Update EI Capitan 10.11.1 Cocoapods not wrok

### ISSUE THREAD

**Issue by sauchye** [CocoaPods/CocoaPods#4479]
This info:

```
➜  ~  pod --verion
zsh: command not found: pod
➜  ~  pod update
zsh: command not found: pod
➜  ~  gem source -l
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych.rb:205:in `parse': (<unknown>): could not find expected ':' while scanning a simple key at line 11 column 1 (Psych::SyntaxError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych.rb:205:in `parse_stream'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych.rb:153:in `parse'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych.rb:129:in `load'
	from /Library/Ruby/Site/2.0.0/rubygems/config_file.rb:333:in `load_file'
	from /Library/Ruby/Site/2.0.0/rubygems/config_file.rb:198:in `initialize'
	from /Library/Ruby/Site/2.0.0/rubygems/gem_runner.rb:74:in `new'
	from /Library/Ruby/Site/2.0.0/rubygems/gem_runner.rb:74:in `do_configuration'
	from /Library/Ruby/Site/2.0.0/rubygems/gem_runner.rb:39:in `run'
	from /usr/bin/gem:21:in `<main>'
```

And i change ``csrutil`` status, but not fix it.

```

**Comment by segiddins** [comment]
This sounds like a rubygems issue rather than something specific to cocoapods.

**Comment by sauchye** [comment]
thanks :）
