### ISSUE TITLE
NoMethodError - undefined method `update' for #<Pod::Source name:master type:file system>

### ISSUE THREAD

**Issue by kayvan-n** [CocoaPods/CocoaPods#4506]
### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?
i tries to run `pod install` and got this error.

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 0.39.0
        Ruby : ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin15]
    RubyGems : 2.4.5
        Host : Mac OS X 10.11 (15A284)
       Xcode : 7.1 (7B91b)
         Git : git version 2.4.9 (Apple Git-60)
Ruby lib dir : /usr/local/Cellar/ruby/2.2.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 298d9220126ab038c3ba41e57ae1185659c86b23
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-search  : 0.1.0
cocoapods-stats   : 0.6.2
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.5.1
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

target 'XXX' do
pod "AMSlideMenu", "~> 1.5.4"
pod "AFNetworking", "~> 2.0"
pod "VKVideoPlayer", "~> 0.1.4"
pod "Masonry", "~> 0.6.2"
pod "SZTextView", "~> 1.2.1"
pod "UIActivityIndicator-for-SDWebImage", "~> 1.2"
pod "Parse", "~> 1.9.0"
pod "ParseCrashReporting", "~> 1.9"
pod "Bolts", "~> 1.4"
end
```

### Error

```
NoMethodError - undefined method `update' for #<Pod::Source name:master type:file system>
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/sources_manager.rb:306:in `block (2 levels) in update'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/sources_manager.rb:305:in `block in update'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/sources_manager.rb:304:in `each'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/sources_manager.rb:304:in `update'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:213:in `block in update_repositories'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:211:in `each'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:211:in `update_repositories'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:132:in `block in resolve_dependencies'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:131:in `resolve_dependencies'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:105:in `install!'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:101:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by segiddins** [comment]
Is this using the released version of CocoaPods?

**Comment by kayvan-n** [comment]
I think so. I'm using CocoaPods version 0.39.0

**Comment by kayvan-n** [comment]
Here is what I have done recently:
A few months ago I installed CocoaPods via `gem install` and it worked perfectly. Two days before I encounter this issue, I installed `Latex` for Mac. (I think this is important because there is some commands like `pod2latex` that I have not noticed before)
After that `pod` command was inaccessible I had to reinstall CocoaPods. After reinstalling (again via `gem install` this issue happened.

**Comment by kayvan-n** [comment]
it seams uninstalling and reinstalling CocoaPods several times solved the problem.
Also I needed to update my repositories to make CocoaPods works fine. (`pod repo update`)

**Comment by allaire** [comment]
Getting this error on master

**Comment by segiddins** [comment]
@allaire using cocoapods master also requires using core master.

**Comment by segiddins** [comment]
Closing since this should be impossible to happen.
