### ISSUE TITLE
lint crashes with error on latest master

### ISSUE THREAD

**Issue by dnkoutso** [CocoaPods/CocoaPods#4523]
``` 
-> InternalLib (1.0.42)
    - ERROR | [iOS] unknown: Encountered an unknown error (undefined method `build_configuration_list' for nil:NilClass
/Users/build/.rvm/gems/ruby-2.0.0-p481/gems/cocoapods-0.39.5058/lib/cocoapods/validator.rb:435:in `block (2 levels) in install_pod'
/Users/build/.rvm/gems/ruby-2.0.0-p481/gems/cocoapods-0.39.5058/lib/cocoapods/validator.rb:433:in `each'
/Users/build/.rvm/gems/ruby-2.0.0-p481/gems/cocoapods-0.39.5058/lib/cocoapods/validator.rb:433:in `block in install_pod'
/Users/build/.rvm/gems/ruby-2.0.0-p481/gems/cocoapods-0.39.5058/lib/cocoapods/validator.rb:432:in `each'
/Users/build/.rvm/gems/ruby-2.0.0-p481/gems/cocoapods-0.39.5058/lib/cocoapods/validator.rb:432:in `install_pod'
/Users/build/.rvm/gems/ruby-2.0.0-p481/gems/cocoapods-0.39.5058/lib/cocoapods/validator.rb:270:in `block in perform_extensive_analysis'
/Users/build/.rvm/gems/ruby-2.0.0-p481/gems/cocoapods-0.39.5058/lib/cocoapods/validator.rb:262:in `each'
/Users/build/.rvm/gems/ruby-2.0.0-p481/gems/cocoapods-0.39.5058/lib/cocoapods/validator.rb:262:in `perform_extensive_analysis'
/Users/build/.rvm/gems/ruby-2.0.0-p481/gems/cocoapods-0.39.5058/lib/cocoapods/validator.rb:79:in `validate'
/Users/build/.rvm/gems/ruby-2.0.0-p481/gems/cocoapods-0.39.5058/lib/cocoapods/command/lib.rb:164:in `block in run'
/Users/build/.rvm/gems/ruby-2.0.0-p481/gems/cocoapods-0.39.5058/lib/cocoapods/command/lib.rb:153:in `each'
/Users/build/.rvm/gems/ruby-2.0.0-p481/gems/cocoapods-0.39.5058/lib/cocoapods/command/lib.rb:153:in `run'
/Users/build/.rvm/gems/ruby-2.0.0-p481@global/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Users/build/.rvm/gems/ruby-2.0.0-p481/gems/cocoapods-0.39.5058/lib/cocoapods/command.rb:47:in `run'
/Users/build/.rvm/gems/ruby-2.0.0-p481/gems/cocoapods-0.39.5058/bin/pod:44:in `<top (required)>'
/Users/build/.rvm/gems/ruby-2.0.0-p481/bin/pod:23:in `load'
/Users/build/.rvm/gems/ruby-2.0.0-p481/bin/pod:23:in `<main>'
/Users/build/.rvm/gems/ruby-2.0.0-p481/bin/ruby_executable_hooks:15:in `eval'
/Users/build/.rvm/gems/ruby-2.0.0-p481/bin/ruby_executable_hooks:15:in `<main>'
```

We made an internal release of CocoaPods from SHA b917ffd9e16769c48a7bf748d8d111e6bd015ac8 (called it .5058 for internal reasons) but when we `lint` the above error shows up.

I cannot provide the podspec unfortunately as its internal but I can tell you it has one dependency to another internal pod that has only `.h` files and a pre-built vendored-library `.a`, no other actual sources.

Both the podspec being linted and its dependency to the internal pod have `s.ios.deployment_target = "7.0"`

Works with 0.39.0

**Comment by dnkoutso** [comment]
Removing the podspec -> internal pod dependency makes it work...but ultimately we dont want that.

**Comment by segiddins** [comment]
Are you sure you're also using the correct commits of Core and Xcodeproj?

**Comment by dnkoutso** [comment]
I will verify again perhaps that is the case.

**Comment by dnkoutso** [comment]
@segiddins I have reproduced the issue.

It occurs for podspecs and libraries that have no source files and are pre-built. Here's a zip with a pre-built sample library and a podspec that fails to lint it.

Again this is using our internal release of CocoaPods but here are the SHAs.

```
  # 1. CocoaPods master -> sha: 2128c44a799d46fdfeca85e4af2ed15f95310a2e
  # 2. Xcodeproj -> sha: fe9b173a46052a0743b4a7f52274f3bfd2ad327f
  # 3. CocoaPods-Core -> sha: 6c2544496ed201104e712dd95793ec7bc6a171e8
```

https://www.dropbox.com/s/v4034137rlkd3mx/SampleLibrary.zip?dl=0

**Comment by segiddins** [comment]
Ah ok I think I know what's causing this, thanks!

**Comment by dnkoutso** [comment]
:+1:
