### ISSUE TITLE
pod install Error cannot load such file -- active_support/inflector

### ISSUE THREAD

**Issue by aceprince** [CocoaPods/CocoaPods#4525]
### Command

```
/usr/bin/pod install
```

### Stack

```
   CocoaPods : 0.39.0
        Ruby : ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]
    RubyGems : 2.5.0
        Host : Mac OS X 10.11.1 (15B42)
       Xcode : 7.1 (7B91b)
         Git : git version 2.4.9 (Apple Git-60)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ e43b7064cacd2bdfff162294cd9f8eb32928bd7e
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-search  : 0.1.0
cocoapods-stats   : 0.6.2
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.5.1
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target :Demo do
    pod 'AFNetworking', '~> 2.4.1'
end
```

### Error

```
LoadError - cannot load such file -- active_support/inflector
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/project/object_attributes.rb:15:in `<class:AbstractObjectAttribute>'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/project/object_attributes.rb:14:in `<module:Object>'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/project/object_attributes.rb:3:in `<class:Project>'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/project/object_attributes.rb:2:in `<module:Xcodeproj>'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/project/object_attributes.rb:1:in `<top (required)>'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/project/object.rb:468:in `<top (required)>'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/project.rb:4:in `<top (required)>'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer/target_inspector.rb:32:in `compute_results'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:659:in `block (2 levels) in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:657:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:657:in `block in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:656:in `inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:61:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:213:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:136:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:135:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:105:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

**Comment by blackhuman** [comment]
Maybe it lacks a gem **activesupport** which is used as "*A toolkit of support libraries and Ruby core extensions extracted from the Rails framework. *"
Try `sudo gem install activesupport` to solve this.

**Comment by aceprince** [comment]
@blackhuman thanks, you are right!
