### ISSUE TITLE
Pod install fails

### ISSUE THREAD

**Issue by dylangyesbreghs** [CocoaPods/CocoaPods#4542]
――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/dylangyesbreghs/.rbenv/versions/2.2.3/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 0.39.0
        Ruby : ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]
    RubyGems : 2.4.5.1
        Host : Mac OS X 10.11.1 (15B42)
       Xcode : 7.1.1 (7B1005)
         Git : git version 2.4.9 (Apple Git-60)
Ruby lib dir : /Users/dylangyesbreghs/.rbenv/versions/2.2.3/lib
Repositories : bitbucket-icapps-podspecs - https://bitbucket.org/icapps/podspecs @ 367925ab6df8819668c7df726890ecefaa74d92a
               master - https://github.com/CocoaPods/Specs.git @ 7b277298f139fe9aa7f875bc399e6624c38dcb8d
```

### Plugins

```
cocoapods-deintegrate : 0.2.1
cocoapods-plugins     : 0.4.2
cocoapods-search      : 0.1.0
cocoapods-stats       : 0.6.2
cocoapods-trunk       : 0.6.4
cocoapods-try         : 0.5.1
```

### Podfile

```ruby
platform :ios, '8.0'
pod "RMDateSelectionViewController", "~> 2.0.3"
```

### Error

```
NoMethodError - undefined method `dump' for Psych:Module
/Users/dylangyesbreghs/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-core-0.39.0/lib/cocoapods-core/yaml_helper.rb:99:in `process_according_to_class'
/Users/dylangyesbreghs/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-core-0.39.0/lib/cocoapods-core/yaml_helper.rb:112:in `block in process_array'
/Users/dylangyesbreghs/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-core-0.39.0/lib/cocoapods-core/yaml_helper.rb:111:in `map'
/Users/dylangyesbreghs/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-core-0.39.0/lib/cocoapods-core/yaml_helper.rb:111:in `process_array'
/Users/dylangyesbreghs/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-core-0.39.0/lib/cocoapods-core/yaml_helper.rb:97:in `process_according_to_class'
/Users/dylangyesbreghs/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-core-0.39.0/lib/cocoapods-core/yaml_helper.rb:148:in `block in process_hash'
/Users/dylangyesbreghs/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-core-0.39.0/lib/cocoapods-core/yaml_helper.rb:146:in `map'
/Users/dylangyesbreghs/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-core-0.39.0/lib/cocoapods-core/yaml_helper.rb:146:in `process_hash'
/Users/dylangyesbreghs/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-core-0.39.0/lib/cocoapods-core/yaml_helper.rb:41:in `convert_hash'
/Users/dylangyesbreghs/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-core-0.39.0/lib/cocoapods-core/lockfile.rb:347:in `to_yaml'
/Users/dylangyesbreghs/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-core-0.39.0/lib/cocoapods-core/lockfile.rb:300:in `block in write_to_disk'
/Users/dylangyesbreghs/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-core-0.39.0/lib/cocoapods-core/lockfile.rb:300:in `open'
/Users/dylangyesbreghs/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-core-0.39.0/lib/cocoapods-core/lockfile.rb:300:in `open'
/Users/dylangyesbreghs/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-core-0.39.0/lib/cocoapods-core/lockfile.rb:300:in `write_to_disk'
/Users/dylangyesbreghs/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:724:in `block in write_lockfiles'
/Users/dylangyesbreghs/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:140:in `message'
/Users/dylangyesbreghs/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:723:in `write_lockfiles'
/Users/dylangyesbreghs/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:161:in `block in generate_pods_project'
/Users/dylangyesbreghs/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Users/dylangyesbreghs/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:153:in `generate_pods_project'
/Users/dylangyesbreghs/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:111:in `install!'
/Users/dylangyesbreghs/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/dylangyesbreghs/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:101:in `run'
/Users/dylangyesbreghs/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Users/dylangyesbreghs/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Users/dylangyesbreghs/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/Users/dylangyesbreghs/.rbenv/versions/2.2.3/bin/pod:23:in `load'
/Users/dylangyesbreghs/.rbenv/versions/2.2.3/bin/pod:23:in `<main>'
```
――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

**Comment by orta** [comment]
Likely a dupe of https://github.com/CocoaPods/CocoaPods/issues/2908 - @dylangyesbreghs can you please search for issues before writing new ones: https://github.com/CocoaPods/CocoaPods/search?q=Psych%3AModule&type=Issues&utf8=✓
