### ISSUE TITLE
Im not able to install CocoaPods (El Capitain - OSX)

### ISSUE THREAD

**Issue by mlaidouni** [CocoaPods/CocoaPods#4547]
Hello everyone, im facing an issue when i type this command on terminal:

$ vim Podfile
$ pod install

![Issue CocoPods](https://d3c33hcgiwev3.cloudfront.net/imageAssetProxy.v1/T_FIB4xrEeWisRLkE7o57Q_20da0d90099547f02ed2a2ff970dd174_Capture-d__cran-2015-11-16-_-15.06.44.png?expiry=1447804800000&hmac=U-UDCalHRgaOrdhEjQmkocF7rEmPjR87l-e3fy7oSd4)

i have installed CocoaPods and i can't add it to xcode, when i type Pod Install on terminal its bring me this error, so maybe im going something wrong, does someone have an idea about what could be raison for this issue ??

Any solution would be very helpful, Thanks

**Comment by segiddins** [comment]
Can you please share the entire error report?

**Comment by mlaidouni** [comment]
Hi @segiddins Thanks for quick replay, here is the entire error report

### Error

```
ArgumentError - Illformed requirement `"-> 1.2.8"`
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-core-0.39.0/lib/cocoapods-core/requirement.rb:63:in `parse'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-core-0.39.0/lib/cocoapods-core/requirement.rb:88:in `block in initialize'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-core-0.39.0/lib/cocoapods-core/requirement.rb:88:in `map!'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-core-0.39.0/lib/cocoapods-core/requirement.rb:88:in `initialize'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-core-0.39.0/lib/cocoapods-core/requirement.rb:34:in `new'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-core-0.39.0/lib/cocoapods-core/requirement.rb:34:in `create'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-core-0.39.0/lib/cocoapods-core/dependency.rb:92:in `initialize'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-core-0.39.0/lib/cocoapods-core/podfile/target_definition.rb:650:in `new'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-core-0.39.0/lib/cocoapods-core/podfile/target_definition.rb:650:in `block in pod_dependencies'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-core-0.39.0/lib/cocoapods-core/podfile/target_definition.rb:646:in `map'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-core-0.39.0/lib/cocoapods-core/podfile/target_definition.rb:646:in `pod_dependencies'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-core-0.39.0/lib/cocoapods-core/podfile/target_definition.rb:87:in `non_inherited_dependencies'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-core-0.39.0/lib/cocoapods-core/podfile/target_definition.rb:79:in `dependencies'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/podfile_validator.rb:59:in `block in validate_pod_directives'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/podfile_validator.rb:58:in `each'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/podfile_validator.rb:58:in `flat_map'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/podfile_validator.rb:58:in `validate_pod_directives'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/podfile_validator.rb:29:in `validate'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:155:in `validate_podfile!'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:57:in `analyze'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:213:in `analyze'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:136:in `block in resolve_dependencies'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:135:in `resolve_dependencies'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:105:in `install!'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:101:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by segiddins** [comment]
You need to change `"-> 1.2.8"` to `"~> 1.2.8"`.
