### ISSUE TITLE
Error while generate project structure 

### ISSUE THREAD

**Issue by rmuhamedgaliev** [CocoaPods/CocoaPods#4596]
```bash
### Stack

   CocoaPods : 0.39.0
        Ruby : ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]
    RubyGems : 2.4.8
        Host : Mac OS X 10.11.1 (15B42)
       Xcode : 7.1.1 (7B1005)
         Git : git version 2.4.9 (Apple Git-60)
Ruby lib dir : /usr/local/Cellar/ruby/2.2.3/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ a828e815ac7b13b5fdffeac92657ccb8f235a78b


### Plugins


cocoapods-plugins : 0.4.2
cocoapods-search  : 0.1.0
cocoapods-stats   : 0.6.2
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.5.1


### Podfile

### Error

NoMethodError - undefined method `[]' for nil:NilClass
/usr/local/lib/ruby/gems/2.2.0/gems/xcodeproj-0.28.2/lib/xcodeproj/project.rb:461:in `[]'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:90:in `set_target_xcconfig'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:25:in `block (2 levels) in integrate'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:23:in `each'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:23:in `block in integrate'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:22:in `each'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:22:in `integrate'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/user_project_integrator/target_integrator.rb:43:in `block in integrate!'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/user_project_integrator/target_integrator.rb:40:in `integrate!'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/user_project_integrator.rb:116:in `block in integrate_user_targets'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/user_project_integrator.rb:115:in `each'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/user_project_integrator.rb:115:in `integrate_user_targets'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/user_project_integrator.rb:63:in `integrate!'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:750:in `block in integrate_user_project'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:747:in `integrate_user_project'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:112:in `install!'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:101:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=undefined+method+%60%5B%5D%27+for+nil%3ANilClass&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!
```

Why it happens?

**Comment by neonichu** [comment]
Hard to say without more information, it looks like Xcodeproj cannot find the main group of your project. Are you able to share the project file or any other way for us to reproduce it?

**Comment by neonichu** [comment]
Closing because of lack of response.
