### ISSUE TITLE
NoMethodError - undefined method `each_recursive' for nil:NilClass

### ISSUE THREAD

**Issue by daemonDevarshi** [CocoaPods/CocoaPods#4679]
### Report

* What did you do?

Tried `pod install` and got reported error :(
Next time tried `pod update` still same error :’(

* What did you expect to happen?

Workspace to be configured properly without any error

* What happened instead?

It showed reported error after these statements:
```
Generating Pods project
Integrating client project
```

### Stack

```
   CocoaPods : 0.39.0
        Ruby : ruby 2.0.0p643 (2015-02-25 revision 49749) [x86_64-darwin14.1.0]
    RubyGems : 2.4.6
        Host : Mac OS X 10.11 (15A284)
       Xcode : 7.1 (7B91b)
         Git : git version 2.4.9 (Apple Git-60)
Ruby lib dir : /Users/myaccount/.rvm/rubies/ruby-2.0.0-p643/lib
Repositories : Login - https://my_personal_bit_bucket_repo@bitbucket.org/my_personal_bit_bucket_repo/login.git @ 7093g3cefda84ea50c086d43f1afc84031d12a4h3s
               master - https://github.com/CocoaPods/Specs.git @ 8a415b349e657a17093g3cefdaa99d031d12a4h3s
               MyLogin - https://my_personal_bit_bucket_repo@bitbucket.org/my_personal_bit_bucket_repo/mylogin.git @ bsd3ts7154dd8a415b349e6b7a31e3a7093g3cefda
               MyRepo - https://my_personal_bit_bucket_repo@bitbucket.org/my_personal_bit_bucket_repo/mylogin.git @ fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
HEAD
               MySubModule - https://my_personal_bit_bucket_repo@bitbucket.org/my_personal_bit_bucket_repo/mysubmodule.git @ 8a415b349e62d6d43f1afc8403926740e153e5eb
               XYPodSpecs - https://my_personal_bit_bucket_repo@bitbucket.org/my_personal_bit_bucket_repo/XYpodspecs.git @ b349e62d6d4378a31d9c3f27278dafc840392674
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-search  : 0.1.0
cocoapods-stats   : 0.6.2
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.5.1
```

### Podfile

```ruby
platform :ios, '7.1'

pod 'Reachability', '~> 3.2'

#pod 'JWT', git: 'https://github.com/yourkarma/JWT.git', tag: '1.0.0'
pod 'LBBlurredImage'
pod 'DCPathButton', '~> 2.0.2'
#pod 'TTTAttributedLabel'
pod 'AFNetworking', '~> 2.0' 
#pod 'FMDB', '~> 2.2'
pod 'RETableViewManager', :head
pod 'RESideMenu', '~> 4.0.3'
pod 'ReactiveCocoa', '~> 2.3' 
pod 'FontAwesomeKit', '~> 2.2'
pod 'PixateFreestyle', '~> 2.1'
#pod 'MKNetworkKit', '0.87'
pod 'GoogleAnalytics-iOS-SDK', '~> 3.0'
pod 'FlurrySDK', '~> 5.4'
#pod 'Reveal-iOS-SDK', '~> 1.5.1', :configurations => ['Debug']
pod 'TMCache', :head
#pod 'PRAugmentedReality', '~> 3.1'
pod 'MBProgressHUD', '~> 0.8'
pod 'J2ObjC', '~> 0.9.3'
pod 'Fabric'
pod 'Crashlytics'
pod 'ComponentKit', '0.11'
pod 'FBSDKCoreKit', '~> 4.1'
pod 'apptentive-ios', '~> 1.7'
pod 'MobileAppTracker', '~> 3.8'
pod 'UrbanAirship-iOS-SDK', '~> 6.0'
pod 'youtube-ios-player-helper', '~> 0.1.3'
pod 'NMRangeSlider', '~> 1.2'
pod 'JSONModel', '~> 1.0.2'


#pod 'XY/XYCommon', :path => 'XY/'


target :’Xyzd’ do
  pod 'XY/Assets/Brands/Xyzd', :path => 'XY/'
end

target :’Tree’ do
  pod 'XY/Assets/Brands/Tree', :path => 'XY/'
end
```

### Error

```
NoMethodError - undefined method `each_recursive' for nil:NilClass
/Users/myaccount/.rvm/gems/ruby-2.0.0-p643/gems/xcodeproj-0.28.2/lib/xcodeproj/workspace.rb:148:in `to_s'
/Users/myaccount/.rvm/gems/ruby-2.0.0-p643/gems/xcodeproj-0.28.2/lib/xcodeproj/workspace.rb:178:in `block in save_as'
/Users/myaccount/.rvm/gems/ruby-2.0.0-p643/gems/xcodeproj-0.28.2/lib/xcodeproj/workspace.rb:177:in `open'
/Users/myaccount/.rvm/gems/ruby-2.0.0-p643/gems/xcodeproj-0.28.2/lib/xcodeproj/workspace.rb:177:in `save_as'
/Users/myaccount/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-0.39.0/lib/cocoapods/installer/user_project_integrator.rb:95:in `create_workspace'
/Users/myaccount/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-0.39.0/lib/cocoapods/installer/user_project_integrator.rb:62:in `integrate!'
/Users/myaccount/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:750:in `block in integrate_user_project'
/Users/myaccount/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Users/myaccount/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:747:in `integrate_user_project'
/Users/myaccount/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:112:in `install!'
/Users/myaccount/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/myaccount/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:156:in `run'
/Users/myaccount/.rvm/gems/ruby-2.0.0-p643/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Users/myaccount/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Users/myaccount/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/Users/myaccount/.rvm/gems/ruby-2.0.0-p643/bin/pod:23:in `load'
/Users/myaccount/.rvm/gems/ruby-2.0.0-p643/bin/pod:23:in `<main>'
/Users/myaccount/.rvm/gems/ruby-2.0.0-p643/bin/ruby_executable_hooks:15:in `eval'
/Users/myaccount/.rvm/gems/ruby-2.0.0-p643/bin/ruby_executable_hooks:15:in `<main>'

**Comment by neonichu** [comment]
Seems there is some issue with generating the workspace — could you tell us the name of your Xcode project?

**Comment by daemonDevarshi** [comment]
`XYMobile`

**Comment by neonichu** [comment]
That is weird, I kinda expected it to contain non-ASCII characters or be "special" in some other way. Could you try deleting the workspace and see if regenerating it from scratch helps?

**Comment by daemonDevarshi** [comment]
voila.. it resolved the issue.. I owe you a bear for that :)

**Comment by neonichu** [comment]
:beers:
