### ISSUE TITLE
error on  `pod outdated`

### ISSUE THREAD

**Issue by alphastryk** [CocoaPods/CocoaPods#4699]
🌈 

### Command

```
/usr/local/bin/pod outdated
```

### Report

* What did you do?

ran `pod outdated` in my project directory

* What did you expect to happen?

list of outdated pods

* What happened instead?

error, see below

### Stack

```
   CocoaPods : 0.39.0
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.2 (15C50)
       Xcode : 7.2 (7C68)
         Git : git version 2.5.4 (Apple Git-61)
Ruby lib dir : /usr/local/Cellar/ruby/2.3.0/lib
Repositories : jumio-distribution - http://mobile-sdk.jumio.com/distribution.git @ 37633e096078578ab921818e32351c6a0d089e08
               master - https://github.com/CocoaPods/Specs.git @ 298493999ed1a38de73fe168431cbd18d07558d5
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-search  : 0.1.0
cocoapods-stats   : 0.6.2
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.5.1
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
source 'http://mobile-sdk.jumio.com/distribution.git'

workspace 'WorkspaceName.xcworkspace'
xcodeproj 'ProjectName.xcodeproj'

platform :ios, '8.0'

target :ProjectName do
    pod 'AFNetworking', '~> 2.5.3', :inhibit_warnings => true
    pod 'AFNetworkActivityLogger', '~> 2.0', :inhibit_warnings => true
    pod 'Mantle', '~> 1.5', :inhibit_warnings => true
    pod 'MBProgressHUD', '~> 0.9', :inhibit_warnings => true
    pod 'AXRatingView', '~> 1.0', :inhibit_warnings => true
    pod 'objc-geohash', '~> 0.0', :inhibit_warnings => true
    pod 'NewRelicAgent', '~> 5.3', :inhibit_warnings => true
    pod 'FBSDKCoreKit', '~> 4.8', :inhibit_warnings => true
    pod 'FBSDKLoginKit', '~> 4.8', :inhibit_warnings => true
    pod 'MobileAppTracker', '~> 3.8.1', :inhibit_warnings => true
    pod 'GPUImage', '~> 0.1.6', :inhibit_warnings => true
    pod 'GoogleConversionTracking', '~> 3.2', :inhibit_warnings => true
    pod 'Branch', '~> 0.11', :inhibit_warnings => true
    pod 'JumioMobileSDK', '1.8.0', :inhibit_warnings => true
    pod 'Ono', '~> 1.2', :inhibit_warnings => true
    pod 'PayPal-iOS-SDK', '~> 2.11', :inhibit_warnings => true
    pod 'GoogleAnalytics', '~> 3.13', :inhibit_warnings => true
    pod 'Mixpanel', '~> 2.9.1', :inhibit_warnings => true
end

target :ProjectNameTests do
    pod 'OHHTTPStubs', '~> 3.1', :inhibit_warnings => true
    pod 'GoogleAnalytics', '~> 3.13', :inhibit_warnings => true
end
```

### Error

```
NoMethodError - undefined method `to_ary' for #<Pod::Specification name="AFNetworkActivityLogger">
Did you mean?  to_query
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver/lazy_specification.rb:14:in `method_missing'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:64:in `flatten'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:64:in `block in resolve'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:63:in `tap'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:63:in `resolve'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:539:in `block in resolve_dependencies'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:537:in `resolve_dependencies'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:70:in `analyze'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command/outdated.rb:75:in `block in unlocked_pods'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:80:in `titled_section'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command/outdated.rb:73:in `unlocked_pods'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command/outdated.rb:61:in `block in updates'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command/outdated.rb:55:in `map'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command/outdated.rb:55:in `updates'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command/outdated.rb:19:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

Even if I run against a project with a single target and a single pod I still have the same issue. `pod install` also fails with the same messaging.

Let me know if there's anything else I can provide to help with this issue - thanks!

**Comment by orta** [comment]
This is a bug we have with ruby 2.3.0, we're releasing a beta pretty soon, or you can use [master CocoaPods](https://guides.cocoapods.org/using/a-gemfile.html) or by switching rubies.

**Comment by alphastryk** [comment]
Ok, thanks for the quick response!

**Comment by idealhack** [comment]
I encountered this problem too. I have to `brew uninstall ruby` and use ruby 2.0 provided by system.

I always have to use CocoaPods 0.35.0, here's why: I have a pod depend on GPUImage, which have warnings when compiling with a higher version of CocoaPods, such as 0.39.0.

I'll try CocoaPods 1.0 after its release, if the problem exists, it should be reported to GPUImage.

**Comment by cepages** [comment]
I have the same problem with ruby 2.3.0, any update about this? 

Which ruby version should I get instead?

Thanks

**Comment by cepages** [comment]
I made it work with 1.0.0.beta.8 

Thanks :)
