### ISSUE TITLE
CocoaPods 1.0 configurations setting error

### ISSUE THREAD

**Issue by keith** [CocoaPods/CocoaPods#4707]
Using CocoaPods 1.0 this code in my Podfile now errors on `pod install`:

```ruby
pod "Foo", :configurations => ["Beta"]
```

Here's the error message:

```
[!] Invalid `Podfile` file: undefined method `<<' for nil:NilClass. Updating CocoaPods might fix the issue.

 #  from /path/Podfile:29
 #  -------------------------------------------
 >      pod 'Foo', :configurations => ['Beta']
 #  -------------------------------------------
```

This didn't seem to be mentioned in the CHANGELOG and I didn't see an integration spec for this so I assume it may have been an oversight.

**Comment by segiddins** [comment]
Can you share the verbose output?

**Comment by keith** [comment]
Here's the stacktrace:

```

/Users/ksmiley/.gem/gems/cocoapods-core-1.0.0.beta.1/lib/cocoapods-core/podfile/target_definition.rb:396:in `whitelist_pod_for_configuration'
/Users/ksmiley/.gem/gems/cocoapods-core-1.0.0.beta.1/lib/cocoapods-core/podfile/target_definition.rb:765:in `block in parse_configuration_whitelist'
/Users/ksmiley/.gem/gems/cocoapods-core-1.0.0.beta.1/lib/cocoapods-core/podfile/target_definition.rb:764:in `each'
/Users/ksmiley/.gem/gems/cocoapods-core-1.0.0.beta.1/lib/cocoapods-core/podfile/target_definition.rb:764:in `parse_configuration_whitelist'
/Users/ksmiley/.gem/gems/cocoapods-core-1.0.0.beta.1/lib/cocoapods-core/podfile/target_definition.rb:480:in `store_pod'
/Users/ksmiley/.gem/gems/cocoapods-core-1.0.0.beta.1/lib/cocoapods-core/podfile/dsl.rb:194:in `pod'
/Users/ksmiley/dev/phoenix/Podfile:29:in `block (2 levels) in from_ruby'
/Users/ksmiley/.gem/gems/cocoapods-core-1.0.0.beta.1/lib/cocoapods-core/podfile/dsl.rb:294:in `target'
/Users/ksmiley/dev/phoenix/Podfile:11:in `block in from_ruby'
/Users/ksmiley/.gem/gems/cocoapods-core-1.0.0.beta.1/lib/cocoapods-core/podfile.rb:291:in `eval'
/Users/ksmiley/.gem/gems/cocoapods-core-1.0.0.beta.1/lib/cocoapods-core/podfile.rb:291:in `block in from_ruby'
/Users/ksmiley/.gem/gems/cocoapods-core-1.0.0.beta.1/lib/cocoapods-core/podfile.rb:51:in `instance_eval'
/Users/ksmiley/.gem/gems/cocoapods-core-1.0.0.beta.1/lib/cocoapods-core/podfile.rb:51:in `initialize'
/Users/ksmiley/.gem/gems/cocoapods-core-1.0.0.beta.1/lib/cocoapods-core/podfile.rb:287:in `new'
/Users/ksmiley/.gem/gems/cocoapods-core-1.0.0.beta.1/lib/cocoapods-core/podfile.rb:287:in `from_ruby'
/Users/ksmiley/.gem/gems/cocoapods-core-1.0.0.beta.1/lib/cocoapods-core/podfile.rb:253:in `from_file'
/Users/ksmiley/.gem/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/config.rb:189:in `podfile'
/Users/ksmiley/.gem/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/command.rb:112:in `verify_podfile_exists!'
/Users/ksmiley/.gem/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/command/project.rb:96:in `run'
/Users/ksmiley/.gem/gems/claide-1.0.0.beta.1/lib/claide/command.rb:312:in `run'
/Users/ksmiley/.gem/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/command.rb:48:in `run'
/Users/ksmiley/.gem/gems/cocoapods-1.0.0.beta.1/bin/pod:44:in `<top (required)>'
/Users/ksmiley/.gem/bin/pod:23:in `load'
/Users/ksmiley/.gem/bin/pod:23:in `<main>'
```

**Comment by imton** [comment]
+1

**Comment by segiddins** [comment]
Could someone provide the output of `pod env`?

**Comment by keith** [comment]
```
