### ISSUE TITLE
CocoaPods 1.0 doesn't handle lockfiles that used to have :head declared

### ISSUE THREAD

**Issue by orta** [CocoaPods/CocoaPods#4710]
### Command

```
/Users/orta/Library/Developer/Xcode/DerivedData/CocoaPods-gllyogzvsbzexieoizliifwelpnw/Build/Products/Debug/CocoaPods.app/Contents/Resources/bundle/bin/pod install --ansi --verbose
```

### Report

* What did you do?

Migrated Eigen's Analytics / ISO8601 pod to use `:git` not `:head`. Here's the [before](https://github.com/artsy/eigen/blob/7386df79dfac4d5e72247afc017ad348c7910888/Podfile.lock#L32) Lockfile. Might have been overzealous in #4697

* What happened instead?

### Stack

```
   CocoaPods : 1.0.0.beta.1
        Ruby : ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]
    RubyGems : 2.5.0
        Host : Mac OS X 10.11.2 (15C50)
       Xcode : 7.2 (7C68)
         Git : git version 2.6.2
Ruby lib dir : /Users/orta/Library/Developer/Xcode/DerivedData/CocoaPods-gllyogzvsbzexieoizliifwelpnw/Build/Products/Debug/CocoaPods.app/Contents/Resources/bundle/lib
Repositories : artsy - https://github.com/artsy/Specs.git @ ef8ffbf6d794b7853a662bdc067036382380d45b
               master - https://github.com/CocoaPods/Specs.git @ d5be2236b231cc0d8813e9a909e331a3c8bd3a05
```

### Plugins

```
cocoapods-deintegrate     : 1.0.0.beta.1
cocoapods-keys            : 1.6.0
cocoapods-plugins         : 1.0.0.beta.1
cocoapods-plugins-install : 0.0.1
cocoapods-search          : 1.0.0.beta.1
cocoapods-stats           : 1.0.0.beta.1
cocoapods-trunk           : 1.0.0.beta.1
cocoapods-try             : 1.0.0.beta.1
```

### Podfile

```ruby
source 'https://github.com/artsy/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!

install! 'cocoapods', :deterministic_uuids => false

# Yep.
inhibit_all_warnings!

# Allows per-dev overrides
local_podfile = "Podfile.local"
eval(File.read(local_podfile)) if File.exist? local_podfile

plugin 'cocoapods-keys', {
    :project => "Artsy",
    :target => "Artsy",
    :keys => [
        "ArtsyAPIClientSecret",
        "ArtsyAPIClientKey",
        "ArtsyFacebookAppID",
        "ArtsyTwitterKey",
        "ArtsyTwitterSecret",
        "ArtsyTwitterStagingKey",
        "ArtsyTwitterStagingSecret",
        "SegmentProductionWriteKey",
        "SegmentDevWriteKey",
        "AdjustProductionAppToken"
    ]
}

target 'Artsy' do

  # Networking
  pod 'AFNetworking', "~> 2.5"
  pod 'AFOAuth1Client', :git => "https://github.com/lxcid/AFOAuth1Client.git", :tag => "0.4.0"
  pod 'AFNetworkActivityLogger'
  pod 'SDWebImage', '>= 3.7.2' # 3.7.2 contains a fix that allows you to not force decoding each image, which uses lots of memory

  # Core
  pod 'ALPValidator'
  pod 'ARGenericTableViewController', :git => 'https://github.com/orta/ARGenericTableViewController.git'
  pod 'CocoaLumberjack', :git => 'https://github.com/CocoaLumberjack/CocoaLumberjack.git' # Unreleased > 2.0.1 version has a CP modulemap fix
  pod 'FLKAutoLayout', :git => 'https://github.com/alloy/FLKAutoLayout.git', :branch => 'add-support-for-layout-guides-take-2'
  pod 'FXBlurView'
  pod 'iRate'
  pod 'ISO8601DateFormatter', :git => "https://github.com/orta/iso-8601-date-formatter"
  pod 'JLRoutes', :git => 'https://github.com/orta/JLRoutes.git'
  pod 'JSBadgeView'
  pod 'JSDecoupledAppDelegate', :git => 'https://github.com/orta/JSDecoupledAppDelegate.git', :branch => 'patch-1'
  pod 'Mantle', '~> 1.5.6'
  pod 'MMMarkdown'
  pod 'NPKeyboardLayoutGuide'
  pod 'ReactiveCocoa'
  pod 'UICKeyChainStore'

  # Core owned by Artsy
  pod 'ARTiledImageView', :git => 'https://github.com/dblock/ARTiledImageView'
  pod 'ARCollectionViewMasonryLayout'
  pod 'ORStackView', :git => 'https://github.com/1aurabrown/ORStackView.git'
  pod 'UIView+BooleanAnimations'
  pod 'NAMapKit', :git => 'https://github.com/neilang/NAMapKit'

  # Deprecated:
  # UIAlertView is deprecated for iOS8 APIs
  pod 'UIAlertView+Blocks'

  # Language Enhancments
  pod 'KSDeferred'
  pod 'MultiDelegate'
  pod 'ObjectiveSugar'

  # X-Callback-Url support
  pod 'InterAppCommunication'

  # Artsy Spec repo stuff
  pod 'Artsy-UIButtons'
  pod 'Artsy+UIColors'
  pod 'Artsy+UILabels', '>= 1.3.2'

  if ENV['ARTSY_STAFF_MEMBER'] != nil || ENV['CI'] != nil
    pod 'Artsy+UIFonts', :git => "https://github.com/artsy/Artsy-UIFonts.git", :branch => "old_fonts_new_lib"
  else
    pod 'Artsy+OSSUIFonts'
  end

  # Facebook
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'

  # Analytics
  pod 'Analytics', :git => "https://github.com/segmentio/analytics-ios.git"
  pod 'ARAnalytics', :git => 'https://github.com/orta/ARAnalytics.git', :subspecs => ["Segmentio", "HockeyApp", "Adjust", "DSL"]

  # Developer Pods
  pod 'DHCShakeNotifier'
  pod 'ORKeyboardReactingApplication'
  pod 'VCRURLConnection'

  # Easter Eggs
  pod 'ARASCIISwizzle'
  pod 'DRKonamiCode'

  target 'Artsy Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
    pod 'OHHTTPStubs'
    pod 'XCTest+OHHTTPStubSuiteCleanUp'
    pod 'Specta'
    pod 'Expecta'
    pod 'OCMock'
  end
end

post_install do |installer|
  # Disable bitcode for now. Specifically needed for HockeySDK and ARAnalytics.
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end

  app_plist = "Artsy/App_Resources/Artsy-Info.plist"
  plist_buddy = "/usr/libexec/PlistBuddy"
  version = `#{plist_buddy} -c "Print CFBundleShortVersionString" #{app_plist}`.strip
  puts "Updating CocoaPods' version numbers to #{version}"

  installer.pods_project.targets.each do |target|
    `#{plist_buddy} -c "Set CFBundleShortVersionString #{version}" "Pods/Target Support Files/#{target}/Info.plist"`
  end
end
```

### Error

```
ArgumentError - Illformed requirement `" HEAD"`
/Users/orta/Library/Developer/Xcode/DerivedData/CocoaPods-gllyogzvsbzexieoizliifwelpnw/Build/Products/Debug/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-core-1.0.0.beta.1/lib/cocoapods-core/requirement.rb:63:in `parse'
/Users/orta/Library/Developer/Xcode/DerivedData/CocoaPods-gllyogzvsbzexieoizliifwelpnw/Build/Products/Debug/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-core-1.0.0.beta.1/lib/cocoapods-core/requirement.rb:88:in `block in initialize'
/Users/orta/Library/Developer/Xcode/DerivedData/CocoaPods-gllyogzvsbzexieoizliifwelpnw/Build/Products/Debug/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-core-1.0.0.beta.1/lib/cocoapods-core/requirement.rb:88:in `map!'
/Users/orta/Library/Developer/Xcode/DerivedData/CocoaPods-gllyogzvsbzexieoizliifwelpnw/Build/Products/Debug/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-core-1.0.0.beta.1/lib/cocoapods-core/requirement.rb:88:in `initialize'
/Users/orta/Library/Developer/Xcode/DerivedData/CocoaPods-gllyogzvsbzexieoizliifwelpnw/Build/Products/Debug/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-core-1.0.0.beta.1/lib/cocoapods-core/requirement.rb:34:in `new'
/Users/orta/Library/Developer/Xcode/DerivedData/CocoaPods-gllyogzvsbzexieoizliifwelpnw/Build/Products/Debug/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-core-1.0.0.beta.1/lib/cocoapods-core/requirement.rb:34:in `create'
/Users/orta/Library/Developer/Xcode/DerivedData/CocoaPods-gllyogzvsbzexieoizliifwelpnw/Build/Products/Debug/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-core-1.0.0.beta.1/lib/cocoapods-core/dependency.rb:116:in `initialize'
/Users/orta/Library/Developer/Xcode/DerivedData/CocoaPods-gllyogzvsbzexieoizliifwelpnw/Build/Products/Debug/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-core-1.0.0.beta.1/lib/cocoapods-core/dependency.rb:355:in `new'
/Users/orta/Library/Developer/Xcode/DerivedData/CocoaPods-gllyogzvsbzexieoizliifwelpnw/Build/Products/Debug/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-core-1.0.0.beta.1/lib/cocoapods-core/dependency.rb:355:in `from_string'
/Users/orta/Library/Developer/Xcode/DerivedData/CocoaPods-gllyogzvsbzexieoizliifwelpnw/Build/Products/Debug/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-core-1.0.0.beta.1/lib/cocoapods-core/lockfile.rb:116:in `block in dependencies'
/Users/orta/Library/Developer/Xcode/DerivedData/CocoaPods-gllyogzvsbzexieoizliifwelpnw/Build/Products/Debug/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-core-1.0.0.beta.1/lib/cocoapods-core/lockfile.rb:115:in `map'
/Users/orta/Library/Developer/Xcode/DerivedData/CocoaPods-gllyogzvsbzexieoizliifwelpnw/Build/Products/Debug/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-core-1.0.0.beta.1/lib/cocoapods-core/lockfile.rb:115:in `dependencies'
/Users/orta/Library/Developer/Xcode/DerivedData/CocoaPods-gllyogzvsbzexieoizliifwelpnw/Build/Products/Debug/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-core-1.0.0.beta.1/lib/cocoapods-core/lockfile.rb:259:in `detect_changes_with_podfile'
/Users/orta/Library/Developer/Xcode/DerivedData/CocoaPods-gllyogzvsbzexieoizliifwelpnw/Build/Products/Debug/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/installer/analyzer.rb:198:in `block in generate_podfile_state'
/Users/orta/Library/Developer/Xcode/DerivedData/CocoaPods-gllyogzvsbzexieoizliifwelpnw/Build/Products/Debug/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/user_interface.rb:63:in `section'
/Users/orta/Library/Developer/Xcode/DerivedData/CocoaPods-gllyogzvsbzexieoizliifwelpnw/Build/Products/Debug/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/installer/analyzer.rb:197:in `generate_podfile_state'
/Users/orta/Library/Developer/Xcode/DerivedData/CocoaPods-gllyogzvsbzexieoizliifwelpnw/Build/Products/Debug/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/installer/analyzer.rb:68:in `analyze'
/Users/orta/Library/Developer/Xcode/DerivedData/CocoaPods-gllyogzvsbzexieoizliifwelpnw/Build/Products/Debug/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/installer.rb:223:in `analyze'
/Users/orta/Library/Developer/Xcode/DerivedData/CocoaPods-gllyogzvsbzexieoizliifwelpnw/Build/Products/Debug/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/installer.rb:147:in `block in resolve_dependencies'
/Users/orta/Library/Developer/Xcode/DerivedData/CocoaPods-gllyogzvsbzexieoizliifwelpnw/Build/Products/Debug/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/user_interface.rb:63:in `section'
/Users/orta/Library/Developer/Xcode/DerivedData/CocoaPods-gllyogzvsbzexieoizliifwelpnw/Build/Products/Debug/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/installer.rb:146:in `resolve_dependencies'
/Users/orta/Library/Developer/Xcode/DerivedData/CocoaPods-gllyogzvsbzexieoizliifwelpnw/Build/Products/Debug/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/installer.rb:109:in `install!'
/Users/orta/Library/Developer/Xcode/DerivedData/CocoaPods-gllyogzvsbzexieoizliifwelpnw/Build/Products/Debug/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-keys-1.6.0/lib/plugin.rb:99:in `install!'
/Users/orta/Library/Developer/Xcode/DerivedData/CocoaPods-gllyogzvsbzexieoizliifwelpnw/Build/Products/Debug/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/command/project.rb:67:in `run_install_with_update'
/Users/orta/Library/Developer/Xcode/DerivedData/CocoaPods-gllyogzvsbzexieoizliifwelpnw/Build/Products/Debug/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/command/project.rb:97:in `run'
/Users/orta/Library/Developer/Xcode/DerivedData/CocoaPods-gllyogzvsbzexieoizliifwelpnw/Build/Products/Debug/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/claide-1.0.0.beta.1/lib/claide/command.rb:312:in `run'
/Users/orta/Library/Developer/Xcode/DerivedData/CocoaPods-gllyogzvsbzexieoizliifwelpnw/Build/Products/Debug/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/command.rb:48:in `run'
/Users/orta/Library/Developer/Xcode/DerivedData/CocoaPods-gllyogzvsbzexieoizliifwelpnw/Build/Products/Debug/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.beta.1/bin/pod:44:in `<top (required)>'
/Users/orta/Library/Developer/Xcode/DerivedData/CocoaPods-gllyogzvsbzexieoizliifwelpnw/Build/Products/Debug/CocoaPods.app/Contents/Resources/bundle/bin/pod:23:in `load'
/Users/orta/Library/Developer/Xcode/DerivedData/CocoaPods-gllyogzvsbzexieoizliifwelpnw/Build/Products/Debug/CocoaPods.app/Contents/Resources/bundle/bin/pod:23:in `<main>'
```

**Comment by segiddins** [comment]
Ah ok. This should probably give an informative error.

**Comment by SirWellington** [comment]
I'm having this issue too. Is there a way to fix it?

**Comment by SirWellington** [comment]
Couldn't infer before, but I guess deleting the `Podfile.lock` file did the trick.

**Comment by orta** [comment]
I went and deleted the `:head` lines from the lockfile, I think future betas will make this not needed
