### ISSUE TITLE
Unable to find the specification for pod with custom :git =>

### ISSUE THREAD

**Issue by nabeelarif100** [CocoaPods/CocoaPods#4716]
### Command 🌈

```
/usr/local/bin/pod outdated
```

### Report

* What did you do?

I am trying to check which of my pods have updates available i.e are outdated. As you can see from the above command.

* What did you expect to happen?

I expect to see a list of outdated pods

* What happened instead?

Instead of displaying me the list of outdated pods, it should me error which is posted below. It was working before upgrading to latest version of cocoapods i.e 1.0.0.beta.1.
### Stack

```
   CocoaPods : 1.0.0.beta.1
        Ruby : ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]
    RubyGems : 2.0.14
        Host : Mac OS X 10.11.2 (15C50)
       Xcode : 7.2 (7C68)
         Git : git version 2.5.4 (Apple Git-61)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ f43f0e26ff791a3c036c83d24fcd50a1f2f4a788
```

### Plugins

```
cocoapods-deintegrate : 1.0.0.beta.1
cocoapods-plugins     : 1.0.0.beta.1
cocoapods-search      : 1.0.0.beta.1
cocoapods-stats       : 1.0.0.beta.1
cocoapods-trunk       : 1.0.0.beta.1
cocoapods-try         : 1.0.0.beta.1
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

def available_pods
pod 'AFNetworking', '2.6.3'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'PDKeychainBindingsController', '~> 0.0.1'
pod 'FMDB/SQLCipher'
pod 'ZXingObjC', '~> 3.1.0'
pod 'SDWebImage', '~>3.7.2'
pod 'SignalR-ObjC','~>2.0.0.beta3'
pod 'CJPAdController', :git => 'https://github.com/nabeelarif100/CJPAdController.git'
pod 'ECSlidingViewController', '~> 2.0.3'
pod 'VGParallaxHeader'
pod 'EMString'
pod 'Google/SignIn'
pod 'VIPhotoView', '~> 0.1'
pod 'EncryptedCoreData', :git => 'https://github.com/project-imas/encrypted-core-data.git'
end

target 'MyApp' do
available_pods
end

target 'MyApp PreProd' do
available_pods
end

target 'MyApp Test' do
available_pods
end

target 'MyApp Dev' do
available_pods
end

target 'MyApp Local' do
available_pods
end
```

### Error

```
Pod::StandardError - [Bug] Unable to find the specification for `CJPAdController (from `https://github.com/nabeelarif100/CJPAdController.git`)`.
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/resolver.rb:296:in `find_cached_set'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/resolver.rb:108:in `search_for'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/resolver.rb:211:in `block in sort_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/resolver.rb:205:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/resolver.rb:205:in `sort_by'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/resolver.rb:205:in `sort_dependencies'
/Library/Ruby/Gems/2.0.0/gems/molinillo-0.4.1/lib/molinillo/resolution.rb:130:in `block (2 levels) in <class:Resolution>'
/Library/Ruby/Gems/2.0.0/gems/molinillo-0.4.1/lib/molinillo/resolution.rb:173:in `initial_state'
/Library/Ruby/Gems/2.0.0/gems/molinillo-0.4.1/lib/molinillo/resolution.rb:99:in `start_resolution'
/Library/Ruby/Gems/2.0.0/gems/molinillo-0.4.1/lib/molinillo/resolution.rb:62:in `resolve'
/Library/Ruby/Gems/2.0.0/gems/molinillo-0.4.1/lib/molinillo/resolver.rb:41:in `resolve'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/resolver.rb:62:in `resolve'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/installer/analyzer.rb:551:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/user_interface.rb:63:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/installer/analyzer.rb:549:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/installer/analyzer.rb:73:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/command/outdated.rb:75:in `block in unlocked_pods'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/user_interface.rb:84:in `titled_section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/command/outdated.rb:73:in `unlocked_pods'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/command/outdated.rb:61:in `block in updates'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/command/outdated.rb:55:in `map'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/command/outdated.rb:55:in `updates'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/command/outdated.rb:19:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0.beta.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.1/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by neonichu** [comment]
This might be related to #4717

**Comment by segiddins** [comment]
Try running `pod install` before `pod outdated`
