### ISSUE TITLE
Install fails on 1.0 when using custom Podspec

### ISSUE THREAD

**Issue by orta** [CocoaPods/CocoaPods#4717]
This looks to me like we're ignoring the local Podspec declaration after the migration.

With this Podfile:

``` ruby
# coding: utf-8
platform :osx, '10.10'

use_frameworks!

inhibit_all_warnings!

target "CocoaPods" do


  # This one
  pod 'Fragaria', :podspec => 'Fragaria.podspec.json'


  pod 'ANSIEscapeHelper', :podspec => 'ANSIEscapeHelper.podspec'
  pod 'Sparkle'
  pod 'JustPromises'
  
  target "CocoaPodsTests" do
  	inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end

post_install do |installer|
  ...
end

```

``` sh
  Preparing

Fully deintegrating due to major version update

Deintegrating `CocoaPods.xcodeproj`
Deintegrating target `CocoaPods`
Deintegrating target `pod`
Deintegrating target `CocoaPodsTests`
Deintegrating target `ReflectionService`
Removing `Pods` directory.

Project has been deintegrated. No traces of CocoaPods left in project.
Note: The workspace referencing the Pods project still remains.

Updating local specs repositories

Updating spec repo `master`
  $ /Users/orta/Library/Developer/Xcode/DerivedData/CocoaPods-gllyogzvsbzexieoizliifwelpnw/Build/Products/Debug/CocoaPods.app/Contents/Resources/bundle/bin/git pull --ff-only
  Already up-to-date.

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-CocoaPods`: (``)
  Using `ARCHS` setting to build architectures of target `Pods-CocoaPodsTests`: (``)

Finding Podfile changes
  A JustPromises
  - ANSIEscapeHelper
  - Fragaria
  - Nimble
  - Quick
  - Sparkle

Fetching external sources
-> Fetching podspec for `ANSIEscapeHelper` from `ANSIEscapeHelper.podspec`
-> Pre-downloading: `Fragaria` from `https://github.com/bitstadium/Fragaria.git`, commit `11ea9399cd01d061218a99a67b4e01a65eb07696`
 > Git download
 > Git download
     $ /Users/orta/Library/Developer/Xcode/DerivedData/CocoaPods-gllyogzvsbzexieoizliifwelpnw/Build/Products/Debug/CocoaPods.app/Contents/Resources/bundle/bin/git clone https://github.com/bitstadium/Fragaria.git /var/folders/mk/gxhr550d5mbcv5s9_f61x84h0000gn/T/d20160103-44865-1smz397
     Cloning into '/var/folders/mk/gxhr550d5mbcv5s9_f61x84h0000gn/T/d20160103-44865-1smz397'...
   $ /Users/orta/Library/Developer/Xcode/DerivedData/CocoaPods-gllyogzvsbzexieoizliifwelpnw/Build/Products/Debug/CocoaPods.app/Contents/Resources/bundle/bin/git checkout --quiet 11ea9399cd01d061218a99a67b4e01a65eb07696
[!] Unable to find a specification for 'Fragaria'.

/Users/orta/Library/Developer/Xcode/DerivedData/CocoaPods-gllyogzvsbzexieoizliifwelpnw/Build/Products/Debug/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/external_sources/abstract_external_source.rb:117:in `block in pre_download'
/Users/orta/Library/Developer/Xcode/DerivedData/CocoaPods-gllyogzvsbzexieoizliifwelpnw/Build/Products/Debug/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/user_interface.rb:84:in `titled_section'
/Users/orta/Library/Developer/Xcode/DerivedData/CocoaPods-gllyogzvsbzexieoizliifwelpnw/Build/Products/Debug/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/external_sources/abstract_external_source.rb:112:in `pre_download'
/Users/orta/Library/Developer/Xcode/DerivedData/CocoaPods-gllyogzvsbzexieoizliifwelpnw/Build/Products/Debug/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/external_sources/downloader_source.rb:13:in `fetch'
/Users/orta/Library/Developer/Xcode/DerivedData/CocoaPods-gllyogzvsbzexieoizliifwelpnw/Build/Products/Debug/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/installer/analyzer.rb:470:in `fetch_external_source'
/Users/orta/Library/Developer/Xcode/DerivedData/CocoaPods-gllyogzvsbzexieoizliifwelpnw/Build/Products/Debug/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/installer/analyzer.rb:446:in `block (2 levels) in fetch_external_sources'
/Users/orta/Library/Developer/Xcode/DerivedData/CocoaPods-gllyogzvsbzexieoizliifwelpnw/Build/Products/Debug/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/installer/analyzer.rb:445:in `each'
/Users/orta/Library/Developer/Xcode/DerivedData/CocoaPods-gllyogzvsbzexieoizliifwelpnw/Build/Products/Debug/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/installer/analyzer.rb:445:in `block in fetch_external_sources'
/Users/orta/Library/Developer/Xcode/DerivedData/CocoaPods-gllyogzvsbzexieoizliifwelpnw/Build/Products/Debug/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/user_interface.rb:63:in `section'
/Users/orta/Library/Developer/Xcode/DerivedData/CocoaPods-gllyogzvsbzexieoizliifwelpnw/Build/Products/Debug/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/installer/analyzer.rb:444:in `fetch_external_sources'
/Users/orta/Library/Developer/Xcode/DerivedData/CocoaPods-gllyogzvsbzexieoizliifwelpnw/Build/Products/Debug/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/installer/analyzer.rb:72:in `analyze'
/Users/orta/Library/Developer/Xcode/DerivedData/CocoaPods-gllyogzvsbzexieoizliifwelpnw/Build/Products/Debug/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/installer.rb:223:in `analyze'
/Users/orta/Library/Developer/Xcode/DerivedData/CocoaPods-gllyogzvsbzexieoizliifwelpnw/Build/Products/Debug/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/installer.rb:147:in `block in resolve_dependencies'
/Users/orta/Library/Developer/Xcode/DerivedData/CocoaPods-gllyogzvsbzexieoizliifwelpnw/Build/Products/Debug/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/user_interface.rb:63:in `section'
/Users/orta/Library/Developer/Xcode/DerivedData/CocoaPods-gllyogzvsbzexieoizliifwelpnw/Build/Products/Debug/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/installer.rb:146:in `resolve_dependencies'
/Users/orta/Library/Developer/Xcode/DerivedData/CocoaPods-gllyogzvsbzexieoizliifwelpnw/Build/Products/Debug/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/installer.rb:109:in `install!'
/Users/orta/Library/Developer/Xcode/DerivedData/CocoaPods-gllyogzvsbzexieoizliifwelpnw/Build/Products/Debug/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/command/project.rb:67:in `run_install_with_update'
/Users/orta/Library/Developer/Xcode/DerivedData/CocoaPods-gllyogzvsbzexieoizliifwelpnw/Build/Products/Debug/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/command/project.rb:97:in `run'
/Users/orta/Library/Developer/Xcode/DerivedData/CocoaPods-gllyogzvsbzexieoizliifwelpnw/Build/Products/Debug/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/claide-1.0.0.beta.1/lib/claide/command.rb:312:in `run'
/Users/orta/Library/Developer/Xcode/DerivedData/CocoaPods-gllyogzvsbzexieoizliifwelpnw/Build/Products/Debug/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/command.rb:48:in `run'
/Users/orta/Library/Developer/Xcode/DerivedData/CocoaPods-gllyogzvsbzexieoizliifwelpnw/Build/Products/Debug/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.beta.1/bin/pod:44:in `<top (required)>'
/Users/orta/Library/Developer/Xcode/DerivedData/CocoaPods-gllyogzvsbzexieoizliifwelpnw/Build/Products/Debug/CocoaPods.app/Contents/Resources/bundle/bin/pod:23:in `load'
/Users/orta/Library/Developer/Xcode/DerivedData/CocoaPods-gllyogzvsbzexieoizliifwelpnw/Build/Products/Debug/CocoaPods.app/Contents/Resources/bundle/bin/pod:23:in `<main>'
```

**Comment by orta** [comment]
Tested on 0.39, and I got the same problem:

```
~/d/m/a/C/app (promise) ⏛  pod install
[!] Unable to load a specification for the plugin `/Users/orta/.rvm/gems/ruby-2.1.3/gems/cocoapods-deintegrate-1.0.0.beta.1`
Updating local specs repositories

CocoaPods 1.0.0.beta.1 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
Fetching podspec for `ANSIEscapeHelper` from `ANSIEscapeHelper.podspec`
Pre-downloading: `Fragaria` from `https://github.com/bitstadium/Fragaria.git`, commit `11ea9399cd01d061218a99a67b4e01a65eb07696`
[!] Unable to find a specification for 'Fragaria'.

[!] CocoaPods was not able to update the `master` repo. If this is an unexpected issue and persists you can inspect it running `pod repo update --verbose

```

**Comment by segiddins** [comment]
Pretty sure this is due to the cache searching for a podspec when we already have one.
