### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by slizeray** [CocoaPods/CocoaPods#4747]
Hello,

I thin I messed up my cocoa pods environment. I install the beta and since then I can't run pod install on any projects.

I get the following errors

### Error

```
NoMethodError - undefined method `user_targets' for #<Pod::Installer::PostInstallHooksContext::UmbrellaTargetDescription:0x007fcdba917af0>
/Users/slizeray/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-stats-1.0.0.beta.2/lib/cocoapods_stats/target_mapper.rb:20:in `block in pods_from_project'
/Users/slizeray/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-stats-1.0.0.beta.2/lib/cocoapods_stats/target_mapper.rb:9:in `each'
/Users/slizeray/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-stats-1.0.0.beta.2/lib/cocoapods_stats/target_mapper.rb:9:in `flat_map'
/Users/slizeray/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-stats-1.0.0.beta.2/lib/cocoapods_stats/target_mapper.rb:9:in `pods_from_project'
/Users/slizeray/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-stats-0.6.2/lib/cocoapods_plugin.rb:31:in `block (2 levels) in <module:CocoaPodsStats>'
/Users/slizeray/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:80:in `titled_section'
/Users/slizeray/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-stats-0.6.2/lib/cocoapods_plugin.rb:27:in `block in <module:CocoaPodsStats>'
/Users/slizeray/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:117:in `call'
/Users/slizeray/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:117:in `block (3 levels) in run'
/Users/slizeray/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:140:in `message'
/Users/slizeray/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:111:in `block (2 levels) in run'
/Users/slizeray/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:109:in `each'
/Users/slizeray/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:109:in `block in run'
/Users/slizeray/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:140:in `message'
/Users/slizeray/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:108:in `run'
/Users/slizeray/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:481:in `run_plugins_post_install_hooks'
/Users/slizeray/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:462:in `perform_post_install_actions'
/Users/slizeray/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:113:in `install!'
/Users/slizeray/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/slizeray/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:101:in `run'
/Users/slizeray/.rvm/gems/ruby-2.2.1@global/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Users/slizeray/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Users/slizeray/.rvm/gems/ruby-2.2.1/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/Users/slizeray/.rvm/gems/ruby-2.2.1/bin/pod:23:in `load'
/Users/slizeray/.rvm/gems/ruby-2.2.1/bin/pod:23:in `<main>'
/Users/slizeray/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
/Users/slizeray/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

Thanks aheads,

Stéphane

**Comment by segiddins** [comment]
Closing as a duplicate.
