### ISSUE TITLE
Just trying to pod install

### ISSUE THREAD

**Issue by Chris-Sipe** [CocoaPods/CocoaPods#4750]
## Command 🌈

```
/Users/user/.gem/bin/pod install
```

### Report

* What did you do?
type 'pod install' in my project folder
* What did you expect to happen?
set up cocoapods for my project
* What happened instead?
I got hit with one of these: 
```
[!] Unable to load a specification for the plugin `/Library/Ruby/Gems/2.0.0/gems/cocoapods-deintegrate-1.0.0.beta.1`
Updating local specs repositories

CocoaPods 1.0.0.beta.2 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
Downloading dependencies
Using SwiftyJSON (2.3.2)
Generating Pods project
Integrating client project
Sending stats
[!] Unable to load a specification for the plugin `/Library/Ruby/Gems/2.0.0/gems/cocoapods-deintegrate-1.0.0.beta.1`
```

 followed by the rest of the stack messages

### Stack

```
   CocoaPods : 0.39.0
        Ruby : ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]
    RubyGems : 2.4.8
        Host : Mac OS X 10.11.2 (15C50)
       Xcode : 7.2 (7C68)
         Git : git version 2.5.4 (Apple Git-61)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 3c1f8aca37a71d59bd4f2a81e91ac84a13220df0
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-search  : 0.1.0
cocoapods-stats   : 0.6.2
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.5.1
```

### Podfile

```ruby
platform :ios, '8.0'
use_frameworks!

target 'myApp' do
  pod 'SwiftyJSON', '~> 2.3'
end
```

### Error

```
NoMethodError - undefined method `user_targets' for #<Pod::Installer::PostInstallHooksContext::UmbrellaTargetDescription:0x007fd5b4424f00>
/Library/Ruby/Gems/2.0.0/gems/cocoapods-stats-1.0.0.beta.2/lib/cocoapods_stats/target_mapper.rb:20:in `block in pods_from_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-stats-1.0.0.beta.2/lib/cocoapods_stats/target_mapper.rb:9:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-stats-1.0.0.beta.2/lib/cocoapods_stats/target_mapper.rb:9:in `flat_map'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-stats-1.0.0.beta.2/lib/cocoapods_stats/target_mapper.rb:9:in `pods_from_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-stats-0.6.2/lib/cocoapods_plugin.rb:31:in `block (2 levels) in <module:CocoaPodsStats>'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:80:in `titled_section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-stats-0.6.2/lib/cocoapods_plugin.rb:27:in `block in <module:CocoaPodsStats>'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:117:in `call'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:117:in `block (3 levels) in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:140:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:111:in `block (2 levels) in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:109:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:109:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:140:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:108:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:481:in `run_plugins_post_install_hooks'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:462:in `perform_post_install_actions'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:113:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/Users/user/.gem/bin/pod:23:in `load'
/Users/user/.gem/bin/pod:23:in `<main>'
```

**Comment by segiddins** [comment]
This issue is a duplicate.
