### ISSUE TITLE
We couldn’t find any issues matching 'undefined method `user_targets' for #<Pod::Installer::PostInstallHooksContext::UmbrellaTargetDescription:0x007f848f1a1f88>'

### ISSUE THREAD

**Issue by itree** [CocoaPods/CocoaPods#4757]
### Command

```
/usr/bin/pod install --verbose
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 0.39.0
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.4.8
        Host : Mac OS X 10.10.5 (14F1509)
       Xcode : 7.2 (7C68)
         Git : git version 2.5.4 (Apple Git-61)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 0c3a0e8a9fc600464765efe945ce354a7c2bf581
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-search  : 0.1.0
cocoapods-stats   : 0.6.2
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.5.1
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'

# ignore all warnings from all pods
inhibit_all_warnings!

pod 'BlocksKit', '~> 2.2.5'
pod 'CocoaLumberjack', '~> 1.9.2'
pod 'JSQMessagesViewController', '~> 7.1.0'
pod 'Masonry', '~> 0.6.1'
pod 'objcTox', '0.4.0'
pod 'UITextView+Placeholder', '~> 1.0.9'
pod 'SDCAlertView', '~> 2.5.2'
```

### Error

```
NoMethodError - undefined method `user_targets' for #<Pod::Installer::PostInstallHooksContext::UmbrellaTargetDescription:0x007f848f1a1f88>
/Library/Ruby/Gems/2.0.0/gems/cocoapods-stats-1.0.0.beta.2/lib/cocoapods_stats/target_mapper.rb:20:in `block in pods_from_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-stats-1.0.0.beta.2/lib/cocoapods_stats/target_mapper.rb:9:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-stats-1.0.0.beta.2/lib/cocoapods_stats/target_mapper.rb:9:in `flat_map'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-stats-1.0.0.beta.2/lib/cocoapods_stats/target_mapper.rb:9:in `pods_from_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-stats-0.6.2/lib/cocoapods_plugin.rb:31:in `block (2 levels) in <module:CocoaPodsStats>'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:80:in `titled_section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-stats-0.6.2/lib/cocoapods_plugin.rb:27:in `block in <module:CocoaPodsStats>'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:117:in `call'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:117:in `block (3 levels) in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:140:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:111:in `block (2 levels) in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:109:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:109:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:140:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:108:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:481:in `run_plugins_post_install_hooks'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:462:in `perform_post_install_actions'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:113:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'

**Comment by segiddins** [comment]
This issue is a duplicate.

**Comment by itree** [comment]
cool thanks. Can you point to the duplicate issue?

**Comment by orta** [comment]
It's only 6 down from the top of the issues page @itree - https://github.com/CocoaPods/CocoaPods/issues/4741 - please respect our time, it takes time away from being able to fix the actual problems.

**Comment by itree** [comment]
Ok thanks.  What I'm copy and pasting is from the command  line and recommend by command line prompt.  Maybe that is why you are getting some many of this request.  Thanks.
