### ISSUE TITLE
AMap3DMap install failed

### ISSUE THREAD

**Issue by Transparentmask** [CocoaPods/CocoaPods#4767]
In my previous project, I can correctly using AMap3DMap(3.2.1).
But when I clone a new copy of same project, pod install give me an error. The version of AMap3DMap pod is not changed. so how can I fix it?

The content of Podfile.lock in my previous project folder.
```
transparentmask$ cat Podfile.lock 
PODS:
  - Alamofire (2.0.2)
  - AMap3DMap (3.2.1)
  - AMapSearch (3.1.0)
  - RMUniversalAlert (0.7):
    - RMUniversalAlert/Core (= 0.7)
  - RMUniversalAlert/Core (0.7):
    - UIActionSheet+Blocks (>= 0.9)
    - UIAlertController+Blocks (>= 0.9)
    - UIAlertView+Blocks (>= 0.9)
  - SwiftyJSON (2.3.1)
  - UIActionSheet+Blocks (0.9)
  - UIAlertController+Blocks (0.9)
  - UIAlertView+Blocks (0.9)

DEPENDENCIES:
  - Alamofire (~> 2.0)
  - AMap3DMap
  - AMapSearch
  - RMUniversalAlert
  - SwiftyJSON

SPEC CHECKSUMS:
  Alamofire: 8edbab00802a752bb5240cc2abe70e7e881488ad
  AMap3DMap: 1f179c4fc41a60e42243466eb188e3be946aa163
  AMapSearch: aa7621ae8aec9cb8df116710b26e3fe3d09dc0ff
  RMUniversalAlert: bce2ca406c24065b76665725c83e48006e8f65f8
  SwiftyJSON: 592b53bee5ef3dd9b3bebc6b9cb7ee35426ae8c3
  UIActionSheet+Blocks: e180b7dad0a721ab7f212ac9742af799008bb358
  UIAlertController+Blocks: b48c673ff60726da468b32ab21bbc7683512d45b
  UIAlertView+Blocks: a46c99c5144f6c5dbc7d62fd2a0678daceec89a3

COCOAPODS: 0.39.0
```

### Command

```
/usr/local/bin/pod install --verbose --no-repo-update
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 0.39.0
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.2 (15C50)
       Xcode : 7.2 (7C68)
         Git : git version 2.7.0
Ruby lib dir : /usr/local/Cellar/ruby/2.3.0/lib
Repositories : LTPrivateSpecs - https://github.com/Transparentmask/PrivateSpecs.git @ 0956a00996b29177a4da22df66650b10089d52ae
               master - https://github.com/CocoaPods/Specs.git @ fe05be0802298ea8d88bd63b287c5f11e8c7d4c9
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-search  : 0.1.0
cocoapods-stats   : 0.6.2
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.5.1
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'GasChat' do
	pod 'Alamofire', '~> 2.0'
#	pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
	pod 'SwiftyJSON'

	pod 'AMap3DMap', '~> 3.2.1'
	pod 'AMapSearch'

	pod 'RBStoryboardLink'

	pod 'RMUniversalAlert'
end

target 'GasChat_AppStore' do
    pod 'Alamofire', '~> 2.0'
#    pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
	pod 'SwiftyJSON'
    
    pod 'AMap3DMap', '~> 3.2.1'
    pod 'AMapSearch'
    
    pod 'RBStoryboardLink'

    pod 'RMUniversalAlert'
end
```

### Error

```
NoMethodError - undefined method `to_ary' for #<Pod::Specification name="AMap3DMap">
Did you mean?  to_query
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver/lazy_specification.rb:14:in `method_missing'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:64:in `flatten'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:64:in `block in resolve'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:63:in `tap'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:63:in `resolve'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:539:in `block in resolve_dependencies'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:537:in `resolve_dependencies'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:70:in `analyze'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:213:in `analyze'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:136:in `block in resolve_dependencies'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:135:in `resolve_dependencies'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:105:in `install!'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:101:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by Transparentmask** [comment]
I found some dup issues. Close this one. Sorry.
