### ISSUE TITLE
Error install crashlytics

### ISSUE THREAD

**Issue by rmuhamedgaliev** [CocoaPods/CocoaPods#4779]
――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/opt/rbenv/versions/2.2.4/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 0.39.0
        Ruby : ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin15]
    RubyGems : 2.4.5.1
        Host : Mac OS X 10.11.2 (15C50)
       Xcode : 7.2 (7C68)
         Git : git version 2.7.0
Ruby lib dir : /usr/local/opt/rbenv/versions/2.2.4/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ cf11183b4daa101c854815c335e9c84c3b5edb5e
```

### Plugins

```

```

### Error

```
NameError - uninitialized constant Pod::Downloader::Http::URI
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/cocoapods-downloader-0.9.3/lib/cocoapods-downloader/http.rb:54:in `type_with_url'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/cocoapods-downloader-0.9.3/lib/cocoapods-downloader/http.rb:32:in `type'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/cocoapods-downloader-0.9.3/lib/cocoapods-downloader/http.rb:21:in `download!'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/cocoapods-downloader-0.9.3/lib/cocoapods-downloader/base.rb:80:in `block in download'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/downloader.rb:145:in `block in ui_action'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/downloader.rb:144:in `ui_action'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/cocoapods-downloader-0.9.3/lib/cocoapods-downloader/base.rb:78:in `download'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/downloader.rb:110:in `download_source'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/downloader.rb:65:in `download_request'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/downloader/cache.rb:170:in `download'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/downloader/cache.rb:153:in `block in uncached_pod'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/downloader/cache.rb:180:in `call'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/downloader/cache.rb:180:in `in_tmpdir'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/downloader/cache.rb:152:in `uncached_pod'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/downloader/cache.rb:33:in `download_pod'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/downloader.rb:34:in `download'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/pod_source_installer.rb:113:in `download_source'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/pod_source_installer.rb:53:in `install!'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:339:in `install_source_of_pod'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:306:in `block (2 levels) in install_pod_sources'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:80:in `titled_section'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:305:in `block in install_pod_sources'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:297:in `each'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:297:in `install_pod_sources'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:146:in `block in download_dependencies'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:144:in `download_dependencies'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:106:in `install!'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:101:in `run'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/usr/local/opt/rbenv/versions/2.2.4/bin/pod:23:in `load'
/usr/local/opt/rbenv/versions/2.2.4/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=uninitialized+constant+Pod%3A%3ADownloader%3A%3AHttp%3A%3AURI&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

**Comment by segiddins** [comment]
We should probably throw a `require 'uri'` at the top of https://github.com/CocoaPods/cocoapods-downloader/blob/master/lib/cocoapods-downloader/http.rb, if you want to make a PR!

**Comment by dnkoutso** [comment]
This works just fine for me.

```ruby
source 'https://stash.corp.squareup.com/scm/ios/squarepods.git'
source 'https://github.com/CocoaPods/Specs'

platform :ios, '7.0'

target 'SampleApp' do
    pod 'Crashlytics', '~> 3.6'
end
```
Tried ruby 2.0.0 and 2.2.1.

**Comment by segiddins** [comment]
Even so, that file should require URI
