### ISSUE TITLE
Error on pod install - follow on to previous ticket #4785

### ISSUE THREAD

**Issue by DaveKerr** [CocoaPods/CocoaPods#4790]
I created ticket 4785 which a recommendation was given and closed.  I upgraded to 0.39.0 and I get the following error template which is the same error.  I also tried to install a version of Facebook SDK that I had successfully installed with cocoapods in the past.  Still get the error.

### Command

```
/usr/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 0.39.0
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.0.14
        Host : Mac OS X 10.10.4 (14E46)
       Xcode : 7.0.1 (7A1001)
         Git : git version 2.3.8 (Apple Git-58)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ f631a942ec2ed30b66893411b3f48ab125a89851
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-search  : 0.1.0
cocoapods-stats   : 0.6.2
cocoapods-trunk   : 0.3.1
cocoapods-try     : 0.5.1
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
pod 'FacebookSDK', '~> 3.21.1'
```

### Error

```
Pod::Podfile::StandardError - Unsupported platform ``. Platform must be `:ios`, `:osx`, `:tvos`, or `:watchos`.
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.39.0/lib/cocoapods-core/podfile/target_definition.rb:441:in `set_platform'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer/target_inspector.rb:153:in `compute_platform'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer/target_inspector.rb:40:in `compute_results'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:659:in `block (2 levels) in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:657:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:657:in `block in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:656:in `inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:61:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:213:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:136:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:135:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:105:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

**Comment by orta** [comment]
That pod doesn't seem to exist: https://cocoapods.org/?q=FacebookSDK - where does it come from? Facebook use `FB*` pods - https://cocoapods.org/owners/7750

**Comment by DaveKerr** [comment]
Same error if I replace podfile with:

pod 'FBSDKLoginKit', '~> 4.6.0'
pod 'FBSDKCoreKit', '~> 4.6.0'
pod 'FBSDKShareKit', '~> 4.6.0'

**Comment by orta** [comment]
Weird, I've just done the same and got no problems. 

```
~/D/FBIssue ⏛  more Podfile
platform :ios, '8.0'

target 'FBIssue' do
  # pod 'FBSDKLoginKit', :git => "https://github.com/chrisp-fb/facebook-ios-sdk"
  # pod 'FBSDKCoreKit', :git =>"https://github.com/chrisp-fb/facebook-ios-sdk"
  pod 'FBSDKLoginKit', '~> 4.6.0'
  pod 'FBSDKCoreKit', '~> 4.6.0'
  pod 'FBSDKShareKit', '~> 4.6.0'

end

~/D/FBIssue ⏛  bundle exec pod --version
0.39.0

~/D/FBIssue ⏛  bundle exec pod install
Updating local specs repositories

CocoaPods 1.0.0.beta.2 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
Downloading dependencies
Using Bolts (1.6.0)
Installing FBSDKCoreKit 4.6.0 (was 4.8.0)
Installing FBSDKLoginKit 4.6.0 (was 4.8.0)
Installing FBSDKShareKit (4.6.0)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 3 dependencies from the Podfile and 4 total pods installed.
```

Any chance you can try the [Mac app](https://cocoapods.org/app) which hosts its own ruby environment ( You'll need to update your Podfile to 1.0 syntax though - see #4706  )

**Comment by DaveKerr** [comment]
I'm going to restart my machine. Do you need any information that I can get you before I do so?

Thanks,
Dave

**Comment by segiddins** [comment]
I'm guessing the issue here is that no `*_DEPLOYMENT_TARGET` setting is set for the project or the target in question?

**Comment by DaveKerr** [comment]
I have re-installed to the latest gem and changed the pod to 

pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod ‘FBSDKShareKit'

That worked.  Not sure what happened and not sure we can figure it out either.

I need to move on with my project so we should close this.
