### ISSUE TITLE
EPERM - Operation not permitted error when running pod update via jenkins

### ISSUE THREAD

**Issue by kasunk** [CocoaPods/CocoaPods#4794]
### Command

```
/usr/local/bin/pod update
```

### Report

* What did you do?
I am running an xcodebuild using jenkins

* What did you expect to happen?
The pod update command executes as normal

* What happened instead?
pod update fails with the attached error stack.

### Stack

```
   CocoaPods : 0.39.0
        Ruby : ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]
    RubyGems : 2.4.8
        Host : Mac OS X 10.11.2 (15C50)
       Xcode : 7.0 (7A220)
         Git : git version 2.3.8 (Apple Git-58)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 6881723fdc8b871ead64b0ea5c2b62a9e76cb3bc
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-search  : 0.1.0
cocoapods-stats   : 0.6.2
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.5.1
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

platform :ios, '8.0'

target 'CardinalHector' do
    
    pod 'AFNetworking'
    pod 'Mantle'
    pod 'MBProgressHUD'
    
    pod 'DRCircularProgress', '~> 1.0.3'
    pod 'Realm' , '~> 0.96.2'
    #pod 'JTCalendar'
    pod 'KeychainItemWrapper', '~> 1.2'
    use_frameworks!
    
    pod 'Moscapsule', :git => 'https://github.com/flightonary/Moscapsule.git'
    pod 'OpenSSL-Universal', '~> 1.0.1.l'
    pod 'MQTTClient'
    
end

target 'CardinalHectorTests' do
    
end

target 'CardinalHectorUITests' do
    
end
```

### Error

```
Errno::EPERM - Operation not permitted - /Users/Shared/Jenkins/Home/workspace/Cardinal/Pods/AFNetworking/AFNetworking/AFNetworking.h
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1333:in `chmod'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1333:in `chmod'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:975:in `block in chmod'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:974:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:974:in `chmod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/pod_source_installer.rb:92:in `block in unlock_files!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/pod_source_installer.rb:189:in `[]'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/pod_source_installer.rb:189:in `block (2 levels) in each_source_file'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/pod_source_installer.rb:187:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/pod_source_installer.rb:187:in `block in each_source_file'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/pod_source_installer.rb:186:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/pod_source_installer.rb:186:in `each_source_file'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/pod_source_installer.rb:91:in `unlock_files!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:361:in `block in unlock_pod_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:359:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:359:in `unlock_pod_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:461:in `perform_post_install_actions'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:113:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:156:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by neonichu** [comment]
Seems like the user who is running `pod update` doesn't have the right permissions to unlock (set write permissions on) files in the sandbox. Maybe a different user did run the initial `pod install`?

**Comment by kasunk** [comment]
Yse that was the problem and after I gave permission by "chmod -R 777
./Pods" it works .

On Thu, Jan 21, 2016 at 5:40 PM, Boris Bügling <notifications@github.com>
wrote:

> Seems like the user who is running pod update doesn't have the right
> permissions to unlock (set write permissions on) files in the sandbox.
> Maybe a different user did run the initial pod install?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CocoaPods/CocoaPods/issues/4794#issuecomment-173552737>
> .
>



-- 

*Best Regards,Kasun Aravinda*

**Comment by hvadotnarola** [comment]
I am getting this error after adding ios platform and hitting command `tns run ios`

>Processing node_modules failed. Error: Command sandbox-pod failed with exit code 71 Error output: 
 /Users/C173/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.0.1/bin/sandbox-pod:149: warning: Insecure world writable dir /Users/C173 in PATH, mode 040777
sandbox-exec: /Users/C173/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.0.1/bin/pod: Operation not permitted
