### ISSUE TITLE
Unable to install pods

### ISSUE THREAD

**Issue by davejlong** [CocoaPods/CocoaPods#4796]
### Command

```
/Users/david/.gem/ruby/2.3.0/bin/pod install
```

### Report

* What did you do?

Cloned my application; ran `gem install cocoapods`; ran `pod install`

* What did you expect to happen?

All of my pods to properly install.

* What happened instead?

Error installing Alamofire dependency.

### Stack

```
   CocoaPods : 0.39.0
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.2 (15C50)
       Xcode : 7.2 (7C68)
         Git : git version 2.7.0
Ruby lib dir : /Users/david/.rubies/ruby-2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ e70431d580c636c545c6128b187787bac19c049e
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-search  : 0.1.0
cocoapods-stats   : 0.6.2
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.5.1
```

### Podfile

```ruby
source "https://github.com/CocoaPods/Specs.git"
platform :ios, "9.0"

use_frameworks!

pod "Alamofire", "~> 3.1"
pod "SwiftyJSON", "~> 2.3"
pod "RealmSwift", "~> 0.97"
pod "SwiftSpinner", "~> 0.8"
pod "ResponseDetective", "~> 0.3"
pod "Locksmith", "~> 2.0"

pod "NewRelicAgent"
pod "Fabric"
pod "Crashlytics"
```

### Error

```
NoMethodError - undefined method `to_ary' for #<Pod::Specification name="Alamofire">
Did you mean?  to_query
/Users/david/.gem/ruby/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver/lazy_specification.rb:14:in `method_missing'
/Users/david/.gem/ruby/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:64:in `flatten'
/Users/david/.gem/ruby/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:64:in `block in resolve'
/Users/david/.gem/ruby/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:63:in `tap'
/Users/david/.gem/ruby/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:63:in `resolve'
/Users/david/.gem/ruby/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:539:in `block in resolve_dependencies'
/Users/david/.gem/ruby/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Users/david/.gem/ruby/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:537:in `resolve_dependencies'
/Users/david/.gem/ruby/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:70:in `analyze'
/Users/david/.gem/ruby/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:213:in `analyze'
/Users/david/.gem/ruby/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:136:in `block in resolve_dependencies'
/Users/david/.gem/ruby/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Users/david/.gem/ruby/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:135:in `resolve_dependencies'
/Users/david/.gem/ruby/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:105:in `install!'
/Users/david/.gem/ruby/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/david/.gem/ruby/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:101:in `run'
/Users/david/.gem/ruby/2.3.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Users/david/.gem/ruby/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Users/david/.gem/ruby/2.3.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/Users/david/.gem/ruby/2.3.0/bin/pod:23:in `load'
/Users/david/.gem/ruby/2.3.0/bin/pod:23:in `<main>'
```

**Comment by orta** [comment]
Thanks for the feedback. This is a bug with 0.39 and ruby 2.3.0 - #4689 
You can fix it by updating the the 1.0.0beta or using a different build of ruby for 0.39.

**Comment by davejlong** [comment]
So I am forced to use a beta build of Cocoapods in order to keep Alamofire updated, but now I can't install Realm, because 0.39 doesn't work with Cocoapods 1.0. Is that any solution that let's me use both Realm and Alamofire in a project?

**Comment by segiddins** [comment]
@davejlong you could also use CocoaPods 0.39 with a pre-2.3 version of ruby

**Comment by jshultz** [comment]
@davejlong   if you use rbenv you can set your local directory to use a specific version of ruby ( 2.2.2 for example) and it works fine.
