### ISSUE TITLE
Do a search on GitHub for issues relating to a crash?

### ISSUE THREAD

**Issue by orta** [CocoaPods/CocoaPods#4817]
I'm sure I've seen this in a ruby tool  ( maybe @krausefx's fastlane? ) but taking the 2.3.0 issue as an example:

What if we took the first 3 or 4 words from the error and searched for issues for that: so taking this issue https://github.com/CocoaPods/CocoaPods/issues/4748

Crashing line: `NoMethodError - undefined method 'to_ary' for #<Pod::Specification name="iVersion">'`
Assuming the `NoMethodError` is already a separate token of the error if we just did a search for `undefined method to_ary`:

https://github.com/CocoaPods/CocoaPods/search?q=undefined+method+%60to_ary%27&type=Issues&utf8=✓ this gives us 12 results

We could probably reduce a lot of issue churn by having it automatically search like this in the exception.

**Comment by segiddins** [comment]
We already put a link to a search below the error template.

**Comment by orta** [comment]
I don't think it's enough TBH

**Comment by segiddins** [comment]
What more can we do besides show them a link?

**Comment by orta** [comment]
We could provide some inline results, and improve the wording around the search link, e.g. after a crash:
```
### Error


NoMethodError - undefined method `to_ary' for #<Pod::Specification name="iVersion">
Did you mean?  to_query
/Users/swordray/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver/lazy_specification.rb:14:in `method_missing'
/Users/swordray/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:64:in `flatten'
/Users/swordray/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:64:in `block in resolve'
/Users/swordray/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:63:in `tap'
/Users/swordray/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:63:in `resolve'
/Users/swordray/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:539:in `block in resolve_dependencies'
/Users/swordray/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Users/swordray/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:537:in `resolve_dependencies'
/Users/swordray/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:70:in `analyze'
/Users/swordray/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:213:in `analyze'
/Users/swordray/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:136:in `block in resolve_dependencies'
/Users/swordray/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Users/swordray/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:135:in `resolve_dependencies'
/Users/swordray/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:105:in `install!'
/Users/swordray/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/swordray/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:101:in `run'
/Users/swordray/.rvm/gems/ruby-2.3.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Users/swordray/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Users/swordray/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/Users/swordray/.rvm/gems/ruby-2.3.0/bin/pod:23:in `load'
/Users/swordray/.rvm/gems/ruby-2.3.0/bin/pod:23:in `<main>'
/Users/swordray/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/Users/swordray/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'

[⠁⠂⠄⡀⢀⠠⠐⠈] - Looking for related issues on CocoaPods/CocoaPods
```

While it loads, then, we can show the top 3, and provide a more link:

```
- undefined method `to_ary' for #<Pod::Specification name="iVersion">Did you mean? to_query
  https://github.com/CocoaPods/CocoaPods/issues/4748  [closed] [1 comment]

- NoMethodError - undefined method `to_ary' for Pod EAIntroView
  https://github.com/CocoaPods/CocoaPods/issues/4391  [closed] [15 comments]

- Do a search on GitHub for issues relating to a crash?
  https://github.com/CocoaPods/CocoaPods/issues/4391  [open] [3 comments]

and 10 more at
https://github.com/CocoaPods/CocoaPods/search?q=undefined+method+%60to_ary%27&type=Issues&utf8=✓
```

**Comment by segiddins** [comment]
Ah ok, I see what you mean. Yeah, that'd be cool ;)

**Comment by KrauseFx** [comment]
Great idea! This would even be something that can be used for any Ruby/GitHub based open source project :+1:

**Comment by orta** [comment]
The dependency https://github.com/orta/gh-issues-inspector is now ready for integration
