### ISSUE TITLE
Pod trunk deprecate not working from master

### ISSUE THREAD

**Issue by k06a** [CocoaPods/CocoaPods#4833]
### Command

```
/Users/k06a/.bundle/ruby/2.0.0/bin/pod trunk deprecate ABCropRotateView --in-favor-of=CroptateView
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.0.0.beta.2
        Ruby : ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.2 (15C50)
       Xcode : 7.2 (7C68)
         Git : git version 2.5.4 (Apple Git-61)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ baa75d1048267b436399f8c1d13fc820c435ba5f
               Searchie - git@github.com:Searchie/CocoaPodSpecs.git @ ebb2d770aa75f6841bb025ae407d54469575a867
```

### Plugins

```
cocoapods-deintegrate : 1.0.0.beta.1
cocoapods-plugins     : 1.0.0.beta.1
cocoapods-search      : 1.0.0.beta.1
cocoapods-stats       : 1.0.0.beta.3
cocoapods-trunk       : 1.0.0.beta.1
cocoapods-try         : 1.0.0.beta.2
```

### Error

```
NoMethodError - undefined method `bytesize' for #<Hash:0x007f8dd2a573e8>
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/generic_request.rb:179:in `send_request_with_body'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/generic_request.rb:130:in `exec'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1410:in `block in transport_request'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1409:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1409:in `transport_request'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1382:in `request'
/Library/Ruby/Gems/2.0.0/gems/nap-1.0.0/lib/rest/request.rb:186:in `block in perform'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:852:in `start'
/Library/Ruby/Gems/2.0.0/gems/nap-1.0.0/lib/rest/request.rb:186:in `perform'
/Library/Ruby/Gems/2.0.0/gems/nap-1.0.0/lib/rest/request.rb:195:in `perform'
/Library/Ruby/Gems/2.0.0/gems/nap-1.0.0/lib/rest.rb:68:in `patch'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-1.0.0.beta.1/lib/pod/command/trunk.rb:45:in `create_request'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-1.0.0.beta.1/lib/pod/command/trunk.rb:28:in `request_url'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-1.0.0.beta.1/lib/pod/command/trunk.rb:36:in `request_path'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-1.0.0.beta.1/lib/pod/command/trunk/deprecate.rb:33:in `deprecate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-1.0.0.beta.1/lib/pod/command/trunk/deprecate.rb:28:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0.beta.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.2/bin/pod:44:in `<top (required)>'
/Users/k06a/.bundle/ruby/2.0.0/bin/pod:23:in `load'
/Users/k06a/.bundle/ruby/2.0.0/bin/pod:23:in `<main>'
```

**Comment by segiddins** [comment]
This is an issue that has already been fixed in CocoaPods/cocoapods-trunk.
