### ISSUE TITLE
Adding support for watchos 2 target into preexisting environment

### ISSUE THREAD

**Issue by asowers1** [CocoaPods/CocoaPods#4856]
### Command

```
/Users/Andrew/.rbenv/versions/2.2.0/bin/pod install
```

### Report
I'm having an issue adding support for a watchos 2 target to my Podfile. I have been able to create a new XCProject and go through the examples to get things working, but when I attempt to produce a similar result in my actual project, things go awry. If someone would be willing to work  through this with me, I would be extremely grateful :pray: 

### Stack

```
   CocoaPods : 0.39.0
        Ruby : ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin15]
    RubyGems : 2.4.5
        Host : Mac OS X 10.11.3 (15D21)
       Xcode : 7.2 (7C68)
         Git : git version 2.5.4 (Apple Git-61)
Ruby lib dir : /Users/Andrew/.rbenv/versions/2.2.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 205b715b0f56dbf3cf23f3e6d72b575f2f3f5e05
```

### Plugins

```
cocoapods-keys    : 1.6.0
cocoapods-plugins : 0.4.2
cocoapods-search  : 0.1.0
cocoapods-stats   : 0.6.2
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.5.1
```

### Podfile

```ruby
use_frameworks!
inhibit_all_warnings!

target 'Karma' do
pod "Moses",    git: "https://github.com/klaaspieter/moses"
pod "Hotshot",  git: "https://#####:##########@yourkarma/hotshot.git"
pod "Bars",     git: "https://github.com/yourkarma/Bars.git", commit: "8f6b655"
pod "Numeric",  git: "https://github.com/klaaspieter/numeric"
pod "Cards",    git: "https://github.com/yourkarma/Cards"

pod "SDWebImage"
pod "HockeySDK"
pod 'Google/Analytics'
pod "pop"
pod "OAStackView"
pod "Fabric"
pod "Crashlytics"

# Until the following PRs are merged
# https://github.com/stripe/stripe-ios/pull/271
# https://github.com/stripe/stripe-ios/pull/272
pod "Stripe", git: "https://github.com/yourkarma/stripe-ios.git", branch: "karma-changes"

pod "RNCryptor"

pod "1PasswordExtension"
pod "RBStoryboardLink", "~> 0.1"

pod "Logger",   path: "./Logger"
pod "API",      path: "./API"
pod "Notify",   path: "./Notify"
end

target "Tests" do
pod "Quick"
pod "Nimble"
pod "KPAViewControllerTestHelper"
end

target "watchkitapp Extension" do
platform :watchos, '2.0'
pod 'Alamofire', :git => 'git@github.com:neonichu/Alamofire.git', :branch => 'watchos'
# this is just to see if I can get a basic pod setup
end

plugin "cocoapods-keys", {
  project: "Karma",
  keys: ["OAuthSecret"]
}

def update_search_user_paths(configuration)
  configuration.build_settings["ALWAYS_SEARCH_USER_PATHS"] = "NO"
end

def speed_up_debug_builds
    puts("Update debug pod settings to speed up build time")
    Dir.glob(File.join("Pods", "**", "Pods*{debug,Private}.xcconfig")).each do |file|
      File.open(file, 'a') { |f| f.puts "\nDEBUG_INFORMATION_FORMAT = dwarf" }
    end
end

# Because https://github.com/CocoaPods/CocoaPods/issues/4421
def set_framework_version_numbers(installer)
  app_plist = "Karma/Info.plist"
  plist_buddy = "/usr/libexec/PlistBuddy"
  version = `#{plist_buddy} -c "Print CFBundleShortVersionString" #{app_plist}`.strip
  puts "Updating CocoaPods' version numbers to #{version}"

  installer.pods_project.targets.each do |target|
    `#{plist_buddy} -c "Set CFBundleShortVersionString #{version}" "Pods/Target Support Files/#{target}/Info.plist"`
  end
end

post_install do |installer|
    installer.pods_project.build_configuration_list.build_configurations.each do |configuration|
      update_search_user_paths configuration
    end
    speed_up_debug_builds

    set_framework_version_numbers installer
end
```

### Error

```
Pod::Podfile::StandardError - Unsupported platform ``. Platform must be `:ios`, `:osx`, `:tvos`, or `:watchos`.
/Users/Andrew/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoapods-core-0.39.0/lib/cocoapods-core/podfile/target_definition.rb:441:in `set_platform'
/Users/Andrew/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer/target_inspector.rb:153:in `compute_platform'
/Users/Andrew/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer/target_inspector.rb:40:in `compute_results'
/Users/Andrew/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:659:in `block (2 levels) in inspect_targets_to_integrate'
/Users/Andrew/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:657:in `each'
/Users/Andrew/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:657:in `block in inspect_targets_to_integrate'
/Users/Andrew/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Users/Andrew/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:656:in `inspect_targets_to_integrate'
/Users/Andrew/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:61:in `analyze'
/Users/Andrew/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:213:in `analyze'
/Users/Andrew/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:136:in `block in resolve_dependencies'
/Users/Andrew/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Users/Andrew/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:135:in `resolve_dependencies'
/Users/Andrew/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:105:in `install!'
/Users/Andrew/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoapods-keys-1.6.0/lib/plugin.rb:99:in `install!'
/Users/Andrew/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/Andrew/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:101:in `run'
/Users/Andrew/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Users/Andrew/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Users/Andrew/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/Users/Andrew/.rbenv/versions/2.2.0/bin/pod:23:in `load'
/Users/Andrew/.rbenv/versions/2.2.0/bin/pod:23:in `<main>'
```

**Comment by segiddins** [comment]
Can you share a project that reproduces this issue with us? Thanks!

**Comment by asowers1** [comment]
Would it be alright if I strip the project of code and pods private repo'd behind our vpn?

**Comment by segiddins** [comment]
Sure! It could even be a totally different project, as long as t reproduces the issue.

**Comment by asowers1** [comment]
Here is the project producing the same issue, but stripped of the goods ;) https://drive.google.com/open?id=0BxnGwcgU4AYtWUpzT1RGSUYwVHc People let me know if I've erred in any way or you require more information :)

**Comment by neonichu** [comment]
Can't access the example, but as a workaround, explicitly setting a platform at the top-level should work.

**Comment by asowers1** [comment]
When I set the top-level platform explicitly, I receive this warning that I've seen mentioned here https://github.com/CocoaPods/CocoaPods/issues/2633

```
: [!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Karma` to `Pods/Target Support Files/Pods-Karma/Pods-Karma.debug.xcconfig` or include the `Pods/Target Support Files/Pods-Karma/Pods-Karma.debug.xcconfig` in your build configuration.

[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Karma` to `Pods/Target Support Files/Pods-Karma/Pods-Karma.release.xcconfig` or include the `Pods/Target Support Files/Pods-Karma/Pods-Karma.release.xcconfig` in your build configuration.
```

And I am unable to use my Pods specified in the watch extension target.

Also, why would Pod files like the one below work as expected without explicitly specifying a top-level platform and mine not?
```
# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'watchTest' do
pod 'Alamofire', '~> 2.0.0-beta.1'
end

target 'watchTestTests' do

end

target 'watchTestUITests' do

end

target 'watchTest WatchKit App' do

end

target 'watchTest WatchKit Extension' do
platform :watchos, '2.0'
pod 'Alamofire', '~> 2.0.0-beta.1'
end
```

You should be able to request access to the example via the link? Let me know if it's broken for you.
I really appreciate your help :)

**Comment by asowers1** [comment]
Okay, here's an open like to the project: https://drive.google.com/a/yourkarma.com/file/d/0BxnGwcgU4AYtWUpzT1RGSUYwVHc/view?usp=sharing Please let me know if I can provide any more information. I would really love to be able to use cocoapods in all of our future targets.

**Comment by segiddins** [comment]
This is happening because neither the project nor the iOS targets have an SDKROOT set

**Comment by asowers1** [comment]
Is that different from setting the Deployable Target in the General tab of the target? Because that doesn't change anything for me. Could you send a screenshot of where you were able to set the SDKROOT and successfully run a pod install without specifying a top level platform in the Podfile?

**Comment by segiddins** [comment]
Just search for the SDKROOT setting in the build settings tab and make sure it is set explicitly -- I'm not near a computer right now.

**Comment by asowers1** [comment]
They appear to be set as iphoneos on my end. Am I overlooking something fundamental?

**Comment by segiddins** [comment]
They're not actually set -- they're falling back to a default. Try setting them explicitly.
