### ISSUE TITLE
 undefined method `to_ary' 

### ISSUE THREAD

**Issue by dcorbin** [CocoaPods/CocoaPods#4891]
### Command

```
/usr/local/var/rbenv/versions/2.3.0/bin/pod install
```

### Report

I think the details below say it better than I can.  I will note that I subsequently download the beta app and managed to get things working with that.

### Stack

```
   CocoaPods : 0.39.0
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.3 (15D21)
       Xcode : 7.2 (7C68)
         Git : git version 2.7.1
Ruby lib dir : /usr/local/var/rbenv/versions/2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 61b075150300a0264d2d8959c85e3241d93951f5
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-search  : 0.1.0
cocoapods-stats   : 0.6.2
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.5.1
```

### Podfile

```ruby
pod 'InAppSettingsKit'
```

### Error

```
NoMethodError - undefined method `to_ary' for #<Pod::Specification name="InAppSettingsKit">
Did you mean?  to_query
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver/lazy_specification.rb:14:in `method_missing'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:64:in `flatten'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:64:in `block in resolve'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:63:in `tap'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:63:in `resolve'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:539:in `block in resolve_dependencies'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:537:in `resolve_dependencies'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:70:in `analyze'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:213:in `analyze'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:136:in `block in resolve_dependencies'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:135:in `resolve_dependencies'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:105:in `install!'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:101:in `run'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/usr/local/var/rbenv/versions/2.3.0/bin/pod:23:in `load'
/usr/local/var/rbenv/versions/2.3.0/bin/pod:23:in `<main>'
```

**Comment by segiddins** [comment]
The first version to support ruby 2.3 is the CocoaPods 1.0 beta.
