### ISSUE TITLE
pod install for IMFCore fails

### ISSUE THREAD

**Issue by clouibm** [CocoaPods/CocoaPods#4906]
### Command

```
/usr/bin/pod install
```

### Report

* What did you do?
Following Bluemix sample app at https://github.com/ibm-bluemix-mobile-services/bms-samples-ios-hellotodo
And running 'pod install'

* What did you expect to happen?
'pod install' to finish successfully.
* What happened instead?
An error occured.

### Stack

```
   CocoaPods : 1.0.0.beta.3
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.0.14
        Host : Mac OS X 10.10.5 (14F1509)
       Xcode : 7.2.1 (7C1002)
         Git : git version 2.5.4 (Apple Git-61)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ c30171c82486277205292bf54ee69efd6be8bb12
```

### Plugins

```
cocoapods-deintegrate : 1.0.0.beta.1
cocoapods-plugins     : 1.0.0.beta.1
cocoapods-search      : 1.0.0.beta.1
cocoapods-stats       : 1.0.0.beta.3
cocoapods-trunk       : 1.0.0.beta.2
cocoapods-try         : 1.0.0.beta.2
```

### Podfile

```ruby
platform :ios, '9.0'

target 'helloTodo' do
pod 'IMFCore'
end
workspace 'helloTodo'
```

### Error

```
NoMethodError - undefined method `add_element' for nil:NilClass
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.0.0.beta.2/lib/xcodeproj/workspace.rb:107:in `<<'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.3/lib/cocoapods/installer/user_project_integrator.rb:94:in `block in create_workspace'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.3/lib/cocoapods/installer/user_project_integrator.rb:94:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.3/lib/cocoapods/installer/user_project_integrator.rb:94:in `create_workspace'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.3/lib/cocoapods/installer/user_project_integrator.rb:62:in `integrate!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.3/lib/cocoapods/installer.rb:770:in `block in integrate_user_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.3/lib/cocoapods/user_interface.rb:63:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.3/lib/cocoapods/installer.rb:767:in `integrate_user_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.3/lib/cocoapods/installer.rb:116:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.3/lib/cocoapods/command/project.rb:67:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.3/lib/cocoapods/command/project.rb:97:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0.beta.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.3/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.3/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

**Comment by segiddins** [comment]
The issue is that the workspace in https://github.com/ibm-bluemix-mobile-services/bms-samples-ios-hellotodo/tree/master/helloTodo is invalid. Try deleting it and then running `pod install`.

**Comment by clouibm** [comment]
After removing helloTodo.xcworkspace as suggested, 'pod install' succeeds. Thanks segiddins!

**Comment by sibeliusseraphini** [comment]
@segiddins there should be a better error message for this case

**Comment by segiddins** [comment]
@sibeliusseraphini a PR improving the error message in xcodeproj would be much appreciated!
