### ISSUE TITLE
NoMethodError - undefined method `user_targets' for #<Pod::Installer::PostInstallHooksContext::UmbrellaTargetDescription:

### ISSUE THREAD

**Issue by sagargondaliya** [CocoaPods/CocoaPods#4919]
I am trying to install pod but it generates following error. Here i post logs of Terminal.

`Last login: Sat Feb 20 14:31:41 on ttys001
Arvaans-Mac-mini:~ Arvaan$ cd /Users/Arvaan/Desktop/CocoapodsDemo 
Arvaans-Mac-mini:CocoapodsDemo Arvaan$ pod install
[!] Unable to load a specification for the plugin `/Users/Arvaan/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-deintegrate-1.0.0.beta.1`
Updating local specs repositories

CocoaPods 1.0.0.beta.3 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
Downloading dependencies
Using RAMReel (1.0.5)
Generating Pods project
Integrating client project
Sending stats
[!] Unable to load a specification for the plugin `/Users/Arvaan/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-deintegrate-1.0.0.beta.1`

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/Arvaan/.rvm/rubies/ruby-2.2.1/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 0.39.0
        Ruby : ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin15]
    RubyGems : 2.5.2
        Host : Mac OS X 10.11.2 (15C50)
       Xcode : 7.1 (7B91b)
         Git : git version 2.4.9 (Apple Git-60)
Ruby lib dir : /Users/Arvaan/.rvm/rubies/ruby-2.2.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ ffd720f3434db0c842113643bc471934355ffb0e
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-search  : 0.1.0
cocoapods-stats   : 0.6.2
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.5.1
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project

platform :ios, '8.0'
use_frameworks!

target 'CocoapodsDemo' do

pod 'RAMReel'

end
```

### Error

```
NoMethodError - undefined method `user_targets' for #<Pod::Installer::PostInstallHooksContext::UmbrellaTargetDescription:0x007fc683ba52d8>
/Users/Arvaan/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-stats-1.0.0.beta.2/lib/cocoapods_stats/target_mapper.rb:20:in `block in pods_from_project'
/Users/Arvaan/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-stats-1.0.0.beta.2/lib/cocoapods_stats/target_mapper.rb:9:in `each'
/Users/Arvaan/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-stats-1.0.0.beta.2/lib/cocoapods_stats/target_mapper.rb:9:in `flat_map'
/Users/Arvaan/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-stats-1.0.0.beta.2/lib/cocoapods_stats/target_mapper.rb:9:in `pods_from_project'
/Users/Arvaan/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-stats-0.6.2/lib/cocoapods_plugin.rb:31:in `block (2 levels) in <module:CocoaPodsStats>'
/Users/Arvaan/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:80:in `titled_section'
/Users/Arvaan/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-stats-0.6.2/lib/cocoapods_plugin.rb:27:in `block in <module:CocoaPodsStats>'
/Users/Arvaan/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:117:in `call'
/Users/Arvaan/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:117:in `block (3 levels) in run'
/Users/Arvaan/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:140:in `message'
/Users/Arvaan/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:111:in `block (2 levels) in run'
/Users/Arvaan/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:109:in `each'
/Users/Arvaan/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:109:in `block in run'
/Users/Arvaan/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:140:in `message'
/Users/Arvaan/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:108:in `run'
/Users/Arvaan/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:481:in `run_plugins_post_install_hooks'
/Users/Arvaan/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:462:in `perform_post_install_actions'
/Users/Arvaan/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:113:in `install!'
/Users/Arvaan/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/Arvaan/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:101:in `run'
/Users/Arvaan/.rvm/gems/ruby-2.2.1@global/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Users/Arvaan/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Users/Arvaan/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/Users/Arvaan/.rvm/rubies/ruby-2.2.1/bin/pod:22:in `load'
/Users/Arvaan/.rvm/rubies/ruby-2.2.1/bin/pod:22:in `<main>'
/Users/Arvaan/.rvm/gems/ruby-2.2.1@global/bin/ruby_executable_hooks:15:in `eval'
/Users/Arvaan/.rvm/gems/ruby-2.2.1@global/bin/ruby_executable_hooks:15:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=undefined+method+%60user_targets%27+for+%23%3CPod%3A%3AInstaller%3A%3APostInstallHooksContext%3A%3AUmbrellaTargetDescription%3A0x007fc683ba52d8%3E&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Arvaans-Mac-mini:CocoapodsDemo Arvaan$ 
`

**Comment by segiddins** [comment]
This is a duplicate issue. Run `gem install cocoapods-stats --pre`.

**Comment by sagargondaliya** [comment]
Its fixed , now
Thanks
