### ISSUE TITLE
pod trunk push resulting in Internal sever error 500

### ISSUE THREAD

**Issue by alokjha** [CocoaPods/CocoaPods#4922]
I am trying to push an update to my podspec and getting 500 error.

````
* BUILD SUCCEEDED **

 -> GetSimpl-iOS7 (1.2.6)

opening connection to trunk.cocoapods.org:443...
opened
starting SSL for trunk.cocoapods.org:443...
SSL established
<- "POST /api/v1/pods?allow_warnings=false HTTP/1.1\r\nContent-Type: application/json; charset=utf-8\r\nAccept: application/json; charset=utf-8\r\nUser-Agent: CocoaPods/0.39.0\r\nAuthorization: Token 0d755ff873ad10b9518de4bf0ee3edec\r\nAccept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3\r\nHost: trunk.cocoapods.org\r\nContent-Length: 562\r\n\r\n"
<- "{\"name\":\"GetSimpl-iOS7\",\"version\":\"1.2.6\",\"summary\":\"GetSimpl iOS SDK Static Library\",\"homepage\":\"https://github.com/GetSimpl/simpl-ios-sdk-dist-ios7\",\"source\":{\"git\":\"https://github.com/GetSimpl/simpl-ios-sdk-dist-ios7.git\",\"tag\":\"v1.2.6\"},\"license\":{\"type\":\"Commercial\",\"file\":\"License\"},\"platforms\":{\"ios\":\"7.0\"},\"authors\":{\"Alok Jha\":\"alok@getsimpl.com\"},\"ios\":{\"resources\":\"GetSimplResources.bundle\",\"vendored_libraries\":\"libGetSimpl.a\"},\"source_files\":\"include/*.h\",\"public_header_files\":\"include/*.h\",\"preserve_paths\":\"libGetSimpl.a\",\"requires_arc\":true}\n"
-> "HTTP/1.1 500 Internal Server Error\r\n"
-> "Date: Mon, 22 Feb 2016 08:49:30 GMT\r\n"
-> "Connection: keep-alive\r\n"
-> "Strict-Transport-Security: max-age=31536000\r\n"
-> "Content-Type: application/json\r\n"
-> "Content-Length: 141\r\n"
-> "X-Content-Type-Options: nosniff\r\n"
-> "Server: thin 1.6.2 codename Doc Brown\r\n"
-> "Via: 1.1 vegur\r\n"
-> "\r\n"
reading 141 bytes...
-> "{\"error\":\"An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later.\"}"
read 141 bytes
Conn keep-alive
[!] An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later.

/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-0.6.4/lib/pod/command/trunk.rb:68:in `print_error'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-0.6.4/lib/pod/command/trunk.rb:28:in `request_url'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-0.6.4/lib/pod/command/trunk.rb:34:in `request_path'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-0.6.4/lib/pod/command/trunk/push.rb:60:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
````

I tried it multiple times but still not working.

My pod version is : 0.39.0
Also when trying to go to http://cocoapods.org/pods/GetSimpl-iOS7 , Internal Server error 500 is getting received by browser.

**Comment by alokjha** [comment]
But Cocoapod spec repo https://github.com/CocoaPods/Specs/tree/master/Specs/GetSimpl-iOS7 is showing that v1.2.6 is pushed but I never got any confirmation while doing pod trunk push.

**Comment by orta** [comment]
Hrm, I'm seeing some errors around this timeframe which look related to [the GitHub API](https://rpm.newrelic.com/accounts/395442/applications/1999899/filterable_errors#/metric/table?top_facet=transactionUiName&primary_facet=error.class&_k=5vo084)

**Comment by alokjha** [comment]
The thing is that I tried a using my pod in a test project and cocoapod installed the version 1.2.6 which I was trying to push to trunk . But still http://cocoapods.org/pods/GetSimpl-iOS7 returns Internal Server Error.

**Comment by segiddins** [comment]
That's an issue that belongs over on the CocoaPods.org repo.
