### ISSUE TITLE
ArgumentError - Illformed requirement `"~>pod 3.0.4"`

### ISSUE THREAD

**Issue by polegithub** [CocoaPods/CocoaPods#4938]
Update all pods
Updating local specs repositories

CocoaPods 1.0.0.beta.3 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/chengpoleness/.rvm/gems/ruby-2.0.0-p598/bin/pod update
```

### Report

* What did you do?
  pod update

* What did you expect to happen?
  pod update successfully

* What happened instead?
 ArgumentError - Illformed requirement `"~>pod 3.0.4"`

### Stack

```
   CocoaPods : 0.39.0
        Ruby : ruby 2.0.0p598 (2014-11-13 revision 48408) [x86_64-darwin14.0.0]
    RubyGems : 2.4.5
        Host : Mac OS X 10.10.5 (14F1021)
       Xcode : 7.2 (7C68)
         Git : git version 2.5.4 (Apple Git-61)
Ruby lib dir : /Users/chengpoleness/.rvm/rubies/ruby-2.0.0-p598/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 71b8d0a6e42c5e11c9063cd4a32a0f6861f7a5ed
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-search  : 0.1.0
cocoapods-stats   : 0.6.2
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.5.1
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, "7.0"

target "DadaStaff" do
    pod 'AMap3DMap', '~> 3.2.1' #3D地图SDK(2D地图和3D地图不能同时使用)
    pod 'AMapSearch', '~> 3.2.0'  #搜索服务SDK
    pod 'AFNetworking', '~> 2.5.4'
    pod 'AFNetworkActivityLogger', '~> 2.0.4'
    pod 'Toast', '~> 2.3'
    pod 'OpenUDID'
    pod 'IQActionSheetPickerView', '~> 1.0.1'
    pod 'IQKeyboardManager', '~> 3.3.0'
    pod 'Mantle', '~> 2.0'
    pod 'JGProgressHUD', '~> 1.2.5'
    pod 'WebViewJavascriptBridge', '~> 4.1.4'
    pod 'BrightSDK', '~>pod 3.0.4'
    pod 'Qiniu'
    pod 'Base64', '~> 1.0.1'
    pod 'Bugtags', '~> 1.1.7'
    pod 'zipzap'
    pod 'tingyunApp', '~> 2.3.3'
    #pod 'CocoaAsyncSocket', '~> 7.4.1'
    #pod 'CustomIOSAlertView', '~> 0.9.3'  #自定义alertView
end

target "DadaStaffTests" do
    
end

target "dadaShop" do
    #pod 'AMap2DMap', "2.4" #2D地图SDK
    pod 'AMap3DMap', '~> 3.2.1' #3D地图SDK(2D地图和3D地图不能同时使用)
    pod 'AMapSearch', '~> 3.2.0'  #搜索服务SDK
    pod 'AFNetworking', '~> 2.5.4'
    pod 'AFNetworkActivityLogger', '~> 2.0.4'
    pod 'Toast', '~> 2.3'
    pod 'OpenUDID'
    pod 'IQActionSheetPickerView', '~> 1.0.1'
    pod 'IQKeyboardManager', '~> 3.3.0'
    pod 'Mantle', '~> 2.0'
    pod 'JGProgressHUD', '~> 1.2.5'
    pod 'WebViewJavascriptBridge', '~> 4.1.4'
    pod 'BrightSDK', '~> 3.0.4'
    pod 'Qiniu'
    pod 'Base64', '~> 1.0.1'
    pod 'Bugtags', '~> 1.1.7'
    pod 'CocoaAsyncSocket', '~> 7.4.1'
    pod 'ProtocolBuffers'
    #pod 'CustomIOSAlertView', '~> 0.9.3'  #自定义alertView
end

target "dadaShopTests" do
    
end

target "plyChip" do
    pod 'Reachability', '3.1.0'
    pod 'AFNetworking', '~> 2.5.4'
    pod 'JGProgressHUD', '~> 1.2.5'
    pod 'AMapSearch', '~> 3.2.0'  #搜索服务SDK
    pod 'AMap3DMap', '~> 3.2.1' #3D地图SDK(2D地图和3D地图不能同时使用)
    pod 'CocoaLumberjack'
    pod 'DateTools'
    pod 'MJRefresh'
    pod 'libqrencode'
    pod 'QRCodeReaderViewController'
    pod 'Bugtags', '~> 1.1.7'
    pod 'WebViewJavascriptBridge', '~> 4.1.4'
end

target "plyChipTests" do
    
end

target "shop" do
    pod 'AMap3DMap', '~> 3.2.1' #3D地图SDK(2D地图和3D地图不能同时使用)
    pod 'AMapSearch', '~> 3.2.0'  #搜索服务SDK
    pod 'AFNetworking', '~> 2.5.4'
    pod 'Toast', '~> 2.3'
    pod 'OpenUDID'
    pod 'IQActionSheetPickerView', '~> 1.0.1'
    pod 'IQKeyboardManager', '~> 3.3.0'
    pod 'JGProgressHUD', '~> 1.2.5'
end

target "shopTests" do
    
    
end
```

### Error

```
ArgumentError - Illformed requirement `"~>pod 3.0.4"`
/Users/chengpoleness/.rvm/gems/ruby-2.0.0-p598/gems/cocoapods-core-0.39.0/lib/cocoapods-core/requirement.rb:63:in `parse'
/Users/chengpoleness/.rvm/gems/ruby-2.0.0-p598/gems/cocoapods-core-0.39.0/lib/cocoapods-core/requirement.rb:88:in `block in initialize'
/Users/chengpoleness/.rvm/gems/ruby-2.0.0-p598/gems/cocoapods-core-0.39.0/lib/cocoapods-core/requirement.rb:88:in `map!'
/Users/chengpoleness/.rvm/gems/ruby-2.0.0-p598/gems/cocoapods-core-0.39.0/lib/cocoapods-core/requirement.rb:88:in `initialize'
/Users/chengpoleness/.rvm/gems/ruby-2.0.0-p598/gems/cocoapods-core-0.39.0/lib/cocoapods-core/requirement.rb:34:in `new'
/Users/chengpoleness/.rvm/gems/ruby-2.0.0-p598/gems/cocoapods-core-0.39.0/lib/cocoapods-core/requirement.rb:34:in `create'
/Users/chengpoleness/.rvm/gems/ruby-2.0.0-p598/gems/cocoapods-core-0.39.0/lib/cocoapods-core/dependency.rb:92:in `initialize'
/Users/chengpoleness/.rvm/gems/ruby-2.0.0-p598/gems/cocoapods-core-0.39.0/lib/cocoapods-core/podfile/target_definition.rb:650:in `new'
/Users/chengpoleness/.rvm/gems/ruby-2.0.0-p598/gems/cocoapods-core-0.39.0/lib/cocoapods-core/podfile/target_definition.rb:650:in `block in pod_dependencies'
/Users/chengpoleness/.rvm/gems/ruby-2.0.0-p598/gems/cocoapods-core-0.39.0/lib/cocoapods-core/podfile/target_definition.rb:646:in `map'
/Users/chengpoleness/.rvm/gems/ruby-2.0.0-p598/gems/cocoapods-core-0.39.0/lib/cocoapods-core/podfile/target_definition.rb:646:in `pod_dependencies'
/Users/chengpoleness/.rvm/gems/ruby-2.0.0-p598/gems/cocoapods-core-0.39.0/lib/cocoapods-core/podfile/target_definition.rb:87:in `non_inherited_dependencies'
/Users/chengpoleness/.rvm/gems/ruby-2.0.0-p598/gems/cocoapods-core-0.39.0/lib/cocoapods-core/podfile/target_definition.rb:79:in `dependencies'
/Users/chengpoleness/.rvm/gems/ruby-2.0.0-p598/gems/cocoapods-0.39.0/lib/cocoapods/installer/podfile_validator.rb:59:in `block in validate_pod_directives'
/Users/chengpoleness/.rvm/gems/ruby-2.0.0-p598/gems/cocoapods-0.39.0/lib/cocoapods/installer/podfile_validator.rb:58:in `each'
/Users/chengpoleness/.rvm/gems/ruby-2.0.0-p598/gems/cocoapods-0.39.0/lib/cocoapods/installer/podfile_validator.rb:58:in `flat_map'
/Users/chengpoleness/.rvm/gems/ruby-2.0.0-p598/gems/cocoapods-0.39.0/lib/cocoapods/installer/podfile_validator.rb:58:in `validate_pod_directives'
/Users/chengpoleness/.rvm/gems/ruby-2.0.0-p598/gems/cocoapods-0.39.0/lib/cocoapods/installer/podfile_validator.rb:29:in `validate'
/Users/chengpoleness/.rvm/gems/ruby-2.0.0-p598/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:155:in `validate_podfile!'
/Users/chengpoleness/.rvm/gems/ruby-2.0.0-p598/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:57:in `analyze'
/Users/chengpoleness/.rvm/gems/ruby-2.0.0-p598/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:213:in `analyze'
/Users/chengpoleness/.rvm/gems/ruby-2.0.0-p598/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:136:in `block in resolve_dependencies'
/Users/chengpoleness/.rvm/gems/ruby-2.0.0-p598/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Users/chengpoleness/.rvm/gems/ruby-2.0.0-p598/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:135:in `resolve_dependencies'
/Users/chengpoleness/.rvm/gems/ruby-2.0.0-p598/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:105:in `install!'
/Users/chengpoleness/.rvm/gems/ruby-2.0.0-p598/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/chengpoleness/.rvm/gems/ruby-2.0.0-p598/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:156:in `run'
/Users/chengpoleness/.rvm/gems/ruby-2.0.0-p598@global/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Users/chengpoleness/.rvm/gems/ruby-2.0.0-p598/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Users/chengpoleness/.rvm/gems/ruby-2.0.0-p598/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/Users/chengpoleness/.rvm/gems/ruby-2.0.0-p598/bin/pod:23:in `load'
/Users/chengpoleness/.rvm/gems/ruby-2.0.0-p598/bin/pod:23:in `<main>'
/Users/chengpoleness/.rvm/gems/ruby-2.0.0-p598/bin/ruby_executable_hooks:15:in `eval'
/Users/chengpoleness/.rvm/gems/ruby-2.0.0-p598/bin/ruby_executable_hooks:15:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

**Comment by neonichu** [comment]
One of your dependencies is malformed, `pod 'BrightSDK', '~>pod 3.0.4'`
