### ISSUE TITLE
protobuf -ios  pod install error

### ISSUE THREAD

**Issue by fengshuo1992** [CocoaPods/CocoaPods#4955]
> ℹ Please fill out this template when filing an issue.
### Error

```
Errno::ENOENT - No such file or directory - /Users/mac/.cocoapods/repos/master
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.39.0/lib/cocoapods-core/source.rb:41:in `chdir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.39.0/lib/cocoapods-core/source.rb:41:in `url'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-stats-0.6.2/lib/cocoapods_plugin.rb:4:in `validates?'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-stats-0.6.2/lib/cocoapods_plugin.rb:25:in `block in <module:CocoaPodsStats>'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:117:in `call'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:117:in `block (3 levels) in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:140:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:111:in `block (2 levels) in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:109:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:109:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:140:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:108:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:481:in `run_plugins_post_install_hooks'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:462:in `perform_post_install_actions'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:113:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
* [ ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

> ℹ Please replace this with what you did.  
>  Run `pod install`

## What did you expected to happen?

> ℹ Please replace this with what you expected to happen.  
> e.g. Install all pod dependencies correctly.

## What happened instead?

> ℹ Please replace this with of what happened instead.  
> e.g. Pod A is missing the subspec B for target C.

## Podfile

source 'https://gitcafe.com/akuandev/Specs.git'

# platform :ios, '8.0'

target "APP" do

pod "ProtocolBuffers", "~> 1.9.7"

end
```ruby
```

**Comment by segiddins** [comment]
@orta this is a bug in stats -- it needs to handle the master repo not being cloned.

**Comment by orta** [comment]
Legit

**Comment by orta** [comment]
I'm not sure, TBH I thought [this was a safe assumption](https://github.com/CocoaPods/cocoapods-stats/blob/master/lib/cocoapods_plugin.rb#L22-L25) on the CP API for checking for the existence of a spec repo, is it not?

**Comment by segiddins** [comment]
Ah you know what, it might be a bug in the `SourcesManager`. It should return an empty array for `master` if that repo hasn't been set up.
