### ISSUE TITLE
undefined method `has_key?' for nil:NilClass

### ISSUE THREAD

**Issue by AnthonyMDev** [CocoaPods/CocoaPods#4967]
### Command

```
/usr/local/bin/pod update
```

### Stack

```
   CocoaPods : 0.39.0
        Ruby : ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
    RubyGems : 2.4.5
        Host : Mac OS X 10.11.3 (15D21)
       Xcode : 7.2.1 (7C1002)
         Git : git version 2.5.4 (Apple Git-61)
Ruby lib dir : /usr/local/Cellar/ruby/2.2.2/lib
Repositories : my-private-cocoapods - [PRIVATE REPO URL REDACTED] @ 136dccbe4a4f04a72b182aef5476130d2a0f4e35
               master - https://github.com/CocoaPods/Specs.git @ 4814a3af5cdd7c17176c4204a9c351a0b0e6ae55
               Zorts - https://bitbucket.org/app-order/zorts-private-spec-repo.git @ 0226e051a820aa6ebe7ec488034653ec1be6a581
```

### Plugins

```
cocoapods-deintegrate : 0.2.1
cocoapods-links       : 0.2.0
cocoapods-plugins     : 0.4.2
cocoapods-search      : 0.1.0
cocoapods-stats       : 0.6.2
cocoapods-trunk       : 0.6.4
cocoapods-try         : 0.5.1
```

### Podfile

```ruby
platform :ios, "8.0"

inhibit_all_warnings!

source [PRIVATE REPO URL REDACTED]
source 'https://github.com/CocoaPods/Specs.git'

def import_pods
  pod 'AFNetworkActivityLogger', '~> 2.0'
  pod 'AOReportAdapter/Core', '~> 1.0'
  pod 'AOReportAdapter/Calendar', '~> 1.0'
  pod 'AOReportLoginController', '~> 0.2'
  pod 'AOThemeManager', '~> 0.4'
  pod 'MMDrawerController', '~> 0.5.7'  
end

target "AOFieldOfficer" do
  import_pods
end

target "AOFieldOfficerTests" do
  import_pods
  pod 'AOTestCase', '~> 1.0'
  pod 'Expecta', '~> 0.3'
  pod 'OCMock', '~> 3.0'
end
```

### Error

```
NoMethodError - undefined method `has_key?' for nil:NilClass
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-links-0.2.0/lib/pod/lockfile.rb:185:in `block in merge_hashes'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-links-0.2.0/lib/pod/lockfile.rb:181:in `each'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-links-0.2.0/lib/pod/lockfile.rb:181:in `merge_hashes'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-links-0.2.0/lib/pod/lockfile.rb:99:in `to_link_hash'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-links-0.2.0/lib/pod/lockfile.rb:53:in `to_link_yaml'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-links-0.2.0/lib/pod/lockfile.rb:32:in `write_to_disk'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:724:in `block in write_lockfiles'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:140:in `message'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:723:in `write_lockfiles'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:161:in `block in generate_pods_project'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:153:in `generate_pods_project'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:111:in `install!'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:156:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by segiddins** [comment]
This looks to be a bug in cocoapods-links

**Comment by AnthonyMDev** [comment]
Deleting my `Podfile.lock` and then running `pod update` worked fine.

Here is the contents of the lock file I removed.

```
PODS:
  - AFAmazonS3Client (3.0.0-amdev):
    - AFNetworking (~> 2.0)
  - AFNetworkActivityLogger (2.0.4):
    - AFNetworking/NSURLConnection (~> 2.0)
    - AFNetworking/NSURLSession (~> 2.0)
  - AFNetworking (2.6.3):
    - AFNetworking/NSURLConnection (= 2.6.3)
    - AFNetworking/NSURLSession (= 2.6.3)
    - AFNetworking/Reachability (= 2.6.3)
    - AFNetworking/Security (= 2.6.3)
    - AFNetworking/Serialization (= 2.6.3)
    - AFNetworking/UIKit (= 2.6.3)
  - AFNetworking+ImageActivityIndicator (1.0.2):
    - AFNetworking (~> 2.0)
  - AFNetworking/NSURLConnection (2.6.3):
    - AFNetworking/Reachability
    - AFNetworking/Security
    - AFNetworking/Serialization
  - AFNetworking/NSURLSession (2.6.3):
    - AFNetworking/Reachability
    - AFNetworking/Security
    - AFNetworking/Serialization
  - AFNetworking/Reachability (2.6.3)
  - AFNetworking/Security (2.6.3)
  - AFNetworking/Serialization (2.6.3)
  - AFNetworking/UIKit (2.6.3):
    - AFNetworking/NSURLConnection
    - AFNetworking/NSURLSession
  - ALLabel (2.0.0)
  - AMPullToRefresh (1.0.0)
  - AMRefreshingTableViewController (1.0.0):
    - AMPullToRefresh (~> 1.0)
    - AutoLayoutCells (~> 0.6)
    - MBProgressHUD (~> 0.8)
    - UIScrollView-InfiniteScroll (~> 0.2)
  - AOBaseControllers (2.1.0)
  - AOInputAccessoryToolbar (2.0.3)
  - AOPhotoPageViewController (1.2.2):
    - AOPhotoPageViewController/AOPhotoPageViewController (= 1.2.2)
    - AOPhotoPageViewController/AOPhotoPreviewPageViewController (= 1.2.2)
  - AOPhotoPageViewController/AOPhotoPageViewController (1.2.2):
    - AFNetworking+ImageActivityIndicator (~> 1.0)
    - Image+Bundle+Name (~> 0.1.0)
  - AOPhotoPageViewController/AOPhotoPreviewPageViewController (1.2.2):
    - AOPhotoPageViewController/AOPhotoPageViewController
  - AOPickerTextField (2.0.1):
    - AOInputAccessoryToolbar (~> 2.0)
  - AOPullToRefresh (0.2.0)
  - AOReportAdapter/Calendar (0.13.5):
    - AOReportAdapter/Core
    - AOReportCalendar (~> 0.2)
  - AOReportAdapter/Core (0.13.5):
    - AFAmazonS3Client (~> 3.0-amdev)
    - AMRefreshingTableViewController (~> 1.0)
    - AOReportControllers (~> 0.5)
    - AOReportModels (~> 0.5)
    - AOReportNavigationController (~> 0.3)
    - AOReportNetworking (~> 0.11)
    - AOReportUploadTaskList (~> 0.1)
    - AOThemeManager (~> 0.4)
    - AOValidation (~> 0.3)
    - AOValidationProtocol (~> 1.0)
    - MBProgressHUD+AOTapToCancel (~> 1.0)
  - AOReportCalendar (0.2.3):
    - AOBaseControllers (~> 2.0)
    - AOInputAccessoryToolbar (~> 2.0)
    - AutoLayoutCells (~> 0.6)
    - MBProgressHUD+AOTapToCancel (~> 1.0)
    - UIViewController+AOPinToLayout (~> 0.1)
  - AOReportControllers (0.5.0):
    - ALLabel (~> 2.0)
    - AOBaseControllers (~> 2.0)
    - AOInputAccessoryToolbar (~> 2.0)
    - AOPhotoPageViewController (~> 1.0)
    - AOPickerTextField (~> 2.0)
    - AOThemeManager (~> 0.4)
    - AOValidation (~> 0.3)
    - AOValidationProtocol (~> 1.0)
    - AutoLayoutCells (~> 0.6)
    - AutoLayoutTextViews (~> 1.1)
    - Image+Bundle+Name (~> 0.1)
    - MBProgressHUD+AOTapToCancel (~> 1.0)
    - SignatureView (~> 1.0)
    - TPKeyboardAvoiding (~> 1.2)
    - UIImage+ColorPlaceholder (~> 1.0)
    - UIImage-Resize (~> 1.0)
    - UIView+AORefreshFont (~> 1.0)
    - UIViewController+AOPinToLayout (~> 0.1)
  - AOReportLoginController (0.3.3):
    - AOBaseControllers (~> 2.0)
    - MBProgressHUD+AOTapToCancel (~> 1.0)
    - TPKeyboardAvoiding (~> 1.2)
    - UIViewController+AOPinToLayout (~> 0.1)
  - AOReportModels (0.5.9):
    - AOReportNetworking (~> 0.8)
    - UICKeyChainStore (~> 1.0)
    - UIColor+Additions (~> 1.0)
    - XMLDictionary (~> 1.4)
  - AOReportNavigationController (0.3.3):
    - AOReportControllers (~> 0.4)
    - AOReportModels (~> 0.5)
  - AOReportNetworking (0.11.0):
    - AFAmazonS3Client (~> 3.0-amdev)
    - AFNetworking (~> 2.5)
    - NSString-UrlEncode (~> 1.1)
    - XMLDictionary (~> 1.4)
  - AOReportUploadTaskList (0.1.3):
    - AOBaseControllers (~> 2.0)
    - AOPullToRefresh (~> 0.2)
    - AutoLayoutCells (~> 0.6)
    - UIView+AORefreshFont (~> 1.0)
  - AOTestCase (1.0.3)
  - AOThemeManager (0.6.0):
    - HexColors (~> 2.3)
  - AOValidation (0.3.2)
  - AOValidationProtocol (1.0.1)
  - AutoLayoutCells (0.9.0):
    - AutoLayoutCells/SharedCategories (= 0.9.0)
    - AutoLayoutCells/TableViewCells (= 0.9.0)
  - AutoLayoutCells/SharedCategories (0.9.0):
    - UIImageView+ALActivityIndicatorView (~> 1.0)
  - AutoLayoutCells/TableViewCells (0.9.0):
    - ALLabel (~> 2.0)
    - AutoLayoutCells/SharedCategories
    - AutoLayoutTextViews (~> 1.1)
  - AutoLayoutTextViews (1.2.3)
  - Expecta (0.4.2)
  - HexColors (2.3.0)
  - Image+Bundle+Name (0.1.1)
  - MBProgressHUD (0.9.2)
  - MBProgressHUD+AOTapToCancel (1.0.0):
    - MBProgressHUD (~> 0.9)
  - MMDrawerController (0.5.7):
    - MMDrawerController/Core (= 0.5.7)
    - MMDrawerController/MMDrawerBarButtonItem (= 0.5.7)
    - MMDrawerController/MMDrawerVisualStates (= 0.5.7)
    - MMDrawerController/Subclass (= 0.5.7)
  - MMDrawerController/Core (0.5.7)
  - MMDrawerController/MMDrawerBarButtonItem (0.5.7):
    - MMDrawerController/Core
  - MMDrawerController/MMDrawerVisualStates (0.5.7):
    - MMDrawerController/Core
  - MMDrawerController/Subclass (0.5.7):
    - MMDrawerController/Core
  - NSString-UrlEncode (1.2.0)
  - OCMock (3.2.2)
  - SignatureView (1.1.0)
  - TPKeyboardAvoiding (1.2.11)
  - UICKeyChainStore (1.1.1)
  - UIColor+Additions (1.0.1)
  - UIImage+ColorPlaceholder (1.0.0)
  - UIImage-Resize (1.0.1)
  - UIImageView+ALActivityIndicatorView (1.0.0)
  - UIScrollView-InfiniteScroll (0.7.3)
  - UIView+AORefreshFont (1.0.2)
  - UIViewController+AOPinToLayout (0.1.0)
  - XMLDictionary (1.4)

DEPENDENCIES:
  - AFNetworkActivityLogger (~> 2.0)
  - AOReportAdapter/Calendar (from `/Users/Anthony/Documents/AORepos/AOReportAdapter`)
  - AOReportAdapter/Core (from `/Users/Anthony/Documents/AORepos/AOReportAdapter`)
  - AOReportControllers (from `/Users/Anthony/Documents/AORepos/AOReportControllers`)
  - AOReportLoginController (~> 0.2)
  - AOReportModels (from `/Users/Anthony/Documents/AORepos/AOReportModels`)
  - AOReportNetworking (from `/Users/Anthony/Documents/AORepos/AOReportNetworking`)
  - AOTestCase (~> 1.0)
  - AOThemeManager (~> 0.4)
  - Expecta (~> 0.3)
  - MMDrawerController (~> 0.5.7)
  - OCMock (~> 3.0)

EXTERNAL SOURCES:
  AOReportAdapter:
    :path: "/Users/Anthony/Documents/AORepos/AOReportAdapter"

CHECKOUT OPTIONS: 

SPEC CHECKSUMS:
  AFAmazonS3Client: 0c49068fb20497cbb3325e3f2379bca3e34ab997
  AFNetworkActivityLogger: 121486778117d53b3ab1c61d264b88081d0c3eee
  AFNetworking: cb8d14a848e831097108418f5d49217339d4eb60
  AFNetworking+ImageActivityIndicator: 2d1a65e082909f6c5f0e8af0ae810e1118e5f21c
  ALLabel: 0f527f4f5445f4b9fac4d78bf28655f88908bd93
  AMPullToRefresh: 40ca9c74acfcbcddb396e5c3ddef50aa3ad13f4b
  AMRefreshingTableViewController: 8b95a5b89bb708816000acfb7aebb284382e581b
  AOBaseControllers: 9f18d9bc592e524153fb42e1a9e03f6b389bf449
  AOInputAccessoryToolbar: a7f6f78766ae4051e351bcb442bb66b245d254da
  AOPhotoPageViewController: ce1a0e1f1ddc1ca5efb23950850d37e25f17d7f7
  AOPickerTextField: 238cd988b54f2138a8dcea9010fdee79ed4e5c65
  AOPullToRefresh: de4f33da07eb70bcc33aa92906488a48a036e925
  AOReportAdapter: a74a6a504a45c6bbe07398692b47820327846564
  AOReportCalendar: cf6e67cc06bac10b7b941d9423162517b752b234
  AOReportControllers: 96b7046edce7234907a2902c9bd567d7424e17d7
  AOReportLoginController: 6c9143aa40af424ab4c733140536d925969a5b0a
  AOReportModels: c1b6ad36ab293980f968b139b2f31fe8455951b1
  AOReportNavigationController: bde5cce0d3412da542e6ea5f7a4b1370c744fc20
  AOReportNetworking: dd221ed16d417de10eb0fc511e7d3215178d200f
  AOReportUploadTaskList: 4e19b210313f1cda50e4ebd8baac6902198cad29
  AOTestCase: 8325e06da1193b74a8a21d97627f759c6b877347
  AOThemeManager: 688d36c5b54bfdb6b8b79a05f0c5b4271b111bd7
  AOValidation: 2b770fcc5fc37ba4bf0e7f4a502507fec215d53a
  AOValidationProtocol: aa0f6ffa79acfe2adb1d232f727588d97290fd5e
  AutoLayoutCells: bc22da5fc3d6a69cc92a8331149baf45537d760b
  AutoLayoutTextViews: 50d76d8938f263794e3344ee6876001f806c7cda
  Expecta: 78b4e8b0c8291fa4524d7f74016b6065c2e391ec
  HexColors: 6ad3947c3447a055a3aa8efa859def096351fe5f
  Image+Bundle+Name: 3cd7187fee2a293248b3848336b02d585a81104b
  MBProgressHUD: 1569cf7ace17a8bac47aabfbb8580a49690386d1
  MBProgressHUD+AOTapToCancel: 61bf1323491ab16787090966a878bbcb4ed37410
  MMDrawerController: 7a4cf8e25596bf2434e03ce50d22a8608ddee6a1
  NSString-UrlEncode: 771d85f86676c20209060005d26f0230e11e3b1c
  OCMock: 18c9b7e67d4c2770e95bb77a9cc1ae0c91fe3835
  SignatureView: 23bb085add66110062decbfa899ed93d111b76e5
  TPKeyboardAvoiding: e5ce146b313de063957bfa75a13f1e9b0ff18ab7
  UICKeyChainStore: 891bcd2fe687c92db8e648cba035c4e662ffa43e
  UIColor+Additions: fbfe003aec113c03daa14d1e6bed8b4317546856
  UIImage+ColorPlaceholder: 480e381329471ef7912246ced8cf1e51ff275906
  UIImage-Resize: fa776860f10e6900bbaf53a73e494bdceaaccc77
  UIImageView+ALActivityIndicatorView: f38f2c19ed2927e0b359201c143f25628ce30711
  UIScrollView-InfiniteScroll: b6c7d6d155dca7f9c5dd43813ecffeb301b3d50c
  UIView+AORefreshFont: 2baccb00af37a89c6d6bf6d7055e3c3281de8e33
  UIViewController+AOPinToLayout: c465a527528400b66fc9c986f6fb83d08107d2e5
  XMLDictionary: f9f51601ba76678b594ab485f2b00ec1fed23724

COCOAPODS: 0.39.0
```

**Comment by AnthonyMDev** [comment]
@segiddins Okay, if you think it's a cocoapods-links bug, then you can close this. I've got it working for myself now. Just wanted to make you guys aware of the issue.
