### ISSUE TITLE
Get `write_plist' for Xcodeproj:Module when using acknowledgments plugin

### ISSUE THREAD

**Issue by rist** [CocoaPods/CocoaPods#4991]
### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?
Tried to add acknowledgments plugin

* What did you expect to happen?

* What happened instead?
Command aborted with ``NoMethodError - undefined method `write_plist' for Xcodeproj:Module``

### Stack

```
   CocoaPods : 1.0.0.beta.4
        Ruby : ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]
    RubyGems : 2.0.14
        Host : Mac OS X 10.11.3 (15D21)
       Xcode : 7.2.1 (7C1002)
         Git : git version 2.5.4 (Apple Git-61)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 37c242772e47165074deea501be14254c7e640a6
```

### Plugins

```
cocoapods-acknowledgements : 1.0.0
cocoapods-deintegrate      : 1.0.0.beta.1
cocoapods-plugins          : 1.0.0.beta.1
cocoapods-search           : 1.0.0.beta.1
cocoapods-stats            : 1.0.0.beta.3
cocoapods-trunk            : 1.0.0.beta.2
cocoapods-try              : 1.0.0.beta.2
```

### Podfile

```ruby
platform :ios, '7.1'
plugin 'cocoapods-acknowledgements', :settings_bundle => true

inhibit_all_warnings!

# networking
pod 'AFNetworkActivityLogger'
pod 'AFNetworking', '~> 2.5'

# core
pod 'BlocksKit'
pod 'FXNotifications', '~> 1.1'
pod 'UIDeviceIdentifier', '~> 1.0.1'
pod 'MAKVONotificationCenter', '~> 0.0.2'
pod 'UICKeyChainStore', '~> 2.1'
pod 'Mantle', '~> 1.5'
pod 'libextobjc', '~> 0.4'
pod 'GVUserDefaults', '~> 1.0.0'
pod 'BlocksKit'
pod 'DTTJailbreakDetection'

# ui
pod 'PSTAlertController', '~> 1.0'  # needed for iOS7 support
pod 'OpenInGoogleMaps'
pod 'UIViewController+KeyboardAnimation'
pod 'UIViewPlusPosition'
pod 'JGProgressHUD', '~> 1.3'
pod 'ColorUtils', '~> 1.1'
pod 'UIImage-Resize', '~> 1.0'
pod 'SDWebImage', '~> 3.7.0'
pod 'IRLSize'

target 'XXXXX Internal' do
    pod 'OHHTTPStubs', '~> 4.7.0'
end

target 'XXXXX Unit Tests' do
	inherit! :search_paths
    pod 'OHHTTPStubs', '~> 4.7.0'
	pod 'Expecta', :inhibit_warnings => true
end

target 'XXXXX Health Tests' do
	inherit! :search_paths
    pod 'Expecta', :inhibit_warnings => true
end
```

### Error

```
NoMethodError - undefined method `write_plist' for Xcodeproj:Module
/Library/Ruby/Gems/2.0.0/gems/cocoapods-acknowledgements-1.0.0/lib/cocoapods_acknowledgements.rb:6:in `save_metadata'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-acknowledgements-1.0.0/lib/cocoapods_acknowledgements.rb:64:in `block (4 levels) in <module:CocoaPodsAcknowledgements>'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-acknowledgements-1.0.0/lib/cocoapods_acknowledgements.rb:56:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-acknowledgements-1.0.0/lib/cocoapods_acknowledgements.rb:56:in `block (3 levels) in <module:CocoaPodsAcknowledgements>'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-acknowledgements-1.0.0/lib/cocoapods_acknowledgements.rb:53:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-acknowledgements-1.0.0/lib/cocoapods_acknowledgements.rb:53:in `block (2 levels) in <module:CocoaPodsAcknowledgements>'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.4/lib/cocoapods/user_interface.rb:63:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-acknowledgements-1.0.0/lib/cocoapods_acknowledgements.rb:46:in `block in <module:CocoaPodsAcknowledgements>'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.4/lib/cocoapods/hooks_manager.rb:109:in `call'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.4/lib/cocoapods/hooks_manager.rb:109:in `block (3 levels) in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.4/lib/cocoapods/user_interface.rb:144:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.4/lib/cocoapods/hooks_manager.rb:103:in `block (2 levels) in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.4/lib/cocoapods/hooks_manager.rb:101:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.4/lib/cocoapods/hooks_manager.rb:101:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.4/lib/cocoapods/user_interface.rb:144:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.4/lib/cocoapods/hooks_manager.rb:100:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.4/lib/cocoapods/installer.rb:466:in `run_plugins_post_install_hooks'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.4/lib/cocoapods/installer.rb:447:in `perform_post_install_actions'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.4/lib/cocoapods/installer.rb:116:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.4/lib/cocoapods/command/project.rb:67:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.4/lib/cocoapods/command/project.rb:97:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0.beta.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.4/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.4/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by segiddins** [comment]
@marcelofabri you'll want to update acknowledgements for the xcodeproj 1.0 api

**Comment by marcelofabri** [comment]
@segiddins https://github.com/CocoaPods/cocoapods-acknowledgements/pull/24 should fix the issue (we need a release though).

@rist Can you try using `master`? To do so, you should add this to your `Gemfile`:

```ruby
gem 'cocoapods-acknowledgements', :git => 'https://github.com/cocoapods/cocoapods-acknowledgements.git'
```

**Comment by rist** [comment]
@marcelofabri switching to master solved the problem - thanks
should I just close the issue or wait for a release?

**Comment by orta** [comment]
We've made a release :+1:
