### ISSUE TITLE
"undefined method `root' for nil:NilClass" error when using "pod install"

### ISSUE THREAD

**Issue by sn0w** [CocoaPods/CocoaPods#4998]
- [x] I've read and understood the [CONTRIBUTING guidelines](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md) and have done my best effort to follow (🌈 )

### Command

```
/usr/local/bin/pod install --verbose
```

### Report

* What did you do?
I executed `pod install --verbose`

* What did you expect to happen?
Cocoapods installs the dependencies

* What happened instead?
A stack-trace popped up

### Stack

```
   CocoaPods : 1.0.0.beta.5
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.3 (15D21)
       Xcode : 7.2.1 (7C1002)
         Git : git version 2.5.4 (Apple Git-61)
Ruby lib dir : /usr/local/Cellar/ruby/2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ f892a4e63b6b6d8adbcef919d312e9aeb09e5719
```

### Plugins

```
cocoapods-deintegrate : 1.0.0.beta.1
cocoapods-plugins     : 1.0.0.beta.1
cocoapods-search      : 1.0.0.beta.1
cocoapods-stats       : 1.0.0.beta.3
cocoapods-trunk       : 1.0.0.beta.2
cocoapods-try         : 1.0.0.beta.2
```

### Podfile

```ruby
platform :ios, '8.4'

target 'Example' do
end

target 'ExampleTests' do
end

pod 'powerdefines'
pod 'YYHRequest'
pod 'MBProgressHUD', '~> 0.9.1'
```

### Error
```
NoMethodError - undefined method `root' for nil:NilClass
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.0.0.beta.3/lib/xcodeproj/workspace.rb:148:in `to_s'
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.0.0.beta.3/lib/xcodeproj/workspace.rb:178:in `block in save_as'
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.0.0.beta.3/lib/xcodeproj/workspace.rb:177:in `open'
/usr/local/lib/ruby/gems/2.3.0/gems/xcodeproj-1.0.0.beta.3/lib/xcodeproj/workspace.rb:177:in `save_as'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.0.beta.5/lib/cocoapods/installer/user_project_integrator.rb:95:in `create_workspace'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.0.beta.5/lib/cocoapods/installer/user_project_integrator.rb:62:in `integrate!'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.0.beta.5/lib/cocoapods/installer.rb:741:in `block in integrate_user_project'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.0.beta.5/lib/cocoapods/user_interface.rb:63:in `section'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.0.beta.5/lib/cocoapods/installer.rb:738:in `integrate_user_project'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.0.beta.5/lib/cocoapods/installer.rb:115:in `install!'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.0.beta.5/lib/cocoapods/command/project.rb:67:in `run_install_with_update'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.0.beta.5/lib/cocoapods/command/project.rb:97:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/claide-1.0.0.beta.2/lib/claide/command.rb:312:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.0.beta.5/lib/cocoapods/command.rb:48:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.0.beta.5/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by orta** [comment]
can you see if this has been fixed by b5?

**Comment by sn0w** [comment]
Seems like it's fixed now.

\*closing\*

**Comment by rogerhu** [comment]
The issue is caused by a fresh checkout having an existing .xcworkspace dir without contents.xcworkspacedata.  I need to include the schemes so Travis will build but didn't include this file.

The code for Xcodeproj has the following logic:

https://github.com/CocoaPods/Xcodeproj/blob/68feabcf6cbfa51c9874e5a85750d4c1966ca3d4/lib/xcodeproj/workspace.rb#L43-L52
```
 if document.nil? || document.is_a?(REXML::Document)
        @document = document
```

The exception is triggered by assuming @document is not nil (https://github.com/CocoaPods/Xcodeproj/blob/68feabcf6cbfa51c9874e5a85750d4c1966ca3d4/lib/xcodeproj/workspace.rb#L63-L68):

```

    def self.new_from_xcworkspace(path)
      from_s(File.read(File.join(path, 'contents.xcworkspacedata')),
             File.expand_path(File.dirname(path)))
    rescue Errno::ENOENT
      new(nil)
    end
```

I think the solution is to instantate a document always but not sure why this logic is here.  Any thoughts?

**Comment by rogerhu** [comment]
Added a PR here -- https://github.com/CocoaPods/Xcodeproj/pull/366

**Comment by rogerhu** [comment]
In particular the new(nil) logic breaks xcodeproj

**Comment by codepushr** [comment]
Same problem here. Fresh checkout, pod install and this error.

**Comment by AlmogBaku** [comment]
I solved it by:
1. upgrading cocapods
2. remove the `xcworkspace` `Podfile.lock` `Pods/` and any other trail of previous installation

**Comment by onethread** [comment]
Getting the same issue. Tried clearing it all per AlmogBaku's comment, but that didn't work

```
   CocoaPods : 1.1.0.rc.3
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.6 (15G1004)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 8d31fc3f0fcc7a4c4b3d0e545491e7b44d9f53ad
```

**Comment by dominostars** [comment]
Same issue. Deleting pods not helping. This is happening after I tried removing a dependency from a local `.podspec`

**Comment by apfritts** [comment]
Howdy! I'm also running into the same issue. I'm using Swift 3 and a codegen'd Swagger pod.

```
NoMethodError - undefined method `dirname' for nil:NilClass
/Users/apfritts/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.1.1/lib/cocoapods/validator.rb:261:in `dot_swift_version'
/Users/apfritts/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.1.1/lib/cocoapods/validator.rb:145:in `failure_reason'
/Users/apfritts/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.1.1/lib/cocoapods/external_sources/abstract_external_source.rb:176:in `validate_podspec'
/Users/apfritts/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.1.1/lib/cocoapods/external_sources/abstract_external_source.rb:163:in `store_podspec'
/Users/apfritts/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.1.1/lib/cocoapods/external_sources/abstract_external_source.rb:119:in `block in pre_download'
/Users/apfritts/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:85:in `titled_section'
/Users/apfritts/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.1.1/lib/cocoapods/external_sources/abstract_external_source.rb:112:in `pre_download'
/Users/apfritts/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.1.1/lib/cocoapods/external_sources/downloader_source.rb:13:in `fetch'
/Users/apfritts/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:639:in `fetch_external_source'
/Users/apfritts/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:615:in `block (2 levels) in fetch_external_sources'
/Users/apfritts/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:614:in `each'
/Users/apfritts/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:614:in `block in fetch_external_sources'
/Users/apfritts/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/apfritts/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:613:in `fetch_external_sources'
/Users/apfritts/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:73:in `analyze'
/Users/apfritts/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:236:in `analyze'
/Users/apfritts/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:150:in `block in resolve_dependencies'
/Users/apfritts/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/apfritts/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:149:in `resolve_dependencies'
/Users/apfritts/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:110:in `install!'
/Users/apfritts/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.1.1/lib/cocoapods/command/install.rb:37:in `run'
/Users/apfritts/.rvm/gems/ruby-2.3.1/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Users/apfritts/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/Users/apfritts/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/Users/apfritts/.rvm/gems/ruby-2.3.1/bin/pod:23:in `load'
/Users/apfritts/.rvm/gems/ruby-2.3.1/bin/pod:23:in `<main>'
/Users/apfritts/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/Users/apfritts/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```
