### ISSUE TITLE
Ambly pod, to_ary - error

### ISSUE THREAD

**Issue by dotemacs** [CocoaPods/CocoaPods#5019]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did I do before creating this issue?

The error message, helpfully, advised me to search for the error in the existing issues using this URL:

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=undefined+method+%60to_ary%27+for+%23%3CPod%3A%3ASpecification+name%3D%22Ambly%22%3E%0ADid+you+mean%3F++to_query&type=Issues

Which I did, but no issues existed.

## What did you do?

> git clone https://github.com/mfikes/replete.git
> cd replete
> gem install cocoapods
> pod install

## What did you expected to happen?

I expected the `Ambly` pod to install.

## What happened instead?

The error below.

## What else did I try?

Installing the test version and seeing how that fares.

> $ gem install cocoapods --pre
> $ pod --version
> 1.0.0.beta.5
> $ pod install
Updating local specs repositories
Analyzing dependencies
[!] The dependency `Ambly (~> 0.6.0)` is not used in any concrete target.

## The error

This error is produced by the stable version of the cocopods: 0.39.0.

```
NoMethodError - undefined method `to_ary' for #<Pod::Specification name="Ambly">
Did you mean?  to_query
/Users/alex/.gem/ruby/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver/lazy_specification.rb:14:in `method_missing'
/Users/alex/.gem/ruby/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:64:in `flatten'
/Users/alex/.gem/ruby/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:64:in `block in resolve'
/Users/alex/.gem/ruby/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:63:in `tap'
/Users/alex/.gem/ruby/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:63:in `resolve'
/Users/alex/.gem/ruby/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:539:in `block in resolve_dependencies'
/Users/alex/.gem/ruby/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Users/alex/.gem/ruby/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:537:in `resolve_dependencies'
/Users/alex/.gem/ruby/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:70:in `analyze'
/Users/alex/.gem/ruby/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:213:in `analyze'
/Users/alex/.gem/ruby/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:136:in `block in resolve_dependencies'
/Users/alex/.gem/ruby/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Users/alex/.gem/ruby/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:135:in `resolve_dependencies'
/Users/alex/.gem/ruby/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:105:in `install!'
/Users/alex/.gem/ruby/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/alex/.gem/ruby/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:101:in `run'
/Users/alex/.gem/ruby/2.3.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Users/alex/.gem/ruby/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Users/alex/.gem/ruby/2.3.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/Users/alex/.gem/ruby/2.3.0/bin/pod:23:in `load'
/Users/alex/.gem/ruby/2.3.0/bin/pod:23:in `<main>'
```

## Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

pod "Ambly", "~> 0.6.0"
```

### Stack

```
   CocoaPods : 0.39.0
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin14]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.3 (15D21)
       Xcode : 7.1 (7B91b)
         Git : git version 2.7.0
Ruby lib dir : /Users/alex/.rubies/ruby-2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ ded090e831de766fa213aa42acc3c19540742f4a
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-search  : 0.1.0
cocoapods-stats   : 0.6.2
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.5.1
```

**Comment by orta** [comment]
This is a known bug with 0.39 and ruby 2.3.0, to fix either use and older version of ruby or the 1.0 betas #4689

**Comment by dotemacs** [comment]
Wasn't aware of it.

Maybe this could be mentioned in the error message?

Thanks.
