### ISSUE TITLE
Duplicate targets causes crash

### ISSUE THREAD

**Issue by FullMetalFist** [CocoaPods/CocoaPods#5029]
Sorry hit the button too early.

I accidentally copied & pasted my target in my Podfile causing CP to crash, I know the proble,m, but would be nice to have it fail elegantly if theres two targets with the same name

```ruby
target :PlayingWithTests do
  # your app dependencies
end

target :PlayingWithTests do
  pod 'Specta', '~> 1.0'
  pod 'Expecta',     '~> 1.0'   # expecta matchers
  # pod 'OCMock',      '~> 2.2'   # OCMock
  # pod 'OCHamcrest',  '~> 3.0'   # hamcrest matchers
  # pod 'OCMockito',   '~> 1.0'   # OCMock
  # pod 'LRMocky',     '~> 0.9'   # LRMocky
end
```
### Error

```
Errno::EEXIST - File exists @ dir_s_mkdir - /Users/mvilabrera/Developer/Practice/PlayingWithTests/Pods/Target Support Files/Pods-PlayingWithTests
/Users/mvilabrera/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/installer/target_installer.rb:90:in `mkdir'
/Users/mvilabrera/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/installer/target_installer.rb:90:in `mkdir'
/Users/mvilabrera/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-1.0.0.beta.1/lib/cocoapods/installer/target_installer.rb:90:in `create_support_files_dir'
```

**Comment by segiddins** [comment]
Please fill out the rest of the issue template, along with the version of CocoaPods you're using.

**Comment by segiddins** [comment]
The Podfile validator needs to check for duplicate target names in the same Xcode project. A PR implementing that would be greatly appreciated!
