### ISSUE TITLE
pod install crashes with --no-integrate

### ISSUE THREAD

**Issue by cjcaufield** [CocoaPods/CocoaPods#5032]
### Command

```
/usr/local/bin/pod install --no-integrate
```

### Report

* What did you do?

Ran pod install --no-integrate on a brand new project.

* What did you expect to happen?

The pod should have installed.

* What happened instead?

I got the included crash report.

### Stack

```
   CocoaPods : 0.39.0
        Ruby : ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]
    RubyGems : 2.0.14
        Host : Mac OS X 10.11.2 (15C50)
       Xcode : 7.2.1 (7C1002)
         Git : git version 2.5.4 (Apple Git-61)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 1e15ffc208fe96afa97f83d12845f765b21edb4c
               SGLKit - https://github.com/cjcaufield/SGLKit.git @ 43547966874f9fd333047335ed47d90c7f469843
```

### Plugins

```
cocoapods-deintegrate : 0.2.1
cocoapods-plugins     : 0.4.2
cocoapods-search      : 0.1.0
cocoapods-stats       : 0.6.2
cocoapods-trunk       : 0.6.4
cocoapods-try         : 0.5.1
```

### Podfile

```ruby
use_frameworks!

target 'FrameworkTest' do
  platform :osx, '10.9'
  pod 'OpenSSL', '~> 1.0'
end

target 'FrameworkTestTouch' do
  platform :ios, '9.0'
  pod 'OpenSSL', '~> 1.0'
end
```

### Error

```
NoMethodError - undefined method `name' for nil:NilClass
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:579:in `block (2 levels) in prepare_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:579:in `select'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:579:in `block in prepare_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:140:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:550:in `prepare_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:154:in `block in generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:153:in `generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:111:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by cjcaufield** [comment]
Here's a sample project: https://github.com/cjcaufield/FrameworkTest

Just run "pod install --no-integrate" to cause the error.

**Comment by neonichu** [comment]
You can work around this issue by specifying a platform at the top-level, not only for the individual targets. 

The error message for this could indeed be nicer, but since 1.0 doesn't have the implicit top-level target anymore, it is no longer relevant for future development.

**Comment by cjcaufield** [comment]
Thanks for your time, neonichu.  The fix you described worked.
