### ISSUE TITLE
Can't pod install on beta6, CFTypeRef error

### ISSUE THREAD

**Issue by mtitolo** [CocoaPods/CocoaPods#5037]
* [:rainbow:] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Ran `bundle exec pod install` with beta6

## What did you expected to happen?

I expected `pod install` to install pods

## What happened instead?

It threw an error.

### Stack

```
   CocoaPods : 1.0.0.beta.6
        Ruby : ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]
    RubyGems : 2.2.3
        Host : Mac OS X 10.11.3 (15D21)
       Xcode : 7.2 (7C68)
         Git : git version 2.5.4 (Apple Git-61)
Ruby lib dir : /Users/michele/.rvm/rubies/ruby-2.2.0/lib
Repositories :internal-pods - https://internal.specs.repo.git @ 2699cba8098040c5035571e898b1e183ba053f33
               internal - git@internal.specs.repo:repo/repo.git @ 0f9dc60bd6bece0c97141e0e59479b25ab89f39c
               master - https://github.com/CocoaPods/Specs.git @ cfeeee0d99543618038dd47badcbe167747ec853
```

### Plugins

```
cocoapods-deintegrate : 1.0.0.beta.1
cocoapods-plugins     : 1.0.0.beta.1
cocoapods-search      : 1.0.0.beta.1
cocoapods-stats       : 1.0.0.beta.3
cocoapods-trunk       : 1.0.0.beta.2
cocoapods-try         : 1.0.0.beta.3
```

### Podfile

```ruby
"Please run `pod install` with bundle exec instead." unless defined?(Bundler)
platform :ios, '8.0'

use_frameworks!

source 'https://internal.specs.repo.git'
source 'https://github.com/CocoaPods/Specs.git'


target 'MainApplication' do
   # removed internal pods
    pod 'MGSwipeTableCell', '~>1.4.3'
    pod 'DeepLinkKit', '~>1.1.0'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
            config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
            config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
            config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
        end
    end
end
```

### Error

```
TypeError - Unable to convert Ruby value `"DeepLinkKit"' into a CFTypeRef.
/Users/michele/.rvm/gems/ruby-2.2.0/gems/xcodeproj-1.0.0.beta.3/lib/xcodeproj/plist/ffi/core_foundation.rb:383:in `RubyValueToCFTypeRef'
/Users/michele/.rvm/gems/ruby-2.2.0/gems/xcodeproj-1.0.0.beta.3/lib/xcodeproj/plist/ffi/core_foundation.rb:402:in `block in RubyHashToCFDictionary'
/Users/michele/.rvm/gems/ruby-2.2.0/gems/xcodeproj-1.0.0.beta.3/lib/xcodeproj/plist/ffi/core_foundation.rb:400:in `each'
/Users/michele/.rvm/gems/ruby-2.2.0/gems/xcodeproj-1.0.0.beta.3/lib/xcodeproj/plist/ffi/core_foundation.rb:400:in `RubyHashToCFDictionary'
/Users/michele/.rvm/gems/ruby-2.2.0/gems/xcodeproj-1.0.0.beta.3/lib/xcodeproj/plist/ffi/core_foundation.rb:372:in `RubyValueToCFTypeRef'
/Users/michele/.rvm/gems/ruby-2.2.0/gems/xcodeproj-1.0.0.beta.3/lib/xcodeproj/plist/ffi/core_foundation.rb:402:in `block in RubyHashToCFDictionary'
/Users/michele/.rvm/gems/ruby-2.2.0/gems/xcodeproj-1.0.0.beta.3/lib/xcodeproj/plist/ffi/core_foundation.rb:400:in `each'
/Users/michele/.rvm/gems/ruby-2.2.0/gems/xcodeproj-1.0.0.beta.3/lib/xcodeproj/plist/ffi/core_foundation.rb:400:in `RubyHashToCFDictionary'
/Users/michele/.rvm/gems/ruby-2.2.0/gems/xcodeproj-1.0.0.beta.3/lib/xcodeproj/plist/ffi/core_foundation.rb:372:in `RubyValueToCFTypeRef'
/Users/michele/.rvm/gems/ruby-2.2.0/gems/xcodeproj-1.0.0.beta.3/lib/xcodeproj/plist/ffi/core_foundation.rb:402:in `block in RubyHashToCFDictionary'
/Users/michele/.rvm/gems/ruby-2.2.0/gems/xcodeproj-1.0.0.beta.3/lib/xcodeproj/plist/ffi/core_foundation.rb:400:in `each'
/Users/michele/.rvm/gems/ruby-2.2.0/gems/xcodeproj-1.0.0.beta.3/lib/xcodeproj/plist/ffi/core_foundation.rb:400:in `RubyHashToCFDictionary'
/Users/michele/.rvm/gems/ruby-2.2.0/gems/xcodeproj-1.0.0.beta.3/lib/xcodeproj/plist/ffi.rb:103:in `ruby_hash_write_xcode'
/Users/michele/.rvm/gems/ruby-2.2.0/gems/xcodeproj-1.0.0.beta.3/lib/xcodeproj/plist/ffi.rb:40:in `write_to_path'
/Users/michele/.rvm/gems/ruby-2.2.0/gems/xcodeproj-1.0.0.beta.3/lib/xcodeproj/plist.rb:46:in `write_to_path'
/Users/michele/.rvm/gems/ruby-2.2.0/gems/xcodeproj-1.0.0.beta.3/lib/xcodeproj/project.rb:332:in `save'
/Users/michele/.rvm/gems/ruby-2.2.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/installer.rb:694:in `block in write_pod_project'
/Users/michele/.rvm/gems/ruby-2.2.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/user_interface.rb:144:in `message'
/Users/michele/.rvm/gems/ruby-2.2.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/installer.rb:686:in `write_pod_project'
/Users/michele/.rvm/gems/ruby-2.2.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/installer.rb:173:in `block in generate_pods_project'
/Users/michele/.rvm/gems/ruby-2.2.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/user_interface.rb:63:in `section'
/Users/michele/.rvm/gems/ruby-2.2.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/installer.rb:167:in `generate_pods_project'
/Users/michele/.rvm/gems/ruby-2.2.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/installer.rb:119:in `install!'
/Users/michele/.rvm/gems/ruby-2.2.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/command/install.rb:37:in `run'
/Users/michele/.rvm/gems/ruby-2.2.0/gems/claide-1.0.0.beta.3/lib/claide/command.rb:334:in `run'
/Users/michele/.rvm/gems/ruby-2.2.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/command.rb:50:in `run'
/Users/michele/.rvm/gems/ruby-2.2.0/gems/cocoapods-1.0.0.beta.6/bin/pod:44:in `<top (required)>'
/Users/michele/.rvm/gems/ruby-2.2.0/bin/pod:23:in `load'
/Users/michele/.rvm/gems/ruby-2.2.0/bin/pod:23:in `<main>'
/Users/michele/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
/Users/michele/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by roma86** [comment]
Have same error

**Comment by cjwirth** [comment]
I was having this same exact error, with the same exact setup (except I use rbenv instead of rvm :stuck_out_tongue_winking_eye: )

I ended up being able to fix it by using Ruby 2.1.0.

**Comment by appplemac** [comment]
Getting same error locally on Ruby 2.2.0, no issues with 2.0.0-p648 or 2.3.0.

**Comment by segiddins** [comment]
I was unable to reproduce this on 2.2.4, I'll try installing 2.2.0, but my guess is going to be that the suggested fix is to use a newer ruby version, sorry.

**Comment by segiddins** [comment]
Yup, reproduced this on 2.2.0, but only intermittently ¯\_(ツ)_/¯. Best bet is to use 2.2.4, I guess.
