### ISSUE TITLE
React Native Video Core - Cocoapods issue

### ISSUE THREAD

**Issue by michaeljgilmore** [CocoaPods/CocoaPods#5060]
### Error

```
NoMethodError - undefined method `to_ary' for #<Pod::Specification name="UriParser-cpp">
Did you mean?  to_query
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.37.2/lib/cocoapods/resolver/lazy_specification.rb:14:in `method_missing'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.37.2/lib/cocoapods/resolver.rb:59:in `flatten'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.37.2/lib/cocoapods/resolver.rb:59:in `block in resolve'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.37.2/lib/cocoapods/resolver.rb:58:in `tap'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.37.2/lib/cocoapods/resolver.rb:58:in `resolve'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.37.2/lib/cocoapods/installer/analyzer.rb:440:in `block in resolve_dependencies'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.37.2/lib/cocoapods/user_interface.rb:59:in `section'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.37.2/lib/cocoapods/installer/analyzer.rb:438:in `resolve_dependencies'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.37.2/lib/cocoapods/installer/analyzer.rb:63:in `analyze'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.37.2/lib/cocoapods/installer.rb:196:in `analyze'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.37.2/lib/cocoapods/installer.rb:114:in `block in resolve_dependencies'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.37.2/lib/cocoapods/user_interface.rb:59:in `section'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.37.2/lib/cocoapods/installer.rb:113:in `resolve_dependencies'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.37.2/lib/cocoapods/installer.rb:93:in `install!'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.37.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.37.2/lib/cocoapods/command/project.rb:101:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/claide-0.8.2/lib/claide/command.rb:312:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.37.2/lib/cocoapods/command.rb:46:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.37.2/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=undefined+method+%60to_ary%27+for+%23%3CPod%3A%3ASpecification+name%3D%22UriParser-cpp%22%3E%0ADid+you+mean%3F++to_query&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

**Comment by orta** [comment]
0.39 has issues with Ruby 2.3.0, please use the search before raising issues, this has come up a lot. The solution is either using a different version of ruby, or using the 1.0 branches.
