### ISSUE TITLE
pod spec lint got an Error

### ISSUE THREAD

**Issue by HaloWang** [CocoaPods/CocoaPods#5084]
# Report

I got an Error when run `pod spec lint --verbose`

`ERROR | [iOS] unknown: Encountered an unknown error (File name too long ...........`

## What did I do?

`pod spec lint --verbose`

```
Last login: Fri Mar 25 10:43:39 on ttys000
cd /Users/WangCe/FangYuanObjC
➜  ~ cd /Users/WangCe/FangYuanObjC
➜  FangYuanObjC git:(master) pod spec lint --verbose      

    FangYuanObjC (0.0.6) - Analyzing on iOS 7.0 platform.
  Preparing

Analyzing dependencies

Fetching external sources
-> Fetching podspec for `FangYuanObjC` from `/Users/WangCe/FangYuanObjC/FangYuanObjC.podspec`

Resolving dependencies of 

Comparing resolved specification to the sandbox manifest
  A FangYuanObjC

Downloading dependencies

-> Installing FangYuanObjC (0.0.6)
 > Git download
 > Git download
     $ /usr/bin/git clone https://github.com/HaloWang/FangYuanObjC.git
     /var/folders/gc/2wsry8y94mq9bq44x3s66r580000gn/T/d20160325-1847-bg2ha0
     --single-branch --depth 1 --branch 0.0.6
     Cloning into '/var/folders/gc/2wsry8y94mq9bq44x3s66r580000gn/T/d20160325-1847-bg2ha0'...
     Note: checking out '05f0b4a7044df7342dca1b05454e8cb5f228b931'.
     
     You are in 'detached HEAD' state. You can look around, make experimental
     changes and commit them, and you can discard any commits you make in this
     state without impacting any branches by performing another checkout.
     
     If you want to create a new branch to retain commits you create, you may
     do so (now or later) by using -b with the checkout command again. Example:
     
       git checkout -b <new-branch-name>
     

[!] Error installing FangYuanObjC
 -> FangYuanObjC (0.0.6)
    - ERROR | [iOS] unknown: Encountered an unknown error (File name too long - /var/folders/gc/2wsry8y94mq9bq44x3s66r580000gn/T/d20160325-1847-bg2ha0/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/Assets.xcassets/AppIcon.appiconset/Contents.json) during validation.

Analyzed 1 podspec.

[!] The spec did not pass validation, due to 1 error.

/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/spec/lint.rb:77:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
➜  FangYuanObjC git:(master) 
```

## Podfile

```
Pod::Spec.new do |s|
  s.name         = "FangYuanObjC"
  s.version      = "0.0.6"
  s.summary      = "A lightweght layout tool written by Objective-C"
  s.homepage     = "https://github.com/HaloWang/FangYuanObjC"
  s.license      = { :type => "MIT", :file => "FILE_LICENSE" }
  s.author             = { "王策" => "634692517@qq.com" }
  s.platform     = :ios, "7.0"
  s.source       = { :git => "https://github.com/HaloWang/FangYuanObjC.git", :tag => "0.0.6" }
  s.source_files  = "FangYuanObjC/*.{h,m}"
  s.framework  = "UIKit"
  s.requires_arc = true
end
```

**Comment by HaloWang** [comment]
pod --version
0.39.0

**Comment by orta** [comment]
Interesting
`    - ERROR | [iOS] unknown: Encountered an unknown error (File name too long - /var/folders/gc/2wsry8y94mq9bq44x3s66r580000gn/T/d20160325-1847-bg2ha0/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/FangYuanObjCDemo/Assets.xcassets/AppIcon.appiconset/Contents.json)` during validation.


This is probably a due to this extra Podspec: https://github.com/HaloWang/FangYuanObjC/blob/master/FangYuanObjC/FangYuanObjC.podspec

Have you tried removing it and re-running the linter?

**Comment by HaloWang** [comment]
@orta I found a "FangYuanObjCDemo" folder loop in commit [https://github.com/HaloWang/FangYuanObjC/commit/edfb6c0700af97be98b5ac8427546f2588ee4dc7](url)
I don't know what happened
After I delete this "LOOP", error is gone 😂
