### ISSUE TITLE
Crash when running 'pod install' after upgrade from 0.x to 1.0.0.beta.6

### ISSUE THREAD

**Issue by dbaroncelli** [CocoaPods/CocoaPods#5111]
### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.0.0.beta.6
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.4 (15E65)
       Xcode : 7.3 (7D175)
         Git : git version 2.6.4 (Apple Git-63)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 372a75e76328d15e68617a3bcf89f7f3697f770a
```

### Plugins

```

```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!  # needed when using Swift


target 'Trenìt!' do
    
    pod 'Google/Analytics'
    pod 'GoogleIDFASupport'
    pod 'Google/AdMob'
    
    pod 'Fabric'
    pod 'Crashlytics'
    
    pod 'SQLite.swift', '~> 0.10.1'
    
end
```

### Error

```
LoadError - cannot load such file -- cocoapods_deintegrate
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/installer.rb:495:in `block in deintegrate_if_different_major_version'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/user_interface.rb:63:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/installer.rb:493:in `deintegrate_if_different_major_version'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/installer.rb:132:in `block in prepare'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/user_interface.rb:144:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/installer.rb:131:in `prepare'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/installer.rb:113:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/command/install.rb:37:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0.beta.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.6/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by Brett-Best** [comment]
@dbaroncelli it looks like it can't find Cocoapods Deintegrate.
Try running this in terminal `[sudo] gem install cocoapods-deintegrate --pre`.

**Comment by dbaroncelli** [comment]
Yes, it worked!!!
many thanks

**Comment by phlippieb** [comment]
If you don't want to live on the bleeding edge, I didn't need `--pre`.

**Comment by alexfeng** [comment]
### Command

```
/Users/mac/.rvm/rubies/ruby-2.3.0/bin/pod update --verbose --no-repo-update
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.2.1
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin16]
    RubyGems : 2.5.1
        Host : Mac OS X 10.12.4 (16E195)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /Users/mac/.rvm/rubies/ruby-2.3.0/lib
Repositories : artsy - https://github.com/artsy/Specs.git @ 5710c812b912e14f0f7acd6ab80adc8fc34e1185
               coding-cocoapods-specs - https://git.coding.net/CocoaPods/Specs.git @ ab3494b3a2ec1a03a1cb58e70aa6b0c7c3ae7b90
               master - https://github.com/CocoaPods/Specs.git @ f872ec90ba127e2ccc506a11701298749e593f3c
               taobao-baichuansdk-alibcspecs - http://repo.baichuan-ios.taobao.com/baichuanSDK/AliBCSpecs.git @ a4c62aea6b808cf492a246e6282c133e9ffb111f
               XBSpecs - https://github.com/alexfeng/XBSpecs.git @ caa56aff6ecb616ccc479731b476a603fee24e5c
```

### Plugins

```
cocoapods-trunk : 1.2.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

#use_frameworks!

target 'XBIMSDK_Example' do
  pod 'XBIMSDK', :path => '../'
  pod 'Reachability', '~> 3.2'
  pod 'Toast', '~> 3.0'
  pod 'XBDatas', '~> 0.1.2'
  pod 'AFNetworking', '~> 3.1.0'
  pod 'MJRefresh', '~> 3.1.12'
  pod 'IQKeyboardManager', '~> 4.0.9'
end


target 'XBIMSDK_Tests' do
    inherit! :search_paths
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
```

### Error

```
LoadError - cannot load such file -- cocoapods_deintegrate
/Users/mac/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
/Users/mac/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
/Users/mac/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.2.1/lib/cocoapods/installer/user_project_integrator.rb:120:in `block in integrate_user_targets'
/Users/mac/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.2.1/lib/cocoapods/config.rb:41:in `with_changes'
/Users/mac/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.2.1/lib/cocoapods/installer/user_project_integrator.rb:119:in `integrate_user_targets'
/Users/mac/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.2.1/lib/cocoapods/installer/user_project_integrator.rb:63:in `integrate!'
/Users/mac/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.2.1/lib/cocoapods/installer.rb:614:in `block in integrate_user_project'
/Users/mac/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.2.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/mac/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.2.1/lib/cocoapods/installer.rb:611:in `integrate_user_project'
/Users/mac/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.2.1/lib/cocoapods/installer.rb:117:in `install!'
/Users/mac/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.2.1/lib/cocoapods/command/update.rb:81:in `run'
/Users/mac/.rvm/gems/ruby-2.3.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Users/mac/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.2.1/lib/cocoapods/command.rb:52:in `run'
/Users/mac/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.2.1/bin/pod:55:in `<top (required)>'
/Users/mac/.rvm/rubies/ruby-2.3.0/bin/pod:23:in `load'
/Users/mac/.rvm/rubies/ruby-2.3.0/bin/pod:23:in `<main>'
/Users/mac/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/Users/mac/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```
