### ISSUE TITLE
NoMethodError - undefined method `to_ary' for #<Pod::Specification name="AFNetworking">

### ISSUE THREAD

**Issue by Jincong** [CocoaPods/CocoaPods#5119]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

> Run `pod install`

## What did you expected to happen?

> Install all pod dependencies correctly.

## What happened instead?

> ### Command

```
/Users/ZuoJincong/.rvm/rubies/ruby-2.3.0/bin/pod update
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 0.39.0
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.4 (15E65)
       Xcode : 7.3 (7D175)
         Git : git version 2.6.4 (Apple Git-63)
Ruby lib dir : /Users/ZuoJincong/.rvm/rubies/ruby-2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 3f03d07189ed423b1364f635f97ac5f2f18bac3c
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-search  : 0.1.0
cocoapods-stats   : 0.6.2
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.5.1
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, "7.0"

inhibit_all_warnings!

link_with 'GBA4iOS', 'GBA4iOS-Simulator'

pod 'RSTWebViewController', :git => 'https://github.com/rileytestut/RSTWebViewController-Legacy.git'
pod "AFNetworking", "~> 2.4"
pod "PSPDFTextView", :git => 'https://github.com/steipete/PSPDFTextView.git'
pod "Dropbox-iOS-SDK", "~> 1.3.0"
pod "CrashlyticsFramework", "~> 2.1.0"
```

### Error

```
NoMethodError - undefined method `to_ary' for #<Pod::Specification name="AFNetworking">
Did you mean?  to_query
/Users/ZuoJincong/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/resolver/lazy_specification.rb:14:in `method_missing'
/Users/ZuoJincong/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:64:in `flatten'
/Users/ZuoJincong/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:64:in `block in resolve'
/Users/ZuoJincong/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:63:in `tap'
/Users/ZuoJincong/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:63:in `resolve'
/Users/ZuoJincong/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:539:in `block in resolve_dependencies'
/Users/ZuoJincong/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Users/ZuoJincong/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:537:in `resolve_dependencies'
/Users/ZuoJincong/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:70:in `analyze'
/Users/ZuoJincong/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:213:in `analyze'
/Users/ZuoJincong/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:136:in `block in resolve_dependencies'
/Users/ZuoJincong/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Users/ZuoJincong/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:135:in `resolve_dependencies'
/Users/ZuoJincong/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:105:in `install!'
/Users/ZuoJincong/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/ZuoJincong/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:156:in `run'
/Users/ZuoJincong/.rvm/gems/ruby-2.3.0@global/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Users/ZuoJincong/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Users/ZuoJincong/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/Users/ZuoJincong/.rvm/rubies/ruby-2.3.0/bin/pod:23:in `load'
/Users/ZuoJincong/.rvm/rubies/ruby-2.3.0/bin/pod:23:in `<main>'
/Users/ZuoJincong/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/Users/ZuoJincong/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=undefined+method+%60to_ary%27+for+%23%3CPod%3A%3ASpecification+name%3D%22AFNetworking%22%3E%0ADid+you+mean%3F++to_query&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

```

**Comment by orta** [comment]
Please use the search we have over 25 of these issues: #4391

**Comment by SimpLeYuchao** [comment]
why? and please give me a solution. thank you

**Comment by wanggang316** [comment]
I updated pod 1.0 bate solve this question.
