### ISSUE TITLE
Integrating client project and then Cocoapods Breaks

### ISSUE THREAD

**Issue by irahardianto** [CocoaPods/CocoaPods#5148]
Hi below is the error I encountered. 
It starts just when I execute command pod install when trying to install carbonkit was doing fine before.

what I have tried
- Removing Carbonkit and try pod install -> error
- Create new project pod init and pod install Carbonkit -> works
- Read this https://github.com/CocoaPods/CocoaPods/issues/4741 -> error
- Execute gem install cocoapods-stats --pre -> error
- Uninstall and install gem install cocoapods --pre -> error
- Install and use ruby 2.2.4 and reinstall cocoapods -> error

Help me please, I have no idea whats going on and im on tight deadline.
Thanks in advance really appreciate the help!

### Command

```
/Users/pagers/.rvm/gems/ruby-2.2.4/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 0.39.0
        Ruby : ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin15]
    RubyGems : 2.4.8
        Host : Mac OS X 10.11.4 (15E65)
       Xcode : 7.3 (7D175)
         Git : git version 2.6.4
Ruby lib dir : /Users/pagers/.rvm/rubies/ruby-2.2.4/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 95e368adeb09e0ed71214983a6c7d8458c9f7acb
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-search  : 0.1.0
cocoapods-stats   : 0.6.2
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.5.1
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'pagersapp' do
	pod 'Alamofire', '~> 3.0'
	pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
	pod 'Eureka', '~> 1.5'
	pod 'CarbonKit', '~>2.1'

end
```

### Error

```
NoMethodError - undefined method `files' for <PBXFileReference path=`Pods` UUID=`203C09CA1CAAEA4B000FA8C0`>:Xcodeproj::Project::Object::PBXFileReference
/Users/pagers/.rvm/gems/ruby-2.2.4/gems/cocoapods-0.39.0/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:91:in `set_target_xcconfig'
/Users/pagers/.rvm/gems/ruby-2.2.4/gems/cocoapods-0.39.0/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:25:in `block (2 levels) in integrate'
/Users/pagers/.rvm/gems/ruby-2.2.4/gems/cocoapods-0.39.0/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:23:in `each'
/Users/pagers/.rvm/gems/ruby-2.2.4/gems/cocoapods-0.39.0/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:23:in `block in integrate'
/Users/pagers/.rvm/gems/ruby-2.2.4/gems/cocoapods-0.39.0/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:22:in `each'
/Users/pagers/.rvm/gems/ruby-2.2.4/gems/cocoapods-0.39.0/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:22:in `integrate'
/Users/pagers/.rvm/gems/ruby-2.2.4/gems/cocoapods-0.39.0/lib/cocoapods/installer/user_project_integrator/target_integrator.rb:43:in `block in integrate!'
/Users/pagers/.rvm/gems/ruby-2.2.4/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Users/pagers/.rvm/gems/ruby-2.2.4/gems/cocoapods-0.39.0/lib/cocoapods/installer/user_project_integrator/target_integrator.rb:40:in `integrate!'
/Users/pagers/.rvm/gems/ruby-2.2.4/gems/cocoapods-0.39.0/lib/cocoapods/installer/user_project_integrator.rb:116:in `block in integrate_user_targets'
/Users/pagers/.rvm/gems/ruby-2.2.4/gems/cocoapods-0.39.0/lib/cocoapods/installer/user_project_integrator.rb:115:in `each'
/Users/pagers/.rvm/gems/ruby-2.2.4/gems/cocoapods-0.39.0/lib/cocoapods/installer/user_project_integrator.rb:115:in `integrate_user_targets'
/Users/pagers/.rvm/gems/ruby-2.2.4/gems/cocoapods-0.39.0/lib/cocoapods/installer/user_project_integrator.rb:63:in `integrate!'
/Users/pagers/.rvm/gems/ruby-2.2.4/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:750:in `block in integrate_user_project'
/Users/pagers/.rvm/gems/ruby-2.2.4/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Users/pagers/.rvm/gems/ruby-2.2.4/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:747:in `integrate_user_project'
/Users/pagers/.rvm/gems/ruby-2.2.4/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:112:in `install!'
/Users/pagers/.rvm/gems/ruby-2.2.4/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/pagers/.rvm/gems/ruby-2.2.4/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:101:in `run'
/Users/pagers/.rvm/gems/ruby-2.2.4/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Users/pagers/.rvm/gems/ruby-2.2.4/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Users/pagers/.rvm/gems/ruby-2.2.4/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/Users/pagers/.rvm/gems/ruby-2.2.4/bin/pod:23:in `load'
/Users/pagers/.rvm/gems/ruby-2.2.4/bin/pod:23:in `<main>'
/Users/pagers/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `eval'
/Users/pagers/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by irahardianto** [comment]
ah ya i forgot, before updating my ruby version was 2.2.1, same error though.

**Comment by segiddins** [comment]
Can you check and see if this particular error is fixed in the CocoaPods 1.0 betas? If not, sharing a project we could use to reproduce would be very helpful. Thanks!

**Comment by irahardianto** [comment]
Hi, I don't know what i did, but i tried to open the project from workspace then config paths on build setting and build phase, and everything works.

I did what you tell me do, upgrade CocoaPods to 1.0.0.beta.6, Im not quite sure whether update to beta or paths config or opening from workspace did the job, since before the config paths and workspace, my ruby was 2.2.1 and upgrading to beta doing no good, thank you very though, all is well now.

Here is my current environment version.
Ruby 2.2.4
CocoaPods 1.0.0.beta.6
and some suggestion always opens your project from workspace?

**Comment by segiddins** [comment]
Glad you got things working!
