### ISSUE TITLE
Pod try error 1.0.0 beta 7

### ISSUE THREAD

**Issue by taher-mosbah** [CocoaPods/CocoaPods#5159]
### Command

```
/usr/local/bin/pod try FBMemoryProfiler
```

### Report

* What did you do?
pod try FBMemoryProfiler

* What did you expect to happen?
Clone and launch Xcode project

* What happened instead?
Error

### Stack

```
   CocoaPods : 1.0.0.beta.7
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.4 (15E65)
       Xcode : 7.3 (7D175)
         Git : git version 2.8.1
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 2dd7635bb205dc34a26ed0de8e393c3016eeb2ed
```

### Plugins

```
cocoapods-deintegrate : 1.0.0.beta.1
cocoapods-plugins     : 1.0.0.beta.1
cocoapods-search      : 1.0.0.beta.2
cocoapods-stats       : 1.0.0.beta.4
cocoapods-trunk       : 1.0.0.beta.3
cocoapods-try         : 1.0.0.beta.3
```

### Error

```
NameError - uninitialized constant Pod::Command::Try::SourcesManager
/Library/Ruby/Gems/2.0.0/gems/cocoapods-try-1.0.0.beta.3/lib/pod/command/try.rb:201:in `block in update_specs_repos'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.7/lib/cocoapods/user_interface.rb:63:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-try-1.0.0.beta.3/lib/pod/command/try.rb:200:in `update_specs_repos'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-try-1.0.0.beta.3/lib/pod/command/try.rb:67:in `setup_spec_in_sandbox'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-try-1.0.0.beta.3/lib/pod/command/try.rb:35:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0.beta.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.7/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.7/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by segiddins** [comment]
Oops, looks like we also need to update `cocoapods-try`. Sorry!
