### ISSUE TITLE
1.0.0.b8 Shows Error Message when Offline and trying to update repos

### ISSUE THREAD

**Issue by orta** [CocoaPods/CocoaPods#5175]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

### Command

```
~/d/i/a/eigen (master) ⏛  bundle exec pod install --repo-update
Updating local specs repositories
```

### Report

* What did you do?

I was offline, and I requested a `repo update` in my `pod install`

* What did you expect to happen?

A message letting me know that it couldn't connect to the Specs server?

* What happened instead?

Stack Trace

### Stack

```
   CocoaPods : 1.0.0.beta.8
        Ruby : ruby 2.1.3p242 (2014-09-19 revision 47630) [x86_64-darwin14.0]
    RubyGems : 2.4.8
        Host : Mac OS X 10.11.4 (15E65)
       Xcode : 7.3 (7D175)
         Git : git version 2.6.4 (Apple Git-63)
Ruby lib dir : /Users/orta/.rvm/rubies/ruby-2.1.3/lib
Repositories : artsy - https://github.com/artsy/Specs.git @ f2334365b5b1a080efa4ded6425001010e5795dd
               master - https://github.com/CocoaPods/Specs.git @ fe02cf1b78c496cb6933d46b55c8dd4069efbe0d
```

### Plugins

```
cocoapods-deintegrate : 1.0.0.beta.1
cocoapods-keys        : 1.6.0
cocoapods-plugins     : 1.0.0.beta.1
cocoapods-search      : 1.0.0.beta.2
cocoapods-stats       : 1.0.0.beta.4
cocoapods-trunk       : 1.0.0.beta.4
cocoapods-try         : 1.0.0.beta.4
```

### Podfile

```ruby
[... it's irrelevant, but artsy/eigen ] 
```

### Error

```
SocketError - getaddrinfo: nodename nor servname provided, or not known
/Users/orta/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/net/http.rb:879:in `initialize'
/Users/orta/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/net/http.rb:879:in `open'
/Users/orta/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/net/http.rb:879:in `block in connect'
/Users/orta/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/timeout.rb:76:in `timeout'
/Users/orta/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/net/http.rb:878:in `connect'
/Users/orta/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
/Users/orta/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/net/http.rb:852:in `start'
/Users/orta/.rvm/gems/ruby-2.1.3/gems/nap-1.1.0/lib/rest/request.rb:183:in `perform'
/Users/orta/.rvm/gems/ruby-2.1.3/gems/nap-1.1.0/lib/rest/request.rb:192:in `perform'
/Users/orta/.rvm/gems/ruby-2.1.3/gems/nap-1.1.0/lib/rest.rb:24:in `get'
/Users/orta/.rvm/gems/ruby-2.1.3/gems/cocoapods-core-1.0.0.beta.8/lib/cocoapods-core/github.rb:99:in `modified_since_commit'
```

**Comment by segiddins** [comment]
@orta looks like you truncated the stack trace. @DanielTomlinson want to add some error handing to the `MasterSource` method that's making the network request? (Ideally if its an actually error just say theres an issue connecting to github?)

**Comment by orta** [comment]
Oops, yeah, amended
