### ISSUE TITLE
NoMethodError - undefined method `name' for nil:NilClass (version 1.0.0.rc.1)

### ISSUE THREAD

**Issue by vinceis1337** [CocoaPods/CocoaPods#5236]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Attempted to pod install using a vanilla file.

## What did you expected to happen?

Install pod dependencies.

## What happened instead?

```
NoMethodError - undefined method `name' for nil:NilClass
/Users/vliao/.rvm/gems/ruby-2.2.1/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/resolver.rb:459:in `block (2 levels) in spec_is_platform_compatible?'
/Users/vliao/.rvm/gems/ruby-2.2.1/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/resolver.rb:459:in `select'
/Users/vliao/.rvm/gems/ruby-2.2.1/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/resolver.rb:459:in `block in spec_is_platform_compatible?'
/Users/vliao/.rvm/gems/ruby-2.2.1/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/resolver.rb:458:in `each'
/Users/vliao/.rvm/gems/ruby-2.2.1/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/resolver.rb:458:in `all?'
/Users/vliao/.rvm/gems/ruby-2.2.1/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/resolver.rb:458:in `spec_is_platform_compatible?'
/Users/vliao/.rvm/gems/ruby-2.2.1/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/resolver.rb:179:in `requirement_satisfied_by?'
/Users/vliao/.rvm/gems/ruby-2.2.1/gems/molinillo-0.4.5/lib/molinillo/resolution.rb:131:in `block (2 levels) in <class:Resolution>'
/Users/vliao/.rvm/gems/ruby-2.2.1/gems/molinillo-0.4.5/lib/molinillo/resolution.rb:393:in `new_spec_satisfied?'
/Users/vliao/.rvm/gems/ruby-2.2.1/gems/molinillo-0.4.5/lib/molinillo/resolution.rb:381:in `attempt_to_activate_new_spec'
/Users/vliao/.rvm/gems/ruby-2.2.1/gems/molinillo-0.4.5/lib/molinillo/resolution.rb:320:in `attempt_to_activate'
/Users/vliao/.rvm/gems/ruby-2.2.1/gems/molinillo-0.4.5/lib/molinillo/resolution.rb:147:in `process_topmost_state'
/Users/vliao/.rvm/gems/ruby-2.2.1/gems/molinillo-0.4.5/lib/molinillo/resolution.rb:72:in `resolve'
/Users/vliao/.rvm/gems/ruby-2.2.1/gems/molinillo-0.4.5/lib/molinillo/resolver.rb:42:in `resolve'
/Users/vliao/.rvm/gems/ruby-2.2.1/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/resolver.rb:62:in `resolve'
/Users/vliao/.rvm/gems/ruby-2.2.1/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/installer/analyzer.rb:563:in `block in resolve_dependencies'
/Users/vliao/.rvm/gems/ruby-2.2.1/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/user_interface.rb:63:in `section'
/Users/vliao/.rvm/gems/ruby-2.2.1/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/installer/analyzer.rb:561:in `resolve_dependencies'
/Users/vliao/.rvm/gems/ruby-2.2.1/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/installer/analyzer.rb:76:in `analyze'
/Users/vliao/.rvm/gems/ruby-2.2.1/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/installer.rb:227:in `analyze'
/Users/vliao/.rvm/gems/ruby-2.2.1/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/installer.rb:151:in `block in resolve_dependencies'
/Users/vliao/.rvm/gems/ruby-2.2.1/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/user_interface.rb:63:in `section'
/Users/vliao/.rvm/gems/ruby-2.2.1/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/installer.rb:150:in `resolve_dependencies'
/Users/vliao/.rvm/gems/ruby-2.2.1/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/installer.rb:114:in `install!'
/Users/vliao/.rvm/gems/ruby-2.2.1/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/command/install.rb:37:in `run'
/Users/vliao/.rvm/gems/ruby-2.2.1/gems/claide-1.0.0.rc.1/lib/claide/command.rb:334:in `run'
/Users/vliao/.rvm/gems/ruby-2.2.1/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/command.rb:50:in `run'
/Users/vliao/.rvm/gems/ruby-2.2.1/gems/cocoapods-1.0.0.rc.1/bin/pod:55:in `<top (required)>'
/Users/vliao/.rvm/gems/ruby-2.2.1/bin/pod:23:in `load'
/Users/vliao/.rvm/gems/ruby-2.2.1/bin/pod:23:in `<main>'
/Users/vliao/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
/Users/vliao/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

## Podfile

```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift

source 'ssh://git@stash.rmn.com:7999/mbl/cocoa-podspecs.git'
source 'https://github.com/CocoaPods/Specs.git'


use_frameworks!
abstract_target 'Alpha' do
	pod 'ExamplePod/Base', :path => "../rmn-common-ios"
	target 'test1' do
		pod 'ExamplePod', :path => "../rmn-common-ios"
	end

	target 'test1 WatchKit 1 Extension' do

	end
end
```

**Comment by vinceis1337** [comment]
I wrote on the closed and related ticket https://github.com/CocoaPods/CocoaPods/issues/4814 that uncommenting the global platform from
```
# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
```

to

```
# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
```

solved this problem.
