### ISSUE TITLE
pod trunk me AND pod trunk push Error For help

### ISSUE THREAD

**Issue by swp-song** [CocoaPods/CocoaPods#5255]
――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod trunk me
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.0.0.rc.2
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.4 (15E65)
       Xcode : 7.3 (7D175)
         Git : git version 2.6.4 (Apple Git-63)
Ruby lib dir : /usr/local/Cellar/ruby/2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
HEAD
```

### Plugins

```
cocoapods-deintegrate : 1.0.0.rc.2
cocoapods-plugins     : 1.0.0.rc.1
cocoapods-search      : 1.0.0.rc.1
cocoapods-stats       : 1.0.0.rc.1
cocoapods-trunk       : 1.0.0.rc.1
cocoapods-try         : 1.0.0.rc.1
```

### Error

```
Netrc::Error - Permission bits for '/Users/songweiping/.netrc' should be 0600, but are 644
/usr/local/lib/ruby/gems/2.3.0/gems/netrc-0.7.8/lib/netrc.rb:33:in `check_permissions'
/usr/local/lib/ruby/gems/2.3.0/gems/netrc-0.7.8/lib/netrc.rb:40:in `read'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-trunk-1.0.0.rc.1/lib/pod/command/trunk.rb:90:in `netrc'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-trunk-1.0.0.rc.1/lib/pod/command/trunk.rb:95:in `token'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-trunk-1.0.0.rc.1/lib/pod/command/trunk/me.rb:16:in `validate!'
/usr/local/lib/ruby/gems/2.3.0/gems/claide-1.0.0.rc.1/lib/claide/command.rb:333:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.0.rc.2/lib/cocoapods/command.rb:50:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.0.rc.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by k0nserv** [comment]
Run `sudo chmod 600  /Users/songweiping/.netrc` and it should solve it

**Comment by swp-song** [comment]
@k0nserv Thank you

**Comment by gb-6k-house** [comment]
also i have this problem,but Run chmod 600 /Users/songweiping/.netrc can not solve it

**Comment by gb-6k-house** [comment]
/Users/niupark/Software/ruby/bin/pod trunk push
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]
    RubyGems : 2.4.8
        Host : Mac OS X 10.11.3 (15D21)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ eeef2b1c6d4ca333e88ce5cadf286cd2e07d7f81
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

### Error

```
Errno::EACCES - Permission denied - /Users/niupark/.netrc
/Library/Ruby/Gems/2.0.0/gems/netrc-0.7.8/lib/netrc.rb:49:in `read'
/Library/Ruby/Gems/2.0.0/gems/netrc-0.7.8/lib/netrc.rb:49:in `read'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-1.0.0/lib/pod/command/trunk.rb:90:in `netrc'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-1.0.0/lib/pod/command/trunk.rb:95:in `token'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-1.0.0/lib/pod/command/trunk/push.rb:47:in `validate!'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:333:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/bin/pod:55:in `<top (required)>'
/Users/niupark/Software/ruby/bin/pod:23:in `load'
/Users/niupark/Software/ruby/bin/pod:23:in `<main>'

**Comment by guillemf** [comment]
Same is happening to me

### Stack

```
   CocoaPods : 1.9.1
        Ruby : ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin19]
    RubyGems : 3.1.2
        Host : Mac OS X 10.15.4 (19E287)
       Xcode : 11.4 (11E146)
         Git : git version 2.24.1 (Apple Git-126)
Ruby lib dir : /Users/xxxx/.rvm/rubies/ruby-2.7.0/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ 276e53e9e31466e628172338e43b34b50f7b5bcb

               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Error

```
Netrc::Error - Permission bits for '/Users/xxxxx/.netrc' should be 0600, but are 640
/Users/xxxxx/.rvm/gems/ruby-2.7.0/gems/netrc-0.11.0/lib/netrc.rb:45:in `check_permissions'
/Users/xxxxx/.rvm/gems/ruby-2.7.0/gems/netrc-0.11.0/lib/netrc.rb:52:in `read'
/Users/xxxxx/.rvm/gems/ruby-2.7.0/gems/cocoapods-trunk-1.4.1/lib/pod/command/trunk.rb:106:in `netrc'
/Users/xxxxx/.rvm/gems/ruby-2.7.0/gems/cocoapods-trunk-1.4.1/lib/pod/command/trunk.rb:111:in `token'
/Users/xxxxx/.rvm/gems/ruby-2.7.0/gems/cocoapods-trunk-1.4.1/lib/pod/command/trunk/push.rb:56:in `validate!'
/Users/xxxxx/.rvm/gems/ruby-2.7.0/gems/claide-1.0.3/lib/claide/command.rb:333:in `run'
/Users/xxxxx/.rvm/gems/ruby-2.7.0/gems/cocoapods-1.9.1/lib/cocoapods/command.rb:52:in `run'
/Users/xxxxx/.rvm/gems/ruby-2.7.0/gems/cocoapods-1.9.1/bin/pod:55:in `<top (required)>'
/Users/xxxxx/.rvm/gems/ruby-2.7.0/bin/pod:23:in `load'
/Users/xxxxx/.rvm/gems/ruby-2.7.0/bin/pod:23:in `<main>'
/Users/xxxxx/.rvm/gems/ruby-2.7.0/bin/ruby_executable_hooks:24:in `eval'
/Users/xxxxx/.rvm/gems/ruby-2.7.0/bin/ruby_executable_hooks:24:in `<main>'
```
