### ISSUE TITLE
ENOENT generating pod project (version 1.0)

### ISSUE THREAD

**Issue by hjanuschka** [CocoaPods/CocoaPods#5279]
### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?
upgrade to cocoapods 1.0 (official)
removed `Pods/` `Podfile.lock`  - and the `.xcworkspace`
run: `pod install`

* What did you expect to happen?

working project

* What happened instead?

failed with error - see stack below

### Stack

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.4 (15E65)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.8.2
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : hjanuschka - https://github.com/hjanuschka/mypods.git @ f43c678b70ca82fa4f9652b8c550c8afdb9b20c9
               kmmpods - git@gitlab.krone.at:mobile/KMMPODS.git @ b92eb6893ce6a3b8983d331a3d1630114e330944
               master - https://github.com/CocoaPods/Specs.git @ 6a1ff287c165f876dd873fcb3c983768e3e0f333
               zi0p4tch0 - https://github.com/Zi0P4tch0/Specs.git @ 36c0ca3d50c412be5fa4d4f2fb6e127d129b8fac
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-packager    : 1.3.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/hjanuschka/mypods.git'
source 'git@gitlab.krone.at:mobile/KMMPODS.git'

use_frameworks!


platform :ios, "8.0"

target "fivexfive" do
    pod "kmmsologin"
    pod 'AFNetworking', :git => 'https://github.com/AFNetworking/AFNetworking.git', :branch => 'master'
    pod 'AcknowledgementsBundle'
    pod 'UIColor-HexString', :git=>'https://github.com/hjanuschka/UIColor-HexString.git'
    pod "CustomKINWebBrowser"
# pod 'Google/Analytics'
    pod 'GoogleAnalytics'
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
    pod 'ISRefreshControl', '~> 1.4.1'
    pod 'OneSignal'
    pod 'UIAlertView+Blocks', '~> 0.8'
    pod 'iRate', '~> 1.11'
    #pod 'PSUpdateApp', '~> 2.0'
    pod 'SDWebImage'
    pod 'UIActivityIndicator-for-SDWebImage'
    pod 'MWPhotoBrowser', :git => 'https://github.com/hjanuschka/MWPhotoBrowser.git', :branch => 'master'
    pod 'NSString-HYPContainsString', :git =>'https://github.com/hyperoslo/NSString-HYPContainsString.git'
    pod 'UITableView-NXEmptyView'
    pod 'Fabric'
    pod 'Crashlytics'
    #pod 'GBDeviceInfo'
    pod 'IQKeyboardManager'
    pod 'DAAppsViewController'
    pod 'EAIntroView'
    #pod 'AdTech-SDK'
    pod 'FXForms'
    pod 'TWSReleaseNotesView'
    #pod 'UIView+UIImageEffects'
    pod 'NSString-UrlEncode', :git => 'https://github.com/kevinrenskers/NSString-URLEncode.git'
    pod "SpinKit"
    pod "MRoundedButton", :git => "https://github.com/rohanaurora/MRoundedButton.git"
    pod 'REFrostedViewController'
    pod 'DCKeyValueObjectMapping'
    pod 'NSObject-ObjectMap'
    pod 'FXBlurView'
    pod 'LGPlaceholderView'
    pod "RMStepsController"

    pod 'UIActionSheet-Blocks'
    pod 'UIImage-ResizeMagick'
    pod 'DateTools'
    pod 'TTTAttributedLabel'
    pod 'FXNotifications'
    pod 'SimulatorRemoteNotifications'
    pod 'M13BadgeView'
    pod 'FLAnimatedImage'
    pod 'JVFloatLabeledTextField'
    pod 'PNChart'
    pod 'HCSStarRatingView'

    pod 'OEWA_Spring'
    pod 'AdTech-SDK'


end

#post_install do |installer_representation|
#    installer_representation.pods_project.build_configurations.each { |bc|
#      bc.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
#    }
#    installer_representation.pods_project.targets.each do |target|
#        target.build_configurations.each do |config|
#            if config.name != 'Release'
#                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'DEBUG=1']
#            end
#        end
#    end
#end
```

### Error

```
Errno::ENOENT - No such file or directory - /Users/hjanuschka/Desktop/CLOUD_DRIVE_OLD/FIVEXFIVE/FiveXFive/Pods/Target Support Files/Pods
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/project.rb:186:in `realpath'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/project.rb:186:in `realpath'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/project.rb:186:in `add_file_reference'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/installer/file_references_installer.rb:185:in `block (2 levels) in add_file_accessors_paths_to_pods_group'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/installer/file_references_installer.rb:183:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/installer/file_references_installer.rb:183:in `block in add_file_accessors_paths_to_pods_group'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/installer/file_references_installer.rb:178:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/installer/file_references_installer.rb:178:in `add_file_accessors_paths_to_pods_group'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/installer/file_references_installer.rb:106:in `block in add_resources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/user_interface.rb:144:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/installer/file_references_installer.rb:104:in `add_resources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/installer/file_references_installer.rb:40:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/installer.rb:609:in `install_file_references'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/installer.rb:169:in `block in generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/user_interface.rb:63:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/installer.rb:167:in `generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/installer.rb:119:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/command/install.rb:37:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'

**Comment by neonichu** [comment]
This seems to be an issue with the `AcknowledgementsBundle` pod, it contains a symlink ( see <https://github.com/rivera-ernesto/AcknowledgementsBundle/blob/master/Pods-acknowledgements.plist>) into `Target Support Files` on which `realpath` fails, because the target file doesn't exist, yet.

Considering that there's no implicit root target anymore, there'll never realistically be a `Target Support Files/Pods` directory with 1.0 anymore, so the `AcknowledgementsBundle` pod needs to be updated for 1.0 — you should probably report that upstream.

Generally, I'm unsure if we want to handle this case specially, e.g. add a file reference using the symlink, instead of the real path or have a more specialised error message.

**Comment by Coeur** [comment]
AcknowledgementsBundle deliberately ignored `pod lib lint` check, according to https://github.com/rivera-ernesto/AcknowledgementsBundle/pull/2:

> it seems that the pod does not pass the pod lib lint check since there is no Pods-acknowledgements.plist yet so the simlink is broken
> [...]
> Could push to CocoaPods by temporarily replacing the local plist sym link by a real plist file.

**Comment by neonichu** [comment]
That makes sense, lint will check if all `source_files` are actually available. So I think we can close this.

**Comment by hjanuschka** [comment]
thx that worked!

@neonichu  do you have tipp for me how can find out wich pod was the culprit? (mayber for other problems) - i already tried --verbose

**Comment by neonichu** [comment]
Not a great one, I actually added a `print` in `project.rb` to figure this one out :)
