### ISSUE TITLE
When I want to use pod papackage to make a static library  in cocoapods - 1.0.0,it has an error , but in cocoapods - 0.39.0 without error

### ISSUE THREAD

**Issue by KF5** [CocoaPods/CocoaPods#5305]
Usage of the constant `Pod::SourcesManager` is deprecated, use `Pod::Config.instance.sources_manager` instead (called from /Users/admin/.rvm/gems/ruby-2.0.0-p598@global/gems/cocoapods-packager-1.3.0/lib/cocoapods-packager/pod_utils.rb:73:in `spec_with_name')

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/admin/.rvm/gems/ruby-2.0.0-p598/bin/pod package SDK.podspec --force
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.0.0p598 (2014-11-13 revision 48408) [x86_64-darwin14.0.0]
    RubyGems : 2.6.4
        Host : Mac OS X 10.11.2 (15C50)
       Xcode : 7.3 (7D175)
         Git : git version 2.6.4 (Apple Git-63)
Ruby lib dir : /Users/admin/.rvm/rubies/ruby-2.0.0-p598/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ bd0d96bba465d6656a1abded73970d688756518d
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-packager    : 1.3.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

### Error

```
NoMethodError - undefined method `integrate_targets=' for #<Pod::Config:0x007f9af3a20f40>
/Users/admin/.rvm/gems/ruby-2.0.0-p598@global/gems/cocoapods-packager-1.3.0/lib/pod/command/package.rb:65:in `build_in_sandbox'
/Users/admin/.rvm/gems/ruby-2.0.0-p598@global/gems/cocoapods-packager-1.3.0/lib/pod/command/package.rb:84:in `block in build_package'
/Users/admin/.rvm/gems/ruby-2.0.0-p598@global/gems/cocoapods-packager-1.3.0/lib/pod/command/package.rb:83:in `each'
/Users/admin/.rvm/gems/ruby-2.0.0-p598@global/gems/cocoapods-packager-1.3.0/lib/pod/command/package.rb:83:in `build_package'
/Users/admin/.rvm/gems/ruby-2.0.0-p598@global/gems/cocoapods-packager-1.3.0/lib/pod/command/package.rb:56:in `run'
/Users/admin/.rvm/gems/ruby-2.0.0-p598@global/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Users/admin/.rvm/gems/ruby-2.0.0-p598@global/gems/cocoapods-1.0.0/lib/cocoapods/command.rb:50:in `run'
/Users/admin/.rvm/gems/ruby-2.0.0-p598@global/gems/cocoapods-1.0.0/bin/pod:55:in `<top (required)>'
/Users/admin/.rvm/gems/ruby-2.0.0-p598/bin/pod:23:in `load'
/Users/admin/.rvm/gems/ruby-2.0.0-p598/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

**Comment by segiddins** [comment]
This is a big with the packager, not CocoaPods itself.

**Comment by 342261733** [comment]
Do you know how to fix this?

**Comment by 342261733** [comment]
But I am in cocoapods - 0.39.0, there are the same error.  My cocoapods-packager -v 1.3.0, what's your version?

**Comment by leviyehonatan** [comment]
having same issue? any update?

**Comment by KF5** [comment]
My cocoapods-packager is also 1.3.0

**Comment by 342261733** [comment]
When my cocoapods-packager go back to verion 1.0.0 resolved this question.

**Comment by 342261733** [comment]
But  there is a error in 1.0.0 when packing. Now I update to 1.3.0 to fix the issue

**Comment by leviyehonatan** [comment]
1.3.0 of what ? cocoapods?!

**Comment by leviyehonatan** [comment]
how do i install the 1.0.0 version of cocoapods?

**Comment by 342261733** [comment]
Just use gem install.

**Comment by 342261733** [comment]
1.3.0 is cocoapods-packager.       cocoapods use 0.39.0
