### ISSUE TITLE
NameError - uninitialized constant CoreFoundation

### ISSUE THREAD

**Issue by tompson** [CocoaPods/CocoaPods#5311]
### Command

```
/Users/tom/.gem/ruby/2.0.0/bin/pod install
```

### Report

error when running `pod install`

### Stack

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.4 (15E65)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 1333dbedb25ef38c65c7e512d133f2287bab2051
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

### Podfile

```ruby
platform :ios, '7.1'

def shared_pods
  pod 'CocoaLumberjack'
  pod 'Lockbox'
  pod 'Reachability'
  pod 'ZipArchive', '~> 1.4.0'
  pod 'AFAmazonS3Manager'
  pod 'BBBadgeBarButtonItem'
end

target 'myapp' do
  shared_pods
end

```

### Error

```
NameError - uninitialized constant CoreFoundation
/Users/tom/.gem/ruby/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/sources_manager.rb:171:in `const_missing'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.0.0/lib/xcodeproj/plist/ffi/core_foundation.rb:271:in `ptr'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.0.0/lib/xcodeproj/plist/ffi/core_foundation.rb:73:in `RubyHashPropertyListRead'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.0.0/lib/xcodeproj/plist/ffi.rb:54:in `read_from_path'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.0.0/lib/xcodeproj/plist.rb:22:in `read_from_path'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.0.0/lib/xcodeproj/project.rb:200:in `initialize_from_file'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.0.0/lib/xcodeproj/project.rb:102:in `open'
/Users/tom/.gem/ruby/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/installer/analyzer.rb:695:in `block (2 levels) in inspect_targets_to_integrate'
/Users/tom/.gem/ruby/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/installer/analyzer.rb:694:in `each'
/Users/tom/.gem/ruby/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/installer/analyzer.rb:694:in `block in inspect_targets_to_integrate'
/Users/tom/.gem/ruby/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/user_interface.rb:63:in `section'
/Users/tom/.gem/ruby/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/installer/analyzer.rb:689:in `inspect_targets_to_integrate'
/Users/tom/.gem/ruby/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/installer/analyzer.rb:66:in `analyze'
/Users/tom/.gem/ruby/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/installer.rb:227:in `analyze'
/Users/tom/.gem/ruby/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/installer.rb:151:in `block in resolve_dependencies'
/Users/tom/.gem/ruby/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/user_interface.rb:63:in `section'
/Users/tom/.gem/ruby/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/installer.rb:150:in `resolve_dependencies'
/Users/tom/.gem/ruby/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/installer.rb:114:in `install!'
/Users/tom/.gem/ruby/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/command/install.rb:37:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Users/tom/.gem/ruby/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/command.rb:50:in `run'
/Users/tom/.gem/ruby/2.0.0/gems/cocoapods-1.0.0/bin/pod:55:in `<top (required)>'
/Users/tom/.gem/ruby/2.0.0/bin/pod:23:in `load'
/Users/tom/.gem/ruby/2.0.0/bin/pod:23:in `<main>'
```

**Comment by tompson** [comment]
caused by broken xcode project file

**Comment by junyixin** [comment]
After updating CocoaPods encounter the same problem

**Comment by norsez** [comment]
Hi @tompson just curious. How did you figure it was the broken xcode project file?

**Comment by vitaliiblazheiev** [comment]
how to fix this issue? I have the same issue after updating cocoapods to latest version 1.0.1 from 0.39.0

**Comment by segiddins** [comment]
@vitaliiblazheiev
This issue has been closed, please open up a new issue complete with all of the details requested in the issue template.

**Comment by nolanw** [comment]
This is an extremely unhelpful error message! Would appreciate reopening the issue to add a more clear error message.

**Comment by NickWarrior** [comment]
Maybe your project.pbxproj is destroyed.so you should check your project.pbxproj carefully. By Test.xcodeproj -->show Package contents -->project.pbxproj.
