### ISSUE TITLE
ArgumentError - invalid byte sequence in US-ASCII

### ISSUE THREAD

**Issue by ArturBaghdas** [CocoaPods/CocoaPods#5348]
/usr/local/bin/pod install --verbose
### Report
* What did you do?
* What did you expect to happen?
* What happened instead?

### Stack
   CocoaPods : 1.0.0
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3 (7D175)
         Git : git version 2.6.4 (Apple Git-63)
Ruby lib dir : /Users/sflpro/.rbenv/versions/2.3.0/lib
Repositories : artsy - https://github.com/Artsy/Specs.git @ f2334365b5b1a080efa4ded6425001010e5795dd
               master - https://github.com/CocoaPods/Specs.git @ 85076c42a9d0d612068d258a04a87e61cd4b215d

### Plugins

cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Artsy/Specs.git'

platform :ios, '8.0'

target 'Couch Coach' do

pod 'AFNetworking'
pod 'Mantle'
pod 'Fabric'
pod 'Crashlytics'
pod 'JSONKit-NoWarning'
pod 'AFNetworkActivityLogger'
pod 'SDWebImage'
pod 'MZFormSheetPresentationController'
pod 'AMWaveTransition'
pod 'SlackTextViewController'
pod 'TwitterKit'
pod 'FBSDKLoginKit'
pod 'Localytics'
pod 'Google/Analytics'

end
```

### Error

```
ArgumentError - invalid byte sequence in US-ASCII
/Users/sflpro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/xcodeproj-1.0.0/lib/xcodeproj/plist.rb:86:in `match'
/Users/sflpro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/xcodeproj-1.0.0/lib/xcodeproj/plist.rb:86:in `match'
/Users/sflpro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/xcodeproj-1.0.0/lib/xcodeproj/plist.rb:86:in `file_in_conflict?'
/Users/sflpro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/xcodeproj-1.0.0/lib/xcodeproj/plist.rb:19:in `read_from_path'
/Users/sflpro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/xcodeproj-1.0.0/lib/xcodeproj/project.rb:200:in `initialize_from_file'
/Users/sflpro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/xcodeproj-1.0.0/lib/xcodeproj/project.rb:102:in `open'
/Users/sflpro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.0/lib/cocoapods/installer/analyzer.rb:695:in `block (2 levels) in inspect_targets_to_integrate'
/Users/sflpro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.0/lib/cocoapods/installer/analyzer.rb:694:in `each'
/Users/sflpro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.0/lib/cocoapods/installer/analyzer.rb:694:in `block in inspect_targets_to_integrate'
/Users/sflpro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.0/lib/cocoapods/user_interface.rb:63:in `section'
/Users/sflpro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.0/lib/cocoapods/installer/analyzer.rb:689:in `inspect_targets_to_integrate'
/Users/sflpro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.0/lib/cocoapods/installer/analyzer.rb:66:in `analyze'
/Users/sflpro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.0/lib/cocoapods/installer.rb:227:in `analyze'
/Users/sflpro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.0/lib/cocoapods/installer.rb:151:in `block in resolve_dependencies'
/Users/sflpro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.0/lib/cocoapods/user_interface.rb:63:in `section'
/Users/sflpro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.0/lib/cocoapods/installer.rb:150:in `resolve_dependencies'
/Users/sflpro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.0/lib/cocoapods/installer.rb:114:in `install!'
/Users/sflpro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.0/lib/cocoapods/command/install.rb:37:in `run'
/Users/sflpro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Users/sflpro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.0/lib/cocoapods/command.rb:50:in `run'
/Users/sflpro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

**Comment by neonichu** [comment]
Could you please share the output of the `locale` command on your system and share your Xcode project file with us?

**Comment by ArturBaghdas** [comment]
Thanks for quick response 
![screen shot 2016-05-18 at 11 59 17 am](https://cloud.githubusercontent.com/assets/13787379/15351568/ef5d9f5a-1cf0-11e6-9d2e-383251d1a9e0.png)

**Comment by ArturBaghdas** [comment]
LANG="en_US.UTF-8" fixed the issue, thanks
