### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by miraclebg** [CocoaPods/CocoaPods#5353]
### Command

```
/usr/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 0.38.2
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.6.2
        Host : Mac OS X 10.11.5 (15F31a)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ c5ffbf685544ca7757a7b6fe679e7a4447a456ea
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-search  : 1.0.0.beta.1
cocoapods-stats   : 0.5.3
cocoapods-trunk   : 1.0.0.beta.2
cocoapods-try     : 0.4.5
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'SmallWorld' do

pod 'Firebase', '>= 2.5.0'
pod 'FirebaseUI', '~> 0.3'
pod 'FBSDKCoreKit'
pod 'FBSDKShareKit'
pod 'FBSDKLoginKit'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'ActionSheetPicker-3.0', '~> 2.0.4'
pod 'Google-Mobile-Ads-SDK'
pod 'Fabric'
pod 'Crashlytics'
pod 'TTTAttributedLabel'
pod 'APLSlideMenu'
pod 'TOActionSheet'
#pod 'TGCameraViewController'
pod 'IQActionSheetPickerView'
pod 'FXBlurView'
pod 'SDWebImage'
pod 'Rollout.io'
#pod 'CCBottomRefreshControl'
pod 'MRProgress'
pod 'AFNetworking', '~> 3.0'
pod 'CocoaLumberjack'
pod 'GoogleMaps'
pod 'CMMapLauncher'

end

target 'SmallWorldTests' do

end

target 'SmallWorldUITests' do

end
```

### Error

```
Errno::ENOENT - No such file or directory - /Users/mkovachev/sworkspace/small-world/Pods/GoogleAppUtilities/Frameworks/GoogleAppUtilities.framework/Headers
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/sandbox/file_accessor.rb:161:in `realpath'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/sandbox/file_accessor.rb:161:in `realpath'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/sandbox/file_accessor.rb:161:in `vendored_frameworks_headers_dir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:239:in `block in vendored_frameworks_header_mappings'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:238:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:238:in `vendored_frameworks_header_mappings'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:140:in `block (3 levels) in link_headers'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:117:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:117:in `block (2 levels) in link_headers'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:116:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:116:in `block in link_headers'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:140:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:115:in `link_headers'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:41:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:562:in `install_file_references'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:152:in `block in generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:150:in `generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:110:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
/usr/bin/pod:22:in `load'
/usr/bin/pod:22:in `<main>'
```

**Comment by miraclebg** [comment]
If i remove 'pod 'FirebaseUI', '~> 0.3'' all is ok.

**Comment by vinceis1337** [comment]
Have you tried upgrading to 0.39.0 or even 1.0.0?

**Comment by miraclebg** [comment]
@vinceis1337 Interesting... 

When i check with gem list --local i see that:

cocoapods (1.0.0, 1.0.0.beta.6, 1.0.0.beta.5, 1.0.0.beta.2, 0.39.0, 0.38.2)
cocoapods-core (1.0.0, 1.0.0.beta.6, 1.0.0.beta.5, 1.0.0.beta.2, 0.39.0, 0.38.2, 0.35.0)
cocoapods-deintegrate (1.0.0, 1.0.0.beta.1)
cocoapods-downloader (1.0.0, 1.0.0.beta.2, 1.0.0.beta.1, 0.9.3, 0.9.0, 0.8.1)
cocoapods-plugins (1.0.0, 1.0.0.beta.1, 0.4.2, 0.3.2)
cocoapods-search (1.0.0, 1.0.0.beta.1, 0.1.0)
cocoapods-stats (1.0.0, 1.0.0.beta.3, 0.6.2, 0.5.3)
cocoapods-trunk (1.0.0, 1.0.0.beta.2, 1.0.0.beta.1, 0.6.4, 0.6.1, 0.4.1)
cocoapods-try (1.0.0, 1.0.0.beta.3, 1.0.0.beta.2, 0.5.1, 0.4.5, 0.4.3)

But then i do that:

Martins-MacBook-Pro-2:small-world mkovachev$ /usr/bin/pod --version
0.38.2

There must be something going on here with my install - probably another conflicting version.

I'll fix that first and let you know on 1.0.0.

Thanks for the hint!

**Comment by miraclebg** [comment]
You are right - it was the version - with 1.0.0 it all works properly.

Didn't have an idea gem allows you to store multiple versions at once.. probably somehow it's possible to activate a specific one only - but i just went and reinstalled it all :)

**Comment by vinceis1337** [comment]
@miraclebg glad you got it fixed! :)
