### ISSUE TITLE
Excute "pod package Test.podspec --force" failed, but passed validation.

### ISSUE THREAD

**Issue by KosonGou** [CocoaPods/CocoaPods#5359]
### Command

```
/usr/local/bin/pod package Test.podspec --force
```

### Report

* What did you do?
```
    Make static library with cocoapods-packager
```
* What did you expect to happen?
```
    Package success.
```
* What happened instead?
```
    an error occurred.
```

### Stack

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.4.8
        Host : Mac OS X 10.11.4 (15E65)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 1736e85469043934321cf21413c4f1121f2bdee5
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-packager    : 1.3.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

### Error

```
NoMethodError - undefined method `integrate_targets=' for #<Pod::Config:0x007f929c91b4b0>
/Library/Ruby/Gems/2.0.0/gems/cocoapods-packager-1.3.0/lib/pod/command/package.rb:65:in `build_in_sandbox'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-packager-1.3.0/lib/pod/command/package.rb:84:in `block in build_package'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-packager-1.3.0/lib/pod/command/package.rb:83:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-packager-1.3.0/lib/pod/command/package.rb:83:in `build_package'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-packager-1.3.0/lib/pod/command/package.rb:56:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by neonichu** [comment]
See <https://github.com/CocoaPods/cocoapods-packager/issues/137#issuecomment-218980020>

**Comment by KosonGou** [comment]
@neonichu OK,Thanks.
