### ISSUE TITLE
pod install: Error installing an iOS 8 framework's .modulemap

### ISSUE THREAD

**Issue by cbowns** [CocoaPods/CocoaPods#5364]
- [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).
# Report
## What did you do?

With `bundler`, I upgraded from `cocoapods (1.0.0.rc.1)` to `cocoapods (1.0.0)`, then ran `bundle exec pod install`.
## What did you expected to happen?

I expected cocoapods to do some Xcode project frippery, since 1.0 has been all about better project file management.
## What happened instead?

An error!
### Error

```
Generating Pods project
  - Creating Pods project
  - Adding source files to Pods project
  - Adding frameworks to Pods project
  - Adding libraries to Pods project
  - Adding resources to Pods project
  - Linking headers
  - Installing targets
    - Installing target `AWSCore` iOS 8.0
      - Generating Info.plist file at `Pods/Target Support Files/AWSCore/Info.plist`
      - Generating module map file at `Pods/Target Support Files/AWSCore/AWSCore.modulemap`
      - Generating umbrella header at `Pods/Target Support Files/AWSCore/AWSCore-umbrella.h`
    - Installing target `AWSS3` iOS 8.0
      - Generating Info.plist file at `Pods/Target Support Files/AWSS3/Info.plist`
      - Generating module map file at `Pods/Target Support Files/AWSS3/AWSS3.modulemap`
      - Generating umbrella header at `Pods/Target Support Files/AWSS3/AWSS3-umbrella.h`
    - Installing target `Alamofire` iOS 8.0
      - Generating Info.plist file at `Pods/Target Support Files/Alamofire/Info.plist`
      - Generating module map file at `Pods/Target Support Files/Alamofire/Alamofire.modulemap`
      - Generating umbrella header at `Pods/Target Support Files/Alamofire/Alamofire-umbrella.h`
    - Installing target `Cereal` iOS 8.0
      - Generating Info.plist file at `Pods/Target Support Files/Cereal/Info.plist`
      - Generating module map file at `Pods/Target Support Files/Cereal/Cereal.modulemap`
      - Generating umbrella header at `Pods/Target Support Files/Cereal/Cereal-umbrella.h`
    - Installing target `CocoaLumberjack` iOS 8.0
      - Generating Info.plist file at `Pods/Target Support Files/CocoaLumberjack/Info.plist`
      - Copying module map file to `Pods/Target Support Files/CocoaLumberjack/CocoaLumberjack.modulemap`

Errno::ENOENT - No such file or directory @ rb_sysopen - /Users/cbowns/Development/crlf/client/utility-iOS/Pods/CocoaLumberjack/Framework/Lumberjack/CocoaLumberjack.modulemap
/Users/cbowns/.rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:1391:in `initialize'
/Users/cbowns/.rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:1391:in `open'
/Users/cbowns/.rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:1391:in `copy_file'
/Users/cbowns/.rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:485:in `copy_file'
/Users/cbowns/.rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:402:in `block in cp'
/Users/cbowns/.rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:1570:in `block in fu_each_src_dest'
/Users/cbowns/.rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:1586:in `fu_each_src_dest0'
/Users/cbowns/.rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:1568:in `fu_each_src_dest'
/Users/cbowns/.rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:401:in `cp'
/Users/cbowns/.gem/ruby/2.2.1/gems/cocoapods-1.0.0/lib/cocoapods/installer/target_installer/pod_target_installer.rb:314:in `block in create_module_map'
/Users/cbowns/.gem/ruby/2.2.1/gems/cocoapods-1.0.0/lib/cocoapods/user_interface.rb:144:in `message'
/Users/cbowns/.gem/ruby/2.2.1/gems/cocoapods-1.0.0/lib/cocoapods/installer/target_installer/pod_target_installer.rb:313:in `create_module_map'
/Users/cbowns/.gem/ruby/2.2.1/gems/cocoapods-1.0.0/lib/cocoapods/installer/target_installer/pod_target_installer.rb:25:in `block in install!'
/Users/cbowns/.gem/ruby/2.2.1/gems/cocoapods-1.0.0/lib/cocoapods/user_interface.rb:144:in `message'
/Users/cbowns/.gem/ruby/2.2.1/gems/cocoapods-1.0.0/lib/cocoapods/installer/target_installer/pod_target_installer.rb:17:in `install!'
/Users/cbowns/.gem/ruby/2.2.1/gems/cocoapods-1.0.0/lib/cocoapods/installer.rb:621:in `block (2 levels) in install_libraries'
/Users/cbowns/.gem/ruby/2.2.1/gems/cocoapods-1.0.0/lib/cocoapods/installer.rb:619:in `each'
/Users/cbowns/.gem/ruby/2.2.1/gems/cocoapods-1.0.0/lib/cocoapods/installer.rb:619:in `block in install_libraries'
/Users/cbowns/.gem/ruby/2.2.1/gems/cocoapods-1.0.0/lib/cocoapods/user_interface.rb:144:in `message'
/Users/cbowns/.gem/ruby/2.2.1/gems/cocoapods-1.0.0/lib/cocoapods/installer.rb:618:in `install_libraries'
/Users/cbowns/.gem/ruby/2.2.1/gems/cocoapods-1.0.0/lib/cocoapods/installer.rb:170:in `block in generate_pods_project'
/Users/cbowns/.gem/ruby/2.2.1/gems/cocoapods-1.0.0/lib/cocoapods/user_interface.rb:63:in `section'
/Users/cbowns/.gem/ruby/2.2.1/gems/cocoapods-1.0.0/lib/cocoapods/installer.rb:167:in `generate_pods_project'
/Users/cbowns/.gem/ruby/2.2.1/gems/cocoapods-1.0.0/lib/cocoapods/installer.rb:119:in `install!'
/Users/cbowns/.gem/ruby/2.2.1/gems/cocoapods-1.0.0/lib/cocoapods/command/install.rb:37:in `run'
/Users/cbowns/.gem/ruby/2.2.1/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Users/cbowns/.gem/ruby/2.2.1/gems/cocoapods-1.0.0/lib/cocoapods/command.rb:50:in `run'
/Users/cbowns/.gem/ruby/2.2.1/gems/cocoapods-1.0.0/bin/pod:55:in `<top (required)>'
/Users/cbowns/.gem/ruby/2.2.1/bin/pod:23:in `load'
/Users/cbowns/.gem/ruby/2.2.1/bin/pod:23:in `<main>'
```
### Stack

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin15]
    RubyGems : 2.4.5
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.8.2
Ruby lib dir : /Users/cbowns/.rubies/ruby-2.2.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 04dcd6ac52c6248ddb4572066ca4a80f3e13e953
```
### Installation Source

```
Executable Path: /Users/cbowns/.gem/ruby/2.2.1/bin/pod
```
### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```
### Podfile

``` ruby
platform :ios, '9.0'

use_frameworks!
inhibit_all_warnings!

# Pods for both Inspire and Tests:
def common_pods
  # Data serialization to disk:
  pod 'Cereal', '~> 1.2'

  # Bluetooth and helpers
  pod 'NSData+FastHex'

  # Authorization and Security
  pod 'Valet', '~> 2.2'

  # Networking
  pod 'Alamofire', '~> 3.0'

  # Logging
  pod 'CocoaLumberjack/Swift', '~> 2.0'

  # Defaults:
  pod 'SwiftyUserDefaults', '~> 2.0'

  # Amazon S3 for uploading logs
  pod 'AWSS3', '~> 2.3'
end

target 'Inspire' do
  # Pull in our common pods.
  common_pods

  # Authorization and Security
  # pod 'p2.OAuth2', '~> 2.1' # Not needed yet, but helpful for refresh token handling

  # Networking
  # TODO: bump this to master (or, god forbid, they tag a stable release)
  # pod 'Spine', :git => 'https://github.com/wvteijlingen/Spine.git', :branch => 'swift-2.0'

  # UI alerts:
  pod 'SimpleAlert', '~> 1.3'

  # Crash tracking and build distribution
  pod 'Fabric'
  pod 'Crashlytics'

  # Tracking user activities and interactions
  pod 'Appsee'
end

# Pods for testing.
def testing_pods
  # pod 'Quick', '~> 0.8'
  # pod 'Nimble', '~> 3.0'
end

target 'InspireTests' do
  common_pods
  testing_pods
end
```
## Project that demonstrates the issue

I'm unable to provide this project, as it's a closed-source client project.

**Comment by neonichu** [comment]
Can't reproduce this when integrating into a fresh project, unfortunately. Maybe this is an issue with a previous version of the `CocoaLumberjack` pod? A fresh integration uses 2.3.0.

**Comment by cbowns** [comment]
@neonichu Yeah, I'll dig a bit more. It looks like rolling my `Gemfile` back to `cocoapods (1.0.0.rc.1)` also fails on `install`, so I might be Doing It Wrong. More info shortly…

**Comment by cbowns** [comment]
@neonichu Actually, a different question:

`pod install` fails on this `.modulemap` file, but a `pod update CocoaLumberjack` successfully installs 2.3.0.

Am I doing `pod install` wrong here? I wanted to basically say, "Hey CocoaPods, now that you're at 1.0, I bet you've got a few small changes to make to the Pods .xcodeproj and all, but please don't make any changes to my installed pod versions." What command do I want for that?

**Comment by neonichu** [comment]
`pod install` is the right command for that. The files inside "Target Support Files" are regenerated every time, no matter which command you use.

My guess is that your project has an older version of `CocoaLumberjack` listed in the `Podfile.lock`, which might have an incompatibility with CocoaPods 1.0, while you're getting the newest version (2.3.0) with the `pod update` command, which seems to be fine.

**Comment by cbowns** [comment]
kk, thanks!

**Comment by cbowns** [comment]
I just ran through `git bisect` on this project, and found that `cocoapods (1.0.0.beta.8)` works while `cocoapods (1.0.0.rc.1)` breaks. I reduced this down to the following:

Beta 8:

```
cbowns at Warp in ~/Development/crlf/carrot-sense/utility-iOS on master at cd210e7 (ahead 1) -~ ☆
% ± bundle exec pod --version                                                                                                                                                                                            2016-05-19 [14:07:57]
1.0.0.beta.8


cbowns at Warp in ~/Development/crlf/carrot-sense/utility-iOS on master at cd210e7 (ahead 1) -~ ☆
% ± cat Gemfile                                                                                                                                                                                                          2016-05-19 [14:08:09]
source 'https://rubygems.org'

# We use cocoapods
gem 'cocoapods', "1.0.0.beta.8"

# We use fastlane for build distribution
gem 'fastlane'


cbowns at Warp in ~/Development/crlf/carrot-sense/utility-iOS on master at cd210e7 (ahead 1) -~ ☆
% ± bundle exec pod install                                                                                                                                                                                              2016-05-19 [14:08:00]
Analyzing dependencies
Downloading dependencies
Using AWSCore (2.3.6)
Using AWSS3 (2.3.6)
Using Alamofire (3.2.1)
Using Appsee (2.2)
Using Cereal (1.2.1)
Using CocoaLumberjack (2.2.0)
Using Crashlytics (3.7.0)
Using Fabric (1.6.7)
Using NSData+FastHex (1.0.1)
Using SimpleAlert (1.3.1)
Using SwiftyUserDefaults (2.1.3)
Using Valet (2.2.1)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 11 dependencies from the Podfile and 12 total pods installed.
```

When I roll forward CocoaPods to `1.0.0.rc.1`:

```
% ± bundle exec pod --version                                                                                                                                2016-05-19 [14:09:23]
1.0.0.rc.1

cbowns at Warp in ~/Development/crlf/carrot-sense/utility-iOS on master at 68a1c9c (ahead 2) ~ ☆
% ± cat Gemfile                                                                                                                                              2016-05-19 [14:09:27]
source 'https://rubygems.org'

# We use cocoapods
gem 'cocoapods', "1.0.0.rc.1"

# We use fastlane for build distribution
gem 'fastlane'

cbowns at Warp in ~/Development/crlf/carrot-sense/utility-iOS on master at 68a1c9c (ahead 2) ~ ☆
% ± bundle exec pod install                                                                                                                                  2016-05-19 [14:09:31]
Analyzing dependencies
Downloading dependencies
Using AWSCore (2.3.6)
Using AWSS3 (2.3.6)
Using Alamofire (3.2.1)
Using Appsee (2.2)
Using Cereal (1.2.1)
Using CocoaLumberjack (2.2.0)
Using Crashlytics (3.7.0)
Using Fabric (1.6.7)
Using NSData+FastHex (1.0.1)
Using SimpleAlert (1.3.1)
Using SwiftyUserDefaults (2.1.3)
Using Valet (2.2.1)
Generating Pods project

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

/Users/cbowns/.gem/ruby/2.2.1/bin/pod install

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

   CocoaPods : 1.0.0.rc.1
        Ruby : ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin15]
    RubyGems : 2.4.5
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.8.2
Ruby lib dir : /Users/cbowns/.rubies/ruby-2.2.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ b51895cfb9a7bfa2d0e95c63d2366980283f476f

### Plugins

cocoapods-deintegrate : 1.0.0.rc.1
cocoapods-plugins     : 1.0.0.rc.1
cocoapods-search      : 1.0.0.rc.1
cocoapods-stats       : 1.0.0.rc.1
cocoapods-trunk       : 1.0.0.rc.1
cocoapods-try         : 1.0.0.rc.1

### Podfile

platform :ios, '9.0'

use_frameworks!
inhibit_all_warnings!

# Pods for both Inspire and Tests:
def common_pods
  # Data serialization to disk:
  pod 'Cereal', '~> 1.2'

  # Bluetooth and helpers
  pod 'NSData+FastHex'

  # Authorization and Security
  pod 'Valet', '~> 2.2'

  # Networking
  pod 'Alamofire', '~> 3.0'

  # Logging
  pod 'CocoaLumberjack/Swift', '~> 2.0'

  # Defaults:
  pod 'SwiftyUserDefaults', '~> 2.0'

  # Amazon S3 for uploading logs
  pod 'AWSS3', '~> 2.3'
end

target 'Inspire' do
  # Pull in our common pods.
  common_pods

  # Authorization and Security
  # pod 'p2.OAuth2', '~> 2.1' # Not needed yet, but helpful for refresh token handling

  # Networking
  # TODO: bump this to master (or, god forbid, they tag a stable release)
  # pod 'Spine', :git => 'https://github.com/wvteijlingen/Spine.git', :branch => 'swift-2.0'

  # UI alerts:
  pod 'SimpleAlert', '~> 1.3'

  # Crash tracking and build distribution
  pod 'Fabric'
  pod 'Crashlytics'

  # Tracking user activities and interactions
  pod 'Appsee'
end

# Pods for testing.
def testing_pods
  # pod 'Quick', '~> 0.8'
  # pod 'Nimble', '~> 3.0'
end

target 'InspireTests' do
  common_pods
  testing_pods
end

### Error

Errno::ENOENT - No such file or directory @ rb_sysopen - /Users/cbowns/Development/crlf/carrot-sense/utility-iOS/Pods/CocoaLumberjack/Framework/Lumberjack/CocoaLumberjack.modulemap
/Users/cbowns/.rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:1391:in `initialize'
/Users/cbowns/.rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:1391:in `open'
/Users/cbowns/.rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:1391:in `copy_file'
/Users/cbowns/.rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:485:in `copy_file'
/Users/cbowns/.rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:402:in `block in cp'
/Users/cbowns/.rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:1570:in `block in fu_each_src_dest'
/Users/cbowns/.rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:1586:in `fu_each_src_dest0'
/Users/cbowns/.rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:1568:in `fu_each_src_dest'
/Users/cbowns/.rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:401:in `cp'
/Users/cbowns/.gem/ruby/2.2.1/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/installer/target_installer/pod_target_installer.rb:314:in `block in create_module_map'
/Users/cbowns/.gem/ruby/2.2.1/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/user_interface.rb:144:in `message'
/Users/cbowns/.gem/ruby/2.2.1/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/installer/target_installer/pod_target_installer.rb:313:in `create_module_map'
/Users/cbowns/.gem/ruby/2.2.1/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/installer/target_installer/pod_target_installer.rb:25:in `block in install!'
/Users/cbowns/.gem/ruby/2.2.1/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/user_interface.rb:144:in `message'
/Users/cbowns/.gem/ruby/2.2.1/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/installer/target_installer/pod_target_installer.rb:17:in `install!'
/Users/cbowns/.gem/ruby/2.2.1/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/installer.rb:621:in `block (2 levels) in install_libraries'
/Users/cbowns/.gem/ruby/2.2.1/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/installer.rb:619:in `each'
/Users/cbowns/.gem/ruby/2.2.1/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/installer.rb:619:in `block in install_libraries'
/Users/cbowns/.gem/ruby/2.2.1/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/user_interface.rb:144:in `message'
/Users/cbowns/.gem/ruby/2.2.1/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/installer.rb:618:in `install_libraries'
/Users/cbowns/.gem/ruby/2.2.1/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/installer.rb:170:in `block in generate_pods_project'
/Users/cbowns/.gem/ruby/2.2.1/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/user_interface.rb:63:in `section'
/Users/cbowns/.gem/ruby/2.2.1/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/installer.rb:167:in `generate_pods_project'
/Users/cbowns/.gem/ruby/2.2.1/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/installer.rb:119:in `install!'
/Users/cbowns/.gem/ruby/2.2.1/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/command/install.rb:37:in `run'
/Users/cbowns/.gem/ruby/2.2.1/gems/claide-1.0.0.rc.1/lib/claide/command.rb:334:in `run'
/Users/cbowns/.gem/ruby/2.2.1/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/command.rb:50:in `run'
/Users/cbowns/.gem/ruby/2.2.1/gems/cocoapods-1.0.0.rc.1/bin/pod:55:in `<top (required)>'
/Users/cbowns/.gem/ruby/2.2.1/bin/pod:23:in `load'
/Users/cbowns/.gem/ruby/2.2.1/bin/pod:23:in `<main>'
```

**Comment by DanToml** [comment]
@cbowns Are you still seeing this on `1.2.0.rc.1`?

**Comment by cbowns** [comment]
This is an old client project but lemme try

**Comment by DanToml** [comment]
Closing due to lack of activity - If this is still a bug please file a new issue with a sample project.
