### ISSUE TITLE
### Error ArgumentError - recursive array join

### ISSUE THREAD

**Issue by DavidHuang61** [CocoaPods/CocoaPods#5379]
what wrong with me?
when I run 'pod install', I have an error.

### Stack

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin14]
    RubyGems : 2.6.1
        Host : Mac OS X 10.11.4 (15E65)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /usr/local/Cellar/ruby/2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ e3012ee8749d91054bfa3d63c7de3a7adc7f7c55
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
 platform :ios, '7.0'

target 'ZJBL-DZ' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ZJBL-DZ
  pod pod 'AFNetworking', '3.1.0'

end
```

This is error :
### Error

```
ArgumentError - recursive array join
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-core-1.0.0/lib/cocoapods-core/source/metadata.rb:50:in `join'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-core-1.0.0/lib/cocoapods-core/source/metadata.rb:50:in `path_fragment'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-core-1.0.0/lib/cocoapods-core/source.rb:111:in `pod_path'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-core-1.0.0/lib/cocoapods-core/source.rb:265:in `search'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-core-1.0.0/lib/cocoapods-core/source/aggregate.rb:83:in `block in search'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-core-1.0.0/lib/cocoapods-core/source/aggregate.rb:83:in `select'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-core-1.0.0/lib/cocoapods-core/source/aggregate.rb:83:in `search'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.0/lib/cocoapods/resolver.rb:346:in `create_set_from_sources'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.0/lib/cocoapods/resolver.rb:316:in `find_cached_set'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.0/lib/cocoapods/resolver.rb:289:in `specifications_for_dependency'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.0/lib/cocoapods/resolver.rb:107:in `search_for'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.0/lib/cocoapods/resolver.rb:205:in `block in sort_dependencies'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.0/lib/cocoapods/resolver.rb:199:in `each'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.0/lib/cocoapods/resolver.rb:199:in `sort_by'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.0/lib/cocoapods/resolver.rb:199:in `sort_dependencies'
/usr/local/lib/ruby/gems/2.3.0/gems/molinillo-0.4.5/lib/molinillo/resolution.rb:131:in `block (2 levels) in <class:Resolution>'
/usr/local/lib/ruby/gems/2.3.0/gems/molinillo-0.4.5/lib/molinillo/resolution.rb:174:in `initial_state'
/usr/local/lib/ruby/gems/2.3.0/gems/molinillo-0.4.5/lib/molinillo/resolution.rb:100:in `start_resolution'
/usr/local/lib/ruby/gems/2.3.0/gems/molinillo-0.4.5/lib/molinillo/resolution.rb:63:in `resolve'
/usr/local/lib/ruby/gems/2.3.0/gems/molinillo-0.4.5/lib/molinillo/resolver.rb:42:in `resolve'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.0/lib/cocoapods/resolver.rb:62:in `resolve'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.0/lib/cocoapods/installer/analyzer.rb:563:in `block in resolve_dependencies'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.0/lib/cocoapods/user_interface.rb:63:in `section'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.0/lib/cocoapods/installer/analyzer.rb:561:in `resolve_dependencies'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.0/lib/cocoapods/installer/analyzer.rb:76:in `analyze'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.0/lib/cocoapods/installer.rb:227:in `analyze'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.0/lib/cocoapods/installer.rb:151:in `block in resolve_dependencies'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.0/lib/cocoapods/user_interface.rb:63:in `section'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.0/lib/cocoapods/installer.rb:150:in `resolve_dependencies'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.0/lib/cocoapods/installer.rb:114:in `install!'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.0/lib/cocoapods/command/install.rb:37:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.0/lib/cocoapods/command.rb:50:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

**Comment by segiddins** [comment]
My guess is this is happening because you wrote `pod` twice, but we should handle that better

**Comment by DavidHuang61** [comment]
@segiddins This is a old project. Manual import AFNetworking. I want to use pod an manage my project. so I run 'pod init' and 'pod install'.

**Comment by DavidHuang61** [comment]
@segiddins sorry! I am find my error. Thank you !!!
