### ISSUE TITLE
NoMethodError - undefined method `integrate_targets=' for #<Pod::Config:0x007fe5d2bb1c40>

### ISSUE THREAD

**Issue by KianLiu** [CocoaPods/CocoaPods#5402]
When I run  "pod package JWHybridFramework.podspec --force" ,occurred this error.
cocoapods version is 1.0.0
ruby version is 2.2.1p85

Usage of the constant `Pod::SourcesManager` is deprecated, use `Pod::Config.instance.sources_manager` instead (called from /Users/liuqian/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-packager-1.3.0/lib/cocoapods-packager/pod_utils.rb:73:in `spec_with_name')

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/liuqian/.rvm/rubies/ruby-2.2.1/bin/pod package JWHybridFramework.podspec --force
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
    RubyGems : 2.5.2
        Host : Mac OS X 10.11.4 (15E65)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /Users/liuqian/.rvm/rubies/ruby-2.2.1/lib
Repositories : coding-hging-specs - https://git.coding.net/hging/Specs.git @ b3fc2489dc1a00fd3e65d6d9ca85a1e70796aee2
               gitcafe-akuandev-specs - https://gitcafe.com/akuandev/Specs.git @ b97d1e07ecffd4c3b30efc12a2aad639df4ed8c4
               JZMSpecs - git@gitlab:cocoapods/JZMSpecs.git @ 1b413e4f55c6de9794eb6f56233531b8fdb22ad7
               master - https://github.com/CocoaPods/Specs.git @ 8df8bf1ada72999355f305d2a83a23d544ce1362
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-packager    : 1.3.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

### Error

```
NoMethodError - undefined method `integrate_targets=' for #<Pod::Config:0x007fe5d2bb1c40>
/Users/liuqian/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-packager-1.3.0/lib/pod/command/package.rb:65:in `build_in_sandbox'
/Users/liuqian/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-packager-1.3.0/lib/pod/command/package.rb:84:in `block in build_package'
/Users/liuqian/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-packager-1.3.0/lib/pod/command/package.rb:83:in `each'
/Users/liuqian/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-packager-1.3.0/lib/pod/command/package.rb:83:in `build_package'
/Users/liuqian/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-packager-1.3.0/lib/pod/command/package.rb:56:in `run'
/Users/liuqian/.rvm/gems/ruby-2.2.1@global/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Users/liuqian/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-1.0.0/lib/cocoapods/command.rb:50:in `run'
/Users/liuqian/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-1.0.0/bin/pod:55:in `<top (required)>'
/Users/liuqian/.rvm/rubies/ruby-2.2.1/bin/pod:22:in `load'
/Users/liuqian/.rvm/rubies/ruby-2.2.1/bin/pod:22:in `<main>'
/Users/liuqian/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
/Users/liuqian/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

**Comment by orta** [comment]
This looks like might be an issue on CocoaPods Packager, rather than CocoaPods itself.

**Comment by KianLiu** [comment]
Thanks,so which version of  CocoaPods Packager should I use?  Currently,it is 1.3.0.

**Comment by manuyavuz** [comment]
@KianLiu if you want to use packager with 1.0 version, you should use [support-1.0](https://github.com/CocoaPods/cocoapods-packager/tree/support-1.0) branch of the plugin.

**Comment by neonichu** [comment]
See CocoaPods/cocoapods-packager#138
