### ISSUE TITLE
NoMethodError - undefined method `path' for nil:NilClass

### ISSUE THREAD

**Issue by zrhdev** [CocoaPods/CocoaPods#5427]
# Report
## What did you do?

pod 'wax', :git => 'https://github.com/zrhdev/wax.git', :tag => '1.2.0'

```
/usr/local/bin/pod install --no-repo-update
```
## What did you expected to happen?

Install all pod correctly.
## What happened instead?

The same question of #4887 have not been closed.
### Error

```
NoMethodError - undefined method `path' for nil:NilClass
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.0.0/lib/xcodeproj/project/object/native_target.rb:442:in `block in add_file_references'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.0.0/lib/xcodeproj/project/object/native_target.rb:441:in `map'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.0.0/lib/xcodeproj/project/object/native_target.rb:441:in `add_file_references'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/installer/target_installer/pod_target_installer.rb:94:in `block in add_files_to_build_phases'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/installer/target_installer/pod_target_installer.rb:75:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/installer/target_installer/pod_target_installer.rb:75:in `add_files_to_build_phases'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/installer/target_installer/pod_target_installer.rb:21:in `block in install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/user_interface.rb:144:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/installer/target_installer/pod_target_installer.rb:17:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/installer.rb:621:in `block (2 levels) in install_libraries'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/installer.rb:619:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/installer.rb:619:in `block in install_libraries'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/user_interface.rb:144:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/installer.rb:618:in `install_libraries'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/installer.rb:170:in `block in generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/user_interface.rb:63:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/installer.rb:167:in `generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/installer.rb:119:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/command/install.rb:37:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```
### Stack

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.6.4
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : cms - http://gitlab.365eche.com/Frame/CMSpecs.git @ 7906b0bf8dea0ee498dff7e3d6db67eb1cbe938a
               master - https://github.com/CocoaPods/Specs.git @ c6816cefd545836066f614647ec6a91dca2d57ea
```
### Installation Source

```
Executable Path: /usr/local/bin/pod
```
### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```
## Project that demonstrates the issue

pod 'wax', :git => 'https://github.com/zrhdev/wax.git', :tag => '1.2.0'

**Comment by segiddins** [comment]
This is happening since https://github.com/zrhdev/wax/blob/master/lib/extensions/json/yajl/yajl_common.h is a symlink

**Comment by segiddins** [comment]
If someone could test this and make a PR, this should fix it
```diff
diff --git a/lib/cocoapods/installer/target_installer/pod_target_installer.rb b/lib/cocoapods/installer/target_installer/pod_target_installer.rb
index e5e1321..e2232b9 100644
--- a/lib/cocoapods/installer/target_installer/pod_target_installer.rb
+++ b/lib/cocoapods/installer/target_installer/pod_target_installer.rb
@@ -91,7 +91,11 @@ module Pod
             native_target.add_file_references(regular_file_refs, flags)
           end
 
-          header_file_refs = headers.map { |sf| project.reference_for_path(sf) }
+          header_file_refs = headers.map do |sf|
+            project.reference_for_path(sf).tap do |ref|
+              raise "unable to find ref for #{sf}" unless ref
+            end
+          end
           native_target.add_file_references(header_file_refs) do |build_file|
             add_header(build_file, public_headers, private_headers)
           end
diff --git a/lib/cocoapods/project.rb b/lib/cocoapods/project.rb
index 6923e42..8eb2b30 100644
--- a/lib/cocoapods/project.rb
+++ b/lib/cocoapods/project.rb
@@ -184,6 +184,7 @@ module Pod
       group = group_for_path_in_group(file_path_name, group, reflect_file_system_structure)
 
       if ref = reference_for_path(file_path_name.realpath)
+        @refs_by_absolute_path[absolute_path.to_s] = ref
         ref
       else
         ref = group.new_file(file_path_name.realpath)
```

**Comment by zrhdev** [comment]
Who can do it?

**Comment by segiddins** [comment]
@zrhdev you could, if you wanted to 😄

**Comment by denniszelada** [comment]
Hello @segiddins, I created the PR can you give me access to push the branch?

Thanks,

Dennis

**Comment by segiddins** [comment]
I'm not seeing a new PR opened against the CocoaPods repo?
