### ISSUE TITLE
NoMethodError - undefined method `gsub' for nil:NilClass

### ISSUE THREAD

**Issue by raonyvf** [CocoaPods/CocoaPods#5430]
> ℹ Please fill out this template when filing an issue.
> All lines beginning with an ℹ symbol instruct you with
> what info we expect.  
> Please remove this line and all above before submitting.

* [ ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace this with what you did.  
pod install

## What did you expected to happen?

ℹ Please replace this with what you expected to happen.  
e.g. Install all pod dependencies correctly.

## What happened instead?

ℹ Please replace this with of what happened instead.  
raonyvf$ pod install
Analyzing dependencies
Downloading dependencies
Installing GoogleMaps (1.13.2)

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/raonyvf/.rbenv/versions/2.2.2/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
    RubyGems : 2.4.8
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3 (7D175)
         Git : git version 2.6.4 (Apple Git-63)
Ruby lib dir : /Users/raonyvf/.rbenv/versions/2.2.2/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 0513bb20a18a0ed714dbfbccc90252fbb1548b6b
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
target 'testeGoogleMaps'
pod 'GoogleMaps'
```

### Error

```
NoMethodError - undefined method `gsub' for nil:NilClass
/Users/raonyvf/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0/lib/cocoapods/sandbox/path_list.rb:58:in `block in read_file_system'
/Users/raonyvf/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0/lib/cocoapods/sandbox/path_list.rb:58:in `map'
/Users/raonyvf/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0/lib/cocoapods/sandbox/path_list.rb:58:in `read_file_system'
/Users/raonyvf/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0/lib/cocoapods/sandbox/path_list.rb:31:in `files'
/Users/raonyvf/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0/lib/cocoapods/sandbox/path_list.rb:115:in `relative_glob'
/Users/raonyvf/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0/lib/cocoapods/sandbox/path_list.rb:79:in `glob'
/Users/raonyvf/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0/lib/cocoapods/sandbox/file_accessor.rb:363:in `expanded_paths'
/Users/raonyvf/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0/lib/cocoapods/sandbox/file_accessor.rb:334:in `paths_for_attribute'
/Users/raonyvf/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0/lib/cocoapods/sandbox/file_accessor.rb:152:in `vendored_frameworks'
/Users/raonyvf/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0/lib/cocoapods/sandbox/pod_dir_cleaner.rb:69:in `map'
/Users/raonyvf/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0/lib/cocoapods/sandbox/pod_dir_cleaner.rb:69:in `used_files'
/Users/raonyvf/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0/lib/cocoapods/sandbox/pod_dir_cleaner.rb:51:in `clean_paths'
/Users/raonyvf/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0/lib/cocoapods/sandbox/pod_dir_cleaner.rb:18:in `clean!'
/Users/raonyvf/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0/lib/cocoapods/installer/pod_source_installer.rb:141:in `clean_installation'
/Users/raonyvf/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0/lib/cocoapods/installer/pod_source_installer.rb:72:in `clean!'
/Users/raonyvf/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0/lib/cocoapods/installer.rb:357:in `each'
/Users/raonyvf/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0/lib/cocoapods/installer.rb:357:in `clean_pod_sources'
/Users/raonyvf/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0/lib/cocoapods/installer.rb:162:in `block in download_dependencies'
/Users/raonyvf/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0/lib/cocoapods/user_interface.rb:63:in `section'
/Users/raonyvf/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0/lib/cocoapods/installer.rb:158:in `download_dependencies'
/Users/raonyvf/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0/lib/cocoapods/installer.rb:115:in `install!'
/Users/raonyvf/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0/lib/cocoapods/command/install.rb:37:in `run'
/Users/raonyvf/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Users/raonyvf/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0/lib/cocoapods/command.rb:50:in `run'
/Users/raonyvf/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0/bin/pod:55:in `<top (required)>'
/Users/raonyvf/.rbenv/versions/2.2.2/bin/pod:23:in `load'
/Users/raonyvf/.rbenv/versions/2.2.2/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=undefined+method+%60gsub%27+for+nil%3ANilClass&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

## CocoaPods Environment

ℹ Please replace this with the output of `pod env`.
### Stack

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
    RubyGems : 2.4.8
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3 (7D175)
         Git : git version 2.6.4 (Apple Git-63)
Ruby lib dir : /Users/raonyvf/.rbenv/versions/2.2.2/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 0513bb20a18a0ed714dbfbccc90252fbb1548b6b
```

### Installation Source

```
Executable Path: /Users/raonyvf/.rbenv/versions/2.2.2/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
target 'testeGoogleMaps'
pod 'GoogleMaps'
```

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

**Comment by segiddins** [comment]
Please share the output of `pod env` as the issue template requests so we can take a look. Thanks!

**Comment by raonyvf** [comment]
Hi segiddins
I already updated the post with the output from prod env. Is there any clue to help me?
I have been struggling my self to fix it but I could not yet.

Thanks

**Comment by segiddins** [comment]
I can't reproduce this issue with the given Podfile, sorry

**Comment by raonyvf** [comment]
What kind of information do you need to reproduce this issue?

**Comment by segiddins** [comment]
Ideally a project that reproduces the issue just by running `pod install`

**Comment by raonyvf** [comment]
I update the post. Check if its ok for you

**Comment by neonichu** [comment]
Closing because of lack of activity.
