### ISSUE TITLE
NoMethodError - undefined method `version' for nil:NilClass

### ISSUE THREAD

**Issue by NikolayNahimov** [CocoaPods/CocoaPods#5449]
# Report
## What did you do?

Run `pod list` in the empty dirctory.
## What did you expected to happen?

See the list of available pods.
## What happened instead?

The below error. 
### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : bitbucket-mpymnt-io.mpymnt.repo.pods - https://bitbucket.org/mpymnt/io.mpymnt.repo.pods.git @ 196b723a7937006e7c0abd5fa100169835d505a8
               master - https://github.com/CocoaPods/Specs.git @ 47c053ee2bb61f3b7a9ccfcbbb6348c8ad935cee
               thepaymenthouse - https://github.com/ThePaymentHouse/TphFramework_iOS.git @ 6044a884d465fa63f3dcb545938a7d0dcf1088dd
```
### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```
### Error

```
NoMethodError - undefined method `version' for nil:NilClass
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:204:in `pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command/list.rb:24:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command/list.rb:24:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command/list.rb:24:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by neonichu** [comment]
Could you try to run `pod repo lint`?

**Comment by NikolayNahimov** [comment]
Linting spec repo `bitbucket-mpymnt-io.mpymnt.repo.pods`

...............................................................................

-> A framework should only be specified by its name
  - mcommerce (1.7.0, 1.6.0, 1.5.5)
  - mcommerce.checkout (1.7.0, 1.6.0, 1.5.5)

Analyzed 79 podspecs files.

[!] 1 podspecs failed validation.

**Comment by DanToml** [comment]
Could you fix the broken specification and try again?

**Comment by DanToml** [comment]
Closing due to lack of activity - If this is still a bug please file a new issue with a sample project.
