### ISSUE TITLE
Integrate Xcode 7.3.1 with Xcode Server and Cocoapods 1.0.1

### ISSUE THREAD

**Issue by baltameme** [CocoaPods/CocoaPods#5464]
I was trying to Integrate Cocoapods 1.0.1 with the XCode Server Bots.
Here is my prebuild script for the Bot

export LANG=en_US.UTF-8
cd PROJECT_NAME
if [ -e "Pods" ] #See if the Pods directory already exists
then
/usr/local/bin/pod update --verbose #update pods if it does
else
/usr/local/bin/pod install --verbose #install if it doesn't
fi 

### Command

```
/usr/local/bin/pod update --verbose
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.4 (15E65)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : 
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '8.0'
target 'DawriPlus' do
	pod 'SwiftyJSON'
	pod 'PromiseKit'
end
```

### Error

```
SignalException - SIGTERM
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/executable.rb:155:in `value'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/executable.rb:155:in `block in popen3'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open3.rb:217:in `popen_run'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open3.rb:99:in `popen3'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/executable.rb:150:in `popen3'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/executable.rb:63:in `execute_command'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/executable.rb:27:in `block in executable'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command/repo/add.rb:71:in `block in clone_repo'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command/repo/add.rb:69:in `chdir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command/repo/add.rb:69:in `clone_repo'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command/repo/add.rb:41:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command/repo/add.rb:39:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command/setup.rb:54:in `add_master_repo'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command/setup.rb:27:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command/setup.rb:21:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/sources_manager.rb:25:in `find_or_create_source_with_url'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:654:in `block in sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:653:in `map'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:653:in `sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:144:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:114:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command/update.rb:60:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by manuyavuz** [comment]
What's the integration result? Is it something like this:

```
Running task was terminated because it produced no activity for more than 600 seconds (use sudo xcrun xcscontrol --configure-integration-timeout to increase this timeout)
```
If so, this is most probably because `pod update` command does not finish until integration timeout is over, so it gets an interrupt from operating system, which causes above error.

Solution would be using `pod install` inside your prebuild script, and updating CocoaPods Specs repo manually from time to time. This is what I do while using Xcode Bots with CocoaPods.

**Comment by baltameme** [comment]
@manuyavuz  yes the result is as you mentioned. However, I tried to put the script as the following but still receive the same result:

export LANG=en_US.UTF-8
cd PROJECT_NAME
/usr/local/bin/pod install --verbose

Moreover, I tried also to change the integration-timeout to 900 seconds but still not resolved.

**Comment by manuyavuz** [comment]
Seems like your server does not have master Specs repo yet, so `pod install` internally calls `pod setup` command, and it does not complete operation on time because with new deep clone policy inside 1.0 version, first fetching of Specs repo may take long depending on your network bandwidth.

I suggest you to use terminal in your server and log into `_xcsbuildd` user, then run `pod setup` command there, and wait until operation is done. I'm pretty sure after that your integrations will start to work again.

**Comment by baltameme** [comment]
@manuyavuz thanks so much, your suggested command worked well however, the Bot gave me another error 

/Library/Developer/XcodeServer/Integrations/Caches/75abe5510f17fa7b280ec16e9c014369/Source/DawriPlus/DawriPlus/ViewServiceManager.swift:10:8: No such module 'SwiftyJSON'

Here's the 

Cocoapods integration log:

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-DawriPlus`: (``)

Resolving dependencies of `Podfile`

Comparing resolved specification to the sandbox manifest
  A OMGHTTPURLRQ
  A PromiseKit
  A SwiftyJSON

Downloading dependencies

-> Installing OMGHTTPURLRQ (3.1.2)
  > Copying OMGHTTPURLRQ from `/var/_xcsbuildd/Library/Caches/CocoaPods/Pods/Release/OMGHTTPURLRQ/3.1.2-38316` to `Pods/OMGHTTPURLRQ`

-> Installing PromiseKit (3.2.0)
  > Copying PromiseKit from `/var/_xcsbuildd/Library/Caches/CocoaPods/Pods/Release/PromiseKit/3.2.0-1db02` to `Pods/PromiseKit`

-> Installing SwiftyJSON (2.3.2)
  > Copying SwiftyJSON from `/var/_xcsbuildd/Library/Caches/CocoaPods/Pods/Release/SwiftyJSON/2.3.2-04cce` to `Pods/SwiftyJSON`
  - Running pre install hooks

Generating Pods project
  - Creating Pods project
  - Adding source files to Pods project
  - Adding frameworks to Pods project
  - Adding libraries to Pods project
  - Adding resources to Pods project
  - Linking headers
  - Installing targets
    - Installing target `OMGHTTPURLRQ` iOS 8.0
      - Generating Info.plist file at `Pods/Target Support Files/OMGHTTPURLRQ/Info.plist`
      - Generating module map file at `Pods/Target Support Files/OMGHTTPURLRQ/OMGHTTPURLRQ.modulemap`
      - Generating umbrella header at `Pods/Target Support Files/OMGHTTPURLRQ/OMGHTTPURLRQ-umbrella.h`
    - Installing target `PromiseKit` iOS 8.0
      - Generating Info.plist file at `Pods/Target Support Files/PromiseKit/Info.plist`
      - Copying module map file to `Pods/Target Support Files/PromiseKit/PromiseKit.modulemap`
    - Installing target `SwiftyJSON` iOS 8.0
      - Generating Info.plist file at `Pods/Target Support Files/SwiftyJSON/Info.plist`
      - Generating module map file at `Pods/Target Support Files/SwiftyJSON/SwiftyJSON.modulemap`
      - Generating umbrella header at `Pods/Target Support Files/SwiftyJSON/SwiftyJSON-umbrella.h`
    - Installing target `Pods-DawriPlus` iOS 8.0
      - Generating Info.plist file at `Pods/Target Support Files/Pods-DawriPlus/Info.plist`
      - Generating module map file at `Pods/Target Support Files/Pods-DawriPlus/Pods-DawriPlus.modulemap`
      - Generating umbrella header at `Pods/Target Support Files/Pods-DawriPlus/Pods-DawriPlus-umbrella.h`
  - Running post install hooks
  - Writing Xcode project file to `Pods/Pods.xcodeproj`
    - Generating deterministic UUIDs
  - Writing Lockfile in `Podfile.lock`
  - Writing Manifest in `Pods/Manifest.lock`

Integrating client project

Integrating target `Pods-DawriPlus` (`DawriPlus.xcodeproj` project)
  - Running post install hooks
    - cocoapods-stats from `/Library/Ruby/Gems/2.0.0/gems/cocoapods-stats-1.0.0/lib/cocoapods_plugin.rb`

Sending stats
      - OMGHTTPURLRQ, 3.1.2
      - PromiseKit, 3.2.0
      - SwiftyJSON, 2.3.2
  Pod installation complete! There are 2 dependencies from the Podfile and 3 total pods installed.

**Comment by manuyavuz** [comment]
Are you sure that your project works correctly on your machine? There is nothing wrong about the `pod install` process according to the log, so I don't think it's anymore related to CocoaPods.

I can suggest you to copy the contents in `/Library/Developer/XcodeServer/Integrations/Caches/75abe5510f17fa7b280ec16e9c014369/Source` to your local machine and try to run tests there, and check if anything is wrong. If error continues, try running `pod deintegrate`, and then `pod install`, and try again.

If error continues and you think it's still related to CocoaPods, please open a new issue with a sample project.

I'm closing this because CocoaPods has nothing to do about Xcode Server.
