### ISSUE TITLE
Pod update error

### ISSUE THREAD

**Issue by ngocthanh2207** [CocoaPods/CocoaPods#5478]
# What did you do?
I run pod update, some pod work done, but when update google/analytics something wrong

### Error

```
Errno::ENOENT - No such file or directory - /Users/phamngocthanh/Documents/Dropbox/ios/workspace/FreeLancer/Tintin/Pods/GoogleInterchangeUtilities/Frameworks/GoogleInterchangeUtilities.framework/Headers
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/sandbox/file_accessor.rb:161:in `realpath'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/sandbox/file_accessor.rb:161:in `realpath'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/sandbox/file_accessor.rb:161:in `vendored_frameworks_headers_dir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:239:in `block in vendored_frameworks_header_mappings'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:238:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:238:in `vendored_frameworks_header_mappings'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:140:in `block (3 levels) in link_headers'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:117:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:117:in `block (2 levels) in link_headers'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:116:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:116:in `block in link_headers'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:140:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:115:in `link_headers'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:41:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:562:in `install_file_references'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:152:in `block in generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:150:in `generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:110:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:156:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'

**Comment by segiddins** [comment]
Hi, can you try with CocoaPods 1.0.1? Thanks!

**Comment by neonichu** [comment]
Closing because of lack of activity.
