### ISSUE TITLE
Type checking error: got `Fixnum` for attribute: Attribute `runOnlyForDeploymentPostprocessing`

### ISSUE THREAD

**Issue by djfitz** [CocoaPods/CocoaPods#5489]
# Report
## What did you do?

Run `pod install`
## What did you expect to happen?

Install all pod dependencies correctly.
## What happened instead?

See output below
### Command

```
/usr/local/bin/pod install
```
### Installation Source

```
Executable Path: /usr/local/bin/pod
```
### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 6bf4a401cbc8ef493f620af74e7e55ef0d591287
```
### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```
### Podfile

``` ruby
source 'https://github.com/CocoaPods/Specs.git'

pod 'AFNetworking', '~> 2.6.3’
pod 'Crashlytics'
pod ‘Fabric’
pod 'UIAlertView+Blocks'
pod 'APAddressBook'
pod 'Realm', '~> 0.94.1'
pod 'NSString+RemoveEmoji'
pod 'KISSmetrics-iOS-SDK'
pod 'NSString-Hashes'
pod 'SocketRocket'
pod 'Fabric'
pod 'UrbanAirship-iOS-SDK'
```
### Error

Re-creating CocoaPods due to major version update.

```
RuntimeError - [Xcodeproj] Type checking error: got `Fixnum` for attribute: Attribute `runOnlyForDeploymentPostprocessing` (type: `simple`, classes: `[String]`, owner class: `AbstractBuildPhase`)
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.1.0/lib/xcodeproj/project/object_attributes.rb:141:in `validate_value'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.1.0/lib/xcodeproj/project/object_attributes.rb:318:in `block in attribute'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.1.0/lib/xcodeproj/project/object_attributes.rb:106:in `set_value'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.1.0/lib/xcodeproj/project/object.rb:283:in `block in configure_with_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.1.0/lib/xcodeproj/project/object.rb:282:in `each'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.1.0/lib/xcodeproj/project/object.rb:282:in `configure_with_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.1.0/lib/xcodeproj/project.rb:258:in `new_from_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.1.0/lib/xcodeproj/project/object.rb:350:in `object_with_uuid'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.1.0/lib/xcodeproj/project/object.rb:300:in `block (2 levels) in configure_with_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.1.0/lib/xcodeproj/project/object.rb:299:in `each'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.1.0/lib/xcodeproj/project/object.rb:299:in `block in configure_with_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.1.0/lib/xcodeproj/project/object.rb:296:in `each'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.1.0/lib/xcodeproj/project/object.rb:296:in `configure_with_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.1.0/lib/xcodeproj/project.rb:258:in `new_from_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.1.0/lib/xcodeproj/project/object.rb:350:in `object_with_uuid'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.1.0/lib/xcodeproj/project/object.rb:300:in `block (2 levels) in configure_with_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.1.0/lib/xcodeproj/project/object.rb:299:in `each'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.1.0/lib/xcodeproj/project/object.rb:299:in `block in configure_with_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.1.0/lib/xcodeproj/project/object.rb:296:in `each'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.1.0/lib/xcodeproj/project/object.rb:296:in `configure_with_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.1.0/lib/xcodeproj/project.rb:258:in `new_from_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.1.0/lib/xcodeproj/project.rb:202:in `initialize_from_file'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.1.0/lib/xcodeproj/project.rb:102:in `open'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:496:in `block (2 levels) in deintegrate_if_different_major_version'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:496:in `map'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:496:in `block in deintegrate_if_different_major_version'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:495:in `deintegrate_if_different_major_version'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:132:in `block in prepare'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:141:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:131:in `prepare'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:113:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command/install.rb:37:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by segiddins** [comment]
Can you please share your Xcode project? It sounds like its internal plist might be malformed

**Comment by djfitz** [comment]
Unfortunately this project is for a commercial app, and I can't post the Xcode project publicly. FWIW, the project builds and runs fine. I only got this error after upgrading cocoapods.

Is there something I can look at in the project that might indicate corruption?

**Comment by segiddins** [comment]
search it for `runOnlyForDeploymentPostprocessing` and make sure the value is a string instead of a number

**Comment by djfitz** [comment]
I looked through my project file and found an instance of a ```runOnlyForDeploymentPostprocessing``` key that is an integer. Is this de-facto evidence of corruption? I have no knowledge of Xcode project files, but wanted to see if this is actually true.

**Comment by segiddins** [comment]
It should be a string instead of an integer

**Comment by djfitz** [comment]
Is there definitive documentation that says this? Should I file a bug with Apple?

**Comment by djfitz** [comment]
FWIW, I changed the project file to make that key a string. pod install gets a little further but I get another error here

https://github.com/CocoaPods/CocoaPods/issues/5490
```[!] The dependency `AFNetworking (~> 2.6.3)` is not used in any concrete target.```
(and more errors for all entries in my podfile)

**Comment by segiddins** [comment]
Well that's fixed by putting your dependencies inside a target block

**Comment by dnkoutso** [comment]
@segiddins any action items here? I don't think its a cocoapods issue here.
