### ISSUE TITLE
Concrete error for loading podspecs via git should be shown

### ISSUE THREAD

**Issue by qteqoo** [CocoaPods/CocoaPods#5507]
# Report
## What did you do?

I created a custom public repo to test .podspec file for my own library. I added this repo as a source for a pod. I issued `pod install --verbose`.
## What did you expect to happen?

I expected to see `pod install --verbose` worked without errors.
## What happened instead?

I got an error which stated that it wasn't able to find a specification for my pod:

```
Preparing

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-test-ios-client`: (``)

Fetching external sources
-> Pre-downloading: `TestPodspec` from `https://github.com/mesmerizingr/TestPodspec.git`, tag `prod-0.1.0`
 > Git download
 > Git download
     $ /usr/bin/git clone https://github.com/mesmerizingr/TestPodspec.git
     /var/folders/74/mj6wg4_150s3_2r3p888_bl80000gp/T/d20160611-54891-1a2gvc3 --template= --single-branch --depth 1 --branch
     prod-0.1.0
     Cloning into '/var/folders/74/mj6wg4_150s3_2r3p888_bl80000gp/T/d20160611-54891-1a2gvc3'...
     Note: checking out '646ab61471cf9f7f1c1601e1cacd47fc19891250'.

     You are in 'detached HEAD' state. You can look around, make experimental
     changes and commit them, and you can discard any commits you make in this
     state without impacting any branches by performing another checkout.

     If you want to create a new branch to retain commits you create, you may
     do so (now or later) by using -b with the checkout command again. Example:

       git checkout -b <new-branch-name>

[!] Unable to find a specification for 'TestPodspec'.

/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/external_sources/abstract_external_source.rb:117:in `block in pre_download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:84:in `titled_section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/external_sources/abstract_external_source.rb:112:in `pre_download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/external_sources/downloader_source.rb:13:in `fetch'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:479:in `fetch_external_source'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:455:in `block (2 levels) in fetch_external_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:454:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:454:in `block in fetch_external_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:453:in `fetch_external_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:73:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:227:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:151:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:150:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:114:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command/install.rb:37:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'

[!] Unable to load a podspec from `TestPodspec.podspec`, skipping:

Pod::DSLError
```
### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 718ad1f05c2c6625d35f6f22ecf92a96248f3ed9
```
### Installation Source

```
Executable Path: /usr/local/bin/pod
```
### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```
### Podfile

``` ruby
platform :ios, "8.0"
use_frameworks!

target "test-ios-client" do
  pod "TestPodspec", :git => "https://github.com/mesmerizingr/TestPodspec.git", :tag => "prod-0.1.0"
end
```
## Project that demonstrates the issue

https://github.com/mesmerizingr/TestPodspec.git

**Comment by neonichu** [comment]
My guess is that the spec can't be loaded because of the invalid version here: https://github.com/mesmerizingr/TestPodspec/blob/master/TestPodspec.podspec#L4 and in case of fetching a spec via `git` this error is swallowed somehow.

Could you please try making sure the spec lints locally and then re-try?

**Comment by mesmerizingr** [comment]
@neonichu should specs' version be specifically formatted? Do you mean something close to '0.1.0' and without 'prod-' prefix?

As for the linter, would you like me to issue `pod spec lint --verbose` and paste output here? Did I understand you right?

**Comment by neonichu** [comment]
Yes, the version needs to follow semver, see https://guides.cocoapods.org/syntax/podspec.html#version — I don't think you need to paste the output, just make sure that `pod lib lint` succeeds successfully before using the podspec.

**Comment by mesmerizingr** [comment]
@neonichu you were absolutely right, here's the output:

```
 -> TestPodspec.podspec
    - ERROR | spec: The specification defined in `/Users/mesmerizingsnow/Developer/TestPodspec/TestPodspec.podspec` could not be loaded.


[!] Invalid `TestPodspec.podspec` file: Malformed version number string prod-0.1.0.

 #  from /Users/mesmerizingsnow/Developer/TestPodspec/TestPodspec.podspec:11
 #  -------------------------------------------
 #      :git => "https://github.com/mesmerizingr/TestPodspec.git",
 >      :tag => spec.version
 #    }
 #  -------------------------------------------


[!] /Users/mesmerizingsnow/Developer/TestPodspec/TestPodspec.podspec did not pass validation, due to 1 error.
You can use the `--no-clean` option to inspect any issue.

/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command/lib/lint.rb:75:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command/lib/lint.rb:47:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command/lib/lint.rb:47:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

I've already pushed new changes to the repository while the linter is in work and I have a gut feeling that my problem will have been resolved by the time it finishes 😎

Also, as I've already got your attention maybe you could explain me why does one need to set `spec.source` attribute in a .podspec file that sits alongside with a sources in a repo that IS actually the source? The documentation on the official site is rather poor on that and I've not found any explanation elsewhere.

**Comment by mesmerizingr** [comment]
<img width="1066" alt="screen shot 2016-06-12 at 12 05 33 am" src="https://cloud.githubusercontent.com/assets/13511218/15987447/823c5ca0-3031-11e6-8be8-c4a159f7fe2c.png">

Great, it works now 👍 Also note that this semantic versioning error doesn't actually show up in the output as the underlying error hiding behind more general and unrelated one which obscures users. Perhaps related issue should be created if not already.

**Comment by neonichu** [comment]
Yah, I agree — I just changed the name to reflect that we should look into not swallowing the concrete error in this case.

**Comment by mesmerizingr** [comment]
@neonichu as on my last question, would you mind answering? I would be very grateful, many thanks from me 😉

**Comment by neonichu** [comment]
@mesmerizingr just for consistency

**Comment by mesmerizingr** [comment]
@neonichu thanks for the answer!

**Comment by davidair** [comment]
I've tried testing this recently and I am getting a _Malformed version number string_ error when trying "pod install" with a podspec hosted on github that has a bad version string, so I am assuming this issue has been fixed.

**Comment by DanToml** [comment]
Awesome 👍
