### ISSUE TITLE
Illformed requirement `"1.0.9'"`

### ISSUE THREAD

**Issue by tyforfreedom** [CocoaPods/CocoaPods#5520]
I get an error.How can i do for it?

```
ArgumentError - Illformed requirement `"1.0.9'"`
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.39.0/lib/cocoapods-core/requirement.rb:63:in `parse'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.39.0/lib/cocoapods-core/requirement.rb:88:in `block in initialize'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.39.0/lib/cocoapods-core/requirement.rb:88:in `map!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.39.0/lib/cocoapods-core/requirement.rb:88:in `initialize'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.39.0/lib/cocoapods-core/requirement.rb:34:in `new'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.39.0/lib/cocoapods-core/requirement.rb:34:in `create'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.39.0/lib/cocoapods-core/dependency.rb:92:in `initialize'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.39.0/lib/cocoapods-core/specification/consumer.rb:180:in `new'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.39.0/lib/cocoapods-core/specification/consumer.rb:180:in `block in dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.39.0/lib/cocoapods-core/specification/consumer.rb:179:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.39.0/lib/cocoapods-core/specification/consumer.rb:179:in `map'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.39.0/lib/cocoapods-core/specification/consumer.rb:179:in `dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.39.0/lib/cocoapods-core/specification.rb:300:in `block in dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.39.0/lib/cocoapods-core/specification.rb:299:in `map'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.39.0/lib/cocoapods-core/specification.rb:299:in `dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.39.0/lib/cocoapods-core/specification.rb:308:in `all_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:130:in `dependencies_for'
/Library/Ruby/Gems/2.0.0/gems/molinillo-0.4.3/lib/molinillo/resolution.rb:131:in `block (2 levels) in <class:Resolution>'
/Library/Ruby/Gems/2.0.0/gems/molinillo-0.4.3/lib/molinillo/resolution.rb:419:in `require_nested_dependencies_for'
/Library/Ruby/Gems/2.0.0/gems/molinillo-0.4.3/lib/molinillo/resolution.rb:411:in `activate_spec'
/Library/Ruby/Gems/2.0.0/gems/molinillo-0.4.3/lib/molinillo/resolution.rb:376:in `attempt_to_activate_new_spec'
/Library/Ruby/Gems/2.0.0/gems/molinillo-0.4.3/lib/molinillo/resolution.rb:320:in `attempt_to_activate'
/Library/Ruby/Gems/2.0.0/gems/molinillo-0.4.3/lib/molinillo/resolution.rb:147:in `process_topmost_state'
/Library/Ruby/Gems/2.0.0/gems/molinillo-0.4.3/lib/molinillo/resolution.rb:72:in `resolve'
/Library/Ruby/Gems/2.0.0/gems/molinillo-0.4.3/lib/molinillo/resolver.rb:42:in `resolve'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:62:in `resolve'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:539:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:537:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:70:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:213:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:136:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:135:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:105:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:156:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

**Comment by segiddins** [comment]
What's the contents of your Podfile?

**Comment by mrackwitz** [comment]
From the error message, you have likely specified a single quote at the end of the version number in your Podfile. Removing that should resolve the issue.
