### ISSUE TITLE
Can not build a project after update to CocoaPods 1.0.1

### ISSUE THREAD

**Issue by gridNA** [CocoaPods/CocoaPods#5535]
- [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).
# Report
## What did you do?

1) update CocoaPods to 1.0.1
2) pod install
3) cleaned DerievedData
4) cleaned project
5) build
## What did you expect to happen?

The app should run as with previous version (0.39.0) of CocaPods
## What happened instead?

Receive a lot of linking errors
All the time error is different 
Mostly the ZalandoFoundation, ZMantle and Accengage is missing
## CocoaPods Environment 1.0.1

```
   Ruby : ruby 2.2.3
   RubyGems : 2.2.0
   Host : Mac OS X 10.11.4 (15E65)
   Xcode : 7.3
   Git : git version 2.7.4 (Apple Git-66)
```
## Podfile

```
require_relative 'scripts/xcode_helper'

def z_project(proj)
  xcodeproj "#{proj}/#{proj}"
end

source 'https://github.com/Accengage/CocoaPodsSpecs.git'
source 'https://stash.zalando.net/scm/shop-mobile/specs.git'
source 'https://github.com/CocoaPods/Specs'

platform :ios, '8.0'

inhibit_all_warnings!
use_frameworks!

def app
  pod 'AFNetworkActivityLogger', '2.0.4'
  pod 'Apptimize', '~> 2.16'
  pod 'CHTCollectionViewWaterfallLayout', '~> 0.9'
  pod 'GNAContextMenu', git: 'git://github.com/haldun/GNAContextMenu.git', branch: 'master'
  pod 'GoogleAppIndexing', '~> 2.0'
  pod 'HockeySDK', '~> 3'
  pod 'IntelligentSplitViewController', '~> 1.2'
  pod 'JLRoutes', git: 'https://github.com/diamondsky/JLRoutes.git', commit: 'a3bf7b19a7f2ea9705a74f5c056811165c150e98'
  pod 'JRSwizzle', '1.0'
  pod 'PEPhotoCropEditor', git: 'git://github.com/gdj4ever/PEPhotoCropEditor.git', tag: 'v1.3.3'
  pod 'Reachability', '3.2'
  pod 'RMDateSelectionViewController', '~> 1.5'
  pod 'SVPullToRefresh', '0.4.1'
  pod 'SwipeView', '1.3.2'
  pod 'Timepiece', '~> 0.4'
  pod 'ZDBCamera', '2.3.21'
end

def foundation
  pod 'Adjust/Criteo', '~> 4.6'
  pod 'AFNetworking', '~> 2.5'
  pod 'SDWebImage', '~> 3.7'
  pod 'TransformerKit', '0.5.4'
  pod 'TWMessageBarManager', git: 'ssh://git@stash.zalando.net:7999/~dgeorgakopou/twmessagebarmanager.git', branch: 'master'
  pod 'ZMantle', '~> 2.0'
  pod 'Accengage-iOS-SDK', '~> 5.5'
end

def animation
  pod 'zpop', '1.0.9'
end

def carousel
  pod 'iCarousel', '~> 1.8'
end

def forms
  pod '1PasswordExtension', '~> 1.8'
  pod 'TPKeyboardAvoiding', '~> 1.2'
  pod 'TTTAttributedLabel', '~> 1.13'
end

def account
  pod 'FXKeychain', '~> 1.5'
  #Fix for the issue https://github.com/mxcl/PromiseKit/issues/415
  #Please point to the original repo after it is fixed
  pod 'PromiseKit', git: 'https://github.com/yunuserenguzel/PromiseKit.git', branch: 'hot_fix'
  pod 'ZFormatterKit'
end

def article
  pod 'Agrume', '~> 2.2'
  pod 'JTSImageViewController', '~> 1.4'
end

def json_parsing
  pod 'ObjectMapper', '~> 1.2'
end

def flexible_layout
  json_parsing
end

def coupon_box
  pod 'Timepiece', '~> 0.4'
  pod 'RealmSwift', '~> 0.98'
  json_parsing
end

def common_tests
  pod 'ZTest', '0.1.3'
  pod 'SwiftHamcrest', '~> 0.4'
end

def all
  account
  animation
  app
  article
  carousel
  forms
  foundation
  flexible_layout
  coupon_box
end

# --- Targets

workspace 'zalando'
z_project 'zalando'

target :zalando do
  all
end

target :zalandoTests do
  common_tests
end

target :zalandoUITests do
  common_tests
  pod 'AMYServer', '~> 2.1'
  pod 'KIF/IdentifierTests', '3.2.2'
end

target :ZalandoFoundation do
  z_project 'ZalandoFoundation'
  pod 'Google/Analytics'
  pod 'GoogleIDFASupport'
  foundation
end

# --- Targets: Main App Modules

target :DeliveryTracking do
  z_project 'DeliveryTracking'
  foundation
  animation
end

target :FormBuilder do
  z_project 'FormBuilder'
  foundation
  forms
end

target :ZalandoAccount do
  z_project 'ZalandoAccount'
  foundation
  forms
  account
end

target :ZalandoArticle do
  z_project 'ZalandoArticle'
  foundation
  forms
  account
  article
end

target :ZalandoCarts do
  z_project 'ZalandoCarts'
  foundation
  forms
  account
end

target :ZTeaser do
  z_project 'ZTeaser'
  foundation
  carousel
end

# --- Targets: FlexibleLayoutKit

target :FlexibleLayoutKit do
  z_project 'FlexibleLayoutKit'
  flexible_layout
end

target :FlexibleLayoutDemo do
  z_project 'FlexibleLayoutKit'
  flexible_layout
end

target :FlexibleLayoutKitTests do
  z_project 'FlexibleLayoutKit'
  common_tests
end

target :FlexibleLayoutDemoTests do
  z_project 'FlexibleLayoutKit'
  common_tests
end

# --- Targets: ZalandoFilters

target :ZalandoFilters do
  z_project 'ZalandoFilters'
  json_parsing
end

target :ZalandoFiltersTests do
  z_project 'ZalandoFilters'
  common_tests
end

# --- Targets: CouponBox

target :CouponBox do
  z_project 'CouponBox'
  coupon_box
end

target :CouponBoxTests do
  z_project 'CouponBox'
  common_tests
end

# --- Scripts

post_install do |installer|
  update_pods_builds_settings(installer)
  XcodeHelper.update_projects_build_settings
  XcodeHelper.convert_projects_to_plist_format
end

def update_pods_builds_settings(installer)
  installer.pods_project.targets.each do |target|
    XcodeHelper.set_default_build_settings(target)
  end
end
```

**Comment by segiddins** [comment]
Is one of those targets a framework target?

**Comment by gridNA** [comment]
all of them are frameworks, except zalando.

**Comment by segiddins** [comment]
Integrating into framework targets is unsupported, although we have an open PR for that

**Comment by gridNA** [comment]
great, will wait for updates

**Comment by neitzj** [comment]
@segiddins: Can you post a link to that pull request. I just upgraded to cocoapods 1.0 and I think I'm having the sample problem. Thanks.

**Comment by segiddins** [comment]
https://github.com/CocoaPods/CocoaPods/pull/5502

**Comment by DanToml** [comment]
@gridNA Please can you try this on `1.1.0.beta.1`?

**Comment by gridNA** [comment]
Hi @DanToml,
I tried on `1.1.0.beta.1 `and got this error:

`Unable to find host target for Pods-ZalandoFoundation, Pods-DeliveryTracking, Pods-FormBuilder, Pods-ZalandoAccount, Pods-ZalandoArticle, Pods-ZalandoCarts, Pods-ZTeaser. Please add the host targets for the embedded targets to the Podfile.`

**Comment by benasher44** [comment]
@gridNA several PRs have merged recently to help address this. Can you try using CocoaPods master?

**Comment by gridNA** [comment]
Hi @benasher44,

I used CocoaPods master, and did not get this problem anymore, although I've got another one. In `Podfile` we need to run configuration script `require_relative 'scripts/xcode_helper'` but wheen I run pod install I got this error:

```
[!] Invalid `Podfile` file: cannot load such file -- work_queue.

 #  from /Users/kgridina/fashion-store/Podfile:1
 #  -------------------------------------------
 >  require_relative 'scripts/xcode_helper'
 #
 #  -------------------------------------------
```

When I commented out `require_relative 'scripts/xcode_helper'` - pod install worked as a charm. Do you have any ideas why `xcode_helper` script can not be loaded?

**Comment by segiddins** [comment]
I'd change your podfile to 

```ruby
begin
  require_relative 'scripts/xcode_helper'
rescue LoadError => e
  warn e
  warn e.backtrace
  raise
end
```

So you can see the full backtrace to the load error

**Comment by gridNA** [comment]
Hi @segiddins,

Thanks for help. I got a backtrace:

```
cannot load such file -- work_queue
/Users/kgridina/fashion-store/scripts/xcode_helper.rb:3:in `require'
/Users/kgridina/fashion-store/scripts/xcode_helper.rb:3:in `<top (required)>'
/Users/kgridina/fashion-store/Podfile:2:in `require_relative'
/Users/kgridina/fashion-store/Podfile:2:in `block in from_ruby'
/Users/kgridina/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/Core-db99f5e8b938/lib/cocoapods-core/podfile.rb:290:in `eval'
/Users/kgridina/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/Core-db99f5e8b938/lib/cocoapods-core/podfile.rb:290:in `block in from_ruby'
/Users/kgridina/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/Core-db99f5e8b938/lib/cocoapods-core/podfile.rb:50:in `instance_eval'
/Users/kgridina/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/Core-db99f5e8b938/lib/cocoapods-core/podfile.rb:50:in `initialize'
/Users/kgridina/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/Core-db99f5e8b938/lib/cocoapods-core/podfile.rb:286:in `new'
/Users/kgridina/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/Core-db99f5e8b938/lib/cocoapods-core/podfile.rb:286:in `from_ruby'
/Users/kgridina/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/Core-db99f5e8b938/lib/cocoapods-core/podfile.rb:252:in `from_file'
/Users/kgridina/cocoapods/CocoaPods/lib/cocoapods/config.rb:191:in `podfile'
/Users/kgridina/cocoapods/CocoaPods/lib/cocoapods/command.rb:123:in `verify_podfile_exists!'
/Users/kgridina/cocoapods/CocoaPods/lib/cocoapods/command/install.rb:33:in `run'
/Users/kgridina/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/CLAide-61071679fc96/lib/claide/command.rb:334:in `run'
/Users/kgridina/cocoapods/CocoaPods/lib/cocoapods/command.rb:50:in `run'
/Users/kgridina/cocoapods/CocoaPods/bin/pod:55:in `<main>'
```

**Comment by segiddins** [comment]
Seems to be an issue with you `xcode_helper` script rather than something in CocoaPods

**Comment by gridNA** [comment]
@segiddins  Hm, this is strange, because on ```CocoaPods 0.39.0``` it works perfectly fine. I also checked that gem ```work_queue``` exists in ruby gems. 
It would be great if you can run test ```Podspec``` with some script, that has ```require 'work_queue'```. 
Also it can be something wrong with the paths though. 
Maybe you have any idea why it is happening only in CocoaPod 1.0.1?

**Comment by segiddins** [comment]
No clue without seeing all of the moving parts in question

**Comment by gridNA** [comment]
Hi @segiddins I replaced work_queue library with a system one `require 'thread'`,  pulled latest Master branch from CocoaPods, and got this error:

```
NoMethodError - undefined method 'platform' for nil:NilClass
/Users/kgridina/cocoapods/CocoaPods/lib/cocoapods/installer/analyzer.rb:320:in 'block in analyze_host_targets_in_podfile'
/Users/kgridina/cocoapods/CocoaPods/lib/cocoapods/installer/analyzer.rb:329:in 'call'
/Users/kgridina/cocoapods/CocoaPods/lib/cocoapods/installer/analyzer.rb:329:in 'block (2 levels) in analyze_host_targets_in_podfile'
/Users/kgridina/cocoapods/CocoaPods/lib/cocoapods/installer/analyzer.rb:328:in 'each'
/Users/kgridina/cocoapods/CocoaPods/lib/cocoapods/installer/analyzer.rb:328:in 'block in analyze_host_targets_in_podfile'
/Users/kgridina/cocoapods/CocoaPods/lib/cocoapods/installer/analyzer.rb:326:in 'each'
/Users/kgridina/cocoapods/CocoaPods/lib/cocoapods/installer/analyzer.rb:326:in 'analyze_host_targets_in_podfile'
/Users/kgridina/cocoapods/CocoaPods/lib/cocoapods/installer/analyzer.rb:354:in 'generate_targets'
/Users/kgridina/cocoapods/CocoaPods/lib/cocoapods/installer/analyzer.rb:78:in 'analyze'
/Users/kgridina/cocoapods/CocoaPods/lib/cocoapods/installer.rb:236:in 'analyze'
/Users/kgridina/cocoapods/CocoaPods/lib/cocoapods/installer.rb:150:in 'block in resolve_dependencies'
/Users/kgridina/cocoapods/CocoaPods/lib/cocoapods/user_interface.rb:64:in 'section'
/Users/kgridina/cocoapods/CocoaPods/lib/cocoapods/installer.rb:149:in 'resolve_dependencies'
/Users/kgridina/cocoapods/CocoaPods/lib/cocoapods/installer.rb:110:in 'install!'
/Users/kgridina/cocoapods/CocoaPods/lib/cocoapods/command/install.rb:37:in 'run'
/Users/kgridina/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/CLAide-61071679fc96/lib/claide/command.rb:334:in 'run'
/Users/kgridina/cocoapods/CocoaPods/lib/cocoapods/command.rb:50:in 'run'
/Users/kgridina/cocoapods/CocoaPods/bin/pod:55:in '<main>'
```
It might be related for this issue - https://github.com/CocoaPods/CocoaPods/issues/4887 or this one https://github.com/CocoaPods/CocoaPods/issues/5427

**Comment by segiddins** [comment]
Please open a separate issue for that

**Comment by gridNA** [comment]
Done https://github.com/CocoaPods/CocoaPods/issues/5783

**Comment by gridNA** [comment]
bug #5783 was fixed and closed, but I still have issues with building the project. I got an error:

`<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Headers/ZalandoFoundation.h"
        ^
/Users/kgridina/fashion-store/ZalandoFoundation/ZalandoFoundation/ZalandoFoundation.h:94:9: note: in file included from /Users/kgridina/fashion-store/ZalandoFoundation/ZalandoFoundation/ZalandoFoundation.h:94:
#import "TrackableViewController.h"
        ^
/Users/kgridina/fashion-store/ZalandoFoundation/ZalandoFoundation/accengage/TrackableViewController.h:5:9: error: 'AccengageKit/BMA4SViewController.h' file not found
#import <AccengageKit/BMA4SViewController.h>
        ^
<unknown>:0: error: could not build Objective-C module 'ZalandoFoundation'`

**Comment by benasher44** [comment]
@gridNA this is a build error? In which target is the error occurring?

**Comment by gridNA** [comment]
@benasher44 it is the error inside `ZalandoFoundation`
In attached file you can see the error list.
<img width="731" alt="screen shot 2016-08-29 at 15 34 52" src="https://cloud.githubusercontent.com/assets/2902842/18053134/4e818006-6dfe-11e6-845b-a228f6fbe7ca.png">

**Comment by benasher44** [comment]
@gridNA can you click on the button on the right edge there next to `BitlyClient.swift` and copy paste the output so we can see the include paths? Then, I'd also like to see the state/screenshot of your built products directory (`~/Library/Developer/Xcode/DerivedData/<Project-SomeUUID>/Build/Products/Debug-iphonesimulator/`).

**Comment by gridNA** [comment]
@benasher44 Here is it:

````
CompileSwift normal arm64 /Users/kgridina/fashion-store/ZalandoFoundation/ZalandoFoundation/BitlyClient.swift
    cd /Users/kgridina/fashion-store/ZalandoFoundation
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -frontend -c /Users/kgridina/fashion-store/ZalandoFoundation/ZalandoFoundation/apptimize/ABTest.swift /Users/kgridina/fashion-store/ZalandoFoundation/ZalandoFoundation/apptimize/ABTestTrackingFormatter.swift /Users/kgridina/fashion-store/ZalandoFoundation/ZalandoFoundation/apptimize/ABTester.swift /Users/kgridina/fashion-store/ZalandoFoundation/ZalandoFoundation/apptimize/ABTestingGateway.swift /Users/kgridina/fashion-store/ZalandoFoundation/ZalandoFoundation/accengage/AccengageInAppNotificationDataSource.swift /Users/kgridina/fashion-store/ZalandoFoundation/ZalandoFoundation/accengage/AccengageTracker.swift /Users/kgridina/fashion-store/ZalandoFoundation/ZalandoFoundation/other/AppConfiguration.swift -primary-file /Users/kgridina/fashion-store/ZalandoFoundation/ZalandoFoundation/BitlyClient.swift /Users/kgridina/fashion-store/ZalandoFoundation/ZalandoFoundation/tracking/CartViewControllerTrackingHelper.swift /Users/kgridina/fashion-store/ZalandoFoundation/ZalandoFoundation/other/CustomNavigationDelegate.swift /Users/kgridina/fashion-store/ZalandoFoundation/ZalandoFoundation/extensions/foundation/DebugUtil.swift /Users/kgridina/fashion-store/ZalandoFoundation/ZalandoFoundation/networking/EnablePhoneLinksUserScript.swift /Users/kgridina/fashion-store/ZalandoFoundation/ZalandoFoundation/extensions/foundation/ErrorPrinter.swift /Users/kgridina/fashion-store/ZalandoFoundation/ZalandoFoundation/other/FeatureToggle.swift /Users/kgridina/fashion-store/ZalandoFoundation/ZalandoFoundation/FileMockProvider.swift /Users/kgridina/fashion-store/ZalandoFoundation/ZalandoFoundation/extensions/foundation/FoundationExtensions.swift /Users/kgridina/fashion-store/ZalandoFoundation/ZalandoFoundation/other/GCDHelper.swift /Users/kgridina/fashion-store/ZalandoFoundation/ZalandoFoundation/InterProcessCommunication/InterProcessCommunicationView.swift /Users/kgridina/fashion-store/ZalandoFoundation/ZalandoFoundation/InterProcessCommunication/InterProcessCommunicator.swift /Users/kgridina/fashion-store/ZalandoFoundation/ZalandoFoundation/networking/MonitoringURLProtocol.swift /Users/kgridina/fashion-store/ZalandoFoundation/ZalandoFoundation/fallback/NewLoginRequiredFallbackViewController.swift /Users/kgridina/fashion-store/ZalandoFoundation/ZalandoFoundation/NotificationsConstants.swift /Users/kgridina/fashion-store/ZalandoFoundation/ZalandoFoundation/ObjectCache.swift /Users/kgridina/fashion-store/ZalandoFoundation/ZalandoFoundation/PartnerWebViewController.swift /Users/kgridina/fashion-store/ZalandoFoundation/ZalandoFoundation/RemoteLog.swift /Users/kgridina/fashion-store/ZalandoFoundation/ZalandoFoundation/search/SearchIndexService.swift /Users/kgridina/fashion-store/ZalandoFoundation/ZalandoFoundation/search/SearchUseCase.swift /Users/kgridina/fashion-store/ZalandoFoundation/ZalandoFoundation/Sharing.swift /Users/kgridina/fashion-store/zalando/zalando/vendor/Siren/Siren.swift /Users/kgridina/fashion-store/ZalandoFoundation/ZalandoFoundation/extensions/uikit/UIKitExtensions.swift /Users/kgridina/fashion-store/ZalandoFoundation/ZalandoFoundation/extensions/foundation/UIViewController+UserActivity.swift /Users/kgridina/fashion-store/zalando/zalando/UpdateNotifier.swift /Users/kgridina/fashion-store/ZalandoFoundation/ZalandoFoundation/networking/WebViewController.swift /Users/kgridina/fashion-store/ZalandoFoundation/ZalandoFoundation/entities/ZCategory+SearchableItem.swift /Users/kgridina/fashion-store/ZalandoFoundation/ZalandoFoundation/deviceInfo/ZDevice.swift /Users/kgridina/fashion-store/ZalandoFoundation/ZalandoFoundation/localization/ZSwiftLocalization.swift /Users/kgridina/fashion-store/ZalandoFoundation/ZalandoFoundation/other/ZTeaserGender.swift /Users/kgridina/fashion-store/ZalandoFoundation/ZalandoFoundation/other/ZUserDefaults.swift /Users/kgridina/fashion-store/ZalandoFoundation/ZalandoFoundation/other/ZalandoActivityIndicator.swift -target arm64-apple-ios8.0 -Xllvm -aarch64-use-tbi -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk -I /Users/kgridina/Library/Developer/Xcode/DerivedData/zalando-hblhlwtypexjckaoxhxfvgbrsgmg/Build/Products/Debug-iphoneos -F /Users/kgridina/Library/Developer/Xcode/DerivedData/zalando-hblhlwtypexjckaoxhxfvgbrsgmg/Build/Products/Debug-iphoneos -F /Users/kgridina/fashion-store/ZalandoFoundation/../zalando/zalando/vendor -F /Users/kgridina/Library/Developer/Xcode/DerivedData/zalando-hblhlwtypexjckaoxhxfvgbrsgmg/Build/Products/Debug-iphoneos/AFNetworking -F /Users/kgridina/Library/Developer/Xcode/DerivedData/zalando-hblhlwtypexjckaoxhxfvgbrsgmg/Build/Products/Debug-iphoneos/Accengage-iOS-SDK -F /Users/kgridina/Library/Developer/Xcode/DerivedData/zalando-hblhlwtypexjckaoxhxfvgbrsgmg/Build/Products/Debug-iphoneos/Adjust -F /Users/kgridina/Library/Developer/Xcode/DerivedData/zalando-hblhlwtypexjckaoxhxfvgbrsgmg/Build/Products/Debug-iphoneos/SDWebImage -F /Users/kgridina/Library/Developer/Xcode/DerivedData/zalando-hblhlwtypexjckaoxhxfvgbrsgmg/Build/Products/Debug-iphoneos/TWMessageBarManager -F /Users/kgridina/Library/Developer/Xcode/DerivedData/zalando-hblhlwtypexjckaoxhxfvgbrsgmg/Build/Products/Debug-iphoneos/TransformerKit -F /Users/kgridina/Library/Developer/Xcode/DerivedData/zalando-hblhlwtypexjckaoxhxfvgbrsgmg/Build/Products/Debug-iphoneos/ZMantle -F /Users/kgridina/fashion-store/ZalandoFoundation/../Pods/AppDynamicsAgent/iOSAgent-4.2.3.1 -F /Users/kgridina/fashion-store/ZalandoFoundation/../Pods/FirebaseAnalytics/Frameworks/frameworks -F /Users/kgridina/fashion-store/ZalandoFoundation/../Pods/FirebaseInstanceID/Frameworks/frameworks -F /Users/kgridina/fashion-store/ZalandoFoundation/../Pods/Google/Frameworks -F /Users/kgridina/fashion-store/ZalandoFoundation/../Pods/GoogleInterchangeUtilities/Frameworks -F /Users/kgridina/fashion-store/ZalandoFoundation/../Pods/GoogleSymbolUtilities/Frameworks -F /Users/kgridina/fashion-store/ZalandoFoundation/../Pods/GoogleUtilities/Frameworks -enable-testing -g -import-underlying-module -module-cache-path /Users/kgridina/Library/Developer/Xcode/DerivedData/ModuleCache -D DEBUG -serialize-debugging-options -Xcc -I/Users/kgridina/Library/Developer/Xcode/DerivedData/zalando-hblhlwtypexjckaoxhxfvgbrsgmg/Build/Intermediates/ZalandoFoundation.build/Debug-iphoneos/ZalandoFoundation.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/kgridina/Library/Developer/Xcode/DerivedData/zalando-hblhlwtypexjckaoxhxfvgbrsgmg/Build/Intermediates/ZalandoFoundation.build/Debug-iphoneos/ZalandoFoundation.build/ZalandoFoundation-generated-files.hmap -Xcc -I/Users/kgridina/Library/Developer/Xcode/DerivedData/zalando-hblhlwtypexjckaoxhxfvgbrsgmg/Build/Intermediates/ZalandoFoundation.build/Debug-iphoneos/ZalandoFoundation.build/ZalandoFoundation-own-target-headers.hmap -Xcc -I/Users/kgridina/Library/Developer/Xcode/DerivedData/zalando-hblhlwtypexjckaoxhxfvgbrsgmg/Build/Intermediates/ZalandoFoundation.build/Debug-iphoneos/ZalandoFoundation.build/ZalandoFoundation-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc /Users/kgridina/Library/Developer/Xcode/DerivedData/zalando-hblhlwtypexjckaoxhxfvgbrsgmg/Build/Intermediates/ZalandoFoundation.build/all-product-headers.yaml -Xcc -iquote -Xcc /Users/kgridina/Library/Developer/Xcode/DerivedData/zalando-hblhlwtypexjckaoxhxfvgbrsgmg/Build/Intermediates/ZalandoFoundation.build/Debug-iphoneos/ZalandoFoundation.build/ZalandoFoundation-project-headers.hmap -Xcc -I/Users/kgridina/Library/Developer/Xcode/DerivedData/zalando-hblhlwtypexjckaoxhxfvgbrsgmg/Build/Products/Debug-iphoneos/include -Xcc -I/Users/kgridina/fashion-store/ZalandoFoundation/../Pods/Google/Headers -Xcc -I/Users/kgridina/fashion-store/ZalandoFoundation/../Pods/Headers/Public -Xcc -I/Users/kgridina/fashion-store/ZalandoFoundation/../Pods/Headers/Public/AppDynamicsAgent -Xcc -I/Users/kgridina/fashion-store/ZalandoFoundation/../Pods/Headers/Public/Apptimize -Xcc -I/Users/kgridina/fashion-store/ZalandoFoundation/../Pods/Headers/Public/FirebaseAnalytics -Xcc -I/Users/kgridina/fashion-store/ZalandoFoundation/../Pods/Headers/Public/FirebaseInstanceID -Xcc -I/Users/kgridina/fashion-store/ZalandoFoundation/../Pods/Headers/Public/Google -Xcc -I/Users/kgridina/fashion-store/ZalandoFoundation/../Pods/Headers/Public/GoogleAnalytics -Xcc -I/Users/kgridina/fashion-store/ZalandoFoundation/../Pods/Headers/Public/GoogleAppIndexing -Xcc -I/Users/kgridina/fashion-store/ZalandoFoundation/../Pods/Headers/Public/GoogleIDFASupport -Xcc -I/Users/kgridina/fashion-store/ZalandoFoundation/../Pods/Headers/Public/GoogleInterchangeUtilities -Xcc -I/Users/kgridina/fashion-store/ZalandoFoundation/../Pods/Headers/Public/GoogleSymbolUtilities -Xcc -I/Users/kgridina/fashion-store/ZalandoFoundation/../Pods/Headers/Public/GoogleUtilities -Xcc -I/Users/kgridina/fashion-store/ZalandoFoundation/../Pods/Headers/Public/HockeySDK -Xcc -I/Users/kgridina/Library/Developer/Xcode/DerivedData/zalando-hblhlwtypexjckaoxhxfvgbrsgmg/Build/Intermediates/ZalandoFoundation.build/Debug-iphoneos/ZalandoFoundation.build/DerivedSources/arm64 -Xcc -I/Users/kgridina/Library/Developer/Xcode/DerivedData/zalando-hblhlwtypexjckaoxhxfvgbrsgmg/Build/Intermediates/ZalandoFoundation.build/Debug-iphoneos/ZalandoFoundation.build/DerivedSources -Xcc -DDEBUG=1 -Xcc -DCOCOAPODS=1 -Xcc -DCOCOAPODS=1 -Xcc -ivfsoverlay -Xcc /Users/kgridina/Library/Developer/Xcode/DerivedData/zalando-hblhlwtypexjckaoxhxfvgbrsgmg/Build/Intermediates/ZalandoFoundation.build/Debug-iphoneos/ZalandoFoundation.build/unextended-module-overlay.yaml -Xcc -working-directory/Users/kgridina/fashion-store/ZalandoFoundation -emit-module-doc-path /Users/kgridina/Library/Developer/Xcode/DerivedData/zalando-hblhlwtypexjckaoxhxfvgbrsgmg/Build/Intermediates/ZalandoFoundation.build/Debug-iphoneos/ZalandoFoundation.build/Objects-normal/arm64/BitlyClient~partial.swiftdoc -Onone -module-name ZalandoFoundation -emit-module-path /Users/kgridina/Library/Developer/Xcode/DerivedData/zalando-hblhlwtypexjckaoxhxfvgbrsgmg/Build/Intermediates/ZalandoFoundation.build/Debug-iphoneos/ZalandoFoundation.build/Objects-normal/arm64/BitlyClient~partial.swiftmodule -serialize-diagnostics-path /Users/kgridina/Library/Developer/Xcode/DerivedData/zalando-hblhlwtypexjckaoxhxfvgbrsgmg/Build/Intermediates/ZalandoFoundation.build/Debug-iphoneos/ZalandoFoundation.build/Objects-normal/arm64/BitlyClient.dia -emit-dependencies-path /Users/kgridina/Library/Developer/Xcode/DerivedData/zalando-hblhlwtypexjckaoxhxfvgbrsgmg/Build/Intermediates/ZalandoFoundation.build/Debug-iphoneos/ZalandoFoundation.build/Objects-normal/arm64/BitlyClient.d -emit-reference-dependencies-path /Users/kgridina/Library/Developer/Xcode/DerivedData/zalando-hblhlwtypexjckaoxhxfvgbrsgmg/Build/Intermediates/ZalandoFoundation.build/Debug-iphoneos/ZalandoFoundation.build/Objects-normal/arm64/BitlyClient.swiftdeps -o /Users/kgridina/Library/Developer/Xcode/DerivedData/zalando-hblhlwtypexjckaoxhxfvgbrsgmg/Build/Intermediates/ZalandoFoundation.build/Debug-iphoneos/ZalandoFoundation.build/Objects-normal/arm64/BitlyClient.o

<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Headers/ZalandoFoundation.h"
        ^
/Users/kgridina/fashion-store/ZalandoFoundation/ZalandoFoundation/ZalandoFoundation.h:94:9: note: in file included from /Users/kgridina/fashion-store/ZalandoFoundation/ZalandoFoundation/ZalandoFoundation.h:94:
#import "TrackableViewController.h"
        ^
/Users/kgridina/fashion-store/ZalandoFoundation/ZalandoFoundation/accengage/TrackableViewController.h:5:9: error: 'AccengageKit/BMA4SViewController.h' file not found
#import <AccengageKit/BMA4SViewController.h>
        ^
<unknown>:0: error: could not build Objective-C module 'ZalandoFoundation'
![screen shot 2016-08-31 at 11 47 14](https://cloud.githubusercontent.com/assets/2902842/18124029/d759a502-6f70-11e6-8206-efee6b6beaf5.png)
![screen shot 2016-08-31 at 11 47 38](https://cloud.githubusercontent.com/assets/2902842/18124027/d758123c-6f70-11e6-839a-aee914a0897c.png)
![screen shot 2016-08-31 at 11 47 58](https://cloud.githubusercontent.com/assets/2902842/18124030/d75ad594-6f70-11e6-9f1b-bf8aa081fdd0.png)
![screen shot 2016-08-31 at 11 48 06](https://cloud.githubusercontent.com/assets/2902842/18124028/d758d302-6f70-11e6-892a-aab33570d638.png)
![screen shot 2016-08-31 at 11 47 14](https://cloud.githubusercontent.com/assets/2902842/18124092/03646754-6f71-11e6-9e5f-94d1e9bdcf03.png)
![screen shot 2016-08-31 at 11 47 38](https://cloud.githubusercontent.com/assets/2902842/18124091/03639428-6f71-11e6-8aef-1820a8a670ac.png)
![screen shot 2016-08-31 at 11 47 58](https://cloud.githubusercontent.com/assets/2902842/18124094/036ac3ce-6f71-11e6-9a8f-90291ab94e93.png)
![screen shot 2016-08-31 at 11 48 06](https://cloud.githubusercontent.com/assets/2902842/18124090/0363a8b4-6f71-11e6-8b5d-8d99a07ccce1.png)




````

**Comment by benasher44** [comment]
Can I see what's in the Accengage-iOS-SDK folder?

**Comment by gridNA** [comment]
@benasher44 Here are the files:
![screen shot 2016-08-31 at 16 17 43](https://cloud.githubusercontent.com/assets/2902842/18132280/803a5c1e-6f96-11e6-819e-667fd43b120e.png)

**Comment by benasher44** [comment]
That's interesting. @mrackwitz (helpful when I was having these issues in the CocoaPods 1.0 betas) would you expect it be able to find the header in `/Users/kgridina/Library/Developer/Xcode/DerivedData/zalando-hblhlwtypexjckaoxhxfvgbrsgmg/Build/Products/Debug-iphoneos/Accensgage-iOS-SDK/BMA4SSDK/BMA4SViewController/BMA4SViewController.h` with the include path as `-F /Users/kgridina/Library/Developer/Xcode/DerivedData/zalando-hblhlwtypexjckaoxhxfvgbrsgmg/Build/Products/Debug-iphoneos/Accengage-iOS-SDK`?

**Comment by gridNA** [comment]
@benasher44 hi, are there any updates?

**Comment by benasher44** [comment]
Unfortunately there are no updates. I might have more time to look into this next week, but at the moment my attention is taken mostly by Xcode 8 and Swift support.

**Comment by benasher44** [comment]
@gridNA I think we've narrowed it down together to something being the matter with framework search paths in this particular case. I encourage you clone CocoaPods and have a look around in the meantime. I'd probably start by working backwards from one of the generators in `lib/cocoapods/generator/xcconfig/`, since those ultimately spit out the settings we're concerned about here.

**Comment by benasher44** [comment]
@gridNA I've been staring at this some more, and I think the best way to fix this is to ask the vendor publishing the spec to fix the pod spec. Since this is a framework search path, it's looking in the Headers folder for your header, not finding it there, and then giving up. This make sense, since framework bundles always have the Headers folder where all public headers are located.

Possible podspec fixes:
- Move the `BMA4SViewController` folder and its contents into the Headers folder
- Add a custom module map that specifies all of the available headers (not 100% sure this will work)

In any case, I think the main issue here is the structure of the project and how that's communicated via the podspec. As of 1.0, CocoaPods is probably more rigid about this, via the search paths it generates, which is why you're seeing this now.

**Comment by DanToml** [comment]
Closing due to lack of activity, but it seems that @benasher44's solution is the most reasonable one here.
