### ISSUE TITLE
Error: Unable to convert Ruby value `"Alamofire"' into a CFTypeRef

### ISSUE THREAD

**Issue by yujtah** [CocoaPods/CocoaPods#5536]
### Command

```
/Users/yujtah/.rvm/gems/ruby-2.2.0/bin/pod install
```

### Report

* I'm trying to install SwiftyDropbox pod

* I'm getting an error instead, after "pod install"

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]
    RubyGems : 2.4.6
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /Users/yujtah/.rvm/rubies/ruby-2.2.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 4c1e1956f1eb7e377ee513a406c4a1bd73fa95d0
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

### Podfile

```ruby
platform :ios, '9.0'
use_frameworks!

target 'Drptst' do
  pod 'SwiftyDropbox'
end
```

### Error

```
TypeError - Unable to convert Ruby value `"Alamofire"' into a CFTypeRef.
/Users/yujtah/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.1.0/lib/xcodeproj/plist/ffi/core_foundation.rb:383:in `RubyValueToCFTypeRef'
/Users/yujtah/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.1.0/lib/xcodeproj/plist/ffi/core_foundation.rb:402:in `block in RubyHashToCFDictionary'
/Users/yujtah/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.1.0/lib/xcodeproj/plist/ffi/core_foundation.rb:400:in `each'
/Users/yujtah/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.1.0/lib/xcodeproj/plist/ffi/core_foundation.rb:400:in `RubyHashToCFDictionary'
/Users/yujtah/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.1.0/lib/xcodeproj/plist/ffi/core_foundation.rb:372:in `RubyValueToCFTypeRef'
/Users/yujtah/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.1.0/lib/xcodeproj/plist/ffi/core_foundation.rb:402:in `block in RubyHashToCFDictionary'
/Users/yujtah/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.1.0/lib/xcodeproj/plist/ffi/core_foundation.rb:400:in `each'
/Users/yujtah/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.1.0/lib/xcodeproj/plist/ffi/core_foundation.rb:400:in `RubyHashToCFDictionary'
/Users/yujtah/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.1.0/lib/xcodeproj/plist/ffi/core_foundation.rb:372:in `RubyValueToCFTypeRef'
/Users/yujtah/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.1.0/lib/xcodeproj/plist/ffi/core_foundation.rb:402:in `block in RubyHashToCFDictionary'
/Users/yujtah/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.1.0/lib/xcodeproj/plist/ffi/core_foundation.rb:400:in `each'
/Users/yujtah/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.1.0/lib/xcodeproj/plist/ffi/core_foundation.rb:400:in `RubyHashToCFDictionary'
/Users/yujtah/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.1.0/lib/xcodeproj/plist/ffi.rb:103:in `ruby_hash_write_xcode'
/Users/yujtah/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.1.0/lib/xcodeproj/plist/ffi.rb:40:in `write_to_path'
/Users/yujtah/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.1.0/lib/xcodeproj/plist.rb:46:in `write_to_path'
/Users/yujtah/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.1.0/lib/xcodeproj/project.rb:332:in `save'
/Users/yujtah/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:696:in `block in write_pod_project'
/Users/yujtah/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:141:in `message'
/Users/yujtah/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:688:in `write_pod_project'
/Users/yujtah/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:173:in `block in generate_pods_project'
/Users/yujtah/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/Users/yujtah/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:167:in `generate_pods_project'
/Users/yujtah/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:119:in `install!'
/Users/yujtah/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.0.1/lib/cocoapods/command/install.rb:37:in `run'
/Users/yujtah/.rvm/gems/ruby-2.2.0@global/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Users/yujtah/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'
/Users/yujtah/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
/Users/yujtah/.rvm/gems/ruby-2.2.0/bin/pod:23:in `load'
/Users/yujtah/.rvm/gems/ruby-2.2.0/bin/pod:23:in `<main>'
/Users/yujtah/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
/Users/yujtah/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by segiddins** [comment]
This is a known bug in Ruby 2.2.0, please use an updated ruby version (it's since been fixed in the FFI module).
