### ISSUE TITLE
Cocoapods crashes on `pod trunk push` when there's a syntax error in the podspec

### ISSUE THREAD

**Issue by dlo** [CocoaPods/CocoaPods#5541]
# Report

## What did you do?

pod trunk push

## What did you expect to happen?

Upload my pod to CocoaPods Trunk.

## What happened instead?

Ruby crashes.

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.9.0
Ruby lib dir : /Users/dan/.rbenv/versions/2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 32482f5cd5b2f58eb3a79fc2c036b6d5a2d867ed
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

### Error

```
ArgumentError - different prefix: "" and "/Users/dan/Documents/Projects/TableViewPopoverPresenting"
/Users/dan/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pathname.rb:520:in `relative_path_from'
/Users/dan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:187:in `path'
/Users/dan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-trunk-1.0.0/lib/pod/command/trunk/push.rb:97:in `rescue in spec'
/Users/dan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-trunk-1.0.0/lib/pod/command/trunk/push.rb:94:in `spec'
/Users/dan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-trunk-1.0.0/lib/pod/command/trunk/push.rb:106:in `validate_podspec'
/Users/dan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-trunk-1.0.0/lib/pod/command/trunk/push.rb:61:in `run'
/Users/dan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Users/dan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'
/Users/dan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

## Project that demonstrates the issue

https://github.com/lionheart/TableViewPopoverPresenting/tree/b5de2cb6f6056844452b87fa436de73d55dc2717

**Comment by dlo** [comment]
Original issue fixed by fixing a syntax error, but probably worth it to improve the error messaging, since there was no indication for what was wrong.

**Comment by orta** [comment]
What was the syntax error?

**Comment by dlo** [comment]
An unescaped single quote 😊

https://github.com/lionheart/TableViewPopoverPresenting/commit/f2551b9089cfb98ea824007a3994d516c66a2b00

**Comment by orta** [comment]
Thanks, 

@CocoaPods/core wonder if our Podspec parser could use the same kind of syntax exception handling we do for Podfiles?

**Comment by segiddins** [comment]
Iirc it does use the DSLError

**Comment by orta** [comment]
Alright, then this looks like an edge-case I'm afraid, I'm going to close the issue - thanks for bringing it up @dlo

**Comment by dlo** [comment]
@orta of course. To be clear, is this a wontfix?

**Comment by segiddins** [comment]
Ah actually re-reading the backtrace this is something we should fix

**Comment by ZaidPathan** [comment]
For me it was ’ instead of ',
changing to ' on summery fixed my issue.
