### ISSUE TITLE
pod update fails on master version of repo

### ISSUE THREAD

**Issue by dlo** [CocoaPods/CocoaPods#5542]
### Command

```
/usr/local/bin/pod update
```

### Report

* What did you do?

I ran `pod update` for the example project for `TableViewPopoverPresenting`, a Swift library. See sample code at https://github.com/lionheart/TableViewPopoverPresenting/tree/cocoapods.

* What did you expect to happen?

The workspace is generated.

* What happened instead?

Ruby crashed.

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.9.0
Ruby lib dir : /Users/dan/.rbenv/versions/2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 02f21f84fc05a72dbd3a7bdc4731c30e289eb800
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

### Podfile

```ruby
platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
project 'TableViewPopoverPresenting.xcodeproj'

inhibit_all_warnings!
use_frameworks!

target 'TableViewPopoverPresenting_Example' do
  pod 'TableViewPopoverPresenting', :path => '../'

  pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'

  target 'TableViewPopoverPresenting_UITests' do
    inherit! :search_paths
  end
end
```

### Error

```
NoMethodError - undefined method `preprocess_options' for Pod::Downloader:Module
Did you mean?  preprocess_request
/Users/dan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/downloader.rb:130:in `preprocess_request'
/Users/dan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/downloader.rb:37:in `download'
/Users/dan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/pod_source_installer.rb:120:in `download_source'
/Users/dan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/pod_source_installer.rb:60:in `install!'
/Users/dan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:353:in `install_source_of_pod'
/Users/dan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:320:in `block (2 levels) in install_pod_sources'
/Users/dan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:84:in `titled_section'
/Users/dan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:319:in `block in install_pod_sources'
/Users/dan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:311:in `each'
/Users/dan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:311:in `install_pod_sources'
/Users/dan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:157:in `block in download_dependencies'
/Users/dan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/Users/dan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:155:in `download_dependencies'
/Users/dan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:112:in `install!'
/Users/dan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/command/update.rb:60:in `run'
/Users/dan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Users/dan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'
/Users/dan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'

**Comment by orta** [comment]
You probably need to also use master cocoapods-downloader ATM too - https://github.com/CocoaPods/CocoaPods/pull/5386#issuecomment-227042823

**Comment by segiddins** [comment]
Yup -- you might want to check out https://github.com/segiddins/beta-pod if you want to run unreleased CocoaPods versions, or else see https://guides.cocoapods.org/using/unreleased-features.html
