### ISSUE TITLE
TypeError - no implicit conversion of nil into String

### ISSUE THREAD

**Issue by svenresch** [CocoaPods/CocoaPods#5564]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod install`

Running with the latest v1.0.1 now errors out. This has not happened up to CocoaPods v0.39. The issue seems to be rooted with 2 pods that are being used (example Podfile entries listed below). Guess something is amiss with their podspec files but I have not yet been able to see why this is the case.

## What did you expect to happen?

Install all pod dependencies correctly.

## What happened instead?

TypeError - no implicit conversion of nil into String

## CocoaPods Environment

   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)

## Project that demonstrates the issue

The following Podfile with either Pod being referenced will exhibit the same error. Podfile is listed below.

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : alexdrone - https://github.com/alexdrone/ios-fontawesome.git @ 3ef4db504ffde636c1f8a5320f1e5b6183f6102c
               beanstream-drwp - https://github.com/Beanstream-DRWP/beanstream-ios-specs.git @ 9b26e5b7d42c6dbe098bfe4c382f5df2c47630ee
               friend-lga - https://github.com/Friend-LGA/LGRadioButtonsView.git @ c3c327ca58f75263cf59394d324c9eb08857088c
               jdg - https://github.com/jdg/MBProgressHUD.git @ 2546c7efd99bea0aa6b3de1cd44ae2db8097a51a
               jonasgessner - https://github.com/JonasGessner/JGActionSheet.git @ 5cdeb2c33ec9d02bc9bf5de23fb3fc00a7391934
               master - https://github.com/CocoaPods/Specs.git @ 203381cd689dd8c3b5c5f1410e368f5bd6053af7
               mbcharbonneau - https://github.com/mbcharbonneau/UIImage-Categories.git @ 989dc01924481c72ad354344d380acd9fe529b62
               steipete - https://github.com/steipete/PSAlertView.git @ 132f5436b5608c6f810330743abe13f29d5a71be
```

### Plugins

```
cocoapods-art         : 0.9.4
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/JonasGessner/JGActionSheet.git'
source 'https://github.com/Friend-LGA/LGRadioButtonsView.git'

target 'PodTest' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PodTest
  pod 'JGActionSheet', '= 1.0.4'
  #pod 'LGRadioButtonsView', '= 1.0.0'

end
```

### Error

```
TypeError - no implicit conversion of nil into String
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.0.1/lib/cocoapods-core/specification.rb:523:in `initialize'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.0.1/lib/cocoapods-core/specification.rb:523:in `new'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.0.1/lib/cocoapods-core/specification.rb:523:in `from_file'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.0.1/lib/cocoapods-core/specification/set.rb:45:in `specification'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.0.1/lib/cocoapods-core/source.rb:268:in `search'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.0.1/lib/cocoapods-core/source/aggregate.rb:83:in `block in search'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.0.1/lib/cocoapods-core/source/aggregate.rb:83:in `select'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.0.1/lib/cocoapods-core/source/aggregate.rb:83:in `search'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/resolver.rb:346:in `create_set_from_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/resolver.rb:316:in `find_cached_set'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/resolver.rb:289:in `specifications_for_dependency'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/resolver.rb:107:in `search_for'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/resolver.rb:205:in `block in sort_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/resolver.rb:199:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/resolver.rb:199:in `sort_by'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/resolver.rb:199:in `sort_dependencies'
/Library/Ruby/Gems/2.0.0/gems/molinillo-0.4.5/lib/molinillo/resolution.rb:131:in `block (2 levels) in <class:Resolution>'
/Library/Ruby/Gems/2.0.0/gems/molinillo-0.4.5/lib/molinillo/resolution.rb:174:in `initial_state'
/Library/Ruby/Gems/2.0.0/gems/molinillo-0.4.5/lib/molinillo/resolution.rb:100:in `start_resolution'
/Library/Ruby/Gems/2.0.0/gems/molinillo-0.4.5/lib/molinillo/resolution.rb:63:in `resolve'
/Library/Ruby/Gems/2.0.0/gems/molinillo-0.4.5/lib/molinillo/resolver.rb:42:in `resolve'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/resolver.rb:62:in `resolve'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:563:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:561:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:76:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:227:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:151:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:150:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:114:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command/install.rb:37:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by DanToml** [comment]
@svenresch Your Podfile is incorrect, `sources` are used to define alternative spec repositories, not the repository of an individual pod. You can find the documentation for the DSL here: https://guides.cocoapods.org/syntax/podfile.html

```
source 'https://github.com/CocoaPods/Specs.git'

target 'PodTest' do
  pod 'JGActionSheet', '= 1.0.4'
  pod 'LGRadioButtonsView', '= 1.0.0'
end
```

**Comment by svenresch** [comment]
@dantoml @nwest The source listed originally was edited to be as follows shortly thereafter.

source 'https://github.com/JonasGessner/JGActionSheet.git'
source 'https://github.com/Friend-LGA/LGRadioButtonsView.git'

**Comment by svenresch** [comment]
Again, our setup has worked in the past (I think for over a year) until the 1.0.1 update.

**Comment by svenresch** [comment]
Hi Nate. I've added some comments. Are you sure this one should be closed?

Thx,
Sven

**Comment by segiddins** [comment]
@svenresch what Dan and Nate have said is 100% correct -- if it work previously, that would've been entirely by accident.

**Comment by svenresch** [comment]
@seginddins The example listed is a minimal example to help isolate and demo the error. The project I am working in has a half dozen or so other 3rd party pods also pulled in via a defined 'source'. So it seems that just the two pods listed in this ticket are a cause of the specified error.
