### ISSUE TITLE
pod install problem..

### ISSUE THREAD

**Issue by sunwootech** [CocoaPods/CocoaPods#5574]
> ℹ Please fill out this template when filing an issue.
> All lines beginning with an ℹ symbol instruct you with
> what info we expect.  
> Please remove this line and all above before submitting.

* [ ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace this with what you did.  
```
pod install --verbose
  Preparing

Setting up CocoaPods master repo

Cloning spec repo `master` from `https://github.com/CocoaPods/Specs.git` (branch `master`)
  $ /usr/bin/git clone https://github.com/CocoaPods/Specs.git master
  Cloning into 'master'...
  error: RPC failed; curl 56 SSLRead() return error -9806
  fatal: The remote end hung up unexpectedly
  fatal: early EOF
  fatal: index-pack failed
[!] Unable to add a source with url `https://github.com/CocoaPods/Specs.git` named `master`.
(/usr/bin/git clone https://github.com/CocoaPods/Specs.git master

Cloning into 'master'...
error: RPC failed; curl 56 SSLRead() return error -9806
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
)
You can try adding it manually in `~/.cocoapods/repos` or via `pod repo add`.

/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/sources_manager.rb:35:in `rescue in find_or_create_source_with_url'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/sources_manager.rb:38:in `find_or_create_source_with_url'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:654:in `block in sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:653:in `map'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:653:in `sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:144:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:114:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command/install.rb:37:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

==================================================================
and that
```
cd ~/.cocopods/repo

protanks-Mac:repos protank$ git clone https://github.com/CocoaPods/Specs.git master --verbose
Cloning into 'master'...
POST git-upload-pack (305 bytes)
remote: Counting objects: 726378, done.
remote: Compressing objects: 100% (9/9), done.
Receiving objects:  11% (79902/726378), 15.63 MiB | 2.63 MiB/s 

receving pause..
```

**Comment by segiddins** [comment]
Does cloning manually via the `git` command work? If not, then it's not an issue in CocoaPods but rather a problem with your network setup.

**Comment by jinthreek89** [comment]
Hi, @segiddins .
I have a issue same @sunwootech .
This problem is only network setup, right?
Never there is other problems?
I was wasted time for 2 days because this issue.
I want your help.

**Comment by sunwootech** [comment]
p {margin-top:0px;margin-bottom:0px;} 


	
	
Hi..when i have such problem.my computer config. -----------------------------------------window10 +vmware + ios10 + cocoapods + config process..------------------------------------------still don't know what problems.Now i use mac mini and same cocoapods config processno problems!!--------- 원본 메일 ---------보낸사람: Guanghe Jin <notifications@github.com>받는사람 : CocoaPods/CocoaPods <CocoaPods@noreply.github.com>참조 : sunwootech <webmaster@sunwootech.co.kr>,Mention <mention@noreply.github.com>날짜: 2016년 7월 03일 일요일, 11시 03분 33초 +0900제목: Re: [CocoaPods/CocoaPods] pod install problem.. (#5574)

	Hi, @segiddins .
I have a issue same @sunwootech .
This problem is only network setup, right?
Never there is other problems?
I was wasted time for 2 days because this issue.
I want your help.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




		
p  {font-size:10pt ! important;font-family:돋움,'굴림',gulim,tahoma,sans-serif ! important;}

**Comment by segiddins** [comment]
@jinthreek89 did you try manually running the git command?

**Comment by neonichu** [comment]
Closing because of lack of activity.

**Comment by yurevich1** [comment]
I have got the same problem. Git clone doesn't work properly.

**Comment by mohshin-shah** [comment]
Please open the terminal and execute this 
git config --global user.email "youremail@xxx.xxx"
then try `pod install`

**Comment by yurevich1** [comment]
I found the solutin. This is a network (virtual machine) issue. NAT connection suddenly freezes git cloning after several megabytes downloading.
Otherwise I have to clone the data from somewhere outside the machine.

I have to change the connection into Bridged state in order to use git and cocoapods correctly.

**Comment by kimky1122** [comment]
This is my first time writing this article.
I was in the nat environment in vmware (virtual machine).
It's like a treasure.
Resolved.

I remember the last time.
Thank you.
