### ISSUE TITLE
Co'coapods private repo can not install with SSH URL

### ISSUE THREAD

**Issue by sohotj** [CocoaPods/CocoaPods#5580]
# My Podfile
# **source 'tangjie@localhost:/Users/tangjie/dev/git-server/TGOPodSpec.git'  #my private repo url**
source 'https://github.com/CocoaPods/Specs.git'  
# Uncomment this line to define a global platform for your project
#platform :ios, '9.0'

target 'TGOPod' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TGOPod
  pod 'TGOPodLib', '~> 0.1.0'
  target 'TGOPodTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TGOPodUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

ℹ Now I can search my private lib.  
-> TGOPodLib (0.1.0)
   A short description of TGOPodLib.
   pod 'TGOPodLib', '~> 0.1.0'
   - Homepage: tangjie@localhost:/Users/tangjie/dev/git-server/TGOPodLib.git
   - Source:   tangjie@localhost:/Users/tangjie/dev/git-server/TGOPodLib.git
   - Versions: 0.1.0 [tangOPSPod repo]

ℹ After "pod install", the log below.

ℹ Cloning spec repo `localhost:/users/tangjie/dev/git-server-tgopodspec` from `tangjie@localhost:/Users/tangjie/dev/git-server/TGOPodSpec.git`
Password:

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : localhost: -  @ fatal: Not a git repository (or any of the parent directories): .git
               master - https://github.com/CocoaPods/Specs.git @ 84998d9f2fd5177e8b1cd2ba184d8a80a19a2808
               tangOPSPod - tangjie@localhost:/Users/tangjie/dev/git-server/TGOPodSpec.git/ @ 1097ce06933b6286283a9ffdc1afdcc7e5d09b80
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

### Podfile

```ruby
source 'tangjie@localhost:/Users/tangjie/dev/git-server/TGOPodSpec.git'  #我们自己的私有spec仓库的地址
source 'https://github.com/CocoaPods/Specs.git'  #官方仓库的地址
# Uncomment this line to define a global platform for your project
#platform :ios, '9.0'

target 'TGOPod' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TGOPod
  pod 'TGOPodLib', '~> 0.1.0'
  target 'TGOPodTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TGOPodUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

### Error

```
# **RuntimeError - Unable to create a source with URL tangjie@localhost:/Users/tangjie/dev/git-server/TGOPodSpec.git**
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/sources_manager.rb:42:in `find_or_create_source_with_url'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:654:in `block in sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:653:in `map'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:653:in `sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:144:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:114:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command/install.rb:37:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

ℹ  pod env
MacBook-Pro-2:repos tangjie$ pod env

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : localhost: -  @ # **fatal: Not a git repository (or any of the parent directories)**: .git
               master - https://github.com/CocoaPods/Specs.git @ 84998d9f2fd5177e8b1cd2ba184d8a80a19a2808
               tangOPSPod - tangjie@localhost:/Users/tangjie/dev/git-server/TGOPodSpec.git/ @ 1097ce06933b6286283a9ffdc1afdcc7e5d09b80
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

ℹ How can I "pod install" with Git ssh URL.

**Comment by neonichu** [comment]
I think the issue is that the URL to your private spec repo does not contain a protocol.

**Comment by sohotj** [comment]
@neonichu I Misunderstanding the Git protocol URL.My private spec contain the ssh url.Does cocoapod support ssh url?

**Comment by benasher44** [comment]
Ah yep the URL just needs to have `ssh://` in it. So instead of:
```
source 'tangjie@localhost:/Users/tangjie/dev/git-server/TGOPodSpec.git' #my private repo url
```
try:
```
source 'ssh://tangjie@localhost:/Users/tangjie/dev/git-server/TGOPodSpec.git' #my private repo url
```

This has been open for months now. Going to close, but feel free to reopen if this doesn't fix it for you.

**Comment by EddieLukeAtmey** [comment]
Hi I'm having this same trouble and source 'ssh://myPrivateURL' doesn't works.

My host config:
Host github.com
    Hostname github.com
    User EddieLukeAtmey
    IdentityFile ~/.ssh/id_rsa

I tried `pod update` and yield this:

```
Unable to add a source with url `ssh://git@github.com:EddieLukeAtmey/private-repo.git` named `github-private-repo`.
You can try adding it manually in `/Users/eddie/.cocoapods/repos` or via `pod repo add`.
```
I'm not sure what to do.

my pod file:
```
source 'ssh://git@github.com:EddieLukeAtmey/private-repo.git'
target 'MyApp' do
use_frameworks!
pod 'MyRepo', :git => 'ssh://git@github.com:EddieLukeAtmey/private-repo.git'
end
```
