### ISSUE TITLE
[Xcode 8 Swift 3] undefined method `path' for nil:NilClass with xcassets folder

### ISSUE THREAD

**Issue by eebean2** [CocoaPods/CocoaPods#5616]
### Command

```
/usr/local/bin/pod install
```
### Report
- What did you do?

`pod install` on custom pod that include a .xcassets folder
- What did you expect to happen?

Pod to successfully install
- What happened instead?

The bellow errors (this is the template from the console).
### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12 (16A239j)
       Xcode : 8.0 (8S162m)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 3c8bb66dc27a832593ccf512295c3fbce2c3de0b
```
### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```
### Podfile

``` ruby
use_frameworks!



target 'StarMessenger_Example' do
  pod 'StarMessenger', :path => '../'

  target 'StarMessenger_Tests' do
    inherit! :search_paths


  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'NO'
        end
    end
end
```
### Error

```
NoMethodError - undefined method `path' for nil:NilClass
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.1.0/lib/xcodeproj/project/object/native_target.rb:462:in `block in add_file_references'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.1.0/lib/xcodeproj/project/object/native_target.rb:461:in `map'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.1.0/lib/xcodeproj/project/object/native_target.rb:461:in `add_file_references'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/target_installer/pod_target_installer.rb:100:in `block in add_files_to_build_phases'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/target_installer/pod_target_installer.rb:76:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/target_installer/pod_target_installer.rb:76:in `add_files_to_build_phases'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/target_installer/pod_target_installer.rb:21:in `block in install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:141:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/target_installer/pod_target_installer.rb:17:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:621:in `block (2 levels) in install_libraries'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:619:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:619:in `block in install_libraries'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:141:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:618:in `install_libraries'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:170:in `block in generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:167:in `generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:119:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command/install.rb:37:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by eebean2** [comment]
I'm noting this outside the initial report because I still believe it is either a bug, or should be looked at for enhancement.

I resolved this by deleting all reference to the .xcassets folder (and relocating the initial hard folder to my desktop). Then relocating it to the Assets folder within the pod. It would only run `pod install` or `pod update` after that. If this is on purpose, it should be looked at to be included where ever Xcode includes it (as this is not default).

**Comment by neonichu** [comment]
I'm having a hard time understanding exactly what you changed to make this work. Are you able to share the Pod you used and what you changed?

**Comment by eebean2** [comment]
I had to move the assets folder from `[podname] > [podname] > Classes` folder to `[podname] > [podname] > Assets` folder. Before this, it kept crashing.

**Comment by DanToml** [comment]
This looks like it was a local configuration issue, if this is still a problem please file a new issue, including a sample project.
