### ISSUE TITLE
About CocoaPods error when performed in the launchd.plist

### ISSUE THREAD

**Issue by ybma-xbzheng** [CocoaPods/CocoaPods#5618]
### Command

```
/usr/local/bin/pod update
```

### Report

* What did you do?
   performed pod update in the user agents launchd.plist.

* What did you expect to happen?
   :-)

* What happened instead?
   :-(

### Stack

```
   CocoaPods : 0.39.0
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 1b7bd683a2003c2c2d38bfe827bb7311e767bf6d
               spec - ssh://git@gitlab.*.domain:*/mobile-ios/PodSpecs.git @ 8a8b0b63f1454b5534f42be6f76dd453c6277217
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-search  : 0.1.0
cocoapods-stats   : 0.6.2
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.5.1
```
### Error

```
ArgumentError - invalid byte sequence in US-ASCII
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/plist_helper.rb:112:in `match'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/plist_helper.rb:112:in `match'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/plist_helper.rb:112:in `block in file_in_conflict?'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/plist_helper.rb:112:in `each_line'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/plist_helper.rb:112:in `each'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/plist_helper.rb:112:in `any?'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/plist_helper.rb:112:in `file_in_conflict?'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/plist_helper.rb:66:in `read'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/plist_helper.rb:13:in `read_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/project.rb:193:in `initialize_from_file'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/project.rb:95:in `open'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer/target_inspector.rb:32:in `compute_results'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:659:in `block (2 levels) in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:657:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:657:in `block in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:656:in `inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:61:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:213:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:136:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:135:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:105:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:156:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by ybma-xbzheng** [comment]
If i performed pod update manually in the terminal，everything is ok.

**Comment by alloy** [comment]
launchd scripts don’t get executed in a shell, which is what those profile scripts are for.

Try setting the `LANG` environment variable to `en_US.UTF-8` with the `EnvironmentVariables` key in your launchd plist.

(As described in the man page: https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man5/launchd.plist.5.html)

**Comment by ybma-xbzheng** [comment]
@alloy your solution worked for me，thank you very much!

**Comment by alloy** [comment]
Ace 👌
