### ISSUE TITLE
[!] Unable to load a podspec from `DateTools.podspec`, skipping:

### ISSUE THREAD

**Issue by VincentSit** [CocoaPods/CocoaPods#5626]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

```
pod install --no-repo-update --verbose
```

I fork `DateTools` and made some changes to adapt to our projects.

0.39.0 work fine, but it does not work in 1.0.1.

If you remove it or use

```
pod 'DateTools'
```

instead of

```
pod 'DateTools',: git => 'https://github.com/VincentSit/DateTools.git'
```

It can work properly. So I guess may be my [DateTools.podspec](https://github.com/VincentSit/DateTools/blob/master/DateTools.podspec) has a problem.

I encountered this problem a long time ago, which cause me to have to continue to use 0.39.0.
I tried searching, but did not find a solution.
 
## What did you expect to happen?

Pod work fine.

### Error Message

```
[!] Unable to load a podspec from `DateTools.podspec`, skipping:

Pod::DSLError
```

### Log

```
➜ pod install --no-repo-update --verbose
  Preparing

Re-creating CocoaPods due to major version update.

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-MyTargetName`: (``)

Finding Podfile changes
  - AFNetworkActivityLogger
  - AFNetworking
  - AWSS3
  - Aspects
  - BlocksKit
  - Bugtags
  - BugtagsInsta
  - Charts
  - CocoaLumberjack
  - DZNEmptyDataSet
  - DateTools
  - FCFileManager
  - FCUUID
  - FLEX
  - FMDB
  - IDMPhotoBrowser
  - JDStatusBarNotification
  - JLPermissions
  - JSPatchSDK
  - KVOController
  - LDProgressView
  - MARKRangeSlider
  - MD5Digest
  - MOBFoundation
  - MZTimerLabel
  - MagicalRecord
  - Masonry
  - Motis
  - NKOColorPickerView
  - PBWebViewController
  - PKRevealController
  - PSTAlertController
  - RMDateSelectionViewController
  - RNCryptor
  - SDVersion
  - SDWebImage
  - SVProgressHUD
  - SVPullToRefresh
  - SWTableViewCell
  - ShareSDK2
  - SystemServices
  - TTTAttributedLabel
  - UITextView+Blocks
  - UITextView+Placeholder
  - WTAScrollViewKeyboardManager
  - XCDLumberjackNSLogger
  - YLGIFImage
  - ZendeskSDK
  - libextobjc

Fetching external sources
-> Pre-downloading: `AFNetworkActivityLogger` from `https://github.com/AFNetworking/AFNetworkActivityLogger.git`, commit `abc565fe804f210dfda3b028c9a64e7c32e44600`
  > Copying AFNetworkActivityLogger from
  `/Users/vincentxue/Library/Caches/CocoaPods/Pods/External/AFNetworkActivityLogger/787ddd72fb16f84c74b6881f5a69e848`
  to `Pods/AFNetworkActivityLogger`
-> Pre-downloading: `DateTools` from `https://github.com/VincentSit/DateTools.git`, commit `5fdce372ea3a79236d5799bd3572457784bcc8c7`
 > Git download
 > Git download
     $ /usr/bin/git clone https://github.com/VincentSit/DateTools.git
     /var/folders/_0/8v4j8mjs5l7czflk31r4___80000gn/T/d20160714-14711-ps2kc9 --template=
     Cloning into '/var/folders/_0/8v4j8mjs5l7czflk31r4___80000gn/T/d20160714-14711-ps2kc9'...
   $ /usr/bin/git checkout --quiet 5fdce372ea3a79236d5799bd3572457784bcc8c7
[!] Unable to find a specification for 'DateTools'.

/Users/vincentxue/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/external_sources/abstract_external_source.rb:117:in `block in pre_download'
/Users/vincentxue/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:84:in `titled_section'
/Users/vincentxue/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/external_sources/abstract_external_source.rb:112:in `pre_download'
/Users/vincentxue/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/external_sources/downloader_source.rb:13:in `fetch'
/Users/vincentxue/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:479:in `fetch_external_source'
/Users/vincentxue/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:455:in `block (2 levels) in fetch_external_sources'
/Users/vincentxue/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:454:in `each'
/Users/vincentxue/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:454:in `block in fetch_external_sources'
/Users/vincentxue/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/Users/vincentxue/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:453:in `fetch_external_sources'
/Users/vincentxue/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:73:in `analyze'
/Users/vincentxue/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:227:in `analyze'
/Users/vincentxue/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:151:in `block in resolve_dependencies'
/Users/vincentxue/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/Users/vincentxue/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:150:in `resolve_dependencies'
/Users/vincentxue/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:114:in `install!'
/Users/vincentxue/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/command/install.rb:37:in `run'
/Users/vincentxue/.rvm/gems/ruby-2.3.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Users/vincentxue/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'
/Users/vincentxue/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
/Users/vincentxue/.rvm/gems/ruby-2.3.0/bin/pod:23:in `load'
/Users/vincentxue/.rvm/gems/ruby-2.3.0/bin/pod:23:in `<main>'
/Users/vincentxue/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/Users/vincentxue/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'

[!] Unable to load a podspec from `DateTools.podspec`, skipping:

Pod::DSLError
```

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /Users/vincentxue/.rvm/rubies/ruby-2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 978e5ef94f48683e5b67f9065710ff32f43a0c29
```

### Installation Source

```
Executable Path: /Users/vincentxue/.rvm/gems/ruby-2.3.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

### Podfile

```
platform :ios, '8.0'

inhibit_all_warnings!
use_frameworks!

target 'MyTargetName' do

# Views
pod 'Masonry'
pod 'SVProgressHUD'#, '1.1.2'
pod 'PSTAlertController'
pod 'RMDateSelectionViewController', '1.4.3'
pod 'TTTAttributedLabel'
pod 'DZNEmptyDataSet', '1.5.2'
pod 'PBWebViewController'
pod 'YLGIFImage'
pod 'SVPullToRefresh', :git => 'https://github.com/VincentSit/SVPullToRefresh.git', :branch => 'master'
#pod 'FDStackView', '~> 1.0-alpha'
pod 'MZTimerLabel'
pod 'LDProgressView'
pod 'SWTableViewCell'
pod 'NKOColorPickerView'
pod 'MARKRangeSlider'
pod 'JDStatusBarNotification'
pod 'UITextView+Blocks'
pod 'Charts'

# Models
pod 'AFNetworking'
pod 'AFNetworkActivityLogger', :git => 'https://github.com/AFNetworking/AFNetworkActivityLogger.git', :branch => '3_0_0'
pod 'MagicalRecord', '2.2'
pod 'Motis', '1.3.0'
pod 'AWSS3', '~> 2.2.6'

# Helpers
pod 'SDWebImage'
pod 'PKRevealController', :git => 'https://github.com/VincentSit/PKRevealController.git', :branch => 'ibaby'
pod 'CocoaLumberjack'
pod 'JLPermissions/Photos'
pod 'JLPermissions/Camera'
pod 'JLPermissions/Microphone'
pod 'JLPermissions/Notification', :inhibit_warnings => true
pod 'SDVersion'
pod 'BlocksKit'
pod 'DateTools', :git => 'https://github.com/VincentSit/DateTools.git'
pod 'WTAScrollViewKeyboardManager', '0.0.1'
pod 'MD5Digest'
pod 'RNCryptor', '3.0.1'
pod 'libextobjc'

# ShareSDK Begin
pod 'MOBFoundation'
pod 'ShareSDK2'
pod 'ShareSDK2/UI/Flat'
pod 'ShareSDK2/Connection/WeChat'
pod 'ShareSDK2/Connection/Facebook'
pod 'ShareSDK2/Connection/Instagram'
pod 'ShareSDK2/Connection/Twitter'
# ShareSDK End

pod 'IDMPhotoBrowser', :git => 'https://github.com/VincentSit/IDMPhotoBrowser.git', :branch => 'master'
pod 'FCFileManager'
pod 'UITextView+Placeholder'
pod 'XCDLumberjackNSLogger'
pod 'ZendeskSDK'
pod 'KVOController'
pod 'Bugtags'
pod 'BugtagsInsta', :configurations => ['Debug']
pod 'JSPatchSDK'
#pod 'JSPatch/Extensions'
pod 'FMDB'
pod 'SystemServices'
pod 'FCUUID'
#pod 'Rollout.io', '~> 1.0.0'
pod 'FLEX', '~> 2.0', :configurations => ['Debug']
pod 'Aspects'

end
```

## Project that demonstrates the issue

[PodDemo](https://drive.google.com/file/d/0Bz7ghMT14BvuZjBIVTdVdnVIVjQ/view?usp=sharing)

**Comment by VincentSit** [comment]
Sloved.

See https://github.com/VincentSit/DateTools/commit/9cbdcd7b63e59e2a93a7145b3dbb9c59c10fa1a8

**Comment by VincentSit** [comment]
I found an inner logic, if you remove it from the Podfile, waiting for the other Pods installation is complete. Then add it to the Podfile,  it can be installed successfully.

If you don't have any Pod installed, you install all of the pod directly, then it will fail.

**Comment by benasher44** [comment]
@VincentSit can you try updating to CocoaPods 1.1.1 and see if you're still experiencing this issue?

**Comment by VincentSit** [comment]
@benasher44 

I am using version 1.1.1 now, this issue has been fixed, thanks! I forgot to update the issues.

**Comment by benasher44** [comment]
No prob! Thank you!
