### ISSUE TITLE
Realm 1.0.2 pod fails to install with core is not a symlink unrecoverable error.

### ISSUE THREAD

**Issue by taher007saeed** [CocoaPods/CocoaPods#5636]
* [ ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
Realm (1.0.2) fails to install.

## What did you do?
pod update --verbose

Tried various trouble shooting methods -
```
pod cache clean Realm
pod cache clean RealmSwift
pod deintegrate || rm -rf Pods
rm -rf /tmp/core_bin
pod install --verbose
rm -rf ~/Library/Developer/Xcode/DerivedData
```

Cleaned Xcode cache
[Realm trouble shooting](https://realm.io/docs/swift/latest/#cocoapods)
[Similar ticket](https://github.com/realm/realm-cocoa/issues/2312)

The issue persists.

## What did you expect to happen?
Install all pod dependencies correctly.

## What happened instead?

```
-> Installing Realm (1.0.2)
 > Git download
 > Git download
     $ /usr/bin/git clone https://github.com/realm/realm-cocoa.git /var/folders/9q/vh11js3159g15m73dts1gq980000gq/T/d20160716-91531-p7vo5p --template=
     --single-branch --depth 1 --branch v1.0.2
     Cloning into '/var/folders/9q/vh11js3159g15m73dts1gq980000gq/T/d20160716-91531-p7vo5p'...
     Note: checking out '10ef693b9935694f58f49b264008f6cf3ccccf61'.
     
     You are in 'detached HEAD' state. You can look around, make experimental
     changes and commit them, and you can discard any commits you make in this
     state without impacting any branches by performing another checkout.
     
     If you want to create a new branch to retain commits you create, you may
     do so (now or later) by using -b with the checkout command again. Example:
     
       git checkout -b <new-branch-name>
     
 > Running prepare command
   $ /bin/bash -c  set -e sh build.sh cocoapods-setup
   core is not a symlink. Deleting...
   Downloading dependency: core 1.3.1
   tar (child): xz: Cannot exec: No such file or directory
   tar (child): Error is not recoverable: exiting now
   tar: Child returned status 2
   tar: Error is not recoverable: exiting now
[!] /bin/bash -c 
set -e
sh build.sh cocoapods-setup

core is not a symlink. Deleting...
Downloading dependency: core 1.3.1
tar (child): xz: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now


/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/executable.rb:69:in `execute_command'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/executable.rb:27:in `block in executable'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/pod_source_preparer.rb:66:in `block (2 levels) in run_prepare_command'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/pod_source_preparer.rb:60:in `chdir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/pod_source_preparer.rb:60:in `block in run_prepare_command'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/pod_source_preparer.rb:59:in `run_prepare_command'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/pod_source_preparer.rb:37:in `prepare!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/downloader/cache.rb:201:in `copy_and_clean'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/downloader/cache.rb:158:in `block (2 levels) in uncached_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/downloader/cache.rb:156:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/downloader/cache.rb:156:in `block in uncached_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/downloader/cache.rb:180:in `call'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/downloader/cache.rb:180:in `in_tmpdir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/downloader/cache.rb:152:in `uncached_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/downloader/cache.rb:33:in `download_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/downloader.rb:39:in `download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/pod_source_installer.rb:120:in `download_source'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/pod_source_installer.rb:60:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:346:in `install_source_of_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:313:in `block (2 levels) in install_pod_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:84:in `titled_section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:312:in `block in install_pod_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:304:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:304:in `install_pod_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:160:in `block in download_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:158:in `download_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:115:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command/update.rb:60:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

## CocoaPods Environment

1.1.0.beta.1

**Comment by DanToml** [comment]
@taher007saeed I'm unable to reproduce this with a new project and a Podfile that only installs `Realm` and `RealmSwift` on `1.1.0.beta.1`. Please can you share a Podfile or Project that reproduces this issue?

**Comment by segiddins** [comment]
It looks to me like the failure is coming from Realm's `prepare_command`

**Comment by taher007saeed** [comment]
Let me work on a sample project to replicate the issue. In addition to Realm and RealmSwift, we also use the below pods that may contribute to the issue.

```
RBQFetchedResultsController
Realm
RealmGridController
RealmSwift
RealmTableViewController
```

**Comment by taher007saeed** [comment]
@DanToml [Here's the sample project](https://www.dropbox.com/s/f9xxcpwfgaxsmh9/RealmPodUpdateFailure.zip?dl=0) that throws up the same error on pod update.

**More on environment -**
Xcode - Version 7.3 (7D175)
MacOS - El Capitan V 10.11.5(15F34)
CocoaPods - 1.0.1

**Comment by taher007saeed** [comment]
## Workaround - 

Pointing the RealmSwift pod to 1.0.1 allows pod update to complete successfully.

**Comment by neonichu** [comment]
Looks like Realm switched to `xz` compression for their tarball in 1.0.2, which isn't installed by default on macOS — you should be able to install it using homebrew.

**Comment by taher007saeed** [comment]
Thanks! ``` brew install xz ``` fixed this.
