### ISSUE TITLE
pod install Google Map error

### ISSUE THREAD

**Issue by michaelliesenberg** [CocoaPods/CocoaPods#5668]
Hi so i did pod install after creating a Podfile with this on it:

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.1'

target 'SO-32079263' do
pod 'GoogleMaps'
end

I get this error when i execute "pod install":
### Error

```
RuntimeError - [!] Xcodeproj doesn't know about the following attributes {"name"=>"Compile Sources"} for the 'PBXSourcesBuildPhase' isa.
If this attribute was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.2.0/lib/xcodeproj/project/object.rb:321:in `configure_with_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.2.0/lib/xcodeproj/project.rb:258:in `new_from_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.2.0/lib/xcodeproj/project/object.rb:350:in `object_with_uuid'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.2.0/lib/xcodeproj/project/object.rb:300:in `block (2 levels) in configure_with_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.2.0/lib/xcodeproj/project/object.rb:299:in `each'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.2.0/lib/xcodeproj/project/object.rb:299:in `block in configure_with_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.2.0/lib/xcodeproj/project/object.rb:296:in `each'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.2.0/lib/xcodeproj/project/object.rb:296:in `configure_with_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.2.0/lib/xcodeproj/project.rb:258:in `new_from_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.2.0/lib/xcodeproj/project/object.rb:350:in `object_with_uuid'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.2.0/lib/xcodeproj/project/object.rb:300:in `block (2 levels) in configure_with_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.2.0/lib/xcodeproj/project/object.rb:299:in `each'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.2.0/lib/xcodeproj/project/object.rb:299:in `block in configure_with_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.2.0/lib/xcodeproj/project/object.rb:296:in `each'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.2.0/lib/xcodeproj/project/object.rb:296:in `configure_with_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.2.0/lib/xcodeproj/project.rb:258:in `new_from_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.2.0/lib/xcodeproj/project.rb:202:in `initialize_from_file'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.2.0/lib/xcodeproj/project.rb:102:in `open'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:695:in `block (2 levels) in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:694:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:694:in `block in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:689:in `inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:66:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:227:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:151:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:150:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:114:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command/install.rb:37:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'

I am using a Qt project which compiles for the xcode.
On the build directory i have a xcode project. I have a google map plug in for it and on the MAC it works but on the iphone the map doesnt appear. So i did the steps as googlemap sdk for ios tells to do but i cant install it for the Qt project.
On a normal Xcode Project it works but not for a QT Project.
Any idea?
```

**Comment by segiddins** [comment]
Can you share the project that caused this? Thanks!

**Comment by michaelliesenberg** [comment]
Hi Segiddins,

here is the xcode project on the build directoty:
https://github.com/michaelliesenberg/xcode_build

**Comment by fabianrenner** [comment]
Having the same problem here with a Qt qmake generated xcodeproj file which has invalid `name` attributes. removing the offending entries allows to run `pod init` et.al.

As the xcodeproj file works in general in XCode, a possible solution would be if CocoaPods would ignore these attributes.
