### ISSUE TITLE
what

### ISSUE THREAD

**Issue by ellmcz** [CocoaPods/CocoaPods#5692]
――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod trunk push
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.1.0.beta.1
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.6 (15G31)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /Users/Ellmcz/.rvm/rubies/ruby-2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 787e8e1018b9e4d780e2854963e91cf81307035a
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

### Error

```
ArgumentError - Malformed version number string v1.0.2
/Users/Ellmcz/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-core-1.1.0.beta.1/lib/cocoapods-core/version.rb:52:in `initialize'
/Users/Ellmcz/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-core-1.1.0.beta.1/lib/cocoapods-core/vendor/version.rb:199:in `new'
/Users/Ellmcz/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-core-1.1.0.beta.1/lib/cocoapods-core/vendor/version.rb:199:in `new'
/Users/Ellmcz/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-core-1.1.0.beta.1/lib/cocoapods-core/specification/root_attribute_accessors.rb:31:in `version'
/Users/Ellmcz/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-core-1.1.0.beta.1/lib/cocoapods-core/specification/linter.rb:109:in `block in check_required_attributes'
/Users/Ellmcz/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-core-1.1.0.beta.1/lib/cocoapods-core/specification/linter.rb:108:in `each'
/Users/Ellmcz/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-core-1.1.0.beta.1/lib/cocoapods-core/specification/linter.rb:108:in `check_required_attributes'
/Users/Ellmcz/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-core-1.1.0.beta.1/lib/cocoapods-core/specification/linter.rb:50:in `lint'
/Users/Ellmcz/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.1.0.beta.1/lib/cocoapods/validator.rb:249:in `perform_linting'
/Users/Ellmcz/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.1.0.beta.1/lib/cocoapods/validator.rb:78:in `validate'
/Users/Ellmcz/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-trunk-1.0.0/lib/pod/command/trunk/push.rb:109:in `validate_podspec'
/Users/Ellmcz/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-trunk-1.0.0/lib/pod/command/trunk/push.rb:61:in `run'
/Users/Ellmcz/.rvm/gems/ruby-2.3.0@global/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Users/Ellmcz/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.1.0.beta.1/lib/cocoapods/command.rb:50:in `run'
/Users/Ellmcz/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.1.0.beta.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
/Users/Ellmcz/.rvm/gems/ruby-2.3.0@global/bin/ruby_executable_hooks:15:in `eval'
/Users/Ellmcz/.rvm/gems/ruby-2.3.0@global/bin/ruby_executable_hooks:15:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=Malformed+version+number+string+v1.0.2&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Found no similar issues. To create a new issue, please visit:
https://github.com/cocoapods/cocoapods/issues/new

**Comment by DanToml** [comment]
It looks like you are using an invalid version string in your podspec (`v1.0.2`). Versions must conform to http://semver.org, so in this case would be simply `1.0.2`. (more info: https://guides.cocoapods.org/syntax/podspec.html)
