### ISSUE TITLE
regression in 1.1.0.beta.1: can't install with multiple targets

### ISSUE THREAD

**Issue by Coeur** [CocoaPods/CocoaPods#5737]
Note: could be a duplicate of either #5661 or #5700, but my Podfile looking quite different, I feel like to post it
The issue is that installing my targets with 1.1.0.beta.1 doesn't work. It is working with 1.0.1.
Note2: the target "MyApp-UnitTests" has no host: it's independent from the other two. The project is currently for Xcode 8 beta 4 (using Swift 2.3)

### Command

```
/usr/local/bin/pod install
```

### Stack

```
   CocoaPods : 1.1.0.beta.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.6 (15G31)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : example-pods-repo - ssh://git@stash.example.com:7999/mobile/pods-repo.git @ f974d4fe849d999f7aeaf7635f10b393a79c7e5a
               master - https://github.com/CocoaPods/Specs.git @ 0d40c4864f501eb51f6703884330cb2780ac6ac2
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '8.0'
use_frameworks!

abstract_target 'default_pods' do
    # swift dependencies
    pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'swift2.3'
    
    target 'MyApp-Release'
    target 'MyApp-Debug'
    target 'MyApp-UnitTests'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '2.3'
        end
    end
end
```

### Error

```
Errno::EEXIST - File exists - /Users/antoinecoeur/Development/MyApp/Pods/Target Support Files/Alamofire
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.1/lib/cocoapods/installer/xcode/pods_project_generator/target_installer.rb:92:in `mkdir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.1/lib/cocoapods/installer/xcode/pods_project_generator/target_installer.rb:92:in `mkdir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.1/lib/cocoapods/installer/xcode/pods_project_generator/target_installer.rb:92:in `create_support_files_dir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.1/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:21:in `block in install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.1/lib/cocoapods/user_interface.rb:142:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.1/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:19:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:155:in `block (2 levels) in install_libraries'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:153:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:153:in `block in install_libraries'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.1/lib/cocoapods/user_interface.rb:142:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:152:in `install_libraries'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:64:in `generate!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.1/lib/cocoapods/installer.rb:181:in `block in generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.1/lib/cocoapods/installer.rb:180:in `generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.1/lib/cocoapods/installer.rb:116:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.1/lib/cocoapods/command/install.rb:37:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.1/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by Coeur** [comment]
Example project: https://github.com/Coeur/cocoapods5737

You can:
a) deintegrate install with CocoaPods 1.0.1 to see it works
b) deintegrate and install with CocoaPods 1.1.0.beta.1 to see it doesn't work

**Comment by toohotz** [comment]
Having the same issue with the beta as well stating the target has no host file.  Saw an issues regarding this in another thread that was closed but apparently I'm not the only one trying to find out why this is occurring.

**Comment by segiddins** [comment]
Does https://github.com/CocoaPods/CocoaPods/issues/5747 fix this for you? If so, @benasher44 it seems like there's an example project attached here that could be a useful integration spec?

**Comment by benasher44** [comment]
While I can now reproduce this reliably in my own project, @Coeur that sample project doesn't reproduced the issue for me.

**Comment by lifely** [comment]
I can confirm this bug as well, since i'm just working on updating our base-code to xcode 8.0 and swift 2.3/3.0 i could easily fix this issue by commenting my target links like so : 

```
abstract_target 'defaults' do 
     ...
     ..

     target 'Thalys'                                                                                                                                                                                              
#   target 'Thalys Recette'                                                                                                                                                                                    
#   target 'Thalys Recette 2'                                                                                                                                                                                  
#   target 'Thalys Recette 3'                                                                                                                                                                                  
#   target 'Thalys Recette 8'                                                                                                                                                                                  
#   target 'Thalys Pre-Production'                                                                                                                                                                             
#   target 'Thalys Production'      

end
```

It will help me for now, but i'll need a solution in the long term

**Comment by BarlowTucker** [comment]
I had this issue as well.  I was able to resolve it by setting the `Use Legacy Swift Language Version` to `YES` for my Test targets (it was unspecified).  It appears that all the targets have to manually be set to the same Swift version to work.

**Comment by Legoless** [comment]
This issue still remains in 1.1.0.rc2. I'll post more info later.

**Comment by Coeur** [comment]
No @Legoless, I tried it with each release of CocoaPods, and this issue is not happening anymore. You are probably facing #5864, i.e. mixing different Swift versions.
