### ISSUE TITLE
pod install with version failed

### ISSUE THREAD

**Issue by vani2** [CocoaPods/CocoaPods#5756]
## What did you do?

Run `pod _0.39_ install`

## What did you expect to happen?

Install all pod dependencies correctly (on my other MacBooks it just works).

### Error

```
NoMethodError - undefined method `to_ary' for #<Pod::Specification name="AFDownloadRequestOperation">
Did you mean?  to_query
/Users/build/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/resolver/lazy_specification.rb:14:in `method_missing'
/Users/build/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:64:in `flatten'
/Users/build/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:64:in `block in resolve'
/Users/build/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:63:in `tap'
/Users/build/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:63:in `resolve'
/Users/build/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:539:in `block in resolve_dependencies'
/Users/build/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Users/build/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:537:in `resolve_dependencies'
/Users/build/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:70:in `analyze'
/Users/build/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:213:in `analyze'
/Users/build/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:136:in `block in resolve_dependencies'
/Users/build/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Users/build/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:135:in `resolve_dependencies'
/Users/build/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:105:in `install!'
/Users/build/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/build/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:101:in `run'
/Users/build/.rvm/gems/ruby-2.3.0@global/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Users/build/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Users/build/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/Users/build/.rvm/rubies/ruby-2.3.0/bin/pod:23:in `load'
/Users/build/.rvm/rubies/ruby-2.3.0/bin/pod:23:in `<main>'
/Users/build/.rvm/gems/ruby-2.3.0@global/bin/ruby_executable_hooks:15:in `eval'
/Users/build/.rvm/gems/ruby-2.3.0@global/bin/ruby_executable_hooks:15:in `<main>'
```

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.6 (15G31)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /Users/build/.rvm/rubies/ruby-2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 272c14412e87066df8ad64d1dee4bc847b6f8937
```

### Installation Source

```
Executable Path: /Users/build/.rvm/rubies/ruby-2.3.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '7.0'
inhibit_all_warnings!

xcodeproj '<my private project>/<my private file>.xcodeproj'

target :code, :exclusive => true do
    link_with '<my private target>'
    
    pod 'AFNetworking'
    pod 'AFDownloadRequestOperation'
    pod 'RXCollections'
    pod 'Reachability', '3.1.0'
    pod 'TTTAttributedLabel', '=1.13.4'
    pod 'MagicalRecord'
    pod 'SDWebImage', '=2.7.4'
    pod 'hpple', '=0.1.0'
    pod 'ViewDeck', '=2.2.11'
    pod 'CocoaSecurity', '~> 1.2.1'
    pod 'lua'
    pod 'SSKeychain', :git => 'https://github.com/<my private account>/sskeychain.git'
    pod 'GoogleTagManager'
    pod 'HexColors', '~> 2.2.1'
    pod 'ReactiveCocoa', '~> 2.3.1'
    pod 'AppsFlyer-SDK', :git => 'https://github.com/<my private account>/AppsFlyer-SDK.git'
    pod 'FXBlurView', '~> 1.6.2'
    pod 'Crashlytics'
    pod 'Fabric'
    pod 'Nimbus'
    pod 'CMPopTipView'
    pod 'GoogleMaps'
    pod 'YandexMobileMetrica'
    pod 'CocoaLumberjack'
    pod 'AKPickerView'
    pod 'FLKAutoLayout'
    pod 'ORStackView'
    pod 'Shimmer'
    pod 'HCSStarRatingView', '~> 1.4.3'
    pod 'SCPageViewController', '~> 2.0.5'
    pod 'AFNetworkActivityLogger'
    pod 'FBSDKCoreKit', '~> 4.10.1'
    pod 'FBSDKShareKit','~> 4.10.1'
    pod 'SSZipArchive'
    pod 'SignalR-ObjC'
end


target '<my private repo>', :exclusive => true do
    pod 'AFNetworking'
    pod 'OCMock', '~>3.1'
    pod 'MagicalRecord'
    pod 'Kiwi'
end

target '<my other target>', :exclusive => true do
    pod 'AFNetworking'
    pod 'Reachability', '3.1.0'
    pod '<my private repo>', :git => 'https://github.com/<my private account>/<my private repo>.git', :branch => 'devel_lib', :tag => '0.1.0'
    pod 'CocoaSecurity', '~> 1.2.1'
    pod 'SSKeychain', :git => 'https://github.com/<my private account>/sskeychain.git'
    pod 'GoogleTagManager'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_STRICT_OBJC_MSGSEND'] = 'NO'
        end
    end
    
    target = installer.pods_project.targets.find{|t| t.to_s == "MagicalRecord"}
    target.build_configurations.each do |config|
        s = config.build_settings['GCC_PREPROCESSOR_DEFINITIONS']
        s = [ '$(inherited)' ] if s == nil;
        s.push('MR_LOGGING_DISABLED=1') if config.to_s == "Debug";
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = s
    end
end
```

**Comment by neonichu** [comment]
CocoaPods 0.39 doesn't support Ruby 2.3
