### ISSUE TITLE
Errno::EEXIST - File exists when adding SWIFT_VERSION = 2.3; to project file

### ISSUE THREAD

**Issue by tompson** [CocoaPods/CocoaPods#5765]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

- Opened the project in Xcode 8 Beta 6
- Run convert Swift 2.3 (this adds SWIFT_VERSION = 2.3;  to the project file)
- Run `pod install`

## What did you expect to happen?
Install all pod dependencies correctly.

## What happened instead?
I get the following error

### Error

```
Errno::EEXIST - File exists - /Users/tom/Development/myproject/Pods/Target Support Files/AFAmazonS3Manager
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.1/lib/cocoapods/installer/xcode/pods_project_generator/target_installer.rb:92:in `mkdir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.1/lib/cocoapods/installer/xcode/pods_project_generator/target_installer.rb:92:in `mkdir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.1/lib/cocoapods/installer/xcode/pods_project_generator/target_installer.rb:92:in `create_support_files_dir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.1/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:21:in `block in install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.1/lib/cocoapods/user_interface.rb:142:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.1/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:19:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:155:in `block (2 levels) in install_libraries'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:153:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:153:in `block in install_libraries'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.1/lib/cocoapods/user_interface.rb:142:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:152:in `install_libraries'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:64:in `generate!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.1/lib/cocoapods/installer.rb:181:in `block in generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.1/lib/cocoapods/installer.rb:180:in `generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.1/lib/cocoapods/installer.rb:116:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.1/lib/cocoapods/command/install.rb:37:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.1/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

### Stack

```
   CocoaPods : 1.1.0.beta.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12 (16A294a)
       Xcode : 8.0 (8S201h)
         Git : git version 2.9.3
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 8a66fac331354e69c2db21b57815316aa9ea34e0
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
platform :ios, '8.1'
# Uncomment this line if you're using Swift
# use_frameworks!
#

def shared_pods
    pod 'CocoaLumberjack'
    pod 'ZipArchive', '~> 1.4.0'
    pod 'AFAmazonS3Manager'
end

target 'Auftragserfassung' do
  shared_pods
end

target 'AuftragserfassungTest' do
  shared_pods
end
```

**Comment by DanToml** [comment]
This was fixed on master by #5760

**Comment by Legoless** [comment]
I still get this though in 1.1.0.rc2.

**Comment by Coeur** [comment]
@Legoless, you are probably facing #5864, i.e mixing Swift versions.

**Comment by Legoless** [comment]
You're right @Coeur. The error was so similar, I figured this was the problem on start. Thanks!
