### ISSUE TITLE
Pod update is unable to complete

### ISSUE THREAD

**Issue by BenMaer** [CocoaPods/CocoaPods#5767]
🌈

* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
Attempting to do 'pod update' fails.

Note that I replaced all mentions of my folder name, which included my real name, with "[myUsername]", without the quotes, to remain anonymous. I hope that's not confusing.

## What did you do?
Ran `pod update` from terminal.

ℹ Please replace this with what you did.  
e.g. Run `pod update`

## What did you expect to happen?
Update all pod dependencies correctly.

## What happened instead?
The `pod update` command wasn't able to finish. I get the following errors:
### Error

```
Errno::ENOENT - No such file or directory @ realpath_rec - /Users/[myUsername]/Documents/Repositories/Resplendent/ResplendentRestkit/Example/Pods/RestKit/Vendor
/Users/[myUsername]/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/project.rb:186:in `realpath'
/Users/[myUsername]/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/project.rb:186:in `realpath'
/Users/[myUsername]/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/project.rb:186:in `add_file_reference'
/Users/[myUsername]/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/file_references_installer.rb:185:in `block (2 levels) in add_file_accessors_paths_to_pods_group'
/Users/[myUsername]/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/file_references_installer.rb:183:in `each'
/Users/[myUsername]/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/file_references_installer.rb:183:in `block in add_file_accessors_paths_to_pods_group'
/Users/[myUsername]/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/file_references_installer.rb:178:in `each'
/Users/[myUsername]/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/file_references_installer.rb:178:in `add_file_accessors_paths_to_pods_group'
/Users/[myUsername]/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/file_references_installer.rb:72:in `block in add_source_files_references'
/Users/[myUsername]/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:141:in `message'
/Users/[myUsername]/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/file_references_installer.rb:71:in `add_source_files_references'
/Users/[myUsername]/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/file_references_installer.rb:37:in `install!'
/Users/[myUsername]/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:609:in `install_file_references'
/Users/[myUsername]/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:169:in `block in generate_pods_project'
/Users/[myUsername]/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/Users/[myUsername]/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:167:in `generate_pods_project'
/Users/[myUsername]/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:119:in `install!'
/Users/[myUsername]/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/command/update.rb:60:in `run'
/Users/[myUsername]/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Users/[myUsername]/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'
/Users/[myUsername]/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
/Users/[myUsername]/.rbenv/versions/2.3.1/bin/pod:23:in `load'
/Users/[myUsername]/.rbenv/versions/2.3.1/bin/pod:23:in `<main>'
```

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.6 (15G31)
       Xcode : 7.3 (7D175)
         Git : git version 2.6.4 (Apple Git-63)
Ruby lib dir : /Users/[myUsername]/.rbenv/versions/2.3.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 96d7724f85b3d3ce4248d6cb1d384b125a9355d9
```

### Installation Source

```
Executable Path: /Users/[myUsername]/.rbenv/versions/2.3.1/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
use_frameworks!

target 'ResplendentRestkit_Example' do
  pod 'ResplendentRestkit', :path => '../'

  target 'ResplendentRestkit_Tests' do
    inherit! :search_paths

    
  end
end
```

## Project that demonstrates the issue
The "Example" project in the following library: [ResplendentRestkit](https://github.com/Resplendent/ResplendentRestkit)

**Comment by segiddins** [comment]
Seems to be an issue with the cached data in the `Pods` directory -- `rm -rf Pods && pod update` worked for me

**Comment by BenMaer** [comment]
That resolved my issue. I somehow seem to be able to hit it every once in a while, which is odd, but I can resolve the issue by doing what you posted, or by re cloning.
