### ISSUE TITLE
RuntimeError - [!] Xcodeproj doesn't know about the following attributes {"fileEncoding"=>"4"} for the 'PBXGroup' isa.

### ISSUE THREAD

**Issue by KingWu123** [CocoaPods/CocoaPods#5773]
――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ f0aeaffe7881df645b75512dc298cd459988035b
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

### Podfile

```ruby
platform :ios, '7.0'
#use_frameworks!个别需要用到它，比如reactiveCocoa

target 'PRIS_iPhone' do
    pod 'FMDB', '~>2.6'
    # pod 'FMDB/FTS'   # FMDB with FTS
    # pod 'FMDB/standalone'   # FMDB with latest SQLite amalgamation source
    # pod 'FMDB/standalone/FTS'   # FMDB with latest SQLite amalgamation source and FTS
    # pod 'FMDB/SQLCipher'   # FMDB with SQLCipher'


    pod 'SDWebImage', '~>3.7.4'

    pod 'Masonry', '~> 0.6.4'
end
```

### Error

```
RuntimeError - [!] Xcodeproj doesn't know about the following attributes {"fileEncoding"=>"4"} for the 'PBXGroup' isa.
If this attribute was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.1.0/lib/xcodeproj/project/object.rb:321:in `configure_with_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.1.0/lib/xcodeproj/project.rb:258:in `new_from_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.1.0/lib/xcodeproj/project/object.rb:350:in `object_with_uuid'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.1.0/lib/xcodeproj/project/object.rb:300:in `block (2 levels) in configure_with_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.1.0/lib/xcodeproj/project/object.rb:299:in `each'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.1.0/lib/xcodeproj/project/object.rb:299:in `block in configure_with_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.1.0/lib/xcodeproj/project/object.rb:296:in `each'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.1.0/lib/xcodeproj/project/object.rb:296:in `configure_with_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.1.0/lib/xcodeproj/project.rb:258:in `new_from_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.1.0/lib/xcodeproj/project/object.rb:350:in `object_with_uuid'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.1.0/lib/xcodeproj/project/object.rb:300:in `block (2 levels) in configure_with_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.1.0/lib/xcodeproj/project/object.rb:299:in `each'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.1.0/lib/xcodeproj/project/object.rb:299:in `block in configure_with_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.1.0/lib/xcodeproj/project/object.rb:296:in `each'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.1.0/lib/xcodeproj/project/object.rb:296:in `configure_with_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.1.0/lib/xcodeproj/project.rb:258:in `new_from_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.1.0/lib/xcodeproj/project/object.rb:350:in `object_with_uuid'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.1.0/lib/xcodeproj/project/object.rb:290:in `block in configure_with_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.1.0/lib/xcodeproj/project/object.rb:287:in `each'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.1.0/lib/xcodeproj/project/object.rb:287:in `configure_with_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.1.0/lib/xcodeproj/project.rb:258:in `new_from_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.1.0/lib/xcodeproj/project.rb:202:in `initialize_from_file'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.1.0/lib/xcodeproj/project.rb:102:in `open'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:695:in `block (2 levels) in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:694:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:694:in `block in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:689:in `inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:66:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:227:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:151:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:150:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:114:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command/install.rb:37:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

**Comment by neonichu** [comment]
Are you able to share the project this is happening with? Was it created by Xcode or by some other means?

**Comment by neonichu** [comment]
Closing because of lack of activity.
