### ISSUE TITLE
NoMethodError - undefined method `platform' for nil:NilClass error after running pod install from master branch

### ISSUE THREAD

**Issue by gridNA** [CocoaPods/CocoaPods#5783]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

1) cloned unreleased feature from CocoaPods: git clone https://github.com/CocoaPods/CocoaPods.git
2) git checkout master
3) bundle install
4) /Users/kgridina/cocoapods/CocoaPods/bin/pod install

## What did you expect to happen?

The app should run as with previous version (0.39.0) of CocaPods

## Error

```
NoMethodError - undefined method `platform' for nil:NilClass
/Users/kgridina/cocoapods/CocoaPods/lib/cocoapods/installer/analyzer.rb:320:in `block in analyze_host_targets_in_podfile'
/Users/kgridina/cocoapods/CocoaPods/lib/cocoapods/installer/analyzer.rb:329:in `call'
/Users/kgridina/cocoapods/CocoaPods/lib/cocoapods/installer/analyzer.rb:329:in `block (2 levels) in analyze_host_targets_in_podfile'
/Users/kgridina/cocoapods/CocoaPods/lib/cocoapods/installer/analyzer.rb:328:in `each'
/Users/kgridina/cocoapods/CocoaPods/lib/cocoapods/installer/analyzer.rb:328:in `block in analyze_host_targets_in_podfile'
/Users/kgridina/cocoapods/CocoaPods/lib/cocoapods/installer/analyzer.rb:326:in `each'
/Users/kgridina/cocoapods/CocoaPods/lib/cocoapods/installer/analyzer.rb:326:in `analyze_host_targets_in_podfile'
/Users/kgridina/cocoapods/CocoaPods/lib/cocoapods/installer/analyzer.rb:354:in `generate_targets'
/Users/kgridina/cocoapods/CocoaPods/lib/cocoapods/installer/analyzer.rb:78:in `analyze'
/Users/kgridina/cocoapods/CocoaPods/lib/cocoapods/installer.rb:236:in `analyze'
/Users/kgridina/cocoapods/CocoaPods/lib/cocoapods/installer.rb:150:in `block in resolve_dependencies'
/Users/kgridina/cocoapods/CocoaPods/lib/cocoapods/user_interface.rb:64:in `section'
/Users/kgridina/cocoapods/CocoaPods/lib/cocoapods/installer.rb:149:in `resolve_dependencies'
/Users/kgridina/cocoapods/CocoaPods/lib/cocoapods/installer.rb:110:in `install!'
/Users/kgridina/cocoapods/CocoaPods/lib/cocoapods/command/install.rb:37:in `run'
/Users/kgridina/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/CLAide-61071679fc96/lib/claide/command.rb:334:in `run'
/Users/kgridina/cocoapods/CocoaPods/lib/cocoapods/command.rb:50:in `run'
/Users/kgridina/cocoapods/CocoaPods/bin/pod:55:in `<main>'
```
## CocoaPods Environment

 ```
CocoaPods : 1.1.0.beta.1
        Ruby : ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]
    RubyGems : 2.4.8
        Host : Mac OS X 10.11.3 (15D21)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /Users/kgridina/.rbenv/versions/2.2.3/lib
Repositories : accengage - https://github.com/Accengage/CocoaPodsSpecs.git @ 66e9de64664678ebeb70d8f67db79bc130c6f019
               master - https://github.com/CocoaPods/Specs.git @ 547c51a9a0bda950ab7dcb2157be2be6714805b7
               zalando-scm-shop-mobile-specs - https://stash.zalando.net/scm/shop-mobile/specs.git @ 7944fca15a750e02bc6ed61d467525fb88a5ac33

```
## Plugins

```
claide-plugins         : 0.9.0
cocoapods-deintegrate  : 1.0.0
cocoapods-dependencies : 1.0.0.beta.1
cocoapods-plugins      : 1.0.0
cocoapods-search       : 1.0.0
cocoapods-stats        : 1.0.0
cocoapods-trunk        : 1.0.0
cocoapods-try          : 1.1.0
cocoapods_debug        : 0.1.0
```

## Podfile

```ruby
require_relative 'scripts/xcode_helper'

def z_project(proj)
  project "#{proj}/#{proj}"
end

source 'https://github.com/Accengage/CocoaPodsSpecs.git'
source 'https://stash.zalando.net/scm/shop-mobile/specs.git'
source 'https://github.com/CocoaPods/Specs'

platform :ios, '8.0'

inhibit_all_warnings!
use_frameworks!

def app
  pod 'AFNetworkActivityLogger', '2.0.4'
  pod 'Apptimize', '~> 2.16'
  pod 'CHTCollectionViewWaterfallLayout', '~> 0.9'
  pod 'GNAContextMenu', git: 'git://github.com/haldun/GNAContextMenu.git', branch: 'master'
  pod 'GoogleAppIndexing', '~> 2.0'
  pod 'HockeySDK', '~> 3'
  pod 'IntelligentSplitViewController', '~> 1.2'
  pod 'JLRoutes', git: 'https://github.com/diamondsky/JLRoutes.git', commit: 'a3bf7b19a7f2ea9705a74f5c056811165c150e98'
  pod 'JRSwizzle', '1.0'
  pod 'PEPhotoCropEditor', git: 'git://github.com/gdj4ever/PEPhotoCropEditor.git', tag: 'v1.3.3'
  pod 'Reachability', '3.2'
  pod 'RMDateSelectionViewController', '~> 1.5'
  pod 'SVPullToRefresh', '0.4.1'
  pod 'SwipeView', '1.3.2'
  pod 'Timepiece', '~> 0.4'
  pod 'ZDBCamera', '2.3.21'
end

def foundation
  pod 'Adjust/Criteo', '~> 4.8'
  pod 'AFNetworking', '~> 2.5'
  pod 'SDWebImage', '~> 3.7'
  pod 'TransformerKit', '0.5.4'
  pod 'TWMessageBarManager', git: 'ssh://git@stash.zalando.net:7999/~dgeorgakopou/twmessagebarmanager.git', branch: 'master'
  pod 'ZMantle', '~> 2.0'
  pod 'Accengage-iOS-SDK', '~> 5.5'
end

def animation
  pod 'zpop', '1.0.9'
end

def carousel
  pod 'iCarousel', '~> 1.8'
end

def forms
  pod '1PasswordExtension', '~> 1.8'
  pod 'TPKeyboardAvoiding', '~> 1.2'
  pod 'TTTAttributedLabel', '~> 1.13'
end

def account
  pod 'FXKeychain', '~> 1.5'
  #Fix for the issue https://github.com/mxcl/PromiseKit/issues/415
  #Please point to the original repo after it is fixed
  pod 'PromiseKit', git: 'https://github.com/yunuserenguzel/PromiseKit.git', branch: 'hot_fix'
  pod 'ZFormatterKit'
end

def article
  pod 'Agrume', '~> 2.2'
  pod 'JTSImageViewController', '~> 1.4'
end

def json_parsing
  pod 'ObjectMapper', '~> 1.2'
end

def flexible_layout
  json_parsing
end

def coupon_box
  pod 'Timepiece', '~> 0.4'
  json_parsing
end

def common_tests
  pod 'ZTest', '0.1.3'
  pod 'SwiftHamcrest', '~> 0.4'
end

def all
  account
  animation
  app
  article
  carousel
  forms
  foundation
  flexible_layout
  coupon_box
end

# --- Targets

workspace 'zalando'
z_project 'zalando'

target :zalando do
  all
end

target :zalandoTests do
  common_tests
end

target :zalandoUITests do
  common_tests
  pod 'AMYServer', '~> 2.1'
  pod 'KIF/IdentifierTests', '3.2.2'
end

target :ZalandoFoundation do
  z_project 'ZalandoFoundation'
  pod 'AppDynamicsAgent', '~> 42.3.0'
  pod 'Google/Analytics'
  pod 'GoogleIDFASupport'
  foundation
end

# --- Targets: Main App Modules

target :DeliveryTracking do
  z_project 'DeliveryTracking'
  foundation
  animation
end

target :FormBuilder do
  z_project 'FormBuilder'
  foundation
  forms
end

target :ZalandoAccount do
  z_project 'ZalandoAccount'
  foundation
  forms
  account
end

target :ZalandoArticle do
  z_project 'ZalandoArticle'
  foundation
  forms
  account
  article
end

target :ZalandoCarts do
  z_project 'ZalandoCarts'
  foundation
  forms
  account
end

target :ZTeaser do
  z_project 'ZTeaser'
  foundation
  carousel
end

# --- Targets: FlexibleLayoutKit

target :FlexibleLayoutKit do
  z_project 'FlexibleLayoutKit'
  flexible_layout
end

target :FlexibleLayoutDemo do
  z_project 'FlexibleLayoutKit'
  flexible_layout
end

target :FlexibleLayoutKitTests do
  z_project 'FlexibleLayoutKit'
  common_tests
end

target :FlexibleLayoutDemoTests do
  z_project 'FlexibleLayoutKit'
  common_tests
end

# --- Targets: ZalandoFilters

target :ZalandoFilters do
  z_project 'ZalandoFilters'
  json_parsing
end

target :ZalandoFiltersTests do
  z_project 'ZalandoFilters'
  common_tests
end

# --- Targets: CouponBox

target :CouponBox do
  z_project 'CouponBox'
  coupon_box
end

target :CouponBoxTests do
  z_project 'CouponBox'
  common_tests
end

# --- Scripts

post_install do |installer|
  update_pods_builds_settings(installer)
  XcodeHelper.update_projects_build_settings
  XcodeHelper.convert_projects_to_plist_format
end

def update_pods_builds_settings(installer)
  installer.pods_project.targets.each do |target|
    XcodeHelper.set_default_build_settings(target)
  end
end
```

**Comment by benasher44** [comment]
@gridNA I'm going to have a branch up for you soon that I'd like you to try to get some more detailed error info.

**Comment by benasher44** [comment]
@gridNA can you try installing using this branch:
```
gem 'cocoapods', :git => 'https://github.com/benasher44/CocoaPods', :branch => 'basher_plaform_nil'
```
This is just CocoaPods master + some exceptions I added to help try to debug this.

**Comment by gridNA** [comment]
Hi @benasher44 

I tried it and got this error:
`[!] Missing target definition for host uuid: 34EFE97E349EAF275CD2AFA12CD73CF7`

**Comment by benasher44** [comment]
@gridNA can you grep through your project file for `34EFE97E349EAF275CD2AFA12CD73CF7` and infer which target this uuid refers to? This'll help me debug further

**Comment by gridNA** [comment]
@benasher44 this is `ZalandoFoundationTests` target, which is inside ZalandoFoundation module.

**Comment by benasher44** [comment]
@gridNA thanks that's helpful! I've updated my branch, can you update and try pod install'ing again?

**Comment by benasher44** [comment]
@gridNA I was able to reproduce this issue, and #5795 is open to fix it. It's using the same `basher_plaform_nil` branch. I'd appreciate if you could update with the latest commits pushed to that branch and verify the fix!

**Comment by gridNA** [comment]
cool, works for me, thanks a lot @benasher44.

**Comment by benasher44** [comment]
Going to keep this open until the PR is merged
