### ISSUE TITLE
ArgumentError - user usr doesn't exist

### ISSUE THREAD

**Issue by jordanHochstetler** [CocoaPods/CocoaPods#5788]
Jordans-Macintosh:MFXEditor jordanhochstetler$ pod update
Update all pods

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
### Command

```
/Users/jordanhochstetler/.rvm/gems/ruby-2.3.0/bin/pod update
```
### Report
- What did you do?
- What did you expect to happen?
- What happened instead?
### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.6.6
        Host : Mac OS X 10.11.6 (15G31)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /Users/jordanhochstetler/.rvm/rubies/ruby-2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ fe61532e9dd23a025c69b660a180adccf9b844b1
```
### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```
### Podfile

``` ruby
project ’MFX Editor'
use_frameworks!

target 'MFX Editor' do
pod 'Flurry-iOS-SDK/FlurrySDK', '~> 7.6'
end
```
### Error

```
ArgumentError - user usr doesn't exist
/Users/jordanhochstetler/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/executable.rb:93:in `expand_path'
/Users/jordanhochstetler/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/executable.rb:93:in `block in which'
/Users/jordanhochstetler/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/executable.rb:92:in `each'
/Users/jordanhochstetler/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/executable.rb:92:in `which'
/Users/jordanhochstetler/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/executable.rb:110:in `which!'
/Users/jordanhochstetler/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/executable.rb:133:in `capture_command'
/Users/jordanhochstetler/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/sources_manager.rb:102:in `git'
/Users/jordanhochstetler/.rvm/gems/ruby-2.3.0/gems/cocoapods-core-1.0.1/lib/cocoapods-core/source.rb:45:in `block in url'
/Users/jordanhochstetler/.rvm/gems/ruby-2.3.0/gems/cocoapods-core-1.0.1/lib/cocoapods-core/source.rb:44:in `chdir'
/Users/jordanhochstetler/.rvm/gems/ruby-2.3.0/gems/cocoapods-core-1.0.1/lib/cocoapods-core/source.rb:44:in `url'
/Users/jordanhochstetler/.rvm/gems/ruby-2.3.0/gems/cocoapods-core-1.0.1/lib/cocoapods-core/source/manager.rb:347:in `block in source_with_url'
/Users/jordanhochstetler/.rvm/gems/ruby-2.3.0/gems/cocoapods-core-1.0.1/lib/cocoapods-core/source/manager.rb:346:in `each'
/Users/jordanhochstetler/.rvm/gems/ruby-2.3.0/gems/cocoapods-core-1.0.1/lib/cocoapods-core/source/manager.rb:346:in `find'
/Users/jordanhochstetler/.rvm/gems/ruby-2.3.0/gems/cocoapods-core-1.0.1/lib/cocoapods-core/source/manager.rb:346:in `source_with_url'
/Users/jordanhochstetler/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/sources_manager.rb:18:in `find_or_create_source_with_url'
/Users/jordanhochstetler/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:654:in `block in sources'
/Users/jordanhochstetler/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:653:in `map'
/Users/jordanhochstetler/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:653:in `sources'
/Users/jordanhochstetler/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:144:in `resolve_dependencies'
/Users/jordanhochstetler/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:114:in `install!'
/Users/jordanhochstetler/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/command/update.rb:60:in `run'
/Users/jordanhochstetler/.rvm/gems/ruby-2.3.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Users/jordanhochstetler/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'
/Users/jordanhochstetler/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
/Users/jordanhochstetler/.rvm/gems/ruby-2.3.0/bin/pod:23:in `load'
/Users/jordanhochstetler/.rvm/gems/ruby-2.3.0/bin/pod:23:in `<main>'
/Users/jordanhochstetler/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/Users/jordanhochstetler/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

**Comment by segiddins** [comment]
Out of curiosity, what's the output of `env` and `ruby -e 'p Dir.home'`?

**Comment by jordanHochstetler** [comment]
"/Users/jordanhochstetler"

**Comment by segiddins** [comment]
What's the output running with `--verbose`? I have a hunch about what the underlying cause may be (a file named `~usr` somewhere)

**Comment by jordanHochstetler** [comment]
I get the same exact output when I do --verbose. I think you're on the right track though. I'm still working on this issue

**Comment by benasher44** [comment]
Can you update to CocoaPods 1.1.0 RC 3? The code path in question here has changed a lot, and I don't think this should be an issue anymore.

**Comment by orta** [comment]
Closing due to inactivity

**Comment by oey** [comment]
Got the same kind of error, replace usr with bin. Looked eventually at the source file executable.rb, which pointed me at $PATH which contained a typo ~bin instead of ~/bin

Fixed my path, and pod works as expected.

**Comment by ndoctor13** [comment]
Did you get this resolved? If yes, what did you do? I am getting the below error and no command seems to work. Its a similar error I believe

Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/executable.rb:93:in `expand_path': user .composer doesn't exist (ArgumentError)
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/executable.rb:93:in `block in which'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/executable.rb:92:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/executable.rb:92:in `which'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/executable.rb:110:in `which!'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/executable.rb:133:in `capture_command'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/command.rb:116:in `git_version'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/command.rb:128:in `verify_minimum_git_version!'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/command.rb:49:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/bin/pod:55:in `<top (required)>'
	from /usr/local/bin/pod:23:in `load'
	from /usr/local/bin/pod:23:in `<main>'
