### ISSUE TITLE
'pod search' broken, not sure how I broke it

### ISSUE THREAD

**Issue by xaphod** [CocoaPods/CocoaPods#5792]
I can't search for pods anymore. How'd I break this? pod update and pod install still work fine.

### Command

```
/Users/Tim/.rvm/gems/ruby-2.3.0/bin/pod search foo
```

### Report

* What did you do?
Searched for a pod
* What did you expect to happen?
Search to complete
* What happened instead?
Crash

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.6 (15G31)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /Users/Tim/.rvm/rubies/ruby-2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 45846a245a1c683b0133485366fc2c7a74b2c2df
               xaphod - https://github.com/xaphod/podspecs.git @ 11230bdb2b37f195ef92b6b3a08b5fa6cb4ba221
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/xaphod/podspecs.git'

target 'MyTarget' do
platform :ios, '8.1'
pod 'CocoaLumberjack', '~> 2.3.0' # for CocoaHTTPServer -> EyeFi
pod 'AFNetworking', '~> 3.0'
pod 'Bluepeer' # xaphod spec repo
end

target 'Watch' do
platform :watchos, '2.2'
#pod 'JBWatchActivityIndicator', :git => 'https://github.com/xaphod/JBWatchActivityIndicator.git'
end

target 'Watch Extension' do
platform :watchos, '2.2'
#pod 'JBWatchActivityIndicator', :git => 'https://github.com/xaphod/JBWatchActivityIndicator.git'
end
```

### Error

```
JSON::ParserError - 784: unexpected token at 's":["SwisscomKit"]}}'
/Users/Tim/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/json/common.rb:156:in `parse'
/Users/Tim/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/json/common.rb:156:in `parse'
/Users/Tim/.rvm/gems/ruby-2.3.0/gems/cocoapods-core-1.0.1/lib/cocoapods-core/source/manager.rb:251:in `stored_search_index'
/Users/Tim/.rvm/gems/ruby-2.3.0/gems/cocoapods-core-1.0.1/lib/cocoapods-core/source/manager.rb:187:in `updated_search_index'
/Users/Tim/.rvm/gems/ruby-2.3.0/gems/cocoapods-core-1.0.1/lib/cocoapods-core/source/manager.rb:118:in `search_by_name'
/Users/Tim/.rvm/gems/ruby-2.3.0/gems/cocoapods-search-1.0.0/lib/cocoapods-search/command/search.rb:87:in `local_search'
/Users/Tim/.rvm/gems/ruby-2.3.0/gems/cocoapods-search-1.0.0/lib/cocoapods-search/command/search.rb:63:in `run'
/Users/Tim/.rvm/gems/ruby-2.3.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Users/Tim/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'
/Users/Tim/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
/Users/Tim/.rvm/gems/ruby-2.3.0/bin/pod:23:in `load'
/Users/Tim/.rvm/gems/ruby-2.3.0/bin/pod:23:in `<main>'
/Users/Tim/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/Users/Tim/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by neonichu** [comment]
There doesn't seem to be a "SwisscomKit" pod in the master repo, so my guess would be there's an invalid podspec in a private spec repo you're using. You could try identifying it using `pod repo lint`.

**Comment by xaphod** [comment]
Hi @neonichu thanks for your comment.
Here is some pod repo output:

    Tim-rMBP:folder Tim$ pod repo list

	master
	- Type: git (master)
	- URL:  https://github.com/CocoaPods/Specs.git
	- Path: /Users/Tim/.cocoapods/repos/master

	xaphod
	- Type: git (master)
	- URL:  https://github.com/xaphod/podspecs.git
	- Path: /Users/Tim/.cocoapods/repos/xaphod

	2 repos
    
	Tim-rMBP:folder Tim$ pod repo lint xaphod

	Linting spec repo `xaphod`

	.........

	Analyzed 9 podspecs files.

	All the specs passed validation.

	Tim-rMBP:Photobooth Tim$

... so I guess something somehow got corrupted with my master repo? How can I fix it? I did run just "pod repo lint" and there was a TON of output, with a ton of red / bad stuff.

**Comment by neonichu** [comment]
Could be that there was an invalid podspec around when the search cache was originally created — could you try `rm ~/Library/Caches/CocoaPods/search_index.json` and see if the result changes.

**Comment by xaphod** [comment]
Hi @neonichu that file doesn't exist as root or as my local user. What else ?

**Comment by xaphod** [comment]
Ah, I found this command I didn't know about, and it fixed it: `pod cache clean --all`
