### ISSUE TITLE
'trunk' is updating local remote.origin to point to CocoaPods/Specs. wat.

### ISSUE THREAD

**Issue by jessesquires** [CocoaPods/CocoaPods#5823]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

🌈 

# Report

## What did you do?

`pod trunk push JSQWebViewController.podspec`

Trying to push [JSQWebViewController 4.0.0](https://github.com/jessesquires/JSQWebViewController/releases/tag/4.0.0).

## What did you expect to happen?

`trunk` works like it always has

## What happened instead?

CocoaPods updates my local repo `remote.origin` to `remote.origin.url=https://github.com/CocoaPods/Specs.git`. And then fails with the error:

```
Validating podspec
 -> JSQWebViewController (4.0.0)
    - ERROR | [iOS] unknown: Encountered an unknown error (Must be in the root of the repo (/Users/jesse/.cocoapods/repos/master), instead in /Users/jesse/GitHub/JSQWebViewController.) during validation.

[!] The spec did not pass validation, due to 1 error.
```

Running `git config -l` before and after running `trunk` clearly shows this. Obviously, remote should be `https://github.com/jessesquires/JSQWebViewController.git`, and CocoaPods should *not* be modifying this... 

lolwut

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.1.3p242 (2014-09-19 revision 47630) [x86_64-darwin14.0]
    RubyGems : 2.2.2
        Host : Mac OS X 10.11.6 (15G1004)
       Xcode : 8.0 (8A218a)
         Git : git version 2.10.0
Ruby lib dir : /usr/local/var/rbenv/versions/2.1.3/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ ce9b9413f59761e81d032dc8372e53d7ddc59dc7
```

### Installation Source

```
Executable Path: /usr/local/var/rbenv/versions/2.1.3/bin/pod
```

### Plugins

```
claide-plugins             : 0.9.1
cocoapods-acknowledgements : 1.1.1
cocoapods-deintegrate      : 1.0.0
cocoapods-plugins          : 1.0.0
cocoapods-search           : 1.0.0
cocoapods-stats            : 1.0.0
cocoapods-trunk            : 1.0.0
cocoapods-try              : 1.1.0
```

**Comment by benasher44** [comment]
This looks like more `Dir.chdir` failing in Xcode 8.

**Comment by benasher44** [comment]
@jessesquires looks like `pod trunk push` uses CocoaPods Core's `SourcesManager` to update the local copy of trunk. If `Dir.chdir` fails, then well it'll run git commands in your current working directory. This is fixed in CocoaPods/Core#352. Can you try setting up a Gemfile to use that Core PR? I think that'll fix it.

**Comment by jessesquires** [comment]
Thanks @benasher44 !

That's quite a workaround, considering I'll need to do that half a dozen times or more for various Swift libs that need updates. 

I ran `pod trunk push --verbose` from `~/.cocoapods/repos/master` to see what would happen. The `remote.origin` problem doesn't happen. But validation fails:

```bash
Updating spec repo `master`

CocoaPods 1.1.0.beta.2 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.1.0.beta.2

Validating podspec
    JSQWebViewController (4.0.0) - Analyzing on iOS 8.0 platform.
  Preparing

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-App`: (``)

Fetching external sources
-> Fetching podspec for `JSQWebViewController` from `/Users/jesse/GitHub/JSQWebViewController/JSQWebViewController.podspec`

Resolving dependencies of 

Comparing resolved specification to the sandbox manifest
  A JSQWebViewController

Downloading dependencies

-> Installing JSQWebViewController (4.0.0)
  > Copying JSQWebViewController from `/Users/jesse/Library/Caches/CocoaPods/Pods/External/JSQWebViewController/db247e44bea340ac0a7609c6982ec857-f5e05` to
  `../../../../../private/var/folders/tx/s__fjnns3yd_23813_gwk7sh0000gn/T/CocoaPods/Lint/Pods/JSQWebViewController`
  - Running pre install hooks

Generating Pods project
  - Creating Pods project
  - Adding source files to Pods project
  - Adding frameworks to Pods project
  - Adding libraries to Pods project
  - Adding resources to Pods project
  - Linking headers
  - Installing targets
    - Installing target `JSQWebViewController` iOS 8.0
      - Generating Info.plist file at `../../../../../private/var/folders/tx/s__fjnns3yd_23813_gwk7sh0000gn/T/CocoaPods/Lint/Pods/Target Support
      Files/JSQWebViewController/Info.plist`
      - Generating module map file at `../../../../../private/var/folders/tx/s__fjnns3yd_23813_gwk7sh0000gn/T/CocoaPods/Lint/Pods/Target Support
      Files/JSQWebViewController/JSQWebViewController.modulemap`
      - Generating umbrella header at `../../../../../private/var/folders/tx/s__fjnns3yd_23813_gwk7sh0000gn/T/CocoaPods/Lint/Pods/Target Support
      Files/JSQWebViewController/JSQWebViewController-umbrella.h`
    - Installing target `Pods-App` iOS 8.0
      - Generating Info.plist file at `../../../../../private/var/folders/tx/s__fjnns3yd_23813_gwk7sh0000gn/T/CocoaPods/Lint/Pods/Target Support Files/Pods-App/Info.plist`
      - Generating module map file at `../../../../../private/var/folders/tx/s__fjnns3yd_23813_gwk7sh0000gn/T/CocoaPods/Lint/Pods/Target Support Files/Pods-App/Pods-App.modulemap`
      - Generating umbrella header at `../../../../../private/var/folders/tx/s__fjnns3yd_23813_gwk7sh0000gn/T/CocoaPods/Lint/Pods/Target Support Files/Pods-App/Pods-App-umbrella.h`
  - Running post install hooks
  - Writing Xcode project file to `../../../../../private/var/folders/tx/s__fjnns3yd_23813_gwk7sh0000gn/T/CocoaPods/Lint/Pods/Pods.xcodeproj`
  - Writing Lockfile in `../../../../../var/folders/tx/s__fjnns3yd_23813_gwk7sh0000gn/T/CocoaPods/Lint/Podfile.lock`
  - Writing Manifest in `../../../../../private/var/folders/tx/s__fjnns3yd_23813_gwk7sh0000gn/T/CocoaPods/Lint/Pods/Manifest.lock`

Integrating client project

[!] Please close any current Xcode sessions and use `App.xcworkspace` for this project from now on.

Integrating target `Pods-App` (`../../../../../var/folders/tx/s__fjnns3yd_23813_gwk7sh0000gn/T/CocoaPods/Lint/App.xcodeproj` project)
  Adding Build Phase '[CP] Embed Pods Frameworks' to project.
  Adding Build Phase '[CP] Copy Pods Resources' to project.
  Adding Build Phase '[CP] Check Pods Manifest.lock' to project.
  - Running post install hooks
  Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.
   Building with xcodebuild. 
xcodebuild clean build -workspace App.xcworkspace -scheme App -configuration Release CODE_SIGN_IDENTITY=- -sdk iphonesimulator -destination id=18F3F746-2251-4CD4-9378-5BCD41F50A60
Build settings from command line:
    CODE_SIGN_IDENTITY = -
    SDKROOT = iphonesimulator10.0

xcodebuild: error: 'App.xcworkspace' does not exist.
 -> JSQWebViewController (4.0.0)
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code.
    - NOTE  | [iOS] xcodebuild:  xcodebuild: error: 'App.xcworkspace' does not exist.

[!] The spec did not pass validation, due to 1 error.

/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-trunk-1.0.0/lib/pod/command/trunk/push.rb:111:in `validate_podspec'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-trunk-1.0.0/lib/pod/command/trunk/push.rb:61:in `run'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'
/usr/local/var/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
/usr/local/var/rbenv/versions/2.1.3/bin/pod:23:in `load'
/usr/local/var/rbenv/versions/2.1.3/bin/pod:23:in `<main>'
```

**Comment by benasher44** [comment]
@jessesquires great! Now you've hit the bug we're discussing in #5822.

I agree this is frustrating. There are actually a few issues at play here. Once we get these fixed, there will likely be another release.

**Comment by DanToml** [comment]
Closing this as a duplicate, but it will be fixed as a part of #5822. When the issues documented in #5825 are fixed, I'll be releasing `1.1.0.rc.1` which should allow for shipping pods with Xcode 8.

**Comment by jessesquires** [comment]
Awesome! 🙌 🎉 I'll subscribe to those issues.

Thanks @benasher44 and @DanToml ! 😄

**Comment by iDevelopper** [comment]
Re-installing Xcode 7.3.1, set the path for the active developer directory of Xcode 7. This fixes the issue. Pod lint passe validation!
