### ISSUE TITLE
pod repo update error

### ISSUE THREAD

**Issue by Loayelshall** [CocoaPods/CocoaPods#5845]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

run ' pod repo update --verbose
## What did you expect to happen?

setup cocoapods repo master
e.g. Install all pod dependencies correctly.

## What happened instead?

Updating spec repo `master`
  $ /Applications/CocoaPods.app/Contents/Resources/bundle/bin/git pull --ff-only
  error: RPC failed; result=56, HTTP code = 200
  fatal: The remote end hung up unexpectedly
  fatal: early EOF
  fatal: index-pack failed

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Applications/CocoaPods.app/Contents/Resources/bundle/bin/pod repo update --verbose
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]
    RubyGems : 2.5.0
        Host : Mac OS X 10.11.6 (15G1004)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.6.2
Ruby lib dir : /Applications/CocoaPods.app/Contents/Resources/bundle/lib
Repositories : 
```

### Plugins

```
cocoapods-check           : 0.2.1.beta.1
cocoapods-deintegrate     : 1.0.0
cocoapods-plugins         : 1.0.0
cocoapods-plugins-install : 0.0.1
cocoapods-search          : 1.0.0
cocoapods-stats           : 1.0.0
cocoapods-trunk           : 1.0.0
cocoapods-try             : 1.0.0
```

### Error

```
Errno::ENOENT - No such file or directory - getcwd
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-core-1.0.0/lib/cocoapods-core/source.rb:402:in `getwd'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-core-1.0.0/lib/cocoapods-core/source.rb:402:in `pwd'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-core-1.0.0/lib/cocoapods-core/source.rb:402:in `ensure_in_repo!'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-core-1.0.0/lib/cocoapods-core/source.rb:448:in `diff_until_commit_hash'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-core-1.0.0/lib/cocoapods-core/source.rb:347:in `block in update'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-core-1.0.0/lib/cocoapods-core/source.rb:337:in `chdir'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-core-1.0.0/lib/cocoapods-core/source.rb:337:in `update'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-core-1.0.0/lib/cocoapods-core/master_source.rb:15:in `update'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0/lib/cocoapods/sources_manager.rb:87:in `block (2 levels) in update'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0/lib/cocoapods/user_interface.rb:63:in `section'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0/lib/cocoapods/sources_manager.rb:86:in `block in update'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0/lib/cocoapods/sources_manager.rb:85:in `each'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0/lib/cocoapods/sources_manager.rb:85:in `update'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0/lib/cocoapods/command/repo/update.rb:23:in `run'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0/lib/cocoapods/command.rb:50:in `run'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0/bin/pod:55:in `<top (required)>'
/Applications/CocoaPods.app/Contents/Resources/bundle/bin/pod:23:in `load'
/Applications/CocoaPods.app/Contents/Resources/bundle/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=No+such+file+or+directory+-+getcwd&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

[!] CocoaPods was not able to update the `master` repo. If this is an unexpected issue and persists you can inspect it running `pod repo update --verbose`
e.g. Pod A is missing the subspec B for target C.

**Comment by DanToml** [comment]
This seems to be a problem with your internet connection rather than with CocoaPods itself. (as it is `git pull` which is failing with a network error)
