### ISSUE TITLE
the title to this 

### ISSUE THREAD

**Issue by samyoungnyc** [CocoaPods/CocoaPods#5853]
* [y] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

Downloaded the following project: [LINK](https://www.raywenderlich.com/136692/introduction-google-cardboard-ios) - ran `pod init` then `pod install` (also tried `pod update`). 

## What did you do?
 Run `pod install`

## What did you expect to happen?
 Install 'GVRSDK' pod dependency correctly.

## What happened instead?
 The crash listed below. 

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.4 (15E65)
       Xcode : 7.3 (7D175)
         Git : git version 2.6.4 (Apple Git-63)
Ruby lib dir : /Users/hal/.rbenv/versions/2.3.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 0101b010bb538992ccdb52f9a1bbf1ea9742852d
```

### Installation Source

```
Executable Path: /Users/hal/.rbenv/versions/2.3.1/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
target "Vacation 360" do
    pod 'GVRSDK'
end
```

### Error

```
RuntimeError - [Xcodeproj] Consistency issue: no parent for object `Main Group`: ``
/Users/hal/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/xcodeproj-1.3.1/lib/xcodeproj/project/object/helpers/groupable_helper.rb:18:in `parent'
/Users/hal/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/xcodeproj-1.3.1/lib/xcodeproj/project/object/helpers/groupable_helper.rb:118:in `source_tree_real_path'
/Users/hal/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/xcodeproj-1.3.1/lib/xcodeproj/project/object/helpers/groupable_helper.rb:100:in `real_path'
/Users/hal/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/xcodeproj-1.3.1/lib/xcodeproj/project/object/helpers/groupable_helper.rb:121:in `source_tree_real_path'
/Users/hal/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/xcodeproj-1.3.1/lib/xcodeproj/project/object/helpers/groupable_helper.rb:100:in `real_path'
/Users/hal/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/xcodeproj-1.3.1/lib/xcodeproj/project/object/helpers/groupable_helper.rb:121:in `source_tree_real_path'
/Users/hal/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/xcodeproj-1.3.1/lib/xcodeproj/project/object/helpers/groupable_helper.rb:187:in `set_path_with_source_tree'
/Users/hal/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/xcodeproj-1.3.1/lib/xcodeproj/project/object/helpers/file_references_factory.rb:102:in `new_file_reference'
/Users/hal/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/xcodeproj-1.3.1/lib/xcodeproj/project/object/helpers/file_references_factory.rb:31:in `new_reference'
/Users/hal/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/xcodeproj-1.3.1/lib/xcodeproj/project/object/group.rb:222:in `new_reference'
/Users/hal/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:83:in `block in set_target_xcconfig'
/Users/hal/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:101:in `set_target_xcconfig'
/Users/hal/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:22:in `block (2 levels) in integrate'
/Users/hal/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:20:in `each'
/Users/hal/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:20:in `block in integrate'
/Users/hal/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:19:in `each'
/Users/hal/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:19:in `integrate'
/Users/hal/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/user_project_integrator/target_integrator.rb:53:in `block in integrate!'
/Users/hal/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/Users/hal/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/user_project_integrator/target_integrator.rb:52:in `integrate!'
/Users/hal/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/user_project_integrator.rb:129:in `each'
/Users/hal/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/user_project_integrator.rb:129:in `integrate_user_targets'
/Users/hal/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/user_project_integrator.rb:63:in `integrate!'
/Users/hal/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:767:in `block in integrate_user_project'
/Users/hal/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/Users/hal/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:764:in `integrate_user_project'
/Users/hal/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:120:in `install!'
/Users/hal/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/command/install.rb:37:in `run'
/Users/hal/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Users/hal/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'
/Users/hal/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
/Users/hal/.rbenv/versions/2.3.1/bin/pod:23:in `load'
/Users/hal/.rbenv/versions/2.3.1/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

## Project that demonstrates the issue

The repo below should reproduce the issue. 

https://github.com/samyoungnyc/gvrbugsampleproject.git

**Comment by dhoskins** [comment]
[https://github.com/CocoaPods/CocoaPods/issues/5847](https://github.com/CocoaPods/CocoaPods/issues/5847)
