### ISSUE TITLE
1.0.1 - upgrading a Pod breaks another one that's got nothing to do with the first

### ISSUE THREAD

**Issue by manjubasha** [CocoaPods/CocoaPods#5862]
Here is my podfile 
```
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'
inhibit_all_warnings!

xcodeproj 'AlwaysOn'
pod 'CorePlot', :git => 'https://github.com/core-plot/core-plot.git'
pod 'Google/Analytics'

target 'AlwaysOnKIFTests' do
  pod 'KIF', '~> 3.3.0'
  pod 'KIF/IdentifierTests', '~> 3.3.0'
end
```

**When i have 0.38x pod and download coreplot and Google Analytics.  Google Analytics fails with 0.38x**

```
Errno::ENOENT - No such file or directory - /Users/onlife/Documents/Xcode/Manju/Apps/G4/Manju/SampleApp/Pods/GoogleInterchangeUtilities/Frameworks/GoogleInterchangeUtilities.framework/Headers
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/sandbox/file_accessor.rb:161:in `realpath'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/sandbox/file_accessor.rb:161:in `realpath'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/sandbox/file_accessor.rb:161:in `vendored_frameworks_headers_dir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:239:in `block in vendored_frameworks_header_mappings'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:238:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:238:in `vendored_frameworks_header_mappings'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:140:in `block (3 levels) in link_headers'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:117:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:117:in `block (2 levels) in link_headers'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:116:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:116:in `block in link_headers'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:140:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:115:in `link_headers'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:41:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:562:in `install_file_references'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:152:in `block in generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:150:in `generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:110:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**whereas when i upgrade cocoapods to 1.0.1 and download it breaks `coreplot`. I donot understand the interlink issue that persists. Help me solve this. Looking forward to hear from you.**

**Comment by benasher44** [comment]
Can you fill out the issue template and provide a sample project please? It's hard to diagnose without one. Thanks!

**Comment by manjubasha** [comment]
Can you please give me the format?

**Comment by orta** [comment]
https://github.com/CocoaPods/CocoaPods/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by manjubasha** [comment]
### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 0.38.2
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.4 (15E65)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 54652b1709a28b70cb06560eb693b3a246bc8db5
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-search  : 1.0.0
cocoapods-stats   : 0.5.3
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.4.5
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'
inhibit_all_warnings!

xcodeproj 'AlwaysOn'
pod 'CorePlot', :git => 'https://github.com/core-plot/core-plot.git'
pod 'Google/Analytics'

target 'AlwaysOnKIFTests' do
  pod 'KIF', '~> 3.3.0'
  pod 'KIF/IdentifierTests', '~> 3.3.0'
end
```

### Error

```
Errno::ENOENT - No such file or directory - /Users/onlife/Documents/Xcode/Emids/Gazelle/G4/ALWS-1405/AlwaysOn/Pods/GoogleInterchangeUtilities/Frameworks/GoogleInterchangeUtilities.framework/Headers
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/sandbox/file_accessor.rb:161:in `realpath'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/sandbox/file_accessor.rb:161:in `realpath'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/sandbox/file_accessor.rb:161:in `vendored_frameworks_headers_dir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:239:in `block in vendored_frameworks_header_mappings'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:238:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:238:in `vendored_frameworks_header_mappings'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:140:in `block (3 levels) in link_headers'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:117:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:117:in `block (2 levels) in link_headers'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:116:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:116:in `block in link_headers'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:140:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:115:in `link_headers'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:41:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:562:in `install_file_references'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:152:in `block in generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:150:in `generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:110:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by Coeur** [comment]
You may have more support with a log for 1.0.1 or 1.1.0.rc.2.

**Comment by DanToml** [comment]
@manjubasha It appears that you are still using CocoaPods 0.38, can you please fill in the Issue Template with the error that occurs with 1.0.1

**Comment by benasher44** [comment]
CocoaPods 1.1.1 is now out. Please update your CocoaPods. If you're still experiencing this after updating, please file a new issue. Thanks for filing!
