### ISSUE TITLE
Can't install pods on Xcode 8

### ISSUE THREAD

**Issue by francocorreasosa** [CocoaPods/CocoaPods#5872]
### Command

```
/Users/franco/.rvm/gems/ruby-2.3.0/bin/pod install
```

### Report
I just cloned the repo and did `pod install`

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.12 (16A320)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /Users/franco/.rvm/rubies/ruby-2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 3757ff40647835207f6e003fea5623fad53b6a6d
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Candelaria' do
	pod 'Alamofire'
	pod 'SwiftyJSON'
	pod 'ObjectMapper'
	pod 'IBAnimatable'
    pod "SwiftSpinner"
    pod 'KFSwiftImageLoader', '~> 2.0'
    pod 'MBProgressHUD'
    pod 'JSQMessagesViewController'
    pod 'NSDate+TimeAgo'
    pod 'RNCryptor', '~> 4.0.0-beta'
    pod 'QRCodeReader.swift'
    pod 'DeviceKit'
end

target 'CandelariaTests' do

end

target 'CandelariaUITests' do

end
```

### Error

```
Pod::StandardError - Must be in the root of the repo (/Users/franco/.cocoapods/repos/master), instead in /Users/franco/Code/candelaria-ios.
/Users/franco/.rvm/gems/ruby-2.3.0/gems/cocoapods-core-1.0.1/lib/cocoapods-core/source.rb:403:in `ensure_in_repo!'
/Users/franco/.rvm/gems/ruby-2.3.0/gems/cocoapods-core-1.0.1/lib/cocoapods-core/source.rb:431:in `git_commit_hash'
/Users/franco/.rvm/gems/ruby-2.3.0/gems/cocoapods-core-1.0.1/lib/cocoapods-core/master_source.rb:31:in `block in requires_update?'
/Users/franco/.rvm/gems/ruby-2.3.0/gems/cocoapods-core-1.0.1/lib/cocoapods-core/master_source.rb:31:in `chdir'
/Users/franco/.rvm/gems/ruby-2.3.0/gems/cocoapods-core-1.0.1/lib/cocoapods-core/master_source.rb:31:in `requires_update?'
/Users/franco/.rvm/gems/ruby-2.3.0/gems/cocoapods-core-1.0.1/lib/cocoapods-core/master_source.rb:14:in `update'
/Users/franco/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/sources_manager.rb:88:in `block (2 levels) in update'
/Users/franco/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/Users/franco/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/sources_manager.rb:87:in `block in update'
/Users/franco/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/sources_manager.rb:86:in `each'
/Users/franco/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/sources_manager.rb:86:in `update'
/Users/franco/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/command/setup.rb:62:in `update_master_repo'
/Users/franco/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/command/setup.rb:25:in `block in run'
/Users/franco/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/Users/franco/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/command/setup.rb:21:in `run'
/Users/franco/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/sources_manager.rb:25:in `find_or_create_source_with_url'
/Users/franco/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:654:in `block in sources'
/Users/franco/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:653:in `map'
/Users/franco/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:653:in `sources'
/Users/franco/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:144:in `resolve_dependencies'
/Users/franco/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:114:in `install!'
/Users/franco/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/command/install.rb:37:in `run'
/Users/franco/.rvm/gems/ruby-2.3.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Users/franco/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'
/Users/franco/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
/Users/franco/.rvm/gems/ruby-2.3.0/bin/pod:23:in `load'
/Users/franco/.rvm/gems/ruby-2.3.0/bin/pod:23:in `<main>'
/Users/franco/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/Users/franco/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by benasher44** [comment]
@francocorreasosa Xcode 8 support is slated for 1.1.0. Please upgraded to the latest, which is currently 1.1.0.rc.2

**Comment by benasher44** [comment]
You can do this by doing `gem install cocoapods --pre`. Once you've done that, ensure you have that version running with `pod --version`. Thanks~

**Comment by huixisheng** [comment]
`gem install cocoapods --pre` can't update  `1.1.0.rc.2`.  result is `1.1.0.beta.2`
