### ISSUE TITLE
Mac OSX 10.11.6 : CocoaPods Setup Failed

### ISSUE THREAD

**Issue by hitendradeveloper** [CocoaPods/CocoaPods#5899]
Hi I am facing error like below.
FYI : I have stable internet connectino.
I ran *sudo gem install cocoapods command* from the terminal successfully.
Buy when I try to run *pod setup --verbose* getting below error.

```
Hitendras-Mac-mini:My_repo hitendramac$ pod setup --verbose

Setting up CocoaPods master repo

Cloning spec repo `master` from `https://github.com/CocoaPods/Specs.git` (branch `master`)
  $ /usr/bin/git clone https://github.com/CocoaPods/Specs.git master
  Cloning into 'master'...
  error: RPC failed; curl 18 transfer closed with outstanding read data remaining
  fatal: The remote end hung up unexpectedly
  fatal: early EOF
  fatal: index-pack failed
[!] /usr/bin/git clone https://github.com/CocoaPods/Specs.git master

Cloning into 'master'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed


/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/executable.rb:69:in `execute_command'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/executable.rb:27:in `block in executable'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command/repo/add.rb:71:in `block in clone_repo'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command/repo/add.rb:69:in `chdir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command/repo/add.rb:69:in `clone_repo'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command/repo/add.rb:41:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command/repo/add.rb:39:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command/setup.rb:54:in `add_master_repo'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command/setup.rb:27:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command/setup.rb:21:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
Hitendras-Mac-mini:My_repo hitendramac$ 

```

I also tried to pull the repo manually in the directory */Users/hitendramac/.cocoapods/repos/master*
Also getting the similar error for the same

```
Hitendras-Mac-mini:master hitendramac$ git clone https://github.com/CocoaPods/Specs.git
Cloning into 'Specs'...
remote: Counting objects: 825960, done.
remote: Compressing objects: 100% (63/63), done.
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
Hitendras-Mac-mini:master hitendramac$ 

```

**Comment by neonichu** [comment]
I just did a fresh clone successfully, so it seems like this has to be related to your network somehow. You could try cloning via `git://` and see if that makes a difference.

**Comment by EvgenyKarkan** [comment]
@hitendradeveloper I was getting the same error while my Mac was under `VPN` connection, but without `VPN` - everything went fine, thanks, @neonichu.

**Comment by Git-sunming** [comment]
I have the same problem. Could you tell me how to solve it?

**Comment by xxzizixx** [comment]
@EvgenyKarkan @neonichu  I have the same problem, and don't konw how to solve it , and the most terrible thing is that without VPN, I can't connect to github in company's mac pro,  do you konw why and how to do it? Thanks .
