### ISSUE TITLE
File exists on Pod Install

### ISSUE THREAD

**Issue by elrodsj** [CocoaPods/CocoaPods#5924]
🌈
> Before you start, are you using the CocoaPods beta release?
> a lot has changed with Xcode 8 that is not backwards compatible.
>yes
> Xcode 8 Status: Only works with CocoaPods 1.1.0
> Swift 3: You need to add a `.swift-version` file, see the CHANGELOG
> China: Use https://gems.ruby-china.org/ instead of https://gems.ruby-china.org/ for the RC see #5910

* [x ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod install`

## What did you expect to happen?

Install all pod dependencies correctly.

## What happened instead?

```
Errno::EEXIST - File exists - ***/AMA_CORE_MR/Pods/Target Support Files/AFNetworking
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/xcode/pods_project_generator/target_installer.rb:92:in `mkdir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/xcode/pods_project_generator/target_installer.rb:92:in `mkdir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/xcode/pods_project_generator/target_installer.rb:92:in `create_support_files_dir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:21:in `block in install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/user_interface.rb:142:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:19:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:155:in `block (2 levels) in install_libraries'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:153:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:153:in `block in install_libraries'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/user_interface.rb:142:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:152:in `install_libraries'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:64:in `generate!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:179:in `block in generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:178:in `generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:115:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/command/install.rb:37:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

### Stack

```
   CocoaPods : 1.1.0.rc.2
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.6 (15G1004)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : AMAPodSpecs - ****
               master - https://github.com/CocoaPods/Specs.git @ 7b264a83ecd21a0e1c9a48d03f42cc5957851eff
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

inhibit_all_warnings!

#include ruby helper class
require_relative "CocoaPodsHelperMethods"

#instantiate helper
helper = CocoaPodsHelperMethods.new

#clear out the build configuration for each project
helper.clearBuildConfigs("./AMA_CORE_MR.xcodeproj/project.pbxproj", "../../Core/CoreFramework/CoreFramework.xcodeproj/project.pbxproj")

workspace 'VerizonWorkspace.xcworkspace'

def corePods
    
    pod 'Bolts'
    pod 'AFNetworking', '~> 1.3'
    pod 'CocoaLumberjack'
    pod 'CorePlot'
    pod 'Mixpanel'
    pod 'Mantle'
    pod 'Appirater'
    pod 'ASIHTTPRequest'
    pod 'RNCryptor', '~> 3.0.1'

end

target :vmsqa do

project './AMA_CORE_MR.xcodeproj'

pod 'Fabric'
pod 'Crashlytics'

corePods

end

target :CoreFramework do

project '../../Core/CoreFramework/CoreFramework.xcodeproj'
corePods

end
```

**Comment by elrodsj** [comment]
I've tried solution from #5864, but it didn't work for me.

**Comment by benasher44** [comment]
Can you verify that your targets CoreFramework and vsmqa have the same "Use Legacy Swift Language Version" setting?

**Comment by elrodsj** [comment]
CoreFramework is a static library and does not have "Use Legacy Swift Language Version" in the build settings.

**Comment by benasher44** [comment]
Hm okay. I think this might be an edge case we need to fix with Swift support. I'll try to put together a PR soon. In the meantime, you might be able to workaround this by setting the `SWIFT_VERSION` build setting for CoreFramework or just at the project level

**Comment by elrodsj** [comment]
Adding `SWIFT_VERSION = 3.0` as a user-defined build setting in CoreFramework worked. Thanks for the help!

**Comment by neoneye** [comment]
I just had same stack trace. 

For my unittest target , I added `SWIFT_VERSION = 3.0` and now `pod install` works.

**Comment by benasher44** [comment]
Hello again! Most of the discussion around this issue has been happening in #5864 and #5834. This is a known issue, and we're working to get it fixed (shooting for rc3). The first PR is out (#5917), which adds a helpful error message when we've found conflicting Swift versions in your project. Expect to see more fixes for this coming soon. I think this issue is pretty well covered and discussed by these other 2 issues, so I'm going to close this one. Thanks for filling!
