### ISSUE TITLE
pod lib lint error

### ISSUE THREAD

**Issue by aolan** [CocoaPods/CocoaPods#5936]
When podspec file has this code:
`spec.ios.resource_bundle = { 'SDK_CoreData' => 'Common/Classes/SDK/*.xcdatamodeld' }
`

then run "_pod lib lint_"

It will appear error like this:

```
ERROR | [iOS] unknown: Encountered an unknown error (undefined method `deployment_target=' for #<Xcodeproj::Project::Object::PBXNativeTarget:0x007f88cb581a28>
Did you mean?  deployment_target) during validation.

```

platform: iOS
environment: Xcode8
cocoapods version: 1.1.0.rc.2

Thanks.

**Comment by neonichu** [comment]
Please share the full verbose output of `pod lib lint` and a complete podspec that reproduces this issue.

**Comment by aolan** [comment]
When i use 'pod install --verbose', the log like this:

### Command

```
/Users/souutsu/.rvm/rubies/ruby-2.3.0/bin/pod install --verbose
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.1.0.rc.2
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.6 (15G1004)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /Users/souutsu/.rvm/rubies/ruby-2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 7f32ec7863407a0bbaa60b312d2c06cd62bba0bb
               PKSpecs - https://github.com/aolan/PKSpecs @ 834e19e7721d313812692e0da47a0a037466fecb
               QXWZSpecs - https://code.wz-inc.com/iOS_Common/QXWZSpecs.git @ 876e4dbc23e85564af49661efda4a342c501a86e
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
use_frameworks!

target 'QXWZCommon_Example' do
  pod 'QXWZCommon', :path => '../'

  target 'QXWZCommon_Tests' do
    inherit! :search_paths


  end
end
```

### Error

```
NoMethodError - undefined method `deployment_target=' for #<Xcodeproj::Project::Object::PBXNativeTarget:0x007fa7f32ab050>
Did you mean?  deployment_target
/Users/souutsu/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:168:in `block (2 levels) in add_resources_bundle_targets'
/Users/souutsu/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:140:in `each'
/Users/souutsu/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:140:in `block in add_resources_bundle_targets'
/Users/souutsu/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:139:in `each'
/Users/souutsu/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:139:in `add_resources_bundle_targets'
/Users/souutsu/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:22:in `block in install!'
/Users/souutsu/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/user_interface.rb:142:in `message'
/Users/souutsu/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:19:in `install!'
/Users/souutsu/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:155:in `block (2 levels) in install_libraries'
/Users/souutsu/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:153:in `each'
/Users/souutsu/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:153:in `block in install_libraries'
/Users/souutsu/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/user_interface.rb:142:in `message'
/Users/souutsu/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:152:in `install_libraries'
/Users/souutsu/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:64:in `generate!'
/Users/souutsu/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:179:in `block in generate_pods_project'
/Users/souutsu/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/user_interface.rb:64:in `section'
/Users/souutsu/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:178:in `generate_pods_project'
/Users/souutsu/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:115:in `install!'
/Users/souutsu/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/command/install.rb:37:in `run'
/Users/souutsu/.rvm/gems/ruby-2.3.0@global/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Users/souutsu/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/command.rb:50:in `run'
/Users/souutsu/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.1.0.rc.2/bin/pod:55:in `<top (required)>'
/Users/souutsu/.rvm/rubies/ruby-2.3.0/bin/pod:23:in `load'
/Users/souutsu/.rvm/rubies/ruby-2.3.0/bin/pod:23:in `<main>'
/Users/souutsu/.rvm/gems/ruby-2.3.0@global/bin/ruby_executable_hooks:15:in `eval'
/Users/souutsu/.rvm/gems/ruby-2.3.0@global/bin/ruby_executable_hooks:15:in `<main>'
```



```
Pod::Spec.new do |s|
    s.name             = 'QXWZCommon'
    s.version          = '0.0.13'
    s.summary          = 'QXWZCommon.'
    s.description      = <<-DESC
    常用。
                        DESC

    s.homepage         = 'https://code.wz-inc.com/iOS_Common/QXWZCommon'
    s.license          = 'MIT'
    s.author           = { 'wei.cao' => 'adcaowei@163.com' }
    s.source           = { :git => 'https://code.wz.com/iOS_Common/QXWZCommon.git', :tag => s.version.to_s }

    s.platform = :ios
      
    s.subspec 'CloudShadow' do |cloudshadow|
        cloudshadow.source_files = 'QXWZCommon/Classes/CloudShadow/*'
        cloudshadow.public_header_files = 'QXWZCommon/Classes/CloudShadow/*.h'
        cloudshadow.ios.frameworks = 'CoreData', 'CoreLocation'
        cloudshadow.ios.resource_bundle = { 'QXWZSDK_CoreData' => 'QXWZCommon/Classes/CloudShadow/*.xcdatamodeld' }
    end
end
```

**Comment by aolan** [comment]
How to completely remove Cocoapods, i find error even user command 'pod search Masonry'。


### Command

```
/Users/souutsu/.rvm/rubies/ruby-2.3.0/bin/pod search Masonry
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.6.6
        Host : Mac OS X 10.11.6 (15G1004)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /Users/souutsu/.rvm/rubies/ruby-2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ dae48d6a29542cc219c1e22d21cd26f203e1ae29
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

### Error

```
JSON::ParserError - 784: unexpected token at '常用分类。":["QXWZCommon"],"adcaowei@163.com":["QXWZCommon"]}}'
/Users/souutsu/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/json/common.rb:156:in `parse'
/Users/souutsu/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/json/common.rb:156:in `parse'
/Users/souutsu/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-core-1.0.1/lib/cocoapods-core/source/manager.rb:251:in `stored_search_index'
/Users/souutsu/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-core-1.0.1/lib/cocoapods-core/source/manager.rb:187:in `updated_search_index'
/Users/souutsu/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-core-1.0.1/lib/cocoapods-core/source/manager.rb:118:in `search_by_name'
/Users/souutsu/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-search-1.0.0/lib/cocoapods-search/command/search.rb:87:in `local_search'
/Users/souutsu/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-search-1.0.0/lib/cocoapods-search/command/search.rb:63:in `run'
/Users/souutsu/.rvm/gems/ruby-2.3.0@global/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Users/souutsu/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'
/Users/souutsu/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
/Users/souutsu/.rvm/rubies/ruby-2.3.0/bin/pod:22:in `load'
/Users/souutsu/.rvm/rubies/ruby-2.3.0/bin/pod:22:in `<main>'
/Users/souutsu/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/Users/souutsu/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'

**Comment by orta** [comment]
Perhaps a mis-match of xcodeproj and cocoapods? Can you try with the latest release please

**Comment by DanToml** [comment]
Closing due to lack of activity, if this is still a problem, please file a new issue and include a sample project.
