### ISSUE TITLE
Unable to build XCode-8.0 compatible project

### ISSUE THREAD

**Issue by rhwood** [CocoaPods/CocoaPods#5939]
Attempting to build pods with either 1.0.1 (installed using Homebrew on my personal laptop) or 1.1.0rc2 (on Travis-CI) results in the following error when using a project that is "Xcode-8.0 compatible". Reverting the project compatibility to "XCode-6.3" allows this to work.

Travis-CI failure is at https://travis-ci.org/rhwood/roster-decoder/builds/162159901
Failure from personal laptop follows:

### Command

```
/usr/local/Cellar/cocoapods/1.0.1/libexec/bin/pod install
```

### Report

* What did you do?
pod install on XCode-8.0 compatible project
* What did you expect to happen?
pod install to create pod framework
* What happened instead?
this failure.

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12 (16A323)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 16851c90e9b2eba8f8a6c7c08a3adc0591bc18f5
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

### Podfile

```ruby
platform :ios, '9.0'
use_frameworks!

target 'Roster Decoder' do
  pod 'Fuzi', '~> 1.0.0'
  pod 'SwiftyDropbox', '~> 4.0.2'
  pod 'Firebase/Core'
  pod 'Firebase/AdMob'
end

target 'Roster DecoderTests' do

end
```

### Error

```
RuntimeError - [Xcodeproj] Unknown object version.
/usr/local/Cellar/cocoapods/1.0.1/libexec/gems/xcodeproj-1.1.0/lib/xcodeproj/project.rb:217:in `initialize_from_file'
/usr/local/Cellar/cocoapods/1.0.1/libexec/gems/xcodeproj-1.1.0/lib/xcodeproj/project.rb:102:in `open'
/usr/local/Cellar/cocoapods/1.0.1/libexec/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:695:in `block (2 levels) in inspect_targets_to_integrate'
/usr/local/Cellar/cocoapods/1.0.1/libexec/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:694:in `each'
/usr/local/Cellar/cocoapods/1.0.1/libexec/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:694:in `block in inspect_targets_to_integrate'
/usr/local/Cellar/cocoapods/1.0.1/libexec/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/usr/local/Cellar/cocoapods/1.0.1/libexec/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:689:in `inspect_targets_to_integrate'
/usr/local/Cellar/cocoapods/1.0.1/libexec/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:66:in `analyze'
/usr/local/Cellar/cocoapods/1.0.1/libexec/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:227:in `analyze'
/usr/local/Cellar/cocoapods/1.0.1/libexec/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:151:in `block in resolve_dependencies'
/usr/local/Cellar/cocoapods/1.0.1/libexec/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/usr/local/Cellar/cocoapods/1.0.1/libexec/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:150:in `resolve_dependencies'
/usr/local/Cellar/cocoapods/1.0.1/libexec/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:114:in `install!'
/usr/local/Cellar/cocoapods/1.0.1/libexec/gems/cocoapods-1.0.1/lib/cocoapods/command/install.rb:37:in `run'
/usr/local/Cellar/cocoapods/1.0.1/libexec/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/usr/local/Cellar/cocoapods/1.0.1/libexec/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'
/usr/local/Cellar/cocoapods/1.0.1/libexec/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
/usr/local/Cellar/cocoapods/1.0.1/libexec/bin/pod:23:in `load'
/usr/local/Cellar/cocoapods/1.0.1/libexec/bin/pod:23:in `<main>'
```

**Comment by neonichu** [comment]
This should have been fixed by Xcodeproj 1.3.1, please double-check that you have that version installed. In any case, using CP 1.0.1 in conjunction with Xcode 8 will not work.

**Comment by rhwood** [comment]
Other than this issue, I'm having no problems using using 1.0.1 with Xcode 8.0. I'll check on the xcodeproj version this evening.

**Comment by neonichu** [comment]
You could be lucky that you're not hitting any of them, but we changed a lot of small things to support Xcode 8 in CP 1.1.0

**Comment by EMart002** [comment]
@neonichu i'm currently also having some problems regarding the latest version 1.1.0.rc2
I've been updating my source code today and wasn't able to push my cocoapod version. 
- ERROR | [iOS] xcodebuild:  EMCommon/EMCommon/Classes/NSDate+EMKit.swift:19:38: error: use of undeclared type 'Date' 

Any suggestions?

**Comment by benasher44** [comment]
Xcode 8 requires using CocoaPods 1.1.0.rc.3. Please update to 1.1.0.rc.3 and file a new issue if you're still experiencing this. Thanks!
