### ISSUE TITLE
Unable to convert Ruby value `"AWSCognito"' into a CFTypeRef.

### ISSUE THREAD

**Issue by EricRen20** [CocoaPods/CocoaPods#5943]
### Command

```
/Users/quxcc5215/.rvm/gems/ruby-2.2.0/bin/pod install
```

### Report

 I was trying to update the AWS SDK library to the latest version using the cocoapods, but I got an error during the pod install and pod update.. the error is 
```
Unable to convert Ruby value `"AWSCognito"' into a CFTypeRef.
```
 I also tried the pre version(1.1.0) cocoapods. and I got the same error.

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]
    RubyGems : 2.4.6
        Host : Mac OS X 10.12 (16A323)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /Users/quxcc5215/.rvm/rubies/ruby-2.2.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ ff3995e47bfa58eaaf529d1e7b6931bc89eeb2f9
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
def appPod
	pod 'AWSCore'
	pod 'AWSS3'
	pod 'AWSDynamoDB'
	pod 'AWSCognito'
	pod 'AWSMobileAnalytics'
	pod 'AWSCognitoIdentityProvider'
	pod 'AWSSNS'
	pod 'AWSPushManager'
end

target 'app' do
	appPod
end

target 'appTests' do
	appPod
end
```

### Error

```
TypeError - Unable to convert Ruby value `"AWSCognito"' into a CFTypeRef.
/Users/quxcc5215/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.3.1/lib/xcodeproj/plist/ffi/core_foundation.rb:383:in `RubyValueToCFTypeRef'
/Users/quxcc5215/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.3.1/lib/xcodeproj/plist/ffi/core_foundation.rb:402:in `block in RubyHashToCFDictionary'
/Users/quxcc5215/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.3.1/lib/xcodeproj/plist/ffi/core_foundation.rb:400:in `each'
/Users/quxcc5215/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.3.1/lib/xcodeproj/plist/ffi/core_foundation.rb:400:in `RubyHashToCFDictionary'
/Users/quxcc5215/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.3.1/lib/xcodeproj/plist/ffi/core_foundation.rb:372:in `RubyValueToCFTypeRef'
/Users/quxcc5215/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.3.1/lib/xcodeproj/plist/ffi/core_foundation.rb:402:in `block in RubyHashToCFDictionary'
/Users/quxcc5215/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.3.1/lib/xcodeproj/plist/ffi/core_foundation.rb:400:in `each'
/Users/quxcc5215/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.3.1/lib/xcodeproj/plist/ffi/core_foundation.rb:400:in `RubyHashToCFDictionary'
/Users/quxcc5215/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.3.1/lib/xcodeproj/plist/ffi/core_foundation.rb:372:in `RubyValueToCFTypeRef'
/Users/quxcc5215/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.3.1/lib/xcodeproj/plist/ffi/core_foundation.rb:402:in `block in RubyHashToCFDictionary'
/Users/quxcc5215/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.3.1/lib/xcodeproj/plist/ffi/core_foundation.rb:400:in `each'
/Users/quxcc5215/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.3.1/lib/xcodeproj/plist/ffi/core_foundation.rb:400:in `RubyHashToCFDictionary'
/Users/quxcc5215/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.3.1/lib/xcodeproj/plist/ffi.rb:159:in `ruby_hash_write_devtoolscore'
/Users/quxcc5215/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.3.1/lib/xcodeproj/plist/ffi.rb:149:in `ruby_hash_write_xcode'
/Users/quxcc5215/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.3.1/lib/xcodeproj/plist/ffi.rb:72:in `write_to_path'
/Users/quxcc5215/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.3.1/lib/xcodeproj/plist.rb:46:in `write_to_path'
/Users/quxcc5215/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.3.1/lib/xcodeproj/project.rb:333:in `save'
/Users/quxcc5215/.rvm/gems/ruby-2.2.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:696:in `block in write_pod_project'
/Users/quxcc5215/.rvm/gems/ruby-2.2.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:141:in `message'
/Users/quxcc5215/.rvm/gems/ruby-2.2.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:688:in `write_pod_project'
/Users/quxcc5215/.rvm/gems/ruby-2.2.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:173:in `block in generate_pods_project'
/Users/quxcc5215/.rvm/gems/ruby-2.2.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/Users/quxcc5215/.rvm/gems/ruby-2.2.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:167:in `generate_pods_project'
/Users/quxcc5215/.rvm/gems/ruby-2.2.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:119:in `install!'
/Users/quxcc5215/.rvm/gems/ruby-2.2.0/gems/cocoapods-1.0.1/lib/cocoapods/command/install.rb:37:in `run'
/Users/quxcc5215/.rvm/gems/ruby-2.2.0@global/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Users/quxcc5215/.rvm/gems/ruby-2.2.0/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'
/Users/quxcc5215/.rvm/gems/ruby-2.2.0/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
/Users/quxcc5215/.rvm/gems/ruby-2.2.0/bin/pod:23:in `load'
/Users/quxcc5215/.rvm/gems/ruby-2.2.0/bin/pod:23:in `<main>'
/Users/quxcc5215/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
/Users/quxcc5215/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by nicklockwood** [comment]
I'm seeing potentially the same issue with the word "Expression":

```
Validating podspec
 -> Expression (0.1)
    - ERROR | [iOS] unknown: Encountered an unknown error (Unable to convert Ruby value `"Expression"' into a CFTypeRef.) during validation.

[!] The spec did not pass validation, due to 1 error.
```

**Comment by EricRen20** [comment]
upgrade the ruby version to 2.2.3 fix this bug.
