### ISSUE TITLE
Failed to update pods, using swift 3

### ISSUE THREAD

**Issue by VicFrolov** [CocoaPods/CocoaPods#5964]
### Command

```
/usr/local/bin/pod update
```
### Report
- What did you do?

ran pod update
- What did you expect to happen?
  pods to update, after doing `gem install cocoapods -v 1.1.0.rc.2` to have swiftyJSON working
- What happened instead?
  received error below
### Stack

```
   CocoaPods : 1.1.0.rc.2
        Ruby : ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]
    RubyGems : 2.0.3
        Host : Mac OS X 10.12 (16A323)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /usr/local/Cellar/ruby/2.2.3/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ a74c155b1fa18dc07c2ab885f4e8da56f29434fb
```
### Plugins

```
cocoapods-clean       : 0.0.1
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```
### Podfile

``` ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Markit' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Markit
  pod 'Firebase'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'SwiftyJSON', '3.0.0'

end
```
### Error

```
ArgumentError - comparison of Pod::Version with Gem::Version failed
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/sources_manager.rb:132:in `>'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/sources_manager.rb:132:in `verify_compatibility!'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/sources_manager.rb:90:in `block (2 levels) in update'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/sources_manager.rb:87:in `block in update'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/sources_manager.rb:86:in `each'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/sources_manager.rb:86:in `update'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/analyzer.rb:220:in `block in update_repositories'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/analyzer.rb:218:in `each'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/analyzer.rb:218:in `update_repositories'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:146:in `block in resolve_dependencies'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:145:in `resolve_dependencies'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:110:in `install!'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/command/update.rb:60:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/command.rb:50:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.0.rc.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by danipralea** [comment]
I have the same issue. never able to run `pod update`

**Comment by benasher44** [comment]
Can you try this with CocoaPods 1.1.0? The final release is out now.

**Comment by danipralea** [comment]
Thank you for your reply, @benasher44 I just did. and still having the issue

```
/usr/local/bin/pod update
```

### Report

* What did you do?

ran `pod update`

* What did you expect to happen?

have the pods expected

* What happened instead?

received error

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.3
        Host : Mac OS X 10.11.6 (15G1004)
       Xcode : 8.0 (8A218a)
         Git : git version 2.5.3
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ f7a3886a01ddff24178495998a56018eb27e36ee
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!


target 'private' do

pod 'Socket.IO-Client-Swift', '8.0.2'
pod 'Alamofire', '4.0.1'
pod 'ObjectMapper', '2.1.0'
pod 'SwiftyJSON', '3.1.1'

pod 'Crashlytics', '3.8.2'
pod 'Fabric', '1.6.9'

pod 'FBSDKCoreKit', '4.16.0'
pod 'FBSDKLoginKit', '4.16.0'

pod 'RxSwift',    '3.0.0-beta.2'
pod 'RxCocoa',    '3.0.0-beta.2'

pod 'SkyFloatingLabelTextField', git: "https://github.com/MLSDev/SkyFloatingLabelTextField.git", branch: "swift3"

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |configuration|
            configuration.build_settings['SWIFT_VERSION'] = "3.0"
        end
    end
end
```

### Error

```
ArgumentError - comparison of Pod::Version with Gem::Version failed
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/sources_manager.rb:132:in `>'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/sources_manager.rb:132:in `verify_compatibility!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/sources_manager.rb:90:in `block (2 levels) in update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/sources_manager.rb:87:in `block in update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/sources_manager.rb:86:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/sources_manager.rb:86:in `update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:220:in `block in update_repositories'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:218:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:218:in `update_repositories'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:146:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:145:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:110:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command/update.rb:60:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by benasher44** [comment]
Hm okay. Can you try changing this line:
```
pod 'SkyFloatingLabelTextField', git: "https://github.com/MLSDev/SkyFloatingLabelTextField.git", branch: "swift3"
```
to be
```
pod 'SkyFloatingLabelTextField', :git => "https://github.com/MLSDev/SkyFloatingLabelTextField.git", :branch => "swift3"
```

**Comment by benasher44** [comment]
If someone could post a project that reproduces this, that would be great. I haven't had any luck reproducing this locally.

**Comment by danipralea** [comment]
nope, still having the issue

**Comment by benasher44** [comment]
@danipralea could you post a sample project if you're still experiencing this? I haven't been able to reproduce this given the existing information.

**Comment by iljaiwas** [comment]
Run into the same issue. Solved by running this command on macOS 10.11:

    sudo gem update -n /usr/local/bin –system

**Comment by danipralea** [comment]
@benasher44 it's doing that for all my projects.
@iljaiwas thanks for the solution - but it didn't worked for me

**Comment by benasher44** [comment]
@danipralea can you post a project that reproduces the issue? That'd go a long way toward helping debug this. Thanks!

**Comment by VicFrolov** [comment]
same issue here

**Comment by benasher44** [comment]
@VicFrolov could you post a project that reproduces the issue? That'd be really helpful. Thanks!

**Comment by DanToml** [comment]
Closing due to lack of activity - If this is still a bug please file a new issue with a sample project.
