### ISSUE TITLE
Crash when running pod install: Expected target or target_proxy, from which to fetch a uuid

### ISSUE THREAD

**Issue by aleph7** [CocoaPods/CocoaPods#5985]
### Command

```
~/.rbenv/versions/2.3.1/bin/pod install
```
### Report
- What did you do?

Ran `pod install`
- What did you expect to happen?

Pods being installed
- What happened instead?

Crash!
### Stack

```
   CocoaPods : 1.1.0.rc.2
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.12 (16A323)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /Users/alejandro/.rbenv/versions/2.3.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 2de22ded43198dbf7e7b4d1c4ab1406c5c30e986
```
### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```
### Podfile

``` ruby
use_frameworks!

target 'IntuneFeatures.OSX' do
  platform :osx, '10.12'
  target 'IntuneFeaturesTests.OSX'

  pod 'HDF5Kit', :git => 'https://github.com/aleph7/HDF5Kit.git', :branch => 'master'
  pod 'Peak/MIDI', :git => 'https://github.com/hoseking/Peak.git', :branch => 'master'
  pod 'Upsurge', :git => 'https://github.com/aleph7/Upsurge.git', :branch => 'master'
end

target 'IntuneFeatures.iOS' do
  platform :ios, '10.0'
  target 'IntuneFeaturesTests.iOS'

  pod 'HDF5Kit', :git => 'https://github.com/aleph7/HDF5Kit.git', :branch => 'master'
  pod 'Peak/MIDI', :git => 'https://github.com/hoseking/Peak.git', :branch => 'master'
  pod 'Upsurge', :git => 'https://github.com/aleph7/Upsurge.git', :branch => 'master'
end

target :CompileFeatures do
  platform :osx, '10.12'

  pod 'HDF5Kit', :git => 'https://github.com/aleph7/HDF5Kit.git', :branch => 'master'
  pod 'Peak/MIDI', :git => 'https://github.com/hoseking/Peak.git', :branch => 'master'
  pod 'Peak/AudioFile', :git => 'https://github.com/hoseking/Peak.git', :branch => 'master'
  pod 'Upsurge', :git => 'https://github.com/aleph7/Upsurge.git', :branch => 'master'
end
```
### Error

```
RuntimeError - Expected target or target_proxy, from which to fetch a uuid
/Users/alejandro/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/xcodeproj-1.3.1/lib/xcodeproj/project/object/target_dependency.rb:50:in `native_target_uuid'
/Users/alejandro/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/xcodeproj-1.3.1/lib/xcodeproj/project.rb:560:in `map'
/Users/alejandro/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/xcodeproj-1.3.1/lib/xcodeproj/project.rb:560:in `block in host_targets_for_embedded_target'
/Users/alejandro/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/xcodeproj-1.3.1/lib/xcodeproj/project.rb:558:in `select'
/Users/alejandro/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/xcodeproj-1.3.1/lib/xcodeproj/project.rb:558:in `host_targets_for_embedded_target'
/Users/alejandro/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/analyzer.rb:284:in `block (2 levels) in analyze_host_targets_in_podfile'
/Users/alejandro/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/analyzer.rb:283:in `each'
/Users/alejandro/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/analyzer.rb:283:in `block in analyze_host_targets_in_podfile'
/Users/alejandro/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/analyzer.rb:281:in `each'
/Users/alejandro/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/analyzer.rb:281:in `analyze_host_targets_in_podfile'
/Users/alejandro/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/analyzer.rb:363:in `generate_targets'
/Users/alejandro/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/analyzer.rb:78:in `analyze'
/Users/alejandro/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:236:in `analyze'
/Users/alejandro/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:150:in `block in resolve_dependencies'
/Users/alejandro/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/user_interface.rb:64:in `section'
/Users/alejandro/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:149:in `resolve_dependencies'
/Users/alejandro/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:110:in `install!'
/Users/alejandro/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/command/install.rb:37:in `run'
/Users/alejandro/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Users/alejandro/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/command.rb:50:in `run'
/Users/alejandro/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.0.rc.2/bin/pod:55:in `<top (required)>'
/Users/alejandro/.rbenv/versions/2.3.1/bin/pod:23:in `load'
/Users/alejandro/.rbenv/versions/2.3.1/bin/pod:23:in `<main>'
```

**Comment by orta** [comment]
This feels really strange, if I had to guess maybe there are some targets that are said to still exist in the xcodeproj file but the UUIDs they reference have gone, likely as the result of a manual merge. Can you look through your Xcode project's file as source and verify that all of the target references have corresponding objects?

**Comment by aleph7** [comment]
I didn't find anything that could be wrong. You can have a look by using that Podfile on https://github.com/venturemedia/intune-features

**Comment by benasher44** [comment]
Looks like there was a bad target dependency in one of your targets. This patch fixes it and allows pod install to continue.
```
diff --git a/IntuneFeatures.xcodeproj/project.pbxproj b/IntuneFeatures.xcodeproj/project.pbxproj
index aaf43fa..b6fa99e 100644
--- a/IntuneFeatures.xcodeproj/project.pbxproj
+++ b/IntuneFeatures.xcodeproj/project.pbxproj
@@ -821,10 +821,6 @@
                        target = 61BBC3B51C407891006C6DF0 /* IntuneFeatures.iOS */;
                        targetProxy = 61BBC3C11C407891006C6DF0 /* PBXContainerItemProxy */;
                };
-               A94555841CAED97E00E62839 /* PBXTargetDependency */ = {
-                       isa = PBXTargetDependency;
-                       name = PeakOSX;
-               };
 /* End PBXTargetDependency section */
 
 /* Begin XCBuildConfiguration section */
```
Going to keep this open, since this issue comes up every now and then, and we could have better error messaging here about where to go to look for this.

**Comment by aleph7** [comment]
That fixed it! Thanks.

**Comment by cannyboy** [comment]
I've got this problem - is there a standard way of solving it? What should I be looking for? The `pbxproj` file is quite obscure to me. Is there something I can reset in Xcode itself?

**Comment by benasher44** [comment]
It usually a bad entry in a "target dependencies" build phase for one of your targets. In your project file, it'd be a `PBXTargetDependency` entry with no `target` or `targetProxy` property.

**Comment by cannyboy** [comment]
Thanks, for future reference it was this that I removed:

    12BE36B91B15D1B300778475 /* PBXTargetDependency */ = {
                           isa = PBXTargetDependency;
                           name = Alamofire;
                    };

**Comment by dnkoutso** [comment]
@cannyboy I opened a PR that provides a better and easier error message for others to be able to figure this out quickly.

**Comment by diennt82** [comment]
I fixed this issue. I removed all PBXTargetDependency
/* Begin PBXTargetDependency section */
..
/* End PBXTargetDependency section */

Thanks.
