### ISSUE TITLE
Cannot run pod install or podupdate with 1.1.0 rc2

### ISSUE THREAD

**Issue by javaboyjunior** [CocoaPods/CocoaPods#6005]
Am using Xcode 8.

### Command

```
/usr/local/bin/pod update
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.1.0.rc.2
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12 (16A323)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ c9c49efcec1c4da66b24b58c1111f5cdca24d9cf
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
def myPods
  pod 'RXPromise', '~> 0.13.1'
  pod 'AsyncImageView'
  pod 'ActionSheetPicker-3.0'
  pod 'vfrReader'
  pod 'T1Autograph', '~> 1.6.0'
  pod 'AviarySDK'
  pod 'GoogleMaps'
  pod 'IHKeyboardAvoiding'
  pod 'QBImagePickerController', git:'https://github.com/fotonotes/QBImagePicker.git'
end

target 'XXX' do
  myPods
end

target 'XXXXXX' do
  myPods
end
```

### Error

```
NameError - uninitialized constant CoreFoundation
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/sources_manager.rb:168:in `const_missing'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.3.1/lib/xcodeproj/plist/ffi/core_foundation.rb:271:in `ptr'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.3.1/lib/xcodeproj/plist/ffi/core_foundation.rb:73:in `RubyHashPropertyListRead'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.3.1/lib/xcodeproj/plist/ffi.rb:87:in `read_from_path'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.3.1/lib/xcodeproj/plist.rb:22:in `read_from_path'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.3.1/lib/xcodeproj/project.rb:200:in `initialize_from_file'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.3.1/lib/xcodeproj/project.rb:102:in `open'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/analyzer.rb:825:in `block (2 levels) in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/analyzer.rb:824:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/analyzer.rb:824:in `block in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/analyzer.rb:819:in `inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/analyzer.rb:66:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:236:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:150:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:149:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:110:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/command/update.rb:60:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=uninitialized+constant+CoreFoundation&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
 - NameError - uninitialized constant CoreFoundation
   https://github.com/CocoaPods/CocoaPods/issues/5311 [closed] [4 comments]
   3 weeks ago

 - Crash when reading Xcode project during intergration
   https://github.com/CocoaPods/CocoaPods/issues/2483 [closed] [76 comments]
   30 Mar 2015

 - error installation gem
   https://github.com/CocoaPods/CocoaPods/issues/699 [closed] [15 comments]
   10 Jan 2013

**Comment by javaboyjunior** [comment]
Caused by broken xcode file
