### ISSUE TITLE
Must be in the root of the repo 

### ISSUE THREAD

**Issue by bryanboyko** [CocoaPods/CocoaPods#6026]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

1. clone repo of .c and .h files. There is no .xcodeproj and all files are in top level directory
2. run 'pod lib create dsp_dungeon' 
3. update podspec to corresponding url's and add summary
4. run 'pod lib lint --verbose'

## What did you expect to happen?

lint would pass and i would be able to push podspec/podfile/xcodeproj and then use the pod

## What happened instead?

lint failed with error
```
    - ERROR | [iOS] unknown: Encountered an unknown error (Must be in the root of the repo (/Users/bryanboyko/.cocoapods/repos/master), instead in /Users/bryanboyko/XCode/dsp_dungeon/dsp_dungeon.
/Users/bryanboyko/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-core-1.0.1/lib/cocoapods-core/source.rb:403:in `ensure_in_repo!'
/Users/bryanboyko/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-core-1.0.1/lib/cocoapods-core/source.rb:431:in `git_commit_hash'
/Users/bryanboyko/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-core-1.0.1/lib/cocoapods-core/master_source.rb:31:in `block in requires_update?'
/Users/bryanboyko/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-core-1.0.1/lib/cocoapods-core/master_source.rb:31:in `chdir'
/Users/bryanboyko/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-core-1.0.1/lib/cocoapods-core/master_source.rb:31:in `requires_update?'
/Users/bryanboyko/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-core-1.0.1/lib/cocoapods-core/master_source.rb:14:in `update'
/Users/bryanboyko/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.1/lib/cocoapods/sources_manager.rb:88:in `block (2 levels) in update'
/Users/bryanboyko/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/Users/bryanboyko/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.1/lib/cocoapods/sources_manager.rb:87:in `block in update'
/Users/bryanboyko/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.1/lib/cocoapods/sources_manager.rb:86:in `each'
/Users/bryanboyko/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.1/lib/cocoapods/sources_manager.rb:86:in `update'
/Users/bryanboyko/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.1/lib/cocoapods/command/setup.rb:62:in `update_master_repo'
/Users/bryanboyko/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.1/lib/cocoapods/command/setup.rb:25:in `block in run'
/Users/bryanboyko/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/Users/bryanboyko/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.1/lib/cocoapods/command/setup.rb:21:in `run'
/Users/bryanboyko/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.1/lib/cocoapods/sources_manager.rb:25:in `find_or_create_source_with_url'
/Users/bryanboyko/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:654:in `block in sources'
/Users/bryanboyko/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:653:in `map'
/Users/bryanboyko/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:653:in `sources'
/Users/bryanboyko/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:144:in `resolve_dependencies'
/Users/bryanboyko/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.1/lib/cocoapods/validator.rb:373:in `block in download_pod'
/Users/bryanboyko/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.1/lib/cocoapods/validator.rb:373:in `each'
/Users/bryanboyko/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.1/lib/cocoapods/validator.rb:373:in `download_pod'
/Users/bryanboyko/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.1/lib/cocoapods/validator.rb:269:in `block in perform_extensive_analysis'
/Users/bryanboyko/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.1/lib/cocoapods/validator.rb:263:in `each'
/Users/bryanboyko/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.1/lib/cocoapods/validator.rb:263:in `perform_extensive_analysis'
/Users/bryanboyko/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.1/lib/cocoapods/validator.rb:81:in `validate'
/Users/bryanboyko/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.1/lib/cocoapods/command/lib/lint.rb:58:in `block in run'
/Users/bryanboyko/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.1/lib/cocoapods/command/lib/lint.rb:47:in `each'
/Users/bryanboyko/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.1/lib/cocoapods/command/lib/lint.rb:47:in `run'
/Users/bryanboyko/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Users/bryanboyko/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'
/Users/bryanboyko/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
/Users/bryanboyko/.rbenv/versions/2.2.3/bin/pod:23:in `load'
/Users/bryanboyko/.rbenv/versions/2.2.3/bin/pod:23:in `<main>'
) during validation.

```

## CocoaPods Environment

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

**Comment by benasher44** [comment]
What version of CocoaPods are you using? And what version of Xcode are you using?

**Comment by bryanboyko** [comment]
cocoapods 1.0.1
XCode 8

**Comment by benasher44** [comment]
Ah Xcode 8 support was added in 1.1.0 RC builds. The latest is 1.1.0.rc.3, and this issue has been fixed in these more recent builds. Please update to the latest. Thanks!
