### ISSUE TITLE
A question about PrivateSpec dependency

### ISSUE THREAD

**Issue by mcmengchen** [CocoaPods/CocoaPods#6039]
## My need is to create a private pod which must depend on another private pod.

+ My depended private pod is named 'RBTest'. It's  podspec file is as follow: 
```
Pod::Spec.new do |s|
  s.name             = 'RBTest'
  s.version          = '0.1.0'
  s.summary          = 'a framework'
  s.description      = 'A short description of RBFrameWorkTest.!!!'
  s.homepage         = 'https://git.coding.net/michell/RBPrivateTest.git'
  s.license          = { :type => 'MIT', :file => 'LICENSE' }
  s.author           = { 'mengchen' => 'mengchen@roo.com' }
  s.source           = { :git => 'https://git.coding.net/michell/RBPrivateTest.git', :tag => s.version.to_s }
  s.ios.deployment_target = '7.0'
  s.source_files = 'RBTest/Classes/**/*'
end
```
![2016-10-15 12 04 47](https://cloud.githubusercontent.com/assets/9442979/19407276/9eca8f8a-92cf-11e6-803e-d9850b19079c.png)

+ My private pod is named 'RBTestPrivateSpec'. It's pod spec file is as follow:
```

Pod::Spec.new do |s|
  s.name             = 'RBTestPrivateSpec'
  s.version          = '0.1.0'
  s.summary          = 'a framework'
  s.description      = 'A short description of RBFrameWorkTest.!!!'
  s.homepage         = 'https://git.coding.net/michell/RBTestPrivateSpec.git'
  s.license          = { :type => 'MIT', :file => 'LICENSE' }
  s.author           = { 'mengchen' => 'mengchen@roo.com' }
  s.source           = { 
    :git => 'https://git.coding.net/michell/RBTestPrivateSpec.git',
    :tag => s.version.to_s,
    }
  s.ios.deployment_target = '7.0'
  s.source_files = 'RBTestPrivateSpec/Classes/**/*'
  s.dependency 'RBTest'
end
```
![2016-10-15 12 10 28](https://cloud.githubusercontent.com/assets/9442979/19407291/632ca75a-92d0-11e6-9a41-d80092266da8.png)

## How to lint my private pod 'RBTestPrivateSpec'?
When I use the command : 
```
pod spec lint RBTestPrivateSpec.podspec --sources='https://github.com/CocoaPods/Specs.git,https://git.coding.net/michell/RBPrivateTest.git' --verbose
```
I have the error:
```
Resolving dependencies of 
 -> RBTestPrivateSpec (0.1.0)
    - ERROR | [iOS] unknown: Encountered an unknown error (An unexpected version directory `Classes` was encountered for the `/Users/william/.cocoapods/repos/RBTest/RBTest` Pod in the `RBTest` repository.
/Users/william/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-core-1.0.1/lib/cocoapods-core/source.rb:171:in `rescue in block in versions'
/Users/william/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-core-1.0.1/lib/cocoapods-core/source.rb:168:in `block in versions'
/Users/william/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-core-1.0.1/lib/cocoapods-core/source.rb:166:in `map'
/Users/william/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-core-1.0.1/lib/cocoapods-core/source.rb:166:in `versions'
/Users/william/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-core-1.0.1/lib/cocoapods-core/specification/set.rb:85:in `block in versions_by_source'
/Users/william/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-core-1.0.1/lib/cocoapods-core/specification/set.rb:84:in `each'
/Users/william/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-core-1.0.1/lib/cocoapods-core/specification/set.rb:84:in `versions_by_source'
/Users/william/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-core-1.0.1/lib/cocoapods-core/specification/set.rb:60:in `versions'
/Users/william/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-core-1.0.1/lib/cocoapods-core/specification/set.rb:66:in `highest_version'
/Users/william/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-core-1.0.1/lib/cocoapods-core/specification/set.rb:76:in `highest_version_spec_path'
/Users/william/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-core-1.0.1/lib/cocoapods-core/specification/set.rb:45:in `specification'
/Users/william/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-core-1.0.1/lib/cocoapods-core/source.rb:268:in `search'
/Users/william/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-core-1.0.1/lib/cocoapods-core/source/aggregate.rb:83:in `block in search'
/Users/william/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-core-1.0.1/lib/cocoapods-core/source/aggregate.rb:83:in `select'
/Users/william/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-core-1.0.1/lib/cocoapods-core/source/aggregate.rb:83:in `search'
/Users/william/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-1.0.1/lib/cocoapods/resolver.rb:346:in `create_set_from_sources'
/Users/william/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-1.0.1/lib/cocoapods/resolver.rb:316:in `find_cached_set'
/Users/william/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-1.0.1/lib/cocoapods/resolver.rb:289:in `specifications_for_dependency'
/Users/william/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-1.0.1/lib/cocoapods/resolver.rb:107:in `search_for'
/Users/william/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-1.0.1/lib/cocoapods/resolver.rb:205:in `block in sort_dependencies'
/Users/william/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-1.0.1/lib/cocoapods/resolver.rb:199:in `each'
/Users/william/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-1.0.1/lib/cocoapods/resolver.rb:199:in `sort_by'
/Users/william/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-1.0.1/lib/cocoapods/resolver.rb:199:in `sort_dependencies'
/Users/william/.rvm/gems/ruby-2.0.0-p643/gems/molinillo-0.4.5/lib/molinillo/resolution.rb:131:in `block (2 levels) in <class:Resolution>'
/Users/william/.rvm/gems/ruby-2.0.0-p643/gems/molinillo-0.4.5/lib/molinillo/resolution.rb:437:in `push_state_for_requirements'
/Users/william/.rvm/gems/ruby-2.0.0-p643/gems/molinillo-0.4.5/lib/molinillo/resolution.rb:429:in `require_nested_dependencies_for'
/Users/william/.rvm/gems/ruby-2.0.0-p643/gems/molinillo-0.4.5/lib/molinillo/resolution.rb:417:in `activate_spec'
/Users/william/.rvm/gems/ruby-2.0.0-p643/gems/molinillo-0.4.5/lib/molinillo/resolution.rb:382:in `attempt_to_activate_new_spec'
/Users/william/.rvm/gems/ruby-2.0.0-p643/gems/molinillo-0.4.5/lib/molinillo/resolution.rb:320:in `attempt_to_activate'
/Users/william/.rvm/gems/ruby-2.0.0-p643/gems/molinillo-0.4.5/lib/molinillo/resolution.rb:147:in `process_topmost_state'
/Users/william/.rvm/gems/ruby-2.0.0-p643/gems/molinillo-0.4.5/lib/molinillo/resolution.rb:72:in `resolve'
/Users/william/.rvm/gems/ruby-2.0.0-p643/gems/molinillo-0.4.5/lib/molinillo/resolver.rb:42:in `resolve'
/Users/william/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-1.0.1/lib/cocoapods/resolver.rb:62:in `resolve'
/Users/william/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:563:in `block in resolve_dependencies'
/Users/william/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/Users/william/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:561:in `resolve_dependencies'
/Users/william/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:76:in `analyze'
/Users/william/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:227:in `analyze'
/Users/william/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:151:in `block in resolve_dependencies'
/Users/william/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/Users/william/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:150:in `resolve_dependencies'
/Users/william/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-1.0.1/lib/cocoapods/validator.rb:373:in `block in download_pod'
/Users/william/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-1.0.1/lib/cocoapods/validator.rb:373:in `each'
/Users/william/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-1.0.1/lib/cocoapods/validator.rb:373:in `download_pod'
/Users/william/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-1.0.1/lib/cocoapods/validator.rb:269:in `block in perform_extensive_analysis'
/Users/william/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-1.0.1/lib/cocoapods/validator.rb:263:in `each'
/Users/william/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-1.0.1/lib/cocoapods/validator.rb:263:in `perform_extensive_analysis'
/Users/william/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-1.0.1/lib/cocoapods/validator.rb:81:in `validate'
/Users/william/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-1.0.1/lib/cocoapods/command/spec/lint.rb:60:in `block in run'
/Users/william/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-1.0.1/lib/cocoapods/command/spec/lint.rb:50:in `each'
/Users/william/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-1.0.1/lib/cocoapods/command/spec/lint.rb:50:in `run'
/Users/william/.rvm/gems/ruby-2.0.0-p643/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Users/william/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'
/Users/william/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
/Users/william/.rvm/gems/ruby-2.0.0-p643/bin/pod:23:in `load'
/Users/william/.rvm/gems/ruby-2.0.0-p643/bin/pod:23:in `<main>'
) during validation.

Analyzed 1 podspec.

[!] The spec did not pass validation, due to 1 error.

/Users/william/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-1.0.1/lib/cocoapods/command/spec/lint.rb:77:in `run'
/Users/william/.rvm/gems/ruby-2.0.0-p643/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Users/william/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'
/Users/william/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
/Users/william/.rvm/gems/ruby-2.0.0-p643/bin/pod:23:in `load'
/Users/william/.rvm/gems/ruby-2.0.0-p643/bin/pod:23:in `<main>'
```
## Did anybody have the trouble? How can I resolve it ?

**Comment by orta** [comment]
Are you using Xcode 8, CocoaPods 1.0.1 does not support Xcode 8 I'm afraid - only the RC

**Comment by mcmengchen** [comment]
My Xcode version is 7.3.     @orta

**Comment by orta** [comment]
What does the result of `xcode-select --print-path` say? 
Please can you test with the CocoaPods 1.1.0.rc.3 also?

**Comment by mcmengchen** [comment]
The result of ```xcode-select --print-path``` is ```/Applications/Xcode.app/Contents/Developer```.
I have test with the newest CocoaPods version, but it still does.

**Comment by DanToml** [comment]
It looks like you're providing the repo for your pod as a Source to lint, but sources are repos of specifications like CocoaPods/Specs

**Comment by mcmengchen** [comment]
How to resolve it? @DanToml

**Comment by DanToml** [comment]
@mcmengchen You can use a private specs repository: https://guides.cocoapods.org/making/private-cocoapods.html

**Comment by mcmengchen** [comment]
I have read the webpage. The thing I want to do is to make a private specs repo depends on  another private specs repo. I think this webpage can't solve my problem.

**Comment by orta** [comment]
I think you may be confused by the terminology, a spec repo contains a lot of Pods. You cannot have a specs  that relies on other spec repos, as that doesn't make sense. 

You probably don't want to include `https://git.coding.net/michell/RBPrivateTest.git` in your lint command.

**Comment by mcmengchen** [comment]
'RBTest' has been a private pod. I just want to use it in my private pod named 'RBTestPrivateSpec'. How can I achieve it? @orta

**Comment by mcmengchen** [comment]
Can anybody help me ? @segiddins @fabiopelosin @alloy @mrackwitz @kylef @neonichu @benasher44 @DanToml @AliSoftware  @lukeredpath

**Comment by benasher44** [comment]
I don't really understand. Do you want to distribute `RBTestPrivateSpec` publicly, but it depends on `RBTest` only for you?

**Comment by mcmengchen** [comment]
Yes, but ```RBTestPrivateSpec``` is still private, it only for our team to use.   I hope they can use it via add 
```
pod "RBTestPrivateSpec",:git =>'https://git.coding.net/michell/RBTestPrivateSpec.git‘ 
```
in their podfile to use it.
@benasher44

**Comment by benasher44** [comment]
In that case, you should look at setting up a private specs repo here: https://guides.cocoapods.org/making/private-cocoapods.html. This is the only way that I know of to support private pod that also has a private dependency, since there's no equivalent `:git` argument for podspec dependencies.

**Comment by benasher44** [comment]
I think the next steps here are pretty well-documented. Please try out some of the suggested solutions and open a new issue, if you run into any problems. Thanks for filing!

**Comment by mcmengchen** [comment]
Thank u. @benasher44
