### ISSUE TITLE
Can't create podspec

### ISSUE THREAD

**Issue by inoue0426** [CocoaPods/CocoaPods#6072]
# Report 
🌈

## What did you do?
```
X069-155:YICam inoueyoshitaka$ ls
Demo		LICENSE		README.md	YICam		YICam.xcodeproj	YICamTests
X069-155:YICam inoueyoshitaka$ pod spec create git@github.com:inoue0426/YICam.git
```
Under this enviroment, I typed `pod spec create git@github.com:inoue0426/YICam.git` from terminal.

## What did you expect to happen?
I want to manage Swift library by CocoaPods.

### Error

```
Errno::ENOENT - No such file or directory @ rb_sysopen - /Users/inoueyoshitaka/Code/YICam/git@github.com:inoue0426/YICam.git.podspec
/Users/inoueyoshitaka/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/command/spec/create.rb:39:in `initialize'
/Users/inoueyoshitaka/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/command/spec/create.rb:39:in `open'
/Users/inoueyoshitaka/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/command/spec/create.rb:39:in `open'
/Users/inoueyoshitaka/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/command/spec/create.rb:39:in `run'
/Users/inoueyoshitaka/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Users/inoueyoshitaka/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/Users/inoueyoshitaka/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/Users/inoueyoshitaka/.rbenv/versions/2.3.1/bin/pod:22:in `load'
/Users/inoueyoshitaka/.rbenv/versions/2.3.1/bin/pod:22:in `<main>'
```

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
    RubyGems : 2.6.7
        Host : Mac OS X 10.11.6 (15G31)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /Users/inoueyoshitaka/.rbenv/versions/2.3.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 8b9929d7b36cc0c559bf4f8eb88d33116a40e604
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

**Comment by orta** [comment]
For others looking [you need to use the github repo URL, rather than a ssh URL](https://guides.cocoapods.org/terminal/commands.html#pod_spec_create) -`pod spec create [NAME|https://github.com/USER/REPO]`

**Comment by inoue0426** [comment]
Thanks! 
This mistake was very careless...🤔
