### ISSUE TITLE
Unable to convert Ruby value `"GTMSessionFetcher"' into a CFTypeRef

### ISSUE THREAD

**Issue by KingFeef** [CocoaPods/CocoaPods#6094]
> ℹ Please fill out this template when filing an issue.
> All lines beginning with an ℹ symbol instruct you with
> what info we expect.  
> Please remove this line and all above before submitting.

> Before you start, are you using the CocoaPods beta release?
> a lot has changed with Xcode 8 that is not backwards compatible.
>
> Xcode 8 Status: Only works with CocoaPods 1.1.0
> Swift 3: You need to add a `.swift-version` file, see the CHANGELOG
> China: Use https://gems.ruby-china.org/ instead of https://gems.ruby-china.org/ for the RC see #5910

* [ ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace this with what you did.  
Run pod update

## What did you expect to happen?

Update all pod dependencies correctly.

## What happened instead?

Received an error message and now project in Xcode is not building properly.  Here's the error message.

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]
    RubyGems : 2.6.3
        Host : Mac OS X 10.12 (16A323)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /Users/AppleComputer/.rvm/rubies/ruby-2.2.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 3221595f1f5e8c13053a18ac71419d2a67d897d6
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '8.1'

target 'Funyado' do

  use_frameworks!

  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  source 'https://github.com/CocoaPods/Specs.git'
  pod 'GoogleMaps'
  pod 'GooglePlaces'

  # Pods for Funyado

end
```

### Error

```
TypeError - Unable to convert Ruby value `"GTMSessionFetcher"' into a CFTypeRef.
/Users/AppleComputer/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.3.3/lib/xcodeproj/plist/ffi/core_foundation.rb:383:in `RubyValueToCFTypeRef'
/Users/AppleComputer/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.3.3/lib/xcodeproj/plist/ffi/core_foundation.rb:402:in `block in RubyHashToCFDictionary'
/Users/AppleComputer/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.3.3/lib/xcodeproj/plist/ffi/core_foundation.rb:400:in `each'
/Users/AppleComputer/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.3.3/lib/xcodeproj/plist/ffi/core_foundation.rb:400:in `RubyHashToCFDictionary'
/Users/AppleComputer/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.3.3/lib/xcodeproj/plist/ffi/core_foundation.rb:372:in `RubyValueToCFTypeRef'
/Users/AppleComputer/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.3.3/lib/xcodeproj/plist/ffi/core_foundation.rb:402:in `block in RubyHashToCFDictionary'
/Users/AppleComputer/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.3.3/lib/xcodeproj/plist/ffi/core_foundation.rb:400:in `each'
/Users/AppleComputer/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.3.3/lib/xcodeproj/plist/ffi/core_foundation.rb:400:in `RubyHashToCFDictionary'
/Users/AppleComputer/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.3.3/lib/xcodeproj/plist/ffi/core_foundation.rb:372:in `RubyValueToCFTypeRef'
/Users/AppleComputer/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.3.3/lib/xcodeproj/plist/ffi/core_foundation.rb:402:in `block in RubyHashToCFDictionary'
/Users/AppleComputer/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.3.3/lib/xcodeproj/plist/ffi/core_foundation.rb:400:in `each'
/Users/AppleComputer/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.3.3/lib/xcodeproj/plist/ffi/core_foundation.rb:400:in `RubyHashToCFDictionary'
/Users/AppleComputer/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.3.3/lib/xcodeproj/plist/ffi.rb:130:in `ruby_hash_write_devtoolscore'
/Users/AppleComputer/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.3.3/lib/xcodeproj/plist/ffi.rb:120:in `ruby_hash_write_xcode'
/Users/AppleComputer/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.3.3/lib/xcodeproj/plist/ffi.rb:43:in `write_to_path'
/Users/AppleComputer/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.3.3/lib/xcodeproj/plist.rb:46:in `write_to_path'
/Users/AppleComputer/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.3.3/lib/xcodeproj/project.rb:335:in `save'
/Users/AppleComputer/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.1.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:77:in `block in write'
/Users/AppleComputer/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:142:in `message'
/Users/AppleComputer/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.1.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:69:in `write'
/Users/AppleComputer/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:182:in `block in generate_pods_project'
/Users/AppleComputer/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/AppleComputer/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:178:in `generate_pods_project'
/Users/AppleComputer/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:115:in `install!'
/Users/AppleComputer/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.1.1/lib/cocoapods/command/update.rb:60:in `run'
/Users/AppleComputer/.rvm/gems/ruby-2.2.0@global/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Users/AppleComputer/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/Users/AppleComputer/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/Users/AppleComputer/.rvm/gems/ruby-2.2.0/bin/pod:22:in `load'
/Users/AppleComputer/.rvm/gems/ruby-2.2.0/bin/pod:22:in `<main>'
/Users/AppleComputer/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
/Users/AppleComputer/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]
    RubyGems : 2.6.3
        Host : Mac OS X 10.12 (16A323)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /Users/AppleComputer/.rvm/rubies/ruby-2.2.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 3221595f1f5e8c13053a18ac71419d2a67d897d6
```

### Installation Source

```
Executable Path: /Users/AppleComputer/.rvm/gems/ruby-2.2.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '8.1'

target 'Funyado' do

  use_frameworks!

  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  source 'https://github.com/CocoaPods/Specs.git'
  pod 'GoogleMaps'
  pod 'GooglePlaces'

  # Pods for Funyado

end
```

**Comment by KingFeef** [comment]
Well, I just ran pod install, and then pod update again...both got errors. Then I ran pod update again with my Xcode open by accident and the update took.  I'm not sure what actually caused the update to work, but there's no error now.

**Comment by benasher44** [comment]
Hm interesting. On master, this code path is gone. I'm going to close this one for now. A beta will be coming out shortly with this update. Please file a new ticket if you experience this when the beta comes out. Thanks for filing!
