### ISSUE TITLE
crash on pod install

### ISSUE THREAD

**Issue by keepingitneil** [CocoaPods/CocoaPods#6095]
### Stack                                                                                                                                                                                            [58/80]

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12 (16A323)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 0cbc936f9726cc021e936e92185a3e04bd4f289a
               riano-specs - git@github.com:bebo/podspecs.git @ cc410b489405ac97ad914267efb11ddd9c177614
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'riano' do

use_frameworks!

pod 'Fabric'
pod 'Crashlytics'
pod 'SocketRocket'
pod 'RxSwift'
pod 'RxCocoa'
pod 'SDWebImage'
pod 'Realm'
pod 'Alamofire', '4.0.1'
pod 'GCDWebServer', '~> 3.2.5'                                                                                                                                                                       [15/80]
pod 'riano-ios-tooltipper', { :git => 'git@github.com:bebo/riano-ios-tooltipper.git', :branch => 'master' }
pod 'riano-ios-event-tracker', { :git => 'git@github.com:bebo/riano-ios-event-tracker.git', :branch => 'master' }
pod 'riano-ios-use-cases', { :git => 'git@github.com:bebo/riano-ios-use-cases.git', :branch => 'master' }
pod 'riano-ios-http', { :git => 'git@github.com:bebo/riano-ios-http.git', :branch => 'master' }
end
```

### Error

```
NoMethodError - undefined method `dirname' for nil:NilClass
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/validator.rb:261:in `dot_swift_version'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/validator.rb:145:in `failure_reason'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/external_sources/abstract_external_source.rb:176:in `validate_podspec'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/external_sources/abstract_external_source.rb:163:in `store_podspec'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/external_sources/abstract_external_source.rb:119:in `block in pre_download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:85:in `titled_section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/external_sources/abstract_external_source.rb:112:in `pre_download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/external_sources/downloader_source.rb:13:in `fetch'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:639:in `fetch_external_source'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:615:in `block (2 levels) in fetch_external_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:614:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:614:in `block in fetch_external_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:613:in `fetch_external_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:73:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:236:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:150:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:149:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:110:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command/install.rb:37:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/usr/local/Cellar/cocoapods/1.1.1/libexec/bin/pod:23:in `load'
/usr/local/Cellar/cocoapods/1.1.1/libexec/bin/pod:23:in `<main>'
```

**Comment by benasher44** [comment]
It looks like something is wrong with how it's reading the contents of one of the `bebo/` repos. Those are private, so it's hard for me to debug this. Can you provide more information about the layout of those repos?

**Comment by keepingitneil** [comment]
```.
├── Podfile
├── Podfile.lock
├── Pods/
├── README.md
├── RianoUseCases
│   ├── Info.plist
│   ├── RianoUseCases.h
│   └── src
│       ├── CheckHasDoneLocationUseCase.swift
│       ├── CheckServerCodeUseCase.swift
│       ├── ClearKeychainUseCase.swift
│       ├── CreateServerUseCase.swift
│       ├── DeleteUserSessionUseCase.swift
│       ├── DeviceCheckLoginUseCase.swift
│       ├── DeviceLoginUseCase.swift
│       ├── DeviceSaveLoginUseCase.swift
│       ├── GetDeviceIdUseCase.swift
│       ├── GetServerListUseCase.swift
│       ├── GetServerRosterUseCase.swift
│       ├── GetTokboxDeviceIdUseCase.swift
│       ├── GetUserMeFromCacheUseCase.swift
│       ├── GetUserProfileUseCase.swift
│       ├── GetUserSessionUseCase.swift
│       ├── GetWidgetFromCacheUseCase.swift
│       ├── KeychainSwiftDistrib.swift
│       ├── RealmFactory.swift
│       ├── RealmModels.swift
│       ├── RedundantSaveDeviceIdUseCase.swift
│       ├── RedundantSaveLoginUseCase.swift
│       ├── SaveDeviceIdUseCase.swift
│       ├── SaveProfileImageUseCase.swift
│       ├── SaveTokboxDeviceIdUseCase.swift
│       ├── SaveUserMeToCacheUseCase.swift
│       ├── SaveUserSessionUseCase.swift
│       ├── SaveWidgetToCacheUseCase.swift
│       ├── SendAPNSTokensUseCase.swift
│       ├── Server.swift
│       ├── SyncAccountUseCase.swift
│       ├── SyncUserUseCase.swift
│       ├── UpdateUserUseCase.swift
│       ├── User.swift
│       ├── UserMe.swift
│       ├── UserProfile.swift
│       └── UserSession.swift
├── RianoUseCases.xcodeproj
│   ├── project.pbxproj
│   ├── project.xcworkspace
│   │   ├── contents.xcworkspacedata
│   │   └── xcuserdata
│   │       └── neildwyer.xcuserdatad
│   │           └── UserInterfaceState.xcuserstate
│   ├── xcshareddata
│   │   └── xcschemes
│   │       └── RianoUseCases.xcscheme
│   └── xcuserdata
│       └── neildwyer.xcuserdatad
│           └── xcschemes
│               └── xcschememanagement.plist
├── RianoUseCases.xcworkspace
│   └── contents.xcworkspacedata
├── RianoUseCasesTests
│   ├── Info.plist
│   └── RianoUseCasesTests.swift
├── riano-ios-use-cases.podspec```

**Comment by benasher44** [comment]
This was fixed by ee6c72975df2f56fed1f4a0acf0874f9c9a22f8f, which isn't in 1.1.1, but it will be in an upcoming beta release. Thanks for filing!

**Comment by sunwell** [comment]
I have a same problem. But when I reinstall **_CocoaPods_** with `sudo gem install cocoapods -n /usr/local/bin --verbose`, my **_CocoaPods_** version is still **_1.1.1_**. How can I update **_CocoaPods_** to the latest version.

**Comment by benasher44** [comment]
`gem intall cocoapods --pre`

**Comment by sunwell** [comment]
@benasher44 Thx~
