### ISSUE TITLE
Nanaimo::Reader::ParseError - not a valid string at index 114798 (char is "$")

### ISSUE THREAD

**Issue by newmanw** [CocoaPods/CocoaPods#6101]
# Report

## What did you do?

ℹ Please replace this with what you did.  
pod install

## What did you expect to happen?
not an error

ℹ Please replace this with what you expected to happen.  
Install all pod dependencies correctly.

## What happened instead?

ℹ Please replace this with of what happened instead.  
### Error

```
Nanaimo::Reader::ParseError - not a valid string at index 114798 (char is "$")
/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.1.1/lib/nanaimo/reader.rb:251:in `raise_parser_error'
/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.1.1/lib/nanaimo/reader.rb:116:in `parse_string'
/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.1.1/lib/nanaimo/reader.rb:106:in `parse_object'
/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.1.1/lib/nanaimo/reader.rb:159:in `parse_dictionary'
/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.1.1/lib/nanaimo/reader.rb:98:in `parse_object'
/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.1.1/lib/nanaimo/reader.rb:159:in `parse_dictionary'
/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.1.1/lib/nanaimo/reader.rb:98:in `parse_object'
/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.1.1/lib/nanaimo/reader.rb:159:in `parse_dictionary'
/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.1.1/lib/nanaimo/reader.rb:98:in `parse_object'
/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.1.1/lib/nanaimo/reader.rb:73:in `parse!'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.0/lib/xcodeproj/plist.rb:27:in `read_from_path'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.0/lib/xcodeproj/project.rb:200:in `initialize_from_file'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.0/lib/xcodeproj/project.rb:102:in `open'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:855:in `block (2 levels) in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:854:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:854:in `block in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:849:in `inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:66:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:236:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:150:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:149:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:110:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command/install.rb:37:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

## CocoaPods Environment

ℹ Please replace this with the output of `pod env`.
no output

**Comment by orta** [comment]
Can you share your Xcodeproject? 

Or if note, some of the bits that seem relevant to the error message "not a valid string at index 114798 (char is "$")"

**Comment by newmanw** [comment]
I cannot.  I did remove all dependencies from my Podfile:

```bash
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target :"MyProject" do
end
```

I have also removed my xcworkspace.

Of note I just downloaded and updated to xcode 8.1.  I did not see this issue when using xcode 8.0.

**Comment by newmanw** [comment]
@orta 'some of the bits that seem relevant to the error message'.  Not sure where to even start looking.  Any ideas?

**Comment by phimage** [comment]
Same error here I think
```
Nanaimo::Reader::ParseError - not a valid string at index 70273 (char is "$")
````
At character 70273 of my Project.xcodeproj/project.pbxproj I have
```
buildToolPath = $PROJECT_DIR/genstrings/mergegenstrings.py;
```

more of my project files (two target of type external build system which launch some scripts)
```
/* Begin PBXLegacyTarget section */
		C46800B81AF0FD6F00BF0835 /* mergegenstrings.py */ = {
			isa = PBXLegacyTarget;
			buildArgumentsString = "$PROJECT_NAME '\"\\s*(.+)\"\\.localized'";
			buildConfigurationList = C46800B91AF0FD6F00BF0835 /* Build configuration list for PBXLegacyTarget "mergegenstrings.py" */;
			buildPhases = (
			);
			buildToolPath = $PROJECT_DIR/genstrings/mergegenstrings.py;
			buildWorkingDirectory = $PROJECT_DIR;
			dependencies = (
			);
			name = mergegenstrings.py;
			passBuildSettingsInEnvironment = 1;
			productName = mergegenstrings.py;
		};
		C4853AF71AC55A74006DDB03 /* mogenerator */ = {
			isa = PBXLegacyTarget;
			buildArgumentsString = "--swift --v2 --model \"$PROJECT_DIR/Model.xcdatamodeld\" --template-path \"$PROJECT_DIR/mogenerator/template\" --output-dir \"$PROJECT_DIR/$PROJECT_NAME/Model\"";
			buildConfigurationList = C4853AFA1AC55A74006DDB03 /* Build configuration list for PBXLegacyTarget "mogenerator" */;
			buildPhases = (
			);
			buildToolPath = $PROJECT_DIR/mogenerator/mogenerator;
			buildWorkingDirectory = "";
			dependencies = (
			);
			name = mogenerator;
			passBuildSettingsInEnvironment = 1;
			productName = moogenerator;
		};
```

**Comment by montehurd** [comment]
> Of note I just downloaded and updated to xcode 8.1. I did not see this issue when using xcode 8.0.

Same.

**Comment by orta** [comment]
These errors are specific to the version of xcodeproj you have, for now, you can do:

```sh
[sudo] gem uninstall xcodeproj
[sudo] gem install xcodeproj -v 1.3.3
```

To get back to our last major release, which should work fine.

@phimage that is the sort of thing, yeah! Thanks

**Comment by segiddins** [comment]
`gem install nanaimo:0.1.2` will also fix it :)
