### ISSUE TITLE
Error installing pods after updating xcodeproj

### ISSUE THREAD

**Issue by beloso** [CocoaPods/CocoaPods#6104]
🌈
- [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md). 
  # Report
### Command

```
/Users/tveloso/.rbenv/versions/2.2.3/bin/pod install
```
### Report
- What did you do?

Ran `bundle update`, then `pod update`.
- What did you expect to happen?

Pods to be installed without problems
- What happened instead?

An error due to the latest version of Xcodeproj (1.4.0) I think.
I claims it can write to an Ascii plist file

I've posted a redacted version of my podfile.
### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]
    RubyGems : 2.6.7
        Host : Mac OS X 10.12 (16A323)
       Xcode : 8.0 (8A218a)
         Git : git version 2.10.1
Ruby lib dir : /Users/tveloso/.rbenv/versions/2.2.3/lib
Repositories : redacted-podspecs - git@gitlab.redacted.com:ios/redacted-podspecs.git @ afa0abd5d370a3b5782d4f24aa3b35b2dd1641c8
               master - https://github.com/CocoaPods/Specs.git @ bc15e82ef4cf2e8b5ccc3a13e0154940bd099a2d
```
### Plugins

```
cocoapods-clean       : 0.0.1
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
slather               : 2.3.0
```
### Podfile

``` ruby
source 'https://github.com/CocoaPods/Specs.git'
source 'git@gitlab.redacted.com:ios/redacted-podspecs.git'

platform :ios, '8.0'

target 'redacted' do
  pod 'redactedSDK', '0.20.5'
  pod 'AFNetworkActivityLumberjackLogger', :git => 'https://github.com/crsantos/AFNetworkActivityLumberjackLogger', :branch => 'feature/afnetworking3'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'
  pod 'CWStatusBarNotification'
  pod 'ASMediaFocusManager', :git => 'https://github.com/autresphere/ASMediaFocusManager', :commit => '3eb1f228305b125619dcda161468f4f17a45de95'
  pod 'DeepLinkKit', '~> 1.2.0'
  pod 'CYWheelPickerView'
  pod 'UIImageViewAligned'
  pod 'MMPReactiveCoreLocation'

  target 'redactedTests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'OCMockito'
    pod 'Expecta+OCMock'
    pod 'OHHTTPStubs'
  end
end

post_install do |installer|
  use_lumberjack_with_mqtt_client(installer)

  rebuild_preprocessor_macros(installer)
end

######################################################################
# Use CocoaLumberjack with MQTTClient

def use_lumberjack_with_mqtt_client(installer)

  installer.pods_project.targets.each do |target|
    if target.name == "MQTTClient"
      target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'LUMBERJACK=1']
      end
    end
  end
end

######################################################################
# Rebuilds preprocessor macros for SDK pod
def rebuild_preprocessor_macros(installer)

  macros = {
    'Debug' => 'DEBUG=1',
    'InHouse' => 'INHOUSE=1',
    'AppStore' => 'APPSTORE=1',
    'Release' => ''
  }

  installer.pods_project.targets.each do |target|
    if target.name == "redactedSDK"
      puts "Rebuilding preprocessor macros for " + target.name
      target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', macros[config.name]]
      end
    end
  end
end
```
### Error

```
RuntimeError - Cannot write  to an ascii plist
/Users/tveloso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/nanaimo-0.1.1/lib/nanaimo/writer.rb:63:in `write_object'
/Users/tveloso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/nanaimo-0.1.1/lib/nanaimo/writer.rb:110:in `write_array_element'
/Users/tveloso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/nanaimo-0.1.1/lib/nanaimo/writer.rb:91:in `block in write_array'
/Users/tveloso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/nanaimo-0.1.1/lib/nanaimo/writer.rb:90:in `each'
/Users/tveloso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/nanaimo-0.1.1/lib/nanaimo/writer.rb:90:in `write_array'
/Users/tveloso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/nanaimo-0.1.1/lib/nanaimo/writer.rb:53:in `write_object'
/Users/tveloso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/nanaimo-0.1.1/lib/nanaimo/writer.rb:140:in `write_dictionary_key_value_pair'
/Users/tveloso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/nanaimo-0.1.1/lib/nanaimo/xcode_project_writer.rb:41:in `write_dictionary_key_value_pair'
/Users/tveloso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/nanaimo-0.1.1/lib/nanaimo/writer.rb:119:in `block in write_dictionary'
/Users/tveloso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/nanaimo-0.1.1/lib/nanaimo/writer.rb:118:in `each'
/Users/tveloso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/nanaimo-0.1.1/lib/nanaimo/writer.rb:118:in `write_dictionary'
/Users/tveloso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/nanaimo-0.1.1/lib/nanaimo/xcode_project_writer.rb:19:in `write_dictionary'
/Users/tveloso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/nanaimo-0.1.1/lib/nanaimo/writer.rb:55:in `write_object'
/Users/tveloso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/nanaimo-0.1.1/lib/nanaimo/writer.rb:140:in `write_dictionary_key_value_pair'
/Users/tveloso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/nanaimo-0.1.1/lib/nanaimo/xcode_project_writer.rb:41:in `write_dictionary_key_value_pair'
/Users/tveloso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/nanaimo-0.1.1/lib/nanaimo/writer.rb:119:in `block in write_dictionary'
/Users/tveloso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/nanaimo-0.1.1/lib/nanaimo/writer.rb:118:in `each'
/Users/tveloso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/nanaimo-0.1.1/lib/nanaimo/writer.rb:118:in `write_dictionary'
/Users/tveloso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/nanaimo-0.1.1/lib/nanaimo/xcode_project_writer.rb:19:in `write_dictionary'
/Users/tveloso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/nanaimo-0.1.1/lib/nanaimo/writer.rb:55:in `write_object'
/Users/tveloso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/nanaimo-0.1.1/lib/nanaimo/writer.rb:140:in `write_dictionary_key_value_pair'
/Users/tveloso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/nanaimo-0.1.1/lib/nanaimo/xcode_project_writer.rb:41:in `write_dictionary_key_value_pair'
/Users/tveloso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/nanaimo-0.1.1/lib/nanaimo/xcode_project_writer.rb:29:in `block (2 levels) in write_dictionary'
/Users/tveloso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/nanaimo-0.1.1/lib/nanaimo/xcode_project_writer.rb:28:in `each'
/Users/tveloso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/nanaimo-0.1.1/lib/nanaimo/xcode_project_writer.rb:28:in `block in write_dictionary'
/Users/tveloso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/nanaimo-0.1.1/lib/nanaimo/xcode_project_writer.rb:24:in `each'
/Users/tveloso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/nanaimo-0.1.1/lib/nanaimo/xcode_project_writer.rb:24:in `write_dictionary'
/Users/tveloso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/nanaimo-0.1.1/lib/nanaimo/writer.rb:55:in `write_object'
/Users/tveloso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/nanaimo-0.1.1/lib/nanaimo/writer.rb:140:in `write_dictionary_key_value_pair'
/Users/tveloso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/nanaimo-0.1.1/lib/nanaimo/xcode_project_writer.rb:41:in `write_dictionary_key_value_pair'
/Users/tveloso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/nanaimo-0.1.1/lib/nanaimo/writer.rb:119:in `block in write_dictionary'
/Users/tveloso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/nanaimo-0.1.1/lib/nanaimo/writer.rb:118:in `each'
/Users/tveloso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/nanaimo-0.1.1/lib/nanaimo/writer.rb:118:in `write_dictionary'
/Users/tveloso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/nanaimo-0.1.1/lib/nanaimo/xcode_project_writer.rb:19:in `write_dictionary'
/Users/tveloso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/nanaimo-0.1.1/lib/nanaimo/writer.rb:55:in `write_object'
/Users/tveloso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/nanaimo-0.1.1/lib/nanaimo/writer.rb:29:in `write'
/Users/tveloso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/xcodeproj-1.4.0/lib/xcodeproj/project.rb:353:in `block in save'
/Users/tveloso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/xcodeproj-1.4.0/lib/xcodeproj/project.rb:353:in `open'
/Users/tveloso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/xcodeproj-1.4.0/lib/xcodeproj/project.rb:353:in `save'
/Users/tveloso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:77:in `block in write'
/Users/tveloso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:142:in `message'
/Users/tveloso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:69:in `write'
/Users/tveloso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:182:in `block in generate_pods_project'
/Users/tveloso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/tveloso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:178:in `generate_pods_project'
/Users/tveloso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:115:in `install!'
/Users/tveloso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.1/lib/cocoapods/command/install.rb:37:in `run'
/Users/tveloso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Users/tveloso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/Users/tveloso/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/Users/tveloso/.rbenv/versions/2.2.3/bin/pod:22:in `load'
/Users/tveloso/.rbenv/versions/2.2.3/bin/pod:22:in `<main>'
```

**Comment by Brett-Best** [comment]
I'm also seeing this, my podfile is below.

```ruby
plugin 'cocoapods-acknowledgements', :settings_bundle => true

platform :ios, '9.0'
use_frameworks!

def pods_snapshot
  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'AlamofireNetworkActivityIndicator'
  pod 'Decodable'
  pod 'HockeySDK'
  pod 'Hue'
  pod 'Moya'
  pod 'Result'
end

target 'Snapshot Wall' do
  pods_snapshot

  target 'Snapshot Wall Tests' do
    inherit! :search_paths
  end

  target 'Snapshot Wall UI Tests' do
    inherit! :search_paths
  end
end
```

**Comment by DanToml** [comment]
Interesting. My guess is that something is `nil` in the project.

**Comment by rocco** [comment]
Same here, upgraded from xcodeproj 1.3.2 to 1.4.0. This version started using the Nanaimo gem to parse .pbxproj files. In my case it's a Cordova-generated project. Works with 1.3.2 so I rolled back.

**Comment by Dinalli** [comment]
Anyone found a solution to this yet ? I've tried a few things including trying the latest beta of Cocoapods and had no luck.

**Comment by beloso** [comment]
I've rolled back to xcodeproj 1.3.3 in my gem file. Everything is working.

**Comment by nicolasgoutaland** [comment]
I there, did just encounter the same problem.
Pod install run well, but the pbxproj is incorrect.
Did uninstall xcodeproj and force installation of version 1.3.3, and everything is fine now.

**Comment by segiddins** [comment]
Please try again with Xcodeproj 1.4.1

**Comment by rocco** [comment]
@segiddins works for me now using 1.4.1 with a Cordova project based on [cordova-ios](https://github.com/apache/cordova-ios) 4.3.0 - thanks!

**Comment by beloso** [comment]
@segiddins `pod install`/`pod update` does complete without an issue

But I am getting the following error in xcode now:
`/Users/tveloso/Developer/redacted/Pods/Pods.xcodeproj Couldn't load project`

**Comment by segiddins** [comment]
Can you please share the project Xcode can't open?

**Comment by beloso** [comment]
Can I email it to you?

**Comment by segiddins** [comment]
It's preferred to post it publicly so anyone can try to investigate the issue

**Comment by beloso** [comment]
I haven't forgotten about this. It's a chaotic time for me to prepare the `Pods.xcodeproj`. I need to remove references to a private pod that I can't disclose.

I'll try to get to this next week.

**Comment by beloso** [comment]
I'm finally able to come back to this.

Is there a quick way to anonymize a xcodeproj file?

I have a private pod that I don't have the right to disclose.

**Comment by DanToml** [comment]
Sadly there's no easy way to do so without changing the results of parsing anyway, however, this should be fixed in the latest versions of Xcodeproj and Nanaimo, if this is still a problem please file a new issue, including a sample project.
