### ISSUE TITLE
Nanaimo parse error

### ISSUE THREAD

**Issue by dyegos** [CocoaPods/CocoaPods#6124]
### Command
```
/usr/local/bin/pod install
```
### Report
* What did you do?
I'm updating my cocoapods version from 1.0.1 to 1.1.1 and running pod install to try the new integration
* What did you expect to happen?
I expected to be able to run `pod install` and have the pods integrated without problems
* What happened instead?
The command fails the output bellow
* Aditional information:
I tried to deintegrate the pods, but it fails with the same error.
### Stack
```
   CocoaPods : 1.1.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.1 (16B2555)
       Xcode : 8.1 (8B62)
         Git : git version 2.10.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ fe5b0a40ae93ce1193c72ecb8393a880094e1131
```
### Plugins
```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```
### Podfile
```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
target 'Spendee' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!
  # Pods for Spendee
    pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'Google/SignIn'
    pod 'Google/Analytics'
    pod 'GoogleIDFASupport'
    
    pod 'FBSDKCoreKit', '~> 4.8.0'
    pod 'FBSDKLoginKit', '~> 4.8.0'
    pod 'SVProgressHUD', '~> 1.1.3'
    pod 'BVReorderTableView', '~> 1.0.0'
    pod 'MagicalRecord', '~> 2.3.0'
    pod 'AFNetworking', '~> 2.6.3'
    pod 'AFNetworkActivityLogger', '~> 2.0.4'
    pod 'SDWebImage', '~> 3.7.3'
    pod 'CocoaLumberjack', '~> 2.2.0'
    pod 'Mantle', '~> 2.0.5'
    pod 'EGOCache', '~> 2.1.3'
    pod 'HockeySDK', '~> 3.8.5'
    pod 'JVFloatLabeledTextField', '~> 1.1.0'
    pod 'NSDate+Calendar', '~> 0.0.8'
    pod 'pop', '~> 1.0.9'
    pod 'DACircularProgress', '~> 2.3.1'
    pod 'PureLayout', '~> 3.0.1'
    pod 'CargoBay', '~> 2.1.1'
    pod 'Lockbox', '~> 2.1.0'
    pod 'FormatterKit', '~> 1.8.0'
    pod 'UICountingLabel', '~> 1.4.0'
    pod 'AMPopTip', '~> 1.2.0'
    pod 'TTTAttributedLabel', '~> 1.13.4'
end
```
### Error
```
Nanaimo::Reader::ParseError - Array [#<Nanaimo::QuotedString:0x007f863513aca0 @value="$(inherited)", @annotation="">, #<Nanaimo::QuotedString:0x007f863513a9a8 @value="COCOAPODS=1", @annotation="">, #<Nanaimo::QuotedString:0x007f863513a6b0 @value="$(inherited)", @annotation="">, #<Nanaimo::QuotedString:0x007f863513a2f0 @value="BITHOCKEY_VERSION=\"@\\", @annotation="">] missing ',' in between objects
/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.1.2/lib/nanaimo/reader.rb:251:in `raise_parser_error'
/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.1.2/lib/nanaimo/reader.rb:140:in `parse_array'
/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.1.2/lib/nanaimo/reader.rb:100:in `parse_object'
/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.1.2/lib/nanaimo/reader.rb:159:in `parse_dictionary'
/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.1.2/lib/nanaimo/reader.rb:98:in `parse_object'
/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.1.2/lib/nanaimo/reader.rb:159:in `parse_dictionary'
/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.1.2/lib/nanaimo/reader.rb:98:in `parse_object'
/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.1.2/lib/nanaimo/reader.rb:159:in `parse_dictionary'
/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.1.2/lib/nanaimo/reader.rb:98:in `parse_object'
/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.1.2/lib/nanaimo/reader.rb:159:in `parse_dictionary'
/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.1.2/lib/nanaimo/reader.rb:98:in `parse_object'
/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.1.2/lib/nanaimo/reader.rb:73:in `parse!'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.0/lib/xcodeproj/plist.rb:27:in `read_from_path'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.0/lib/xcodeproj/project.rb:200:in `initialize_from_file'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.0/lib/xcodeproj/project.rb:102:in `open'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:855:in `block (2 levels) in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:854:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:854:in `block in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:849:in `inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:66:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:236:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:150:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:149:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:110:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command/install.rb:37:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by dyegos** [comment]
Same error is present on 1.2.0.beta.1

**Comment by dyegos** [comment]
The same error happens on `1.2.0.beta.1` version:
```
   CocoaPods : 1.2.0.beta.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.1 (16B2555)
       Xcode : 8.1 (8B62)
         Git : git version 2.10.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ fe5b0a40ae93ce1193c72ecb8393a880094e1131
```

**Comment by dyegos** [comment]
Here are the project config files previous and after the error
[Nanaimo parse error.zip](https://github.com/CocoaPods/CocoaPods/files/566464/Nanaimo.parse.error.zip)

**Comment by segiddins** [comment]
Can you `gem install xcodeproj:1.4.1` and try again? Thanks!

**Comment by dyegos** [comment]
Okay, I'll try it tomorrow

**Comment by GE-N** [comment]
@segiddins I have the same problem with him and tried install `xcodeproj 1.4.1`. It's work :)

**Comment by dyegos** [comment]
@segiddins I worked like a charm. Thank you :)

**Comment by mvalbuquerque** [comment]
i have fixed 

MacBook-Pro-de-Vinicius:bin mvalbuquerque$ sudo gem uninstall nanaimo

Select gem to uninstall:
 1. nanaimo-0.2.2
 2. nanaimo-0.2.3
 3. All versions
> 3
Successfully uninstalled nanaimo-0.2.2

You have requested to uninstall the gem:
	nanaimo-0.2.3

xcodeproj-1.4.1 depends on nanaimo (~> 0.2.0)
If you remove this gem, these dependencies will not be met.
Continue with Uninstall? [yN]  y
Successfully uninstalled nanaimo-0.2.3
MacBook-Pro-de-Vinicius:bin mvalbuquerque$ sudo gem uninstall nanaimo

MacBook-Pro-de-Vinicius:bin mvalbuquerque$ sudo gem install nanaimo
Fetching: nanaimo-0.2.3.gem (100%)
Successfully installed nanaimo-0.2.3
Parsing documentation for nanaimo-0.2.3
Installing ri documentation for nanaimo-0.2.3
1 gem installed
MacBook-Pro-de-Vinicius:bin mvalbuquerque$

**Comment by mobilestar0223** [comment]
I have had same issue, I followed @mvalbuquerque, And it fix my issue and works well. 👍 
Thanks.
