### ISSUE TITLE
Nanaimo::Reader::ParseError - [!] Dictionary missing ';' after key-value pair for "shellScript", found "$"

### ISSUE THREAD

**Issue by aqutam** [CocoaPods/CocoaPods#6129]
### Command

```
/Users/takayukitamura/.rbenv/versions/2.2.2/bin/pod install
```

### Report

* What did you do?
Since I could not Pod install, I did the following.

```
rm -rf ~/.cocoapods
rm -fr ~/Library/Caches/CocoaPods
sudo gem uninstall cocoapods
sudo gem update --system
sudo gem update
sudo gem cleanup
sudo gem install cocoapods --pre
pod setup
```

* What did you expect to happen?
I will expect to be able to have pod install.
* What happened instead?
Failed to pod install.

### Stack

```
   CocoaPods : 1.2.0.beta.1
        Ruby : ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin13]
    RubyGems : 2.6.8
        Host : Mac OS X 10.11.6 (15G1108)
       Xcode : 8.1 (8B62)
         Git : git version 2.7.0
Ruby lib dir : /Users/takayukitamura/.rbenv/versions/2.2.2/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 99cef25b1ff65c04528fda18d69225a92cb69371
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

pre_install do
    system("sed -i '' '/UITextField/d' Pods/BlocksKit/BlocksKit/BlocksKit+UIKit.h")
    system('rm Pods/BlocksKit/BlocksKit/UIKit/UITextField+BlocksKit.h')
    system('rm Pods/BlocksKit/BlocksKit/UIKit/UITextField+BlocksKit.m')
end

def common_pods
  pod 'Appirater'
  pod 'BlocksKit', '~>2.2.5'
  #pod 'JMImageCache'
  pod 'KissXML'
  pod 'NSLogger'
  pod 'Reachability'
  pod 'SVProgressHUD', '1.1'
  pod 'UICKeyChainStore', '~>2.0.4'
  pod 'ZBarSDK', '~>1.3.1'
  pod 'GoogleAnalytics-iOS-SDK', '~>3.0.2'
  pod 'NSHash', '~> 1.0.1'
end

target 'ProjName Dev' do
  common_pods
end

target 'ProjName Staging' do
  common_pods
end

target 'ProjName Enterprise' do
  common_pods
end

target 'ProjName' do
  common_pods
end
```

### Error

```
Nanaimo::Reader::ParseError - [!] Dictionary missing ';' after key-value pair for "shellScript", found "$"
    #  -------------------------------------------
    #  			runOnlyForDeploymentPostprocessing = 0;
    #  			shellPath = /bin/sh;
6502>  			shellScript = "echo \"codesign --verify --force --sign \\"$CODE_SIGN_IDENTITY\\" \\"$CODESIGNING_FOLDER_PATH\\"\"\nIDENTITIES=`security find-identity -v -s \"Code Signing\" | grep \"iPhone Developer\" | awk \'{ print $2 }\'`\n\n\nfor SHA in $IDENTITIES; do\ncodesign --verify --force --sign $SHA \"$CODESIGNING_FOLDER_PATH\"\nif [ $? -eq 0 ]; then\necho \"Matching identity found: $SHA\"\nexit 0\nfi\ndone;\n\nexit 1";
                                                                    ^
    #  		};
    #  		BF3EA46A199235E2004A09C8 /* ShellScript */ = {
    #  -------------------------------------------

/Users/takayukitamura/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/nanaimo-0.2.0/lib/nanaimo/reader.rb:277:in `raise_parser_error'
/Users/takayukitamura/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/nanaimo-0.2.0/lib/nanaimo/reader.rb:191:in `parse_dictionary'
/Users/takayukitamura/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/nanaimo-0.2.0/lib/nanaimo/reader.rb:124:in `parse_object'
/Users/takayukitamura/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/nanaimo-0.2.0/lib/nanaimo/reader.rb:185:in `parse_dictionary'
/Users/takayukitamura/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/nanaimo-0.2.0/lib/nanaimo/reader.rb:124:in `parse_object'
/Users/takayukitamura/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/nanaimo-0.2.0/lib/nanaimo/reader.rb:185:in `parse_dictionary'
/Users/takayukitamura/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/nanaimo-0.2.0/lib/nanaimo/reader.rb:124:in `parse_object'
/Users/takayukitamura/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/nanaimo-0.2.0/lib/nanaimo/reader.rb:99:in `parse!'
/Users/takayukitamura/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/xcodeproj-1.4.1/lib/xcodeproj/plist.rb:27:in `read_from_path'
/Users/takayukitamura/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/xcodeproj-1.4.1/lib/xcodeproj/project.rb:200:in `initialize_from_file'
/Users/takayukitamura/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/xcodeproj-1.4.1/lib/xcodeproj/project.rb:102:in `open'
/Users/takayukitamura/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer.rb:516:in `block (2 levels) in deintegrate_if_different_major_version'
/Users/takayukitamura/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer.rb:516:in `map'
/Users/takayukitamura/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer.rb:516:in `block in deintegrate_if_different_major_version'
/Users/takayukitamura/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/takayukitamura/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer.rb:515:in `deintegrate_if_different_major_version'
/Users/takayukitamura/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer.rb:132:in `block in prepare'
/Users/takayukitamura/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/user_interface.rb:142:in `message'
/Users/takayukitamura/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer.rb:131:in `prepare'
/Users/takayukitamura/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer.rb:109:in `install!'
/Users/takayukitamura/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/command/install.rb:37:in `run'
/Users/takayukitamura/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Users/takayukitamura/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/command.rb:50:in `run'
/Users/takayukitamura/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.2.0.beta.1/bin/pod:55:in `<top (required)>'
/Users/takayukitamura/.rbenv/versions/2.2.2/bin/pod:22:in `load'
/Users/takayukitamura/.rbenv/versions/2.2.2/bin/pod:22:in `<main>'
```

**Comment by segiddins** [comment]
`gem install nanaimo:0.2.2` should fix things!

**Comment by TosinAF** [comment]
Having same issue and the above didnt work :(

**Comment by segiddins** [comment]
@TosinAF please share the error template you encountered?

**Comment by TosinAF** [comment]
Analyzing dependencies

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.2.0.beta.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.6 (15G1108)
       Xcode : 8.1 (8B62)
         Git : git version 2.9.3 (Apple Git-75)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ baad1d4e667339325a32b7948ef1a51812f6f625
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs'

use_frameworks!

platform :ios, '10.0'

def development_pods
    pod 'TiaAPI', :path => './Tia/Development Pods/TiaAPI'
    pod 'TiaCore', :path => './Tia/Development Pods/TiaCore'
end

def external_pods
    pod 'Typist', :git => 'https://github.com/totocaster/Typist.git', :commit => 'e2e5b05'
    pod 'UIView+Shimmer'
    pod 'Anchorage', '3.0'
    pod 'BrightFutures', '5.0.1'
    pod 'Localize-Swift', '1.6'
    pod 'SwiftyBeaver', '1.0.3'
    pod 'Kingfisher', '3.1.4'
    pod 'Cartography', '1.0'
    pod 'Socket.IO-Client-Swift', '8.1.2'
    pod 'SGNavigationProgress', '1.2'
    pod 'MXSegmentedPager'
    pod 'Reveal-SDK', :configurations => ['Debug']
end

target 'Tia' do
    development_pods
    external_pods
end
```

### Error

```
LoadError - cannot load such file -- nanaimo
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.1/lib/xcodeproj/plist.rb:23:in `read_from_path'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.1/lib/xcodeproj/project.rb:200:in `initialize_from_file'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.1/lib/xcodeproj/project.rb:102:in `open'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer/analyzer.rb:855:in `block (2 levels) in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer/analyzer.rb:854:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer/analyzer.rb:854:in `block in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer/analyzer.rb:849:in `inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer/analyzer.rb:66:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer.rb:236:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer.rb:150:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer.rb:149:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer.rb:110:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/command/install.rb:37:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=cannot+load+such+file+--+nanaimo&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
 - LoadError - cannot load such file -- nanaimo
   https://github.com/CocoaPods/CocoaPods/issues/6214 [open] [9 comments]
   a week ago

 - pod lib create fails: uninitialized constant Nanaimo::Reader::StringScanner (NameError)
   https://github.com/CocoaPods/CocoaPods/issues/6106 [closed] [14 comments]
   4 weeks ago

**Comment by segiddins** [comment]
Your issue looks like https://github.com/CocoaPods/CocoaPods/issues/6214 rather than this issue

**Comment by segiddins** [comment]
Closing due to lack of response from the OP.

**Comment by MarcSteven** [comment]
@segiddins  The issue is still existing, today I met the weird issues

**Comment by HugoRamonPereira** [comment]
I am having this in 2024...
