### ISSUE TITLE
Not able to install pod on Xcode 7.3.1

### ISSUE THREAD

**Issue by vishal91** [CocoaPods/CocoaPods#6135]
# Report

## What did you do?
 Run `pod install`
on Mac Siera for Xcode 7.3.1 , Swift 2.2

## What did you expect to happen?
Install all pod dependencies correctly.
It was working fine till yesterday. 
## What happened instead?

```
[!] An error occurred while processing the post-install hook of the Podfile.

undefined method `project' for #<Pod::Installer:0x007ffd39173d40>

User/Documents/tinyowl-ios/Podfile:35:in `block (2 levels) in from_ruby'
User/.rvm/gems/ruby-2.0.0-p648/gems/cocoapods-core-1.1.1/lib/cocoapods-core/podfile.rb:179:in `call'
User/.rvm/gems/ruby-2.0.0-p648/gems/cocoapods-core-1.1.1/lib/cocoapods-core/podfile.rb:179:in `post_install!'
User/.rvm/gems/ruby-2.0.0-p648/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:668:in `run_podfile_post_install_hook'
User/.rvm/gems/ruby-2.0.0-p648/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:656:in `block in run_podfile_post_install_hooks'
User/.rvm/gems/ruby-2.0.0-p648/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:142:in `message'
User/.rvm/gems/ruby-2.0.0-p648/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:655:in `run_podfile_post_install_hooks'
User/.rvm/gems/ruby-2.0.0-p648/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:181:in `block in generate_pods_project'
User/.rvm/gems/ruby-2.0.0-p648/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'
User/.rvm/gems/ruby-2.0.0-p648/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:178:in `generate_pods_project'
User/.rvm/gems/ruby-2.0.0-p648/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:115:in `install!'
User/.rvm/gems/ruby-2.0.0-p648/gems/cocoapods-1.1.1/lib/cocoapods/command/install.rb:37:in `run'
User/.rvm/gems/ruby-2.0.0-p648/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
User/.rvm/gems/ruby-2.0.0-p648/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
User/.rvm/gems/ruby-2.0.0-p648/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
User/.rvm/gems/ruby-2.0.0-p648/bin/pod:23:in `load'
User/.rvm/gems/ruby-2.0.0-p648/bin/pod:23:in `<main>'
User/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `eval'
User/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `<main>'

```

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [x86_64-darwin15.5.0]
    RubyGems : 2.4.8
        Host : Mac OS X 10.12 (16A323)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.9.2
Ruby lib dir : /Users/vishaldandge/.rvm/rubies/ruby-2.0.0-p648/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ c7c8e5dbd160993d3c7e85573a658f5d78469686
```

### Installation Source

```
Executable Path: /Users/vishaldandge/.rvm/gems/ruby-2.0.0-p648/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
platform :ios, "8.0"

inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'

pod 'Paytm-iOS-SDK', :git => 'git@github.com:Flutterbee/Paytm-iOS-SDK.git'
# paytm sdk contains compiled reachability so it is disabled
# pod 'Reachability', '~> 3.1'
pod 'RestKit', :git => 'https://github.com/Flutterbee/RestKit.git', :tag => 'tny_v0.23.3'
pod 'MagicalRecord', '2.2'
pod 'AFHTTPRequestOperationLogger', '1.0.0'
pod 'SDWebImage', '~>3.6'
pod 'SDWebImage/WebP', '~>3.6'
pod 'MBProgressHUD', '~> 0.8'
pod 'JRSwizzle', '~> 1.0'
pod 'Mixpanel', :git => 'https://github.com/Flutterbee/mixpanel-iphone.git', :tag => 'tny_v2.6.2'
pod 'MultiDelegate'
pod 'FLAnimatedImage', '~> 1.0'
pod 'PayU-iOS-SDK', :git => 'https://github.com/Flutterbee/PayU-iOS-SDK.git', :tag => 'tny_v2.2.2'
pod 'Fabric'
pod 'Crashlytics'
pod 'Helpshift', '~> 5.3.0-support'
pod 'Branch'
pod 'GoogleMaps'
pod 'FirebaseMessaging', '~> 1.1'
pod 'GoogleConversionTracking', '~> 3.4.0'
target :TinyOwlTests do
    pod 'OCMockito' , '~> 1.0'
    pod 'MagicalRecord', '2.2'
end

post_install do |installer_representation|
    installer_representation.project.targets.each do |target|
        if target.name == 'Pods-TinyOwl-Appboy-iOS-SDK'
            target.build_configurations.each do |config|
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'ABK_ENABLE_IDFA_COLLECTION=1'
            end
        end
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end
```

**Comment by orta** [comment]
The source code for your post install hook is crashing, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
