### ISSUE TITLE
NameError - uninitialized constant Informative @ libs/cocoapods/sources_manager.rb:168:in `const_missing'

### ISSUE THREAD

**Issue by justinseanmartin** [CocoaPods/CocoaPods#6140]
🌈  Searched and there wasn't any prior issue logged with this call stack. Also bumped to the latest released version, and seeing the same thing in 1.2.0.beta.1 as well.

### Command

```
/Users/jmartin/.rvm/gems/ruby-2.1.3/bin/pod install
```

### Report

* What did you do?
I was making some changes to our Podfile around importing subspecs. The dependency podspec has subspecs that are defined as:

```
  s.default_subspec = 'Core'

  s.subspec 'Core' do |core|
    core.source_files = 'Source/Core/**/*.{h,m}'
    mock.private_header_files = 'Source/Core/**/Internal/**/*.{h}'
  end

  s.subspec 'Subspec' do |mock|
    mock.dependency 'Dependency/Core'
    mock.source_files = 'Source/Subspec/**/*.{h,m}'
    mock.private_header_files = 'Source/Subspec/**/Internal/**/*.{h}'
  end

  s.subspec 'Tests' do |tests|
    tests.dependency 'Dependency/Subspec'
    tests.framework = 'XCTest'
    tests.source_files = 'Tests/**/*.{h,m}'
  end
```

I'm adding it to our Podfile like:

```
target 'App' do
  project 'App.xcodeproj'
  pod 'Dependency', path: 'Frameworks/Dependency/Dependency.podspec'
  pod 'Dependency/Subspec', path: 'Frameworks/Dependency/Dependency.podspec', configuration: ['Debug']
end

target 'TestApp' do
  project 'TestApp.xcodeproj'
  pod 'Dependency/Tests', path: 'Frameworks/Dependency/Dependency.podspec'
end
```

* What did you expect to happen?
Should pod install, with `Core` linked into Release & Debug configs, `Subspec` linked into the Debug config, and `Tests` linked into the `TestApp` only

* What happened instead?
It throws the below exception.

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.1.3p242 (2014-09-19 revision 47630) [x86_64-darwin14.0]
    RubyGems : 2.4.8
        Host : Mac OS X 10.11.6 (15G1004)
       Xcode : 8.0 (8A218a)
         Git : git version 2.9.0
Ruby lib dir : /Users/jmartin/.rvm/rubies/ruby-2.1.3/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 5731c5a76110308ea05985747316f46254fb6d3a
               Internal - Internal
               Internal - Internal
```

### Plugins

```
cocoapods-check        : 1.0.0
cocoapods-deintegrate  : 1.0.1
cocoapods-dependencies : 1.0.0.beta.1
cocoapods-plugins      : 1.0.0
cocoapods-search       : 1.0.0
cocoapods-stats        : 1.0.0
cocoapods-trunk        : 1.1.1
cocoapods-try          : 1.1.0
```

### Podfile

Can't include the full Podfile here. I'll see if I can get a minimal repro though without having our private pod dependencies if that helps for investigation.

### Error

```
NameError - uninitialized constant Informative
/Users/jmartin/.rvm/gems/ruby-2.1.3/gems/cocoapods-1.1.1/lib/cocoapods/sources_manager.rb:168:in `const_missing'
/Users/jmartin/Development/ios/app/pods_perf.rb:36:in `block in <top (required)>'
/Users/jmartin/.rvm/gems/ruby-2.1.3/gems/cocoapods-1.1.1/lib/cocoapods/target/aggregate_target.rb:141:in `block in pod_targets_for_build_configuration'
/Users/jmartin/.rvm/gems/ruby-2.1.3/gems/cocoapods-1.1.1/lib/cocoapods/target/aggregate_target.rb:140:in `select'
/Users/jmartin/.rvm/gems/ruby-2.1.3/gems/cocoapods-1.1.1/lib/cocoapods/target/aggregate_target.rb:140:in `pod_targets_for_build_configuration'
/Users/jmartin/.rvm/gems/ruby-2.1.3/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:397:in `block (2 levels) in verify_no_duplicate_framework_and_library_names'
/Users/jmartin/.rvm/gems/ruby-2.1.3/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:396:in `each'
/Users/jmartin/.rvm/gems/ruby-2.1.3/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:396:in `block in verify_no_duplicate_framework_and_library_names'
/Users/jmartin/.rvm/gems/ruby-2.1.3/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:395:in `each'
/Users/jmartin/.rvm/gems/ruby-2.1.3/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:395:in `verify_no_duplicate_framework_and_library_names'
/Users/jmartin/.rvm/gems/ruby-2.1.3/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:112:in `install!'
/Users/jmartin/.rvm/gems/ruby-2.1.3/gems/cocoapods-1.1.1/lib/cocoapods/command/install.rb:37:in `run'
/Users/jmartin/.rvm/gems/ruby-2.1.3/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Users/jmartin/.rvm/gems/ruby-2.1.3/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/Users/jmartin/.rvm/gems/ruby-2.1.3/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/Users/jmartin/.rvm/gems/ruby-2.1.3/bin/pod:23:in `load'
/Users/jmartin/.rvm/gems/ruby-2.1.3/bin/pod:23:in `<main>'
/Users/jmartin/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `eval'
/Users/jmartin/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by justinseanmartin** [comment]
Seems like there are two problems. 

1. Crashing when it should be giving me an error message. I assume the fix there is trivial, but doesn't seem obvious from glancing at the code.
2. Trying to import two different subspecs from the same podspec for different configurations. This seems like it is probably a harder problem and should potentially be broken out into its own separate issue. I'm not sure if this is even intended to work, but it would be helpful at least in this case for us to have some set of debug only functionality that is exposed as a subspec from a library.

**Comment by segiddins** [comment]
What's `pods_perf.rb`? That seems to be where the crash is coming from

**Comment by justinseanmartin** [comment]
I need a :facepalm: emoji, sorry for not noticing that on the stack. Issue 1 above goes away without the CocoaPods modifications file. We just fast tracked a couple of the performance improvements that @dnkoutso put into master before bumping to the official release. The actual error message does appear properly with:

```
[!] The subspecs of `Dependency` are linked to different build configurations for the `Pods-Base-App` target. CocoaPods does not currently support subspecs across different build configurations.
```

From the message, I take this to be totally by design for the moment. Apologies for the randomization.
