### ISSUE TITLE
NoMethodError - undefined method `swift_version=' 

### ISSUE THREAD

**Issue by HamzaGhazouani** [CocoaPods/CocoaPods#6144]
### Command

```
/usr/local/bin/pod trunk push HGCircularSlider.podspec
```

### Report

I tried to publish my new open source library compatible Xcode 7.3 Swift 2.3 https://github.com/HamzaGhazouani/HGCircularSlider
But I get the error below 

### Stack

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.6 (15G31)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 3c1ce906e42018f1ecb383ebbeaab43cccdc3ab6
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Error

```
NoMethodError - undefined method `swift_version=' for #<Pod::Validator:0x007f96f09def70>
/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-1.1.1/lib/pod/command/trunk/push.rb:118:in `validate_podspec'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-1.1.1/lib/pod/command/trunk/push.rb:64:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by benasher44** [comment]
Hi! This kind of Swift version support wasn't added until CocoaPods 1.1.0, and it looks like you're using CocoaPods 1.0. Please update your CocoaPods and file a new issue if you're still experiencing this. Thanks for filing!

**Comment by amberdixon** [comment]
I'm seeing the same issue in cocoapods-1.1.0.rc.2. This is my Gemfile:

```
source 'https://rubygems.org' do
  gem 'cocoapods', '1.1.0.rc.2'
end
```

Here's the error:
```
NoMethodError - undefined method `swift_version=' for #<Pod::Validator:0x007f9e7db8a1f0>
/Users/amberdixon/.rvm/gems/ruby-2.1.3/gems/cocoapods-trunk-1.1.1/lib/pod/command/trunk/push.rb:118:in `validate_podspec'
/Users/amberdixon/.rvm/gems/ruby-2.1.3/gems/cocoapods-trunk-1.1.1/lib/pod/command/trunk/push.rb:64:in `run'
/Users/amberdixon/.rvm/gems/ruby-2.1.3/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Users/amberdixon/.rvm/gems/ruby-2.1.3/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/command.rb:50:in `run'
/Users/amberdixon/.rvm/gems/ruby-2.1.3/gems/cocoapods-1.1.0.rc.2/bin/pod:55:in `<top (required)>'
/Users/amberdixon/.rvm/gems/ruby-2.1.3/bin/pod:23:in `load'
/Users/amberdixon/.rvm/gems/ruby-2.1.3/bin/pod:23:in `<main>'
/Users/amberdixon/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `eval'
/Users/amberdixon/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by amberdixon** [comment]
Actually this works fine for cocoapods-1.1.0 (just not for the 1.1.0.rc.2).
