### ISSUE TITLE
Pod installation error

### ISSUE THREAD

**Issue by nagarajuios** [CocoaPods/CocoaPods#6145]
### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12 (16A323)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 7ba606eaf1e0bd8b062e23440e7fdb7fe793a52e
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.0.beta.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'Example' do
    pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'master'
    
    pod 'SlideMenuControllerSwift', :git => 'https://github.com/dekatotoro/SlideMenuControllerSwift.git', :branch => 'master'
    pod 'Kingfisher',  :git => 'https://github.com/onevcat/Kingfisher', :branch => 'master'
    pod 'CryptoSwift', :git => 'https://github.com/krzyzanowskim/CryptoSwift', :branch => 'master'
    pod 'SpringIndicator', :git => 'https://github.com/KyoheiG3/SpringIndicator.git', :branch => 'master'
    pod 'Glyptodon','~>1.0.10'
    pod 'KVNProgress','~> 2.2'
    pod 'DynamicButton', :git => 'https://github.com/yannickl/DynamicButton.git', :branch => 'master'
    pod 'JVFloatLabeledTextField','~> 1.1'
    pod 'PNChart','~> 0.8'
    pod 'VTAcknowledgementsViewController','~> 0.17'
    pod 'HCSStarRatingView','~> 1.4.5'
    pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'master'
    pod 'libPhoneNumber-iOS', '~> 0.8'
    pod 'DownloadButton','~> 0.1.0'
    pod 'Popover', :git => 'https://github.com/corin8823/Popover.git', :branch => 'swift3.0'
    pod 'Appsee','~> 2.2'
    pod 'Fabric', '~> 1.6.7'
    pod 'Crashlytics','~> 3.7.0'
    pod 'SDWebImage', '~> 3.7'
    pod 'VENTokenField', '~> 2.5'
    pod 'libPusher', '~> 1.6'
    pod 'PusherSwift', :git => 'https://github.com/pusher/pusher-websocket-swift', :branch => 'swift-3'
    pod 'MSCellAccessory', '~> 1.1'
    pod 'MRProgress', '~> 0.8'
    pod 'Intercom', '3.0.11'
    pod 'JSQMessagesViewController', '~> 7.3'
    pod 'UrbanAirship-iOS-SDK','~> 7.0.4'
    pod 'XCGLogger', :git => 'https://github.com/DaveWoodCom/XCGLogger.git', :branch => 'swift_3.0'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
```

### Error

```
NoMethodError - undefined method `source_tree' for #<Xcodeproj::Project::Object::XCBuildConfiguration:0x007f84878b6c68>
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.3.2/lib/xcodeproj/project/object/helpers/groupable_helper.rb:116:in `source_tree_real_path'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.3.2/lib/xcodeproj/project/object/helpers/groupable_helper.rb:100:in `real_path'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.3.2/lib/xcodeproj/project/object/helpers/groupable_helper.rb:121:in `source_tree_real_path'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.3.2/lib/xcodeproj/project/object/helpers/groupable_helper.rb:100:in `real_path'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.3.2/lib/xcodeproj/project/object/file_reference.rb:163:in `real_path'
/Users//.gem/ruby/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:49:in `block (2 levels) in update_to_cocoapods_0_34'
/Users//.gem/ruby/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:46:in `select'
/Users//.gem/ruby/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:46:in `block in update_to_cocoapods_0_34'
/Users//.gem/ruby/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:45:in `each'
/Users//.gem/ruby/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:45:in `update_to_cocoapods_0_34'
/Users//.gem/ruby/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:21:in `block (2 levels) in integrate'
/Users//.gem/ruby/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:20:in `each'
/Users//.gem/ruby/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:20:in `block in integrate'
/Users//.gem/ruby/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:19:in `each'
/Users//.gem/ruby/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:19:in `integrate'
/Users//.gem/ruby/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/user_project_integrator/target_integrator.rb:53:in `block in integrate!'
/Users//.gem/ruby/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/Users//.gem/ruby/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/user_project_integrator/target_integrator.rb:52:in `integrate!'
/Users//.gem/ruby/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/user_project_integrator.rb:129:in `each'
/Users//.gem/ruby/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/user_project_integrator.rb:129:in `integrate_user_targets'
/Users//.gem/ruby/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/user_project_integrator.rb:63:in `integrate!'
/Users//.gem/ruby/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:767:in `block in integrate_user_project'
/Users//.gem/ruby/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/Users//.gem/ruby/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:764:in `integrate_user_project'
/Users//.gem/ruby/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:120:in `install!'
/Users//.gem/ruby/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command/install.rb:37:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Users/-/.gem/ruby/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'
/Users//.gem/ruby/2.0.0/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by benasher44** [comment]
Hi! It looks like you're using CocoaPods 1.0.1 with Xcode 8. Xcode 8 is only supported by at least CocoaPods 1.1.0. Please update your CocoaPods install and file a new issue if you're still experiencing this. Thanks for filing!
