### ISSUE TITLE
Error when running 'try' on google places picker

### ISSUE THREAD

**Issue by MattSich** [CocoaPods/CocoaPods#6150]
### Command

```
/usr/local/bin/pod try GooglePlacePicker
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.2.0.beta.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.6 (15G31)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 135789f3aeb34c80ab3cdb0aaa4bcc7554366e66
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'

target 'GooglePlacePickerDemos' do
    pod 'GooglePlacePicker', '= 2.1.0'
    pod 'GooglePlaces', '= 2.1.0'
    pod 'GoogleMaps', '= 2.1.0'
end
```

### Error

```
Errno::EACCES - Permission denied - /private/var/folders/8l/mw2bscts7c35rvmkd9xrdypn2flh9g/T/CocoaPods/Try/GooglePlacePicker/Example/GooglePlacePickerDemos.xcodeproj/project.pbxproj
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.1/lib/xcodeproj/project.rb:353:in `initialize'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.1/lib/xcodeproj/project.rb:353:in `open'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.1/lib/xcodeproj/project.rb:353:in `save'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer/user_project_integrator.rb:139:in `block in save_projects'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer/user_project_integrator.rb:137:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer/user_project_integrator.rb:137:in `save_projects'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer/user_project_integrator.rb:65:in `integrate!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer.rb:612:in `block in integrate_user_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer.rb:609:in `integrate_user_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer.rb:117:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/command/install.rb:37:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:534:in `invoke'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-try-1.1.0/lib/pod/command/try.rb:238:in `block in perform_cocoapods_installation'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/user_interface.rb:85:in `titled_section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-try-1.1.0/lib/pod/command/try.rb:237:in `perform_cocoapods_installation'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-try-1.1.0/lib/pod/command/try.rb:192:in `block in install_podfile'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-try-1.1.0/lib/pod/command/try.rb:191:in `chdir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-try-1.1.0/lib/pod/command/try.rb:191:in `install_podfile'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-try-1.1.0/lib/pod/command/try.rb:54:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/user_interface.rb:116:in `title'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-try-1.1.0/lib/pod/command/try.rb:49:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by dnkoutso** [comment]
Seems like a permission issue on your .xcodeproj. What are the permissions and does it work on a previous version of cocoapods?

**Comment by DanToml** [comment]
Closing due to lack of activity. If this is still a a problem please file a new issue, including a sample project.
