### ISSUE TITLE
Pod Install error

### ISSUE THREAD

**Issue by EARoa** [CocoaPods/CocoaPods#6157]
### Command

```
/Users/ea_roa/.rbenv/versions/2.3.1/bin/pod install
```

### Report

* **What did you do?** ran `pod install`

* **What did you expect to happen?** My pods would install

* **What happened instead?** horrible things. (jk, just wouldn't install)

### Stack

```
   CocoaPods : 0.39.0
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]
    RubyGems : 2.5.1
        Host : Mac OS X 10.12.1 (16B2657)
       Xcode : 8.1 (8B62)
         Git : git version 2.9.3 (Apple Git-75)
Ruby lib dir : /Users/ea_roa/.rbenv/versions/2.3.1/lib
Repositories : https: -  @ fatal: Not a git repository (or any of the parent directories): .git
               master - https://github.com/CocoaPods/Specs.git @ 6dfca5ec597fc6830c8f470b0e2fa6c6bf910dcd
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-search  : 0.1.0
cocoapods-stats   : 0.6.2
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.5.1
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Planet Tour' do
  pod 'Firebase/Core'
end
```

### Error

```
NoMethodError - undefined method `to_ary' for #<Pod::Specification name="FirebaseAnalytics">
Did you mean?  to_query
/Users/ea_roa/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver/lazy_specification.rb:14:in `method_missing'
/Users/ea_roa/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:64:in `flatten'
/Users/ea_roa/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:64:in `block in resolve'
/Users/ea_roa/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:63:in `tap'
/Users/ea_roa/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:63:in `resolve'
/Users/ea_roa/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:539:in `block in resolve_dependencies'
/Users/ea_roa/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Users/ea_roa/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:537:in `resolve_dependencies'
/Users/ea_roa/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:70:in `analyze'
/Users/ea_roa/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:213:in `analyze'
/Users/ea_roa/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:136:in `block in resolve_dependencies'
/Users/ea_roa/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Users/ea_roa/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:135:in `resolve_dependencies'
/Users/ea_roa/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:105:in `install!'
/Users/ea_roa/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/ea_roa/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:101:in `run'
/Users/ea_roa/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Users/ea_roa/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Users/ea_roa/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/Users/ea_roa/.rbenv/versions/2.3.1/bin/pod:23:in `load'
/Users/ea_roa/.rbenv/versions/2.3.1/bin/pod:23:in `<main>'
```

**Comment by EARoa** [comment]
I reinstalled Cocoapods and it works!
