### ISSUE TITLE
Multiple targets with same name but different case throwing file exists error

### ISSUE THREAD

**Issue by CW-ShubhamJain** [CocoaPods/CocoaPods#6177]
This is how my pod file looks 
```ruby
target 'ABC' do
pod "AFNetworking", ">= 2.0"
pod "SDWebImage", ">=3.5.0"
pod "Google-Mobile-Ads-SDK", "~> 7.0"
pod 'QuickBlox'
pod 'JSQMessagesViewController'
pod 'TWMessageBarManager'
pod 'Fabric'
pod 'Tune'
pod 'Crashlytics'
pod 'Toast', '~> 3.0'
pod 'Appirater'
pod 'Google/SignIn'

#donot update   'JSQMessagesViewController'
#instead use pod install --no-repo-update    after adding your libs

#for updating  use 'pod update SSKeychain'   and update all libs specifically rather that updating all
end

target 'ABCTests' do

end

target 'Abc' do
    end
```
## What did you do?

Updated cocoa pod version from 0.39.0 to 1.0.0
And thus added corresponding changes to the podfile

## What did you expect to happen?

Appropriate cocoa pods upgradation

## What happened instead?
```
Errno::EEXIST - File exists @ dir_s_mkdir - /Users/shubham/Desktop/ABC-ios/Pods/Target Support Files/Pods-ABC
/Users/shubham/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-1.1.1/lib/cocoapods/installer/xcode/pods_project_generator/target_installer.rb:92:in `mkdir'
/Users/shubham/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-1.1.1/lib/cocoapods/installer/xcode/pods_project_generator/target_installer.rb:92:in `mkdir'
/Users/shubham/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-1.1.1/lib/cocoapods/installer/xcode/pods_project_generator/target_installer.rb:92:in `create_support_files_dir'
/Users/shubham/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-1.1.1/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:16:in `block in install!'
/Users/shubham/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:142:in `message'
/Users/shubham/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-1.1.1/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:14:in `install!'
/Users/shubham/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-1.1.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:160:in `block (2 levels) in install_libraries'
/Users/shubham/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-1.1.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:158:in `each'
/Users/shubham/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-1.1.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:158:in `block in install_libraries'
/Users/shubham/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:142:in `message'
/Users/shubham/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-1.1.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:152:in `install_libraries'
/Users/shubham/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-1.1.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:64:in `generate!'
/Users/shubham/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:179:in `block in generate_pods_project'
/Users/shubham/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/shubham/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:178:in `generate_pods_project'
/Users/shubham/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:115:in `install!'
/Users/shubham/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-1.1.1/lib/cocoapods/command/install.rb:37:in `run'
/Users/shubham/.rvm/gems/ruby-2.1.2@global/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Users/shubham/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/Users/shubham/.rvm/gems/ruby-2.1.2@global/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/Users/shubham/.rvm/rubies/ruby-2.1.2/bin/pod:23:in `load'
/Users/shubham/.rvm/rubies/ruby-2.1.2/bin/pod:23:in `<main>'
/Users/shubham/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
/Users/shubham/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
```
## CocoaPods Environment

ℹ Please replace this with the output of `pod env`.

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin13.0]
    RubyGems : 2.4.8
        Host : Mac OS X 10.11.6 (15G1004)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /Users/shubham/.rvm/rubies/ruby-2.1.2/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 0fa32b76caf5c96df053beb27b57b6f426920527

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

**Comment by orta** [comment]
Can you please provide an example project

**Comment by DanToml** [comment]
Closing due to lack of activity - If this is still a bug please file a new issue with a sample project.
