### ISSUE TITLE
Pod spec lint fails after upgrade from 0.39.0 to 1.1.1 of pod that uses static library with --use-libraries

### ISSUE THREAD

**Issue by dodongo** [CocoaPods/CocoaPods#6188]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

Trying to migrate our pod from cocoapods 0.39.0 to 1.1.1 stable, and encountering issues linting it which is blocking us from releasing new versions. It appears that during linting, cocoapods now tries to link our library to architectures that it does not support. Seems perhaps related to https://github.com/CocoaPods/CocoaPods/issues/5854, though we're not using dynamic frameworks.

## What did you do?

Run `pod spec lint --allow-warnings --use-libraries --verbose`

## What did you expect to happen?

Podspec validates successfully, which was the behavior of cocoapods 0.39.0

## What happened instead?

Validation fails with:

```
** BUILD FAILED **

The following build commands failed:
	Ld /Users/dongaxho/Library/Developer/Xcode/DerivedData/App-drrvrgrpwpaccheaatfefpntfhbh/Build/Intermediates/App.build/Release-iphonesimulator/App.build/Objects-normal/i386/App normal i386
	Ld /Users/dongaxho/Library/Developer/Xcode/DerivedData/App-drrvrgrpwpaccheaatfefpntfhbh/Build/Intermediates/App.build/Release-iphonesimulator/App.build/Objects-normal/x86_64/App normal x86_64
(2 failures)
 -> LevelUpSDK (1.12.0)
    - ERROR | [LevelUpSDK/Core,LevelUpSDK/Testing] xcodebuild: Returned an unsuccessful exit code.
    - WARN  | [LevelUpSDK/Core] xcodebuild:  ZXingObjC/ZXingObjC/client/ZXCapture.m:99:20: warning: assigning to 'id<CALayerDelegate> _Nullable' from incompatible type 'ZXCapture *const __strong'
    - NOTE  | [LevelUpSDK/Core,LevelUpSDK/Testing] xcodebuild:  clang: error: linker command failed with exit code 1 (use -v to see invocation)
    - WARN  | [LevelUpSDK/Testing] xcodebuild:  OHHTTPStubs/OHHTTPStubs/OHHTTPStubs.m:190:2: warning: This code uses a private method: use only for you app testing. Don't use OHHTTPStubs when publishing your app on the App Store. [-W#warnings]

Analyzed 1 podspec.

[!] The spec did not pass validation, due to 1 error.

/Users/dongaxho/.rvm/gems/ruby-2.1.4/gems/cocoapods-1.1.1/lib/cocoapods/command/spec/lint.rb:81:in `run'
/Users/dongaxho/.rvm/gems/ruby-2.1.4/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Users/dongaxho/.rvm/gems/ruby-2.1.4/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/Users/dongaxho/.rvm/gems/ruby-2.1.4/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/Users/dongaxho/.rvm/gems/ruby-2.1.4/bin/pod:23:in `load'
/Users/dongaxho/.rvm/gems/ruby-2.1.4/bin/pod:23:in `<main>'
/Users/dongaxho/.rvm/gems/ruby-2.1.4/bin/ruby_executable_hooks:15:in `eval'
/Users/dongaxho/.rvm/gems/ruby-2.1.4/bin/ruby_executable_hooks:15:in `<main>'
```

Linker errors:

```
ld: building for iOS simulator, but linking against dylib built for OSX (/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/lib/libSystem.tbd). file '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/lib/libSystem.tbd' for architecture i386
```

```
ld: building for iOS simulator, but linking against dylib built for OSX (/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/lib/libobjc.tbd). file '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/lib/libobjc.tbd' for architecture x86_64
```

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.1.4p265 (2014-10-27 revision 48166) [x86_64-darwin14.0]
    RubyGems : 2.4.8
        Host : Mac OS X 10.12.1 (16B2555)
       Xcode : 8.1 (8B62)
         Git : git version 2.6.1
Ruby lib dir : /Users/dongaxho/.rvm/rubies/ruby-2.1.4/lib
Repositories : cocoapods - https://github.com/CocoaPods/Old-Specs.git @ 6e256ccc84aad851d401fabb79b2c0f9e09bb875
               master - https://github.com/CocoaPods/Specs.git @ 41808e2fb0dcdead1707dd5eea67c9c4469970e2
```

### Installation Source

```
Executable Path: /Users/dongaxho/.rvm/gems/ruby-2.1.4/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-deploy      : 0.0.10
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Old-Specs.git'

platform :ios, '8.0'

target 'Testing App' do
  pod 'AFNetworking/NSURLConnection', '2.6.1'
  pod 'LUKeychainAccess', '1.2.3'
  pod 'ZXingObjC/QRCode', '3.0.4'

  target 'Tests' do
    inherit! :search_paths
    pod 'Kiwi', '2.4.0'
    pod 'OHHTTPStubs', '1.1.2'
  end

  target 'LevelUpSDK' do
    inherit! :search_paths
  end
end
```

## Project that demonstrates the issue

https://github.com/TheLevelUp/levelup-sdk-ios

**Comment by dnkoutso** [comment]
This is "expected". in 1.0.0 the linter will attempt to link the generated project with the pod. In 0.39.0 it wasn't so you werent seeing this error.

Either fix the error (use `--no-clean` and open the project yourself) or https://github.com/CocoaPods/CocoaPods/pull/5677 must land to allow running lint without linking.

**Comment by dodongo** [comment]
@dnkoutso I had inspected the generated App.workspace, and the error is definitely caused because it's attempting to link the static library to the unsupported x86_64 and i386 architectures. Even if we were to generate a static library that includes slices for the missing architectures, I think these would prevent dependent apps from being submitted to the app store. Would love some guidance on how static library pods usually get around this issue.

**Comment by dnkoutso** [comment]
If you are shipping a pod with a pre-built vendored static lib you should probably ship the "fat" version with all architectures included. 

Xcode is smart enough to `lipo -thin` (http://ss64.com/osx/lipo.html) the lib depending on what architecture its building for.

Otherwise, I am out of ideas, again #5677 might be what you need for this case, which seems to be valid.

**Comment by dnkoutso** [comment]
@dodongo I am closing this since the new `--skip-import-validation` is now an option.
