### ISSUE TITLE
pod repo update fails

### ISSUE THREAD

**Issue by dlo** [CocoaPods/CocoaPods#6190]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

pod repo update --verbose

## What did you expect to happen?

The local pod spec Git repo should update.

## What happened instead?

Ruby crashes with the following traceback.

```
$ pod repo update --verbose

Updating spec repo `master`
  $ /usr/local/bin/git -C /Users/dan/.cocoapods/repos/master pull --ff-only
  error: Cannot pull with rebase: You have unstaged changes.
[!] CocoaPods was not able to update the `master` repo. If this is an unexpected issue and persists you can inspect it running `pod repo update --verbose`

/Users/dan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/sources_manager.rb:110:in `rescue in update_git_repo'
/Users/dan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/sources_manager.rb:106:in `update_git_repo'
/Users/dan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/sources_manager.rb:124:in `update_git_repo'
/Users/dan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-core-1.1.1/lib/cocoapods-core/source.rb:334:in `update'
/Users/dan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-core-1.1.1/lib/cocoapods-core/master_source.rb:15:in `update'
/Users/dan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/sources_manager.rb:88:in `block (2 levels) in update'
/Users/dan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/dan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/sources_manager.rb:87:in `block in update'
/Users/dan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/sources_manager.rb:86:in `each'
/Users/dan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/sources_manager.rb:86:in `update'
/Users/dan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/command/repo/update.rb:23:in `run'
/Users/dan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Users/dan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/Users/dan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.12.1 (16B2555)
       Xcode : 8.1 (8B62)
         Git : git version 2.10.2
Ruby lib dir : /Users/dan/.rbenv/versions/2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 0fba74284883418d8eacd92e86158f62a0d14d76
               wepay - git@github.com:wepay/mobile-podspecs.git @ 277fce1c76ad03b4063800cea89e041ac1a7d12e
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-playgrounds : 1.2.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

**Comment by dnkoutso** [comment]
Can you `cd ~/.cocoapods/repos/master` and do a `git status` there? Seems like the repo in your machine is in a bad state. `git checkout .` will also reset things out and you should re-run the command.

Uncertain how the repo got in a bad state though...

**Comment by dnkoutso** [comment]
Can you `cd ~/.cocoapods/repos/master` and do a `git status` there? Seems like the repo in your machine is in a bad state. `git checkout .` will also reset things out and you should re-run the command.

Uncertain how the repo got in a bad state though...

**Comment by dlo** [comment]
Weird. Just ran git status.

```
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit (use -u to show untracked files)
```

But then ran `pod repo update` again, and it worked? ¯\_(ツ)_/¯

If there was an issue, looks like it resolved itself.

**Comment by keshiim** [comment]
I can`t fix it yet(╯﹏╰)
