### ISSUE TITLE
Internal server error occurred when publishing podspec

### ISSUE THREAD

**Issue by morou** [CocoaPods/CocoaPods#6200]
# Report
Failed to publish my podspec with following error.

```
[!] An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later.
```

## What did you do?

`pod trunk push Repro.podspec`

## What did you expect to happen?

My new pod (Repro 2.1.12) is published.

## What happened instead?

Got following error.

```
opening connection to trunk.cocoapods.org:443...
opened
starting SSL for trunk.cocoapods.org:443...
SSL established
<- "POST /api/v1/pods?allow_warnings=false HTTP/1.1\r\nContent-Type: application/json; charset=utf-8\r\nAccept: application/json; charset=utf-8\r\nUser-Agent: CocoaPods/1.0.0\r\nAuthorization: Token ae7aeff1707b65ab00943eca46b4f399\r\nAccept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3\r\nHost: trunk.cocoapods.org\r\nContent-Length: 928\r\n\r\n"
<- "{\"name\":\"Repro\",\"version\":\"2.1.12\",\"summary\":\"Repro is a mobile analytics tool that lets you have much deeper understanding of mobile app users with play-by-play videos.\",\"homepage\":\"https://repro.io/\",\"license\":{\"type\":\"Copyright\",\"text\":\"(c) 2015 Repro Inc.\"},\"authors\":{\"Repro\":\"support@repro.io\"},\"social_media_url\":\"https://twitter.com/reproio\",\"source\":{\"git\":\"https://github.com/reproio/repro-ios-sdk.git\",\"tag\":\"2.1.12\"},\"documentation_url\":\"http://docs.repro.io\",\"platforms\":{\"ios\":null},\"requires_arc\":true,\"public_header_files\":\"Repro.embeddedframework/Repro.framework/Headers/*.h\",\"source_files\":\"Repro.embeddedframework/Repro.framework/Headers/*.h\",\"vendored_frameworks\":\"Repro.embeddedframework/Repro.framework\",\"resources\":\"Repro.embeddedframework/Resources/ReproSDKResources.bundle\",\"frameworks\":[\"AVFoundation\",\"CoreMedia\",\"CoreTelephony\",\"MobileCoreServices\",\"Security\",\"SystemConfiguration\"],\"libraries\":\"z\"}\n"
-> "HTTP/1.1 500 Internal Server Error\r\n"
-> "Date: Fri, 18 Nov 2016 02:04:27 GMT\r\n"
-> "Connection: keep-alive\r\n"
-> "Strict-Transport-Security: max-age=31536000\r\n"
-> "Content-Type: application/json\r\n"
-> "Content-Length: 141\r\n"
-> "X-Content-Type-Options: nosniff\r\n"
-> "Server: thin 1.6.2 codename Doc Brown\r\n"
-> "Via: 1.1 vegur\r\n"
-> "\r\n"
reading 141 bytes...
-> "{\"error\":\"An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later.\"}"
read 141 bytes
Conn keep-alive
[!] An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later.

/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-1.0.0/lib/pod/command/trunk.rb:70:in `print_error'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-1.0.0/lib/pod/command/trunk.rb:30:in `request_url'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-1.0.0/lib/pod/command/trunk.rb:36:in `request_path'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-1.0.0/lib/pod/command/trunk/push.rb:70:in `push_to_trunk'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-1.0.0/lib/pod/command/trunk/push.rb:62:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

### Stack

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.6.4
        Host : Mac OS X 10.11.6 (15G1108)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.10.1
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 8532b73b2869f30b7dfe0f26a4531554675ea723
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

**Comment by morou** [comment]
And now, failed to open my page `https://cocoapods.org/pods/Repro` with Internal Server Error(500).

**Comment by devedbox** [comment]
The same problem happened to me.

**Comment by segiddins** [comment]
Being tracked at https://github.com/CocoaPods/trunk.cocoapods.org/issues/207.
