### ISSUE TITLE
NoMethodError - undefined method `swift_version=' for #<Pod::Validator:

### ISSUE THREAD

**Issue by tingxins** [CocoaPods/CocoaPods#6209]
### Error

```
NoMethodError - undefined method `swift_version=' for #<Pod::Validator:0x007febdf99c3e8>
/Users/xxxxxx/.rvm/gems/ruby-2.2.2@global/gems/cocoapods-trunk-1.1.1/lib/pod/command/trunk/push.rb:118:in `validate_podspec'
/Users/xxxxxx/.rvm/gems/ruby-2.2.2@global/gems/cocoapods-trunk-1.1.1/lib/pod/command/trunk/push.rb:64:in `run'
/Users/xxxxxx/.rvm/gems/ruby-2.2.2@global/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Users/xxxxxx/.rvm/gems/ruby-2.2.2@global/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'
/Users/xxxxxx/.rvm/gems/ruby-2.2.2@global/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
/Users/xxxxxx/.rvm/rubies/ruby-2.2.2/bin/pod:23:in `load'
/Users/xxxxxx/.rvm/rubies/ruby-2.2.2/bin/pod:23:in `<main>'
/Users/xxxxxx/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
/Users/xxxxxx/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'
```
I'm making a cocoaPods. When I exes `pod trunk push xxx.podspec. This error occurred. Can anyone helps me? What's the problem above? swift-version? But I never used any swift in my project.

**Comment by DanToml** [comment]
`gem uninstall cocoapods-trunk && gem install cocoapods-trunk --version '1.0.0'` should fix this temporarily. Although we should check to see if the Validator has swift_version here: https://github.com/CocoaPods/cocoapods-trunk/blob/master/lib/pod/command/trunk/push.rb#L118.

**Comment by tingxins** [comment]
get it. thanks
