### ISSUE TITLE
CocoaPods was not able to update the `master` repo.

### ISSUE THREAD

**Issue by DavidHuang61** [CocoaPods/CocoaPods#6236]
# Report

## What did you do?
Run 'pod repo update'

## What did you expect to happen?
Update success !

## What happened instead?
[!] CocoaPods was not able to update the `master` repo. If this is an unexpected issue and persists you can inspect it running `pod repo update --verbose`

![image](https://cloud.githubusercontent.com/assets/17465541/20591768/3b837e68-b265-11e6-9951-345feeab634b.png)
![image](https://cloud.githubusercontent.com/assets/17465541/20591795/521561fa-b265-11e6-82a8-e4745ad61929.png)
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/sources_manager.rb:110:in 'rescue in update_git_repo'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/sources_manager.rb:106:in 'update_git_repo'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/sources_manager.rb:124:in 'update_git_repo'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-core-1.1.1/lib/cocoapods-core/source.rb:334:in 'update'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-core-1.1.1/lib/cocoapods-core/master_source.rb:15:in 'update'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/sources_manager.rb:88:in 'block (2 levels) in update'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in 'section'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/sources_manager.rb:87:in 'block in update'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/sources_manager.rb:86:in 'each'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/sources_manager.rb:86:in 'update'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/command/repo/update.rb:23:in 'run'
/usr/local/lib/ruby/gems/2.3.0/gems/claide-1.0.1/lib/claide/command.rb:334:in 'run'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in 'run'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/bin/pod:55:in '<top (required)>'
/usr/local/bin/pod:22:in 'load'
/usr/local/bin/pod:22:in '\<main\>'

**Comment by DavidHuang61** [comment]
已经解决了， 合并冲突问题， 删除了本地的master后，重新 pod setup 后解决问题。
