### ISSUE TITLE
Error when installing pods

### ISSUE THREAD

**Issue by nicwhitts** [CocoaPods/CocoaPods#6246]
# Report

## What did you do?

Run pod install --verbose

## What did you expect to happen?

Install all pod dependencies correctly.

## What happened instead?

Produced error:

```
pod install --verbose
  Preparing
Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]

Setting up CocoaPods master repo
  $ /usr/local/bin/git remote set-url origin
  https://github.com/CocoaPods/Specs.git
  $ /usr/local/bin/git checkout master
  Already on 'master'
Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
[!] Unable to add a source with url `https://github.com/CocoaPods/Specs.git` named `master-1`.
(The `master` repo is not a git repo.)
You can try adding it manually in `~/.cocoapods/repos` or via `pod repo add`.

/Users/Nic/.rvm/gems/ruby-2.2.3/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/sources_manager.rb:35:in `rescue in find_or_create_source_with_url'
/Users/Nic/.rvm/gems/ruby-2.2.3/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/sources_manager.rb:38:in `find_or_create_source_with_url'
/Users/Nic/.rvm/gems/ruby-2.2.3/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer/analyzer.rb:814:in `block in sources'
/Users/Nic/.rvm/gems/ruby-2.2.3/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer/analyzer.rb:813:in `map'
/Users/Nic/.rvm/gems/ruby-2.2.3/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer/analyzer.rb:813:in `sources'
/Users/Nic/.rvm/gems/ruby-2.2.3/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer.rb:143:in `resolve_dependencies'
/Users/Nic/.rvm/gems/ruby-2.2.3/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer.rb:110:in `install!'
/Users/Nic/.rvm/gems/ruby-2.2.3/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/command/install.rb:37:in `run'
/Users/Nic/.rvm/gems/ruby-2.2.3/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Users/Nic/.rvm/gems/ruby-2.2.3/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/command.rb:50:in `run'
/Users/Nic/.rvm/gems/ruby-2.2.3/gems/cocoapods-1.2.0.beta.1/bin/pod:55:in `<top (required)>'
/Users/Nic/.rvm/gems/ruby-2.2.3/bin/pod:23:in `load'
/Users/Nic/.rvm/gems/ruby-2.2.3/bin/pod:23:in `<main>'
/Users/Nic/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
/Users/Nic/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
```

### Stack

```
   CocoaPods : 1.2.0.beta.1
        Ruby : ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]
    RubyGems : 2.5.0
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 1.8.4
Ruby lib dir : /Users/Nic/.rvm/rubies/ruby-2.2.3/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 063b02b45af5b27e158bb2854a50f8774ec415ae
```

### Installation Source

```
Executable Path: /Users/Nic/.rvm/gems/ruby-2.2.3/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Project' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'RestKit', '~> 0.24.0'



end
```

I had cocoa pods working this morning but i had an unrelated error when compiling so i uninstalled and re installed. Now i get this error every time!

**Comment by dnkoutso** [comment]
Please update your `git` version. This is already fixed in https://github.com/CocoaPods/CocoaPods/pull/6174

**Comment by nicwhitts** [comment]
Wow 8 hours later and its so simple. After fixing git which wouldn't update.
Thanks.
