### ISSUE TITLE
NoMethodError - undefined method `include?' for true:TrueClass

### ISSUE THREAD

**Issue by bl82** [CocoaPods/CocoaPods#6262]
# Report

## What did you do?

ℹ Please replace this with what you did.  
pod install under Xcode 8 my project with podfile

## What did you expect to happen?

ℹ Please replace this with what you expected to happen.  
Install all pod dependencies correctly.

## What happened instead?

ℹ Please replace this with of what happened instead.  
[!] Oh no, an error occurred.

### Stack

```
   CocoaPods : 1.2.0.beta.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.1 (16B2555)
       Xcode : 8.1 (8B62)
         Git : git version 2.6.3
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 773e44ffe5a9832f4af008cc53a6ede2e3f4b5a0
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.1'

pod use_frameworks!

target 'Votecast' do
pod 'Socket.IO-Client-Swift', '~> 8.1.2' # Or latest version
pod 'Fabric'
pod 'Crashlytics'
pod 'MBProgressHUD', '~> 1.0.0'
end
```

### Error

```
NoMethodError - undefined method `include?' for true:TrueClass
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.2.0.beta.1/lib/cocoapods-core/dependency.rb:141:in `subspec_dependency?'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.2.0.beta.1/lib/cocoapods-core/dependency.rb:188:in `root_name'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer/analyzer.rb:208:in `map'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer/analyzer.rb:208:in `generate_podfile_state'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer/analyzer.rb:70:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer.rb:236:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer.rb:150:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer.rb:149:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer.rb:110:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/command/install.rb:37:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

## CocoaPods Environment

ℹ Please replace this with the output of `pod env`.
### Stack

```
   CocoaPods : 1.2.0.beta.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.1 (16B2555)
       Xcode : 8.1 (8B62)
         Git : git version 2.6.3
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 773e44ffe5a9832f4af008cc53a6ede2e3f4b5a0
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.1'

pod use_frameworks!

target 'Votecast' do
pod 'Socket.IO-Client-Swift', '~> 8.1.2' # Or latest version
pod 'Fabric'
pod 'Crashlytics'
pod 'MBProgressHUD', '~> 1.0.0'
end
```

**Comment by dnkoutso** [comment]
@bl82 Your `Podfile` has `pod use_frameworks!` which breaks things. Please only use `use_frameworks!` instead.

I successfully ran `pod install` after making that change.

**Comment by DanToml** [comment]
Closing due to lack of activity. If this is still a a problem please file a new issue.
