### ISSUE TITLE
Permission Denied - Custom Branch causes git clone to root owned directory

### ISSUE THREAD

**Issue by beatscode** [CocoaPods/CocoaPods#6265]
# Report

## What did you do?
pod update

## What did you expect to happen?
Install specific branch of Koloda git repository.

## What happened instead?
An attempt to git clone to a folder which is owned by root.

```
pod update --verbose
Update all pods
  Preparing

Updating local specs repositories

Updating spec repo `master`

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-Beatflipz`: (``)
  Using `ARCHS` setting to build architectures of target `Pods-BeatflipzTests`: (``)

Finding Podfile changes
  M Koloda
  - Charts
  - FBSDKCoreKit
  - FBSDKLoginKit
  - Google-Mobile-Ads-SDK
  - NSDate+TimeAgo
  - SwiftForms
  - SwiftSpinner
  - ZDCChat

Fetching external sources
-> Pre-downloading: `Koloda` from `git@github.com:Yalantis/Koloda.git`, branch `swift-3`
  $ /usr/local/bin/git ls-remote git@github.com:Yalantis/Koloda.git swift-3
  Permission denied (publickey).
  fatal: Could not read from remote repository.

  Please make sure you have the correct access rights
  and the repository exists.
  [!] Failed: /usr/local/bin/git ls-remote git@github.com:Yalantis/Koloda.git swift-3
 > Git download
 > Git download
     $ /usr/local/bin/git clone git@github.com:Yalantis/Koloda.git /tmp/d20161203-83652-5nw7ck --template= --single-branch --depth 1 --branch swift-3
     Cloning into '/tmp/d20161203-83652-5nw7ck'...
     Permission denied (publickey).
     fatal: Could not read from remote repository.

     Please make sure you have the correct access rights
     and the repository exists.

[!] Error installing Koloda
[!] /usr/local/bin/git clone git@github.com:Yalantis/Koloda.git /tmp/d20161203-83652-5nw7ck --template= --single-branch --depth 1 --branch swift-3

Cloning into '/tmp/d20161203-83652-5nw7ck'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Permission denied (publickey).                                                                                                                                                                                                      [27/17362]
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.


/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/downloader.rb:142:in `rescue in execute_command'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/downloader.rb:140:in `execute_command'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-downloader-1.1.2/lib/cocoapods-downloader/base.rb:154:in `block in executable'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-downloader-1.1.2/lib/cocoapods-downloader/git.rb:79:in `block in clone'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/downloader.rb:173:in `block in ui_sub_action'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/downloader.rb:172:in `ui_sub_action'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-downloader-1.1.2/lib/cocoapods-downloader/git.rb:77:in `clone'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-downloader-1.1.2/lib/cocoapods-downloader/git.rb:45:in `download!'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-downloader-1.1.2/lib/cocoapods-downloader/base.rb:82:in `block in download'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/downloader.rb:157:in `block in ui_action'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/downloader.rb:156:in `ui_action'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-downloader-1.1.2/lib/cocoapods-downloader/base.rb:80:in `download'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/downloader.rb:108:in `download_source'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/downloader.rb:75:in `download_request'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/downloader/cache.rb:171:in `download'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/downloader/cache.rb:154:in `block in uncached_pod'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/downloader/cache.rb:181:in `in_tmpdir'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/downloader/cache.rb:153:in `uncached_pod'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/downloader/cache.rb:33:in `download_pod'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/downloader.rb:42:in `download'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/external_sources/abstract_external_source.rb:114:in `block in pre_download'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/user_interface.rb:85:in `titled_section'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/external_sources/abstract_external_source.rb:112:in `pre_download'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/external_sources/downloader_source.rb:13:in `fetch'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer/analyzer.rb:639:in `fetch_external_source'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer/analyzer.rb:615:in `block (2 levels) in fetch_external_sources'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer/analyzer.rb:614:in `each'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer/analyzer.rb:614:in `block in fetch_external_sources'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer/analyzer.rb:613:in `fetch_external_sources'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer/analyzer.rb:73:in `analyze'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer.rb:236:in `analyze'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer.rb:150:in `block in resolve_dependencies'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer.rb:149:in `resolve_dependencies'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer.rb:110:in `install!'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/command/update.rb:60:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/command.rb:50:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.2.0.beta.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

## CocoaPods Environment
```

### Stack

```
   CocoaPods : 1.2.0.beta.1
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]
    RubyGems : 2.5.2
        Host : Mac OS X 10.12.1 (16B2555)
       Xcode : 8.1 (8B62)
         Git : git version 2.10.2
Ruby lib dir : /usr/local/Cellar/ruby/2.3.3/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 972ce957b854cd4a46d5459d1c19d99e3d767f27
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

target 'Beatflipz' do
pod 'SwiftForms'
pod 'Koloda' , :git => 'git@github.com:Yalantis/Koloda.git', :branch => 'swift-3'
pod 'NSDate+TimeAgo'
pod "SwiftSpinner"
pod "FBSDKCoreKit"
pod "FBSDKLoginKit"
pod 'ZDCChat'
pod 'Google-Mobile-Ads-SDK', '~> 7.0'
pod 'Charts'
end

target 'BeatflipzTests' do

end

post_install do |installer|
    `find Pods -regex 'Pods/pop.*\\.h' -print0 | xargs -0 sed -i '' 's/\\(<\\)pop\\/\\(.*\\)\\(>\\)/\\"\\2\\"/'`
end
```

```

**Comment by beatscode** [comment]
Sorry. Seemed to be caused by missing github ssh key.
