### ISSUE TITLE
How to set Deployment Target of User Project?

### ISSUE THREAD

**Issue by benmarten** [CocoaPods/CocoaPods#6275]
* [x ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I'm trying to set the deployment target of the user_app. I have this in my podfile:

```
pi.pods_project.targets.each do |target|
...
end
But this only loops over the pods_project. I tried a couple of combinations of pi.user_project

```## What did you expect to happen?

I can get a reference to the user_project to set the desired deployment target.

## What happened instead?

[!] An error occurred while processing the post-install hook of the Podfile.

undefined method `user_project' for #<Pod::Installer:0x007ff006c28e10>

/Users/Ben/dev/leanplum/Leanplum/AppleSDK/LeanplumTest/Podfile:33:in `block (3 levels) in from_ruby'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-core-1.1.1/lib/cocoapods-core/podfile.rb:179:in `post_install!'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:668:in `run_podfile_post_install_hook'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:656:in `block in run_podfile_post_install_hooks'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:142:in `message'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:655:in `run_podfile_post_install_hooks'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:181:in `block in generate_pods_project'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:178:in `generate_pods_project'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:115:in `install!'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/command/install.rb:37:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'

## CocoaPods Environment

ℹ Please replace this with the output of `pod env`.

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]
    RubyGems : 2.6.6
        Host : Mac OS X 10.12.1 (16B2555)
       Xcode : 8.1 (8B62)
         Git : git version 2.11.0
Ruby lib dir : /usr/local/Cellar/ruby/2.3.3/lib
Repositories : leanplum - https://github.com/Leanplum/CocoaPods.git @ b4cabb972f2b17ead9e9842943b9d1efcc821751
               master - https://github.com/CocoaPods/Specs.git @ a052bd04abdf2eac88470f7a958f6e1ba4f51f73
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-packager    : 1.4.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
slather               : 2.3.0
```

### Podfile

```ruby
LP_VERSION = ENV['LP_VERSION'] ? ENV['LP_VERSION'] : '1.4.1'
DEPLOYMENT_TARGET = ENV['LP_STATIC'] ? '6.0' : '8.0'

source 'https://github.com/Leanplum/CocoaPods.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'LeanplumTest' do
  platform :ios, DEPLOYMENT_TARGET
  if ENV['SOURCES']
    if ENV['LP_STATIC']
      print("Installing Leanplum using SOURCES/STATIC\n")
    else
      print("Installing Leanplum using SOURCES/DYNAMIC\n")
      use_frameworks!
    end
    pod 'Leanplum-SDK', :path => '../Leanplum-SDK'
    pod 'Leanplum-iOS-Location', :path => '../Leanplum-iOS-Location'
  else
    if ENV['LP_STATIC']
      print("Installing Leanplum using PACKAGED/STATIC\n")
      pod 'Leanplum-iOS-SDK-static', '= ' + LP_VERSION
      pod 'Leanplum-iOS-Location-static', '= ' + LP_VERSION
    else
      print("Installing Leanplum using PACKAGED/DYNAMIC\n")
      use_frameworks!
      pod 'Leanplum-iOS-SDK', '= ' + LP_VERSION
      pod 'Leanplum-iOS-Location', '= ' + LP_VERSION
    end
  end
 
  post_install do |pi|
   
    puts pi.user_project.inspect()

    pi.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        print("Setting Deployment target to: " + DEPLOYMENT_TARGET + "\n")
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = DEPLOYMENT_TARGET
        unless pi.podfile.defined_in_file.read().include? "\nuse_frameworks!\n"
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'LP_STATIC=1'
        end
      end
    end
  end
end
```

**Comment by benasher44** [comment]
Hi @benmarten! Try `pi.aggregate_targets`. There 1 aggregate target per target defined in your Podfile, and there's a property called `user_target` on each of those, since each of those targets in your Podfile could be defined in its own project. If your Podfile only manages targets in a single project, it should be safe to do `pi.aggregate_targets.first.user_project`. Hope this helps!

**Comment by benmarten** [comment]
Awesome! That indeed worked:
```
pi.aggregate_targets.first.user_project.build_configurations.each do |config|
  print("Setting App Deployment target to: " + DEPLOYMENT_TARGET + "\n")
  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = DEPLOYMENT_TARGET
end
```
Thanks @benasher44 :)

**Comment by benasher44** [comment]
No problem! Glad you got it working!
