### ISSUE TITLE
Nanaimo parser error with Pusher, Xcodeproj 1.4.1 and Cocoapods 1.0

### ISSUE THREAD

**Issue by ghost** [CocoaPods/CocoaPods#6296]
## Command

```
/Users/jamescampbell/.gem/ruby/2.3.1/bin/pod install
```

### Report

* What did you do?

Installed the pods

* What did you expect to happen?

For the pods to be installed correctly and for that preprocessor macro to be accepted

* What happened instead?

It crashed :(

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.6 (15G31)
       Xcode : 8.0 (8A218a)
         Git : git version 2.6.3
Ruby lib dir : /Users/jamescampbell/.rubies/ruby-2.3.1/lib
Repositories : artsy - https://github.com/artsy/Specs @ f2334365b5b1a080efa4ded6425001010e5795dd
               master - https://github.com/CocoaPods/Specs.git @ df1662e3c9640a6f37750b99672c76a5ff7483f4
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-packager    : 1.5.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

target 'Aiwip' do
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'libPusher'
    pod 'Harpy'
    pod 'NSDate+TimeAgo'
    pod 'SDWebImage' , :git => 'https://github.com/rs/SDWebImage.git' , :commit => '30e9e0b'
end

target 'AiwipTests' do
    pod 'OCMock'
    pod 'OHHTTPStubs'
    pod 'Expecta'
    pod 'Specta'
end
```

### Error

```
Nanaimo::Reader::ParseError - [!] Array missing ',' in between objects
    #  -------------------------------------------
    #                                   "$(inherited)",
    #                                   "COCOAPODS=1",
2871>                                   "kPTPusherClientLibraryVersion=@\\"1.6\\"",
                                                                           ^
    #                                   "kPTPusherClientLibraryVersion=@\\"1.6\\"",
    #                                   "BETA=1",
    #  -------------------------------------------

/Users/jamescampbell/.gem/ruby/2.3.1/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:284:in `raise_parser_error'
/Users/jamescampbell/.gem/ruby/2.3.1/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:173:in `parse_array'
/Users/jamescampbell/.gem/ruby/2.3.1/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:133:in `parse_object'
/Users/jamescampbell/.gem/ruby/2.3.1/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:192:in `parse_dictionary'
/Users/jamescampbell/.gem/ruby/2.3.1/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:131:in `parse_object'
/Users/jamescampbell/.gem/ruby/2.3.1/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:192:in `parse_dictionary'
/Users/jamescampbell/.gem/ruby/2.3.1/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:131:in `parse_object'
/Users/jamescampbell/.gem/ruby/2.3.1/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:192:in `parse_dictionary'
/Users/jamescampbell/.gem/ruby/2.3.1/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:131:in `parse_object'
/Users/jamescampbell/.gem/ruby/2.3.1/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:192:in `parse_dictionary'
/Users/jamescampbell/.gem/ruby/2.3.1/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:131:in `parse_object'
/Users/jamescampbell/.gem/ruby/2.3.1/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:106:in `parse!'
/Users/jamescampbell/.gem/ruby/2.3.1/gems/xcodeproj-1.4.1/lib/xcodeproj/plist.rb:27:in `read_from_path'
/Users/jamescampbell/.gem/ruby/2.3.1/gems/xcodeproj-1.4.1/lib/xcodeproj/project.rb:200:in `initialize_from_file'
/Users/jamescampbell/.gem/ruby/2.3.1/gems/xcodeproj-1.4.1/lib/xcodeproj/project.rb:102:in `open'
/Users/jamescampbell/.gem/ruby/2.3.1/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:855:in `block (2 levels) in inspect_targets_to_integrate'
/Users/jamescampbell/.gem/ruby/2.3.1/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:854:in `each'
/Users/jamescampbell/.gem/ruby/2.3.1/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:854:in `block in inspect_targets_to_integrate'
/Users/jamescampbell/.gem/ruby/2.3.1/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/jamescampbell/.gem/ruby/2.3.1/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:849:in `inspect_targets_to_integrate'
/Users/jamescampbell/.gem/ruby/2.3.1/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:66:in `analyze'
/Users/jamescampbell/.gem/ruby/2.3.1/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:236:in `analyze'
/Users/jamescampbell/.gem/ruby/2.3.1/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:150:in `block in resolve_dependencies'
/Users/jamescampbell/.gem/ruby/2.3.1/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/jamescampbell/.gem/ruby/2.3.1/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:149:in `resolve_dependencies'
/Users/jamescampbell/.gem/ruby/2.3.1/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:110:in `install!'
/Users/jamescampbell/.gem/ruby/2.3.1/gems/cocoapods-1.1.1/lib/cocoapods/command/install.rb:37:in `run'
/Users/jamescampbell/.gem/ruby/2.3.1/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Users/jamescampbell/.gem/ruby/2.3.1/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/Users/jamescampbell/.gem/ruby/2.3.1/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/Users/jamescampbell/.gem/ruby/2.3.1/bin/pod:23:in `load'
/Users/jamescampbell/.gem/ruby/2.3.1/bin/pod:23:in `<main>'
```

**Comment by segiddins** [comment]
Can you share the project? Thanks!

**Comment by james-aiwip** [comment]
@segiddins  sure I'll need to clean it up first

**Comment by DanToml** [comment]
Closing due to lack of activity - If this is still a bug please file a new issue with a sample project.
