### ISSUE TITLE
Pod install & pod --verbose getting failed

### ISSUE THREAD

**Issue by sonu5** [CocoaPods/CocoaPods#6297]
Building in workspace /Users/nishant/.jenkins/workspace/Pods
[Pods] $ /bin/bash -l /var/folders/zr/24d4y1px36sdm22lgpdt4fs00000gn/T/hudson7203124513906908806.sh
    [33mWARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
    Consider adding the following to ~/.profile:

    export LANG=en_US.UTF-8
    [0m
Analyzing dependencies

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/nishant/.rvm/gems/ruby-2.3.1/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]
    RubyGems : 2.5.1
        Host : Mac OS X 10.12.1 (16B2555)
       Xcode : 8.1 (8B62)
         Git : git version 2.9.3 (Apple Git-75)
Ruby lib dir : /Users/nishant/.rvm/rubies/ruby-2.3.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 887880c530f9c3a1cce4da3549a73d1483c4c851
               twilio - https://github.com/twilio/cocoapod-specs @ 19013b036ef2584fc0fa06b4ed06ff87fe0c58da
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.1'

workspace '*******'
project '*******.xcodeproj'

target 'RJ-HHBranded-Prod' do
        project 'HealthHub.xcodeproj'
pod 'SDWebImage'
pod 'ZXingObjC'
pod 'CocoaLumberjack'
pod 'libPhoneNumber-iOS', '~> 0.8'
pod 'Fabric'
pod 'Crashlytics'
pod 'MagicalRecord'
pod 'AFNetworking','~> 2.5.4'
pod 'JKBigInteger'
pod 'GZIP'
pod 'SAMKeychain'
pod 'OCMock'
end

post_install do |installer_representation|
installer_representation.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
        config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
        end
    end
end
```

### Error

```
ArgumentError - invalid byte sequence in US-ASCII
/Users/nishant/.rvm/gems/ruby-2.3.1/gems/xcodeproj-1.4.1/lib/xcodeproj/plist.rb:84:in `match'
/Users/nishant/.rvm/gems/ruby-2.3.1/gems/xcodeproj-1.4.1/lib/xcodeproj/plist.rb:84:in `match'
/Users/nishant/.rvm/gems/ruby-2.3.1/gems/xcodeproj-1.4.1/lib/xcodeproj/plist.rb:84:in `file_in_conflict?'
/Users/nishant/.rvm/gems/ruby-2.3.1/gems/xcodeproj-1.4.1/lib/xcodeproj/plist.rb:20:in `read_from_path'
/Users/nishant/.rvm/gems/ruby-2.3.1/gems/xcodeproj-1.4.1/lib/xcodeproj/project.rb:200:in `initialize_from_file'
/Users/nishant/.rvm/gems/ruby-2.3.1/gems/xcodeproj-1.4.1/lib/xcodeproj/project.rb:102:in `open'
/Users/nishant/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:855:in `block (2 levels) in inspect_targets_to_integrate'
/Users/nishant/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:854:in `each'
/Users/nishant/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:854:in `block in inspect_targets_to_integrate'
/Users/nishant/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/nishant/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:849:in `inspect_targets_to_integrate'
/Users/nishant/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:66:in `analyze'
/Users/nishant/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:236:in `analyze'
/Users/nishant/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:150:in `block in resolve_dependencies'
/Users/nishant/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/nishant/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:149:in `resolve_dependencies'
/Users/nishant/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:110:in `install!'
/Users/nishant/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.1.1/lib/cocoapods/command/install.rb:37:in `run'
/Users/nishant/.rvm/gems/ruby-2.3.1/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Users/nishant/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/Users/nishant/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/Users/nishant/.rvm/gems/ruby-2.3.1/bin/pod:23:in `load'
/Users/nishant/.rvm/gems/ruby-2.3.1/bin/pod:23:in `<main>'
/Users/nishant/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/Users/nishant/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=invalid+byte+sequence+in+US-ASCII&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
 - Pod install fails on invalid byte sequence while having LANG=en_US.UTF-8 in profile
   https://github.com/CocoaPods/CocoaPods/issues/5780 [closed] [5 comments]
   24 Oct 2016

 - ArgumentError - invalid byte sequence in US-ASCII
   https://github.com/CocoaPods/CocoaPods/issues/5348 [closed] [3 comments]
   18 May 2016

 - Error while setting up CocoaPods
   https://github.com/CocoaPods/CocoaPods/issues/5979 [closed] [21 comments]
   6 weeks ago

and 11 more at:
https://github.com/cocoapods/cocoapods/search?q=invalid%20byte%20sequence%20in%20US-ASCII&type=Issues&utf8=✓
/var/folders/zr/24d4y1px36sdm22lgpdt4fs00000gn/T/hudson7203124513906908806.sh: line 4: shell_session_update: command not found
Build step 'Execute shell' marked build as failure
Finished: FAILURE

**Comment by sonu5** [comment]
Completely choked in this issue.
From jenkins I am trying to do pod install. and it will fails always.

**Comment by axl411** [comment]
Before you run `pod install`, add the following lines:

```
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
```

and try again, see if it works.

**Comment by andre-wolfe** [comment]
@axl411: Thank you. This seemed to fix an issue that caused CocoaPods to direct me here.
