### ISSUE TITLE
【Errno::EACCES - Permission denied @ dir_s_rmdir】  how can i do for this?

### ISSUE THREAD

**Issue by su350380433** [CocoaPods/CocoaPods#6300]
appledeMBP:AgoraFaceU_iOS apple$ pod install
Analyzing dependencies
Downloading dependencies
Installing Masonry (1.0.2)

### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]
    RubyGems : 2.6.7
        Host : Mac OS X 10.12.1 (16B2555)
       Xcode : 8.1 (8B62)
         Git : git version 2.9.3 (Apple Git-75)
Ruby lib dir : /usr/local/Cellar/ruby/2.3.3/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ adfed55c6a5258b586ec05bbf8c25b7b40c4e897
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '7.0'
inhibit_all_warnings! 

target 'OpenLive' do
    pod 'Masonry'
end
```

### Error

```
Errno::EACCES - Permission denied @ dir_s_rmdir - /Users/apple/Library/Caches/CocoaPods/Pods
/usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/fileutils.rb:1445:in `rmdir'
/usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/fileutils.rb:1445:in `block in remove_dir1'
/usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/fileutils.rb:1456:in `platform_support'
/usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/fileutils.rb:1444:in `remove_dir1'
/usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/fileutils.rb:1437:in `remove'
/usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/fileutils.rb:779:in `block in remove_entry'
/usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/fileutils.rb:1494:in `ensure in postorder_traverse'
/usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/fileutils.rb:1494:in `postorder_traverse'
/usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/fileutils.rb:777:in `remove_entry'
/usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/fileutils.rb:635:in `block in rm_r'
/usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/fileutils.rb:631:in `each'
/usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/fileutils.rb:631:in `rm_r'
/usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/pathname.rb:587:in `rmtree'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/downloader/cache.rb:83:in `ensure_matching_version'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/downloader/cache.rb:22:in `initialize'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/downloader.rb:41:in `new'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/downloader.rb:41:in `download'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/pod_source_installer.rb:120:in `download_source'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/pod_source_installer.rb:60:in `install!'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:355:in `install_source_of_pod'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:322:in `block (2 levels) in install_pod_sources'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:85:in `titled_section'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:321:in `block in install_pod_sources'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:313:in `each'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:313:in `install_pod_sources'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:159:in `block in download_dependencies'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:157:in `download_dependencies'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:111:in `install!'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/command/install.rb:37:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

**Comment by dnkoutso** [comment]
As the message says you probably dont have write to `/Users/apple/Library/Caches/CocoaPods/Pods`

**Comment by su350380433** [comment]
I solved the problem by executing the command. sudo rm -r -f /Users/apple/Library/Caches/CocoaPods/

thank
