### ISSUE TITLE
help!   cannot load such file -- nanaimo

### ISSUE THREAD

**Issue by Hanwp** [CocoaPods/CocoaPods#6312]
### Command

```
/Users/hanwei/.rvm/rubies/ruby-2.2.1/bin/pod trunk push TangramKit.podspec
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin15]
    RubyGems : 2.6.6
        Host : Mac OS X 10.12.2 (16C67)
       Xcode : 8.2 (8C38)
         Git : git version 2.7.1
Ruby lib dir : /Users/hanwei/.rvm/rubies/ruby-2.2.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 4183f2eb5da729dac5fa6bd9ca83cf731a943584
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Error

```
LoadError - cannot load such file -- nanaimo
/Users/hanwei/.rvm/gems/ruby-2.2.1/gems/xcodeproj-1.4.1/lib/xcodeproj/project.rb:353:in `block in save'
/Users/hanwei/.rvm/gems/ruby-2.2.1/gems/xcodeproj-1.4.1/lib/xcodeproj/project.rb:353:in `open'
/Users/hanwei/.rvm/gems/ruby-2.2.1/gems/xcodeproj-1.4.1/lib/xcodeproj/project.rb:353:in `save'
/Users/hanwei/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-1.1.1/lib/cocoapods/validator.rb:410:in `create_app_project'
/Users/hanwei/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-1.1.1/lib/cocoapods/validator.rb:298:in `block in perform_extensive_analysis'
/Users/hanwei/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-1.1.1/lib/cocoapods/validator.rb:293:in `each'
/Users/hanwei/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-1.1.1/lib/cocoapods/validator.rb:293:in `perform_extensive_analysis'
/Users/hanwei/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-1.1.1/lib/cocoapods/validator.rb:79:in `validate'
/Users/hanwei/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-trunk-1.1.1/lib/pod/command/trunk/push.rb:119:in `validate_podspec'
/Users/hanwei/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-trunk-1.1.1/lib/pod/command/trunk/push.rb:64:in `run'
/Users/hanwei/.rvm/gems/ruby-2.2.1/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Users/hanwei/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/Users/hanwei/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/Users/hanwei/.rvm/rubies/ruby-2.2.1/bin/pod:22:in `load'
/Users/hanwei/.rvm/rubies/ruby-2.2.1/bin/pod:22:in `<main>'
```

**Comment by Hanwp** [comment]
I soved!   Now I only have nanaimo-0.2.3. It workd for me!
```
hanweideMacBook-Pro:TangramKit hanwei$ gem list | grep nanaimo
nanaimo (0.2.3, 0.2.2, 0.1.2)
hanweideMacBook-Pro:TangramKit hanwei$ gem uninstall nanaimo 0.1.2

Select gem to uninstall:
 1. nanaimo-0.1.2
 2. nanaimo-0.2.2
 3. All versions
> 1
Successfully uninstalled nanaimo-0.1.2
hanweideMacBook-Pro:TangramKit hanwei$ gem uninstall nanaimo 0.2.2
Successfully uninstalled nanaimo-0.2.2
hanweideMacBook-Pro:TangramKit hanwei$ gem list | grep nanaimo
nanaimo (0.2.3)

```

**Comment by manojreddy1** [comment]
worked finally, nanaimo (0.2.3) should work, remove all other nanaimo

**Comment by pallaviMN** [comment]
@manojreddy1 , how to uninstall other nanaimo versions

**Comment by manojreddy1** [comment]
@pallaviMN , gem uninstall nanaimo version no.

**Comment by Praga12** [comment]
ERROR: While executing gem … (Errno::EPERM) Operation not permitted - /usr/bin/pod in Xcode 8 swift 3

**Comment by keronakhla** [comment]
I fixed this issue with running the following

#### [sudo] gem uninstall nanaimo
> Select gem to uninstall:
> 1. nanaimo-0.2.2
> 2. nanaimo-0.2.3
> 3. All versions

I selected 3 to remove all versions, then I ran

#### [sudo] gem install nanaimo
> Fetching: nanaimo-0.2.3.gem (100%)
> Successfully installed nanaimo-0.2.3
> Parsing documentation for nanaimo-0.2.3
> Installing ri documentation for nanaimo-0.2.3
> 1 gem installed

It's working now and back to normal!

**Comment by s612** [comment]
keronakhla - When I choose 3 it shows ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.

**Comment by chibimagic** [comment]
@s612 Make sure you're running the command as sudo
