### ISSUE TITLE
Pod Install gives "NoMethodError - undefined method `files' for #"

### ISSUE THREAD

**Issue by noobiehacker** [CocoaPods/CocoaPods#6320]
# Report

Hello there

I am trying to add the SDK to an existing project.
I realized that whenever I tried to do pod install, cocoapods is giving me a no method error, I tried many different solutions and still no luck :( Help would be appreciated!

## What did you do?
pod setup
pod install

## What did you expect to happen?

Install successfully 

## What happened instead?

Analyzing dependencies
Downloading dependencies
Using box-ios-sdk (1.0.14)
Generating Pods project
Integrating client project

### Command

```
/Users/Davix/.rbenv/versions/2.0.0-p353/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.2.0.beta.1
        Ruby : ruby 2.0.0p353 (2013-11-22 revision 43784) [x86_64-darwin15.3.0]
    RubyGems : 2.6.4
        Host : Mac OS X 10.12.1 (16B2555)
       Xcode : 8.1 (8B62)
         Git : git version 2.9.3 (Apple Git-75)
Ruby lib dir : /Users/Davix/.rbenv/versions/2.0.0-p353/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ fb9cd802992b0625e30072dfdb4b0f0c7af85830
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!
workspace 'MyWorkspace'

target 'IBMCaptureSDK-Sample' do
pod 'box-ios-sdk'
end

target 'IBMCaptureSDK-SampleTests' do
pod 'box-ios-sdk'
end
```

### Error

```
NoMethodError - undefined method `files' for #<Xcodeproj::Project::Object::PBXFileReference:0x007ff788490110>
/Users/Davix/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer/user_project_integrator/target_integrator.rb:93:in `block in add_pods_library'
/Users/Davix/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer/user_project_integrator/target_integrator.rb:88:in `each'
/Users/Davix/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer/user_project_integrator/target_integrator.rb:88:in `add_pods_library'
/Users/Davix/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer/user_project_integrator/target_integrator.rb:60:in `block in integrate!'
/Users/Davix/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/Davix/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer/user_project_integrator/target_integrator.rb:57:in `integrate!'
/Users/Davix/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer/user_project_integrator.rb:129:in `each'
/Users/Davix/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer/user_project_integrator.rb:129:in `integrate_user_targets'
/Users/Davix/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer/user_project_integrator.rb:63:in `integrate!'
/Users/Davix/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer.rb:612:in `block in integrate_user_project'
/Users/Davix/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/Davix/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer.rb:609:in `integrate_user_project'
/Users/Davix/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer.rb:117:in `install!'
/Users/Davix/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/command/install.rb:37:in `run'
/Users/Davix/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Users/Davix/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/command.rb:50:in `run'
/Users/Davix/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/cocoapods-1.2.0.beta.1/bin/pod:55:in `<top (required)>'
/Users/Davix/.rbenv/versions/2.0.0-p353/bin/pod:22:in `load'
/Users/Davix/.rbenv/versions/2.0.0-p353/bin/pod:22:in `<main>'
```

[!] Oh no, an error occurred.

### Stack

```
   CocoaPods : 1.2.0.beta.1
        Ruby : ruby 2.0.0p353 (2013-11-22 revision 43784) [x86_64-darwin15.3.0]
    RubyGems : 2.6.4
        Host : Mac OS X 10.12.1 (16B2555)
       Xcode : 8.1 (8B62)
         Git : git version 2.9.3 (Apple Git-75)
Ruby lib dir : /Users/Davix/.rbenv/versions/2.0.0-p353/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ fb9cd802992b0625e30072dfdb4b0f0c7af85830
```

### Installation Source

```
Executable Path: /Users/Davix/.rbenv/versions/2.0.0-p353/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Project Link

https://github.com/noobiehacker/IBMDatacapDemo

**Comment by dnkoutso** [comment]
Might be a bug in CocoaPods but this is causing the problem:

<img width="292" alt="screen_shot_2016-12-16_at_3_12_30_pm" src="https://cloud.githubusercontent.com/assets/310370/21281496/2cf2d72e-c3a2-11e6-8557-57b660debfa0.png">

If you move it into a subgroup then it works.

**Comment by noobiehacker** [comment]
@dnkoutso Nice it works, thank you, @dnkoutso should I close this issue or do you think theres a bug in cocoapod that should be fixed??

**Comment by dnkoutso** [comment]
Probably keep it open for now as this seems like a bug. In the meantime you should be unblocked. :)

**Comment by benasher44** [comment]
Hi @noobiehacker! How did the Frameworks folder ref get there (as opposed to the Frameworks group ref)?

@dnkoutso This looks like some kind of bug in `XcodeProj::Project#frameworks_group`. Maybe we're not handling this scenario: Frameworks folder and Frameworks group.

**Comment by noobiehacker** [comment]
I believe there was some framework not found error so I dragged and drop the framework into the project.

If you can figure out another solution to resolve the same issue than I am interested in knowing how?

**Comment by dnkoutso** [comment]
@benasher44 you are right, the Xcodeproj creates or returns the group called "Frameworks" but it might not be the type we expect.

We should either update to use a more unique cocoapods-specific name or crash with a better message if the group exists and its not the type we expect.

**Comment by DanToml** [comment]
@dnkoutso one problem with that is handling the migration will be tricky - or a breaking (thus not doable till 2.0) change

**Comment by hamidmustafa** [comment]
> Might be a bug in CocoaPods but this is causing the problem:
> 
> <img alt="screen_shot_2016-12-16_at_3_12_30_pm" width="292" src="https://cloud.githubusercontent.com/assets/310370/21281496/2cf2d72e-c3a2-11e6-8557-57b660debfa0.png">
> 
> If you move it into a subgroup then it works.

what does exactly mean by this? I 'm seeing this issue when I added my pods by sourcing from one of my podspec git repo.
