### ISSUE TITLE
Unable to create a source with URL 

### ISSUE THREAD

**Issue by FtheGFW** [CocoaPods/CocoaPods#6363]
### Command

```
/usr/local/bin/pod install --verbose
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 8.0 (8S188o)
         Git : git version 2.7.2
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : CocoaPods - git@github.com:CocoaPods/CocoaPods.git @ 469e9a242d2f1a70fac3a6be87fe0f4dbb741ec7
               master - git@github.com:CocoaPods/Specs.git @ 9fb3a4e16e42487c0f19ff5f6bda31e50dc87291
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!


target 'xxx-project' do

pod 'AFNetworking', '~> 3.0'
pod 'IQKeyboardManager'
pod 'Masonry'
pod 'YYModel'
pod 'YYCategories'
pod 'MBProgressHUD', '~> 1.0.0'

end
```

### Error

```
RuntimeError - Unable to create a source with URL https://github.com/CocoaPods/Specs.git
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/sources_manager.rb:42:in `find_or_create_source_with_url'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:814:in `block in sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:813:in `map'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:813:in `sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:143:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:110:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command/install.rb:37:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by dnkoutso** [comment]
Can you manually run `pod repo add master https://gitcafe.com/akuandev/Specs.git --verbose` and see what the error is?

**Comment by FtheGFW** [comment]
I've figured this out, thanks anyway @dnkoutso 
the cause is I manually changed the pod scripts  installed on my mac with '--depth=1'  appended to save the time of clone the Specs repo, but end up the the above error, so I just have to revert the changes I made and clone the whole project.
