### ISSUE TITLE
Can't lint - error: use of unresolved identifier, error: no such module 'SwiftyJSON'

### ISSUE THREAD

**Issue by ElizaSapir** [CocoaPods/CocoaPods#6375]
# Report

## What did you do?

1. Prepared a podspec
2. Tested locally and it works like a charm
3. Tried to `pod spec lint` (tried even `pod lib lint --use-libraries` it doesn't help)

## What did you expect to happen?

get success when linting since locally is works perfect as i mentioned. 

## What happened instead?

Got list of Errors, please see below:

```
PlayKit (0.1.3)
    - WARN  | summary: The summary is not meaningful.
    - WARN  | [PlayKit/Core] xcodebuild:  PlayKit/Classes/Player/AssetLoaderDelegate.swift:126:27: warning: 'as' test is always true
    - WARN  | [PlayKit/Core] xcodebuild:  PlayKit/Classes/Player/AssetLoaderDelegate.swift:120:13: warning: variable 'dataTask' was never mutated; consider changing to 'let' constant
    - NOTE  | [PlayKit/Core] xcodebuild:  var dataTask = URLSession.shared.dataTask(with: request, completionHandler: {(data: Data?, response: URLResponse?, error: Error?) -> Void in
    - WARN  | [PlayKit/Core] xcodebuild:  PlayKit/Classes/Player/AssetLoaderDelegate.swift:260:78: warning: expression implicitly coerced from 'Error?' to Any
    - NOTE  | [PlayKit/Core] xcodebuild:  PlayKit/Classes/Player/AssetLoaderDelegate.swift:260:85: note: provide a default value to avoid this warning
    - NOTE  | [PlayKit/Core] xcodebuild:  PlayKit/Classes/Player/AssetLoaderDelegate.swift:260:85: note: force-unwrap the value to avoid this warning
    - NOTE  | [PlayKit/Core] xcodebuild:  PlayKit/Classes/Player/AssetLoaderDelegate.swift:260:85: note: explicitly cast to Any with 'as Any' to silence this warning
    - WARN  | [PlayKit/Core] xcodebuild:  PlayKit/Classes/Player/AVPlayerEngine.swift:200:49: warning: result of operator '==' is unused
    - WARN  | [PlayKit/Core] xcodebuild:  PlayKit/Classes/Player/AVPlayerEngine.swift:476:20: warning: non-optional expression of type 'Float64' (aka 'Double') used in a check for optionals
    - WARN  | [PlayKit/Core] xcodebuild:  PlayKit/Classes/Player/DefaultAssetHandler.swift:90:19: warning: value 'fpsCertificate' was defined but never used; consider replacing with boolean test
    - WARN  | [PlayKit/Core] xcodebuild:  PlayKit/Classes/Player/DefaultAssetHandler.swift:96:13: warning: initialization of immutable value 'assetName' was never used; consider replacing with assignment to '_' or removing it
    - WARN  | [PlayKit/Core] xcodebuild:  PlayKit/Classes/Network/KalturaMultiRequestBuilder.swift:44:52: warning: expression implicitly coerced from 'String?' to Any
    - NOTE  | [PlayKit/Core] xcodebuild:  PlayKit/Classes/Network/KalturaMultiRequestBuilder.swift:44:60: note: provide a default value to avoid this warning
    - NOTE  | [PlayKit/Core] xcodebuild:  PlayKit/Classes/Network/KalturaMultiRequestBuilder.swift:44:60: note: force-unwrap the value to avoid this warning
    - NOTE  | [PlayKit/Core] xcodebuild:  PlayKit/Classes/Network/KalturaMultiRequestBuilder.swift:44:60: note: explicitly cast to Any with 'as Any' to silence this warning
    - WARN  | [PlayKit/Core] xcodebuild:  PlayKit/Classes/Network/KalturaMultiRequestBuilder.swift:45:54: warning: expression implicitly coerced from 'String?' to Any
    - NOTE  | [PlayKit/Core] xcodebuild:  PlayKit/Classes/Network/KalturaMultiRequestBuilder.swift:45:62: note: provide a default value to avoid this warning
    - NOTE  | [PlayKit/Core] xcodebuild:  PlayKit/Classes/Network/KalturaMultiRequestBuilder.swift:45:62: note: force-unwrap the value to avoid this warning
    - NOTE  | [PlayKit/Core] xcodebuild:  PlayKit/Classes/Network/KalturaMultiRequestBuilder.swift:45:62: note: explicitly cast to Any with 'as Any' to silence this warning
    - WARN  | [PlayKit/Core] xcodebuild:  PlayKit/Classes/Managers/LocalAssetsManager.swift:14:5: warning: will never be executed
    - NOTE  | [PlayKit/Core] xcodebuild:  PlayKit/Classes/Managers/LocalAssetsManager.swift:14:8: note: condition always evaluates to false
    - WARN  | [PlayKit/Core] xcodebuild:  PlayKit/Classes/Player/MediaEntry.swift:46:34: warning: expression implicitly coerced from 'Any?' to Any
    - NOTE  | [PlayKit/Core] xcodebuild:  PlayKit/Classes/Player/MediaEntry.swift:46:34: note: provide a default value to avoid this warning
    - NOTE  | [PlayKit/Core] xcodebuild:  PlayKit/Classes/Player/MediaEntry.swift:46:34: note: force-unwrap the value to avoid this warning
    - NOTE  | [PlayKit/Core] xcodebuild:  PlayKit/Classes/Player/MediaEntry.swift:46:34: note: explicitly cast to Any with 'as Any' to silence this warning
    - WARN  | [PlayKit/Core] xcodebuild:  PlayKit/Classes/Providers/Mock/MockMediaProvider.swift:71:25: warning: expression implicitly coerced from 'Any?' to Any
    - NOTE  | [PlayKit/Core] xcodebuild:  PlayKit/Classes/Providers/Mock/MockMediaProvider.swift:71:30: note: provide a default value to avoid this warning
    - NOTE  | [PlayKit/Core] xcodebuild:  PlayKit/Classes/Providers/Mock/MockMediaProvider.swift:71:30: note: force-unwrap the value to avoid this warning
    - NOTE  | [PlayKit/Core] xcodebuild:  PlayKit/Classes/Providers/Mock/MockMediaProvider.swift:71:30: note: explicitly cast to Any with 'as Any' to silence this warning
    - WARN  | [PlayKit/Core] xcodebuild:  PlayKit/Classes/Providers/OTT/Parsers/OTTObjectMapper.swift:22:31: warning: expression implicitly coerced from 'Any?' to Any
    - NOTE  | [PlayKit/Core] xcodebuild:  PlayKit/Classes/Providers/OTT/Parsers/OTTObjectMapper.swift:22:31: note: provide a default value to avoid this warning
    - NOTE  | [PlayKit/Core] xcodebuild:  PlayKit/Classes/Providers/OTT/Parsers/OTTObjectMapper.swift:22:31: note: force-unwrap the value to avoid this warning
    - NOTE  | [PlayKit/Core] xcodebuild:  PlayKit/Classes/Providers/OTT/Parsers/OTTObjectMapper.swift:22:31: note: explicitly cast to Any with 'as Any' to silence this warning
    - WARN  | [PlayKit/Core] xcodebuild:  PlayKit/Classes/Providers/OTT/Parsers/OTTResponseParser.swift:26:45: warning: expression implicitly coerced from '[String : Any]?' to Any
    - NOTE  | [PlayKit/Core] xcodebuild:  PlayKit/Classes/Providers/OTT/Parsers/OTTResponseParser.swift:26:45: note: provide a default value to avoid this warning
    - NOTE  | [PlayKit/Core] xcodebuild:  PlayKit/Classes/Providers/OTT/Parsers/OTTResponseParser.swift:26:45: note: force-unwrap the value to avoid this warning
    - NOTE  | [PlayKit/Core] xcodebuild:  PlayKit/Classes/Providers/OTT/Parsers/OTTResponseParser.swift:26:45: note: explicitly cast to Any with 'as Any' to silence this warning
    - WARN  | [PlayKit/Core] xcodebuild:  PlayKit/Classes/Providers/OVP/OVPMediaProvider.swift:133:89: warning: expression implicitly coerced from 'Any?' to Any
    - NOTE  | [PlayKit/Core] xcodebuild:  PlayKit/Classes/Providers/OVP/OVPMediaProvider.swift:133:91: note: provide a default value to avoid this warning
    - NOTE  | [PlayKit/Core] xcodebuild:  PlayKit/Classes/Providers/OVP/OVPMediaProvider.swift:133:91: note: force-unwrap the value to avoid this warning
    - NOTE  | [PlayKit/Core] xcodebuild:  PlayKit/Classes/Providers/OVP/OVPMediaProvider.swift:133:91: note: explicitly cast to Any with 'as Any' to silence this warning
    - WARN  | [PlayKit/Core] xcodebuild:  PlayKit/Classes/Providers/OVP/Parsers/OVPObjectMapper.swift:21:31: warning: expression implicitly coerced from 'Any?' to Any
    - NOTE  | [PlayKit/Core] xcodebuild:  PlayKit/Classes/Providers/OVP/Parsers/OVPObjectMapper.swift:21:31: note: provide a default value to avoid this warning
    - NOTE  | [PlayKit/Core] xcodebuild:  PlayKit/Classes/Providers/OVP/Parsers/OVPObjectMapper.swift:21:31: note: force-unwrap the value to avoid this warning
    - NOTE  | [PlayKit/Core] xcodebuild:  PlayKit/Classes/Providers/OVP/Parsers/OVPObjectMapper.swift:21:31: note: explicitly cast to Any with 'as Any' to silence this warning
    - WARN  | [PlayKit/Core] xcodebuild:  PlayKit/Classes/Player/PlayerLoader.swift:46:106: warning: expression implicitly coerced from 'AnyObject?' to Any
    - NOTE  | [PlayKit/Core] xcodebuild:  PlayKit/Classes/Player/PlayerLoader.swift:46:113: note: provide a default value to avoid this warning
    - NOTE  | [PlayKit/Core] xcodebuild:  PlayKit/Classes/Player/PlayerLoader.swift:46:113: note: force-unwrap the value to avoid this warning
    - NOTE  | [PlayKit/Core] xcodebuild:  PlayKit/Classes/Player/PlayerLoader.swift:46:113: note: explicitly cast to Any with 'as Any' to silence this warning
    - WARN  | [PlayKit/Core] xcodebuild:  PlayKit/Classes/Network/Request.swift:130:16: warning: value 'params' was defined but never used; consider replacing with boolean test
    - ERROR | [iOS] [PlayKit/SamplePlugin] file patterns: The `source_files` pattern did not match any file.
    - ERROR | [iOS] [PlayKit/IMAPlugin] unknown: Encountered an unknown error (The 'Pods-App' target has transitive dependencies that include static binaries: (/private/var/folders/57/pv4_gcjx5pn3_0vht648bqsm0000gn/T/CocoaPods/Lint/Pods/GoogleAds-IMA-iOS-SDK/GoogleInteractiveMediaAds/GoogleInteractiveMediaAds-GoogleIMA3/GoogleInteractiveMediaAds.framework)) during validation.
    - ERROR | [PlayKit/GoogleCastAddon, PlayKit/PhoenixPlugin, PlayKit/KalturaStatsPlugin, and more...] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - ERROR | [iOS] [PlayKit/GoogleCastAddon] xcodebuild:  PlayKit/Addons/GoogleCast/AdInfoParser.swift:31:17: error: use of unresolved identifier 'PKLog'
    - NOTE  | [PlayKit/GoogleCastAddon] xcodebuild:  Foundation.NSLog:1:13: note: did you mean 'NSLog'?
    - NOTE  | [PlayKit/GoogleCastAddon] xcodebuild:  Foundation.NSLog:2:13: note: did you mean 'NSLog'?
    - WARN  | [iOS] [PlayKit/GoogleCastAddon] xcodebuild:  PlayKit/Addons/GoogleCast/AdInfoParser.swift:29:13: warning: non-optional expression of type 'AdsMetadata' used in a check for optionals
    - ERROR | [iOS] [PlayKit/GoogleCastAddon] xcodebuild:  PlayKit/Addons/GoogleCast/AdInfoParser.swift:49:16: error: use of unresolved identifier 'PKLog'
    - WARN  | [iOS] [PlayKit/GoogleCastAddon] xcodebuild:  PlayKit/Addons/GoogleCast/AdInfoParser.swift:46:13: warning: non-optional expression of type 'AdsMetadata' used in a check for optionals
    - WARN  | [iOS] [PlayKit/GoogleCastAddon] xcodebuild:  PlayKit/Addons/GoogleCast/BasicCastBuilder.swift:124:13: warning: constant 'data' inferred to have type '()', which may be unexpected
    - NOTE  | [iOS] [PlayKit/GoogleCastAddon] xcodebuild:  PlayKit/Addons/GoogleCast/BasicCastBuilder.swift:124:13: note: add an explicit type annotation to silence this warning
    - WARN  | [iOS] [PlayKit/GoogleCastAddon] xcodebuild:  PlayKit/Addons/GoogleCast/BasicCastBuilder.swift:124:13: warning: initialization of immutable value 'data' was never used; consider replacing with assignment to '_' or removing it
    - ERROR | [iOS] [PlayKit/GoogleCastAddon] xcodebuild:  PlayKit/Addons/GoogleCast/BasicCastBuilder.swift:172:13: error: use of unresolved identifier 'PKLog'
    - ERROR | [iOS] [PlayKit/GoogleCastAddon] xcodebuild:  PlayKit/Addons/GoogleCast/BasicCastBuilder.swift:177:13: error: use of unresolved identifier 'PKLog'
    - ERROR | [iOS] [PlayKit/YouboraPlugin] unknown: Encountered an unknown error (The 'Pods-App' target has transitive dependencies that include static binaries: (/private/var/folders/57/pv4_gcjx5pn3_0vht648bqsm0000gn/T/CocoaPods/Lint/Pods/Youbora-AVPlayer/ios/static/YouboraPluginAVPlayer.framework)) during validation.
    - ERROR | [iOS] [PlayKit/WidevineClassic] unknown: Encountered an unknown error (Unable to find a specification for `PlayKitWV` depended upon by `PlayKit/WidevineClassic`) during validation.
    - ERROR | [PlayKit/PhoenixPlugin] xcodebuild:  PlayKit/Plugins/Phoenix/BookmarkService.swift:10:8: error: no such module 'SwiftyJSON'
    - ERROR | [PlayKit/KalturaStatsPlugin] xcodebuild:  PlayKit/Plugins/KalturaStats/OVPStatsService.swift:10:8: error: no such module 'SwiftyJSON'
    - ERROR | [PlayKit/KalturaLiveStatsPlugin] xcodebuild:  PlayKit/Plugins/KalturaLiveStats/LiveStatsService.swift:10:8: error: no such module 'SwiftyJSON'
```

## CocoaPods Environment

```
```
   CocoaPods : 1.1.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.1 (16B2555)
       Xcode : 8.1 (8B62)
         Git : git version 2.9.3 (Apple Git-75)

cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

Below you can see the podspec and the repo that contains it:
https://github.com/kaltura/playkit-ios/blob/develop/PlayKit.podspec

**Comment by benasher44** [comment]
Hi @ElizaSapir! Thanks for filing this! It looks like you have subspecs that rely on SwiftyJSON, but they don't have that listed as a dependency. To fix, this you should add `ssp.dependency 'SwiftyJSON'` to your subspecs that require it. Can you give that a try? Thanks!

**Comment by ElizaSapir** [comment]
Hey @benasher44 ,

Looks like now it's better but still i have below error (using --verbose):

```

Elizas-MacBook-Pro-3:playkit-ios elizasapir$ pod spec lint --sources='https://github.com/kaltura/playkit-ios-widevine.git,https://github.com/CocoaPods/Specs' --use-libraries --verbose

    PlayKit (0.1.3) - Analyzing on iOS 8.0 platform.
  Preparing

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-App`: (``)

Fetching external sources
-> Fetching podspec for `PlayKit` from `/Users/elizasapir/Desktop/Kaltura/repos/ovp/ios/playkit-ios/PlayKit.podspec`

Resolving dependencies of

Comparing resolved specification to the sandbox manifest
  A GoogleAds-IMA-iOS-SDK
  A Log
  A PlayKit
  A PlayKitWV
  A SwiftyJSON
  A Youbora-AVPlayer
  A Youbora-YouboraLib
  A google-cast-sdk

Downloading dependencies

-> Installing GoogleAds-IMA-iOS-SDK (3.3.1)
  > Copying GoogleAds-IMA-iOS-SDK from
  `/Users/elizasapir/Library/Caches/CocoaPods/Pods/Release/GoogleAds-IMA-iOS-SDK/3.3.1-56433`
  to
  `../../../../../../../../private/var/folders/57/pv4_gcjx5pn3_0vht648bqsm0000gn/T/CocoaPods/Lint/Pods/GoogleAds-IMA-iOS-SDK`

-> Installing Log (1.0)
  > Copying Log from
  `/Users/elizasapir/Library/Caches/CocoaPods/Pods/Release/Log/1.0-5e368` to
  `../../../../../../../../private/var/folders/57/pv4_gcjx5pn3_0vht648bqsm0000gn/T/CocoaPods/Lint/Pods/Log`

-> Installing PlayKit (0.1.3)
  > Copying PlayKit from
  `/Users/elizasapir/Library/Caches/CocoaPods/Pods/External/PlayKit/972a0803a11e8823eba744304c7544f5-b87f9`
  to
  `../../../../../../../../private/var/folders/57/pv4_gcjx5pn3_0vht648bqsm0000gn/T/CocoaPods/Lint/Pods/PlayKit`

-> Installing PlayKitWV (0.0.1)
  > Copying PlayKitWV from
  `/Users/elizasapir/Library/Caches/CocoaPods/Pods/Release/PlayKitWV/0.0.1-33226`
  to
  `../../../../../../../../private/var/folders/57/pv4_gcjx5pn3_0vht648bqsm0000gn/T/CocoaPods/Lint/Pods/PlayKitWV`

-> Installing SwiftyJSON (3.1.3)
  > Copying SwiftyJSON from
  `/Users/elizasapir/Library/Caches/CocoaPods/Pods/Release/SwiftyJSON/3.1.3-38a8e`
  to
  `../../../../../../../../private/var/folders/57/pv4_gcjx5pn3_0vht648bqsm0000gn/T/CocoaPods/Lint/Pods/SwiftyJSON`

-> Installing Youbora-AVPlayer (5.3.5)
  > Copying Youbora-AVPlayer from
  `/Users/elizasapir/Library/Caches/CocoaPods/Pods/Release/Youbora-AVPlayer/5.3.5-02aea`
  to
  `../../../../../../../../private/var/folders/57/pv4_gcjx5pn3_0vht648bqsm0000gn/T/CocoaPods/Lint/Pods/Youbora-AVPlayer`

-> Installing Youbora-YouboraLib (5.3.8)
  > Copying Youbora-YouboraLib from
  `/Users/elizasapir/Library/Caches/CocoaPods/Pods/Release/Youbora-YouboraLib/5.3.8-523ad`
  to
  `../../../../../../../../private/var/folders/57/pv4_gcjx5pn3_0vht648bqsm0000gn/T/CocoaPods/Lint/Pods/Youbora-YouboraLib`

-> Installing google-cast-sdk (3.3.0)
  > Copying google-cast-sdk from
  `/Users/elizasapir/Library/Caches/CocoaPods/Pods/Release/google-cast-sdk/3.3.0-da198`
  to
  `../../../../../../../../private/var/folders/57/pv4_gcjx5pn3_0vht648bqsm0000gn/T/CocoaPods/Lint/Pods/google-cast-sdk`
  - Running pre install hooks
 -> PlayKit (0.1.3)
    - WARN  | summary: The summary is not meaningful.
    - ERROR | [iOS] unknown: Encountered an unknown error (Pods written in Swift can only be integrated as frameworks; add `use_frameworks!` to your Podfile or target to opt into using it. The Swift Pods being used are: Log, PlayKit, and SwiftyJSON
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:448:in `block (2 levels) in verify_framework_usage'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:443:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:443:in `block in verify_framework_usage'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:440:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:440:in `verify_framework_usage'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/validator.rb:479:in `block in install_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/validator.rb:479:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/validator.rb:479:in `install_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/validator.rb:301:in `block in perform_extensive_analysis'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/validator.rb:293:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/validator.rb:293:in `perform_extensive_analysis'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/validator.rb:79:in `validate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command/spec/lint.rb:64:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command/spec/lint.rb:53:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command/spec/lint.rb:53:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
) during validation.

Analyzed 1 podspec.

[!] The spec did not pass validation, due to 1 error and 1 warning.

/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command/spec/lint.rb:81:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'

```

Tried `--use-libraries` it doesn't help.

Do you have any solution for me?

Thanks!

**Comment by dnkoutso** [comment]
You cant use `--use-libraries` if your pod contains swift. It must be built as a dynamic framework.
```
pod spec lint --sources='https://github.com/kaltura/playkit-ios-widevine.git,https://github.com/CocoaPods/Specs' --verbose
```

**Comment by ElizaSapir** [comment]
Hey @benasher44 ,

So fixed everything my last issue is:

```

    - ERROR | [iOS] unknown: Encountered an unknown error (The 'Pods-App' target has transitive dependencies that include static binaries: (/private/var/folders/57/pv4_gcjx5pn3_0vht648bqsm0000gn/T/CocoaPods/Lint/Pods/GoogleAds-IMA-iOS-SDK/GoogleInteractiveMediaAds/GoogleInteractiveMediaAds-GoogleIMA3/GoogleInteractiveMediaAds.framework)) during validation.


```

How can i handle it, below is my relevant cause from podspec:

```

s.subspec 'IMAPlugin' do |ssp|
    ssp.source_files = 'Plugins/IMA'
    ssp.xcconfig = { 'CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES' => 'YES',
                  'OTHER_LDFLAGS' => '$(inherited) -framework "GoogleInteractiveMediaAds"',
                  'FRAMEWORK_SEARCH_PATHS' => '$(inherited) "${PODS_ROOT}"/**',
                  'LIBRARY_SEARCH_PATHS' => '$(inherited) "${PODS_ROOT}"/**' }
    ssp.dependency 'GoogleAds-IMA-iOS-SDK', '~> 3.3'
end

```

**Comment by benasher44** [comment]
Hi @ElizaSapir! Unfortunately, CocoaPods does not support transitive dependencies that include static binaries at this time. See #2926 for more information. Sorry about that!

**Comment by ElizaSapir** [comment]
@benasher44 ,

So what you propose to do? it works when I pod install my main issue is that i can't lint.

**Comment by benasher44** [comment]
@ElizaSapir if you'd like to push a pod that won't lint, we typically recommend that you proceed with caution (since in this case there were source-level issues to fix) and push using the trunk API if you need. Checkout #5801 for a previous discussion on this.

**Comment by ElizaSapir** [comment]
Hey,

These errors appeared since I had dependencies with static libs. resolved by adding this pods from podfile.
