### ISSUE TITLE
SwiftMQTT with watchOS

### ISSUE THREAD

**Issue by fcesc** [CocoaPods/CocoaPods#6377]
### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.2.0.beta.3
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.2 (16C67)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.10.1 (Apple Git-78)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 8cdf63b0c631d5549f7c5d09f8e5c9d9976ee30d
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

target 'Prova_mqtt' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  
  # Pods for Prova_mqtt
  pod 'SwiftMQTT'

end

target 'Mqtt Watch' do
  # Comment the next line if you're not using Swift and don't want to use dynamic #frameworks
  platform :watchos, '> 2.0'

  pod 'SwiftMQTT'

end
```

### Error

```
ArgumentError - Malformed version number string > 2.0
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.2.0.beta.3/lib/cocoapods-core/version.rb:54:in `initialize'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.2.0.beta.3/lib/cocoapods-core/vendor/version.rb:199:in `new'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.2.0.beta.3/lib/cocoapods-core/vendor/version.rb:199:in `new'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.2.0.beta.3/lib/cocoapods-core/vendor/version.rb:192:in `create'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.2.0.beta.3/lib/cocoapods-core/platform.rb:50:in `initialize'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.2.0.beta.3/lib/cocoapods-core/podfile/target_definition.rb:467:in `new'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.2.0.beta.3/lib/cocoapods-core/podfile/target_definition.rb:467:in `platform'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.2.0.beta.3/lib/cocoapods-core/podfile/target_definition.rb:231:in `matches_platform?'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.2.0.beta.3/lib/cocoapods-core/podfile/target_definition.rb:218:in `exclusive?'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.2.0.beta.3/lib/cocoapods-core/podfile/target_definition.rb:70:in `dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.2.0.beta.3/lib/cocoapods-core/podfile.rb:90:in `map'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.2.0.beta.3/lib/cocoapods-core/podfile.rb:90:in `dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.3/lib/cocoapods/installer/analyzer.rb:798:in `sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.3/lib/cocoapods/installer.rb:143:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.3/lib/cocoapods/installer.rb:110:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.3/lib/cocoapods/command/install.rb:37:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.3/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by dnkoutso** [comment]
I dont think you can use `> 2.0` with `platform`. Please use `2.0`

**Comment by dnkoutso** [comment]
Closing due to inactivity and most likely not a CocoaPods issue.
