### ISSUE TITLE
Unable to update pods

### ISSUE THREAD

**Issue by myralukens** [CocoaPods/CocoaPods#6390]
### Command

```
/usr/local/bin/pod update
```

### Report

* What did you do?
pod update

* What did you expect to happen?
update pods

* What happened instead?
error

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.6 (15G1212)
       Xcode : 8.2 (8C38)
         Git : git version 1.8.4
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ b0f4dcba1754cca8153b8cda0750471342f0d9ee
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

target 'PolyRides' do
   pod 'BubbleTransition'
   pod 'SendGrid', :git => 'https://github.com/scottkawai/sendgrid-swift.git', :submodules => true
   pod 'DZNEmptyDataSet'
   pod 'AFNetworking'
   pod 'GoogleMaps'
   pod 'GooglePlaces'
   pod 'GoogleUtilities'
   pod 'Google/Analytics'
   pod 'FBSDKShareKit'
   pod 'FBSDKCoreKit'
   pod 'FBSDKLoginKit'
   pod 'Siren'
   pod 'Fabric'
   pod 'Crashlytics'
   pod 'Firebase/Core'
   pod 'Firebase/Auth'
   pod 'Firebase/Database'
   pod 'JSQMessagesViewController'
end

target 'PolyRidesTests' do

end

target 'PolyRidesUITests' do

end
```

### Error

```
RuntimeError - Unable to create a source with URL https://github.com/CocoaPods/Specs.git
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/sources_manager.rb:42:in `find_or_create_source_with_url'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:814:in `block in sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:813:in `map'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:813:in `sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:143:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:110:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command/update.rb:60:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by benasher44** [comment]
Hi @myralukens! This will take some time, but you can try removing your `~/.cocoapods` directory, run `pod setup`, and then try again.

**Comment by benasher44** [comment]
Hi @myralukens! I'm going to close this, since there hasn't been any activity on it in some time now. Please feel free to open a new issue and fill out the issue template if you're still experiencing this using the latest version of CocoaPods. Have a great day!
