### ISSUE TITLE
Pod search error 

### ISSUE THREAD

**Issue by Ambtion** [CocoaPods/CocoaPods#6407]
when use pod search it show error, detail next:

### Error

```
JSON::ParserError - 743: unexpected token at ''
/usr/local/lib/ruby/gems/2.2.0/gems/json-2.0.2/lib/json/common.rb:156:in `parse'
/usr/local/lib/ruby/gems/2.2.0/gems/json-2.0.2/lib/json/common.rb:156:in `parse'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-core-1.2.0.beta.3/lib/cocoapods-core/source/manager.rb:251:in `stored_search_index'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-core-1.2.0.beta.3/lib/cocoapods-core/source/manager.rb:187:in `updated_search_index'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-core-1.2.0.beta.3/lib/cocoapods-core/source/manager.rb:118:in `search_by_name'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-search-1.0.0/lib/cocoapods-search/command/search.rb:87:in `local_search'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-search-1.0.0/lib/cocoapods-search/command/search.rb:63:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.2.0.beta.3/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.2.0.beta.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

**Comment by benasher44** [comment]
Hi @Ambtion! Thanks for the report! Did you try deleting your cache by running `rm -rf ~/Library/Caches/CocoaPods`?

**Comment by hc2088** [comment]
gem cleanup cocopods

**Comment by benasher44** [comment]
Going to close this, since it's been more than a month without a response. Please feel free to open a new issue and fill out the issue template using the latest version of CocoaPods, and then we'd be happy to help you out. Have a great day!

**Comment by gb-6k-house** [comment]
i solved this issue by running rm -rf ~/Library/Caches/CocoaPods @Ambtion @benasher44

**Comment by linchen195** [comment]
@benasher44 you are right, thank you.
