### ISSUE TITLE
Problem running pod install after calabash-ios update

### ISSUE THREAD

**Issue by cicerohellmann** [CocoaPods/CocoaPods#6426]
Before anybody raise a rock, I believe that cocoapods should be independent of anything I install in my gems, saving the ones that interfere in it directly.
As this: https://rubygems.org/gems/calabash-cucumber/versions/0.13.0
And this: https://rubygems.org/gems/cocoapods/versions/0.39.0
Shows us, there is nothing that can interfere in each other. So I believe that I'm digging in the wrong way. So I will explain what I'm doing:
I'm having an issue right after I run calabash-ios setup.
I can't run pod install anymore.
It is a fresh installation of MAC OS X Sierra.
This is the output after I run pod install right after I run callabash-ios setup:

`Jenkinss-Mac-mini:Build and Run jenkins$ pod install`

Analyzing dependencies

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/jenkins/.rvm/gems/ruby-2.1.6/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.1.6p336 (2015-04-13 revision 50298) [x86_64-darwin16.0]
    RubyGems : 2.6.8
        Host : Mac OS X 10.12.2 (16C68)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.10.1 (Apple Git-78)
Ruby lib dir : /Users/jenkins/.rvm/rubies/ruby-2.1.6/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 18fcb35bb822863ad5403b841400bd2936e77ab6
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'MAPP' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
 
  # Pods for MAPP
  pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :tag => '3.5.0'
  pod 'SnapKit', '0.22.0'
#  pod 'FSCalendar', '2.3.3'
  pod 'XLPagerTabStrip', '~> 5.0'
  pod 'SwiftyJSON', '2.3.2'
  pod 'Wrap', '1.1.1'
  pod 'AlamofireObjectMapper', '3.0'
  pod 'FCAlertView'
  pod 'DLRadioButton', '1.4.9'
  pod 'DropDown', '1.0.1'
  pod 'RealmSwift'
  pod 'MercadoPagoSDK', '2.0.3.7'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'SwiftValidator', :git => 'https://github.com/jpotts18/SwiftValidator.git', :tag => '4.0.0'
  pod 'VMaskTextField'
  pod 'Adjust', '~> 4.10.2'

    post_install do |installer|
        installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '2.3'
            end
        end
    end

  target 'MAPPTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :tag => '3.5.0'
    pod 'SnapKit', '0.22.0'
    pod 'XLPagerTabStrip', '~> 5.0'
    pod 'SwiftyJSON', '2.3.2'
    pod 'Wrap', '1.1.1'
    pod 'AlamofireObjectMapper', '3.0'
    pod 'DropDown', '1.0.1'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'VMaskTextField'
   
  end

  target 'MAPPUITests' do
    inherit! :search_paths
    # Pods for testing
  end



end
```

### Error

```
LoadError - cannot load such file -- cfpropertylist
/Users/jenkins/.rvm/gems/ruby-2.1.6/gems/xcodeproj-1.4.2/lib/xcodeproj/plist.rb:25:in `read_from_path'
/Users/jenkins/.rvm/gems/ruby-2.1.6/gems/xcodeproj-1.4.2/lib/xcodeproj/project.rb:200:in `initialize_from_file'
/Users/jenkins/.rvm/gems/ruby-2.1.6/gems/xcodeproj-1.4.2/lib/xcodeproj/project.rb:102:in `open'
/Users/jenkins/.rvm/gems/ruby-2.1.6/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:855:in `block (2 levels) in inspect_targets_to_integrate'
/Users/jenkins/.rvm/gems/ruby-2.1.6/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:854:in `each'
/Users/jenkins/.rvm/gems/ruby-2.1.6/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:854:in `block in inspect_targets_to_integrate'
/Users/jenkins/.rvm/gems/ruby-2.1.6/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/jenkins/.rvm/gems/ruby-2.1.6/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:849:in `inspect_targets_to_integrate'
/Users/jenkins/.rvm/gems/ruby-2.1.6/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:66:in `analyze'
/Users/jenkins/.rvm/gems/ruby-2.1.6/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:236:in `analyze'
/Users/jenkins/.rvm/gems/ruby-2.1.6/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:150:in `block in resolve_dependencies'
/Users/jenkins/.rvm/gems/ruby-2.1.6/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/jenkins/.rvm/gems/ruby-2.1.6/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:149:in `resolve_dependencies'
/Users/jenkins/.rvm/gems/ruby-2.1.6/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:110:in `install!'
/Users/jenkins/.rvm/gems/ruby-2.1.6/gems/cocoapods-1.1.1/lib/cocoapods/command/install.rb:37:in `run'
/Users/jenkins/.rvm/gems/ruby-2.1.6/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Users/jenkins/.rvm/gems/ruby-2.1.6/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/Users/jenkins/.rvm/gems/ruby-2.1.6/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/Users/jenkins/.rvm/gems/ruby-2.1.6/bin/pod:22:in `load'
/Users/jenkins/.rvm/gems/ruby-2.1.6/bin/pod:22:in `<main>'
/Users/jenkins/.rvm/gems/ruby-2.1.6/bin/ruby_executable_hooks:15:in `eval'
/Users/jenkins/.rvm/gems/ruby-2.1.6/bin/ruby_executable_hooks:15:in `<main>'
```
### Edit 1

So I was reviewing my post and  realized that I didn't read the plist.rb file in the first warning line..
Looks like we have a dependency that conflicts with calabash and it is from xcodeproj.

Here is what the plist.rb file looks like if someone has any interest:

```
autoload :Nanaimo, 'nanaimo'
autoload :CFPropertyList, 'cfpropertylist'

module Xcodeproj
  # Provides support for loading and serializing property list files.
  #
  module Plist
    # @return [Hash] Returns the native objects loaded from a property list
    #         file.
    #
    # @param  [#to_s] path
    #         The path of the file.
    #
    def self.read_from_path(path)
      path = path.to_s
      unless File.exist?(path)
        raise Informative, "The plist file at path `#{path}` doesn't exist."
      end
      contents = File.read(path)
      if file_in_conflict?(contents)
        raise Informative, "The file `#{path}` is in a merge conflict."
      end
      case Nanaimo::Reader.plist_type(contents)
      when :xml, :binary
        CFPropertyList.native_types(CFPropertyList::List.new(:data => contents).value)
      else
        Nanaimo::Reader.new(contents).parse!.as_ruby
      end
    end

    # Serializes a hash as an XML property list file.
    #
    # @param  [#to_hash] hash
    #         The hash to store.
    #
    # @param  [#to_s] path
    #         The path of the file.
    #
    def self.write_to_path(hash, path)
      if hash.respond_to?(:to_hash)
        hash = hash.to_hash
      else
        raise TypeError, "The given `#{hash.inspect}` must respond " \
                          "to #to_hash'."
      end

      unless path.is_a?(String) || path.is_a?(Pathname)
        raise TypeError, "The given `#{path}` must be a string or 'pathname'."
      end
      path = path.to_s
      raise IOError, 'Empty path.' if path.empty?

      File.open(path, 'w') do |f|
        plist = Nanaimo::Plist.new(hash, :xml)
        Nanaimo::Writer::XMLWriter.new(plist, :pretty => true, :output => f, :strict => false).write
      end
    end

    # The known modules that can serialize plists.
    #
    KNOWN_IMPLEMENTATIONS = []

    class << self
      # @deprecated This method will be removed in 2.0
      #
      # @return [Nil]
      #
      attr_accessor :implementation
    end

    # @deprecated This method will be removed in 2.0
    #
    # @return [Nil]
    #
    def self.autoload_implementation
    end

    # @return [Bool] Checks whether there are merge conflicts in the file.
    #
    # @param  [#to_s] path
    #         The contents of the file.
    #
    def self.file_in_conflict?(contents)
      contents.match(/^(<|=|>){7}/)
    end
  end
end
```

**Comment by Brett-Best** [comment]
See if [this](https://github.com/CocoaPods/CocoaPods/issues/6382#issuecomment-271069108) fixes your problem.

**Comment by cicerohellmann** [comment]
I did all the common solutions, changed the versions and everything, even tried solutions kinda related to the issue like de nanonena gem that generate glitches. 
I tried everything (All the issues that cocoapods suggest when it crashes, and every recent (llast year) link possible). Looks like I'm a rare animal and nobody has this poblem.
I can provide any information as my other information that can help to solve this issue.
Right now I'm updating everything to the latest release possible to see if it fixes.

**Comment by cicerohellmann** [comment]
The real problem here is that this machine that I'm installing this things is supposed too be an automated system and I will probably run calabash-ios setup a lot of times, because we don't want  to carry it's frameworks for no reason. I just wanted to understand what is happening so I could open a PR and solve this thing for the sake of all the QA Automators around the world. And this is another thing. I don't understand why I feel like the only one having this specific issue, obviously there are other ppl with really look alike problems and it is probably a dependency conflict but this one is directly related too calabash and cocoapods. What I wanted to say is that this machine can't keep uninstalling and installing this all the time because it takes a lot of time if you sum it up in a day of tests and it doesn't make sense that this iis something that need too be done. I already used this setup some months ago and I don't remember getting this kind of issue.
