### ISSUE TITLE
NoMethodError - undefined method `dirname' for nil:NilClass, with Local development pods

### ISSUE THREAD

**Issue by sajeel** [CocoaPods/CocoaPods#6430]
Fetching podspec for `DevApi` from `DevApi`

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.4.8
        Host : Mac OS X 10.12 (16A323)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 594f91f162ef5c231b824832f437efbf378e5579
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'trafficmonitor' do


#pod 'GooglePlacesSearchController' , '~>0.1.5'
#pod 'GooglePlacesAutocomplete' , '~>0.3.0'


pod 'GoogleMaps', '~>1.12.3'
pod 'FBSDKCoreKit' , '~>4.1.0'
pod 'FBSDKLoginKit' , '~>4.1.0'
pod 'FBSDKShareKit' , '~>4.1.0'
pod 'Pushwoosh', '~>2.13.5'
pod 'Reachability', '3.0.0'
pod 'MBProgressHUD', '0.9.1'
pod 'UIAlertView-Blocks', '1.0'
pod 'SVWebViewController'
pod 'Fabric'
pod 'Crashlytics'
pod 'ReactiveViewModel', '~> 0.2'
pod 'Toast', '~>3.0'
pod 'DevApi', :path => 'DevApi'


end
```

### Error

```
NoMethodError - undefined method `dirname' for nil:NilClass
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/validator.rb:261:in `dot_swift_version'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/validator.rb:145:in `failure_reason'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/external_sources/abstract_external_source.rb:176:in `validate_podspec'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/external_sources/abstract_external_source.rb:163:in `store_podspec'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/external_sources/path_source.rb:17:in `block in fetch'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:85:in `titled_section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/external_sources/path_source.rb:11:in `fetch'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:639:in `fetch_external_source'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:615:in `block (2 levels) in fetch_external_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:614:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:614:in `block in fetch_external_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:613:in `fetch_external_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:73:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:236:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:150:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:149:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:110:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command/install.rb:37:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

**Comment by sajeel** [comment]
If dont include the (pod 'DevApi', :path => 'DevApi') line in the podfile, it works. But as soon i tried to introduce the development pods it broke. 

"DevApi.podspec" is never changed, worked with older version of cocoapods, but as soon i update the cocoapod to version 1.2.0.rc.1 it broke.

**Comment by benasher44** [comment]
Hi @sajeel! Thanks for reporting this! I believe this was fixed in one of the 1.2.0 releases. Can you please try `1.2.0.rc.1`? You can install it by running `gem install cocoapods --pre` or by modifying your Gemfile if you have one. Thanks!

**Comment by sajeel** [comment]
Thanks @benasher44 . yeah just checked that, problem was that there two version of Cocoapods 

1.1.0
1.2.0.rc.1

so i have to delete the version with 1.1.0 in order for it to work. couldn't figure it out why it was not using the latest cocoapods?

**Comment by benasher44** [comment]
Awesome! Glad you got it working! Maybe it just pics the most recent non-pre-release version? I'm not entirely sure, but I frequently find myself uninstalling old CocoaPods versions as well :)
