### ISSUE TITLE
Getting error after editing a podspec

### ISSUE THREAD

**Issue by hartbit** [CocoaPods/CocoaPods#644]
I'm getting a `different prefix` error when installing a pod that references a podspec that I tried to modify. I'm not an expert in Ruby, but the code I modified in `cocos2d.podspec` seems ok. I ran it through IRB without any trouble.
## Podspec

``` ruby
Pod::Spec.new do |s|
  s.name        =  'cocos2d'
  s.license     =  'MIT'
  s.version     =  '2.0.0'
  s.summary     =  'cocos2d for iPhone is a framework for building 2D games, demos, and other graphical/interactive applications.'
  s.description =  'cocos2d for iPhone is a framework for building 2D games, demos, and other graphical/interactive applications for iPod Touch, iPhone, iPad and Mac. It is based on the cocos2d design but instead of using python it, uses objective-c.'
  s.homepage    =  'http://www.cocos2d-iphone.org'
  s.author      =  { 'Ricardo Quesada' => 'ricardoquesada@gmail.com', 'Zynga Inc.' => 'https://zynga.com/' }
  s.source      =  {:git => 'https://github.com/cocos2d/cocos2d-iphone.git', :tag => 'release-2.0'}

  common_sources = FileList['cocos2d/**/*.{h,m,c}'].exclude(/Platforms\/.+\//) +
                   FileList['external/libpng/*.{h,c}'].exclude(/pngtest/) +
                   ['external/kazmath/src/**/*.{c,h}', 'external/kazmath/include/**/*.{c,h}']
  s.osx.source_files = common_sources + ['cocos2d/Platforms/Mac/*.{h,m}']
  s.ios.source_files = common_sources + ['cocos2d/Platforms/iOS/*.{h,m}']
  s.xcconfig   =  { 'HEADER_SEARCH_PATHS' => '"${PODS_ROOT}/cocos2d/external/kazmath/include"' }
  s.frameworks =  ["OpenGLES", "QuartzCore", "GameKit"]
  s.library    =  'z'

  s.subspec 'CocosDenshion' do |p|
    common_sources2 = ['CocosDenshion/CocosDenshion/*.{h,m}', 'CocosDenshion/CocosDenshionExtras/CDXPropertyModifierAction.{h,m}']
    p.ios.source_files = common_sources2
    p.osx.source_files = common_sources2 + ['CocosDenshion/CocosDenshionExtras/CDXMacOSXSupport.{h,m}']
    p.frameworks   =  ["OpenAL", "AVFoundation", "AudioToolbox"]
  end

  s.prefix_header_contents = '''
#define CC_ENABLE_GL_STATE_CACHE 1
'''

  def s.copy_header_mapping(from)
    from.relative_path_from(Pathname.new('cocos2d'))
  end
end
```
## Podfile

``` ruby
platform :ios, '5.0'

pod 'BlocksKit'
pod 'cocos2d', '2.0.0'
pod 'TestFlightSDK'
pod 'JRSwizzle'
pod 'InAppSettingsKit'

inhibit_all_warnings!
```
## Error

```
different prefix: "" and "/Users/david/Dropbox/Projects/GraviMaze/Pods"
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/pathname.rb:730:in `relative_path_from'
/Library/Ruby/Gems/1.8/gems/cocoapods-0.16.0.rc3/lib/cocoapods/local_pod.rb:209:in `relativize_from_sandbox'
/Library/Ruby/Gems/1.8/gems/cocoapods-0.16.0.rc3/lib/cocoapods/local_pod.rb:229:in `relative_source_files_by_spec'
/Library/Ruby/Gems/1.8/gems/cocoapods-0.16.0.rc3/lib/cocoapods/local_pod.rb:229:in `map'
/Library/Ruby/Gems/1.8/gems/cocoapods-0.16.0.rc3/lib/cocoapods/local_pod.rb:229:in `relative_source_files_by_spec'
/Library/Ruby/Gems/1.8/gems/cocoapods-0.16.0.rc3/lib/cocoapods/local_pod.rb:228:in `each'
/Library/Ruby/Gems/1.8/gems/cocoapods-0.16.0.rc3/lib/cocoapods/local_pod.rb:228:in `relative_source_files_by_spec'
/Library/Ruby/Gems/1.8/gems/cocoapods-0.16.0.rc3/lib/cocoapods/local_pod.rb:405:in `add_file_references_to_project'
/Library/Ruby/Gems/1.8/gems/cocoapods-0.16.0.rc3/lib/cocoapods/installer.rb:22:in `project'
/Library/Ruby/Gems/1.8/gems/cocoapods-0.16.0.rc3/lib/cocoapods/installer.rb:22:in `each'
/Library/Ruby/Gems/1.8/gems/cocoapods-0.16.0.rc3/lib/cocoapods/installer.rb:22:in `project'
/Library/Ruby/Gems/1.8/gems/cocoapods-0.16.0.rc3/lib/cocoapods/installer.rb:118:in `install!'
/Library/Ruby/Gems/1.8/gems/cocoapods-0.16.0.rc3/lib/cocoapods/user_interface.rb:77:in `message'
/Library/Ruby/Gems/1.8/gems/cocoapods-0.16.0.rc3/lib/cocoapods/installer.rb:117:in `install!'
/Library/Ruby/Gems/1.8/gems/cocoapods-0.16.0.rc3/lib/cocoapods/user_interface.rb:37:in `section'
/Library/Ruby/Gems/1.8/gems/cocoapods-0.16.0.rc3/lib/cocoapods/installer.rb:112:in `install!'
/Library/Ruby/Gems/1.8/gems/cocoapods-0.16.0.rc3/lib/cocoapods/command/install.rb:46:in `run_install_with_update'
/Library/Ruby/Gems/1.8/gems/cocoapods-0.16.0.rc3/lib/cocoapods/command/update.rb:24:in `run'
/Library/Ruby/Gems/1.8/gems/cocoapods-0.16.0.rc3/lib/cocoapods/command.rb:75:in `run'
/Library/Ruby/Gems/1.8/gems/cocoapods-0.16.0.rc3/bin/pod:16
/usr/bin/pod:23:in `load'
/usr/bin/pod:23
```

**Comment by itmarsung** [comment]
when I use "pod trunk registe". error 
![fc8bd65c-13e1-4511-9087-25c1b1a7c809](https://cloud.githubusercontent.com/assets/20719532/25981083/a2cc78c0-3705-11e7-9238-d03ff0caa341.png)
