### ISSUE TITLE
Unable to find a specification for ALL 

### ISSUE THREAD

**Issue by Vladius25** [CocoaPods/CocoaPods#6444]
# Report

## What did you do?

 Run `pod install`

## What did you expect to happen?

 Install all pod dependencies correctly.

## What happened instead?

 
`[!] Unable to find a specification for GoogleMaps`
For all dependencies.

### Stack

```
   CocoaPods : 1.2.0
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.6.8
        Host : Mac OS X 10.12.2 (16C67)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.10.1 (Apple Git-78)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : .git - https://github.com/CocoaPods/Specs.git @ HEAD
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Interests' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	
  # Pods for Interests
 pod 'GoogleMaps'
 
  target 'InterestsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'InterestsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```
## Also
`pod repo update --verbose`

```
Updating spec repo `.git`
  $ /usr/bin/git -C /Users/admin/.cocoapods/repos/.git fetch origin
  $ /usr/bin/git -C /Users/admin/.cocoapods/repos/.git rev-parse --abbrev-ref
  HEAD
  HEAD
  $ /usr/bin/git -C /Users/admin/.cocoapods/repos/.git reset --hard origin/HEAD
  fatal: ambiguous argument 'origin/HEAD': unknown revision or path not in the working tree.
  Use '--' to separate paths from revisions, like this:
  'git <command> [<revision>...] -- [<file>...]'
[!] CocoaPods was not able to update the `.git` repo. If this is an unexpected issue and persists you can inspect it running `pod repo update --verbose`

/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/sources_manager.rb:112:in `rescue in update_git_repo'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/sources_manager.rb:106:in `update_git_repo'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.2.0/lib/cocoapods-core/source.rb:334:in `update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/sources_manager.rb:88:in `block (2 levels) in update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/sources_manager.rb:87:in `block in update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/sources_manager.rb:86:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/sources_manager.rb:86:in `update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/command/repo/update.rb:23:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

## What did you do?

`pod repo remove master ; pod setup`
Reinstall cocoapods

**Comment by Vladius25** [comment]
Thank you very much! It's working.

**Comment by Vladius25** [comment]
#
