### ISSUE TITLE
Internal server error when pushing new pod

### ISSUE THREAD

**Issue by ConfusedVorlon** [CocoaPods/CocoaPods#6474]
> Before you start, are you using the latest CocoaPods release?

yes

 [ Y] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod trunk push HSTableView.podspec --verbose`

## What did you expect to happen?

publish pod

## What happened instead?

failure with instructions to check twitter for errors (none seen)

```

<snip>
** BUILD SUCCEEDED **

 -> HSTableView (0.1.0)

opening connection to trunk.cocoapods.org:443...
opened
starting SSL for trunk.cocoapods.org:443...
SSL established
<- "POST /api/v1/pods?allow_warnings=false HTTP/1.1\r\nContent-Type: application/json; charset=utf-8\r\nAccept: application/json; charset=utf-8\r\nUser-Agent: CocoaPods/1.2.0\r\nAuthorization: Token a25ce76b228efe8a70fd8a19897089fd\r\nAccept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3\r\nHost: trunk.cocoapods.org\r\nContent-Length: 1156\r\n\r\n"
<- "{\"name\":\"HSTableView\",\"version\":\"0.1.0\",\"summary\":\"A simpler, more elegant UITableView using objects, blocks and no delegates\",\"description\":\"A simpler, more elegant UITableView. Rows are managed by objects. Things happen with blocks.\\n\\nYour whole table is declared up front with no need for delegates\\n\\nThe table view uses a responder chain approach to provide settings. Any setting can be set at the row level, the section level or the table level.\\n\\nThis allows simple configuration at the table level, and easy customisation at the row level.\\n\\nBlocks are used for tap handlers, delete handlers, etc.\\n\\nDefault (coloured) accessories are supported\\n\\nHSTableView is suitable for situations where there is a known finite number of rows (although the number can change). It doesn\u{2019}t support infinite scrolling tables (you\u{2019}ll have to use UITableView and delegates for that!)\",\"homepage\":\"https://github.com/ConfusedVorlon/HSTableView\",\"license\":\"MIT\",\"authors\":\"Rob Jonson\",\"platforms\":{\"ios\":\"9.0\"},\"source\":{\"git\":\"https://github.com/ConfusedVorlon/HSTableView.git\",\"tag\":\"0.1.0\"},\"source_files\":\"HSTableView\",\"pushed_with_swift_version\":\"3.0\"}\n"
-> "HTTP/1.1 500 Internal Server Error\r\n"
-> "Date: Tue, 07 Feb 2017 15:51:39 GMT\r\n"
-> "Connection: keep-alive\r\n"
-> "Strict-Transport-Security: max-age=31536000\r\n"
-> "Content-Type: application/json\r\n"
-> "Content-Length: 141\r\n"
-> "X-Content-Type-Options: nosniff\r\n"
-> "Server: thin 1.6.2 codename Doc Brown\r\n"
-> "Via: 1.1 vegur\r\n"
-> "\r\n"
reading 141 bytes...
-> "{\"error\":\"An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later.\"}"
read 141 bytes
Conn keep-alive
[!] An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later.

/Users/rob/.rvm/gems/ruby-2.3.0/gems/cocoapods-trunk-1.1.2/lib/pod/command/trunk.rb:70:in `print_error'
/Users/rob/.rvm/gems/ruby-2.3.0/gems/cocoapods-trunk-1.1.2/lib/pod/command/trunk.rb:30:in `request_url'
/Users/rob/.rvm/gems/ruby-2.3.0/gems/cocoapods-trunk-1.1.2/lib/pod/command/trunk.rb:36:in `request_path'
/Users/rob/.rvm/gems/ruby-2.3.0/gems/cocoapods-trunk-1.1.2/lib/pod/command/trunk/push.rb:79:in `push_to_trunk'
/Users/rob/.rvm/gems/ruby-2.3.0/gems/cocoapods-trunk-1.1.2/lib/pod/command/trunk/push.rb:65:in `run'
/Users/rob/.rvm/gems/ruby-2.3.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Users/rob/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.2.0/lib/cocoapods/command.rb:52:in `run'
/Users/rob/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.2.0/bin/pod:55:in `<top (required)>'
/Users/rob/.rvm/gems/ruby-2.3.0/bin/pod:22:in `load'
/Users/rob/.rvm/gems/ruby-2.3.0/bin/pod:22:in `<main>'
/Users/rob/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/Users/rob/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
Retina-iMac-3:HSTableView rob$ pod trunk push HSTableView.podspec --verbose
```

### Stack

```
   CocoaPods : 1.2.0
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.6.3
        Host : Mac OS X 10.12.3 (16D32)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.10.1 (Apple Git-78)
Ruby lib dir : /Users/rob/.rvm/rubies/ruby-2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 2875e9fb983932700917632035be09f6200903ba
```

### Installation Source

```
Executable Path: /Users/rob/.rvm/gems/ruby-2.3.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

https://github.com/ConfusedVorlon/HSTableView

**Comment by fins** [comment]
Today I'm having very similar error right now.

**Comment by segiddins** [comment]
Thanks for the heads up -- please try again now

**Comment by segiddins** [comment]
(I think this was https://github.com/CocoaPods/trunk.cocoapods.org/issues/207 again)

**Comment by ConfusedVorlon** [comment]
worked for me. Thanks.

**Comment by invisibleBully** [comment]
This is happening again.
