### ISSUE TITLE
[OSX] xcodebuild:  error: You don’t have permission to save the file “Info.plist” in the folder “Resources”.

### ISSUE THREAD

**Issue by andrewBatutin** [CocoaPods/CocoaPods#6491]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

pod trunk push JSONRPCom.podspec --verbose

## What did you expect to happen?

Successful pod push

## What happened instead?

xcodebuild error 
```
> [OSX] xcodebuild:  error: You don’t have permission to save the file “Info.plist” in the folder “Resources”.

`** BUILD FAILED **


The following build commands failed:
	ProcessInfoPlistFile /Users/andrewbatutin/Library/Developer/Xcode/DerivedData/App-egvugseotxpuswhecsilyuordmgz/Build/Products/Release/JSONRPCom/JSONRPCom.framework/Versions/A/Resources/Info.plist Target\ Support\ Files/JSONRPCom/Info.plist
(1 failure)
 -> JSONRPCom (0.0.4)
    - ERROR | [OSX] xcodebuild: Returned an unsuccessful exit code.
    - NOTE  | [OSX] xcodebuild:  error: You don’t have permission to save the file “Info.plist” in the folder “Resources”.

[!] The spec did not pass validation, due to 1 error.
[!] The validator for Swift projects uses Swift 3.0 by default, if you are using a different version of swift you can use a `.swift-version` file to set the version for your Pod. For example to use Swift 2.3, run:
    `echo "2.3" > .swift-version`.

/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-1.1.2/lib/pod/command/trunk/push.rb:121:in `validate_podspec'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-1.1.2/lib/pod/command/trunk/push.rb:64:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'`
```

### Stack

```
   CocoaPods : 1.2.0
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.2 (16C67)
       Xcode : 8.0 (8A218a)
         Git : git version 2.11.1
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : andrewbatutin - https://github.com/andrewBatutin/JSONRPCom.git @ b3336d27497be7c10d7ae89e35a012e61bdeeced
               AVS - https://bitbucket.org/testrunner/avs.git @ 06b7342cacff9a6b389d524bdee1616c4aec0f24
               bitbucket-avs - https://Randall_Stephens@bitbucket.org/Randall_Stephens/avs.git @ 56194059fd1b1d1cc17f1d16e3e4add9cf36b978
               bitbucket-avs-1 - https://Randall_Stephens@bitbucket.org/testrunner/avs.git @ 8f4911ea81ec84d99188ccb4ae8fd2d1ac75e962
               bitbucket-testrunner-avs - https://bitbucket.org/testrunner/avs.git @ 7c03895d3263f71b7afedbb52f140942a71cffba
               master - https://github.com/CocoaPods/Specs.git @ 2a3fb24aaadb3244f8683fc561c3e04f0e4cd7e2
               pods_tests - git@bitbucket.org:andriy_batutin/pods_test.git @ 3d4e7aa34c75718a0eacc35cf3cd25a38b6005cb
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'JSONRPCom' do
	pod "Mantle"
end

target 'JSONRPComTests' do
	
end

target 'sndbx' do

end
```

## Project that demonstrates the issue

https://github.com/andrewBatutin/JSONRPCom

## Additional info

pod lib lint works just fine

no idea what's wrong

tried latest and v 1.1.0 of cocopods - no pregres

Thnx

**Comment by andrewBatutin** [comment]
fixed by adding --use-libraries flag
