### ISSUE TITLE
pod search  error

### ISSUE THREAD

**Issue by dacaiguoguo** [CocoaPods/CocoaPods#6503]
### Command

```
/Users/dacai/.rvm/gems/ruby-2.2.5@pod111/bin/pod search --simple AF
```

### Report

* What did you do?
```
pod search --simple AF
```

* What did you expect to happen?
```
show result
```
* What happened instead?
```
error
```
already try `rm -rf ~/Library/Caches/CocoaPods` no help

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.2.5p319 (2016-04-26 revision 54774) [x86_64-darwin16]
    RubyGems : 2.6.7
        Host : Mac OS X 10.12.3 (16D25a)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.10.1 (Apple Git-78)
Ruby lib dir : /Users/dacai/.rvm/rubies/ruby-2.2.5/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ e409f1663957df99cb869accfcaea6631acc07b5
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
```

### Error

```
Errno::ENOENT - No such file or directory - most
/Users/dacai/.rvm/gems/ruby-2.2.5@pod111/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:379:in `popen'
/Users/dacai/.rvm/gems/ruby-2.2.5@pod111/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:379:in `with_pager'
/Users/dacai/.rvm/gems/ruby-2.2.5@pod111/gems/cocoapods-search-1.0.0/lib/cocoapods-search/command/search.rb:94:in `local_search'
/Users/dacai/.rvm/gems/ruby-2.2.5@pod111/gems/cocoapods-search-1.0.0/lib/cocoapods-search/command/search.rb:63:in `run'
/Users/dacai/.rvm/gems/ruby-2.2.5@pod111/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Users/dacai/.rvm/gems/ruby-2.2.5@pod111/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/Users/dacai/.rvm/gems/ruby-2.2.5@pod111/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/Users/dacai/.rvm/gems/ruby-2.2.5@pod111/bin/pod:22:in `load'
/Users/dacai/.rvm/gems/ruby-2.2.5@pod111/bin/pod:22:in `<main>'
/Users/dacai/.rvm/gems/ruby-2.2.5@pod111/bin/ruby_executable_hooks:15:in `eval'
/Users/dacai/.rvm/gems/ruby-2.2.5@pod111/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by dacaiguoguo** [comment]
### found reason !

pager set error
```
export PAGER="most"
```
I change to less 
```
export PAGER="less"
```
