### ISSUE TITLE
LoadError - cannot load such file -- macho

### ISSUE THREAD

**Issue by YW-Keep** [CocoaPods/CocoaPods#6519]
```
LoadError - cannot load such file -- macho
/Users/tang/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-d1.2.0/lib/cocoapods/sandbox/file_accessor.rb:377:in `rescue in dynamic_binary?'
/Users/tang/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.2.0/lib/cocoapods/sandbox/file_accessor.rb:375:in `dynamic_binary?'
/Users/tang/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.2.0/lib/cocoapods/sandbox/file_accessor.rb:214:in `block in vendored_dynamic_libraries'
/Users/tang/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.2.0/lib/cocoapods/sandbox/file_accessor.rb:213:in `select'
/Users/tang/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.2.0/lib/cocoapods/sandbox/file_accessor.rb:213:in `vendored_dynamic_libraries'
/Users/tang/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.2.0/lib/cocoapods/sandbox/file_accessor.rb:222:in `vendored_static_libraries'
/Users/tang/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.2.0/lib/cocoapods/sandbox/file_accessor.rb:236:in `vendored_static_artifacts'
/Users/tang/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.2.0/lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb:56:in `block in generate'
/Users/tang/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.2.0/lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb:56:in `any?'
/Users/tang/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.2.0/lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb:56:in `generate'
/Users/tang/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.2.0/lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb:39:in `save_as'
/Users/tang/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.2.0/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:87:in `block in create_xcconfig_file'
/Users/tang/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.2.0/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:84:in `each'
/Users/tang/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.2.0/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:84:in `create_xcconfig_file'
/Users/tang/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.2.0/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:18:in `block in install!'
/Users/tang/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.2.0/lib/cocoapods/user_interface.rb:142:in `message'
/Users/tang/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.2.0/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:14:in `install!'
/Users/tang/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.2.0/lib/cocoapods/installer/xcode/pods_project_generator.rb:160:in `block (2 levels) in install_libraries'
/Users/tang/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.2.0/lib/cocoapods/installer/xcode/pods_project_generator.rb:158:in `each'
/Users/tang/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.2.0/lib/cocoapods/installer/xcode/pods_project_generator.rb:158:in `block in install_libraries'
/Users/tang/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.2.0/lib/cocoapods/user_interface.rb:142:in `message'
/Users/tang/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.2.0/lib/cocoapods/installer/xcode/pods_project_generator.rb:152:in `install_libraries'
/Users/tang/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.2.0/lib/cocoapods/installer/xcode/pods_project_generator.rb:64:in `generate!'
/Users/tang/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:179:in `block in generate_pods_project'
/Users/tang/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.2.0/lib/cocoapods/user_interface.rb:64:in `section'
/Users/tang/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:178:in `generate_pods_project'
/Users/tang/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:115:in `install!'
/Users/tang/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.2.0/lib/cocoapods/command/install.rb:37:in `run'
/Users/tang/.rvm/gems/ruby-2.2.4/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Users/tang/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.2.0/lib/cocoapods/command.rb:52:in `run'
/Users/tang/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.2.0/bin/pod:55:in `<top (required)>'
/Users/tang/.rvm/rubies/ruby-2.2.4/bin/pod:22:in `load'
/Users/tang/.rvm/rubies/ruby-2.2.4/bin/pod:22:in `<main>'
/Users/tang/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `eval'
/Users/tang/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `<main>'
```
   i  pod  install  then, like this

**Comment by dnkoutso** [comment]
Can you paste your podfile please?

**Comment by dnkoutso** [comment]
Do you have `ruby-macho` gem installed? `gem install ruby-macho`?

**Comment by YW-Keep** [comment]
platform :ios, '8.0'
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'        #官方仓库地址
source 'git@114.55.31.119:xcar-ios/private-pod-library.git'       #私有仓库地址
target 'boxster' do

pod 'MJRefresh'
pod 'Masonry'
pod 'SDWebImage'
pod 'MBProgressHUD','~> 0.9.2'
pod 'YYModel'
pod 'CARGateway'
pod 'AliyunOSSiOS'
pod 'ShareSDK3'
pod 'MOBFoundation'
pod 'IQKeyboardManager'
pod 'AliPay'
pod 'TZImagePickerController'
pod 'ShareSDK3/ShareSDKUI'
pod 'ShareSDK3/ShareSDKPlatforms/QQ'
pod 'ShareSDK3/ShareSDKPlatforms/SinaWeibo'
pod 'ShareSDK3/ShareSDKPlatforms/WeChat'
pod 'BaiduMapKit' #百度地图SDK

end
post_install do |installer|

installer.pods_project.targets.each do |target|

target.build_configurations.each do |config|

config.build_settings['ENABLE_BITCODE'] = 'NO'

end

end

end

**Comment by YW-Keep** [comment]
I am  sure  ruby-macho  installed, I have tried.

**Comment by kjian** [comment]
You have installed multiple macho, uninstall all of them until the lastest one.

**Comment by YW-Keep** [comment]
yes,you are right

**Comment by benasher44** [comment]
@YW-Keep glad you got it figured out! I'm going to close this one, since it appears you were able to get your gem issues resolved. Have a great day!
