### ISSUE TITLE
- ERROR | [iOS] unknown: Encountered an unknown error (No such file or directory @ rb_file_s_rename

### ISSUE THREAD

**Issue by pengjinning** [CocoaPods/CocoaPods#6538]
```
[!] Found podspec `AppKeFu.podspec`

Updating spec repo `master`
Validating podspec
    AppKeFu (4.4.3) - Analyzing on iOS 8.0 platform.
  Preparing

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-App`: (``)

Fetching external sources
-> Fetching podspec for `AppKeFu` from `/Users/ningjinpeng/Desktop/CocoapodsMy/AppKeFu-iOS/AppKeFu.podspec`

Resolving dependencies of 

Comparing resolved specification to the sandbox manifest
  A AppKeFu

Downloading dependencies

-> Installing AppKeFu (4.4.3)
  > Copying AppKeFu from `/Users/ningjinpeng/Library/Caches/CocoaPods/Pods/External/AppKeFu/052a7d662caa327356e6f7f55a520d7f-7e79f` to
  `../../../../../private/var/folders/zv/t8k141l91cn431wwvv6m_c7m0000gn/T/CocoaPods/Lint/Pods/AppKeFu`
  - Running pre install hooks

Generating Pods project
  - Creating Pods project
  - Adding source files to Pods project
  - Adding frameworks to Pods project
  - Adding libraries to Pods project
  - Adding resources to Pods project
  - Linking headers
  - Installing targets
    - Installing target `Pods-App` iOS 8.0
      - Generating Info.plist file at `../../../../../private/var/folders/zv/t8k141l91cn431wwvv6m_c7m0000gn/T/CocoaPods/Lint/Pods/Target Support
      Files/Pods-App/Info.plist`
      - Generating module map file at `../../../../../private/var/folders/zv/t8k141l91cn431wwvv6m_c7m0000gn/T/CocoaPods/Lint/Pods/Target Support
      Files/Pods-App/Pods-App.modulemap`
      - Generating umbrella header at `../../../../../private/var/folders/zv/t8k141l91cn431wwvv6m_c7m0000gn/T/CocoaPods/Lint/Pods/Target Support
      Files/Pods-App/Pods-App-umbrella.h`
  - Running post install hooks
  - Writing Xcode project file to `../../../../../private/var/folders/zv/t8k141l91cn431wwvv6m_c7m0000gn/T/CocoaPods/Lint/Pods/Pods.xcodeproj`
  - Writing Lockfile in `../../../../../var/folders/zv/t8k141l91cn431wwvv6m_c7m0000gn/T/CocoaPods/Lint/Podfile.lock`
  - Writing Manifest in `../../../../../private/var/folders/zv/t8k141l91cn431wwvv6m_c7m0000gn/T/CocoaPods/Lint/Pods/Manifest.lock`

Integrating client project

[!] Please close any current Xcode sessions and use `App.xcworkspace` for this project from now on.

Integrating target `Pods-App` (`../../../../../var/folders/zv/t8k141l91cn431wwvv6m_c7m0000gn/T/CocoaPods/Lint/App.xcodeproj` project)
  Adding Build Phase '[CP] Embed Pods Frameworks' to project.
  Adding Build Phase '[CP] Copy Pods Resources' to project.
  Adding Build Phase '[CP] Check Pods Manifest.lock' to project.
  - Running post install hooks

-> Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.
 -> AppKeFu (4.4.3)
    - ERROR | [iOS] unknown: Encountered an unknown error (No such file or directory @ rb_file_s_rename - (/private/var/folders/zv/t8k141l91cn431wwvv6m_c7m0000gn/T/CocoaPods/Lint/Pods/Pods.xcodeproj/xcuserdata/ningjinpeng.xcuserdatad/xcschemes/AppKeFu.xcscheme, /private/var/folders/zv/t8k141l91cn431wwvv6m_c7m0000gn/T/CocoaPods/Lint/Pods/Pods.xcodeproj/xcshareddata/xcschemes/AppKeFu.xcscheme)
/usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/fileutils.rb:462:in `rename'
/usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/fileutils.rb:462:in `block in mv'
/usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/fileutils.rb:1454:in `block in fu_each_src_dest'
/usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/fileutils.rb:1470:in `fu_each_src_dest0'
/usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/fileutils.rb:1452:in `fu_each_src_dest'
/usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/fileutils.rb:451:in `mv'
/usr/local/lib/ruby/gems/2.4.0/gems/xcodeproj-1.4.2/lib/xcodeproj/scheme.rb:244:in `share_scheme'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.2.1.beta.1/lib/cocoapods/validator.rb:431:in `add_app_project_import'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.2.1.beta.1/lib/cocoapods/validator.rb:307:in `block in perform_extensive_analysis'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.2.1.beta.1/lib/cocoapods/validator.rb:298:in `each'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.2.1.beta.1/lib/cocoapods/validator.rb:298:in `perform_extensive_analysis'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.2.1.beta.1/lib/cocoapods/validator.rb:79:in `validate'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-trunk-1.1.2/lib/pod/command/trunk/push.rb:119:in `validate_podspec'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-trunk-1.1.2/lib/pod/command/trunk/push.rb:64:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.2.1.beta.1/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.2.1.beta.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
) during validation.

[!] The spec did not pass validation, due to 1 error.

/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-trunk-1.1.2/lib/pod/command/trunk/push.rb:121:in `validate_podspec'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-trunk-1.1.2/lib/pod/command/trunk/push.rb:64:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.2.1.beta.1/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.2.1.beta.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'

# Report

## What did you do?

ℹ pod trunk push 

## What did you expect to happen?

ℹ update my framework to cocoapod

## What happened instead?

ℹ -> AppKeFu (4.4.3)
    - ERROR | [iOS] unknown: Encountered an unknown error (No such file or directory @ rb_file_s_rename - (/private/var/folders/zv/t8k141l91cn431wwvv6m_c7m0000gn/T/CocoaPods/Lint/Pods/Pods.xcodeproj/xcuserdata/ningjinpeng.xcuserdatad/xcschemes/AppKeFu.xcscheme, /private/var/folders/zv/t8k141l91cn431wwvv6m_c7m0000gn/T/CocoaPods/Lint/Pods/Pods.xcodeproj/xcshareddata/xcschemes/AppKeFu.xcscheme)

## CocoaPods Environment

ℹ ### Stack

```
   CocoaPods : 1.2.1.beta.1
        Ruby : ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
    RubyGems : 2.6.8
        Host : Mac OS X 10.12.3 (16D32)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.10.1 (Apple Git-78)
Ruby lib dir : /usr/local/Cellar/ruby/2.4.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ d7a235b9a7b642063de4986938bf3d780751daf1
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0

## Project that demonstrates the issue

ℹ https://github.com/pengjinning/AppKeFu-iOS.git
```

**Comment by dnkoutso** [comment]
Need to see `AppKeFu.podspec` is it published?

**Comment by pengjinning** [comment]
this is AppKeFu.podspec:


Pod::Spec.new do |s|

  s.name         = "AppKeFu"
  s.version      = "4.4.3"
  s.summary      = "iOS Helpdesk framework."
  s.description  = <<-DESC
                  Online chat Lib for ios, Helpdesk system
                   DESC
  s.homepage     = "http://www.appkefu.com"
  s.license      = "MIT"
  s.author       = { "jackning" => "pengjinning@163.com" }
  s.platform     = :ios, "8.0"
  s.source       = { :git => "https://github.com/pengjinning/AppKeFu-iOS.git", :tag => "#{s.version}" }
  s.vendored_frameworks = "frameworks/cocoapods/AppKeFuFramework.framework"
  s.resource     = "frameworks/cocoapods/AppKeFuResources.bundle"
  s.requires_arc = true
  s.xcconfig     = { "ENABLE_BITCODE" => "NO" }

end

AppKeFu previous version is 4.4.2

**Comment by karalabe** [comment]
This same thing just began to happen on our pods too. We've been regularly pushing with no errors and we haven't updated out pod-specs for months. Perhaps the latest beta release broke something?

**Comment by Vinclai** [comment]
Same issue with 1.2.1 try to pod trunk or pod lint .podspec with framework inside. Spend more then four hours, and now i'm just Install version 1.1.1 and all working from first attemp

**Comment by dnkoutso** [comment]
I just used: 

`pod spec lint AppKeFu.podspec --verbose` 

And got:

```** BUILD SUCCEEDED **

 -> AppKeFu (4.4.3)

Analyzed 1 podspec.

AppKeFu.podspec passed validation.```

**Comment by pengjinning** [comment]
I downgrade my cocoapods to version 1.1.1, and it worked for me now

**Comment by dnkoutso** [comment]
@pengjinning I'd like to understand if this is a regression from 1.2.1.beta.1. Wonder if this is related https://github.com/CocoaPods/CocoaPods/issues/6373

**Comment by pengjinning** [comment]
I uninstalled 1.2.1.beta.1, then reinstalled version 1.1.1

**Comment by Vinclai** [comment]
@pengjinning You may install two version at the same time:
```
sudo gem install cocoapods -v 1.1.1
```
Then you just write version, something like that:
```
pod _1.1.1_ spec lint
```

**Comment by dnkoutso** [comment]
This may be fixed by https://github.com/CocoaPods/CocoaPods/pull/6558
