### ISSUE TITLE
Unable to find a specification for 'Pod file' after Using `ARCHS` setting to build architectures of target

### ISSUE THREAD

**Issue by KiranJasvanee** [CocoaPods/CocoaPods#6539]
When I tried to pod my own uploaded library created on Swift 3.0.1, I unable to do it. I don't able to understand by below error that, is it because of anything wrong I've done while uploading or something wrong while I'm pod install. 

```
Kiran-Jasvanee-MAC241:trial-1 mac241$ pod install --verbose
  Preparing

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-trial-1`: (``)

Resolving dependencies of `Podfile`
[!] Unable to find a specification for `KJCurveSlider`

/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/resolver.rb:442:in `handle_resolver_error'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/resolver.rb:65:in `rescue in resolve'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/resolver.rb:57:in `resolve'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/installer/analyzer.rb:719:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/installer/analyzer.rb:717:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/installer/analyzer.rb:76:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:236:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:150:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:149:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:110:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/command/install.rb:37:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by benasher44** [comment]
Hi @KiranJasvanee! Thanks for the report! Can you please post your Podfile? Thanks!

**Comment by KiranJasvanee** [comment]
Hi @benasher44 Benasher, It's working fine now, the issue was I had a dependency of objective-c files and my own library swift code was less compare to it. That's github algo might have choose objective-c rather than swift.  But I'm facing another issue, if you might've idea about it, my pod is not downloading by using simply (pod 'KJCurveSlider') in a pod file, I've to add pod name with path (pod 'KJCurveSlider', :git => 'https://github.com/KiranJasvanee/KJCurveSlider') to get it worked. Any idea why it's happening! Thanks

**Comment by benasher44** [comment]
Have you published a podspec for that pod?
