### ISSUE TITLE
Crash occured while `pod install`

### ISSUE THREAD

**Issue by chashmeetsingh** [CocoaPods/CocoaPods#6570]
### Stack

```
   CocoaPods : 1.2.0
        Ruby : ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]
    RubyGems : 2.4.5.1
        Host : Mac OS X 10.12.3 (16D32)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.10.1 (Apple Git-78)
Ruby lib dir : /Users/exxon/.rvm/rubies/ruby-2.2.3/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 3cd60f215513516e28bb7dc73102e0f6e8e0e5b9
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Susi' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Susi
  pod 'Material'
  pod 'Toast-Swift', '~> 2.0.0'
  pod 'Alamofire', '~> 4.4'
  pod 'SwiftyJSON'
  pod 'RealmSwift'
  pod 'Popover'
  pod 'SwiftValidators'
  pod 'ALTextInputBar'
end
```

### Error

```
Errno::EPERM - Operation not permitted @ chmod_internal - /Users/exxon/Projects/susi_iOS/Pods/SwiftValidators/Sources/Phone.swift
/Users/exxon/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/fileutils.rb:1344:in `chmod'
/Users/exxon/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/fileutils.rb:1344:in `chmod'
/Users/exxon/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/fileutils.rb:999:in `block in chmod'
/Users/exxon/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/fileutils.rb:998:in `each'
/Users/exxon/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/fileutils.rb:998:in `chmod'
/Users/exxon/.rvm/gems/ruby-2.2.3/gems/cocoapods-1.2.0/lib/cocoapods/installer/pod_source_installer.rb:99:in `block in unlock_files!'
/Users/exxon/.rvm/gems/ruby-2.2.3/gems/cocoapods-1.2.0/lib/cocoapods/installer/pod_source_installer.rb:191:in `[]'
/Users/exxon/.rvm/gems/ruby-2.2.3/gems/cocoapods-1.2.0/lib/cocoapods/installer/pod_source_installer.rb:191:in `block (2 levels) in each_source_file'
/Users/exxon/.rvm/gems/ruby-2.2.3/gems/cocoapods-1.2.0/lib/cocoapods/installer/pod_source_installer.rb:189:in `each'
/Users/exxon/.rvm/gems/ruby-2.2.3/gems/cocoapods-1.2.0/lib/cocoapods/installer/pod_source_installer.rb:189:in `block in each_source_file'
/Users/exxon/.rvm/gems/ruby-2.2.3/gems/cocoapods-1.2.0/lib/cocoapods/installer/pod_source_installer.rb:188:in `each'
/Users/exxon/.rvm/gems/ruby-2.2.3/gems/cocoapods-1.2.0/lib/cocoapods/installer/pod_source_installer.rb:188:in `each_source_file'
/Users/exxon/.rvm/gems/ruby-2.2.3/gems/cocoapods-1.2.0/lib/cocoapods/installer/pod_source_installer.rb:98:in `unlock_files!'
/Users/exxon/.rvm/gems/ruby-2.2.3/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:377:in `block in unlock_pod_sources'
/Users/exxon/.rvm/gems/ruby-2.2.3/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:375:in `each'
/Users/exxon/.rvm/gems/ruby-2.2.3/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:375:in `unlock_pod_sources'
/Users/exxon/.rvm/gems/ruby-2.2.3/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:471:in `perform_post_install_actions'
/Users/exxon/.rvm/gems/ruby-2.2.3/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:121:in `install!'
/Users/exxon/.rvm/gems/ruby-2.2.3/gems/cocoapods-1.2.0/lib/cocoapods/command/install.rb:37:in `run'
/Users/exxon/.rvm/gems/ruby-2.2.3/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Users/exxon/.rvm/gems/ruby-2.2.3/gems/cocoapods-1.2.0/lib/cocoapods/command.rb:52:in `run'
/Users/exxon/.rvm/gems/ruby-2.2.3/gems/cocoapods-1.2.0/bin/pod:55:in `<top (required)>'
/Users/exxon/.rvm/gems/ruby-2.2.3/bin/pod:23:in `load'
/Users/exxon/.rvm/gems/ruby-2.2.3/bin/pod:23:in `<main>'
/Users/exxon/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
/Users/exxon/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'

**Comment by dnkoutso** [comment]
Seems like a file permission issue, we could do a better job at the error message.

**Comment by chashmeetsingh** [comment]
running pod install caused this, now can't even run that.

**Comment by benasher44** [comment]
Maybe this was run with `sudo` at some point? Can you show the permissions of the Pods directory and all of the directories leading through to `Pods/SwiftValidators/Sources/Phone.swift` please? Thanks!

**Comment by chashmeetsingh** [comment]
Yes @benasher44 you are right, I did run it with sudo once because of some swiftlint file permission error.

**Comment by benasher44** [comment]
Ah okay great. This is likely just a local permissions issue then, which can be resolved. Y forcefully removing the Pods directory and running `pod install` again as the local user. I'm going to close this, since there doesn't appear to be action for CocoaPods to take here.
