### ISSUE TITLE
'pod install' failure

### ISSUE THREAD

**Issue by flostik2008** [CocoaPods/CocoaPods#6600]
### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do? - pod install 

* What did you expect to happen? - installation of all specified dependencies.

* What happened instead? - '[!] Oh no, an error occurred.'

### Stack

```
   CocoaPods : 1.1.0.rc.2
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.6 (15G31)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.10.1 (Apple Git-78)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 933a96aa26061400a1216c790f38e0167e18f1f9
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '10.0'

use_frameworks!

pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'FirebaseUI'

target 'DatabaseExample' do
end
target 'DatabaseExampleSwift' do
end
target 'DatabaseExampleTests' do
end
```

### Error

```
Errno::EEXIST - File exists - /Users/564n/Desktop/iOSDev2/FirebaseSamples/quickstart-ios/database/Pods/Target Support Files/Bolts
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/xcode/pods_project_generator/target_installer.rb:92:in `mkdir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/xcode/pods_project_generator/target_installer.rb:92:in `mkdir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/xcode/pods_project_generator/target_installer.rb:92:in `create_support_files_dir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:21:in `block in install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/user_interface.rb:142:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:19:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:155:in `block (2 levels) in install_libraries'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:153:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:153:in `block in install_libraries'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/user_interface.rb:142:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:152:in `install_libraries'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:64:in `generate!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:179:in `block in generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:178:in `generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:115:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/command/install.rb:37:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by dnkoutso** [comment]
@flostik2008 installation worked for me on a sample app with two targets.

```
Downloading dependencies
Installing Bolts (1.8.4)
Installing FBSDKCoreKit (4.20.2)
Installing FBSDKLoginKit (4.20.2)
Installing Fabric (1.6.11)
Installing Firebase (3.15.0)
Installing FirebaseAnalytics (3.7.0)
Installing FirebaseAuth (3.1.1)
Installing FirebaseCore (3.5.2)
Installing FirebaseDatabase (3.1.2)
Installing FirebaseInstanceID (1.0.9)
Installing FirebaseStorage (1.1.0)
Installing FirebaseUI (3.1.1)
Installing GTMOAuth2 (1.1.4)
Installing GTMSessionFetcher (1.1.9)
Installing GoogleSignIn (4.0.2)
Installing GoogleToolboxForMac (2.1.1)
Installing SDWebImage (4.0.0)
Installing TwitterCore (2.8.0)
Installing TwitterKit (2.8.1)
Generating Pods project
Integrating client project
Pod installation complete! There are 3 dependencies from the Podfile and 19 total pods installed
```

If you delete the `Pods/` folder and try again does it work?

It seems you are also using CocoaPods 1.1.0.rc.2 can you please update to 1.2.0 or 1.2.1.beta.1?

**Comment by flostik2008** [comment]
@dnkoutso  awesome, worked after updating cocoapods and deleting the Pods/ folder. 
Issue is resolved.
