### ISSUE TITLE
LoadError - cannot load such file -- macho

### ISSUE THREAD

**Issue by ehlersd** [CocoaPods/CocoaPods#6602]
I previously had this problem, had to revert back to 1.1.1.  Updated again to cocoapods 1.2.0 and I'm getting the same macho error as before. Everything was working fine with v1.1.1.

gem which macho returns:

/Users/darrenehlers/.rvm/gems/ruby-2.2.3/gems/ruby-macho-1.0.0/lib/macho.rb

I reverted back to cocoapods 1.1.1 and it's back working fine. Something with the 1.2.0 setup.

### Command

```
/Users/darrenehlers/.rvm/gems/ruby-2.2.3/bin/pod lib lint --sources=http://xxx.xxx.xxx/private-cocoapods.git,master --private
```

### Report

* What did you do?

Running lint on my podspec

* What did you expect to happen?

Success reported

* What happened instead?

Ruby crash

### Stack

```
   CocoaPods : 1.2.0
        Ruby : ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin16]
    RubyGems : 2.4.8
        Host : Mac OS X 10.12.5 (16F43c)
       Xcode : 8.3 (8E162)
         Git : git version 2.11.0 (Apple Git-81)
Ruby lib dir : /Users/darrenehlers/.rvm/rubies/ruby-2.2.3/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ f6ec45710fbe2df3e024e7b68bf1ee54096b8681
               Private-Cocoapods - http://xxx.xxx.xxx/private-cocoapods.git @ 1687940e7e990462a60b6c11bfcb838b60dfee29
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
```

### Error

```
LoadError - cannot load such file -- macho
/Users/darrenehlers/.rvm/gems/ruby-2.2.3@global/gems/cocoapods-1.2.0/lib/cocoapods/sandbox/file_accessor.rb:377:in `rescue in dynamic_binary?'
/Users/darrenehlers/.rvm/gems/ruby-2.2.3@global/gems/cocoapods-1.2.0/lib/cocoapods/sandbox/file_accessor.rb:375:in `dynamic_binary?'
/Users/darrenehlers/.rvm/gems/ruby-2.2.3@global/gems/cocoapods-1.2.0/lib/cocoapods/sandbox/file_accessor.rb:162:in `block in vendored_dynamic_frameworks'
/Users/darrenehlers/.rvm/gems/ruby-2.2.3@global/gems/cocoapods-1.2.0/lib/cocoapods/sandbox/file_accessor.rb:161:in `select'
/Users/darrenehlers/.rvm/gems/ruby-2.2.3@global/gems/cocoapods-1.2.0/lib/cocoapods/sandbox/file_accessor.rb:161:in `vendored_dynamic_frameworks'
/Users/darrenehlers/.rvm/gems/ruby-2.2.3@global/gems/cocoapods-1.2.0/lib/cocoapods/sandbox/file_accessor.rb:170:in `vendored_static_frameworks'
/Users/darrenehlers/.rvm/gems/ruby-2.2.3@global/gems/cocoapods-1.2.0/lib/cocoapods/sandbox/file_accessor.rb:236:in `vendored_static_artifacts'
/Users/darrenehlers/.rvm/gems/ruby-2.2.3@global/gems/cocoapods-1.2.0/lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb:56:in `block in generate'
/Users/darrenehlers/.rvm/gems/ruby-2.2.3@global/gems/cocoapods-1.2.0/lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb:56:in `any?'
/Users/darrenehlers/.rvm/gems/ruby-2.2.3@global/gems/cocoapods-1.2.0/lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb:56:in `generate'
/Users/darrenehlers/.rvm/gems/ruby-2.2.3@global/gems/cocoapods-1.2.0/lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb:39:in `save_as'
/Users/darrenehlers/.rvm/gems/ruby-2.2.3@global/gems/cocoapods-1.2.0/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:87:in `block in create_xcconfig_file'
/Users/darrenehlers/.rvm/gems/ruby-2.2.3@global/gems/cocoapods-1.2.0/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:84:in `each'
/Users/darrenehlers/.rvm/gems/ruby-2.2.3@global/gems/cocoapods-1.2.0/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:84:in `create_xcconfig_file'
/Users/darrenehlers/.rvm/gems/ruby-2.2.3@global/gems/cocoapods-1.2.0/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:18:in `block in install!'
/Users/darrenehlers/.rvm/gems/ruby-2.2.3@global/gems/cocoapods-1.2.0/lib/cocoapods/user_interface.rb:142:in `message'
/Users/darrenehlers/.rvm/gems/ruby-2.2.3@global/gems/cocoapods-1.2.0/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:14:in `install!'
/Users/darrenehlers/.rvm/gems/ruby-2.2.3@global/gems/cocoapods-1.2.0/lib/cocoapods/installer/xcode/pods_project_generator.rb:160:in `block (2 levels) in install_libraries'
/Users/darrenehlers/.rvm/gems/ruby-2.2.3@global/gems/cocoapods-1.2.0/lib/cocoapods/installer/xcode/pods_project_generator.rb:158:in `each'
/Users/darrenehlers/.rvm/gems/ruby-2.2.3@global/gems/cocoapods-1.2.0/lib/cocoapods/installer/xcode/pods_project_generator.rb:158:in `block in install_libraries'
/Users/darrenehlers/.rvm/gems/ruby-2.2.3@global/gems/cocoapods-1.2.0/lib/cocoapods/user_interface.rb:142:in `message'
/Users/darrenehlers/.rvm/gems/ruby-2.2.3@global/gems/cocoapods-1.2.0/lib/cocoapods/installer/xcode/pods_project_generator.rb:152:in `install_libraries'
/Users/darrenehlers/.rvm/gems/ruby-2.2.3@global/gems/cocoapods-1.2.0/lib/cocoapods/installer/xcode/pods_project_generator.rb:64:in `generate!'
/Users/darrenehlers/.rvm/gems/ruby-2.2.3@global/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:179:in `block in generate_pods_project'
/Users/darrenehlers/.rvm/gems/ruby-2.2.3@global/gems/cocoapods-1.2.0/lib/cocoapods/user_interface.rb:64:in `section'
/Users/darrenehlers/.rvm/gems/ruby-2.2.3@global/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:178:in `generate_pods_project'
/Users/darrenehlers/.rvm/gems/ruby-2.2.3@global/gems/cocoapods-1.2.0/lib/cocoapods/validator.rb:481:in `block in install_pod'
/Users/darrenehlers/.rvm/gems/ruby-2.2.3@global/gems/cocoapods-1.2.0/lib/cocoapods/validator.rb:481:in `each'
/Users/darrenehlers/.rvm/gems/ruby-2.2.3@global/gems/cocoapods-1.2.0/lib/cocoapods/validator.rb:481:in `install_pod'
/Users/darrenehlers/.rvm/gems/ruby-2.2.3@global/gems/cocoapods-1.2.0/lib/cocoapods/validator.rb:303:in `block in perform_extensive_analysis'
/Users/darrenehlers/.rvm/gems/ruby-2.2.3@global/gems/cocoapods-1.2.0/lib/cocoapods/validator.rb:295:in `each'
/Users/darrenehlers/.rvm/gems/ruby-2.2.3@global/gems/cocoapods-1.2.0/lib/cocoapods/validator.rb:295:in `perform_extensive_analysis'
/Users/darrenehlers/.rvm/gems/ruby-2.2.3@global/gems/cocoapods-1.2.0/lib/cocoapods/validator.rb:79:in `validate'
/Users/darrenehlers/.rvm/gems/ruby-2.2.3@global/gems/cocoapods-1.2.0/lib/cocoapods/command/lib/lint.rb:62:in `block in run'
/Users/darrenehlers/.rvm/gems/ruby-2.2.3@global/gems/cocoapods-1.2.0/lib/cocoapods/command/lib/lint.rb:50:in `each'
/Users/darrenehlers/.rvm/gems/ruby-2.2.3@global/gems/cocoapods-1.2.0/lib/cocoapods/command/lib/lint.rb:50:in `run'
/Users/darrenehlers/.rvm/gems/ruby-2.2.3/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Users/darrenehlers/.rvm/gems/ruby-2.2.3@global/gems/cocoapods-1.2.0/lib/cocoapods/command.rb:52:in `run'
/Users/darrenehlers/.rvm/gems/ruby-2.2.3@global/gems/cocoapods-1.2.0/bin/pod:55:in `<top (required)>'
/Users/darrenehlers/.rvm/gems/ruby-2.2.3/bin/pod:23:in `load'
/Users/darrenehlers/.rvm/gems/ruby-2.2.3/bin/pod:23:in `<main>'
```

**Comment by dnkoutso** [comment]
Weird @ehlersd for me `macho` returns `ruby-macho-0.2.6/lib/macho.rb`

If you switch and `gem uninstall macho` and `gem install macho` again does it work?

**Comment by ehlersd** [comment]
`gem install macho` gives me this error:

```
ERROR:  Could not find a valid gem 'macho' (>= 0) in any repository
ERROR:  Possible alternatives: cacho, mach, mache, nacho
```

**Comment by dnkoutso** [comment]
@ehlersd try `gem install macho --source=http://rubygems.org`?

**Comment by ehlersd** [comment]
@dnkoutso That gives me the exact same error.

**Comment by dnkoutso** [comment]
@ehlersd ugh my bad is it `gem install macho --source=http://rubygems.org`.

Not a ruby expert here......apologies.

**Comment by ehlersd** [comment]
That did the trick!

(and no worries, I'm no ruby expert either!)

**Comment by dnkoutso** [comment]
<3
