### ISSUE TITLE
pod spec lint error

### ISSUE THREAD

**Issue by yangshengtao** [CocoaPods/CocoaPods#6607]
I met this error, and the Thirdlib which is not private spec repo. 

my pod version is 1.2.0

pod spec lint --verbose
Resolving dependencies of 
 -> Mylib (0.1.0)
    - ERROR | [iOS] unknown: Encountered an unknown error (Unable to find a specification for `Thirdlib` depended upon by `Thirdlib`

```
/Users/tony/.rvm/gems/ruby-2.2.2@global/gems/cocoapods-1.2.0/lib/cocoapods/resolver.rb:442:in `handle_resolver_error'
/Users/tony/.rvm/gems/ruby-2.2.2@global/gems/cocoapods-1.2.0/lib/cocoapods/resolver.rb:65:in `rescue in resolve'
/Users/tony/.rvm/gems/ruby-2.2.2@global/gems/cocoapods-1.2.0/lib/cocoapods/resolver.rb:57:in `resolve'
/Users/tony/.rvm/gems/ruby-2.2.2@global/gems/cocoapods-1.2.0/lib/cocoapods/installer/analyzer.rb:719:in `block in resolve_dependencies'
/Users/tony/.rvm/gems/ruby-2.2.2@global/gems/cocoapods-1.2.0/lib/cocoapods/user_interface.rb:64:in `section'
/Users/tony/.rvm/gems/ruby-2.2.2@global/gems/cocoapods-1.2.0/lib/cocoapods/installer/analyzer.rb:717:in `resolve_dependencies'
/Users/tony/.rvm/gems/ruby-2.2.2@global/gems/cocoapods-1.2.0/lib/cocoapods/installer/analyzer.rb:76:in `analyze'
/Users/tony/.rvm/gems/ruby-2.2.2@global/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:236:in `analyze'
/Users/tony/.rvm/gems/ruby-2.2.2@global/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:150:in `block in resolve_dependencies'
/Users/tony/.rvm/gems/ruby-2.2.2@global/gems/cocoapods-1.2.0/lib/cocoapods/user_interface.rb:64:in `section'
/Users/tony/.rvm/gems/ruby-2.2.2@global/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:149:in `resolve_dependencies'
/Users/tony/.rvm/gems/ruby-2.2.2@global/gems/cocoapods-1.2.0/lib/cocoapods/validator.rb:405:in `block in download_pod'
/Users/tony/.rvm/gems/ruby-2.2.2@global/gems/cocoapods-1.2.0/lib/cocoapods/validator.rb:405:in `each'
/Users/tony/.rvm/gems/ruby-2.2.2@global/gems/cocoapods-1.2.0/lib/cocoapods/validator.rb:405:in `download_pod'
/Users/tony/.rvm/gems/ruby-2.2.2@global/gems/cocoapods-1.2.0/lib/cocoapods/validator.rb:301:in `block in perform_extensive_analysis'
/Users/tony/.rvm/gems/ruby-2.2.2@global/gems/cocoapods-1.2.0/lib/cocoapods/validator.rb:295:in `each'
/Users/tony/.rvm/gems/ruby-2.2.2@global/gems/cocoapods-1.2.0/lib/cocoapods/validator.rb:295:in `perform_extensive_analysis'
/Users/tony/.rvm/gems/ruby-2.2.2@global/gems/cocoapods-1.2.0/lib/cocoapods/validator.rb:79:in `validate'
/Users/tony/.rvm/gems/ruby-2.2.2@global/gems/cocoapods-1.2.0/lib/cocoapods/command/spec/lint.rb:64:in `block in run'
/Users/tony/.rvm/gems/ruby-2.2.2@global/gems/cocoapods-1.2.0/lib/cocoapods/command/spec/lint.rb:53:in `each'
/Users/tony/.rvm/gems/ruby-2.2.2@global/gems/cocoapods-1.2.0/lib/cocoapods/command/spec/lint.rb:53:in `run'
/Users/tony/.rvm/gems/ruby-2.2.2@global/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Users/tony/.rvm/gems/ruby-2.2.2@global/gems/cocoapods-1.2.0/lib/cocoapods/command.rb:52:in `run'
/Users/tony/.rvm/gems/ruby-2.2.2@global/gems/cocoapods-1.2.0/bin/pod:55:in `<top (required)>'
/Users/tony/.rvm/gems/ruby-2.2.2/bin/pod:22:in `load'
/Users/tony/.rvm/gems/ruby-2.2.2/bin/pod:22:in `<main>'
/Users/tony/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
/Users/tony/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'
) during validation.

Analyzed 1 podspec.
```

**Comment by yangshengtao** [comment]
pod env 

### Stack

```
   CocoaPods : 1.2.0
        Ruby : ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
    RubyGems : 2.6.8
        Host : Mac OS X 10.12 (16A323)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.10.1 (Apple Git-78)

**Comment by orta** [comment]
Can you post your Podspec? Are you adding itself as a dependency?
