### ISSUE TITLE
Error when trying to update a cocoapod?

### ISSUE THREAD

**Issue by patchthecode** [CocoaPods/CocoaPods#6609]
I uninstalled cocoapods.
And reinstalled it to version 1.2.0

But now i cant update my pod. Any help please?

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod update
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.2.0
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.5.0
        Host : Mac OS X 10.12.4 (16E195)
       Xcode : 8.3 (8E162)
         Git : git version 2.11.0 (Apple Git-81)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 92bd98fa5ff75861ca1fec53c8aef2032a6f7d05
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Almak' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'Alamofire'
pod 'SwiftyJSON'
pod 'RealmSwift'
pod 'JTAppleCalendar', :git => 'https://github.com/patchthecode/JTAppleCalendar.git'
pod 'NVActivityIndicatorView'
pod 'GoogleMaps'
pod 'SwiftLint'

end
```

### Error

```
LoadError - cannot load such file -- nanaimo
/Users/jt/.gem/gems/xcodeproj-1.4.1/lib/xcodeproj/plist.rb:23:in `read_from_path'
/Users/jt/.gem/gems/xcodeproj-1.4.1/lib/xcodeproj/project.rb:200:in `initialize_from_file'
/Users/jt/.gem/gems/xcodeproj-1.4.1/lib/xcodeproj/project.rb:102:in `open'
/Users/jt/.gem/gems/cocoapods-1.2.0/lib/cocoapods/installer/analyzer.rb:851:in `block (2 levels) in inspect_targets_to_integrate'
/Users/jt/.gem/gems/cocoapods-1.2.0/lib/cocoapods/installer/analyzer.rb:850:in `each'
/Users/jt/.gem/gems/cocoapods-1.2.0/lib/cocoapods/installer/analyzer.rb:850:in `block in inspect_targets_to_integrate'
/Users/jt/.gem/gems/cocoapods-1.2.0/lib/cocoapods/user_interface.rb:64:in `section'
/Users/jt/.gem/gems/cocoapods-1.2.0/lib/cocoapods/installer/analyzer.rb:845:in `inspect_targets_to_integrate'
/Users/jt/.gem/gems/cocoapods-1.2.0/lib/cocoapods/installer/analyzer.rb:66:in `analyze'
/Users/jt/.gem/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:236:in `analyze'
/Users/jt/.gem/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:150:in `block in resolve_dependencies'
/Users/jt/.gem/gems/cocoapods-1.2.0/lib/cocoapods/user_interface.rb:64:in `section'
/Users/jt/.gem/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:149:in `resolve_dependencies'
/Users/jt/.gem/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:110:in `install!'
/Users/jt/.gem/gems/cocoapods-1.2.0/lib/cocoapods/command/update.rb:81:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Users/jt/.gem/gems/cocoapods-1.2.0/lib/cocoapods/command.rb:52:in `run'
/Users/jt/.gem/gems/cocoapods-1.2.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

**Comment by dnkoutso** [comment]
please see https://github.com/CocoaPods/CocoaPods/issues/6214
