### ISSUE TITLE
ArgumentError - Malformed version number string $(inherited)

### ISSUE THREAD

**Issue by maximepontoire** [CocoaPods/CocoaPods#6634]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I run _pod install_ on my podfile : 

`# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
#source 'ssh://git@git.steamulo.com/iphone/steamulo-specs.git'

# Disable sending stats
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

target 'MyTarget' do
    
    pod 'Toast', '3.0'
    pod 'Mapwize', '1.7.1'
    pod 'NAOSDKPOD', '4.0.22'
    pod 'GBDeviceInfo', '~> 4.1'
    pod 'JSONModel', '1.2.0'
    pod 'AFNetworking', '3.1.0'
    pod 'CocoaLumberjack', '3.0.0'
    pod 'Dimelo-iOS', :git => 'https://github.com/dimelo/Dimelo-iOS.git', :tag => 'v1.3.1'
    pod 'NSString-Hashes', '1.2.2'
    pod 'Fabric', '1.6.8'
    pod 'Crashlytics', '3.8.3'
    pod 'SSAccessibility'
    
end

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
`

## What did you expect to happen?

All pods should be installed. I've tried to remove the podfile and pods/ rep, make a pod init and the issue is the same 
## What happened instead?

> Analyzing dependencies
Pre-downloading: `Dimelo-iOS` from `https://github.com/dimelo/Dimelo-iOS.git`, tag `v1.3.1`
Downloading dependencies
Using AFNetworking (3.1.0)
Using CocoaLumberjack (3.0.0)
Using Crashlytics (3.8.3)
Installing Dimelo-iOS (1.3.1)
Using Fabric (1.6.8)
Using GBDeviceInfo (4.1.0)
Using JSONModel (1.2.0)
Using Mapwize (1.7.1)
Using NAOSDKPOD (4.0.22)
Using NSString-Hashes (1.2.2)
Using SSAccessibility (0.2.0)
Using Toast (3.0)
Generating Pods project

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.2.0
        Ruby : ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
    RubyGems : 2.6.8
        Host : Mac OS X 10.12.4 (16E195)
       Xcode : 8.3.1 (8E1000a)
         Git : git version 2.11.0 (Apple Git-81)
Ruby lib dir : /usr/local/Cellar/ruby/2.4.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 22c2d4b4b7e42a29d14de62bbb8599a9d77892ea
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
slather               : 2.4.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
#source 'ssh://git@git.steamulo.com/iphone/steamulo-specs.git'

# Disable sending stats
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

target 'MyTarget' do
    
    pod 'Toast', '3.0'
    pod 'Mapwize', '1.7.1'
    pod 'NAOSDKPOD', '4.0.22'
    pod 'GBDeviceInfo', '~> 4.1'
    pod 'JSONModel', '1.2.0'
    pod 'AFNetworking', '3.1.0'
    pod 'CocoaLumberjack', '3.0.0'
    pod 'Dimelo-iOS', :git => 'https://github.com/dimelo/Dimelo-iOS.git', :tag => 'v1.3.1'
    pod 'NSString-Hashes', '1.2.2'
    pod 'Fabric', '1.6.8'
    pod 'Crashlytics', '3.8.3'
    pod 'SSAccessibility'
    
end

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
```

### Error

```
ArgumentError - Malformed version number string $(inherited)
/usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/rubygems/version.rb:207:in `initialize'
/usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/rubygems/version.rb:199:in `new'
/usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/rubygems/version.rb:199:in `new'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.2.0/lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb:111:in `embedded_content_settings'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.2.0/lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb:63:in `generate'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.2.0/lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb:39:in `save_as'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.2.0/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:87:in `block in create_xcconfig_file'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.2.0/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:84:in `each'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.2.0/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:84:in `create_xcconfig_file'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.2.0/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:18:in `block in install!'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.2.0/lib/cocoapods/user_interface.rb:142:in `message'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.2.0/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:14:in `install!'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.2.0/lib/cocoapods/installer/xcode/pods_project_generator.rb:160:in `block (2 levels) in install_libraries'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.2.0/lib/cocoapods/installer/xcode/pods_project_generator.rb:158:in `each'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.2.0/lib/cocoapods/installer/xcode/pods_project_generator.rb:158:in `block in install_libraries'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.2.0/lib/cocoapods/user_interface.rb:142:in `message'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.2.0/lib/cocoapods/installer/xcode/pods_project_generator.rb:152:in `install_libraries'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.2.0/lib/cocoapods/installer/xcode/pods_project_generator.rb:64:in `generate!'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:179:in `block in generate_pods_project'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.2.0/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:178:in `generate_pods_project'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:115:in `install!'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.2.0/lib/cocoapods/command/install.rb:37:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.2.0/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.2.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=Malformed+version+number+string+%24%28inherited%29&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Found no similar issues. To create a new issue, please visit:

> https://github.com/cocoapods/cocoapods/issues/new

>
### Stack

```
   CocoaPods : 1.2.0
        Ruby : ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
    RubyGems : 2.6.8
        Host : Mac OS X 10.12.4 (16E195)
       Xcode : 8.3.1 (8E1000a)
         Git : git version 2.11.0 (Apple Git-81)
Ruby lib dir : /usr/local/Cellar/ruby/2.4.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 22c2d4b4b7e42a29d14de62bbb8599a9d77892ea
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
slather               : 2.4.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
#source 'ssh://git@git.steamulo.com/iphone/steamulo-specs.git'

# Disable sending stats
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

target 'MyTarget' do
    
    pod 'Toast', '3.0'
    pod 'Mapwize', '1.7.1'
    pod 'NAOSDKPOD', '4.0.22'
    pod 'GBDeviceInfo', '~> 4.1'
    pod 'JSONModel', '1.2.0'
    pod 'AFNetworking', '3.1.0'
    pod 'CocoaLumberjack', '3.0.0'
    pod 'Dimelo-iOS', :git => 'https://github.com/dimelo/Dimelo-iOS.git', :tag => 'v1.3.1'
    pod 'NSString-Hashes', '1.2.2'
    pod 'Fabric', '1.6.8'
    pod 'Crashlytics', '3.8.3'
    pod 'SSAccessibility'
    
end

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
```

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

**Comment by orta** [comment]
Looks like somewhere you have a semver version of a library that doesn't conform to the semver spec: http://semver.org

**Comment by Gaoyanxiang** [comment]
### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.5.2
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    RubyGems : 2.7.7
        Host : Mac OS X 10.13.2 (17C88)
       Xcode : 9.3 (9E145)
         Git : git version 2.15.1 (Apple Git-101)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ d6ec8667fc7ba190209c49089af0a2da9f3717c9
               WqUtils - https://gitee.com/Gollen/WqUtils.git @ 229b966f9ec828987bbf5b4ba497ebc5397f5e88
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Demo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'MJRefresh'
  # Pods for Demo

  target 'DemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

### Error

```
ArgumentError - Malformed version number string 
/Library/Ruby/Site/2.3.0/rubygems/version.rb:209:in `initialize'
/Library/Ruby/Site/2.3.0/rubygems/version.rb:200:in `new'
/Library/Ruby/Site/2.3.0/rubygems/version.rb:200:in `new'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb:123:in `embedded_content_settings'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb:68:in `generate'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb:39:in `save_as'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/xcode/pods_project_generator/target_installer.rb:112:in `update_changed_file'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:96:in `block in create_xcconfig_file'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:93:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:93:in `create_xcconfig_file'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:18:in `block in install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/user_interface.rb:142:in `message'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:14:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:181:in `block (2 levels) in install_libraries'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:179:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:179:in `block in install_libraries'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/user_interface.rb:142:in `message'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:167:in `install_libraries'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:65:in `generate!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/installer.rb:184:in `block in generate_pods_project'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/installer.rb:183:in `generate_pods_project'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/installer.rb:119:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/command/install.rb:41:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/bin/pod:55:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

**Comment by CWTgithub** [comment]
I also encountered such a problem, how can I solve it?
