### ISSUE TITLE
an error occurred,when running 'pod install' or 'pod update' after upgrade from 1.2.0 to 1.2.1

### ISSUE THREAD

**Issue by alexfeng** [CocoaPods/CocoaPods#6679]
### Command

```
/Users/mac/.rvm/rubies/ruby-2.3.0/bin/pod update --verbose --no-repo-update
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.2.1
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin16]
    RubyGems : 2.5.1
        Host : Mac OS X 10.12.4 (16E195)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /Users/mac/.rvm/rubies/ruby-2.3.0/lib
Repositories : artsy - https://github.com/artsy/Specs.git @ 5710c812b912e14f0f7acd6ab80adc8fc34e1185
               coding-cocoapods-specs - https://git.coding.net/CocoaPods/Specs.git @ ab3494b3a2ec1a03a1cb58e70aa6b0c7c3ae7b90
               master - https://github.com/CocoaPods/Specs.git @ f872ec90ba127e2ccc506a11701298749e593f3c
               taobao-baichuansdk-alibcspecs - http://repo.baichuan-ios.taobao.com/baichuanSDK/AliBCSpecs.git @ a4c62aea6b808cf492a246e6282c133e9ffb111f
               XBSpecs - https://github.com/alexfeng/XBSpecs.git @ caa56aff6ecb616ccc479731b476a603fee24e5c
```

### Plugins

```
cocoapods-trunk : 1.2.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

#use_frameworks!

target 'XBIMSDK_Example' do
  pod 'XBIMSDK', :path => '../'
  pod 'Reachability', '~> 3.2'
  pod 'Toast', '~> 3.0'
  pod 'XBDatas', '~> 0.1.2'
  pod 'AFNetworking', '~> 3.1.0'
  pod 'MJRefresh', '~> 3.1.12'
  pod 'IQKeyboardManager', '~> 4.0.9'
end


target 'XBIMSDK_Tests' do
    inherit! :search_paths
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
```

### Error

```
LoadError - cannot load such file -- cocoapods_deintegrate
/Users/mac/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
/Users/mac/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
/Users/mac/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.2.1/lib/cocoapods/installer/user_project_integrator.rb:120:in `block in integrate_user_targets'
/Users/mac/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.2.1/lib/cocoapods/config.rb:41:in `with_changes'
/Users/mac/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.2.1/lib/cocoapods/installer/user_project_integrator.rb:119:in `integrate_user_targets'
/Users/mac/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.2.1/lib/cocoapods/installer/user_project_integrator.rb:63:in `integrate!'
/Users/mac/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.2.1/lib/cocoapods/installer.rb:614:in `block in integrate_user_project'
/Users/mac/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.2.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/mac/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.2.1/lib/cocoapods/installer.rb:611:in `integrate_user_project'
/Users/mac/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.2.1/lib/cocoapods/installer.rb:117:in `install!'
/Users/mac/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.2.1/lib/cocoapods/command/update.rb:81:in `run'
/Users/mac/.rvm/gems/ruby-2.3.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Users/mac/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.2.1/lib/cocoapods/command.rb:52:in `run'
/Users/mac/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.2.1/bin/pod:55:in `<top (required)>'
/Users/mac/.rvm/rubies/ruby-2.3.0/bin/pod:23:in `load'
/Users/mac/.rvm/rubies/ruby-2.3.0/bin/pod:23:in `<main>'
/Users/mac/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/Users/mac/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by dnkoutso** [comment]
Do you have https://github.com/CocoaPods/cocoapods-deintegrate installed?

**Comment by alexfeng** [comment]
installed
take this

gem list

*** LOCAL GEMS ***

activesupport (4.2.8)
bigdecimal (default: 1.2.6)
CFPropertyList (2.3.5)
claide (1.0.1)
cocoapods (1.2.1)
cocoapods-core (1.2.1)
cocoapods-deintegrate (1.0.1)
cocoapods-downloader (1.1.3)
cocoapods-plugins (1.0.0)
cocoapods-search (1.0.0)
cocoapods-stats (1.0.0)
cocoapods-trunk (1.2.0)
cocoapods-try (1.1.0)
colored2 (3.1.2)

**Comment by NianJi** [comment]
same problem!

**Comment by alexfeng** [comment]
I change ruby version to 2.2.2 and reinstall cocoapods ，it work well！
