### ISSUE TITLE
pod search not working!

### ISSUE THREAD

**Issue by archmagees** [CocoaPods/CocoaPods#6682]
### Command

```
/usr/local/bin/pod search acykit
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.2.1
        Ruby : ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
    RubyGems : 2.6.11
        Host : Mac OS X 10.12.4 (16E195)
       Xcode : 8.3.2 (8E2002)
         Git : git version 2.12.2
Ruby lib dir : /usr/local/Cellar/ruby/2.4.1_1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 4ac645df362d7172a3d3a485b20f2111543805fa
               taobao-baichuansdk-alibcspecs - http://repo.baichuan-ios.taobao.com/baichuanSDK/AliBCSpecs.git @ 3b30403e91c4831453e0a26f8d770f334291faea
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
slather               : 2.4.1
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!


target 'ACYKit_Example' do


  pod 'ACYKit', :path => '../'

  pod 'CocoaLumberjack', :inhibit_warnings => true
  pod 'Masonry', :inhibit_warnings => true
  pod 'HexColors', '4.0.0', :inhibit_warnings => true # 5.0.0 is written in Swift 3
  pod 'SDWebImage', :inhibit_warnings => true
  pod 'MLeaksFinder', :inhibit_warnings => true
  pod 'Aspects'

  target 'ACYKit_Tests' do
    inherit! :search_paths

    pod 'Kiwi', :inhibit_warnings => true
#	pod 'FBSnapshotTestCase'
  end

end


#  pod 'FLAnimatedImage'
#  pod 'PINRemoteImage'
#  pod 'TAOverlay'

#pod 'AFNetworking", :git => 'https://github.com/gowalla/AFNetworking.git', :branch => 'dev'
#pod 'AFNetworking', :git => 'https://github.com/gowalla/AFNetworking.git', :commit => '082f8319af'
```

### Error

```
JSON::ParserError - 765: unexpected token at ''
/usr/local/lib/ruby/gems/2.4.0/gems/json-2.1.0/lib/json/common.rb:156:in `parse'
/usr/local/lib/ruby/gems/2.4.0/gems/json-2.1.0/lib/json/common.rb:156:in `parse'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-core-1.2.1/lib/cocoapods-core/source/manager.rb:251:in `stored_search_index'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-core-1.2.1/lib/cocoapods-core/source/manager.rb:187:in `updated_search_index'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-core-1.2.1/lib/cocoapods-core/source/manager.rb:118:in `search_by_name'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-search-1.0.0/lib/cocoapods-search/command/search.rb:87:in `local_search'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-search-1.0.0/lib/cocoapods-search/command/search.rb:63:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.2.1/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.2.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

**Comment by benasher44** [comment]
Hi there! Thanks for the report! Could you please try running `rm -rf ~/Library/Caches/CocoaPods` to see if that fixes your issue. Thanks!

**Comment by archmagees** [comment]
That works! 
Thank you very much indeed!

**Comment by benasher44** [comment]
Glad that fixed it for you!

**Comment by nourallahtq** [comment]
not working until today
