### ISSUE TITLE
Could not run pod release 

### ISSUE THREAD

**Issue by woooha** [CocoaPods/CocoaPods#6705]
### Command

```
/Users/woooha/.rvm/gems/ruby-2.3.1/bin/pod release
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.2.1
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
    RubyGems : 2.6.11
        Host : Mac OS X 10.12.4 (16E195)
       Xcode : 8.3 (8E162)
         Git : git version 2.12.2
Ruby lib dir : /Users/woooha/.rvm/rubies/ruby-2.3.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 5213430ec4ffaa391e4ada84e5e52b49059f56c0
               zerozero-specs - git@git.zerozero.cn:iOS/Specs.git @ 8414d770d91ef53ecba33236f630f6bc450b67a6
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-release     : 0.3.1
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
slather               : 2.4.1
```

### Error

```
NameError - uninitialized constant Pod::Command::Release::SourcesManager
/Users/woooha/.rvm/gems/ruby-2.3.1/gems/cocoapods-release-0.3.1/lib/pod/command/release.rb:37:in `run'
/Users/woooha/.rvm/gems/ruby-2.3.1/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Users/woooha/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.2.1/lib/cocoapods/command.rb:52:in `run'
/Users/woooha/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.2.1/bin/pod:55:in `<top (required)>'
/Users/woooha/.rvm/gems/ruby-2.3.1/bin/pod:22:in `load'
/Users/woooha/.rvm/gems/ruby-2.3.1/bin/pod:22:in `<main>'
/Users/woooha/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/Users/woooha/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by orta** [comment]
CocoaPods Release is a third-party plugin, I'd recommend helping them fix this on their side: https://github.com/Sparrow-Labs/cocoapods-release
