### ISSUE TITLE
 The spec did not pass validation, due to 1 error.

### ISSUE THREAD

**Issue by AmjadPatan** [CocoaPods/CocoaPods#6761]
I'm trying to push a podspec to my private repo, but i'm getting the following error.

```
`- ERROR | [iOS] unknown: Encountered an unknown error (Pod::DSLError
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.2.1/lib/cocoapods-core/specification.rb:661:in `rescue in _eval_podspec'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.2.1/lib/cocoapods-core/specification.rb:654:in `_eval_podspec'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.2.1/lib/cocoapods-core/specification.rb:562:in `block in from_string'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.2.1/lib/cocoapods-core/specification.rb:559:in `chdir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.2.1/lib/cocoapods-core/specification.rb:559:in `from_string'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.2.1/lib/cocoapods-core/specification.rb:542:in `from_file'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/sandbox/podspec_finder.rb:15:in `block in podspecs'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/sandbox/podspec_finder.rb:14:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/sandbox/podspec_finder.rb:14:in `podspecs'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/downloader.rb:82:in `download_request'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/downloader/cache.rb:171:in `download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/downloader/cache.rb:154:in `block in uncached_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/downloader/cache.rb:181:in `call'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/downloader/cache.rb:181:in `in_tmpdir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/downloader/cache.rb:153:in `uncached_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/downloader/cache.rb:33:in `download_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/downloader.rb:42:in `download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/installer/pod_source_installer.rb:120:in `download_source'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/installer/pod_source_installer.rb:60:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/installer.rb:357:in `install_source_of_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/installer.rb:322:in `block (2 levels) in install_pod_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/user_interface.rb:85:in `titled_section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/installer.rb:321:in `block in install_pod_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/installer.rb:313:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/installer.rb:313:in `install_pod_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/installer.rb:159:in `block in download_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/installer.rb:157:in `download_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/validator.rb:408:in `block in download_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/validator.rb:408:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/validator.rb:408:in `download_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/validator.rb:304:in `block in perform_extensive_analysis'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/validator.rb:298:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/validator.rb:298:in `perform_extensive_analysis'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/validator.rb:79:in `validate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/command/spec/lint.rb:67:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/command/spec/lint.rb:55:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/command/spec/lint.rb:55:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
) during validation.`
```

When i do pod lib lint , i get a success message, but when i do pod spec lint i'm getting the above error.

**Comment by dnkoutso** [comment]
Its very hard to debug this without the podspec itself. Paste its contents here.

`spec lint` will clone the current tag in the podspec so you are probably cloning the previous tag that worked.

**Comment by AmjadPatan** [comment]
Please find the below podspec file.

`Pod::Spec.new do |s|

# 1
s.platform = :ios
s.ios.deployment_target = '9.0'
s.name = "GraniteFramework"
s.summary = "GraniteFramework provides access to common libraries."
s.requires_arc = true

# 2
s.version = "0.1.13"

# 3
s.license = { :type => "MIT", :file => "LICENSE" }

# 4 - Replace with your name and e-mail address
s.author = { "Amjad" => "Amjad.Patan@honeywell.com" }

# 5 - Replace this URL with your own Github page's URL (from the address bar)
s.homepage = "https://acsbitbucket.honeywell.com/projects/GRANITE_APPS/repos/ios-graniteframework/browse"

# 6 - Replace this URL with your own Git URL from "Quick Setup"
s.source = { :git => "https://acsbitbucket.honeywell.com/scm/granite_apps/ios-graniteframework.git", :tag => "#{s.version}"}

# 7
s.framework = "UIKit", "Foundation", "CoreBluetooth", "ExternalAccessory", "CoreLocation"
s.dependency 'GraniteRESTClient', '~> 0.1.0'
s.dependency 'GMEllipticCurveCrypto', '~>0.1.0'
s.dependency 'RSAEncryption', '~>0.1.1'
s.dependency 'CommonCrypto', '~>0.1.0'
s.dependency 'SignalRClient', '~>0.1.0'

# 8
s.source_files = "GraniteFramework/**/*.{swift,c,h,m}"

# 9
s.resources = "GraniteFramework/**/*.{png,jpeg,jpg,storyboard,xib,json}"

end
`

**Comment by QDFish** [comment]
hello, I have same problem about that, I try pod update and pod repo push --allow-warnings, i think the --allow-warnings solve my problem

**Comment by EricCheungSCUT** [comment]
Hi, did you fix this problem? I am facing the same problem, too

**Comment by GorCat** [comment]
save with me 

```

Pod::Spec.new do |s|
  s.name             = 'EHSUIKit'
  s.version          = '0.2.0'
  s.summary          = 'EHS 3 个端可共用的组件'
  s.homepage         = 'http://GorCat@gitlab.lmdo.cn/GorCat/EHSUIKit'
  s.license          = { :type => 'MIT', :file => 'LICENSE' }
  s.author           = { 'GorCat' => 'luoyangchengguo@gmail.com' }
  s.source           = { :git => 'http://GorCat@gitlab.lmdo.cn/GorCat/EHSUIKit.git', :tag => s.version.to_s }
  s.requires_arc = true

  s.ios.deployment_target = '8.0'
  s.dependency 'IGListKit', '~>3.4.0'
  s.dependency 'QMUIKit'
  s.dependency 'EasyReact'
  s.dependency 'AFNetworking', '~>3.2.1'

  s.source_files = 'EHSUIKit/Classes/EHSUIKit.h'
  s.public_header_files = 'EHSUIKit/Classes/EHSUIKit.h'

  s.subspec 'Network' do |ss|
    ss.source_files = 'EHSUIKit/Classes/Network/*.{h,m}'
    ss.public_header_files = 'EHSUIKit/Classes/Network/*.h'
  end

  s.subspec 'Model' do |ss|
    ss.source_files = 'EHSUIKit/Classes/Model/*.{h,m}'
    ss.public_header_files = 'EHSUIKit/Classes/Model/*.h'
  end

  s.subspec 'Danger' do |ss|
    ss.source_files = 'EHSUIKit/Classes/Danger/*.{h,m}'
    ss.public_header_files = 'EHSUIKit/Classes/Classes/*.h'
  end

  s.subspec 'RootViewController' do |ss|
    ss.source_files = 'EHSUIKit/Classes/RootController/EHSRootViewController.{h,m}'
    ss.public_header_files = 'EHSUIKit/Classes/RootController/EHSRootViewController.h'
  end

end
```
