### ISSUE TITLE
DSLError

### ISSUE THREAD

**Issue by archerLj** [CocoaPods/CocoaPods#6801]
# Report
i create a podspec, and i get an DSLError when i run the command of 
"pod spec lint A_Category.podspec --verbose --allow-warnings"

## What happened instead?
and this is the error:
```
 -> A_Category (0.0.1)
    - ERROR | [iOS] unknown: Encountered an unknown error (Pod::DSLError
/Users/archerlj/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-core-1.2.1/lib/cocoapods-core/specification.rb:661:in `rescue in _eval_podspec'
/Users/archerlj/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-core-1.2.1/lib/cocoapods-core/specification.rb:654:in `_eval_podspec'
/Users/archerlj/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-core-1.2.1/lib/cocoapods-core/specification.rb:562:in `block in from_string'
/Users/archerlj/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-core-1.2.1/lib/cocoapods-core/specification.rb:559:in `chdir'
/Users/archerlj/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-core-1.2.1/lib/cocoapods-core/specification.rb:559:in `from_string'
/Users/archerlj/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-core-1.2.1/lib/cocoapods-core/specification.rb:542:in `from_file'
/Users/archerlj/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.2.1/lib/cocoapods/sandbox/podspec_finder.rb:15:in `block in podspecs'
/Users/archerlj/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.2.1/lib/cocoapods/sandbox/podspec_finder.rb:14:in `each'
/Users/archerlj/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.2.1/lib/cocoapods/sandbox/podspec_finder.rb:14:in `podspecs'
/Users/archerlj/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.2.1/lib/cocoapods/downloader.rb:82:in `download_request'
/Users/archerlj/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.2.1/lib/cocoapods/downloader/cache.rb:171:in `download'
/Users/archerlj/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.2.1/lib/cocoapods/downloader/cache.rb:154:in `block in uncached_pod'
/Users/archerlj/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.2.1/lib/cocoapods/downloader/cache.rb:181:in `in_tmpdir'
/Users/archerlj/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.2.1/lib/cocoapods/downloader/cache.rb:153:in `uncached_pod'
/Users/archerlj/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.2.1/lib/cocoapods/downloader/cache.rb:33:in `download_pod'
/Users/archerlj/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.2.1/lib/cocoapods/downloader.rb:42:in `download'
/Users/archerlj/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.2.1/lib/cocoapods/installer/pod_source_installer.rb:120:in `download_source'
/Users/archerlj/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.2.1/lib/cocoapods/installer/pod_source_installer.rb:60:in `install!'
/Users/archerlj/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.2.1/lib/cocoapods/installer.rb:357:in `install_source_of_pod'
/Users/archerlj/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.2.1/lib/cocoapods/installer.rb:322:in `block (2 levels) in install_pod_sources'
/Users/archerlj/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.2.1/lib/cocoapods/user_interface.rb:85:in `titled_section'
/Users/archerlj/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.2.1/lib/cocoapods/installer.rb:321:in `block in install_pod_sources'
/Users/archerlj/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.2.1/lib/cocoapods/installer.rb:313:in `each'
/Users/archerlj/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.2.1/lib/cocoapods/installer.rb:313:in `install_pod_sources'
/Users/archerlj/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.2.1/lib/cocoapods/installer.rb:159:in `block in download_dependencies'
/Users/archerlj/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.2.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/archerlj/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.2.1/lib/cocoapods/installer.rb:157:in `download_dependencies'
/Users/archerlj/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.2.1/lib/cocoapods/validator.rb:408:in `block in download_pod'
/Users/archerlj/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.2.1/lib/cocoapods/validator.rb:408:in `each'
/Users/archerlj/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.2.1/lib/cocoapods/validator.rb:408:in `download_pod'
/Users/archerlj/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.2.1/lib/cocoapods/validator.rb:304:in `block in perform_extensive_analysis'
/Users/archerlj/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.2.1/lib/cocoapods/validator.rb:298:in `each'
/Users/archerlj/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.2.1/lib/cocoapods/validator.rb:298:in `perform_extensive_analysis'
/Users/archerlj/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.2.1/lib/cocoapods/validator.rb:79:in `validate'
/Users/archerlj/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.2.1/lib/cocoapods/command/spec/lint.rb:67:in `block in run'
/Users/archerlj/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.2.1/lib/cocoapods/command/spec/lint.rb:55:in `each'
/Users/archerlj/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.2.1/lib/cocoapods/command/spec/lint.rb:55:in `run'
/Users/archerlj/.rvm/gems/ruby-2.3.0@global/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/archerlj/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.2.1/lib/cocoapods/command.rb:52:in `run'
/Users/archerlj/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.2.1/bin/pod:55:in `<top (required)>'
/Users/archerlj/.rvm/rubies/ruby-2.3.0/bin/pod:23:in `load'
/Users/archerlj/.rvm/rubies/ruby-2.3.0/bin/pod:23:in `<main>'
/Users/archerlj/.rvm/gems/ruby-2.3.0@global/bin/ruby_executable_hooks:15:in `eval'
/Users/archerlj/.rvm/gems/ruby-2.3.0@global/bin/ruby_executable_hooks:15:in `<main>'
) during validation.

Analyzed 1 podspec.

[!] The spec did not pass validation, due to 1 error.

/Users/archerlj/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.2.1/lib/cocoapods/command/spec/lint.rb:84:in `run'
/Users/archerlj/.rvm/gems/ruby-2.3.0@global/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/archerlj/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.2.1/lib/cocoapods/command.rb:52:in `run'
/Users/archerlj/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.2.1/bin/pod:55:in `<top (required)>'
/Users/archerlj/.rvm/rubies/ruby-2.3.0/bin/pod:23:in `load'
/Users/archerlj/.rvm/rubies/ruby-2.3.0/bin/pod:23:in `<main>'
/Users/archerlj/.rvm/gems/ruby-2.3.0@global/bin/ruby_executable_hooks:15:in `eval'
/Users/archerlj/.rvm/gems/ruby-2.3.0@global/bin/ruby_executable_hooks:15:in `<main>'
```

## CocoaPods Environment
my CocoaPods version is 1.2.1

## Project that demonstrates the issue
this is my podspec file's content:
```
Pod::Spec.new do |s|
  s.name         = "A_Category"
  s.version      = "0.0.1"
  s.summary      = "A_Category."
  s.description  = <<-DESC
                    this is A_Category
                   DESC
  s.homepage     = "https://github.com/LFModulizationDemo/A_Category"
  s.license      = { :type => "MIT", :file => "FILE_LICENSE" }
  s.author       = { "archerLj" => "lj0011977@163.com" }
  s.platform     = :ios, "7.0"
  s.source       = { :git => "https://github.com/LFModulizationDemo/A_Category.git", :tag => "0.0.1" }
  s.source_files = "A_Category/A_Category/**/*.{h,m}"
  s.requires_arc = true
  s.dependency "CTMediator"
end

```

**Comment by orta** [comment]
I think if you run it with `--verbose` you'll get a better version of the error message, but this is basically a syntax error in your Podspec.

**Comment by archerLj** [comment]
I did run it with `--berbose`, and it show me DSLError that i had ben write at the beginning of this issue.  It show me some syntax error first and i fixed them (such as use `"` instead of `“`), but the DSLError message help me nothing, it just give me a message of `[iOS] unknown: Encountered an unknown error (Pod::DSLError`  and a lot of message i don't understand.

**Comment by archerLj** [comment]
The test source has been pushed to gitHub on here [https://github.com/LFModulizationDemo/A_Category](https://github.com/LFModulizationDemo/A_Category). Please show me if there have some syntax error in my Podspec. I will be very appreciated cause I have been tried a lot of methods and they didn't work.

**Comment by paulb777** [comment]
Perhaps, brackets not braces - 
`  s.source_files = "A_Category/A_Category/**/*.[h,m]"`

**Comment by archerLj** [comment]
There's no difference between`*.[h,m]` and `*.{h,m}`.  All of them have no work.  The DSLError is still shown.

**Comment by orta** [comment]
The version you posted is 👍, but you're checking against the version in your tag, which isn't because it has smart quotes: https://github.com/LFModulizationDemo/A_Category/blob/0.0.1/A_Category.podspec#L19

We really should improve the way that those errors are highlighted - are you on the latest release of CocoaPods/

**Comment by archerLj** [comment]
My pod version is `1.2.1`.  The Error info is really hard to understand for me. Anyway, thanks a lot, it worked for me.

**Comment by gurjindersinghkhalsa** [comment]
@archerLj 
Can you please define what you did to get the issue resolved. I am unable to find out.
Thanks!
