### ISSUE TITLE
BUILD SUCCEEDED but my demo Demo did not pass validation with error

### ISSUE THREAD

**Issue by xiao-xi** [CocoaPods/CocoaPods#6805]
> my pod version
> 
```
➜  PushDemo git:(master) ✗ pod --version
1.3.0.beta.1
```
> my Xcode version.
>
```
Xcode 8.3.1
```

# Report

## What did you do?
 
I used a 3rd party lib of JPush (it doesn't support  architecture i386) in my lib, and when I run the command: `pod lib lint --verbose --use-libraries --allow-warnings `, then  an error returned which says like below:

```
Signing Identity:     "-"

    /usr/bin/codesign --force --sign - --timestamp=none /Users/xiaodou_chenxiaoxiang/Library/Developer/Xcode/DerivedData/App-eiahrqzgjqfuamanikgpvjgfsbdr/Build/Products/Release-iphonesimulator/App.app

** BUILD SUCCEEDED **

   Testing with xcodebuild. 
 -> PushDemo (0.1.0)
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code.
    - WARN  | xcodebuild:  /Users/xiaodou_chenxiaoxiang/Desktop/PodPrivate/XDPrivatePod/PushDemo/PushDemo/JPush/JPUSHService.h:140:11: warning: parameter 'advertisingIdentifier' not found in the function declaration [-Wdocumentation]
    - NOTE  | [iOS] xcodebuild:  ld: warning: ld: warning: ignoring file /Users/xiaodou_chenxiaoxiang/Desktop/PodPrivate/XDPrivatePod/PushDemo/PushDemo/JPush/libjpush-ios-3.0.5.a, missing required architecture i386 in file /Users/xiaodou_chenxiaoxiang/Desktop/PodPrivate/XDPrivatePod/PushDemo/PushDemo/JPush/libjpush-ios-3.0.5.a (4 slices)ignoring file /Users/xiaodou_chenxiaoxiang/Desktop/PodPrivate/XDPrivatePod/PushDemo/PushDemo/JPush/libjcore-ios-1.1.3.a, missing required architecture i386 in file /Users/xiaodou_chenxiaoxiang/Desktop/PodPrivate/XDPrivatePod/PushDemo/PushDemo/JPush/libjcore-ios-1.1.3.a (4 slices)
    - NOTE  | [iOS] xcodebuild:  clang: error: linker command failed with exit code 1 (use -v to see invocation)
    - NOTE  | [iOS] [PushDemo/JPush] xcodebuild:  ld: warning: ignoring file /Users/xiaodou_chenxiaoxiang/Desktop/PodPrivate/XDPrivatePod/PushDemo/PushDemo/JPush/libjpush-ios-3.0.5.a, missing required architecture i386 in file /Users/xiaodou_chenxiaoxiang/Desktop/PodPrivate/XDPrivatePod/PushDemo/PushDemo/JPush/libjpush-ios-3.0.5.a (4 slices)
    - NOTE  | [iOS] [PushDemo/JPush] xcodebuild:  ld: warning: ignoring file /Users/xiaodou_chenxiaoxiang/Desktop/PodPrivate/XDPrivatePod/PushDemo/PushDemo/JPush/libjcore-ios-1.1.3.a, missing required architecture i386 in file /Users/xiaodou_chenxiaoxiang/Desktop/PodPrivate/XDPrivatePod/PushDemo/PushDemo/JPush/libjcore-ios-1.1.3.a (4 slices)

[!] PushDemo did not pass validation, due to 1 error.
You can use the `--no-clean` option to inspect any issue.

/Users/xiaodou_chenxiaoxiang/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.3.0.beta.1/lib/cocoapods/command/lib/lint.rb:85:in `block in run'
/Users/xiaodou_chenxiaoxiang/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.3.0.beta.1/lib/cocoapods/command/lib/lint.rb:54:in `each'
/Users/xiaodou_chenxiaoxiang/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.3.0.beta.1/lib/cocoapods/command/lib/lint.rb:54:in `run'
/Users/xiaodou_chenxiaoxiang/.rvm/gems/ruby-2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/xiaodou_chenxiaoxiang/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.3.0.beta.1/lib/cocoapods/command.rb:52:in `run'
/Users/xiaodou_chenxiaoxiang/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.3.0.beta.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
/Users/xiaodou_chenxiaoxiang/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
```

## What did you expect to happen?
I wonder how to let PushDemo pass validation without error.

## What happened instead?
```
 -> PushDemo (0.1.0)
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code.
    - WARN  | xcodebuild:  /Users/xiaodou_chenxiaoxiang/Desktop/PodPrivate/XDPrivatePod/PushDemo/PushDemo/JPush/JPUSHService.h:140:11: warning: parameter 'advertisingIdentifier' not found in the function declaration [-Wdocumentation]
    - NOTE  | [iOS] xcodebuild:  ld: warning: ld: warning: ignoring file /Users/xiaodou_chenxiaoxiang/Desktop/PodPrivate/XDPrivatePod/PushDemo/PushDemo/JPush/libjpush-ios-3.0.5.a, missing required architecture i386 in file /Users/xiaodou_chenxiaoxiang/Desktop/PodPrivate/XDPrivatePod/PushDemo/PushDemo/JPush/libjpush-ios-3.0.5.a (4 slices)ignoring file /Users/xiaodou_chenxiaoxiang/Desktop/PodPrivate/XDPrivatePod/PushDemo/PushDemo/JPush/libjcore-ios-1.1.3.a, missing required architecture i386 in file /Users/xiaodou_chenxiaoxiang/Desktop/PodPrivate/XDPrivatePod/PushDemo/PushDemo/JPush/libjcore-ios-1.1.3.a (4 slices)
    - NOTE  | [iOS] xcodebuild:  clang: error: linker command failed with exit code 1 (use -v to see invocation)
    - NOTE  | [iOS] [PushDemo/JPush] xcodebuild:  ld: warning: ignoring file /Users/xiaodou_chenxiaoxiang/Desktop/PodPrivate/XDPrivatePod/PushDemo/PushDemo/JPush/libjpush-ios-3.0.5.a, missing required architecture i386 in file /Users/xiaodou_chenxiaoxiang/Desktop/PodPrivate/XDPrivatePod/PushDemo/PushDemo/JPush/libjpush-ios-3.0.5.a (4 slices)
    - NOTE  | [iOS] [PushDemo/JPush] xcodebuild:  ld: warning: ignoring file /Users/xiaodou_chenxiaoxiang/Desktop/PodPrivate/XDPrivatePod/PushDemo/PushDemo/JPush/libjcore-ios-1.1.3.a, missing required architecture i386 in file /Users/xiaodou_chenxiaoxiang/Desktop/PodPrivate/XDPrivatePod/PushDemo/PushDemo/JPush/libjcore-ios-1.1.3.a (4 slices)

[!] PushDemo did not pass validation, due to 1 error.
```

## CocoaPods Environment

my podspec file is below:

```
Pod::Spec.new do |s|
  s.name             = 'PushDemo'
  s.version          = '0.1.0'
  s.summary          = 'push of XDDemo.'

# This description is used to generate tags and improve search results.
#   * Think: What does it do? Why did you write it? What is the focus?
#   * Try to keep it short, snappy and to the point.
#   * Write the description between the DESC delimiters below.
#   * Finally, don't worry about the indent, CocoaPods strips it!

  s.description      = <<-DESC
TODO: Add long description of the pod here.
                       DESC

  s.homepage         = 'https://www.51xiaodou.com'
  # s.screenshots     = 'www.example.com/screenshots_1', 'www.example.com/screenshots_2'
  s.license          = { :type => 'MIT', :file => 'LICENSE' }
  s.author           = { 'xiao-xi' => '36871102@qq.com' }
  s.source           = { :git => 'http://git.51xiaodou.com/XD_App_dev/XDPush.git', :tag => s.version.to_s }
  # s.social_media_url = 'https://twitter.com/<TWITTER_USERNAME>'

  s.ios.deployment_target = '8.0'
  s.source_files = 'PushDemo/Classes/**/*.{h,m}'
  s.subspec 'JPush' do |jpush|
    jpush.source_files = 'PushDemo/JPush/*.h'
    jpush.public_header_files = 'PushDemo/JPush/*.h'
    jpush.frameworks = 'CFNetwork','CoreFoundation','CoreTelephony','SystemConfiguration','CoreGraphics','Foundation','UIKit','Security','UserNotifications'
    jpush.ios.preserve_paths      = 'PushDemo/JPush/libjcore-ios-1.1.3.a', 'PushDemo/JPush/libjpush-ios-3.0.5.a'
    jpush.ios.vendored_libraries  = 'PushDemo/JPush/libjcore-ios-1.1.3.a', 'PushDemo/JPush/libjpush-ios-3.0.5.a'
    jpush.libraries = 'resolv','z'
    jpush.xcconfig = { 'HEADER_SEARCH_PATHS' => "${PODS_ROOT}/#{s.name}/PushDemo/JPush/**" }
  end
end

```

## Project that demonstrates the issue

The git repository of my project is : https://git.coding.net/one_fools/Demo.git

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
