### ISSUE TITLE
EACCES - Permission denied (pointing to a non-existent hard drive)

### ISSUE THREAD

**Issue by ysoftware** [CocoaPods/CocoaPods#6894]
### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?
pod install

* What did you expect to happen?
I used this exact podfile before on another machine and it worked.

* What happened instead?
CocoaPods downloaded all the pods I needed but then gave me the following error. 

I find it interesting because it says, I don't have access to Volumes/Media HD, but this is the hard drive from my previous machine and it does not exist in this environment. I also get the same error in the desktop app, v1.2.0. I've tried deleting Pods folder, 

Another fun thing - is that my project build and runs just fine. 
Please, ask for more if you find it interesting or just close it if this issue is of no help for you.
Cheers.

### Stack

```
   CocoaPods : 1.3.0.beta.3
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.6 (16G29)
       Xcode : 8.3.3 (8E3004b)
         Git : git version 2.11.0 (Apple Git-81)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 91f41326925c4c55411fee5b733380a01dda79b1
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
workspace '/Volumes/Media HD/ysoftware/Documents/Doctor Who/Whoniverse iOS/iOSDoctorWho/Whoniverse.xcworkspace'

use_frameworks!

abstract_target 'App' do

  # shared pods
  pod 'Kingfisher', '~> 3'
  pod 'CoreStore', '~> 4'
  pod 'SwiftyJSON'

  target 'iOSDoctorWho' do
    platform :ios, '8.0'
    
    pod 'R.swift'
    pod 'Google-Mobile-Ads-SDK'
	  pod 'SKPhotoBrowser'
    inherit! :search_paths
  end

  target 'WatchOS Extension' do
    platform :watchos, '2.0'
  end

  target 'iOSDoctorWho Today Extension' do
    platform :ios, '8.2'
  end
  
end
```

### Error

```
Errno::EACCES - Permission denied - /Volumes/Media HD
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:245:in `mkdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:245:in `fu_mkdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:219:in `block (2 levels) in mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:217:in `reverse_each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:217:in `block in mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:203:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:203:in `mkdir_p'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.5.1/lib/xcodeproj/workspace.rb:178:in `save_as'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.0.beta.3/lib/cocoapods/installer/user_project_integrator.rb:101:in `create_workspace'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.0.beta.3/lib/cocoapods/installer/user_project_integrator.rb:62:in `integrate!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.0.beta.3/lib/cocoapods/installer.rb:563:in `block in integrate_user_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.0.beta.3/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.0.beta.3/lib/cocoapods/installer.rb:560:in `integrate_user_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.0.beta.3/lib/cocoapods/installer.rb:121:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.0.beta.3/lib/cocoapods/command/install.rb:41:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.0.beta.3/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.0.beta.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by amorde** [comment]
This line:

```
workspace '/Volumes/Media HD/ysoftware/Documents/Doctor Who/Whoniverse iOS/iOSDoctorWho/Whoniverse.xcworkspace'
```

in your Podfile is telling CocoaPods to create the workspace there. Remove that line to use CocoaPod's default behavior of creating a workspace in the same directory of the project.

**Comment by dnkoutso** [comment]
I believe what @amorde is correct and also I do not think this is an issue with CocoaPods. Going to close this one.

We *could* perhaps provide a better error message....................
