### ISSUE TITLE
CocoaPods crashes only when Pod is specified by git URL

### ISSUE THREAD

**Issue by colemancda** [CocoaPods/CocoaPods#6946]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod install` with development pod specified by local path, which succeeded. Then tried to run `pod install` again after changing the development pod path to its git URL, and which caused `pod` to crash.

## What did you expect to happen?

Install all pod dependencies correctly as when the pod is specified as path.

## What happened instead?

The command line `pod` program crashed.

```
Errno::ENOENT - No such file or directory - /Users/coleman/Developer/LinPhoneSwiftPodExample/Pods/BelledonneSIP/Sources/LinPhone
/usr/local/Cellar/cocoapods/1.3.1/libexec/gems/cocoapods-1.3.1/lib/cocoapods/project.rb:189:in `realpath'
/usr/local/Cellar/cocoapods/1.3.1/libexec/gems/cocoapods-1.3.1/lib/cocoapods/project.rb:189:in `realpath'
/usr/local/Cellar/cocoapods/1.3.1/libexec/gems/cocoapods-1.3.1/lib/cocoapods/project.rb:189:in `add_file_reference'
/usr/local/Cellar/cocoapods/1.3.1/libexec/gems/cocoapods-1.3.1/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:188:in `block (2 levels) in add_file_accessors_paths_to_pods_group'
/usr/local/Cellar/cocoapods/1.3.1/libexec/gems/cocoapods-1.3.1/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:186:in `each'
/usr/local/Cellar/cocoapods/1.3.1/libexec/gems/cocoapods-1.3.1/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:186:in `block in add_file_accessors_paths_to_pods_group'
/usr/local/Cellar/cocoapods/1.3.1/libexec/gems/cocoapods-1.3.1/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:180:in `each'
/usr/local/Cellar/cocoapods/1.3.1/libexec/gems/cocoapods-1.3.1/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:180:in `add_file_accessors_paths_to_pods_group'
/usr/local/Cellar/cocoapods/1.3.1/libexec/gems/cocoapods-1.3.1/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:74:in `block in add_source_files_references'
/usr/local/Cellar/cocoapods/1.3.1/libexec/gems/cocoapods-1.3.1/lib/cocoapods/user_interface.rb:142:in `message'
/usr/local/Cellar/cocoapods/1.3.1/libexec/gems/cocoapods-1.3.1/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:73:in `add_source_files_references'
/usr/local/Cellar/cocoapods/1.3.1/libexec/gems/cocoapods-1.3.1/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:39:in `install!'
/usr/local/Cellar/cocoapods/1.3.1/libexec/gems/cocoapods-1.3.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:161:in `install_file_references'
/usr/local/Cellar/cocoapods/1.3.1/libexec/gems/cocoapods-1.3.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:64:in `generate!'
/usr/local/Cellar/cocoapods/1.3.1/libexec/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:183:in `block in generate_pods_project'
/usr/local/Cellar/cocoapods/1.3.1/libexec/gems/cocoapods-1.3.1/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/Cellar/cocoapods/1.3.1/libexec/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:182:in `generate_pods_project'
/usr/local/Cellar/cocoapods/1.3.1/libexec/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:119:in `install!'
/usr/local/Cellar/cocoapods/1.3.1/libexec/gems/cocoapods-1.3.1/lib/cocoapods/command/install.rb:41:in `run'
/usr/local/Cellar/cocoapods/1.3.1/libexec/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/usr/local/Cellar/cocoapods/1.3.1/libexec/gems/cocoapods-1.3.1/lib/cocoapods/command.rb:52:in `run'
/usr/local/Cellar/cocoapods/1.3.1/libexec/gems/cocoapods-1.3.1/bin/pod:55:in `<top (required)>'
/usr/local/Cellar/cocoapods/1.3.1/libexec/bin/pod:23:in `load'
/usr/local/Cellar/cocoapods/1.3.1/libexec/bin/pod:23:in `<main>'
```

### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.6 (16G29)
       Xcode : 8.3.3 (8E3004b)
         Git : git version 2.11.0 (Apple Git-81)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ de8185e19b457c12459c532235bc8b17be051424
```

### Installation Source

```
Executable Path: /usr/local/Cellar/cocoapods/1.3.1/libexec/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'

use_frameworks!

target 'LinPhoneSwiftExample' do
	pod 'BelledonneToolbox', :git => 'https://github.com/colemancda/LinPhoneSwift.git'
	pod 'BelledonneSIP', :git => 'https://github.com/colemancda/LinPhoneSwift.git'
	pod 'MediaStreamer', :git => 'https://github.com/colemancda/LinPhoneSwift.git'
	pod 'LinPhoneSwift', :git => 'https://github.com/colemancda/LinPhoneSwift.git'
end
```

## Project that demonstrates the issue

https://github.com/colemancda/LinPhoneSwiftPodExample

**Comment by amorde** [comment]
Side note, I'd be willing to argue that a better error message here would be helpful

**Comment by colemancda** [comment]
@amorde Thanks for helping me out, I'll manually specify those files and exclude the symlinks.

**Comment by amorde** [comment]
@colemancda No problem. Please report back if that fixes the issue :)

**Comment by dnkoutso** [comment]
@amorde feel free to make a PR to improve the error message :D

**Comment by dnkoutso** [comment]
Also see this PR if you want to finish it up https://github.com/CocoaPods/CocoaPods/pull/6604
