### ISSUE TITLE
Nanaimo::Reader::ParseError - [!] Array missing ',' in between objects

### ISSUE THREAD

**Issue by cpheinrich** [CocoaPods/CocoaPods#6947]
### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

 I merged my master branch  into develop branch and then opened the .xcworkspace file, but XCode couldn't load project due to Workspace integrity so I tried to fix the issue by running 'pod install'

* What did you expect to happen?

 I expected pod install to work and for my .xcworkspace file to be fixed

* What happened instead?
 Pod install failed with the error provided below.

**NOTE:** This error is similar to one raised in issue #6129, but the solution given there (gem install nanaimo) didn't fix my issue. I should also mention that the Vuforia_UnityExtensions.... files it complains about are file that are auto-generated by Unity. Any advice on how to get around this would be greatly appreciated. Thanks!

### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.6 (16G29)
       Xcode : 8.3.3 (8E3004b)
         Git : git version 2.13.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 6c856971d2d5f010439ce9ec635a30f2b508e425
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '9.2'

target 'triple' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for triple
  pod 'RealmSwift'
  pod 'ObjectMapper'
  pod 'Kingfisher'
  pod 'Alamofire'
  pod 'Analytics'
  pod 'Branch'
  pod 'Sentry', :git => 'https://github.com/getsentry/sentry-cocoa.git', :subspecs => ['Core', 'KSCrash'], :tag => '3.1.2'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0' # or '3.0'
    end
  end
end
```

### Error

```
Nanaimo::Reader::ParseError - [!] Array missing ',' in between objects
     #  -------------------------------------------
     #  				B26B82291F33FA47003D2669 /* Vuforia_UnityExtensions_Vuforia_WordResultImpl911273601.h */,
     #  				B26B822A1F33FA47003D2669 /* Vuforia_UnityExtensions_Vuforia_WordTemplateMode1097144495.h */,
15846>  		B22BC2B51EA7AD8500C8E978 /* Native */ = {
        		                                      ^
     #  			isa = PBXGroup;
     #  			children = (
     #  -------------------------------------------

/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:284:in `raise_parser_error'
/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:173:in `parse_array'
/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:133:in `parse_object'
/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:192:in `parse_dictionary'
/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:131:in `parse_object'
/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:192:in `parse_dictionary'
/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:131:in `parse_object'
/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:192:in `parse_dictionary'
/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:131:in `parse_object'
/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:106:in `parse!'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.5.1/lib/xcodeproj/plist.rb:27:in `read_from_path'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.5.1/lib/xcodeproj/project.rb:200:in `initialize_from_file'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.5.1/lib/xcodeproj/project.rb:102:in `open'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/analyzer.rb:903:in `block (2 levels) in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/analyzer.rb:902:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/analyzer.rb:902:in `block in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/analyzer.rb:897:in `inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/analyzer.rb:69:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:242:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:154:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:153:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:116:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/command/install.rb:41:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by orta** [comment]
Can you post an example xcodeproject?

**Comment by cpheinrich** [comment]
Hello, thanks for getting back to me. Unfortunately, the project has many parts, some of which are not in Github, and I haven't found a way to get a simple example project that reproduces the issue. Do you have any general advice for things I can try? 

Things I have tried so far:
- uninstalling old versions of nanaimo
- reinstalling cocoapods
- updating cocoapods

and so far no luck. Thanks!
