### ISSUE TITLE
Build MobileVLCKit  Errno::EINVAL - Invalid argument

### ISSUE THREAD

**Issue by tonycap** [CocoaPods/CocoaPods#7004]
> ℹ Errno::EINVAL - Invalid argument
> hi ， i have use VLC bitcode for iOS， but cocoapods lib only have no bitcode. so i Compile the VLC。 because this famework is only for me , so I build local pod lib. use VLC framework is work by use pod install. but use builded bitcode VLC has err :Errno::EINVAL - Invalid argument - MobileVLCKit.framework/MobileVLCKit
>  so i want to know how to reslove it.

# Report

## What did you do?

ℹ  create local pod lib,  podspec is 
```
Pod::Spec.new do |s|

  # ―――  Spec Metadata  ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――― #
  #
  #  These will help people to find your library, and whilst it
  #  can feel like a chore to fill in it's definitely to your advantage. The
  #  summary should be tweet-length, and the description more in depth.
  #

  s.name         = "MobileVLCKit"
  s.version      = "1.0.0"
  s.summary      = "MobileVLCKit is an bitcode Objective-C for libvlc's external interface on iOS"
  s.homepage     = "https://wiki.videolan.org/VLCKit/"

  s.license      = "MIT"

  # ――― Author Metadata  ――――――――――――――――――――――――――――――――――――――――――――――――――――――――― #
  s.author             = { "*********" => "********" }

  #  Specify the location from where the source should be retrieved.
  #  Supports git, hg, bzr, svn and HTTP.
  #

  s.source       = { :git => "", :tag => "0.0.1" }

  s.ios.vendored_framework = 'MobileVLCKit.framework'
  s.public_header_files = 'obileVLCKit.framework/Headers/*.h'
  s.ios.deployment_target = '7.0'
  s.frameworks = 'QuartzCore', 'CoreText', 'AVFoundation', 'Security', 'CFNetwork', 'AudioToolbox', 'OpenGLES', 'CoreGraphics', 'VideoToolbox', 'CoreMedia'
  s.libraries = 'c++', 'xml2', 'z', 'bz2', 'iconv', 'c++11'
  s.requires_arc = false
   s.xcconfig = {
    'CLANG_CXX_LANGUAGE_STANDARD' => 'c++11',
    'CLANG_CXX_LIBRARY' => 'libc++'
  }

end
```

ℹ  `pod install`
  it show 
```
Errno::EINVAL - Invalid argument - /Users/a123/Documents/project/qiju_pro_ios/Qiju/ThirdParty/VLC/MobileVLCKit.framework/MobileVLCKit
/Library/Ruby/Gems/2.0.0/gems/ruby-macho-1.1.0/lib/macho/fat_file.rb:62:in `read'
/Library/Ruby/Gems/2.0.0/gems/ruby-macho-1.1.0/lib/macho/fat_file.rb:62:in `open'
/Library/Ruby/Gems/2.0.0/gems/ruby-macho-1.1.0/lib/macho/fat_file.rb:62:in `initialize'
/Library/Ruby/Gems/2.0.0/gems/ruby-macho-1.1.0/lib/macho.rb:31:in `new'
/Library/Ruby/Gems/2.0.0/gems/ruby-macho-1.1.0/lib/macho.rb:31:in `open'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.0.beta.2/lib/cocoapods/sandbox/file_accessor.rb:379:in `dynamic_binary?'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.0.beta.2/lib/cocoapods/sandbox/file_accessor.rb:162:in `block in vendored_dynamic_frameworks'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.0.beta.2/lib/cocoapods/sandbox/file_accessor.rb:161:in `select'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.0.beta.2/lib/cocoapods/sandbox/file_accessor.rb:161:in `vendored_dynamic_frameworks'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.0.beta.2/lib/cocoapods/sandbox/file_accessor.rb:170:in `vendored_static_frameworks'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.0.beta.2/lib/cocoapods/generator/xcconfig/xcconfig_helper.rb:107:in `add_static_dependency_build_settings'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.0.beta.2/lib/cocoapods/generator/xcconfig/xcconfig_helper.rb:80:in `block in add_settings_for_file_accessors_of_target'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.0.beta.2/lib/cocoapods/generator/xcconfig/xcconfig_helper.rb:78:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.0.beta.2/lib/cocoapods/generator/xcconfig/xcconfig_helper.rb:78:in `add_settings_for_file_accessors_of_target'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.0.beta.2/lib/cocoapods/generator/xcconfig/xcconfig_helper.rb:322:in `block in generate_vendored_build_settings'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.0.beta.2/lib/cocoapods/generator/xcconfig/xcconfig_helper.rb:320:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.0.beta.2/lib/cocoapods/generator/xcconfig/xcconfig_helper.rb:320:in `generate_vendored_build_settings'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.0.beta.2/lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb:75:in `generate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.0.beta.2/lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb:39:in `save_as'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:87:in `block in create_xcconfig_file'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:84:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:84:in `create_xcconfig_file'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:18:in `block in install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.0.beta.2/lib/cocoapods/user_interface.rb:142:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:14:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:165:in `block (2 levels) in install_libraries'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:163:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:163:in `block in install_libraries'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.0.beta.2/lib/cocoapods/user_interface.rb:142:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:157:in `install_libraries'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:64:in `generate!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.0.beta.2/lib/cocoapods/installer.rb:183:in `block in generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.0.beta.2/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.0.beta.2/lib/cocoapods/installer.rb:182:in `generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.0.beta.2/lib/cocoapods/installer.rb:119:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.0.beta.2/lib/cocoapods/command/install.rb:41:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.0.beta.2/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.0.beta.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

what should i do?

**Comment by dnkoutso** [comment]
This looks like a corrupted or bad `MobileVLCKit.framework` file that cannot be processed. Are you sure the file is valid?

**Comment by dnkoutso** [comment]
I believe this is not a cocoapods library issue so I am going to close it but will keep an eye out.
