### ISSUE TITLE
pod install doesnt work anymore

### ISSUE THREAD

**Issue by appcelerate** [CocoaPods/CocoaPods#7005]
### Command

```
/Users/.../.rvm/gems/ruby-2.1.5/bin/pod install
```

### Report

* What did you do?
run pod install

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin14.0]
    RubyGems : 2.4.3
        Host : Mac OS X 10.12.6 (16G29)
       Xcode : 8.3.3 (8E3004b)
         Git : git version 2.11.0 (Apple Git-81)
Ruby lib dir : /Users/.../.rvm/rubies/ruby-2.1.5/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 5721e4e78b7ddeb0ea9c9a034f3aa1a99daf5d62
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# coding: utf-8
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!
# ignore all warnings from all pods
inhibit_all_warnings!
target "App" do

    pod 'Adjust',  '<=4.10.2', :inhibit_warnings => true
    pod 'Alamofire', '<=4.3.0', :inhibit_warnings => true
    pod 'Amplitude-iOS', '<=3.8.5', :inhibit_warnings => true
    pod 'Appboy-iOS-SDK', '<=2.24.3', :inhibit_warnings => true
    pod 'Crashlytics', '~>  3.8', :inhibit_warnings => true
    pod 'DeepLinkKit', '<=1.2.2', :inhibit_warnings => true
    pod 'FBSDKCoreKit', '<=4.18.0', :inhibit_warnings => true
    pod 'FBSDKLoginKit', '<=4.18.0', :inhibit_warnings => true
    pod 'FBSDKShareKit', '<=4.18.0', :inhibit_warnings => true
    pod 'Fabric', :inhibit_warnings => true
    pod 'GoogleConversionTracking', '3.4.0', :inhibit_warnings => true
    pod 'IQKeyboardManagerSwift', '<=4.0.8', :inhibit_warnings => true
    pod 'JTAppleCalendar', '<=6.1.6', :inhibit_warnings => true
    pod 'KDCircularProgress', '~>  1.5.2', :inhibit_warnings => true
    pod 'KMPlaceholderTextView', '~> 1.3.0', :inhibit_warnings => true
    pod 'MKRingProgressView', '<=1.1', :inhibit_warnings => true
    pod 'NVActivityIndicatorView', '~>  3.6.0', :inhibit_warnings => true
    pod 'ObjectMapper', '<=2.1.0', :inhibit_warnings => true
    pod 'Presentr', '~>  1.2.3', :inhibit_warnings => true
    pod 'SAConfettiView', :git => 'https://github.com/gokhanakkurt/SAConfettiView', :branch => 'swift3', :inhibit_warnings => true
    pod 'SwiftyUserDefaults', '<=3.0.1', :inhibit_warnings => true
    pod 'XCGLogger', '<=4.0.0', :inhibit_warnings => true
    pod 'MZDownloadManager'
    pod 'M13ProgressSuite'
    pod 'Kingfisher', '<= 3.12.2'
    pod 'Firebase/Core'
    pod 'Firebase/RemoteConfig'
    pod 'Firebase/Crash'
    pod 'Firebase/Performance'
    pod 'FacebookShare'

end

target "Today Extension" do
    pod 'Alamofire', '<=4.3.0', :inhibit_warnings => true
    pod 'SwiftyUserDefaults', '<=3.0.1', :inhibit_warnings => true
    pod 'Fabric'
    pod 'Crashlytics', '~>  3.8'
end

target "Rich Notification" do
    pod 'Appboy-iOS-SDK', '<=2.24.3', :inhibit_warnings => true
    pod 'Fabric'
    pod 'Crashlytics', '~>  3.8'
end

target "Message Extension" do
    use_frameworks!
    pod 'Alamofire', '<=4.3.0', :inhibit_warnings => true
    pod 'AlamofireImage', '<=3.2.0', :inhibit_warnings => true
    pod 'SwiftyUserDefaults', '<=3.0.1', :inhibit_warnings => true
    pod 'Fabric'
    pod 'Crashlytics', '~>  3.8'
end

target "Watch Extension" do
    platform :watchos, '3.0'
    use_frameworks!
    pod 'Alamofire', '<=4.3.0', :inhibit_warnings => true
    pod 'AlamofireImage', '<=3.2.0', :inhibit_warnings => true
    pod 'SwiftyUserDefaults', '<=3.0.1', :inhibit_warnings => true

end


post_install do |installer|

    puts("Generating Acknowledgements.plist…")
    require 'fileutils'
    FileUtils.cp_r('Pods/Target Support Files/Pods-App/Pods-App-
-acknowledgements.plist', 'App/Settings.bundle/Acknowledgements.plist', :remove_destination => true)

    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end

    puts("Config Appboy")
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if target.name == "Appboy-iOS-SDK"
                config.build_settings["OTHER_LDFLAGS"] = '$(inherited) "-ObjC"'
            end
        end
    end

    puts("Update debug pod settings to speed up build time")
    Dir.glob(File.join("Pods", "**", "Pods*{debug,Private}.xcconfig")).each do |file|
        File.open(file, 'a') { |f| f.puts "\nDEBUG_INFORMATION_FORMAT = dwarf" }
    end

end
```

### Error

```
Nanaimo::Reader::ParseError - [!] Unexpected end of string while parsing
   #  -------------------------------------------
   #  			containerPortal = F16DA3401BB032B30072C724 /* Project object */;
   #  			proxyType = 1;
716>  			remoteGlobalIDString =
      			                       ^
   #  -------------------------------------------

/Users/.../.rvm/gems/ruby-2.1.5@global/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:284:in `raise_parser_error'
/Users/.../.rvm/gems/ruby-2.1.5@global/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:129:in `parse_object'
/Users/.../.rvm/gems/ruby-2.1.5@global/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:192:in `parse_dictionary'
/Users/.../.rvm/gems/ruby-2.1.5@global/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:131:in `parse_object'
/Users/.../.rvm/gems/ruby-2.1.5@global/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:192:in `parse_dictionary'
/Users/.../.rvm/gems/ruby-2.1.5@global/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:131:in `parse_object'
/Users/.../.rvm/gems/ruby-2.1.5@global/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:192:in `parse_dictionary'
/Users/.../.rvm/gems/ruby-2.1.5@global/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:131:in `parse_object'
/Users/.../.rvm/gems/ruby-2.1.5@global/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:106:in `parse!'
/Users/.../.rvm/gems/ruby-2.1.5/gems/xcodeproj-1.5.1/lib/xcodeproj/plist.rb:27:in `read_from_path'
/Users/.../.rvm/gems/ruby-2.1.5/gems/xcodeproj-1.5.1/lib/xcodeproj/project.rb:200:in `initialize_from_file'
/Users/.../.rvm/gems/ruby-2.1.5/gems/xcodeproj-1.5.1/lib/xcodeproj/project.rb:102:in `open'
/Users/.../.rvm/gems/ruby-2.1.5@global/gems/cocoapods-1.3.1/lib/cocoapods/installer/analyzer.rb:903:in `block (2 levels) in inspect_targets_to_integrate'
/Users/.../.rvm/gems/ruby-2.1.5@global/gems/cocoapods-1.3.1/lib/cocoapods/installer/analyzer.rb:902:in `each'
/Users/.../.rvm/gems/ruby-2.1.5@global/gems/cocoapods-1.3.1/lib/cocoapods/installer/analyzer.rb:902:in `block in inspect_targets_to_integrate'
/Users/.../.rvm/gems/ruby-2.1.5@global/gems/cocoapods-1.3.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/.../.rvm/gems/ruby-2.1.5@global/gems/cocoapods-1.3.1/lib/cocoapods/installer/analyzer.rb:897:in `inspect_targets_to_integrate'
/Users/.../.rvm/gems/ruby-2.1.5@global/gems/cocoapods-1.3.1/lib/cocoapods/installer/analyzer.rb:69:in `analyze'
/Users/.../.rvm/gems/ruby-2.1.5@global/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:242:in `analyze'
/Users/.../.rvm/gems/ruby-2.1.5@global/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:154:in `block in resolve_dependencies'
/Users/.../.rvm/gems/ruby-2.1.5@global/gems/cocoapods-1.3.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/.../.rvm/gems/ruby-2.1.5@global/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:153:in `resolve_dependencies'
/Users/.../.rvm/gems/ruby-2.1.5@global/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:116:in `install!'
/Users/.../.rvm/gems/ruby-2.1.5@global/gems/cocoapods-1.3.1/lib/cocoapods/command/install.rb:41:in `run'
/Users/.../.rvm/gems/ruby-2.1.5@global/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/.../.rvm/gems/ruby-2.1.5@global/gems/cocoapods-1.3.1/lib/cocoapods/command.rb:52:in `run'
/Users/.../.rvm/gems/ruby-2.1.5@global/gems/cocoapods-1.3.1/bin/pod:55:in `<top (required)>'
/Users/.../.rvm/gems/ruby-2.1.5/bin/pod:23:in `load'
/Users/.../.rvm/gems/ruby-2.1.5/bin/pod:23:in `<main>'
/Users/.../.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/Users/.../.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by dnkoutso** [comment]
I dont think this is a library issue. Please check the error and your xcodeproj setting where the error points to.

**Comment by terflogag** [comment]
Same issue since this morning, but nothing change since the last week in my project 🤔
