### ISSUE TITLE
Qt generated Xcode project didn't appreciate by 'pod install'

### ISSUE THREAD

**Issue by ensoreus** [CocoaPods/CocoaPods#7018]
### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.6 (16G29)
       Xcode : 8.3.3 (8E3004b)
         Git : git version 2.11.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 01a7df9c4b33652ff0cee6cd5d901462966d6e44
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '9.0'

source "https://github.com/CocoaPods/Specs.git"

target 'MyProject' do
  use_frameworks!
  pod 'Firebase/Core'
end
```

### Error

```
RuntimeError - [!] Xcodeproj doesn't know about the following attributes {"name"=>"Compile Sources"} for the 'PBXSourcesBuildPhase' isa.
If this attribute was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project/object.rb:321:in `configure_with_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project.rb:261:in `new_from_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project/object.rb:350:in `object_with_uuid'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project/object.rb:300:in `block (2 levels) in configure_with_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project/object.rb:299:in `each'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project/object.rb:299:in `block in configure_with_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project/object.rb:296:in `each'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project/object.rb:296:in `configure_with_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project.rb:261:in `new_from_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project/object.rb:350:in `object_with_uuid'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project/object.rb:300:in `block (2 levels) in configure_with_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project/object.rb:299:in `each'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project/object.rb:299:in `block in configure_with_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project/object.rb:296:in `each'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project/object.rb:296:in `configure_with_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project.rb:261:in `new_from_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project.rb:202:in `initialize_from_file'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project.rb:102:in `open'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:855:in `block (2 levels) in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:854:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:854:in `block in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:849:in `inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:66:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:236:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:150:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:149:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:110:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command/install.rb:37:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by dnkoutso** [comment]
Maybe update to 1.3.1 of CocoaPods which updates to a later version of Xcodeproj?

Also this does not seem to be a cocoapods library issue in my opinion.

**Comment by ensoreus** [comment]
`Updating installed gems
Nothing to update`

Seems like I have to update up to 1.3.1 by hands

**Comment by ensoreus** [comment]
But thank you anyway

**Comment by dnkoutso** [comment]
@ensoreus did that fix the problem?

**Comment by ensoreus** [comment]
Not really
Xcodeproj fails to recognize tags
"PBXSources"
"PBXFramework"
"PBXResource"
So I just made a elisp script to remove them. Seems like int harmless

**Comment by tonnyonepos** [comment]
@ensoreus can you go into more detail about how you fixed the problem? Are you editing the project.pbxproj file? Your help is much appreciated!

**Comment by pro9rammer** [comment]
Appreciate @pro9rammer

**Comment by tonnyonepos** [comment]
@ensoreus Thank you very much! I had a few more errors like this. Simply deleted those properties. Was able to get 'pod init' working.

**Comment by dnkoutso** [comment]
I think I am going to close this and we should perhaps reopen an issue with Xcodeproj to support these attributes or make Qt not print out those attributes. If you feel strongly please comment here and depending on the issue I can re-open.
