### ISSUE TITLE
CocoaDocs fails for project

### ISSUE THREAD

**Issue by gk-brown** [CocoaPods/CocoaPods#7041]
**NOTE** _I submitted this issue yesterday on the [CocoaDocs repo](https://github.com/CocoaPods/cocoadocs.org/issues/538). Resubmitting here since I'm not sure which is most appropriate._

I recently pushed [MarkupKit](https://github.com/gk-brown/MarkupKit) version 3.4, but the documentation still refers to version 3.3.

  http://cocoadocs.org/docsets/MarkupKit/

I tried re-generating the docs via this URL:

  http://api.cocoadocs.org:4567/redeploy/MarkupKit/latest

However, this did not resolve the problem. According to the following URL, it seems like it might be a disk space issue:

  http://api.cocoadocs.org:4567/error/MarkupKit/3.4

The output is as follows:

```
report_error({"message":"\u001b[31m[!] /usr/bin/git clone https://github.com/gk-brown/MarkupKit.git /Users/cocoadocs/cocoadocs.org/activity_pods/download/MarkupKit/3.4/MarkupKit --template= --single-branch --depth 1 --branch 3.4\n\nCloning into '/Users/cocoadocs/cocoadocs.org/activity_pods/download/MarkupKit/3.4/MarkupKit'...\nfatal: unable to lock packed-refs file: No space left on device\n\u001b[0m","trace":["/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/cocoapods-1.1.1/lib/cocoapods/executable.rb:69:in `execute_command'","/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/cocoapods-1.1.1/lib/cocoapods/downloader.rb:140:in `execute_command'","/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/cocoapods-downloader-1.1.3/lib/cocoapods-downloader/base.rb:154:in `block in executable'","/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/cocoapods-downloader-1.1.3/lib/cocoapods-downloader/git.rb:79:in `block in clone'","/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/cocoapods-1.1.1/lib/cocoapods/downloader.rb:173:in `block in ui_sub_action'","/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'","/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/cocoapods-1.1.1/lib/cocoapods/downloader.rb:172:in `ui_sub_action'","/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/cocoapods-downloader-1.1.3/lib/cocoapods-downloader/git.rb:77:in `clone'","/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/cocoapods-downloader-1.1.3/lib/cocoapods-downloader/git.rb:45:in `download!'","/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/cocoapods-downloader-1.1.3/lib/cocoapods-downloader/base.rb:82:in `block in download'","/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/cocoapods-1.1.1/lib/cocoapods/downloader.rb:157:in `block in ui_action'","/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'","/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/cocoapods-1.1.1/lib/cocoapods/downloader.rb:156:in `ui_action'","/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/cocoapods-downloader-1.1.3/lib/cocoapods-downloader/base.rb:80:in `download'","/Users/cocoadocs/cocoadocs.org/classes/source_downloader.rb:36:in `block in download_pod_source_files'","/Users/cocoadocs/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'","/Users/cocoadocs/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/timeout.rb:35:in `block in catch'","/Users/cocoadocs/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/timeout.rb:35:in `catch'","/Users/cocoadocs/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/timeout.rb:35:in `catch'","/Users/cocoadocs/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/timeout.rb:106:in `timeout'","/Users/cocoadocs/cocoadocs.org/classes/source_downloader.rb:34:in `download_pod_source_files'","/Users/cocoadocs/cocoadocs.org/./cocoapods-simple.rb:72:in `run'","/Users/cocoadocs/cocoadocs.org/./cocoapods-simple.rb:192:in `<main>'"]}
)
```

**Comment by orta** [comment]
Hi, yeah, the CocoaDocs repo is the right place for this. I don't have much time for CocoaPods anymore but CocoaDocs [was sunsetted back in May](http://blog.cocoapods.org/CocoaDocs-Documentation-Sunsetting/) from our side, so it's just been continuing to run while there's work to migrate to another host. So I'm closing this issue, as your original is in the right place.
