### ISSUE TITLE
Pod search failed after installed Xcode 9

### ISSUE THREAD

**Issue by lnnkai** [CocoaPods/CocoaPods#7071]
# Report

## What did you do?

Run `pod search Bugly`

## What did you expect to happen?

List result correctly.

### Error

```
JSON::ParserError - 751: unexpected token at ''
/usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/json/common.rb:156:in `parse'
/usr/local/Cellar/ruby/2.4.2/lib/ruby/2.4.0/json/common.rb:156:in `parse'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-core-1.4.0.beta.1/lib/cocoapods-core/source/manager.rb:251:in `stored_search_index'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-core-1.4.0.beta.1/lib/cocoapods-core/source/manager.rb:187:in `updated_search_index'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-core-1.4.0.beta.1/lib/cocoapods-core/source/manager.rb:118:in `search_by_name'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-search-1.0.0/lib/cocoapods-search/command/search.rb:87:in `local_search'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-search-1.0.0/lib/cocoapods-search/command/search.rb:63:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.4.0.beta.1/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.4.0.beta.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

### Stack

```
   CocoaPods : 1.4.0.beta.1
        Ruby : ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin16]
    RubyGems : 2.6.13
        Host : Mac OS X 10.12.6 (16G29)
       Xcode : 9.0 (9A235)
         Git : git version 2.13.5 (Apple Git-94)
Ruby lib dir : /usr/local/Cellar/ruby/2.4.2/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 0d86944714c9ef1cc4b289fc23d8033e90099644
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

**Comment by dnkoutso** [comment]
Try removing the search index:

```
rm ~/Library/Caches/CocoaPods/search_index.json
pod search Bugly
```

**Comment by lnnkai** [comment]
all right，thanks.
