### ISSUE TITLE
cocoapods will not run at all without sudo, gives error `expand_path': user . doesn't exist (ArgumentError)

### ISSUE THREAD

**Issue by jspenc72** [CocoaPods/CocoaPods#7113]
# Report

## What did you do?

ℹ Please replace this with what you did.  
Run
```bash 
pod
```

```bash 
pod install
pod update
pod env
```
## What did you expect to happen?

See standard usage output, install pods, update pods.

## What happened instead?
```bash
/Users/jsp/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.4.0.beta.1/lib/cocoapods/executable.rb:93:in `expand_path': user . doesn't exist (ArgumentError)
	from /Users/jsp/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.4.0.beta.1/lib/cocoapods/executable.rb:93:in `block in which'
	from /Users/jsp/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.4.0.beta.1/lib/cocoapods/executable.rb:92:in `each'
	from /Users/jsp/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.4.0.beta.1/lib/cocoapods/executable.rb:92:in `which'
	from /Users/jsp/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.4.0.beta.1/lib/cocoapods/executable.rb:110:in `which!'
	from /Users/jsp/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.4.0.beta.1/lib/cocoapods/executable.rb:133:in `capture_command'
	from /Users/jsp/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.4.0.beta.1/lib/cocoapods/command.rb:116:in `git_version'
	from /Users/jsp/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.4.0.beta.1/lib/cocoapods/command.rb:128:in `verify_minimum_git_version!'
	from /Users/jsp/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.4.0.beta.1/lib/cocoapods/command.rb:49:in `run'
	from /Users/jsp/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.4.0.beta.1/bin/pod:55:in `<top (required)>'
	from /Users/jsp/.rvm/gems/ruby-2.4.1/bin/pod:23:in `load'
	from /Users/jsp/.rvm/gems/ruby-2.4.1/bin/pod:23:in `<main>'
	from /Users/jsp/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/jsp/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
```
## CocoaPods Environment (pod env) gives error above
Here is output of ```env``` instead
```bash
jesses-mbp:~ jsp$ env
MANPATH=/Users/jsp/.nvm/versions/node/v8.1.2/share/man:/usr/local/share/man:/usr/share/man:/opt/X11/share/man:/Library/TeX/texbin/man:/Applications/Xcode.app/Contents/Developer/usr/share/man:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man
rvm_bin_path=/Users/jsp/.rvm/bin
TERM_PROGRAM=Apple_Terminal
GEM_HOME=/Users/jsp/.rvm/gems/ruby-2.4.1
NVM_CD_FLAGS=
SHELL=/bin/bash
TERM=xterm-256color
IRBRC=/Users/jsp/.rvm/rubies/ruby-2.4.1/.irbrc
TMPDIR=/var/folders/15/6_l9f4vj6t9010qr18930q0w0000gn/T/
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.6rR3BpVA2P/Render
TERM_PROGRAM_VERSION=388.1.1
MY_RUBY_HOME=/Users/jsp/.rvm/rubies/ruby-2.4.1
TERM_SESSION_ID=9C4AB9BA-5BF9-4B4E-BC9C-E026666EDF40
NVM_DIR=/Users/jsp/.nvm
USER=jsp
_system_type=Darwin
rvm_path=/Users/jsp/.rvm
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.UkzvLBah48/Listeners
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
rvm_prefix=/Users/jsp
PATH=/Users/jsp/.rvm/gems/ruby-2.4.1/bin:/Users/jsp/.rvm/gems/ruby-2.4.1@global/bin:/Users/jsp/.rvm/rubies/ruby-2.4.1/bin:~./Users/jsp/.pyenv/shims/python:/Users/jsp/.pyenv/shims:/Users/jsp/anaconda3/bin:/Users/jsp/.nvm/versions/node/v8.1.2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin:/Users/jsp/.rvm/bin
NVM_NODEJS_ORG_MIRROR=https://nodejs.org/dist
PWD=/Users/jsp
LANG=en_US.UTF-8
_system_arch=x86_64
XPC_FLAGS=0x0
_system_version=10.12
XPC_SERVICE_NAME=0
rvm_version=1.29.3 (latest)
PYENV_SHELL=bash
SHLVL=1
HOME=/Users/jsp
LOGNAME=jsp
GEM_PATH=/Users/jsp/.rvm/gems/ruby-2.4.1:/Users/jsp/.rvm/gems/ruby-2.4.1@global
NVM_BIN=/Users/jsp/.nvm/versions/node/v8.1.2/bin
NVM_IOJS_ORG_MIRROR=https://iojs.org/dist
DISPLAY=/private/tmp/com.apple.launchd.fwsxGaI5Nc/org.macosforge.xquartz:0
RUBY_VERSION=ruby-2.4.1
_system_name=OSX
_=/usr/bin/env
```

**Comment by jspenc72** [comment]
Curious as it is that if I execute ```pod``` as sudo I get the expected output. See below

```bash
/Users/jsp/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/claide-1.0.2/lib/claide/command.rb:439:in `help!': [!] You cannot run CocoaPods as root. (CLAide::Help)

Usage:

    $ pod COMMAND

      CocoaPods, the Cocoa library package manager.

Commands:

    + cache      Manipulate the CocoaPods cache
    + env        Display pod environment
    + init       Generate a Podfile for the current directory
    + install    Install project dependencies according to versions from a
                 Podfile.lock
    + ipc        Inter-process communication
    + lib        Develop pods
    + list       List pods
    + outdated   Show outdated project dependencies
    + repo       Manage spec-repositories
    + setup      Setup the CocoaPods environment
    + spec       Manage pod specs
    + update     Update outdated project dependencies and create new Podfile.lock

Options:

    --silent     Show nothing
    --version    Show the version of the tool
    --verbose    Show more debugging information
    --no-ansi    Show output without ANSI codes
    --help       Show help banner of specified command
	from /Users/jsp/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.4.0.beta.1/lib/cocoapods/command.rb:47:in `run'
	from /Users/jsp/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.4.0.beta.1/bin/pod:55:in `<top (required)>'
	from /Users/jsp/.rvm/gems/ruby-2.4.1/bin/pod:23:in `load'
	from /Users/jsp/.rvm/gems/ruby-2.4.1/bin/pod:23:in `<main>'
	from /Users/jsp/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/jsp/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by jspenc72** [comment]
while troubleshooting I have found that the problem persists on both cocoapods 1.3.1 as well as cocoa pods-1.4.0.beta.1

**Comment by jspenc72** [comment]
Problem persists with a raw ruby install as well as latest.

**Comment by jspenc72** [comment]
Only known update to system since problem occurred is updating XCode

**Comment by jspenc72** [comment]
And installing all related ios 11 build tools, simulators.

**Comment by paulb777** [comment]
Similar to #5788. Something is likely wrong with your PATH.  The substring `bin:~./Users` looks suspicious.

**Comment by jspenc72** [comment]
What is cocoa pods expecting to be in the path? What should be included. 

I already saw  #5788 and checked my path accordingly. I think it is a different issue.

```bin:~./Users``` is related to my python installation which is managed by pyenv. And is working without issue. Unless cocoapods is using python under the hood it shouldn't effect anything.

**Comment by jspenc72** [comment]
Just to be sure I have updated my $PATH so that entry is excluded and the issue remains.

**Comment by jspenc72** [comment]
Here is the updated ```env``` output without the "suspicious entry"
```bash
MANPATH=/Users/jsp/.nvm/versions/node/v8.1.2/share/man:/usr/local/share/man:/usr/share/man:/opt/X11/share/man:/Library/TeX/texbin/man:/Applications/Xcode.app/Contents/Developer/usr/share/man:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man
rvm_bin_path=/Users/jsp/.rvm/bin
TERM_PROGRAM=Apple_Terminal
GEM_HOME=/Users/jsp/.rvm/gems/ruby-2.4.1
NVM_CD_FLAGS=
SHELL=/bin/bash
TERM=xterm-256color
IRBRC=/Users/jsp/.rvm/rubies/ruby-2.4.1/.irbrc
TMPDIR=/var/folders/15/6_l9f4vj6t9010qr18930q0w0000gn/T/
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.6rR3BpVA2P/Render
TERM_PROGRAM_VERSION=388.1.1
MY_RUBY_HOME=/Users/jsp/.rvm/rubies/ruby-2.4.1
TERM_SESSION_ID=D1751EE3-2A0A-474C-98D4-EADE722192E1
rvm_stored_umask=0022
NVM_DIR=/Users/jsp/.nvm
USER=jsp
_system_type=Darwin
rvm_path=/Users/jsp/.rvm
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.UkzvLBah48/Listeners
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
rvm_prefix=/Users/jsp
PATH=~./Users/jsp/.pyenv/shims/python:/Users/jsp/.pyenv/shims:/Users/jsp/anaconda3/bin:/Users/jsp/.rvm/gems/ruby-2.4.1/bin:/Users/jsp/.rvm/gems/ruby-2.4.1@global/bin:/Users/jsp/.rvm/rubies/ruby-2.4.1/bin:/Users/jsp/.nvm/versions/node/v8.1.2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin:/Users/jsp/.rvm/bin
rvm_loaded_flag=1
NVM_NODEJS_ORG_MIRROR=https://nodejs.org/dist
PWD=/Users/jsp
LANG=en_US.UTF-8
_system_arch=x86_64
XPC_FLAGS=0x0
_system_version=10.12
XPC_SERVICE_NAME=0
rvm_version=1.29.3 (latest)
PYENV_SHELL=bash
SHLVL=1
HOME=/Users/jsp
LOGNAME=jsp
GEM_PATH=/Users/jsp/.rvm/gems/ruby-2.4.1:/Users/jsp/.rvm/gems/ruby-2.4.1@global
NVM_BIN=/Users/jsp/.nvm/versions/node/v8.1.2/bin
NVM_IOJS_ORG_MIRROR=https://iojs.org/dist
DISPLAY=/private/tmp/com.apple.launchd.fwsxGaI5Nc/org.macosforge.xquartz:0
RUBY_VERSION=ruby-2.4.1
rvm_user_install_flag=1
_system_name=OSX
_=/usr/bin/env

```

**Comment by jspenc72** [comment]
And the problem remains.
```bash
/Users/jsp/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.4.0.beta.1/lib/cocoapods/executable.rb:93:in `expand_path': user . doesn't exist (ArgumentError)
	from /Users/jsp/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.4.0.beta.1/lib/cocoapods/executable.rb:93:in `block in which'
	from /Users/jsp/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.4.0.beta.1/lib/cocoapods/executable.rb:92:in `each'
	from /Users/jsp/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.4.0.beta.1/lib/cocoapods/executable.rb:92:in `which'
	from /Users/jsp/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.4.0.beta.1/lib/cocoapods/executable.rb:110:in `which!'
	from /Users/jsp/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.4.0.beta.1/lib/cocoapods/executable.rb:133:in `capture_command'
	from /Users/jsp/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.4.0.beta.1/lib/cocoapods/command.rb:116:in `git_version'
	from /Users/jsp/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.4.0.beta.1/lib/cocoapods/command.rb:128:in `verify_minimum_git_version!'
	from /Users/jsp/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.4.0.beta.1/lib/cocoapods/command.rb:49:in `run'
	from /Users/jsp/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.4.0.beta.1/bin/pod:55:in `<top (required)>'
	from /Users/jsp/.rvm/gems/ruby-2.4.1/bin/pod:23:in `load'
	from /Users/jsp/.rvm/gems/ruby-2.4.1/bin/pod:23:in `<main>'
	from /Users/jsp/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/jsp/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by jspenc72** [comment]
I have tried a complete reinstallation without success. Can you please provide a list of directories that should be included in $PATH in order for cocoa pods to run?

**Comment by jspenc72** [comment]
I found a resolution after researching similar issues related to rvm to manage multiple ruby installations. 

The following command resolved my issue.
```bash
rvm reset 
```

 Cocoapods now runs without issue.

```bash
Jesses-MacBook-Pro:~ jsp$ rvm ls

rvm rubies

 * ruby-2.4.1 [ x86_64 ]

# => - current
# =* - current && default
#  * - default

Jesses-MacBook-Pro:~ jsp$ pod
Usage:

    $ pod COMMAND

      CocoaPods, the Cocoa library package manager.

Commands:

    + cache         Manipulate the CocoaPods cache
    + clean         Remove Podfile.lock, Pods/ and *.xcworkspace
    + deintegrate   Deintegrate CocoaPods from your project
    + env           Display pod environment
    + init          Generate a Podfile for the current directory
    + install       Install project dependencies according to versions from a
                    Podfile.lock
    + ipc           Inter-process communication
    + lib           Develop pods
    + list          List pods
    + outdated      Show outdated project dependencies
    + plugins       Show available CocoaPods plugins
    + repo          Manage spec-repositories
    + search        Search for pods
    + setup         Setup the CocoaPods environment
    + spec          Manage pod specs
    + trunk         Interact with the CocoaPods API (e.g. publishing new specs)
    + try           Try a Pod!
    + update        Update outdated project dependencies and create new Podfile.lock

Options:

    --silent        Show nothing
    --version       Show the version of the tool
    --verbose       Show more debugging information
    --no-ansi       Show output without ANSI codes
    --help          Show help banner of specified command
Jesses-MacBook-Pro:~ jsp$ 

```
