### ISSUE TITLE
 `pod install` crash when called

### ISSUE THREAD

**Issue by icanswiftabit** [CocoaPods/CocoaPods#7152]
### Command

```
/Users/blazej/Projects/ProjectA-iOS/.gems/ruby/2.4.0/bin/pod update
```

### Report

* What did you do?
`bundel exec pod install`

* What did you expect to happen?
Have installed pods

* What happened instead?
Crash

### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
    RubyGems : 2.6.12
        Host : Mac OS X 10.13 (17A405)
       Xcode : 9.0.1 (9A1004)
         Git : git version 2.13.5 (Apple Git-94)
Ruby lib dir : /Users/blazej/.rvm/rubies/ruby-2.4.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 86bd032436ccee737ce6afff51961e63870c40bd
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-keys        : 2.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '9.0'

inhibit_all_warnings!

abstract_target 'All' do
	use_frameworks!

# Layer.com dependencies
	pod 'LayerKit', '~> 0.26.8'
	pod 'Atlas', '~> 1.1.2'
	pod 'LayerKitDiagnostics', '~> 1.0'

# UI dependencies	
	pod 'JDStatusBarNotification', '~> 1.5.5'
	pod 'FDTake', '~> 1.0.0'

# Architectural dependencies
pod 'AsyncSwift', '~> 2.0.1'	

# External services dependencies	
	pod 'FBSDKCoreKit', '~> 4.24.0'
	pod 'FBSDKLoginKit', '~> 4.24.0'
	pod 'NewRelicAgent', '~> 5.14.1'
	pod 'BugfenderSDK', '~> 1.4.5'
	pod 'Fabric', '~> 1.6.12'
	pod 'Crashlytics', '~> 3.8.5'
	pod 'GoogleAnalytics', '~> 3.17'
	pod 'GooglePlaces', '~> 2.3.0'
	pod 'Firebase/RemoteConfig', '~> 4.0.4'
	pod 'libPhoneNumber-iOS', '~> 0.9.10'
    pod 'Moya', '~> 8.0.5'

	target 'ProjectA' do
	end

	target 'ProjectB' do
	end

	target 'ProjectC' do
	end

	target 'ProjectD' do
	end

	target 'ProjectC' do
	end

    target 'Test Tests' do

        pod 'Quick', '~> 1.1.0'
        pod 'Nimble', '~> 7.0.1'
        pod 'Mockingjay', `~> 2.0.0`
    end
end


plugin 'cocoapods-keys', {
  :project => 'Test',
  :target => 'All',
  :keys => [ // keys
  ]
}
```

### Error

```
ArgumentError - Illformed requirement `""`
/Users/blazej/Projects/ProjectA-iOS/.gems/ruby/2.4.0/gems/cocoapods-core-1.3.1/lib/cocoapods-core/requirement.rb:63:in `parse'
/Users/blazej/Projects/ProjectA-iOS/.gems/ruby/2.4.0/gems/cocoapods-core-1.3.1/lib/cocoapods-core/requirement.rb:88:in `block in initialize'
/Users/blazej/Projects/ProjectA-iOS/.gems/ruby/2.4.0/gems/cocoapods-core-1.3.1/lib/cocoapods-core/requirement.rb:88:in `map!'
/Users/blazej/Projects/ProjectA-iOS/.gems/ruby/2.4.0/gems/cocoapods-core-1.3.1/lib/cocoapods-core/requirement.rb:88:in `initialize'
/Users/blazej/Projects/ProjectA-iOS/.gems/ruby/2.4.0/gems/cocoapods-core-1.3.1/lib/cocoapods-core/requirement.rb:34:in `new'
/Users/blazej/Projects/ProjectA-iOS/.gems/ruby/2.4.0/gems/cocoapods-core-1.3.1/lib/cocoapods-core/requirement.rb:34:in `create'
/Users/blazej/Projects/ProjectA-iOS/.gems/ruby/2.4.0/gems/cocoapods-core-1.3.1/lib/cocoapods-core/dependency.rb:116:in `initialize'
/Users/blazej/Projects/ProjectA-iOS/.gems/ruby/2.4.0/gems/cocoapods-core-1.3.1/lib/cocoapods-core/podfile/target_definition.rb:753:in `new'
/Users/blazej/Projects/ProjectA-iOS/.gems/ruby/2.4.0/gems/cocoapods-core-1.3.1/lib/cocoapods-core/podfile/target_definition.rb:753:in `block in pod_dependencies'
/Users/blazej/Projects/ProjectA-iOS/.gems/ruby/2.4.0/gems/cocoapods-core-1.3.1/lib/cocoapods-core/podfile/target_definition.rb:749:in `map'
/Users/blazej/Projects/ProjectA-iOS/.gems/ruby/2.4.0/gems/cocoapods-core-1.3.1/lib/cocoapods-core/podfile/target_definition.rb:749:in `pod_dependencies'
/Users/blazej/Projects/ProjectA-iOS/.gems/ruby/2.4.0/gems/cocoapods-core-1.3.1/lib/cocoapods-core/podfile/target_definition.rb:96:in `non_inherited_dependencies'
/Users/blazej/Projects/ProjectA-iOS/.gems/ruby/2.4.0/gems/cocoapods-core-1.3.1/lib/cocoapods-core/podfile/target_definition.rb:74:in `dependencies'
/Users/blazej/Projects/ProjectA-iOS/.gems/ruby/2.4.0/gems/cocoapods-core-1.3.1/lib/cocoapods-core/podfile.rb:90:in `map'
/Users/blazej/Projects/ProjectA-iOS/.gems/ruby/2.4.0/gems/cocoapods-core-1.3.1/lib/cocoapods-core/podfile.rb:90:in `dependencies'
/Users/blazej/Projects/ProjectA-iOS/.gems/ruby/2.4.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/analyzer.rb:850:in `sources'
/Users/blazej/Projects/ProjectA-iOS/.gems/ruby/2.4.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:147:in `resolve_dependencies'
/Users/blazej/Projects/ProjectA-iOS/.gems/ruby/2.4.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:116:in `install!'
/Users/blazej/Projects/ProjectA-iOS/.gems/ruby/2.4.0/gems/cocoapods-1.3.1/lib/cocoapods/command/update.rb:81:in `run'
/Users/blazej/Projects/ProjectA-iOS/.gems/ruby/2.4.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/blazej/Projects/ProjectA-iOS/.gems/ruby/2.4.0/gems/cocoapods-1.3.1/lib/cocoapods/command.rb:52:in `run'
/Users/blazej/Projects/ProjectA-iOS/.gems/ruby/2.4.0/gems/cocoapods-1.3.1/bin/pod:55:in `<top (required)>'
/Users/blazej/Projects/ProjectA-iOS/.gems/ruby/2.4.0/bin/pod:23:in `load'
/Users/blazej/Projects/ProjectA-iOS/.gems/ruby/2.4.0/bin/pod:23:in `<top (required)>'
/Users/blazej/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `load'
/Users/blazej/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `kernel_load'
/Users/blazej/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:27:in `run'
/Users/blazej/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/cli.rb:362:in `exec'
/Users/blazej/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/blazej/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/blazej/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/Users/blazej/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/cli.rb:22:in `dispatch'
/Users/blazej/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/Users/blazej/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/cli.rb:13:in `start'
/Users/blazej/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/exe/bundle:30:in `block in <top (required)>'
/Users/blazej/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/Users/blazej/.rvm/gems/ruby-2.4.1/gems/bundler-1.15.4/exe/bundle:22:in `<top (required)>'
/Users/blazej/.rvm/gems/ruby-2.4.1/bin/bundle:23:in `load'
/Users/blazej/.rvm/gems/ruby-2.4.1/bin/bundle:23:in `<main>'
/Users/blazej/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
/Users/blazej/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by icanswiftabit** [comment]
The issue was used ` insted of ' in 54 line of the Podfile. 🤦‍♂️
