### ISSUE TITLE
Crash on 1.4.0.beta2 during `pod install` for pods with test_spec

### ISSUE THREAD

**Issue by adc-amatosov** [CocoaPods/CocoaPods#7174]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
Crash on 1.4.0.beta2 during `pod install` for pods with test_spec

## What did you do?

Run `pod install`

## What did you expect to happen?

Install all pod dependencies correctly.

### Error

```
NoMethodError - undefined method `add_dependency' for nil:NilClass
~/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/cocoapods-1.4.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:307:in `block in add_dependent_targets_to_native_target'
~/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/cocoapods-1.4.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:305:in `each'
~/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/cocoapods-1.4.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:305:in `add_dependent_targets_to_native_target'
~/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/cocoapods-1.4.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:295:in `block in add_pod_target_test_dependencies'
~/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/cocoapods-1.4.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:291:in `each'
~/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/cocoapods-1.4.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:291:in `add_pod_target_test_dependencies'
~/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/cocoapods-1.4.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:225:in `block (2 levels) in set_target_dependencies'
~/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/cocoapods-1.4.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:219:in `each'
~/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/cocoapods-1.4.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:219:in `block in set_target_dependencies'
~/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/cocoapods-1.4.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:214:in `each'
~/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/cocoapods-1.4.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:214:in `set_target_dependencies'
~/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/cocoapods-1.4.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:67:in `generate!'
~/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/cocoapods-1.4.0.beta.2/lib/cocoapods/installer.rb:184:in `block in generate_pods_project'
~/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/cocoapods-1.4.0.beta.2/lib/cocoapods/user_interface.rb:64:in `section'
~/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/cocoapods-1.4.0.beta.2/lib/cocoapods/installer.rb:183:in `generate_pods_project'
~/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/cocoapods-1.4.0.beta.2/lib/cocoapods/installer.rb:119:in `install!'
~/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/cocoapods-1.4.0.beta.2/lib/cocoapods/command/install.rb:41:in `run'
~/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
~/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/cocoapods-1.4.0.beta.2/lib/cocoapods/command.rb:52:in `run'
~/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/cocoapods-1.4.0.beta.2/bin/pod:55:in `<top (required)>'
~/.rbenv/versions/2.2.5/bin/pod:23:in `load'
~/.rbenv/versions/2.2.5/bin/pod:23:in `<main>'
```
### Stack

```
   CocoaPods : 1.4.0.beta.2
        Ruby : ruby 2.2.5p319 (2016-04-26 revision 54774) [x86_64-darwin15]
    RubyGems : 2.6.13
        Host : Mac OS X 10.13 (17A405)
       Xcode : 9.0 (9A235)
         Git : git version 2.10.2
Ruby lib dir : /Users/amatosov.ctr/.rbenv/versions/2.2.5/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ bd17f6f3e5131bda4ce72034abc1966d570899e9
```

### Installation Source

```
Executable Path: /Users/amatosov.ctr/.rbenv/versions/2.2.5/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-packager    : 1.5.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

It happens on the closed source repos. I am still trying to figure out what causes the issue.

**Comment by dnkoutso** [comment]
Please provide sample app to make it easier to debug.

**Comment by adc-amatosov** [comment]
Sure. 
The first case I had is the osx only pod with tests. 
Both pure swift.
Also crashes with another pod. Still trying to figure out what is wrong with this one

**Comment by adc-amatosov** [comment]
Here you go https://github.com/adc-amatosov/TestSpecs/tree/watchos_tests_crash

**Comment by adc-amatosov** [comment]
```
target 'SimpleWatch Extension' do
  platform :watchos, "4"
  pod 'TestSpecs', :path => '../', :testspecs => ["Tests"] # THIS testspecs crashes pod install
end
```

**Comment by dnkoutso** [comment]
probably related to watchos target.

**Comment by anton-matosov** [comment]
Exactly. it crashes only for watchos targets. 
I believe there were changes to no generate test targets for watchos in 1.4.0 beta. This might have caused this crashing.
IMO the `pod install` for setup like this should fail, but with error instead of exception.
Something like `watchOS unit testing is not available in Xcode. Unit test target can't be generated on watchOS platform for {pod name}. Please remove : testspecs`

**Comment by dnkoutso** [comment]
Will remove from 1.4.0 but will mark it as an easy improvement for us.

**Comment by adc-amatosov** [comment]
```
diff --git a/lib/cocoapods/installer/xcode/pods_project_generator.rb b/lib/cocoapods/installer/xcode/pods_project_generator.rb
index ebd3af9..1a86009 100644
--- a/lib/cocoapods/installer/xcode/pods_project_generator.rb
+++ b/lib/cocoapods/installer/xcode/pods_project_generator.rb
@@ -304,6 +304,7 @@ module Pod
         def add_dependent_targets_to_native_target(dependent_targets, native_target, is_app_extension, requires_frameworks, frameworks_group)
           dependent_targets.each do |pod_dependency_target|
             next unless pod_dependency_target.should_build?
+            next if native_target == nil
             native_target.add_dependency(pod_dependency_target.native_target)
             configure_app_extension_api_only_for_target(pod_dependency_target) if is_app_extension
 

```
solves the issue for me

**Comment by dnkoutso** [comment]
It might be a bit more complicated than that. There is a question to be asked why are we trying to add these dependencies if there hasn't been a target generated to begin with.

**Comment by adc-amatosov** [comment]
Agreed. 
Also I still got watchOS-Unit-Tests targets in the Pods project...

**Comment by maximkhatskevich** [comment]
I use 'cocoapods-1.6.0.beta.2' and the issue with "no such module 'XCTest'" in [watchOS] context still persists.

**Comment by SuperBarracuda** [comment]
I added an iOS deployment target to test spec get around this issue. I think otherwise it inherits the base projects. 

` s.ios.deployment_target = "9.0"
 s.watchos.deployment_target = '4.0'
 s.tvos.deployment_target = '10.0'
 s.dependency 'MKDKit/MKDOrbis'
 s.dependency 'FMDB'
 s.xcconfig = { 'HEADER_SEARCH_PATHS' => '/usr/include/libxml2' }
 s.libraries = 'xml2', 'z', 'sqlite3'
 s.frameworks = 'CoreGraphics'
 
 s.test_spec 'Tests' do |test_spec|
   test_spec.ios.deployment_target = "9.0"
   test_spec.source_files = 'tests/XCTest/**/*.{h,m,swift}'
   test_spec.dependency 'MKDTestHelpers'
 end  `
