### ISSUE TITLE
Bug with subspec/spec mix used with configurations or incorrect usage of Pod syntax ?

### ISSUE THREAD

**Issue by LiohAu** [CocoaPods/CocoaPods#7231]
Hi guys, I'm having an issue and I hope that you'll be able to help me to solve it.

I tried to use the `Podfile` below, and I get the following error : 

```
TypeError - no implicit conversion of Array into String
/.../.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-core-1.3.1/lib/cocoapods-core/podfile/target_definition.rb:754:in `+'
/.../.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-core-1.3.1/lib/cocoapods-core/podfile/target_definition.rb:754:in `block in configuration_pod_whitelist'
/.../.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-core-1.3.1/lib/cocoapods-core/podfile/target_definition.rb:747:in `merge'
/.../.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-core-1.3.1/lib/cocoapods-core/podfile/target_definition.rb:747:in `configuration_pod_whitelist'
/.../.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-core-1.3.1/lib/cocoapods-core/podfile/target_definition.rb:447:in `all_whitelisted_configurations'
/.../.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-core-1.3.1/lib/cocoapods-core/podfile/target_definition.rb:446:in `all_whitelisted_configurations'
/.../.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:261:in `each'
/.../.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:261:in `flat_map'
/.../.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:261:in `validate_build_configurations'
/.../.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:155:in `block in resolve_dependencies'
/.../.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.3.1/lib/cocoapods/user_interface.rb:64:in `section'
/.../.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:153:in `resolve_dependencies'
/.../.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:116:in `install!'
/.../.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.3.1/lib/cocoapods/command/install.rb:41:in `run'
/.../.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/.../.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.3.1/lib/cocoapods/command.rb:52:in `run'
/.../.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-1.3.1/bin/pod:55:in `<top (required)>'
/.../.rbenv/versions/2.2.2/bin/pod:23:in `load'
/.../.rbenv/versions/2.2.2/bin/pod:23:in `<main>'
```

```
source 'https://github.com/CocoaPods/Specs.git'
source 'http://...privaterepo.../Specs'

workspace 'Wks'

platform :ios, '10.0'

def app_common_pods
    pod 'Fabric'
    pod 'Crashlytics'
end

abstract_target 'DependentProjectFramework' do
  project 'Wks/DependentProjectFramework/DependentProjectFramework.xcodeproj'
  pod 'PrivateFrameworkWithSubSpecs/Core', '~> 2.0.1', :configuration => 'Release'
  pod 'PrivateFrameworkWithSubSpecs-Debug/Core', '~> 2.0.1', :configuration => 'Debug'

# Putting those 2 lines in this abstract_target block works
#  pod 'PrivateFramework', :configuration => 'Release'
#  pod 'PrivateFramework-Debug', :configuration => 'Debug'
  
  abstract_target 'AppFramework' do

    # With the following 2 lines in this abstract_target, it does NOT works
    pod 'PrivateFramework', :configuration => 'Release'
    pod 'PrivateFramework-Debug', :configuration => 'Debug'
  
      target 'MyApp' do
        project 'MyApp.xcodeproj'
        app_common_pods
        pod 'PrivateFramework', :configuration => 'Release'
        pod 'PrivateFramework-Debug', :configuration => 'Debug'
      end

  end
end
```

As suggested by the error, it seems that the line of code `parent.send(:configuration_pod_whitelist).merge(whitelist_hash) { |l, r| (l + r).uniq }` located in the `configuration_pod_whitelist` method in `target_definition.rb` file try to use the `+` operator with `l` being `Release` (string) and `r` being `SMDF/Core` (Array).

So is this a bug or am I using an invalid Podfile syntax ? 

If so how can I restrict the debug pod to the debug configuration and release pod for the others ?

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

**Comment by LiohAu** [comment]
Well if the Podfile I wrote is valid, this is a real bug.
