### ISSUE TITLE
pod trunk push error

### ISSUE THREAD

**Issue by ProMonkeyZ** [CocoaPods/CocoaPods#7243]
When i use 'pod spec lint --verbose --allow-warnings', LRNetworking.podspec passed validation.

But , when i use 'pod trunk push LRNetworking.podspec --verbose --allow-warnings'', the error log is : 
### Error

```
NoMethodError - undefined method `skip_tests=' for #<Pod::Validator:0x007fb7d72bbb00>
/Users/zln/.rvm/gems/ruby-2.2.2@global/gems/cocoapods-trunk-1.3.0/lib/pod/command/trunk/push.rb:124:in `validate_podspec'
/Users/zln/.rvm/gems/ruby-2.2.2@global/gems/cocoapods-trunk-1.3.0/lib/pod/command/trunk/push.rb:68:in `run'
/Users/zln/.rvm/gems/ruby-2.2.2@global/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/zln/.rvm/gems/ruby-2.2.2@global/gems/cocoapods-1.2.1/lib/cocoapods/command.rb:52:in `run'
/Users/zln/.rvm/gems/ruby-2.2.2@global/gems/cocoapods-1.2.1/bin/pod:55:in `<top (required)>'
/Users/zln/.rvm/rubies/ruby-2.2.2/bin/pod:23:in `load'
/Users/zln/.rvm/rubies/ruby-2.2.2/bin/pod:23:in `<main>'
/Users/zln/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
/Users/zln/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by ProMonkeyZ** [comment]
My podsepe file is : 
### podsped
```
#
# Be sure to run `pod lib lint LRNetworking.podspec' to ensure this is a
# valid spec before submitting.
#
# Any lines starting with a # are optional, but their use is encouraged
# To learn more about a Podspec see http://guides.cocoapods.org/syntax/podspec.html
#

Pod::Spec.new do |s|
  s.name             = 'LRNetworking'
  s.version          = '0.1.1'
  s.summary          = 'Based on RAC netWorking lib.'

# This description is used to generate tags and improve search results.
#   * Think: What does it do? Why did you write it? What is the focus?
#   * Try to keep it short, snappy and to the point.
#   * Write the description between the DESC delimiters below.
#   * Finally, don't worry about the indent, CocoaPods strips it!

  s.description      = <<-DESC
    Based on RAC netWorking lib, you can use in your project.
                       DESC

  s.homepage         = 'https://github.com/ProMonkeyZ/LRNetworking'
  # s.screenshots     = 'www.example.com/screenshots_1', 'www.example.com/screenshots_2'
  s.license          = { :type => 'MIT', :file => 'LICENSE' }
  s.author           = { '18333675676@163.com' => 'zhanglining@syswin.com' }
  s.source           = { :git => 'https://github.com/ProMonkeyZ/LRNetworking.git', :tag => s.version.to_s }
  # s.social_media_url = 'https://twitter.com/<TWITTER_USERNAME>'

  s.ios.deployment_target = '8.0'

  s.source_files = 'LRNetworking/Classes/**/*'
  
  # s.resource_bundles = {
  #   'LRNetworking' => ['LRNetworking/Assets/*.png']
  # }

  # s.public_header_files = 'Pod/Classes/**/*.h'
  # s.frameworks = 'UIKit', 'MapKit'
    s.dependency 'ReactiveObjC', '~> 2.1.2'
end
```

**Comment by dnkoutso** [comment]
Upgrade to CocoaPods 1.3.1 or 1.4.0.beta.2.

**Comment by ProMonkeyZ** [comment]
Thank you very much .
