### ISSUE TITLE
pod trunk me Error

### ISSUE THREAD

**Issue by mgfjxxiexiaolong** [CocoaPods/CocoaPods#7252]
```
xiexiaolongMacBook-Pro:test xiexiaolong1$ pod trunk me --verbose
opening connection to trunk.cocoapods.org:443...
[!] There was an error fetching your info from trunk: execution expired

/Library/Ruby/Gems/2.3.0/gems/cocoapods-trunk-1.3.0/lib/pod/command/trunk/me.rb:70:in `rescue in run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-trunk-1.3.0/lib/pod/command/trunk/me.rb:24:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
xiexiaolongMacBook-Pro:test xiexiaolong1$ pod --version
1.3.1
xiexiaolongMacBook-Pro:test xiexiaolong1$ 


```

**Comment by orta** [comment]
Does something like `curl https://trunk.cocoapods.org/api/v1/pods/ORStackView` fail for you?

**Comment by dnkoutso** [comment]
Also file a bug in https://github.com/CocoaPods/cocoapods-trunk instead.

This is not a CocoaPods library issue per se so I am going to close.

**Comment by mgfjxxiexiaolong** [comment]
@orta

**Comment by mgfjxxiexiaolong** [comment]
@orta @dnkoutso  I don't know how to solve this problem.
```
xiexiaolongMacBook-Pro:~ xiexiaolong1$ curl https://trunk.cocoapods.org/api/v1/pods/ORStackView
{"versions":[{"name":"0.5.0","created_at":"2014-05-19 21:57:16 UTC"},{"name":"0.6.0","created_at":"2014-05-19 21:57:31 UTC"},{"name":"0.6.1","created_at":"2014-05-19 21:57:51 UTC"},{"name":"1.0.0","created_at":"2014-05-19 22:03:01 UTC"},{"name":"1.1.0","created_at":"2014-05-19 22:07:04 UTC"},{"name":"1.2.0","created_at":"2014-05-23 12:27:06 UTC"},{"name":"2.0.0","created_at":"2014-10-11 17:39:40 UTC"},{"name":"2.0.1","created_at":"2016-04-12 13:54:23 UTC"},{"name":"2.0.2","created_at":"2016-04-12 14:27:53 UTC"},{"name":"2.0.3","created_at":"2016-04-12 14:29:42 UTC"},{"name":"3.0.0","created_at":"2015-04-22 17:44:21 UTC"},{"name":"3.0.1","created_at":"2015-05-14 08:44:43 UTC"}],"owners":[{"created_at":"2014-05-19 21:36:13 UTC","email":"orta.therox@gmail.com","name":"Orta Therox"},{"created_at":"2014-05-19 21:48:58 UTC","email":"ash@ashfurrow.com","name":"Ash Furrow"}]}
```

**Comment by mgfjxxiexiaolong** [comment]
@orta It worked. Thank you!

**Comment by Arvindcs** [comment]
while 'pod trunk register' I'm getting below error
[!] There was an error registering with trunk: execution expired
