### ISSUE TITLE
undefined method `name' for nil:NilClass

### ISSUE THREAD

**Issue by panyult** [CocoaPods/CocoaPods#7300]
# Report
I have went through #4887  #7174   #5449 #5236,and tried to solve my problem,but it didn't work.Please save my life.Thanks a lot! @segiddins 

[LTRunLoop git respository](https://github.com/panyult/LTRunLoop.git)

## What did you do?

 I am creating my framework,after editing` .podspec `file,I run ` pod lib lint LTRunLoop.podspec`.  

## What did you expect to happen?

>  LTRunLoop passed validation.
And life becomes better.

 
### errors accurred as follow:
   -> LTRunLoop (0.1.0)

    - ERROR | [iOS] frameworks: A framework should only be specified by its name

    - ERROR | [iOS] unknown: Encountered an unknown error (The `LTRunLoop` pod failed to validate due to 1 error:
    - ERROR | [iOS] frameworks: A framework should only be specified by its name  )during validation.

### Detail Error

```
NoMethodError - undefined method `name' for nil:NilClass
/Users/litao/.rvm/gems/ruby-2.4.2@global/gems/cocoapods-1.4.0.rc.1/lib/cocoapods/validator.rb:253:in `validation_dir'
/Users/litao/.rvm/gems/ruby-2.4.2@global/gems/cocoapods-1.4.0.rc.1/lib/cocoapods/command/lib/lint.rb:71:in `block in run'
/Users/litao/.rvm/gems/ruby-2.4.2@global/gems/cocoapods-1.4.0.rc.1/lib/cocoapods/command/lib/lint.rb:54:in `each'
/Users/litao/.rvm/gems/ruby-2.4.2@global/gems/cocoapods-1.4.0.rc.1/lib/cocoapods/command/lib/lint.rb:54:in `run'
/Users/litao/.rvm/gems/ruby-2.4.2@global/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/litao/.rvm/gems/ruby-2.4.2@global/gems/cocoapods-1.4.0.rc.1/lib/cocoapods/command.rb:52:in `run'
/Users/litao/.rvm/gems/ruby-2.4.2@global/gems/cocoapods-1.4.0.rc.1/bin/pod:55:in `<top (required)>'
/Users/litao/.rvm/rubies/ruby-2.4.2/bin/pod:23:in `load'
/Users/litao/.rvm/rubies/ruby-2.4.2/bin/pod:23:in `<main>'
/Users/litao/.rvm/gems/ruby-2.4.2@global/bin/ruby_executable_hooks:15:in `eval'
/Users/litao/.rvm/gems/ruby-2.4.2@global/bin/ruby_executable_hooks:15:in `<main>'
```

### Stack

```
   CocoaPods : 1.4.0.rc.1
        Ruby : ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin16]
    RubyGems : 2.6.14
        Host : Mac OS X 10.12.6 (16G29)
       Xcode : 9.2 (9C40b)
         Git : git version 2.14.3 (Apple Git-98)
Ruby lib dir : /Users/litao/.rvm/rubies/ruby-2.4.2/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 892695177031ea889760fe48eb62fe75b7d75765
```

### Installation Source

```
Executable Path: /Users/litao/.rvm/rubies/ruby-2.4.2/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

[LTRunLoop git respository](https://github.com/panyult/LTRunLoop.git)

## podspec file 
```
Pod::Spec.new do |s|
s.name             = 'LTRunLoop'
s.version          = '0.1.0'
s.summary          = 'LTRunLoop help you to define self-define input source when you want use the run loop of a secondary thread to handle something for you.'
s.homepage         = 'https://github.com/panyult/LTRunLoop'
s.license          = { :type => 'MIT', :file => 'LICENSE' }
s.author           = { 'panyult' => 'litaoxiwang@163.com' }
s.source           = { :git => 'https://github.com/panyult/LTRunLoop.git', :tag => s.version }
s.platform         = :ios, '8.0'
s.requires_arc     = true
s.source_files     = 'Pod/LTRunLoop/**/*.{h,m}'
s.frameworks       = 'UIKit,Foundation,CoreFoundation'

end
```

## Podfile
```
platform :ios, '8.0'

use_frameworks!

target 'LTRunLoop_Example' do
  pod 'LTRunLoop', :path => '../'

  target 'LTRunLoop_Tests' do
    inherit! :search_paths

    
  end
end

```

**Comment by dnkoutso** [comment]
Change:
```ruby
s.frameworks       = 'UIKit,Foundation,CoreFoundation'
```
to:
```ruby
s.frameworks       = 'UIKit', 'Foundation', 'CoreFoundation'
```
Also your `s.source_files` is wrong and use:
```ruby
s.source_files     = 'LTRunLoop/**/*.{h,m}'
```
This is not a CocoaPods library issue. Closing.

**Comment by panyult** [comment]
@dnkoutso Thanks a lot ! You do save my life ! Merry Christmas!
