### ISSUE TITLE
pod install fail

### ISSUE THREAD

**Issue by sunjc53yy** [CocoaPods/CocoaPods#7320]
――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    RubyGems : 2.6.14
        Host : Mac OS X 10.13 (17A365)
       Xcode : 9.2 (9C40b)
         Git : git version 2.14.3 (Apple Git-98)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 5a5c1bb6b8a3d024503dd920ff3edf970a8fede4
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'RiceCircle' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RiceCircle
  pod 'AFNetworking', '~> 3.0'
  pod 'MJExtension', '~> 3.0.13'
  pod 'MJRefresh', '~> 3.1.12'
  pod 'Masonry', '~> 1.0.2'
  pod 'FMDB', '~> 2.6.2'
  pod 'Mantle', '~> 2.1.0'
  pod 'SDWebImage', '~> 3.8'
  pod 'MBProgressHUD', '~> 1.0.0'
  pod 'KVOController', '~> 1.2.0'
  target 'RiceCircleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RiceCircleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

### Error

```
Errno::EOPNOTSUPP - Operation not supported on socket @ rb_file_s_symlink - (../../../AFNetworking/AFNetworking/AFNetworking.h, /Volumes/VMware Shared Folders/VirtualMachinesShared/ios/Pods/Headers/Private/AFNetworking/AFNetworking.h)
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:358:in `symlink'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:358:in `block in ln_s'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:1585:in `fu_each_src_dest0'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:356:in `ln_s'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:379:in `ln_sf'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/sandbox/headers_store.rb:99:in `add_file'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/sandbox/headers_store.rb:75:in `block in add_files'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/sandbox/headers_store.rb:74:in `map'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/sandbox/headers_store.rb:74:in `add_files'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:132:in `block (4 levels) in link_headers'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:131:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:131:in `block (3 levels) in link_headers'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:119:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:119:in `block (2 levels) in link_headers'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:118:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:118:in `block in link_headers'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/user_interface.rb:142:in `message'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:117:in `link_headers'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:43:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:161:in `install_file_references'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:64:in `generate!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:183:in `block in generate_pods_project'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:182:in `generate_pods_project'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:119:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/command/install.rb:41:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'

**Comment by dnkoutso** [comment]
This one works for me.

```
Analyzing dependencies
Downloading dependencies
Installing AFNetworking (3.1.0)
Installing FMDB (2.6.2)
Installing KVOController (1.2.0)
Installing MBProgressHUD (1.0.0)
Installing MJExtension (3.0.13)
Installing MJRefresh (3.1.15.1)
Installing Mantle (2.1.0)
Installing Masonry (1.0.2)
Installing SDWebImage (3.8.2)
Generating Pods project
Integrating client project
Pod installation complete! There are 9 dependencies from the Podfile and 9 total pods installed.
```

I believe you might be having something that is a symlink in your folder configuration. Can you please upload a sample app that demonstrates the issue clearly?

Will keep this open with "awaiting input" unless it auto closes without any future feedback.
