### ISSUE TITLE
Nanaimo::Reader::ParseError - [!] Dictionary missing ';' after key-value pair for "shellScript", found "<"

### ISSUE THREAD

**Issue by steffansk1997** [CocoaPods/CocoaPods#7356]
### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?
I tried to buid a unity project for iOS from a unity installation on a mac. When I build on windows I get a parse error on the pbx file

* What did you expect to happen?
A successful build for xcode

* What happened instead?
A corrupted xcodeproj file was generated

### Stack

```
   CocoaPods : 1.4.0
        Ruby : ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin16]
    RubyGems : 2.7.4
        Host : Mac OS X 10.13.2 (17C88)
       Xcode : 9.2 (9C40b)
         Git : git version 2.14.3 (Apple Git-98)
Ruby lib dir : /usr/local/Cellar/ruby/2.5.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 934c920465c438d5214242ebb2791f606f65628a
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/CocoaPods/Specs'
platform :ios, '7.0'

target 'Unity-iPhone' do
pod 'Firebase/Analytics', '4.8.0'
pod 'Firebase/Core', '4.8.0'
pod 'Google-Mobile-Ads-SDK', '~> 7.0'
end
```

### Error

```
Nanaimo::Reader::ParseError - [!] Dictionary missing ';' after key-value pair for "shellScript", found "<"
    #  -------------------------------------------
    #  			);
    #  			name = InfoPlist.strings;
1489>  			sourceTree = "<group>";
       			              ^
    #  		};
    #  /* End PBXVariantGroup section */
    #  -------------------------------------------

/usr/local/lib/ruby/gems/2.5.0/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:284:in `raise_parser_error'
/usr/local/lib/ruby/gems/2.5.0/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:198:in `parse_dictionary'
/usr/local/lib/ruby/gems/2.5.0/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:131:in `parse_object'
/usr/local/lib/ruby/gems/2.5.0/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:192:in `parse_dictionary'
/usr/local/lib/ruby/gems/2.5.0/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:131:in `parse_object'
/usr/local/lib/ruby/gems/2.5.0/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:192:in `parse_dictionary'
/usr/local/lib/ruby/gems/2.5.0/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:131:in `parse_object'
/usr/local/lib/ruby/gems/2.5.0/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:106:in `parse!'
/usr/local/lib/ruby/gems/2.5.0/gems/xcodeproj-1.5.4/lib/xcodeproj/plist.rb:27:in `read_from_path'
/usr/local/lib/ruby/gems/2.5.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project.rb:200:in `initialize_from_file'
/usr/local/lib/ruby/gems/2.5.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project.rb:102:in `open'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/analyzer.rb:907:in `block (2 levels) in inspect_targets_to_integrate'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/analyzer.rb:906:in `each'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/analyzer.rb:906:in `block in inspect_targets_to_integrate'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/analyzer.rb:901:in `inspect_targets_to_integrate'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/analyzer.rb:75:in `analyze'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:243:in `analyze'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:154:in `block in resolve_dependencies'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:153:in `resolve_dependencies'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:116:in `install!'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/command/install.rb:41:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by dnkoutso** [comment]
Can you please upload a sample project?

**Comment by dnkoutso** [comment]
This seems an issue with the user project, not the generated project.

I was able to successfully `pod install`

```
The Gemfile's dependencies are satisfied
Analyzing dependencies
Downloading dependencies
Using Firebase (4.8.0)
Using FirebaseAnalytics (4.0.5)
Using FirebaseCore (4.0.13)
Using FirebaseInstanceID (2.0.8)
Using Google-Mobile-Ads-SDK (7.27.0)
Using GoogleToolboxForMac (2.1.3)
Using nanopb (0.3.8)
Generating Pods project
Integrating client project
Pod installation complete! There are 3 dependencies from the Podfile and 7 total pods installed.
```

If no sample app is provided this will be automatically closed.

**Comment by steffansk1997** [comment]
I fixed the issue, it had to do with a lost post processing script somewhere in the project that was meant for windows

**Comment by dnkoutso** [comment]
perfect!
