### ISSUE TITLE
new error on installing charts realm

### ISSUE THREAD

**Issue by GopiipoG** [CocoaPods/CocoaPods#7363]
```
 # Pods for chartSwift
	use_frameworks!
	pod ‘Charts’
	pod ‘ChartsRealm’
  target 'chartSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'chartSwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

### Error

```
Errno::EACCES - Permission denied - /var/folders/jz/pl1w85k15ns9md1kbgcgx_0w0000gp/T/d20180124-5401-jh4c1s/Realm/ObjectStore/Dockerfile
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1380:in `initialize'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1380:in `open'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1380:in `copy_file'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1348:in `copy'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:463:in `block in copy_entry'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1485:in `call'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1485:in `wrap_traverse'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1488:in `block in wrap_traverse'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1487:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1487:in `wrap_traverse'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1488:in `block in wrap_traverse'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1487:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1487:in `wrap_traverse'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1488:in `block in wrap_traverse'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1487:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1487:in `wrap_traverse'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:460:in `copy_entry'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:435:in `block in cp_r'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1558:in `block in fu_each_src_dest'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1574:in `fu_each_src_dest0'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1556:in `fu_each_src_dest'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:434:in `cp_r'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1.beta.1/lib/cocoapods/downloader/cache.rb:201:in `copy_and_clean'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1.beta.1/lib/cocoapods/downloader/cache.rb:159:in `block (2 levels) in uncached_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1.beta.1/lib/cocoapods/downloader/cache.rb:157:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1.beta.1/lib/cocoapods/downloader/cache.rb:157:in `block in uncached_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1.beta.1/lib/cocoapods/downloader/cache.rb:181:in `call'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1.beta.1/lib/cocoapods/downloader/cache.rb:181:in `in_tmpdir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1.beta.1/lib/cocoapods/downloader/cache.rb:153:in `uncached_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1.beta.1/lib/cocoapods/downloader/cache.rb:33:in `download_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1.beta.1/lib/cocoapods/downloader.rb:42:in `download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1.beta.1/lib/cocoapods/installer/pod_source_installer.rb:120:in `download_source'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1.beta.1/lib/cocoapods/installer/pod_source_installer.rb:60:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1.beta.1/lib/cocoapods/installer.rb:357:in `install_source_of_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1.beta.1/lib/cocoapods/installer.rb:322:in `block (2 levels) in install_pod_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1.beta.1/lib/cocoapods/user_interface.rb:85:in `titled_section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1.beta.1/lib/cocoapods/installer.rb:321:in `block in install_pod_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1.beta.1/lib/cocoapods/installer.rb:313:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1.beta.1/lib/cocoapods/installer.rb:313:in `install_pod_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1.beta.1/lib/cocoapods/installer.rb:159:in `block in download_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1.beta.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1.beta.1/lib/cocoapods/installer.rb:157:in `download_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1.beta.1/lib/cocoapods/installer.rb:111:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1.beta.1/lib/cocoapods/command/install.rb:37:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1.beta.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1.beta.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=Permission+denied+-+%2Fvar%2Ffolders%2Fjz%2Fpl1w85k15ns9md1kbgcgx_0w0000gp%2FT%2Fd20180124-5401-jh4c1s%2FRealm%2FObjectStore%2FDockerfile&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

**Comment by dnkoutso** [comment]
This one works for me locally. It appears to be a local machine issue in which CocoaPods does not have access to write to the cache. Please fix your permissions issue on your machine and try again:

```
The Gemfile's dependencies are satisfied
Analyzing dependencies
Downloading dependencies
Installing Charts (3.0.4)
Installing ChartsRealm (3.0.4)
Installing Realm (2.10.2)
Installing RealmSwift (2.10.2)
Generating Pods project
Integrating client project
Pod installation complete! There are 2 dependencies from the Podfile and 4 total pods installed.
```
