### ISSUE TITLE
[!] Oh no, an error occurred.

### ISSUE THREAD

**Issue by yaron3** [CocoaPods/CocoaPods#7380]
CocoaPods : 1.4.0
        Ruby : ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin17]
    RubyGems : 2.6.14
        Host : Mac OS X 10.13.3 (17D47)
       Xcode : 9.2 (9C40b)
         Git : git version 2.14.3 (Apple Git-98)

# Report
create new pod file

## What did you do?
run pod init
pod install

## What did you expect to happen?
create empty pod

## What happened instead?
show error:
### Error

```
Errno::EACCES - Permission denied @ rb_sysopen - /Users/yaronjackoby/code/tunity-ios/Tunity.xcodeproj/project.pbxproj
/Users/yaronjackoby/.rvm/gems/ruby-2.4.2@global/gems/xcodeproj-1.5.4/lib/xcodeproj/project.rb:353:in `initialize'
/Users/yaronjackoby/.rvm/gems/ruby-2.4.2@global/gems/xcodeproj-1.5.4/lib/xcodeproj/project.rb:353:in `open'
/Users/yaronjackoby/.rvm/gems/ruby-2.4.2@global/gems/xcodeproj-1.5.4/lib/xcodeproj/project.rb:353:in `save'
/Users/yaronjackoby/.rvm/gems/ruby-2.4.2@global/gems/cocoapods-1.4.0/lib/cocoapods/installer/user_project_integrator.rb:139:in `block in save_projects'
/Users/yaronjackoby/.rvm/gems/ruby-2.4.2@global/gems/cocoapods-1.4.0/lib/cocoapods/installer/user_project_integrator.rb:137:in `each'
/Users/yaronjackoby/.rvm/gems/ruby-2.4.2@global/gems/cocoapods-1.4.0/lib/cocoapods/installer/user_project_integrator.rb:137:in `save_projects'
/Users/yaronjackoby/.rvm/gems/ruby-2.4.2@global/gems/cocoapods-1.4.0/lib/cocoapods/installer/user_project_integrator.rb:65:in `integrate!'
/Users/yaronjackoby/.rvm/gems/ruby-2.4.2@global/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:582:in `block in integrate_user_project'
/Users/yaronjackoby/.rvm/gems/ruby-2.4.2@global/gems/cocoapods-1.4.0/lib/cocoapods/user_interface.rb:64:in `section'
/Users/yaronjackoby/.rvm/gems/ruby-2.4.2@global/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:579:in `integrate_user_project'
/Users/yaronjackoby/.rvm/gems/ruby-2.4.2@global/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:121:in `install!'
/Users/yaronjackoby/.rvm/gems/ruby-2.4.2@global/gems/cocoapods-1.4.0/lib/cocoapods/command/install.rb:41:in `run'
/Users/yaronjackoby/.rvm/gems/ruby-2.4.2@global/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/yaronjackoby/.rvm/gems/ruby-2.4.2@global/gems/cocoapods-1.4.0/lib/cocoapods/command.rb:52:in `run'
/Users/yaronjackoby/.rvm/gems/ruby-2.4.2@global/gems/cocoapods-1.4.0/bin/pod:55:in `<top (required)>'
/Users/yaronjackoby/.rvm/rubies/ruby-2.4.2/bin/pod:23:in `load'
/Users/yaronjackoby/.rvm/rubies/ruby-2.4.2/bin/pod:23:in `<main>'
/Users/yaronjackoby/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `eval'
/Users/yaronjackoby/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

### Stack

```
   CocoaPods : 1.4.0
        Ruby : ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin17]
    RubyGems : 2.6.14
        Host : Mac OS X 10.13.3 (17D47)
       Xcode : 9.2 (9C40b)
         Git : git version 2.14.3 (Apple Git-98)
Ruby lib dir : /Users/yaronjackoby/.rvm/rubies/ruby-2.4.2/lib
Repositories : 
```

### Installation Source

```
Executable Path: /Users/yaronjackoby/.rvm/rubies/ruby-2.4.2/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'
target 'Tunity' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for Tunity

  target 'TunityTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

**Comment by dnkoutso** [comment]
Seems like a permissions issue with your machine and the user you are running with. Try 'sudo' or fixing permissions.

This is not a cocoapods library issue.

**Comment by dnkoutso** [comment]
Also use stackoverflow to ask a question with cocoapods tag
