### ISSUE TITLE
Crash when target has no sources but a test spec tries to add dependencies to it

### ISSUE THREAD

**Issue by dnkoutso** [CocoaPods/CocoaPods#7394]
### Command

```
/Users/dimitris/.rvm/gems/ruby-2.4.2/bin/pod lib lint Some.podspec
```

### Report

* What did you do?
Have a podspec with a test spec and dependencies but the actual sources do not create a native target.

* What did you expect to happen?
Things to work.

* What happened instead?
Crashed with following stacktrace

### Stack

```
   CocoaPods : 1.4.0
        Ruby : ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin16]
    RubyGems : 2.6.14
        Host : Mac OS X 10.13.2 (17C205)
       Xcode : 9.2 (9C40b)
         Git : git version 2.15.0
Ruby lib dir : /Users/dimitris/.rvm/rubies/ruby-2.4.2/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 3478b04d995a1b059a54188ecd3d9033de0eb989               
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-gen         : 0.1.19
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Error

```
NoMethodError - undefined method `add_dependency' for nil:NilClass
/Users/dimitris/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/pods_project_generator.rb:329:in `block in add_resource_bundles_to_native_target'
/Users/dimitris/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/pods_project_generator.rb:327:in `each'
/Users/dimitris/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/pods_project_generator.rb:327:in `add_resource_bundles_to_native_target'
/Users/dimitris/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/pods_project_generator.rb:294:in `block (2 levels) in add_pod_target_test_dependencies'
/Users/dimitris/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/pods_project_generator.rb:293:in `each'
/Users/dimitris/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/pods_project_generator.rb:293:in `block in add_pod_target_test_dependencies'
/Users/dimitris/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/pods_project_generator.rb:292:in `each'
/Users/dimitris/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/pods_project_generator.rb:292:in `add_pod_target_test_dependencies'
/Users/dimitris/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/pods_project_generator.rb:226:in `block (2 levels) in set_target_dependencies'
/Users/dimitris/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/pods_project_generator.rb:220:in `each'
/Users/dimitris/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/pods_project_generator.rb:220:in `block in set_target_dependencies'
/Users/dimitris/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/pods_project_generator.rb:215:in `each'
/Users/dimitris/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/pods_project_generator.rb:215:in `set_target_dependencies'
/Users/dimitris/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/pods_project_generator.rb:67:in `generate!'
/Users/dimitris/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:184:in `block in generate_pods_project'
/Users/dimitris/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.4.0/lib/cocoapods/user_interface.rb:64:in `section'
/Users/dimitris/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:183:in `generate_pods_project'
/Users/dimitris/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:119:in `install!'
/Users/dimitris/.rvm/gems/ruby-2.4.2/gems/cocoapods-gen-0.1.19/lib/cocoapods-gen/command/gen.rb:101:in `install'
/Users/dimitris/.rvm/gems/ruby-2.4.2/gems/cocoapods-gen-0.1.19/lib/cocoapods-gen/command/gen.rb:74:in `block in run'
/Users/dimitris/.rvm/gems/ruby-2.4.2/gems/cocoapods-gen-0.1.19/lib/cocoapods-gen/command/gen.rb:69:in `map'
/Users/dimitris/.rvm/gems/ruby-2.4.2/gems/cocoapods-gen-0.1.19/lib/cocoapods-gen/command/gen.rb:69:in `run'
/Users/dimitris/.rvm/gems/ruby-2.4.2/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/dimitris/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.4.0/lib/cocoapods/command.rb:52:in `run'
/Users/dimitris/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.4.0/bin/pod:55:in `<top (required)>'
/Users/dimitris/.rvm/gems/ruby-2.4.2/bin/pod:23:in `load'
/Users/dimitris/.rvm/gems/ruby-2.4.2/bin/pod:23:in `<top (required)>'
/Users/dimitris/.rvm/gems/ruby-2.4.2/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `load'
/Users/dimitris/.rvm/gems/ruby-2.4.2/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `kernel_load'
/Users/dimitris/.rvm/gems/ruby-2.4.2/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:28:in `run'
/Users/dimitris/.rvm/gems/ruby-2.4.2/gems/bundler-1.16.1/lib/bundler/cli.rb:424:in `exec'
/Users/dimitris/.rvm/gems/ruby-2.4.2/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/dimitris/.rvm/gems/ruby-2.4.2/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/dimitris/.rvm/gems/ruby-2.4.2/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/Users/dimitris/.rvm/gems/ruby-2.4.2/gems/bundler-1.16.1/lib/bundler/cli.rb:27:in `dispatch'
/Users/dimitris/.rvm/gems/ruby-2.4.2/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/Users/dimitris/.rvm/gems/ruby-2.4.2/gems/bundler-1.16.1/lib/bundler/cli.rb:18:in `start'
/Users/dimitris/.rvm/gems/ruby-2.4.2/gems/bundler-1.16.1/exe/bundle:30:in `block in <top (required)>'
/Users/dimitris/.rvm/gems/ruby-2.4.2/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
/Users/dimitris/.rvm/gems/ruby-2.4.2/gems/bundler-1.16.1/exe/bundle:22:in `<top (required)>'
/Users/dimitris/.rvm/gems/ruby-2.4.2/bin/bundle:23:in `load'
/Users/dimitris/.rvm/gems/ruby-2.4.2/bin/bundle:23:in `<main>'
```

**Comment by dnkoutso** [comment]
The same most likely applies to empty resource bundles and test specs

**Comment by segiddins** [comment]
It looks like the validator already checks whether the file patterns (if given) match anything

**Comment by dnkoutso** [comment]
This is actually a bit more difficult to accomplish as I originally thought. I know exactly what needs to change but it needs to be done carefully to avoid other breakages. Updated label to "moderate"

**Comment by dnkoutso** [comment]
Punting to 1.6.0 where hopefully a bigger refactor will solve this.

**Comment by dnkoutso** [comment]
I think this is fixed by https://github.com/CocoaPods/CocoaPods/pull/7610 but will verify.

**Comment by dnkoutso** [comment]
This error is actually fixed. CocoaPods no longer crashes but we do have an existing issue. Basically pods that `should_build?` returns `false` will no longer install test specs.

Will track as a different issue and close this one.

**Comment by dnkoutso** [comment]
Did discover another bug though, PR here https://github.com/CocoaPods/CocoaPods/pull/7750
