### ISSUE TITLE
NoMethodError - undefined method `files' for <PBXFileReference path=`Pods` UUID=`95DE25F61D4A826D00EF927B`>:Xcodeproj::Project::Object::PBXFileReference

### ISSUE THREAD

**Issue by terrybu** [CocoaPods/CocoaPods#7395]
# Report

## What did you do?
 Run `pod install`

## What did you expect to happen?
Install all pod dependencies correctly.

## What happened instead?

```
NoMethodError - undefined method `files' for <PBXFileReference path=`Pods` UUID=`95DE25F61D4A826D00EF927B`>:Xcodeproj::Project::Object::PBXFileReference
/Users/tbu/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:47:in `set_target_xcconfig'
/Users/tbu/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:21:in `block (2 levels) in integrate'
/Users/tbu/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:20:in `each'
/Users/tbu/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:20:in `block in integrate'
/Users/tbu/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:19:in `each'
/Users/tbu/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:19:in `integrate'
/Users/tbu/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/user_project_integrator/target_integrator.rb:220:in `block in integrate!'
/Users/tbu/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/user_interface.rb:64:in `section'
/Users/tbu/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/user_project_integrator/target_integrator.rb:219:in `integrate!'
/Users/tbu/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/user_project_integrator.rb:129:in `each'
/Users/tbu/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/user_project_integrator.rb:129:in `integrate_user_targets'
/Users/tbu/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/user_project_integrator.rb:63:in `integrate!'
/Users/tbu/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:582:in `block in integrate_user_project'
/Users/tbu/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/user_interface.rb:64:in `section'
/Users/tbu/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:579:in `integrate_user_project'
/Users/tbu/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:121:in `install!'
/Users/tbu/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/command/install.rb:41:in `run'
/Users/tbu/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/tbu/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/command.rb:52:in `run'
/Users/tbu/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/bin/pod:55:in `<top (required)>'
/Users/tbu/.rbenv/versions/2.5.0/bin/pod:23:in `load'
/Users/tbu/.rbenv/versions/2.5.0/bin/pod:23:in `<main>'
```

**Comment by dnkoutso** [comment]
Please provide a sample app. I can't debug this with this information only.

**Comment by terrybu** [comment]
Sample app is a private repo, is that okay? 
https://github.com/payfone/authwifi-sample/tree/master/client-ios

**Comment by dnkoutso** [comment]
@terrybu unfortunately not i cannot clone this.

**Comment by terrybu** [comment]
@dnkoutso is it possible for me to zip it and send it to you? or should I attach it here

**Comment by dnkoutso** [comment]
Attach it here, you can also send it to me if you'd like not to attach it here for everyone to be able to download it, whatever works for you.

**Comment by terrybu** [comment]
@dnkoutso would rather email it to you, thanks so much. Your email?

**Comment by dnkoutso** [comment]
its in my profile

**Comment by dnkoutso** [comment]
You somehow added another 'Pods' reference to your project as a resource causing the crash. Remove it and it fixes the problem.

<img width="1512" alt="screen_shot_2018-02-02_at_2_36_31_pm" src="https://user-images.githubusercontent.com/310370/35758021-a7cbec1e-0826-11e8-9d4e-3ba9551d87e8.png">

**Comment by terrybu** [comment]
Thanks so much, that looks like that solved it

**Comment by elizabethsiegle** [comment]
thanks @dnkoutso, that helped me too!
