### ISSUE TITLE
Pod Search but an error occurred

### ISSUE THREAD

**Issue by sapphirezzz** [CocoaPods/CocoaPods#7406]
### Command

```
/usr/local/bin/pod search ZPhotoPicker
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.4.0
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]
    RubyGems : 2.6.12
        Host : Mac OS X 10.13.4 (17E139j)
       Xcode : 9.2 (9C40b)
         Git : git version 2.15.1
Ruby lib dir : /Users/zack/.rvm/rubies/ruby-2.3.3/lib
Repositories : aliyun - https://github.com/aliyun/aliyun-specs.git @ 1ecbd779f2fd12ce4d728ce4afd1e9ba2357593b
               master - https://github.com/CocoaPods/Specs.git @ 116663251d38392b32c4b8dee6472028314026cd
               mooyooorg - https://github.com/MooYooOrg/Specs.git @ ba74d3670895f2d057680c22a3d6eff96de7f47f
```

### Plugins

```
claide-plugins        : 0.9.2
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Error

```
JSON::ParserError - 765: unexpected token at 'om":["lottie-ios-lib"],"libwebp":["libwebp"],"encode":["libwebp","mjblibwebp"],"decode":["libwebp","mjblibwebp"],"format.":["libwebp","mjblibwebp"],"Inc.":["libwebp","mjblibwebp"],"mjblibwebp":["mjblibwebp"]}}'
/Users/zack/.rvm/gems/ruby-2.3.3/gems/json-2.1.0/lib/json/common.rb:156:in `parse'
/Users/zack/.rvm/gems/ruby-2.3.3/gems/json-2.1.0/lib/json/common.rb:156:in `parse'
/Users/zack/.rvm/gems/ruby-2.3.3@global/gems/cocoapods-core-1.4.0/lib/cocoapods-core/source/manager.rb:251:in `stored_search_index'
/Users/zack/.rvm/gems/ruby-2.3.3@global/gems/cocoapods-core-1.4.0/lib/cocoapods-core/source/manager.rb:187:in `updated_search_index'
/Users/zack/.rvm/gems/ruby-2.3.3@global/gems/cocoapods-core-1.4.0/lib/cocoapods-core/source/manager.rb:118:in `search_by_name'
/Users/zack/.rvm/gems/ruby-2.3.3@global/gems/cocoapods-search-1.0.0/lib/cocoapods-search/command/search.rb:87:in `local_search'
/Users/zack/.rvm/gems/ruby-2.3.3@global/gems/cocoapods-search-1.0.0/lib/cocoapods-search/command/search.rb:63:in `run'
/Users/zack/.rvm/gems/ruby-2.3.3@global/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/zack/.rvm/gems/ruby-2.3.3/gems/cocoapods-1.4.0/lib/cocoapods/command.rb:52:in `run'
/Users/zack/.rvm/gems/ruby-2.3.3/gems/cocoapods-1.4.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
/Users/zack/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
/Users/zack/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by dnkoutso** [comment]
Can you try `pod cache clean --all` first?

**Comment by dnkoutso** [comment]
Actually also remove `~/Library/Caches/CocoaPods/search_index.json` file and try again.
