### ISSUE TITLE
🌈 Xcode 9.3 Beta Support

### ISSUE THREAD

**Issue by Coder-256** [CocoaPods/CocoaPods#7440]
### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?
I ran `pod install`.
* What did you expect to happen?
I expected `pod install` to run and the Pods project to be generated.
* What happened instead?
CocoaPods crashed. I believe that this is because I am using Xcode 9.3 beta 2 (9Q107o), which has an object version of 50 and has a few minor changes in the pbxproj format (provisioning style, Swift optimization, runpath search paths, etc).

### Stack

```
   CocoaPods : 1.4.0
        Ruby : ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]
    RubyGems : 2.7.4
        Host : Mac OS X 10.13.3 (17D47)
       Xcode : 9.3 (9Q107o)
         Git : git version 2.16.1
Ruby lib dir : /usr/local/Cellar/ruby/2.5.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 2944caefd3c4426945ea5a4f1b1a81fec954dfeb
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ExistingMapTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ExistingMapTest

end
```

### Error

```
RuntimeError - [Xcodeproj] Unknown object version.
/usr/local/lib/ruby/gems/2.5.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project.rb:217:in `initialize_from_file'
/usr/local/lib/ruby/gems/2.5.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project.rb:102:in `open'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/analyzer.rb:907:in `block (2 levels) in inspect_targets_to_integrate'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/analyzer.rb:906:in `each'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/analyzer.rb:906:in `block in inspect_targets_to_integrate'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/analyzer.rb:901:in `inspect_targets_to_integrate'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/analyzer.rb:75:in `analyze'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:243:in `analyze'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:154:in `block in resolve_dependencies'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:153:in `resolve_dependencies'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:116:in `install!'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/command/install.rb:41:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by paulb777** [comment]
`gem update xcodeproj` to 1.5.6

**Comment by Coder-256** [comment]
I'm so sorry.
