### ISSUE TITLE
Undefined method files for PBXFileReference path=Pods 

### ISSUE THREAD

**Issue by reitzig** [CocoaPods/CocoaPods#7450]
### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

`pod install`

* What did you expect to happen?

For the pods to install as usual.

* What happened instead?

During/after step `Integrating client project` the error given below occured.

### Stack

```
   CocoaPods : 1.4.0
        Ruby : ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]
    RubyGems : 2.7.6
        Host : Mac OS X 10.13.3 (17D47)
       Xcode : 9.2 (9C40b)
         Git : git version 2.16.2
Ruby lib dir : /usr/local/Cellar/ruby/2.5.0_1/lib
Repositories : <custom>  - <custom> @ fba384e2826043023eeb3b3172982f2c19ae4679
               master - https://github.com/CocoaPods/Specs.git @ 1919d042f1ca954939afaa444a1d4f17b41058ba
               <custom>  - <custom>  @ a9e778db681616f465676da3bb35c9513c5129d4
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source '<custom>'
source 'https://github.com/CocoaPods/Specs.git'
project 'HsdkaInteropTests.xcodeproj'

target 'HsdkaInteropTests' do
  use_frameworks!
  platform :osx, '10.12'

  inhibit_all_warnings!
  pod 'HealthDataSpace', '1.dev'
  pod 'SecureMessaging', '1.dev'

  target 'TestingHsdkaInteropTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
```

### Error

```
NoMethodError - undefined method `files' for <PBXFileReference path=`Pods` UUID=`OBJ_20`>:Xcodeproj::Project::Object::PBXFileReference
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:47:in `set_target_xcconfig'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:21:in `block (2 levels) in integrate'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:20:in `each'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:20:in `block in integrate'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:19:in `each'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:19:in `integrate'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/user_project_integrator/target_integrator.rb:220:in `block in integrate!'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/user_project_integrator/target_integrator.rb:219:in `integrate!'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/user_project_integrator.rb:129:in `each'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/user_project_integrator.rb:129:in `integrate_user_targets'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/user_project_integrator.rb:63:in `integrate!'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:582:in `block in integrate_user_project'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:579:in `integrate_user_project'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:121:in `install!'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/command/install.rb:41:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```
 And later (after the reporting instructions):

```
Looking for related issues on cocoapods/cocoapods...
Traceback (most recent call last):
	12: from /usr/local/bin/pod:23:in `<main>'
	11: from /usr/local/bin/pod:23:in `load'
	10: from /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/bin/pod:55:in `<top (required)>'
	 9: from /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/command.rb:52:in `run'
	 8: from /usr/local/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:324:in `run'
	 7: from /usr/local/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:337:in `rescue in run'
	 6: from /usr/local/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:396:in `handle_exception'
	 5: from /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/command.rb:67:in `report_error'
	 4: from /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/user_interface/error_report.rb:119:in `search_for_exceptions'
	 3: from /usr/local/lib/ruby/gems/2.5.0/gems/gh_inspector-1.1.2/lib/gh_inspector/inspector.rb:59:in `search_exception'
	 2: from /usr/local/lib/ruby/gems/2.5.0/gems/gh_inspector-1.1.2/lib/gh_inspector/inspector.rb:65:in `search_query'
	 1: from /usr/local/lib/ruby/gems/2.5.0/gems/gh_inspector-1.1.2/lib/gh_inspector/sidekick.rb:24:in `search'
/usr/local/lib/ruby/gems/2.5.0/gems/gh_inspector-1.1.2/lib/gh_inspector/sidekick.rb:67:in `url_for_request': uninitialized constant GhInspector::Sidekick::ERB (NameError)
```

**Comment by reitzig** [comment]
After deleting `Pods`, `pod install` completes successfully. Huh?

**Comment by dnkoutso** [comment]
You probably had a bad reference of Pods project.

**Comment by reitzig** [comment]
If so, then CocoaPods *probably* created it. This is my basic process:

```
swift package init
swift package generate-xcodeproj --xcconfig=<sth that imports the Pods config>
pod install
```

I make no manual modifications to the resulting project or workspace. Well, beyond anything that XCode and/or AppCode do automatically, if anything.

Frankly, closing a ticket the software asked me to create with saying "you probably had [an issue you couldn't avoid]" does not inspire great confidence in said software.

**Comment by dnkoutso** [comment]
@reitzig apologies for being trigger happy. There are a lot of issues filed daily. 

If you can get the error again and reproduce it, perhaps even with a sample app I'd be happy to re-open and investigate.

Your issue looks identical to https://github.com/CocoaPods/CocoaPods/issues/7395 which is why I closed it fairly fast. The stacktrace looks identical.

**Comment by reitzig** [comment]
Heh, I get that. CocoaPods is a popular application with, sorry to be blunt, a number of issues. It's unfortunate that GitHub mashes support and development tickets. :/ I'm sure it's hell to triage.

I'll see what I can do regarding reproducing the problem. The issue doesn't appear consistently, which is what's confusing to me. With SwiftPM, CocoaPods, XCode (or plain `xcodebuild`), and AppCode all working on the same files, I'm never sure what causes what. :/
