### ISSUE TITLE
Error when building (when using CocoaPods from source)

### ISSUE THREAD

**Issue by rmtmckenzie** [CocoaPods/CocoaPods#7467]
🌈
### Command

```
/Users/morgan/Programming/CocoaPods/Rainforest/CocoaPods/bin/pod install
```

### Report

* What did you do?
Get Rainforest and build as per instructions.
Then, ran `rake examples:build`
Same things happen when I try to run `pod install` on my own project that uses cocoapods.

* What did you expect to happen?

Successful build.
* What happened instead?
See error below. It seems not to be auto-loading properly.

### Stack

```
   CocoaPods : 1.4.0
        Ruby : ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin17]
    RubyGems : 2.6.14
        Host : Mac OS X 10.13.3 (17D102)
       Xcode : 9.2 (9C40b)
         Git : git version 2.14.3 (Apple Git-98)
Ruby lib dir : /Users/morgan/.rvm/rubies/ruby-2.4.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ a92cf583e8ee90f5b758d7a70015a26b75d2e0c4
```

### Plugins

```
claide-plugins         : 0.9.2
cocoapods-deintegrate  : 1.0.2
cocoapods-dependencies : 1.1.0
cocoapods-plugins      : 1.0.0
cocoapods-search       : 1.0.0
cocoapods-stats        : 1.0.0
cocoapods-trunk        : 1.3.0
cocoapods-try          : 1.1.0
cocoapods_debug        : 0.1.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
 platform :ios, '10.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

def parse_KV_file(file, separator='=')
  file_abs_path = File.expand_path(file)
  if !File.exists? file_abs_path
    return [];
  end
  pods_ary = []
  skip_line_start_symbols = ["#", "/"]
  File.foreach(file_abs_path) { |line|
      next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
      plugin = line.split(pattern=separator)
      if plugin.length == 2
        podname = plugin[0].strip()
        path = plugin[1].strip()
        podpath = File.expand_path("#{path}", file_abs_path)
        pods_ary.push({:name => podname, :path => podpath});
      else
        puts "Invalid plugin specification: #{line}"
      end
  }
  return pods_ary
end

target 'Runner' do
  use_frameworks!

  # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
  # referring to absolute paths on developers' machines.
  system('rm -rf Pods/.symlinks')
  system('mkdir -p Pods/.symlinks/flutter')
  system('mkdir -p Pods/.symlinks/plugins')

  # Flutter Pods
  generated_xcode_build_settings = parse_KV_file('./Flutter/Generated.xcconfig')
  if generated_xcode_build_settings.empty?
    puts "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter packages get is executed first."
  end
  generated_xcode_build_settings.map { |p|
    if p[:name] == 'FLUTTER_FRAMEWORK_DIR'
      symlink = File.join('Pods', '.symlinks', 'flutter', File.basename(p[:path]))
      File.symlink(p[:path], symlink)
      pod 'Flutter', :path => symlink
    end
  }

  # Plugin Pods
  plugin_pods = parse_KV_file('../.flutter-plugins')
  plugin_pods.map { |p|
    symlink = File.join('Pods', '.symlinks', 'plugins', File.basename(p[:path]))
    File.symlink(p[:path], symlink)
    pod p[:name], :path => File.join(symlink, 'ios')
  }
end

pre_install do |installer|
  # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
```

### Error

```
NameError - uninitialized constant Nanaimo::Reader
Did you mean?  ThreadError
/Users/morgan/Programming/CocoaPods/Rainforest/Xcodeproj/lib/xcodeproj/plist.rb:23:in `read_from_path'
/Users/morgan/Programming/CocoaPods/Rainforest/Xcodeproj/lib/xcodeproj/project.rb:201:in `initialize_from_file'
/Users/morgan/Programming/CocoaPods/Rainforest/Xcodeproj/lib/xcodeproj/project.rb:103:in `open'
/Users/morgan/Programming/CocoaPods/Rainforest/CocoaPods/lib/cocoapods/installer/analyzer.rb:917:in `block (2 levels) in inspect_targets_to_integrate'
/Users/morgan/Programming/CocoaPods/Rainforest/CocoaPods/lib/cocoapods/installer/analyzer.rb:916:in `each'
/Users/morgan/Programming/CocoaPods/Rainforest/CocoaPods/lib/cocoapods/installer/analyzer.rb:916:in `block in inspect_targets_to_integrate'
/Users/morgan/Programming/CocoaPods/Rainforest/CocoaPods/lib/cocoapods/user_interface.rb:64:in `section'
/Users/morgan/Programming/CocoaPods/Rainforest/CocoaPods/lib/cocoapods/installer/analyzer.rb:911:in `inspect_targets_to_integrate'
/Users/morgan/Programming/CocoaPods/Rainforest/CocoaPods/lib/cocoapods/installer/analyzer.rb:75:in `analyze'
/Users/morgan/Programming/CocoaPods/Rainforest/CocoaPods/lib/cocoapods/installer.rb:243:in `analyze'
/Users/morgan/Programming/CocoaPods/Rainforest/CocoaPods/lib/cocoapods/installer.rb:154:in `block in resolve_dependencies'
/Users/morgan/Programming/CocoaPods/Rainforest/CocoaPods/lib/cocoapods/user_interface.rb:64:in `section'
/Users/morgan/Programming/CocoaPods/Rainforest/CocoaPods/lib/cocoapods/installer.rb:153:in `resolve_dependencies'
/Users/morgan/Programming/CocoaPods/Rainforest/CocoaPods/lib/cocoapods/installer.rb:116:in `install!'
/Users/morgan/Programming/CocoaPods/Rainforest/CocoaPods/lib/cocoapods/command/install.rb:41:in `run'
/Users/morgan/Programming/CocoaPods/Rainforest/CLAide/lib/claide/command.rb:334:in `run'
/Users/morgan/Programming/CocoaPods/Rainforest/CocoaPods/lib/cocoapods/command.rb:52:in `run'
/Users/morgan/Programming/CocoaPods/Rainforest/CocoaPods/bin/pod:55:in `<main>'
```

**Comment by dnkoutso** [comment]
Seems like nanaimo gem is not installed

**Comment by rmtmckenzie** [comment]
Isn't the idea with the rainforest that the local nanaimo is used though? That's what I was trying to do here.

**Comment by segiddins** [comment]
Have you run `bundle install` in the Rainforest repo?

**Comment by dnkoutso** [comment]
imo we should file an issue in https://github.com/CocoaPods/Rainforest instead

**Comment by rmtmckenzie** [comment]
@segiddins I'm fairly sure I did but I will double check when I get a minute and then file in Rainforest if it is still an issue.
