### ISSUE TITLE
Error when trying to install pods (Errno::ENOSYS - Function not implemented @ rb_file_s_symlink)

### ISSUE THREAD

**Issue by cvfm** [CocoaPods/CocoaPods#7480]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run pod install (or even pod update)

## What did you expect to happen?

Install all pod dependencies correctly.

## What happened instead?

I got the error below: 
```
Errno::ENOSYS - Function not implemented @ rb_file_s_symlink - (../../../AFNetworking/AFNetworking/AFNetworking.h, /Volumes/GoogleDrive/Meu Drive/Projetos/Tellme/_SVN_iOS/iphone/Pods/Headers/Private/AFNetworking/AFNetworking.h)
/usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/fileutils.rb:358:in `symlink'
/usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/fileutils.rb:358:in `block in ln_s'
/usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/fileutils.rb:1585:in `fu_each_src_dest0'
/usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/fileutils.rb:356:in `ln_s'
/usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/fileutils.rb:379:in `ln_sf'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/sandbox/headers_store.rb:99:in `add_file'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/sandbox/headers_store.rb:75:in `block in add_files'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/sandbox/headers_store.rb:74:in `map'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/sandbox/headers_store.rb:74:in `add_files'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:151:in `block (4 levels) in link_headers'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:150:in `each'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:150:in `block (3 levels) in link_headers'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:138:in `each'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:138:in `block (2 levels) in link_headers'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:137:in `each'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:137:in `block in link_headers'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/user_interface.rb:142:in `message'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:136:in `link_headers'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:44:in `install!'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/pods_project_generator.rb:163:in `install_file_references'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/pods_project_generator.rb:64:in `generate!'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:184:in `block in generate_pods_project'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:183:in `generate_pods_project'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:119:in `install!'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/command/install.rb:41:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.4.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
/usr/local/bin/ruby_executable_hooks:15:in `eval'
/usr/local/bin/ruby_executable_hooks:15:in `<main>'
```

### Stack

```
   CocoaPods : 1.4.0
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.12.6 (16G29)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.10.1 (Apple Git-78)
Ruby lib dir : /usr/local/Cellar/ruby/2.3.1_2/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 9444913654649797b4d1fddde99c4ebb1091dd37
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
target "MyProject" do

platform :ios, '7.0'

pod 'AFNetworking'
pod 'MBProgressHUD', '~> 0.8'
pod 'ReactiveCocoa', '~> 2.1.6'
pod 'SDWebImage', '~> 3.5'
pod 'TTTAttributedLabel'
pod 'HPGrowingTextView'
pod 'TCMobileProvision', '~> 1.0'
pod 'FSCalendar', '~> 2.7'

end

**Comment by dnkoutso** [comment]
This one worked for me:
```
Analyzing dependencies
Downloading dependencies
Installing AFNetworking (3.2.0)
Installing DTFoundation (1.7.13)
Installing FSCalendar (2.7.9)
Installing HPGrowingTextView (1.1)
Installing MBProgressHUD (0.9.2)
Installing ReactiveCocoa (2.1.8)
Installing SDWebImage (3.8.2)
Installing TCMobileProvision (1.0.0)
Installing TTTAttributedLabel (2.0.0)
Generating Pods project
Integrating client project
Pod installation complete! There are 8 dependencies from the Podfile and 9 total pods installed.
```

Please provide a sample app demonstrating the issue.

**Comment by cvfm** [comment]
More details:
I just realized that the <pod install> works on my old (project) folder. However, it does not work in the new folder that I created in the "Drive File Stream" (new Google Drive).

**Comment by dnkoutso** [comment]
its kinda hard to diagnose this without a list of steps to reproduce it or a sample app.

**Comment by cvfm** [comment]
I could not create a sample app, sorry. However, I will leave my suppositions here to help someone else.
I was trying to install the pods in a folder that was in my Drive File Stream (new Google Drive). However, in MacOS the Drive File Stream folder is recognized as a flash drive. My supposition is that this is the problem (the flash drive). Because I just cloned the repository to another folder that is not recognized as flash drive and it worked fine.

Thanks for your attention @dnkoutso!

**Comment by long1eu** [comment]
@cvfm Did you found a solution for this?
