### ISSUE TITLE
Nativescript angular cocoapods-1.4.0 fails to run after plugin installation

### ISSUE THREAD

**Issue by genkan-drew** [CocoaPods/CocoaPods#7537]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

tns plugin add nativescript-iqkeyboardmanager
tns run ios --clean

## What did you expect to happen?

Application to run in the ios simulator

## What happened instead?

SystemStackError - stack level too deep
/Mobile/360-id/id360/platforms/ios/Podfile:325:in `post_install1'
/Mobile/360-id/id360/platforms/ios/Podfile:356:in `block (2 levels) in from_ruby'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.4.0/lib/cocoapods-core/podfile.rb:179:in `post_install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:638:in `run_podfile_post_install_hook'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:626:in `block in run_podfile_post_install_hooks'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/user_interface.rb:142:in `message'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:625:in `run_podfile_post_install_hooks'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:186:in `block in generate_pods_project'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:183:in `generate_pods_project'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:119:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/command/install.rb:41:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.


## CocoaPods Environment

CocoaPods : 1.4.0
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    RubyGems : 2.5.2
        Host : Mac OS X 10.13.3 (17D47)
       Xcode : 9.2 (9C40b)
         Git : git version 2.14.3 (Apple Git-98)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 9db90a2c73c284d9b3199b75c6483081688ef9be
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
use_frameworks!

target "id360" do
# Begin Podfile - /Mobile/360-id/id360/node_modules/nativescript-bottombar/platforms/ios/Podfile 
 use_frameworks!
pod 'MiniTabBar', :git => 'https://github.com/rhanb/MiniTabBar.git'
def post_install1 (installer)
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end 
 # End Podfile 
# Begin Podfile - /Mobile/360-id/id360/node_modules/nativescript-ocr/platforms/ios/Podfile 
 pod 'TesseractOCRiOS', :git => 'https://github.com/eddyverbruggen/Tesseract-OCR-iOS.git'

def post_install2 (installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end 
 # End Podfile 

end
def post_install1 (installer)
  post_install1 installer
  post_install2 installer# Begin Podfile - /Mobile/360-id/id360/node_modules/nativescript-bottombar/platforms/ios/Podfile 
 use_frameworks!
pod 'MiniTabBar', :git => 'https://github.com/rhanb/MiniTabBar.git'
def post_install2 (installer)
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end 
 # End Podfile 
# Begin Podfile - /Mobile/360-id/id360/node_modules/nativescript-ocr/platforms/ios/Podfile 
 pod 'TesseractOCRiOS', :git => 'https://github.com/eddyverbruggen/Tesseract-OCR-iOS.git'

def post_install3 (installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end 
 # End Podfile 

end
def post_install1 (installer)
  post_install1 installer
  post_install2 installer
  post_install3 installer# Begin Podfile - /Mobile/360-id/id360/node_modules/nativescript-bottombar/platforms/ios/Podfile 
 use_frameworks!
pod 'MiniTabBar', :git => 'https://github.com/rhanb/MiniTabBar.git'
def post_install2 (installer)
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end 
 # End Podfile 
# Begin Podfile - /Mobile/360-id/id360/node_modules/nativescript-ocr/platforms/ios/Podfile 
 pod 'TesseractOCRiOS', :git => 'https://github.com/eddyverbruggen/Tesseract-OCR-iOS.git'

def post_install3 (installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end 
 # End Podfile 

end
def post_install1 (installer)
  post_install1 installer
  post_install2 installer
  post_install3 installer# Begin Podfile - /Mobile/360-id/id360/node_modules/nativescript-bottombar/platforms/ios/Podfile 
 use_frameworks!
pod 'MiniTabBar', :git => 'https://github.com/rhanb/MiniTabBar.git'
def post_install2 (installer)
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end 
 # End Podfile 
# Begin Podfile - /Mobile/360-id/id360/node_modules/nativescript-ocr/platforms/ios/Podfile 
 pod 'TesseractOCRiOS', :git => 'https://github.com/eddyverbruggen/Tesseract-OCR-iOS.git'

def post_install3 (installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end 
 # End Podfile 

end
def post_install1 (installer)
  post_install1 installer
  post_install2 installer
  post_install3 installer# Begin Podfile - /Mobile/360-id/id360/node_modules/nativescript-bottombar/platforms/ios/Podfile 
 use_frameworks!
pod 'MiniTabBar', :git => 'https://github.com/rhanb/MiniTabBar.git'
def post_install2 (installer)
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end 
 # End Podfile 
# Begin Podfile - /Mobile/360-id/id360/node_modules/nativescript-ocr/platforms/ios/Podfile 
 pod 'TesseractOCRiOS', :git => 'https://github.com/eddyverbruggen/Tesseract-OCR-iOS.git'

def post_install3 (installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end 
 # End Podfile 

end
def post_install1 (installer)
  post_install1 installer
  post_install2 installer
  post_install3 installer# Begin Podfile - /Mobile/360-id/id360/node_modules/nativescript-bottombar/platforms/ios/Podfile 
 use_frameworks!
pod 'MiniTabBar', :git => 'https://github.com/rhanb/MiniTabBar.git'
def post_install2 (installer)
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end 
 # End Podfile 
# Begin Podfile - /Mobile/360-id/id360/node_modules/nativescript-ocr/platforms/ios/Podfile 
 pod 'TesseractOCRiOS', :git => 'https://github.com/eddyverbruggen/Tesseract-OCR-iOS.git'

def post_install3 (installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end 
 # End Podfile 

end
def post_install1 (installer)
  post_install1 installer
  post_install2 installer
  post_install3 installer# Begin Podfile - /Mobile/360-id/id360/node_modules/nativescript-bottombar/platforms/ios/Podfile 
 use_frameworks!
pod 'MiniTabBar', :git => 'https://github.com/rhanb/MiniTabBar.git'
def post_install2 (installer)
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end 
 # End Podfile 
# Begin Podfile - /Mobile/360-id/id360/node_modules/nativescript-ocr/platforms/ios/Podfile 
 pod 'TesseractOCRiOS', :git => 'https://github.com/eddyverbruggen/Tesseract-OCR-iOS.git'

def post_install3 (installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end 
 # End Podfile 

end
def post_install1 (installer)
  post_install1 installer
  post_install2 installer
  post_install3 installer# Begin Podfile - /Mobile/360-id/id360/node_modules/nativescript-bottombar/platforms/ios/Podfile 
 use_frameworks!
pod 'MiniTabBar', :git => 'https://github.com/rhanb/MiniTabBar.git'
def post_install2 (installer)
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end 
 # End Podfile 
# Begin Podfile - /Mobile/360-id/id360/node_modules/nativescript-ocr/platforms/ios/Podfile 
 pod 'TesseractOCRiOS', :git => 'https://github.com/eddyverbruggen/Tesseract-OCR-iOS.git'

def post_install3 (installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end 
 # End Podfile 

end
def post_install1 (installer)
  post_install1 installer
  post_install2 installer
  post_install3 installer# Begin Podfile - /Mobile/360-id/id360/node_modules/nativescript-bottombar/platforms/ios/Podfile 
 use_frameworks!
pod 'MiniTabBar', :git => 'https://github.com/rhanb/MiniTabBar.git'
def post_install2 (installer)
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end 
 # End Podfile 
# Begin Podfile - /Mobile/360-id/id360/node_modules/nativescript-ocr/platforms/ios/Podfile 
 pod 'TesseractOCRiOS', :git => 'https://github.com/eddyverbruggen/Tesseract-OCR-iOS.git'

def post_install3 (installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end 
 # End Podfile 

end
def post_install1 (installer)
  post_install1 installer
  post_install2 installer
  post_install3 installer# Begin Podfile - /Mobile/360-id/id360/node_modules/nativescript-bottombar/platforms/ios/Podfile 
 use_frameworks!
pod 'MiniTabBar', :git => 'https://github.com/rhanb/MiniTabBar.git'
def post_install2 (installer)
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end 
 # End Podfile 
# Begin Podfile - /Mobile/360-id/id360/node_modules/nativescript-ocr/platforms/ios/Podfile 
 pod 'TesseractOCRiOS', :git => 'https://github.com/eddyverbruggen/Tesseract-OCR-iOS.git'

def post_install3 (installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end 
 # End Podfile 

end
def post_install1 (installer)
  post_install1 installer
  post_install2 installer
  post_install3 installer# Begin Podfile - /Mobile/360-id/id360/node_modules/nativescript-bottombar/platforms/ios/Podfile 
 use_frameworks!
pod 'MiniTabBar', :git => 'https://github.com/rhanb/MiniTabBar.git'
def post_install2 (installer)
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end 
 # End Podfile 
# Begin Podfile - /Mobile/360-id/id360/node_modules/nativescript-ocr/platforms/ios/Podfile 
 pod 'TesseractOCRiOS', :git => 'https://github.com/eddyverbruggen/Tesseract-OCR-iOS.git'

def post_install3 (installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end 
 # End Podfile 

end
def post_install1 (installer)
  post_install1 installer
  post_install2 installer
  post_install3 installer# Begin Podfile - /Mobile/360-id/id360/node_modules/nativescript-bottombar/platforms/ios/Podfile 
 use_frameworks!
pod 'MiniTabBar', :git => 'https://github.com/rhanb/MiniTabBar.git'
def post_install2 (installer)
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end 
 # End Podfile 
# Begin Podfile - /Mobile/360-id/id360/node_modules/nativescript-ocr/platforms/ios/Podfile 
 pod 'TesseractOCRiOS', :git => 'https://github.com/eddyverbruggen/Tesseract-OCR-iOS.git'

def post_install3 (installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end 
 # End Podfile 

end
def post_install1 (installer)
  post_install1 installer
  post_install2 installer
  post_install3 installer# Begin Podfile - /Mobile/360-id/id360/node_modules/nativescript-bottombar/platforms/ios/Podfile 
 use_frameworks!
pod 'MiniTabBar', :git => 'https://github.com/rhanb/MiniTabBar.git'
def post_install2 (installer)
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end 
 # End Podfile 
# Begin Podfile - /Mobile/360-id/id360/node_modules/nativescript-iqkeyboardmanager/platforms/ios/Podfile 
 pod 'IQKeyboardManager', '~> 5.0.0'
 
 # End Podfile 
# Begin Podfile - /Mobile/360-id/id360/node_modules/nativescript-ocr/platforms/ios/Podfile 
 pod 'TesseractOCRiOS', :git => 'https://github.com/eddyverbruggen/Tesseract-OCR-iOS.git'

def post_install3 (installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end 
 # End Podfile 

end
post_install do |installer|
  post_install1 installer
  post_install2 installer
  post_install3 installer
end
```

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

**Comment by orta** [comment]
> SystemStackError - stack level too deep

Impies you've got an infinite loop somewhere.

**Comment by dnkoutso** [comment]
This seems like a user error in the custom `post_install` hooks you've written. 

Going to close as this does not appear a CocoaPods library issue. Feel free to comment further and if we can confirm its a CocoaPods problem I an will re-open.
