### ISSUE TITLE
Error on pod trunk push

### ISSUE THREAD

**Issue by Recouse** [CocoaPods/CocoaPods#7555]
### Command

```
/usr/local/bin/pod trunk push MaterialProgressBar.podspec
```

### Report

* What did you do?
Pushed my pod

* What did you expect to happen?
Push

* What happened instead?
Got an error: [!] Oh no, an error occurred.

### Stack

```
   CocoaPods : 1.4.0
        Ruby : ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]
    RubyGems : 2.7.4
        Host : Mac OS X 10.13.3 (17D47)
       Xcode : 9.2 (9C40b)
         Git : git version 2.16.1
Ruby lib dir : /usr/local/Cellar/ruby/2.5.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 503f4173b8e892ea6723165ed968ee6394923ed8
```

### Plugins

```
cocoapods-clean       : 0.0.1
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Error

```
Netrc::Error - Permission bits for '/Users/recouse/.netrc' should be 0600, but are 644
/usr/local/lib/ruby/gems/2.5.0/gems/netrc-0.11.0/lib/netrc.rb:45:in `check_permissions'
/usr/local/lib/ruby/gems/2.5.0/gems/netrc-0.11.0/lib/netrc.rb:52:in `read'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-trunk-1.3.0/lib/pod/command/trunk.rb:106:in `netrc'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-trunk-1.3.0/lib/pod/command/trunk.rb:111:in `token'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-trunk-1.3.0/lib/pod/command/trunk/push.rb:54:in `validate!'
/usr/local/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:333:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.4.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by dnkoutso** [comment]
The error clearly shows what the problem is.

Please also use StackOverflow under `cocoapods` tags for these questions.

Probably need to `chmod` the `.netrc` file.

**Comment by Recouse** [comment]
Oh, sorry. Thank you.
