### ISSUE TITLE
NoMethodError - undefined method `version' for nil:NilClass

### ISSUE THREAD

**Issue by awanglilong** [CocoaPods/CocoaPods#7561]
### Command

```
/Users/wanglilong/.rvm/rubies/ruby-2.4.1/bin/pod list
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.5.0.beta.1
        Ruby : ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
    RubyGems : 2.6.14
        Host : Mac OS X 10.12.6 (16G1212)
       Xcode : 9.1 (9B55)
         Git : git version 2.13.6 (Apple Git-96)
Ruby lib dir : /Users/wanglilong/.rvm/rubies/ruby-2.4.1/lib
Repositories : .git - https://github.com/CocoaPods/Specs.git @ e8783d55ad2eb614677f08ee2c258df0fbbf5fbf
               master - https://github.com/CocoaPods/Specs.git @ d2194f68b5a4e7dfa8e0310fed76e71694c9ec5d
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'new' do
pod 'AFNetworking’

end
```

### Error

```
NoMethodError - undefined method `version' for nil:NilClass
/Users/wanglilong/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.5.0.beta.1/lib/cocoapods/user_interface.rb:209:in `pod'
/Users/wanglilong/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.5.0.beta.1/lib/cocoapods/command/list.rb:24:in `block in run'
/Users/wanglilong/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.5.0.beta.1/lib/cocoapods/command/list.rb:24:in `each'
/Users/wanglilong/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.5.0.beta.1/lib/cocoapods/command/list.rb:24:in `run'
/Users/wanglilong/.rvm/gems/ruby-2.4.1@global/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/wanglilong/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.5.0.beta.1/lib/cocoapods/command.rb:52:in `run'
/Users/wanglilong/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.5.0.beta.1/bin/pod:55:in `<top (required)>'
/Users/wanglilong/.rvm/rubies/ruby-2.4.1/bin/pod:23:in `load'
/Users/wanglilong/.rvm/rubies/ruby-2.4.1/bin/pod:23:in `<main>'
/Users/wanglilong/.rvm/gems/ruby-2.4.1@global/bin/ruby_executable_hooks:15:in `eval'
/Users/wanglilong/.rvm/gems/ruby-2.4.1@global/bin/ruby_executable_hooks:15:in `<main>'


ls -l ~/.cocoapods/repos/master/Specs            print
total 0
drwxr-xr-x 19 wanglilong staff 646 3 30 09:12 0
drwxr-xr-x 18 wanglilong staff 612 3 30 07:37 1
drwxr-xr-x 18 wanglilong staff 612 3 30 07:37 2
drwxr-xr-x 18 wanglilong staff 612 3 30 07:37 3
drwxr-xr-x 18 wanglilong staff 612 3 30 07:37 4
drwxr-xr-x 18 wanglilong staff 612 3 30 07:37 5
drwxr-xr-x 18 wanglilong staff 612 3 30 07:37 6
drwxr-xr-x 18 wanglilong staff 612 3 30 07:38 7
drwxr-xr-x 18 wanglilong staff 612 3 30 07:38 8
drwxr-xr-x 18 wanglilong staff 612 3 30 07:38 9
drwxr-xr-x 18 wanglilong staff 612 3 30 07:38 a
drwxr-xr-x 18 wanglilong staff 612 3 30 07:38 b
drwxr-xr-x 18 wanglilong staff 612 3 30 07:38 c
drwxr-xr-x 18 wanglilong staff 612 3 30 07:38 d
drwxr-xr-x 18 wanglilong staff 612 3 30 07:38 e
drwxr-xr-x 18 wanglilong staff 612 3 30 07:38 f

I  have   run 
sudo rm -fr ~/.cocoapods/repos/master
pod setup


The problems still exist.

pod install   show
[!] Unable to find a specification for `AFNetworking`

**Comment by awanglilong** [comment]
sudo rm -fr ~/.cocoapods/repos/master. then pod setup   many times, the problems still exist.
But,before pod setup,  delete .cocoapods folder. Now it's ok.

**Comment by acalism** [comment]
> sudo rm -fr ~/.cocoapods/repos/master. then pod setup many times, the problems still exist.
> But,before pod setup, delete .cocoapods folder. Now it's ok.

same issue. but it does not work for me.

**Comment by domdop** [comment]
Ich bin derzeit nicht im Büro. Ich kehre zurück am  02.01.2019.
Ich werde Ihre Nachricht nach meiner Rückkehr beantworten.

Die Rückmeldung bezieht sich auf ein Mail mit folgendem Thema:
Re: [CocoaPods/CocoaPods] NoMethodError - undefined method `version' for
nil:NilClass (#7561)

____________________________________________________________________________________________
Gesendet (c) GRZ/RACON Linz 2018 Agent 'Abwesenheit'

----------------------------------------
Raiffeisen Software GmbH
Firmenbuchnummer: 86804d, Landesgericht Linz
DVR: 0572934, UID: ATU 36961105

Der Austausch von Nachrichten mit dem oben angeführten Absender via E-Mail
dient ausschließlich Informationszwecken. Rechtsgeschäftliche Erklärungen
dürfen über dieses Medium nicht ausgetauscht werden.
Correspondence with above mentioned sender via e-mail is only for
information purposes. This medium is not to be used for the exchange of
legally-binding communications.
----------------------------------------
