### ISSUE TITLE
The operation couldn’t be completed. (CocoaPods.CPPodfileInitErrors error 0.)

### ISSUE THREAD

**Issue by nissaba** [CocoaPods/CocoaPods#7614]
### Command

```
/Applications/CocoaPods.app/Contents/Resources/bundle/bin/pod init TestGridCell.xcodeproj
```

### Report

* What did you do? file> new podfile from project

* What did you expect to happen? to get a new podfile

* What happened instead? got the error asking to fill this and post it.

### Stack

```
   CocoaPods : 1.4.0
        Ruby : ruby 2.2.6p396 (2016-11-15 revision 56800) [x86_64-darwin15]
    RubyGems : 2.6.8
        Host : Mac OS X 10.13.4 (17E199)
       Xcode : 9.3 (9E145)
         Git : git version 2.6.2
Ruby lib dir : /Applications/CocoaPods.app/Contents/Resources/bundle/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ e4d749b95636b5a3d75893d51ecee8c5ab35215a
               StringyImage - http://pascale:pige2[tombes@gitbuntu.prospects/iOS/StringyImage.git @ e8c7c21c04451885ec7ee17d87cd9bfb2e657dd1
```

### Plugins

```
cocoapods-check           : 1.0.0
cocoapods-deintegrate     : 1.0.2
cocoapods-plugins         : 1.0.0
cocoapods-plugins-install : 0.0.1
cocoapods-search          : 1.0.0
cocoapods-stats           : 1.0.0
cocoapods-trunk           : 1.3.0
cocoapods-try             : 1.1.0
```

### Error

```
RuntimeError - [Xcodeproj] Unknown object version.
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project.rb:217:in `initialize_from_file'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project.rb:102:in `open'
/Applications/CocoaPods.app/Contents/Resources/

**Comment by dnkoutso** [comment]
Please update to Xcodeproj gem 1.5.7.
