### ISSUE TITLE
Internal server error when pushing new pod

### ISSUE THREAD

**Issue by EricBup** [CocoaPods/CocoaPods#7657]
* [ Y] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod trunk push BZButton.podspec --verbose`

## What did you expect to happen?

publish pod.

## What happened instead?

failure with instructions to check twitter for errors (none seen).
```
    ** BUILD SUCCEEDED **
    
   Testing with `xcodebuild`. 
 -> BZButton (1.1.5)

opening connection to trunk.cocoapods.org:443...
opened
starting SSL for trunk.cocoapods.org:443...
SSL established
<- "POST /api/v1/pods?allow_warnings=false HTTP/1.1\r\nContent-Type: application/json; charset=utf-8\r\nAccept: application/json; charset=utf-8\r\nUser-Agent: CocoaPods/1.5.0\r\nAuthorization: Token ***\r\nAccept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3\r\nHost: trunk.cocoapods.org\r\nContent-Length: 352\r\n\r\n"
<- "{\"name\":\"BZButton\",\"version\":\"1.1.5\",\"summary\":\"xib control button image and text\",\"homepage\":\"https://github.com/EricBup/BZButton\",\"license\":\"MIT\",\"authors\":{\"EricBup\":\"375298211@qq.com\"},\"platforms\":{\"ios\":\"8.0\"},\"source\":{\"git\":\"https://github.com/EricBup/BZButton.git\",\"tag\":\"1.1.5\"},\"source_files\":\"BZButton/Classess/*.{h,m}\",\"requires_arc\":true}\n"
-> "HTTP/1.1 500 Internal Server Error\r\n"
-> "Date: Wed, 18 Apr 2018 06:49:21 GMT\r\n"
-> "Connection: keep-alive\r\n"
-> "Strict-Transport-Security: max-age=31536000\r\n"
-> "Content-Type: application/json\r\n"
-> "Content-Length: 141\r\n"
-> "X-Content-Type-Options: nosniff\r\n"
-> "Server: thin 1.6.2 codename Doc Brown\r\n"
-> "Via: 1.1 vegur\r\n"
-> "\r\n"
reading 141 bytes...
-> "{\"error\":\"An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later.\"}"
read 141 bytes
Conn keep-alive
[!] An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later.

/Users/eric_bup/.rvm/gems/ruby-2.4.1/gems/cocoapods-trunk-1.3.0/lib/pod/command/trunk.rb:70:in `print_error'
/Users/eric_bup/.rvm/gems/ruby-2.4.1/gems/cocoapods-trunk-1.3.0/lib/pod/command/trunk.rb:30:in `request_url'
/Users/eric_bup/.rvm/gems/ruby-2.4.1/gems/cocoapods-trunk-1.3.0/lib/pod/command/trunk.rb:36:in `request_path'
/Users/eric_bup/.rvm/gems/ruby-2.4.1/gems/cocoapods-trunk-1.3.0/lib/pod/command/trunk/push.rb:83:in `push_to_trunk'
/Users/eric_bup/.rvm/gems/ruby-2.4.1/gems/cocoapods-trunk-1.3.0/lib/pod/command/trunk/push.rb:69:in `run'
/Users/eric_bup/.rvm/gems/ruby-2.4.1/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/eric_bup/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.5.0/lib/cocoapods/command.rb:52:in `run'
/Users/eric_bup/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.5.0/bin/pod:55:in `<top (required)>'
/Users/eric_bup/.rvm/gems/ruby-2.4.1/bin/pod:23:in `load'
/Users/eric_bup/.rvm/gems/ruby-2.4.1/bin/pod:23:in `<main>'
/Users/eric_bup/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
/Users/eric_bup/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
```

### Stack

```
   CocoaPods : 1.5.0
        Ruby : ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
    RubyGems : 2.6.14
        Host : Mac OS X 10.12.6 (16G29)
       Xcode : 9.2 (9C40b)
         Git : git version 2.14.3 (Apple Git-98)
Ruby lib dir : /Users/eric_bup/.rvm/rubies/ruby-2.4.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 81be904c104283252f21a46bf6f5062283e56914
```

### Installation Source

```
Executable Path: /Users/eric_bup/.rvm/gems/ruby-2.4.1/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

https://github.com/EricBup/BZButton

**Comment by EricBup** [comment]
From 7 days ago to now.Once uploaded successfully, the version number is 1.0.1.However, it cannot be used normally and it cannot be updated.

**Comment by EricBZH** [comment]
Could you please check it for me? Is my account blacklisted? Because I have always had this problem, and I have already found many answers to this type of question. I can only re-upload with a new GithHub account, and the results won't work.

**Comment by EricBZH** [comment]
@dnkoutso Could you please check it for me? Is my account blacklisted? Because I have always had this problem, and I have already found many answers to this type of question. I can only re-upload with a new GithHub account, and the results won't work.

**Comment by EricBup** [comment]
@dnkoutso Could you please check it for me? Is my account blacklisted? Because I have always had this problem, and I have already found many answers to this type of question. I can only re-upload with a new GithHub account, and the results won't work.
