### ISSUE TITLE
pod search marqueeview error,this pod is made by myself,but it doesn't work;I have try anything;

### ISSUE THREAD

**Issue by OneWang** [CocoaPods/CocoaPods#7668]
pod search marqueeview

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/jack/.rvm/gems/ruby-2.4.0/bin/pod search marqueeview
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.5.0
        Ruby : ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin17]
    RubyGems : 2.6.14
        Host : Mac OS X 10.13.4 (17E199)
       Xcode : 9.3 (9E145)
         Git : git version 2.15.1 (Apple Git-101)
Ruby lib dir : /Users/jack/.rvm/rubies/ruby-2.4.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ d4815404ae25a0ca3e73d1298cff56ea10ec447c
               specs - https://github.com/OneWang/MarqueeView.git @ 1c5d8bfb2a0928094524896b1d4be5b5c2aaf217
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Error

```
ArgumentError - comparison of Pod::Version with nil failed
/Users/jack/.rvm/gems/ruby-2.4.0@global/gems/cocoapods-core-1.5.0/lib/cocoapods-core/source/aggregate.rb:60:in `<'
/Users/jack/.rvm/gems/ruby-2.4.0@global/gems/cocoapods-core-1.5.0/lib/cocoapods-core/source/aggregate.rb:60:in `block in representative_set'
/Users/jack/.rvm/gems/ruby-2.4.0@global/gems/cocoapods-core-1.5.0/lib/cocoapods-core/source/aggregate.rb:56:in `each'
/Users/jack/.rvm/gems/ruby-2.4.0@global/gems/cocoapods-core-1.5.0/lib/cocoapods-core/source/aggregate.rb:56:in `representative_set'
/Users/jack/.rvm/gems/ruby-2.4.0@global/gems/cocoapods-core-1.5.0/lib/cocoapods-core/source/manager.rb:129:in `block in search_by_name'
/Users/jack/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/set.rb:324:in `each_key'
/Users/jack/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/set.rb:324:in `each'
/Users/jack/.rvm/gems/ruby-2.4.0@global/gems/cocoapods-core-1.5.0/lib/cocoapods-core/source/manager.rb:128:in `map'
/Users/jack/.rvm/gems/ruby-2.4.0@global/gems/cocoapods-core-1.5.0/lib/cocoapods-core/source/manager.rb:128:in `search_by_name'
/Users/jack/.rvm/gems/ruby-2.4.0/gems/cocoapods-search-1.0.0/lib/cocoapods-search/command/search.rb:87:in `local_search'
/Users/jack/.rvm/gems/ruby-2.4.0/gems/cocoapods-search-1.0.0/lib/cocoapods-search/command/search.rb:63:in `run'
/Users/jack/.rvm/gems/ruby-2.4.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/jack/.rvm/gems/ruby-2.4.0@global/gems/cocoapods-1.5.0/lib/cocoapods/command.rb:52:in `run'
/Users/jack/.rvm/gems/ruby-2.4.0@global/gems/cocoapods-1.5.0/bin/pod:55:in `<top (required)>'
/Users/jack/.rvm/gems/ruby-2.4.0/bin/pod:23:in `load'
/Users/jack/.rvm/gems/ruby-2.4.0/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=comparison+of+Pod%3A%3AVersion+with+nil+failed&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
 - Swift unit tests broken after the migration to cocoapods 0.36.RC.1
   https://github.com/CocoaPods/CocoaPods/issues/3244 [closed] [11 comments]
   31 Mar 2015

**Comment by dnkoutso** [comment]
Please file an issue on https://github.com/CocoaPods/cocoapods-search repo
