### ISSUE TITLE
https://github.com/CocoaPods/CocoaPods/search?q=Illformed+requirement+%60%22%7E%3E+r2.0%22%60&type=Issues

### ISSUE THREAD

**Issue by hanil1207** [CocoaPods/CocoaPods#7677]
* [ ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace these two lines with what you did.  
e.g. Run `pod install`

## What did you expect to happen?

ℹ Please replace these two lines with what you expected to happen.  
e.g. Install all pod dependencies correctly.

## What happened instead?

ℹ Please replace these two lines with of what happened instead.  
e.g. Pod A is missing the subspec B for target C.

## CocoaPods Environment

ℹ Please replace these two lines with the output of `pod env`.
e.g. via `pod env | pbcopy`

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

**Comment by dnkoutso** [comment]
please fill in the template.

**Comment by hanil1207** [comment]
### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.4.0
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    RubyGems : 2.5.2
        Host : Mac OS X 10.13.4 (17E199)
       Xcode : 9.2 (9C40b)
         Git : git version 2.14.3 (Apple Git-98)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 42040b5d78da20ee095bc3d3043d44e0425a9eb8
```

### Plugins

```
cocoapods-clean       : 0.0.1
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'vMOD' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for vMOD
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Fabric'
  pod 'TwitterKit'
  pod 'IOSLinkedInAPIFix', '~> r2.0'
  pod 'ApiAI'
  pod 'FRHyperLabel'
  pod 'GoogleMobileVision/FaceDetector'
  pod 'SDWebImage', '~> 4.0'
end
```

### Error

```
ArgumentError - Illformed requirement `"~> r2.0"`
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.4.0/lib/cocoapods-core/requirement.rb:63:in `parse'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.4.0/lib/cocoapods-core/requirement.rb:88:in `block in initialize'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.4.0/lib/cocoapods-core/requirement.rb:88:in `map!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.4.0/lib/cocoapods-core/requirement.rb:88:in `initialize'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.4.0/lib/cocoapods-core/requirement.rb:34:in `new'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.4.0/lib/cocoapods-core/requirement.rb:34:in `create'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.4.0/lib/cocoapods-core/dependency.rb:116:in `initialize'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.4.0/lib/cocoapods-core/podfile/target_definition.rb:796:in `new'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.4.0/lib/cocoapods-core/podfile/target_definition.rb:796:in `block in pod_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.4.0/lib/cocoapods-core/podfile/target_definition.rb:792:in `map'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.4.0/lib/cocoapods-core/podfile/target_definition.rb:792:in `pod_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.4.0/lib/cocoapods-core/podfile/target_definition.rb:96:in `non_inherited_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.4.0/lib/cocoapods-core/podfile/target_definition.rb:74:in `dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/podfile_validator.rb:71:in `block in validate_pod_directives'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/podfile_validator.rb:70:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/podfile_validator.rb:70:in `flat_map'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/podfile_validator.rb:70:in `validate_pod_directives'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/podfile_validator.rb:34:in `validate'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/analyzer.rb:188:in `validate_podfile!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/analyzer.rb:71:in `analyze'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:243:in `analyze'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:154:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:153:in `resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:116:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/command/install.rb:41:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

**Comment by dnkoutso** [comment]
```
pod 'IOSLinkedInAPIFix', '~> 2.0'
```
