### ISSUE TITLE
NoMethodError - undefined method `new_variant_group' for #<Xcodeproj::Project::Object::PBXFileReference:0x00007fe8fe1dd460>

### ISSUE THREAD

**Issue by nverinaud** [CocoaPods/CocoaPods#7707]
🌈

### Command

```
~/.rbenv/versions/2.5.1/bin/pod install
```

### Report

* What did you do?

I ran `pod install` inside this repository : https://github.com/Ryfacto/IntentKit/tree/master/Example

* What did you expect to happen?

It should have installed the pods and create the `.xcworkspace`.

* What happened instead?

It failed with the error below.

### Stack

```
   CocoaPods : 1.5.0
        Ruby : ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
    RubyGems : 2.7.6
        Host : Mac OS X 10.13.4 (17E199)
       Xcode : 9.3 (9E145)
         Git : git version 2.11.0
Ruby lib dir : /Users/nico/.rbenv/versions/2.5.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 5dcc84652becfc6a3994a1bd68316590dd285a78
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
#plugin 'slather'

target :IntentKit do
  pod "MWLayoutHelpers"
  pod "IntentKit", :path => "../"
end

target :IntentKitTests do
    pod "Specta", "~> 0.2.1"
    pod "Expecta", "~> 0.2.3"
    pod "OCMockito", "~> 3.0"
end
```

### Error

```
NoMethodError - undefined method `new_variant_group' for #<Xcodeproj::Project::Object::PBXFileReference:0x00007fe8fe1dd460>
/Users/nico/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.0/lib/cocoapods/project.rb:375:in `group_for_path_in_group'
/Users/nico/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.0/lib/cocoapods/project.rb:210:in `add_file_reference'
/Users/nico/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.0/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:213:in `block (2 levels) in add_file_accessors_paths_to_pods_group'
/Users/nico/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.0/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:211:in `each'
/Users/nico/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.0/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:211:in `block in add_file_accessors_paths_to_pods_group'
/Users/nico/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.0/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:205:in `each'
/Users/nico/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.0/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:205:in `add_file_accessors_paths_to_pods_group'
/Users/nico/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.0/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:107:in `block in add_resources'
/Users/nico/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.0/lib/cocoapods/user_interface.rb:142:in `message'
/Users/nico/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.0/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:105:in `add_resources'
/Users/nico/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.0/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:42:in `install!'
/Users/nico/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.0/lib/cocoapods/installer/xcode/pods_project_generator.rb:163:in `install_file_references'
/Users/nico/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.0/lib/cocoapods/installer/xcode/pods_project_generator.rb:64:in `generate!'
/Users/nico/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.0/lib/cocoapods/installer.rb:184:in `block in generate_pods_project'
/Users/nico/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.0/lib/cocoapods/user_interface.rb:64:in `section'
/Users/nico/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.0/lib/cocoapods/installer.rb:183:in `generate_pods_project'
/Users/nico/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.0/lib/cocoapods/installer.rb:119:in `install!'
/Users/nico/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.0/lib/cocoapods/command/install.rb:41:in `run'
/Users/nico/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/nico/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.0/lib/cocoapods/command.rb:52:in `run'
/Users/nico/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.0/bin/pod:55:in `<top (required)>'
/Users/nico/.rbenv/versions/2.5.1/bin/pod:23:in `load'
/Users/nico/.rbenv/versions/2.5.1/bin/pod:23:in `<main>'

**Comment by dnkoutso** [comment]
@nverinaud can you provide a sample app please? I believe this is because you had an additional `Pods.xcodeproj` reference in your project but I am unable to diagnose with the the given info.

**Comment by dnkoutso** [comment]
Excellent thank you!

**Comment by dnkoutso** [comment]
@nverinaud definitely a bug. Appears to be on:
```ruby
ss.resources = 'IntentKit/IntentKit-Localizations.bundle'
```

Need to investigate further.

**Comment by nverinaud** [comment]
Okay, thanks for your help on this ! Do not hesitate if I can be of any help. 😉

**Comment by dnkoutso** [comment]
@nverinaud found it further but you might have a good workaround. The problem is that there are 2 `InfoPList.strings` localized files within that bundle.

Removing them (which they appear to be empty) does the trick.

**Comment by dnkoutso** [comment]
Actually removing `Localizable.strings` too...but thats dumb cause that is exactly what you need.

Definitely an issue in the library for handling these.

**Comment by dnkoutso** [comment]
Removing this line `'IntentKit' => 'IntentKit/{**/*.strings,Images/*.png}',` makes it work.

**Comment by nverinaud** [comment]
@dnkoutso  Thanks for your help, it is awesome ! 🎉
