### ISSUE TITLE
[1.5 swift] pod lib lint failed with '--use-libraries' param

### ISSUE THREAD

**Issue by 0x5e** [CocoaPods/CocoaPods#7738]
## Step to reproduce

1. Run `pod lib create TYTestLib`
2. Add a swift pod depedency in podspec: `s.dependency 'Alamofire'`
3. Run `pod lib lint --allow-warnings --use-libraries --verbose`

```
.....

    ** BUILD FAILED **


    The following build commands failed:
    	Ld /Users/admin/Library/Developer/Xcode/DerivedData/App-cbhtfphhmqekmebvaiewmnbdhvxq/Build/Intermediates.noindex/App.build/Release-iphonesimulator/App.build/Objects-normal/x86_64/App normal x86_64
    	Ld /Users/admin/Library/Developer/Xcode/DerivedData/App-cbhtfphhmqekmebvaiewmnbdhvxq/Build/Intermediates.noindex/App.build/Release-iphonesimulator/App.build/Objects-normal/i386/App normal i386
    	CreateUniversalBinary /Users/admin/Library/Developer/Xcode/DerivedData/App-cbhtfphhmqekmebvaiewmnbdhvxq/Build/Products/Release-iphonesimulator/App.app/App normal i386\ x86_64
    	GenerateDSYMFile /Users/admin/Library/Developer/Xcode/DerivedData/App-cbhtfphhmqekmebvaiewmnbdhvxq/Build/Products/Release-iphonesimulator/App.app.dSYM /Users/admin/Library/Developer/Xcode/DerivedData/App-cbhtfphhmqekmebvaiewmnbdhvxq/Build/Products/Release-iphonesimulator/App.app/App
    	CodeSign /Users/admin/Library/Developer/Xcode/DerivedData/App-cbhtfphhmqekmebvaiewmnbdhvxq/Build/Products/Release-iphonesimulator/App.app
    (5 failures)
   Testing with `xcodebuild`.
 -> TYTestLib (0.1.0)
    - WARN  | summary: The summary is not meaningful.
    - WARN  | url: The URL (https://github.com/0x5e/TYTestLib) is not reachable.
    - WARN  | [iOS] swift: The validator used Swift 3.2 by default because no Swift version was specified. To specify a Swift version during validation, add the `swift_version` attribute in your podspec. Note that usage of the `--swift-version` parameter or a `.swift-version` file is now deprecated.
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code.
    - NOTE  | xcodebuild:  ld: warning: Auto-Linking library not found for -lswiftCore
    - NOTE  | xcodebuild:  ld: warning: Auto-Linking library not found for -lswiftQuartzCore
    - NOTE  | xcodebuild:  ld: warning: Auto-Linking library not found for -lswiftCoreImage
    - NOTE  | xcodebuild:  ld: warning: Auto-Linking library not found for -lswiftCoreGraphics
    - NOTE  | xcodebuild:  ld: warning: Auto-Linking library not found for -lswiftDispatch
    - NOTE  | xcodebuild:  ld: warning: Auto-Linking library not found for -lswiftObjectiveC
    - NOTE  | xcodebuild:  ld: warning: Auto-Linking library not found for -lswiftCoreFoundation
    - NOTE  | xcodebuild:  ld: warning: Auto-Linking library not found for -lswiftUIKit
    - NOTE  | xcodebuild:  ld: warning: Auto-Linking library not found for -lswiftDarwin
    - NOTE  | xcodebuild:  ld: warning: Auto-Linking library not found for -lswiftMetal
    - NOTE  | xcodebuild:  ld: warning: Auto-Linking library not found for -lswiftFoundation
    - NOTE  | xcodebuild:  clang: error: linker command failed with exit code 1 (use -v to see invocation)
    - NOTE  | [iOS] xcodebuild:  fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: /Users/admin/Library/Developer/Xcode/DerivedData/App-cbhtfphhmqekmebvaiewmnbdhvxq/Build/Intermediates.noindex/App.build/Release-iphonesimulator/App.build/Objects-normal/i386/App (No such file or directory)
    - NOTE  | [iOS] xcodebuild:  error: cannot parse the debug map for "/Users/admin/Library/Developer/Xcode/DerivedData/App-cbhtfphhmqekmebvaiewmnbdhvxq/Build/Products/Release-iphonesimulator/App.app/App": No such file or directory

[!] TYTestLib did not pass validation, due to 1 error.
You can use the `--no-clean` option to inspect any issue.

/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.0/lib/cocoapods/command/lib/lint.rb:85:in `block in run'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.0/lib/cocoapods/command/lib/lint.rb:54:in `each'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.0/lib/cocoapods/command/lib/lint.rb:54:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.0/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

And `pod repo push ....` failed with same reason😥

**Comment by dnkoutso** [comment]
Please upload a sample app. We can't diagnose this easily with the provided information.

**Comment by 0x5e** [comment]
[TYTestLib.zip](https://github.com/CocoaPods/CocoaPods/files/1997346/TYTestLib.zip)
It's just an empty project

**Comment by jcbremond** [comment]
same problem here with a pure objc project...
reinstall cocoapod 1.4 --> build -> everything is working well ...

**Comment by 0x5e** [comment]
If my app(pure objc project) use this pod, I got the same error, but  if I add a empty swift file to the project, problem solved, this is magic😄
So I can only use this pod from git branch, can't push to our private spec

**Comment by dnkoutso** [comment]
Yes this is a bug.
