### ISSUE TITLE
CocoaPods -- TypeError - no implicit conversion of nil into String

### ISSUE THREAD

**Issue by Liberate99** [CocoaPods/CocoaPods#7739]
when i try to install AFNetworking by cocoaPods,i met this error.

### Podfile

```ruby
source 'https://github.com/AFNetworking/AFNetworking.git'
platform :ios, '11.0'
target 'imayuan' do
pod 'AFNetworking', '~> 3.1.0'
end
```

### Error

```
TypeError - no implicit conversion of nil into String
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-core-1.5.2/lib/cocoapods-core/specification.rb:594:in `initialize'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-core-1.5.2/lib/cocoapods-core/specification.rb:594:in `new'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-core-1.5.2/lib/cocoapods-core/specification.rb:594:in `from_file'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-core-1.5.2/lib/cocoapods-core/specification/set.rb:56:in `specification_name'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-core-1.5.2/lib/cocoapods-core/source.rb:274:in `search'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-core-1.5.2/lib/cocoapods-core/source/aggregate.rb:83:in `block in search'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-core-1.5.2/lib/cocoapods-core/source/aggregate.rb:83:in `select'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-core-1.5.2/lib/cocoapods-core/source/aggregate.rb:83:in `search'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/resolver.rb:428:in `create_set_from_sources'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/resolver.rb:398:in `find_cached_set'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/resolver.rb:372:in `specifications_for_dependency'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/resolver.rb:177:in `search_for'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/resolver.rb:288:in `block in sort_dependencies'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/resolver.rb:281:in `each'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/resolver.rb:281:in `sort_by'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/resolver.rb:281:in `sort_dependencies'
/usr/local/lib/ruby/gems/2.2.0/gems/molinillo-0.6.5/lib/molinillo/delegates/specification_provider.rb:53:in `block in sort_dependencies'
/usr/local/lib/ruby/gems/2.2.0/gems/molinillo-0.6.5/lib/molinillo/delegates/specification_provider.rb:70:in `with_no_such_dependency_error_handling'
/usr/local/lib/ruby/gems/2.2.0/gems/molinillo-0.6.5/lib/molinillo/delegates/specification_provider.rb:52:in `sort_dependencies'
/usr/local/lib/ruby/gems/2.2.0/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:288:in `initial_state'
/usr/local/lib/ruby/gems/2.2.0/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:210:in `start_resolution'
/usr/local/lib/ruby/gems/2.2.0/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:168:in `resolve'
/usr/local/lib/ruby/gems/2.2.0/gems/molinillo-0.6.5/lib/molinillo/resolver.rb:43:in `resolve'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/resolver.rb:123:in `resolve'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/analyzer.rb:781:in `block in resolve_dependencies'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/analyzer.rb:779:in `resolve_dependencies'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/analyzer.rb:88:in `analyze'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/installer.rb:243:in `analyze'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/installer.rb:154:in `block in resolve_dependencies'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/installer.rb:153:in `resolve_dependencies'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/installer.rb:116:in `install!'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/command/install.rb:41:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'

do anyone know how to solve it?

**Comment by dnkoutso** [comment]
This line `source 'https://github.com/AFNetworking/AFNetworking.git'` is wrong. This is supposed to be a CocoaPods specs repo not a repo for a library to use.
