### ISSUE TITLE
pod lib create  error

### ISSUE THREAD

**Issue by Wu-Dong-Hui** [CocoaPods/CocoaPods#7743]
* [ ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

pod lib create

## What did you expect to happen?

create a pod lib

## What happened instead?

/Users/wu/.rvm/gems/ruby-2.3.0/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object/helpers/build_settings_array_settings_by_object_version.rb:27:in `<module:BuildSettingsArraySettingsByObjectVersion>': undefined method `to_set' for #<Array:0x007fb8748fe808> (NoMethodError)
Did you mean?  to_s
	from /Users/wu/.rvm/gems/ruby-2.3.0/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object/helpers/build_settings_array_settings_by_object_version.rb:8:in `<class:XCBuildConfiguration>'
	from /Users/wu/.rvm/gems/ruby-2.3.0/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object/helpers/build_settings_array_settings_by_object_version.rb:4:in `<module:Object>'
	from /Users/wu/.rvm/gems/ruby-2.3.0/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object/helpers/build_settings_array_settings_by_object_version.rb:3:in `<class:Project>'
	from /Users/wu/.rvm/gems/ruby-2.3.0/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object/helpers/build_settings_array_settings_by_object_version.rb:2:in `<module:Xcodeproj>'
	from /Users/wu/.rvm/gems/ruby-2.3.0/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object/helpers/build_settings_array_settings_by_object_version.rb:1:in `<top (required)>'
	from /Users/wu/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/wu/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/wu/.rvm/gems/ruby-2.3.0/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object/build_configuration.rb:194:in `<top (required)>'
	from /Users/wu/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/wu/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/wu/.rvm/gems/ruby-2.3.0/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object.rb:521:in `<top (required)>'
	from /Users/wu/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/wu/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/wu/.rvm/gems/ruby-2.3.0/gems/xcodeproj-1.5.8/lib/xcodeproj/project.rb:5:in `<top (required)>'
	from /Users/wu/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/wu/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/wu/Desktop/wu/ZPRoute/ZP/ZPRoute/setup/ProjectManipulator.rb:30:in `run'
	from /Users/wu/Desktop/wu/ZPRoute/ZP/ZPRoute/setup/ConfigureiOS.rb:73:in `perform'
	from /Users/wu/Desktop/wu/ZPRoute/ZP/ZPRoute/setup/ConfigureiOS.rb:7:in `perform'
	from /Users/wu/Desktop/wu/ZPRoute/ZP/ZPRoute/setup/TemplateConfigurator.rb:85:in `run'
	from ./configure:9:in `<main>'

To learn more about the template see `https://github.com/CocoaPods/pod-template.git`.
To learn more about creating a new pod, see `http://guides.cocoapods.org/making/making-a-cocoapod`.

### Stack

```
   CocoaPods : 1.5.2
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin16]
    RubyGems : 2.6.11
        Host : Mac OS X 10.13.4 (17E199)
       Xcode : 9.3 (9E145)
         Git : git version 2.15.1 (Apple Git-101)
Ruby lib dir : /Users/wu/.rvm/rubies/ruby-2.3.0/lib
Repositories : aliyun - https://github.com/aliyun/aliyun-specs.git @ 5d9655a03ad9953e5b5e6e2bd7c93c32a4920b05
               master - https://github.com/CocoaPods/Specs.git @ ed0a4f7d8e3a9d20c0387b47a6ebacf3d3f52645
               PrivatePods - https://github.com/Wu-Dong-Hui/PrivatePodsSpecs.git @ 221aa7da6f5cc5968dbb34296bb36a197438bf73
               PrivatePodsSpecs - https://github.com/Wu-Dong-Hui/PrivatePodsSpecs.git @ 221aa7da6f5cc5968dbb34296bb36a197438bf73
               zhaopin-mobile-ios-common-index - http://gitlab.dev.zhaopin.com/Mobile/ios-common-index.git @ ba99b94203e8d116cb8f993295f65bf8075d27bb
```

### Installation Source

```
Executable Path: /Users/wu/.rvm/gems/ruby-2.3.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-packager    : 1.5.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

**Comment by amorde** [comment]
I think this is fixed in https://github.com/CocoaPods/Xcodeproj/pull/573
