### ISSUE TITLE
Cocoapods 1.5.2 crashes with rome plugin

### ISSUE THREAD

**Issue by jugutier** [CocoaPods/CocoaPods#7757]
### Report

* What did you do?
run `pod install` on an empty folder with just this Podfile

```
platform :ios, '8.0'

plugin 'cocoapods-rome'

target 'caesar' do
  pod 'Alamofire'
end

```

* What did you expect to happen?

To get an output folder with the compiled `Alamofire` framework

* What happened instead?

Got an error.

### Command

```
/Users/julian/.rbenv/versions/2.0.0/bin/pod install
```

### Stack

```
   CocoaPods : 1.5.2
        Ruby : ruby 2.0.0p647 (2015-08-18 revision 51631) [x86_64-darwin16.6.0]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.6 (16G1212)
       Xcode : 9.2 (9C40b)
         Git : git version 2.14.3 (Apple Git-98)
Ruby lib dir : /Users/julian/.rbenv/versions/2.0.0-p647/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 422a260e27e8636972adf4eeace58f53f26a031f
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-rome        : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '8.0'

plugin 'cocoapods-rome'

target 'caesar' do
  pod 'Alamofire'
end
```

### Error

```
NoMethodError - undefined method `build_settings' for nil:NilClass
/Users/julian/.rbenv/versions/2.0.0-p647/lib/ruby/gems/2.0.0/gems/cocoapods-rome-1.0.0/lib/cocoapods-rome/post_install.rb:44:in `block in enable_debug_information'
/Users/julian/.rbenv/versions/2.0.0-p647/lib/ruby/gems/2.0.0/gems/cocoapods-rome-1.0.0/lib/cocoapods-rome/post_install.rb:42:in `each'
/Users/julian/.rbenv/versions/2.0.0-p647/lib/ruby/gems/2.0.0/gems/cocoapods-rome-1.0.0/lib/cocoapods-rome/post_install.rb:42:in `enable_debug_information'
/Users/julian/.rbenv/versions/2.0.0-p647/lib/ruby/gems/2.0.0/gems/cocoapods-rome-1.0.0/lib/cocoapods-rome/post_install.rb:73:in `block in <top (required)>'
/Users/julian/.rbenv/versions/2.0.0-p647/lib/ruby/gems/2.0.0/gems/cocoapods-1.5.2/lib/cocoapods/hooks_manager.rb:109:in `call'
/Users/julian/.rbenv/versions/2.0.0-p647/lib/ruby/gems/2.0.0/gems/cocoapods-1.5.2/lib/cocoapods/hooks_manager.rb:109:in `block (3 levels) in run'
/Users/julian/.rbenv/versions/2.0.0-p647/lib/ruby/gems/2.0.0/gems/cocoapods-1.5.2/lib/cocoapods/user_interface.rb:142:in `message'
/Users/julian/.rbenv/versions/2.0.0-p647/lib/ruby/gems/2.0.0/gems/cocoapods-1.5.2/lib/cocoapods/hooks_manager.rb:103:in `block (2 levels) in run'
/Users/julian/.rbenv/versions/2.0.0-p647/lib/ruby/gems/2.0.0/gems/cocoapods-1.5.2/lib/cocoapods/hooks_manager.rb:101:in `each'
/Users/julian/.rbenv/versions/2.0.0-p647/lib/ruby/gems/2.0.0/gems/cocoapods-1.5.2/lib/cocoapods/hooks_manager.rb:101:in `block in run'
/Users/julian/.rbenv/versions/2.0.0-p647/lib/ruby/gems/2.0.0/gems/cocoapods-1.5.2/lib/cocoapods/user_interface.rb:142:in `message'
/Users/julian/.rbenv/versions/2.0.0-p647/lib/ruby/gems/2.0.0/gems/cocoapods-1.5.2/lib/cocoapods/hooks_manager.rb:100:in `run'
/Users/julian/.rbenv/versions/2.0.0-p647/lib/ruby/gems/2.0.0/gems/cocoapods-1.5.2/lib/cocoapods/installer.rb:455:in `run_plugins_post_install_hooks'
/Users/julian/.rbenv/versions/2.0.0-p647/lib/ruby/gems/2.0.0/gems/cocoapods-1.5.2/lib/cocoapods/installer.rb:433:in `perform_post_install_actions'
/Users/julian/.rbenv/versions/2.0.0-p647/lib/ruby/gems/2.0.0/gems/cocoapods-1.5.2/lib/cocoapods/installer.rb:125:in `install!'
/Users/julian/.rbenv/versions/2.0.0-p647/lib/ruby/gems/2.0.0/gems/cocoapods-1.5.2/lib/cocoapods/command/install.rb:41:in `run'
/Users/julian/.rbenv/versions/2.0.0-p647/lib/ruby/gems/2.0.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/julian/.rbenv/versions/2.0.0-p647/lib/ruby/gems/2.0.0/gems/cocoapods-1.5.2/lib/cocoapods/command.rb:52:in `run'
/Users/julian/.rbenv/versions/2.0.0-p647/lib/ruby/gems/2.0.0/gems/cocoapods-1.5.2/bin/pod:55:in `<top (required)>'
/Users/julian/.rbenv/versions/2.0.0/bin/pod:23:in `load'
/Users/julian/.rbenv/versions/2.0.0/bin/pod:23:in `<main>'
```

**Comment by dnkoutso** [comment]
@jugutier I am sorry but I think this issue should actually be filed on the https://github.com/CocoaPods/Rome repo

**Comment by jugutier** [comment]
yeah that makes sense, sorry I wasn't sure where to put it.

**Comment by jugutier** [comment]
maybe a try/catch on `cocoapods/hooks_manager.rb:109:in `call'` with some message would be in order for plugins to not crash cocoapods?

**Comment by dnkoutso** [comment]
no problem. If possible please file there. I am going to close this one.

**Comment by dnkoutso** [comment]
hm interesting, we kind of want to leverage those crashes

**Comment by jugutier** [comment]
@dnkoutso If you don't think that is necessary then let's just close it. I don't think we want to hide the error just make it more clear that it's coming from a plugin so that users like me know where to file their issue haha

This may be not necessary if plugins are not so widely used 

Just filed here https://github.com/CocoaPods/Rome/issues/67

**Comment by orta** [comment]
I guess we could parse the stack trace and see if the top line is a cocoapods gem?

**Comment by jugutier** [comment]
Something like this around the block calls? with a nice banner saying "Plugin interrupted execution" or similar

https://gist.github.com/mikepfirrmann/3820663

**Comment by dnkoutso** [comment]
for now keeping open and marking it as a discussion and potential enhancement.
