### ISSUE TITLE
pod update run error

### ISSUE THREAD

**Issue by fightingForYou** [CocoaPods/CocoaPods#7772]
### Command

```
/usr/local/bin/pod update
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.5.2
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    RubyGems : 2.6.13
        Host : Mac OS X 10.13.4 (17E199)
       Xcode : 9.3 (9E145)
         Git : git version 2.8.1
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : something's private
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
#三方库静态库
source "private.podspec"
inhibit_all_warnings!

platform :ios, '8.0'

target 'MGJShoppingGuide_Example' do
    pod 'MGJShoppingGuide', :path => '../', :inhibit_warnings => false
    #第三方 工具
    pod 'FDStackView'
    pod 'MLeaksFinder'
    pod 'FBMemoryProfiler'

    target 'MGJShoppingGuide_ExampleTests' do
        inherit! :search_paths
    end
end

install! 'cocoapods', :deterministic_uuids => false

post_install do |installer|
    cmd="
    dir=\"`pwd`/Pods/Headers/Public\"
    cd $dir
    for pod in `ls -1`
    do
        cd $pod
        inner=`ls -1`
        if [ \"$pod\" == \"$inner\" ]
        then
            mv $inner/* ./
            rm -rf $inner
            for file in `ls -1`
            do
                followPath=`ls -l \"$file\" | awk -F ' ../' '{print $2}'`
                ln -fs \"$followPath\" \"$file\"
            done
        fi
        cd $dir
    done
    "
    system(cmd)
end
```

### Error

```
ArgumentError - Illformed requirement `"MGJUIComponent/Tips"`
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.5.2/lib/cocoapods-core/requirement.rb:63:in `parse'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.5.2/lib/cocoapods-core/requirement.rb:88:in `block in initialize'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.5.2/lib/cocoapods-core/requirement.rb:88:in `map!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.5.2/lib/cocoapods-core/requirement.rb:88:in `initialize'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.5.2/lib/cocoapods-core/requirement.rb:34:in `new'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.5.2/lib/cocoapods-core/requirement.rb:34:in `create'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.5.2/lib/cocoapods-core/dependency.rb:115:in `initialize'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.5.2/lib/cocoapods-core/specification/consumer.rb:210:in `new'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.5.2/lib/cocoapods-core/specification/consumer.rb:210:in `block in dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.5.2/lib/cocoapods-core/specification/consumer.rb:209:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.5.2/lib/cocoapods-core/specification/consumer.rb:209:in `map'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.5.2/lib/cocoapods-core/specification/consumer.rb:209:in `dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.5.2/lib/cocoapods-core/specification.rb:336:in `block in dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.5.2/lib/cocoapods-core/specification.rb:335:in `map'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.5.2/lib/cocoapods-core/specification.rb:335:in `dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.5.2/lib/cocoapods-core/specification.rb:344:in `all_dependencies'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/delegate.rb:341:in `block in delegating_block'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/resolver.rb:190:in `dependencies_for'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.5/lib/molinillo/delegates/specification_provider.rb:18:in `block in dependencies_for'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.5/lib/molinillo/delegates/specification_provider.rb:70:in `with_no_such_dependency_error_handling'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.5/lib/molinillo/delegates/specification_provider.rb:17:in `dependencies_for'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:807:in `block in group_possibilities'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:806:in `reverse_each'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:806:in `group_possibilities'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:778:in `possibilities_for_requirement'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:761:in `push_state_for_requirements'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:746:in `require_nested_dependencies_for'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:729:in `activate_new_spec'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:686:in `attempt_to_activate'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:254:in `process_topmost_state'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:182:in `resolve'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.5/lib/molinillo/resolver.rb:43:in `resolve'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/resolver.rb:123:in `resolve'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/analyzer.rb:781:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/analyzer.rb:779:in `resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/analyzer.rb:88:in `analyze'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/installer.rb:243:in `analyze'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/installer.rb:154:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/installer.rb:153:in `resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/installer.rb:116:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/command/update.rb:97:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by dnkoutso** [comment]
Please provide a sample app demonstrating the issue.

Most likely a problem with the `MGJUIComponent` podspec. Is this a private pod or a public one?
