### ISSUE TITLE
"pod update" fails with "ArgumentError - comparison of Pod::Version with Gem::Version failed"

### ISSUE THREAD

**Issue by andrewcar** [CocoaPods/CocoaPods#7774]
### Command

```
/usr/local/bin/pod update
```

### Report

* What did you do?
Ran 'pod update'

* What did you expect to happen?
I expected Cocoapods to update all of my dependencies.

* What happened instead?
I got an error saying 'ArgumentError - comparison of Pod::Version with Gem::Version failed'

### Stack

```
   CocoaPods : 1.5.2
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    RubyGems : 2.0.3
        Host : Mac OS X 10.13.5 (17F66a)
       Xcode : 9.3.1 (9E501)
         Git : git version 2.10.1
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ cd8a7373395a2105cf17073fc2e7a64a2bf8110e
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
target 'hoods' do

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

use_frameworks!

pod 'Mapbox-iOS-SDK', '~> 4.0'
pod 'FoursquareAPIClient', '~> 4.0'
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Storage'
pod 'Firebase/Database'
pod 'Firebase/Firestore'
pod 'mailcore2-ios'
pod 'Spotify-iOS-SDK'
pod 'Alamofire', '~> 4.7'
pod 'UIImageColors'

end
```

### Error

```
ArgumentError - comparison of Pod::Version with Gem::Version failed
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/sources_manager.rb:136:in `>'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/sources_manager.rb:136:in `verify_compatibility!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/sources_manager.rb:90:in `block (2 levels) in update'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/sources_manager.rb:87:in `block in update'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/sources_manager.rb:86:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/sources_manager.rb:86:in `update'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/analyzer.rb:252:in `block in update_repositories'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/analyzer.rb:250:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/analyzer.rb:250:in `update_repositories'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/installer.rb:150:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/installer.rb:149:in `resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/installer.rb:116:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/command/update.rb:97:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

* [X ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

**Comment by dnkoutso** [comment]
Seems like a dup of https://github.com/CocoaPods/CocoaPods/issues/7765 and fixed here https://github.com/CocoaPods/CocoaPods/pull/7769

@andrewcar I am going to pre-emptively close but if you think this is a different issue I will re-open this!

**Comment by dnkoutso** [comment]
I take it back, not sure if its the same issue.

**Comment by dnkoutso** [comment]
Need a sample here.

**Comment by andrewcar** [comment]
It's a commercial app so I won't be able to, unfortunately.

**Comment by dnkoutso** [comment]
@andrewcar best I can provide is to try using master using https://bundler.io/v1.12/git.html. We just merged a fix there that could be the same issue here.

**Comment by dnkoutso** [comment]
Hoping it works for you and its the same issue!

**Comment by emelelias** [comment]
hi

**Comment by emelelias** [comment]
Issue exists 1.6.1 cocoapods
