### ISSUE TITLE
URI::InvalidURIError - bad URI(is not URI?)

### ISSUE THREAD

**Issue by Whirlwind** [CocoaPods/CocoaPods#7790]
```
URI::InvalidURIError - bad URI(is not URI?): git@code.byted.org:ugc/OpenCV.git
/Users/whirlwind/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/uri/rfc3986_parser.rb:67:in `split'
/Users/whirlwind/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/uri/rfc3986_parser.rb:73:in `parse'
/Users/whirlwind/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/uri/common.rb:231:in `parse'
/Users/whirlwind/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/uri/common.rb:737:in `URI'
/Users/whirlwind/Documents/Developer/CocoaPods/CocoaPods/lib/cocoapods/installer/pod_source_installer.rb:126:in `verify_source_is_secure'
/Users/whirlwind/Documents/Developer/CocoaPods/CocoaPods/lib/cocoapods/installer/pod_source_installer.rb:107:in `download_source'
/Users/whirlwind/Documents/Developer/CocoaPods/CocoaPods/lib/cocoapods/installer/pod_source_installer.rb:62:in `install!'
/Users/whirlwind/Documents/Developer/CocoaPods/CocoaPods/lib/cocoapods/installer.rb:367:in `install_source_of_pod'
/Users/whirlwind/Documents/Developer/CocoaPods/CocoaPods/lib/cocoapods/installer.rb:332:in `block (2 levels) in install_pod_sources'
/Users/whirlwind/Documents/Developer/CocoaPods/CocoaPods/lib/cocoapods/user_interface.rb:86:in `titled_section'
/Users/whirlwind/Documents/Developer/CocoaPods/CocoaPods/lib/cocoapods/installer.rb:331:in `block in install_pod_sources'
/Users/whirlwind/Documents/Developer/CocoaPods/CocoaPods/lib/cocoapods/installer.rb:314:in `each'
/Users/whirlwind/Documents/Developer/CocoaPods/CocoaPods/lib/cocoapods/installer.rb:314:in `install_pod_sources'
/Users/whirlwind/Documents/Developer/CocoaPods/CocoaPods/lib/cocoapods/installer.rb:163:in `block in download_dependencies'
/Users/whirlwind/Documents/Developer/CocoaPods/CocoaPods/lib/cocoapods/user_interface.rb:64:in `section'
/Users/whirlwind/Documents/Developer/CocoaPods/CocoaPods/lib/cocoapods/installer.rb:162:in `download_dependencies'
/Users/whirlwind/Documents/Developer/CocoaPods/CocoaPods/lib/cocoapods/installer.rb:117:in `install!'
/Users/whirlwind/Documents/Developer/CocoaPods/CocoaPods/lib/cocoapods/command/update.rb:97:in `run'
/Users/whirlwind/.rvm/gems/ruby-2.4.1/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/whirlwind/Documents/Developer/CocoaPods/CocoaPods/lib/cocoapods/command.rb:52:in `run'
```

I check the source code : 
```
      def verify_source_is_secure(root_spec)
        return if root_spec.source.nil? || (root_spec.source[:http].nil? && root_spec.source[:git].nil?)
        source = if !root_spec.source[:http].nil?
                   URI(root_spec.source[:http].to_s)
                 elsif !root_spec.source[:git].nil?
                   URI(root_spec.source[:git].to_s)
                 end
        if UNENCRYPTED_PROTOCOLS.include?(source.scheme)
          UI.warn "'#{root_spec.name}' uses the unencrypted '#{source.scheme}' protocol to transfer the Pod. " \
                'Please be sure you\'re in a safe network with only trusted hosts. ' \
                'Otherwise, please reach out to the library author to notify them of this security issue.'
        end
      end
```
The `URI(root_spec.source[:git].to_s)` not works for `git@code.byted.org:ugc/OpenCV.git`:
```
❯ irb
2.4.1 :001 > URI
NameError: uninitialized constant URI
	from (irb):1
	from /Users/whirlwind/.rvm/rubies/ruby-2.4.1/bin/irb:11:in `<main>'
2.4.1 :002 > require 'uri'
 => true
2.4.1 :003 > URI
 => URI
2.4.1 :004 > URI('git@code.byted.org:ugc/OpenCV.git')
URI::InvalidURIError: bad URI(is not URI?): git@code.byted.org:ugc/OpenCV.git
	from /Users/whirlwind/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/uri/rfc3986_parser.rb:67:in `split'
	from /Users/whirlwind/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/uri/rfc3986_parser.rb:73:in `parse'
	from /Users/whirlwind/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/uri/common.rb:231:in `parse'
	from /Users/whirlwind/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/uri/common.rb:737:in `URI'
	from (irb):4
	from /Users/whirlwind/.rvm/rubies/ruby-2.4.1/bin/irb:11:in `<main>'
```

**Comment by dnkoutso** [comment]
yes, it seems like you are using 1.6.0 (master) which is not yet released. What is the podspec?

**Comment by Whirlwind** [comment]
The podspec is simple:
```
Pod::Spec.new do |s|
  s.name         = "AIOpenCV"
  s.version      = "3.2.0"
  s.license      = {
  :type => 'Proprietary',
  :text => <<-LICENSE
  OpenCV. All Rights Reserved.
  LICENSE
  }
  s.homepage     = 'https://code.byted.org/ugc/OpenCV'
  s.authors      = 'opencv.org'
  s.summary      = 'OpenCV (Computer Vision) for iOS..'
  s.description  = <<-DESC
  * OpenCV: open source computer vision library.
  DESC

  s.frameworks   = 'Accelerate','AssetsLibrary','AVFoundation','CoreGraphics','CoreImage','CoreMedia','CoreVideo','Foundation','QuartzCore','UIKit'
  s.source       = { :git => "git@code.byted.org:ugc/OpenCV.git", :tag => s.version.to_s }
  s.platform     = :ios, '7.0'
  s.requires_arc = true
  s.preserve_paths      = 'opencv2.framework'
  s.public_header_files = 'opencv2.framework//Versions/A/Headers/**/*{.h,.hpp}'
  s.vendored_frameworks = 'opencv2.framework'
  s.libraries = 'stdc++'
end
```

**Comment by dnkoutso** [comment]
Do you own the podspec? Do you also consume this pod remotely or via `:path`?

**Comment by dnkoutso** [comment]
Will re-apply this but for this repo https://github.com/CocoaPods/Core/pull/84
