### ISSUE TITLE
[pod lib lint error]  error: None of the input catalogs contained a matching stickers icon set or app icon set named  "AppIcon".

### ISSUE THREAD

**Issue by jueying-xiangfeng** [CocoaPods/CocoaPods#7791]
- NOTE  | [iOS] xcodebuild:  : error: None of the input catalogs contained a matching stickers icon set or app icon set named  "AppIcon".
    - NOTE  | [iOS] xcodebuild:  ToonKit/ToonKit/ToonKit.xcassets:./tn_navi_baritem_mark.imageset: warning: The image set name "tn_navi_baritem_mark" is used by multiple image sets.

**Comment by dnkoutso** [comment]
Would like a sample app for this and please in fill in the issue template. Its very difficult to diagnose and debug issues with the given information.

**Comment by jueying-xiangfeng** [comment]
How do you do，I use this command to check: pod lib lint - sources = 'http:// XXXX, https://github.com/CocoaPods/Specs.git - use - libraries - allow - warnings。
The error message appears：
`    - NOTE  | [iOS] xcodebuild:  : error: None of the input catalogs contained a matching stickers icon set or app icon set named  "AppIcon".`
`[!] TNBluetooth did not pass validation, due to 2 errors.`

This information also appears at the end：
`/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command/lib/lint.rb:85:in `block in run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command/lib/lint.rb:54:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command/lib/lint.rb:54:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'`

I'm trying to execute：
`sudo rm -fr ~/.cocoapods/repos/master
pod setup`
8/5000  
But the results were wrong。

**Comment by dnkoutso** [comment]
Sorry please upload a sample that shows the problem. I cant figure this out from this information.
