### ISSUE TITLE
Couldn't install Pods - Nanaimo::Reader::ParseError - [!] Dictionary missing 

### ISSUE THREAD

**Issue by tsoutotw** [CocoaPods/CocoaPods#7846]
### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    RubyGems : 2.5.2
        Host : Mac OS X 10.13.5 (17F77)
       Xcode : 9.4 (9F1027a)
         Git : git version 2.15.1 (Apple Git-101)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : 
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target ‘Projeto’ do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for Projeto
    pod 'Alamofire', '~> 4.7'
    pod 'RealmSwift', '~> 3.0' 
    pod 'Firebase/Core', '~> 5.2.0'
    pod 'Firebase/Messaging', '~> 5.2.0'
    pod 'Firebase/Auth', '~> 5.2.0'
    
    target 'ProjetoTests’ do
        inherit! :search_paths
        pod 'Quick', '~> 1.2.0'
        pod 'Nimble', '~> 7.0.3'
    end
    
    target 'ProjetoUITests' do
        #inherit! :search_paths
        pod 'Quick', '~> 1.2.0'
        pod 'Nimble', '~> 7.0.3'
    end
    
    target 'ProjetoSnapshotTests' do
        inherit! :search_paths
        pod 'iOSSnapshotTestCase', '~> 2.2.0'
    end
end
```

### Error

```
Nanaimo::Reader::ParseError - [!] Dictionary missing ';' after key-value pair for "BC7C66BFBBF635C10AA1704C", found ""
    #  -------------------------------------------
    #  	rootObject = F2D43DD5206987FF000A922B /* Project object */;
    #  }
1294>  
       ^
    #  -------------------------------------------

/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.5/lib/nanaimo/reader.rb:283:in `raise_parser_error'
/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.5/lib/nanaimo/reader.rb:199:in `parse_dictionary'
/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.5/lib/nanaimo/reader.rb:132:in `parse_object'
/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.5/lib/nanaimo/reader.rb:193:in `parse_dictionary'
/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.5/lib/nanaimo/reader.rb:132:in `parse_object'
/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.5/lib/nanaimo/reader.rb:193:in `parse_dictionary'
/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.5/lib/nanaimo/reader.rb:132:in `parse_object'
/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.5/lib/nanaimo/reader.rb:193:in `parse_dictionary'
/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.5/lib/nanaimo/reader.rb:132:in `parse_object'
/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.5/lib/nanaimo/reader.rb:107:in `parse!'
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.7/lib/xcodeproj/plist.rb:27:in `read_from_path'
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project.rb:201:in `initialize_from_file'
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project.rb:103:in `open'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:918:in `block (2 levels) in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:917:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:917:in `block in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:912:in `inspect_targets_to_integrate'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:78:in `analyze'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:243:in `analyze'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:154:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:153:in `resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:116:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command/install.rb:41:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

**Comment by dnkoutso** [comment]
Probably a bad project value, we will need a sample project showing the issue to debug this.
