### ISSUE TITLE
add thrid part lib to my project which is sub of multi projects 

### ISSUE THREAD

**Issue by jimUpdate** [CocoaPods/CocoaPods#7847]
### Command

```
/Users/zhouzhoujie/.rbenv/versions/2.1.0/bin/pod install
```

### Report

* What did you do?

pod 'MGJRouter' to 'Router' which is a sub  project of the workspace

* What did you expect to happen?

it is ok

* What happened instead?

it is crash when I do 'pod install'

### Stack

```
   CocoaPods : 1.4.0.beta.1
        Ruby : ruby 2.1.0p0 (2013-12-25 revision 44422) [x86_64-darwin16.0]
    RubyGems : 2.6.13
        Host : Mac OS X 10.13.4 (17E202)
       Xcode : 9.4.1 (9F2000)
         Git : git version 2.15.2 (Apple Git-101.1)
Ruby lib dir : /Users/zhouzhoujie/.rbenv/versions/2.1.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ fd0883f67ebe63760e8fef101f7290ee719950b6
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project

platform:ios, '10.0'
use_frameworks!
inhibit_all_warnings!#忽略警告

def common_pods
    pod 'Moya/RxSwift','8.0.5'
    pod 'RxSwift', '3.6.1'
    pod 'RxCocoa', '3.6.1'
    pod 'SwiftyJSON', '3.1.4'
    pod 'Toaster', '2.0.4'#吐司
    pod 'SnapKit', '3.2.0'#代码添加约束
    pod 'MJRefresh', '3.1.15'
    pod 'HGPlaceholders', '0.2.3'
    pod 'Kingfisher', '4.3.0'#加载图片
    pod 'HTMLString', '3.0.0'#富文本处理工具
    
    pod 'JRDB', '2.1.1'#数据库
    pod 'SwipeMenuViewController', '2.0.2'#tab切换
    pod 'FSCalendar', '2.7.9'#值班日历
    pod 'SwiftEventBus', '2.1.2'
    pod 'SVProgressHUD', '2.2.5'#弹窗
    pod 'NextGrowingTextView', '1.1.0'#多文本输入
    pod 'SLExpandableTableView', '1.3.1'#可折叠的UItableView
    pod 'TZImagePickerController', '1.9.6'#图片选择框架
    pod 'SearchEmojiOnString', '~> 1.0'#表情校验[不固定版本,因为需要包含尽可能多的表情]
    pod 'IQKeyboardManagerSwift', '5.0.8'
    
    pod 'Bugly'#bugly异常上报
    
end

target 'ipms_xinxike' do
    common_pods
end

target 'Router' do
    project "Modules/Router/Router"
    pod 'MGJRouter', '~>0.9.0'
end

target 'WordPress' do
    project "Modules/WordPress/WordPress"
    pod 'CocoaLumberjack'
    pod 'CocoaLumberjack/Swift'#Log收集器用于平时debug
    pod 'NSObject-SafeExpectations','0.0.2'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
            config.build_settings['ARCHS'] = 'i386 x86_64 arm7s arm7 arm64'
        end
    end
end
```

### Error

```
RuntimeError - [Xcodeproj] Unknown object version.
/Users/zhouzhoujie/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/xcodeproj-1.5.2/lib/xcodeproj/project.rb:217:in `initialize_from_file'
/Users/zhouzhoujie/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/xcodeproj-1.5.2/lib/xcodeproj/project.rb:102:in `open'
/Users/zhouzhoujie/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/cocoapods-1.4.0.beta.1/lib/cocoapods/installer/analyzer.rb:907:in `block (2 levels) in inspect_targets_to_integrate'
/Users/zhouzhoujie/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/cocoapods-1.4.0.beta.1/lib/cocoapods/installer/analyzer.rb:906:in `each'
/Users/zhouzhoujie/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/cocoapods-1.4.0.beta.1/lib/cocoapods/installer/analyzer.rb:906:in `block in inspect_targets_to_integrate'
/Users/zhouzhoujie/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/cocoapods-1.4.0.beta.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/zhouzhoujie/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/cocoapods-1.4.0.beta.1/lib/cocoapods/installer/analyzer.rb:901:in `inspect_targets_to_integrate'
/Users/zhouzhoujie/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/cocoapods-1.4.0.beta.1/lib/cocoapods/installer/analyzer.rb:75:in `analyze'
/Users/zhouzhoujie/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/cocoapods-1.4.0.beta.1/lib/cocoapods/installer.rb:243:in `analyze'
/Users/zhouzhoujie/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/cocoapods-1.4.0.beta.1/lib/cocoapods/installer.rb:154:in `block in resolve_dependencies'
/Users/zhouzhoujie/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/cocoapods-1.4.0.beta.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/zhouzhoujie/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/cocoapods-1.4.0.beta.1/lib/cocoapods/installer.rb:153:in `resolve_dependencies'
/Users/zhouzhoujie/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/cocoapods-1.4.0.beta.1/lib/cocoapods/installer.rb:116:in `install!'
/Users/zhouzhoujie/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/cocoapods-1.4.0.beta.1/lib/cocoapods/command/install.rb:41:in `run'
/Users/zhouzhoujie/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/zhouzhoujie/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/cocoapods-1.4.0.beta.1/lib/cocoapods/command.rb:52:in `run'
/Users/zhouzhoujie/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/cocoapods-1.4.0.beta.1/bin/pod:55:in `<top (required)>'
/Users/zhouzhoujie/.rbenv/versions/2.1.0/bin/pod:23:in `load'
/Users/zhouzhoujie/.rbenv/versions/2.1.0/bin/pod:23:in `<main>'
```

**Comment by jimUpdate** [comment]
I just find the 解决方案 #7697  @YouZoudeFish 非常 3Q

**Comment by dnkoutso** [comment]
Please update `xcodeproj` gem. `gem update xcodeproj` to 1.5.9.

Going to preemptively close and re-open if the issue persists and its an actual cocoapods bug.
