### ISSUE TITLE
LoadError - cannot load such file -- macho

### ISSUE THREAD

**Issue by chutianfan** [CocoaPods/CocoaPods#7864]
Analyzing dependencies
Downloading dependencies
Installing AFNetworking (3.1.0)
Installing AXNavigationBackItemInjection (0.0.2)
Installing AXWebViewController (0.4.8)
Installing AgoraRtcEngine_iOS (2.0.2)
Installing Aspects (1.4.1)
Installing BHInfiniteScrollView (1.5.3)
Installing CYLTableViewPlaceHolder (1.0.8)
Installing CocoaLumberjack (3.2.1)
Installing DACircularProgress (2.3.1)
Installing FFToast (1.2.0)
Installing FMDB (2.6.2)
Installing FlyImage (1.1)
Installing HXWeiboPhotoPicker (2.1.5)
Installing HexColors (2.2.1)
Installing IQKeyboardManager (4.0.13)
Installing LPActionSheet (1.0)
Installing MBProgressHUD (1.0.0)
Installing MJExtension (3.0.15)
Installing MJRefresh (3.1.15.3)
Installing Masonry (1.0.2)
Installing NIMSDK (3.7.0)
Installing NJKWebViewProgress (0.2.3)
Installing Onboard (2.3.3)
Installing Pgyer (2.8.9)
Installing PushNotificationManager (1.0.3)
Installing Reachability (3.2)
Installing SDWebImage (4.2.3)
Installing SVProgressHUD (2.1.2)
Installing SocketRocket (0.5.1)
Installing TSMessages (0.9.12)
Installing TTTAttributedLabel (2.0.0)
Installing UMengAnalytics-NO-IDFA (4.2.5)
Installing YYKit (1.0.9)
Installing ZYCornerRadius (1.0.2)
Installing iOS7Colors (2.1.0)
Generating Pods project

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/Seven/.rvm/gems/ruby-2.2.4/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin15]
    RubyGems : 2.6.14
        Host : Mac OS X 10.13.4 (17E202)
       Xcode : 9.4 (9F1027a)
         Git : git version 2.15.1 (Apple Git-101)
Ruby lib dir : /Users/Seven/.rvm/rubies/ruby-2.2.4/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 94953ba8d8e279d9dc58f82772434f7813b2161f
               tianleios - https://github.com/tianleios/CDSpecs.git @ 7118001de34cd8907dd92a1a2717af62776718a4
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project

platform :ios, '9.0'

#https://github.com/XQBoy/MasonryExercise
target 'IMMOfSNS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for IMMOfSNS
  
  
  #pod 'ReactiveCocoa', '~> 5.0.0'
  #pod 'JSONKit', '~> 1.5pre'



#业务组件
#开机导航
pod 'Onboard','~> 2.3.3'

#Banner  https://github.com/qylibohao/BHInfiniteScrollView
pod 'BHInfiniteScrollView'

#UMeng
pod 'UMengAnalytics-NO-IDFA', '~> 4.2.5'
pod 'Pgyer', '~> 2.8.9'

#APP卡顿问题检测
#pod 'KMCGeigerCounter', '~> 0.2.2'


#组件
#pod 'AsyncDisplayKit', '~> 2.2'
pod 'iOS7Colors', '~> 2.1.0'
pod 'TSMessages', '~> 0.9.12'


#YYKit
pod 'YYKit', '~> 1.0.9'
pod 'TTTAttributedLabel', '~> 2.0.0'


#Masonry
pod 'Masonry', '~> 1.0.2'

pod 'PushNotificationManager', '~> 1.0.3'

#自动计算高度
#pod 'UITableView+FDTemplateLayoutCell', '~> 1.5.beta'


#网络
pod 'AFNetworking', '~> 3.1.0'
pod 'Reachability', '~> 3.2'

#WebSocket
pod 'SocketRocket', '~> 0.5.1'

#数据库
pod 'FMDB', '~> 2.6.2'


#进度指示
pod 'SVProgressHUD', '~> 2.1.2'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'DACircularProgress', '~> 2.3.1'
pod 'FFToast', '~> 1.2.0'
#pod 'MBProgressHUD+JDragon'

pod 'HXWeiboPhotoPicker', '~> 2.1.5'

#图片
pod 'SDWebImage', '~> 4.2.3'
pod 'ZYCornerRadius', '~> 1.0.2'
pod 'FlyImage', '~> 1.1'
pod 'AXWebViewController', '~> 0.4.8'


#下拉刷新
pod 'MJRefresh', '~> 3.1.15.3'
pod 'MJExtension', '~> 3.0.15'


pod 'LPActionSheet', '~> 1.0'


pod 'CocoaLumberjack', '~> 3.2.1'


#空视图补充
#pod 'DZNEmptyDataSet'
pod 'CYLTableViewPlaceHolder', '~> 1.0.8'
#键盘管理
pod 'IQKeyboardManager', '~> 4.0.13'
#pod 'XHInputView', '~> 1.0.2'

pod 'NIMSDK', '~> 3.7.0'
#pod 'QMUIKit'
pod 'AgoraRtcEngine_iOS', '~> 2.0.2'


  target 'IMMOfSNSTests' do
    inherit! :search_paths
    # Pods for testing
  end


  target 'IMMOfSNSUITests' do
    inherit! :search_paths
    # Pods for testing
  end


end
```

### Error

```
LoadError - cannot load such file -- macho
/Users/Seven/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.5.3/lib/cocoapods/sandbox/file_accessor.rb:432:in `rescue in dynamic_binary?'
/Users/Seven/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.5.3/lib/cocoapods/sandbox/file_accessor.rb:427:in `dynamic_binary?'
/Users/Seven/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.5.3/lib/cocoapods/sandbox/file_accessor.rb:164:in `block in vendored_dynamic_frameworks'
/Users/Seven/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.5.3/lib/cocoapods/sandbox/file_accessor.rb:163:in `select'
/Users/Seven/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.5.3/lib/cocoapods/sandbox/file_accessor.rb:163:in `vendored_dynamic_frameworks'
/Users/Seven/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.5.3/lib/cocoapods/sandbox/file_accessor.rb:172:in `vendored_static_frameworks'
/Users/Seven/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.5.3/lib/cocoapods/generator/xcconfig/xcconfig_helper.rb:122:in `add_static_dependency_build_settings'
/Users/Seven/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.5.3/lib/cocoapods/generator/xcconfig/xcconfig_helper.rb:89:in `block in add_settings_for_file_accessors_of_target'
/Users/Seven/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.5.3/lib/cocoapods/generator/xcconfig/xcconfig_helper.rb:86:in `each'
/Users/Seven/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.5.3/lib/cocoapods/generator/xcconfig/xcconfig_helper.rb:86:in `add_settings_for_file_accessors_of_target'
/Users/Seven/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.5.3/lib/cocoapods/generator/xcconfig/pod_xcconfig.rb:65:in `generate'
/Users/Seven/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.5.3/lib/cocoapods/generator/xcconfig/pod_xcconfig.rb:39:in `save_as'
/Users/Seven/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator/target_installer.rb:112:in `update_changed_file'
/Users/Seven/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:384:in `create_xcconfig_file'
/Users/Seven/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:28:in `block in install!'
/Users/Seven/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:142:in `message'
/Users/Seven/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:19:in `install!'
/Users/Seven/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator.rb:176:in `block (2 levels) in install_libraries'
/Users/Seven/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator.rb:173:in `each'
/Users/Seven/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator.rb:173:in `block in install_libraries'
/Users/Seven/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:142:in `message'
/Users/Seven/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator.rb:167:in `install_libraries'
/Users/Seven/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator.rb:65:in `generate!'
/Users/Seven/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:184:in `block in generate_pods_project'
/Users/Seven/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
/Users/Seven/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:183:in `generate_pods_project'
/Users/Seven/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:119:in `install!'
/Users/Seven/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.5.3/lib/cocoapods/command/install.rb:41:in `run'
/Users/Seven/.rvm/gems/ruby-2.2.4/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/Seven/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
/Users/Seven/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
/Users/Seven/.rvm/gems/ruby-2.2.4/bin/pod:22:in `load'
/Users/Seven/.rvm/gems/ruby-2.2.4/bin/pod:22:in `<main>'
/Users/Seven/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `eval'
/Users/Seven/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=cannot+load+such+file+--+macho&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

And
192:IMMOfSNS Seven$ gem which macho
/Users/Seven/.rvm/gems/ruby-2.2.4/gems/ruby-macho-1.2.0/lib/macho.rb

**Comment by dnkoutso** [comment]
@chutianfan this is a dup of https://github.com/CocoaPods/CocoaPods/issues/7849 and has been closed due to missing configuration and unable to reproduce.

Also recommend using StackOverflow using `cocoapods` tag for these questions. If we can show that this is a cocoapods library issue then I will be happy to re-open this and mark it as a defect.
