### ISSUE TITLE
[Master] There are two failed unit tests

### ISSUE THREAD

**Issue by Whirlwind** [CocoaPods/CocoaPods#7874]
There are two unit tests:
```
Bacon::Error: [{:name=>"FrameworkA.framework", :input_path=>"${PODS_ROOT}/../../../../../../../../some/absolute/path/to/FrameworkA.framework", :output_path=>"${TARGET_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}/FrameworkA.framework"}].==([{:name=>"FrameworkA.framework", :input_path=>"${PODS_ROOT}/../../../../../../../some/absolute/path/to/FrameworkA.framework", :output_path=>"${TARGET_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}/FrameworkA.framework"}]) failed
	spec/unit/target/aggregate_target_spec.rb:206:in `block (4 levels) in <module:Pod>': frameworks by config and input output paths - returns vendored frameworks by config
	/Users/whirlwind/Documents/Developer/CocoaPods/CocoaPods/spec/spec_helper/pre_flight.rb:25:in `call'
	/Users/whirlwind/Documents/Developer/CocoaPods/CocoaPods/spec/spec_helper/pre_flight.rb:25:in `block in <class:Context>'
	spec/unit/target/aggregate_target_spec.rb:195:in `block (3 levels) in <module:Pod>'
	spec/unit/target/aggregate_target_spec.rb:123:in `block (2 levels) in <module:Pod>'
	spec/unit/target/aggregate_target_spec.rb:86:in `block in <module:Pod>'
	spec/unit/target/aggregate_target_spec.rb:4:in `<module:Pod>'
	spec/unit/target/aggregate_target_spec.rb:3:in `<top (required)>'
	/Users/whirlwind/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:74:in `load'
	/Users/whirlwind/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:74:in `kernel_load'
	/Users/whirlwind/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:28:in `run'
	/Users/whirlwind/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:424:in `exec'
	/Users/whirlwind/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	/Users/whirlwind/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
	/Users/whirlwind/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
	/Users/whirlwind/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:27:in `dispatch'
	/Users/whirlwind/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
	/Users/whirlwind/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:18:in `start'
	/Users/whirlwind/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.16.2/exe/bundle:30:in `block in <top (required)>'
	/Users/whirlwind/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/bundler/friendly_errors.rb:124:in `with_friendly_errors'
	/Users/whirlwind/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.16.2/exe/bundle:22:in `<top (required)>'
	/Users/whirlwind/.rvm/gems/ruby-2.4.1/bin/bundle:23:in `load'
	/Users/whirlwind/.rvm/gems/ruby-2.4.1/bin/bundle:23:in `<main>'
	/Users/whirlwind/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
	/Users/whirlwind/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'

Bacon::Error: [{:name=>"FrameworkA.framework", :input_path=>"${PODS_ROOT}/../../../../../../../../absolute/path/to/FrameworkA.framework", :output_path=>"${TARGET_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}/FrameworkA.framework"}].==([{:name=>"FrameworkA.framework", :input_path=>"${PODS_ROOT}/../../../../../../../absolute/path/to/FrameworkA.framework", :output_path=>"${TARGET_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}/FrameworkA.framework"}]) failed
	spec/unit/target/aggregate_target_spec.rb:235:in `block (4 levels) in <module:Pod>': frameworks by config and input output paths - returns correct input and output paths for vendored frameworks
	/Users/whirlwind/Documents/Developer/CocoaPods/CocoaPods/spec/spec_helper/pre_flight.rb:25:in `call'
	/Users/whirlwind/Documents/Developer/CocoaPods/CocoaPods/spec/spec_helper/pre_flight.rb:25:in `block in <class:Context>'
	spec/unit/target/aggregate_target_spec.rb:224:in `block (3 levels) in <module:Pod>'
	spec/unit/target/aggregate_target_spec.rb:123:in `block (2 levels) in <module:Pod>'
	spec/unit/target/aggregate_target_spec.rb:86:in `block in <module:Pod>'
	spec/unit/target/aggregate_target_spec.rb:4:in `<module:Pod>'
	spec/unit/target/aggregate_target_spec.rb:3:in `<top (required)>'
	/Users/whirlwind/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:74:in `load'
	/Users/whirlwind/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:74:in `kernel_load'
	/Users/whirlwind/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:28:in `run'
	/Users/whirlwind/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:424:in `exec'
	/Users/whirlwind/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	/Users/whirlwind/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
	/Users/whirlwind/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
	/Users/whirlwind/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:27:in `dispatch'
	/Users/whirlwind/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
	/Users/whirlwind/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:18:in `start'
	/Users/whirlwind/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.16.2/exe/bundle:30:in `block in <top (required)>'
	/Users/whirlwind/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/bundler/friendly_errors.rb:124:in `with_friendly_errors'
	/Users/whirlwind/.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.16.2/exe/bundle:22:in `<top (required)>'
	/Users/whirlwind/.rvm/gems/ruby-2.4.1/bin/bundle:23:in `load'
	/Users/whirlwind/.rvm/gems/ruby-2.4.1/bin/bundle:23:in `<main>'
	/Users/whirlwind/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
	/Users/whirlwind/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
```
They work fine in github ci, but failed in my mac. It seams that it causes by the project path.

**Comment by amorde** [comment]
I actually have the same issue, these tests fail for me all the time on my personal machine but work fine on CI. It's not a big deal but can be annoying.

**Comment by dnkoutso** [comment]
weird passes for me. What is `sandbox.root` for you? Mine is `/Users/dnkoutso/Development/ios/cocoapods/tmp/Pods`

**Comment by paulb777** [comment]
I always have two tests fail when running locally also.

**Comment by amorde** [comment]
Mine is `/Users/eric/Projects/CocoaPods/tmp/Pods`

**Comment by dnkoutso** [comment]
That is probably the problem. Perhaps CI has the same level of subdirs as mine and it works. We can fix that.

**Comment by amorde** [comment]
oh interesting. yeah that could be it

**Comment by amorde** [comment]
I can look into it since I have it readily reproducible

**Comment by dnkoutso** [comment]
👍

**Comment by amorde** [comment]
actually, why do the input paths need to be relative to `$PODS_ROOT`?

it seems like this:

`${PODS_ROOT}/../../../../../../../some/absolute/path/to/FrameworkA.framework`

should be:

`/some/absolute/path/to/FrameworkA.framework`

_unless_ the path is actually a descendent of ${PODS_ROOT}

**Comment by dnkoutso** [comment]
> unless the path is actually a descendent of ${PODS_ROOT}

Correct on this since all pod sources are installed there including the vendored frameworks a pod may bring.

We should ensure it works for the case of a local development pod and having an absolute path might actually fail for different devs?

**Comment by dnkoutso** [comment]
Let's go with the change you made. I verified locally it also passes for me (on your branch)

**Comment by dnkoutso** [comment]
thank you @amorde !

**Comment by amorde** [comment]
thanks @Whirlwind for giving me the motivation to fix it!
