### ISSUE TITLE
Pod Update failed on Mac OS X 10.14

### ISSUE THREAD

**Issue by applexiaohao** [CocoaPods/CocoaPods#7895]
### Command

```
/usr/local/bin/pod update --verbose --no-repo-update
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
    RubyGems : 2.6.11
        Host : Mac OS X 10.14 (18A314h)
       Xcode : 9.4.1 (9F2000)
         Git : git version 2.15.2 (Apple Git-101.1)
Ruby lib dir : /usr/local/Cellar/ruby/2.4.1_1/lib
Repositories : ios_pr_amap_specs - git@gitlab.alibaba-inc.com:amap_rd_app_ios/ios_pr_amap_specs.git @ 19f9870002ac999df5871003dca8ba4b01c83c2c
               master - https://github.com/CocoaPods/Specs.git @ c2d0315a177432b874cd50e3dbae446e5a9c254f
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

post_install do | installer |
    installer.pods_project.targets.each do |target|
       target.build_configurations.each do |config|
          config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
          config.build_settings['GCC_WARN_ABOUT_RETURN_TYPE'] = 'YES_ERROR'
          if config.name.include?("Debug")
             config.build_settings['WARNING_CFLAGS'] = '-Wpartial-availability'
          end
          if target.name.include?("dynamicUI")
             config.build_settings['GCC_OPTIMIZATION_LEVEL'] = '0'
          end
       end
    end

    # 解决app icon不显示问题
    copy_pods_resources_path = "Pods/Target Support Files/Pods-AMapiPhone/Pods-AMapiPhone-resources.sh"
    copy_pods_resources_path_test = "Pods/Target Support Files/Pods-AMapiPhone-AMapiPhoneTest/Pods-AMapiPhone-AMapiPhoneTest-resources.sh"
    copy_pods_resources_path_monkey = "Pods/Target Support Files/Pods-AMapiPhone-AMapiPhoneMonkey/Pods-AMapiPhone-AMapiPhoneMonkey-resources.sh"

    string_to_replace = '--compile "${BUILT_PRODUCTS_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}"'
    assets_compile_with_app_icon_arguments = '--compile "${BUILT_PRODUCTS_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}" --app-icon "${ASSETCATALOG_COMPILER_APPICON_NAME}" --output-partial-info-plist "${BUILD_DIR}/assetcatalog_generated_info.plist"'

    text = File.read(copy_pods_resources_path)
    new_contents = text.gsub(string_to_replace, assets_compile_with_app_icon_arguments)
    File.open(copy_pods_resources_path, "w") {|file| file.puts new_contents }

    text = File.read(copy_pods_resources_path_test)
    new_contents = text.gsub(string_to_replace, assets_compile_with_app_icon_arguments)
    File.open(copy_pods_resources_path_test, "w") {|file| file.puts new_contents }

    text = File.read(copy_pods_resources_path_monkey)
    new_contents = text.gsub(string_to_replace, assets_compile_with_app_icon_arguments)
    File.open(copy_pods_resources_path_monkey, "w") {|file| file.puts new_contents }
end


project 'AMapiPhone.xcodeproj'

def amap_pods_build
pod 'ankit',  :path => '../../ios_pr_amap_ankit'
pod 'core',  :path => '../../ios_pr_amap_core'
pod 'basemap',  :path => '../../ios_pr_amap_basemap'
pod 'engine',  :path => '../../ios_pr_amap_engine'
pod 'engineadapter',  :path => '../../ios_pr_amap_engineadapter'
pod 'externalFrameworks',  :path => '../../ios_pr_amap_thirdparty'
pod 'lifeservice',  :path => '../../ios_pr_amap_lifeservice'
pod 'publictransit',  :path => '../../ios_pr_amap_publictransit'
pod 'route',  :path => '../../ios_pr_amap_route'
pod 'search',  :path => '../../ios_pr_amap_search'
pod 'user',  :path => '../../ios_pr_amap_user'
pod 'dynamicUI', :path => '../../ios_pr_amap_dynamicUI'
pod 'utils', :path => '../../ios_pr_amap_utils'
pod 'net', :path => '../../ios_pr_amap_net'
pod 'businesscommon', :path => '../../ios_pr_amap_businesscommon'
pod 'Account', :path => '../../amap_bundle_account'
pod 'macro', :path => '../../ios_pr_amap_macro'
pod 'aos', :path => '../../amap_bundle_aos'
pod 'MapHome', :path => '../../amap_bundle_maphome'
pod 'Feed', :path => '../../amap_bundle_feed'
pod 'FrequentLocation', :path => '../../amap_bundle_frequentlocation'
pod 'TrafficEvent', :path => '../../amap_bundle_trafficevent'
pod 'Agroup', :path => '../../amap_bundle_agroup'
pod 'MsgBox', :path => '../../amap_bundle_msgbox'
pod 'Activities', :path => '../../amap_bundle_activities'
pod 'Notification', :path => '../../amap_bundle_notification'
pod 'PhotoSelect', :path => '../../amap_bundle_photoselect'
pod 'Share', :path => '../../amap_bundle_share'
pod 'WebView', :path => '../../amap_bundle_webview'
pod 'SplashScreen', :path => '../../amap_bundle_splashscreen'
pod 'CitySelect', :path => '../../amap_bundle_cityselect'
pod 'LoactionSelect', :path => '../../amap_bundle_loactionselect'
pod 'FeatureGuide', :path => '../../amap_bundle_featureguide'
pod 'Feedback', :path => '../../amap_bundle_feedback'
#pod 'debug', :path => '../../ios_pr_amap_debug'
#pod 'performance', :path => '../../ios_pr_amap_performance'
end

def amap_pods_test_build
  pod 'coreTest',  :path => '../../ios_pr_amap_core'
  pod 'lifeserviceTest',  :path => '../../ios_pr_amap_lifeservice'
  pod 'publictransitTest',  :path => '../../ios_pr_amap_publictransit'
  pod 'routeTest',  :path => '../../ios_pr_amap_route'
  pod 'searchTest',  :path => '../../ios_pr_amap_search'
  pod 'userTest',  :path => '../../ios_pr_amap_user'
  pod 'externalFrameworksTest', :path => '../../ios_pr_amap_thirdparty'
end

target 'AMapiPhone' do
  amap_pods_build
  target 'AMapiPhoneTest' do
    amap_pods_test_build
  end
  target 'AMapiPhoneMonkey' do
    amap_pods_test_build
  end
end
```

### Error

```
Errno::EEXIST - File exists @ syserr_fail2_in - /Users/haohao/Desktop/AMAP/ios-xxx/ios_pr_amap_project/AMapiPhone/Pods/Headers/Private/externalFrameworks/Window.h
/usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/fileutils.rb:320:in `symlink'
/usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/fileutils.rb:320:in `block in ln_s'
/usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/fileutils.rb:1474:in `fu_each_src_dest0'
/usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/fileutils.rb:318:in `ln_s'
/usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/fileutils.rb:337:in `ln_sf'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/sandbox/headers_store.rb:124:in `add_file'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/sandbox/headers_store.rb:100:in `block in add_files'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/sandbox/headers_store.rb:99:in `map'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/sandbox/headers_store.rb:99:in `add_files'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:151:in `block (4 levels) in link_headers'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:149:in `each'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:149:in `block (3 levels) in link_headers'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:146:in `each'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:146:in `block (2 levels) in link_headers'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:135:in `each'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:135:in `block in link_headers'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:142:in `message'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:134:in `link_headers'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:44:in `install!'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator.rb:163:in `install_file_references'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator.rb:64:in `generate!'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:184:in `block in generate_pods_project'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:183:in `generate_pods_project'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:119:in `install!'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/command/update.rb:97:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

**Comment by dnkoutso** [comment]
Without a sample app this is hard to debug.

Some guesses:

a) At least two of your pods include the same header `Window.h`.
b) try `rm -rf Pods/` and `pod install` again.

**Comment by applexiaohao** [comment]
b)

### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
    RubyGems : 2.6.11
        Host : Mac OS X 10.14 (18A314h)
       Xcode : 9.4.1 (9F2000)
         Git : git version 2.15.2 (Apple Git-101.1)
Ruby lib dir : /usr/local/Cellar/ruby/2.4.1_1/lib
Repositories : ios_pr_amap_specs - git@gitlab.alibaba-inc.com:amap_rd_app_ios/ios_pr_amap_specs.git @ 5e8be4088ffcc2b0e72279bceb03c1484874a743
               master - https://github.com/CocoaPods/Specs.git @ c2d0315a177432b874cd50e3dbae446e5a9c254f
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
install! 'cocoapods', :deterministic_uuids => false
source "git@gitlab.alibaba-inc.com:amap_rd_app_ios/ios_pr_amap_specs.git"
post_install do | installer |
    installer.pods_project.targets.each do |target|
       target.build_configurations.each do |config|
          config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
          config.build_settings['GCC_WARN_ABOUT_RETURN_TYPE'] = 'YES_ERROR'
          if config.name.include?("Debug")
             config.build_settings['WARNING_CFLAGS'] = '-Wpartial-availability'
          end
          if target.name.include?("dynamicUI")
             config.build_settings['GCC_OPTIMIZATION_LEVEL'] = '0'
          end
       end
    end

    # 解决app icon不显示问题
    copy_pods_resources_path = "Pods/Target Support Files/Pods-AMapiPhone/Pods-AMapiPhone-resources.sh"
    copy_pods_resources_path_test = "Pods/Target Support Files/Pods-AMapiPhone-AMapiPhoneTest/Pods-AMapiPhone-AMapiPhoneTest-resources.sh"
    copy_pods_resources_path_monkey = "Pods/Target Support Files/Pods-AMapiPhone-AMapiPhoneMonkey/Pods-AMapiPhone-AMapiPhoneMonkey-resources.sh"

    string_to_replace = '--compile "${BUILT_PRODUCTS_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}"'
    assets_compile_with_app_icon_arguments = '--compile "${BUILT_PRODUCTS_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}" --app-icon "${ASSETCATALOG_COMPILER_APPICON_NAME}" --output-partial-info-plist "${BUILD_DIR}/assetcatalog_generated_info.plist"'

    text = File.read(copy_pods_resources_path)
    new_contents = text.gsub(string_to_replace, assets_compile_with_app_icon_arguments)
    File.open(copy_pods_resources_path, "w") {|file| file.puts new_contents }

    text = File.read(copy_pods_resources_path_test)
    new_contents = text.gsub(string_to_replace, assets_compile_with_app_icon_arguments)
    File.open(copy_pods_resources_path_test, "w") {|file| file.puts new_contents }

    text = File.read(copy_pods_resources_path_monkey)
    new_contents = text.gsub(string_to_replace, assets_compile_with_app_icon_arguments)
    File.open(copy_pods_resources_path_monkey, "w") {|file| file.puts new_contents }
end

project 'AMapiPhone.xcodeproj'

def amap_pods_build
  pod 'ankit', :path => '../../ios_pr_amap_ankit'
  pod 'core', :path => '../../ios_pr_amap_core'
  pod 'engine', :path => '../../ios_pr_amap_engine'
  pod 'engineadapter', :path => '../../ios_pr_amap_engineadapter'
  pod 'externalFrameworks', :path => '../../ios_pr_amap_thirdparty'
  pod 'basemap', :path => '../../ios_pr_amap_basemap'
  pod 'publictransit', :path => '../../ios_pr_amap_publictransit'
  pod 'search', :path => '../../ios_pr_amap_search'
  pod 'user', :path => '../../ios_pr_amap_user'
  pod 'lifeservice', :path => '../../ios_pr_amap_lifeservice'
  pod 'dynamicUI', :path => '../../ios_pr_amap_dynamicUI'
  pod 'route', :path => '../../ios_pr_amap_route'
  pod 'utils', :path => '../../ios_pr_amap_utils'
  pod 'net', :path => '../../ios_pr_amap_net'
  pod 'businesscommon', :path => '../../ios_pr_amap_businesscommon'
  pod 'Account','1.0.0.20180620184517'
  pod 'macro', :path => '../../ios_pr_amap_macro'
  pod 'aos', :path => '../../amap_bundle_aos'
  pod 'MapHome','1.0.0.20180621203601'
  pod 'Feed','1.0.0.20180530120816'
  pod 'FrequentLocation','1.0.0.20180530120815'
  pod 'TrafficEvent','1.0.0.20180613212056'
  pod 'Agroup','1.0.0.20180530120812'
  pod 'MsgBox','1.0.0.20180627201552'
  pod 'Activities','1.0.0.20180530120813'
  pod 'Notification','1.0.0.20180530120810'
  pod 'PhotoSelect','1.0.0.20180612145352'
  pod 'Share','1.0.0.20180530120556'
  pod 'WebView','1.0.0.20180607101208'
  pod 'SplashScreen','1.0.0.20180614115207'
  pod 'CitySelect','1.0.0.20180530111649'
  pod 'LoactionSelect','1.0.0.20180606164816'
  pod 'FeatureGuide','1.0.0.20180611220059'
  pod 'Feedback','1.0.0.20180619183546'
#pod 'debug', :path => '../../ios_pr_amap_debug'
#pod 'performance', :path => '../../ios_pr_amap_performance'
end

def amap_pods_test_build
  pod 'coreTest',  :path => '../../ios_pr_amap_core'
  pod 'lifeserviceTest',  :path => '../../ios_pr_amap_lifeservice'
  pod 'publictransitTest',  :path => '../../ios_pr_amap_publictransit'
  pod 'routeTest',  :path => '../../ios_pr_amap_route'
  pod 'searchTest',  :path => '../../ios_pr_amap_search'
  pod 'userTest',  :path => '../../ios_pr_amap_user'
  pod 'externalFrameworksTest', :path => '../../ios_pr_amap_thirdparty'
end

target 'AMapiPhone' do
  amap_pods_build
  target 'AMapiPhoneTest' do
    amap_pods_test_build
  end
  target 'AMapiPhoneMonkey' do
    amap_pods_test_build
  end
end
```

### Error

```
Errno::EEXIST - File exists @ syserr_fail2_in - /Users/haohao/Desktop/AMAP/ios-xxx/ios_pr_amap_project/AMapiPhone/Pods/Headers/Private/externalFrameworks/Window.h
/usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/fileutils.rb:320:in `symlink'
/usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/fileutils.rb:320:in `block in ln_s'
/usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/fileutils.rb:1474:in `fu_each_src_dest0'
/usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/fileutils.rb:318:in `ln_s'
/usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/fileutils.rb:337:in `ln_sf'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/sandbox/headers_store.rb:124:in `add_file'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/sandbox/headers_store.rb:100:in `block in add_files'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/sandbox/headers_store.rb:99:in `map'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/sandbox/headers_store.rb:99:in `add_files'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:151:in `block (4 levels) in link_headers'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:149:in `each'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:149:in `block (3 levels) in link_headers'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:146:in `each'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:146:in `block (2 levels) in link_headers'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:135:in `each'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:135:in `block in link_headers'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:142:in `message'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:134:in `link_headers'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:44:in `install!'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator.rb:163:in `install_file_references'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator.rb:64:in `generate!'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:184:in `block in generate_pods_project'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:183:in `generate_pods_project'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:119:in `install!'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/command/install.rb:41:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

**Comment by applexiaohao** [comment]
![image](https://user-images.githubusercontent.com/2010339/42088385-e3f122d6-7bcb-11e8-90ba-6e04fd0f0040.png)
有一个window.h还有一个Window.h
1、~/Desktop/AMAP/ios-xxx/ios_pr_amap_thirdparty/Vorbis/window.h
2、~/Desktop/AMAP/ios-xxx/ios_pr_amap_thirdparty/ZBarSDK/Headers/ZBarSDK/zbar/Window.h

和这个有关吗
