### ISSUE TITLE
Cannot push private pod spec up

### ISSUE THREAD

**Issue by MaxHasADHD** [CocoaPods/CocoaPods#7930]
# Report

## What did you do?
I'm trying to push a private pod spec to a private trunk repo.

## What did you expect to happen?
My pod spec would be pushed to my private trunk repo

## What happened instead?

I am receiving an error.

Validating spec
 -> XXXXXKit (1.0.0)
    - WARN  | url: The URL (https://github.com/Username/XXXXXKit) is not reachable.
    - ERROR | [iOS] unknown: Encountered an unknown error (no implicit conversion of nil into String) during validation.

[!] The `XXXXXKit.podspec` specification does not validate.

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    RubyGems : 2.5.2
        Host : Mac OS X 10.13.5 (17F77)
       Xcode : 9.4 (9F1027a)
         Git : git version 2.15.1 (Apple Git-101)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ dc14cc1c376227a56fed49b0a74ae29f68453741
               XXXXXKit - https://github.com/Username/XXXXXKit.git @ 4076e7655bacd2396b489c05d25aa0ede935793f
               PrivateTrunk - https://github.com/Username/PrivateTrunk.git @ ef63734a60318e061412fe47f22627063bb08f83
               YYYYYKit - https://github.com/Username/YYYYYKit.git @ 90550b14893f6c1e04b5a12777b59087334d753f
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'XXXXXKit' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for XXXXXKit
  pod 'YYYYYKit'
  pod 'SwiftyBeaver'

  target 'XXXXXKitTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
```

Screenshot of my private podspec. It passes linting, but I can't get it to push.

<img width="808" alt="screen shot 2018-07-14 at 6 23 25 pm" src="https://user-images.githubusercontent.com/1296190/42728855-07d4bbae-8793-11e8-8786-ec6d98962258.png">

I've been looking into this for about 6 hours, and have had no luck, even watched a video tutorial on setting up private pod repos. This was my last resort.

**Comment by amorde** [comment]
Could you post the output with the `--verbose` flag? The part that would be helpful is the stack trace of where the error occured

**Comment by MaxHasADHD** [comment]
```Validating spec
    XXXXXKit (1.0.0) - Analyzing on iOS 11.0 platform.
  Preparing

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-App`: (``)

Fetching external sources
-> Fetching podspec for `XXXXXKit` from `/Users/maximilianlitteral/Desktop/Apps/XXXXXKit/XXXXXKit.podspec`

Resolving dependencies of 
 -> XXXXXKit (1.0.0)
    - WARN  | url: The URL (https://github.com/Username/XXXXXKit) is not reachable.
    - ERROR | [iOS] unknown: Encountered an unknown error (no implicit conversion of nil into String
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/specification.rb:594:in `initialize'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/specification.rb:594:in `new'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/specification.rb:594:in `from_file'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/specification/set.rb:56:in `specification_name'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/source.rb:274:in `search'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/source/aggregate.rb:83:in `block in search'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/source/aggregate.rb:83:in `select'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/source/aggregate.rb:83:in `search'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:428:in `create_set_from_sources'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:398:in `find_cached_set'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:372:in `specifications_for_dependency'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:177:in `search_for'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:288:in `block in sort_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:281:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:281:in `sort_by'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:281:in `sort_dependencies'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.5/lib/molinillo/delegates/specification_provider.rb:53:in `block in sort_dependencies'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.5/lib/molinillo/delegates/specification_provider.rb:70:in `with_no_such_dependency_error_handling'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.5/lib/molinillo/delegates/specification_provider.rb:52:in `sort_dependencies'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:754:in `push_state_for_requirements'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:746:in `require_nested_dependencies_for'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:729:in `activate_new_spec'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:686:in `attempt_to_activate'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:254:in `process_topmost_state'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:182:in `resolve'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.5/lib/molinillo/resolver.rb:43:in `resolve'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:123:in `resolve'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:781:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:779:in `resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:88:in `analyze'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:243:in `analyze'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:154:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:153:in `resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/validator.rb:472:in `block in download_pod'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/validator.rb:472:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/validator.rb:472:in `download_pod'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/validator.rb:318:in `block in perform_extensive_analysis'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/validator.rb:312:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/validator.rb:312:in `perform_extensive_analysis'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/validator.rb:87:in `validate'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command/repo/push.rb:139:in `block in validate_podspec_files'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command/repo/push.rb:130:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command/repo/push.rb:130:in `validate_podspec_files'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command/repo/push.rb:75:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
) during validation.

[!] The `XXXXXKit.podspec` specification does not validate.

/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command/repo/push.rb:144:in `block in validate_podspec_files'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command/repo/push.rb:130:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command/repo/push.rb:130:in `validate_podspec_files'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command/repo/push.rb:75:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'```

**Comment by amorde** [comment]
Looks CocoaPods is unable to find the file with your spec, either due to a version mismatch or a name mismatch. Is it possible that the name of your `.podspec` file doesn't match the name specified inside the specification?

If that's not it then more info is needed to figure this out

**Comment by MaxHasADHD** [comment]
@amorde the names are the same. It looks like I can get further into the process if I remove `s.dependency "YYYYYKit"` in my pod spec, but then I get an error from the code that the framework is missing. If I run `pod repo` I see `YYYYYKit` there, could that possibly be an issue?

Also, the pod spec for `YYYYYKit` is:
```
Pod::Spec.new do |s|

  s.name      = "YYYYYKit"
  s.version   = "1.0.1"
  s.summary   = "Summary"
  s.homepage  = "https://github.com/Username/YYYYYKit"

  s.license   = { :type => "MIT", :file => "License.md" }

  s.authors   = "Maximilian Litteral"

  s.swift_version             = "4.0"
  s.ios.deployment_target     = "10.0"
  s.osx.deployment_target     = "10.10"
  s.watchos.deployment_target = "3.0"

  s.source        = { :git => "https://github.com/Username/YYYYYKit.git", :tag => "#{s.version}" }
  s.source_files  = "Common", "Common/**/*.{h,m,swift}"

  s.requires_arc = true

end
```

**Comment by amorde** [comment]
Is `YYYYKit` available in the same private repo?

Also if you're pushing to a private repo you don't need to rerun the validation, you can skip it with command line arguments. See https://guides.cocoapods.org/terminal/commands.html#pod_repo_push

**Comment by MaxHasADHD** [comment]
`YYYYYKit` is a public repo, so not private. But this project uses it in the Podfile, and I added it as a dependency.

**Comment by amorde** [comment]
You may need to use the `--sources` argument when running `pod repo push` depending on your setup. Again if you're pushing XXXXKit to a _private_ repo, you don't have to run the validation at all

**Comment by dnkoutso** [comment]
How do you `lint`? Is it via `pod lib lint` or `pod spec lint`? If it's the latter then it might be that an older SHA is cloned since `spec lint` will clone at the tag. You can also use `--no-clean` which will keep the generated project from `lint` around and you can open it and inspect yourself.

I personally don't think this is a CocoaPods bug so far. We can keep this issue open but its also best asked in StackOverflow under `cocoapods` tag.

**Comment by MaxHasADHD** [comment]
I believe `pod spec lint`.

I also reset my git history and tags before I added cocoapods, and then did the entire set up again, and made a new pod spec repo on GitHub, but it resulted in the same error.

**Comment by dnkoutso** [comment]
Have you ensured the tag specified in your podspec points to the right SHA and not an older one since `pod spec lint` will actually *clone* that tag.

**Comment by MaxHasADHD** [comment]
@dnkoutso yup! This is the only tag on the repo, points to the commit I added the pod spec to.

**Comment by MaxHasADHD** [comment]
Finally got this working by running `pod repo push PodspecRepo XXXXXKit.podspec --allow-warnings --skip-tests --sources=https://github.com/CocoaPods/Specs.git,master --skip-import-validation`
