### ISSUE TITLE
help! while doing pod install

### ISSUE THREAD

**Issue by lewnick** [CocoaPods/CocoaPods#7963]
### Error

```
ArgumentError - Illformed requirement `"~> 替换为所使用的 SDK 版本号"`
/Users/nicge/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-core-1.5.3/lib/cocoapods-core/requirement.rb:63:in `parse'
/Users/nicge/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-core-1.5.3/lib/cocoapods-core/requirement.rb:88:in `block in initialize'
/Users/nicge/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-core-1.5.3/lib/cocoapods-core/requirement.rb:88:in `map!'
/Users/nicge/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-core-1.5.3/lib/cocoapods-core/requirement.rb:88:in `initialize'
/Users/nicge/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-core-1.5.3/lib/cocoapods-core/requirement.rb:34:in `new'
/Users/nicge/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-core-1.5.3/lib/cocoapods-core/requirement.rb:34:in `create'
/Users/nicge/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-core-1.5.3/lib/cocoapods-core/dependency.rb:115:in `initialize'
/Users/nicge/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-core-1.5.3/lib/cocoapods-core/podfile/target_definition.rb:890:in `new'
/Users/nicge/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-core-1.5.3/lib/cocoapods-core/podfile/target_definition.rb:890:in `block in pod_dependencies'
/Users/nicge/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-core-1.5.3/lib/cocoapods-core/podfile/target_definition.rb:886:in `map'
/Users/nicge/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-core-1.5.3/lib/cocoapods-core/podfile/target_definition.rb:886:in `pod_dependencies'
/Users/nicge/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-core-1.5.3/lib/cocoapods-core/podfile/target_definition.rb:96:in `non_inherited_dependencies'
/Users/nicge/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-core-1.5.3/lib/cocoapods-core/podfile/target_definition.rb:74:in `dependencies'
/Users/nicge/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer/podfile_dependency_cache.rb:43:in `block in from_podfile'
/Users/nicge/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer/podfile_dependency_cache.rb:42:in `each'
/Users/nicge/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer/podfile_dependency_cache.rb:42:in `from_podfile'
/Users/nicge/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:58:in `initialize'
/Users/nicge/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:248:in `new'
/Users/nicge/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:248:in `create_analyzer'
/Users/nicge/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:147:in `resolve_dependencies'
/Users/nicge/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:116:in `install!'
/Users/nicge/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-1.5.3/lib/cocoapods/command/install.rb:41:in `run'
/Users/nicge/.rvm/gems/ruby-2.1.1@global/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/nicge/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
/Users/nicge/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
/Users/nicge/.rvm/rubies/ruby-2.1.1/bin/pod:23:in `load'
/Users/nicge/.rvm/rubies/ruby-2.1.1/bin/pod:23:in `<main>'
/Users/nicge/.rvm/gems/ruby-2.1.1@global/bin/ruby_executable_hooks:24:in `eval'
/Users/nicge/.rvm/gems/ruby-2.1.1@global/bin/ruby_executable_hooks:24:in `<main>'

**Comment by dnkoutso** [comment]
Seems like a dependency is wrongly declared. Please use StackOverflow under `cocoapods` tag for these kind of questions. Also if you are certain its a CocoaPods library issue please include a sample app and I *will* re-open this issue for you!

**Comment by dnkoutso** [comment]
`~> 替换为所使用的 SDK 版本号` should be a version number like `~> 3.0` or `~> 3.0.beta.1`
