### ISSUE TITLE
When I execute pod install in terminal ,show this error：

### ISSUE THREAD

**Issue by wsv587** [CocoaPods/CocoaPods#8034]
### Error

```
Net::OpenTimeout - execution expired
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/net/http.rb:937:in `initialize'
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/net/http.rb:937:in `open'
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/net/http.rb:937:in `block in connect'
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/timeout.rb:103:in `timeout'
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/net/http.rb:935:in `connect'
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/net/http.rb:909:in `start'
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/open-uri.rb:337:in `open_http'
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/open-uri.rb:755:in `buffer_open'
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/open-uri.rb:226:in `block in open_loop'

**Comment by dnkoutso** [comment]
This seems like an network issue. Sorry with the given information its impossible to debug this.

Please file an issue with a template, providing a sample app and explaining exactly where CocoaPods did not work as expected.

**Comment by zengweihuanfengzizhi** [comment]
有的，loading之后超时
