### ISSUE TITLE
NoMethodError - undefined method `real_path' for nil:NilClass

### ISSUE THREAD

**Issue by rajeshkumarlingavel** [CocoaPods/CocoaPods#8061]
## What did I do?
`pod install`

## What did I expect to happen?
Install all pod dependencies correctly.

### Error

```
NoMethodError - undefined method `real_path' for nil:NilClass
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project/object/container_item_proxy.rb:96:in `container_portal_annotation'
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project/object/container_item_proxy.rb:105:in `to_hash_as'
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project/object.rb:421:in `to_ascii_plist'
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project.rb:288:in `block in to_ascii_plist'
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project.rb:286:in `each'
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project.rb:286:in `to_ascii_plist'
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project.rb:355:in `block in save'
/Library/Ruby/Gems/2.3.0/gems/atomos-0.1.2/lib/atomos.rb:20:in `block in atomic_write'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/tempfile.rb:295:in `open'
/Library/Ruby/Gems/2.3.0/gems/atomos-0.1.2/lib/atomos.rb:16:in `atomic_write'
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.7/lib/xcodeproj/project.rb:354:in `save'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.0/lib/cocoapods/installer/user_project_integrator.rb:139:in `block in save_projects'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.0/lib/cocoapods/installer/user_project_integrator.rb:137:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.0/lib/cocoapods/installer/user_project_integrator.rb:137:in `save_projects'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.0/lib/cocoapods/installer/user_project_integrator.rb:65:in `integrate!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.0/lib/cocoapods/installer.rb:591:in `block in integrate_user_project'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.0/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.0/lib/cocoapods/installer.rb:588:in `integrate_user_project'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.0/lib/cocoapods/installer.rb:121:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.0/lib/cocoapods/command/install.rb:41:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.0/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'

**Comment by dnkoutso** [comment]
Seems like you are using an older version of Xcodeproj gem. Can you please `gem update xcodeproj`? Also update to CocoaPods 1.5.3 as well.

Would need to see an `.xcodeproj` attached here to debug.

**Comment by rajeshkumarlingavel** [comment]
Oops, I not authorized to share the .xcodeproj file. I update the  Xcodeproj gem and CocoaPods 1.5.3 still having the same issue.

**Comment by rajeshkumarlingavel** [comment]
Xcode generates Recovered framework in the project. After deleting it Pod installs success.

**Comment by rajeshkumarlingavel** [comment]
Xcode generates Recovered framework in the project. After deleting it Pod installs success.  @dnkoutso Thanks for the reply.

**Comment by serges147** [comment]
I reproduced this problem with simple dummy project. The `undefined method `real_path'` crash happens when workspace has two projects with different set of configurations, like one with "Debug|Release" and another with "Debug|Release|ReleaseBeta". Please reopen. I can share zip file of the project.

**Comment by serges147** [comment]
No such problem on cocoapods v 1.5.3.

**Comment by amorde** [comment]
@serges147 can you open a separate issue and include the dummy project?

**Comment by serges147** [comment]
https://github.com/CocoaPods/CocoaPods/issues/8082
