### ISSUE TITLE
Operation not supported on socket @ rb_file_s_symlink

### ISSUE THREAD

**Issue by AlfredBauer** [CocoaPods/CocoaPods#8077]
### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

**I tried to build my flutter project on Mac VM through shared folder. Project is located on Windows OS. During to this, command "pod install" are launched and then I see error which presented below**

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin17]
    RubyGems : 2.7.7
        Host : Mac OS X 10.13.6 (17G65)
       Xcode : 9.4.1 (9F2000)
         Git : git version 2.15.2 (Apple Git-101.1)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ c2c9c7bcae8c3158a6cb240e939924b1114f534e
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project

 platform :ios, '9.0'



# CocoaPods analytics sends network stats synchronously affecting flutter build latency.

ENV['COCOAPODS_DISABLE_STATS'] = 'true'


project 'Runner.xcodeproj'

def parse_KV_file(file,separator='=')

  file_abs_path = File.expand_path(file)

  if !File.exists? file_abs_path

    return [];

  end

  pods_ary = []

  skip_line_start_symbols = ["#", "/"]

  File.foreach(file_abs_path) { |line|

      next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }

      plugin = line.split(pattern=separator)

      if plugin.length == 2

        podname = plugin[0].strip()

        path = plugin[1].strip()

        podpath = File.expand_path("#{path}", file_abs_path)

        pods_ary.push({:name => podname,:path=>podpath});

      else

        puts "Invalid plugin specification: #{line}"

      end

  }

  return pods_ary

end



target 'Runner' do

  # Flutter Pods

  generated_xcode_build_settings = parse_KV_file("./Flutter/Generated.xcconfig")

  if generated_xcode_build_settings.empty?

    puts "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter build or flutter run is executed once first."

  end

  generated_xcode_build_settings.map{ |p|

    if p[:name]=='FLUTTER_FRAMEWORK_DIR'

      pod 'Flutter', :path => p[:path]

    end

  }



  # Plugin Pods

  plugin_pods = parse_KV_file("../.flutter-plugins")

  plugin_pods.map{ |p|

    pod p[:name], :path => File.expand_path("ios",p[:path])

  }

end



post_install do |installer|

  installer.pods_project.targets.each do |target|

    target.build_configurations.each do |config|

      config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = ''

      config.build_settings['ENABLE_BITCODE'] = 'NO'

    end

  end

end
```

### Error

```
Errno::EOPNOTSUPP - Operation not supported on socket @ rb_file_s_symlink - (../../../Bolts/Bolts/iOS/BFAppLink.h, /Volumes/VMware Shared Folders/Flutter/CodeLabs/*my project*/ios/Pods/Headers/Private/Bolts/BFAppLink.h)
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:359:in `symlink'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:359:in `block in ln_s'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:1586:in `fu_each_src_dest0'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:357:in `ln_s'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:380:in `ln_sf'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/sandbox/headers_store.rb:124:in `add_file'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/sandbox/headers_store.rb:100:in `block in add_files'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/sandbox/headers_store.rb:99:in `map'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/sandbox/headers_store.rb:99:in `add_files'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:151:in `block (4 levels) in link_headers'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:149:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:149:in `block (3 levels) in link_headers'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:146:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:146:in `block (2 levels) in link_headers'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:135:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:135:in `block in link_headers'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:142:in `message'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:134:in `link_headers'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:44:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator.rb:163:in `install_file_references'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator.rb:64:in `generate!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:184:in `block in generate_pods_project'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:183:in `generate_pods_project'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:119:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command/install.rb:41:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

And I found the "solution" of this problem **Operation not supported on socket @ rb_file_s_symlink** . I've just copy my project from shared folder on Windows to Mac VM. For me it's just a workaround.

**Comment by dnkoutso** [comment]
This seems like you are pointing to a symlink as a source.

Sorry this is not enough information to debug this. Please upload a sample app. It is best to ask these questions in StackOverflow under `cocoapods` tag.
