### ISSUE TITLE
NoMethodError - undefined method `real_path`

### ISSUE THREAD

**Issue by serges147** [CocoaPods/CocoaPods#8082]
# Report

## What did you do?

`pod install`

## What did you expect to happen?

All pods correctly installed

## What happened instead?

```
[!] An error occurred while processing the post-install hook of the Podfile.

undefined method `real_path' for nil:NilClass

/Users/sergei/Desktop/TryCocoaPods16/Podfile:26:in `patch_xcconfig_file'
/Users/sergei/Desktop/TryCocoaPods16/Podfile:36:in `block (4 levels) in from_ruby'
/Users/sergei/Desktop/TryCocoaPods16/Podfile:34:in `each'
/Users/sergei/Desktop/TryCocoaPods16/Podfile:34:in `block (3 levels) in from_ruby'
/Users/sergei/Desktop/TryCocoaPods16/Podfile:32:in `each'
/Users/sergei/Desktop/TryCocoaPods16/Podfile:32:in `block (2 levels) in from_ruby'
/Users/sergei/.rvm/gems/ruby-2.4.2/gems/cocoapods-core-1.6.0.beta.1/lib/cocoapods-core/podfile.rb:179:in `post_install!'
/Users/sergei/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/installer.rb:685:in `run_podfile_post_install_hook'
/Users/sergei/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/installer.rb:673:in `block in run_podfile_post_install_hooks'
/Users/sergei/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/user_interface.rb:145:in `message'
/Users/sergei/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/installer.rb:672:in `run_podfile_post_install_hooks'
/Users/sergei/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/installer.rb:197:in `block in generate_pods_project'
/Users/sergei/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/sergei/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/installer.rb:194:in `generate_pods_project'
/Users/sergei/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/installer.rb:125:in `install!'
/Users/sergei/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/command/install.rb:48:in `run'
/Users/sergei/.rvm/gems/ruby-2.4.2/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/sergei/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/command.rb:52:in `run'
/Users/sergei/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.6.0.beta.1/bin/pod:55:in `<top (required)>'
/Users/sergei/.rvm/gems/ruby-2.4.2/bin/pod:23:in `load'
/Users/sergei/.rvm/gems/ruby-2.4.2/bin/pod:23:in `<main>'
/Users/sergei/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `eval'
/Users/sergei/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `<main>'
```
### Stack

```
   CocoaPods : 1.6.0.beta.1
        Ruby : ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin17]
    RubyGems : 2.6.14
        Host : Mac OS X 10.13.6 (17G65)
       Xcode : 9.4.1 (9F2000)
         Git : git version 2.15.2 (Apple Git-101.1)
Ruby lib dir : /Users/sergei/.rvm/rubies/ruby-2.4.2/lib
Repositories : cocoapods-local - file:///Users/sergei/.cocoapods/repos-art/cocoapods-local @ ef581fd6702607fa5cb0535d0cb909999c5ff014
               master - https://github.com/CocoaPods/Specs.git @ 4abe09c9d9498b46f51cc2b05c59f5b5fb3d6ae1
               mb-internal-specs - git@github.mb-internal.com:AdwareMedic/specs.git @ 57e9210510871cf5f33b9694fce562b028cc295d
```

### Installation Source

```
Executable Path: /Users/sergei/.rvm/gems/ruby-2.4.2/bin/pod
```

### Plugins

```
cocoapods-art         : 1.0.0
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
slather               : 2.4.6
```

### Podfile

```ruby
platform :osx, '10.10'
use_frameworks!

workspace 'TryCocoaPods16'

def podAlamofire
  pod 'Alamofire'
end

target 'TryCocoaPods16' do

  project 'TryCocoaPods16.xcodeproj'
  pod 'Alamofire'

end

target 'MyFramework' do

  project 'MyFramework/MyFramework.xcodeproj'
  pod 'Alamofire'

end

def patch_xcconfig_file(config)

  puts config.base_configuration_reference.real_path

end

post_install do |installer_representation|

  installer_representation.pods_project.targets.each do |target|

    target.build_configurations.each do |config|

      patch_xcconfig_file(config)

    end

  end

end
```

## Project that demonstrates the issue

https://github.com/serges147/TryCocoaPods16.git

**Comment by serges147** [comment]
My investigation showed that the key to reproduce this issue is the following:

Workspace has **two projects with different set of configurations**, like one with "Debug|Release" and another with "Debug|Release|ReleaseBeta". Please reopen. I can share zip file of the project.

**Comment by dnkoutso** [comment]
This is an error in your own `Podfile` you have a method called `patch_xcconfig_file(config)`.

Please use StackOverflow under `cocoapods` tag for these questions.

**Comment by dnkoutso** [comment]
You are also not mapping your configuration `project 'MyProject', 'ReleaseBeta' => :release`

**Comment by serges147** [comment]
ok, why it worked in 1.5.3 ?

**Comment by serges147** [comment]
Also, I'm not sure that I need such mapping b/c 'ReleaseBeta' could be just not applicable for the 'MyProject' at all, but still cocoapods tries to build a configuration for it.

**Comment by dnkoutso** [comment]
Is the repo you have a good sample to test this?

**Comment by serges147** [comment]
Looks like, indeed, adding `, 'ReleaseBeta' => :release` fixes the problem.

**Comment by serges147** [comment]
@dnkoutso Yup, I did it specifically for this report

**Comment by dnkoutso** [comment]
great thanks

**Comment by dnkoutso** [comment]
@serges147 Yes it works on 1.5.3 but no longer in 1.6.0.beta.1 but I am checking to see if its actually the right thing 1.6.0.beta.1 does.

**Comment by dnkoutso** [comment]
Still not sure if its a defect once I find a bit of time I will look into what changed and whether it was a regression or a correct thing.

**Comment by szotp** [comment]
This happened to me because I did not have a Release config at all. It looks like "Debug" and "Release" are hardcoded without checking if they exist. Attaching sample project as a proof.

[ConfigsProblem.zip](https://github.com/CocoaPods/CocoaPods/files/2900401/ConfigsProblem.zip)

This project has no Debug config, but it's still handled (I have added print in the hook). A workaround I'm going to use is skipping if config.name == Debug.
```
Analyzing dependencies
Downloading dependencies
Generating Pods project
Checking config: Release
Checking config: Debug
Integrating client project
Sending stats
```

**Comment by onmyway133** [comment]
I didn't have this problem in 1.6.0.beta.2

**Comment by onmyway133** [comment]
There maybe lots of causes for this error, but in my case, it is because of missing xcconfig file https://github.com/onmyway133/blog/issues/170

**Comment by enzomanuelmangano** [comment]
In my case I just removed the Podfile.lock and runned `pod install`
