### ISSUE TITLE
 pod trunk register error

### ISSUE THREAD

**Issue by cikichen** [CocoaPods/CocoaPods#8109]
――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod trunk register xxx xxx
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.6.0.beta.1
        Ruby : ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
    RubyGems : 2.7.7
        Host : Mac OS X 10.13.6 (17G2307)
       Xcode : 10.0 (10A255)
         Git : git version 2.17.1 (Apple Git-112)
Ruby lib dir : /usr/local/Cellar/ruby/2.5.1/lib
Repositories : cm - ssh://git@on_spec_repo.git @ bc3dcbdfdfdf0a7efae2e54ba0a1b79dee82b75b38
               master - https://github.com/CocoaPods/Specs.git @ c04567ab93ffdc0fddd8c80a74dae86e8b8e8072
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-packager    : 1.5.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Error

```
Netrc::Error - Permission bits for '/Users/simon/.netrc' should be 0600, but are 644
/usr/local/lib/ruby/gems/2.5.0/gems/netrc-0.11.0/lib/netrc.rb:45:in `check_permissions'
/usr/local/lib/ruby/gems/2.5.0/gems/netrc-0.11.0/lib/netrc.rb:52:in `read'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-trunk-1.3.1/lib/pod/command/trunk.rb:106:in `netrc'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-trunk-1.3.1/lib/pod/command/trunk/register.rb:72:in `save_token'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-trunk-1.3.1/lib/pod/command/trunk/register.rb:62:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=Permission+bits+for+%27%2FUsers%2Fsimon%2F.netrc%27+should+be+0600%2C+but+are+644&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
 - Getting error after editing a podspec
   https://github.com/CocoaPods/CocoaPods/issues/644 [closed] [4 comments]
   12 May 2017

**Comment by cikichen** [comment]
Fixed
```
chmod 0600 .netrc
```
