### ISSUE TITLE
NoMethodError - undefined method `real_path' for nil:NilClass

### ISSUE THREAD

**Issue by AntonAppreal** [CocoaPods/CocoaPods#8126]
pod install

```
/usr/local/bin/pod install
```

### Report

* What did you do?

pod install

* What did you expect to happen?
integrate cocoa pods in project

* What happened instead?

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin17]
    RubyGems : 2.7.7
        Host : Mac OS X 10.13.6 (17G65)
       Xcode : 9.4.1 (9F2000)
         Git : git version 2.15.2 (Apple Git-101.1)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : bitbucket-glide-specs - git@bitbucket.org:glidetalk/glide-specs.git @ 67d6f2c0db93ebab57f1565f358c833d7ee8db74
               master - https://github.com/CocoaPods/Specs.git @ 96c56f5f0b71d6da6ec4e14cff6d7180558a0bb3
```

### Plugins

```
cocoapods-clean       : 0.0.1
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Wristcam' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Wristcam

  target 'WristcamTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Wristcam WatchKit App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Wristcam WatchKit App

end

target 'Wristcam WatchKit Extension' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Wristcam WatchKit Extension

end
```

### Error

```
NoMethodError - undefined method `real_path' for nil:NilClass
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.6.0/lib/xcodeproj/project/object/container_item_proxy.rb:96:in `container_portal_annotation'
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.6.0/lib/xcodeproj/project/object/container_item_proxy.rb:105:in `to_hash_as'
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.6.0/lib/xcodeproj/project/object.rb:421:in `to_ascii_plist'
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.6.0/lib/xcodeproj/project.rb:293:in `block in to_ascii_plist'
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.6.0/lib/xcodeproj/project.rb:291:in `each'
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.6.0/lib/xcodeproj/project.rb:291:in `to_ascii_plist'
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.6.0/lib/xcodeproj/project.rb:360:in `block in save'
/Library/Ruby/Gems/2.3.0/gems/atomos-0.1.3/lib/atomos.rb:21:in `block in atomic_write'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/tempfile.rb:295:in `open'
/Library/Ruby/Gems/2.3.0/gems/atomos-0.1.3/lib/atomos.rb:17:in `atomic_write'
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.6.0/lib/xcodeproj/project.rb:359:in `save'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/user_project_integrator.rb:139:in `block in save_projects'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/user_project_integrator.rb:137:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/user_project_integrator.rb:137:in `save_projects'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/user_project_integrator.rb:65:in `integrate!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:591:in `block in integrate_user_project'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:588:in `integrate_user_project'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:121:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command/install.rb:41:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

**Comment by dnkoutso** [comment]
Please upload a sample app demonstrating the issue.

**Comment by AntonAppreal** [comment]
also i have tried known issues
Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=undefined+method+%60real_path%27+for+nil%3ANilClass&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

**Comment by AntonAppreal** [comment]
> Please upload a sample app demonstrating the issue.

Project is under NDA, so i can't do this. But if i create simple project just for test, pod is setup without problems.

**Comment by dnkoutso** [comment]
Apologies but it is difficult to diagnose this without one.

I believe this is a build setting within your `.xcodeproj` that can't be parsed.

Best advise is to put `puts` statements within /Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.6.0/lib/xcodeproj/project/object/container_item_proxy.rb and try to debug this.

**Comment by chrisballinger** [comment]
I noticed that 1.6.0-beta1 threw the same error for a post_install hack that used config.base_configuration_reference.real_path, and adding a nil check fixed the issue. You could try forking the xcodeproj gem and adding some more nil checks in there.

**Comment by dnkoutso** [comment]
Still need a sample here.

**Comment by AntonAppreal** [comment]
if i make sample project it works fine, the issue is in the particular xcode project file, i can't share it...
May be you know reasons in project file structure that cause this error?

**Comment by huntharo** [comment]
@dnkoutso - I was able to fix this problem for project.

***How Others Might Find their Problem***

- Make a backup of your pbxproj file or ensure it's checked into source control
- Search the pbxproj file for "Recovered references"
- If there are recovered references, search the file for the listed UUIDs
- Remove the sections that reference the recovered reference UUIDs
- Remove the recovered reference section
- Save the pbxproj file
- Run pod install again

***How I Found the Problem***
I can't post the entire project.pbxproj file publicly, but here is what I found that may allow others to fix their broken project files:

- The `/* Begin PBXFileReference section */` contained a `sourceTree="<absolute>"` reference that pointed to my home diretory
  - `7C0CC0E720182084002E42F3 /* KCKeepAwake.xcodeproj */ = {isa = PBXFileReference; lastKnownFileType = "wrapper.pb-project"; name = KCKeepAwake.xcodeproj; path = "/Users/nouser/Documents/prog/someapp/node_modules/react-native/Libraries/WebSocket/../../../react-native-keep-awake/ios/KCKeepAwake.xcodeproj"; sourceTree = "<absolute>"; };`
  - This was a duplicate project file reference
  - This was the only `<absolute>` file reference - this is why it caught my eye, that and that it was a duplicate
  - Removing this line by itself did not cause `pod install` to work
- The ID `7C0CC0E720182084002E42F3` was referenced in `/* Begin PBXContainerItemProxy section */`
  - Removing this section and the above PBXFileReference allowed `pod install` to complete
  - Note: `xcodeproj` complains about some dangling references the first time `pod install` is run after this, but it cleans them up and doesn't complain on subsequent runs
 - Following these references through the file, I was able to find that this was referenced by `/* Recovered References */` in `/* Begin PBXGroup section */`
   - There were two UUIDs references in recovered references (both of which were duplicate of other correctly referenced projects)
   - Searching the project.pbxproj file for these two UUIDs, removing the sections that reference them, then removing the recovered references section allowed `pod install` to work
   - Note: `xcodeproj` complained in this case too, if I recall correctly, but I think it cleaned up the references as well

***Sample Data from Bad pbxproj File***
As much of the reference tree as I followed:

* ` /* Begin PBXFileReference section */`
    * 7C0CC0E720182084002E42F3 /* KCKeepAwake.xcodeproj */ = {isa = PBXFileReference; lastKnownFileType = "wrapper.pb-project"; name = KCKeepAwake.xcodeproj; path = "/Users/nouser/Documents/prog/someapp/node_modules/react-native/Libraries/WebSocket/../../../react-native-keep-awake/ios/KCKeepAwake.xcodeproj"; sourceTree = "<absolute>"; };
    * `/* Begin PBXContainerItemProxy section */`
        *         7C0CC0ED20182084002E42F3 /* PBXContainerItemProxy */ = {
        *             isa = PBXContainerItemProxy;
        *             containerPortal = 7C0CC0E720182084002E42F3 /* KCKeepAwake.xcodeproj */;
        *             proxyType = 2;
        *             remoteGlobalIDString = 134814201AA4EA6300B7C361;
        *             remoteInfo = KCKeepAwake;
        *         };
        * `/* Begin PBXReferenceProxy section */`
            *         7C0CC0EE20182084002E42F3 /* libKCKeepAwake.a */ = {
            *             isa = PBXReferenceProxy;
            *             fileType = archive.ar;
            *             path = libKCKeepAwake.a;
            *             remoteRef = 7C0CC0ED20182084002E42F3 /* PBXContainerItemProxy */;
            *             sourceTree = BUILT_PRODUCTS_DIR;
            *         };
            * Appears in remoteRef field
            * `/* Begin PBXBuildFile section */`
                * 7C0CC116201820AA002E42F3 /* libKCKeepAwake.a in Frameworks */ = {isa = PBXBuildFile; fileRef = 7C0CC0EE20182084002E42F3 /* libKCKeepAwake.a */; };
                * Appears in fileRef field
            * `/* Begin PBXGroup section */`
                *         7C13C959202392AA00EB09DC /* Recovered References */ = {
                *             isa = PBXGroup;
                *             children = (
                *                 7C0CC0EE20182084002E42F3 /* libKCKeepAwake.a */,
                *                 7C432A58200731F700D2D225 /* libCodePush.a */,
                *             );
                *             name = "Recovered References";
                *             sourceTree = "<group>";
                *         };

**Comment by Anastasiiaq** [comment]
I get the same error in `CocoaPods 1.12.1`, for the `post_install` hook, which used `config.base_configuration_reference.real_path`, and adding a nil check fixed the problem.

This was because the project was using custom configuration names (not `Release` and `Debug`), and Cocoa when do `pod install` generates these configurations in the pods project (#7813) that don't have a reference to `.xcconfig` and `real_path` returns `nil`.
