### ISSUE TITLE
Pod lint doesn't find simulators.

### ISSUE THREAD

**Issue by raull** [CocoaPods/CocoaPods#8168]
* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

`pod lib lint --private --allow-warnings --sources='privateRepo,https://github.com/CocoaPods/Specs.git' --fail-fast --verbose --no-clean`

## What did you expect to happen?

Pass lint validation.

## What happened instead?

Getting an unexpected error about not finding simulators

```Building with xcodebuild.

    - WARN  | source: Git SSH URLs will NOT work for people behind firewalls configured to only allow HTTP, therefore HTTPS is preferred.
    - WARN  | [iOS] swift: The validator used Swift 3.2 by default because no Swift version was specified. To specify a Swift version during validation, add the `swift_version` attribute in your podspec. Note that usage of the `--swift-version` parameter or a `.swift-version` file is now deprecated.
    - ERROR | [iOS] unknown: Encountered an unknown error (Could not find a `ios` simulator (valid values: ). Ensure that Xcode -> Window -> Devices has at least one `ios` simulator listed or otherwise add one.
/Users/raulvillalpando/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fourflusher-2.0.1/lib/fourflusher/find.rb:106:in `usable_simulators'
/Users/raulvillalpando/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fourflusher-2.0.1/lib/fourflusher/find.rb:97:in `simulator'
/Users/raulvillalpando/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/fourflusher-2.0.1/lib/fourflusher/xcodebuild.rb:7:in `destination'
/Users/raulvillalpando/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/validator.rb:918:in `xcodebuild'
/Users/raulvillalpando/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/validator.rb:616:in `block in build_pod'
/Users/raulvillalpando/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/user_interface.rb:145:in `message'
/Users/raulvillalpando/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/validator.rb:606:in `build_pod'
/Users/raulvillalpando/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/validator.rb:371:in `block in perform_extensive_analysis'
/Users/raulvillalpando/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/validator.rb:359:in `each'
/Users/raulvillalpando/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/validator.rb:359:in `all?'
/Users/raulvillalpando/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/validator.rb:359:in `perform_extensive_analysis'
/Users/raulvillalpando/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/validator.rb:128:in `validate'
/Users/raulvillalpando/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/command/lib/lint.rb:75:in `block in run'
/Users/raulvillalpando/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/command/lib/lint.rb:60:in `each'
/Users/raulvillalpando/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/command/lib/lint.rb:60:in `run'
/Users/raulvillalpando/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/raulvillalpando/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/command.rb:52:in `run'
/Users/raulvillalpando/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.1/bin/pod:55:in `<top (required)>'
/Users/raulvillalpando/.rbenv/versions/2.5.1/bin/pod:23:in `load'
/Users/raulvillalpando/.rbenv/versions/2.5.1/bin/pod:23:in `<main>'
) during validation.

Pods workspace available at `/var/folders/mz/0v5nwgqs6xzcyl59r_gvx5xr0000gp/T/CocoaPods-Lint-20181009-73682-t95zu6-PaymentsKit/App.xcworkspace` for inspection.

[!] did not pass validation, due to 1 error.
```

## CocoaPods Environment
Tried with MacOS High Sierra and CocoaPods 1.5.2

```
   CocoaPods : 1.6.0.beta.1
        Ruby : ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin18]
    RubyGems : 2.7.6
        Host : Mac OS X 10.14 (18A391)
       Xcode : 10.0 (10A255)
         Git : git version 2.17.1 (Apple Git-112)
Ruby lib dir : /Users/raulvillalpando/.rbenv/versions/2.5.1/lib

```

**Comment by dnkoutso** [comment]
Please see this https://github.com/CocoaPods/CocoaPods/issues/8163.

going to close as if its the same issue but I will re-open if its a different one.

**Comment by dnkoutso** [comment]
Specifically https://github.com/CocoaPods/CocoaPods/issues/8163#issuecomment-427480520

**Comment by raull** [comment]
@dnkoutso That was it, thanks for the help!
