### ISSUE TITLE
undefined local variable or method `value' for #<Pod::Specification::Consumer:0x007ffef90994a8>

### ISSUE THREAD

**Issue by kylefleming** [CocoaPods/CocoaPods#819]
### Report
- What did you do?

Tried to fix `AWSiOSSDK.podspec` by adding `header_mappings_dir` to subspecs:

```
Pod::Spec.new do |s|
  s.name         =  'AWSiOSSDK'
  s.version      =  '1.4.4'
  s.license      =  'Apache 2.0'
  s.summary      =  'Amazon Web Services SDK for iOS.'
  s.homepage     =  'http://aws.amazon.com/sdkforios'
  s.author       =  { 'Amazon Web Services' => 'amazonwebservices' }
  s.source       =  { :git => 'https://github.com/aws/aws-sdk-ios.git', :tag => '1.4.4' }
  s.description  =  'The AWS SDK for iOS provides a library, code samples, and documentation for developers to build connected mobile applications using AWS.'
  s.platform     =  :ios

  s.header_mappings_dir = 'src/include'

  s.prefix_header_contents = <<-PCH
#ifdef __OBJC__
#import "AmazonLogger.h"
#import "AmazonErrorHandler.h"
#endif
  PCH

  s.subspec 'Runtime' do |ss|
    ss.header_mappings_dir = 'src/include'
    ss.source_files = "src/Amazon.Runtime/**/*.m", "src/include"
    ss.dependency 'AWSiOSSDK/DynamoDB'
    ss.dependency 'SBJson'
  end

  %w[ AutoScaling CloudWatch DynamoDB EC2 ElasticLoadBalancing S3 SES SNS SQS STS SimpleDB ].each do |name|
    s.subspec name do |ss|
      ss.header_mappings_dir = 'src/include'
      ss.source_files = "src/Amazon.#{name}/**/*.m", "src/include/#{name}"
      ss.dependency 'AWSiOSSDK/Runtime'
    end
  end
end
```

and then ran `pod install`. It appears there's a bug in `Core` at line `lib/cocoapods-core/specification/consumer.rb:250`
### Stack

```
   CocoaPods : 0.17.0.rc1
        Ruby : ruby 1.9.3p194 (2012-04-20 revision 35410) [x86_64-darwin11.4.2]
    RubyGems : 1.8.24
        Host : Mac OS X 10.8.2 (12C3012)
       Xcode : 4.6 (4H127)
Ruby lib dir : /Users/kyle/.rvm/rubies/ruby-1.9.3-p194/lib
Repositories : {redacted}
               master - https://github.com/CocoaPods/Specs.git @ 31211a08031383ed1966b1bd81a1bdcfb3cd17df
```
### Podfile

``` ruby
          platform :ios, '5.0'

inhibit_all_warnings!

pod 'AFNetworking', '0.10.0' # crashes at higher versions
pod 'AFOAuth2Client', :git => '{redacted}'
pod 'BlocksKit', '~> 1.8'
pod 'CocoaLumberjack', '~> 1.6'
pod 'DDPageControl', '~> 0.1'
pod 'GRMustache', '~> 5.5'
pod 'GoogleAnalytics-iOS-SDK', '~> 2.0beta4'
pod 'HockeySDK', '~> 3.0'
pod 'JASidePanels', '~> 1.2'
pod 'JSONKit', '~> 1.5pre'
pod 'MBProgressHUD', '~> 0.5'
pod 'Reachability', '~> 3.1'
pod 'SDWebImage', '2.7'
pod 'SSDataKit', '~> 0.1'
pod 'SSKeychain', '~> 0.2'
pod 'SSPullToRefresh', '~> 1.1'
pod 'SSToolkit', '~> 1.0'
pod 'SVPullToRefresh', '~> 0.4'
pod 'TTTAttributedLabel', '~> 1.6'
pod 'AWSiOSSDK/S3', '~> 1.4'
pod 'iCarousel', '~> 1.7'
pod 'UrbanAirship-iOS-SDK', '~> 1.3'
```
### Error

```
undefined local variable or method `value' for #<Pod::Specification::Consumer:0x007f970cbf0ba8>
/Users/kyle/.rvm/gems/ruby-1.9.3-p194@ios/gems/cocoapods-core-0.17.0.rc1/lib/cocoapods-core/specification/consumer.rb:250:in `merge_values'
/Users/kyle/.rvm/gems/ruby-1.9.3-p194@ios/gems/cocoapods-core-0.17.0.rc1/lib/cocoapods-core/specification/consumer.rb:189:in `value_with_inheritance'
/Users/kyle/.rvm/gems/ruby-1.9.3-p194@ios/gems/cocoapods-core-0.17.0.rc1/lib/cocoapods-core/specification/consumer.rb:166:in `value_for_attribute'
/Users/kyle/.rvm/gems/ruby-1.9.3-p194@ios/gems/cocoapods-core-0.17.0.rc1/lib/cocoapods-core/specification/consumer.rb:54:in `block in spec_attr_accessor'
/Users/kyle/.rvm/gems/ruby-1.9.3-p194@ios/gems/cocoapods-0.17.0.rc1/lib/cocoapods/installer/file_references_installer.rb:164:in `block in header_mappings'
/Users/kyle/.rvm/gems/ruby-1.9.3-p194@ios/gems/cocoapods-0.17.0.rc1/lib/cocoapods/installer/file_references_installer.rb:162:in `each'
/Users/kyle/.rvm/gems/ruby-1.9.3-p194@ios/gems/cocoapods-0.17.0.rc1/lib/cocoapods/installer/file_references_installer.rb:162:in `header_mappings'
/Users/kyle/.rvm/gems/ruby-1.9.3-p194@ios/gems/cocoapods-0.17.0.rc1/lib/cocoapods/installer/file_references_installer.rb:117:in `block (2 levels) in link_headers'
/Users/kyle/.rvm/gems/ruby-1.9.3-p194@ios/gems/cocoapods-0.17.0.rc1/lib/cocoapods/installer/file_references_installer.rb:111:in `each'
/Users/kyle/.rvm/gems/ruby-1.9.3-p194@ios/gems/cocoapods-0.17.0.rc1/lib/cocoapods/installer/file_references_installer.rb:111:in `block in link_headers'
/Users/kyle/.rvm/gems/ruby-1.9.3-p194@ios/gems/cocoapods-0.17.0.rc1/lib/cocoapods/user_interface.rb:107:in `message'
/Users/kyle/.rvm/gems/ruby-1.9.3-p194@ios/gems/cocoapods-0.17.0.rc1/lib/cocoapods/installer/file_references_installer.rb:109:in `link_headers'
/Users/kyle/.rvm/gems/ruby-1.9.3-p194@ios/gems/cocoapods-0.17.0.rc1/lib/cocoapods/installer/file_references_installer.rb:39:in `install!'
/Users/kyle/.rvm/gems/ruby-1.9.3-p194@ios/gems/cocoapods-0.17.0.rc1/lib/cocoapods/installer.rb:276:in `install_file_references'
/Users/kyle/.rvm/gems/ruby-1.9.3-p194@ios/gems/cocoapods-0.17.0.rc1/lib/cocoapods/installer.rb:109:in `block in generate_pods_project'
/Users/kyle/.rvm/gems/ruby-1.9.3-p194@ios/gems/cocoapods-0.17.0.rc1/lib/cocoapods/user_interface.rb:46:in `section'
/Users/kyle/.rvm/gems/ruby-1.9.3-p194@ios/gems/cocoapods-0.17.0.rc1/lib/cocoapods/installer.rb:106:in `generate_pods_project'
/Users/kyle/.rvm/gems/ruby-1.9.3-p194@ios/gems/cocoapods-0.17.0.rc1/lib/cocoapods/installer.rb:86:in `install!'
/Users/kyle/.rvm/gems/ruby-1.9.3-p194@ios/gems/cocoapods-0.17.0.rc1/lib/cocoapods/command/project.rb:40:in `run_install_with_update'
/Users/kyle/.rvm/gems/ruby-1.9.3-p194@ios/gems/cocoapods-0.17.0.rc1/lib/cocoapods/command/project.rb:70:in `run'
/Users/kyle/.rvm/gems/ruby-1.9.3-p194@ios/gems/claide-0.2.0/lib/claide.rb:535:in `run'
/Users/kyle/.rvm/gems/ruby-1.9.3-p194@ios/gems/cocoapods-0.17.0.rc1/lib/cocoapods/command.rb:36:in `run'
/Users/kyle/.rvm/gems/ruby-1.9.3-p194@ios/gems/cocoapods-0.17.0.rc1/bin/pod:16:in `<top (required)>'
/Users/kyle/.rvm/gems/ruby-1.9.3-p194@ios/bin/pod:19:in `load'
/Users/kyle/.rvm/gems/ruby-1.9.3-p194@ios/bin/pod:19:in `<main>'
/Users/kyle/.rvm/gems/ruby-1.9.3-p194@ios/bin/ruby_noexec_wrapper:14:in `eval'
/Users/kyle/.rvm/gems/ruby-1.9.3-p194@ios/bin/ruby_noexec_wrapper:14:in `<main>'
```

**Comment by CoolKii** [comment]
Invalid `Podfile` file: undefined local variable or method `ios' for #<Pod::Podfile:0x007fddd248e650>.

**Comment by kylefleming** [comment]
@CoolKii If you're experiencing a crash, please file it as a new issue, since this one has been resolved and closed. Thanks.
