### ISSUE TITLE
Internal server error when pushing new pod

### ISSUE THREAD

**Issue by kawoou** [CocoaPods/CocoaPods#8200]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod trunk push --verbose AnyDate.podspec`

## What did you expect to happen?

Publish pod.

## What happened instead?

```bash
opening connection to trunk.cocoapods.org:443...
opened
starting SSL for trunk.cocoapods.org:443...
SSL established
<- "POST /api/v1/pods?allow_warnings=false HTTP/1.1\r\nContent-Type: application/json; charset=utf-8\r\nAccept: application/json; charset=utf-8\r\nUser-Agent: CocoaPods/1.6.0.beta.1\r\nAuthorization: Token 55816a8c2dfa9c6478b83acaf960cff4\r\nAccept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3\r\nHost: trunk.cocoapods.org\r\nContent-Length: 531\r\n\r\n"
<- "{\"name\":\"AnyDate\",\"version\":\"1.1.0\",\"summary\":\"Swifty Date & Time API inspired from Java 8 DateTime API.\",\"license\":{\"type\":\"MIT\",\"file\":\"LICENSE\"},\"homepage\":\"https://github.com/kawoou/AnyDate\",\"authors\":{\"Jungwon An\":\"kawoou@kawoou.kr\"},\"social_media_url\":\"http://fb.com/kawoou\",\"source\":{\"git\":\"https://github.com/Kawoou/AnyDate.git\",\"tag\":\"v1.1.0\"},\"source_files\":\"Sources/**/*.{swift}\",\"frameworks\":\"Foundation\",\"module_name\":\"AnyDate\",\"requires_arc\":true,\"platforms\":{\"ios\":\"8.0\",\"tvos\":\"9.0\",\"osx\":\"10.10\",\"watchos\":\"2.0\"}}\n"
-> "HTTP/1.1 500 Internal Server Error\r\n"
-> "Date: Thu, 18 Oct 2018 13:43:26 GMT\r\n"
-> "Connection: keep-alive\r\n"
-> "Strict-Transport-Security: max-age=31536000\r\n"
-> "Content-Type: application/json\r\n"
-> "Content-Length: 141\r\n"
-> "X-Content-Type-Options: nosniff\r\n"
-> "Server: thin 1.6.2 codename Doc Brown\r\n"
-> "Via: 1.1 vegur\r\n"
-> "\r\n"
reading 141 bytes...
-> "{\"error\":\"An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later.\"}"
read 141 bytes
Conn keep-alive
[!] An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later.
```

### Stack

```
   CocoaPods : 1.6.0.beta.1
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14 (18A391)
       Xcode : 10.0 (10A255)
         Git : git version 2.17.1 (Apple Git-112)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ abd59b8f20605113dfe9a7832b1ea0a8672df588
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-clean       : 0.0.1
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

https://github.com/kawoou/AnyDate/blob/v1.1.0/AnyDate.podspec

**Comment by seanbdoherty** [comment]
Same issue on cocoapods version 1.5.3.

**Comment by MKGitHub** [comment]
Same issue right NOW, so annoying!

**Comment by gereons** [comment]
+1

**Comment by aserrr** [comment]
+1

**Comment by nabilsafatli** [comment]
Same happening here: https://cocoapods.org/pods/Clappr

**Comment by podkovyrin** [comment]
Same with https://cocoapods.org/pods/bls-signatures-pod

**Comment by podkovyrin** [comment]
Increasing pod version worked for me

**Comment by MKGitHub** [comment]
> Increasing pod version worked for me

Could you be more specific exactly what you did???

**Comment by segiddins** [comment]
> … opened this issue 6 hours ago … still no news… PERFECT!

sorry, didnt see it until now.

it looks like we're seeing some 500s, backtrace is as follows for anyone who wants to look into the code

```
18 Oct 2018 04:12:55.430201 <190>1 2018-10-18T11:12:55.142778+00:00 app web.2 - - /app/vendor/ruby-2.1.3/lib/ruby/2.1.0/net/http.rb:879:in `initialize': execution expired (Net::OpenTimeout)
	from /app/vendor/ruby-2.1.3/lib/ruby/2.1.0/net/http.rb:879:in `open'
	from /app/vendor/ruby-2.1.3/lib/ruby/2.1.0/net/http.rb:879:in `block in connect'
	from /app/vendor/ruby-2.1.3/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'
	from /app/vendor/ruby-2.1.3/lib/ruby/2.1.0/timeout.rb:101:in `call'
	from /app/vendor/ruby-2.1.3/lib/ruby/2.1.0/timeout.rb:101:in `timeout'
	from /app/vendor/ruby-2.1.3/lib/ruby/2.1.0/net/http.rb:878:in `connect'
	from /app/vendor/ruby-2.1.3/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
	from /app/vendor/ruby-2.1.3/lib/ruby/2.1.0/net/http.rb:852:in `start'
	from /app/vendor/bundle/ruby/2.1.0/gems/nap-1.1.0/lib/rest/request.rb:183:in `perform'
	from /app/vendor/bundle/ruby/2.1.0/gems/nap-1.1.0/lib/rest/request.rb:192:in `perform'
	from /app/vendor/bundle/ruby/2.1.0/gems/nap-1.1.0/lib/rest.rb:100:in `post'
	from /app/lib/webhook.rb:151:in `block (4 levels) in start_child_process_thread'
	from /app/lib/webhook.rb:150:in `fork'
	from /app/lib/webhook.rb:150:in `block (3 levels) in start_child_process_thread'
	from /app/lib/webhook.rb:149:in `each'
	from /app/lib/webhook.rb:149:in `block (2 levels) in start_child_process_thread'
	from /app/lib/webhook.rb:132:in `loop'
	from /app/lib/webhook.rb:132:in `block in start_child_process_thread'
	from /app/lib/webhook.rb:131:in `fork'
	from /app/lib/webhook.rb:131:in `start_child_process_thread'
	from /app/lib/webhook.rb:62:in `enable'
	from /app/config/init.rb:62:in `<top (required)>'
	from /app/app/controllers/app_controller.rb:4:in `require'
	from /app/app/controllers/app_controller.rb:4:in `<top (required)>'
	from /app/config.ru:4:in `require'
	from /app/config.ru:4:in `block in <main>'
	from /app/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:55:in `instance_eval'
	from /app/vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:55:in `initialize'
	from /app/config.ru:1:in `new'
	from /app/config.ru:1:in `<main>'
	from /app/vendor/bundle/ruby/2.1.0/gems/thin-1.6.2/lib/rack/adapter/loader.rb:33:in `eval'
	from /app/vendor/bundle/ruby/2.1.0/gems/thin-1.6.2/lib/rack/adapter/loader.rb:33:in `load'
	from /app/vendor/bundle/ruby/2.1.0/gems/thin-1.6.2/lib/rack/adapter/loader.rb:42:in `for'
	from /app/vendor/bundle/ruby/2.1.0/gems/thin-1.6.2/lib/thin/controllers/controller.rb:170:in `load_adapter'
	from /app/vendor/bundle/ruby/2.1.0/gems/thin-1.6.2/lib/thin/controllers/controller.rb:74:in `start'
	from /app/vendor/bundle/ruby/2.1.0/gems/thin-1.6.2/lib/thin/runner.rb:199:in `run_command'
	from /app/vendor/bundle/ruby/2.1.0/gems/thin-1.6.2/lib/thin/runner.rb:155:in `run!'
	from /app/vendor/bundle/ruby/2.1.0/gems/thin-1.6.2/bin/thin:6:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.1.0/bin/thin:23:in `load'
	from /app/vendor/bundle/ruby/2.1.0/bin/thin:23:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.1.0/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:74:in `load'
	from /app/vendor/bundle/ruby/2.1.0/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
	from /app/vendor/bundle/ruby/2.1.0/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.1.0/gems/bundler-1.15.2/lib/bundler/cli.rb:360:in `exec'
	from /app/vendor/bundle/ruby/2.1.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.1.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.1.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
	from /app/vendor/bundle/ruby/2.1.0/gems/bundler-1.15.2/lib/bundler/cli.rb:20:in `dispatch'
	from /app/vendor/bundle/ruby/2.1.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
	from /app/vendor/bundle/ruby/2.1.0/gems/bundler-1.15.2/lib/bundler/cli.rb:10:in `start'
	from /app/vendor/bundle/ruby/2.1.0/gems/bundler-1.15.2/exe/bundle:30:in `block in <top (required)>'
	from /app/vendor/bundle/ruby/2.1.0/gems/bundler-1.15.2/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
	from /app/vendor/bundle/ruby/2.1.0/gems/bundler-1.15.2/exe/bundle:22:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.1.0/bin/bundle:19:in `load'
	from /app/vendor/bundle/ruby/2.1.0/bin/bundle:19:in `<main>'
```

**Comment by aserrr** [comment]
Seems to be fixed. Just published successfully.

**Comment by gereons** [comment]
Works for me again as well, didn't need to bump the version.

**Comment by MKGitHub** [comment]
I could push a new version but the page at https://cocoapods.org/pods/ says "Internal Server Error"

**Comment by kawoou** [comment]
I have confirmed that push a new version successful.
Thank you for your resolve.

But, I don't close the issue because there seems to be other new issues.

**Comment by dnkoutso** [comment]
Hello, thanks for the reports everyone. This might have been a blip although I am personally uncertain what has happened.

It seems to be resolved (via magic...). For now I am going to close this issue and continue monitoring reports.

If you *still* get a 500 when trying to publish please *do* post here and we will try to diagnose it.

**Comment by dnkoutso** [comment]
@MKGitHub thanks we will try to take a look today/this week.

I am still monitoring this so don't worry if it remains closed. It might actually be a better idea to keep the issue in the trunk repo instead of here.
