### ISSUE TITLE
CP raise a error when a pod uses a pre-release version in other pod

### ISSUE THREAD

**Issue by Whirlwind** [CocoaPods/CocoaPods#8216]
I using CocoaPods v1.6.0.beta.1, I get a error:
```

  In snapshot (Podfile.lock):
    TTTracker (= 1.1.11-rc.0, ~> 1.1.1)

  In Podfile:
    TTPushSDK (from `git url`, commit `575fad426b1e7581458991f529fe42e81095c297`) was resolved to 0.1.3, which depends on
      TTTracker

There are only pre-release versions available satisfying the following requirements:

	'TTTracker', '= 1.1.11-rc.0, ~> 1.1.1'

	'TTTracker', '>= 0'

You should explicitly specify the version in order to install a pre-release version
```

I check my Podfile, it does not specify the `TTTracker`. But in my Podfile.lock, I found that:
```
  - AWETrackerService (0.1.8):
    - BDTracker (= 0.1.3-rc.0)
    - HTSServiceKit
    - TTInstallService (= 1.1.3.2)
    - TTNetworkManager (~> 2.2.8)
    - TTTracker (= 1.1.11-rc.0)
    - UMengAnalytics (~> 4.1.4)
```
 The TTTracker's version is from other dependency, and it uses a pre-release version. I think it should be OK. Is it a bug?

**Comment by Whirlwind** [comment]
It works in CocoaPods v1.6.0.beta.2. I close this issue.

**Comment by Whirlwind** [comment]
It still exists in v1.6.0.beta.2. But at the first it is OK, and it raises error after run `pod install` again.

```
  In snapshot (Podfile.lock):
    TTTracker (= 1.1.11-rc.0, ~> 1.1.1)

  In Podfile:
    TTPushSDK (from `git url`, commit `575fad426b1e7581458991f529fe42e81095c297`) was resolved to 0.1.3, which depends on
      TTTracker

There are only pre-release versions available satisfying the following requirements:

	'TTTracker', '= 1.1.11-rc.0, ~> 1.1.1'

	'TTTracker', '>= 0'

You should explicitly specify the version in order to install a pre-release version

```

**Comment by Whirlwind** [comment]
It works in CocoaPods v1.5.3.

**Comment by amorde** [comment]
@Whirlwind I believe this is just a warning that only a pre-release version satisfies the requirements, and therefore CocoaPods is recommending to make it explicit by using `pod 'TTTracker', '1.1.11-rc.0'`

**Comment by Whirlwind** [comment]
The prerelease version is required by other pod , and the pod make it 'explicit'. I think the prerelease pod should be written in my podfile.

**Comment by amorde** [comment]
Interesting, this might be a bug then. Will need to look into it

**Comment by amorde** [comment]
do you specify another version requirement in your Podfile? ex. do you have something like `pod 'TTTracker', '>= 1.1.0'`?

**Comment by Whirlwind** [comment]
No, the `TTTracker` could not found in my Podfile. It is required by other pod.

**Comment by amorde** [comment]
> In snapshot (Podfile.lock):
    TTTracker (= 1.1.11-rc.0, ~> 1.1.1)

It looks like the requirement `~> 1.1.1` is coming from somewhere, and without enough information this is difficult to debug. It must be the requirement of a pod, in your Podfile, or was previously in your Podfile and is therefore including in the Podfile.lock

**Comment by Whirlwind** [comment]
`TTTracker` is required by two pods, so the `Podfile.lock` show `TTTracker (= 1.1.11-rc.0, ~> 1.1.1)`.
But the Podfile not require `TTTracker`.

**Comment by Whirlwind** [comment]
I get this error in v1.5.3.....

```
	11: from /Users/whirlwind/.rvm/gems/ruby-2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:779:in `resolve_dependencies'
	10: from /Users/whirlwind/.rvm/gems/ruby-2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
	 9: from /Users/whirlwind/.rvm/gems/ruby-2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:781:in `block in resolve_dependencies'
	 8: from /Users/whirlwind/.rvm/gems/ruby-2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:123:in `resolve'
	 7: from /Users/whirlwind/.rvm/gems/ruby-2.5.0/gems/molinillo-0.6.5/lib/molinillo/resolver.rb:43:in `resolve'
	 6: from /Users/whirlwind/.rvm/gems/ruby-2.5.0/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:182:in `resolve'
	 5: from /Users/whirlwind/.rvm/gems/ruby-2.5.0/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:254:in `process_topmost_state'
	 4: from /Users/whirlwind/.rvm/gems/ruby-2.5.0/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:684:in `attempt_to_activate'
	 3: from /Users/whirlwind/.rvm/gems/ruby-2.5.0/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:308:in `unwind_for_conflict'
	 2: from /Users/whirlwind/.rvm/gems/ruby-2.5.0/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:308:in `tap'
	 1: from /Users/whirlwind/.rvm/gems/ruby-2.5.0/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:310:in `block in unwind_for_conflict'
/Users/whirlwind/.rvm/gems/ruby-2.5.0/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:328:in `raise_error_unless_state': [!] [!] CocoaPods could not find compatible versions for pod "TTTracker": (Pod::NoSpecFoundError)
  In snapshot (Podfile.lock):
    TTTracker (= 1.1.11-rc.0, ~> 1.1.1)

  In Podfile:
    TTPushSDK (from `git@myprivate.com:IOS/tt_pods_push_sdk.git`, commit `575fad426b1e7581458991f529fe42e81095c297`) was resolved to 0.1.3, which depends on
      TTTracker

Due to the previous naïve CocoaPods resolver, you were using a pre-release version of `TTTracker`, without explicitly asking for a pre-release version, which now leads to a conflict. Please decide to either use that pre-release version by adding the version requirement to your Podfile (e.g. `pod 'TTTracker', '= 1.1.11-rc.0, ~> 1.1.1'`) or revert to a stable version by running `pod update TTTracker`.
```

**Comment by Whirlwind** [comment]
Is it a bug? or CocoaPods still want to make the `TTTracker` explicit?

**Comment by amorde** [comment]
Ah ok, so there's 2 version requirements coming from 2 different podspecs. I guess you could argue that there shouldn't be a warning here, but that would be quite difficult to implement. would love to hear other opinions on this

**Comment by Whirlwind** [comment]
Now, there are 3 pods are pre-release version, and they are required by other pods. I must specify them in my Podfile. But I don't know what the pod to do. So I don't want to write it in my Podfile. Because if the pre-release pods are removed or updated from the dependencies, I could forget to update/remove them in my Podfile.

**Comment by amorde** [comment]
Yes I understand, you make a valid point. However this is just a warning, you can ignore if you don't mind. I think the general idea was that pods should be depending on pre-release versions but I am lacking the context of when this was implemented

**Comment by Whirlwind** [comment]
It is a error, not warning.... I could not ignore it...

**Comment by amorde** [comment]
sounds like a bug then
