### ISSUE TITLE
NoMethodError - undefined method `app_specification?' for #<Pod::Specification>

### ISSUE THREAD

**Issue by amorde** [CocoaPods/CocoaPods#8290]
* [X] 🌈 I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

`pod install`

## What did you expect to happen?

The pods to be installed successfully

## What happened instead?

A crash occurred with the following stacktrace:

```
NoMethodError - undefined method `app_specification?' for #<Pod::Specification name="Alamofire">
/usr/local/Cellar/ruby/2.4.3_1/lib/ruby/2.4.0/delegate.rb:87:in `method_missing'
/Users/eric/dev/AppSpecIssue/.bundle/ruby/2.4.0/bundler/gems/CocoaPods-b49c9a1c79fe/lib/cocoapods/resolver.rb:109:in `block (3 levels) in resolver_specs_by_target'
/usr/local/Cellar/ruby/2.4.3_1/lib/ruby/2.4.0/set.rb:324:in `each_key'
/usr/local/Cellar/ruby/2.4.3_1/lib/ruby/2.4.0/set.rb:324:in `each'
/Users/eric/dev/AppSpecIssue/.bundle/ruby/2.4.0/bundler/gems/CocoaPods-b49c9a1c79fe/lib/cocoapods/resolver.rb:107:in `map'
/Users/eric/dev/AppSpecIssue/.bundle/ruby/2.4.0/bundler/gems/CocoaPods-b49c9a1c79fe/lib/cocoapods/resolver.rb:107:in `block (2 levels) in resolver_specs_by_target'
/Users/eric/dev/AppSpecIssue/.bundle/ruby/2.4.0/bundler/gems/CocoaPods-b49c9a1c79fe/lib/cocoapods/resolver.rb:101:in `each'
/Users/eric/dev/AppSpecIssue/.bundle/ruby/2.4.0/bundler/gems/CocoaPods-b49c9a1c79fe/lib/cocoapods/resolver.rb:101:in `block in resolver_specs_by_target'
/Users/eric/dev/AppSpecIssue/.bundle/ruby/2.4.0/bundler/gems/CocoaPods-b49c9a1c79fe/lib/cocoapods/resolver.rb:100:in `tap'
/Users/eric/dev/AppSpecIssue/.bundle/ruby/2.4.0/bundler/gems/CocoaPods-b49c9a1c79fe/lib/cocoapods/resolver.rb:100:in `resolver_specs_by_target'
/Users/eric/dev/AppSpecIssue/.bundle/ruby/2.4.0/bundler/gems/CocoaPods-b49c9a1c79fe/lib/cocoapods/resolver.rb:89:in `resolve'
/Users/eric/dev/AppSpecIssue/.bundle/ruby/2.4.0/bundler/gems/CocoaPods-b49c9a1c79fe/lib/cocoapods/installer/analyzer.rb:931:in `block in resolve_dependencies'
/Users/eric/dev/AppSpecIssue/.bundle/ruby/2.4.0/bundler/gems/CocoaPods-b49c9a1c79fe/lib/cocoapods/user_interface.rb:64:in `section'
/Users/eric/dev/AppSpecIssue/.bundle/ruby/2.4.0/bundler/gems/CocoaPods-b49c9a1c79fe/lib/cocoapods/installer/analyzer.rb:929:in `resolve_dependencies'
/Users/eric/dev/AppSpecIssue/.bundle/ruby/2.4.0/bundler/gems/CocoaPods-b49c9a1c79fe/lib/cocoapods/installer/analyzer.rb:113:in `analyze'
/Users/eric/dev/AppSpecIssue/.bundle/ruby/2.4.0/bundler/gems/CocoaPods-b49c9a1c79fe/lib/cocoapods/installer.rb:292:in `analyze'
/Users/eric/dev/AppSpecIssue/.bundle/ruby/2.4.0/bundler/gems/CocoaPods-b49c9a1c79fe/lib/cocoapods/installer.rb:172:in `block in resolve_dependencies'
/Users/eric/dev/AppSpecIssue/.bundle/ruby/2.4.0/bundler/gems/CocoaPods-b49c9a1c79fe/lib/cocoapods/user_interface.rb:64:in `section'
/Users/eric/dev/AppSpecIssue/.bundle/ruby/2.4.0/bundler/gems/CocoaPods-b49c9a1c79fe/lib/cocoapods/installer.rb:171:in `resolve_dependencies'
/Users/eric/dev/AppSpecIssue/.bundle/ruby/2.4.0/bundler/gems/CocoaPods-b49c9a1c79fe/lib/cocoapods/installer.rb:134:in `install!'
/Users/eric/dev/AppSpecIssue/.bundle/ruby/2.4.0/bundler/gems/CocoaPods-b49c9a1c79fe/lib/cocoapods/command/install.rb:48:in `run'
/Users/eric/dev/AppSpecIssue/.bundle/ruby/2.4.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/eric/dev/AppSpecIssue/.bundle/ruby/2.4.0/bundler/gems/CocoaPods-b49c9a1c79fe/lib/cocoapods/command.rb:52:in `run'
/Users/eric/dev/AppSpecIssue/.bundle/ruby/2.4.0/bundler/gems/CocoaPods-b49c9a1c79fe/bin/pod:55:in `<top (required)>'
/Users/eric/dev/AppSpecIssue/.bundle/ruby/2.4.0/bin/pod:23:in `load'
/Users/eric/dev/AppSpecIssue/.bundle/ruby/2.4.0/bin/pod:23:in `<top (required)>'
/Users/eric/.gem/ruby/2.4.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `load'
/Users/eric/.gem/ruby/2.4.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `kernel_load'
/Users/eric/.gem/ruby/2.4.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:28:in `run'
/Users/eric/.gem/ruby/2.4.0/gems/bundler-1.16.1/lib/bundler/cli.rb:424:in `exec'
/Users/eric/.gem/ruby/2.4.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/eric/.gem/ruby/2.4.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/eric/.gem/ruby/2.4.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/Users/eric/.gem/ruby/2.4.0/gems/bundler-1.16.1/lib/bundler/cli.rb:27:in `dispatch'
/Users/eric/.gem/ruby/2.4.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/Users/eric/.gem/ruby/2.4.0/gems/bundler-1.16.1/lib/bundler/cli.rb:18:in `start'
/Users/eric/.gem/ruby/2.4.0/gems/bundler-1.16.1/exe/bundle:30:in `block in <top (required)>'
/Users/eric/.gem/ruby/2.4.0/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
/Users/eric/.gem/ruby/2.4.0/gems/bundler-1.16.1/exe/bundle:22:in `<top (required)>'
/Users/eric/.gem/ruby/2.4.0/bin/bundle:23:in `load'
/Users/eric/.gem/ruby/2.4.0/bin/bundle:23:in `<main>'
```

### Stack

```
   CocoaPods : 1.6.0.beta.2
        Ruby : ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-darwin17]
    RubyGems : 2.6.14
        Host : Mac OS X 10.14 (18A391)
       Xcode : 10.0 (10A255)
         Git : git version 2.17.1 (Apple Git-112)
Ruby lib dir : /usr/local/Cellar/ruby/2.4.3_1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 79391244f11a73f1b179c1643db014137eb4e8f7
```

### Installation Source

```
Executable Path: /Users/eric/dev/AppSpecIssue/.bundle/ruby/2.4.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
target 'AppSpecIssue' do
  use_frameworks!
  pod 'Alamofire'
end
```

A sample project is attached - it uses bundler to install & run CocoaPods
[SampleProject.zip](https://github.com/CocoaPods/CocoaPods/files/2593133/SampleProject.zip)

**Comment by amorde** [comment]
is it possible its just an issue with the gemspec? it seems like I have an older version of Core

**Comment by amorde** [comment]
yup, actually just my mistake. I forgot to pull in the latest from Core.
