### ISSUE TITLE
Uninitialized constant Nanaimo::Reader::StringScanner after installing Nanaimo

### ISSUE THREAD

**Issue by matibzurovski** [CocoaPods/CocoaPods#8298]
* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod install`

## What did you expect to happen?

Install all pod dependencies correctly.

## What happened instead?

Got an the Nanaimo issue. I've seen old issues being solved after updating the gem version. I've tried that already and didn't work out.
I am using version `0.2.6`:
```bash
$ gem which nanaimo
/Users/matias/.rvm/gems/jruby-9.2.0.0@global/gems/nanaimo-0.2.6/lib/nanaimo.rb
```

### Stack

```
   CocoaPods : 1.5.3
        Ruby : jruby 9.2.0.0 (2.5.0) 2018-05-24 81156a8 Java HotSpot(TM) 64-Bit Server VM 25.131-b11 on 1.8.0_131-b11 +jit [darwin-x86_64]
    RubyGems : 2.7.6
        Host : Mac OS X 10.14.1 (18B75)
       Xcode : 10.1 (10B61)
         Git : git version 2.17.2 (Apple Git-113)
Ruby lib dir : /Users/matias/.rvm/rubies/jruby-9.2.0.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ e842b97e245ee143d3bdbc382ceb47dd53b1a706
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '10.0'
use_frameworks!

workspace 'MySDK'

project 'sdk/MySDK.xcodeproj'

target 'MySDK' do
    project 'sdk/MySDK.xcodeproj'
    pod 'Unbox'
end
```

### Error

```
NameError - uninitialized constant Nanaimo::Reader::StringScanner
org/jruby/RubyModule.java:3526:in `const_missing'
/Users/matias/.rvm/rubies/jruby-9.2.0.0/lib/ruby/gems/shared/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:97:in `initialize'
/Users/matias/.rvm/rubies/jruby-9.2.0.0/lib/ruby/gems/shared/gems/xcodeproj-1.7.0/lib/xcodeproj/plist.rb:27:in `read_from_path'
/Users/matias/.rvm/rubies/jruby-9.2.0.0/lib/ruby/gems/shared/gems/xcodeproj-1.7.0/lib/xcodeproj/project.rb:206:in `initialize_from_file'
/Users/matias/.rvm/rubies/jruby-9.2.0.0/lib/ruby/gems/shared/gems/xcodeproj-1.7.0/lib/xcodeproj/project.rb:108:in `open'
/Users/matias/.rvm/rubies/jruby-9.2.0.0/lib/ruby/gems/shared/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:918:in `block in inspect_targets_to_integrate'
org/jruby/RubyHash.java:1396:in `each'
/Users/matias/.rvm/rubies/jruby-9.2.0.0/lib/ruby/gems/shared/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:917:in `block in inspect_targets_to_integrate'
/Users/matias/.rvm/rubies/jruby-9.2.0.0/lib/ruby/gems/shared/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
/Users/matias/.rvm/rubies/jruby-9.2.0.0/lib/ruby/gems/shared/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:912:in `inspect_targets_to_integrate'
/Users/matias/.rvm/rubies/jruby-9.2.0.0/lib/ruby/gems/shared/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:78:in `analyze'
/Users/matias/.rvm/rubies/jruby-9.2.0.0/lib/ruby/gems/shared/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:243:in `analyze'
/Users/matias/.rvm/rubies/jruby-9.2.0.0/lib/ruby/gems/shared/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:154:in `block in resolve_dependencies'
/Users/matias/.rvm/rubies/jruby-9.2.0.0/lib/ruby/gems/shared/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
/Users/matias/.rvm/rubies/jruby-9.2.0.0/lib/ruby/gems/shared/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:153:in `resolve_dependencies'
/Users/matias/.rvm/rubies/jruby-9.2.0.0/lib/ruby/gems/shared/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:116:in `install!'
/Users/matias/.rvm/rubies/jruby-9.2.0.0/lib/ruby/gems/shared/gems/cocoapods-1.5.3/lib/cocoapods/command/install.rb:41:in `run'
/Users/matias/.rvm/rubies/jruby-9.2.0.0/lib/ruby/gems/shared/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/matias/.rvm/rubies/jruby-9.2.0.0/lib/ruby/gems/shared/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
/Users/matias/.rvm/rubies/jruby-9.2.0.0/lib/ruby/gems/shared/gems/cocoapods-1.5.3/bin/pod:55:in `<main>'
org/jruby/RubyKernel.java:994:in `load'
/Users/matias/.rvm/rubies/jruby-9.2.0.0/bin/pod:1:in `<eval>'
org/jruby/RubyKernel.java:1037:in `eval'
/Users/matias/.rvm/gems/jruby-9.2.0.0/bin/jruby_executable_hooks:24:in `<main>'
```

**Comment by segiddins** [comment]
Hm, I’m not sure we’ve tested anything on jruby at all

**Comment by matibzurovski** [comment]
Seems there was a big mess on my gems environment. Not sure why it complained about `Nanaimo`, but I actually solved it by removing `rvm` and cleaning a little bit the path were gems are installed.
