### ISSUE TITLE
Can't push pod to trunk but passes local validation

### ISSUE THREAD

**Issue by SoolyChristy** [CocoaPods/CocoaPods#8311]
Hi, 
I'm trying to push a pod to the trunk.

It does pass local validation:
```
$ pod lib lint
Ignoring ffi-1.9.25 because its extensions are not built.  Try: gem pristine ffi --version 1.9.25

 -> PermissionDirector (0.0.2)
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | [iOS] xcodebuild:  note: Planning build
    - NOTE  | [iOS] xcodebuild:  note: Constructing build description
    - NOTE  | [iOS] xcodebuild:  warning: Skipping code signing because the target does not have an Info.plist file. (in target 'App')

PermissionDirector passed validation.
```

However when trying to push to the trunk I get:
```
 -> PermissionDirector (0.0.2)
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | [iOS] xcodebuild:  note: Planning build
    - NOTE  | [iOS] xcodebuild:  note: Constructing build description
    - NOTE  | [iOS] xcodebuild:  warning: Skipping code signing because the target does not have an Info.plist file. (in target 'App')

opening connection to trunk.cocoapods.org:443...
opened
starting SSL for trunk.cocoapods.org:443...
SSL established
<- "POST /api/v1/pods?allow_warnings=false HTTP/1.1\r\nContent-Type: application/json; charset=utf-8\r\nAccept: application/json; charset=utf-8\r\nUser-Agent: CocoaPods/1.5.3\r\nAuthorization: Token 181e6fa504be548c3654a9291ce97a52\r\nAccept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3\r\nHost: trunk.cocoapods.org\r\nContent-Length: 490\r\n\r\n"
<- "{\"name\":\"PermissionDirector\",\"version\":\"0.0.2\",\"summary\":\"iOS Permission manager.\",\"description\":\"PermissionDirector is a iOS permission manager.\",\"homepage\":\"https://github.com/SoolyChristy/PermissionDirector\",\"license\":{\"type\":\"MIT\",\"file\":\"LICENSE\"},\"authors\":{\"SoolyChristy\":\"imsooly@163.com\"},\"source\":{\"git\":\"https://github.com/SoolyChristy/PermissionDirector.git\",\"tag\":\"0.0.2\"},\"source_files\":[\"Sources/*.swift\"],\"platforms\":{\"ios\":\"9.0\"},\"swift_version\":\"4.2\",\"requires_arc\":true}\n"
-> "HTTP/1.1 500 Internal Server Error\r\n"
-> "Date: Tue, 27 Nov 2018 03:56:57 GMT\r\n"
-> "Connection: keep-alive\r\n"
-> "Strict-Transport-Security: max-age=31536000\r\n"
-> "Content-Type: application/json\r\n"
-> "Content-Length: 141\r\n"
-> "X-Content-Type-Options: nosniff\r\n"
-> "Server: thin 1.6.2 codename Doc Brown\r\n"
-> "Via: 1.1 vegur\r\n"
-> "\r\n"
reading 141 bytes...
-> "{\"error\":\"An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later.\"}"
read 141 bytes
Conn keep-alive
[!] An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later.

/Library/Ruby/Gems/2.3.0/gems/cocoapods-trunk-1.3.0/lib/pod/command/trunk.rb:70:in `print_error'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-trunk-1.3.0/lib/pod/command/trunk.rb:30:in `request_url'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-trunk-1.3.0/lib/pod/command/trunk.rb:36:in `request_path'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-trunk-1.3.0/lib/pod/command/trunk/push.rb:83:in `push_to_trunk'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-trunk-1.3.0/lib/pod/command/trunk/push.rb:69:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

My .podspec file looks like this:
```
Pod::Spec.new do |s|
  s.name         = "PermissionDirector"
  s.version      = "0.0.2"
  s.summary      = "iOS Permission manager."
  s.description  = <<-DESC
PermissionDirector is a iOS permission manager.
                   DESC
  s.homepage     = "https://github.com/SoolyChristy/PermissionDirector"
  s.license      = { :type => "MIT", :file => "LICENSE" }
  s.author       = { "SoolyChristy" => "imsooly@163.com" }
  s.source       = { :git => "https://github.com/SoolyChristy/PermissionDirector.git", :tag => s.version }
  s.source_files  = ["Sources/*.swift"]
  s.platform     = :ios, '9.0'
  s.swift_version = "4.2"
  s.requires_arc = true

end
```

**Comment by dnkoutso** [comment]
Something on the server is throwing. Recommend filing on https://github.com/CocoaPods/cocoapods-trunk

**Comment by SoolyChristy** [comment]
I can not understand
