### ISSUE TITLE
An internal server error occurred when push a new version

### ISSUE THREAD

**Issue by jonathantribouharet** [CocoaPods/CocoaPods#8405]
Hi,

* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

From this git https://github.com/ProovGroup/weproov-ios-sdk

I run:

```
pod trunk push WeProovSDK.podspec
```

Which gave me this:

```
Updating spec repo `master`
warning: inexact rename detection was skipped due to too many files.
warning: you may want to set your diff.renameLimit variable to at least 6527 and retry the command.

CocoaPods 1.6.0.beta.2 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.6.0.beta.2

Validating podspec
 -> WeProovSDK (1.0.9)
    - WARN  | summary: The summary is not meaningful.
    - WARN  | description: The description is shorter than the summary.
    - WARN  | [iOS] swift: The validator used Swift 3.2 by default because no Swift version was specified. To specify a Swift version during validation, add the `swift_version` attribute in your podspec. Note that usage of the `--swift-version` parameter or a `.swift-version` file is now deprecated.
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | [iOS] xcodebuild:  note: Planning build
    - NOTE  | [iOS] xcodebuild:  note: Constructing build description
    - NOTE  | [iOS] xcodebuild:  warning: Skipping code signing because the target does not have an Info.plist file. (in target 'App')
    - WARN  | xcodebuild:  FLAnimatedImage/FLAnimatedImage/FLAnimatedImage.m:302:142: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
    - WARN  | xcodebuild:  ACEDrawingView/ACEDrawingView/ACEDrawingView.m:106:1: warning: implementing deprecated method [-Wdeprecated-implementations]
    - NOTE  | xcodebuild:  ACEDrawingView/ACEDrawingView/ACEDrawingView.h:103:40: note: method 'prev_image' declared here
    - WARN  | xcodebuild:  ACEDrawingView/ACEDrawingView/ACEDrawingView.m:110:1: warning: implementing deprecated method [-Wdeprecated-implementations]
    - NOTE  | xcodebuild:  ACEDrawingView/ACEDrawingView/ACEDrawingView.h:103:40: note: method 'setPrev_image:' declared here
    - NOTE  | [iOS] xcodebuild:  ld: warning: 

[!] The spec did not pass validation, due to 6 warnings (but you can use `--allow-warnings` to ignore them).
```

Then I run:

```
pod trunk push WeProovSDK.podspec --allow-warnings
```

which gave me this:

```
Updating spec repo `master`

CocoaPods 1.6.0.beta.2 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.6.0.beta.2

Validating podspec
 -> WeProovSDK (1.0.9)
    - WARN  | summary: The summary is not meaningful.
    - WARN  | description: The description is shorter than the summary.
    - WARN  | [iOS] swift: The validator used Swift 3.2 by default because no Swift version was specified. To specify a Swift version during validation, add the `swift_version` attribute in your podspec. Note that usage of the `--swift-version` parameter or a `.swift-version` file is now deprecated.
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | [iOS] xcodebuild:  note: Planning build
    - NOTE  | [iOS] xcodebuild:  note: Constructing build description
    - NOTE  | [iOS] xcodebuild:  warning: Skipping code signing because the target does not have an Info.plist file. (in target 'App')
    - WARN  | xcodebuild:  FLAnimatedImage/FLAnimatedImage/FLAnimatedImage.m:302:142: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior [-Wimplicit-retain-self]
    - WARN  | xcodebuild:  ACEDrawingView/ACEDrawingView/ACEDrawingView.m:106:1: warning: implementing deprecated method [-Wdeprecated-implementations]
    - NOTE  | xcodebuild:  ACEDrawingView/ACEDrawingView/ACEDrawingView.h:103:40: note: method 'prev_image' declared here
    - WARN  | xcodebuild:  ACEDrawingView/ACEDrawingView/ACEDrawingView.m:110:1: warning: implementing deprecated method [-Wdeprecated-implementations]
    - NOTE  | xcodebuild:  ACEDrawingView/ACEDrawingView/ACEDrawingView.h:103:40: note: method 'setPrev_image:' declared here
    - NOTE  | [iOS] xcodebuild:  ld: warning: ignoring file WeProovSDK/WeProovSDK/WeProovSDK.framework/WeProovSDK, missing required architecture i386 in file WeProovSDK/WeProovSDK/WeProovSDK.framework/WeProovSDK (3 slices)

[!] An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later.
```

## What did you expect to happen?

To push the pod correctly.

## What happened instead?

An error "[!] An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later."

### Stack

I tried with cocoapod pod 1.5.3 and I updated to 1.6.0.beta.2

```
   CocoaPods : 1.6.0.beta.2
        Ruby : ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin17]
    RubyGems : 2.7.7
        Host : Mac OS X 10.14.2 (18C54)
       Xcode : 10.1 (10B61)
         Git : git version 2.17.2 (Apple Git-113)
Ruby lib dir : /Users/jonathan/.rvm/rubies/ruby-2.2.2/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 49abc736016a6791609da4df67370bfb20542c58
```

### Installation Source

```
Executable Path: /Users/jonathan/.rvm/gems/ruby-2.2.2/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

https://github.com/ProovGroup/weproov-ios-sdk

## More informations:

When I run:

```
 pod trunk push WeProovSDK.podspec --allow-warnings --verbose
```

I have this

```
opening connection to trunk.cocoapods.org:443...
opened
starting SSL for trunk.cocoapods.org:443...
SSL established
<- "POST /api/v1/pods?allow_warnings=true HTTP/1.1\r\nContent-Type: application/json; charset=utf-8\r\nAccept: application/json; charset=utf-8\r\nUser-Agent: CocoaPods/1.6.0.beta.2\r\nAuthorization: Token XXXXXXXXX\r\nAccept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3\r\nHost: trunk.cocoapods.org\r\nContent-Length: 768\r\n\r\n"
<- "{\"name\":\"WeProovSDK\",\"version\":\"1.0.9\",\"summary\":\"A short description of WeProovSDK\",\"description\":\"A long description of WeProovSDK\",\"license\":{\"type\":\"ProovGroup License\",\"file\":\"LICENSE\"},\"authors\":\"ProovGroup\",\"homepage\":\"https://github.com/ProovGroup/weproov-ios-sdk\",\"source\":{\"git\":\"https://github.com/ProovGroup/weproov-ios-sdk.git\",\"tag\":\"1.0.9\"},\"platforms\":{\"ios\":\"10.0\"},\"ios\":{\"vendored_frameworks\":[\"WeProovSDK/WeProovSDK.framework\"]},\"pod_target_xcconfig\":{\"ENABLE_BITCODE\":\"NO\"},\"user_target_xcconfig\":{\"ENABLE_BITCODE\":\"NO\"},\"preserve_paths\":\"WeProovSDK/Wprv.framework\",\"dependencies\":{\"ACEDrawingView\":[\"~> 2.2\"],\"APAddressBook\":[\"~> 0.3\"],\"FLAnimatedImage\":[\"~> 1.0\"],\"JTMaterialSpinner\":[\"~> 3.0\"],\"MBProgressHUD\":[\"~> 1.1\"],\"SnapKit\":[\"~> 4.0\"]}}\n"
-> "HTTP/1.1 500 Internal Server Error\r\n"
-> "Date: Thu, 10 Jan 2019 10:50:21 GMT\r\n"
-> "Connection: keep-alive\r\n"
-> "Strict-Transport-Security: max-age=31536000\r\n"
-> "Content-Type: application/json\r\n"
-> "Content-Length: 141\r\n"
-> "X-Content-Type-Options: nosniff\r\n"
-> "Server: thin 1.6.2 codename Doc Brown\r\n"
-> "Via: 1.1 vegur\r\n"
-> "\r\n"
reading 141 bytes...
-> "{\"error\":\"An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later.\"}"
read 141 bytes
Conn keep-alive
[!] An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later.

/Users/jonathan/.rvm/gems/ruby-2.2.2@global/gems/cocoapods-trunk-1.3.1/lib/pod/command/trunk.rb:70:in `print_error'
/Users/jonathan/.rvm/gems/ruby-2.2.2@global/gems/cocoapods-trunk-1.3.1/lib/pod/command/trunk.rb:30:in `request_url'
/Users/jonathan/.rvm/gems/ruby-2.2.2@global/gems/cocoapods-trunk-1.3.1/lib/pod/command/trunk.rb:36:in `request_path'
/Users/jonathan/.rvm/gems/ruby-2.2.2@global/gems/cocoapods-trunk-1.3.1/lib/pod/command/trunk/push.rb:85:in `push_to_trunk'
/Users/jonathan/.rvm/gems/ruby-2.2.2@global/gems/cocoapods-trunk-1.3.1/lib/pod/command/trunk/push.rb:71:in `run'
/Users/jonathan/.rvm/gems/ruby-2.2.2@global/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/jonathan/.rvm/gems/ruby-2.2.2/gems/cocoapods-1.6.0.beta.2/lib/cocoapods/command.rb:52:in `run'
/Users/jonathan/.rvm/gems/ruby-2.2.2/gems/cocoapods-1.6.0.beta.2/bin/pod:55:in `<top (required)>'
/Users/jonathan/.rvm/gems/ruby-2.2.2/bin/pod:23:in `load'
/Users/jonathan/.rvm/gems/ruby-2.2.2/bin/pod:23:in `<main>'
/Users/jonathan/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:24:in `eval'
/Users/jonathan/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:24:in `<main>'
```

Also I'm not the owner of the projet and the page https://cocoapods.org/pods/WeProovSDK show an "Internal Server Error".

Thanks.

**Comment by anand-plivo** [comment]
The same thing just happened to me too. The pod page is gone now. 
https://cocoapods.org/pods/PlivoVoiceKit

**Comment by dnkoutso** [comment]
@orta any quick ideas here? Or logs that show the error?

**Comment by jonathantribouharet** [comment]
By the way, I have released another version with another tag and everything is working now.

**Comment by anand-plivo** [comment]
I released another version now that version is added but the page https://cocoapods.org/pods/PlivoVoiceKit still has "internal server error"
