### ISSUE TITLE
"/CocoaPods/Specs is not a valid repository name"

### ISSUE THREAD

**Issue by edenman** [CocoaPods/CocoaPods#8475]
* [Yup] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

```
pod repo update --verbose

Updating spec repo `master`
  $ /usr/local/bin/git -C /Users/edenman/.cocoapods/repos/master fetch origin --progress
  fatal: remote error: 
    /CocoaPods/Specs is not a valid repository name
    Email support@github.com for help
[!] CocoaPods was not able to update the `master` repo. If this is an unexpected issue and persists you can inspect it running `pod repo update --verbose`

/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0.beta.2/lib/cocoapods/sources_manager.rb:114:in `rescue in update_git_repo'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0.beta.2/lib/cocoapods/sources_manager.rb:105:in `update_git_repo'
...
```

## What did you expect to happen?

Update of the pod repo so I could grab the latest version of a dep I want to update 

## What happened instead?

The error message above.  Here's the output of pod repo, if it's relevant:

```
pod repo

master
- Type: git (master)
- URL:  https://github.com/CocoaPods/Specs.git
- Path: /Users/edenman/.cocoapods/repos/master

1 repo
```
### Stack

```
   CocoaPods : 1.6.0.beta.2
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.2 (18C54)
       Xcode : 10.1 (10B61)
         Git : git version 2.20.1
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ e96bd6cb18ce03055c277429f6e04344ed1aecfd
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.1'
use_frameworks!
workspace 'Recharge'

# ignore compiler warnings from Pods
inhibit_all_warnings!

target 'Consumer' do
  project 'consumer/Consumer.xcodeproj'

  # Local pods
  pod 'CommonAPI', :path => 'CommonAPI'

  # Third-party pods
	pod 'GoogleMaps'
	pod 'GooglePlaces'
	pod 'Alamofire'
	pod 'SwiftyJSON'
	pod 'ObjectMapper'
	pod 'PromiseKit/CorePromise'
	pod 'SwiftyUserDefaults'
	pod 'EmitterKit'
	pod 'Stripe'
	pod 'FBSDKCoreKit'
	pod 'FBSDKLoginKit'
	pod 'FBSDKShareKit'
	pod 'libPusher'
	pod 'RSKImageCropper'
	pod 'SDWebImage'
	pod 'libPhoneNumber-iOS'
	pod 'Mixpanel'
	pod 'CocoaLumberjack/Swift'
	pod 'LogglyLogger-CocoaLumberjack'
	pod 'Bugsnag'
	pod 'Sift'
	pod 'TTTAttributedLabel'
	pod 'pop'
	pod 'Branch'
	pod 'Firebase/Core'
	pod 'PureLayout'
	pod 'markymark'
	pod 'Reveal-SDK', :configurations => ['Debug']

	target 'ConsumerTests' do
		inherit! :search_paths
  end
end

target 'Host' do
  project 'host/Host.xcodeproj'

  # Local pods
  pod 'CommonAPI', :path => 'CommonAPI'

  # Third-party pods
	pod 'Alamofire'
	pod 'SwiftyJSON'
	pod 'ObjectMapper'
	pod 'PromiseKit/CorePromise'
	pod 'SwiftyUserDefaults'
	pod 'EmitterKit'
	pod 'FBSDKCoreKit'
	pod 'FBSDKLoginKit'
	pod 'FBSDKShareKit'
	pod 'RSKImageCropper'
	pod 'SDWebImage'
	pod 'libPhoneNumber-iOS'
	pod 'Mixpanel'
	pod 'CocoaLumberjack/Swift'
	pod 'LogglyLogger-CocoaLumberjack'
	pod 'Bugsnag'
	pod 'pop'
	pod 'Branch'
	pod 'PureLayout'
	pod 'markymark'
	pod 'Reveal-SDK', :configurations => ['Debug']

	target 'HostTests' do
		inherit! :search_paths
  end
end
```

## Project that demonstrates the issue

Haven't tried to repro yet, will do that now

**Comment by edenman** [comment]
```
[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
        ignorecase = true
        precomposeunicode = true
[remote "origin"]
        url = https://github.com/CocoaPods/Specs.git
        fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
        remote = origin
        merge = refs/heads/master```

**Comment by edenman** [comment]
Nevermind, pebcak.  I had this in my top-level ~/.gitconfig:
```
[url "ssh://git@github.com/"]
        insteadOf = https://github.com
```

**Comment by edenman** [comment]
(note the trailing slash in the ssh url and the lack of trailing slash in the https one)

**Comment by amorde** [comment]
👍
