### ISSUE TITLE
Setting cache_root from config or env gives error

### ISSUE THREAD

**Issue by Endareth** [CocoaPods/CocoaPods#8515]
Before you start, are you using the latest CocoaPods release? Yes, 1.5.3
 [X ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
Edit ~/.cocapods/config.yaml and added:
cache_root: "/Users/username/testcache"
Run: `pod cache list`

## What did you expect to happen?
Empty cache info displayed

## What happened instead?
Error displayed

```
NoMethodError - undefined method `exist?' for ".":String
/Users/piershearn/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/config.rb:90:in `cache_root'
/Users/piershearn/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/command/cache.rb:17:in `initialize'
/Users/piershearn/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/command/cache/list.rb:25:in `initialize'
/Users/piershearn/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/claide-1.0.2/lib/claide/command.rb:356:in `new'
/Users/piershearn/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/claide-1.0.2/lib/claide/command.rb:356:in `parse'
/Users/piershearn/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/claide-1.0.2/lib/claide/command.rb:352:in `parse'
/Users/piershearn/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/claide-1.0.2/lib/claide/command.rb:352:in `parse'
/Users/piershearn/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/claide-1.0.2/lib/claide/command.rb:330:in `run'
/Users/piershearn/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
/Users/piershearn/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
/Users/piershearn/.rbenv/versions/2.4.2/bin/pod:23:in `load'
/Users/piershearn/.rbenv/versions/2.4.2/bin/pod:23:in `<main>'
```

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin16]
    RubyGems : 2.6.13
        Host : Mac OS X 10.13.6 (17G4015)
       Xcode : 10.1 (10B61)
         Git : git version 2.20.1
Ruby lib dir : /Users/****/.rbenv/versions/2.4.2/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ aadeaf5e6e2f1b7fba720444076268b9b9b5a4ec
```

### Installation Source

```
Executable Path: /Users/****/.rbenv/versions/2.4.2/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
slather               : 2.4.6
```

### Podfile
Not relevant, happens with all projects

## Project that demonstrates the issue
Not relevant, happens with all projects

**Comment by Endareth** [comment]
Not sure if it's related, but when investigating this, attempting to set the cache location by setting/exporting CP_CACHE_DIR doesn't appear to do anything.

**Comment by dnkoutso** [comment]
Probably a legitimate bug.

**Comment by tripleCC** [comment]
CocoaPods 1.5.3 doesn't use CP_CACHE_DIR for cache directory yet.

**Comment by segiddins** [comment]
I think we just need to wrap the user-provided value for `:cache_root` in a `Pathname`
