### ISSUE TITLE
[1.7.0.beta.1] Cannot run pod install. Installation issue

### ISSUE THREAD

**Issue by AndrewBarba** [CocoaPods/CocoaPods#8545]
# Report

## What did you do?

1. Installed CocoaPods 1.7.0.beta.1
2. Added `source 'https://cdn.jsdelivr.net/cocoa/'` to my Podfile
3. Added `install! 'cocoapods', :generate_multiple_pod_projects => true, :incremental_installation => true` to my Podfile
2. Ran `pod install`

## What did you expect to happen?

I expected the install to succeed

## What happened instead?

```bash
Analyzing dependencies
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- concurrent (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.7.0.beta.1/lib/cocoapods-core/cdn_source.rb:3:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.7.0.beta.1/lib/cocoapods-core/source/manager.rb:289:in `block in source_from_path'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.7.0.beta.1/lib/cocoapods-core/source/manager.rb:296:in `source_from_path'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.7.0.beta.1/lib/cocoapods-core/source/manager.rb:305:in `block in aggregate_with_repos'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.7.0.beta.1/lib/cocoapods-core/source/manager.rb:305:in `map'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.7.0.beta.1/lib/cocoapods-core/source/manager.rb:305:in `aggregate_with_repos'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.7.0.beta.1/lib/cocoapods-core/source/manager.rb:24:in `aggregate'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.7.0.beta.1/lib/cocoapods-core/source/manager.rb:58:in `all'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.beta.1/lib/cocoapods/user_interface/error_report.rb:173:in `repo_information'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.beta.1/lib/cocoapods/user_interface/error_report.rb:77:in `stack'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.beta.1/lib/cocoapods/user_interface/error_report.rb:24:in `report'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.beta.1/lib/cocoapods/command.rb:66:in `report_error'
	from /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:396:in `handle_exception'
	from /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:337:in `rescue in run'
	from /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:324:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.beta.1/lib/cocoapods/command.rb:52:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.beta.1/bin/pod:55:in `<top (required)>'
	from /usr/local/bin/pod:22:in `load'
	from /usr/local/bin/pod:22:in `<main>'
```

## CocoaPods Environment

`pod env | pbcopy` produced the same error as above

v1.7.0.beta.1

**Comment by AndrewBarba** [comment]
I followed this guide to install Ruby 2.6.1 and, reinstalled CocoaPods and `pod install` ran successfully:

https://codingpad.maryspad.com/2017/04/29/update-mac-os-x-to-the-current-version-of-ruby/

**Comment by dnkoutso** [comment]
Yes this appears to be an environment setup issue. I can't reproduce and CI passes.

@AndrewBarba going to close preemptively let me know and I can re-open.

**Comment by AndrewBarba** [comment]
Good to go, new project structure is awesome. Building and running successfully
