### ISSUE TITLE
Execute `pod install` , error: Oh no, an error occurred.

### ISSUE THREAD

**Issue by Jinxiansen** [CocoaPods/CocoaPods#8578]
When I run the `pod install` command, an error occurs on the terminal: Oh no, an error occurred.

This looks like a permission issue, but I have given `jenkins` permission: 

`sudo chmod 777 /Users/duoduotu/.jenkins`

`
Errno::EACCES - Permission denied @ apply2files - /Users/duoduotu/.jenkins/workspace/iOS_DuoDuoTu_AppStore/duoduotu/duoduotu.xcodeproj/project.pbxproj
`

### Error

```
Errno::EACCES - Permission denied @ apply2files - /Users/duoduotu/.jenkins/workspace/iOS_DuoDuoTu_AppStore/duoduotu/duoduotu.xcodeproj/project.pbxproj
/Users/duoduotu/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/fileutils.rb:1130:in `utime'
/Users/duoduotu/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/fileutils.rb:1130:in `block in touch'
/Users/duoduotu/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/fileutils.rb:1127:in `each'
/Users/duoduotu/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/fileutils.rb:1127:in `touch'
/Users/duoduotu/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/user_project_integrator.rb:151:in `block in save_projects'
/Users/duoduotu/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/user_project_integrator.rb:139:in `each'
/Users/duoduotu/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/user_project_integrator.rb:139:in `save_projects'
/Users/duoduotu/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/user_project_integrator.rb:67:in `integrate!'
/Users/duoduotu/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:645:in `block in integrate_user_project'
/Users/duoduotu/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.6.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/duoduotu/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:642:in `integrate_user_project'
/Users/duoduotu/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:141:in `install!'
/Users/duoduotu/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.6.1/lib/cocoapods/command/install.rb:48:in `run'
/Users/duoduotu/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/duoduotu/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.6.1/lib/cocoapods/command.rb:52:in `run'
/Users/duoduotu/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.6.1/bin/pod:55:in `<top (required)>'
/Users/duoduotu/.rvm/rubies/ruby-2.6.0/bin/pod:23:in `load'
/Users/duoduotu/.rvm/rubies/ruby-2.6.0/bin/pod:23:in `<main>'
/Users/duoduotu/.rvm/rubies/ruby-2.6.0/bin/ruby_executable_hooks:24:in `eval'
/Users/duoduotu/.rvm/rubies/ruby-2.6.0/bin/ruby_executable_hooks:24:in `<main>'
```

### Stack

```
   CocoaPods : 1.6.1
        Ruby : ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-darwin18]
    RubyGems : 3.0.1
        Host : Mac OS X 10.14.3 (18D109)
       Xcode : 10.1 (10B61)
         Git : git version 2.17.2 (Apple Git-113)
Ruby lib dir : /Users/duoduotu/.rvm/rubies/ruby-2.6.0/lib
Repositories : LYGSpecRepo - https://gitlab.laoyuegou.com/ComponentLibrary/lygspecrepo.git @ 41c9cdbd8673f67b36296806f205b4e18b516d7a
               master - https://github.com/CocoaPods/Specs.git @ 337bd4b06668227e9038951e993d12c064da9fdb
```

### Installation Source

```
Executable Path: /Users/duoduotu/.rvm/rubies/ruby-2.6.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.3
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

This problem has already plagued me for 1 day, our company's listing plan is blocked because of me, please help me! Thank you!

🤔

> English is not my native language; please excuse typing errors.

**Comment by orta** [comment]
At a guess, you probably need to set the permissions recursively.

**Comment by Jinxiansen** [comment]
Yes, I have set permissions and all of its subdirectories and still can't solve this problem. When the pod is executed, the permissions of the project.xcodeproj file become inaccessible.

**Comment by Jinxiansen** [comment]
Very helpless, I changed this way yesterday to solve this problem: `Create a new User` on the Mac, can solve this problem. 🤪
