### ISSUE TITLE
No such file or directory @ rb_sysopen

### ISSUE THREAD

**Issue by hamdshah** [CocoaPods/CocoaPods#8599]
# Report
I'm using `Gem bundler` for installing `Cocoapods`. And even after deleting the `Pods/` directory which was the case to fix it "suggested in old issues" is not working.

## What did you do?
Run `pod install`

## What did you expect to happen?
 Install all pod dependencies correctly.

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
inhibit_all_warnings!

use_frameworks!

# Pods for XYZiOS
def common_pods
    #    ****** Swift 4.2 Pods  *******
    pod 'Eureka', '4.3.0'
    pod 'SwiftyUserDefaults', '4.0.0-alpha.1'
    pod 'Swinject', '2.5.0'
    pod 'SwinjectStoryboard', '2.1.0'
    pod 'RxSwift', '4.4.0'
    pod 'RxCocoa',    '4.4.0'
    pod 'RxSwiftExt', '3.3.0'
    pod 'RxDataSources', '3.1.0'
    pod 'SwiftDate', '5.0.13'
    pod 'R.swift', '= 5.0.0.alpha.2'
    pod 'IQKeyboardManagerSwift', '6.1.1'
    pod 'XMPPFramework/Swift', '4.0'
    pod 'MessageKit', '~> 2.0.0'
    pod 'ReCaptcha/RxSwift', '1.4.1'

    #    ****** Swift 3.2 Pods  *******
    pod 'RangeSeekSlider', '1.7.0'

    #    ****** Objective-C *******
    pod 'Fabric', '1.7.9'
    pod 'Crashlytics', '3.10.5'
    pod 'SVProgressHUD', '2.2.5'
    pod 'SDWebImage', '~> 4.4.2'
    pod 'FirebaseCore', '5.0.6'
    pod 'FirebaseMessaging', '3.0.3'
    pod 'Sift', '1.0.1'
    pod 'ZendeskSDK', '2.1.1'
    
    #-------Private Components-----#
    pod 'MyOSUtilities/UIKit', :path => './Components/MyOSUtilities/', :inhibit_warnings => false
    pod 'CityPicker', :path => './Components/CityPicker', :inhibit_warnings => false
    pod 'ImageUploadFeature', :path => './Components/ImageUploadFeature', :inhibit_warnings => false
    pod 'MyOS.Networking', :path => './Components/MyOSNetworking', :inhibit_warnings => false
    pod 'MyOS.Authenticator', :path => './Components/MyOSAuthenticator', :inhibit_warnings => false
    pod 'MyOS.UserPresence', :path => './Components/MyOSUserPresence', :inhibit_warnings => false
    pod 'MyOS.AppVersionVerifier', :path => './Components/MyOSAppVersionVerifier', :inhibit_warnings => false
    pod 'MyOS.UIAuthenticator', :path => './Components/MyOSUIAuthenticator/', :inhibit_warnings => false
    pod 'MyOSAnalytics', :path => './Components/MyOSAnalytics/', :inhibit_warnings => false
end

# Pods for MyTarget1 Target
def MyTarget1_pods
    #-------Private Components-----#
    pod 'MyOSPayment', :path => './Components/MyOSPayment/'
end

# Pods for testing
def testing_pods
    pod 'Quick', '1.3.2'
    pod 'Nimble', '7.3.1'
    pod 'RxTest', '4.4.0'
    pod 'RxBlocking', '4.4.0'    
end

# Pods for snapshot testing
def snapshot_testing_pods
    pod 'SnapshotTesting', '~> 1.1'
end

target 'MyTarget2' do
    common_pods
end

target 'MyTarget3' do
    common_pods
end

target 'MyTarget1' do
    common_pods
    MyTarget1_pods
end

target 'XYZiOSTests' do
    inherit! :search_paths
    testing_pods
    common_pods
end

target 'XYZiOSUITests' do
    inherit! :search_paths
    testing_pods
end

target 'ComponentsTests' do
    inherit! :search_paths
    testing_pods
end

target 'SnapshotTests' do
    inherit! :search_paths
    snapshot_testing_pods
end

# Post install script for the pods which doesn't support Swift 4.0 yet
post_install do |installer|
#    List of targets
    targetsWithSwift3_2 = ['RangeSeekSlider']
    installer.pods_project.targets.each do |target|
        if targetsWithSwift3_2.include? target.name
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '3.2'
            end
        end
    end
end
```

### Error

```
Errno::ENOENT - No such file or directory @ rb_sysopen - /Users/mobileci/builds/3b714cf7/0/MyOS/apps/iOS/Pods/Target Support Files/Pods-MyTarget2/Pods-MyTarget2.debug.xcconfig
/Users/mobileci/.rvm/gems/ruby-2.4.0/gems/xcodeproj-1.8.1/lib/xcodeproj/config.rb:257:in `read'
/Users/mobileci/.rvm/gems/ruby-2.4.0/gems/xcodeproj-1.8.1/lib/xcodeproj/config.rb:257:in `read'
/Users/mobileci/.rvm/gems/ruby-2.4.0/gems/xcodeproj-1.8.1/lib/xcodeproj/config.rb:257:in `extract_hash'
/Users/mobileci/.rvm/gems/ruby-2.4.0/gems/xcodeproj-1.8.1/lib/xcodeproj/config.rb:64:in `initialize'
/Users/mobileci/.rvm/gems/ruby-2.4.0/gems/xcodeproj-1.8.1/lib/xcodeproj/project/object/build_configuration.rb:213:in `new'
/Users/mobileci/.rvm/gems/ruby-2.4.0/gems/xcodeproj-1.8.1/lib/xcodeproj/project/object/build_configuration.rb:213:in `config'
/Users/mobileci/.rvm/gems/ruby-2.4.0/gems/xcodeproj-1.8.1/lib/xcodeproj/project/object/build_configuration.rb:90:in `resolve_build_setting'
/Users/mobileci/.rvm/gems/ruby-2.4.0/gems/xcodeproj-1.8.1/lib/xcodeproj/project/object/build_configuration.rb:95:in `resolve_build_setting'
/Users/mobileci/.rvm/gems/ruby-2.4.0/gems/xcodeproj-1.8.1/lib/xcodeproj/project/object/configuration_list.rb:78:in `block in get_setting'
/Users/mobileci/.rvm/gems/ruby-2.4.0/gems/xcodeproj-1.8.1/lib/xcodeproj/project/object/configuration_list.rb:77:in `each'
/Users/mobileci/.rvm/gems/ruby-2.4.0/gems/xcodeproj-1.8.1/lib/xcodeproj/project/object/configuration_list.rb:77:in `get_setting'
/Users/mobileci/.rvm/gems/ruby-2.4.0/gems/xcodeproj-1.8.1/lib/xcodeproj/project/object/native_target.rb:55:in `resolved_build_setting'
/Users/mobileci/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer/target_inspector.rb:228:in `block in compute_swift_version_from_targets'
/Users/mobileci/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer/target_inspector.rb:220:in `each'
/Users/mobileci/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer/target_inspector.rb:220:in `inject'
/Users/mobileci/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer/target_inspector.rb:220:in `compute_swift_version_from_targets'
/Users/mobileci/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer/target_inspector.rb:45:in `compute_results'
/Users/mobileci/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:1028:in `block (3 levels) in inspect_targets_to_integrate'
/Users/mobileci/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:1026:in `each'
/Users/mobileci/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:1026:in `block (2 levels) in inspect_targets_to_integrate'
/Users/mobileci/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:1024:in `each'
/Users/mobileci/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:1024:in `block in inspect_targets_to_integrate'
/Users/mobileci/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.6.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/mobileci/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:1019:in `inspect_targets_to_integrate'
/Users/mobileci/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:96:in `analyze'
/Users/mobileci/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:266:in `analyze'
/Users/mobileci/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:174:in `block in resolve_dependencies'
/Users/mobileci/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.6.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/mobileci/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:173:in `resolve_dependencies'
/Users/mobileci/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:136:in `install!'
/Users/mobileci/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.6.1/lib/cocoapods/command/install.rb:48:in `run'
/Users/mobileci/.rvm/gems/ruby-2.4.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/mobileci/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.6.1/lib/cocoapods/command.rb:52:in `run'
/Users/mobileci/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.6.1/bin/pod:55:in `<top (required)>'
/Users/mobileci/.rvm/gems/ruby-2.4.0/bin/pod:22:in `load'
/Users/mobileci/.rvm/gems/ruby-2.4.0/bin/pod:22:in `<main>'
/Users/mobileci/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
/Users/mobileci/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'
```

## CocoaPods Environment
```
   CocoaPods : 1.6.1
        Ruby : ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
    RubyGems : 2.6.10
        Host : Mac OS X 10.14.2 (18C54)
       Xcode : 10.1 (10B61)
         Git : git version 2.17.2 (Apple Git-113)
Ruby lib dir : /Users/mobileci/.rvm/rubies/ruby-2.4.0/lib
Repositories : accengage - https://github.com/Accengage/CocoaPodsSpecs.git 
               XYZ-engagement-podsspecs - https://gitlab.XYZ.com/engagement/PodsSpecs.git
               XYZ-mobile-podsspec - https://gitlab.XYZ.com/mobile/PodsSpec.git
               XYZ-podsspecs - ssh://git@gitlab.XYZ.de:2124/engagement/PodsSpecs.git
               master - https://github.com/CocoaPods/Specs.git
```

### Plugins

```
cocoapods-deintegrate : 1.0.3
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

**Comment by dnkoutso** [comment]
Please upload a sample app, i cant' repro or diagnose with given info.

**Comment by hamdshah** [comment]
@dnkoutso 
I'm gonna try to re-create the issue in a sample. I'm not sure if it would be possible though.

After using the pod degenerate tool it started working.
I have the `project.pbxproj` diff. If it can help I can share that.

One thing that I forgot to mention that before switching to `bundler` we were using `COCOAPODS: 1.5.3` now we are using `COCOAPODS: 1.6.1` with `bundler`.
