### ISSUE TITLE
pod install abstract_target with plugin cocoapods-binary cause TypeError - no implicit conversion of Array into String

### ISSUE THREAD

**Issue by kingnight** [CocoaPods/CocoaPods#8660]
try to use abstract_target with plugin cocoapods-binary

### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.6.1
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.4 (18E226)
       Xcode : 10.2 (10E125)
         Git : git version 2.20.1 (Apple Git-117)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 3a4ebc0a8d215bf368e737fe22d69774a4186778
               privatePodTestRepo - https://github.com/kingnight/privatePodTestRepo.git @ 95a043ace3b5f1b338e97e84a0c82f4fc2441ce5
```

### Plugins

```
cocoapods-binary      : 0.4.2
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
require_relative 'patch_static_framework'
source 'https://github.com/CocoaPods/Specs.git'
plugin 'cocoapods-binary'
all_binary!
platform :ios, '10.0'

abstract_target 'Base' do
    use_frameworks!
    pod 'SDWebImage', '~> 4.0'
    pod 'SDWebImage/WebP'
    pod 'SDWebImage/GIF'
    pod 'SnapKit'
    pod 'lottie-ios','2.1.5'
    
    target 'sohuhy' do
        use_frameworks!
        pod 'AFNetworking','~> 2.5.4'
        #pod 'SDWebImage', '~> 4.0'
        #pod 'SDWebImage/WebP'
        #pod 'SDWebImage/GIF'
        pod 'YYText'
        pod 'YYWebImage'
        pod 'Masonry'
        #pod 'SnapKit'
        pod 'Bugly'
        #pod 'lottie-ios','2.1.5'
        pod 'KVOController'
        pod 'MJRefresh', :inhibit_warnings => true
        pod 'SVProgressHUD'
        pod 'Protobuf', '3.0.0'
        pod 'MQTTClient'
        pod 'CocoaLumberjack'
        pod 'JRSwizzle'
    end

    target 'HYContentShare' do

    end

    target 'SHNetService' do
    
        #use_frameworks!
        pod 'Alamofire', '~> 4.7.3'
    end

    target 'sohuhyShareExtension' do
        #use_frameworks!
        #pod 'Alamofire', '~> 4.7.3'
    end
end
```

### Error

```
TypeError - no implicit conversion of Array into String
/Library/Ruby/Gems/2.3.0/gems/cocoapods-binary-0.4.2/lib/cocoapods-binary/Prebuild.rb:131:in `basename'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-binary-0.4.2/lib/cocoapods-binary/Prebuild.rb:131:in `block (2 levels) in prebuild_frameworks!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-binary-0.4.2/lib/cocoapods-binary/Prebuild.rb:129:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-binary-0.4.2/lib/cocoapods-binary/Prebuild.rb:129:in `map'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-binary-0.4.2/lib/cocoapods-binary/Prebuild.rb:129:in `block in prebuild_frameworks!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-binary-0.4.2/lib/cocoapods-binary/Prebuild.rb:118:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-binary-0.4.2/lib/cocoapods-binary/Prebuild.rb:118:in `prebuild_frameworks!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-binary-0.4.2/lib/cocoapods-binary/Prebuild.rb:206:in `block in <class:Installer>'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:476:in `perform_post_install_actions'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:145:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-binary-0.4.2/lib/cocoapods-binary/Main.rb:103:in `block in <top (required)>'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/hooks_manager.rb:124:in `block (3 levels) in run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/user_interface.rb:145:in `message'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/hooks_manager.rb:116:in `block (2 levels) in run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/hooks_manager.rb:115:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/hooks_manager.rb:115:in `block in run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/user_interface.rb:145:in `message'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/hooks_manager.rb:114:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:468:in `run_plugins_pre_install_hooks'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:159:in `block in prepare'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/user_interface.rb:145:in `message'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:155:in `prepare'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:135:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/command/install.rb:48:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

**Comment by leavez** [comment]
@kingnight It's a bug of the plugin, not cocoapods itself. cocoapods-binary 0.4.3 have already solve this. You could try it.

**Comment by kingnight** [comment]
thanks a lot @leavez

**Comment by orta** [comment]
Closing this because it's not an issue with CocoaPods 👍
