### ISSUE TITLE
Cannot start CocoaPods at all

### ISSUE THREAD

**Issue by ForceBru** [CocoaPods/CocoaPods#8661]
* I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod`.

## What did you expect to happen?

Um... not error out, I guess :D

## What happened instead?

I got an error message:

```
iMac-ForceBru:Pyto forcebru$ pod
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/command.rb:118:in `git_version': Failed to extract git version from `git --version` ("git version 2.19.GIT\n") (RuntimeError)
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/command.rb:130:in `verify_minimum_git_version!'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/command.rb:49:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/bin/pod:55:in `<top (required)>'
	from /usr/local/bin/pod:22:in `load'
	from /usr/local/bin/pod:22:in `<main>'
```

## macOS info
A relatively fresh install of macOS Mojave 10.14.4. I tried uninstalling and re-installing CocoaPods. The reinstallation succeeded (I mean, it's the first time I'm installing it anyways).

## CocoaPods Environment

No idea:

```
iMac-ForceBru:Pyto forcebru$ pod env
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/command.rb:118:in `git_version': Failed to extract git version from `git --version` ("git version 2.19.GIT\n") (RuntimeError)
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/command.rb:130:in `verify_minimum_git_version!'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/command.rb:49:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/bin/pod:55:in `<top (required)>'
	from /usr/local/bin/pod:22:in `load'
	from /usr/local/bin/pod:22:in `<main>'
```

## Project that demonstrates the issue

I'm trying to build [Pyto](https://github.com/ColdGrub1384/Pyto), but I can't even start the `pod` command, so I guess it's unrelated.

**Comment by orta** [comment]
Did you compile git from scratch? Looks like we might need to add support for that

**Comment by ForceBru** [comment]
@orta, I think I did since it says "version 2.19.__GIT__". Not sure why I did this tho. I think the stock git was missing some features or something. Is there a way to revert it? I tried to reinstall it with `xcode-select --install`, but it just told me that they were already installed (which makes sense).

**Comment by orta** [comment]
`brew install git` might fix that?

**Comment by ForceBru** [comment]
@orta, apparently, my version of git is installed in `/Users/forcebru/bin/git`, not in `/usr/local/bin`, where `brew`ed files seem to go, so it just updated the `brew`ed version of git (for whatever reason I had two).

**Comment by ForceBru** [comment]
So, I ended up putting `brew`'s path (`/usr/local/bin`) at the beginning of the `PATH` variable with `export PATH=/usr/local/bin:$PATH`, so `pod` got the correct version of git. I know it's a temporary workaround because `PATH` will be reset on the next login, but it's fine in my case.

**Comment by orta** [comment]
Personally, I'd use this as a chance to contribute to CP and fix it while you can get into the right state to repro - if we've got this far and no-one has hit this, it's unlikely it'll get fixed. I'm gonna mark it as a good first step for someone though, just in case others want a good place to start 👍

**Comment by Coeur** [comment]
@ForceBru  may I suggest to rename the issue to make it explicit that it's about git version?

**Comment by SportApps** [comment]
Hey guys! I have similar issue in 2022 where I can't run Cocoapods on my Mac M1 Machine - it seems to be related to Git as I get  this error:

```
[ +735 ms] /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:128:in `git_version': Failed to
extract git version from `git --version` ("") (RuntimeError)
                        from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:140:in
                        `verify_minimum_git_version!'
                        from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:49:in `run'
                        from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
                        from /usr/local/bin/pod:23:in `load'
                        from /usr/local/bin/pod:23:in `<main>'
[   +2 ms] Warning: CocoaPods is installed but broken. Skipping pod install.
             You appear to have CocoaPods installed but it is not working.
             This can happen if the version of Ruby that CocoaPods was installed with is different from the one being
used to
             invoke it.
             This can usually be fixed by re-installing CocoaPods.
           To re-install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
           
[   +9 ms] CocoaPods not installed or not in valid state.
[   +1 ms] Error launching application on iPhone SE (3rd generation).
[+6728 ms] "flutter run" took 17,627ms.
[  +36 ms] 
```

More info here:
https://github.com/flutter/flutter/issues/102911

Can somebody help?
