### ISSUE TITLE
`pod trunk push` fails although `pod lib lint` is successful.

### ISSUE THREAD

**Issue by ankitthakur** [CocoaPods/CocoaPods#8685]
# Report

## What did you do?

ℹ Firstly run `pod lib lint` and that get successful. 
```
$ pod lib lint
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin18/rbconfig.rb:215: warning: Insecure world writable dir /usr/local/bin in PATH, mode 040777

 -> ATLocationManager (0.0.1)
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | xcodebuild:  note: Planning build
    - NOTE  | xcodebuild:  note: Constructing build description

ATLocationManager passed validation.
```
ℹ Then run `pod trunk push ATLocationManager.podspec` and that get failed. 

## What did you expect to happen?

ℹ It should get successful and should publish the pod.

## What happened instead?

ℹ It gave error on `pod trunk push ATLocationManager.podspec`
```
$ pod trunk push ATLocationManager.podspec
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin18/rbconfig.rb:215: warning: Insecure world writable dir /usr/local/bin in PATH, mode 040777
Updating spec repo `master`

CocoaPods 1.7.0.beta.3 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.7.0.beta.3

Validating podspec
 -> ATLocationManager (0.0.1)
    - ERROR | file patterns: The `source_files` pattern did not match any file.
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | xcodebuild:  note: Planning build
    - NOTE  | xcodebuild:  note: Constructing build description

[!] The spec did not pass validation, due to 1 error.
```

## CocoaPods Environment

ℹ Please replace these two lines with the output of `pod env`.
e.g. via `pod env | pbcopy`

### Stack

```
   CocoaPods : 1.6.0
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.4 (18E226)
       Xcode : 10.2 (10E125)
         Git : git version 2.20.1 (Apple Git-117)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ fe47f2200e409bccc9648231bb6f5bacdaf2495e
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
use_frameworks!

target 'ATLocationManager_Example' do
  pod 'ATLocationManager', :path => '../../'

  target 'ATLocationManager_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end
```

### Podspec File:
```
#
# Be sure to run `pod lib lint ATLocationManager.podspec' to ensure this is a
# valid spec before submitting.
#
# Any lines starting with a # are optional, but their use is encouraged
# To learn more about a Podspec see https://guides.cocoapods.org/syntax/podspec.html
#

Pod::Spec.new do |spec|
  spec.name             = 'ATLocationManager'
  spec.version          = '0.0.1'
  spec.summary          = 'Core Location library with user defined configurations for iOS and OSX'
  spec.swift_version    = '5.0'

# This description is used to generate tags and improve search results.
#   * Think: What does it do? Why did you write it? What is the focus?
#   * Try to keep it short, snappy and to the point.
#   * Write the description between the DESC delimiters below.
#   * Finally, don't worry about the indent, CocoaPods strips it!

  spec.description      = <<-DESC
Core Location library in beta test version to fetch location with scheduled interval (as minimum interval difference) between consequtive locations with Best Accurary
                       DESC

  spec.homepage         = 'https://github.com/ankitthakur/ATLocationManager'
  # spec.screenshots     = 'www.example.com/screenshots_1', 'www.example.com/screenshots_2'
  spec.license          = { :type => 'MIT', :file => 'LICENSE' }
  spec.author           = { 'Ankit Thakur' => 'ankitthakur85@icloud.com' }
  spec.source           = { :git => 'https://github.com/ankitthakur/ATLocationManager.git', :tag => spec.version.to_s }
  # spec.social_media_url = 'https://twitter.com/<TWITTER_USERNAME>'

  spec.requires_arc = true
  spec.ios.deployment_target  = '10.0'
  spec.osx.deployment_target  = '10.10'

  spec.source_files       = 'ATLocationManager/Sources/Common/*/*.swift'
  spec.ios.source_files   = 'ATLocationManager/Sources/iOS/*/*.swift'
  spec.osx.source_files   = 'ATLocationManager/Sources/OSX/*/*.swift'

  # spec.resource_bundles = {
  #   'ATLocationManager' => ['ATLocationManager/Assets/*.png']
  # }

  # spec.public_header_files = 'Pod/Classes/**/*.h'
  spec.frameworks = 'CoreLocation'
  spec.ios.framework  = 'UIKit'
  spec.osx.framework  = 'AppKit'
  # spec.dependency 'AFNetworking', '~> 2.3'
end
```

## Project that demonstrates the issue

ℹ https://github.com/ankitthakur/ATLocationManager

## Detailed Logs from 
`pod trunk push ATLocationManager.podspec --verbose`

```
$ pod trunk push ATLocationManager.podspec --verbose
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin18/rbconfig.rb:215: warning: Insecure world writable dir /usr/local/bin in PATH, mode 040777

Updating spec repo `master`

CocoaPods 1.7.0.beta.3 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.7.0.beta.3

Validating podspec
    ATLocationManager (0.0.1) - Analyzing on iOS 10.0 platform.
  Preparing

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-App`: (``)

Fetching external sources
-> Fetching podspec for `ATLocationManager` from `/Users/ankitthakur/Documents/Github/ATLocationManager/ATLocationManager/ATLocationManager.podspec`

Resolving dependencies of

Comparing resolved specification to the sandbox manifest
  A ATLocationManager

Downloading dependencies

-> Installing ATLocationManager (0.0.1)
  > Copying ATLocationManager from `/Users/ankitthakur/Library/Caches/CocoaPods/Pods/External/ATLocationManager/b976e05d634ea9168aed007485aed3cb-2caaf` to
  `../../../../../../private/var/folders/__/03k8ghwd21z5y_qktvldd2cr0000gp/T/CocoaPods-Lint-20190409-18903-1utq4k4-ATLocationManager/Pods/ATLocationManager`
  - Running pre install hooks

Generating Pods project
  - Creating Pods project
  - Adding source files to Pods project
  - Adding frameworks to Pods project
  - Adding libraries to Pods project
  - Adding resources to Pods project
  - Linking headers
  - Installing targets
.....
GenerateDSYMFile /Users/ankitthakur/Library/Developer/Xcode/DerivedData/App-eaffuyotpbhgsneltktbntreivnl/Build/Products/Release/App.app.dSYM /Users/ankitthakur/Library/Developer/Xcode/DerivedData/App-eaffuyotpbhgsneltktbntreivnl/Build/Products/Release/App.app/Contents/MacOS/App (in target: App)
        cd /var/folders/__/03k8ghwd21z5y_qktvldd2cr0000gp/T/CocoaPods-Lint-20190409-18903-1utq4k4-ATLocationManager
        /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dsymutil /Users/ankitthakur/Library/Developer/Xcode/DerivedData/App-eaffuyotpbhgsneltktbntreivnl/Build/Products/Release/App.app/Contents/MacOS/App -o /Users/ankitthakur/Library/Developer/Xcode/DerivedData/App-eaffuyotpbhgsneltktbntreivnl/Build/Products/Release/App.app.dSYM

    Touch /Users/ankitthakur/Library/Developer/Xcode/DerivedData/App-eaffuyotpbhgsneltktbntreivnl/Build/Products/Release/App.app (in target: App)
        cd /var/folders/__/03k8ghwd21z5y_qktvldd2cr0000gp/T/CocoaPods-Lint-20190409-18903-1utq4k4-ATLocationManager
        /usr/bin/touch -c /Users/ankitthakur/Library/Developer/Xcode/DerivedData/App-eaffuyotpbhgsneltktbntreivnl/Build/Products/Release/App.app

    RegisterWithLaunchServices /Users/ankitthakur/Library/Developer/Xcode/DerivedData/App-eaffuyotpbhgsneltktbntreivnl/Build/Products/Release/App.app (in target: App)
        cd /var/folders/__/03k8ghwd21z5y_qktvldd2cr0000gp/T/CocoaPods-Lint-20190409-18903-1utq4k4-ATLocationManager
        builtin-lsRegisterURL /Users/ankitthakur/Library/Developer/Xcode/DerivedData/App-eaffuyotpbhgsneltktbntreivnl/Build/Products/Release/App.app

    ** BUILD SUCCEEDED **

   Testing with `xcodebuild`.
 -> ATLocationManager (0.0.1)
    - ERROR | file patterns: The `source_files` pattern did not match any file.
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | xcodebuild:  note: Planning build
    - NOTE  | xcodebuild:  note: Constructing build description

[!] The spec did not pass validation, due to 1 error.

/Library/Ruby/Gems/2.3.0/gems/cocoapods-trunk-1.3.1/lib/pod/command/trunk/push.rb:134:in `validate_podspec'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-trunk-1.3.1/lib/pod/command/trunk/push.rb:70:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'

**Comment by dnkoutso** [comment]
`pod lib lint` uses local files while `pod trunk push` will clone the repository at the tag you have specified in your sources.

Check what tag `0.0.1` points to and update it.

It is also best to ask this in StackOverflow under `cocoapods` tag.

**Comment by dineshsharma1** [comment]
it was tag issue. you have to change tag every time when you change in code.
