### ISSUE TITLE
An error occurred when I just run "Pod init"

### ISSUE THREAD

**Issue by windseason** [CocoaPods/CocoaPods#8705]
――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod init
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.6.0
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.3 (18D109)
       Xcode : 10.2 (10E125)
         Git : git version 2.19.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ df5f9d7d42d21004269c341a25fd69456c039d5c
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby

```

### Error

```
TypeError - no implicit conversion of nil into String
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/command/init.rb:87:in `extname'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/command/init.rb:87:in `block in target_module'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/command/init.rb:87:in `any?'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/command/init.rb:87:in `target_module'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/command/init.rb:72:in `block in podfile_template'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/command/init.rb:68:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/command/init.rb:68:in `podfile_template'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/command/init.rb:45:in `block in run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/command/init.rb:45:in `open'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/command/init.rb:45:in `open'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/command/init.rb:45:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

**Comment by windseason** [comment]
Surprisingly, no error when I use cocoapods-1.5.3

**Comment by dnkoutso** [comment]
Please paste podspec and sample repo

**Comment by windseason** [comment]
> Please paste podspec and sample repo

I started from an existing project which hasn't been configured to use pod before.  The above error occurred when I ran "Pod init", so there is no podspec yet. The Podfile is left empty when this error happened.

**Comment by windseason** [comment]
One more thing, the xcode project is a complicated one which includes multiple targets and third-party sources which are integrated using  "git submodule"

**Comment by dnkoutso** [comment]
Still need a sample here.

**Comment by windseason** [comment]
It works with verison 1.7.0.beta.3. 
So close this ticket.
