### ISSUE TITLE
Can't specify same configuration for two pods if one is in abstract_target and the other is inside, in a target

### ISSUE THREAD

**Issue by malaba** [CocoaPods/CocoaPods#8732]
# Report

## What did you do? 
Run `pod install`

## What did you expect to happen?
Install all pod dependencies correctly.

### Stack

```
   CocoaPods : 1.6.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]
    RubyGems : 3.0.3
        Host : Mac OS X 10.14.3 (18D109)
       Xcode : 10.2 (10E125)
         Git : git version 2.21.0
Ruby lib dir : /usr/local/Cellar/ruby/2.6.3/lib
Repositories : bitbucket-xebia-mobile-pods-specs - https://bitbucket.org/xebia-mobile/pods-specs.git @ 23ab2bd8d322b411822295f4d70e47b26e6d1f9d
               goinstant - https://github.com/goinstant/pods-specs-public @ 8fc9da7f193f0c4d07b9d287b9237565cb2f7d3d
               master - https://github.com/CocoaPods/Specs.git @ 1eabab27ff020ce9e1f87672f69bb91a63cb36cb
```

### Plugins

```
cocoapods-binary      : 0.4.3
cocoapods-deintegrate : 1.0.3
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
slather               : 2.4.7
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!

abstract_target 'AbstractStuff' do
  pod 'Result', :configurations => ['Debug']

  target 'One' do
    pod 'Async', :configurations => ['Debug']
  end

  target 'Two' do
    pod 'Reusable', :configurations => ['Release']
  end
end
```

### Error

```
TypeError - no implicit conversion of Array into String
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.6.1/lib/cocoapods-core/podfile/target_definition.rb:886:in `+'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.6.1/lib/cocoapods-core/podfile/target_definition.rb:886:in `block in configuration_pod_whitelist'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.6.1/lib/cocoapods-core/podfile/target_definition.rb:886:in `merge'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.6.1/lib/cocoapods-core/podfile/target_definition.rb:886:in `configuration_pod_whitelist'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.6.1/lib/cocoapods-core/podfile/target_definition.rb:455:in `all_whitelisted_configurations'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:474:in `generate_target'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:408:in `block in generate_targets'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:407:in `map'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:407:in `generate_targets'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:117:in `analyze'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:266:in `analyze'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:174:in `block in resolve_dependencies'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.6.1/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:173:in `resolve_dependencies'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:136:in `install!'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.6.1/lib/cocoapods/command/install.rb:48:in `run'
/usr/local/lib/ruby/gems/2.6.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.6.1/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.6.1/bin/pod:55:in `<top (required)>'
/usr/local/lib/ruby/gems/current/bin/pod:23:in `load'
/usr/local/lib/ruby/gems/current/bin/pod:23:in `<main>'
```

## Project that demonstrates the issue
I made a minimal Xcode proj that demonstrate the issue:

https://github.com/malaba/AbstractPodfile.git

## Explanation
Pods were chosen at random, to be small. You can try with any pods instead of `Result`, `Async` and `Reusable`.

In this `Podfile` I cannot have a pods in the `abstract_target` (inherited by target One and Two) that specify a configuration that is the same as a configuration specified in another pod on a target.

Meaning that if you change the configuration for pod `Async` to Release it work:
```ruby
abstract_target 'AbstractStuff' do
  pod 'Result', :configurations => ['Debug']
  
  target 'One' do
    pod 'Async', :configurations => ['Release']
  end

  target 'Two' do
    pod 'Reusable', :configurations => ['Release']
  end
```

But to keep configuration Debug on both `Result` and `Async` shouldn't be a problem.

It also work if you move `pod 'Result'` into the target One (and duplicate it in target Two):
```ruby
abstract_target 'AbstractStuff' do
  target 'One' do
    pod 'Result', :configurations => ['Debug']
    pod 'Async', :configurations => ['Debug']
  end

  target 'Two' do
    pod 'Result', :configurations => ['Debug']
    pod 'Reusable', :configurations => ['Release']
  end
end
```

Isn't `abstract_target` supposed to be used for dependency inheritance for enclosed targets ? And why can't I specify the same configuration in both `abstract_target` and `target` for two different pods ?

Thanks.
(note: this seems related ? https://github.com/CocoaPods/CocoaPods/issues/5366, old and was auto closed...)

**Comment by SolaWing** [comment]
I find this line crash:

**Comment by m1entus** [comment]
+1

**Comment by hitsthings** [comment]
XCode newbie here.

I'm adding KIF to a react-native project and am seeing this. I don't think there's any good workarounds since all my react-native dependencies are auto-linked so I can't move anything around:

```
target 'In8' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"

  target 'In8Tests' do
    inherit! :complete
    
    # the configuration option causes a bug
    pod 'KIF', :configurations => ['Debug']
  end

  use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })
  post_install do |installer|
    flipper_post_install(installer)
  end
end
```

I've removed the `:configurations` from `KIF` and that fixes the problem. Since this is tests anyway, I'm not sure why I need to only add it to the Debug config, so I'm running with that part commented out and crossing my fingers for now.

**Comment by dnkoutso** [comment]
@malaba I know this issue is old but i just tried with 1.11.0.beta.2 and maybe its fixed?

My Podfile from your git project:

```ruby
platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!

abstract_target 'AbstractStuff' do
  pod 'Alamofire', :configurations => ['Debug']
  
  target 'One' do
  	pod 'Async', :configurations => ['Debug']
  end

  target 'Two' do
    pod 'Reusable', :configurations => ['Release']
  end
end
```

Generated framework.sh scripts for target `One`:

```
if [[ "$CONFIGURATION" == "Debug" ]]; then
  install_framework "${BUILT_PRODUCTS_DIR}/Alamofire/Alamofire.framework"
  install_framework "${BUILT_PRODUCTS_DIR}/Async/Async.framework"
fi
if [ "${COCOAPODS_PARALLEL_CODE_SIGN}" == "true" ]; then
  wait
fi
```

Generated framework.sh scripts for target `Two`:

```
if [[ "$CONFIGURATION" == "Debug" ]]; then
  install_framework "${BUILT_PRODUCTS_DIR}/Alamofire/Alamofire.framework"
fi
if [[ "$CONFIGURATION" == "Release" ]]; then
  install_framework "${BUILT_PRODUCTS_DIR}/Reusable/Reusable.framework"
fi
if [ "${COCOAPODS_PARALLEL_CODE_SIGN}" == "true" ]; then
  wait
fi
```

It also did not crash. 

I used pod `Alamofire` instead of `Result` because or an unrelated issue I had but it should not matter according to your report.

Is it possible to confirm so we can close this issue? Unfortunately I cannot provide the change and release version this was fixed.

**Comment by malaba** [comment]
> @malaba I know this issue is old but i just tried with 1.11.0.beta.2 and maybe its fixed?
> 
> ...
>
> Is it possible to confirm so we can close this issue? Unfortunately I cannot provide the change and release version this was fixed.

@dnkoutso  I just installed latest beta via `gem install cocoapods --pre` and indeed it doesn't crash anymore.

Both project build and run on Xcode. So I say you can close this issue. 

_Hope than in between now and v1.11.0 release it won't be changed again and the bug re-introduced._ 🤞

**Comment by dnkoutso** [comment]
awesome!
