### ISSUE TITLE
'pod install' for Firebase/Core not working on Windows

### ISSUE THREAD

**Issue by JohnnyRico117** [CocoaPods/CocoaPods#8736]
I'm trying to import the Firebase frameworks to my Flutter Project.
I'm using CocoaPods on Windows (with Ruby)
I have the newest version of CocoaPods and Git

When I run "pod setup" everything works. Then 'pod init' and the Podfile is added to the project.
Then I add 'pod Firebase/Core' to the podfile and run the following and an error occures:

C:\Users\<username>\AndroidStudioProjects\<projectname>\ios>pod install
    WARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
    Consider adding the following to ~/.profile:

    export LANG=en_US.UTF-8

Analyzing dependencies

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
C:/Ruby25-x64/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.6.1
        Ruby : ruby 2.5.5p157 (2019-03-15 revision 67260) [x64-mingw32]
    RubyGems : 2.7.6.2
        Host : Unable to find an executable (No such file or directory - sw_vers)  ()
       Xcode : -version) ()
         Git : git version 2.21.0.windows.1
Ruby lib dir : C:/Ruby25-x64/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 4f4ffa85c65b9e41661e0a6266c4b3ff6f4df6fb
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Runner' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for Runner

  pod 'Firebase/Core'
end
```

### Error

```
Errno::ENOENT - No such file or directory - env -u GIT_CONFIG git -C "C:/Users/<username>/.cocoapods/repos/master" config --get remote.origin.url
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.6.1/lib/cocoapods-core/source.rb:448:in ``'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.6.1/lib/cocoapods-core/source.rb:448:in `repo_git'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.6.1/lib/cocoapods-core/source.rb:46:in `url'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.6.1/lib/cocoapods-core/source/manager.rb:347:in `block in source_with_url'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.6.1/lib/cocoapods-core/source/manager.rb:346:in `each'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.6.1/lib/cocoapods-core/source/manager.rb:346:in `find'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.6.1/lib/cocoapods-core/source/manager.rb:346:in `source_with_url'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.1/lib/cocoapods/sources_manager.rb:18:in `find_or_create_source_with_url'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:169:in `block in sources'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:168:in `map'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:168:in `sources'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:908:in `block in resolve_dependencies'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.1/lib/cocoapods/user_interface.rb:64:in `section'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:907:in `resolve_dependencies'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:114:in `analyze'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:266:in `analyze'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:174:in `block in resolve_dependencies'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.1/lib/cocoapods/user_interface.rb:64:in `section'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:173:in `resolve_dependencies'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:136:in `install!'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.1/lib/cocoapods/command/install.rb:48:in `run'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.1/lib/cocoapods/command.rb:52:in `run'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.1/bin/pod:55:in `<top (required)>'
C:/Ruby25-x64/bin/pod:23:in `load'
C:/Ruby25-x64/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

[!] `<PBXGroup UUID=`97C146E51CF9000F007C117D`>` attempted to initialize an object with an unknown UUID. `CF3B75C9A7D2FA2A4C99F110` for attribute: `children`. This can be the result of a merge and  the unknown UUID is being discarded.

**Comment by dnkoutso** [comment]
Have you tried 1.7.0.beta? I do not believe there was windows support in 1.6.x

**Comment by JohnnyRico117** [comment]
Actually, after days of trying, I just now figured out, that the use of CocoaPods is not necessary when using flutter.

**Comment by davidair** [comment]
I was able to install the Firebase pods on Windows using CocoaPods 1.7.0.beta.3.

To install the 1.7.0 beta, simply use "gem install cocoapods --pre"
