### ISSUE TITLE
 target.headers_build_phase.clear [!] An error occurred while processing the post-install hook of the Podfile.

### ISSUE THREAD

**Issue by zuojinmin** [CocoaPods/CocoaPods#8745]
Generating Pods project
[!] An error occurred while processing the post-install hook of the Podfile.

undefined method `headers_build_phase' for <PBXAggregateTarget name=`AKReactNative` UUID=`000000004B40`>:Xcodeproj::Project::Object::PBXAggregateTarget

/Users/zuojinmin/justbon/Podfile:93:in `block (3 levels) in from_ruby'
/Users/zuojinmin/justbon/Podfile:91:in `each'
/Users/zuojinmin/justbon/Podfile:91:in `block (2 levels) in from_ruby'
/Users/zuojinmin/.rvm/gems/ruby-2.4.1/gems/cocoapods-core-1.6.1/lib/cocoapods-core/podfile.rb:179:in `post_install!'
/Users/zuojinmin/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:701:in `run_podfile_post_install_hook'
/Users/zuojinmin/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:689:in `block in run_podfile_post_install_hooks'
/Users/zuojinmin/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.6.1/lib/cocoapods/user_interface.rb:145:in `message'
/Users/zuojinmin/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:688:in `run_podfile_post_install_hooks'
/Users/zuojinmin/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:211:in `block in generate_pods_project'
/Users/zuojinmin/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.6.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/zuojinmin/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:208:in `generate_pods_project'
/Users/zuojinmin/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:139:in `install!'
/Users/zuojinmin/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.6.1/lib/cocoapods/command/install.rb:48:in `run'
/Users/zuojinmin/.rvm/gems/ruby-2.4.1@global/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/zuojinmin/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.6.1/lib/cocoapods/command.rb:52:in `run'
/Users/zuojinmin/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.6.1/bin/pod:55:in `<top (required)>'
/Users/zuojinmin/.rvm/gems/ruby-2.4.1/bin/pod:23:in `load'
/Users/zuojinmin/.rvm/gems/ruby-2.4.1/bin/pod:23:in `<main>'
/Users/zuojinmin/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
/Users/zuojinmin/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'

pod install - > These problems arise
macos = 10.14.4,xcode 10.1 ruby=2.4.1 pod = 1.6.1
{
 target.headers_build_phase.clear
}

Could you tell me what the problem is

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

**Comment by Hellomik2002** [comment]
Sorry can you write solution, i have same issue
```
Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `multi_image_picker` from `.symlinks/plugins/multi_image_picker/ios`
    -> Fetching podspec for `path_provider` from `.symlinks/plugins/path_provider/ios`
    -> Fetching podspec for `permission_handler` from `.symlinks/plugins/permission_handler/ios`

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_7_e_0.txt exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/7/e/0/BSImagePicker/2.10.3/BSImagePicker.podspec.json exists! Returning local because checking is only perfomed in
      repo update
      CDN: trunk Relative path: Specs/7/e/0/BSImagePicker/2.10.3/BSImagePicker.podspec.json exists! Returning local because checking is only perfomed in
      repo update
      CDN: trunk Relative path: all_pods_versions_4_b_c.txt exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/4/b/c/BSImageView/1.0.3/BSImageView.podspec.json exists! Returning local because checking is only perfomed in repo
      update
      CDN: trunk Relative path: all_pods_versions_b_f_6.txt exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/b/f/6/BSGridCollectionViewLayout/1.2.5/BSGridCollectionViewLayout.podspec.json exists! Returning local because
      checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/4/b/c/BSImageView/1.0.3/BSImageView.podspec.json exists! Returning local because checking is only perfomed in repo
      update
      CDN: trunk Relative path: Specs/b/f/6/BSGridCollectionViewLayout/1.2.5/BSGridCollectionViewLayout.podspec.json exists! Returning local because
      checking is only perfomed in repo update

    Comparing resolved specification to the sandbox manifest
      A BSGridCollectionViewLayout
      A BSImagePicker
      A BSImageView
      A Flutter
      A multi_image_picker
      A path_provider
      A permission_handler

    Downloading dependencies

    -> Installing BSGridCollectionViewLayout (1.2.5)
      > Copying BSGridCollectionViewLayout from `/Users/nurzhan/Library/Caches/CocoaPods/Pods/Release/BSGridCollectionViewLayout/1.2.5-333dc` to
      `Pods/BSGridCollectionViewLayout`

    -> Installing BSImagePicker (2.10.3)
      > Copying BSImagePicker from `/Users/nurzhan/Library/Caches/CocoaPods/Pods/Release/BSImagePicker/2.10.3-07404` to `Pods/BSImagePicker`

    -> Installing BSImageView (1.0.3)
      > Copying BSImageView from `/Users/nurzhan/Library/Caches/CocoaPods/Pods/Release/BSImageView/1.0.3-a1494` to `Pods/BSImageView`

    -> Installing Flutter (1.0.0)

    -> Installing multi_image_picker (4.5.8)

    -> Installing path_provider (0.0.1)

    -> Installing permission_handler (3.2.2)
      - Running pre install hooks

    Generating Pods project
      - Creating Pods project
      - Installing files into Pods project
        - Adding source files
        - Adding frameworks
        - Adding libraries
        - Adding resources
        - Adding development pod helper files
        - Linking headers
      - Installing Pod Targets
        - Installing target `BSGridCollectionViewLayout` iOS 8.0
          - Generating module map file at `Pods/Target Support Files/BSGridCollectionViewLayout/BSGridCollectionViewLayout.modulemap`
          - Generating umbrella header at `Pods/Target Support Files/BSGridCollectionViewLayout/BSGridCollectionViewLayout-umbrella.h`
          - Generating Info.plist file at `Pods/Target Support Files/BSGridCollectionViewLayout/BSGridCollectionViewLayout-Info.plist`
          - Generating dummy source at `Pods/Target Support Files/BSGridCollectionViewLayout/BSGridCollectionViewLayout-dummy.m`
        - Installing target `BSImagePicker` iOS 9.0
          - Generating Info.plist file at `Pods/Target Support Files/BSImagePicker/ResourceBundle-BSImagePicker-BSImagePicker-Info.plist`
          - Generating module map file at `Pods/Target Support Files/BSImagePicker/BSImagePicker.modulemap`
          - Generating umbrella header at `Pods/Target Support Files/BSImagePicker/BSImagePicker-umbrella.h`
          - Generating Info.plist file at `Pods/Target Support Files/BSImagePicker/BSImagePicker-Info.plist`
          - Generating dummy source at `Pods/Target Support Files/BSImagePicker/BSImagePicker-dummy.m`
        - Installing target `BSImageView` iOS 8.0
          - Generating module map file at `Pods/Target Support Files/BSImageView/BSImageView.modulemap`
          - Generating umbrella header at `Pods/Target Support Files/BSImageView/BSImageView-umbrella.h`
          - Generating Info.plist file at `Pods/Target Support Files/BSImageView/BSImageView-Info.plist`
          - Generating dummy source at `Pods/Target Support Files/BSImageView/BSImageView-dummy.m`
        - Installing target `Flutter` iOS 8.0
        - Installing target `multi_image_picker` iOS 9.0
          - Generating module map file at `Pods/Target Support Files/multi_image_picker/multi_image_picker.modulemap`
          - Generating umbrella header at `Pods/Target Support Files/multi_image_picker/multi_image_picker-umbrella.h`
          - Generating Info.plist file at `Pods/Target Support Files/multi_image_picker/multi_image_picker-Info.plist`
          - Generating dummy source at `Pods/Target Support Files/multi_image_picker/multi_image_picker-dummy.m`
        - Installing target `path_provider` iOS 8.0
          - Generating module map file at `Pods/Target Support Files/path_provider/path_provider.modulemap`
          - Generating umbrella header at `Pods/Target Support Files/path_provider/path_provider-umbrella.h`
          - Generating Info.plist file at `Pods/Target Support Files/path_provider/path_provider-Info.plist`
          - Generating dummy source at `Pods/Target Support Files/path_provider/path_provider-dummy.m`
        - Installing target `permission_handler` iOS 8.0
          - Generating module map file at `Pods/Target Support Files/permission_handler/permission_handler.modulemap`
          - Generating umbrella header at `Pods/Target Support Files/permission_handler/permission_handler-umbrella.h`
          - Generating Info.plist file at `Pods/Target Support Files/permission_handler/permission_handler-Info.plist`
          - Generating dummy source at `Pods/Target Support Files/permission_handler/permission_handler-dummy.m`
      - Installing Aggregate Targets
        - Installing target `Pods-Runner` iOS 11.0
          - Generating Info.plist file at `Pods/Target Support Files/Pods-Runner/Pods-Runner-Info.plist`
          - Generating module map file at `Pods/Target Support Files/Pods-Runner/Pods-Runner.modulemap`
          - Generating umbrella header at `Pods/Target Support Files/Pods-Runner/Pods-Runner-umbrella.h`
          - Generating dummy source at `Pods/Target Support Files/Pods-Runner/Pods-Runner-dummy.m`
      - Generating deterministic UUIDs
      - Stabilizing target UUIDs
      - Running post install hooks
    [!] An error occurred while processing the post-install hook of the Podfile.

    undefined method `headers_build_phase' for #<Xcodeproj::Project::Object::PBXAggregateTarget:0x00007fbadd529eb0>

    /Users/nurzhan/Desktop/Grata/grata_FULL/mobileApp/ios/Podfile:87:in `block (3 levels) in from_ruby'
    /Users/nurzhan/Desktop/Grata/grata_FULL/mobileApp/ios/Podfile:83:in `each'
    /Users/nurzhan/Desktop/Grata/grata_FULL/mobileApp/ios/Podfile:83:in `block (2 levels) in from_ruby'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/podfile.rb:179:in `post_install!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:856:in `run_podfile_post_install_hook'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:844:in `block in run_podfile_post_install_hooks'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:145:in `message'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:843:in `run_podfile_post_install_hooks'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:322:in `block in create_and_save_projects'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:303:in `create_and_save_projects'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:294:in `generate_pods_project'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:173:in `integrate'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:162:in `install!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.3.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:22:in `load'
    /usr/local/bin/pod:22:in `<main>'

    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:858:in `rescue in run_podfile_post_install_hook'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:855:in `run_podfile_post_install_hook'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:844:in `block in run_podfile_post_install_hooks'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:145:in `message'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:843:in `run_podfile_post_install_hooks'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:322:in `block in create_and_save_projects'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:303:in `create_and_save_projects'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:294:in `generate_pods_project'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:173:in `integrate'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:162:in `install!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.3.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:22:in `load'
    /usr/local/bin/pod:22:in `<main>'

Error running pod install
Error launching application on iPhone 11 Pro Max.
```
