### ISSUE TITLE
Malformed version number string {VER}

### ISSUE THREAD

**Issue by MeteC** [CocoaPods/CocoaPods#8785]
### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?
I added the `:git => ...` specifier to the podfile line beginning `pod 'SharkORM'...` (see below)

* What did you expect to happen?
To pull the SharkORM pod from git master branch

* What happened instead?
Message "Pre-downloading: `SharkORM` from `https://github.com/sharksync/sharkorm.git`" appears and then it crashes, providing me this template.

Note without the :git => specifier here, all is well.
I first encountered this issue running CocoaPods 1.5.0, then updated, but get the same problem.

### Stack

```
   CocoaPods : 1.6.1
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.4 (18E226)
       Xcode : 10.2.1 (10E1001)
         Git : git version 2.20.1 (Apple Git-117)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 87bd6b740f63965d823ecd1fd94d0aceb4561c8a
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

abstract_target 'ASIGN' do
    
    pod 'SharkORM', :git => 'https://github.com/sharksync/sharkorm.git', :inhibit_warnings => true # specify git to get actual latest version
    pod 'CocoaAsyncSocket'
    pod 'AFNetworking', '~> 3.0'
    # pod 'what3words', :git => 'https://github.com/what3words/w3w-swift-wrapper.git' # this is the online version
    pod 'CocoaLumberjack/Swift'
    pod 'SimpleKeychain'
    
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'FCAlertView', :inhibit_warnings => true
    pod 'OpenSSL-Universal' # for GR4 TLS
    
    pod 'ClusterKit/MapKit' # for GeoAlerts for now.. useful for other map stuff?
    pod 'SwiftRichString'
    
    target 'ASIGN Pro' do
      # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
      use_frameworks!

      # Pods for ASIGN Pro
      
    end

    target 'DSIGN Pro' do
      use_frameworks!

      # Pods for DSIGN Pro

    end
    
    
    # TEST TARGETS
    target 'Tests-CORE' do
        use_frameworks!
    end
    
    target 'Tests-GR4' do
        use_frameworks!
    end
    
    # BASIC ASIGNS
    
    target 'UN-ASIGN' do
        use_frameworks!
    end
    
    target 'UN-DSIGN' do
        use_frameworks!
    end
    
    target 'IGAD-ASIGN' do
        use_frameworks!
    end
    
    target 'Satellite-ASIGN' do
        use_frameworks!
    end
    
    target 'UN-Pilot' do
        use_frameworks!
    end
    
    target 'UAV-Pilot' do
        use_frameworks!
    end
    
    target 'UAV-ASIGN' do
        use_frameworks!
        
        pod 'DJI-SDK-iOS', '~> 4.6'
        pod 'DJI-UXSDK-iOS', '~> 4.6'
        pod 'DJIWidget', '~> 1.0'
    end
    
    target 'Praetium' do
        use_frameworks!
    end
    
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF'] = 'NO'
        end
    end
end
```

### Error

```
ArgumentError - Malformed version number string {VER}
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.6.1/lib/cocoapods-core/version.rb:47:in `initialize'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.6.1/lib/cocoapods-core/vendor/version.rb:199:in `new'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.6.1/lib/cocoapods-core/vendor/version.rb:199:in `new'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.6.1/lib/cocoapods-core/specification/root_attribute_accessors.rb:37:in `version'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.6.1/lib/cocoapods-core/specification/linter.rb:124:in `block in check_required_attributes'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.6.1/lib/cocoapods-core/specification/linter.rb:123:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.6.1/lib/cocoapods-core/specification/linter.rb:123:in `check_required_attributes'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.6.1/lib/cocoapods-core/specification/linter.rb:50:in `lint'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/validator.rb:340:in `perform_linting'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/validator.rb:127:in `validate'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/external_sources/abstract_external_source.rb:191:in `block in validate_podspec'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/config.rb:41:in `with_changes'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/external_sources/abstract_external_source.rb:190:in `validate_podspec'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/external_sources/abstract_external_source.rb:178:in `store_podspec'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/external_sources/abstract_external_source.rb:130:in `block in pre_download'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/user_interface.rb:86:in `titled_section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/external_sources/abstract_external_source.rb:113:in `pre_download'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/external_sources/downloader_source.rb:13:in `fetch'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:825:in `fetch_external_source'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:804:in `block (2 levels) in fetch_external_sources'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:803:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:803:in `block in fetch_external_sources'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:802:in `fetch_external_sources'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:107:in `analyze'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:266:in `analyze'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:174:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:173:in `resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:136:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/command/install.rb:48:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

**Comment by orta** [comment]
[`{VER}` isn't](https://github.com/sharksync/sharkorm/blob/master/SharkORM.podspec#L10) a real semantic version number, and so it fails. You should probably send a PR to that repo and make it a normal version.

That said, CocoaPods could do a better job on the error report here (saying the name of the pod, the failing server version, and what it should look like)

**Comment by MeteC** [comment]
Yeah I kind of figured it was up to the repo to fix that, and mentioned it to them, but I filed it here since the crash was so spectacular ;-)
