### ISSUE TITLE
Invalid argument @ io_fread error when linting pod with large vendored files (>2gb)

### ISSUE THREAD

**Issue by phildow** [CocoaPods/CocoaPods#8786]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

pod spec lint TensorIOTensorFlow.podspec --verbose

## What did you expect to happen?

I expected file the pod to lint correctly

## What happened instead?

The pod fails to lint with the following error:

```
- ERROR | [iOS] unknown: Encountered an unknown error (Invalid argument @ io_fread - /path/to/vendored/framework/file

/Library/Ruby/Gems/2.3.0/gems/ruby-macho-1.4.0/lib/macho/fat_file.rb:94:in `read'
/Library/Ruby/Gems/2.3.0/gems/ruby-macho-1.4.0/lib/macho/fat_file.rb:94:in `open'
/Library/Ruby/Gems/2.3.0/gems/ruby-macho-1.4.0/lib/macho/fat_file.rb:94:in `initialize'
/Library/Ruby/Gems/2.3.0/gems/ruby-macho-1.4.0/lib/macho.rb:31:in `new'
/Library/Ruby/Gems/2.3.0/gems/ruby-macho-1.4.0/lib/macho.rb:31:in `open'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/sandbox/file_accessor.rb:436:in `dynamic_binary?'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/sandbox/file_accessor.rb:171:in `block in vendored_dynamic_frameworks'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/sandbox/file_accessor.rb:170:in `select'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/sandbox/file_accessor.rb:170:in `vendored_dynamic_frameworks'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/sandbox/file_accessor.rb:179:in `vendored_static_frameworks'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/sandbox/file_accessor.rb:245:in `vendored_static_artifacts'
...
```

As far as I can tell this is a problem with ruby reading files larger than 2gb. The file is a static library we are vending in a .framework bundle and comes in at a hefty ~2.5gb. The previous version of this framework vended a smaller static library with the same directory structure and it linted without any issues.

### Stack

```
   CocoaPods : 1.6.0
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.4 (18E226)
       Xcode : 10.2.1 (10E1001)
         Git : git version 2.20.1 (Apple Git-117)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 79664131a6e07a7492255fc8e1135ced79a6a7c8
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

https://github.com/doc-ai/tensorio-tensorflow-ios

**Comment by dnkoutso** [comment]
Seems like a bug in `ruby-macho` gem. /cc @woodruffw 

Perhaps fixed in the latest 2.x version but CocoaPods is still on the 1.x version.

**Comment by phildow** [comment]
Will attempt a lint with 2.x and report back

**Comment by woodruffw** [comment]
My guess is that the `fread` that underlies ruby-macho's `File.read` is failing at the signed 32-bit boundary (2.5GB would put you _just_ over that). I'll take a look this evening.

**Comment by woodruffw** [comment]
Hmm, so here's the `io_fread` signature:

```c
static long
io_fread(VALUE str, long offset, long size, rb_io_t *fptr)
```

I'm *pretty* sure macOS is LP64, so `size` shouldn't be overflowing at 2.5GB. The only other actual failure mode in `io_fread` looks like the string re-allocation, but I don't think that's what's failing here (I'd expect a different error). So I'm a bit stumped, at least until I look into this more deeply.

Generally speaking, it would be ideal if `ruby-macho` didn't suck the entire file into memory to perform its operations. Unfortunately, most of the current codebase is built around the assumption that a raw buffer of the file's contents is always available. It might be feasible to add a mode that only parses the load commands, which would reduce the size of the in-memory buffer drastically.

**Comment by yyoon** [comment]
Any updates on this? I am experiencing the exact same issue while linting.

**Comment by woodruffw** [comment]
> Any updates on this? I am experiencing the exact same issue while linting.

No update on the ruby-macho side. I haven't had time to work on an I/O abstraction that avoids sucking the whole binary into memory, but would review and accept a PR for one.

In the mean time, my recommendation (which you should take with a grain of salt, since I don't know anything about iOS apps!) is that you vendor or otherwise rearchitect your Mach-Os so that they fall under ~2.4GB.

**Comment by yyoon** [comment]
Okay. Thanks for the quick reply. I guess the current viable workaround is to remove one of the less used target architecture (x86_64) from the vendored framework.

**Comment by Lianghuajian** [comment]
You can consider to remove unnecessarily mach-o archs from Pods/ in pre_install time, I solve this problem doing this
```
require 'fileutils'
require 'open3'

pre_install do | installer |
  puts "pod time pre_install #{Time.now.to_s}"

#  if $build_machine
#    pod_library_thin(['i386','x86_64'])
#  else
    # local pods
    pod_library_thin(['armv7','i386'])
#  end

  puts "pod time pre_install finish #{Time.now.to_s}"
end

def pod_library_thin(archs)

  if archs.empty?
    return
  end

  libraries = Dir["Pods/**/*.a"]

  size_before = 0
  size_after = 0
  libraries.each { |e|
    size_before = size_before + File.size(e)
    archs.each { |arch|
      cmd = "lipo -remove #{arch} #{e} -output #{e}"
      stdout, stderr, status = Open3.capture3(cmd)
    }
    size_after = size_after + File.size(e)
  }
  puts 'pod_library_thin %.1f M' % ((size_before - size_after).to_f / (1024 ** 2))
end

```

**Comment by bitfriend** [comment]
In my case, `ruby-macho` failed about even 700MB of input file.
I tried all versions of `ruby-macho` up to `1.11.3`, but nothing could solve error `Invalid argument @ io_fread`.
The only solution was to reduce input file size under the error in source code not fixed.
I used release build of my library as input file, instead of debug build.
Its size was 200MB and this solution compiled iOS app and ran it on iOS simulator successfully.
