### ISSUE TITLE
Failed to update an old podspec

### ISSUE THREAD

**Issue by ppamorim** [CocoaPods/CocoaPods#8793]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I am trying to update the spec of my repo but I am getting a Swift version error.

## What did you expect to happen?

Release the version 0.9 of my repo.

## What happened instead?

When I run `pod lib lint --no-clean --verbose`, I get this error:

(I don't have anything setting swift 3.0.2 on the current project)

```
    CircularRevealKit (0.9) - Analyzing on iOS 9.0 platform.
  Preparing

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-App`: (``)

Fetching external sources
-> Fetching podspec for `CircularRevealKit` from `/Users/ppamorim/Repository/CircularRevealKit`

Resolving dependencies of 

Comparing resolved specification to the sandbox manifest
  A CircularRevealKit

Downloading dependencies

-> Installing CircularRevealKit (0.9)
  - Running pre install hooks

Generating Pods project
  - Creating Pods project
  - Adding source files to Pods project
  - Adding frameworks to Pods project
  - Adding libraries to Pods project
  - Adding resources to Pods project
  - Adding development pod helper files to Pods project
  - Linking headers
  - Installing targets
    - Installing target `CircularRevealKit` iOS 9.0
      - Generating module map file at
      `../../../../private/var/folders/c5/hdl6lqzj1ljd28rq603r3k_c0000gp/T/CocoaPods-Lint-20190511-61506-juthsi-CircularRevealKit/Pods/Target
      Support Files/CircularRevealKit/CircularRevealKit.modulemap`
      - Generating umbrella header at
      `../../../../private/var/folders/c5/hdl6lqzj1ljd28rq603r3k_c0000gp/T/CocoaPods-Lint-20190511-61506-juthsi-CircularRevealKit/Pods/Target
      Support Files/CircularRevealKit/CircularRevealKit-umbrella.h`
      - Generating Info.plist file at
      `../../../../private/var/folders/c5/hdl6lqzj1ljd28rq603r3k_c0000gp/T/CocoaPods-Lint-20190511-61506-juthsi-CircularRevealKit/Pods/Target
      Support Files/CircularRevealKit/CircularRevealKit-Info.plist`
      - Generating dummy source at
      `../../../../private/var/folders/c5/hdl6lqzj1ljd28rq603r3k_c0000gp/T/CocoaPods-Lint-20190511-61506-juthsi-CircularRevealKit/Pods/Target
      Support Files/CircularRevealKit/CircularRevealKit-dummy.m`
    - Installing target `Pods-App` iOS 9.0
      - Generating Info.plist file at
      `../../../../private/var/folders/c5/hdl6lqzj1ljd28rq603r3k_c0000gp/T/CocoaPods-Lint-20190511-61506-juthsi-CircularRevealKit/Pods/Target
      Support Files/Pods-App/Pods-App-Info.plist`
      - Generating module map file at
      `../../../../private/var/folders/c5/hdl6lqzj1ljd28rq603r3k_c0000gp/T/CocoaPods-Lint-20190511-61506-juthsi-CircularRevealKit/Pods/Target
      Support Files/Pods-App/Pods-App.modulemap`
      - Generating umbrella header at
      `../../../../private/var/folders/c5/hdl6lqzj1ljd28rq603r3k_c0000gp/T/CocoaPods-Lint-20190511-61506-juthsi-CircularRevealKit/Pods/Target
      Support Files/Pods-App/Pods-App-umbrella.h`
      - Generating dummy source at
      `../../../../private/var/folders/c5/hdl6lqzj1ljd28rq603r3k_c0000gp/T/CocoaPods-Lint-20190511-61506-juthsi-CircularRevealKit/Pods/Target
      Support Files/Pods-App/Pods-App-dummy.m`
  - Running post install hooks
  - Writing Xcode project file to
  `../../../../private/var/folders/c5/hdl6lqzj1ljd28rq603r3k_c0000gp/T/CocoaPods-Lint-20190511-61506-juthsi-CircularRevealKit/Pods/Pods.xcodeproj`
  - Writing Lockfile in
  `../../../../var/folders/c5/hdl6lqzj1ljd28rq603r3k_c0000gp/T/CocoaPods-Lint-20190511-61506-juthsi-CircularRevealKit/Podfile.lock`
  - Writing Manifest in
  `../../../../private/var/folders/c5/hdl6lqzj1ljd28rq603r3k_c0000gp/T/CocoaPods-Lint-20190511-61506-juthsi-CircularRevealKit/Pods/Manifest.lock`

Integrating client project

[!] Please close any current Xcode sessions and use `App.xcworkspace` for this project from now on.

Integrating target `Pods-App` (`../../../../var/folders/c5/hdl6lqzj1ljd28rq603r3k_c0000gp/T/CocoaPods-Lint-20190511-61506-juthsi-CircularRevealKit/App.xcodeproj` project)
  Adding Build Phase '[CP] Embed Pods Frameworks' to project.
  Adding Build Phase '[CP] Check Pods Manifest.lock' to project.

-> Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.
   Building with `xcodebuild`. 
    $ /usr/bin/xcodebuild clean build -workspace
    /var/folders/c5/hdl6lqzj1ljd28rq603r3k_c0000gp/T/CocoaPods-Lint-20190511-61506-juthsi-CircularRevealKit/App.xcworkspace
    -scheme App -configuration Release CODE_SIGN_IDENTITY=- -sdk iphonesimulator -destination
    id=CB6AC203-5ED2-4CAC-B13B-7160020DB3B8
    Build settings from command line:
        CODE_SIGN_IDENTITY = -
        SDKROOT = iphonesimulator12.2
    
    note: Using new build system
    
    ** CLEAN SUCCEEDED **
    
    note: Using new build system
    note: Planning build
    note: Constructing build description
    Build system information
    error: SWIFT_VERSION '3.0.2' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'App')
    
    Build system information
    error: SWIFT_VERSION '3.0.2' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'CircularRevealKit')
    
    Build system information
    error: SWIFT_VERSION '3.0.2' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'App')
    
    Build system information
    error: SWIFT_VERSION '3.0.2' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'CircularRevealKit')
    
    ** BUILD FAILED **
    
   Testing with `xcodebuild`. 
 -> CircularRevealKit (0.9)
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code.
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | [iOS] xcodebuild:  note: Planning build
    - NOTE  | [iOS] xcodebuild:  note: Constructing build description
    - NOTE  | xcodebuild:  error: SWIFT_VERSION '3.0.2' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'App')
    - NOTE  | xcodebuild:  error: SWIFT_VERSION '3.0.2' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'CircularRevealKit')

Pods workspace available at `/var/folders/c5/hdl6lqzj1ljd28rq603r3k_c0000gp/T/CocoaPods-Lint-20190511-61506-juthsi-CircularRevealKit/App.xcworkspace` for inspection.

[!] CircularRevealKit did not pass validation, due to 1 error.

/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/command/lib/lint.rb:92:in `block in run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/command/lib/lint.rb:60:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/command/lib/lint.rb:60:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

### Stack

```
   CocoaPods : 1.6.1
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 3.0.3
        Host : Mac OS X 10.14.4 (18E226)
       Xcode : 10.2.1 (10E1001)
         Git : git version 2.20.1 (Apple Git-117)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ c83fce913abede26fda19c96a05a1ea4276a587a
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

https://github.com/T-Pro/CircularRevealKit

**Comment by dnkoutso** [comment]
You are using a newer version of Xcode. Please update. Set `s.swift_version = '4.0'` in your podspec.

Will re-open if we find a bug.

**Comment by ppamorim** [comment]
@dnkoutso I am not setting the swift version on my podspec, shouldn't it be transparent. Will my project work on Swift 4.2 projects if I set 5.0?

**Comment by ppamorim** [comment]
@dnkoutso I managed to solve this by removing the `.swift-version` file produced by a old cocoapods version and adding the flag `s.swift_version = '5.0'`. I was able to detect it based on this comment:

https://github.com/MaxDesiatov/XMLCoder/issues/57#issuecomment-451905813

I believe that `pod lib lint` should detect this file and warn the developer that this is deprecated and should be removed.
