### ISSUE TITLE
Cannot reference git projects on a podspec file

### ISSUE THREAD

**Issue by rdlopes** [CocoaPods/CocoaPods#885]
-> ObjectiveScrap
### Report
- What did you do?
  Trying to reference a github project in my podspec file, that can be found at https://github.com/rdlopes/ObjectiveScrap/blob/master/ObjectiveScrap.podspec

Tried:
1- s.dependency 'HTMLDocument', :git => "https://github.com/stklieme/HTMLDocument.git", :tag => "0.0.1"
2- s.dependency 'HTMLDocument', :git => "https://github.com/stklieme/HTMLDocument.git"
3- s.dependency 'HTMLDocument', :podspec => "Specs/HTMLDocument.podspec"
None is working.
- What did you expect to happen?
  pod spec lint would analyse the podspec and pass validation
- What happened instead?
  validation fails because of an illformed requirement
### Stack

```
   CocoaPods : 0.17.0.rc2
        Ruby : ruby 1.9.3p286 (2012-10-12 revision 37165) [x86_64-darwin12]
    RubyGems : 2.0.0
        Host : Mac OS X 10.8.3 (12D78)
       Xcode : 4.6.1 (4H512)
Ruby lib dir : /opt/local/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ b7cbde16a685f3f73f6373deba5e78b63517d430
               rdlopes - git@github.com:rdlopes/Specs.git @ 68db630cf9fc76cfea3fc06acbbc64012426f4d8
```
### Error

```
ArgumentError - Illformed requirement [{:git=>"https://github.com/stklieme/HTMLDocument.git", :tag=>"0.0.1"}]
/opt/local/lib/ruby1.9/gems/1.9.1/gems/cocoapods-core-0.17.0.rc2/lib/cocoapods-core/vendor/requirement.rb:83:in `parse'
/opt/local/lib/ruby1.9/gems/1.9.1/gems/cocoapods-core-0.17.0.rc2/lib/cocoapods-core/vendor/requirement.rb:108:in `block in initialize'
/opt/local/lib/ruby1.9/gems/1.9.1/gems/cocoapods-core-0.17.0.rc2/lib/cocoapods-core/vendor/requirement.rb:108:in `map!'
/opt/local/lib/ruby1.9/gems/1.9.1/gems/cocoapods-core-0.17.0.rc2/lib/cocoapods-core/vendor/requirement.rb:108:in `initialize'
/opt/local/lib/ruby1.9/gems/1.9.1/gems/cocoapods-core-0.17.0.rc2/lib/cocoapods-core/vendor/requirement.rb:46:in `new'
/opt/local/lib/ruby1.9/gems/1.9.1/gems/cocoapods-core-0.17.0.rc2/lib/cocoapods-core/vendor/requirement.rb:46:in `create'
/opt/local/lib/ruby1.9/gems/1.9.1/gems/cocoapods-core-0.17.0.rc2/lib/cocoapods-core/vendor/dependency.rb:52:in `initialize'
/opt/local/lib/ruby1.9/gems/1.9.1/gems/cocoapods-core-0.17.0.rc2/lib/cocoapods-core/dependency.rb:77:in `initialize'
/opt/local/lib/ruby1.9/gems/1.9.1/gems/cocoapods-core-0.17.0.rc2/lib/cocoapods-core/specification/consumer.rb:147:in `new'
/opt/local/lib/ruby1.9/gems/1.9.1/gems/cocoapods-core-0.17.0.rc2/lib/cocoapods-core/specification/consumer.rb:147:in `block in dependencies'
/opt/local/lib/ruby1.9/gems/1.9.1/gems/cocoapods-core-0.17.0.rc2/lib/cocoapods-core/specification/consumer.rb:146:in `each'
/opt/local/lib/ruby1.9/gems/1.9.1/gems/cocoapods-core-0.17.0.rc2/lib/cocoapods-core/specification/consumer.rb:146:in `map'
/opt/local/lib/ruby1.9/gems/1.9.1/gems/cocoapods-core-0.17.0.rc2/lib/cocoapods-core/specification/consumer.rb:146:in `dependencies'
/opt/local/lib/ruby1.9/gems/1.9.1/gems/cocoapods-core-0.17.0.rc2/lib/cocoapods-core/specification.rb:252:in `dependencies'
/opt/local/lib/ruby1.9/gems/1.9.1/gems/cocoapods-core-0.17.0.rc2/lib/cocoapods-core/specification.rb:263:in `all_dependencies'
/opt/local/lib/ruby1.9/gems/1.9.1/gems/cocoapods-0.17.0.rc2/lib/cocoapods/resolver.rb:163:in `block (2 levels) in find_dependency_specs'
/opt/local/lib/ruby1.9/gems/1.9.1/gems/cocoapods-0.17.0.rc2/lib/cocoapods/user_interface.rb:107:in `message'
/opt/local/lib/ruby1.9/gems/1.9.1/gems/cocoapods-0.17.0.rc2/lib/cocoapods/resolver.rb:152:in `block in find_dependency_specs'
/opt/local/lib/ruby1.9/gems/1.9.1/gems/cocoapods-0.17.0.rc2/lib/cocoapods/resolver.rb:148:in `each'
/opt/local/lib/ruby1.9/gems/1.9.1/gems/cocoapods-0.17.0.rc2/lib/cocoapods/resolver.rb:148:in `find_dependency_specs'
/opt/local/lib/ruby1.9/gems/1.9.1/gems/cocoapods-0.17.0.rc2/lib/cocoapods/resolver.rb:65:in `block (2 levels) in resolve'
/opt/local/lib/ruby1.9/gems/1.9.1/gems/cocoapods-0.17.0.rc2/lib/cocoapods/user_interface.rb:46:in `section'
/opt/local/lib/ruby1.9/gems/1.9.1/gems/cocoapods-0.17.0.rc2/lib/cocoapods/resolver.rb:63:in `block in resolve'
/opt/local/lib/ruby1.9/gems/1.9.1/gems/cocoapods-0.17.0.rc2/lib/cocoapods/resolver.rb:62:in `each'
/opt/local/lib/ruby1.9/gems/1.9.1/gems/cocoapods-0.17.0.rc2/lib/cocoapods/resolver.rb:62:in `resolve'
/opt/local/lib/ruby1.9/gems/1.9.1/gems/cocoapods-0.17.0.rc2/lib/cocoapods/installer/analyzer.rb:286:in `block in resolve_dependencies'
/opt/local/lib/ruby1.9/gems/1.9.1/gems/cocoapods-0.17.0.rc2/lib/cocoapods/user_interface.rb:46:in `section'
/opt/local/lib/ruby1.9/gems/1.9.1/gems/cocoapods-0.17.0.rc2/lib/cocoapods/installer/analyzer.rb:284:in `resolve_dependencies'
/opt/local/lib/ruby1.9/gems/1.9.1/gems/cocoapods-0.17.0.rc2/lib/cocoapods/installer/analyzer.rb:56:in `analyze'
/opt/local/lib/ruby1.9/gems/1.9.1/gems/cocoapods-0.17.0.rc2/lib/cocoapods/installer.rb:156:in `analyze'

/opt/local/lib/ruby1.9/gems/1.9.1/gems/cocoapods-0.17.0.rc2/lib/cocoapods/installer.rb:92:in `block in resolve_dependencies'
/opt/local/lib/ruby1.9/gems/1.9.1/gems/cocoapods-0.17.0.rc2/lib/cocoapods/user_interface.rb:46:in `section'
/opt/local/lib/ruby1.9/gems/1.9.1/gems/cocoapods-0.17.0.rc2/lib/cocoapods/installer.rb:91:in `resolve_dependencies'
/opt/local/lib/ruby1.9/gems/1.9.1/gems/cocoapods-0.17.0.rc2/lib/cocoapods/installer.rb:84:in `install!'
/opt/local/lib/ruby1.9/gems/1.9.1/gems/cocoapods-0.17.0.rc2/lib/cocoapods/validator.rb:238:in `install_pod'
/opt/local/lib/ruby1.9/gems/1.9.1/gems/cocoapods-0.17.0.rc2/lib/cocoapods/validator.rb:205:in `block in perform_extensive_analysis'
/opt/local/lib/ruby1.9/gems/1.9.1/gems/cocoapods-0.17.0.rc2/lib/cocoapods/validator.rb:201:in `each'
/opt/local/lib/ruby1.9/gems/1.9.1/gems/cocoapods-0.17.0.rc2/lib/cocoapods/validator.rb:201:in `perform_extensive_analysis'
/opt/local/lib/ruby1.9/gems/1.9.1/gems/cocoapods-0.17.0.rc2/lib/cocoapods/validator.rb:69:in `validate'
/opt/local/lib/ruby1.9/gems/1.9.1/gems/cocoapods-0.17.0.rc2/lib/cocoapods/command/spec.rb:95:in `block in run'
/opt/local/lib/ruby1.9/gems/1.9.1/gems/cocoapods-0.17.0.rc2/lib/cocoapods/command/spec.rb:89:in `each'
/opt/local/lib/ruby1.9/gems/1.9.1/gems/cocoapods-0.17.0.rc2/lib/cocoapods/command/spec.rb:89:in `run'
/opt/local/lib/ruby1.9/gems/1.9.1/gems/claide-0.2.0/lib/claide.rb:535:in `run'
/opt/local/lib/ruby1.9/gems/1.9.1/gems/cocoapods-0.17.0.rc2/lib/cocoapods/command.rb:36:in `run'
/opt/local/lib/ruby1.9/gems/1.9.1/gems/cocoapods-0.17.0.rc2/bin/pod:16:in `<top (required)>'
/opt/local/bin/pod:23:in `load'
/opt/local/bin/pod:23:in `<main>'
```

**Comment by newmanw** [comment]
is this ever going to be possible?  Don't always have control over wether or no author will release to cocoapods.
