### ISSUE TITLE
NoMethodError - undefined method `recursive_predecessors' for nil:NilClass

### ISSUE THREAD

**Issue by whiteholekong** [CocoaPods/CocoaPods#8860]
――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod update
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.4.0
        Ruby : ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
    RubyGems : 2.6.11
        Host : Mac OS X 10.14.5 (18F132)
       Xcode : 10.2.1 (10E1001)
         Git : git version 2.20.1 (Apple Git-117)
Ruby lib dir : /usr/local/Cellar/ruby/2.4.1_1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 40ae43598f28ec09f2759eb6fff346688a7405d5
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

def pods
  pod 'Cartography'
  pod 'Localize-Swift'
  pod 'libPhoneNumber-iOS'
  pod 'PKHUD'
  pod 'FontAwesome.swift'
  pod 'Charts', '3.1.1'

  pod 'ObjectMapper'
  pod 'Moya'
  pod 'Moya/RxSwift'
  pod 'Moya-ObjectMapper/RxSwift'
  pod 'SwiftyJSON'
  pod 'AlamofireObjectMapper'
  
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxKeyboard', '~> 0.3'
  
  pod 'Stripe'
  
  pod 'Firebase/Core'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/Messaging'
  
  pod 'SwiftyRSA'
  
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  
end


target 'KeyChain Pay' do
  pods
end

target 'KeyChain Pay Dev' do
  pods
end
```

### Error

```
NoMethodError - undefined method `recursive_predecessors' for nil:NilClass
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.4.0/lib/cocoapods/resolver.rb:526:in `spec_is_platform_compatible?'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.4.0/lib/cocoapods/resolver.rb:220:in `requirement_satisfied_by?'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.4/lib/molinillo/delegates/specification_provider.rb:25:in `block in requirement_satisfied_by?'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.4/lib/molinillo/delegates/specification_provider.rb:70:in `with_no_such_dependency_error_handling'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.4/lib/molinillo/delegates/specification_provider.rb:24:in `requirement_satisfied_by?'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.4/lib/molinillo/resolution.rb:486:in `block in possibility_satisfies_requirements?'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.4/lib/molinillo/resolution.rb:486:in `each'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.4/lib/molinillo/resolution.rb:486:in `all?'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.4/lib/molinillo/resolution.rb:486:in `possibility_satisfies_requirements?'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.4/lib/molinillo/resolution.rb:471:in `block (3 levels) in filter_possibilities_for_primary_unwind'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.4/lib/molinillo/resolution.rb:470:in `any?'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.4/lib/molinillo/resolution.rb:470:in `block (2 levels) in filter_possibilities_for_primary_unwind'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.4/lib/molinillo/resolution.rb:469:in `each'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.4/lib/molinillo/resolution.rb:469:in `none?'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.4/lib/molinillo/resolution.rb:469:in `block in filter_possibilities_for_primary_unwind'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.4/lib/molinillo/resolution.rb:468:in `reject!'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.4/lib/molinillo/resolution.rb:468:in `filter_possibilities_for_primary_unwind'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.4/lib/molinillo/resolution.rb:453:in `filter_possibilities_after_unwind'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.4/lib/molinillo/resolution.rb:314:in `block in unwind_for_conflict'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.4/lib/molinillo/resolution.rb:308:in `tap'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.4/lib/molinillo/resolution.rb:308:in `unwind_for_conflict'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.4/lib/molinillo/resolution.rb:702:in `attempt_to_filter_existing_spec'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.4/lib/molinillo/resolution.rb:673:in `attempt_to_activate'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.4/lib/molinillo/resolution.rb:254:in `process_topmost_state'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.4/lib/molinillo/resolution.rb:182:in `resolve'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.4/lib/molinillo/resolver.rb:43:in `resolve'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.4.0/lib/cocoapods/resolver.rb:110:in `resolve'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/analyzer.rb:770:in `block in resolve_dependencies'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.4.0/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/analyzer.rb:767:in `resolve_dependencies'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/analyzer.rb:85:in `analyze'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:243:in `analyze'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:154:in `block in resolve_dependencies'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.4.0/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:153:in `resolve_dependencies'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:116:in `install!'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.4.0/lib/cocoapods/command/update.rb:81:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.4.0/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.4.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

**Comment by dnkoutso** [comment]
Please upgrade to CocoaPods 1.7.0. The report also does not contain enough information for us to the issue.

I will re-open this once more information is attached.

**Comment by whiteholekong** [comment]
――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod update
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.7.2
        Ruby : ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
    RubyGems : 2.6.11
        Host : Mac OS X 10.14.5 (18F132)
       Xcode : 10.2.1 (10E1001)
         Git : git version 2.20.1 (Apple Git-117)
Ruby lib dir : /usr/local/Cellar/ruby/2.4.1_1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ e20a33e6c6fcf7a6413e27c9b32684bf74b7d41b
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

def pods
  pod 'Cartography'
  pod 'Localize-Swift'
  pod 'libPhoneNumber-iOS'
  pod 'PKHUD'
  pod 'FontAwesome.swift'
  pod 'Charts', '3.1.1'

  pod 'ObjectMapper'
  pod 'Moya'
  pod 'Moya/RxSwift'
  pod 'Moya-ObjectMapper/RxSwift'
  pod 'SwiftyJSON'
  pod 'AlamofireObjectMapper'
  
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxKeyboard', '~> 0.3'
  
  pod 'Stripe', '15.0.1'
  
  pod 'Firebase/Core'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/Messaging'
  pod 'Firebase/Analytics'
  pod 'Firebase/Performance'
  
  # Pods for PodTest
  pod 'Fabric', '~> 1.10.1'
  pod 'Crashlytics', '~> 3.13.1'
  
  pod 'SwiftyRSA'
  
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  
end


target 'my-app' do
  pods
end

```

### Error

```
NoMethodError - undefined method `recursive_predecessors' for nil:NilClass
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.7.2/lib/cocoapods/resolver.rb:519:in `spec_is_platform_compatible?'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.7.2/lib/cocoapods/resolver.rb:201:in `requirement_satisfied_by?'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:25:in `block in requirement_satisfied_by?'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:70:in `with_no_such_dependency_error_handling'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:24:in `requirement_satisfied_by?'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:486:in `block in possibility_satisfies_requirements?'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:486:in `each'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:486:in `all?'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:486:in `possibility_satisfies_requirements?'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:471:in `block (3 levels) in filter_possibilities_for_primary_unwind'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:470:in `any?'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:470:in `block (2 levels) in filter_possibilities_for_primary_unwind'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:469:in `each'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:469:in `none?'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:469:in `block in filter_possibilities_for_primary_unwind'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:468:in `reject!'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:468:in `filter_possibilities_for_primary_unwind'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:453:in `filter_possibilities_after_unwind'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:314:in `block in unwind_for_conflict'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `tap'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `unwind_for_conflict'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:702:in `attempt_to_filter_existing_spec'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:673:in `attempt_to_activate'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:254:in `process_topmost_state'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
/usr/local/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.7.2/lib/cocoapods/resolver.rb:88:in `resolve'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.7.2/lib/cocoapods/installer/analyzer.rb:939:in `block in resolve_dependencies'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.7.2/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.7.2/lib/cocoapods/installer/analyzer.rb:937:in `resolve_dependencies'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.7.2/lib/cocoapods/installer/analyzer.rb:118:in `analyze'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.7.2/lib/cocoapods/installer.rb:398:in `analyze'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.7.2/lib/cocoapods/installer.rb:221:in `block in resolve_dependencies'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.7.2/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.7.2/lib/cocoapods/installer.rb:220:in `resolve_dependencies'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.7.2/lib/cocoapods/installer.rb:156:in `install!'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.7.2/lib/cocoapods/command/update.rb:62:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.7.2/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.7.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

**Comment by whiteholekong** [comment]
Error still occur after I upgrade CocoaPods to 1.7.2 and remove whole pod project and reinstall it.

**Comment by dnkoutso** [comment]
Please upload a sample app and I can re-open this issue or I will file a new one.

**Comment by upendrasiripurapu** [comment]
Hi, I'm facing the same issue. If you managed to solve this issue can you please post it here. Thank you.

**Comment by whiteholekong** [comment]
I still cannot solve this issue. I need install every time.

**Comment by upendrasiripurapu** [comment]
If possible, can you explain me what does install every time means. I tried all the possible ways like updating cocoapods, deintegrating pods, manually removing pods and added again and many more. But still I'm not able to run the app.

**Comment by whiteholekong** [comment]
I mean I need to call "pod install" instead of "pod update".

**Comment by ravi-culturealley** [comment]
Any solution? I am getting the same error with latest pod & macOS.

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.11.3
        Ruby : ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.x86_64-darwin21]
    RubyGems : 3.0.3.1
        Host : macOS 12.5.1 (21G83)
       Xcode : 13.4.1 (13F100)
         Git : git version 2.36.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '12.0'

# ignore all warnings from all pods
inhibit_all_warnings!

target 'my-app' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Google Pods
  pod 'GoogleSignIn'
  pod 'GoogleMobileAdsMediationFacebook'
  pod 'GoogleMobileAdsMediationUnity'
  pod 'GoogleMobileAdsMediationAdColony'

  # Firebase Pods
  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/Auth'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/AdMob'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/InAppMessaging'
  pod 'Firebase/Firestore'
  pod 'Firebase/Functions'
  pod 'Firebase/Crashlytics'

  # Facebook
  pod 'FBSDKCoreKit/Swift'
  pod 'FBSDKLoginKit/Swift'
  pod 'FBSDKShareKit/Swift'
  pod 'FBAudienceNetwork'

  # Flurry
  pod 'Flurry-iOS-SDK/FlurrySDK'

  # Reachability
  pod 'ReachabilitySwift'

  # Others
  pod 'SSZipArchive'
  pod 'TTTAttributedLabel'
  pod "YoutubePlayer-in-WKWebView", "~> 0.3.0"

  target 'my-app Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'my-app UITests' do
    inherit! :search_paths
    # Pods for testing
  end

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      end
    end
  end

end
```

### Error

```
NoMethodError - undefined method `recursive_predecessors' for nil:NilClass
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:542:in `spec_is_platform_compatible?'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:227:in `requirement_satisfied_by?'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:25:in `block in requirement_satisfied_by?'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:77:in `with_no_such_dependency_error_handling'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:24:in `requirement_satisfied_by?'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:480:in `block in possibility_satisfies_requirements?'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:480:in `all?'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:480:in `possibility_satisfies_requirements?'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:465:in `block (3 levels) in filter_possibilities_for_primary_unwind'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:464:in `any?'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:464:in `block (2 levels) in filter_possibilities_for_primary_unwind'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:463:in `none?'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:463:in `block in filter_possibilities_for_primary_unwind'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:462:in `reject!'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:462:in `filter_possibilities_for_primary_unwind'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:447:in `filter_possibilities_after_unwind'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:303:in `block in unwind_for_conflict'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:297:in `tap'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:297:in `unwind_for_conflict'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:700:in `attempt_to_filter_existing_spec'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:672:in `attempt_to_activate'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:254:in `process_topmost_state'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:182:in `resolve'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in `resolve'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:94:in `resolve'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:1078:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:1076:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:416:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:241:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:240:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:161:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

**Comment by ravi-culturealley** [comment]
> If possible, can you explain me what does install every time means. I tried all the possible ways like updating cocoapods, deintegrating pods, manually removing pods and added again and many more. But still I'm not able to run the app.

Did you find any solution, @upendrasiripurapu ?
