### ISSUE TITLE
`pod install --deployment` fails but `Podfile` is not changed

### ISSUE THREAD

**Issue by appleios** [CocoaPods/CocoaPods#8863]
🌈

* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod install --deployment`

## What did you expect to happen?

It should succeed because Podfile and Podfile.lock are not changed (`git diff` does not find any difference)

## What happened instead?

It fails with error:
```
[!] There were changes to the lockfile in deployment mode:
PODS:
  New Lockfile:
    - MAMNews (0.1.0):
      - BrainPixel
      - MAMAdition
      - MAMAGOF
      - MAMAlerts
      - MAMCommon
      - MAMError
      - MAMPush
      - MobSI
      - PACSOperations
  Old Lockfile:
    - MAMNews (0.1.0):
      - BrainPixel
      - MAMAdition
      - MAMAGOF
      - MAMAlerts
      - MAMCommon
      - MAMError
      - MAMPush
      - MobSI
      - PACSOperations

/Users/vm06lau/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:347:in `verify_no_lockfile_changes!'
/Users/vm06lau/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:181:in `block in resolve_dependencies'
/Users/vm06lau/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/vm06lau/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:179:in `resolve_dependencies'
/Users/vm06lau/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:136:in `install!'
/Users/vm06lau/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/command/install.rb:48:in `run'
/Users/vm06lau/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/vm06lau/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/command.rb:52:in `run'
/Users/vm06lau/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/cocoapods-1.6.1/bin/pod:55:in `<top (required)>'
/Users/vm06lau/.rbenv/versions/2.3.7/bin/pod:22:in `load'
/Users/vm06lau/.rbenv/versions/2.3.7/bin/pod:22:in `<top (required)>'
/Users/vm06lau/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/bundler-2.0.1/lib/bundler/cli/exec.rb:74:in `load'
/Users/vm06lau/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/bundler-2.0.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
/Users/vm06lau/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/bundler-2.0.1/lib/bundler/cli/exec.rb:28:in `run'
/Users/vm06lau/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/bundler-2.0.1/lib/bundler/cli.rb:463:in `exec'
/Users/vm06lau/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/vm06lau/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/vm06lau/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/Users/vm06lau/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/bundler-2.0.1/lib/bundler/cli.rb:27:in `dispatch'
/Users/vm06lau/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/Users/vm06lau/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/bundler-2.0.1/lib/bundler/cli.rb:18:in `start'
/Users/vm06lau/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/bundler-2.0.1/exe/bundle:30:in `block in <top (required)>'
/Users/vm06lau/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/bundler-2.0.1/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/Users/vm06lau/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/bundler-2.0.1/exe/bundle:22:in `<top (required)>'
/Users/vm06lau/.rbenv/versions/2.3.7/bin/bundle:22:in `load'
/Users/vm06lau/.rbenv/versions/2.3.7/bin/bundle:22:in `<main>'
```

## CocoaPods Environment

Sorry its a private information, I can not share it.

## Project that demonstrates the issue

In `cocoapods-1.6.1/lib/cocoapods/installer.rb:347:in `verify_no_lockfile_changes!'` there is a check
```
    def verify_no_lockfile_changes!
      new_lockfile = generate_lockfile
      return if new_lockfile == lockfile
```

And in `/Core-1e0479d5577f/lib/cocoapods-core/lockfile.rb` there is 
```
    def ==(other)
      other && to_hash == other.to_hash
    end
```

After some debugging I found out that there is actually a difference:
```
PODS:
  New Lockfile:
    "MAMNews (0.1.0)" => [
    "BrainPixel", 
    "MAMAGOF", 
    "MAMAdition", 
    "MAMAlerts", 
    "MAMCommon", 
    "MAMError", 
    "MAMPush", 
    "MobSI", 
    "PACSOperations"
  ]
  Old Lockfile:
  "MAMNews (0.1.0)" => [
    "BrainPixel", 
    "MAMAdition", 
    "MAMAGOF", 
    "MAMAlerts", 
    "MAMCommon", 
    "MAMError", 
    "MAMPush", 
    "MobSI", 
    "PACSOperations"
  ]
```
There is a difference in order. But it should not affect equality.

**Comment by appleios** [comment]
I can create a PR, but which algorithm should be used? sort arrays before comparison (in implementation of equality in Lockfile)?

**Comment by dnkoutso** [comment]
Probably fixed in 1.7.0 did you try it?

**Comment by appleios** [comment]
You are right, its works fine. Sorry for false alert=(

**Comment by dnkoutso** [comment]
No problem!

**Comment by appleios** [comment]
Fixed here https://github.com/CocoaPods/Core/pull/480
