### ISSUE TITLE
Xcode 11 Beta Crash

### ISSUE THREAD

**Issue by ex3ndr** [CocoaPods/CocoaPods#8871]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Install new Xcode 11 Beta, enable mac build for iPad app

## What did you expect to happen?

ℹ pod install to work

## What happened instead?

ℹ pod install crashed with

### Stack

```
   CocoaPods : 1.7.1
        Ruby : ruby 2.6.0p0 (2018-12-25 revision 66547) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15 (19A471t)
       Xcode : 10.2.1 (10E1001)
         Git : git version 2.18.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 23015b259e31cd0853ff5f414f58cd7448525a29
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
use_frameworks!
platform :ios, '9.0'

target 'openland' do

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTImage',
    'RCTNetwork',
    'RCTAnimation',
    'RCTBlob',
    'RCTGeolocation',
    'RCTLinkingIOS',
    'RCTSettings',
    'RCTVibration',
    'RCTPushNotification',
    'RCTActionSheet',
    'RCTCameraRoll'
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'Texture', '2.7'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Auth0', '~> 1.14.2'
  pod 'Starscream', '~> 3.0.2'
  pod 'ReachabilitySwift'

  pod 'AppCenter', '~> 1.13.0'
  pod 'AppCenter/Crashes', '~> 1.13.0'
  pod 'AppCenter/Analytics', '~> 1.13.0'
  pod 'AppCenterReactNativeShared', '~> 1.12.0'

  pod 'react-native-webrtc', :path => '../node_modules/react-native-webrtc'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

  pod 'A0Auth0', :path => '../node_modules/react-native-auth0'

  pod 'react-native-blur', :path => '../node_modules/react-native-blur'

  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'


  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'


  pod 'RNShare', :path => '../node_modules/react-native-share'


  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RCTRestart', :path => '../node_modules/react-native-restart/ios'

  pod 'RNRate', :path => '../node_modules/react-native-rate/ios'
  pod 'react-native-document-picker', :path => '../node_modules/react-native-document-picker'

  pod 'ReactNativeIncallManager', :path => '../node_modules/react-native-incall-manager'

  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

  pod 'react-native-haptic-feedback', :path => '../node_modules/react-native-haptic-feedback'

  pod 'react-native-sqlite-storage', :path => '../node_modules/react-native-sqlite-storage'

  pod 'react-native-background-timer', :path => '../node_modules/react-native-background-timer'

  pod 'react-native-pdf', :path => '../node_modules/react-native-pdf'

end

target 'openlandTests' do
    pod 'SwiftyJSON', '~> 4.0'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
            config.build_settings['SWIFT_VERSION'] = '4.2'
        end
    end
end
```

### Error

```
RuntimeError - [Xcodeproj] Unknown object version.
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.9.0/lib/xcodeproj/project.rb:227:in `initialize_from_file'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.9.0/lib/xcodeproj/project.rb:112:in `open'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.1/lib/cocoapods/installer/analyzer.rb:1051:in `block (2 levels) in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.1/lib/cocoapods/installer/analyzer.rb:1050:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.1/lib/cocoapods/installer/analyzer.rb:1050:in `block in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.1/lib/cocoapods/installer/analyzer.rb:1045:in `inspect_targets_to_integrate'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.1/lib/cocoapods/installer/analyzer.rb:100:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.1/lib/cocoapods/installer.rb:398:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.1/lib/cocoapods/installer.rb:221:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.1/lib/cocoapods/installer.rb:220:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.1/lib/cocoapods/installer.rb:156:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.1/lib/cocoapods/command/install.rb:51:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by ex3ndr** [comment]
Update: Issue appears if framework in the project settings was configured as "ios only"

**Comment by dnkoutso** [comment]
Xcodeproj needs an update to know about the new version of Xcode.

**Comment by dnkoutso** [comment]
PR out.

**Comment by chrisvanbuskirk** [comment]
Is there any workarounds for this?  Kinda of dead in the water.

**Comment by dnkoutso** [comment]
You can use xcodeproj from the PR open directly.

**Comment by dnkoutso** [comment]
Use bundler and specify the branch name on the xcodeproj gem.

**Comment by jlubeck** [comment]
I can confirm that using that PR for xcodeproj solves the issue and allows `pod install` to work again

**Comment by chrisvanbuskirk** [comment]
* xcodeproj (1.9.0 2d38d26)
	Summary: Create and modify Xcode projects from Ruby.
	Homepage: https://github.com/cocoapods/xcodeproj
	Path: /Users/cvbuskirk/.bundle/ruby/2.6.0/Xcodeproj-2d38d26f7ef1

Certainly believe I have the PR.  Yet I continue to have the same error.

> RuntimeError - [Xcodeproj] Unknown object version.

**Comment by chrisvanbuskirk** [comment]
Well, I tried bundler and it failed and I even downloaded the branch (2d38d26f7ef1) and built and install and that failed.  Pretty sure I got the right branch.

**Comment by chrisvanbuskirk** [comment]
I had the wrong branch.  Sorry for the hassle.  Works!

**Comment by jonas-sleepcycle** [comment]
Having the same issue. Can you refer me to how to "use bunder"/xcodeproj to fix the issue? Not used these before.

**Comment by dnkoutso** [comment]
Follow instructions from https://bundler.io/

**Comment by dnkoutso** [comment]
Shipped. `gem update xcodeproj` to get latest version for initial (and maybe final) support for Xcode 11.

**Comment by minuscorp** [comment]
Still crashing after updating to XCode Beta 3

**Comment by cbess** [comment]
The best workaround I found, is to change the `Project Format` back to *Xcode 10.0-compatible*. By default, Xcode upgrades the project format.
