### ISSUE TITLE
1.7.1: Pod::Specification::Consumer is not compatible with tvOS

### ISSUE THREAD

**Issue by rnaharro** [CocoaPods/CocoaPods#8880]
### Command

```
/usr/local/lib/ruby/gems/2.6.0/bin/pod install
```

### Report

* What did you do?
pod install
* What did you expect to happen?
pods installed
* What happened instead?
Error with a pod valid for iOS and tvOS. For iOS is AdobeMobileSDK and for tvOS you must select a subspec AdobeMobileSDK/TVOS.

We change the line 39 in consumer.rb to show the name of the pod that causing the error.

If we comment raise StandardError (or change to print), pods are installed successfully and the project compiles and run into devices correctly.

### Stack

```
   CocoaPods : 1.7.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]
    RubyGems : 3.0.3
        Host : Mac OS X 10.14.5 (18F132)
       Xcode : 10.2.1 (10E1001)
         Git : git version 2.21.0
Ruby lib dir : /usr/local/Cellar/ruby/2.6.3/lib
Repositories : antena3tv-ios-specs - http://intergitlab.antena3tv.es/ios/Specs.git @ c0ac5b1512cf63eff33e9353169f5a8cb0642bb0
               bitbucket-npaw-cocoapods-private-trunk - https://bitbucket.org/npaw/cocoapods-private-trunk.git @ cdc377fd5038eaba0ddcfbe12ad3ec4eb49027a1
               master - https://github.com/CocoaPods/Specs.git @ b2b4a0f8aca87444733d814387fb130d643e7394
               popcorntimetv - https://github.com/PopcornTimeTV/Specs @ d8e0d01c6912e797e9561f58f3534cec82db8b20
```

### Plugins

```
cocoapods-check       : 1.1.0
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
source 'http://intergitlab.antena3tv.es/ios/Specs.git'

use_frameworks!

install! 'cocoapods', :deterministic_uuids => false,
         :generate_multiple_pod_projects => true,
         :incremental_installation => true

def common_pods
    pod 'Alamofire', '~> 4.8.0'
    pod 'ObjectMapper', '~> 3.4'
    pod 'AlamofireObjectMapper', '~> 5.0'

    pod 'SnapKit', '~> 4.2'
    pod 'Kingfisher', '= 4.10.1' #Latest version compatible iOS 9

    pod 'CHIPageControl', '~> 0.1'

    pod 'RealmSwift', '~> 3.1'
    pod 'Realm', '~> 3.7.5'

    pod 'DeviceGuru', '~> 5.0'

    pod 'ComScore/Dynamic', '= 5.8.5'

    # --- Fabric ------
    pod 'Fabric', '~> 1.9'
    pod 'Crashlytics', '~> 3.12'

    # --- Atresmedia ------
    pod 'swissknife-swift', '~> 0.3.0', :inhibit_warnings => false
end

def media_pods
  # --- Atresmedia ------
  pod 'A3MediaPlayer'
end

def ios_pods
    pod 'SideMenu', :git => 'http://intergitlab.antena3tv.es/ios/SideMenu.git'
    pod 'PinCodeTextField', :git => 'http://intergitlab.antena3tv.es/ios/PinCodeTextField.git'
    pod 'IBActionSheet', :git => 'http://intergitlab.antena3tv.es/ios/IBActionSheet.git', :commit => 'dfb8c7e8272d72bce71aaf4f34cad6aa8292b31d'
    pod 'MTDActionSheet', '~> 1.1'
    pod 'MXSegmentedPager', :git => 'http://intergitlab.antena3tv.es/ios/MXSegmentedPager.git'
    pod 'SwipeCellKit', '~> 2.6.0'
    # --- Omniture ------
    pod 'AdobeMobileSDK', '~> 4.18.0'
    # --- SmartAdServer ------
    pod 'SmartAdServer-DisplaySDK'
    # --- Social login ------
    pod 'FBSDKCoreKit', '4.37.0'
    pod 'FBSDKLoginKit', '4.37.0'

    # -- Google login ------
    pod 'GoogleSignIn'
    # -- Chromecast ------
    pod 'ChromecastHelper', '~> 0.3.0'
    # -- Notifications iOS 9 ------
    pod 'CRToast'

    pod 'YouboraFreewheelAdapterLib'
end

def tvos_pods
    # --- Omniture ------
    pod 'AdobeMobileSDK/TVOS'

    # -- Automatically show more button on large texts --
    pod 'TvOSMoreButton', '~> 1.2.3'
    # -- Scrollable large text modal --------------------
    pod 'TvOSTextViewer', '~> 1.2.0'
end

def test_pods
    pod 'Quick', '~> 1.1'
    pod 'Nimble', '~> 7.0'
end

target 'AtresPlayer' do
    platform :ios, '10.0'
    inhibit_all_warnings!
    common_pods
    ios_pods
    media_pods

    # --- TESTING TARGETS ------
    target 'AtresPlayerTests' do
        test_pods
    end

    target 'AtresPlayerUITests' do
        use_frameworks!
        test_pods
    end

end

target 'AtresPlayerTV' do
    platform :tvos, '11.0'
    inhibit_all_warnings!
    common_pods
    tvos_pods
    media_pods

    # --- TESTING TARGETS ------
    target 'AtresPlayerTVTests' do
        test_pods

    end
    target 'AtresPlayerTVUITests' do
      test_pods
    end
end

target 'AtresPlayerTVTopShelf' do
  platform :tvos, '11.0'
  inhibit_all_warnings!

  common_pods
  tvos_pods
end

# --- PRE INSTALL ACTIONS ------
pre_install do |installer|
    # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end

# --- POST INSTALL ACTIONS ------
post_install do |installer|
    installer.aggregate_targets.each do |aggregate_target|
        puts aggregate_target.name
        aggregate_target.xcconfigs.each do |config_name, config_file|
            config_file.attributes['OTHER_LDFLAGS']  = '-weak_framework "AVFoundation"'

            xcconfig_path = aggregate_target.xcconfig_path(config_name)
            config_file.save_as(xcconfig_path)
        end
    end

    project = installer.pods_project
    puts "\e[41m\e[37m\e[1mAdditional configuration from Podfile\e[22m\e[0m"
    puts "\e[35mSet Prevent frameworks which they are already linked with a module from being linked with the main target again\e[0m"
    # prevent frameworks which they are already linked with a module from being linked with the main target again
    installer.aggregate_targets.each do |target|
        project.build_configurations.each do |build_configuration|
            configFilePath = target.xcconfig_path(build_configuration.name)
            configFile = File.read(configFilePath)
            configFile = configFile.gsub(/-framework "Firebase" /, '')
            configFile = configFile.gsub(/-framework "FirebaseCore" /, '')
            configFile = configFile.gsub(/-framework "FirebaseCoreDiagnostics" /, '')
            configFile = configFile.gsub(/-framework "FirebaseNanoPB" /, '')
            configFile = configFile.gsub(/-framework "FirebaseRemoteConfig" /, '')
            configFile = configFile.gsub(/-framework "FirebaseInstanceID" /, '')
            configFile = configFile.gsub(/-framework "FirebaseAnalytics" /, '')
            configFile = configFile.gsub(/-framework "FirebaseABTesting" /, '')
            configFile = configFile.gsub(/-framework "ComScore" /, '')
            configFile = configFile.gsub(/-framework "Crashlytics" /, '')
            configFile = configFile.gsub(/-framework "Fabric" /, '')
            File.open(configFilePath, 'w') { |file| file << configFile }
        end
    end
end
```

### Error

```
Pod::StandardError - AdobeMobileSDK is not compatible with tvos.
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.7.1/lib/cocoapods-core/specification/consumer.rb:39:in `initialize'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.7.1/lib/cocoapods-core/specification.rb:407:in `new'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.7.1/lib/cocoapods-core/specification.rb:407:in `consumer'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.1/lib/cocoapods/target/pod_target.rb:486:in `scheme_for_spec'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:225:in `block in configure_schemes_for_pod_target'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:223:in `each'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:223:in `configure_schemes_for_pod_target'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:88:in `block in configure_schemes'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:86:in `each'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:86:in `configure_schemes'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.1/lib/cocoapods/installer.rb:321:in `block (2 levels) in create_and_save_projects'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.1/lib/cocoapods/installer.rb:320:in `each'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.1/lib/cocoapods/installer.rb:320:in `block in create_and_save_projects'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.1/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.1/lib/cocoapods/installer.rb:290:in `create_and_save_projects'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.1/lib/cocoapods/installer.rb:281:in `generate_pods_project'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.1/lib/cocoapods/installer.rb:159:in `install!'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.1/lib/cocoapods/command/install.rb:51:in `run'
/usr/local/lib/ruby/gems/2.6.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.1/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.1/bin/pod:55:in `<top (required)>'
/usr/local/lib/ruby/gems/2.6.0/bin/pod:23:in `load'
/usr/local/lib/ruby/gems/2.6.0/bin/pod:23:in `<main>'
```

**Comment by dnkoutso** [comment]
Do you have a sample app or podspec? most certainly a bug.

**Comment by dnkoutso** [comment]
Actually you did mention AdobeMobileSDK so I will try to debug it with that.

**Comment by rnaharro** [comment]
Still not working in version 1.7.3

Attach a simple example
[cocoapods17.zip](https://github.com/CocoaPods/CocoaPods/files/3353780/cocoapods17.zip)
