### ISSUE TITLE
NoMethodError - undefined method `real_path' for nil:NilClass

### ISSUE THREAD

**Issue by ldco2016** [CocoaPods/CocoaPods#8884]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I ran `react-native link` in terminal

## What did you expect to happen?

Anything that would lead to fixing the continued build errors I am getting in Xcode, in particular this error:

```
fatal error: 'AppCenterReactNativeCrashes/AppCenterReactNativeCrashes.h' file not found
#import <AppCenterReactNativeCrashes/AppCenterReactNativeCrashes.h>
```

## What happened instead?

I get the following error after running `react-native link`

```
NoMethodError - undefined method `real_path' for nil:NilClass
/Users/danale/.rvm/gems/ruby-2.4.0/gems/xcodeproj-1.9.0/lib/xcodeproj/project/object/container_item_proxy.rb:96:in `container_portal_annotation'
/Users/danale/.rvm/gems/ruby-2.4.0/gems/xcodeproj-1.9.0/lib/xcodeproj/project/object/container_item_proxy.rb:105:in `to_hash_as'
/Users/danale/.rvm/gems/ruby-2.4.0/gems/xcodeproj-1.9.0/lib/xcodeproj/project/object.rb:421:in `to_ascii_plist'
/Users/danale/.rvm/gems/ruby-2.4.0/gems/xcodeproj-1.9.0/lib/xcodeproj/project.rb:297:in `block in to_ascii_plist'
/Users/danale/.rvm/gems/ruby-2.4.0/gems/xcodeproj-1.9.0/lib/xcodeproj/project.rb:295:in `each'
/Users/danale/.rvm/gems/ruby-2.4.0/gems/xcodeproj-1.9.0/lib/xcodeproj/project.rb:295:in `to_ascii_plist'
/Users/danale/.rvm/gems/ruby-2.4.0/gems/xcodeproj-1.9.0/lib/xcodeproj/project.rb:364:in `block in save'
/Users/danale/.rvm/gems/ruby-2.4.0/gems/atomos-0.1.3/lib/atomos.rb:21:in `block in atomic_write'
/Users/danale/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/tempfile.rb:295:in `open'
/Users/danale/.rvm/gems/ruby-2.4.0/gems/atomos-0.1.3/lib/atomos.rb:17:in `atomic_write'
/Users/danale/.rvm/gems/ruby-2.4.0/gems/xcodeproj-1.9.0/lib/xcodeproj/project.rb:363:in `save'
/Users/danale/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.7.1/lib/cocoapods/installer/user_project_integrator.rb:158:in `block in save_projects'
/Users/danale/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.7.1/lib/cocoapods/installer/user_project_integrator.rb:156:in `each'
/Users/danale/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.7.1/lib/cocoapods/installer/user_project_integrator.rb:156:in `save_projects'
/Users/danale/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.7.1/lib/cocoapods/installer/user_project_integrator.rb:76:in `integrate!'
/Users/danale/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.7.1/lib/cocoapods/installer.rb:780:in `block in integrate_user_project'
/Users/danale/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.7.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/danale/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.7.1/lib/cocoapods/installer.rb:776:in `integrate_user_project'
/Users/danale/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.7.1/lib/cocoapods/installer.rb:161:in `install!'
/Users/danale/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.7.1/lib/cocoapods/command/install.rb:51:in `run'
/Users/danale/.rvm/gems/ruby-2.4.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/danale/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.7.1/lib/cocoapods/command.rb:52:in `run'
/Users/danale/.rvm/gems/ruby-2.4.0/gems/cocoapods-1.7.1/bin/pod:55:in `<top (required)>'
/Users/danale/.rvm/gems/ruby-2.4.0/bin/pod:23:in `load'
/Users/danale/.rvm/gems/ruby-2.4.0/bin/pod:23:in `<main>'
/Users/danale/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
/Users/danale/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'
```

### Stack

```
   CocoaPods : 1.7.1
        Ruby : ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
    RubyGems : 2.6.12
        Host : Mac OS X 10.13.6 (17G7024)
       Xcode : 10.1 (10B61)
         Git : git version 2.17.2 (Apple Git-113)
Ruby lib dir : /Users/danale/.rvm/rubies/ruby-2.4.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 391e2605089efd80354d0a28c7ab79fc25a15bee
```

### Installation Source

```
Executable Path: /Users/danale/.rvm/gems/ruby-2.4.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

For NDA reasons I cannot share the project itself.

**Comment by dnkoutso** [comment]
We cannot debug this without a sample app. Sorry please upload one.

**Comment by ldco2016** [comment]
@dnkoutso , you can debug with this sample app
https://www.dropbox.com/s/4cu8k2b0imym159/sampleRN.zip?dl=0

**Comment by dnkoutso** [comment]
You have a bad reference in your project in `libRNSpinkit.a`. Please remove it and installation will be successful. I did it on my machine and it worked.

Closing as we have another issue as enhancement for these msgs.
