### ISSUE TITLE
"Xcodeproj doesn't know about the following attributes" with Xcodeproj, Xcode 11, and pod install/update

### ISSUE THREAD

**Issue by Umar-M-Haroon** [CocoaPods/CocoaPods#8887]
* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Ran Pod install

## What did you expect to happen?

 Install all pod dependencies correctly.

## What happened instead?

ℹ Please replace these two lines with of what happened instead.  
e.g. Pod A is missing the subspec B for target C.

### Stack

```
   CocoaPods : 1.7.1
        Ruby : ruby 2.6.0p0 (2018-12-25 revision 66547) [universal.x86_64-darwin19]
    RubyGems : 3.0.1
        Host : Mac OS X 10.15 (19A471t)
       Xcode : 11.0 (11M336w)
         Git : git version 2.21.0 (Apple Git-120)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ f2e02b0b78d4a3db299d85239ae313a2981e17ca
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
#plugin 'cocoapods-binary'
#enable_bitcode_for_prebuilt_frameworks!

target 'Homely' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
 # all_binary!
  pod 'SwiftLint'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'Firebase/DynamicLinks'
 # pod 'Fabric'
  pod 'lottie-ios'
#  pod 'Crashlytics'
#  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Firestore'
  pod 'SwiftEntryKit', '1.0.1'
  pod 'SDWebImage', '~> 5.0'
  pod 'Charts'
  # Pods for Homely

  target 'HomelyTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Shortcuts' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Shortcuts

end

target 'ShortcutsUI' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ShortcutsUI

end

#target 'WatchApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
 # use_frameworks!

  # Pods for WatchApp

#end

#target 'WatchApp Extension' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
 # use_frameworks!

  # Pods for WatchApp Extension

#end

target 'Widget' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Widget

end
```

## Error output
```
[!] [!] Xcodeproj doesn't know about the following attributes {"platformFilter"=>"ios"} for the 'PBXBuildFile' isa.
If this attribute was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new

[!] [!] Xcodeproj doesn't know about the following attributes {"platformFilter"=>"ios"} for the 'PBXBuildFile' isa.
If this attribute was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new

[!] [!] Xcodeproj doesn't know about the following attributes {"platformFilter"=>"ios"} for the 'PBXBuildFile' isa.
If this attribute was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new

[!] [!] Xcodeproj doesn't know about the following attributes {"platformFilter"=>"ios"} for the 'PBXTargetDependency' isa.
If this attribute was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new

[!] [!] Xcodeproj doesn't know about the following attributes {"platformFilter"=>"ios"} for the 'PBXTargetDependency' isa.
If this attribute was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new

[!] [!] Xcodeproj doesn't know about the following attributes {"platformFilter"=>"ios"} for the 'PBXTargetDependency' isa.
If this attribute was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new
```

### Error

```
RuntimeError - [Xcodeproj] Unknown object version.
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.9.0/lib/xcodeproj/project.rb:227:in `initialize_from_file'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.9.0/lib/xcodeproj/project.rb:112:in `open'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.1/lib/cocoapods/installer/analyzer.rb:1051:in `block (2 levels) in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.1/lib/cocoapods/installer/analyzer.rb:1050:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.1/lib/cocoapods/installer/analyzer.rb:1050:in `block in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.1/lib/cocoapods/installer/analyzer.rb:1045:in `inspect_targets_to_integrate'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.1/lib/cocoapods/installer/analyzer.rb:100:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.1/lib/cocoapods/installer.rb:398:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.1/lib/cocoapods/installer.rb:221:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.1/lib/cocoapods/installer.rb:220:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.1/lib/cocoapods/installer.rb:156:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.1/lib/cocoapods/command/update.rb:62:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

#### Error with Xcodeproj branch
I then added Xcodeproj and cocoa pods into my gem file and hoped the Xcodeproj Xcode 11 branch would help, but it resulted in this error 

### Error

```
NameError - uninitialized constant Xcodeproj::Project::Object::XCSwiftPackageProductDependency::XCRemoteSwiftPackageReference
/Library/Ruby/Gems/2.6.0/bundler/gems/Xcodeproj-01adc295108b/lib/xcodeproj/project/object/swift_package_product_dependency.rb:11:in `<class:XCSwiftPackageProductDependency>'
/Library/Ruby/Gems/2.6.0/bundler/gems/Xcodeproj-01adc295108b/lib/xcodeproj/project/object/swift_package_product_dependency.rb:6:in `<module:Object>'
/Library/Ruby/Gems/2.6.0/bundler/gems/Xcodeproj-01adc295108b/lib/xcodeproj/project/object/swift_package_product_dependency.rb:3:in `<class:Project>'
/Library/Ruby/Gems/2.6.0/bundler/gems/Xcodeproj-01adc295108b/lib/xcodeproj/project/object/swift_package_product_dependency.rb:2:in `<module:Xcodeproj>'
/Library/Ruby/Gems/2.6.0/bundler/gems/Xcodeproj-01adc295108b/lib/xcodeproj/project/object/swift_package_product_dependency.rb:1:in `<top (required)>'
/Library/Ruby/Gems/2.6.0/bundler/gems/Xcodeproj-01adc295108b/lib/xcodeproj/project/object.rb:521:in `require'
/Library/Ruby/Gems/2.6.0/bundler/gems/Xcodeproj-01adc295108b/lib/xcodeproj/project/object.rb:521:in `<top (required)>'
/Library/Ruby/Gems/2.6.0/bundler/gems/Xcodeproj-01adc295108b/lib/xcodeproj/project.rb:5:in `require'
/Library/Ruby/Gems/2.6.0/bundler/gems/Xcodeproj-01adc295108b/lib/xcodeproj/project.rb:5:in `<top (required)>'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.1/lib/cocoapods/installer/analyzer.rb:1051:in `require'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.1/lib/cocoapods/installer/analyzer.rb:1051:in `block (2 levels) in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.1/lib/cocoapods/installer/analyzer.rb:1050:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.1/lib/cocoapods/installer/analyzer.rb:1050:in `block in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.1/lib/cocoapods/installer/analyzer.rb:1045:in `inspect_targets_to_integrate'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.1/lib/cocoapods/installer/analyzer.rb:100:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.1/lib/cocoapods/installer.rb:398:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.1/lib/cocoapods/installer.rb:221:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.1/lib/cocoapods/installer.rb:220:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.1/lib/cocoapods/installer.rb:156:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.1/lib/cocoapods/command/install.rb:51:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<top (required)>'
/Users/umar/.gem/ruby/2.6.0/gems/bundler-2.0.1/lib/bundler/cli/exec.rb:74:in `load'
/Users/umar/.gem/ruby/2.6.0/gems/bundler-2.0.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
/Users/umar/.gem/ruby/2.6.0/gems/bundler-2.0.1/lib/bundler/cli/exec.rb:28:in `run'
/Users/umar/.gem/ruby/2.6.0/gems/bundler-2.0.1/lib/bundler/cli.rb:463:in `exec'
/Users/umar/.gem/ruby/2.6.0/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/umar/.gem/ruby/2.6.0/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/umar/.gem/ruby/2.6.0/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/Users/umar/.gem/ruby/2.6.0/gems/bundler-2.0.1/lib/bundler/cli.rb:27:in `dispatch'
/Users/umar/.gem/ruby/2.6.0/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/Users/umar/.gem/ruby/2.6.0/gems/bundler-2.0.1/lib/bundler/cli.rb:18:in `start'
/Users/umar/.gem/ruby/2.6.0/gems/bundler-2.0.1/exe/bundle:30:in `block in <top (required)>'
/Users/umar/.gem/ruby/2.6.0/gems/bundler-2.0.1/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/Users/umar/.gem/ruby/2.6.0/gems/bundler-2.0.1/exe/bundle:22:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
```

**Comment by dnkoutso** [comment]
PR open already https://github.com/CocoaPods/Xcodeproj/pull/687 and duplicate issue. Closing.

**Comment by Umar-M-Haroon** [comment]
This issue is still occurring even with that branch of xcodeproj. See second error stack

**Comment by dnkoutso** [comment]
Try again I pushed a fix to that too.

**Comment by Umar-M-Haroon** [comment]
Just ran bundle install and then bundle exec pod update, but no avail, same issue.

**Comment by dnkoutso** [comment]
sorry I cant help you here. The branch is open and it works for me for the same stacktrace. If you want upload a sample app here and I will verify.

**Comment by Umar-M-Haroon** [comment]
I wonder if its a gem file issue then, I must be pulling from an incorrect branch. 

Here's my gemfile

```
source "https://rubygems.org"

gem "fastlane"
gem "xcodeproj", :git => "git://github.com/dnkoutso/Xcodeproj.git", :branch => "xcode11_support"
gem "cocoapods"
```

**Comment by Umar-M-Haroon** [comment]
Should this issue still be open due to it still occurring?

**Comment by top-master** [comment]
What is this? log:
```
[!] [!] Xcodeproj doesn't know about the following attributes {"platformFilter"=>"maccatalyst"} for the 'PBXTargetDependency' isa.
If this attribute was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new
```

Add `maccatalyst` to your valid attribute list.
