### ISSUE TITLE
pod install Jenkins

### ISSUE THREAD

**Issue by mehmetfarhan** [CocoaPods/CocoaPods#8899]
――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.7.1
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 3.0.3
        Host : Mac OS X 10.14.5 (18F132)
       Xcode : 10.2.1 (10E1001)
         Git : git version 2.20.1 (Apple Git-117)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 5f95079180e197bf0ed61d723468508bd9d71e7d
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
inhibit_all_warnings!

def shared_pods
#  pod 'CoreNetwork', :git => 'git@bitbucket.org:mobilenoc/core-networking.git', :tag => 'v1.0.1'
end

target 'MobileNOC' do
  platform :ios, '11.0'
  use_frameworks!
  shared_pods
  pod 'ObjectMapper'
  pod 'Charts'
  pod 'IQKeyboardManagerSwift'
  pod 'DropDown'
#  pod 'NMSSH' , :git => "https://github.com/NMSSH/NMSSH"
  pod 'SVProgressHUD'
  pod 'Firebase/Database'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'
  pod 'SwiftLint'
  pod 'UICircularProgressRing'
  pod 'InputMask'
  pod 'ScalingCarousel'
  pod 'SwipeCellKit'
  pod 'MGSwipeTableCell'
  pod 'NYAlertViewController'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Optimizely-iOS-SDK'
  pod 'AlamofireImage'
  pod 'Parchment'
  pod 'Floaty'
  pod 'ChameleonFramework'
  pod 'SimpleTwoWayBinding'
  
  target 'MobileNOCTests' do
    inherit! :search_paths
  end
  
end

target 'MobileNOC-Watch Extension' do
  platform :watchos, '4.0'
  use_frameworks!
  shared_pods
end

target 'NetworkPlatform-iOS' do
  platform :ios, '11.0'
  use_frameworks!
  shared_pods
end

target 'NetworkPlatform-Watch' do
  platform :watchos, '4.0'

  use_frameworks!
  shared_pods
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings.delete('CODE_SIGNING_ALLOWED')
    config.build_settings.delete('CODE_SIGNING_REQUIRED')
  end
end
```

### Error

```
Errno::EACCES - Permission denied @ dir_s_mkdir - /Users/Shared/Jenkins/Library/Caches/CocoaPods
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:254:in `mkdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:254:in `fu_mkdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:228:in `block (2 levels) in mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:226:in `reverse_each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:226:in `block in mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:211:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/fileutils.rb:211:in `mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/pathname.rb:576:in `mkpath'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.1/lib/cocoapods/config.rb:90:in `cache_root'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.1/lib/cocoapods/downloader.rb:33:in `download'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.1/lib/cocoapods/installer/pod_source_installer.rb:109:in `download_source'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.1/lib/cocoapods/installer/pod_source_installer.rb:62:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.1/lib/cocoapods/installer.rb:545:in `install_source_of_pod'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.1/lib/cocoapods/installer.rb:496:in `block (2 levels) in install_pod_sources'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.1/lib/cocoapods/user_interface.rb:86:in `titled_section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.1/lib/cocoapods/installer.rb:495:in `block in install_pod_sources'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.1/lib/cocoapods/installer.rb:478:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.1/lib/cocoapods/installer.rb:478:in `install_pod_sources'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.1/lib/cocoapods/installer.rb:235:in `block in download_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.1/lib/cocoapods/installer.rb:234:in `download_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.1/lib/cocoapods/installer.rb:157:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.1/lib/cocoapods/command/install.rb:51:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

**Comment by dnkoutso** [comment]
Seems like a permission issue on the machine you are running CocoaPods.

Does not appear an issue with CocoaPods so will close
