### ISSUE TITLE
Nanaimo::Reader::ParseError - [!] Dictionary missing ';' after key-value pair for "objects", found ""

### ISSUE THREAD

**Issue by komicon** [CocoaPods/CocoaPods#8906]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
Hey people...I was merging dev into my local branch 
## What did you do?

Run `pod install`

## What did you expect to happen?

Analyzing dependencies
Downloading dependencies
Using AFNetworking (3.2.1)
Using AMPopTip (1.5.3)
Using AppCenter (1.14.0)
Using CRToast (0.0.9)
Using DACircularProgress (2.3.1)
Using DGActivityIndicatorView (2.1.1)
Using DateTools (1.7.0)
Using DeviceKit (1.13.0)
Using EmptyDataSet-Swift (4.2.0)
Using FirebaseAnalytics (3.9.0)
Using FirebaseCore (3.6.0)
Using FirebaseInstanceID (1.0.10)
Using Google (3.1.0)
Using Google-Mobile-Ads-SDK (7.27.0)
Using GoogleAnalytics (3.17.0)
Using GoogleMaps (2.7.0)
Using GooglePlacePicker (2.7.0)
Using GooglePlaces (2.7.0)
Using GoogleToolboxForMac (2.2.0)
Using IQKeyboardManager (6.2.1)
Using JGProgressHUD (2.0.3)
Using KILabel (1.0.0)
Using MBProgressHUD (0.9.2)
Using MWPhotoBrowser (2.1.2)
Using MagicalRecord (2.3.2)
Using MatomoTracker (6.0.0)
Using OpenGraph (1.1.0)
Using ParallaxHeader (2.0.0)
Using PureLayout (3.1.4)
Using RSKImageCropper (2.2.1)
Using Reachability (3.2)
Using SDWebImage (3.8.2)
Using Sheriff (0.3.2)
Using SocketRocket (0.5.1)
Using SwiftyDrop (4.2.0)
Using UIActivityIndicator-for-SDWebImage (1.2)
Using ZVActivityIndicatorView (0.1.6)
Using ZVProgressHUD (2.1.0)
Using libPhoneNumber-iOS (0.9.13)
Using zhPopupController (0.1.9)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 33 dependencies from the Podfile and 40 total pods installed.

## What happened instead?

Analyzing dependencies

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.6.1
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.4 (18E226)
       Xcode : 10.2.1 (10E1001)
         Git : git version 2.19.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories :my repo
               master - https://github.com/CocoaPods/Specs.git @ 358869fc7f69ed9cd589ef2f8ff309be0f91a90d
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

abstract_target 'Alchemy' do
  
  pod 'AFNetworking', '~> 3.0'
  pod 'SDWebImage', '~>3.7'
  pod 'UIActivityIndicator-for-SDWebImage'
  pod 'MagicalRecord', '~> 2.3'
  pod 'DateTools', '~> 1.7'
  pod 'Sheriff'
  pod 'libPhoneNumber-iOS', '~> 0.8'
  pod 'Google/Analytics'
  pod 'AMPopTip', '~>1.5'
  
  def common_pods
  pod 'PureLayout', '~> 3.0'
  pod 'Reachability', '~> 3.2'
  pod 'SocketRocket', '~>0.5'
  pod 'KILabel', '1.0.0'
  pod 'DGActivityIndicatorView'
  pod 'Google-Mobile-Ads-SDK', '~> 7.27.0'
  pod 'zhPopupController', '~> 0.1.9'
  pod 'CRToast'
  pod 'JGProgressHUD'
  pod 'MWPhotoBrowser'
  pod 'IQKeyboardManager'
  pod 'RSKImageCropper'
  pod 'AppCenter'
  pod 'AppCenter/Distribute'
  pod 'ParallaxHeader', '~> 2.0.0'
  pod 'ZVProgressHUD'
  pod 'EmptyDataSet-Swift'
  pod 'MatomoTracker', '~> 6'
  pod 'SwiftyDrop', '~>4.0'
  pod 'GooglePlaces', '= 2.7.0'
  pod 'GooglePlacePicker'
  pod 'GoogleMaps'
  pod 'DeviceKit', '~> 1.3'
  pod 'OpenGraph', '~> 1.1'
end

pods_with_specific_swift_versions = {
  'SwiftyDrop' => '4.2',
  'MatomoTracker' => '4.2',
  'ZVActivityIndicatorView' => '4.2',
  'ZVProgressHUD' => '4.2'
}

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if pods_with_specific_swift_versions.key? target.name
      swift_version = pods_with_specific_swift_versions[target.name]
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = swift_version
      end
    end
  end
end

target 'iZwi LoMzansi Staging' do
    common_pods
    use_frameworks!
end

target 'iZwi LoMzansi Production' do
  common_pods
  use_frameworks!
end

target 'Alchemy Development' do
  common_pods
  use_frameworks!
end

target 'Alchemy Production' do
  common_pods
  use_frameworks!
end

target 'Alchemy Staging' do
  common_pods
  use_frameworks!
end

target 'YFM Development' do
  common_pods
  use_frameworks!
end

target 'YFM Production' do
  common_pods
  use_frameworks!
end

target 'YFM Staging' do
    common_pods
    use_frameworks!
end

target 'Kaya FM Staging' do
  common_pods
  use_frameworks!
end

target 'Kaya FM Development' do
end

target 'UUST Staging' do
  common_pods
  use_frameworks!
end

target 'UUST Production' do
  common_pods
  use_frameworks!
end

target 'FabrikShareExtension' do #uust share extension
  use_frameworks!
  pod 'MatomoTracker', '~> 6'
end

target 'immediaShareExtension' do #immedia share extension
    use_frameworks!
    pod 'MatomoTracker', '~> 6'
end

target 'Geek Patrol Production' do
  common_pods
  use_frameworks!
end

target 'Geek Patrol Staging' do
  common_pods
  use_frameworks!
end

target 'PE Municipality Staging' do
end

target 'Maputaland' do
  common_pods
  use_frameworks!
end

target 'SRC Staging' do
  common_pods
  use_frameworks!
end

target 'SRC Production' do
  common_pods
  use_frameworks!
end

target 'PARK to PARK Staging' do
  common_pods
  use_frameworks!
end

target 'PARK to PARK Production' do
  common_pods
  use_frameworks!
end

target 'Radyo Sesel' do
  common_pods
  use_frameworks!
end

target 'Radyo Sesel Staging' do
  common_pods
  use_frameworks!
end

target 'Paradise FM' do
  common_pods
  use_frameworks!
end

target 'Paradise FM Staging' do
  common_pods
  use_frameworks!
end


target 'Gagasi FM' do
  common_pods
  use_frameworks!
end

target 'Gagasi FM Staging' do
  common_pods
  use_frameworks!
end

target 'PAL' do
  common_pods
  use_frameworks!
end

target 'Global Peace' do
  common_pods
  use_frameworks!
end

target 'Fabrik Staging' do
    common_pods
    use_frameworks!
end

target 'Fabrik Production' do
  common_pods
  use_frameworks!
end

target 'UUSTShareExtension' do #share extension
  use_frameworks!
  pod 'MatomoTracker', '~> 6'
end

target 'PARKtoPARKShareExtension' do #share extension
    use_frameworks!
    pod 'MatomoTracker', '~> 6'
end

target 'SRCShareExtension' do #share extension
    use_frameworks!
    pod 'MatomoTracker', '~> 6'
end


target 'immedia' do
  common_pods
  use_frameworks!
end

target 'ACGL' do
  common_pods
  use_frameworks!
end

target 'Champion Lab' do
  common_pods
  use_frameworks!
end

target 'Champion Lab Staging' do
  common_pods
  use_frameworks!
end

target 'LM Radio' do
  common_pods
  use_frameworks!
end

target 'Media Show Africa Staging' do
  common_pods
  use_frameworks!
end
target 'Eastern Cape Provincial Treasury' do
  common_pods
  use_frameworks!
end

target 'Eastern Cape Provincial Treasury Staging' do
  common_pods
  use_frameworks!
end
target 'Raptors View' do
  common_pods
  use_frameworks!
end

target 'Raptors View Staging' do
  common_pods
  use_frameworks!
end

target 'Media Show Africa' do
  common_pods
  use_frameworks!
end

target 'Maytime SRA' do
  common_pods
  use_frameworks!
end

target 'Maytime Staging' do
  common_pods
  use_frameworks!
end

target 'MaytimeShareExtension' do #share extension
  use_frameworks!
  pod 'MatomoTracker', '~> 6'
end

target 'IDC' do
  common_pods
  use_frameworks!
end

target 'IDC Staging' do
  common_pods
  use_frameworks!
end

target 'IDCShareExtension' do #share extension
  use_frameworks!
  pod 'MatomoTracker', '~> 6'
end

target 'GeekPatrolShareExtension' do #share extension
  use_frameworks!
  pod 'MatomoTracker', '~> 6'
end

target 'Durban Chamber of Commerce' do
  common_pods
  use_frameworks!
end

target 'Durban Chamber of Commerce Staging' do
  common_pods
  use_frameworks!
end

target 'DCCShareExtension' do #share extension
  use_frameworks!
  pod 'MatomoTracker', '~> 6'
end

target 'ASAIPA' do
  common_pods
  use_frameworks!
end
target 'ASAIPA Staging' do
  common_pods
  use_frameworks!
end

target 'ASAIPAShareExtension' do #share extension
  use_frameworks!
  pod 'MatomoTracker', '~> 6'
end

target 'Rosebank CID' do
  common_pods
  use_frameworks!
end

target 'Rosebank CID Staging' do
  common_pods
  use_frameworks!
end

target 'Ward Council Staging' do
end

end
```

### Error

```
Nanaimo::Reader::ParseError - [!] Dictionary missing ';' after key-value pair for "objects", found ""
     #  -------------------------------------------
     #  	rootObject = A0FCDC751CB0125F0093F839 /* Project object */;
     #  }
44119>  
        ^
     #  -------------------------------------------

/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:284:in `raise_parser_error'
/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:199:in `parse_dictionary'
/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:132:in `parse_object'
/Library/Ruby/Gems/2.3.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:107:in `parse!'
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.10.0/lib/xcodeproj/plist.rb:27:in `read_from_path'
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.10.0/lib/xcodeproj/project.rb:210:in `initialize_from_file'
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.10.0/lib/xcodeproj/project.rb:112:in `open'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:1025:in `block (2 levels) in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:1024:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:1024:in `block in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:1019:in `inspect_targets_to_integrate'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:96:in `analyze'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:266:in `analyze'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:174:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:173:in `resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:136:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/command/install.rb:48:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=%5B%21%5D+Dictionary+missing+%27%3B%27+after+key-value+pair+for+%22objects%22%2C+found+%22%22%0A+++++%23++-------------------------------------------%0A+++++%23++%09rootObject+%3D+A0FCDC751CB0125F0093F839+%2F%2A+Project+object+%2A%2F%3B%0A+++++%23++%7D%0A44119%3E++%0A++++++++%5E%0A+++++%23++-------------------------------------------%0A&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
/Library/Ruby/Gems/2.3.0/gems/gh_inspector-1.1.3/lib/gh_inspector/sidekick.rb:95:in `parse_results': undefined method `map' for nil:NilClass (NoMethodError)
Did you mean?  tap
	from /Library/Ruby/Gems/2.3.0/gems/gh_inspector-1.1.3/lib/gh_inspector/sidekick.rb:34:in `search'
	from /Library/Ruby/Gems/2.3.0/gems/gh_inspector-1.1.3/lib/gh_inspector/inspector.rb:68:in `search_query'
	from /Library/Ruby/Gems/2.3.0/gems/gh_inspector-1.1.3/lib/gh_inspector/inspector.rb:62:in `search_exception'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/user_interface/error_report.rb:119:in `search_for_exceptions'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/command.rb:67:in `report_error'
	from /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:396:in `handle_exception'
	from /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:337:in `rescue in run'
	from /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:324:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/command.rb:52:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/bin/pod:55:in `<top (required)>'
	from /usr/local/bin/pod:22:in `load'
	from /usr/local/bin/pod:22:in `<main>'

### Stack

```
   CocoaPods : 1.6.1
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.4 (18E226)
       Xcode : 10.2.1 (10E1001)
         Git : git version 2.19.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories :my repo
               master - https://github.com/CocoaPods/Specs.git @ 358869fc7f69ed9cd589ef2f8ff309be0f91a90d
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

abstract_target 'Alchemy' do
  
  pod 'AFNetworking', '~> 3.0'
  pod 'SDWebImage', '~>3.7'
  pod 'UIActivityIndicator-for-SDWebImage'
  pod 'MagicalRecord', '~> 2.3'
  pod 'DateTools', '~> 1.7'
  pod 'Sheriff'
  pod 'libPhoneNumber-iOS', '~> 0.8'
  pod 'Google/Analytics'
  pod 'AMPopTip', '~>1.5'
  
  def common_pods
  pod 'PureLayout', '~> 3.0'
  pod 'Reachability', '~> 3.2'
  pod 'SocketRocket', '~>0.5'
  pod 'KILabel', '1.0.0'
  pod 'DGActivityIndicatorView'
  pod 'Google-Mobile-Ads-SDK', '~> 7.27.0'
  pod 'zhPopupController', '~> 0.1.9'
  pod 'CRToast'
  pod 'JGProgressHUD'
  pod 'MWPhotoBrowser'
  pod 'IQKeyboardManager'
  pod 'RSKImageCropper'
  pod 'AppCenter'
  pod 'AppCenter/Distribute'
  pod 'ParallaxHeader', '~> 2.0.0'
  pod 'ZVProgressHUD'
  pod 'EmptyDataSet-Swift'
  pod 'MatomoTracker', '~> 6'
  pod 'SwiftyDrop', '~>4.0'
  pod 'GooglePlaces', '= 2.7.0'
  pod 'GooglePlacePicker'
  pod 'GoogleMaps'
  pod 'DeviceKit', '~> 1.3'
  pod 'OpenGraph', '~> 1.1'
end

pods_with_specific_swift_versions = {
  'SwiftyDrop' => '4.2',
  'MatomoTracker' => '4.2',
  'ZVActivityIndicatorView' => '4.2',
  'ZVProgressHUD' => '4.2'
}

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if pods_with_specific_swift_versions.key? target.name
      swift_version = pods_with_specific_swift_versions[target.name]
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = swift_version
      end
    end
  end
end

target 'iZwi LoMzansi Staging' do
    common_pods
    use_frameworks!
end

target 'iZwi LoMzansi Production' do
  common_pods
  use_frameworks!
end

target 'Alchemy Development' do
  common_pods
  use_frameworks!
end

target 'Alchemy Production' do
  common_pods
  use_frameworks!
end

target 'Alchemy Staging' do
  common_pods
  use_frameworks!
end

target 'YFM Development' do
  common_pods
  use_frameworks!
end

target 'YFM Production' do
  common_pods
  use_frameworks!
end

target 'YFM Staging' do
    common_pods
    use_frameworks!
end

target 'Kaya FM Staging' do
  common_pods
  use_frameworks!
end

target 'Kaya FM Development' do
end

target 'UUST Staging' do
  common_pods
  use_frameworks!
end

target 'UUST Production' do
  common_pods
  use_frameworks!
end

target 'FabrikShareExtension' do #uust share extension
  use_frameworks!
  pod 'MatomoTracker', '~> 6'
end

target 'immediaShareExtension' do #immedia share extension
    use_frameworks!
    pod 'MatomoTracker', '~> 6'
end

target 'Geek Patrol Production' do
  common_pods
  use_frameworks!
end

target 'Geek Patrol Staging' do
  common_pods
  use_frameworks!
end

target 'PE Municipality Staging' do
end

target 'Maputaland' do
  common_pods
  use_frameworks!
end

target 'SRC Staging' do
  common_pods
  use_frameworks!
end

target 'SRC Production' do
  common_pods
  use_frameworks!
end

target 'PARK to PARK Staging' do
  common_pods
  use_frameworks!
end

target 'PARK to PARK Production' do
  common_pods
  use_frameworks!
end

target 'Radyo Sesel' do
  common_pods
  use_frameworks!
end

target 'Radyo Sesel Staging' do
  common_pods
  use_frameworks!
end

target 'Paradise FM' do
  common_pods
  use_frameworks!
end

target 'Paradise FM Staging' do
  common_pods
  use_frameworks!
end


target 'Gagasi FM' do
  common_pods
  use_frameworks!
end

target 'Gagasi FM Staging' do
  common_pods
  use_frameworks!
end

target 'PAL' do
  common_pods
  use_frameworks!
end

target 'Global Peace' do
  common_pods
  use_frameworks!
end

target 'Fabrik Staging' do
    common_pods
    use_frameworks!
end

target 'Fabrik Production' do
  common_pods
  use_frameworks!
end

target 'UUSTShareExtension' do #share extension
  use_frameworks!
  pod 'MatomoTracker', '~> 6'
end

target 'PARKtoPARKShareExtension' do #share extension
    use_frameworks!
    pod 'MatomoTracker', '~> 6'
end

target 'SRCShareExtension' do #share extension
    use_frameworks!
    pod 'MatomoTracker', '~> 6'
end


target 'immedia' do
  common_pods
  use_frameworks!
end

target 'ACGL' do
  common_pods
  use_frameworks!
end

target 'Champion Lab' do
  common_pods
  use_frameworks!
end

target 'Champion Lab Staging' do
  common_pods
  use_frameworks!
end

target 'LM Radio' do
  common_pods
  use_frameworks!
end

target 'Media Show Africa Staging' do
  common_pods
  use_frameworks!
end
target 'Eastern Cape Provincial Treasury' do
  common_pods
  use_frameworks!
end

target 'Eastern Cape Provincial Treasury Staging' do
  common_pods
  use_frameworks!
end
target 'Raptors View' do
  common_pods
  use_frameworks!
end

target 'Raptors View Staging' do
  common_pods
  use_frameworks!
end

target 'Media Show Africa' do
  common_pods
  use_frameworks!
end

target 'Maytime SRA' do
  common_pods
  use_frameworks!
end

target 'Maytime Staging' do
  common_pods
  use_frameworks!
end

target 'MaytimeShareExtension' do #share extension
  use_frameworks!
  pod 'MatomoTracker', '~> 6'
end

target 'IDC' do
  common_pods
  use_frameworks!
end

target 'IDC Staging' do
  common_pods
  use_frameworks!
end

target 'IDCShareExtension' do #share extension
  use_frameworks!
  pod 'MatomoTracker', '~> 6'
end

target 'GeekPatrolShareExtension' do #share extension
  use_frameworks!
  pod 'MatomoTracker', '~> 6'
end

target 'Durban Chamber of Commerce' do
  common_pods
  use_frameworks!
end

target 'Durban Chamber of Commerce Staging' do
  common_pods
  use_frameworks!
end

target 'DCCShareExtension' do #share extension
  use_frameworks!
  pod 'MatomoTracker', '~> 6'
end

target 'ASAIPA' do
  common_pods
  use_frameworks!
end
target 'ASAIPA Staging' do
  common_pods
  use_frameworks!
end

target 'ASAIPAShareExtension' do #share extension
  use_frameworks!
  pod 'MatomoTracker', '~> 6'
end

target 'Rosebank CID' do
  common_pods
  use_frameworks!
end

target 'Rosebank CID Staging' do
  common_pods
  use_frameworks!
end

target 'Ward Council Staging' do
end

end
```

## Project that demonstrates the issue
Here's my project file 
[project.pbxproj.zip](https://github.com/CocoaPods/CocoaPods/files/3290492/project.pbxproj.zip)

**Comment by komicon** [comment]
This is my first time submitting am ticket...let me know if I screwed up

**Comment by dnkoutso** [comment]
You have a malformed `project.pbxproj` line 22015 delete `409E0E6C7411B165D405F110 /* [CP] Embed Pods Frameworks */ = {` and save your project.

Probably a result of a bad merge but right now does not appear to be a CocoaPods issue in serialization.

**Comment by komicon** [comment]
thanks buddy...how did you find this malformed line of code at line 22015...I want to be able to solve this is the future

**Comment by komicon** [comment]
> You have a malformed `project.pbxproj` line 22015 delete `409E0E6C7411B165D405F110 /* [CP] Embed Pods Frameworks */ = {` and save the file.
> 
> Probably a result of a bad merge but right now does not appear to be a CocoaPods issue in serialization.

Thanks buddy...how did you find this malformed line of code at line 22015...I want to be able to solve this is the future?

**Comment by ZivKes** [comment]
Please help i have the same issue i would like to know how you located the malformed project file line

**Comment by teffi** [comment]
@ZivKes Had to open pbxproj in a text editor manually and looked up for this malformed  `/* [CP] Embed Pods Frameworks */ = {`. It has no end `}` and content. Browse through the others and you can tell.

**Comment by zero2lambo** [comment]
What if my file is 20 000 lines...would I have to check 20 000 kines of
code?

**Comment by dnkoutso** [comment]
I did it via "binary search". Cut the file in the middle (or try to) and see if that works, then repeat the process until you narrow it down to a certain half that starts to show the issue.

**Comment by zero2lambo** [comment]
Do you have a video tutorial link for that else are you on discord, where
can I DM you?

**Comment by rameswar54** [comment]
@zero2lambo I faced the same problem today and after 3 hours of looking at the .pbxproj file this is how I figured out the issue.
1. Open the `project.pbxproj` file in Xcode, not in Text Edit. 
2. Try using `code folding` feature of Xcode from top, starting with the first `{`

You'll figure out the problem. If you're still unable to figure out the issue, open your repo and do a folder/group comparison with the content structure in `pbxproj` file.

That's how I figured out where one of the ending `};` was missing.
Hope this is helpful. :)

**Comment by s6joui** [comment]
You can also use Kin to check for errors on your pbxproj: https://github.com/Karumi/Kin/
Look for something like this:
`ERROR: line 6813:2 mismatched input 'D8268C4E241C95E7B48D6FD3' expecting 'isa'`

**Comment by glennposadas** [comment]
Just wanna share what I did, and the most logical way to fix this, at least for me. Since we want to save time and take the easiest path as much as possible.

Kin is amazing, I got the missing data issues something, but when I checked the proj file, they're there. 

So... what I did was:
Go to the most recent previous commit that was working, copy the `project.pbxproj` codes and then go back to your latest commit that has the issue, paste all the codes there. Use external diff if you wanna see what caused the error. (OR SIMPLY copy the whole xcodeproj file to somewhere, go to the latest commit, paste it there - replace).

**Comment by NomanGul** [comment]
in my case, semi-colon was missing 🤦

**Comment by sof9816** [comment]
This happened to me when I merge 2 branches and the changes were in the  ```.xcodeproj``` file, and when I accept both changes the file was corrupted because of missing ```};``` due to that some changes were confusing the ```};``` with other lines so after reading the comments above I undo the changes and started to see where the problem is and add the missing ```};```

Thanks for the above comments :) it really helped and hope my comment help someone :)
