### ISSUE TITLE
Cannot Deintegrate

### ISSUE THREAD

**Issue by AdiAyyakad** [CocoaPods/CocoaPods#8936]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

`bundle exec pod deintegrate`

## What did you expect to happen?

Cocoapods cleanup

## What happened instead?

```
NoMethodError - undefined method `build_files' for nil:NilClass
/Users/aditya/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-deintegrate-1.0.4/lib/cocoapods/deintegrator.rb:53:in `block (2 levels) in deintegrate_pods_libraries'
/Users/aditya/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-deintegrate-1.0.4/lib/cocoapods/deintegrator.rb:51:in `each'
/Users/aditya/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-deintegrate-1.0.4/lib/cocoapods/deintegrator.rb:51:in `block in deintegrate_pods_libraries'
/Users/aditya/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.6.0.beta.2/lib/cocoapods/user_interface.rb:64:in `section'
/Users/aditya/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-deintegrate-1.0.4/lib/cocoapods/deintegrator.rb:50:in `deintegrate_pods_libraries'
/Users/aditya/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-deintegrate-1.0.4/lib/cocoapods/deintegrator.rb:29:in `block in deintegrate_target'
/Users/aditya/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.6.0.beta.2/lib/cocoapods/user_interface.rb:64:in `section'
/Users/aditya/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-deintegrate-1.0.4/lib/cocoapods/deintegrator.rb:24:in `deintegrate_target'
/Users/aditya/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-deintegrate-1.0.4/lib/cocoapods/deintegrator.rb:11:in `block (2 levels) in deintegrate_project'
/Users/aditya/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-deintegrate-1.0.4/lib/cocoapods/deintegrator.rb:10:in `each'
/Users/aditya/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-deintegrate-1.0.4/lib/cocoapods/deintegrator.rb:10:in `block in deintegrate_project'
/Users/aditya/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.6.0.beta.2/lib/cocoapods/user_interface.rb:64:in `section'
/Users/aditya/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-deintegrate-1.0.4/lib/cocoapods/deintegrator.rb:9:in `deintegrate_project'
/Users/aditya/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-deintegrate-1.0.4/lib/cocoapods/command/deintegrate.rb:48:in `run'
/Users/aditya/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/aditya/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.6.0.beta.2/lib/cocoapods/command.rb:52:in `run'
/Users/aditya/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cocoapods-1.6.0.beta.2/bin/pod:55:in `<top (required)>'
/Users/aditya/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bin/pod:23:in `load'
/Users/aditya/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bin/pod:23:in `<top (required)>'
/Users/aditya/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.2/lib/bundler/cli/exec.rb:74:in `load'
/Users/aditya/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
/Users/aditya/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.2/lib/bundler/cli/exec.rb:28:in `run'
/Users/aditya/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.2/lib/bundler/cli.rb:424:in `exec'
/Users/aditya/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/aditya/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/aditya/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.2/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/Users/aditya/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.2/lib/bundler/cli.rb:27:in `dispatch'
/Users/aditya/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.2/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/Users/aditya/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.2/lib/bundler/cli.rb:18:in `start'
/Users/aditya/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.2/exe/bundle:30:in `block in <top (required)>'
/Users/aditya/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.2/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/Users/aditya/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.16.2/exe/bundle:22:in `<top (required)>'
/Users/aditya/.rbenv/versions/2.3.1/bin/bundle:23:in `load'
/Users/aditya/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>'
```
### Stack

```
   CocoaPods : 1.6.0.beta.2
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin17]
    RubyGems : 2.5.1
        Host : Mac OS X 10.14.5 (18F132)
       Xcode : 10.1 (10B61)
         Git : git version 2.21.0
Ruby lib dir : /Users/aditya/.rbenv/versions/2.3.1/lib
Repositories : butterflynetwork - git@github.com:ButterflyNetwork/Specs.git @ e79ad68082698d391743cbffa7ea7f4355a6f83f
               master - https://github.com/CocoaPods/Specs.git @ 383827e045a542530b984bc1ab667c83201e08aa
               twilio - https://github.com/twilio/cocoapod-specs @ 9bf659ed7246ba34625b81754031fbd5ac20fe68
```

### Installation Source

```
Executable Path: /Users/aditya/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate    : 1.0.4
cocoapods-no-dev-schemes : 1.0.1
cocoapods-plugins        : 1.0.0
cocoapods-search         : 1.0.0
cocoapods-stats          : 1.1.0
cocoapods-trunk          : 1.3.1
cocoapods-try            : 1.1.0
```

Omitted the Podfile because it seems irrelevant and exposes some local pods. I did try turning my Podfile into:
```
target 'MyProject' do
end
```

And the same issues are occurring. Plus, I can't `pod install` without some `NoMethodError - undefined method `remove_referrer' for nil:NilClass` problem 🤔

**Comment by dnkoutso** [comment]
Can you upload a sample app please?

**Comment by dnkoutso** [comment]
Also please update to 1.6.3 or 1.7.2

**Comment by AdiAyyakad** [comment]
Both 1.6.3 and 1.7.2 break too! Will attempt to repro in a sample project now

**Comment by dnkoutso** [comment]
great!
