### ISSUE TITLE
Packager no longer works

### ISSUE THREAD

**Issue by vitor-gyant** [CocoaPods/CocoaPods#8942]
Hi,

I'm trying to use Cocoapods-packager plugin as state here https://guides.cocoapods.org/plugins/using-pods-for-closed-source-libs.html but it seems that it no longer works.

### Command

```
/Users/vmagalhaes/.rbenv/versions/2.4.4/bin/pod package MySDK.podspec
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.4.4p296 (2018-03-28 revision 63013) [x86_64-darwin18]
    RubyGems : 2.6.14.1
        Host : Mac OS X 10.14.4 (18E226)
       Xcode : 10.2.1 (10E1001)
         Git : git version 2.20.1 (Apple Git-117)
Ruby lib dir : /Users/vmagalhaes/.rbenv/versions/2.4.4/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ b3ac80d346179499328b62d9faad35126139726b
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-packager    : 1.5.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
slather               : 2.4.6
```

### Error

```
Encoding::CompatibilityError - incompatible character encodings: UTF-8 and ASCII-8BIT
/Users/vmagalhaes/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/executable.rb:69:in `execute_command'
/Users/vmagalhaes/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/downloader.rb:140:in `execute_command'
/Users/vmagalhaes/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cocoapods-downloader-1.2.1/lib/cocoapods-downloader/base.rb:154:in `block in executable'
/Users/vmagalhaes/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cocoapods-downloader-1.2.1/lib/cocoapods-downloader/git.rb:79:in `block in clone'
/Users/vmagalhaes/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/downloader.rb:173:in `block in ui_sub_action'
/Users/vmagalhaes/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
/Users/vmagalhaes/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/downloader.rb:172:in `ui_sub_action'
/Users/vmagalhaes/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cocoapods-downloader-1.2.1/lib/cocoapods-downloader/git.rb:77:in `clone'
/Users/vmagalhaes/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cocoapods-downloader-1.2.1/lib/cocoapods-downloader/git.rb:45:in `download!'
/Users/vmagalhaes/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cocoapods-downloader-1.2.1/lib/cocoapods-downloader/base.rb:82:in `block in download'
/Users/vmagalhaes/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/downloader.rb:157:in `block in ui_action'
/Users/vmagalhaes/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
/Users/vmagalhaes/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/downloader.rb:156:in `ui_action'
/Users/vmagalhaes/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cocoapods-downloader-1.2.1/lib/cocoapods-downloader/base.rb:80:in `download'
/Users/vmagalhaes/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/downloader.rb:108:in `download_source'
/Users/vmagalhaes/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/downloader.rb:75:in `download_request'
/Users/vmagalhaes/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/downloader/cache.rb:171:in `download'
/Users/vmagalhaes/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/downloader/cache.rb:154:in `block in uncached_pod'
/Users/vmagalhaes/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/downloader/cache.rb:181:in `in_tmpdir'
/Users/vmagalhaes/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/downloader/cache.rb:153:in `uncached_pod'
/Users/vmagalhaes/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/downloader/cache.rb:33:in `download_pod'
/Users/vmagalhaes/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/downloader.rb:42:in `download'
/Users/vmagalhaes/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/pod_source_installer.rb:121:in `download_source'
/Users/vmagalhaes/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/pod_source_installer.rb:60:in `install!'
/Users/vmagalhaes/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:374:in `install_source_of_pod'
/Users/vmagalhaes/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:339:in `block (2 levels) in install_pod_sources'
/Users/vmagalhaes/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:85:in `titled_section'
/Users/vmagalhaes/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:338:in `block in install_pod_sources'
/Users/vmagalhaes/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:321:in `each'
/Users/vmagalhaes/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:321:in `install_pod_sources'
/Users/vmagalhaes/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:164:in `block in download_dependencies'
/Users/vmagalhaes/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
/Users/vmagalhaes/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:162:in `download_dependencies'
/Users/vmagalhaes/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:117:in `install!'
/Users/vmagalhaes/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cocoapods-packager-1.5.0/lib/cocoapods-packager/pod_utils.rb:26:in `install_pod'
/Users/vmagalhaes/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cocoapods-packager-1.5.0/lib/pod/command/package.rb:79:in `build_in_sandbox'
/Users/vmagalhaes/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cocoapods-packager-1.5.0/lib/pod/command/package.rb:100:in `block in build_package'
/Users/vmagalhaes/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cocoapods-packager-1.5.0/lib/pod/command/package.rb:99:in `each'
/Users/vmagalhaes/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cocoapods-packager-1.5.0/lib/pod/command/package.rb:99:in `build_package'
/Users/vmagalhaes/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cocoapods-packager-1.5.0/lib/pod/command/package.rb:66:in `run'
/Users/vmagalhaes/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/vmagalhaes/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
/Users/vmagalhaes/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
/Users/vmagalhaes/.rbenv/versions/2.4.4/bin/pod:23:in `load'
/Users/vmagalhaes/.rbenv/versions/2.4.4/bin/pod:23:in `<main>'
```

**Comment by dnkoutso** [comment]
Transferring issue to cocoapods-package.

This might be a specific user configuration issue though from the looks of it.
