### ISSUE TITLE
Windows Long Path Failed to Install

### ISSUE THREAD

**Issue by soulsoul666** [CocoaPods/CocoaPods#8959]
Hello guys i trying to call 'pod install' to download and install Firebase with pods but when the path reach 260 (MAX_PATH_LIMIT) the pod fail to download the dependence.

My sugestion is to use '\\?\' before path to make windows expand to Unicode Long Path while downloading

https://docs.microsoft.com/en-us/windows/desktop/fileio/naming-a-file#maximum-path-length-limitation

Error:

D:\UnityProjects\AeC\Robbyson_Mobile\BuildXCode>pod install
Analyzing dependencies
Downloading dependencies
Installing Firebase (6.1.0)
Installing FirebaseAnalytics (6.0.1)
Installing FirebaseAnalyticsInterop (1.2.0)

[!] Error installing FirebaseAnalyticsInterop

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
D:/Program Data/Ruby25-x64/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.7.3
        Ruby : ruby 2.5.5p157 (2019-03-15 revision 67260) [x64-mingw32]
    RubyGems : 2.7.6.2
        Host : Unable to find an executable (No such file or directory - sw_vers)  ()
       Xcode : -version) ()
         Git : git version 2.22.0.windows.1
Ruby lib dir : D:/Program Data/Ruby25-x64/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 3983b6bcc6bf0cefea5bfdd10865abd287e14cdc
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'

target 'Unity-iPhone' do
pod 'Firebase/Core', '6.1.0'
pod 'Firebase/Messaging', '6.1.0'
end
```

### Error

```
Errno::ENOENT - No such file or directory @ rb_sysopen - C:/Users/RafaVR/Library/Caches/CocoaPods/Pods/Release/FirebaseAnalyticsInterop/1.2.0-efbe4/Example/tvOSSample/tvOSSample/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Front.imagestacklayer/Content.imageset/Contents.json
D:/Program Data/Ruby25-x64/lib/ruby/2.5.0/fileutils.rb:1292:in `initialize'
D:/Program Data/Ruby25-x64/lib/ruby/2.5.0/fileutils.rb:1292:in `open'
D:/Program Data/Ruby25-x64/lib/ruby/2.5.0/fileutils.rb:1292:in `block in copy_file'
D:/Program Data/Ruby25-x64/lib/ruby/2.5.0/fileutils.rb:1291:in `open'
D:/Program Data/Ruby25-x64/lib/ruby/2.5.0/fileutils.rb:1291:in `copy_file'
D:/Program Data/Ruby25-x64/lib/ruby/2.5.0/fileutils.rb:1259:in `copy'
D:/Program Data/Ruby25-x64/lib/ruby/2.5.0/fileutils.rb:418:in `block in copy_entry'
D:/Program Data/Ruby25-x64/lib/ruby/2.5.0/fileutils.rb:1390:in `wrap_traverse'
D:/Program Data/Ruby25-x64/lib/ruby/2.5.0/fileutils.rb:1393:in `block in wrap_traverse'
D:/Program Data/Ruby25-x64/lib/ruby/2.5.0/fileutils.rb:1392:in `each'
D:/Program Data/Ruby25-x64/lib/ruby/2.5.0/fileutils.rb:1392:in `wrap_traverse'
D:/Program Data/Ruby25-x64/lib/ruby/2.5.0/fileutils.rb:1393:in `block in wrap_traverse'
D:/Program Data/Ruby25-x64/lib/ruby/2.5.0/fileutils.rb:1392:in `each'
D:/Program Data/Ruby25-x64/lib/ruby/2.5.0/fileutils.rb:1392:in `wrap_traverse'
D:/Program Data/Ruby25-x64/lib/ruby/2.5.0/fileutils.rb:1393:in `block in wrap_traverse'
D:/Program Data/Ruby25-x64/lib/ruby/2.5.0/fileutils.rb:1392:in `each'
D:/Program Data/Ruby25-x64/lib/ruby/2.5.0/fileutils.rb:1392:in `wrap_traverse'
D:/Program Data/Ruby25-x64/lib/ruby/2.5.0/fileutils.rb:1393:in `block in wrap_traverse'
D:/Program Data/Ruby25-x64/lib/ruby/2.5.0/fileutils.rb:1392:in `each'
D:/Program Data/Ruby25-x64/lib/ruby/2.5.0/fileutils.rb:1392:in `wrap_traverse'
D:/Program Data/Ruby25-x64/lib/ruby/2.5.0/fileutils.rb:1393:in `block in wrap_traverse'
D:/Program Data/Ruby25-x64/lib/ruby/2.5.0/fileutils.rb:1392:in `each'
D:/Program Data/Ruby25-x64/lib/ruby/2.5.0/fileutils.rb:1392:in `wrap_traverse'
D:/Program Data/Ruby25-x64/lib/ruby/2.5.0/fileutils.rb:1393:in `block in wrap_traverse'
D:/Program Data/Ruby25-x64/lib/ruby/2.5.0/fileutils.rb:1392:in `each'
D:/Program Data/Ruby25-x64/lib/ruby/2.5.0/fileutils.rb:1392:in `wrap_traverse'
D:/Program Data/Ruby25-x64/lib/ruby/2.5.0/fileutils.rb:1393:in `block in wrap_traverse'
D:/Program Data/Ruby25-x64/lib/ruby/2.5.0/fileutils.rb:1392:in `each'
D:/Program Data/Ruby25-x64/lib/ruby/2.5.0/fileutils.rb:1392:in `wrap_traverse'
D:/Program Data/Ruby25-x64/lib/ruby/2.5.0/fileutils.rb:1393:in `block in wrap_traverse'
D:/Program Data/Ruby25-x64/lib/ruby/2.5.0/fileutils.rb:1392:in `each'
D:/Program Data/Ruby25-x64/lib/ruby/2.5.0/fileutils.rb:1392:in `wrap_traverse'
D:/Program Data/Ruby25-x64/lib/ruby/2.5.0/fileutils.rb:1393:in `block in wrap_traverse'
D:/Program Data/Ruby25-x64/lib/ruby/2.5.0/fileutils.rb:1392:in `each'
D:/Program Data/Ruby25-x64/lib/ruby/2.5.0/fileutils.rb:1392:in `wrap_traverse'
D:/Program Data/Ruby25-x64/lib/ruby/2.5.0/fileutils.rb:415:in `copy_entry'
D:/Program Data/Ruby25-x64/lib/ruby/2.5.0/fileutils.rb:393:in `block in cp_r'
D:/Program Data/Ruby25-x64/lib/ruby/2.5.0/fileutils.rb:1463:in `block in fu_each_src_dest'
D:/Program Data/Ruby25-x64/lib/ruby/2.5.0/fileutils.rb:1479:in `fu_each_src_dest0'
D:/Program Data/Ruby25-x64/lib/ruby/2.5.0/fileutils.rb:1461:in `fu_each_src_dest'
D:/Program Data/Ruby25-x64/lib/ruby/2.5.0/fileutils.rb:392:in `cp_r'
D:/Program Data/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.3/lib/cocoapods/downloader/cache.rb:201:in `copy_and_clean'
D:/Program Data/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.3/lib/cocoapods/downloader/cache.rb:159:in `block (2 levels) in uncached_pod'
D:/Program Data/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.3/lib/cocoapods/downloader/cache.rb:157:in `each'
D:/Program Data/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.3/lib/cocoapods/downloader/cache.rb:157:in `block in uncached_pod'
D:/Program Data/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.3/lib/cocoapods/downloader/cache.rb:181:in `in_tmpdir'
D:/Program Data/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.3/lib/cocoapods/downloader/cache.rb:153:in `uncached_pod'
D:/Program Data/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.3/lib/cocoapods/downloader/cache.rb:33:in `download_pod'
D:/Program Data/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.3/lib/cocoapods/downloader.rb:42:in `download'
D:/Program Data/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.3/lib/cocoapods/installer/pod_source_installer.rb:109:in `download_source'
D:/Program Data/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.3/lib/cocoapods/installer/pod_source_installer.rb:62:in `install!'
D:/Program Data/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.3/lib/cocoapods/installer.rb:545:in `install_source_of_pod'
D:/Program Data/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.3/lib/cocoapods/installer.rb:496:in `block (2 levels) in install_pod_sources'
D:/Program Data/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.3/lib/cocoapods/user_interface.rb:86:in `titled_section'
D:/Program Data/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.3/lib/cocoapods/installer.rb:495:in `block in install_pod_sources'
D:/Program Data/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.3/lib/cocoapods/installer.rb:478:in `each'
D:/Program Data/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.3/lib/cocoapods/installer.rb:478:in `install_pod_sources'
D:/Program Data/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.3/lib/cocoapods/installer.rb:235:in `block in download_dependencies'
D:/Program Data/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.3/lib/cocoapods/user_interface.rb:64:in `section'
D:/Program Data/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.3/lib/cocoapods/installer.rb:234:in `download_dependencies'
D:/Program Data/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.3/lib/cocoapods/installer.rb:157:in `install!'
D:/Program Data/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.3/lib/cocoapods/command/install.rb:51:in `run'
D:/Program Data/Ruby25-x64/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
D:/Program Data/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.3/lib/cocoapods/command.rb:52:in `run'
D:/Program Data/Ruby25-x64/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.3/bin/pod:55:in `<top (required)>'
D:/Program Data/Ruby25-x64/bin/pod:23:in `load'
D:/Program Data/Ruby25-x64/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=No+such+file+or+directory+%40+rb_sysopen+-+C%3A%2FUsers%2FRafaVR%2FLibrary%2FCaches%2FCocoaPods%2FPods%2FRelease%2FFirebaseAnalyticsInterop%2F1.2.0-efbe4%2FExample%2FtvOSSample%2FtvOSSample%2FAssets.xcassets%2FApp+Icon+%26+Top+Shelf+Image.brandassets%2FApp+Icon+-+App+Store.imagestack%2FFront.imagestacklayer%2FContent.imageset%2FContents.json&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Searching for inspections failed: undefined method `map' for nil:NilClass

**Comment by dnkoutso** [comment]
/cc @paulb777 for Firebase stuff.

Yes we can probably fix this.

**Comment by paulb777** [comment]
cc: @davidair for windows

**Comment by davidair** [comment]
I've taken a quick look and the \\?\ suggested by @soulsoul666 looks promising. However, we would need to fight Ruby on this one, because those paths do not allow mixing \ and / and Ruby's File::SEPARATOR is '/' on Windows (see https://bugs.ruby-lang.org/issues/7822), meaning that code that uses it (e.g FileUtils.cp_r) will not work.

One solution would be to re-implement FileUtils.cp_r to be more Windows-friendly.

**Comment by soulsoul666** [comment]
Another problem in windows is related to new default Windows TAR.

Now, windows come with native TAR and CURL commands but in this version of TAR the command `--force` is not supported:

`tar: Option --force-local is not supported`

PODs show try use TAR of Ruby instead of Windows Native TAR, or avoid using --force to fix this problem.

By now the only way to avoid this error is editing the ENVIROMENT VARIABLE PATH and add ruby TAR folder before `C:\Windows\System32` PATH.

Best regards
Rafael

**Comment by soulsoul666** [comment]
> I've taken a quick look and the \?\ suggested by @soulsoul666 looks promising. However, we would need to fight Ruby on this one, because those paths do not allow mixing \ and / and Ruby's File::SEPARATOR is '/' on Windows (see https://bugs.ruby-lang.org/issues/7822), meaning that code that uses it (e.g FileUtils.cp_r) will not work.
> 
> One solution would be to re-implement FileUtils.cp_r to be more Windows-friendly.

@davidair but in this issue mentioned by you is related with another problem.

Windows can't handle with folder with more than 255 chars (even with long path support)

ex
`\\?\c:\<folderwith256charsName>\otherfolder`

No one will try create a single folder with 256 char length hehehehe (my guess)

i thing you can try replace all "/" to "\\" before call FileUtils.r and than add the Prefix "\\?\"

What do you think about this? my sugestion make any sense?

Best Regards
Rafael

**Comment by davidair** [comment]
@AvigarD611 - haven't had a chance to look into it yet

**Comment by rafcsoares** [comment]
Any improvement in this issue?

Best Regards
Rafael

**Comment by rafcsoares** [comment]
@davidair looks like to solve this problem the path must be converted before calling
"mkdir", "mkfile", "file exists" and "directory exist".

As ruby support \\?\ without mixing with / or mixing with subpath we have this "Pseudo-code" to convert path to long path 
(in C#, i dont have enought  knowledge to write this in Ruby pseudo code in ruby)

```
public static string ConvertToWindowsLongPath(string path)
{
	//Prevent errors with nulls
	if(path == null)
		path = ""

	//Convert path to windows forward slash
	path = path.Replace("/", @"\");

	//Here we have to solve relative path and convert it to FullPath
	if(path.StartsWith(@"\") || path.StartsWith(@"."))
	{
		//Now we must solve SubPath (in C# we can do it using Path.GetFullPath as this method solve /../ and ./) 
		path = Path.GetFullPath(path);
	}
	
	//With full path we must check if we need to convert to Unicode Path
	if(path.Length > 255 && !path.StartsWith(@"\\?\"))
		path = @"\\?\" + path;
	
	//Return the full valid path
	return path;
}
```

**Comment by davidair** [comment]
The suggestion makes sense, but there are 129 uses of FileUtils in CocoaPods so this might be some work. I'm also not able to use CocoaPods 1.9.3 on Windows due to https://github.com/CocoaPods/CocoaPods/issues/9731.

**Comment by itamardo** [comment]
Any updates on this issue?
I am trying to add firebase vision ml to my flutter app that I develop on windows and build for iOS using Codemagic.
I seem to fail adding the vision pod for exactly the above reason.
I have set the long path name for win32 in windows 10
I tried pwsh, cmd, git bash

If I could tell Cocoapods somehow not to use c:\users\myuser\....\caches\cocoapods as a base folder that would solve the issue.
Is there some way to force the base folder to some other, short path?

here's my podfile

```
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
# source 'https://cocoapods-cdn.netlify.app/'
source 'https://github.com/CocoaPods/Specs.git'
# project './Runner.xcodeproj'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner
  # pod 'Firebase/Core'
  # pod 'Firebase/MLVision'
  #pod 'Firebase', '6.25.0'
  #pod 'Firebase/MLVisionFaceModel', '6.25.0'
  pod 'Firebase'
  pod 'Firebase/MLVisionFaceModel'
end
```

**Comment by itamardo** [comment]
update: although a bit crude, I opened cocoapods/config.rb and changed cache_root to the constant 'c:/x' after creating that folder. After that, pod update went through.
now i'm facing other, flutter/windows warning which are unrelated to the long path issue

**Comment by davidair** [comment]
Patching config.rb is a cool hack, but can't you just specify it properly via config.yaml? I think on Windows it should be %USERPROFILE%\.cocoapods\config.yaml (based on what I see in https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/config.rb).

Would be curious about your Flutter warning although this is probably outside of the scope of this conversation. Perhaps file an issue on Flutter just to get the conversation started?

**Comment by itamardo** [comment]
Thanks! That **does** sound much better.  I don't know how I missed that comment.

The flutter part is still a problem. Been at it for quite some time now. Still unable to pass the CI build even after solving the warnings. I opened an issue there, too, with more information regarding flutter. Hope someone will have an idea.

**Comment by davidair** [comment]
Do you mind pasting a link to the Flutter issue?

**Comment by itamardo** [comment]
https://github.com/FirebaseExtended/flutterfire/discussions/3938

**Comment by barisferah** [comment]
Has any fix or work around (except for the one that making the cache path something like c:/x) for this issue been found?
