### ISSUE TITLE
pod update error with CDN

### ISSUE THREAD

**Issue by rakuyoMo** [CocoaPods/CocoaPods#8991]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod update`

## What did you expect to happen?

success

## What happened instead?

an error occurred.

### Error

```
NameError - uninitialized constant Concurrent::Promises
Did you mean?  Concurrent::Promise
/Users/mbcore/.rvm/gems/ruby-2.4.0@global/gems/cocoapods-core-1.7.4/lib/cocoapods-core/cdn_source.rb:60:in `block in preheat_existing_files'
/Users/mbcore/.rvm/gems/ruby-2.4.0@global/gems/cocoapods-core-1.7.4/lib/cocoapods-core/cdn_source.rb:59:in `map'
/Users/mbcore/.rvm/gems/ruby-2.4.0@global/gems/cocoapods-core-1.7.4/lib/cocoapods-core/cdn_source.rb:59:in `preheat_existing_files'
/Users/mbcore/.rvm/gems/ruby-2.4.0@global/gems/cocoapods-core-1.7.4/lib/cocoapods-core/cdn_source.rb:229:in `update'
/Users/mbcore/.rvm/gems/ruby-2.4.0@global/gems/cocoapods-1.7.4/lib/cocoapods/sources_manager.rb:93:in `block (2 levels) in update'
/Users/mbcore/.rvm/gems/ruby-2.4.0@global/gems/cocoapods-1.7.4/lib/cocoapods/user_interface.rb:64:in `section'
/Users/mbcore/.rvm/gems/ruby-2.4.0@global/gems/cocoapods-1.7.4/lib/cocoapods/sources_manager.rb:92:in `block in update'
/Users/mbcore/.rvm/gems/ruby-2.4.0@global/gems/cocoapods-1.7.4/lib/cocoapods/sources_manager.rb:91:in `each'
/Users/mbcore/.rvm/gems/ruby-2.4.0@global/gems/cocoapods-1.7.4/lib/cocoapods/sources_manager.rb:91:in `update'
/Users/mbcore/.rvm/gems/ruby-2.4.0@global/gems/cocoapods-1.7.4/lib/cocoapods/installer/analyzer.rb:140:in `block in update_repositories'
/Users/mbcore/.rvm/gems/ruby-2.4.0@global/gems/cocoapods-1.7.4/lib/cocoapods/installer/analyzer.rb:138:in `each'
/Users/mbcore/.rvm/gems/ruby-2.4.0@global/gems/cocoapods-1.7.4/lib/cocoapods/installer/analyzer.rb:138:in `update_repositories'
/Users/mbcore/.rvm/gems/ruby-2.4.0@global/gems/cocoapods-1.7.4/lib/cocoapods/installer.rb:217:in `block in resolve_dependencies'
/Users/mbcore/.rvm/gems/ruby-2.4.0@global/gems/cocoapods-1.7.4/lib/cocoapods/user_interface.rb:64:in `section'
/Users/mbcore/.rvm/gems/ruby-2.4.0@global/gems/cocoapods-1.7.4/lib/cocoapods/installer.rb:216:in `resolve_dependencies'
/Users/mbcore/.rvm/gems/ruby-2.4.0@global/gems/cocoapods-1.7.4/lib/cocoapods/installer.rb:156:in `install!'
/Users/mbcore/.rvm/gems/ruby-2.4.0@global/gems/cocoapods-1.7.4/lib/cocoapods/command/update.rb:62:in `run'
/Users/mbcore/.rvm/gems/ruby-2.4.0@global/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/mbcore/.rvm/gems/ruby-2.4.0@global/gems/cocoapods-1.7.4/lib/cocoapods/command.rb:52:in `run'
/Users/mbcore/.rvm/gems/ruby-2.4.0@global/gems/cocoapods-1.7.4/bin/pod:55:in `<top (required)>'
/Users/mbcore/.rvm/rubies/ruby-2.4.0/bin/pod:23:in `load'
/Users/mbcore/.rvm/rubies/ruby-2.4.0/bin/pod:23:in `<main>'
/Users/mbcore/.rvm/gems/ruby-2.4.0@global/bin/ruby_executable_hooks:24:in `eval'
/Users/mbcore/.rvm/gems/ruby-2.4.0@global/bin/ruby_executable_hooks:24:in `<main>'
```

### Stack

```
   CocoaPods : 1.7.4
        Ruby : ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin18]
    RubyGems : 2.7.7
        Host : Mac OS X 10.14.5 (18F132)
       Xcode : 10.2.1 (10E1001)
         Git : git version 2.18.0
Ruby lib dir : /Users/mbcore/.rvm/rubies/ruby-2.4.0/lib
Repositories : 
               MBCModuleSpecs - https://git.mbcore.com/iOSModuleSwift/MBCModuleSpecs.git @ 062d8dfe576ebb7195caf1801f33a3d1e14d06a5
               mbcore-iosmodule-mbcspecs - https://git.mbcore.com/iOSModule/MBCSpecs.git @ a6d7a4f80475b4fe8522d5f79236dcbcfe409250
               MBCSpecs - git@git.mbcore.com:iOSModule/MBCSpecs.git @ a6d7a4f80475b4fe8522d5f79236dcbcfe409250
```

### Installation Source

```
Executable Path: /Users/mbcore/.rvm/rubies/ruby-2.4.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-playgrounds : 1.2.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

podfile like:

source 'private pod url'
source 'https://cdn.cocoapods.org/'

platform :ios, '10.0'

inhibit_all_warnings!

install! 'cocoapods',
         :generate_multiple_pod_projects => true,
         :incremental_installation => true

target 'TargetName' do

some pods ...

end

**Comment by rakuyoMo** [comment]
By the way

When source is 'https://cdn.jsdelivr.net/cocoa/', the 'pod update' command is executed much faster than 'https://cdn.cocoapods.org/'. Should I use the first source?

**Comment by rakuyoMo** [comment]
I found this [issue](https://github.com/CocoaPods/CocoaPods/issues/8948), It solved my problem. I am very sorry that I should have discovered this issue earlier.

**Comment by yinanwang1** [comment]
And? How to fix?

**Comment by rakuyoMo** [comment]
> And? How to fix?

`gem install concurrent-ruby` or `gem update concurrent-ruby`.

**Comment by yinanwang1** [comment]
> > And? How to fix?
> 
> `gem install concurrent-ruby` or `gem update concurrent-ruby`.

Yes, it works. Thx.

**Comment by lucifer717** [comment]
> > And? How to fix?
> 
> `gem install concurrent-ruby` or `gem update concurrent-ruby`.

thx, it works

**Comment by Theunodb** [comment]
The solutions mentioned above didn't resolve it for me. Not sure if i'm missing something:

### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?
1. pod install
2. Got the error
3. Tried gem install concurrent-ruby
4. pod install, still got the same error

* What did you expect to happen?
the pods to install

* What happened instead?
got the error below: 
NameError - uninitialized constant Concurrent::Promises

### Stack

```
   CocoaPods : 1.8.0.beta.1
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.6 (18G84)
       Xcode : 10.3 (10G8)
         Git : git version 2.20.1 (Apple Git-117)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ 20eb641aaed46674449b00af5fe0f6ec30bddccd
               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-clean       : 0.0.1
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'Sasos' do
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'libPhoneNumber-iOS'
end
```

### Error

```
NameError - uninitialized constant Concurrent::Promises
Did you mean?  Concurrent::Promise
/Users/theunodebruin/.gem/ruby/2.3.0/gems/cocoapods-core-1.8.0.beta.1/lib/cocoapods-core/cdn_source.rb:126:in `block in versions'
/Users/theunodebruin/.gem/ruby/2.3.0/gems/cocoapods-core-1.8.0.beta.1/lib/cocoapods-core/cdn_source.rb:121:in `map'
/Users/theunodebruin/.gem/ruby/2.3.0/gems/cocoapods-core-1.8.0.beta.1/lib/cocoapods-core/cdn_source.rb:121:in `versions'
/Users/theunodebruin/.gem/ruby/2.3.0/gems/cocoapods-core-1.8.0.beta.1/lib/cocoapods-core/specification/set.rb:99:in `block in versions_by_source'
/Users/theunodebruin/.gem/ruby/2.3.0/gems/cocoapods-core-1.8.0.beta.1/lib/cocoapods-core/specification/set.rb:98:in `each'
/Users/theunodebruin/.gem/ruby/2.3.0/gems/cocoapods-core-1.8.0.beta.1/lib/cocoapods-core/specification/set.rb:98:in `each_with_object'
/Users/theunodebruin/.gem/ruby/2.3.0/gems/cocoapods-core-1.8.0.beta.1/lib/cocoapods-core/specification/set.rb:98:in `versions_by_source'
/Users/theunodebruin/.gem/ruby/2.3.0/gems/cocoapods-core-1.8.0.beta.1/lib/cocoapods-core/specification/set.rb:56:in `specification_name'
/Users/theunodebruin/.gem/ruby/2.3.0/gems/cocoapods-core-1.8.0.beta.1/lib/cocoapods-core/cdn_source.rb:212:in `search'
/Users/theunodebruin/.gem/ruby/2.3.0/gems/cocoapods-core-1.8.0.beta.1/lib/cocoapods-core/source/aggregate.rb:83:in `block in search'
/Users/theunodebruin/.gem/ruby/2.3.0/gems/cocoapods-core-1.8.0.beta.1/lib/cocoapods-core/source/aggregate.rb:83:in `select'
/Users/theunodebruin/.gem/ruby/2.3.0/gems/cocoapods-core-1.8.0.beta.1/lib/cocoapods-core/source/aggregate.rb:83:in `search'
/Users/theunodebruin/.gem/ruby/2.3.0/gems/cocoapods-1.8.0.beta.1/lib/cocoapods/resolver.rb:416:in `create_set_from_sources'
/Users/theunodebruin/.gem/ruby/2.3.0/gems/cocoapods-1.8.0.beta.1/lib/cocoapods/resolver.rb:385:in `find_cached_set'
/Users/theunodebruin/.gem/ruby/2.3.0/gems/cocoapods-1.8.0.beta.1/lib/cocoapods/resolver.rb:360:in `specifications_for_dependency'
/Users/theunodebruin/.gem/ruby/2.3.0/gems/cocoapods-1.8.0.beta.1/lib/cocoapods/resolver.rb:165:in `search_for'
/Users/theunodebruin/.gem/ruby/2.3.0/gems/cocoapods-1.8.0.beta.1/lib/cocoapods/resolver.rb:274:in `block in sort_dependencies'
/Users/theunodebruin/.gem/ruby/2.3.0/gems/cocoapods-1.8.0.beta.1/lib/cocoapods/resolver.rb:267:in `each'
/Users/theunodebruin/.gem/ruby/2.3.0/gems/cocoapods-1.8.0.beta.1/lib/cocoapods/resolver.rb:267:in `sort_by'
/Users/theunodebruin/.gem/ruby/2.3.0/gems/cocoapods-1.8.0.beta.1/lib/cocoapods/resolver.rb:267:in `sort_dependencies'
/Users/theunodebruin/.gem/ruby/2.3.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:53:in `block in sort_dependencies'
/Users/theunodebruin/.gem/ruby/2.3.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:70:in `with_no_such_dependency_error_handling'
/Users/theunodebruin/.gem/ruby/2.3.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:52:in `sort_dependencies'
/Users/theunodebruin/.gem/ruby/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:288:in `initial_state'
/Users/theunodebruin/.gem/ruby/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:210:in `start_resolution'
/Users/theunodebruin/.gem/ruby/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:168:in `resolve'
/Users/theunodebruin/.gem/ruby/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
/Users/theunodebruin/.gem/ruby/2.3.0/gems/cocoapods-1.8.0.beta.1/lib/cocoapods/resolver.rb:94:in `resolve'
/Users/theunodebruin/.gem/ruby/2.3.0/gems/cocoapods-1.8.0.beta.1/lib/cocoapods/installer/analyzer.rb:974:in `block in resolve_dependencies'
/Users/theunodebruin/.gem/ruby/2.3.0/gems/cocoapods-1.8.0.beta.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/theunodebruin/.gem/ruby/2.3.0/gems/cocoapods-1.8.0.beta.1/lib/cocoapods/installer/analyzer.rb:972:in `resolve_dependencies'
/Users/theunodebruin/.gem/ruby/2.3.0/gems/cocoapods-1.8.0.beta.1/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/Users/theunodebruin/.gem/ruby/2.3.0/gems/cocoapods-1.8.0.beta.1/lib/cocoapods/installer.rb:410:in `analyze'
/Users/theunodebruin/.gem/ruby/2.3.0/gems/cocoapods-1.8.0.beta.1/lib/cocoapods/installer.rb:234:in `block in resolve_dependencies'
/Users/theunodebruin/.gem/ruby/2.3.0/gems/cocoapods-1.8.0.beta.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/theunodebruin/.gem/ruby/2.3.0/gems/cocoapods-1.8.0.beta.1/lib/cocoapods/installer.rb:233:in `resolve_dependencies'
/Users/theunodebruin/.gem/ruby/2.3.0/gems/cocoapods-1.8.0.beta.1/lib/cocoapods/installer.rb:156:in `install!'
/Users/theunodebruin/.gem/ruby/2.3.0/gems/cocoapods-1.8.0.beta.1/lib/cocoapods/command/install.rb:52:in `run'
/Users/theunodebruin/.gem/ruby/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/theunodebruin/.gem/ruby/2.3.0/gems/cocoapods-1.8.0.beta.1/lib/cocoapods/command.rb:52:in `run'
/Users/theunodebruin/.gem/ruby/2.3.0/gems/cocoapods-1.8.0.beta.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

**Comment by dnkoutso** [comment]
Fixed in beta 2 https://github.com/CocoaPods/Core/pull/577.

`gem install concurrent-ruby`

**Comment by sunkumar** [comment]
updated above command work for me:   sudo gem install concurrent-ruby

**Comment by junfundev** [comment]
Yes, it works. Thx.

**Comment by KarabanDev** [comment]
Thanks for reply

**Comment by realLam** [comment]
> updated above command work for me: sudo gem install concurrent-ruby

wow! It works for me! THX!

**Comment by petersam11** [comment]
It works for me! thanks

**Comment by huiying7** [comment]
> > And? How to fix?
> 
> `gem install concurrent-ruby` or `gem update concurrent-ruby`.

thanks，it works.

**Comment by AalokParikh** [comment]
> > And? How to fix?
> 
> `gem install concurrent-ruby` or `gem update concurrent-ruby`.

Thanks this worked for me too :)

**Comment by mitalskhandhar** [comment]
sudo gem install concurrent-ruby
after installing that it works for me!!
Great Thanks (Y)

**Comment by rohitpradhan** [comment]
> > And? How to fix?
> 
> `gem install concurrent-ruby` or `gem update concurrent-ruby`.

For me `sudo gem install concurrent-ruby` worked

**Comment by PareshPatel721** [comment]
Yes, it works, Thank you. You save my day.

**Comment by OhadMaor-VIA** [comment]
I had to add source 'https://github.com/CocoaPods/Specs.git' to the Podfile.
Hope that helps anyone
