### ISSUE TITLE
LoadError - cannot load such file -- cocoapods/target

### ISSUE THREAD

**Issue by koloff** [CocoaPods/CocoaPods#9011]
# Report

## What did you do?

I installed cocoapods without sudo, but set the GEM_HOME variable and the gem bin path first. When I run the the following command, I get an error: 

 ```
chmod -R 755 . && pod install
```

## What did you expect to happen?

Install all pod dependencies correctly.

### Command
 
 ```
 /build/mts/home/mts/.gem/bin/pod install
 ```
 
 
 ### Stack
 
 ```
    CocoaPods : 1.7.4
         Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin17]
     RubyGems : 2.5.2.3
         Host : Mac OS X 10.13.6 (17G65)
        Xcode : 10.0 (10A255)
          Git : git version 2.17.1 (Apple Git-112)
 Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
 Repositories : master - https://github.com/CocoaPods/Specs.git @ 809efb269e24c5af33b818a79c2e27c29333bfeb
 ```
 
 ### Plugins
 
 ```
 cocoapods-deintegrate : 1.0.4
 cocoapods-plugins     : 1.0.0
 cocoapods-search      : 1.0.0
 cocoapods-stats       : 1.1.0
 cocoapods-trunk       : 1.3.1
 cocoapods-try         : 1.1.0
 ```
 
 ### Podfile
 
 ```ruby
 # Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'
 
 target 'MyApp' do
 
   # Required by RNFirebase
   pod 'Firebase/Core', '~> 5.20.1'
   pod 'Firebase/Messaging', '~> 5.20.1'
 
 
 end
 ```
 
 ### Error
 
 ```
 LoadError - cannot load such file -- cocoapods/target
 /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
 /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
 /build/mts/home/mts/.gem/gems/cocoapods-1.7.4/lib/cocoapods/installer/analyzer.rb:585:in `block (2 levels) in generate_pod_targets'
 /build/mts/home/mts/.gem/gems/cocoapods-1.7.4/lib/cocoapods/installer/analyzer.rb:579:in `each'
 /build/mts/home/mts/.gem/gems/cocoapods-1.7.4/lib/cocoapods/installer/analyzer.rb:579:in `block in generate_pod_targets'
 /build/mts/home/mts/.gem/gems/cocoapods-1.7.4/lib/cocoapods/installer/analyzer.rb:577:in `each'
 /build/mts/home/mts/.gem/gems/cocoapods-1.7.4/lib/cocoapods/installer/analyzer.rb:577:in `each_with_object'
 /build/mts/home/mts/.gem/gems/cocoapods-1.7.4/lib/cocoapods/installer/analyzer.rb:577:in `generate_pod_targets'
 /build/mts/home/mts/.gem/gems/cocoapods-1.7.4/lib/cocoapods/installer/analyzer.rb:411:in `generate_aggregate_targets'
 /build/mts/home/mts/.gem/gems/cocoapods-1.7.4/lib/cocoapods/installer/analyzer.rb:121:in `analyze'
 /build/mts/home/mts/.gem/gems/cocoapods-1.7.4/lib/cocoapods/installer.rb:398:in `analyze'
 /build/mts/home/mts/.gem/gems/cocoapods-1.7.4/lib/cocoapods/installer.rb:221:in `block in resolve_dependencies'
 /build/mts/home/mts/.gem/gems/cocoapods-1.7.4/lib/cocoapods/user_interface.rb:64:in `section'
 /build/mts/home/mts/.gem/gems/cocoapods-1.7.4/lib/cocoapods/installer.rb:220:in `resolve_dependencies'
 /build/mts/home/mts/.gem/gems/cocoapods-1.7.4/lib/cocoapods/installer.rb:156:in `install!'
 /build/mts/home/mts/.gem/gems/cocoapods-1.7.4/lib/cocoapods/command/install.rb:51:in `run'
 /build/mts/home/mts/.gem/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
 /build/mts/home/mts/.gem/gems/cocoapods-1.7.4/lib/cocoapods/command.rb:52:in `run'
 /build/mts/home/mts/.gem/gems/cocoapods-1.7.4/bin/pod:55:in `<top (required)>'
 /build/mts/home/mts/.gem/bin/pod:22:in `load'
 /build/mts/home/mts/.gem/bin/pod:22:in `<main>'
 ```

**Comment by dnkoutso** [comment]
No idea here.
