### ISSUE TITLE
NoMethodError - undefined method `map' for nil:NilClass

### ISSUE THREAD

**Issue by evgeniybaranov** [CocoaPods/CocoaPods#9032]
# Report

## What did you do?
Run `pod install`

### Stack

```
   CocoaPods : 1.7.5
        Ruby : ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin18]
    RubyGems : 3.0.4
        Host : Mac OS X 10.14.5 (18F132)
       Xcode : 10.3 (10G8)
         Git : git version 2.7.0
Ruby lib dir : /Users/my_user_name/.rvm/rubies/ruby-2.4.2/lib
               master - https://github.com/CocoaPods/Specs.git @ df0eb49609abb9a9051fce9b4de28330f6bb9722
```

### Installation Source

```
Executable Path: /Users/my_user_name/.rvm/rubies/ruby-2.4.2/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
require 'xcodeproj'

platform :ios, '10.0'
use_modular_headers!
workspace 'App'

project './App.xcodeproj'
project './AppCore.xcodeproj'
project './AppUI.xcodeproj'
project './AppTheme.xcodeproj'


def dependencies
    pod 'App/Core', :path => 'App.podspec'
    pod 'App/UI', :path => 'App.podspec'
    pod 'App/Themes', :path => 'App.podspec'
end

target 'AppTarget' do
  project './Drugstore.xcodeproj'
  dependencies

end

target 'AppCore' do
  project './AppCore.xcodeproj'
  pod 'RealmSwift'
  
end

target 'AppUI' do
  project './AppUI.xcodeproj'
  pod 'App/Themes', :path => 'App.podspec'
  
end

target 'AppTheme' do
  project './AppTheme.xcodeproj'
  
end
```

### Error

```
NoMethodError - undefined method `map' for nil:NilClass
/Users/evgeniybaranov/.rvm/rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/cocoapods-core-1.7.5/lib/cocoapods-core/lockfile.rb:479:in `generate_dependencies_data'
/Users/evgeniybaranov/.rvm/rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/cocoapods-core-1.7.5/lib/cocoapods-core/lockfile.rb:424:in `generate'
/Users/evgeniybaranov/.rvm/rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:732:in `generate_lockfile'
/Users/evgeniybaranov/.rvm/rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:740:in `write_lockfiles'
/Users/evgeniybaranov/.rvm/rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:286:in `generate_pods_project'
/Users/evgeniybaranov/.rvm/rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:159:in `install!'
/Users/evgeniybaranov/.rvm/rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/cocoapods-1.7.5/lib/cocoapods/command/install.rb:51:in `run'
/Users/evgeniybaranov/.rvm/rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/evgeniybaranov/.rvm/rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/cocoapods-1.7.5/lib/cocoapods/command.rb:52:in `run'
/Users/evgeniybaranov/.rvm/rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/cocoapods-1.7.5/bin/pod:55:in `<top (required)>'
/Users/evgeniybaranov/.rvm/rubies/ruby-2.4.2/bin/pod:23:in `load'
/Users/evgeniybaranov/.rvm/rubies/ruby-2.4.2/bin/pod:23:in `<main>'
/Users/evgeniybaranov/.rvm/rubies/ruby-2.4.2/bin/ruby_executable_hooks:24:in `eval'
/Users/evgeniybaranov/.rvm/rubies/ruby-2.4.2/bin/ruby_executable_hooks:24:in `<main>'
```

```
Pod::Spec.new do |spec|

  # ―――  Spec Metadata  ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――― #

  spec.name           = "App"
  spec.version        = "1.0.0"
  spec.summary        = ""
  spec.homepage       = ""
  spec.license        = ""
  spec.author         = { "" => "" }
  spec.platform       = :ios, "10.0"
  spec.requires_arc         = true
  spec.source         = { :git => "my gitlab server", :branch => 'master' }
  spec.swift_version  = "5.0"

  spec.subspec 'Core' do |core|
    core.source_files         = [ 'AppCore/**/*.{h,m,swift}' ]
    core.requires_arc         = true
    core.dependency 'RealmSwift'
  end

  spec.subspec 'UI' do |ui|
    ui.source_files           = [ 'AppUI/**/*.{h,m,swift}' ]
    ui.dependency 'App/Themes'
  end

  spec.subspec 'Themes' do |themes|
    themes.source_files       = [ 'AppTheme/**/*.{h,m,swift}' ]
  end

end
```

**Comment by dnkoutso** [comment]
Need to see a sample app here. Unable to diagnose with give information.

**Comment by evgeniybaranov** [comment]
> Need to see a sample app here. Unable to diagnose with give information.

Xcode Version 10.3 (10G8)
[test_sample.zip](https://github.com/CocoaPods/CocoaPods/files/3422613/test_sample.zip)

**Comment by dnkoutso** [comment]
Wow that was an interesting one to find.

You are overriding `dependencies` method in your `Podfile` that is used by `podfile.rb` causing things to crash.

Replace:
```ruby
def dependencies
    pod 'App/Core', :path => 'App.podspec'
    pod 'App/UI', :path => 'App.podspec'
    pod 'App/Themes', :path => 'App.podspec'
end
```
with
```ruby
def project_dependencies # or some other method name
    pod 'App/Core', :path => 'App.podspec'
    pod 'App/UI', :path => 'App.podspec'
    pod 'App/Themes', :path => 'App.podspec'
end
```

And all works!

**Comment by evgeniybaranov** [comment]
thanks, now it works

**Comment by haardikdharma10** [comment]
Hi @dnkoutso, I face the same issue. Can you help me with it?
