### ISSUE TITLE
Pod Update - File rename error - macOS Catalina

### ISSUE THREAD

**Issue by AndrewEQ** [CocoaPods/CocoaPods#9052]
# Report

## What did you do?
Run `pod update`

## What did you expect to happen?

Update all pod dependencies correctly.

## What happened instead?

An error occurred:
```
### Error

Errno::EXDEV - Cross-device link @ rb_file_s_rename - (/var/folders/73/qmchj7tx5jv2d2cz2rsx3_yh0000gn/T/.atomos.project.pbxproj20190729-13707-13jqlpy, /MyApp/build/iOS/Debug/Pods/Pods.xcodeproj/project.pbxproj)
/Library/Ruby/Gems/2.6.0/gems/atomos-0.1.3/lib/atomos.rb:26:in `rename'
/Library/Ruby/Gems/2.6.0/gems/atomos-0.1.3/lib/atomos.rb:26:in `block in atomic_write'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tempfile.rb:295:in `open'
/Library/Ruby/Gems/2.6.0/gems/atomos-0.1.3/lib/atomos.rb:17:in `atomic_write'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.11.0/lib/xcodeproj/project.rb:363:in `save'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/xcode/pods_project_generator/pods_project_writer.rb:56:in `block (2 levels) in write!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/user_interface.rb:145:in `message'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/xcode/pods_project_generator/pods_project_writer.rb:42:in `block in write!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/xcode/pods_project_generator/pods_project_writer.rb:41:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/xcode/pods_project_generator/pods_project_writer.rb:41:in `write!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:313:in `block in create_and_save_projects'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:290:in `create_and_save_projects'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:281:in `generate_pods_project'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:159:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/command/update.rb:62:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

### Stack

```
   CocoaPods : 1.7.5
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15 (19A512f)
       Xcode : 11.0 (11M374r)
         Git : git version 2.21.0 (Apple Git-120)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ c32c71c839ca7fa3de6eb4d53496230fdb2cb8d8
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '9.3'

target 'MyApp' do
	use_frameworks!
	pod 'lottie-ios', '~> 2.5.3'
	pod 'UberRides', '~> 0.11'
end
```

## Project that demonstrates the issue

It's only an issue with CocoaPods the tool.

I also logged the issue here in case its more their issue: https://github.com/segiddins/atomos/issues/7

**Comment by dnkoutso** [comment]
Thanks for report. I think the segiddins/atomos#7 is sufficient.

Where in your disk folder is your CocoaPods project present? AFAIK macOS Catalina beta has been out for sometime without this issue being reported. I definitely believe its a bug but only for your case and not a widespread issue.

Going to close as we will use segiddins/atomos#7 to track it.

**Comment by dnkoutso** [comment]
Looks like the folders are here ```Errno::EXDEV - Cross-device link @ rb_file_s_rename - (/var/folders/73/qmchj7tx5jv2d2cz2rsx3_yh0000gn/T/.atomos.project.pbxproj20190729-13707-13jqlpy, /MyApp/build/iOS/Debug/Pods/Pods.xcodeproj/project.pbxproj)```

hm I still wonder how your f/s is mounted.

**Comment by AndrewEQ** [comment]
Hi there, oh, it could be because my project folder is located in the route of my Mac "/", I'll try move it to my user folder and try again.

**Comment by AndrewEQ** [comment]
Ok, it was that, all the commands work from within my user folder, I think Cocoapods or atomos didn't have permission to write there and I couldn't give it via sudo.
