### ISSUE TITLE
FrozenError - can't modify frozen String

### ISSUE THREAD

**Issue by Cpplu11** [CocoaPods/CocoaPods#9065]
I executed `Pod lib lint`, and encouterd an error below
### Error

```
FrozenError - can't modify frozen String
/Users/douyin_ios/.bundle/vendor/gems/cocoapods-1.6.1/lib/cocoapods/validator.rb:382:in `rescue in perform_extensive_analysis'
/Users/douyin_ios/.bundle/vendor/gems/cocoapods-1.6.1/lib/cocoapods/validator.rb:346:in `perform_extensive_analysis'
/Users/douyin_ios/.bundle/vendor/gems/cocoapods-1.6.1/lib/cocoapods/validator.rb:128:in `validate'
/Users/douyin_ios/.bundle/vendor/gems/cocoapods-1.6.1/lib/cocoapods/command/lib/lint.rb:75:in `block in run'
/Users/douyin_ios/.bundle/vendor/gems/cocoapods-1.6.1/lib/cocoapods/command/lib/lint.rb:60:in `each'
/Users/douyin_ios/.bundle/vendor/gems/cocoapods-1.6.1/lib/cocoapods/command/lib/lint.rb:60:in `run'
/Users/douyin_ios/.bundle/vendor/gems/cocoapods-seer-0.2.19/lib/cocoapods/seer/helper/configuration_helper.rb:123:in `run'
/Users/douyin_ios/.bundle/vendor/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/douyin_ios/.bundle/vendor/gems/cocoapods-1.6.1/lib/cocoapods/command.rb:52:in `run'
/Users/douyin_ios/.bundle/vendor/gems/cocoapods-1.6.1/bin/pod:55:in `<top (required)>'
/Users/douyin_ios/.bundle/vendor/bin/pod:29:in `load'
/Users/douyin_ios/.bundle/vendor/bin/pod:29:in `<main>'
```

So I debug `Pod lib lint`, I found the actual error isn't FrozenError, but Molinillo::CircularDependencyError.

The reason of raising FrozenError is below:
```ruby
# cocoapods/validator.rb
def perform_extensive_analysis(spec)
  # unrelated codes are omitted
rescue => e
  message = e.to_s
  message << "\n" << e.backtrace.join("\n") << "\n" if config.verbose?
  error('unknown', "Encountered an unknown error (#{message}) during validation.")
  false
end
```
`message` is Frozen，so modification of `message` is not allowed.
Variable `e` is a Pod::Informative instance, because Molinillo-releated errors are handled to `Pod::Informative` in `Resolver::handle_resolver_error` methods with its original message and backtrace.
```ruby
# cocoapods/resolver.rb
 def handle_resolver_error(error)
      message = error.message
      type = Informative
     # omited
      raise type.new(message).tap { |e| e.set_backtrace(error.backtrace) }
end

In `molinillo/errors.rb` file, all strings are literal because a magic comment declaration below
```ruby
# frozen_string_literal: true
```

so FrozenError is raised, that's what I guessed. I hope you can check whether it is a problem?

`raise type.new(message).tap { |e| e.set_backtrace(error.backtrace) }` changed to 
`raise type.new(message.dup).tap { |e| e.set_backtrace(error.backtrace) }` is OK?

**Comment by dnkoutso** [comment]
Sounds good! Want to make a PR? can you include a test to prove the error?

**Comment by Cpplu11** [comment]
the problem code is
```ruby
  message << "\n" << e.backtrace.join("\n") << "\n" if config.verbose?
```
so the problem occurred when verbose is open

I create a simple pod project using `pod lib create AWETest`, below is AWETest.podspec
```ruby
Pod::Spec.new do |s|
  # omited code
  s.subspec 'sub1' do |ss|
    ss.dependency 'AWETest/sub2'
  end

  s.subspec 'sub2' do |ss|
    ss.dependency 'AWETest/sub1'
  end
end
```
The actual problem is `a circular dependency between AWETest/sub2 and AWETest/sub1`, but when I executed `pod lib lint AWETest.podspec --verbose`, `FrozenError` occured

```
FrozenError - can't modify frozen String
/Users/cppluwang/.rvm/gems/ruby-2.5.0/gems/cocoapods-1.7.5/lib/cocoapods/validator.rb:400:in `rescue in perform_extensive_analysis'
/Users/cppluwang/.rvm/gems/ruby-2.5.0/gems/cocoapods-1.7.5/lib/cocoapods/validator.rb:364:in `perform_extensive_analysis'
/Users/cppluwang/.rvm/gems/ruby-2.5.0/gems/cocoapods-1.7.5/lib/cocoapods/validator.rb:128:in `validate'
/Users/cppluwang/.rvm/gems/ruby-2.5.0/gems/cocoapods-1.7.5/lib/cocoapods/command/lib/lint.rb:86:in `block in run'
/Users/cppluwang/.rvm/gems/ruby-2.5.0/gems/cocoapods-1.7.5/lib/cocoapods/command/lib/lint.rb:69:in `each'
/Users/cppluwang/.rvm/gems/ruby-2.5.0/gems/cocoapods-1.7.5/lib/cocoapods/command/lib/lint.rb:69:in `run'
/Users/cppluwang/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
```
suggested changes:
```ruby
# cocoapods/resolver.rb
raise type.new(message.dup).tap { |e| e.set_backtrace(error.backtrace) } 
```

**Comment by dnkoutso** [comment]
<img width="846" alt="Screen Shot 2019-07-31 at 7 50 20 PM" src="https://user-images.githubusercontent.com/310370/62255735-7a6a5500-b3cc-11e9-8cb2-fa0461fd9635.png">

I am not getting the crash as you do.

**Comment by goodswifter** [comment]
I have encountered the same problem as you, and I solved it in this way! Add this line of code to the podspec file, and you're done.
`s.platform     	= :ios, "9.0"`

**Comment by Whirlwind** [comment]
I have a same crash. I don't care the molinillo error, but the crash make us could not find the reason.
