### ISSUE TITLE
install crash when enable cdn

### ISSUE THREAD

**Issue by miku1958** [CocoaPods/CocoaPods#9090]
### Command

```
/usr/local/Cellar/cocoapods/1.7.5/libexec/bin/pod install
```

### Report

* What did you do?
pod install

* What did you expect to happen?
install success with cdn

* What happened instead?
crash

### Stack

```
   CocoaPods : 1.7.5
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.7.7
        Host : Mac OS X 10.14.5 (18F203)
       Xcode : 11.0 (11M382q)
         Git : git version 2.21.0 (Apple Git-122)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : 
               lazyprivatepods - git@gitlab.lrts.me:lazyaudio-ios/lazyprivatepods.git @ 9b166a4f0b64005012896d1b7a0f581dc1ddc9c7
               lrts-lazyprivatepods - git@gitlab.lrts.me:lazyaudio-ios/lazyprivatepods.git @ 9b166a4f0b64005012896d1b7a0f581dc1ddc9c7
               master - https://github.com/CocoaPods/Specs.git @ f71c0add8ea1046051df4be9a2f9a52f51ed4558
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://cdn.jsdelivr.net/cocoa/'

target 'bilidanmu' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'HandyJSON'
	pod "SwiftyXMLParser"
	pod 'WCDB.swift'
end
```

### Error

```
Errno::ENOENT - No such file or directory @ rb_sysopen - /Users/mikun/.cocoapods/repos/jsdelivr-cocoa/all_pods_versions_f_3_4.txt
/usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-core-1.7.5/lib/cocoapods-core/cdn_source.rb:276:in `initialize'
/usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-core-1.7.5/lib/cocoapods-core/cdn_source.rb:276:in `open'
/usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-core-1.7.5/lib/cocoapods-core/cdn_source.rb:276:in `local_file'
/usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-core-1.7.5/lib/cocoapods-core/cdn_source.rb:253:in `ensure_versions_file_loaded'
/usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-core-1.7.5/lib/cocoapods-core/cdn_source.rb:187:in `search'
/usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-core-1.7.5/lib/cocoapods-core/source/aggregate.rb:83:in `block in search'
/usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-core-1.7.5/lib/cocoapods-core/source/aggregate.rb:83:in `select'
/usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-core-1.7.5/lib/cocoapods-core/source/aggregate.rb:83:in `search'
/usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/resolver.rb:389:in `create_set_from_sources'
/usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/resolver.rb:358:in `find_cached_set'
/usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/resolver.rb:332:in `specifications_for_dependency'
/usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/resolver.rb:139:in `search_for'
/usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/resolver.rb:248:in `block in sort_dependencies'
/usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/resolver.rb:241:in `each'
/usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/resolver.rb:241:in `sort_by'
/usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/resolver.rb:241:in `sort_dependencies'
/usr/local/Cellar/cocoapods/1.7.5/libexec/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:53:in `block in sort_dependencies'
/usr/local/Cellar/cocoapods/1.7.5/libexec/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:70:in `with_no_such_dependency_error_handling'
/usr/local/Cellar/cocoapods/1.7.5/libexec/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:52:in `sort_dependencies'
/usr/local/Cellar/cocoapods/1.7.5/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:288:in `initial_state'
/usr/local/Cellar/cocoapods/1.7.5/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:210:in `start_resolution'
/usr/local/Cellar/cocoapods/1.7.5/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:168:in `resolve'
/usr/local/Cellar/cocoapods/1.7.5/libexec/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
/usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/resolver.rb:88:in `resolve'
/usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/installer/analyzer.rb:939:in `block in resolve_dependencies'
/usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/installer/analyzer.rb:937:in `resolve_dependencies'
/usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/installer/analyzer.rb:118:in `analyze'
/usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:398:in `analyze'
/usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:221:in `block in resolve_dependencies'
/usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:220:in `resolve_dependencies'
/usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:156:in `install!'
/usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/command/install.rb:51:in `run'
/usr/local/Cellar/cocoapods/1.7.5/libexec/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/command.rb:52:in `run'
/usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/bin/pod:55:in `<top (required)>'
/usr/local/Cellar/cocoapods/1.7.5/libexec/bin/pod:22:in `load'
/usr/local/Cellar/cocoapods/1.7.5/libexec/bin/pod:22:in `<main>'
```

**Comment by dnkoutso** [comment]
Change `source 'https://cdn.jsdelivr.net/cocoa/'` to `source 'https://cdn.cocoapods.org/'`

More here http://blog.cocoapods.org/CocoaPods-1.7.2/

Going to close pre-emptively.
