### ISSUE TITLE
Pods installing for React Native project

### ISSUE THREAD

**Issue by ptaberg** [CocoaPods/CocoaPods#9118]
### Command

```
/usr/local/bin/pod install
```

### Report

* I have a React Native project and I run the command `cd ios && pod install`

* I expect to install all Pods

* But I get the error

### Stack

```
   CocoaPods : 1.7.5
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.5 (18F132)
       Xcode : 10.3 (10G8)
         Git : git version 2.20.1 (Apple Git-117)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 765f118d3098a5ec24bc231c14ad271ff8776b68
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
install! 'cocoapods', :deterministic_uuids => false

platform :ios, '10.0'

target 'HelloHabit' do
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'RCTAnimation',
    'RCTBlob',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket',
    'DevSupport',
  ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'react-native-in-app-utils', :podspec => '../node_modules/react-native-in-app-utils/react-native-in-app-utils.podspec'
  pod 'react-native-date-picker', :podspec => '../node_modules/react-native-date-picker/react-native-date-picker.podspec'
  pod 'RNFastImage', :podspec => '../node_modules/react-native-fast-image/RNFastImage.podspec'
  pod 'ReactNativeNavigation', :podspec => '../node_modules/react-native-navigation/ReactNativeNavigation.podspec'
  pod 'RNGestureHandler', :podspec => '../node_modules/react-native-gesture-handler/RNGestureHandler.podspec'
  pod 'RNReanimated', :podspec => '../node_modules/react-native-reanimated/RNReanimated.podspec'
  pod 'Interactable', :podspec => '../node_modules/react-native-interactable/Interactable.podspec'
  pod 'RNKeychain', :podspec => '../node_modules/react-native-keychain/RNKeychain.podspec'
  pod 'RNSVG', :podspec => '../node_modules/react-native-svg/RNSVG.podspec'
  pod 'RNFS', :podspec => '../node_modules/react-native-fs/RNFS.podspec'
  pod 'react-native-image-picker', :podspec => '../node_modules/react-native-image-picker/react-native-image-picker.podspec'
  pod 'react-native-slider', :podspec => '../node_modules/@react-native-community/slider/react-native-slider.podspec'

  pod 'SentryReactNative', :podspec => '../node_modules/react-native-sentry/SentryReactNative.podspec'

  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'

end

post_install do |installer|
  # Disable some shitty RN stuff (I can't see degradation in functional)
  installer.pods_project.targets.each do |target|
    targets_to_ignore = %w(React yoga)
    if targets_to_ignore.include? target.name        
      target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'RCT_ENABLE_INSPECTOR=0'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'ENABLE_PACKAGER_CONNECTION=0'
      end
      target.remove_from_project
    end
  end
end
```

### Error

```
Errno::ENOENT - No such file or directory @ rb_sysopen - /Users/nikolaj/Documents/HelloHabit/node_modules/react-native-fast-image/RNFastImage.podspec
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/open-uri.rb:37:in `initialize'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/open-uri.rb:37:in `open'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/open-uri.rb:37:in `open'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/external_sources/podspec_source.rb:19:in `block in fetch'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/user_interface.rb:86:in `titled_section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/external_sources/podspec_source.rb:11:in `fetch'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/analyzer.rb:854:in `fetch_external_source'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/analyzer.rb:833:in `block (2 levels) in fetch_external_sources'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/analyzer.rb:832:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/analyzer.rb:832:in `block in fetch_external_sources'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/analyzer.rb:831:in `fetch_external_sources'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/analyzer.rb:111:in `analyze'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:398:in `analyze'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:221:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:220:in `resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:156:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/command/install.rb:51:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

**Comment by dnkoutso** [comment]
This file is missing `Errno::ENOENT - No such file or directory @ rb_sysopen - /Users/nikolaj/Documents/HelloHabit/node_modules/react-native-fast-image/RNFastImage.podspec
`
as the error message clearly says.

This seems like a project configuration issue maybe you're missing a step in react native setup. I recommend posting this there or in StackOverflow.

This does not appear to be a CocoaPods library issue.
