### ISSUE TITLE
Errno::ENOENT - No such file or directory @ rb_sysopen

### ISSUE THREAD

**Issue by 463292462** [CocoaPods/CocoaPods#9183]
### Command

```
/usr/local/lib/ruby/gems/2.6.0/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.6.4p104 (2019-08-28 revision 67798) [x86_64-darwin18]
    RubyGems : 3.0.3
        Host : Mac OS X 10.14.5 (18F132)
       Xcode : 11.0 (11A420a)
         Git : git version 2.21.0 (Apple Git-122)
Ruby lib dir : /usr/local/Cellar/ruby/2.6.4_2/lib
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.0
cocoapods-try         : 1.1.0
slather               : 2.4.7
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

plugin 'slather'

use_frameworks!
...
end
```

### Error

```
Errno::ENOENT - No such file or directory @ rb_sysopen - /Users/yangwei/Documents/pro/Pods/Pods.xcodeproj/xcshareddata/xcschemes/Pods.xcscheme
/usr/local/lib/ruby/gems/2.6.0/gems/xcodeproj-1.7.0/lib/xcodeproj/scheme.rb:34:in `initialize'
/usr/local/lib/ruby/gems/2.6.0/gems/xcodeproj-1.7.0/lib/xcodeproj/scheme.rb:34:in `new'
/usr/local/lib/ruby/gems/2.6.0/gems/xcodeproj-1.7.0/lib/xcodeproj/scheme.rb:34:in `initialize'
/usr/local/lib/ruby/gems/2.6.0/gems/slather-2.4.7/lib/slather/project.rb:33:in `new'
/usr/local/lib/ruby/gems/2.6.0/gems/slather-2.4.7/lib/slather/project.rb:33:in `block in slather_setup_for_coverage'
/usr/local/lib/ruby/gems/2.6.0/gems/slather-2.4.7/lib/slather/project.rb:31:in `each'
/usr/local/lib/ruby/gems/2.6.0/gems/slather-2.4.7/lib/slather/project.rb:31:in `slather_setup_for_coverage'
/usr/local/lib/ruby/gems/2.6.0/gems/slather-2.4.7/lib/cocoapods_plugin.rb:7:in `block in <top (required)>'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.5.3/lib/cocoapods/hooks_manager.rb:111:in `block (3 levels) in run'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:142:in `message'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.5.3/lib/cocoapods/hooks_manager.rb:103:in `block (2 levels) in run'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.5.3/lib/cocoapods/hooks_manager.rb:101:in `each'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.5.3/lib/cocoapods/hooks_manager.rb:101:in `block in run'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:142:in `message'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.5.3/lib/cocoapods/hooks_manager.rb:100:in `run'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:455:in `run_plugins_post_install_hooks'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:433:in `perform_post_install_actions'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:125:in `install!'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.5.3/lib/cocoapods/command/install.rb:41:in `run'
/usr/local/lib/ruby/gems/2.6.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
/usr/local/lib/ruby/gems/2.6.0/bin/pod:23:in `load'
/usr/local/lib/ruby/gems/2.6.0/bin/pod:23:in `<top (required)>'
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-1.17.1/lib/bundler/cli/exec.rb:74:in `load'
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-1.17.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-1.17.1/lib/bundler/cli/exec.rb:28:in `run'
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-1.17.1/lib/bundler/cli.rb:463:in `exec'
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-1.17.1/lib/bundler/cli.rb:27:in `dispatch'
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-1.17.1/lib/bundler/cli.rb:18:in `start'
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-1.17.1/exe/bundle:30:in `block in <top (required)>'
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-1.17.1/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-1.17.1/exe/bundle:22:in `<top (required)>'
/usr/local/opt/ruby/bin/bundle:23:in `load'
/usr/local/opt/ruby/bin/bundle:23:in `<main>'
```

**Comment by dnkoutso** [comment]
Please update to cocoapods 1.7.x or 1.8.x.

There is not enough information to diagnose this issue. I will re-open it once you upload a sample app or repo that helps show the issue.

**Comment by 463292462** [comment]
in Gemfile
'''
source "https://rubygems.org"
gem 'cocoapods'
gem "fastlane"
gem 'slather'
'''
in Podfile add  plugin 'slather' and then execute bundle exec pod install i have above problem
