### ISSUE TITLE
error when running pod install

### ISSUE THREAD

**Issue by azaz0133** [CocoaPods/CocoaPods#9195]
`CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Finding Podfile changes
      A cipher2
      A imei_plugin
      A local_auth
      A permission_handler
      A qrcode
      A shared_preferences
      A simple_rsa
      A url_launcher
      - Flutter
      - firebase_messaging

    Fetching external sources
    -> Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
    -> Fetching podspec for `cipher2` from `.symlinks/plugins/cipher2/ios`

    ――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

    ### Command

    ```
    /usr/local/Cellar/cocoapods/1.7.5/libexec/bin/pod install --verbose
    ```

    ### Report

    * What did you do?

    * What did you expect to happen?

    * What happened instead?

    ### Stack

    ```
       CocoaPods : 1.7.5
            Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
        RubyGems : 2.5.2.3
            Host : Mac OS X 10.14.6 (18G95)
           Xcode : 10.3 (10G8)
             Git : git version 2.23.0
    Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
    Repositories : master - https://github.com/CocoaPods/Specs.git @ 7107e9c359787dd6e8f579a6385cf998cf7cb363
    ```

    ### Plugins

    ```
    cocoapods-deintegrate : 1.0.4
    cocoapods-plugins     : 1.0.0
    cocoapods-search      : 1.0.0
    cocoapods-stats       : 1.1.0
    cocoapods-trunk       : 1.3.1
    cocoapods-try         : 1.1.0
    ```

    ### Podfile

    ```ruby
    # Using a CDN with CocoaPods 1.7.2 or later can save a lot of time on pod installation, but it's experimental rather than the default.
    # source 'https://cdn.cocoapods.org/'

    # Uncomment this line to define a global platform for your project
    platform :ios, '8.0'

    # use_frameworks!
    # CocoaPods analytics sends network stats synchronously affecting flutter build latency.
    ENV['COCOAPODS_DISABLE_STATS'] = 'true'

    project 'Runner', {
      'Debug' => :debug,
      'Profile' => :release,
      'Release' => :release,
    }

    def parse_KV_file(file, separator='=')
      file_abs_path = File.expand_path(file)
      if !File.exists? file_abs_path
        return [];
      end
      pods_ary = []
      skip_line_start_symbols = ["#", "/"]
      File.foreach(file_abs_path) { |line|
          next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
          plugin = line.split(pattern=separator)
          if plugin.length == 2
            podname = plugin[0].strip()
            path = plugin[1].strip()
            podpath = File.expand_path("#{path}", file_abs_path)
            pods_ary.push({:name => podname, :path => podpath});
          else
            puts "Invalid plugin specification: #{line}"
          end
      }
      return pods_ary
    end

    target 'Runner' do
      # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
      # referring to absolute paths on developers' machines.
      system('rm -rf .symlinks')
      system('mkdir -p .symlinks/plugins')

      # Flutter Pods
      generated_xcode_build_settings = parse_KV_file('./Flutter/Generated.xcconfig')
      if generated_xcode_build_settings.empty?
        puts "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter pub get is executed first."
      end
      generated_xcode_build_settings.map { |p|
        if p[:name] == 'FLUTTER_FRAMEWORK_DIR'
          symlink = File.join('.symlinks', 'flutter')
          File.symlink(File.dirname(p[:path]), symlink)
          pod 'Flutter', :path => File.join(symlink, File.basename(p[:path]))
        end
      }

      # Plugin Pods
      plugin_pods = parse_KV_file('../.flutter-plugins')
      plugin_pods.map { |p|
        symlink = File.join('.symlinks', 'plugins', p[:name])
        File.symlink(p[:path], symlink)
        pod p[:name], :path => File.join(symlink, 'ios')
      }
    end

    # Prevent CocoaPods from embedding a second Flutter framework and causing an error with the new Xcode build system.
    install! 'cocoapods', :disable_input_output_paths => true

    post_install do |installer|
      installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
      end
    end
    ```

    ### Error

    ```
    ArgumentError - Malformed version number string *
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-core-1.7.5/lib/cocoapods-core/version.rb:47:in `initialize'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-core-1.7.5/lib/cocoapods-core/vendor/version.rb:199:in `new'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-core-1.7.5/lib/cocoapods-core/vendor/version.rb:199:in `new'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-core-1.7.5/lib/cocoapods-core/vendor/version.rb:192:in `create'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-core-1.7.5/lib/cocoapods-core/platform.rb:50:in `initialize'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-core-1.7.5/lib/cocoapods-core/specification.rb:476:in `new'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-core-1.7.5/lib/cocoapods-core/specification.rb:476:in `block in available_platforms'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-core-1.7.5/lib/cocoapods-core/specification.rb:476:in `map'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-core-1.7.5/lib/cocoapods-core/specification.rb:476:in `available_platforms'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-core-1.7.5/lib/cocoapods-core/specification.rb:386:in `dependencies'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/validator.rb:43:in `initialize'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/external_sources/abstract_external_source.rb:201:in `new'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/external_sources/abstract_external_source.rb:201:in
    `validator_for_podspec'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/external_sources/abstract_external_source.rb:186:in
    `validate_podspec'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/external_sources/abstract_external_source.rb:178:in
    `store_podspec'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/external_sources/path_source.rb:17:in `block in fetch'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/user_interface.rb:86:in `titled_section'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/external_sources/path_source.rb:11:in `fetch'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/installer/analyzer.rb:854:in `fetch_external_source'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/installer/analyzer.rb:833:in `block (2 levels) in
    fetch_external_sources'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/installer/analyzer.rb:832:in `each'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/installer/analyzer.rb:832:in `block in fetch_external_sources'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/user_interface.rb:64:in `section'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/installer/analyzer.rb:831:in `fetch_external_sources'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/installer/analyzer.rb:111:in `analyze'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:398:in `analyze'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:221:in `block in resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/user_interface.rb:64:in `section'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:220:in `resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:156:in `install!'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/command/install.rb:51:in `run'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/command.rb:52:in `run'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/bin/pod:55:in `<top (required)>'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/bin/pod:22:in `load'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/bin/pod:22:in `<main>'
    ```

    ――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

    [!] Oh no, an error occurred.

    Search for existing GitHub issues similar to yours:
    https://github.com/CocoaPods/CocoaPods/search?q=Malformed+version+number+string+%2A&type=Issues

    If none exists, create a ticket, with the template displayed above, on:
    https://github.com/CocoaPods/CocoaPods/issues/new

    Be sure to first read the contributing guide for details on how to properly submit a ticket:
    https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

    Don't forget to anonymize any private data!

    Looking for related issues on cocoapods/cocoapods...
     - Malformed version number string
       https://github.com/CocoaPods/CocoaPods/issues/7765 [closed] [47 comments]
       4 weeks ago

     - Malformed version number string {VER}
       https://github.com/CocoaPods/CocoaPods/issues/8785 [closed] [2 comments]
       02 Jul 2019

     - - ERROR | [iOS] unknown: Encountered an unknown error (Malformed version number string ) during validation.
       https://github.com/CocoaPods/CocoaPods/issues/8240 [closed] [19 comments]
       24 May 2019

    and 40 more at:
    https://github.com/cocoapods/cocoapods/search?q=Malformed%20version%20number%20string%20%2A&type=Issues&utf8=✓

Error running pod install
Error launching application on iPhone Xʀ.`

**Comment by dnkoutso** [comment]
Need a sample app to diagnose this.

**Comment by azaz0133** [comment]
> Need a sample app to diagnose this.

this application made from flutter

**Comment by dnkoutso** [comment]
Yes please upload a sample app showing the issue.
