### ISSUE TITLE
Errno::ENOENT - No such file or directory @ rb_sysopen

### ISSUE THREAD

**Issue by byerman** [CocoaPods/CocoaPods#9203]
when i  use a flutter plugin int my flutter project 
the project can run in android 
but in ios
i get the error 
`Errno::ENOENT - No such file or directory @ rb_sysopen - /Users/apple/code/IH_MT/ihmt/ios/Pods/Local Podspecs/fijkplayer.podspec.json`

i answer the plugin author,he said he can't found the error
so i think maybe it's my environment make the mistake

this is my complete logs：

### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.8.1
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.5 (18F132)
       Xcode : 10.3 (10G8)
         Git : git version 2.20.1 (Apple Git-117)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ a4132a4e9de23c1ba0ffe9265bd5c3e23939edbd
               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
  platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def parse_KV_file(file, separator='=')
  file_abs_path = File.expand_path(file)
  if !File.exists? file_abs_path
    return [];
  end
  pods_ary = []
  skip_line_start_symbols = ["#", "/"]
  File.foreach(file_abs_path) { |line|
      next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
      plugin = line.split(pattern=separator)
      if plugin.length == 2
        podname = plugin[0].strip()
        path = plugin[1].strip()
        podpath = File.expand_path("#{path}", file_abs_path)
        pods_ary.push({:name => podname, :path => podpath});
      else
        puts "Invalid plugin specification: #{line}"
      end
  }
  return pods_ary
end

target 'Runner' do
  use_frameworks!

  # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
  # referring to absolute paths on developers' machines.
  system('rm -rf .symlinks')
  system('mkdir -p .symlinks/plugins')

  # Flutter Pods
  generated_xcode_build_settings = parse_KV_file('./Flutter/Generated.xcconfig')
  if generated_xcode_build_settings.empty?
    puts "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter pub get is executed first."
  end
  generated_xcode_build_settings.map { |p|
    if p[:name] == 'FLUTTER_FRAMEWORK_DIR'
      symlink = File.join('.symlinks', 'flutter')
      File.symlink(File.dirname(p[:path]), symlink)
      pod 'Flutter', :path => File.join(symlink, File.basename(p[:path]))
    end
  }

  # Plugin Pods
  plugin_pods = parse_KV_file('../.flutter-plugins')
  plugin_pods.map { |p|
    symlink = File.join('.symlinks', 'plugins', p[:name])
    File.symlink(p[:path], symlink)
    pod p[:name], :path => File.join(symlink, 'ios')
  }
end

# Prevent CocoaPods from embedding a second Flutter framework and causing an error with the new Xcode build system.
install! 'cocoapods', :disable_input_output_paths => true

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
```

### Error

```
Errno::ENOENT - No such file or directory @ rb_sysopen - /Users/apple/code/IH_MT/ihmt/ios/Pods/Local Podspecs/fijkplayer.podspec.json
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.8.1/lib/cocoapods-core/specification.rb:646:in `read'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.8.1/lib/cocoapods-core/specification.rb:646:in `checksum'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.8.1/lib/cocoapods-core/lockfile.rb:533:in `block in generate_checksums'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.8.1/lib/cocoapods-core/lockfile.rb:532:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.8.1/lib/cocoapods-core/lockfile.rb:532:in `generate_checksums'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.8.1/lib/cocoapods-core/lockfile.rb:428:in `generate'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.1/lib/cocoapods/installer.rb:744:in `generate_lockfile'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.1/lib/cocoapods/installer.rb:752:in `write_lockfiles'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.1/lib/cocoapods/installer.rb:299:in `generate_pods_project'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.1/lib/cocoapods/installer.rb:173:in `integrate'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.1/lib/cocoapods/installer.rb:162:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.1/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

**Comment by dnkoutso** [comment]
Need a small sample app that reproduces the issue. This is hard for us to diagnose. Please upload one.

**Comment by mikehaney24** [comment]
For me, it's occurring when I add a dependency to my pod's app_spec.

Removing the line `app_spec.dependency 'SwiftProtobuf'` from `GoogleDataTransportCCTSupport.podspec` resolves the issue.

```
git clone -b mph-cocoapodsdepissue https://github.com/firebase/firebase-ios-sdk.git
cd firebase-ios-sdk
GDT_DEV=1 pod gen GoogleDataTransportCCTSupport.podspec --auto-open --gen-directory=gen --local-sources=. --clean
```

should cause a bug report looking like

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/haneym/.rbenv/versions/2.5.3/bin/pod gen GoogleDataTransportCCTSupport.podspec --auto-open --gen-directory=gen --local-sources=. --clean
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.8.1
        Ruby : ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin18]
    RubyGems : 3.0.4
        Host : Mac OS X 10.14.6 (18G95)
       Xcode : 11.0 (11A420a)
         Git : git version 2.19.0.605.g01d371f741-goog
Ruby lib dir : /Users/haneym/.rbenv/versions/2.5.3/lib
Repositories : cocoapods - git - https://github.com/Cocoapods/Cocoapods.git @ f27e39ef9738ab5cc163534b9a52226439131280
               cocoapods- - CDN - https://cdn.cocoapods.org/
               cpdc-internal - git - sso://cpdc-internal/firebase.git @ 683b0cd627cddb837102c177cc9213e79a143a06
               cpdc-internal-firebase - git - sso://cpdc-internal/firebase @ 683b0cd627cddb837102c177cc9213e79a143a06
               cpdc-internal-firebase-1 - git - /Users/haneym/.cocoapods/repos/cpdc-internal-firebase @ 683b0cd627cddb837102c177cc9213e79a143a06
               cpdc-internal-spec - git - sso://cpdc-internal/spec @ 6947d1cb677869dd00f220b46f2346f425eb7d78
               firebase - git - https://github.com/Firebase/SpecsStaging.git @ 875f4e47d3c5213cf32d31972f22531aa9195366
               jsdelivr-cocoa - CDN - https://cdn.jsdelivr.net/cocoa/
               master - git - https://github.com/CocoaPods/Specs.git @ 30bdeef4050debfc3a570ae83ed689a5abd1077a
               SpecsStaging - git - git@github.com:firebase/SpecsStaging.git @ f9b0a467a5d03d8a6fb829640efa60fbd5c6177b
```

### Plugins

```
cocoapods-deintegrate                 : 1.0.4
cocoapods-dependencies                : 1.3.0
cocoapods-disable-podfile-validations : 0.1.1
cocoapods-generate                    : 1.6.0
cocoapods-plugins                     : 1.0.0
cocoapods-rome                        : 1.0.1
cocoapods-search                      : 1.0.0
cocoapods-stats                       : 1.1.0
cocoapods-trunk                       : 1.4.0
cocoapods-try                         : 1.1.0
```

### Error

```
Errno::ENOENT - No such file or directory @ rb_sysopen - /Users/haneym/.cocoapods/repos/jsdelivr-cocoa/all_pods_versions_4_a_9.txt
/Users/haneym/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.8.1/lib/cocoapods-core/cdn_source.rb:316:in `initialize'
/Users/haneym/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.8.1/lib/cocoapods-core/cdn_source.rb:316:in `open'
/Users/haneym/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.8.1/lib/cocoapods-core/cdn_source.rb:316:in `local_file'
/Users/haneym/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.8.1/lib/cocoapods-core/cdn_source.rb:281:in `ensure_versions_file_loaded'
/Users/haneym/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.8.1/lib/cocoapods-core/cdn_source.rb:204:in `search'
/Users/haneym/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.8.1/lib/cocoapods-core/source/aggregate.rb:83:in `block in search'
/Users/haneym/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.8.1/lib/cocoapods-core/source/aggregate.rb:83:in `select'
/Users/haneym/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.8.1/lib/cocoapods-core/source/aggregate.rb:83:in `search'
/Users/haneym/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-1.8.1/lib/cocoapods/resolver.rb:416:in `create_set_from_sources'
/Users/haneym/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-1.8.1/lib/cocoapods/resolver.rb:385:in `find_cached_set'
/Users/haneym/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-1.8.1/lib/cocoapods/resolver.rb:360:in `specifications_for_dependency'
/Users/haneym/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-1.8.1/lib/cocoapods/resolver.rb:165:in `search_for'
/Users/haneym/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-1.8.1/lib/cocoapods/resolver.rb:274:in `block in sort_dependencies'
/Users/haneym/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-1.8.1/lib/cocoapods/resolver.rb:267:in `each'
/Users/haneym/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-1.8.1/lib/cocoapods/resolver.rb:267:in `sort_by'
/Users/haneym/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-1.8.1/lib/cocoapods/resolver.rb:267:in `sort_dependencies'
/Users/haneym/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:53:in `block in sort_dependencies'
/Users/haneym/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:70:in `with_no_such_dependency_error_handling'
/Users/haneym/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:52:in `sort_dependencies'
/Users/haneym/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:754:in `push_state_for_requirements'
/Users/haneym/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:746:in `require_nested_dependencies_for'
/Users/haneym/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:729:in `activate_new_spec'
/Users/haneym/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:686:in `attempt_to_activate'
/Users/haneym/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:254:in `process_topmost_state'
/Users/haneym/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
/Users/haneym/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
/Users/haneym/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-1.8.1/lib/cocoapods/resolver.rb:94:in `resolve'
/Users/haneym/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-1.8.1/lib/cocoapods/installer/analyzer.rb:986:in `block in resolve_dependencies'
/Users/haneym/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-1.8.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/haneym/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-1.8.1/lib/cocoapods/installer/analyzer.rb:984:in `resolve_dependencies'
/Users/haneym/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-1.8.1/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/Users/haneym/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-1.8.1/lib/cocoapods/installer.rb:410:in `analyze'
/Users/haneym/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-1.8.1/lib/cocoapods/installer.rb:234:in `block in resolve_dependencies'
/Users/haneym/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-1.8.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/haneym/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-1.8.1/lib/cocoapods/installer.rb:233:in `resolve_dependencies'
/Users/haneym/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-1.8.1/lib/cocoapods/installer.rb:156:in `install!'
/Users/haneym/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-generate-1.6.0/lib/cocoapods/generate/installer.rb:57:in `block (3 levels) in install!'
/Users/haneym/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-1.8.1/lib/cocoapods/config.rb:41:in `with_changes'
/Users/haneym/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-generate-1.6.0/lib/cocoapods/generate/installer.rb:54:in `block (2 levels) in install!'
/Users/haneym/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-1.8.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/haneym/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-generate-1.6.0/lib/cocoapods/generate/installer.rb:53:in `block in install!'
/Users/haneym/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-1.8.1/lib/cocoapods/user_interface.rb:118:in `title'
/Users/haneym/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-generate-1.6.0/lib/cocoapods/generate/installer.rb:40:in `install!'
/Users/haneym/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-generate-1.6.0/lib/cocoapods/command/gen.rb:68:in `block in run'
/Users/haneym/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-generate-1.6.0/lib/cocoapods/command/gen.rb:67:in `each'
/Users/haneym/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-generate-1.6.0/lib/cocoapods/command/gen.rb:67:in `run'
/Users/haneym/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/haneym/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-1.8.1/lib/cocoapods/command.rb:52:in `run'
/Users/haneym/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cocoapods-1.8.1/bin/pod:55:in `<top (required)>'
/Users/haneym/.rbenv/versions/2.5.3/bin/pod:23:in `load'
/Users/haneym/.rbenv/versions/2.5.3/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=No+such+file+or+directory+%40+rb_sysopen+-+%2FUsers%2Fhaneym%2F.cocoapods%2Frepos%2Fjsdelivr-cocoa%2Fall_pods_versions_4_a_9.txt&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Found no similar issues. To create a new issue, please visit:
https://github.com/cocoapods/cocoapods/issues/new

[!] Automatically assigning platform `iOS` with version `8.0` on target `App-iOS` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

[!] Automatically assigning platform `macOS` with version `10.11` on target `App-macOS` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

[!] Automatically assigning platform `tvOS` with version `10.0` on target `App-tvOS` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

**Comment by mikehaney24** [comment]
Removing the `jsdelivr-cocoa` repo from `~/.cocoapods/repo` fixes the issue for me.

**Comment by dnkoutso** [comment]
Yes that was the old CDN repo from 1.7.0 to 1.7.2.
