### ISSUE TITLE
Pod install command failed in some case when I use 'cocoapods-binary' plugin or not.

### ISSUE THREAD

**Issue by meccatol** [CocoaPods/CocoaPods#9206]
* [v] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I want to the binary built framework to breakdown bottleneck of project building time.
So I found 'cocoapods-binary' in this article.
<https://guides.cocoapods.org/plugins/pre-compiling-dependencies.html>

I installed a gem 'cocoapods-binary' and added an option ':binary => true' to the pod where I need not source code but the binary framework.

for examples,

```
platform :ios, "10.0"
plugin 'cocoapods-binary'
use_frameworks!
keep_source_code_for_prebuilt_frameworks!

 target 'Project' do
    pod 'SomePod', :binary => true
end
```

That's it. I succeeded to build and run in the simulator and device.

## What did you expect to happen?

After that I've done before, I switched context to another branch because I should do other things at the same time.

However, that branch's Podfile don't have 'plugin 'cocoapods-binary'' and ':binary' options.

When I run a ```pod install``` commend, It's always failed.

## What happened instead?

```pod install``` should be a success although Podfile has a history of using 'cocoapods-binary' plugin.

It's a problem that the command failed when we changed context whatever it has a binary framework.

### Stack

```
   CocoaPods : 1.8.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]
    RubyGems : 3.0.4
        Host : Mac OS X 10.14.6 (18G95)
       Xcode : 11.0 (11A420a)
         Git : git version 2.21.0 (Apple Git-122)
Ruby lib dir : ~/.rvm/rubies/ruby-2.6.3/lib
Repositories : 
master - git - https://github.com/CocoaPods/Specs.git @ 6d8364c88e23afbad6dcbc589888ec13e0fd4116
               
private-pod-repo- git - ...
```

### Installation Source

```
Executable Path: ~/.rvm/gems/ruby-2.6.3/bin/pod
```

### Plugins

```
cocoapods-binary      : 0.4.4
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# -*- coding: utf-8 -*-
platform :ios, "10.0"
inhibit_all_warnings!
use_frameworks!
```

error message here,
### Error

```
Errno::ENOENT - No such file or directory @ realpath_rec - ~/Documents/.../ProjectPath/Pods/_Prebuild/GeneratedFrameworks
~/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.8.1/lib/cocoapods/project.rb:326:in `realpath'
~/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.8.1/lib/cocoapods/project.rb:326:in `realpath'
~/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.8.1/lib/cocoapods/project.rb:326:in `reference_for_path'
~/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.8.1/lib/cocoapods/project.rb:269:in `add_file_reference'
~/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.8.1/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:220:in `block (2 levels) in add_file_accessors_paths_to_pods_group'
~/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.8.1/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:219:in `each'
~/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.8.1/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:219:in `block in add_file_accessors_paths_to_pods_group'
~/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.8.1/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:210:in `each'
~/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.8.1/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:210:in `add_file_accessors_paths_to_pods_group'
~/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.8.1/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:93:in `block in add_source_files_references'
~/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.8.1/lib/cocoapods/user_interface.rb:145:in `message'
~/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.8.1/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:92:in `add_source_files_references'
~/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.8.1/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:46:in `install!'
~/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.8.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:101:in `block in install_file_references'
~/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.8.1/lib/cocoapods/user_interface.rb:145:in `message'
~/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.8.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:99:in `install_file_references'
~/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.8.1/lib/cocoapods/installer/xcode/single_pods_project_generator.rb:17:in `generate!'
~/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.8.1/lib/cocoapods/installer.rb:308:in `block in create_and_save_projects'
~/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.8.1/lib/cocoapods/user_interface.rb:64:in `section'
~/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.8.1/lib/cocoapods/installer.rb:303:in `create_and_save_projects'
~/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.8.1/lib/cocoapods/installer.rb:294:in `generate_pods_project'
~/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.8.1/lib/cocoapods/installer.rb:173:in `integrate'
~/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.8.1/lib/cocoapods/installer.rb:162:in `install!'
~/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.8.1/lib/cocoapods/command/install.rb:52:in `run'
~/.rvm/gems/ruby-2.6.3/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
~/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.8.1/lib/cocoapods/command.rb:52:in `run'
~/.rvm/gems/ruby-2.6.3/gems/cocoapods-1.8.1/bin/pod:55:in `<top (required)>'
~/.rvm/gems/ruby-2.6.3/bin/pod:23:in `load'
~/.rvm/gems/ruby-2.6.3/bin/pod:23:in `<main>'
~/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
~/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=No+such+file+or+directory+%40+realpath_rec+-+%2FUsers%2FCA%2FDocuments%2Fcamp%2Fmain%2Fbandios%2FPods%2F_Prebuild%2FGeneratedFrameworks&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!
```

**Comment by dnkoutso** [comment]
need a sample app here and most likely an issue with cocoapods-binary.

**Comment by meccatol** [comment]
I made a simple xcode project and tested sample app, it didn't get error. it works.
I'll try something to reproduce the error.

**Comment by ccomsi** [comment]
this command works to me.
```
find Pods ! -path "Pods/_Prebuild*" -delete
```

**Comment by lewis-smith** [comment]
I found that even after I uninstalled `cocoapods-binary` I still saw this error. @ccomsi's solution worked for me. Thank you!
