### ISSUE TITLE
Pod try is not working starting from pod 1.8.x

### ISSUE THREAD

**Issue by dashchak** [CocoaPods/CocoaPods#9215]
[+] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run "pod try HEREMapsStarter" or pod try any other lib.
Error happens starting from pod 1.8.x version. Works fine in previous pod versions. 

## What did you expect to happen?

Download lib package

### Error

```
NoMethodError - undefined method `root' for false:FalseClass
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.1/lib/cocoapods/installer/pod_source_installer.rb:179:in `root_spec'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.1/lib/cocoapods/installer/pod_source_installer.rb:192:in `predownloaded?'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.1/lib/cocoapods/installer/pod_source_installer.rb:69:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-try-1.1.0/lib/pod/command/try.rb:139:in `install_pod'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-try-1.1.0/lib/pod/command/try.rb:50:in `block in run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.1/lib/cocoapods/user_interface.rb:118:in `title'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-try-1.1.0/lib/pod/command/try.rb:49:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:26:in `load'
/usr/local/bin/pod:26:in `<main>'
/usr/local/bin/ruby_executable_hooks:24:in `eval'
/usr/local/bin/ruby_executable_hooks:24:in `<main>'
```
## CocoaPods Environment

```
   CocoaPods : 1.8.1
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.6 (18G103)
       Xcode : 11.0 (11A420a)
         Git : git version 2.19.2
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-clean       : 0.0.1
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
earlgrey              : 1.13.0
slather               : 2.4.3
```

**Comment by dnkoutso** [comment]
Yeap a bug in cocoapods-try plugin.
