### ISSUE TITLE
Error running `pod try ...`

### ISSUE THREAD

**Issue by deanWombourne** [CocoaPods/CocoaPods#9220]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod try Alamofire`
(or `pod try XCTest-Gherkin`, `pod try RxSwift` etc)

## What did you expect to happen?

A test project to open for that pod.

## What happened instead?

An error trace

### Error

```
NoMethodError - undefined method `root' for false:FalseClass
/Users/samdean/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.1/lib/cocoapods/installer/pod_source_installer.rb:179:in `root_spec'
/Users/samdean/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.1/lib/cocoapods/installer/pod_source_installer.rb:192:in `predownloaded?'
/Users/samdean/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.1/lib/cocoapods/installer/pod_source_installer.rb:69:in `install!'
/Users/samdean/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/cocoapods-try-1.1.0/lib/pod/command/try.rb:139:in `install_pod'
/Users/samdean/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/cocoapods-try-1.1.0/lib/pod/command/try.rb:50:in `block in run'
/Users/samdean/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.1/lib/cocoapods/user_interface.rb:118:in `title'
/Users/samdean/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/cocoapods-try-1.1.0/lib/pod/command/try.rb:49:in `run'
/Users/samdean/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/samdean/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.1/lib/cocoapods/command.rb:52:in `run'
/Users/samdean/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.1/bin/pod:55:in `<top (required)>'
/Users/samdean/.rbenv/versions/2.6.4/bin/pod:23:in `load'
/Users/samdean/.rbenv/versions/2.6.4/bin/pod:23:in `<main>'
```

### Stack

```
   CocoaPods : 1.8.1
        Ruby : ruby 2.6.4p104 (2019-08-28 revision 67798) [x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15 (19A578c)
       Xcode : 11.0 (11A420a)
         Git : git version 2.21.0 (Apple Git-122)
Ruby lib dir : /Users/samdean/.rbenv/versions/2.6.4/lib
Repositories : digital-atelier - git - https://github.com/digital-atelier/ios-pod-specs.git @ 6159466bc3675b4868bda2901a10a8cd071dabf2
               digital-atelier-1 - git - git@github.com:digital-atelier/ios-pod-specs.git @ 6159466bc3675b4868bda2901a10a8cd071dabf2
               master - git - https://github.com/CocoaPods/Specs.git @ f77b50c9c9b3f29556ddbdc4f5ac02d68038bee3
               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /Users/samdean/.rbenv/versions/2.6.4/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

N/A

**Comment by deanWombourne** [comment]
@peril-staging Yea, submitted by mistake. Fixed already ;)

**Comment by dnkoutso** [comment]
Definitely a bug! It's moved and recorded here https://github.com/CocoaPods/cocoapods-try/issues/63

I almost had a fix but haven't had a time to finish it.

**Comment by dnkoutso** [comment]
Closing as a dup.

**Comment by deanWombourne** [comment]
:+1: Thanks!
