### ISSUE TITLE
NoMethodError - undefined method `build_type'

### ISSUE THREAD

**Issue by 463292462** [CocoaPods/CocoaPods#9231]
bundle exec pod install
### Command

```
/usr/local/lib/ruby/gems/2.6.0/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.8.3
        Ruby : ruby 2.6.4p104 (2019-08-28 revision 67798) [x86_64-darwin18]
    RubyGems : 3.0.3
        Host : Mac OS X 10.14.5 (18F132)
       Xcode : 11.0 (11A420a)
         Git : git version 2.21.0 (Apple Git-122)
Ruby lib dir : /usr/local/Cellar/ruby/2.6.4_2/lib
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
slather               : 2.4.7
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

plugin 'slather'

use_frameworks!

xcodeproj "./xxx.xcodeproj"
target "xxx"  do
   ...
end
```

### Error

```
NoMethodError - undefined method `build_type' for #<Pod::Podfile::TargetDefinition label=Pods-Souyidai>
/usr/local/lib/ruby/gems/2.6.0/bundler/gems/CocoaPods-a4e5c23b31d0/lib/cocoapods/installer/analyzer.rb:608:in `block (2 levels) in generate_pod_targets'
/usr/local/lib/ruby/gems/2.6.0/bundler/gems/CocoaPods-a4e5c23b31d0/lib/cocoapods/installer/analyzer.rb:602:in `each'
/usr/local/lib/ruby/gems/2.6.0/bundler/gems/CocoaPods-a4e5c23b31d0/lib/cocoapods/installer/analyzer.rb:602:in `block in generate_pod_targets'
/usr/local/lib/ruby/gems/2.6.0/bundler/gems/CocoaPods-a4e5c23b31d0/lib/cocoapods/installer/analyzer.rb:600:in `each'
/usr/local/lib/ruby/gems/2.6.0/bundler/gems/CocoaPods-a4e5c23b31d0/lib/cocoapods/installer/analyzer.rb:600:in `each_with_object'
/usr/local/lib/ruby/gems/2.6.0/bundler/gems/CocoaPods-a4e5c23b31d0/lib/cocoapods/installer/analyzer.rb:600:in `generate_pod_targets'
/usr/local/lib/ruby/gems/2.6.0/bundler/gems/CocoaPods-a4e5c23b31d0/lib/cocoapods/installer/analyzer.rb:430:in `generate_targets'
/usr/local/lib/ruby/gems/2.6.0/bundler/gems/CocoaPods-a4e5c23b31d0/lib/cocoapods/installer/analyzer.rb:127:in `analyze'
/usr/local/lib/ruby/gems/2.6.0/bundler/gems/CocoaPods-a4e5c23b31d0/lib/cocoapods/installer.rb:410:in `analyze'
/usr/local/lib/ruby/gems/2.6.0/bundler/gems/CocoaPods-a4e5c23b31d0/lib/cocoapods/installer.rb:234:in `block in resolve_dependencies'
/usr/local/lib/ruby/gems/2.6.0/bundler/gems/CocoaPods-a4e5c23b31d0/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.6.0/bundler/gems/CocoaPods-a4e5c23b31d0/lib/cocoapods/installer.rb:233:in `resolve_dependencies'
/usr/local/lib/ruby/gems/2.6.0/bundler/gems/CocoaPods-a4e5c23b31d0/lib/cocoapods/installer.rb:156:in `install!'
/usr/local/lib/ruby/gems/2.6.0/bundler/gems/CocoaPods-a4e5c23b31d0/lib/cocoapods/command/install.rb:52:in `run'
/usr/local/lib/ruby/gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.6.0/bundler/gems/CocoaPods-a4e5c23b31d0/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/2.6.0/bundler/gems/CocoaPods-a4e5c23b31d0/bin/pod:55:in `<top (required)>'
/usr/local/lib/ruby/gems/2.6.0/bin/pod:23:in `load'
/usr/local/lib/ruby/gems/2.6.0/bin/pod:23:in `<top (required)>'
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-1.17.1/lib/bundler/cli/exec.rb:74:in `load'
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-1.17.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-1.17.1/lib/bundler/cli/exec.rb:28:in `run'
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-1.17.1/lib/bundler/cli.rb:463:in `exec'
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-1.17.1/lib/bundler/cli.rb:27:in `dispatch'
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-1.17.1/lib/bundler/cli.rb:18:in `start'
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-1.17.1/exe/bundle:30:in `block in <top (required)>'
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-1.17.1/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-1.17.1/exe/bundle:22:in `<top (required)>'
/usr/local/opt/ruby/bin/bundle:23:in `load'
/usr/local/opt/ruby/bin/bundle:23:in `<main>'
```

**Comment by dnkoutso** [comment]
This is an insufficient bug report. Seems like you are using a specific SHA of CocoaPods and need to specify cocoapods-core too. 

Sorry going to preemptively close.

**Comment by mokagio** [comment]
FWIW, @dnkoutso's suggestion did it for me.

In my `Gemfile` I was using 

```ruby
 gem 'cocoapods', git: 'https://github.com/cocoapods/cocoapods.git', ref: 'f848680c0b0f246b50a256f1e47758a91b8223a9'
```

and when running `bundle exec pod install` I got the same error.

Adding this did the trick

```ruby
gem 'cocoapods-core', git: 'https://github.com/cocoapods/core.git', ref: '5c7c11df7b4d1626292f525e747fd2732666f99d'
```

The SHA I used for cocoapods-core is the one found in the `Gemfile.lock` for cocoapods in its SHA (`f848680c0b0f246b50a256f1e47758a91b8223a9`).
