### ISSUE TITLE
Error on pod init, update, install

### ISSUE THREAD

**Issue by chrisfischer** [CocoaPods/CocoaPods#9249]
### Command
```
/Users/chrisfischer/.rbenv/versions/jruby-9.2.0.0/bin/pod init
```

### Report

* What did you do?

Run pod init on a fresh project. Also see similar errors when running install or update.

### Stack

```
   CocoaPods : 1.8.3
        Ruby : jruby 9.2.0.0 (2.5.0) 2018-05-24 81156a8 Java HotSpot(TM) 64-Bit Server VM 25.144-b01 on 1.8.0_144-b01 +jit [darwin-x86_64]
    RubyGems : 2.7.6
        Host : Mac OS X 10.14.6 (18G95)
       Xcode : 11.1 (11A1027)
         Git : git version 2.20.1
Ruby lib dir : /Users/chrisfischer/.rbenv/versions/jruby-9.2.0.0/lib
Repositories : master - file system
               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Error

```
NameError - uninitialized constant Nanaimo::Reader::StringScanner
org/jruby/RubyModule.java:3526:in `const_missing'
/Users/chrisfischer/.rbenv/versions/jruby-9.2.0.0/lib/ruby/gems/shared/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:97:in `initialize'
/Users/chrisfischer/.rbenv/versions/jruby-9.2.0.0/lib/ruby/gems/shared/gems/xcodeproj-1.12.0/lib/xcodeproj/plist.rb:27:in `read_from_path'
/Users/chrisfischer/.rbenv/versions/jruby-9.2.0.0/lib/ruby/gems/shared/gems/xcodeproj-1.12.0/lib/xcodeproj/project.rb:210:in `initialize_from_file'
/Users/chrisfischer/.rbenv/versions/jruby-9.2.0.0/lib/ruby/gems/shared/gems/xcodeproj-1.12.0/lib/xcodeproj/project.rb:112:in `open'
/Users/chrisfischer/.rbenv/versions/jruby-9.2.0.0/lib/ruby/gems/shared/gems/cocoapods-1.8.3/lib/cocoapods/command/init.rb:41:in `validate!'
/Users/chrisfischer/.rbenv/versions/jruby-9.2.0.0/lib/ruby/gems/shared/gems/claide-1.0.2/lib/claide/command.rb:333:in `run'
/Users/chrisfischer/.rbenv/versions/jruby-9.2.0.0/lib/ruby/gems/shared/gems/cocoapods-1.8.3/lib/cocoapods/command.rb:52:in `run'
/Users/chrisfischer/.rbenv/versions/jruby-9.2.0.0/lib/ruby/gems/shared/gems/cocoapods-1.8.3/bin/pod:55:in `<main>'
org/jruby/RubyKernel.java:994:in `load'
/Users/chrisfischer/.rbenv/versions/jruby-9.2.0.0/bin/pod:23:in `<main>'
```

**Comment by dnkoutso** [comment]
try `gem install nanaimo`?

**Comment by chrisfischer** [comment]
Hm, unfortunately didn't work, I'm still getting the same error. 

When running pod update on a different project, I get

```
NotImplementedError - fork is not available on this platform
org/jruby/RubyKernel.java:1863:in `fork'
org/jruby/RubyProcess.java:1562:in `fork'
/Users/chrisfischer/.rbenv/versions/jruby-9.2.0.0/lib/ruby/gems/shared/gems/cocoapods-core-1.8.3/lib/cocoapods-core/source/manager.rb:252:in `update_search_index_if_needed_in_background'
/Users/chrisfischer/.rbenv/versions/jruby-9.2.0.0/lib/ruby/gems/shared/gems/cocoapods-1.8.3/lib/cocoapods/sources_manager.rb:129:in `update'
/Users/chrisfischer/.rbenv/versions/jruby-9.2.0.0/lib/ruby/gems/shared/gems/cocoapods-1.8.3/lib/cocoapods/installer/analyzer.rb:145:in `block in update_repositories'
org/jruby/RubyArray.java:1801:in `each'
/Users/chrisfischer/.rbenv/versions/jruby-9.2.0.0/lib/ruby/gems/shared/gems/cocoapods-1.8.3/lib/cocoapods/installer/analyzer.rb:143:in `update_repositories'
/Users/chrisfischer/.rbenv/versions/jruby-9.2.0.0/lib/ruby/gems/shared/gems/cocoapods-1.8.3/lib/cocoapods/installer.rb:230:in `block in resolve_dependencies'
/Users/chrisfischer/.rbenv/versions/jruby-9.2.0.0/lib/ruby/gems/shared/gems/cocoapods-1.8.3/lib/cocoapods/user_interface.rb:64:in `section'
/Users/chrisfischer/.rbenv/versions/jruby-9.2.0.0/lib/ruby/gems/shared/gems/cocoapods-1.8.3/lib/cocoapods/installer.rb:229:in `resolve_dependencies'
/Users/chrisfischer/.rbenv/versions/jruby-9.2.0.0/lib/ruby/gems/shared/gems/cocoapods-1.8.3/lib/cocoapods/installer.rb:156:in `install!'
/Users/chrisfischer/.rbenv/versions/jruby-9.2.0.0/lib/ruby/gems/shared/gems/cocoapods-1.8.3/lib/cocoapods/command/update.rb:63:in `run'
/Users/chrisfischer/.rbenv/versions/jruby-9.2.0.0/lib/ruby/gems/shared/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/chrisfischer/.rbenv/versions/jruby-9.2.0.0/lib/ruby/gems/shared/gems/cocoapods-1.8.3/lib/cocoapods/command.rb:52:in `run'
/Users/chrisfischer/.rbenv/versions/jruby-9.2.0.0/lib/ruby/gems/shared/gems/cocoapods-1.8.3/bin/pod:55:in `<main>'
org/jruby/RubyKernel.java:994:in `load'
/Users/chrisfischer/.rbenv/versions/jruby-9.2.0.0/bin/pod:23:in `<main>'
```

**Comment by dnkoutso** [comment]
I am not quite sure this seems like a cocoapods issue. Try using https://bundler.io/ maybe? It seems some gems are missing in your installation or something.

**Comment by chrisfischer** [comment]
Tried uninstalling and reinstalling cocoapods. It installed and issue still persists, but got this.

```
Fetching cocoapods-1.8.3.gem
Successfully installed cocoapods-1.8.3
Parsing documentation for cocoapods-1.8.3
Before reporting this, could you check that the file you're documenting
has proper syntax:

  /Users/chrisfischer/.rbenv/versions/jruby-9.2.0.0/bin/jruby -c lib/cocoapods/executable.rb

RDoc is not a full Ruby parser and will fail when fed invalid ruby programs.

The internal error was:

	(NoMethodError) undefined method `on_kwrest_param' for #<Ripper::Lexer:0x6a844>

ERROR:  While executing gem ... (NoMethodError)
    undefined method `on_kwrest_param' for #<Ripper::Lexer:0x6a844>
```

**Comment by dnkoutso** [comment]
I continue to believe this is a user configuration issue, maybe see https://github.com/jruby/jruby/issues/5209?

**Comment by chrisfischer** [comment]
I really appreciate your help. I updated to jruby 9.2.8.0 which includes a fix for that issue but same thing is happening. I'll also open an issue in jruby.

```
NotImplementedError - fork is not available on this platform
org/jruby/RubyKernel.java:1872:in `fork'
org/jruby/RubyProcess.java:1559:in `fork'
/Users/chrisfischer/.rbenv/versions/jruby-9.2.8.0/lib/ruby/gems/shared/gems/cocoapods-core-1.8.3/lib/cocoapods-core/source/manager.rb:252:in `update_search_index_if_needed_in_background'
/Users/chrisfischer/.rbenv/versions/jruby-9.2.8.0/lib/ruby/gems/shared/gems/cocoapods-1.8.3/lib/cocoapods/sources_manager.rb:129:in `update'
/Users/chrisfischer/.rbenv/versions/jruby-9.2.8.0/lib/ruby/gems/shared/gems/cocoapods-1.8.3/lib/cocoapods/installer/analyzer.rb:145:in `block in update_repositories'
org/jruby/RubyArray.java:1800:in `each'
/Users/chrisfischer/.rbenv/versions/jruby-9.2.8.0/lib/ruby/gems/shared/gems/cocoapods-1.8.3/lib/cocoapods/installer/analyzer.rb:143:in `update_repositories'
/Users/chrisfischer/.rbenv/versions/jruby-9.2.8.0/lib/ruby/gems/shared/gems/cocoapods-1.8.3/lib/cocoapods/installer.rb:230:in `block in resolve_dependencies'
/Users/chrisfischer/.rbenv/versions/jruby-9.2.8.0/lib/ruby/gems/shared/gems/cocoapods-1.8.3/lib/cocoapods/user_interface.rb:64:in `section'
/Users/chrisfischer/.rbenv/versions/jruby-9.2.8.0/lib/ruby/gems/shared/gems/cocoapods-1.8.3/lib/cocoapods/installer.rb:229:in `resolve_dependencies'
/Users/chrisfischer/.rbenv/versions/jruby-9.2.8.0/lib/ruby/gems/shared/gems/cocoapods-1.8.3/lib/cocoapods/installer.rb:156:in `install!'
/Users/chrisfischer/.rbenv/versions/jruby-9.2.8.0/lib/ruby/gems/shared/gems/cocoapods-1.8.3/lib/cocoapods/command/update.rb:63:in `run'
/Users/chrisfischer/.rbenv/versions/jruby-9.2.8.0/lib/ruby/gems/shared/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/chrisfischer/.rbenv/versions/jruby-9.2.8.0/lib/ruby/gems/shared/gems/cocoapods-1.8.3/lib/cocoapods/command.rb:52:in `run'
/Users/chrisfischer/.rbenv/versions/jruby-9.2.8.0/lib/ruby/gems/shared/gems/cocoapods-1.8.3/bin/pod:55:in `<main>'
org/jruby/RubyKernel.java:1022:in `load'
/Users/chrisfischer/.rbenv/versions/jruby-9.2.8.0/bin/pod:23:in `<main>'
```

**Comment by chrisfischer** [comment]
For anyone else experiencing this, don't use jruby.
