### ISSUE TITLE
[!] Oh no, an error occurred.

### ISSUE THREAD

**Issue by litongde** [CocoaPods/CocoaPods#9258]
pod repo update

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod repo update
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.8.3
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15 (19A583)
       Xcode : 11.1 (11A1027)
         Git : git version 2.21.0 (Apple Git-122)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories :
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Error

```
Errno::ENOENT - No such file or directory @ rb_sysopen - /Users/litongde/.cocoapods/repos/Spec_Lock
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.3/lib/cocoapods/sources_manager.rb:118:in `initialize'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.3/lib/cocoapods/sources_manager.rb:118:in `open'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.3/lib/cocoapods/sources_manager.rb:118:in `update'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.3/lib/cocoapods/command/repo/update.rb:23:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.3/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

**Comment by dnkoutso** [comment]
Already fixed for 1.8.4 release.

**Comment by mboeddeker** [comment]
@dnkoutso 

Please build that 1.8.4
