### ISSUE TITLE
run pod search xxxx show error

### ISSUE THREAD

**Issue by liao5836** [CocoaPods/CocoaPods#9269]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
 Run `pod search mob_sharesdk`

### Stack

```
   CocoaPods : 1.7.0.beta.3
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.5 (18F132)
       Xcode : 11.0 (11A420a)
         Git : git version 2.21.0 (Apple Git-122)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : 
               master - https://github.com/CocoaPods/Specs.git @ 2bcae286f112286c81c3dc91d2b070963a15128b
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Error

```
Errno::ENOENT - No such file or directory @ rb_sysopen - /Users/netcent/.cocoapods/repos/cocoapods/all_pods.txt
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.7.0.beta.3/lib/cocoapods-core/cdn_source.rb:228:in `initialize'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.7.0.beta.3/lib/cocoapods-core/cdn_source.rb:228:in `open'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.7.0.beta.3/lib/cocoapods-core/cdn_source.rb:228:in `local_file'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.7.0.beta.3/lib/cocoapods-core/cdn_source.rb:74:in `pods'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.7.0.beta.3/lib/cocoapods-core/source.rb:242:in `pod_sets'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.7.0.beta.3/lib/cocoapods-core/source/aggregate.rb:138:in `generate_search_index_for_source'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.7.0.beta.3/lib/cocoapods-core/source/manager.rb:189:in `block in updated_search_index'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.7.0.beta.3/lib/cocoapods-core/source/manager.rb:185:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.7.0.beta.3/lib/cocoapods-core/source/manager.rb:185:in `updated_search_index'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.7.0.beta.3/lib/cocoapods-core/source/manager.rb:115:in `search_by_name'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-search-1.0.0/lib/cocoapods-search/command/search.rb:87:in `local_search'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-search-1.0.0/lib/cocoapods-search/command/search.rb:63:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.beta.3/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0.beta.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

**Comment by dnkoutso** [comment]
@igor-makarov I think I saw another report with https://github.com/CocoaPods/Old-Specs being added as a CDN repo. I will probably try to write a test for it.

**Comment by dnkoutso** [comment]
good point on the 1.7.0.beta.3...I didnt see it. 

All of what you are saying makes sense. I had seen this https://github.com/CocoaPods/CocoaPods/issues/9253 which also had that Old-Specs repo as a CDN repo for that user and search failed. If you look at the stacktrace here in this issue it has:
```
/Users/netcent/.cocoapods/repos/cocoapods/
```

Which leads me to believe `cocoapods` is a repo that points to the Old-Specs repo like from #9253.

**Comment by igor-makarov** [comment]
Okay, why doesn't old specs repo get recognized by the new 1.8.0 CDN heuristic?

**Comment by dnkoutso** [comment]
I'd imagine the old-specs repo _shouldn't_ be recognized as a CDN repo and maybe that is the bug?

**Comment by igor-makarov** [comment]
Any idea why? How is it different from another git or file repo?

**Comment by dnkoutso** [comment]
not sure...I could add a spec and see.
