### ISSUE TITLE
Unable to add a source with url `https://cdn.cocoapods.org/` named `cocoapods-`.

### ISSUE THREAD

**Issue by jaygauten** [CocoaPods/CocoaPods#9270]
[*] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

installing a pods in a terminal by running `pod install --verbose`

## What did you expect to happen?

Should install the pods correctly

## What happened instead?

it throws an error: **Unable to add a source with url `https://cdn.cocoapods.org/` named `cocoapods-`.**

### Stack

```
   CocoaPods : 1.7.5
        Ruby : ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin17]
    RubyGems : 2.6.14
        Host : Mac OS X 10.14.6 (18G95)
       Xcode : 10.3 (10G8)
         Git : git version 2.17.0
Ruby lib dir : /Users/jaygauten/.rvm/rubies/ruby-2.4.1/lib
Repositories : 
               master - https://github.com/CocoaPods/Specs.git @ 9f2ea12a2b1701879d34d9407bd7b33f5a115437
```

### Installation Source

```
Executable Path: /Users/jaygauten/.rvm/gems/ruby-2.4.1/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

**Comment by dnkoutso** [comment]
This is insufficient information for us to diagnose the issue. Can you please run the same command with `--verbose` and print the stacktrace?

**Comment by jaygauten** [comment]
@dnkoutso 

```
Preparing
18:05:37 
18:05:37 Analyzing dependencies
18:05:37 
18:05:37 Inspecting targets to integrate
18:05:37   Using `ARCHS` setting to build architectures of target `Pods-Vlocity`: (``)
18:05:37 
18:05:37 Finding Podfile changes
18:05:37   A Cordova
18:05:37   A FMDB
18:05:37   A KSCrash
18:05:37   A Rollbar
18:05:37   A SQLCipher
18:05:37   A SalesforceAnalytics
18:05:37   A SalesforceHybridSDK
18:05:37   A SalesforceSDKCommon
18:05:37   A SalesforceSDKCore
18:05:37   A SmartStore
18:05:37   A SmartSync
18:05:37   - FirebaseMessaging
18:05:37 
18:05:37 Fetching external sources
18:05:37 -> Pre-downloading: `Cordova` from `https://github.com/forcedotcom/cordova-ios`, branch `cordova_5.0.0_sdk`
18:05:37   $ /usr/bin/git ls-remote https://github.com/forcedotcom/cordova-ios cordova_5.0.0_sdk
18:05:39   087f667fac727f03a95d11f5bf47987496b15050	refs/heads/cordova_5.0.0_sdk
18:05:39   > Copying Cordova from `/Users/admin/Library/Caches/CocoaPods/Pods/External/Cordova/e2db477832a2bb63da16c8f0f217bd58` to `Pods/Cordova`
18:05:39 -> Pre-downloading: `FMDB` from `https://github.com/ccgus/fmdb`, tag `2.7.5`
18:05:39   > Copying FMDB from `/Users/admin/Library/Caches/CocoaPods/Pods/External/FMDB/d6672b213e1c258ce23d303e9a21271f` to `Pods/FMDB`
18:05:39 -> Pre-downloading: `KSCrash` from `https://github.com/kstenerud/KSCrash`, tag `1.15.20`
18:05:39   > Copying KSCrash from `/Users/admin/Library/Caches/CocoaPods/Pods/External/KSCrash/01701e132ab49d3815314d869919bc75` to `Pods/KSCrash`
18:05:39 -> Pre-downloading: `Rollbar` from `https://github.com/rollbar/rollbar-ios`, tag `v1.6.0`
18:05:39   > Copying Rollbar from `/Users/admin/Library/Caches/CocoaPods/Pods/External/Rollbar/a6ddec11b591237de0ae381b04f59fff` to `Pods/Rollbar`
18:05:39 -> Pre-downloading: `SQLCipher` from `https://github.com/sqlcipher/sqlcipher`, tag `v4.2.0`
18:05:39   > Copying SQLCipher from `/Users/admin/Library/Caches/CocoaPods/Pods/External/SQLCipher/10e54986220b2cec1ccf5529f7ee4c9f` to `Pods/SQLCipher`
18:05:39 -> Pre-downloading: `SalesforceAnalytics` from `https://github.com/jaygauten/SalesforceMobileSDK-iOS`, tag `v7.3.0`
18:05:39   > Copying SalesforceAnalytics from `/Users/admin/Library/Caches/CocoaPods/Pods/External/SalesforceAnalytics/bfc2cfca93d9be4a547cbb23d501f351` to `Pods/SalesforceAnalytics`
18:05:39 -> Pre-downloading: `SalesforceHybridSDK` from `https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Hybrid`, tag `v7.3.0`
18:05:39   > Copying SalesforceHybridSDK from `/Users/admin/Library/Caches/CocoaPods/Pods/External/SalesforceHybridSDK/3932892bbf2975ee07547665e60efafc` to `Pods/SalesforceHybridSDK`
18:05:39 -> Pre-downloading: `SalesforceSDKCommon` from `https://github.com/jaygauten/SalesforceMobileSDK-iOS`, tag `v7.3.0`
18:05:39   > Copying SalesforceSDKCommon from `/Users/admin/Library/Caches/CocoaPods/Pods/External/SalesforceSDKCommon/bfc2cfca93d9be4a547cbb23d501f351` to `Pods/SalesforceSDKCommon`
18:05:39 -> Pre-downloading: `SalesforceSDKCore` from `https://github.com/jaygauten/SalesforceMobileSDK-iOS`, branch `vlocity-master`
18:05:39   $ /usr/bin/git ls-remote https://github.com/jaygauten/SalesforceMobileSDK-iOS vlocity-master
18:05:41   39361462c2345569ca91e2c23a550eb0264aef10	refs/heads/vlocity-master
18:05:41   > Copying SalesforceSDKCore from `/Users/admin/Library/Caches/CocoaPods/Pods/External/SalesforceSDKCore/0de805d3717802f3880380150a7e11c7` to `Pods/SalesforceSDKCore`
18:05:41 -> Pre-downloading: `SmartStore` from `https://github.com/jaygauten/SalesforceMobileSDK-iOS`, tag `v7.3.0`
18:05:41   > Copying SmartStore from `/Users/admin/Library/Caches/CocoaPods/Pods/External/SmartStore/bfc2cfca93d9be4a547cbb23d501f351` to `Pods/SmartStore`
18:05:41 -> Pre-downloading: `SmartSync` from `https://github.com/jaygauten/SalesforceMobileSDK-iOS`, tag `v7.3.0`
18:05:41   > Copying SmartSync from `/Users/admin/Library/Caches/CocoaPods/Pods/External/SmartSync/bfc2cfca93d9be4a547cbb23d501f351` to `Pods/SmartSync`
18:05:41 
18:05:41 Resolving dependencies of `Podfile`
18:05:41 
18:05:41 Cloning spec repo `cocoapods-` from `https://cdn.cocoapods.org/`
18:05:41   $ /usr/bin/git clone https://cdn.cocoapods.org/ cocoapods-
18:05:41   Cloning into 'cocoapods-'...
18:05:41   fatal: repository 'https://cdn.cocoapods.org/' not found
18:05:41 [!] Unable to add a source with url `https://cdn.cocoapods.org/` named `cocoapods-`.
18:05:41 (/usr/bin/git clone https://cdn.cocoapods.org/ cocoapods-
18:05:41 
18:05:41 Cloning into 'cocoapods-'...
18:05:41 fatal: repository 'https://cdn.cocoapods.org/' not found
18:05:41 )
18:05:41 You can try adding it manually in `/Users/admin/.cocoapods/repos` or via `pod repo add`.
```

**Comment by dnkoutso** [comment]
What does your `Podfile` look like? This is weird its trying to add the repo as a `git` repo where it should be a CDN repo.

Can you also paste the output of `pod --version` and the output of `pod repo list`?

**Comment by jaygauten** [comment]
Here it goes:

pod version: **1.7.5**

PodFile contents:
```
platform :ios, '11.0'
source 'https://cdn.cocoapods.org/'
target 'Vlocity' do
	pod 'SalesforceHybridSDK', :git => 'https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Hybrid', :tag => 'v7.3.0'
	pod 'Cordova', :git => 'https://github.com/forcedotcom/cordova-ios', :branch => 'cordova_5.0.0_sdk'
	pod 'SmartSync', :git => 'https://github.com/jaygauten/SalesforceMobileSDK-iOS', :tag => 'v7.3.0'
	pod 'SmartStore', :git => 'https://github.com/jaygauten/SalesforceMobileSDK-iOS', :tag => 'v7.3.0'
	pod 'FMDB/SQLCipher', :git => 'https://github.com/ccgus/fmdb', :tag => '2.7.5'
	pod 'SQLCipher/fts', :git => 'https://github.com/sqlcipher/sqlcipher', :tag => 'v4.2.0'
	pod 'SalesforceSDKCore', :git => 'https://github.com/jaygauten/SalesforceMobileSDK-iOS', :branch => 'vlocity-master'
	pod 'SalesforceAnalytics', :git => 'https://github.com/jaygauten/SalesforceMobileSDK-iOS', :tag => 'v7.3.0'
	pod 'SalesforceSDKCommon', :git => 'https://github.com/jaygauten/SalesforceMobileSDK-iOS', :tag => 'v7.3.0'
	pod 'FirebaseMessaging', '~> 2.0.0'
	pod 'Rollbar', :git => 'https://github.com/rollbar/rollbar-ios', :tag => 'v1.6.0'
	pod 'KSCrash', :git => 'https://github.com/kstenerud/KSCrash', :tag => '1.15.20'
end
```

**Comment by jaygauten** [comment]
@dnkoutso we also tried modifying the folder permission via chmod, but still same error. 

repo list:
```
07:55:35 master
07:55:35 - Type: git (master)
07:55:35 - URL:  https://github.com/CocoaPods/Specs.git
07:55:35 - Path: /Users/admin/.cocoapods/repos/master
07:55:35 
07:55:35 1 repo
```

**Comment by jaygauten** [comment]
@dnkoutso when i manually adding the repo to the pods im having this issue also,

```
Cloning spec repo `cocoapods-` from `https://cdn.cocoapods.org/`
[!] /usr/local/bin/git clone https://cdn.cocoapods.org/ -- cocoapods-

Cloning into 'cocoapods-'...
fatal: repository 'https://cdn.cocoapods.org/' not found
```

**Comment by dnkoutso** [comment]
@jaygauten can you please upgrade to CocoaPods 1.8.4 and try `pod install --verbose` and paste the output here?

**Comment by robbmcmahan** [comment]
@dnkoutso I'm having the same exact issue on a Jenkins instance. 

> Cloning spec repo `cocoapods-` from `https://cdn.cocoapods.org/`
[!] Unable to add a source with url `https://cdn.cocoapods.org/` named `cocoapods-`.

I do see in the logs 

>[!] The version of CocoaPods used to generate the lockfile (1.7.5) is higher than the version of the current executable (1.6.1). Incompatibility issues may arise.

Is there a certain minimum version to use the CDN?

**Comment by amorde** [comment]
I believe the format has changed since the initial release of the CDN repo functionality. The current CDN should work with CocoaPods 1.8.0 or higher

**Comment by dnkoutso** [comment]
@robbmcmahan if you add the CDN repo with a newer version of CocoaPods I dont think an old version can work unless you `pod repo remove trunk` first.

**Comment by jaygauten** [comment]
@dnkoutso 1.8.4 is having an issue with one of our pods, anyway we already fixed the issue.
it was just the cocoapods version it did not upgrade to 1.7.5 and still on v1.6.1

@dnkoutso please confirm what should be the minimum version to use the CDN, is it 1.7.0?

**Comment by dnkoutso** [comment]
@jaygauten for CDN I recommend latest version of 1.8+

**Comment by dnkoutso** [comment]
I think this can be closed. Let me know if I should re-open.

**Comment by SaeedZhiany** [comment]
I'm facing a similar issue here is my pods related information. (I'm using cocoapods on windows 10)

`pod --version` : `1.9.1`

`pod repo list`
`0 repos`

`pod install --verbose`
```
```

**Comment by SaeedZhiany** [comment]
I'm facing a similar issue here is my pods related information. (I'm using cocoapods on windows 10)

`pod --version` : `1.9.1`

`pod repo list`
`0 repos`

`pod install --verbose`
```
  $ C:/Program Files/nodejs/node.exe -e try {console.log(require('@react-native-community/cli').bin);} catch (e) {console.log(require('react-native/cli').bin);}
  C:\Users\SAEED\workspace\MYPROJECT\node_modules\react-native\node_modules\@react-native-community\cli\build\bin.js
Adding a custom script phase for Pod RNFBApp: [RNFB] Core Configuration
Detected React Native module pods for RCTRestart, RNCAsyncStorage, RNCMaskedView, RNDateTimePicker, RNFBApp, RNFBMessaging, RNGestureHandler, RNInAppBrowser, RNKeychain, RNReanimated, RNSVG, RNScreens, RNTextSize, TouchID, react-native-notifications, and react-native-safe-area-context
  Preparing

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-MYPROJECT`: (``)
  Using `ARCHS` setting to build architectures of target `Pods-MYPROJECT-tvOS`: (``)
  Using `ARCHS` setting to build architectures of target `Pods-MYPROJECT-MYPROJECTTests`: (``)
  Using `ARCHS` setting to build architectures of target `Pods-MYPROJECT-tvOSTests`: (``)

Fetching external sources
-> Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
-> Fetching podspec for `FBLazyVector` from `../node_modules/react-native/Libraries/FBLazyVector`
-> Fetching podspec for `FBReactNativeSpec` from `../node_modules/react-native/Libraries/FBReactNativeSpec`
-> Fetching podspec for `Folly` from `../node_modules/react-native/third-party-podspecs/Folly.podspec`
-> Fetching podspec for `RCTRequired` from `../node_modules/react-native/Libraries/RCTRequired`
-> Fetching podspec for `RCTRestart` from `../node_modules/react-native-restart`
-> Fetching podspec for `RCTTypeSafety` from `../node_modules/react-native/Libraries/TypeSafety`
-> Fetching podspec for `RNCAsyncStorage` from `../node_modules/@react-native-community/async-storage`
-> Fetching podspec for `RNCMaskedView` from `../node_modules/@react-native-community/masked-view`
-> Fetching podspec for `RNDateTimePicker` from `../node_modules/@react-native-community/datetimepicker`
-> Fetching podspec for `RNFBApp` from `../node_modules/@react-native-firebase/app`
-> Fetching podspec for `RNFBMessaging` from `../node_modules/@react-native-firebase/messaging`
-> Fetching podspec for `RNGestureHandler` from `../node_modules/react-native-gesture-handler`
-> Fetching podspec for `RNInAppBrowser` from `../node_modules/react-native-inappbrowser-reborn`
-> Fetching podspec for `RNKeychain` from `../node_modules/react-native-keychain`
-> Fetching podspec for `RNReanimated` from `../node_modules/react-native-reanimated`
-> Fetching podspec for `RNSVG` from `../node_modules/react-native-svg`
-> Fetching podspec for `RNScreens` from `../node_modules/react-native-screens`
-> Fetching podspec for `RNTextSize` from `../node_modules/react-native-text-size/ios`
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/specification/linter.rb:366: warning: deprecated Object#=~ is called on Hash; it always returns nil
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/specification/linter.rb:465: warning: deprecated Object#=~ is called on Hash; it always returns nil
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/specification/linter.rb:492: warning: deprecated Object#=~ is called on Hash; it always returns nil
-> Fetching podspec for `React` from `../node_modules/react-native/`
-> Fetching podspec for `React-Core` from `../node_modules/react-native/`
-> Fetching podspec for `React-CoreModules` from `../node_modules/react-native/React/CoreModules`
-> Fetching podspec for `React-RCTActionSheet` from `../node_modules/react-native/Libraries/ActionSheetIOS`
-> Fetching podspec for `React-RCTAnimation` from `../node_modules/react-native/Libraries/NativeAnimation`
-> Fetching podspec for `React-RCTBlob` from `../node_modules/react-native/Libraries/Blob`
-> Fetching podspec for `React-RCTImage` from `../node_modules/react-native/Libraries/Image`
-> Fetching podspec for `React-RCTLinking` from `../node_modules/react-native/Libraries/LinkingIOS`
-> Fetching podspec for `React-RCTNetwork` from `../node_modules/react-native/Libraries/Network`
-> Fetching podspec for `React-RCTSettings` from `../node_modules/react-native/Libraries/Settings`
-> Fetching podspec for `React-RCTText` from `../node_modules/react-native/Libraries/Text`
-> Fetching podspec for `React-RCTVibration` from `../node_modules/react-native/Libraries/Vibration`
-> Fetching podspec for `React-cxxreact` from `../node_modules/react-native/ReactCommon/cxxreact`
-> Fetching podspec for `React-jsi` from `../node_modules/react-native/ReactCommon/jsi`
-> Fetching podspec for `React-jsiexecutor` from `../node_modules/react-native/ReactCommon/jsiexecutor`
-> Fetching podspec for `React-jsinspector` from `../node_modules/react-native/ReactCommon/jsinspector`
-> Fetching podspec for `ReactCommon` from `../node_modules/react-native/ReactCommon`
-> Fetching podspec for `TouchID` from `../node_modules/react-native-touch-id`
-> Fetching podspec for `Yoga` from `../node_modules/react-native/ReactCommon/yoga`
-> Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
-> Fetching podspec for `react-native-notifications` from `../node_modules/react-native-notifications`
-> Fetching podspec for `react-native-safe-area-context` from `../node_modules/react-native-safe-area-context`

Resolving dependencies of `Podfile`

Cloning spec repo `trunk` from `https://cdn.cocoapods.org/`
  $ C:/Program Files/Git/cmd/git.exe clone https://cdn.cocoapods.org/ -- trunk
  Cloning into 'trunk'...
  fatal: repository 'https://cdn.cocoapods.org/' not found
[!] Unable to add a source with url `https://cdn.cocoapods.org/` named `trunk`.
(C:/Program Files/Git/cmd/git.exe clone https://cdn.cocoapods.org/ -- trunk

Cloning into 'trunk'...
fatal: repository 'https://cdn.cocoapods.org/' not found
)
You can try adding it manually in `C:/Users/SAEED/.cocoapods/repos` or via `pod repo add`.

C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.1/lib/cocoapods/sources_manager.rb:55:in `rescue in create_source_with_url'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.1/lib/cocoapods/sources_manager.rb:49:in `create_source_with_url'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.1/lib/cocoapods/sources_manager.rb:22:in `find_or_create_source_with_url'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:178:in `block in sources'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:177:in `map'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:177:in `sources'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:1064:in `block in resolve_dependencies'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.rb:64:in `section'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:1063:in `resolve_dependencies'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:410:in `analyze'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:235:in `block in resolve_dependencies'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.rb:64:in `section'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:234:in `resolve_dependencies'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:156:in `install!'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.1/lib/cocoapods/command/install.rb:52:in `run'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.1/lib/cocoapods/command.rb:52:in `run'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.1/bin/pod:55:in `<top (required)>'
C:/Ruby27-x64/bin/pod:23:in `load'
C:/Ruby27-x64/bin/pod:23:in `<main>'
```

**Pod file**
```
platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

def add_flipper_pods!(versions = {})
  versions['Flipper'] ||= '~> 0.33.1'
  versions['DoubleConversion'] ||= '1.1.7'
  versions['Flipper-Folly'] ||= '~> 2.1'
  versions['Flipper-Glog'] ||= '0.3.6'
  versions['Flipper-PeerTalk'] ||= '~> 0.0.4'
  versions['Flipper-RSocket'] ||= '~> 1.0'

  pod 'FlipperKit', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitLayoutPlugin', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/SKIOSNetworkPlugin', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitUserDefaultsPlugin', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitReactPlugin', versions['Flipper'], :configuration => 'Debug'

  # List all transitive dependencies for FlipperKit pods
  # to avoid them being linked in Release builds
  pod 'Flipper', versions['Flipper'], :configuration => 'Debug'
  pod 'Flipper-DoubleConversion', versions['DoubleConversion'], :configuration => 'Debug'
  pod 'Flipper-Folly', versions['Flipper-Folly'], :configuration => 'Debug'
  pod 'Flipper-Glog', versions['Flipper-Glog'], :configuration => 'Debug'
  pod 'Flipper-PeerTalk', versions['Flipper-PeerTalk'], :configuration => 'Debug'
  pod 'Flipper-RSocket', versions['Flipper-RSocket'], :configuration => 'Debug'
  pod 'FlipperKit/Core', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/CppBridge', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FBCxxFollyDynamicConvert', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FBDefines', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FKPortForwarding', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitHighlightOverlay', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitLayoutTextSearchable', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitNetworkPlugin', versions['Flipper'], :configuration => 'Debug'
end

# Post Install processing for Flipper
def flipper_post_install(installer)
  installer.pods_project.targets.each do |target|
    if target.name == 'YogaKit'
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.1'
      end
    end
  end
end

target 'MYPROJECT' do
  # Pods for MYPROJECT
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/callinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga', :modular_headers => true

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  target 'MYPROJECTTests' do
    inherit! :complete
    # Pods for testing
  end

  use_native_modules!

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  add_flipper_pods!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'MYPROJECT-tvOS' do
  # Pods for MYPROJECT-tvOS

  target 'MYPROJECT-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
```

This is my first usage of cocoapads on windows for a react-native project (with version 0.62.2) and I'm not familiar with this package manager.

@dnkoutso, @jaygauten, can you help me to solve the problem, please?

**Comment by kirkryan** [comment]
I'm also getting the same error as @SaeedZhiany - Win 10, latest react-native 0.62.2 with latest cocoapods.

**Comment by jaygauten** [comment]
Hi @SaeedZhiany, i just downgraded my pod to use the older version because we still have old plugins to use

**Comment by SaeedZhiany** [comment]
Hi @jaygauten 

Which version of pods you are using?

**Comment by jaygauten** [comment]
we are using cocoapods 1.7.5

**Comment by SaeedZhiany** [comment]
Thanks @jaygauten 
just one more question, you said 
> we still have old plugins to use

are you mean react-native projects use old plugins? or just you and your team? if you mean the former one we can inform RN developers by creating an issue in their repository to upgrade and use up-to-date plugins.

**Comment by jaygauten** [comment]
Hi @SaeedZhiany, to clarify that, our team is using ionic 1 which is on top of angular 1

**Comment by SaeedZhiany** [comment]
Ah, I see. I'm using cocoapods for my react-native project, so maybe my problem not directly related to yours. I should investigate whether react-native is using old plugins.

Thanks for your help! 👍

**Comment by kirkryan** [comment]
I’m using a fresh 0.62.2 react native project and have the same issues on Windows only. Even if I got clone the master repo to the .cocoapods/repos directory it complains about trunk.

Best Regards,

Kirk Ryan
________________________________

**Comment by monospacedmagic** [comment]
Same here, CocoaPods 1.9.1 on Windows 10.

**Comment by SaeedZhiany** [comment]
I tried many versions, none of them help, finally I installed the pods on my macOS vmvare.

**Comment by amorde** [comment]
Would love some help here, none of us use Windows so this will be difficult to reproduce.

I'd recommend giving `pod repo add-cdn trunk 'https://cdn.cocoapods.org'` a shot and see if that works

**Comment by SaeedZhiany** [comment]
@amorde 

Thanks for paying attention to this issue. I executed the command you mentioned, but it is stuck with this message:

```
Adding spec repo `trunk` with CDN `https://cdn.cocoapods.org`
[!] CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/CocoaPods-version.yml Response: SSL peer certificate or SSH remote key was not OK
```

**Comment by amorde** [comment]
`Response: SSL peer certificate or SSH remote key was not OK` so some sort of SSL issue? I'm not sure what we can do, we are currently using https://github.com/typhoeus/typhoeus which wraps `libcurl`, it's possible curl is behaving differently on Windows

**Comment by SaeedZhiany** [comment]
Yeah, it's possible, I remembered when I installed ruby on my windows it had a problem with finding `libcurl` and I had to rename and copy the curl's `libcurl-64x` to the ruby's `bin` folder to make it work.
 
However, I just want to report my cocoapods status on my windows OS to see if others have same problem or not. I'm using my VMVare until we can find what the exact problem is.

**Comment by amorde** [comment]
Going to close in favor of #9731 to focus on the Windows aspect, as this issue was originally something else

**Comment by muhammadrizwan0043** [comment]
@SaeedZhiany did you figure out the issue ,if you have figured out then let me know  because i am facing same error

**Comment by SaeedZhiany** [comment]
@muhammadrizwan0043 
no, I didn't.

> I tried many versions, none of them help, finally I installed the pods on my macOS vmvare.

**Comment by SailingSteve** [comment]
sudo gem install cocoapods -v1.8.4
Solved it for me.

**Comment by trn87** [comment]
> sudo gem install cocoapods -v1.8.4
> Solved it for me.

works for me. made my day thank you

**Comment by danwdart** [comment]
Unfortunately fastly's breaking the CDN - any alternative people are using?

**Comment by evanxg852000** [comment]
@danwdart  Just experienced the same issue in our CircleCI build

**Comment by danwdart** [comment]
Ah, this for now:
source 'https://cocoapods-cdn.netlify.app/'

**Comment by ArthurOliverB** [comment]
I'm going through the same thing. I already tried downgrading to 1.8.4, but still.

**Comment by AdamLinke** [comment]
I am also experiencing same issue now and downgrading to 1.8.4 is not helping.

**Comment by orta** [comment]
See: https://github.com/CocoaPods/CocoaPods/issues/10078 - I'm going to lock this thread to keep our issues focused
