### ISSUE TITLE
pod init error in catalina

### ISSUE THREAD

**Issue by wany0904** [CocoaPods/CocoaPods#9271]
hi 
I'm updated 1.8.4 version.
and I enter pod init.

Traceback (most recent call last):
	5: from /usr/local/bin/pod:23:in `<main>'
	4: from /usr/local/bin/pod:23:in `load'
	3: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
	2: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:49:in `run'
	1: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:130:in `verify_minimum_git_version!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:118:in `git_version': Failed to extract git version from `git --version` ("xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun\n") (RuntimeError)

plz help me

**Comment by wany0904** [comment]
i'm reinstall homebrew.
so it fixed
