### ISSUE TITLE
pod install error

### ISSUE THREAD

**Issue by huyabin** [CocoaPods/CocoaPods#9293]
### Command

```
/Users/huyabin/.rvm/rubies/ruby-2.6.3/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.8.4
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]
    RubyGems : 3.0.6
        Host : Mac OS X 10.14.6 (18G103)
       Xcode : 11.1 (11A1027)
         Git : git version 2.21.0 (Apple Git-122)
Ruby lib dir : /Users/huyabin/.rvm/rubies/ruby-2.6.3/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ d10236291020951c436067f9601c8e16d80b7b1d
               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Health-Doctor' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # Yep.
  inhibit_all_warnings!
  # UI
  pod 'Masonry', '~> 1.1.0'
  pod 'MJRefresh', '~> 3.1.15.7'
  pod 'JXPhotoBrowser', '~> 2.1.0'
  pod 'SDWebImage', '~> 4.4.2'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'FSCalendar', '~> 2.8.0' #日历
  #NETWORKING
  pod 'Alamofire', '~> 4.7.3'
  pod 'CocoaAsyncSocket', '~> 7.6.3'
  # BUGFIX
  pod 'Bugly', '~> 2.5.0'
  # SYSTEM
  pod 'IQKeyboardManager', '~> 6.2.0'
  pod 'CryptoSwift', '~> 0.13.1'
  pod 'LookinServer', :configurations => ['Debug']

end
```

### Error

```
Errno::EACCES - Permission denied @ rb_sysopen - /Users/huyabin/Desktop/Health-Doctor/Pods/Target Support Files/Alamofire/Alamofire.xcconfig
/Users/huyabin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/xcode/pods_project_generator/target_installer_helper.rb:21:in `initialize'
/Users/huyabin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/xcode/pods_project_generator/target_installer_helper.rb:21:in `open'
/Users/huyabin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/xcode/pods_project_generator/target_installer_helper.rb:21:in `update_changed_file'
/Users/huyabin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:570:in `create_xcconfig_file'
/Users/huyabin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:60:in `block in install!'
/Users/huyabin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:145:in `message'
/Users/huyabin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:32:in `install!'
/Users/huyabin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/xcode/pods_project_generator.rb:114:in `block in install_pod_targets'
/Users/huyabin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/xcode/pods_project_generator.rb:111:in `map'
/Users/huyabin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/xcode/pods_project_generator.rb:111:in `install_pod_targets'
/Users/huyabin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/xcode/single_pods_project_generator.rb:32:in `block in install_all_pod_targets'
/Users/huyabin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:145:in `message'
/Users/huyabin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/xcode/single_pods_project_generator.rb:31:in `install_all_pod_targets'
/Users/huyabin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/xcode/single_pods_project_generator.rb:19:in `generate!'
/Users/huyabin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:308:in `block in create_and_save_projects'
/Users/huyabin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
/Users/huyabin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:303:in `create_and_save_projects'
/Users/huyabin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:294:in `generate_pods_project'
/Users/huyabin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:173:in `integrate'
/Users/huyabin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:162:in `install!'
/Users/huyabin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command/install.rb:52:in `run'
/Users/huyabin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/huyabin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
/Users/huyabin/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
/Users/huyabin/.rvm/rubies/ruby-2.6.3/bin/pod:23:in `load'
/Users/huyabin/.rvm/rubies/ruby-2.6.3/bin/pod:23:in `<main>'
/Users/huyabin/.rvm/rubies/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
/Users/huyabin/.rvm/rubies/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
```

**Comment by amorde** [comment]
Hello!

Based on this error message

> Errno::EACCES - Permission denied @ rb_sysopen - /Users/huyabin/Desktop/Health-Doctor/Pods/Target Support Files/Alamofire/Alamofire.xcconfig

this looks like a permissions issue. CocoaPods needs to be able to read and write files inside the `Pods` directory.

I'm going to close as this doesn't appear to be a CocoaPods bug but we can continue troubleshooting here
