### ISSUE TITLE
[!] Invalid character "\u0000" in unquoted string

### ISSUE THREAD

**Issue by arealdeadone** [CocoaPods/CocoaPods#9307]
### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?
Tried to install pods using pod install

* What did you expect to happen?
Install my pods and generate my workspace file

* What happened instead?
Exited with this error

### Stack

```
   CocoaPods : 1.8.4
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15
       Xcode :  (11.2 beta 2)
         Git : git version 2.21.0 (Apple Git-122)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ ee37d943324acc74609674228845fe03e1b1d9c0
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '10.0'

target 'HHC' do
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Messaging'
  pod 'Alamofire', '~> 4.5'
  pod 'Alamofire-SwiftyJSON'
  pod 'SwiftyJSON'
  pod 'Fabric', '~> 1.7.9'
  pod 'Crashlytics', '~> 3.10.5'
  pod 'Firebase/Firestore'
  pod 'Firebase/Analytics'
  pod 'PopupDialog', '~> 0.9'
  pod 'MaterialComponents/BottomSheet'
end
```

### Error

```
Nanaimo::Reader::ParseError - [!] Invalid character "\u0000" in unquoted string
 #  -------------------------------------------
1>  
    ^
 #  -------------------------------------------

/Library/Ruby/Gems/2.6.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:284:in `raise_parser_error'
/Library/Ruby/Gems/2.6.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:150:in `parse_string'
/Library/Ruby/Gems/2.6.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:140:in `parse_object'
/Library/Ruby/Gems/2.6.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:107:in `parse!'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.13.0/lib/xcodeproj/plist.rb:27:in `read_from_path'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.13.0/lib/xcodeproj/project.rb:210:in `initialize_from_file'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.13.0/lib/xcodeproj/project.rb:112:in `open'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:1098:in `block (2 levels) in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:1097:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:1097:in `block in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:1092:in `inspect_targets_to_integrate'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:106:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:410:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:234:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:233:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:156:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by dnkoutso** [comment]
Seems like you have an invalid character in your `.xcodeproj` can you upload it?

**Comment by arealdeadone** [comment]
> Seems like you have an invalid character in your `.xcodeproj` can you upload it?

Got it, found the file triggering the error. It seems  my `project.pbxproj` file got replaced by `0000` all over (don't know how it happened though) . My guess is that it happened while I switched from Xcode 11.1 stable to Xcode 11.2B44. Thanks a lot for pointing the actual cause. 
This time the command worked.

**Comment by dnkoutso** [comment]
thanks!
