### ISSUE TITLE
[!] Oh no, an error occurred.

### ISSUE THREAD

**Issue by GitHubZebra** [CocoaPods/CocoaPods#9321]
pod update
――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/Zebra/.rvm/rubies/ruby-2.6.0/bin/pod update
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.8.4
        Ruby : ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-darwin18]
    RubyGems : 3.0.1
        Host : Mac OS X 10.15 (19A602)
       Xcode : 11.1 (11A1027)
         Git : git version 2.21.0 (Apple Git-122)
Ruby lib dir : /Users/Zebra/.rvm/rubies/ruby-2.6.0/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ 14f6a5eded120516eac9447cfdf940d30e9a09e3
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios,'10.0'

use_frameworks!

target :'SuperVolley' do

    pod 'FMDB'

#    pod 'JCyclePictureView'
    pod 'Kingfisher'
    # 七牛
    pod 'PLShortVideoKit/ex-libMuseProcessor'
    pod 'PLPlayerKit', :podspec => 'https://raw.githubusercontent.com/pili-engineering/PLPlayerKit/master/PLPlayerKit-Universal.podspec'
    pod 'PLMediaStreamingKit', :podspec => 'https://raw.githubusercontent.com/pili-engineering/PLMediaStreamingKit/master/PLMediaStreamingKit-Universal.podspec'
    pod 'Qiniu'
    # 七牛云存储服务
    #pod 'QNNetDiag'
    
    # 融云
    pod 'RongCloudIM/IMLib'
    pod 'RongCloudIM/IMKit'
    
    pod 'BaiduMobStatCodeless'

    # 友盟
    pod 'UMCShare/Social/ReducedQQ'
    pod 'UMCShare/Social/ReducedSina'
    pod 'UMCShare/Social/ReducedWeChat'
#    pod 'UMCCommon'
#    pod 'UMCSecurityPlugins'
#     pod 'UMCAnalytics'

    pod 'WechatOpenSDK'
    #pod 'AlipaySDK'
    
    pod 'JPush'

    pod 'Alamofire'
    pod 'ReactiveCocoa'
    pod 'SDWebImage'
    pod 'MJRefresh'
    pod 'IQKeyboardManager'
    pod 'HandyJSON'
    pod 'YYKit'
    pod 'Masonry'
    pod 'SnapKit'
    pod 'JKit_Swift'
    pod 'SideMenu', '5.0.1'
    #pod 'MJExtension'
    #pod 'CVCalendar', '~> 1.6.1'
    
    pod 'BarrageRenderer'

    pod 'TYPagerController'
    
    # 定位功能
    pod 'AMapLocation'
    
    pod 'AMap2DMap'
    # 搜索功能
    pod 'AMapSearch'
    
#    pod 'SectionIndexView'

end
```

### Error

```
Net::OpenTimeout - execution expired
/Users/Zebra/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/net/http.rb:947:in `initialize'
/Users/Zebra/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/net/http.rb:947:in `open'
/Users/Zebra/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/net/http.rb:947:in `block in connect'
/Users/Zebra/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/timeout.rb:103:in `timeout'
/Users/Zebra/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/net/http.rb:945:in `connect'
/Users/Zebra/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/net/http.rb:930:in `do_start'
/Users/Zebra/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/net/http.rb:919:in `start'
/Users/Zebra/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/open-uri.rb:337:in `open_http'
/Users/Zebra/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/open-uri.rb:756:in `buffer_open'
/Users/Zebra/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/open-uri.rb:226:in `block in open_loop'
/Users/Zebra/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/open-uri.rb:224:in `catch'
/Users/Zebra/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/open-uri.rb:224:in `open_loop'
/Users/Zebra/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/open-uri.rb:165:in `open_uri'
/Users/Zebra/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/open-uri.rb:736:in `open'
/Users/Zebra/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/open-uri.rb:35:in `open'
/Users/Zebra/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/external_sources/podspec_source.rb:19:in `block in fetch'
/Users/Zebra/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:86:in `titled_section'
/Users/Zebra/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/external_sources/podspec_source.rb:11:in `fetch'
/Users/Zebra/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:901:in `fetch_external_source'
/Users/Zebra/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:880:in `block (2 levels) in fetch_external_sources'
/Users/Zebra/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:879:in `each'
/Users/Zebra/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:879:in `block in fetch_external_sources'
/Users/Zebra/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
/Users/Zebra/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:878:in `fetch_external_sources'
/Users/Zebra/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:117:in `analyze'
/Users/Zebra/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:410:in `analyze'
/Users/Zebra/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:234:in `block in resolve_dependencies'
/Users/Zebra/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
/Users/Zebra/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:233:in `resolve_dependencies'
/Users/Zebra/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:156:in `install!'
/Users/Zebra/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command/update.rb:63:in `run'
/Users/Zebra/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/Zebra/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
/Users/Zebra/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
/Users/Zebra/.rvm/rubies/ruby-2.6.0/bin/pod:23:in `load'
/Users/Zebra/.rvm/rubies/ruby-2.6.0/bin/pod:23:in `<main>'
/Users/Zebra/.rvm/rubies/ruby-2.6.0/bin/ruby_executable_hooks:24:in `eval'
/Users/Zebra/.rvm/rubies/ruby-2.6.0/bin/ruby_executable_hooks:24:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

**Comment by dnkoutso** [comment]
Looks like a network issue, you can always revert to use `git` based master specs repo than `CDN`.

Closing as network issue which we cannot do much about and we have implemented retries.
