### ISSUE TITLE
flutter iOS build issue

### ISSUE THREAD

**Issue by nrooban** [CocoaPods/CocoaPods#9333]
Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
Running pod install...
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Fetching external sources
    -> Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
    -> Fetching podspec for `cloud_firestore` from `.symlinks/plugins/cloud_firestore/ios`
    -> Fetching podspec for `cloud_functions` from `.symlinks/plugins/cloud_functions/ios`
    -> Fetching podspec for `contact_picker` from `.symlinks/plugins/contact_picker/ios`
    -> Fetching podspec for `contacts_service` from `.symlinks/plugins/contacts_service/ios`
    -> Fetching podspec for `firebase_auth` from `.symlinks/plugins/firebase_auth/ios`
    -> Fetching podspec for `firebase_core` from `.symlinks/plugins/firebase_core/ios`
    -> Fetching podspec for `firebase_messaging` from `.symlinks/plugins/firebase_messaging/ios`
    -> Fetching podspec for `google_sign_in` from `.symlinks/plugins/google_sign_in/ios`
    -> Fetching podspec for `permission_handler` from `.symlinks/plugins/permission_handler/ios`

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only perfomed in repo update

    Comparing resolved specification to the sandbox manifest
      A AppAuth
      A BoringSSL-GRPC
      A Firebase
      A FirebaseAnalytics
      A FirebaseAnalyticsInterop
      A FirebaseAuth
      A FirebaseAuthInterop
      A FirebaseCore
      A FirebaseCoreDiagnostics
      A FirebaseCoreDiagnosticsInterop
      A FirebaseFirestore
      A FirebaseFunctions
      A FirebaseInstanceID
      A FirebaseMessaging
      A Flutter
      A GTMAppAuth
      A GTMSessionFetcher
      A GoogleAppMeasurement
      A GoogleDataTransport
      A GoogleDataTransportCCTSupport
      A GoogleSignIn
      A GoogleUtilities
      A Protobuf
      A cloud_firestore
      A cloud_functions
      A contact_picker
      A contacts_service
      A firebase_auth
      A firebase_core
      A firebase_messaging
      A gRPC-C++
      A gRPC-Core
      A google_sign_in
      A leveldb-library
      A nanopb
      A permission_handler

    Downloading dependencies

    -> Installing AppAuth (1.2.0)

    ――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

    ### Command

    ```
    /usr/local/bin/pod install --verbose
    ```

    ### Report

    * What did you do?

    * What did you expect to happen?

    * What happened instead?

    ### Stack

    ```
       CocoaPods : 1.7.5
            Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
        RubyGems : 3.0.3
            Host : Mac OS X 10.15.1 (19B88)
           Xcode : 11.0 (11A420a)
             Git : git version 2.21.0 (Apple Git-122)
    Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
    Repositories : master - https://github.com/CocoaPods/Specs.git @ cd122cd491fcaa97dc7d9e2862d2b0e15a09a94e

    ```

    ### Plugins

    ```
    cocoapods-deintegrate : 1.0.4
    cocoapods-plugins     : 1.0.0
    cocoapods-search      : 1.0.0
    cocoapods-stats       : 1.1.0
    cocoapods-trunk       : 1.4.1
    cocoapods-try         : 1.1.0
    ```

    ### Podfile

    ```ruby
    # Uncomment this line to define a global platform for your project
    platform :ios, '9.0'

    # CocoaPods analytics sends network stats synchronously affecting flutter build latency.
    ENV['COCOAPODS_DISABLE_STATS'] = 'true'

    project 'Runner', {
      'Debug' => :debug,
      'Profile' => :release,
      'Release' => :release,
    }

    def parse_KV_file(file, separator='=')
      file_abs_path = File.expand_path(file)
      if !File.exists? file_abs_path
        return [];
      end
      pods_ary = []
      skip_line_start_symbols = ["#", "/"]
      File.foreach(file_abs_path) { |line|
          next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
          plugin = line.split(pattern=separator)
          if plugin.length == 2
            podname = plugin[0].strip()
            path = plugin[1].strip()
            podpath = File.expand_path("#{path}", file_abs_path)
            pods_ary.push({:name => podname, :path => podpath});
          else
            puts "Invalid plugin specification: #{line}"
          end
      }
      return pods_ary
    end

    target 'Runner' do
      use_frameworks!

      # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
      # referring to absolute paths on developers' machines.
      system('rm -rf .symlinks')
      system('mkdir -p .symlinks/plugins')

      # Flutter Pods
      generated_xcode_build_settings = parse_KV_file('./Flutter/Generated.xcconfig')
      if generated_xcode_build_settings.empty?
        puts "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter pub get is executed first."
      end
      generated_xcode_build_settings.map { |p|
        if p[:name] == 'FLUTTER_FRAMEWORK_DIR'
          symlink = File.join('.symlinks', 'flutter')
          File.symlink(File.dirname(p[:path]), symlink)
          pod 'Flutter', :path => File.join(symlink, File.basename(p[:path]))
        end
      }

      # Plugin Pods
      plugin_pods = parse_KV_file('../.flutter-plugins')
      plugin_pods.map { |p|
        symlink = File.join('.symlinks', 'plugins', p[:name])
        File.symlink(p[:path], symlink)
        pod p[:name], :path => File.join(symlink, 'ios')
      }
    end

    # Prevent CocoaPods from embedding a second Flutter framework and causing an error with the new Xcode build system.
    install! 'cocoapods', :disable_input_output_paths => true

    post_install do |installer|
      installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
      end
    end
    ```

    ### Error

    ```
    Errno::ENOTEMPTY - Directory not empty @ dir_s_rmdir - /Users/nrooban/Library/Caches/CocoaPods/Pods
    /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1431:in `rmdir'
    /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1431:in `block in remove_dir1'
    /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1442:in `platform_support'
    /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1430:in `remove_dir1'
    /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1423:in `remove'
    /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:760:in `block in remove_entry'
    /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1480:in `ensure in postorder_traverse'
    /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:1480:in `postorder_traverse'
    /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:758:in `remove_entry'
    /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:610:in `block in rm_r'
    /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:606:in `each'
    /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:606:in `rm_r'
    /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/pathname.rb:589:in `rmtree'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/downloader/cache.rb:83:in `ensure_matching_version'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/downloader/cache.rb:22:in `initialize'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/downloader.rb:41:in `new'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/downloader.rb:41:in `download'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/pod_source_installer.rb:109:in `download_source'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/pod_source_installer.rb:62:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:545:in `install_source_of_pod'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:496:in `block (2 levels) in install_pod_sources'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/user_interface.rb:86:in `titled_section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:495:in `block in install_pod_sources'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:478:in `each'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:478:in `install_pod_sources'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:235:in `block in download_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:234:in `download_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:157:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/command/install.rb:51:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'
    ```

    ――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

    [!] Oh no, an error occurred.

    Search for existing GitHub issues similar to yours:
    https://github.com/CocoaPods/CocoaPods/search?q=Directory+not+empty+%40+dir_s_rmdir+-+%2FUsers%2Fnrooban%2FLibrary%2FCaches%2FCocoaPods%2FPods&type=Issues

    If none exists, create a ticket, with the template displayed above, on:
    https://github.com/CocoaPods/CocoaPods/issues/new

    Be sure to first read the contributing guide for details on how to properly submit a ticket:
    https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

    Don't forget to anonymize any private data!

    Looking for related issues on cocoapods/cocoapods...
    Found no similar issues. To create a new issue, please visit:
    https://github.com/cocoapods/cocoapods/issues/new

Error output from CocoaPods:
↳
        [33mWARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
        Consider adding the following to ~/.profile:

        export LANG=en_US.UTF-8
        [0m

Error running pod install
Error launching application on iPhone 11 Pro Max.

**Comment by nrooban** [comment]
Well well well...  I got this worked by deleting the CocoaPods Caches. 

1. In my case /Users/nrooban/Library/Caches/CocoaPods folder.
2. And POD install from iOS project folder. 

all good now.
