### ISSUE TITLE
Invalid Podfile: pod install fails with use_native_modules!

### ISSUE THREAD

**Issue by danieltov** [CocoaPods/CocoaPods#9341]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

1. Upgrade from React Native 0.59.9 to React Native 0.61.4
2. Use boilerplate Podfile - https://raw.githubusercontent.com/react-native-community/rn-diff-purge/release/0.61.1/RnDiffApp/ios/Podfile
3. Do a `pod repo update` and then a `pod install`

## What did you expect to happen?

A clean `pod install` with the integration of native modules.

## What happened instead?

`pod install` fails when I use the boilerplate Podfile provided by the [RN Upgrade Helper](https://react-native-community.github.io/upgrade-helper/) which calls for `use_native_modules!`. `pod install --verbose` gives me this strange error:

```bash

error Unexpected close tag
Line: 25
Column: 18
Char: >. Run CLI with --verbose flag for more details.

[!] Invalid `Podfile` file: 767: unexpected token at 'Error: Unexpected close tag

Line: 25

Column: 18

Char: >

    at error (/my/project/path/node_modules/sax/lib/sax.js:651:10)

    at strictFail (/my/project/path//node_modules/sax/lib/sax.js:677:7)

    at closeTag (/my/project/path/node_modules/sax/lib/sax.js:871:9)

    at SAXParser.write (/my/project/path/node_modules/sax/lib/sax.js:1436:13)

    at new XmlDocument (/my/project/path/node_modules/xmldoc/lib/xmldoc.js:261:15)

    at readManifest (/my/project/path/node_modules/@react-native-community/cli-platform-android/build/config/readManifest.js:38:10)

    at Object.projectConfig (/my/project/path/node_modules/@react-native-community/cli-platform-android/build/config/index.js:59:46)

    at Object.get project [as project] (/my/project/path/node_modules/react-native/node_modules/@react-native-community/cli/build/tools/config/index.js:136:50)

    at /my/project/path/node_modules/react-native/node_modules/@react-native-community/cli/build/commands/config/config.js:8:452

    at Array.forEach (<anonymous>)
'.

 #  from /my/project/path/ios/Podfile:46
 #  -------------------------------------------
 #  
 >    use_native_modules!
 #  end
 #  -------------------------------------------

/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/podfile.rb:301:in `rescue in block in from_ruby'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/podfile.rb:295:in `block in from_ruby'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/podfile.rb:50:in `instance_eval'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/podfile.rb:50:in `initialize'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/podfile.rb:293:in `new'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/podfile.rb:293:in `from_ruby'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/podfile.rb:259:in `from_file'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/config.rb:200:in `podfile'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:150:in `verify_podfile_exists!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command/install.rb:46:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

Without this my native modules are not properly installing. 

### Stack

```
   CocoaPods : 1.8.4
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.6
        Host : Mac OS X 10.15.1 (19B88)
       Xcode : 11.2 (11B52)
         Git : git version 2.21.0 (Apple Git-122.2)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ 5ac6d6629e10db0d64b0df3707203497c0613fca
               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

## My Podfile

My podfile:
```
platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'MyApp' do
  # Pods for MyApp
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  # pod 'RNFS', :path => '../node_modules/react-native-fs'
  # pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
  # pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  target 'MyAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  use_native_modules!
end

target 'MyApp-tvOS' do
  # Pods for MyApp-tvOS

  target 'MyApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

Please advise! 🙂

**Comment by dnkoutso** [comment]
This appears to be a ReactNative issue and you should file it there. Further more the issue clearly says that the Podfile has probably a syntax error on line 767.

I am going to close as this does not appear to be a CocoaPods library issue.

**Comment by danieltov** [comment]
That's great about line 767 error message, but the Podfile is only 57 lines long and the line the pods output points at is line 46.  There's nothing clear about that.

**Comment by dnkoutso** [comment]
Its possible ReactNative is generating a new Podfile? Again based on error this seems like a syntax error in a Podfile as the error message suggests.

**Comment by dnkoutso** [comment]
I recommend filing a bug with ReactNative folks?

**Comment by danieltov** [comment]
That’s valid. Will do!
