### ISSUE TITLE
Pod install failing with Xcode 11.2.1

### ISSUE THREAD

**Issue by delucamike** [CocoaPods/CocoaPods#9353]
* [Y] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod install`

## What did you expect to happen?

Install all pod dependencies correctly. Everything worked properly before updating Xcode version.

## What happened instead?

Error
```
Traceback (most recent call last):
	34: from /Users/Mike/.rbenv/versions/2.6.5/bin/pod:23:in `<main>'
	33: from /Users/Mike/.rbenv/versions/2.6.5/bin/pod:23:in `load'
	32: from /Users/Mike/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
	31: from /Users/Mike/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
	30: from /Users/Mike/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
	29: from /Users/Mike/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command/install.rb:52:in `run'
	28: from /Users/Mike/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:156:in `install!'
	27: from /Users/Mike/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:233:in `resolve_dependencies'
	26: from /Users/Mike/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
	25: from /Users/Mike/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:234:in `block in resolve_dependencies'
	24: from /Users/Mike/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:410:in `analyze'
	23: from /Users/Mike/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
	22: from /Users/Mike/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:984:in `resolve_dependencies'
	21: from /Users/Mike/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
	20: from /Users/Mike/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:985:in `block in resolve_dependencies'
	19: from /Users/Mike/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:177:in `sources'
	18: from /Users/Mike/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:177:in `map'
	17: from /Users/Mike/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:178:in `block in sources'
	16: from /Users/Mike/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/sources_manager.rb:19:in `find_or_create_source_with_url'
	15: from /Users/Mike/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/source/manager.rb:386:in `source_with_url'
	14: from /Users/Mike/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/source/manager.rb:58:in `all'
	13: from /Users/Mike/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/source/manager.rb:24:in `aggregate'
	12: from /Users/Mike/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/source/manager.rb:324:in `aggregate_with_repos'
	11: from /Users/Mike/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/source/manager.rb:324:in `map'
	10: from /Users/Mike/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/source/manager.rb:324:in `block in aggregate_with_repos'
	 9: from /Users/Mike/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/source/manager.rb:315:in `source_from_path'
	 8: from /Users/Mike/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/source/manager.rb:308:in `block in source_from_path'
	 7: from /Users/Mike/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/source/manager.rb:308:in `new'
	 6: from /Users/Mike/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/cdn_source.rb:29:in `initialize'
	 5: from /Users/Mike/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/source.rb:31:in `initialize'
	 4: from /Users/Mike/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/cdn_source.rb:55:in `refresh_metadata'
	 3: from /Users/Mike/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/source.rb:434:in `refresh_metadata'
	 2: from /Users/Mike/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/source/metadata.rb:28:in `from_file'
	 1: from /Users/Mike/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/source/metadata.rb:28:in `new'
/Users/Mike/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/source/metadata.rb:15:in `initialize': undefined method `with_indifferent_access' for #<String:0x00007fe0d8cea818> (NoMethodError)
```
## CocoaPods Environment

Getting same error as above when trying to get version, but should be 1.8.4

## Project that demonstrates the issue

N/A

**Comment by dnkoutso** [comment]
Please upload a sample app for us to reproduce. This is not sufficient information.

**Comment by delucamike** [comment]
It is not app specific. It would happen with a brand new project. Even just running pod env in a new terminal window will cause the error. 

> On Nov 17, 2019, at 1:38 AM, D. Koutsogiorgas <notifications@github.com> wrote:
> 

﻿
Please upload a sample app for us to reproduce. This is not sufficient information.

**Comment by paulb777** [comment]
Looks resolved on stackoverflow - https://stackoverflow.com/questions/58904421/cocoapods-returning-error-after-xcode-update

**Comment by maxizhukov** [comment]
I have same issue, and pod update not helping

**Comment by govarthananve** [comment]
Please try with the below 
```
rm -rf ~/.cocoapods/repos/trunk/
rm -vrf ~/.cocoapods*
pod install --verbose
```
