### ISSUE TITLE
`initialize': undefined method `with_indifferent_access' for #<String:0x00007ff085da4c88> (NoMethodError)

### ISSUE THREAD

**Issue by laitongxue000** [CocoaPods/CocoaPods#9373]
[LaiTongXue@Mr-Lais-MacBook-Pro:] ~ $ pod search SDWebImage
Traceback (most recent call last):
	27: from /Users/LaiTongXue/.rvm/gems/ruby-2.5.5/bin/ruby_executable_hooks:24:in `<main>'
	26: from /Users/LaiTongXue/.rvm/gems/ruby-2.5.5/bin/ruby_executable_hooks:24:in `eval'
	25: from /Users/LaiTongXue/.rvm/gems/ruby-2.5.5/bin/pod:23:in `<main>'
	24: from /Users/LaiTongXue/.rvm/gems/ruby-2.5.5/bin/pod:23:in `load'
	23: from /Users/LaiTongXue/.rvm/gems/ruby-2.5.5/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
	22: from /Users/LaiTongXue/.rvm/gems/ruby-2.5.5/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
	21: from /Users/LaiTongXue/.rvm/rubies/ruby-2.5.5/lib/ruby/gems/2.5.0/gems/claide-1.0.3/lib/claide/command.rb:324:in `run'
	20: from /Users/LaiTongXue/.rvm/rubies/ruby-2.5.5/lib/ruby/gems/2.5.0/gems/claide-1.0.3/lib/claide/command.rb:337:in `rescue in run'
	19: from /Users/LaiTongXue/.rvm/rubies/ruby-2.5.5/lib/ruby/gems/2.5.0/gems/claide-1.0.3/lib/claide/command.rb:396:in `handle_exception'
	18: from /Users/LaiTongXue/.rvm/gems/ruby-2.5.5/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:66:in `report_error'
	17: from /Users/LaiTongXue/.rvm/gems/ruby-2.5.5/gems/cocoapods-1.8.4/lib/cocoapods/user_interface/error_report.rb:24:in `report'
	16: from /Users/LaiTongXue/.rvm/gems/ruby-2.5.5/gems/cocoapods-1.8.4/lib/cocoapods/user_interface/error_report.rb:77:in `stack'
	15: from /Users/LaiTongXue/.rvm/gems/ruby-2.5.5/gems/cocoapods-1.8.4/lib/cocoapods/user_interface/error_report.rb:173:in `repo_information'
	14: from /Users/LaiTongXue/.rvm/rubies/ruby-2.5.5/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/source/manager.rb:58:in `all'
	13: from /Users/LaiTongXue/.rvm/rubies/ruby-2.5.5/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/source/manager.rb:24:in `aggregate'
	12: from /Users/LaiTongXue/.rvm/rubies/ruby-2.5.5/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/source/manager.rb:324:in `aggregate_with_repos'
	11: from /Users/LaiTongXue/.rvm/rubies/ruby-2.5.5/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/source/manager.rb:324:in `map'
	10: from /Users/LaiTongXue/.rvm/rubies/ruby-2.5.5/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/source/manager.rb:324:in `block in aggregate_with_repos'
	 9: from /Users/LaiTongXue/.rvm/rubies/ruby-2.5.5/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/source/manager.rb:315:in `source_from_path'
	 8: from /Users/LaiTongXue/.rvm/rubies/ruby-2.5.5/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/source/manager.rb:310:in `block in source_from_path'
	 7: from /Users/LaiTongXue/.rvm/rubies/ruby-2.5.5/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/source/manager.rb:310:in `new'
	 6: from /Users/LaiTongXue/.rvm/rubies/ruby-2.5.5/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/cdn_source.rb:29:in `initialize'
	 5: from /Users/LaiTongXue/.rvm/rubies/ruby-2.5.5/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/source.rb:31:in `initialize'
	 4: from /Users/LaiTongXue/.rvm/rubies/ruby-2.5.5/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/cdn_source.rb:55:in `refresh_metadata'
	 3: from /Users/LaiTongXue/.rvm/rubies/ruby-2.5.5/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/source.rb:434:in `refresh_metadata'
	 2: from /Users/LaiTongXue/.rvm/rubies/ruby-2.5.5/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/source/metadata.rb:28:in `from_file'
	 1: from /Users/LaiTongXue/.rvm/rubies/ruby-2.5.5/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/source/metadata.rb:28:in `new'
/Users/LaiTongXue/.rvm/rubies/ruby-2.5.5/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/source/metadata.rb:15:in `initialize': undefined method `with_indifferent_access' for #<String:0x00007ff085da4c88> (NoMethodError)

**Comment by laitongxue000** [comment]
I find a way rm -rf ~/.cocoapods/repos and try pod install and it be solved
