### ISSUE TITLE
pod repo update error when updating spec repo 'trunk'

### ISSUE THREAD

**Issue by RexzeLu** [CocoaPods/CocoaPods#9384]
### Command

```
/usr/local/bin/pod repo update
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.8.3
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15 (19A602)
       Xcode : 11.2.1 (11B53)
         Git : git version 2.22.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : 2-haofanning-privaterepo - git - http://192.168.2.106/haofanning/PrivateRepo @ 94340db05f32be03c7037db0823cc89a741382de
               2-mobile-eimv2-mp_ios_sdk_public-mp_ios_sdk_repo - git - http://192.168.2.106/MOBILE/EIMV2/mp_ios_sdk_public/mp_ios_sdk_repo.git @ 2cf277c35d5451125b22818e9ae0b28fdb8ccdd6
               jxdinfo-mobile-eimv2-mp_ios_sdk_public-mp_ios_sdk_repo - git - http://gitlab.jxdinfo.com/MOBILE/EIMV2/mp_ios_sdk_public/mp_ios_sdk_repo.git @ 2cf277c35d5451125b22818e9ae0b28fdb8ccdd6
               JXDRepo - git - http://gitlab.jxdinfo.com/MOBILE/EIMV2/mp_ios_sdk_public/mp_ios_sdk_repo.git @ 2cf277c35d5451125b22818e9ae0b28fdb8ccdd6
               master - git - https://github.com/CocoaPods/Specs.git @ fb69b2f4dfd0ecf455e0922a0cd07ff01b395cc7
               PrivatePods - git - https://github.com/ModulizationDemo/PrivatePods.git @ 727fb3add4fd6d34275a185841a1607f5b74bfd7
               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Error

```
Errno::EPIPE - Broken pipe - SSL_connect
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/protocol.rb:44:in `connect_nonblock'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/protocol.rb:44:in `ssl_socket_connect'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:996:in `connect'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:930:in `do_start'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:919:in `start'
/Library/Ruby/Gems/2.6.0/gems/nap-1.1.0/lib/rest/request.rb:183:in `perform'
/Library/Ruby/Gems/2.6.0/gems/nap-1.1.0/lib/rest/request.rb:192:in `perform'
/Library/Ruby/Gems/2.6.0/gems/nap-1.1.0/lib/rest.rb:24:in `get'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/cdn_source.rb:400:in `download_retrying_connection_errors'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/cdn_source.rb:355:in `download_retrying_retryable_errors'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/cdn_source.rb:361:in `download_retrying_retryable_errors'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/cdn_source.rb:348:in `download_file'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/cdn_source.rb:63:in `block (2 levels) in preheat_existing_files'
/Library/Ruby/Gems/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/promises.rb:1582:in `evaluate_to'
/Library/Ruby/Gems/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/promises.rb:1765:in `block in on_resolvable'
/Library/Ruby/Gems/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/Library/Ruby/Gems/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/Library/Ruby/Gems/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/Library/Ruby/Gems/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/Library/Ruby/Gems/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/Library/Ruby/Gems/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
/Library/Ruby/Gems/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/promises.rb:1257:in `raise'
/Library/Ruby/Gems/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/promises.rb:1257:in `wait_until_resolved!'
/Library/Ruby/Gems/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/promises.rb:977:in `wait!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/cdn_source.rb:68:in `block in preheat_existing_files'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/cdn_source.rb:419:in `catching_concurrent_errors'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/cdn_source.rb:67:in `preheat_existing_files'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/cdn_source.rb:253:in `update'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.3/lib/cocoapods/sources_manager.rb:122:in `block (3 levels) in update'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.3/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.3/lib/cocoapods/sources_manager.rb:121:in `block (2 levels) in update'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.3/lib/cocoapods/sources_manager.rb:120:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.3/lib/cocoapods/sources_manager.rb:120:in `block in update'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.3/lib/cocoapods/sources_manager.rb:118:in `open'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.3/lib/cocoapods/sources_manager.rb:118:in `update'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.3/lib/cocoapods/command/repo/update.rb:23:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.3/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by dnkoutso** [comment]
Seems like a network issue establishing a connection to our CDN server.

Right now I do not have any workaround. We have implemented retries in 1.8.x which it seems like you are using.

Either retry the operation or use the GIT based CocoaPods repo by adding the `source` to your `Podfile`.

Closing for now as there is no action to be taken.
