### ISSUE TITLE
The cocoapods version is 1.7.4, and when I execute the pod trunk command, I report the following error：

### ISSUE THREAD

**Issue by melo30** [CocoaPods/CocoaPods#9388]
### Command

```
/Users/chencheng/.rvm/rubies/ruby-2.4.1/bin/pod trunk push MJBUserInfoKit.podspec --allow-warnings --use-libraries
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.7.4
        Ruby : ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin17]
    RubyGems : 2.7.7
        Host : Mac OS X 10.15.1 (19B88)
       Xcode : 11.2.1 (11B53)
         Git : git version 2.21.0
Ruby lib dir : /Users/chencheng/.rvm/rubies/ruby-2.4.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ b515bbf3933f4f956141326a3352a3e393330998
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Error

```
NameError - uninitialized constant Pod::TrunkSource
/Users/chencheng/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-trunk-1.4.1/lib/pod/command/trunk/push.rb:147:in `update_master_repo'
/Users/chencheng/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-trunk-1.4.1/lib/pod/command/trunk/push.rb:69:in `run'
/Users/chencheng/.rvm/gems/ruby-2.4.1@global/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/chencheng/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.7.4/lib/cocoapods/command.rb:52:in `run'
/Users/chencheng/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.7.4/bin/pod:55:in `<top (required)>'
/Users/chencheng/.rvm/rubies/ruby-2.4.1/bin/pod:23:in `load'
/Users/chencheng/.rvm/rubies/ruby-2.4.1/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

**Comment by listenzz** [comment]
Same problem with `pod _1.6.1_ trunk push XX.podspec`

**Comment by melo30** [comment]
> Same problem with `pod _1.6.1_ trunk push XX.podspec`

I suspect that this problem is caused by a mismatch between the pod version and the system version. My system version is 10.15.1. How about yours?

**Comment by listenzz** [comment]
@melo30 My system version is  same as you.

**Comment by melo30** [comment]
> @melo30 My system version is same as you.

@listenzz I try to upgrade the pod version to 1.8.4, and there's another problem.Now I feel like I can only return the system version.

**Comment by dnkoutso** [comment]
@igor-makarov is it possible cocoapods-trunk 1.4.1 not to be backwards compatible with 1.7.x and 1.6.x?

Seems like we discussed this here https://github.com/CocoaPods/cocoapods-trunk/pull/132 previously.

**Comment by dnkoutso** [comment]
I was not able to reproduce this. I need clear step-by-step instructions on how this issue can occur.

**Comment by igor-makarov** [comment]
Seems like it's incompatible, but not from the PR you mentioned:


https://github.com/CocoaPods/cocoapods-trunk/blob/67959306c053bc77c73388865a5ac4de22574d96/lib/pod/command/trunk/push.rb#L147

The PR that caused this:  

https://github.com/CocoaPods/cocoapods-trunk/pull/135

**Comment by dnkoutso** [comment]
Ouch, is it a fix we can have in cocoapods-trunk and release 1.4.2?

**Comment by igor-makarov** [comment]
Think so, just need to that the symbol exists I think...

**Comment by dnkoutso** [comment]
sgtm, wonder if we can have a test for it too.

**Comment by dnkoutso** [comment]
Moving this issue from cocoapods/cocoapods to cocoapods/cocoapods-trunk
