### ISSUE TITLE
library not found for class Digest::MD5 -- digest/md5

### ISSUE THREAD

**Issue by MasayukiYAMA** [CocoaPods/CocoaPods#9412]
# Steps to Reproduce
```
pod install ( flutter run )
```

# Logs
```
Launching lib/main.dart on iPhone 11 Pro in debug mode...
Running pod install...
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Fetching external sources
    -> Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
    -> Fetching podspec for `cloud_firestore` from `.symlinks/plugins/cloud_firestore/ios`
    -> Fetching podspec for `firebase_analytics` from `.symlinks/plugins/firebase_analytics/ios`
    -> Fetching podspec for `firebase_auth` from `.symlinks/plugins/firebase_auth/ios`
    -> Fetching podspec for `firebase_core` from `.symlinks/plugins/firebase_core/ios`
    -> Fetching podspec for `firebase_messaging` from `.symlinks/plugins/firebase_messaging/ios`
    -> Fetching podspec for `flutter_pdfview` from `.symlinks/plugins/flutter_pdfview/ios`
    -> Fetching podspec for `path_provider` from `.symlinks/plugins/path_provider/ios`
    -> Fetching podspec for `url_launcher` from `.symlinks/plugins/url_launcher/ios`

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only perfomed in repo update
```
## Command

```
  /Users/username/.rbenv/versions/2.4.1/bin/pod install --verbose
```
##  Stack

```
       CocoaPods : 1.8.1
            Ruby : ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin17]
        RubyGems : 2.7.7
            Host : Mac OS X 10.15 (19A603)
           Xcode : 11.1 (11A1027)
             Git : git version 2.19.2
    Ruby lib dir : /Users/username/.rbenv/versions/2.4.1/lib
    Repositories : master - git - https://github.com/CocoaPods/Specs.git @ 350200e41b58e2b9f888dc31992dcc8f9bfe0be8
                   trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
    cocoapods-clean       : 0.0.1
    cocoapods-deintegrate : 1.0.4
    cocoapods-plugins     : 1.0.0
    cocoapods-search      : 1.0.0
    cocoapods-stats       : 1.1.0
    cocoapods-trunk       : 1.4.0
    cocoapods-try         : 1.1.0
```

 ### Podfile

```ruby
# Uncomment this line to define a global platform for your project
    platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
    ENV['COCOAPODS_DISABLE_STATS'] = 'true'

    project 'Runner', {
      'Debug' => :debug,
      'Profile' => :release,
      'Release' => :release,
    }

    def parse_KV_file(file, separator='=')
      file_abs_path = File.expand_path(file)
      if !File.exists? file_abs_path
        return [];
      end
      pods_ary = []
      skip_line_start_symbols = ["#", "/"]
      File.foreach(file_abs_path) { |line|
          next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
          plugin = line.split(pattern=separator)
          if plugin.length == 2
            podname = plugin[0].strip()
            path = plugin[1].strip()
            podpath = File.expand_path("#{path}", file_abs_path)
            pods_ary.push({:name => podname, :path => podpath});
          else
            puts "Invalid plugin specification: #{line}"
          end
      }
      return pods_ary
    end

    target 'Runner' do
      use_frameworks!

      # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
      # referring to absolute paths on developers' machines.
      system('rm -rf .symlinks')
      system('mkdir -p .symlinks/plugins')

      # Flutter Pods
      generated_xcode_build_settings = parse_KV_file('./Flutter/Generated.xcconfig')
      if generated_xcode_build_settings.empty?
        puts "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter packages get is executed first."
      end
      generated_xcode_build_settings.map { |p|
        if p[:name] == 'FLUTTER_FRAMEWORK_DIR'
          symlink = File.join('.symlinks', 'flutter')
          File.symlink(File.dirname(p[:path]), symlink)
          pod 'Flutter', :path => File.join(symlink, File.basename(p[:path]))
        end
      }

      # Plugin Pods
      plugin_pods = parse_KV_file('../.flutter-plugins')
      plugin_pods.map { |p|
        symlink = File.join('.symlinks', 'plugins', p[:name])
        File.symlink(p[:path], symlink)
        pod p[:name], :path => File.join(symlink, 'ios')
      }
    end

    post_install do |installer|
      installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
      end
    end
```

### Error

```
    LoadError - library not found for class Digest::MD5 -- digest/md5
    /Users/username/.rbenv/versions/2.4.1/lib/ruby/2.4.0/digest.rb:16:in `const_missing'
    /Users/username/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-core-1.8.1/lib/cocoapods-core/source/metadata.rb:45:in `path_fragment'
    /Users/username/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-core-1.8.1/lib/cocoapods-core/cdn_source.rb:311:in `pod_shard_fragment'
    /Users/username/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-core-1.8.1/lib/cocoapods-core/cdn_source.rb:202:in `search'
    /Users/username/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-core-1.8.1/lib/cocoapods-core/source/aggregate.rb:83:in `block in search'
    /Users/username/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-core-1.8.1/lib/cocoapods-core/source/aggregate.rb:83:in `select'
    /Users/username/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-core-1.8.1/lib/cocoapods-core/source/aggregate.rb:83:in `search'
    /Users/username/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.8.1/lib/cocoapods/resolver.rb:416:in `create_set_from_sources'
    /Users/username/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.8.1/lib/cocoapods/resolver.rb:385:in `find_cached_set'
    /Users/username/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.8.1/lib/cocoapods/resolver.rb:360:in `specifications_for_dependency'
    /Users/username/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.8.1/lib/cocoapods/resolver.rb:165:in `search_for'
    /Users/username/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.8.1/lib/cocoapods/resolver.rb:274:in `block in sort_dependencies'
    /Users/username/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.8.1/lib/cocoapods/resolver.rb:267:in `each'
    /Users/username/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.8.1/lib/cocoapods/resolver.rb:267:in `sort_by'
    /Users/username/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.8.1/lib/cocoapods/resolver.rb:267:in `sort_dependencies'
    /Users/username/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:53:in `block in sort_dependencies'
Error running pod install
    /Users/username/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:70:in `with_no_such_dependency_error_handling'
    /Users/username/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:52:in `sort_dependencies'
    /Users/username/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:754:in `push_state_for_requirements'
    /Users/username/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:746:in `require_nested_dependencies_for'
    /Users/username/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:729:in `activate_new_spec'
    /Users/username/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:686:in `attempt_to_activate'
    /Users/username/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:254:in `process_topmost_state'
    /Users/username/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
    /Users/username/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
    /Users/username/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.8.1/lib/cocoapods/resolver.rb:94:in `resolve'
    /Users/username/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.8.1/lib/cocoapods/installer/analyzer.rb:986:in `block in resolve_dependencies'
    /Users/username/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.8.1/lib/cocoapods/user_interface.rb:64:in `section'
    /Users/username/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.8.1/lib/cocoapods/installer/analyzer.rb:984:in `resolve_dependencies'
    /Users/username/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.8.1/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
    /Users/username/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.8.1/lib/cocoapods/installer.rb:410:in `analyze'
    /Users/username/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.8.1/lib/cocoapods/installer.rb:234:in `block in resolve_dependencies'
    /Users/username/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.8.1/lib/cocoapods/user_interface.rb:64:in `section'
    /Users/username/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.8.1/lib/cocoapods/installer.rb:233:in `resolve_dependencies'
    /Users/username/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.8.1/lib/cocoapods/installer.rb:156:in `install!'
    /Users/username/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.8.1/lib/cocoapods/command/install.rb:52:in `run'
    /Users/username/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Users/username/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.8.1/lib/cocoapods/command.rb:52:in `run'
    /Users/username/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.8.1/bin/pod:55:in `<top (required)>'
Error launching application on iPhone 11 Pro.
    /Users/username/.rbenv/versions/2.4.1/bin/pod:23:in `load'
    /Users/username/.rbenv/versions/2.4.1/bin/pod:23:in `<main>'
```

**Comment by dnkoutso** [comment]
See this very old issue https://github.com/CocoaPods/CocoaPods/issues/1837

**Comment by vervorm** [comment]
I have exactly the same error and no idea how to solve this. It may be an old issue but the link to issue #1837 does not help me.

please  need advice

ps. I'm a designer not a developer and going through some flutter/firebase courses
pps. I'm using ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin19]

**Comment by corymalcolmtaylor** [comment]
> I have exactly the same error and no idea how to solve this. It may be an old issue but the link to issue #1837 does not help me.
> 
> please need advice
> 
> ps. I'm a designer not a developer and going through some flutter/firebase courses
> pps. I'm using ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin19]

Me too.  I'm on macOS Catalina.
flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale en-CA)
    • Flutter version 1.12.13+hotfix.5 at /Volumes/macex/flutter
    • Framework revision 27321ebbad (6 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Volumes/macex/androidSDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.7.1

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (2 available)
    • Android SDK built for x86 64 • emulator-5554                        • android-x64 •
      Android 5.1.1 (API 22) (emulator)
    • iPhone 11 Pro Max            • 32FD1F6F-5E9A-4693-BED0-98A75A0AEBAC • ios         •
      com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

• No issues found!

**Comment by corymalcolmtaylor** [comment]
... but I just tried [this trick](https://github.com/flutter/flutter/issues/43079#issuecomment-547961307)   and it seems to have worked.
