### ISSUE TITLE
 pod spec lint --sources='https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git' --allow-warnings --no-clean --verbose

### ISSUE THREAD

**Issue by songhongkang** [CocoaPods/CocoaPods#9466]
Touch /Users/Cer/Library/Developer/Xcode/DerivedData/App-dlfilgdndzmubcabhypcxpmhslkn/Build/Products/Release-iphonesimulator/App.app (in target 'App' from project 'App')
        cd /var/folders/x9/p_5mschs03l8rb1dcccf_s4m0000gn/T/CocoaPods-Lint-20200108-40022-kg21iq-HomePageModule
        /usr/bin/touch -c /Users/Cer/Library/Developer/Xcode/DerivedData/App-dlfilgdndzmubcabhypcxpmhslkn/Build/Products/Release-iphonesimulator/App.app

    warning: Skipping code signing because the target does not have an Info.plist file and one is not being generated automatically. (in target 'App' from project 'App')
    ** BUILD SUCCEEDED **

   Testing with `xcodebuild`.
 -> HomePageModule (2.3.9)

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod spec lint --sources=https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git --allow-warnings --no-clean --verbose
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.8.4
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 3.0.3
        Host : Mac OS X 10.14.5 (18F132)
       Xcode : 11.2.1 (11B53)
         Git : git version 2.21.0 (Apple Git-122.2)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : edu-git-cocoapods-specs - git - https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git @ 81aca6a335c1fd83e86249cf2a9fec269bae540f
               gitee-shk123-shkspecs - git - https://gitee.com/shk123/SHKSpecs.git @ 99a401d51a8a99586d493f44366db720292779fa
               modulizationdemo - git - https://github.com/ModulizationDemo/PrivatePods.git @ 727fb3add4fd6d34275a185841a1607f5b74bfd7
               nicolaskim - git - https://github.com/NicolasKim/NCKSpecs.git @ 66b12969c207870a973b94c669be1b70986e2393
               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Error

```
Encoding::CompatibilityError - incompatible character encodings: UTF-8 and ASCII-8BIT
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/validator.rb:171:in `block in results_message'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/validator.rb:145:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/validator.rb:145:in `results_message'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/validator.rb:140:in `print_results'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/validator.rb:131:in `validate'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/command/spec/lint.rb:78:in `block in run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/command/spec/lint.rb:63:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/command/spec/lint.rb:63:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=incompatible+character+encodings%3A+UTF-8+and+ASCII-8BIT&type=Issues

**Comment by dnkoutso** [comment]
The error message clearly states the issue. Please also file in StackOverflow and search prior issues here for solutions. 

As it stands now this is not an issue and going to close.
