### ISSUE TITLE
Error while running pod update: fatal - No live threads left. Deadlock?

### ISSUE THREAD

**Issue by alexziskind1** [CocoaPods/CocoaPods#9476]
### Command

```
/usr/local/bin/pod update
```

### Report

* What did you do?
Created a new Xcode (11.3) project, added a Podfile (below) and ran `pod update` in the project folder

* What did you expect to happen?
I expected the specified pods to be installed

* What happened instead?
I received an error - `fatal - No live threads left. Deadlock?`

### Stack

```
   CocoaPods : 1.8.4
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.2 (19C57)
       Xcode : 11.3 (11C29)
         Git : git version 2.21.0 (Apple Git-122.2)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '8.1'
target "test1" do
pod 'Firebase'
end
```

### Error

```
fatal - No live threads left. Deadlock?
2 threads, 2 sleeps current:0x00007fb61fb9c720 main thread:0x00007fb65f406d50
* #<Thread:0x00007fb65f864198 sleep_forever>
   rb_thread_t:0x00007fb65f406d50 native:0x000000010e480dc0 int:0
   /Library/Ruby/Gems/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/promises.rb:775:in `sleep'
   /Library/Ruby/Gems/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/promises.rb:775:in `wait'
   /Library/Ruby/Gems/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/promises.rb:775:in `block in wait_until_resolved'
   /Library/Ruby/Gems/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/promises.rb:771:in `synchronize'
   /Library/Ruby/Gems/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/promises.rb:771:in `wait_until_resolved'
   /Library/Ruby/Gems/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/promises.rb:1256:in `wait_until_resolved!'
   /Library/Ruby/Gems/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/promises.rb:977:in `wait!'
   /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/cdn_source.rb:68:in `block in preheat_existing_files'
   /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/cdn_source.rb:419:in `catching_concurrent_errors'
   /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/cdn_source.rb:67:in `preheat_existing_files'
   /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/cdn_source.rb:253:in `update'
   /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/sources_manager.rb:126:in `block (3 levels) in update'
   /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
   /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/sources_manager.rb:125:in `block (2 levels) in update'
   /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/sources_manager.rb:124:in `each'
   /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/sources_manager.rb:124:in `block in update'
   /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/sources_manager.rb:122:in `open'
   /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/sources_manager.rb:122:in `update'
   /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:145:in `block in update_repositories'
   /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:143:in `each'
   /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:143:in `update_repositories'
   /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:230:in `block in resolve_dependencies'
   /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
   /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:229:in `resolve_dependencies'
   /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:156:in `install!'
   /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command/update.rb:63:in `run'
   /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
   /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
   /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
   /usr/local/bin/pod:23:in `load'
   /usr/local/bin/pod:23:in `<main>'
* #<Thread:0x00007fb63f9299e0@/Library/Ruby/Gems/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:317 sleep_forever>
   rb_thread_t:0x00007fb61fb9c720 native:0x000070000a717000 int:0
   /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/monitor.rb:189:in `lock'
   /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/monitor.rb:189:in `mon_enter'
   /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:35:in `require'
   /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/pathname.rb:577:in `mkpath'
   /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/cdn_source.rb:341:in `download_file'
   /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/cdn_source.rb:63:in `block (2 levels) in preheat_existing_files'
   /Library/Ruby/Gems/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/promises.rb:1582:in `evaluate_to'
   /Library/Ruby/Gems/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/promises.rb:1765:in `block in on_resolvable'
   /Library/Ruby/Gems/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
   /Library/Ruby/Gems/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
   /Library/Ruby/Gems/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
   /Library/Ruby/Gems/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
   /Library/Ruby/Gems/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
   /Library/Ruby/Gems/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'

/Library/Ruby/Gems/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/promises.rb:775:in `sleep'
/Library/Ruby/Gems/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/promises.rb:775:in `wait'
/Library/Ruby/Gems/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/promises.rb:775:in `block in wait_until_resolved'
/Library/Ruby/Gems/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/promises.rb:771:in `synchronize'
/Library/Ruby/Gems/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/promises.rb:771:in `wait_until_resolved'
/Library/Ruby/Gems/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/promises.rb:1256:in `wait_until_resolved!'
/Library/Ruby/Gems/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/promises.rb:977:in `wait!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/cdn_source.rb:68:in `block in preheat_existing_files'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/cdn_source.rb:419:in `catching_concurrent_errors'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/cdn_source.rb:67:in `preheat_existing_files'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/cdn_source.rb:253:in `update'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/sources_manager.rb:126:in `block (3 levels) in update'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/sources_manager.rb:125:in `block (2 levels) in update'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/sources_manager.rb:124:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/sources_manager.rb:124:in `block in update'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/sources_manager.rb:122:in `open'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/sources_manager.rb:122:in `update'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:145:in `block in update_repositories'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:143:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:143:in `update_repositories'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:230:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:229:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:156:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command/update.rb:63:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by dnkoutso** [comment]
hmmm weird yes indeed. We did re-implement our CDN network layer in 1.9. Can you try the 1.9 beta?

**Comment by dnkoutso** [comment]
Are you also invoking `pod` simultaneously?

**Comment by alexziskind1** [comment]
Just tested the 1.9 beta and it works just fine! Thanks!
