### ISSUE TITLE
Failed when installing my project

### ISSUE THREAD

**Issue by kiransarvaiya** [CocoaPods/CocoaPods#9503]
――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.9.0.beta.2
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.2 (19C57)
       Xcode : 11.3.1 (11C504)
         Git : git version 2.21.1 (Apple Git-122.3)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'AppName' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
   # public pod from cocoapods repo# code generator
  pod 'SwiftLint'
  pod 'SwiftDate'
  
  #Keyboard Manager
  pod 'IQKeyboardManagerSwift'
  pod 'R.swift'
  # data
  pod 'ObjectMapper'
  # networkMedical App: Test Bitrise Setup with Unit test and swiftlint with all workflow
  pod 'Alamofire'
  pod 'AlamofireObjectMapper'
  pod 'AlamofireNetworkActivityIndicator'
  pod 'ReachabilitySwift'
  pod 'SDWebImage'
  
  #firebase
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/RemoteConfig'
  pod 'Fabric'
  pod 'Crashlytics'
  #Atributed Text
  pod 'ActiveLabel'
  pod 'KWVerificationCodeView'
    
  #UIImage Crop
  pod 'CropViewController'
  
 target 'AppNameTests' do
    inherit! :search_paths

  end
  
  
end
```

### Error

```
NoMethodError - undefined method `merged_pod_target_xcconfigs' for nil:NilClass
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:166:in `block in remove_pod_target_xcconfig_overrides_from_target'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:164:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:164:in `remove_pod_target_xcconfig_overrides_from_target'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:147:in `block in add_target'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:146:in `tap'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:146:in `add_target'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:49:in `block in install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/user_interface.rb:145:in `message'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:34:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:114:in `block in install_pod_targets'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:111:in `map'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:111:in `install_pod_targets'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer/xcode/single_pods_project_generator.rb:32:in `block in install_all_pod_targets'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/user_interface.rb:145:in `message'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer/xcode/single_pods_project_generator.rb:31:in `install_all_pod_targets'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer/xcode/single_pods_project_generator.rb:19:in `generate!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer.rb:308:in `block in create_and_save_projects'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer.rb:303:in `create_and_save_projects'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer.rb:295:in `generate_pods_project'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer.rb:174:in `integrate'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer.rb:162:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```
[!] Oh no, an error occurred.

**Comment by dnkoutso** [comment]
Please upload a sample app.

**Comment by sweetleon** [comment]
Duplicate of #9465
