### ISSUE TITLE
zsh: command not found: Building

### ISSUE THREAD

**Issue by deepBlueC** [CocoaPods/CocoaPods#9504]
version 1.8.4 before 

* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace these two lines with what you did.  
e.g. Run `pod install`

## What did you expect to happen?

ℹ Please replace these two lines with what you expected to happen.  
e.g. Install all pod dependencies correctly.

## What happened instead?

ℹ Please replace these two lines with of what happened instead.  
e.g. Pod A is missing the subspec B for target C.

## CocoaPods Environment

ℹ Please replace these two lines with the output of `pod env`.
e.g. via `pod env | pbcopy`

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.
https://guides.cocoapods.org/using/pod-install-vs-update.html

🌈
g@Gs-Mac-mini two3_taw % pod try Google-Mobile-Ads-SDK
Updating spec repositories

CocoaPods 1.9.0.beta.2 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.9.0.beta.2

Trying Google-Mobile-Ads-SDK

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod try Google-Mobile-Ads-SDK
```

### Report

* What did you do?

pod try Google-Mobile-Ads-SDK

`sudo gem install cocoapods --pre`

zsh: command not found: Building

* What did you expect to happen?

Run without error Google-Mobile-Ads-SDK

* What happened instead?

zsh: command not found: Building 

Probably related to Catalina Mac OSX encountered wit Firebase pod install which became successful.

[!] Oh no, an error occurred. 

### Stack

```
   CocoaPods : 1.8.4
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.2 (19C57)
       Xcode : 11.3.1 (11C504)
         Git : git version 2.21.1 (Apple Git-122.3)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ d9532e58a4464712f1216f41dfe41f4b630ef3d8
               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'two3' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for two3

  target 'two3Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'two3UITests' do
    # Pods for testing

pod try Google-Mobile-Ads-SDK


end
```

### Error

```
NoMethodError - undefined method `root' for false:FalseClass
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/pod_source_installer.rb:179:in `root_spec'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/pod_source_installer.rb:192:in `predownloaded?'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/pod_source_installer.rb:69:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-try-1.1.0/lib/pod/command/try.rb:139:in `install_pod'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-try-1.1.0/lib/pod/command/try.rb:50:in `block in run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:118:in `title'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-try-1.1.0/lib/pod/command/try.rb:49:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred. 

### Command

```
/usr/local/bin/pod try Google-Mobile-Ads-SDK
```

### Report

* What did you do?

deleted Library/Cache/Cocoapods
then pod try Google-Mobile-Ads-SDK again 

* What did you expect to happen?

no errors

* What happened instead?

### Error

```
NoMethodError - undefined method `root' for false:FalseClass
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer/pod_source_installer.rb:179:in `root_spec'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer/pod_source_installer.rb:192:in `predownloaded?'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer/pod_source_installer.rb:69:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-try-1.1.0/lib/pod/command/try.rb:139:in `install_pod'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-try-1.1.0/lib/pod/command/try.rb:50:in `block in run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/user_interface.rb:118:in `title'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-try-1.1.0/lib/pod/command/try.rb:49:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

### Stack

```
   CocoaPods : 1.9.0.beta.2
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.2 (19C57)
       Xcode : 11.3.1 (11C504)
         Git : git version 2.21.1 (Apple Git-122.3)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ 13815dad04c17417ee15e3e6e12bdba49f9510da

               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'two3' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for two3

  target 'two3Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'two3UITests' do
    # Pods for testing

pod try Google-Mobile-Ads-SDK


end
```

### Error

```
NoMethodError - undefined method `root' for false:FalseClass
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer/pod_source_installer.rb:179:in `root_spec'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer/pod_source_installer.rb:192:in `predownloaded?'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer/pod_source_installer.rb:69:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-try-1.1.0/lib/pod/command/try.rb:139:in `install_pod'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-try-1.1.0/lib/pod/command/try.rb:50:in `block in run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/user_interface.rb:118:in `title'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-try-1.1.0/lib/pod/command/try.rb:49:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

Please try on current Catalina Mac OSX 10.15.2

**Comment by deepBlueC** [comment]
https://support.apple.com/en-us/HT208050

shows how to change shell login which did the trick using Firebase. I set mine back to bin/bash, but still got errors, so returned it to bin/zsh.
