### ISSUE TITLE
StarIO Pod Install issue

### ISSUE THREAD

**Issue by Solankill** [CocoaPods/CocoaPods#9511]
――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

Run pod install 

* What did you expect to happen?

The pods to install and create a workspace

* What happened instead?

Below error happened. 

### Stack

```
   CocoaPods : 1.8.4
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.1.2
        Host : Mac OS X 10.15.2 (19C57)
       Xcode : 11.3.1 (11C504)
         Git : git version 2.21.1 (Apple Git-122.3)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-clean       : 0.0.1
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '9.0'

target 'GreenlineDCS' do

  use_frameworks!

pod 'StarIO', 'StarIOVersion'
pod 'StarIO_Extension', 'StarIOExtensionVersion'
pod 'SMCloudServices', 'SMCloudServicesVersion'

end
```

### Error

```
ArgumentError - Illformed requirement `"StarIOVersion"`
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/requirement.rb:63:in `parse'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/requirement.rb:88:in `block in initialize'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/requirement.rb:88:in `map!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/requirement.rb:88:in `initialize'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/requirement.rb:34:in `new'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/requirement.rb:34:in `create'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/dependency.rb:101:in `initialize'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/podfile/target_definition.rb:949:in `new'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/podfile/target_definition.rb:949:in `block in pod_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/podfile/target_definition.rb:945:in `map'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/podfile/target_definition.rb:945:in `pod_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/podfile/target_definition.rb:96:in `non_inherited_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/podfile/target_definition.rb:74:in `dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer/podfile_dependency_cache.rb:44:in `block in from_podfile'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer/podfile_dependency_cache.rb:43:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer/podfile_dependency_cache.rb:43:in `from_podfile'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:85:in `initialize'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:416:in `new'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:416:in `create_analyzer'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:227:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:156:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

**Comment by dnkoutso** [comment]
`pod 'StarIO', 'StarIOVersion' is not a valid version. Please use StackOverflow under `cocoapods` tag for these kind of issues. Closing as this does not appear to be a CocoaPods issue.

**Comment by prajwal2100** [comment]
I am facing a problem where I cannot install the Pod StarIO 2.8.2, but I can install StarIO 2.9.1. However, my project specifically needs StarIO 2.8.2, and I am encountering errors during the installation process.

<img width="730" alt="image" src="https://user-images.githubusercontent.com/48951327/229305400-e802974d-2686-41f6-b5d3-f3825ba251b0.png">

CAN YOU HELP ME WITH THIS ?
I have tried to manually install it, trying to add "~>" in pod file, tried sudo gem install /usr/local/bin/pod
still no luck

**Comment by IPRamaAnadya** [comment]
please change
`
  pod 'StarIO', 'StarIOVersion'
  pod 'StarIO_Extension', 'StarIOExtensionVersion'
  pod 'SMCloudServices', 'SMCloudServicesVersion'
`
to
`
  pod 'StarIO', '2.9.1'
  pod 'StarIO_Extension', '1.16.0'
  pod 'StarIODeviceSetting', '1.0.1'
`

u can check the latest version in [this website](https://cocoapods.org/)
