### ISSUE TITLE
pod repo push

### ISSUE THREAD

**Issue by liuyongjiesail** [CocoaPods/CocoaPods#9541]
――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod repo push metaapp MXNetworking.podspec --use-libraries
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.8.4
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.3 (19D76)
       Xcode : 11.3.1 (11C504)
         Git : git version 2.21.1 (Apple Git-122.3)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : aliyun - git - https://github.com/aliyun/aliyun-specs.git @ e2d4386cca4de7f8152c94e3a2e665ee5e4f4766
               master - git - https://github.com/CocoaPods/Specs.git @ e294e6cc71e31e5fe96b9179c6891db937bdff71
               metaapp - git - http://gitlab.appshahe.com/product/metaapp-ios-specs.git @ 941e24df06b1c1699d4671887605afaf5dad39a4
               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Error

```
Errno::ENOTDIR - Not a directory - /Users/liuyongjie/.cocoapods/repos/metaapp/Specs
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open3.rb:213:in `spawn'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open3.rb:213:in `popen_run'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open3.rb:208:in `popen2e'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open3.rb:390:in `capture2e'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/executable.rb:148:in `capture_command'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command/repo/push.rb:113:in `check_if_push_allowed'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command/repo/push.rb:75:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

**Comment by dnkoutso** [comment]
Please try `rm -rf /Users/liuyongjie/.cocoapods/repos` and try again.

**Comment by liuyongjiesail** [comment]
hi dnkoutso, thank you your help! 

I found this error: 
`Errno::ENOTDIR - Not a directory - /Users/liuyongjie/.cocoapods/repos/metaapp/Specs
`
I only create a Specs directory, this error is resove.
