### ISSUE TITLE
window10 using CocoaPods1.8.4 FirebaseCoreDiagnostics 

### ISSUE THREAD

**Issue by yyh9488** [CocoaPods/CocoaPods#9543]
E:\Release\test2>pod install
    WARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
    Consider adding the following to ~/.profile:

    export LANG=en_US.UTF-8

Analyzing dependencies
Downloading dependencies
Installing Firebase (6.14.0)
Installing FirebaseAnalytics (6.1.7)
Installing FirebaseCore (6.5.0)
Installing FirebaseCoreDiagnostics (1.2.0)

[!] Error installing FirebaseCoreDiagnostics

――― MARKDOWN TEMPLATE ――――――――――――――――――――――――――――――――――――――――――――――― ――――――――――――

### Command

```
D:/Cocoapods/Ruby/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.8.4
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [x64-mingw32]
    RubyGems : 3.0.3
        Host : Unable to find an executable (No such file or directory - sw_vers)  ()
       Xcode : -version) ()
         Git : git version 2.22.0.windows.1
Ruby lib dir : D:/Cocoapods/Ruby/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ 196c32e8c286b8b775a472a82c742582beb9a7d7
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/CocoaPods/Specs'
platform :ios, '9.0'

target 'Unity-iPhone' do
  pod 'Firebase/Analytics', '6.14.0'
  pod 'Firebase/Core', '6.14.0'
  pod 'Google-Mobile-Ads-SDK', '~> 7.50'
end
```

### Error

```
Errno::ENOENT - No such file or directory @ rb_sysopen - C:/Users/Administrator/Library/Caches/CocoaPods/Pods/Release/FirebaseCoreDiagnostics/1.2.0-5e788/Example/Database/App/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Back.imagestacklayer/Content.imageset/Contents.json
D:/Cocoapods/Ruby/lib/ruby/2.6.0/fileutils.rb:1386:in `initialize'
D:/Cocoapods/Ruby/lib/ruby/2.6.0/fileutils.rb:1386:in `open'
D:/Cocoapods/Ruby/lib/ruby/2.6.0/fileutils.rb:1386:in `block in copy_file'
D:/Cocoapods/Ruby/lib/ruby/2.6.0/fileutils.rb:1385:in `open'
D:/Cocoapods/Ruby/lib/ruby/2.6.0/fileutils.rb:1385:in `copy_file'
D:/Cocoapods/Ruby/lib/ruby/2.6.0/fileutils.rb:1353:in `copy'
D:/Cocoapods/Ruby/lib/ruby/2.6.0/fileutils.rb:478:in `block in copy_entry'
D:/Cocoapods/Ruby/lib/ruby/2.6.0/fileutils.rb:1484:in `wrap_traverse'
D:/Cocoapods/Ruby/lib/ruby/2.6.0/fileutils.rb:1487:in `block in wrap_traverse'
D:/Cocoapods/Ruby/lib/ruby/2.6.0/fileutils.rb:1486:in `each'
D:/Cocoapods/Ruby/lib/ruby/2.6.0/fileutils.rb:1486:in `wrap_traverse'
D:/Cocoapods/Ruby/lib/ruby/2.6.0/fileutils.rb:1487:in `block in wrap_traverse'
D:/Cocoapods/Ruby/lib/ruby/2.6.0/fileutils.rb:1486:in `each'
D:/Cocoapods/Ruby/lib/ruby/2.6.0/fileutils.rb:1486:in `wrap_traverse'
D:/Cocoapods/Ruby/lib/ruby/2.6.0/fileutils.rb:1487:in `block in wrap_traverse'
D:/Cocoapods/Ruby/lib/ruby/2.6.0/fileutils.rb:1486:in `each'
D:/Cocoapods/Ruby/lib/ruby/2.6.0/fileutils.rb:1486:in `wrap_traverse'
D:/Cocoapods/Ruby/lib/ruby/2.6.0/fileutils.rb:1487:in `block in wrap_traverse'
D:/Cocoapods/Ruby/lib/ruby/2.6.0/fileutils.rb:1486:in `each'
D:/Cocoapods/Ruby/lib/ruby/2.6.0/fileutils.rb:1486:in `wrap_traverse'
D:/Cocoapods/Ruby/lib/ruby/2.6.0/fileutils.rb:1487:in `block in wrap_traverse'
D:/Cocoapods/Ruby/lib/ruby/2.6.0/fileutils.rb:1486:in `each'
D:/Cocoapods/Ruby/lib/ruby/2.6.0/fileutils.rb:1486:in `wrap_traverse'
D:/Cocoapods/Ruby/lib/ruby/2.6.0/fileutils.rb:1487:in `block in wrap_traverse'
D:/Cocoapods/Ruby/lib/ruby/2.6.0/fileutils.rb:1486:in `each'
D:/Cocoapods/Ruby/lib/ruby/2.6.0/fileutils.rb:1486:in `wrap_traverse'
D:/Cocoapods/Ruby/lib/ruby/2.6.0/fileutils.rb:1487:in `block in wrap_traverse'
D:/Cocoapods/Ruby/lib/ruby/2.6.0/fileutils.rb:1486:in `each'
D:/Cocoapods/Ruby/lib/ruby/2.6.0/fileutils.rb:1486:in `wrap_traverse'
D:/Cocoapods/Ruby/lib/ruby/2.6.0/fileutils.rb:1487:in `block in wrap_traverse'
D:/Cocoapods/Ruby/lib/ruby/2.6.0/fileutils.rb:1486:in `each'
D:/Cocoapods/Ruby/lib/ruby/2.6.0/fileutils.rb:1486:in `wrap_traverse'
D:/Cocoapods/Ruby/lib/ruby/2.6.0/fileutils.rb:1487:in `block in wrap_traverse'
D:/Cocoapods/Ruby/lib/ruby/2.6.0/fileutils.rb:1486:in `each'
D:/Cocoapods/Ruby/lib/ruby/2.6.0/fileutils.rb:1486:in `wrap_traverse'
D:/Cocoapods/Ruby/lib/ruby/2.6.0/fileutils.rb:1487:in `block in wrap_traverse'
D:/Cocoapods/Ruby/lib/ruby/2.6.0/fileutils.rb:1486:in `each'
D:/Cocoapods/Ruby/lib/ruby/2.6.0/fileutils.rb:1486:in `wrap_traverse'
D:/Cocoapods/Ruby/lib/ruby/2.6.0/fileutils.rb:475:in `copy_entry'
D:/Cocoapods/Ruby/lib/ruby/2.6.0/fileutils.rb:453:in `block in cp_r'
D:/Cocoapods/Ruby/lib/ruby/2.6.0/fileutils.rb:1557:in `block in fu_each_src_dest'
D:/Cocoapods/Ruby/lib/ruby/2.6.0/fileutils.rb:1573:in `fu_each_src_dest0'
D:/Cocoapods/Ruby/lib/ruby/2.6.0/fileutils.rb:1555:in `fu_each_src_dest'
D:/Cocoapods/Ruby/lib/ruby/2.6.0/fileutils.rb:452:in `cp_r'
D:/Cocoapods/Ruby/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/downloader/cache.rb:201:in `copy_and_clean'
D:/Cocoapods/Ruby/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/downloader/cache.rb:159:in `block (2 levels) in uncached_pod'
D:/Cocoapods/Ruby/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/downloader/cache.rb:157:in `each'
D:/Cocoapods/Ruby/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/downloader/cache.rb:157:in `block in uncached_pod'
D:/Cocoapods/Ruby/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/downloader/cache.rb:181:in `in_tmpdir'
D:/Cocoapods/Ruby/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/downloader/cache.rb:153:in `uncached_pod'
D:/Cocoapods/Ruby/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/downloader/cache.rb:33:in `download_pod'
D:/Cocoapods/Ruby/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/downloader.rb:42:in `download'
D:/Cocoapods/Ruby/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/pod_source_installer.rb:117:in `download_source'
D:/Cocoapods/Ruby/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/pod_source_installer.rb:69:in `install!'
D:/Cocoapods/Ruby/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:557:in `install_source_of_pod'
D:/Cocoapods/Ruby/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:508:in `block (2 levels) in install_pod_sources'
D:/Cocoapods/Ruby/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:86:in `titled_section'
D:/Cocoapods/Ruby/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:507:in `block in install_pod_sources'
D:/Cocoapods/Ruby/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:490:in `each'
D:/Cocoapods/Ruby/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:490:in `install_pod_sources'
D:/Cocoapods/Ruby/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:248:in `block in download_dependencies'
D:/Cocoapods/Ruby/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
D:/Cocoapods/Ruby/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:247:in `download_dependencies'
D:/Cocoapods/Ruby/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:157:in `install!'
D:/Cocoapods/Ruby/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command/install.rb:52:in `run'
D:/Cocoapods/Ruby/lib/ruby/gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
D:/Cocoapods/Ruby/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
D:/Cocoapods/Ruby/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
D:/Cocoapods/Ruby/bin/pod:23:in `load'
D:/Cocoapods/Ruby/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=No+such+file+or+directory+%40+rb_sysopen+-+C%3A%2FUsers%2FAdministrator%2FLibrary%2FCaches%2FCocoaPods%2FPods%2FRelease%2FFirebaseCoreDiagnostics%2F1.2.0-5e788%2FExample%2FDatabase%2FApp%2FtvOS%2FAssets.xcassets%2FApp+Icon+%26+Top+Shelf+Image.brandassets%2FApp+Icon+-+App+Store.imagestack%2FBack.imagestacklayer%2FContent.imageset%2FContents.json&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Searching for inspections failed: undefined method `map' for nil:NilClass

**Comment by dnkoutso** [comment]
Sorry this is insufficient error report. Please upload a sample app and fill in the issue template

cc @paulb777 if you can see something within this report regarding Firebase + Windows.

**Comment by paulb777** [comment]
Not really. Maybe something to do with the file system and the ampersand in the file name?

One debugging step would be to try `git clone git@github.com:firebase/firebase-ios-sdk.git`

**Comment by amorde** [comment]
There's a known issue with Window & path length, it might be that your path is exceeding the legacy path length (can't find the issue ATM)
