### ISSUE TITLE
NoMethodError - undefined method `available_platforms' for nil:NilClass

### ISSUE THREAD

**Issue by anranos** [CocoaPods/CocoaPods#9567]
```
NoMethodError - undefined method `available_platforms' for nil:NilClass
/Users/didi/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.8.4/lib/cocoapods/resolver.rb:440:in `validate_platform'
/Users/didi/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.8.4/lib/cocoapods/resolver.rb:123:in `block (3 levels) in resolver_specs_by_target'
/Users/didi/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.8.4/lib/cocoapods/resolver.rb:119:in `reverse_each'
/Users/didi/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.8.4/lib/cocoapods/resolver.rb:119:in `block (2 levels) in resolver_specs_by_target'
/Users/didi/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.8.4/lib/cocoapods/resolver.rb:107:in `each'
/Users/didi/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.8.4/lib/cocoapods/resolver.rb:107:in `block in resolver_specs_by_target'
/Users/didi/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.8.4/lib/cocoapods/resolver.rb:106:in `tap'
/Users/didi/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.8.4/lib/cocoapods/resolver.rb:106:in `resolver_specs_by_target'
/Users/didi/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.8.4/lib/cocoapods/resolver.rb:95:in `resolve'
/Users/didi/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:986:in `block in resolve_dependencies'
/Users/didi/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
/Users/didi/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:984:in `resolve_dependencies'
/Users/didi/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/Users/didi/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:410:in `analyze'
/Users/didi/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:234:in `block in resolve_dependencies'
/Users/didi/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
/Users/didi/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:233:in `resolve_dependencies'
/Users/didi/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:156:in `install!'
/Users/didi/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.8.4/lib/cocoapods/command/install.rb:52:in `run'
/Users/didi/.rvm/gems/ruby-2.4.1@global/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/didi/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
/Users/didi/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
/Users/didi/.rvm/gems/ruby-2.4.1@global/bin/pod:23:in `load'
/Users/didi/.rvm/gems/ruby-2.4.1@global/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=undefined+method+%60available_platforms%27+for+nil%3ANilClass&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Searching for inspections failed: Failed to open TCP connection to api.github.com:443 (Connection refused - connect(2) for "api.github.com" port 443)

**Comment by dnkoutso** [comment]
This is not a valid issue report. Please fill in the template properly including all steps you did to get the issue.

Closing as incomplete issue report.

**Comment by wangedoo518** [comment]
小桔科技，这个问题最后怎么解决的哈
