### ISSUE TITLE
Install Pods JSON::ParseError - 783

### ISSUE THREAD

**Issue by C4RR13P0TT3R** [CocoaPods/CocoaPods#9577]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod install --repo-update
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.9.0
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.3 (19D76)
       Xcode : 11.3.1 (11C504)
         Git : git version 2.21.1 (Apple Git-122.3)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BasicAuth' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BasicAuth

	pod 'AWSAuthUI'
	pod 'AWSUserPoolsSignIn'
	pod 'AWSMobileClient'

end
```

### Error

```
JSON::ParserError - 783: unexpected token at ''
/Library/Ruby/Gems/2.6.0/gems/json-2.3.0/lib/json/common.rb:156:in `parse'
/Library/Ruby/Gems/2.6.0/gems/json-2.3.0/lib/json/common.rb:156:in `parse'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.0/lib/cocoapods-core/specification/json.rb:61:in `from_json'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.0/lib/cocoapods-core/specification.rb:742:in `from_string'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.0/lib/cocoapods-core/specification.rb:716:in `from_file'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.0/lib/cocoapods-core/source.rb:186:in `specification'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/resolver/lazy_specification.rb:37:in `specification'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:348:in `block in delegating_block'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:349:in `block in delegating_block'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/resolver.rb:178:in `dependencies_for'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:18:in `block in dependencies_for'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:70:in `with_no_such_dependency_error_handling'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:17:in `dependencies_for'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:807:in `block in group_possibilities'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:806:in `reverse_each'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:806:in `group_possibilities'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:778:in `possibilities_for_requirement'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:295:in `initial_state'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:210:in `start_resolution'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:168:in `resolve'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/resolver.rb:94:in `resolve'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/installer/analyzer.rb:1065:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/installer/analyzer.rb:1063:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/installer.rb:410:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/installer.rb:235:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/installer.rb:234:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/installer.rb:156:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

**Comment by dnkoutso** [comment]
Was able to install successfully in a sample app. Please upload a sample app demonstrating the issue.

```
-> Pod installation complete! There are 3 dependencies from the Podfile and 7 total pods installed.
```

**Comment by C4RR13P0TT3R** [comment]
Its a newly created Xcode Single View App. I could install the pods 'AWSAuthUI' and 'AWSUserPoolsSignIn' successfully. 'AWSMobileClient' triggers the error

**Comment by dnkoutso** [comment]
Try `pod cache clean --all` and retry again?

**Comment by C4RR13P0TT3R** [comment]
resolved it as follows

`# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BasicAuth' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BasicAuth
	pod 'AWSUserPoolsSignIn'
	pod 'AWSAuthUI'
	pod 'AWSMobileClient', '~> 2.12.7'

end`

**Comment by C4RR13P0TT3R** [comment]
The cache clean worked as well, thank you. Tried it with reinstalling cocoa pods, which didn't work out

**Comment by ziruozimi** [comment]
### Command

```
/Users/.rvm/gems/ruby-2.4.6/bin/pod update
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.9.1
        Ruby : ruby 2.4.6p354 (2019-04-01 revision 67394) [x86_64-darwin19]
    RubyGems : 2.7.7
        Host : Mac OS X 10.15.4 (19E266)
       Xcode : 11.4 (11E146)
         Git : git version 2.24.1 (Apple Git-126)
Ruby lib dir : /Users/.rvm/rubies/ruby-2.4.6/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Moya/RxSwift'
  pod 'Kingfisher'

end
```

### Error

```
JSON::ParserError - 783: unexpected token at ''
/Users/.rvm/gems/ruby-2.4.6/gems/json-2.3.0/lib/json/common.rb:156:in `parse'
/Users/.rvm/gems/ruby-2.4.6/gems/json-2.3.0/lib/json/common.rb:156:in `parse'
/Users/.rvm/gems/ruby-2.4.6/gems/cocoapods-core-1.9.1/lib/cocoapods-core/specification/json.rb:61:in `from_json'
/Users/.rvm/gems/ruby-2.4.6/gems/cocoapods-core-1.9.1/lib/cocoapods-core/specification.rb:742:in `from_string'
/Users/.rvm/gems/ruby-2.4.6/gems/cocoapods-core-1.9.1/lib/cocoapods-core/specification.rb:716:in `from_file'
/Users/.rvm/gems/ruby-2.4.6/gems/cocoapods-core-1.9.1/lib/cocoapods-core/source.rb:186:in `specification'
/Users/.rvm/gems/ruby-2.4.6/gems/cocoapods-1.9.1/lib/cocoapods/resolver/lazy_specification.rb:37:in `specification'
/Users/.rvm/gems/ruby-2.4.6/gems/cocoapods-1.9.1/lib/cocoapods/resolver/lazy_specification.rb:29:in `subspec_by_name'
/Users/.rvm/gems/ruby-2.4.6/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:362:in `block in specifications_for_dependency'
/Users/.rvm/gems/ruby-2.4.6/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:362:in `map'
/Users/.rvm/gems/ruby-2.4.6/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:362:in `specifications_for_dependency'
/Users/.rvm/gems/ruby-2.4.6/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:165:in `search_for'
/Users/.rvm/gems/ruby-2.4.6/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:274:in `block in sort_dependencies'
/Users/.rvm/gems/ruby-2.4.6/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:267:in `each'
/Users/.rvm/gems/ruby-2.4.6/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:267:in `sort_by'
/Users/.rvm/gems/ruby-2.4.6/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:267:in `sort_dependencies'
/Users/.rvm/gems/ruby-2.4.6/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:53:in `block in sort_dependencies'
/Users/.rvm/gems/ruby-2.4.6/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:70:in `with_no_such_dependency_error_handling'
/Users/.rvm/gems/ruby-2.4.6/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:52:in `sort_dependencies'
/Users/.rvm/gems/ruby-2.4.6/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:288:in `initial_state'
/Users/.rvm/gems/ruby-2.4.6/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:210:in `start_resolution'
/Users/.rvm/gems/ruby-2.4.6/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:168:in `resolve'
/Users/.rvm/gems/ruby-2.4.6/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
/Users/.rvm/gems/ruby-2.4.6/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:94:in `resolve'
/Users/.rvm/gems/ruby-2.4.6/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:1065:in `block in resolve_dependencies'
/Users/.rvm/gems/ruby-2.4.6/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/.rvm/gems/ruby-2.4.6/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:1063:in `resolve_dependencies'
/Users/.rvm/gems/ruby-2.4.6/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/Users/.rvm/gems/ruby-2.4.6/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:410:in `analyze'
/Users/.rvm/gems/ruby-2.4.6/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:235:in `block in resolve_dependencies'
/Users/.rvm/gems/ruby-2.4.6/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/.rvm/gems/ruby-2.4.6/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:234:in `resolve_dependencies'
/Users/.rvm/gems/ruby-2.4.6/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:156:in `install!'
/Users/.rvm/gems/ruby-2.4.6/gems/cocoapods-1.9.1/lib/cocoapods/command/update.rb:63:in `run'
/Users/.rvm/gems/ruby-2.4.6/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/.rvm/gems/ruby-2.4.6/gems/cocoapods-1.9.1/lib/cocoapods/command.rb:52:in `run'
/Users/.rvm/gems/ruby-2.4.6/gems/cocoapods-1.9.1/bin/pod:55:in `<top (required)>'
/Users/.rvm/gems/ruby-2.4.6/bin/pod:23:in `load'
/Users/.rvm/gems/ruby-2.4.6/bin/pod:23:in `<main>'
```

**Comment by ziruozimi** [comment]
Newly created Xcode Single View App, Cache clean not work.

**Comment by ziruozimi** [comment]
If I use the following Podfile, No problem 

### Podfile
```ruby
platform :ios, '11.0'

target 'Test' do
   use_frameworks!

   pod 'Moya/RxSwift',  'x.x.x'
   pod 'Kingfisher',  'x.x.x'
 
 end
 ```
