### ISSUE TITLE
Can't seem to run pod install on a fresh version of react native

### ISSUE THREAD

**Issue by joegaudet** [CocoaPods/CocoaPods#9585]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Ran ```pod install``` from the ios directory of a fresh install of react-native stable

## What did you expect to happen?

Install all pod dependencies correctly.

## What happened instead?

Following log spew:

Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `Folly` from `../node_modules/react-native/third-party-podspecs/Folly.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`

### Command

```
/Users/joegaudet/.rbenv/versions/2.4.0/bin/pod install
```

### Stack

```
   CocoaPods : 1.9.0
        Ruby : ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
    RubyGems : 2.6.8
        Host : Mac OS X 10.15.3 (19D76)
       Xcode : 11.3.1 (11C504)
         Git : git version 2.22.0
Ruby lib dir : /Users/joegaudet/.rbenv/versions/2.4.0/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ be200d30410122b4eb1574f9c9eed5ef0edf8aa2

               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'FleetFox' do
  # Pods for FleetFox
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  target 'FleetFoxTests' do
    inherit! :search_paths
    # Pods for testing
  end

  use_native_modules!
end

target 'FleetFox-tvOS' do
  # Pods for FleetFox-tvOS

  target 'FleetFox-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

### Error

```
NoMethodError - undefined method `strip' for nil:NilClass
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/typhoeus-1.0.2/lib/typhoeus/response/header.rb:49:in `process_line'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/typhoeus-1.0.2/lib/typhoeus/response/header.rb:37:in `block in parse'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/typhoeus-1.0.2/lib/typhoeus/response/header.rb:35:in `each'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/typhoeus-1.0.2/lib/typhoeus/response/header.rb:35:in `parse'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/typhoeus-1.0.2/lib/typhoeus/response/header.rb:20:in `initialize'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/typhoeus-1.0.2/lib/typhoeus/response/informations.rb:226:in `new'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/typhoeus-1.0.2/lib/typhoeus/response/informations.rb:226:in `headers'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cocoapods-core-1.9.0/lib/cocoapods-core/cdn_source.rb:369:in `block in download_and_save_with_retries_async'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.1.4/lib/concurrent/promises.rb:385:in `apply'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.1.4/lib/concurrent/promises.rb:1148:in `apply'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.1.4/lib/concurrent/promises.rb:1498:in `block (2 levels) in on_resolvable'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.1.4/lib/concurrent/promises.rb:1343:in `evaluate_to'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.1.4/lib/concurrent/promises.rb:1498:in `block in on_resolvable'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.1.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.1.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.1.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.1.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.1.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.1.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.1.4/lib/concurrent/promises.rb:1179:in `raise'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.1.4/lib/concurrent/promises.rb:1179:in `wait_until_resolved!'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.1.4/lib/concurrent/promises.rb:940:in `wait!'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cocoapods-core-1.9.0/lib/cocoapods-core/cdn_source.rb:144:in `block in versions'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cocoapods-core-1.9.0/lib/cocoapods-core/cdn_source.rb:471:in `concurrent_requests_catching_errors'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cocoapods-core-1.9.0/lib/cocoapods-core/cdn_source.rb:121:in `versions'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cocoapods-core-1.9.0/lib/cocoapods-core/specification/set.rb:99:in `block in versions_by_source'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cocoapods-core-1.9.0/lib/cocoapods-core/specification/set.rb:98:in `each'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cocoapods-core-1.9.0/lib/cocoapods-core/specification/set.rb:98:in `each_with_object'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cocoapods-core-1.9.0/lib/cocoapods-core/specification/set.rb:98:in `versions_by_source'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cocoapods-core-1.9.0/lib/cocoapods-core/specification/set.rb:56:in `specification_name'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cocoapods-core-1.9.0/lib/cocoapods-core/cdn_source.rb:216:in `search'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cocoapods-core-1.9.0/lib/cocoapods-core/source/aggregate.rb:83:in `block in search'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cocoapods-core-1.9.0/lib/cocoapods-core/source/aggregate.rb:83:in `select'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cocoapods-core-1.9.0/lib/cocoapods-core/source/aggregate.rb:83:in `search'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cocoapods-1.9.0/lib/cocoapods/resolver.rb:416:in `create_set_from_sources'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cocoapods-1.9.0/lib/cocoapods/resolver.rb:385:in `find_cached_set'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cocoapods-1.9.0/lib/cocoapods/resolver.rb:360:in `specifications_for_dependency'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cocoapods-1.9.0/lib/cocoapods/resolver.rb:165:in `search_for'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cocoapods-1.9.0/lib/cocoapods/resolver.rb:274:in `block in sort_dependencies'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cocoapods-1.9.0/lib/cocoapods/resolver.rb:267:in `each'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cocoapods-1.9.0/lib/cocoapods/resolver.rb:267:in `sort_by'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cocoapods-1.9.0/lib/cocoapods/resolver.rb:267:in `sort_dependencies'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:53:in `block in sort_dependencies'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:70:in `with_no_such_dependency_error_handling'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:52:in `sort_dependencies'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:754:in `push_state_for_requirements'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:746:in `require_nested_dependencies_for'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:729:in `activate_new_spec'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:686:in `attempt_to_activate'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:254:in `process_topmost_state'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cocoapods-1.9.0/lib/cocoapods/resolver.rb:94:in `resolve'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cocoapods-1.9.0/lib/cocoapods/installer/analyzer.rb:1065:in `block in resolve_dependencies'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cocoapods-1.9.0/lib/cocoapods/user_interface.rb:64:in `section'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cocoapods-1.9.0/lib/cocoapods/installer/analyzer.rb:1063:in `resolve_dependencies'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cocoapods-1.9.0/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cocoapods-1.9.0/lib/cocoapods/installer.rb:410:in `analyze'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cocoapods-1.9.0/lib/cocoapods/installer.rb:235:in `block in resolve_dependencies'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cocoapods-1.9.0/lib/cocoapods/user_interface.rb:64:in `section'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cocoapods-1.9.0/lib/cocoapods/installer.rb:234:in `resolve_dependencies'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cocoapods-1.9.0/lib/cocoapods/installer.rb:156:in `install!'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cocoapods-1.9.0/lib/cocoapods/command/install.rb:52:in `run'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cocoapods-1.9.0/lib/cocoapods/command.rb:52:in `run'
/Users/joegaudet/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cocoapods-1.9.0/bin/pod:55:in `<top (required)>'
/Users/joegaudet/.rbenv/versions/2.4.0/bin/pod:22:in `load'
/Users/joegaudet/.rbenv/versions/2.4.0/bin/pod:22:in `<main>'
```

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=undefined+method+%60strip%27+for+nil%3ANilClass&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
 - NoMethodError - undefined method `recursive_predecessors' for nil:NilClass in Flutter App
   https://github.com/CocoaPods/CocoaPods/issues/9286 [closed] [4 comments]
   05 Nov 2019

 - Pod install returning error
   https://github.com/CocoaPods/CocoaPods/issues/2944 [closed] [5 comments]
   20 Nov 2019

 - undefined method `strip' for nil:NilClass
   https://github.com/CocoaPods/CocoaPods/issues/5970 [closed] [8 comments]
   23 Jun 2018

and 3 more at:
https://github.com/cocoapods/cocoapods/search?q=undefined%20method%20%60strip%27%20for%20nil&type=Issues&utf8=✓

### Stack

```
   CocoaPods : 1.9.0
        Ruby : ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
    RubyGems : 2.6.8
        Host : Mac OS X 10.15.3 (19D76)
       Xcode : 11.3.1 (11C504)
         Git : git version 2.22.0
Ruby lib dir : /Users/joegaudet/.rbenv/versions/2.4.0/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ be200d30410122b4eb1574f9c9eed5ef0edf8aa2

               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /Users/joegaudet/.rbenv/versions/2.4.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'FleetFox' do
  # Pods for FleetFox
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  target 'FleetFoxTests' do
    inherit! :search_paths
    # Pods for testing
  end

  use_native_modules!
end

target 'FleetFox-tvOS' do
  # Pods for FleetFox-tvOS

  target 'FleetFox-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

## Project that demonstrates the issue

Build a simple project using edge react-native.

```
# joegaudet @ FMI-VAN-L01 in ~/foodee-dev/FleetFox/ios [7:48:55] C:1
$ react-native --version
3.2.1

# joegaudet @ FMI-VAN-L01 in ~/foodee-dev/FleetFox/ios [7:49:00]
$ node --version
v12.11.1

# joegaudet @ FMI-VAN-L01 in ~/foodee-dev/FleetFox/ios [7:49:04]
$ ruby --version
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
```

**Comment by dnkoutso** [comment]
Please file an issue with ReactNative repo. There are too many variables in this project currently to diagnose this.

If you think its a cocoapods issue please upload a sample app _without_ ReactNative and I will re-open this.
