### ISSUE TITLE
pod trunk push doesn't work if source tag has invalid podspec

### ISSUE THREAD

**Issue by Cyberbeni** [CocoaPods/CocoaPods#9588]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
https://github.com/Cyberbeni/TypedNotificationCenter
replace `INSERT VERSION HERE` with 1.5.1
run `pod trunk push TypedNotificationCenter.podspec` or `pod spec lint`

## What did you expect to happen?
podspec with version 1.5.1 pushed to trunk, as it worked with 1.5.0 before (the version under the 1.5.0 tag didn't have a podspec yet)

## What happened instead?
Pod::DSLError during the process. Adding debug printing to the source of exception, it says it doesn't like that my version is `INSERT VERSION HERE`.

## Project that demonstrates the issue
https://github.com/Cyberbeni/TypedNotificationCenter

**Comment by dnkoutso** [comment]
Whats the issue here? The fact that the error message was not clearly visible and you had to dig in to find it or the fact that `INSERT VERSION HERE` is not valid? If its the latter then this is working as expected.

Did it also raise more info on `--verbose`?

**Comment by Cyberbeni** [comment]
```
 -> TypedNotificationCenter (1.5.1)
    - ERROR | [iOS] unknown: Encountered an unknown error (Pod::DSLError
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.0/lib/cocoapods-core/specification.rb:835:in `rescue in _eval_podspec'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.0/lib/cocoapods-core/specification.rb:826:in `_eval_podspec'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.0/lib/cocoapods-core/specification.rb:736:in `block in from_string'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.0/lib/cocoapods-core/specification.rb:735:in `chdir'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.0/lib/cocoapods-core/specification.rb:735:in `from_string'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.0/lib/cocoapods-core/specification.rb:716:in `from_file'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/sandbox/podspec_finder.rb:15:in `block in podspecs'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/sandbox/podspec_finder.rb:14:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/sandbox/podspec_finder.rb:14:in `podspecs'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/downloader.rb:82:in `download_request'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/downloader/cache.rb:171:in `download'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/downloader/cache.rb:154:in `block in uncached_pod'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/downloader/cache.rb:181:in `in_tmpdir'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/downloader/cache.rb:153:in `uncached_pod'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/downloader/cache.rb:33:in `download_pod'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/downloader.rb:42:in `download'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/installer/pod_source_installer.rb:117:in `download_source'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/installer/pod_source_installer.rb:69:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/installer.rb:557:in `install_source_of_pod'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/installer.rb:508:in `block (2 levels) in install_pod_sources'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/user_interface.rb:86:in `titled_section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/installer.rb:507:in `block in install_pod_sources'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/installer.rb:490:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/installer.rb:490:in `install_pod_sources'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/installer.rb:249:in `block in download_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/installer.rb:248:in `download_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/validator.rb:565:in `block in download_pod'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/validator.rb:565:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/validator.rb:565:in `download_pod'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/validator.rb:389:in `block in perform_extensive_analysis'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/validator.rb:383:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/validator.rb:383:in `perform_extensive_analysis'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/validator.rb:130:in `validate'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/command/spec/lint.rb:78:in `block in run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/command/spec/lint.rb:63:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/command/spec/lint.rb:63:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
) during validation.

Analyzed 1 podspec.

[!] The spec did not pass validation, due to 1 error.

/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/command/spec/lint.rb:95:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

The last 2 lines at the top of the stack trace is this:
```
    message = "Invalid `#{path.basename}` file: #{e.message}"
    raise DSLError.new(message, path, e, string)
```
I just put a `puts message` between those lines to get the actual error message which printed this:
```Invalid `TypedNotificationCenter.podspec` file: Malformed version number string INSERT VERSION HERE```

**Comment by dnkoutso** [comment]
yeah we can expand that and add the message perhaps if its verbose?

**Comment by Cyberbeni** [comment]
My main issue is that I want to push my local version of podspec to trunk while the podspec on the tag has a placeholder value for the version because I want the cocoapods release to be reactive to my actual release instead of building my workflow around cocoapods.

Having to follow the stacktrace to understand an issue is a pretty marginal problem compared to this.

**Comment by dnkoutso** [comment]
if you want to be able to pass a value during publish time then you can use `ENV['MYPOD_VERSION']` instead in your podspec and then publish with `MYPOD_VERSION=1.7.1 && pod trunk push...`

**Comment by Cyberbeni** [comment]
> there hasn't been any activity for a few months

???

If the specified tag doesn't have a podspec file then pushing to trunk works correctly. If the specified tag has an invalid podspec then pushing to trunk fails because it can't validate that podspec (even though only the podspec you are currently pushing to trunk matters).

I know you can work around the problem by commiting and tagging a version with correct podspec and probably a bunch of different ways.

The point is still that the podspec on the specified tag shouldn't be validated. There is even a pretty minimal example provided, I don't know how to explain it any clearer.
