### ISSUE TITLE
JSON::ParserError - 785: unexpected token at ''

### ISSUE THREAD

**Issue by PreSwift** [CocoaPods/CocoaPods#9593]
――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/xxxx/.rvm/rubies/ruby-2.7.0-preview1/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.9.0
        Ruby : ruby 2.7.0preview1 (2019-05-31 trunk c55db6aa271df4a689dc8eb0039c929bf6ed43ff) [x86_64-darwin19]
    RubyGems : 3.1.0.pre1
        Host : Mac OS X 10.15.3 (19D76)
       Xcode : 11.3.1 (11C504)
         Git : git version 2.21.1 (Apple Git-122.3)
Ruby lib dir : /Users/xxxx/.rvm/rubies/ruby-2.7.0-preview1/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '9.0'

use_frameworks!

target 'xxxx' do

### 第三方服务组件
# 极光推送
pod 'JPush'
# 友盟
pod 'UMCCommon'
pod 'UMCAnalytics'
pod 'UMCShare/UI'
pod 'UMCShare/Social/ReducedWeChat'
pod 'UMCShare/Social/ReducedQQ'
pod 'UMCShare/Social/Sina'
# 百度地图及定位
pod 'BaiduMapKit'
pod 'BMKLocationKit'
# 乐播投屏
pod 'LBLelinkKit', '30210'
# 阿里云短视频
pod 'AliyunVideoSDKBasic'
pod 'AlivcConan'
pod 'VODUpload'
pod 'QuCore-ThirdParty'

### 开源框架
pod 'SnapKit'
pod 'QMUIKit'
pod 'Moya/RxSwift'
pod 'Kingfisher'
pod 'MJRefresh'
pod 'HandyJSON'
pod 'SwiftDate'
pod 'RxSwift'
pod 'RxCocoa'
pod 'RxDataSources'
pod 'ReachabilitySwift'
pod 'SwiftKeychainWrapper'
pod 'CHIPageControl/Jaloro'
pod 'FSPagerView'
pod 'RealmSwift'
pod 'YYText'

end
```

### Error

```
JSON::ParserError - 785: unexpected token at ''
/Users/xxxx/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/2.7.0/json/common.rb:156:in `parse'
/Users/xxxx/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/2.7.0/json/common.rb:156:in `parse'
/Users/xxxx/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.9.0/lib/cocoapods-core/specification/json.rb:61:in `from_json'
/Users/xxxx/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.9.0/lib/cocoapods-core/specification.rb:742:in `from_string'
/Users/xxxx/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.9.0/lib/cocoapods-core/specification.rb:716:in `from_file'
/Users/xxxx/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.9.0/lib/cocoapods-core/source.rb:186:in `specification'
/Users/xxxx/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.0/lib/cocoapods/resolver/lazy_specification.rb:37:in `specification'
/Users/xxxx/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.0/lib/cocoapods/resolver/lazy_specification.rb:29:in `subspec_by_name'
/Users/xxxx/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.0/lib/cocoapods/resolver.rb:362:in `block in specifications_for_dependency'
/Users/xxxx/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.0/lib/cocoapods/resolver.rb:362:in `map'
/Users/xxxx/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.0/lib/cocoapods/resolver.rb:362:in `specifications_for_dependency'
/Users/xxxx/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.0/lib/cocoapods/resolver.rb:165:in `search_for'
/Users/xxxx/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.0/lib/cocoapods/resolver.rb:274:in `block in sort_dependencies'
/Users/xxxx/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.0/lib/cocoapods/resolver.rb:267:in `each'
/Users/xxxx/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.0/lib/cocoapods/resolver.rb:267:in `sort_by'
/Users/xxxx/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.0/lib/cocoapods/resolver.rb:267:in `sort_dependencies'
/Users/xxxx/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:53:in `block in sort_dependencies'
/Users/xxxx/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:70:in `with_no_such_dependency_error_handling'
/Users/xxxx/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:52:in `sort_dependencies'
/Users/xxxx/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:288:in `initial_state'
/Users/xxxx/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:210:in `start_resolution'
/Users/xxxx/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:168:in `resolve'
/Users/xxxx/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
/Users/xxxx/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.0/lib/cocoapods/resolver.rb:94:in `resolve'
/Users/xxxx/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.0/lib/cocoapods/installer/analyzer.rb:1065:in `block in resolve_dependencies'
/Users/xxxx/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.0/lib/cocoapods/user_interface.rb:64:in `section'
/Users/xxxx/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.0/lib/cocoapods/installer/analyzer.rb:1063:in `resolve_dependencies'
/Users/xxxx/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.0/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/Users/xxxx/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.0/lib/cocoapods/installer.rb:410:in `analyze'
/Users/xxxx/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.0/lib/cocoapods/installer.rb:235:in `block in resolve_dependencies'
/Users/xxxx/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.0/lib/cocoapods/user_interface.rb:64:in `section'
/Users/xxxx/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.0/lib/cocoapods/installer.rb:234:in `resolve_dependencies'
/Users/xxxx/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.0/lib/cocoapods/installer.rb:156:in `install!'
/Users/xxxx/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.0/lib/cocoapods/command/install.rb:52:in `run'
/Users/xxxx/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/xxxx/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.0/lib/cocoapods/command.rb:52:in `run'
/Users/xxxx/.rvm/rubies/ruby-2.7.0-preview1/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.0/bin/pod:55:in `<top (required)>'
/Users/xxxx/.rvm/rubies/ruby-2.7.0-preview1/bin/pod:23:in `load'
/Users/xxxx/.rvm/rubies/ruby-2.7.0-preview1/bin/pod:23:in `<main>'
/Users/xxxx/.rvm/rubies/ruby-2.7.0-preview1/bin/ruby_executable_hooks:24:in `eval'
/Users/xxxx/.rvm/rubies/ruby-2.7.0-preview1/bin/ruby_executable_hooks:24:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

**Comment by dnkoutso** [comment]
This is an insufficient bug report. Have to close.

Please try `pod cache clean --all` as I've seen in other reports and ask in StackOverflow instead.

**Comment by PreSwift** [comment]
> This is an insufficient bug report. Have to close.
> 
> Please try `pod cache clean --all` as I've seen in other reports and ask in StackOverflow instead.

I have try it, but not work.

**Comment by myheart919** [comment]
> > This is an insufficient bug report. Have to close.
> > Please try `pod cache clean --all` as I've seen in other reports and ask in StackOverflow instead.
> 
> I have try it, but not work.

我刚解决，就是升级cocoapods到最新版本后，要pod 的第三方包里有不支持1.9版的，把cococapods 降低版本重新安装就可以了，例如做如下操作降到1.5.3版本：
sudo gem uninstall cocoapods -v 1.9
sudo gem uninstall  cocoapods-core -v 1.9
sudo gem install cocoapods -v 1.5.3
顺便删除之前的Podfile.lock 和 rm -r ~/.cocoapods/repos/trunk/ 目录
希望可以帮到你

**Comment by PreSwift** [comment]
> > > This is an insufficient bug report. Have to close.
> > > Please try `pod cache clean --all` as I've seen in other reports and ask in StackOverflow instead.
> > 
> > 
> > I have try it, but not work.
> 
> 我刚解决，就是升级cocoapods到最新版本后，要pod 的第三方包里有不支持1.9版的，把cococapods 降低版本重新安装就可以了，例如做如下操作降到1.5.3版本：
> sudo gem uninstall cocoapods -v 1.9
> sudo gem uninstall cocoapods-core -v 1.9
> sudo gem install cocoapods -v 1.5.3
> 顺便删除之前的Podfile.lock 和 rm -r ~/.cocoapods/repos/trunk/ 目录
> 希望可以帮到你

原来如此！太感谢了。
