### ISSUE TITLE
Getting error after editing a podspec

### ISSUE THREAD

**Issue by Rajib-Sarwar** [CocoaPods/CocoaPods#9615]
My podspec is validated but when I am trying to register the trunk I am getting the following error message.

### Command

```
/usr/local/bin/pod trunk push
```

### Stack

```
   CocoaPods : 1.8.4
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.2 (19C57)
       Xcode : 11.3 (11C29)
         Git : git version 2.21.0 (Apple Git-122.2)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ 0a408c6898092d952427524578f5ef209018a0ea
               trunk - CDN - https://cdn.cocoapods.org/
               VizuryEventLogger - git - https://ayon-chowdhury@bitbucket.org/ayon-chowdhury/ios-swift-sdk.git @ 135a6e117294f6ff9da1a18821aa3fdb0790cbb1
               VizuryEventLogger-iOS-SDK - git - https://github.com/Rajib-Sarwar/VizuryEventLogger-iOS-SDK.git @ fb13f8a6098dfcd8cb44b848f2f3f486682cf1b5
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Error

```
Netrc::Error - Permission bits for '/Users/ayonchowdhury/.netrc' should be 0600, but are 644
/Library/Ruby/Gems/2.6.0/gems/netrc-0.11.0/lib/netrc.rb:45:in `check_permissions'
/Library/Ruby/Gems/2.6.0/gems/netrc-0.11.0/lib/netrc.rb:52:in `read'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-trunk-1.4.1/lib/pod/command/trunk.rb:106:in `netrc'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-trunk-1.4.1/lib/pod/command/trunk.rb:111:in `token'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-trunk-1.4.1/lib/pod/command/trunk/push.rb:56:in `validate!'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:333:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by Rajib-Sarwar** [comment]
`chmod 0600 .netrc`
run this command and it will solved
