### ISSUE TITLE
idontknowwhattodo

### ISSUE THREAD

**Issue by MrLonelyLovely** [CocoaPods/CocoaPods#9616]
### Command

```
/usr/local/Cellar/cocoapods/1.9.1/libexec/bin/pod update
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.9.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.3 (19D76)
       Xcode : 11.3.1 (11C504)
         Git : git version 2.21.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
#source 'https://github.com/CocoaPods/Specs.git'
source 'https://cdn.cocoapods.org/'
platform :ios, "13.2"

use_frameworks!
target 'SoulMate' do
pod 'LeanCloud', '~> 17.5.2'
pod 'AVOSCloud','~> 12.1.2'
pod 'AVOSCloudIM'
pod 'AVOSCloudLiveQuery'

end
```

### Error

```
JSON::ParserError - 416: unexpected token at '"AVOS/AVOSCloudIM/Message/AVIMMessage'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/usr/local/Cellar/cocoapods/1.9.1/libexec/gems/cocoapods-core-1.9.1/lib/cocoapods-core/specification/json.rb:61:in `from_json'
/usr/local/Cellar/cocoapods/1.9.1/libexec/gems/cocoapods-core-1.9.1/lib/cocoapods-core/specification.rb:742:in `from_string'
/usr/local/Cellar/cocoapods/1.9.1/libexec/gems/cocoapods-core-1.9.1/lib/cocoapods-core/specification.rb:716:in `from_file'
/usr/local/Cellar/cocoapods/1.9.1/libexec/gems/cocoapods-core-1.9.1/lib/cocoapods-core/source.rb:186:in `specification'
/usr/local/Cellar/cocoapods/1.9.1/libexec/gems/cocoapods-1.9.1/lib/cocoapods/resolver/lazy_specification.rb:37:in `specification'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:348:in `block in delegating_block'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:349:in `block in delegating_block'
/usr/local/Cellar/cocoapods/1.9.1/libexec/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:178:in `dependencies_for'
/usr/local/Cellar/cocoapods/1.9.1/libexec/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:18:in `block in dependencies_for'
/usr/local/Cellar/cocoapods/1.9.1/libexec/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:70:in `with_no_such_dependency_error_handling'
/usr/local/Cellar/cocoapods/1.9.1/libexec/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:17:in `dependencies_for'
/usr/local/Cellar/cocoapods/1.9.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:807:in `block in group_possibilities'
/usr/local/Cellar/cocoapods/1.9.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:806:in `reverse_each'
/usr/local/Cellar/cocoapods/1.9.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:806:in `group_possibilities'
/usr/local/Cellar/cocoapods/1.9.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:778:in `possibilities_for_requirement'
/usr/local/Cellar/cocoapods/1.9.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:761:in `push_state_for_requirements'
/usr/local/Cellar/cocoapods/1.9.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:746:in `require_nested_dependencies_for'
/usr/local/Cellar/cocoapods/1.9.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:729:in `activate_new_spec'
/usr/local/Cellar/cocoapods/1.9.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:686:in `attempt_to_activate'
/usr/local/Cellar/cocoapods/1.9.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:254:in `process_topmost_state'
/usr/local/Cellar/cocoapods/1.9.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
/usr/local/Cellar/cocoapods/1.9.1/libexec/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
/usr/local/Cellar/cocoapods/1.9.1/libexec/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:94:in `resolve'
/usr/local/Cellar/cocoapods/1.9.1/libexec/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:1065:in `block in resolve_dependencies'
/usr/local/Cellar/cocoapods/1.9.1/libexec/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/Cellar/cocoapods/1.9.1/libexec/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:1063:in `resolve_dependencies'
/usr/local/Cellar/cocoapods/1.9.1/libexec/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/usr/local/Cellar/cocoapods/1.9.1/libexec/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:410:in `analyze'
/usr/local/Cellar/cocoapods/1.9.1/libexec/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:235:in `block in resolve_dependencies'
/usr/local/Cellar/cocoapods/1.9.1/libexec/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/Cellar/cocoapods/1.9.1/libexec/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:234:in `resolve_dependencies'
/usr/local/Cellar/cocoapods/1.9.1/libexec/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:156:in `install!'
/usr/local/Cellar/cocoapods/1.9.1/libexec/gems/cocoapods-1.9.1/lib/cocoapods/command/update.rb:63:in `run'
/usr/local/Cellar/cocoapods/1.9.1/libexec/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/usr/local/Cellar/cocoapods/1.9.1/libexec/gems/cocoapods-1.9.1/lib/cocoapods/command.rb:52:in `run'
/usr/local/Cellar/cocoapods/1.9.1/libexec/gems/cocoapods-1.9.1/bin/pod:55:in `<top (required)>'
/usr/local/Cellar/cocoapods/1.9.1/libexec/bin/pod:23:in `load'
/usr/local/Cellar/cocoapods/1.9.1/libexec/bin/pod:23:in `<main>'
```

**Comment by dxn1988** [comment]
Exactly the same error output as yours when running `pod outdated`

**Comment by dnkoutso** [comment]
Please see https://github.com/CocoaPods/CocoaPods/issues/9611 as a duplicate. We have been unable to repro this case and could use some help with clear reproducible steps or someone to diagnose.
