### ISSUE TITLE
NoMethodError - undefined method `module_map_file_to_import' for nil:NilClass

### ISSUE THREAD

**Issue by vzsg** [CocoaPods/CocoaPods#9627]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md). 🌈

# Report

## What did you do?

I have a larger project with custom build configurations and two targets – one app and one extension target – which pulls in dependencies into both the app and the extension. With 1.8.4 and previous versions, everything worked normally.

Then I updated to 1.9.1, tried to run `pod install`, and got the error dump below.

## What did you expect to happen?

That the Pods project is successfully generated and the solution works.

## What happened instead?

The `pod install` command dies at the "Generating Pods project" stage with the following error:

```
NoMethodError - undefined method `module_map_file_to_import' for nil:NilClass
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/target/build_settings.rb:1131:in `block (2 levels) in <class:AggregateTargetSettings>'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/target/build_settings.rb:1131:in `map'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/target/build_settings.rb:1131:in `block in <class:AggregateTargetSettings>'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/target/build_settings.rb:114:in `block in define_build_settings_method'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/target/build_settings.rb:275:in `block in <class:BuildSettings>'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/target/build_settings.rb:1108:in `block in <class:AggregateTargetSettings>'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/target/build_settings.rb:114:in `block in define_build_settings_method'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/target/build_settings.rb:362:in `public_send'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/target/build_settings.rb:362:in `block in to_h'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/target/build_settings.rb:361:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/target/build_settings.rb:361:in `to_h'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/target/build_settings.rb:174:in `block in <class:BuildSettings>'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/target/build_settings.rb:1032:in `block in <class:AggregateTargetSettings>'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/target/build_settings.rb:114:in `block in define_build_settings_method'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/xcode/pods_project_generator/target_installer_helper.rb:16:in `update_changed_file'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:103:in `block in create_xcconfig_file'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:99:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:99:in `create_xcconfig_file'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:18:in `block in install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.rb:145:in `message'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:14:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:130:in `block (2 levels) in install_aggregate_targets'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:128:in `map'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:128:in `block in install_aggregate_targets'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.rb:145:in `message'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:127:in `install_aggregate_targets'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/xcode/single_pods_project_generator.rb:20:in `generate!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:308:in `block in create_and_save_projects'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:303:in `create_and_save_projects'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:295:in `generate_pods_project'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:174:in `integrate'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:162:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

The top entry of the stacktrace is this function:

```ruby
# @return [Array<String>]
define_build_settings_method :module_map_files, :memoized => true, :sorted => true, :uniqued => true, :compacted => true, :from_search_paths_aggregate_targets => :module_map_file_to_import do
    pod_targets.map { |pt| pt.build_settings[@configuration].module_map_file_to_import }
end
```
I added a `puts` call to the map to see what's in the `pt.build_settings` hash. It seems that for the OneSignal pod of the extension, no `debug` configuration was generated, only `release`. Thus the lookup indeed returns a nil.

### Stack

```
   CocoaPods : 1.9.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.3 (19D76)
       Xcode : 11.3.1 (11C505)
         Git : git version 2.21.1 (Apple Git-122.3)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ 280c9ab066a6132186c7a3122c1f34b663ac97b4

               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
workspace 'REDACTED.xcworkspace'

target 'REDACTED' do
  project 'REDACTED',
    'REDACTED CONFIG1 Debug' => :debug,
    'REDACTED CONFIG1 Release' => :release,
    'REDACTED CONFIG2 Debug' => :debug,
    'REDACTED CONFIG2 Release' => :release
  use_frameworks!

  pod 'OneSignal'
end

target 'OneSignalNotificationServiceExtension' do
  use_frameworks!
  pod 'OneSignal'
end
```

## Project that demonstrates the issue

(EDITED) Here is a minimal reproduction project: [ProjectMappingNilError.zip](https://github.com/CocoaPods/CocoaPods/files/4356863/ProjectMappingNilError.zip). As noted in the discussion below and the comments in the Podfile, moving the build configuration mapping up to the global scope fixes the crash.

**Comment by dnkoutso** [comment]
Ah might be a bug actually. Thanks for the report. Think you can investigate and make a PR with a test?

**Comment by dnkoutso** [comment]
Probably putting `puts` statements and debug as you did is the best way for me.

**Comment by vzsg** [comment]
Well, I've never really used Ruby, but I'll digging deeper.

**Comment by dnkoutso** [comment]
Its OK! I had no idea about Ruby when I started with CocoaPods development.

**Comment by vzsg** [comment]
I've managed to setup RubyMine for debugging into CocoaPods. It seems that for the extension, all configurations are detected as `:release`.

![image](https://user-images.githubusercontent.com/1783465/77109605-7d31bd00-6a24-11ea-9fff-8a0ec5bd5e11.png)

But for the application target, half of them are `:debug`... Drilling deeper.

**Comment by vzsg** [comment]
Actually, by stepping through the analyzer I realized what's happening and what's different between the working and not working projects – and it's my fault.

In my Podfile above the `project` keyword was under the `target`, and thus the mapping was not visible from the other target. Moving it out to the global scope fixed the error.

---

So what happens makes sense, but perhaps it could be handled more gracefully, either making both `:debug` and `:release` target definitions regardless of what configurations were found, or with a better error message with hinting at the mistake?

**Comment by dnkoutso** [comment]
perhaps yes, thanks though for the investigation! A better error message if its easy and feasible would be good.

**Comment by vzsg** [comment]
I know that was just a bot message, but 1.9.3 did not change anything.

---

Unfortunately, I haven't had the time to investigate what could be done about catching and explaining the error.
