### ISSUE TITLE
Failure to Install Libraries with Cocoapods Suddenly.

### ISSUE THREAD

**Issue by fumiyasac** [CocoaPods/CocoaPods#9631]
Hi, 
I occur a strange error installing libraries with Cocoapods. So I never find out cause and fix this problems.
I hope this issue help users have problems about complicated errors of Cocoapods.
Thanks.

### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?
→ Error messages is below:
```
RuntimeError - Unsupported workspace file reference type `build`
```

* What did you expect to happen?
→ Very simple, enable to cocoapods!

### Stack

```
   CocoaPods : 1.9.1
        Ruby : ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-darwin19]
    RubyGems : 3.0.1
        Host : Mac OS X 10.15.2 (19C57)
       Xcode : 11.3.1 (11C505)
         Git : git version 2.22.0
Ruby lib dir : /Users/sakaifumiya/.rbenv/versions/2.6.0/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VisualEffectTraceExample' do
  use_frameworks!

  # Pods for VisualEffectTraceExample

  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'ReSwift'
  pod 'RealmSwift'
  pod 'KeychainAccess'
  pod 'DifferenceKit'

  pod 'ESPullToRefresh'
  pod 'ESTabBarController-swift'
  pod 'PanModal'
  pod 'AirBar', '~> 2.0'
  pod 'YPImagePicker'
  pod 'ExpandingMenu', '~> 0.4'
  pod 'Loaf'
  pod 'NVActivityIndicatorView'
  pod 'AnimatedCollectionViewLayout'
  pod 'Nuke'

  pod 'XCGLogger', '~> 7.0.1'
  pod 'ReSwiftMonitor', :configurations => ['Debug']
end
```

### Error

```
RuntimeError - Unsupported workspace file reference type `build`
/Users/sakaifumiya/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/xcodeproj-1.15.0/lib/xcodeproj/workspace/file_reference.rb:74:in `absolute_path'
/Users/sakaifumiya/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/xcodeproj-1.15.0/lib/xcodeproj/workspace.rb:203:in `block in load_schemes'
/Users/sakaifumiya/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/xcodeproj-1.15.0/lib/xcodeproj/workspace.rb:202:in `each'
/Users/sakaifumiya/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/xcodeproj-1.15.0/lib/xcodeproj/workspace.rb:202:in `load_schemes'
/Users/sakaifumiya/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/xcodeproj-1.15.0/lib/xcodeproj/workspace.rb:85:in `from_s'
/Users/sakaifumiya/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/xcodeproj-1.15.0/lib/xcodeproj/workspace.rb:66:in `new_from_xcworkspace'
/Users/sakaifumiya/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/user_project_integrator.rb:102:in `create_workspace'
/Users/sakaifumiya/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/user_project_integrator.rb:71:in `integrate!'
/Users/sakaifumiya/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:801:in `block in integrate_user_project'
/Users/sakaifumiya/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/sakaifumiya/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:797:in `integrate_user_project'
/Users/sakaifumiya/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:176:in `integrate'
/Users/sakaifumiya/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:162:in `install!'
/Users/sakaifumiya/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command/install.rb:52:in `run'
/Users/sakaifumiya/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/sakaifumiya/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command.rb:52:in `run'
/Users/sakaifumiya/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by fumiyasac** [comment]
__【Temporary Solution】__

Maybe, I find out temporary solution is below:

(1) physical delete these files: 

```
- ●●●●.xcworkspace
- Podfile.lock
- Pods/*
```

(2) run `pod install`

In my project, it was successful but not confident.

**Comment by dnkoutso** [comment]
Need a sample app here demonstrating the issue.

**Comment by fumiyasac** [comment]
Hi, @dnkoutso Sample project is below:
https://github.com/fumiyasac/VisualEffectTraceExample/tree/master/VisualEffectTraceExample
If you need only iOS project. I will prepare zip file.

**Comment by paulb777** [comment]
Seems to work fine for me:
```
$ pod install
Analyzing dependencies
Downloading dependencies
Installing AirBar (2.0.5)
Installing AnimatedCollectionViewLayout (1.0.1)
Installing DifferenceKit (1.1.5)
Installing ESPullToRefresh (2.9.2)
Installing ESTabBarController-swift (2.8.0)
Installing ExpandingMenu (0.4.0)
Installing KeychainAccess (4.1.0)
Installing Kingfisher (5.13.2)
Installing Loaf (0.5.0)
Installing NVActivityIndicatorView (4.8.0)
Installing PanModal (1.2.5)
Installing PryntTrimmerView (4.0.0)
Installing ReSwift (5.0.0)
Installing Realm (4.3.2)
Installing RealmSwift (4.3.2)
Installing RxCocoa (5.1.0)
Installing RxRelay (5.1.0)
Installing RxSwift (5.1.0)
Installing SteviaLayout (4.7.3)
Installing YPImagePicker (4.2.0)
Generating Pods project
Integrating client project
Pod installation complete! There are 16 dependencies from the Podfile and 20 total pods installed.

[!] Automatically assigning platform `iOS` with version `13.1` on target `VisualEffectTraceExample` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
$ pod --version
1.9.1
```

**Comment by dnkoutso** [comment]
Same for me this works.

**Comment by dnkoutso** [comment]
@fumiyasac we cannot reproduce with the sample you provided. Please upload another one and confirm it crashes.

**Comment by fumiyasac** [comment]
@paulb777  @dnkoutso 
Thank you for researching! After 2 days later, I tried re-install CocoaPods and execute command, it worked fine my projects. Maybe, it seems not CocoaPods error.
So would you close this issue?

**Comment by madeofmoney** [comment]
This is a real issue and happening on Xcode 12 as well.

**Comment by madeofmoney** [comment]
[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=Unsupported+workspace+file+reference+type+%60build%60&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
 - Failure to Install Libraries with Cocoapods Suddenly.
   https://github.com/CocoaPods/CocoaPods/issues/9631 [closed] [7 comments]
   23 Mar 2020

 - what's wrong with it
   https://github.com/CocoaPods/CocoaPods/issues/8769 [closed] [4 comments]
   22 Feb 2020

 - Resources installed using cocoapods not loaded for xctest bundle
   https://github.com/CocoaPods/CocoaPods/issues/4752 [closed] [47 comments]
   31 Jul 2018

and 1 more at:
https://github.com/cocoapods/cocoapods/search?q=Unsupported%20workspace%20file%20reference%20type%20%60build%60&type=Issues&utf8=✓
adamdahan@Adams-Air-2 silvereskimo-ios-master %
