### ISSUE TITLE
ArgumentError - Malformed version number string ~> 4.0

### ISSUE THREAD

**Issue by 350541732** [CocoaPods/CocoaPods#9667]
* [✔️] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ update some SDK update to swift5.0 via cocoapods

## What did you expect to happen?

ℹ it can install mormal

## What happened instead?

ℹ ArgumentError - Malformed version number string ~> 4.0........

## CocoaPods Environment

ℹ 
```
   CocoaPods : 1.9.0
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin19]
    RubyGems : 2.7.6
        Host : Mac OS X 10.15.2 (19C57)
       Xcode : 11.3.1 (11C504)
         Git : git version 2.26.0
Ruby lib dir : /Users/liguicheng/.rvm/rubies/ruby-2.6.3/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ 6b81ae921e661479ee1be98bd85a66b13ebd0a24

               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /Users/liguicheng/.rvm/gems/ruby-2.6.3/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
use_frameworks!

target 'SwiftLeeTools_Example' do
  pod 'SwiftLeeTools', :path => '../'

  target 'SwiftLeeTools_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
```

## Detail
i write a SDK for ios, in this SDK it has some dependencice. eg, i want update Alamofire to swift 5.0.
my  old podspec:
```
Pod::Spec.new do |s|
  s.name             = 'SwiftLeeTools'
  s.version          = '0.1.6.2'
  s.summary          = 'A short description of SwiftLeeTools.'

  #指定版本
  s.swift_versions = '5.0'
  s.description      = <<-DESC
"iOS swift开发通用工具 包括UIKit foundation 网络封装 等"
                       DESC

  s.homepage         = 'https://github.com/350541732/SwiftLeeTools'
  # s.screenshots     = 'www.example.com/screenshots_1', 'www.example.com/screenshots_2'
  s.license          = { :type => 'MIT', :file => 'LICENSE' }
  s.author           = { 'LeeSin' => '350541732@qq.com' }
  s.source           = { :git => 'https://github.com/350541732/SwiftLeeTools.git', :tag => s.version.to_s }
  # s.social_media_url = 'https://twitter.com/<TWITTER_USERNAME>'
  s.ios.deployment_target = '10.0'
  s.source_files = 'SwiftLeeTools/Classes/**/*' 
   s.resource_bundles = {
     'SwiftLeeTools' => ['SwiftLeeTools/Assets/*.png']
   }
  s.dependency 'Alamofire', '~> 4.7' #网络请求
  s.dependency 'SwiftyJSON', '~> 4.0' #Json数据处理
  s.dependency 'QorumLogs'
  s.dependency 'SnapKit', '~> 4.0.0' #自动布局'
  # s.dependency 'Hero'
  s.dependency 'IQKeyboardManagerSwift'
  s.dependency 'AlamofireImage'
  s.dependency 'DeviceKit'               #设备信息
  s.dependency 'ImageSlideshow/Alamofire'
  s.dependency 'MJRefresh' #上拉刷新 下拉加载
  s.dependency 'SwiftDate', '~> 5.1.0'  #时间工具
  s.dependency 'JXSegmentedView' #切换滚动式图 https://github.com/pujiaxin33/JXSegmentedView
  s.dependency 'ReachabilitySwift'
  s.dependency 'RealmSwift' #Realm 数据库
  s.dependency 'CryptoSwift'#加密
end
```
and when i set  s.dependency 'Alamofire', '~> 5.0 ' and  s.dependency 'AlamofireImage', '~> 4.0' it show 
```
rgumentError - Malformed version number string ~> 4.0
/Users/.rvm/gems/ruby-2.6.3/gems/cocoapods-core-1.9.0/lib/cocoapods-core/version.rb:47:in `initialize'
/Users/.rvm/gems/ruby-2.6.3/gems/cocoapods-core-1.9.0/lib/cocoapods-core/vendor/version.rb:199:in `new'
/Users//.rvm/gems/ruby-2.6.3/gems/cocoapods-core-1.9.0/lib/cocoapods-core/vendor/version.rb:199:in `new'
```

**Comment by dnkoutso** [comment]
I cannot reproduce this. Will need a sample app uploaded with clear steps to repro.

**Comment by srisuk2519** [comment]
เมื่อ ส. 20 มิ.ย. 2563 เวลา 13:34 D. Koutsogiorgas <notifications@github.com>
เขียนว่า:
