### ISSUE TITLE
Pod install results in JSON::ParserError - 767. Trying to install pod 'Firebase/Firestore'

### ISSUE THREAD

**Issue by Sparrownor1** [CocoaPods/CocoaPods#9694]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod install`

## What did you expect to happen?

Install all pod dependencies correctly.

### Error

```
JSON::ParserError - 767: unexpected token at ''
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/specification/json.rb:61:in `from_json'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/specification.rb:742:in `from_string'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/specification.rb:716:in `from_file'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/source.rb:186:in `specification'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/specification/set.rb:58:in `block in specification_name'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/specification/set.rb:56:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/specification/set.rb:56:in `specification_name'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/cdn_source.rb:216:in `search'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/source/aggregate.rb:83:in `block in search'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/source/aggregate.rb:83:in `select'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/source/aggregate.rb:83:in `search'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:416:in `create_set_from_sources'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:385:in `find_cached_set'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:360:in `specifications_for_dependency'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:165:in `search_for'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:274:in `block in sort_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:267:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:267:in `sort_by'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:267:in `sort_dependencies'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:53:in `block in sort_dependencies'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:70:in `with_no_such_dependency_error_handling'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:52:in `sort_dependencies'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:288:in `initial_state'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:210:in `start_resolution'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:168:in `resolve'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:94:in `resolve'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:1065:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:1063:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:410:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:235:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:234:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:156:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

### Stack

```
   CocoaPods : 1.9.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.4 (19E266)
       Xcode : 11.3.1 (11C504)
         Git : git version 2.21.1 (Apple Git-122.3)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sustain' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sustain
  pod 'Firebase/Firestore'

  target 'SustainTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SustainUITests' do
    # Pods for testing
  end

end
```

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

**Comment by dnkoutso** [comment]
Please search for existing issues first. This is already filed and tracked here https://github.com/CocoaPods/CocoaPods/issues/9672 and we need help to diagnose/debug as we cannot reproduce.

**Comment by Sparrownor1** [comment]
@dnkoutso I had been searching around these issues but was not able to find a solution that worked. I tried the ones involving reinstalling and cache clearing which did not help. That is why I decided to file my own issue, especially as I saw the JSON parser error was a different error code. Apologies for the inconvenience. Do you advise that I just follow #9762 ?

**Comment by dnkoutso** [comment]
@Sparrownor1 sorry it my tone was strict. I did not mean to sound like that. I will update it. I think following workarounds in #9762 is OK for sure if it helps with your issue, but even better would be to help us diagnose this I think its a response from CDN not being valid JSON format.

**Comment by Sparrownor1** [comment]
@dnkoutso I have been manually copy-pasting the contents of each empty pod spec file from the GitHub, and now pod install seems to have worked.
Final output from pod install:
```
Downloading dependencies
Installing BoringSSL-GRPC (0.0.3)
Installing Firebase (6.21.0)
Installing FirebaseAuthInterop (1.1.0)
Installing FirebaseCore (6.6.5)
Installing FirebaseCoreDiagnostics (1.2.2)
Installing FirebaseCoreDiagnosticsInterop (1.2.0)
Installing FirebaseFirestore (1.11.2)
Installing GoogleDataTransport (5.1.0)
Installing GoogleDataTransportCCTSupport (2.0.1)
Installing GoogleUtilities (6.5.2)
Installing abseil (0.20190808)
Installing gRPC-C++ (0.0.9)
Installing gRPC-Core (1.21.0)
Installing leveldb-library (1.22)
Installing nanopb (0.3.9011)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `Sustain.xcworkspace` for this project from now on.
Pod installation complete! There is 1 dependency from the Podfile and 15 total pods installed.

[!] Automatically assigning platform `iOS` with version `13.2` on target `Sustain` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
```

**Comment by DevarajNiOS** [comment]
if any one is having similar issue (i.e JSON::ParserError 767) because of "Materialcomponents/*" , this link might help https://github.com/CocoaPods/CocoaPods/issues/9611#issuecomment-599125090.

**Comment by aimanzakikagzi** [comment]
For me, 
```
rm -rf ~/.cocoapods/repos/trunk/
pod install
```

did the trick and it worked.

**Comment by arvyHL** [comment]
Delete the pods file before these command:

`rm -rf ~/.cocoapods/repos/trunk/
pod install`

**Comment by Haibo-Zhou** [comment]
> Delete the pods folder before these command:
> 
> > rm -rf ~/.cocoapods/repos/trunk/
> > pod install

That is worked on me, thank you!

**Comment by Haohao5** [comment]
> For me,
> 
> ```
> rm -rf ~/.cocoapods/repos/trunk/
> pod install
> ```
> 
> did the trick and it worked.

it's worked on me!thanks!

**Comment by QL31** [comment]
> if any one is having similar issue (i.e JSON::ParserError 767) because of "Materialcomponents/*" , this link might help [#9611 (comment)](https://github.com/CocoaPods/CocoaPods/issues/9611#issuecomment-599125090).
> 
> For me below commands worked.
> rm -rf ~/.cocoapods/repos/trunk/
> pod install

It's worked, many thanks

**Comment by balasvctest** [comment]
> Delete the pods folder before these command:
> 
> > rm -rf ~/.cocoapods/repos/trunk/
> > pod install

This worked! Thank you!

**Comment by phoenixsachin** [comment]
> For me,
> 
> ```
> rm -rf ~/.cocoapods/repos/trunk/
> pod install
> ```
> 
> did the trick and it worked.

thanks bro

**Comment by GaboRocker1992** [comment]
I have a mini Mac with apple m2 chip.
This worked for me:
On podfile
comment this: :flipper_configuration => flipper_config,
and add this use_frameworks! :linkage => :static ( after config = use_native_modules! )

and run pod install
