### ISSUE TITLE
pod command fails with '_ffi_prep_cif_var' missing

### ISSUE THREAD

**Issue by buzmeg** [CocoaPods/CocoaPods#9721]
OS X 10.14.6 with Xcode Version 11.2.1 (11B500)

Attempting to install cocoapods from both gem and homebrew fails.  Simply running the pod command crashes:

```
$ uname -a
Darwin MacBook-Pro 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64
$ which ruby
/usr/bin/ruby
$ ruby --version
ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
$ brew install cocoapods
==> Downloading https://homebrew.bintray.com/bottles/cocoapods-1.9.1.mojave.bottle.tar.gz
==> Pouring cocoapods-1.9.1.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/cocoapods/1.9.1: 12,742 files, 30.1MB
$ which ruby
/usr/bin/ruby
$ pod setup
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require': dlopen(/Library/Ruby/Gems/2.3.0/gems/ffi-1.12.2/lib/ffi_c.bundle, 0x0009): symbol '_ffi_prep_cif_var' not found, expected in flat namespace by '/Library/Ruby/Gems/2.3.0/gems/ffi-1.12.2/lib/ffi_c.bundle' - /Library/Ruby/Gems/2.3.0/gems/ffi-1.12.2/lib/ffi_c.bundle (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/ffi-1.12.2/lib/ffi.rb:6:in `rescue in <top (required)>'
	from /Library/Ruby/Gems/2.3.0/gems/ffi-1.12.2/lib/ffi.rb:3:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/ethon-0.12.0/lib/ethon.rb:2:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/typhoeus-1.3.1/lib/typhoeus.rb:2:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/Cellar/cocoapods/1.9.1/libexec/gems/cocoapods-1.9.1/lib/cocoapods/sources_manager.rb:5:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/Cellar/cocoapods/1.9.1/libexec/gems/cocoapods-1.9.1/lib/cocoapods/core_overrides.rb:1:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/Cellar/cocoapods/1.9.1/libexec/gems/cocoapods-1.9.1/lib/cocoapods.rb:75:in `<module:Pod>'
	from /usr/local/Cellar/cocoapods/1.9.1/libexec/gems/cocoapods-1.9.1/lib/cocoapods.rb:17:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /usr/local/Cellar/cocoapods/1.9.1/libexec/gems/cocoapods-1.9.1/bin/pod:36:in `<top (required)>'
	from /usr/local/Cellar/cocoapods/1.9.1/libexec/bin/pod:22:in `load'
	from /usr/local/Cellar/cocoapods/1.9.1/libexec/bin/pod:22:in `<main>'
$ brew uninstall cocoapods
Uninstalling /usr/local/Cellar/cocoapods/1.9.1... (12,742 files, 30.1MB)
$ sudo gem install cocoapods
Password:
Fetching: cocoapods-1.9.1.gem (100%)
Successfully installed cocoapods-1.9.1
Parsing documentation for cocoapods-1.9.1
Installing ri documentation for cocoapods-1.9.1
Done installing documentation for cocoapods after 5 seconds
1 gem installed
$ pod setup
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': dlopen(/Library/Ruby/Gems/2.3.0/gems/ffi-1.12.2/lib/ffi_c.bundle, 0x0009): symbol '_ffi_prep_cif_var' not found, expected in flat namespace by '/Library/Ruby/Gems/2.3.0/gems/ffi-1.12.2/lib/ffi_c.bundle' - /Library/Ruby/Gems/2.3.0/gems/ffi-1.12.2/lib/ffi_c.bundle (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/ffi-1.12.2/lib/ffi.rb:6:in `rescue in <top (required)>'
	from /Library/Ruby/Gems/2.3.0/gems/ffi-1.12.2/lib/ffi.rb:3:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/ethon-0.12.0/lib/ethon.rb:2:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/typhoeus-1.3.1/lib/typhoeus.rb:2:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/sources_manager.rb:5:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods/core_overrides.rb:1:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods.rb:75:in `<module:Pod>'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/lib/cocoapods.rb:17:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.1/bin/pod:36:in `<top (required)>'
	from /usr/local/bin/pod:22:in `load'
	from /usr/local/bin/pod:22:in `<main>'
$ which pod
/usr/local/bin/pod

```

**Comment by dnkoutso** [comment]
Unsure whats going on here. Best to ask StackOverflow. I'd imagine if this was a general issue it would have widespread effect so something tells me its in your environment that is causing this.

**Comment by amorde** [comment]
Can you try `gem pristine ffi`?

**Comment by buzmeg** [comment]
It did something, unfortunately, no change on reinstall.  pod command still crashes.

```sudo gem pristine ffi
Password:
Restoring gems to pristine condition...
Building native extensions.  This could take a while...
Restored ffi-1.12.2
```

**Comment by dnkoutso** [comment]
maybe try `gem pristine --all`?

**Comment by buzmeg** [comment]
It did something, but it still is crashing with the same complaint.

```$ sudo gem pristine ffi
Password:
Restoring gems to pristine condition...
Building native extensions.  This could take a while...
Restored ffi-1.12.2
```

**Comment by dnkoutso** [comment]
sorry not sure what the problem is

**Comment by buzmeg** [comment]
StackOverflow was no help either.
https://stackoverflow.com/questions/61283785/cocoapods-install-failing-due-to-missing-ffi-prep-cif-var

**Comment by dnkoutso** [comment]
See this https://github.com/ffi/ffi/issues/687?

Close this as again I dont think its something we can change here to fix.

We can continue discussion

**Comment by buzmeg** [comment]
Please reopen this.  You don't get off that easily. :)

macOS Mojave 10.14.6 (18G103)

Somebody in Ruby-land is making an assumption about libffi that isn't correct.

There is only one libffi on my system that isn't buried inside an application:
```
$ locate libffi | grep -v Xcode
/Applications/Aquamacs.app/Contents/MacOS/lib/libffi.6.dylib
/Applications/Emacs.app/Contents/MacOS/lib-x86_64-10_7/libffi.6.dylib
/Applications/Emacs.app/Contents/MacOS/lib-x86_64-10_9/libffi.6.dylib
/Applications/Inkscape.app/Contents/Resources/lib/libffi.6.dylib
/Applications/VMware Fusion.app/Contents/Frameworks/libffi.5.dylib
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/libffi.tbd
/usr/lib/libffi.dylib
```

That libffi does *NOT* have the symbol required:

```
$ ls -al /usr/lib/libffi.dylib
-rwxr-xr-x  1 root  wheel  47568 Sep 20  2019 /usr/lib/libffi.dylib

$ nm -a /usr/lib/libffi.dylib | grep -i cif
0000000000001cd0 T _ffi_prep_cif
00000000000011f8 T _ffi_prep_cif_machdep
00000d06 T _ffi_prep_cif
00000b1c T _ffi_prep_cif_machdep
```

Once thing to note is that libffi.5.dylib does *not* have ffi_prep_cif_var while libffi.6.dylib does.

**Comment by buzmeg** [comment]
Nevermind.  Leave it closed.

Bye.

**Comment by amorde** [comment]
@buzmeg please be respectful, there are only a few people who respond & triage issues on this repo when we get a lot of issue submission. I have **175** unread notifications on this repo alone.

Regarding the actual issue, none of us are experiencing this so it's hard for us to know whats happening here, and we aren't experts on `libffi`. 

Did you try the steps mentioned in [this comment](https://github.com/ffi/ffi/issues/687#issuecomment-468005152)?

**Comment by buzmeg** [comment]
@amorde  "Not our problem. Force Close.  Discuss more."  and then blowing someone off is a pretty strong statement--and it's not a "respectful" one.

Anyhow ... the usage of Homebrew also fails with the same complaint unless I *really* go out of my way to redirect everything to local repositories and purge the local ruby.  This then bangs into dependencies from Xcode and macOS.

At this point, just leave the issue closed.  We routed around the CocoaPods dependency so I'm not really set up to continue debugging anymore.

Thanks for at least responding.  It is much appreciated.

Good luck with the backlog.

**Comment by dnkoutso** [comment]
Agree that maybe my response was a bit brush off but I personally do not have the time to diagnose every single issue on every single machine or configuration. 

I understand and respect your frustration but I do not know what is wrong in this case. 

I am going to re-open the issue but know that issues are auto-closed due to inactivity, therefore if noone jumps in it will be closed again.

**Comment by dnkoutso** [comment]
We also tried a couple of suggestions in the beginning of the thread.

**Comment by buzmeg** [comment]
> I am going to re-open the issue but know that issues are auto-closed due to inactivity, therefore if noone jumps in it will be closed again.

It's fine for a bug to auto-close after some amount of time.  I'm used to about 1/3 of my reported bugs being auto-closed.  Quite often I'm doing something off the happy path and fully understand that it falls far below the threshold for opportunity cost.

But please don't force an unresolved issue into closed without confirmation from the original author.  There's no VP of Engineering sitting over our shoulders complaining about the "bug closure rate", "number of outstanding bugs", or "average time to bug closure" metrics out here.

Good luck with stuff.

**Comment by mobile-davinder** [comment]
> gem pristine --all

It works for me

Thanks @dnkoutso

**Comment by buzmeg** [comment]
Close as unresolved.
