### ISSUE TITLE
undefined method `empty?' for nil:NilClass at target_validator.rb:118 when changing swift_versions in pre_install step

### ISSUE THREAD

**Issue by acecilia** [CocoaPods/CocoaPods#9745]
* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Got the following `Podfile`:

```ruby
use_frameworks!
platform :ios, '11.0'

pod 'InputMask', '4.2.0'

pre_install do |installer|
  installer.analysis_result.specifications.each do |s|
    s.swift_versions << '4.2' if s.swift_versions.empty?
  end
end
```

## What did you expect to happen?

`pod install` does not crash

## What happened instead?

`pod install` crashed with:

```
NoMethodError - undefined method `empty?' for nil:NilClass
/Users/user/Desktop/vendor/bundle/ruby/2.6.0/bundler/gems/Cocoapods-2b774aa58f1e/lib/cocoapods/installer/xcode/target_validator.rb:118:in `block in verify_swift_pods_swift_version'
```

## CocoaPods Environment

Tested with cocoapods versions:
- `1.8.4`: not crashing
- `1.9.1`: crashing
- latest on master at the time of writing: crashing

Catalina 10.15.4, Xcode 11.3.1.

## Project that demonstrates the issue

Just run `pod install` in the `Podfile` I shown above.

Looks similar issue than the one explained in https://github.com/CocoaPods/CocoaPods/pull/9688

**Comment by dnkoutso** [comment]
Its because the `Podfile` has no `target` declaration. Not super related I dont think to #9688.

**Comment by acecilia** [comment]
Hi @dnkoutso:

Thanks for the quick fix. I just tested master with the following podfile (just run `pod install`):

```
use_frameworks!
platform :ios, '11.0'
workspace 'All'

pod 'InputMask', '4.2.0'

pre_install do |installer|
  installer.analysis_result.specifications.each do |s|
    s.swift_versions << '4.2' if s.swift_versions.empty?
  end
end
```

The command fails as follows:

```
[!] An error occurred while processing the post-integrate hook of the Podfile.

undefined method `post_integrate!' for #<Pod::Podfile:0x00007fe43c8a9ad0>
Did you mean?  post_install!

/Users/user/Git/SampleCocoapodsProject/vendor/bundle/ruby/2.6.0/bundler/gems/CocoaPods-b812daedb782/lib/cocoapods/installer.rb:903:in `run_podfile_post_integrate_hook'
/Users/user/Git/SampleCocoapodsProject/vendor/bundle/ruby/2.6.0/bundler/gems/CocoaPods-b812daedb782/lib/cocoapods/installer.rb:891:in `block in run_podfile_post_integrate_hooks'
/Users/user/Git/SampleCocoapodsProject/vendor/bundle/ruby/2.6.0/bundler/gems/CocoaPods-b812daedb782/lib/cocoapods/user_interface.rb:145:in `message'
/Users/user/Git/SampleCocoapodsProject/vendor/bundle/ruby/2.6.0/bundler/gems/CocoaPods-b812daedb782/lib/cocoapods/installer.rb:890:in `run_podfile_post_integrate_hooks'
/Users/user/Git/SampleCocoapodsProject/vendor/bundle/ruby/2.6.0/bundler/gems/CocoaPods-b812daedb782/lib/cocoapods/installer.rb:819:in `block in integrate_user_project'
/Users/user/Git/SampleCocoapodsProject/vendor/bundle/ruby/2.6.0/bundler/gems/CocoaPods-b812daedb782/lib/cocoapods/user_interface.rb:64:in `section'
/Users/user/Git/SampleCocoapodsProject/vendor/bundle/ruby/2.6.0/bundler/gems/CocoaPods-b812daedb782/lib/cocoapods/installer.rb:814:in `integrate_user_project'
/Users/user/Git/SampleCocoapodsProject/vendor/bundle/ruby/2.6.0/bundler/gems/CocoaPods-b812daedb782/lib/cocoapods/installer.rb:178:in `integrate'
/Users/user/Git/SampleCocoapodsProject/vendor/bundle/ruby/2.6.0/bundler/gems/CocoaPods-b812daedb782/lib/cocoapods/installer.rb:164:in `install!'
/Users/user/Git/SampleCocoapodsProject/vendor/bundle/ruby/2.6.0/bundler/gems/CocoaPods-b812daedb782/lib/cocoapods/command/install.rb:52:in `run'
/Users/user/Git/SampleCocoapodsProject/vendor/bundle/ruby/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/user/Git/SampleCocoapodsProject/vendor/bundle/ruby/2.6.0/bundler/gems/CocoaPods-b812daedb782/lib/cocoapods/command.rb:52:in `run'
/Users/user/Git/SampleCocoapodsProject/vendor/bundle/ruby/2.6.0/bundler/gems/CocoaPods-b812daedb782/bin/pod:55:in `<top (required)>'
/Users/user/Git/SampleCocoapodsProject/vendor/bundle/ruby/2.6.0/bin/pod:23:in `load'
/Users/user/Git/SampleCocoapodsProject/vendor/bundle/ruby/2.6.0/bin/pod:23:in `<top (required)>'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
/Library/Ruby/Gems/2.6.0/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
```
