### ISSUE TITLE
cd /ios && pod install error

### ISSUE THREAD

**Issue by thaiscristine** [CocoaPods/CocoaPods#9779]
### Command

```
/Users/user/.rvm/rubies/ruby-2.4.1/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.9.1
        Ruby : ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
    RubyGems : 2.6.12
        Host : Mac OS X 10.15 (19A583)
       Xcode :  ()
         Git : git version 2.12.0
Ruby lib dir : /Users/user/.rvm/rubies/ruby-2.4.1/lib
Repositories :
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

def add_flipper_pods!(versions = {})
  versions['Flipper'] ||= '~> 0.33.1'
  versions['DoubleConversion'] ||= '1.1.7'
  versions['Flipper-Folly'] ||= '~> 2.1'
  versions['Flipper-Glog'] ||= '0.3.6'
  versions['Flipper-PeerTalk'] ||= '~> 0.0.4'
  versions['Flipper-RSocket'] ||= '~> 1.0'

  pod 'FlipperKit', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitLayoutPlugin', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/SKIOSNetworkPlugin', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitUserDefaultsPlugin', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitReactPlugin', versions['Flipper'], :configuration => 'Debug'

  # List all transitive dependencies for FlipperKit pods
  # to avoid them being linked in Release builds
  pod 'Flipper', versions['Flipper'], :configuration => 'Debug'
  pod 'Flipper-DoubleConversion', versions['DoubleConversion'], :configuration => 'Debug'
  pod 'Flipper-Folly', versions['Flipper-Folly'], :configuration => 'Debug'
  pod 'Flipper-Glog', versions['Flipper-Glog'], :configuration => 'Debug'
  pod 'Flipper-PeerTalk', versions['Flipper-PeerTalk'], :configuration => 'Debug'
  pod 'Flipper-RSocket', versions['Flipper-RSocket'], :configuration => 'Debug'
  pod 'FlipperKit/Core', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/CppBridge', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FBCxxFollyDynamicConvert', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FBDefines', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FKPortForwarding', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitHighlightOverlay', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitLayoutTextSearchable', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitNetworkPlugin', versions['Flipper'], :configuration => 'Debug'
end

# Post Install processing for Flipper
def flipper_post_install(installer)
  installer.pods_project.targets.each do |target|
    if target.name == 'YogaKit'
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.1'
      end
    end
  end
end

target 'mobile' do
  # Pods for mobile
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/callinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga', :modular_headers => true

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  target 'mobileTests' do
    inherit! :complete
    # Pods for testing
  end

  use_native_modules!

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  add_flipper_pods!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'mobile-tvOS' do
  # Pods for mobile-tvOS

  target 'mobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
```

### Error

```
Errno::EACCES - Permission denied @ dir_s_mkdir - /Users/user/hd-interno/programming/bootcamp/mobile/ios/Pods
/Users/user/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/fileutils.rb:229:in `mkdir'
/Users/user/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/fileutils.rb:229:in `fu_mkdir'
/Users/user/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/fileutils.rb:207:in `block (2 levels) in mkdir_p'
/Users/user/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/fileutils.rb:205:in `reverse_each'
/Users/user/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/fileutils.rb:205:in `block in mkdir_p'
/Users/user/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/fileutils.rb:191:in `each'
/Users/user/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/fileutils.rb:191:in `mkdir_p'
/Users/user/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.9.1/lib/cocoapods/sandbox.rb:66:in `initialize'
/Users/user/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.9.1/lib/cocoapods/config.rb:193:in `new'
/Users/user/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.9.1/lib/cocoapods/config.rb:193:in `sandbox'
/Users/user/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.9.1/lib/cocoapods/command.rb:140:in `installer_for_config'
/Users/user/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.9.1/lib/cocoapods/command/install.rb:47:in `run'
/Users/user/.rvm/gems/ruby-2.4.1@global/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/user/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.9.1/lib/cocoapods/command.rb:52:in `run'
/Users/user/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.9.1/bin/pod:55:in `<top (required)>'
/Users/user/.rvm/rubies/ruby-2.4.1/bin/pod:23:in `load'
/Users/user/.rvm/rubies/ruby-2.4.1/bin/pod:23:in `<main>'
/Users/user/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
/Users/user/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by thaiscristine** [comment]
Apply permission to your user write in the folder

**Comment by Michaelvons** [comment]
sudo chown -R $USER <REACT_NATIVE_PROJECT_FOLDER>

will solve the issue for good!

**Comment by Mitdd9707** [comment]
> sudo chown -R $USER <REACT_NATIVE_PROJECT_FOLDER>
> 
> will solve the issue for good!

Thanks @Michaelvons Its work For me
