### ISSUE TITLE
'pod init' not working as expected

### ISSUE THREAD

**Issue by hemantchauhan** [CocoaPods/CocoaPods#9798]
## What did you do?

Run `pod init`

## What did you expect to happen?

A pod file should have been created in the directory

## What happened instead?

Got this error - 

### Command

```
/usr/local/bin/pod init
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.9.1
        Ruby : ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]
    RubyGems : 3.1.2
        Host : Mac OS X 10.15.4 (19E287)
       Xcode : 11.4.1 (11E503a)
         Git : git version 2.24.2 (Apple Git-127)
Ruby lib dir : /Users/ichi14/.rvm/rubies/ruby-2.7.1/lib
Repositories : 
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Error

```
Nanaimo::Reader::ParseError - [!] Unexpected end of string while parsing
 #  -------------------------------------------
1>  
    ^
 #  -------------------------------------------

/Users/ichi14/.rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:284:in `raise_parser_error'
/Users/ichi14/.rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:130:in `parse_object'
/Users/ichi14/.rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:107:in `parse!'
/Users/ichi14/.rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/xcodeproj-1.16.0/lib/xcodeproj/plist.rb:27:in `read_from_path'
/Users/ichi14/.rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/xcodeproj-1.16.0/lib/xcodeproj/project.rb:210:in `initialize_from_file'
/Users/ichi14/.rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/xcodeproj-1.16.0/lib/xcodeproj/project.rb:112:in `open'
/Users/ichi14/.rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.1/lib/cocoapods/command/init.rb:41:in `validate!'
/Users/ichi14/.rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:333:in `run'
/Users/ichi14/.rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.1/lib/cocoapods/command.rb:52:in `run'
/Users/ichi14/.rvm/rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
/Users/ichi14/.rvm/gems/ruby-2.7.1/bin/ruby_executable_hooks:24:in `eval'
/Users/ichi14/.rvm/gems/ruby-2.7.1/bin/ruby_executable_hooks:24:in `<main>'
```

**Comment by sean-esper** [comment]
@hemantchauhan What was your fix? I have the same issue 5 years later
