### ISSUE TITLE
cannot execute pod install

### ISSUE THREAD

**Issue by mjpb123** [CocoaPods/CocoaPods#9801]
# pod install

### Command

```
/Applications/CocoaPods.app/Contents/Resources/bundle/bin/pod install
```

### Report

* What did you do?
I read in https://github.com/CocoaPods/CocoaPods/issues/9698 that I need to update to 1.16.0 of Xcodeproj so I did.

![image](https://user-images.githubusercontent.com/11970136/82434143-087f0b80-9ac5-11ea-8ebf-7a17597a10b4.png)

* What did you expect to happen?

* What happened instead?
Still gave the same result. :(

### Stack

```
   CocoaPods : 1.5.2
        Ruby : ruby 2.2.6p396 (2016-11-15 revision 56800) [x86_64-darwin15]
    RubyGems : 2.6.8
        Host : Mac OS X 10.15.4 (19E287)
       Xcode : 11.4 (11E146)
         Git : git version 2.6.2
Ruby lib dir : /Applications/CocoaPods.app/Contents/Resources/bundle/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ d1da8f3a461aeadcdcfed968b75cfd40a92e44a9
```

### Plugins

```
cocoapods-check           : 1.0.0
cocoapods-deintegrate     : 1.0.2
cocoapods-plugins         : 1.0.0
cocoapods-plugins-install : 0.0.1
cocoapods-search          : 1.0.0
cocoapods-stats           : 1.0.0
cocoapods-trunk           : 1.3.0
cocoapods-try             : 1.1.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
platform :ios, '10.0'
# Uncomment this line if you're using Swift
use_frameworks!

def shared_pods
    pod 'iCarousel'
    pod 'JVFloatLabeledTextField'
    pod 'Alamofire', '~> 4.8'
    pod 'AlamofireObjectMapper', '~> 5.1.0'
    pod 'CarbonKit'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'PickerCells'
    pod 'NVActivityIndicatorView'
    pod 'JDFTooltips'
    pod 'UIImageView-AGCInitials'
    pod 'FSCalendar'
    pod 'AlamofireImage', '~> 3.5.2'
#    pod 'TwitterKit'
#    pod 'FacebookCore'
#    pod 'FacebookLogin'
#    pod 'FacebookShare'
    pod 'MaterialTextField'
    pod 'WeScan'
    pod 'Firebase/Analytics'
end

target 'XXX' do
    shared_pods
end

target 'XXX' do
    shared_pods
end

target 'XXX' do
    shared_pods
end

target 'XXX' do
    shared_pods
end

#This fixed the IB Designables:
#Failed to render and update auto layout status
post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings.delete('CODE_SIGNING_ALLOWED')
        config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end
end
```

### Error

```
RuntimeError - [Xcodeproj] Unknown object version.
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.8/lib/xcodeproj/project.rb:218:in `initialize_from_file'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/xcodeproj-1.5.8/lib/xcodeproj/project.rb:103:in `open'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/analyzer.rb:918:in `block (2 levels) in inspect_targets_to_integrate'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/analyzer.rb:917:in `each'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/analyzer.rb:917:in `block in inspect_targets_to_integrate'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/user_interface.rb:64:in `section'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/analyzer.rb:912:in `inspect_targets_to_integrate'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/installer/analyzer.rb:78:in `analyze'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/installer.rb:243:in `analyze'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/installer.rb:154:in `block in resolve_dependencies'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/user_interface.rb:64:in `section'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/installer.rb:153:in `resolve_dependencies'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/installer.rb:116:in `install!'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/command/install.rb:41:in `run'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/lib/cocoapods/command.rb:52:in `run'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.5.2/bin/pod:55:in `<top (required)>'
/Applications/CocoaPods.app/Contents/Resources/bundle/bin/pod:22:in `load'
/Applications/CocoaPods.app/Contents/Resources/bundle/bin/pod:22:in `<main>'
```

**Comment by dnkoutso** [comment]
Can you upload your `.xcodeproj` or post a screenshot of its object version?

**Comment by mjpb123** [comment]
> Can you upload your `.xcodeproj` or post a screenshot of its object version?

Sorry, is this it?
<img width="195" alt="image" src="https://user-images.githubusercontent.com/11970136/82512383-88978680-9b42-11ea-81cd-e799bcfb6e55.png">
<img width="359" alt="image" src="https://user-images.githubusercontent.com/11970136/82512428-b250ad80-9b42-11ea-8e90-38033fc5ed08.png">

**Comment by dnkoutso** [comment]
Looks maybe correct. At this point we will need a sample app to reproduce this.

**Comment by mjpb123** [comment]
> Looks maybe correct. At this point we will need a sample app to reproduce this.

How can I submit the sample app?

**Comment by dnkoutso** [comment]
Just put one up on Github and share the link?

**Comment by mjpb123** [comment]
Ran the following to get "pod install" working:
`sudo gem install -n /usr/local/bin cocoapods`

Thank you! :)

**Comment by Ade-Joshe** [comment]
@mjpb123 what will be the equivalent for an mac user
