### ISSUE TITLE
Flutter error when using packages that depend on CocoaPods

### ISSUE THREAD

**Issue by oshalash38** [CocoaPods/CocoaPods#9804]
* [YES] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Trying to run my flutter app which includes a package which depends on CocoaPods

## What did you expect to happen?

My app runs normally

## What happened instead?

An error occurs in the terminal and the app doesn't run.

Terminal:

```Launching lib/main.dart on iPhone SE (2nd generation) in debug mode...
Running pod install...
Error output from CocoaPods:
↳
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/executable.rb:97:in `expand_path': user Developer doesn't exist (ArgumentError)
    	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/executable.rb:97:in `block in which'
    	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/executable.rb:96:in `each'
    	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/executable.rb:96:in `which'
    	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/executable.rb:117:in `which!'
    	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/executable.rb:143:in `capture_command'
    	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/command.rb:116:in `git_version'
    	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/command.rb:130:in `verify_minimum_git_version!'
    	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/command.rb:49:in `run'
    	from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.5/bin/pod:55:in `<top (required)>'
    	from /usr/local/bin/pod:23:in `load'
    	from /usr/local/bin/pod:23:in `<main>'

Error running pod install
Error launching application on iPhone SE (2nd generation).
```

### Stack

```
   CocoaPods : 1.7.5
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.4 (19E287)
       Xcode : 11.4.1 (11E503a)
         Git : git version 2.23.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 444b7a2c520769d11cca2bd08edac266c60bf12a
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

**Comment by oshalash38** [comment]
UPDATE: I tried "flutter run" in the macOS terminal and it worked but it doesn't work in android studio for some reason. Any help would be appreciated.

**Comment by dnkoutso** [comment]
```    def self.which(program)
      program = program.to_s
      paths = ENV.fetch('PATH') { '' }.split(File::PATH_SEPARATOR)
      paths.unshift('./')
      paths.uniq!
      paths.each do |path|
        bin = File.expand_path(program, path)
        if Gem.win_platform?
          bin += '.exe'
        end
        if File.file?(bin) && File.executable?(bin)
          return bin
        end
      end
      nil
    end```

this is the code thats crashing. Something maybe in your `PATH`?

**Comment by dnkoutso** [comment]
> UPDATE: I tried "flutter run" in the macOS terminal and it worked but it doesn't work in android studio for some reason. Any help would be appreciated.

Please file the issue on the Flutter repo.

Closing for now as this does not appear a CocoaPods issue or enhancement.

**Comment by dnkoutso** [comment]
> UPDATE: I tried "flutter run" in the macOS terminal and it worked but it doesn't work in android studio for some reason. Any help would be appreciated.

Please file the issue on the Flutter repo.

Closing for now as this does not appear a CocoaPods issue or enhancement.
