### ISSUE TITLE
NoMethodError - undefined method `real_path' for nil:NilClass

### ISSUE THREAD

**Issue by KLim1989** [CocoaPods/CocoaPods#9808]
# Report

pod install

## What did you expect to happen?
e.g. Install all pod dependencies correctly.

### Error

```
NoMethodError - undefined method `real_path' for nil:NilClass
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.16.0/lib/xcodeproj/project/object/container_item_proxy.rb:96:in `container_portal_annotation'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.16.0/lib/xcodeproj/project/object/container_item_proxy.rb:105:in `to_hash_as'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.16.0/lib/xcodeproj/project/object.rb:421:in `to_ascii_plist'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.16.0/lib/xcodeproj/project.rb:297:in `block in to_ascii_plist'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.16.0/lib/xcodeproj/project.rb:295:in `each'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.16.0/lib/xcodeproj/project.rb:295:in `to_ascii_plist'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.16.0/lib/xcodeproj/project.rb:364:in `block in save'
/Library/Ruby/Gems/2.6.0/gems/atomos-0.1.3/lib/atomos.rb:21:in `block in atomic_write'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tempfile.rb:295:in `open'
/Library/Ruby/Gems/2.6.0/gems/atomos-0.1.3/lib/atomos.rb:17:in `atomic_write'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.16.0/lib/xcodeproj/project.rb:363:in `save'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/user_project_integrator.rb:158:in `block in save_projects'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/user_project_integrator.rb:156:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/user_project_integrator.rb:156:in `save_projects'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/user_project_integrator.rb:76:in `integrate!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:801:in `block in integrate_user_project'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:797:in `integrate_user_project'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:176:in `integrate'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:162:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'

## CocoaPods Environment
 CocoaPods : 1.9.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.5 (19F83c)
       Xcode : 11.4 (11E146)
         Git : git version 2.24.1 (Apple Git-126)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ d6556efa0cda002d22b0181bfdcb62cd4af9731e

               trunk - CDN - https://cdn.cocoapods.org/

## Project that demonstrates the issue

https://github.com/KLim1989/CocoaPodsBugMail/tree/master/MailBugRep


```
Commment
I try to compile the workspace, the project is empty, but even in an almost empty project I get this error. I read tickets on similar problems, I understand that the problem is in the parsing of the project, but I can not understand where. Help me please. Tell me which section .xcodeproj is causing the error, or give a link to instructions on how to debug container_item_proxy.rb.

```

**Comment by dnkoutso** [comment]
Need a sample app here, my gut feeling is that the project is corrupt.

**Comment by allan-simon** [comment]
@dnkoutso  I'm facing the same issue, and what is helping me a lot to find where my file is corrupted is to add some `puts` of the container_portal value , maybe could be a good idea to output it when the exception is thrown ?

**Comment by dnkoutso** [comment]
@allan-simon yes that might be beneficial, this would be a PR in Xcodeproj gem though.
