### ISSUE TITLE
[1.9.2] Error during pod install on CI, Ruby 2.7

### ISSUE THREAD

**Issue by Kaspik** [CocoaPods/CocoaPods#9816]
Already posted this in https://github.com/CocoaPods/CocoaPods/issues/9814 but creating separate issue.

Did not happen on CocoaPods 1.9.1 until the update two days ago.

### Command

```
/Users/administrator/.rbenv/versions/2.7.1/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.9.2
        Ruby : ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]
    RubyGems : 3.1.2
        Host : Mac OS X 10.15.4 (19E287)
       Xcode : 11.5 (11E608c)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /Users/administrator/.rbenv/versions/2.7.1/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
claide-plugins        : 0.9.2
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# By Jakub Kaspar 12/19/2019
# ClassDojo, Inc. 2019
# ClassDojo

source 'https://cdn.cocoapods.org/'

platform :ios, '11.0'
use_frameworks!

# Uncomment below if using a development pod
# install! 'cocoapods', :disable_input_output_paths => true
install! 'cocoapods', :generate_multiple_pod_projects => true, :incremental_installation => true

workspace './ClassDojo'
project 'ClassDojo.xcodeproj'

# ignore all warnings from all pods
inhibit_all_warnings!

def extension_includes
    pod 'DeviceUtil', '~> 6.1', :project_name => 'Other'
end

def ui_includes
    pod 'PINRemoteImage', '~> 3.0', :subspecs => ['iOS', 'PINCache', 'WebP']
    pod 'Nantes', '~> 0.0', :project_name => 'UI'
end

def all_pods
    extension_includes
    ui_includes

    pod 'AFNetworking', '~> 4.0'
    pod 'CocoaLumberjack', '~> 3.6', :project_name => 'Logging'
    pod 'LogglyLogger-CocoaLumberjack', '~> 3.0', :project_name => 'Logging'
    pod 'DifferenceKit', '~> 1.1', :project_name => 'Other'
    pod 'Firebase/Analytics', :project_name => 'Firebase'
    pod 'Firebase/Messaging', '~> 6.17.0', :project_name => 'Firebase'
    pod 'Firebase/Crashlytics', :project_name => 'Firebase'
#    pod 'GDCoreDataConcurrencyDebugging'
    pod 'Hero', '~> 1.5', :project_name => 'UI'
    pod 'iRate', :git => 'https://github.com/classdojo/iRate', :branch => 'master', :project_name => 'Other'
    pod 'JSQMessagesViewController', :git => 'https://github.com/classdojo/JSQMessagesViewController', :branch => 'master', :project_name => 'UI'
    pod 'JDStatusBarNotification', '~> 1.5', :project_name => 'UI' # Not supported anymore
    pod 'Layout', '~> 0.7', :project_name => 'UI'
    pod 'lottie-ios', '~> 3.1', :project_name => 'UI'
    pod 'NextLevel'
    pod 'PNChart', :git => 'https://github.com/classdojo/PNChart', :branch => 'master', :project_name => 'UI'
    pod 'pop', '~> 1.0', :project_name => 'UI'
    pod 'PromiseKit/CorePromise', '~> 6.13', :project_name => 'Other'
    pod 'PubNub', '~> 4.12', :project_name => 'Other'
    pod 'SAMKeychain', '~> 1.5', :project_name => 'Other'
    pod 'SSZipArchive', :project_name => 'Other'
    pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD', :commit => '4fdf3fdc8703fd9915dae33fc1363c604a06b24e', :project_name => 'UI'
    pod 'SwiftEntryKit', '~> 1.2', :project_name => 'UI'
    pod 'SwiftLint', '~> 0.39', :project_name => 'Other'
    pod 'SwiftyStoreKit', '~> 0.15', :project_name => 'Other'
    pod 'Tweaks', '~> 2.3', :project_name => 'Debugging'
    pod 'UICollectionViewLeftAlignedLayout', '~> 1.0', :project_name => 'UI'
end

abstract_target 'App' do
    all_pods

    target 'ClassDojo' do
      target 'Unit Tests' do
        inherit! :search_paths
        pod 'Criollo', :git => 'https://github.com/classdojo/Criollo', :branch => 'master', :project_name => 'Testing' # '~> 0.5'
      end

      target 'UI Tests' do
        inherit! :search_paths
        pod 'Criollo', :git => 'https://github.com/classdojo/Criollo', :branch => 'master', :project_name => 'Testing' # '~> 0.5'
      end

      target 'Integration Tests' do
        pod 'Criollo', :git => 'https://github.com/classdojo/Criollo', :branch => 'master', :project_name => 'Testing' # '~> 0.5'
      end

      pod 'FLEX', '~> 3.1', :configurations => ['Debug'], :project_name => 'Debugging'
      pod 'WoodPeckeriOS', :configurations => ['Debug'], :project_name => 'Debugging'
    end

    target 'ClassDojo_Alpha' do
      all_pods
      pod 'FLEX', '~> 3.1', :project_name => 'Debugging'
    end
end

target 'Nessie' do
  project 'Libraries/Nessie/Nessie'
  ui_includes
end

target 'Messaging' do
  project 'Libraries/Messaging/Messaging'
  ui_includes

  target 'MessagingTests' do
    # Make MessageKit dependencies available
    inherit! :complete
  end
end

abstract_target 'Extensions' do
  target 'Notifications Service' do
    extension_includes
  end
end

post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            if target.name == "Tweaks"
                target.build_configurations.each do |config|
                    config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'FB_TWEAK_ENABLED=1']
                end
            end
            if target.name == "SwiftyStoreKit"
                target.build_configurations.each do |config|
                    if config.name == 'Testing'
                        config.build_settings['ENABLE_TESTABILITY'] = 'YES'
                    end
                end
            end
        end
    end
end
```

### Error

```
Errno::ENOENT - No such file or directory @ rb_sysopen - ary/Caches/CocoaPods/Pods/Release/FirebaseAnalyticsInterop/1.5.0-3f862/d20200523-13193-idlejw/Firebase/InstanceID/NSError+FIRInstanceID.m
/Users/administrator/.rbenv/versions/2.7.1/lib/ruby/2.7.0/fileutils.rb:1413:in `initialize'
/Users/administrator/.rbenv/versions/2.7.1/lib/ruby/2.7.0/fileutils.rb:1413:in `open'
/Users/administrator/.rbenv/versions/2.7.1/lib/ruby/2.7.0/fileutils.rb:1413:in `copy_file'
/Users/administrator/.rbenv/versions/2.7.1/lib/ruby/2.7.0/fileutils.rb:1378:in `copy'
/Users/administrator/.rbenv/versions/2.7.1/lib/ruby/2.7.0/fileutils.rb:497:in `block in copy_entry'
/Users/administrator/.rbenv/versions/2.7.1/lib/ruby/2.7.0/fileutils.rb:1512:in `wrap_traverse'
/Users/administrator/.rbenv/versions/2.7.1/lib/ruby/2.7.0/fileutils.rb:1515:in `block in wrap_traverse'
/Users/administrator/.rbenv/versions/2.7.1/lib/ruby/2.7.0/fileutils.rb:1514:in `each'
/Users/administrator/.rbenv/versions/2.7.1/lib/ruby/2.7.0/fileutils.rb:1514:in `wrap_traverse'
/Users/administrator/.rbenv/versions/2.7.1/lib/ruby/2.7.0/fileutils.rb:1515:in `block in wrap_traverse'
/Users/administrator/.rbenv/versions/2.7.1/lib/ruby/2.7.0/fileutils.rb:1514:in `each'
/Users/administrator/.rbenv/versions/2.7.1/lib/ruby/2.7.0/fileutils.rb:1514:in `wrap_traverse'
/Users/administrator/.rbenv/versions/2.7.1/lib/ruby/2.7.0/fileutils.rb:1515:in `block in wrap_traverse'
/Users/administrator/.rbenv/versions/2.7.1/lib/ruby/2.7.0/fileutils.rb:1514:in `each'
/Users/administrator/.rbenv/versions/2.7.1/lib/ruby/2.7.0/fileutils.rb:1514:in `wrap_traverse'
/Users/administrator/.rbenv/versions/2.7.1/lib/ruby/2.7.0/fileutils.rb:1515:in `block in wrap_traverse'
/Users/administrator/.rbenv/versions/2.7.1/lib/ruby/2.7.0/fileutils.rb:1514:in `each'
/Users/administrator/.rbenv/versions/2.7.1/lib/ruby/2.7.0/fileutils.rb:1514:in `wrap_traverse'
/Users/administrator/.rbenv/versions/2.7.1/lib/ruby/2.7.0/fileutils.rb:494:in `copy_entry'
/Users/administrator/.rbenv/versions/2.7.1/lib/ruby/2.7.0/fileutils.rb:468:in `block in cp_r'
/Users/administrator/.rbenv/versions/2.7.1/lib/ruby/2.7.0/fileutils.rb:1588:in `block in fu_each_src_dest'
/Users/administrator/.rbenv/versions/2.7.1/lib/ruby/2.7.0/fileutils.rb:1604:in `fu_each_src_dest0'
/Users/administrator/.rbenv/versions/2.7.1/lib/ruby/2.7.0/fileutils.rb:1586:in `fu_each_src_dest'
/Users/administrator/.rbenv/versions/2.7.1/lib/ruby/2.7.0/fileutils.rb:467:in `cp_r'
/Users/administrator/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.2/lib/cocoapods/downloader.rb:54:in `block in download'
/Users/administrator/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.2/lib/cocoapods/user_interface.rb:145:in `message'
/Users/administrator/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.2/lib/cocoapods/downloader.rb:52:in `download'
/Users/administrator/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.2/lib/cocoapods/installer/pod_source_installer.rb:117:in `download_source'
/Users/administrator/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.2/lib/cocoapods/installer/pod_source_installer.rb:69:in `install!'
/Users/administrator/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.2/lib/cocoapods/installer.rb:557:in `install_source_of_pod'
/Users/administrator/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.2/lib/cocoapods/installer.rb:508:in `block (2 levels) in install_pod_sources'
/Users/administrator/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.2/lib/cocoapods/user_interface.rb:86:in `titled_section'
/Users/administrator/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.2/lib/cocoapods/installer.rb:507:in `block in install_pod_sources'
/Users/administrator/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.2/lib/cocoapods/installer.rb:490:in `each'
/Users/administrator/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.2/lib/cocoapods/installer.rb:490:in `install_pod_sources'
/Users/administrator/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.2/lib/cocoapods/installer.rb:249:in `block in download_dependencies'
/Users/administrator/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.2/lib/cocoapods/user_interface.rb:64:in `section'
/Users/administrator/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.2/lib/cocoapods/installer.rb:248:in `download_dependencies'
/Users/administrator/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.2/lib/cocoapods/installer.rb:157:in `install!'
/Users/administrator/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.2/lib/cocoapods/command/install.rb:52:in `run'
/Users/administrator/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/administrator/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.2/lib/cocoapods/command.rb:52:in `run'
/Users/administrator/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.2/bin/pod:55:in `<top (required)>'
/Users/administrator/.rbenv/versions/2.7.1/bin/pod:23:in `load'
/Users/administrator/.rbenv/versions/2.7.1/bin/pod:23:in `<top (required)>'
/Users/administrator/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
/Users/administrator/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
/Users/administrator/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
/Users/administrator/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
/Users/administrator/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/administrator/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/Users/administrator/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
/Users/administrator/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
/Users/administrator/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
/Users/administrator/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
/Users/administrator/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
/Users/administrator/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
/Users/administrator/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
/Users/administrator/.rbenv/versions/2.7.1/bin/bundle:23:in `load'
/Users/administrator/.rbenv/versions/2.7.1/bin/bundle:23:in `<main>'
```

**Comment by dnkoutso** [comment]
Can you `rm -rf ../Caches/CocoaPods/`?

**Comment by Kaspik** [comment]
Did that, helped, fixed.

I wonder why this happened, or if it at least helps with fix for future version. :)

Thanks!

PS: Not related - is there some branch with Ruby 2.7 fixes or at least release plan?

**Comment by dnkoutso** [comment]
Not sure why it happened. 

Ruby 2.7 fixes have landed on master branch but there is no timeframe for 1.10 release.

**Comment by Kaspik** [comment]
@dnkoutso I saw 1.9.3 was shipped - does it include Ruby 2.7 fixes? :)

**Comment by samchidi2005** [comment]
CocoaPods : 1.9.3
        Ruby : ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin18]
    RubyGems : 3.1.2
        Host : Mac OS X 10.14.6 (18G8022)
       Xcode : 11.2.1 (11B500)
         Git : git version 2.23.0
Ruby lib dir : /usr/local/Cellar/ruby/2.7.1_2/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ f87702f564e9614ffef81c70479446dd90f828c3

**Comment by samchidi2005** [comment]
Error: /usr/local/Cellar/cocoapods/1.9.3/libexec/gems/cocoapods-core-1.9.3/lib/cocoapods-core/cdn_source.rb:342: warning: URI.escape is obsolete
