### ISSUE TITLE
pod install error

### ISSUE THREAD

**Issue by imanuelpardosi** [CocoaPods/CocoaPods#9881]
### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.9.3
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.5 (19F96)
       Xcode : 11.5 (11E608c)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ ec451abca82ba5bdc3076814051ec3d0d10ed966

               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FU' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FU
    pod 'SkyFloatingLabelTextField', '~> 3.0'
    pod 'IQKeyboardManagerSwift', '6.1.1'
    pod 'FCAlertView', '1.4.0'
    pod 'lottie-ios', '2.5.0'
    pod 'SwiftValidator', '3.0.3'
    pod 'FSCalendar', '2.7.9'
    pod 'Toast-Swift', '4.0 .0'
    pod 'Kingfisher', '~> 5.0'
    pod 'SwiftyUserDefaults', '4.0.0-alpha.1'
    pod 'AMTooltip', '1.0.4'
    pod 'SwiftKeychainWrapper', '3.0.1'
    pod 'FittedSheets', '1.1.4'
    pod 'MBCircularProgressBar', '0.3.5'
    pod 'XJYChart', '2.5.0'
    pod 'DLRadioButton', '~> 1.4'
    pod 'SwiftMessages', '6.0.2'
    pod 'GoogleSignIn', '4.4.0'
    pod 'SkeletonView', '1.4.1'
    pod 'Mixpanel-swift', '2.5.6'
    pod 'LocationPickerViewController', '3.4'
    pod 'Siren', :git => 'https://github.com/ArtSabintsev/Siren.git', :branch => 'swift4.2' # Swift 4.2
    
    pod 'Firebase'
    pod 'Firebase/Core'
    pod 'FirebaseMessaging' #, '~> 2.0.5'
    pod 'Firebase/InAppMessaging'
    pod 'Firebase/InAppMessagingDisplay'
    pod 'Firebase/Analytics'
    pod 'Firebase/Crashlytics'
    pod 'XCDYouTubeKit', '~> 2.8'
    
    pod 'Alamofire', '~> 5.2'
    
  target 'FUTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FUUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

### Error

```
ArgumentError - Illformed requirement `"4.0 .0"`
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.3/lib/cocoapods-core/requirement.rb:63:in `parse'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.3/lib/cocoapods-core/requirement.rb:88:in `block in initialize'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.3/lib/cocoapods-core/requirement.rb:88:in `map!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.3/lib/cocoapods-core/requirement.rb:88:in `initialize'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.3/lib/cocoapods-core/requirement.rb:34:in `new'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.3/lib/cocoapods-core/requirement.rb:34:in `create'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.3/lib/cocoapods-core/dependency.rb:101:in `initialize'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.3/lib/cocoapods-core/podfile/target_definition.rb:979:in `new'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.3/lib/cocoapods-core/podfile/target_definition.rb:979:in `block in pod_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.3/lib/cocoapods-core/podfile/target_definition.rb:975:in `map'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.3/lib/cocoapods-core/podfile/target_definition.rb:975:in `pod_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.3/lib/cocoapods-core/podfile/target_definition.rb:96:in `non_inherited_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.3/lib/cocoapods-core/podfile/target_definition.rb:74:in `dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer/podfile_dependency_cache.rb:44:in `block in from_podfile'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer/podfile_dependency_cache.rb:43:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer/podfile_dependency_cache.rb:43:in `from_podfile'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer.rb:85:in `initialize'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:416:in `new'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:416:in `create_analyzer'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:228:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:156:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by dnkoutso** [comment]
You have a typo as the error message says.

change
```ruby
    pod 'Toast-Swift', '4.0 .0'
```
to
```ruby
    pod 'Toast-Swift', '4.0.0'
```

**Comment by imanuelpardosi** [comment]
solved, thanks a lot.
