### ISSUE TITLE
Pod update error

### ISSUE THREAD

**Issue by JoseG95** [CocoaPods/CocoaPods#9886]
### Command

```
/Users/josegutierrez/.gem/bin/pod update
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.9.3
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.4 (19E287)
       Xcode : 11.4 (11E146)
         Git : git version 2.27.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : bitbucket-podspecs - git - git@bitbucket.org:rappinc/podspecs.git @ b81f17d6f83cc1930c8ad2a6d2313b9eeb56d755

               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
claide-plugins        : 0.9.2
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
slather               : 2.4.9
```

### Podfile

```ruby
source 'https://cdn.cocoapods.org/'
source 'git@bitbucket.org:rappinc/podspecs.git'
require_relative "../../PodfilePostInstallConfiguration.rb"

platform :ios, "12.0"
use_modular_headers!

def core
    pod 'RappiBase', :path => '../../libraries/rappi-base'
    pod 'RappiExtensions', :path => '../../libraries/rappi-extensions'
    pod 'RappiStyleGuide', '~> 1.0.6'
    pod 'RappiCart', :path => '../../libraries/rappi-cart', :testspecs => ['RappiCartTests']
    pod 'RappiUser', :path => '../../libraries/rappiuser-ios'
    pod 'RappiDeepLink', :path => '../../libraries/deeplinks'
    pod 'RappiLoyalty', :path => '../../libraries/loyalty'
    pod 'RappiGrowth', :path => '../../libraries/growth', :testspecs => ['RappiGrowthTests']
    pod 'GlobalSearch', :path => '../../libraries/global-search-ios', :testspecs => ['SearchTests']
    pod 'RappiPay', :path => '../../libraries/RappiPay', :testspecs => ['RappiPayTests']
    pod 'RappiAddress', :path => '../../libraries/rappiaddressios', :testspecs => ['RappiAddressTests']
    pod 'RappiACF', :path => '../../libraries/RappiACF', :testspecs => ['RappiACFTests']
    pod 'RappiLogin', :path => '../../libraries/RappiLogin', :testspecs => ['RappiLoginTests']
    pod 'RappiHomeComponents', :path => '../../libraries/RappiHomeComponents', :testspecs => ['RappiHomeComponentsTests']
    core_utilities
    pod 'RappiWidgets', :path => '../../libraries/RappiWidgets', :testspecs => ['RappiWidgetsTests']
    core_utilities
end

def order
    pod 'RappiPaymentMethods', :path => '../../libraries/RappiPaymentMethods', :testspecs => ['UnitTests']
    pod 'RappiChat', :path => '../../libraries/chat'
    pod 'ETA', :path => '../../libraries/ETA', :testspecs => ['ETATest']
    pod 'RappiSupport', :path => '../../libraries/support', :testspecs => ['SupportTest']

    order_utilities
end

def revenue
  pod 'RappiAds', :path => '../../libraries/RappiAds', :testspecs => ['RappiAdsTests']
end

def stores
    pod 'Market', :path => '../../libraries/market', :testspecs => ['MarketTests']
    pod 'Restaurants', :path => '../../libraries/restaurantsios', :testspecs => ['Restaurants_Tests']
    pod 'RappiSoat', :path => '../../libraries/rappisoat'
    pod 'RappiWhims', :path => '../../libraries/rappiwhims'
    pod 'RappiFavor', :path => '../../libraries/rappifavor/'
    pod 'RappiTransmilenio', :path => '../../libraries/Transmilenio'
    pod 'RentBrella', :path => '../../libraries/RentBrella'
    pod 'RappiBet', :path => '../../libraries/RappiBet', :testspecs => ['RappiBetTests']
    pod 'RappiMall', :path => '../../libraries/RappiMall', :testspecs => ['RappiMallTests']
    pod 'RappiWylsStore', :path => '../../libraries/Wyls'
    pod 'RappiNetwork', :path => '../../libraries/RappiNetwork', :testspecs => ['RappiNetworkTests']
    pod 'RappiInjection', :path => '../../libraries/RappiInjection'
    pod 'AppConfig', :path => '../../libraries/AppConfig'
end

## Third Dependencies
def external_dependencies
  pod 'DyScanFraud/5.1_eu', :path => '../../libraries/dyscan'
  pod 'TrustDefender', :path => '../../libraries/trustdefender'
  pod 'RappiCardIO', :path => '../../libraries/RappiCardIO'
  pod 'Davivienda/Daviplata', :path => '../../libraries/davivienda'
  pod 'Davivienda/Communication', :path => '../../libraries/davivienda'
  pod 'Davivienda/Security', :path => '../../libraries/davivienda'
end

## Utilities
def order_utilities
  # Firebase
  pod 'Firebase', '6.26.0'
  pod 'Firebase/Database'
  pod 'Firebase/Messaging'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Performance'
  pod 'Firebase/Crashlytics'
  pod 'FirebaseDatabase', '6.2.1'
  pod 'FirebaseInstallations', '1.3.0'
  pod 'FirebaseInstanceID', '4.3.4'
  pod 'FirebaseMessaging', '4.4.1'
  pod 'FirebaseStorage', '3.6.1'
  pod 'FirebaseAuth', '6.5.3'
  pod 'FirebaseAuthInterop', '1.1.0'
  pod 'FirebaseRemoteConfig', '4.5.0'
  pod 'FirebasePerformance', '3.1.11'
  pod 'FirebaseCrashlytics', '4.1.1'
  pod 'FirebaseABTesting', '3.2.0'
  pod 'FirebaseAnalytics', '6.6.0'
  pod 'FirebaseAnalyticsInterop', '1.5.0'
  pod 'FirebaseCore', '6.7.2'
  pod 'FirebaseCoreDiagnostics', '1.3.0'
  pod 'FirebaseCoreDiagnosticsInterop', '1.2.0'
  pod 'OpenSSL-Universal', '1.0.2.19'
  pod 'nanopb', '1.30905.0'
  pod 'PromisesObjC', '1.2.9'
  pod 'Protobuf', '3.12.0'

  # Maps
  pod 'Google-Maps-iOS-Utils', '3.1.1'
  pod 'GoogleAppMeasurement', '6.6.0'
  pod 'GoogleDataTransport', '6.2.1'
  pod 'GoogleDataTransportCCTSupport', '3.1.0'
  pod 'GoogleMaps', '3.8.0'
  pod 'GooglePlaces', '3.8.0'
  pod 'GTMSessionFetcher/Core', '1.4.0'

end

def core_utilities
    # RX
    pod 'RxSwift', '5.0.1'
    pod 'RxCocoa', '5.0.1'
    pod 'RxDataSources', '4.0.1'
    pod 'Differentiator', '4.0.1'
    pod 'RxGesture', '3.0.1'
    pod 'RxKeyboard', '1.0.0'
    pod 'RxRelay', '5.1.1'

    # Utilities
    pod 'Alamofire', '4.9.1'
    pod 'RxAlamofire', '5.1.0'
    pod 'Branch', '0.31.4'
    pod 'KeychainAccess', '3.2.0'
    pod 'ObjectMapper', '3.5.1'
    pod 'Swinject', '2.7.1'
    pod 'SwiftOTP', '2.0.0'
    pod 'CryptoSwift', '1.1.2'
    pod 'JumioMobileSDK/NetverifyFace', '3.5.0'
    pod 'leveldb-library', '1.22'
    pod 'libwebp', '1.0.0'
    pod 'ReachabilitySwift', '4.3.1'

    # UI
    pod 'IGListKit', '4.0.0'
    pod 'IGListDiffKit', '4.0.0'
    pod 'IQKeyboardManagerSwift', '6.5.0'
    pod 'lottie-ios', '3.1.8'
    
    external_dependencies
end

def internal_utilities
    # Social
    pod 'FBNotifications', '1.0.1'
    pod 'FBSDKShareKit', '5.15.1'
    pod 'FBSDKLoginKit', '5.15.1'
    pod 'FacebookCore', '0.9.0'
    pod 'FacebookLogin', '0.9.0'
    pod 'FBSDKCoreKit', '5.15.1'
    
    # Analytics
    pod 'Amplitude-iOS', '4.10.0'
    pod 'AppsFlyerFramework', '5.3.0'
    pod 'Rakam-iOS', '4.0.4'
    pod 'Split', '2.5.2'
    pod 'Appboy-iOS-SDK', '3.21.2'
    pod 'UXCam', '3.1.15'
    
    # Payment
    pod 'Sift', '0.9.11'
    
    # Chat
    pod 'ZendeskSDK', '1.11.2.1'
    pod 'ZDCChat', '1.4.3'

    # Image
    pod 'Nuke', '8.4.1'
    pod 'FLAnimatedImage', '1.0.12'
    pod 'Nuke-FLAnimatedImage-Plugin', '6.2'
    pod 'Nuke-WebP-Plugin', '4.0.0'
    pod 'SDWebImage', '5.8.1'

    # Video
    pod 'YoutubeDirectLinkExtractor', '0.3.1'
    pod 'YoutubePlayer-in-WKWebView', '0.3.4'
    
    # UI
    pod 'TagListView', '1.4.0'
    pod 'TTTAttributedLabel', '2.0.0'
    pod 'NSHash', '1.2.0'
    pod 'FCUUID', '1.3.1'
    pod 'UICKeyChainStore', '2.1.2'
    pod 'CropViewController', '2.4.0'
    
    # Logger
    pod 'netfox', '1.19.0', :configurations => ['debug','production']

    # Models
    pod 'Apollo', '0.21.0'
    pod 'JSONModel', '1.8.0'
end

def testing
  # TDD
  pod 'Quick', '2.2.0'
    
  pod 'Nimble', '8.1.1'
  # Services Mocking
  pod 'OHHTTPStubs', '9.0.0'
  pod 'OHHTTPStubs/Swift'
  
  # RX
  pod 'RxBlocking', '5.1.1'
  pod 'RxTest', '5.1.1'
  pod 'RxNimble', '4.7.1'
  pod 'RappiTesting', :path => '../../libraries/RappiTesting' 
end

def rappi_app
  core
  order
  stores
  revenue
  internal_utilities
end

target 'Grability' do
  rappi_app
  target 'GrabilityTests' do
    inherit! :search_paths
    testing
  end
end

post_install do |installer|
  rappi_post_install_swift_versions(installer)
  rappi_post_install_bitcode(installer)
  rappi_post_install_extra(installer, '12.0')
end
```

### Error

```
Nanaimo::Reader::ParseError - [!] Found additional characters after parsing the root plist object
 #  -------------------------------------------
1>  version https://git-lfs.github.com/spec/v1
            ^
 #  oid sha256:9affaa17bbdf3039aa16ce539aa81b745dea0c68f73bb6bc90efd7a9df70cf2b
 #  size 1093
 #  -------------------------------------------

/Library/Ruby/Gems/2.6.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:284:in `raise_parser_error'
/Library/Ruby/Gems/2.6.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:110:in `parse!'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.16.0/lib/xcodeproj/plist.rb:27:in `read_from_path'
/Users/josegutierrez/.gem/gems/cocoapods-1.9.3/lib/cocoapods/xcode/xcframework.rb:36:in `initialize'
/Users/josegutierrez/.gem/gems/cocoapods-1.9.3/lib/cocoapods/target/build_settings.rb:689:in `new'
/Users/josegutierrez/.gem/gems/cocoapods-1.9.3/lib/cocoapods/target/build_settings.rb:689:in `block (2 levels) in <class:PodTargetSettings>'
/Users/josegutierrez/.gem/gems/cocoapods-1.9.3/lib/cocoapods/target/build_settings.rb:689:in `map'
/Users/josegutierrez/.gem/gems/cocoapods-1.9.3/lib/cocoapods/target/build_settings.rb:689:in `block in <class:PodTargetSettings>'
/Users/josegutierrez/.gem/gems/cocoapods-1.9.3/lib/cocoapods/target/build_settings.rb:114:in `block in define_build_settings_method'
/Users/josegutierrez/.gem/gems/cocoapods-1.9.3/lib/cocoapods/target/build_settings.rb:661:in `block in <class:PodTargetSettings>'
/Users/josegutierrez/.gem/gems/cocoapods-1.9.3/lib/cocoapods/target/build_settings.rb:114:in `block in define_build_settings_method'
/Users/josegutierrez/.gem/gems/cocoapods-1.9.3/lib/cocoapods/target/build_settings.rb:671:in `block in <class:PodTargetSettings>'
/Users/josegutierrez/.gem/gems/cocoapods-1.9.3/lib/cocoapods/target/build_settings.rb:114:in `block in define_build_settings_method'
/Users/josegutierrez/.gem/gems/cocoapods-1.9.3/lib/cocoapods/target/build_settings.rb:642:in `block in <class:PodTargetSettings>'
/Users/josegutierrez/.gem/gems/cocoapods-1.9.3/lib/cocoapods/target/build_settings.rb:114:in `block in define_build_settings_method'
/Users/josegutierrez/.gem/gems/cocoapods-1.9.3/lib/cocoapods/target/build_settings.rb:362:in `public_send'
/Users/josegutierrez/.gem/gems/cocoapods-1.9.3/lib/cocoapods/target/build_settings.rb:362:in `block in to_h'
/Users/josegutierrez/.gem/gems/cocoapods-1.9.3/lib/cocoapods/target/build_settings.rb:361:in `each'
/Users/josegutierrez/.gem/gems/cocoapods-1.9.3/lib/cocoapods/target/build_settings.rb:361:in `to_h'
/Users/josegutierrez/.gem/gems/cocoapods-1.9.3/lib/cocoapods/target/build_settings.rb:174:in `block in <class:BuildSettings>'
/Users/josegutierrez/.gem/gems/cocoapods-1.9.3/lib/cocoapods/target/build_settings.rb:544:in `block in <class:PodTargetSettings>'
/Users/josegutierrez/.gem/gems/cocoapods-1.9.3/lib/cocoapods/target/build_settings.rb:114:in `block in define_build_settings_method'
/Users/josegutierrez/.gem/gems/cocoapods-1.9.3/lib/cocoapods/target/build_settings.rb:190:in `save_as'
/Users/josegutierrez/.gem/gems/cocoapods-1.9.3/lib/cocoapods/installer/xcode/pods_project_generator/target_installer_helper.rb:24:in `update_changed_file'
/Users/josegutierrez/.gem/gems/cocoapods-1.9.3/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:584:in `block in create_xcconfig_file'
/Users/josegutierrez/.gem/gems/cocoapods-1.9.3/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:582:in `each'
/Users/josegutierrez/.gem/gems/cocoapods-1.9.3/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:582:in `create_xcconfig_file'
/Users/josegutierrez/.gem/gems/cocoapods-1.9.3/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:45:in `block in install!'
/Users/josegutierrez/.gem/gems/cocoapods-1.9.3/lib/cocoapods/user_interface.rb:145:in `message'
/Users/josegutierrez/.gem/gems/cocoapods-1.9.3/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:34:in `install!'
/Users/josegutierrez/.gem/gems/cocoapods-1.9.3/lib/cocoapods/installer/xcode/pods_project_generator.rb:114:in `block in install_pod_targets'
/Users/josegutierrez/.gem/gems/cocoapods-1.9.3/lib/cocoapods/installer/xcode/pods_project_generator.rb:111:in `map'
/Users/josegutierrez/.gem/gems/cocoapods-1.9.3/lib/cocoapods/installer/xcode/pods_project_generator.rb:111:in `install_pod_targets'
/Users/josegutierrez/.gem/gems/cocoapods-1.9.3/lib/cocoapods/installer/xcode/single_pods_project_generator.rb:32:in `block in install_all_pod_targets'
/Users/josegutierrez/.gem/gems/cocoapods-1.9.3/lib/cocoapods/user_interface.rb:145:in `message'
/Users/josegutierrez/.gem/gems/cocoapods-1.9.3/lib/cocoapods/installer/xcode/single_pods_project_generator.rb:31:in `install_all_pod_targets'
/Users/josegutierrez/.gem/gems/cocoapods-1.9.3/lib/cocoapods/installer/xcode/single_pods_project_generator.rb:19:in `generate!'
/Users/josegutierrez/.gem/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:308:in `block in create_and_save_projects'
/Users/josegutierrez/.gem/gems/cocoapods-1.9.3/lib/cocoapods/user_interface.rb:64:in `section'
/Users/josegutierrez/.gem/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:303:in `create_and_save_projects'
/Users/josegutierrez/.gem/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:295:in `generate_pods_project'
/Users/josegutierrez/.gem/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:174:in `integrate'
/Users/josegutierrez/.gem/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:162:in `install!'
/Users/josegutierrez/.gem/gems/cocoapods-1.9.3/lib/cocoapods/command/update.rb:63:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/josegutierrez/.gem/gems/cocoapods-1.9.3/lib/cocoapods/command.rb:52:in `run'
/Users/josegutierrez/.gem/gems/cocoapods-1.9.3/bin/pod:55:in `<top (required)>'
/Users/josegutierrez/.gem/bin/pod:23:in `load'
/Users/josegutierrez/.gem/bin/pod:23:in `<main>'
```

**Comment by dnkoutso** [comment]
This seems like either a corrupt plist file inside the xcframework or a new feature that makes the plist parser to fail.

Can you please update the issue report with the XCFramework name and contents?

cc @amorde

**Comment by amorde** [comment]
Error looks like a corrupt plist to me, maybe related to git-lfs?
