### ISSUE TITLE
Error when running pod install: "Errno::ENOENT - No such file or directory"

### ISSUE THREAD

**Issue by aditibarbhai** [CocoaPods/CocoaPods#9911]
### Command

```
/usr/local/Cellar/cocoapods/1.9.3/libexec/bin/pod install
```

### Report

* What did you do? 
`pod install`

* What did you expect to happen?
install pods and create podfile.lock

* What happened instead? 
Got the follow error

### Stack

```
   CocoaPods : 1.9.3
        Ruby : ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin18]
    RubyGems : 3.1.2
        Host : Mac OS X 10.14.6 (18G5033)
       Xcode : 11.3.1 (11C504)
         Git : git version 2.21.1 (Apple Git-122.3)
Ruby lib dir : /usr/local/Cellar/ruby/2.7.1_2/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ 20b7aba372871e85091f22d846deb3c3d83531b5

               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target '<AppName>' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"

  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'
  pod 'React-RCTPushNotification', :path => '../node_modules/react-native/Libraries/PushNotificationIOS'
  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
  pod 'appcenter', path: '../node_modules/appcenter/ios'
  pod 'appcenter-crashes', path: '../node_modules/appcenter-crashes/ios'
  pod 'Intercom'
  pod 'react-native-intercom', path: '../node_modules/react-native-intercom'
  pod 'CodePush', :path => '../node_modules/react-native-code-push'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
  pod 'Firebase/Core', '~> 6.3.0'
  pod 'Firebase/Messaging', '~> 6.3.0'
  pod 'react-native-appsflyer', :path => '../node_modules/react-native-appsflyer'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
  pod 'RNSecureKeyStore', :path => '../node_modules/react-native-secure-key-store/ios'
  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  pod 'RNRate', :path => '../node_modules/react-native-rate'

  pod 'react-native-sensitive-info', :path => '../node_modules/react-native-sensitive-info/'

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'react-native-appearance', :path => '../node_modules/react-native-appearance'

  pod 'react-native-document-picker', :path => '../node_modules/react-native-document-picker'

  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'


  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'RNSentry', :path => '../node_modules/@sentry/react-native'

end
```

### Error

```
Errno::ENOENT - No such file or directory @ rb_sysopen - /Users/<username>/Documents/GitHub/almond-mobile/ios/Pods/Local Podspecs/appcenter.podspec.json
/usr/local/Cellar/cocoapods/1.9.3/libexec/gems/cocoapods-core-1.9.3/lib/cocoapods-core/specification.rb:673:in `read'
/usr/local/Cellar/cocoapods/1.9.3/libexec/gems/cocoapods-core-1.9.3/lib/cocoapods-core/specification.rb:673:in `checksum'
/usr/local/Cellar/cocoapods/1.9.3/libexec/gems/cocoapods-core-1.9.3/lib/cocoapods-core/lockfile.rb:533:in `block in generate_checksums'
/usr/local/Cellar/cocoapods/1.9.3/libexec/gems/cocoapods-core-1.9.3/lib/cocoapods-core/lockfile.rb:532:in `each'
/usr/local/Cellar/cocoapods/1.9.3/libexec/gems/cocoapods-core-1.9.3/lib/cocoapods-core/lockfile.rb:532:in `generate_checksums'
/usr/local/Cellar/cocoapods/1.9.3/libexec/gems/cocoapods-core-1.9.3/lib/cocoapods-core/lockfile.rb:428:in `generate'
/usr/local/Cellar/cocoapods/1.9.3/libexec/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:744:in `generate_lockfile'
/usr/local/Cellar/cocoapods/1.9.3/libexec/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:752:in `write_lockfiles'
/usr/local/Cellar/cocoapods/1.9.3/libexec/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:164:in `install!'
/usr/local/Cellar/cocoapods/1.9.3/libexec/gems/cocoapods-1.9.3/lib/cocoapods/command/install.rb:52:in `run'
/usr/local/Cellar/cocoapods/1.9.3/libexec/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/usr/local/Cellar/cocoapods/1.9.3/libexec/gems/cocoapods-1.9.3/lib/cocoapods/command.rb:52:in `run'
/usr/local/Cellar/cocoapods/1.9.3/libexec/gems/cocoapods-1.9.3/bin/pod:55:in `<top (required)>'
/usr/local/Cellar/cocoapods/1.9.3/libexec/bin/pod:23:in `load'
/usr/local/Cellar/cocoapods/1.9.3/libexec/bin/pod:23:in `<main>'
```

**Comment by dnkoutso** [comment]
Please upload a sample app that reproduces the issue _without_ Reactnative

**Comment by aditibarbhai** [comment]
I was able to resolve this issue by changing my appcenter version and renaming the pod to "appcenter-core".
