### ISSUE TITLE
get error when use pod command 

### ISSUE THREAD

**Issue by imansalhi** [CocoaPods/CocoaPods#9941]
# Report

I install cocoapods with `sudo gem install cocoapods` in my react-native project, however i get this error when i do pod install or every command starts with pod

```
/Applications/MAMP/Library/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': dlopen(/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/ffi-1.13.1/lib/ffi_c.bundle, 9): no suitable image found.  Did find: (LoadError)
        /Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/ffi-1.13.1/lib/ffi_c.bundle: code signature in (/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/ffi-1.13.1/lib/ffi_c.bundle) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed. - /Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/ffi-1.13.1/lib/ffi_c.bundle
        from /Applications/MAMP/Library/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/ffi-1.13.1/lib/ffi.rb:6:in `rescue in <top (required)>'
        from /Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/ffi-1.13.1/lib/ffi.rb:3:in `<top (required)>'
        from /Applications/MAMP/Library/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Applications/MAMP/Library/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/ethon-0.12.0/lib/ethon.rb:2:in `<top (required)>'
        from /Applications/MAMP/Library/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Applications/MAMP/Library/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
        from /Applications/MAMP/Library/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Applications/MAMP/Library/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-1.9.3/lib/cocoapods/sources_manager.rb:5:in `<top (required)>'
        from /Applications/MAMP/Library/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Applications/MAMP/Library/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-1.9.3/lib/cocoapods/core_overrides.rb:1:in `<top (required)>'
        from /Applications/MAMP/Library/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Applications/MAMP/Library/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-1.9.3/lib/cocoapods.rb:75:in `<module:Pod>'
        from /Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-1.9.3/lib/cocoapods.rb:17:in `<top (required)>'
        from /Applications/MAMP/Library/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
        from /Applications/MAMP/Library/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
        from /Applications/MAMP/Library/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from /Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-1.9.3/bin/pod:36:in `<top (required)>'
        from /Applications/MAMP/Library/bin/pod:22:in `load'
        from /Applications/MAMP/Library/bin/pod:22:in `<main>'
```

## What did you do?

ℹ  sudo gem install cocoapods & 
pod install << get error here  

## What did you expect to happen?

ℹ be able to use pod command 

## What happened instead?

ℹ i get above error whenever use `pod` commands ...  

## CocoaPods Environment

ℹ  i get same error when run pod env 😢 

My Mac-OS is Catalina

**Comment by dnkoutso** [comment]
This seems an issue with installing. the `ffi` gem that CocoaPods depends upon. I would file an issue with them instead.

**Comment by jcush** [comment]
@dnkoutso Hi,

I'm having the exact same issue currently - I've raised the following issue with FFI: https://github.com/ffi/ffi/issues/836

However, the owner of that repo apparently doesn't own a Mac and knows little about the build process. If you look in that issue you should see all the info I've tried to give him from myself directly and from Apple, but if you're able to assist by adding anything he might need to know (or where to look in the resources I linked) I would _hugely_ appreciate it.

I appreciate you're probably busy and being a dev too I understand how vague issues can be when they're in third-party packages, but in building with CocoaPods everything's third-party to us :-) 

Any info I can contribute more to help please let me know

Thanks

James
