### ISSUE TITLE
Unable to add a source with url `https://github.com/CocoaPods/Specs.git` named `cocoapods`

### ISSUE THREAD

**Issue by quetool** [CocoaPods/CocoaPods#9947]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

`pod install`

## What did you expect to happen?

Install all pod dependencies correctly.

## What happened instead?

```
LAP0231s-MacBook-Pro:mi-banco-ios-universal alfredo.rinaudo$ pod install
Analyzing dependencies
Cloning spec repo `cocoapods` from `https://github.com/CocoaPods/Specs.git`
[!] Unable to add a source with url `https://github.com/CocoaPods/Specs.git` named `cocoapods`.
You can try adding it manually in `/Users/alfredo.rinaudo/.cocoapods/repos` or via `pod repo add`.
```

### Stack

```
   CocoaPods : 1.9.3
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.6 (19G73)
       Xcode : 11.5 (11E608c)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
HEAD

               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

def mibanco_pods
    pod 'AFNetworking'
    pod 'PureLayout'
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
    pod 'GoogleTagManager'
    pod 'Flurry-iOS-SDK/FlurrySDK'
    pod 'NewRelicAgent'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'MaterialComponents/Buttons'
end

def mibanco_watchpods
    pod 'Flurry-iOS-SDK/FlurryWatchOSSDK'
    platform :watchos, '3.0'
end

target "MiBanco-AppleStore" do
    mibanco_pods
end

target "MiBanco-Pilot" do
    mibanco_pods
end

target "MiBancoQA" do
    mibanco_pods
end

target "MiBancoDev" do
    mibanco_pods
end

target "MiBancoObjCTests" do
  mibanco_pods
  inherit! :search_paths
  use_frameworks!
  pod 'OCMockito', '~> 5.0'
end

target "MiBancoSwiftTests" do
  mibanco_pods
  inherit! :search_paths
  use_frameworks!
  pod 'MockingbirdFramework', '~> 0.14'
end

target "MiBancoWatchExtension" do
    mibanco_watchpods
end

target "MiBanco-PilotWatchExtension" do
    mibanco_watchpods
end

target "MiBancoQAWatchExtension" do
    mibanco_watchpods
end

target "MiBancoDevWatchExtension" do
    mibanco_watchpods
end
```

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

**Comment by quetool** [comment]
UPDATE:

I just found this https://github.com/CocoaPods/CocoaPods/issues/4293#issuecomment-144381841

So I ran `pod setup` then `pod install` and this is my new output

```
LAP0231s-MacBook-Pro:mi-banco-ios-universal alfredo.rinaudo$ pod setup
Setup completed
LAP0231s-MacBook-Pro:mi-banco-ios-universal alfredo.rinaudo$ pod install
Analyzing dependencies
[!] Unable to find a specification for `AFNetworking`

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

LAP0231s-MacBook-Pro:mi-banco-ios-universal alfredo.rinaudo$ pod repo update
Updating spec repo `cocoapods`
  $ /usr/bin/git -C /Users/alfredo.rinaudo/.cocoapods/repos/cocoapods fetch origin --progress
  fatal: unable to access 'https://github.com/CocoaPods/Specs.git/': Failed to connect to 10.1.32.228 port 8080: Operation timed out
[!] CocoaPods was not able to update the `cocoapods` repo. If this is an unexpected issue and persists you can inspect it running `pod repo update --verbose`
LAP0231s-MacBook-Pro:mi-banco-ios-universal alfredo.rinaudo$ 
```

**Comment by dnkoutso** [comment]
Can you run the same command with `--verbose` and print the output here? I suspect this is a network issue preventing you from cloning the master specs repo which is now huge.

I also recommend removing `source` from `Podfile` and lean on the CDN.

**Comment by quetool** [comment]
Ok, removing source from Podfile worked but now I have another issue

```
LAP0231s-MacBook-Pro:mi-banco-ios-universal alfredo.rinaudo$ pod install
Analyzing dependencies
Adding spec repo `trunk` with CDN `https://cdn.cocoapods.org/`

CocoaPods 1.10.0.beta.1 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.10.0.beta.1

[!] Unable to find a specification for `PureLayout`

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

LAP0231s-MacBook-Pro:mi-banco-ios-universal alfredo.rinaudo$ 
```

**Comment by dnkoutso** [comment]
Can you do `pod install --repo-update`?

**Comment by quetool** [comment]
Already tried, the output is pretty much the same

```
LAP0231s-MacBook-Pro:mi-banco-ios-universal alfredo.rinaudo$ pod install --repo-update
Updating local specs repositories

CocoaPods 1.10.0.beta.1 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.10.0.beta.1

Analyzing dependencies
[!] Unable to find a specification for `PureLayout`

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

LAP0231s-MacBook-Pro:mi-banco-ios-universal alfredo.rinaudo$
```

--verbose
```
  Preparing

Updating local specs repositories
  CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only perfomed in repo update

Updating spec repo `trunk`
  CDN: trunk Relative path: deprecated_podspecs.txt, has ETag? "f96c2cf83ddfc44e9294f992fd5d9390-ssl-df"
  CDN: trunk Relative path not modified: deprecated_podspecs.txt
  CDN: trunk Going to update 2 files
  CDN: trunk Relative path: all_pods_versions_a_7_5.txt, has ETag? "8a0eb0065a34ead56252d6dfa408a3d3-ssl-df"
  CDN: trunk Relative path: CocoaPods-version.yml, has ETag? "871dbc3ac66ab065476ee696d0c77eeb-ssl"
  CDN: trunk Relative path downloaded: all_pods_versions_a_7_5.txt, save ETag: "8a0eb0065a34ead56252d6dfa408a3d3-ssl-df"
  CDN: trunk Relative path not modified: CocoaPods-version.yml

CocoaPods 1.10.0.beta.1 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.10.0.beta.1


Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-MiBanco-AppleStore`: (``)
  Using `ARCHS` setting to build architectures of target `Pods-MiBanco-Pilot`: (``)
  Using `ARCHS` setting to build architectures of target `Pods-MiBancoQA`: (``)
  Using `ARCHS` setting to build architectures of target `Pods-MiBancoDev`: (``)
  Using `ARCHS` setting to build architectures of target `Pods-MiBancoObjCTests`: (``)
  Using `ARCHS` setting to build architectures of target `Pods-MiBancoSwiftTests`: (``)
  Using `ARCHS` setting to build architectures of target `Pods-MiBancoWatchExtension`: (``)
  Using `ARCHS` setting to build architectures of target `Pods-MiBanco-PilotWatchExtension`: (``)
  Using `ARCHS` setting to build architectures of target `Pods-MiBancoQAWatchExtension`: (``)
  Using `ARCHS` setting to build architectures of target `Pods-MiBancoDevWatchExtension`: (``)

Finding Podfile changes
  A MockingbirdFramework
  M AFNetworking
  - Alamofire
  - Crashlytics
  - Fabric
  - Firebase
  - Flurry-iOS-SDK
  - GoogleTagManager
  - MaterialComponents
  - NewRelicAgent
  - OCMockito
  - PureLayout
  - SwiftyJSON

Resolving dependencies of `Podfile`
  CDN: trunk Relative path: all_pods_versions_a_7_5.txt modified during this run! Returning local
  CDN: trunk Relative path: Specs/a/7/5/AFNetworking/4.0.1/AFNetworking.podspec.json exists! Returning local because checking is only perfomed in repo update
[!] Unable to find a specification for `PureLayout`

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/resolver.rb:389:in `find_cached_set'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/resolver.rb:360:in `specifications_for_dependency'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/resolver.rb:165:in `search_for'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/resolver.rb:274:in `block in sort_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/resolver.rb:267:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/resolver.rb:267:in `sort_by'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/resolver.rb:267:in `sort_dependencies'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:53:in `block in sort_dependencies'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:70:in `with_no_such_dependency_error_handling'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:52:in `sort_dependencies'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:288:in `initial_state'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:210:in `start_resolution'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:168:in `resolve'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/resolver.rb:94:in `resolve'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer.rb:1065:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer.rb:1063:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:410:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:235:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:234:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:156:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by quetool** [comment]
Ok, it took a while but it worked! Thanks!

**Comment by ghasemikasra39** [comment]
` pod install --repo-update --verbose`:
```
  remote: Enumerating objects: 28, done.
  remote: Counting objects: 100% (28/28), done.
  remote: Compressing objects: 100% (18/18), done.
  remote: Total 18 (delta 12), reused 0 (delta 0), pack-reused 0
  From https://github.com/CocoaPods/Specs
     9a05d0f3782a..ff9bf47e4d97  master     -> origin/master
  error: invalid path 'Specs/c/f/f/XCActionSheet./0.0.2/XCActionSheet..podspec.json'
  fatal: Could not reset index file to revision 'origin/master'.
Installing unimodules:
 expo-apple-authentication@2.0.0 from ../node_modules/expo-apple-authentication/ios
 expo-av@8.0.0 from ../node_modules/expo-av/ios
 expo-blur@8.1.2 from ../node_modules/expo-blur/ios
 expo-camera@8.2.0 from ../node_modules/expo-camera/ios
 expo-constants@9.2.0 from ../node_modules/react-native-unimodules/node_modules/expo-constants/ios
 expo-device@2.0.0 from ../node_modules/expo-device/ios
 expo-error-recovery@1.3.0 from ../node_modules/expo-error-recovery/ios
 expo-facebook@8.1.0 from ../node_modules/expo-facebook/ios
 expo-file-system@9.2.0 from ../node_modules/react-native-unimodules/node_modules/expo-file-system/ios
 expo-font@8.3.0 from ../node_modules/expo-font/ios
 expo-image-loader@1.2.0 from ../node_modules/expo-image-loader/ios
 expo-image-manipulator@8.1.0 from ../node_modules/expo-image-manipulator/ios
 expo-image-picker@8.1.0 from ../node_modules/expo-image-picker/ios
 expo-keep-awake@8.3.0 from ../node_modules/expo-keep-awake/ios
 expo-linear-gradient@8.3.1 from ../node_modules/expo/node_modules/expo-linear-gradient/ios
 expo-location@9.0.1 from ../node_modules/expo/node_modules/expo-location/ios
 expo-permissions@9.3.0 from ../node_modules/expo-permissions/ios
 expo-secure-store@8.0.0 from ../node_modules/expo-secure-store/ios
 expo-sensors@9.0.1 from ../node_modules/expo-sensors/ios
 expo-splash-screen@0.6.2 from ../node_modules/expo-splash-screen/ios
 expo-sqlite@8.4.0 from ../node_modules/expo-sqlite/ios
 unimodules-app-loader@1.3.0 from ../node_modules/unimodules-app-loader/ios
 unimodules-barcode-scanner-interface@5.3.0 from ../node_modules/unimodules-barcode-scanner-interface/ios
 unimodules-camera-interface@5.3.0 from ../node_modules/unimodules-camera-interface/ios
 unimodules-constants-interface@5.3.0 from ../node_modules/unimodules-constants-interface/ios
 unimodules-core@5.5.1 from ../node_modules/@unimodules/core/ios
 unimodules-face-detector-interface@5.3.0 from ../node_modules/unimodules-face-detector-interface/ios
 unimodules-file-system-interface@5.3.0 from ../node_modules/unimodules-file-system-interface/ios
 unimodules-font-interface@5.3.0 from ../node_modules/unimodules-font-interface/ios
 unimodules-image-loader-interface@5.3.0 from ../node_modules/unimodules-image-loader-interface/ios
 unimodules-permissions-interface@5.3.0 from ../node_modules/unimodules-permissions-interface/ios
 unimodules-react-native-adapter@5.6.0 from ../node_modules/@unimodules/react-native-adapter/ios
 unimodules-sensors-interface@5.3.0 from ../node_modules/unimodules-sensors-interface/ios
 unimodules-task-manager-interface@5.3.0 from ../node_modules/unimodules-task-manager-interface/ios

Found some duplicated unimodule packages. Installed the ones with the highest version number.
Make sure following dependencies of your project are resolving to one specific version:
 expo-constants, expo-file-system, expo-linear-gradient, expo-location, expo-permissions

  $ C:/Program Files/nodejs/node.exe -e try {console.log(require('@react-native-community/cli').bin);} catch (e) {console.log(require('react-native/cli').bin);}
  C:\Users\Kasra\Documents\youpendo-app-bareworkflow\node_modules\@react-native-community\cli\build\bin.js
Using firebase.json from 'C:/Users/Kasra/Documents/youpendo-app-bareworkflow/firebase.json'
Adding a custom script phase for Pod RNFBApp: [RNFB] Core Configuration
Adding a custom script phase for Pod RNFBCrashlytics: [RNFB] Crashlytics Configuration
Auto-linking React Native modules for target `YoupendoApp`: CodePush, RNBootSplash, RNCAsyncStorage, RNCClipboard, RNCMaskedView, RNCPushNotificationIOS, RNFBAnalytics, RNFBApp, RNFBAuth, RNFBCrashlytics, RNFBDynamicLinks, RNFBFirestore, RNFBMessaging, RNFS, RNGestureHandler, RNReanimated, RNSVG, RNScreens, RNShare, lottie-ios, lottie-react-native, react-native-fetch-blob, react-native-maps, react-native-mixpanel, react-native-netinfo, react-native-safe-area-context, react-native-shimmer, react-native-sms, react-native-video, and react-native-view-shot
  $ C:/Program Files/nodejs/node.exe -e try {console.log(require('@react-native-community/cli').bin);} catch (e) {console.log(require('react-native/cli').bin);}
  C:\Users\Kasra\Documents\youpendo-app-bareworkflow\node_modules\@react-native-community\cli\build\bin.js
  Preparing

Updating local specs repositories

Updating spec repo `cocoapods`
  $ C:/Program Files/Git/mingw64/bin/git.exe -C C:/Users/Kasra/.cocoapods/repos/cocoapods fetch origin --progress
  $ C:/Program Files/Git/mingw64/bin/git.exe -C C:/Users/Kasra/.cocoapods/repos/cocoapods rev-parse --abbrev-ref HEAD
  master
  $ C:/Program Files/Git/mingw64/bin/git.exe -C C:/Users/Kasra/.cocoapods/repos/cocoapods reset --hard origin/master
[!] CocoaPods was not able to update the `cocoapods` repo. If this is an unexpected issue and persists you can inspect it running `pod repo update --verbose`

C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/sources_manager.rb:178:in `rescue in update_git_repo'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/sources_manager.rb:169:in `update_git_repo'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/source.rb:347:in `update'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/sources_manager.rb:135:in `block (3 levels) in update'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/user_interface.rb:64:in `section'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/sources_manager.rb:134:in `block (2 levels) in update'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/sources_manager.rb:133:in `each'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/sources_manager.rb:133:in `block in update'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/sources_manager.rb:131:in `open'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/sources_manager.rb:131:in `update'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:145:in `block in update_repositories'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:143:in `each'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:143:in `update_repositories'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:235:in `block in resolve_dependencies'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/user_interface.rb:64:in `section'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:234:in `resolve_dependencies'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:160:in `install!'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/command/install.rb:52:in `run'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/command.rb:52:in `run'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/bin/pod:55:in `<top (required)>'
C:/Ruby27-x64/bin/pod:23:in `load'
C:/Ruby27-x64/bin/pod:23:in `<main>'

```

Podfile:
```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

workspace 'YoupendoApp.xcworkspace/'
project 'YoupendoApp.xcodeproj/'

source 'https://github.com/CocoaPods/Specs.git'
# source 'https://cdn.cocoapods.org/'

target 'YoupendoApp' do

  use_unimodules!
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # React Native Maps dependencies
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'

  # react-native-cli autolinking
  use_native_modules!

  pod 'react-native-view-shot', :path => '../node_modules/react-native-view-shot'

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end


```

When commenting the `source`:
```
  Cloning into 'trunk'...
  fatal: repository 'https://cdn.cocoapods.org/' not found
Installing unimodules:
 expo-apple-authentication@2.0.0 from ../node_modules/expo-apple-authentication/ios
 expo-av@8.0.0 from ../node_modules/expo-av/ios
 expo-blur@8.1.2 from ../node_modules/expo-blur/ios
 expo-camera@8.2.0 from ../node_modules/expo-camera/ios
 expo-constants@9.2.0 from ../node_modules/react-native-unimodules/node_modules/expo-constants/ios
 expo-device@2.0.0 from ../node_modules/expo-device/ios
 expo-error-recovery@1.3.0 from ../node_modules/expo-error-recovery/ios
 expo-facebook@8.1.0 from ../node_modules/expo-facebook/ios
 expo-file-system@9.2.0 from ../node_modules/react-native-unimodules/node_modules/expo-file-system/ios
 expo-font@8.3.0 from ../node_modules/expo-font/ios
 expo-image-loader@1.2.0 from ../node_modules/expo-image-loader/ios
 expo-image-manipulator@8.1.0 from ../node_modules/expo-image-manipulator/ios
 expo-image-picker@8.1.0 from ../node_modules/expo-image-picker/ios
 expo-keep-awake@8.3.0 from ../node_modules/expo-keep-awake/ios
 expo-linear-gradient@8.3.1 from ../node_modules/expo/node_modules/expo-linear-gradient/ios
 expo-location@9.0.1 from ../node_modules/expo/node_modules/expo-location/ios
 expo-permissions@9.3.0 from ../node_modules/expo-permissions/ios
 expo-secure-store@8.0.0 from ../node_modules/expo-secure-store/ios
 expo-sensors@9.0.1 from ../node_modules/expo-sensors/ios
 expo-splash-screen@0.6.2 from ../node_modules/expo-splash-screen/ios
 expo-sqlite@8.4.0 from ../node_modules/expo-sqlite/ios
 unimodules-app-loader@1.3.0 from ../node_modules/unimodules-app-loader/ios
 unimodules-barcode-scanner-interface@5.3.0 from ../node_modules/unimodules-barcode-scanner-interface/ios
 unimodules-camera-interface@5.3.0 from ../node_modules/unimodules-camera-interface/ios
 unimodules-constants-interface@5.3.0 from ../node_modules/unimodules-constants-interface/ios
 unimodules-core@5.5.1 from ../node_modules/@unimodules/core/ios
 unimodules-face-detector-interface@5.3.0 from ../node_modules/unimodules-face-detector-interface/ios
 unimodules-file-system-interface@5.3.0 from ../node_modules/unimodules-file-system-interface/ios
 unimodules-font-interface@5.3.0 from ../node_modules/unimodules-font-interface/ios
 unimodules-image-loader-interface@5.3.0 from ../node_modules/unimodules-image-loader-interface/ios
 unimodules-permissions-interface@5.3.0 from ../node_modules/unimodules-permissions-interface/ios
 unimodules-react-native-adapter@5.6.0 from ../node_modules/@unimodules/react-native-adapter/ios
 unimodules-sensors-interface@5.3.0 from ../node_modules/unimodules-sensors-interface/ios
 unimodules-task-manager-interface@5.3.0 from ../node_modules/unimodules-task-manager-interface/ios

Found some duplicated unimodule packages. Installed the ones with the highest version number.
Make sure following dependencies of your project are resolving to one specific version:
 expo-constants, expo-file-system, expo-linear-gradient, expo-location, expo-permissions

  $ C:/Program Files/nodejs/node.exe -e try {console.log(require('@react-native-community/cli').bin);} catch (e) {console.log(require('react-native/cli').bin);}
  C:\Users\Kasra\Documents\youpendo-app-bareworkflow\node_modules\@react-native-community\cli\build\bin.js
Using firebase.json from 'C:/Users/Kasra/Documents/youpendo-app-bareworkflow/firebase.json'
Adding a custom script phase for Pod RNFBApp: [RNFB] Core Configuration
Adding a custom script phase for Pod RNFBCrashlytics: [RNFB] Crashlytics Configuration
Auto-linking React Native modules for target `YoupendoApp`: CodePush, RNBootSplash, RNCAsyncStorage, RNCClipboard, RNCMaskedView, RNCPushNotificationIOS, RNFBAnalytics, RNFBApp, RNFBAuth, RNFBCrashlytics, RNFBDynamicLinks, RNFBFirestore, RNFBMessaging, RNFS, RNGestureHandler, RNReanimated, RNSVG, RNScreens, RNShare, lottie-ios, lottie-react-native, react-native-fetch-blob, react-native-maps, react-native-mixpanel, react-native-netinfo, react-native-safe-area-context, react-native-shimmer, react-native-sms, react-native-video, and react-native-view-shot
  $ C:/Program Files/nodejs/node.exe -e try {console.log(require('@react-native-community/cli').bin);} catch (e) {console.log(require('react-native/cli').bin);}
  C:\Users\Kasra\Documents\youpendo-app-bareworkflow\node_modules\@react-native-community\cli\build\bin.js
  Preparing

Updating local specs repositories

Cloning spec repo `trunk` from `https://cdn.cocoapods.org/`
  $ C:/Program Files/Git/mingw64/bin/git.exe clone https://cdn.cocoapods.org/ -- trunk
[!] Unable to add a source with url `https://cdn.cocoapods.org/` named `trunk`.
(C:/Program Files/Git/mingw64/bin/git.exe clone https://cdn.cocoapods.org/ -- trunk

Cloning into 'trunk'...
fatal: repository 'https://cdn.cocoapods.org/' not found
)
You can try adding it manually in `C:/Users/Kasra/.cocoapods/repos` or via `pod repo add`.

C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/sources_manager.rb:54:in `rescue in create_source_with_url'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/sources_manager.rb:48:in `create_source_with_url'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/sources_manager.rb:21:in `find_or_create_source_with_url'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:178:in `block in sources'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:177:in `map'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:177:in `sources'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:143:in `update_repositories'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:235:in `block in resolve_dependencies'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/user_interface.rb:64:in `section'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:234:in `resolve_dependencies'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:160:in `install!'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/command/install.rb:52:in `run'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/lib/cocoapods/command.rb:52:in `run'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0/bin/pod:55:in `<top (required)>'
C:/Ruby27-x64/bin/pod:23:in `load'
C:/Ruby27-x64/bin/pod:23:in `<main>'


```

**Comment by ahmedbhd** [comment]
I commented "source 'https://github.com/CocoaPods/Specs.git'" in my podfile and it worked.

**Comment by shahjahanpak** [comment]
I was able to do it using 
```sh
cd ~/.cocoapods/repos
git clone https://github.com/CocoaPods/Specs.git cocoapods
```
