### ISSUE TITLE
could not install 

### ISSUE THREAD

**Issue by jinmin888** [CocoaPods/CocoaPods#9961]
Report

## What did you do?

 Run `pod install`

## What did you expect to happen?

Install all pod dependencies correctly.

### Error

```
NoMethodError - undefined method `gsub' for {"MembershipSDK"=>["MembershipSDK/LocalizedStrings/*.lproj/*"]}:Hash
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.2/lib/cocoapods/sandbox/path_list.rb:195:in `dir_glob_equivalent_patterns'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.2/lib/cocoapods/sandbox/path_list.rb:140:in `block in relative_glob'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.2/lib/cocoapods/sandbox/path_list.rb:132:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.2/lib/cocoapods/sandbox/path_list.rb:132:in `flat_map'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.2/lib/cocoapods/sandbox/path_list.rb:132:in `relative_glob'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.2/lib/cocoapods/sandbox/path_list.rb:92:in `glob'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.2/lib/cocoapods/sandbox/file_accessor.rb:444:in `expanded_paths'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.2/lib/cocoapods/sandbox/file_accessor.rb:416:in `paths_for_attribute'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.2/lib/cocoapods/sandbox/file_accessor.rb:85:in `source_files'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.2/lib/cocoapods/target/pod_target.rb:235:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.2/lib/cocoapods/target/pod_target.rb:235:in `flat_map'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.2/lib/cocoapods/target/pod_target.rb:235:in `should_build?'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.2/lib/cocoapods/installer/xcode/target_validator.rb:50:in `block (3 levels) in verify_no_duplicate_framework_and_library_names'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.2/lib/cocoapods/installer/xcode/target_validator.rb:50:in `select'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.2/lib/cocoapods/installer/xcode/target_validator.rb:50:in `block (2 levels) in verify_no_duplicate_framework_and_library_names'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.2/lib/cocoapods/installer/xcode/target_validator.rb:45:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.2/lib/cocoapods/installer/xcode/target_validator.rb:45:in `block in verify_no_duplicate_framework_and_library_names'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.2/lib/cocoapods/installer/xcode/target_validator.rb:44:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.2/lib/cocoapods/installer/xcode/target_validator.rb:44:in `verify_no_duplicate_framework_and_library_names'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.2/lib/cocoapods/installer/xcode/target_validator.rb:35:in `validate!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.2/lib/cocoapods/installer.rb:578:in `validate_targets'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.2/lib/cocoapods/installer.rb:158:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.2/lib/cocoapods/command/install.rb:51:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.2/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.7.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

## CocoaPods Environment
```
   CocoaPods : 1.7.2
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.6 (19G60d)
       Xcode : 11.6 (11E708)
         Git : git version 2.19.2
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : co-iosmembersipsdk_spec - git@github.smartstudy.co.kr:tech/iOSMembersipSDK_Spec.git @ ecee055bd363ea1087524df486ef5b15c2d873fb
               co-pinkfongidlib_spec - git@github.smartstudy.co.kr:tech/PinkfongIDLib_Spec.git @ 88f685d89b886d80db4f08378bdbb024b269b77a
               master - https://github.com/CocoaPods/Specs.git @ e33a4fb9f1bdeef6efe63528ba076a0626567920
               PinkfongIDLib - https://github.smartstudy.co.kr/tech/ios_pid_lib.git @ d77431ac196b0977eb7eab7824f2b6688f123908
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
use_frameworks!

platform :ios, '9.0'

source 'git@github.smartstudy.co.kr:tech/iOSMembersipSDK_Spec.git’
source 'https://github.com/CocoaPods/Specs.git'


target 'MembershipSDKSample' do
  pod 'MembershipSDK', :path => '../'
  pod 'MBProgressHUD'
  pod 'KidsLock'

  target 'MembershipSDK_Tests' do
    inherit! :search_paths


  end
end
```
## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

**Comment by dnkoutso** [comment]
Need a sample app here. Also you are using an old version of CocoaPods. Can you bump to 1.9.3?
