### ISSUE TITLE
 undefined method `create_or_update_build_phase' for Pod::Installer::UserProjectIntegrator::TargetIntegrator:Class

### ISSUE THREAD

**Issue by foolzzz** [CocoaPods/CocoaPods#9984]
### Error

```
NoMethodError - undefined method `create_or_update_build_phase' for Pod::Installer::UserProjectIntegrator::TargetIntegrator:Class
Did you mean?  create_or_update_shell_script_build_phase
/Users/fa11ing1eaf/.rvm/gems/ruby-2.7.0/gems/cocoapods-xcfilelist-patch-0.0.4/lib/cocoapods-xcfilelist-patch/target_integrator_patch.rb:37:in `create_or_update_copy_resources_script_phase_to_target'
/Users/fa11ing1eaf/.rvm/gems/ruby-2.7.0/gems/cocoapods-xcfilelist-patch-0.0.4/lib/cocoapods-xcfilelist-patch/target_integrator_patch.rb:20:in `block in add_copy_resources_script_phase'
/Users/fa11ing1eaf/.rvm/gems/ruby-2.7.0/gems/cocoapods-xcfilelist-patch-0.0.4/lib/cocoapods-xcfilelist-patch/target_integrator_patch.rb:9:in `each'
/Users/fa11ing1eaf/.rvm/gems/ruby-2.7.0/gems/cocoapods-xcfilelist-patch-0.0.4/lib/cocoapods-xcfilelist-patch/target_integrator_patch.rb:9:in `add_copy_resources_script_phase'
/Users/fa11ing1eaf/.rvm/gems/ruby-2.7.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/user_project_integrator/target_integrator.rb:405:in `block in integrate!'
/Users/fa11ing1eaf/.rvm/gems/ruby-2.7.0/gems/cocoapods-1.9.3/lib/cocoapods/user_interface.rb:64:in `section'
/Users/fa11ing1eaf/.rvm/gems/ruby-2.7.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/user_project_integrator/target_integrator.rb:398:in `integrate!'
/Users/fa11ing1eaf/.rvm/gems/ruby-2.7.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/user_project_integrator.rb:146:in `each'
/Users/fa11ing1eaf/.rvm/gems/ruby-2.7.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/user_project_integrator.rb:146:in `integrate_user_targets'
/Users/fa11ing1eaf/.rvm/gems/ruby-2.7.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/user_project_integrator.rb:73:in `integrate!'
/Users/fa11ing1eaf/.rvm/gems/ruby-2.7.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:801:in `block in integrate_user_project'
/Users/fa11ing1eaf/.rvm/gems/ruby-2.7.0/gems/cocoapods-1.9.3/lib/cocoapods/user_interface.rb:64:in `section'
/Users/fa11ing1eaf/.rvm/gems/ruby-2.7.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:797:in `integrate_user_project'
/Users/fa11ing1eaf/.rvm/gems/ruby-2.7.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:176:in `integrate'
/Users/fa11ing1eaf/.rvm/gems/ruby-2.7.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:162:in `install!'
/Users/fa11ing1eaf/.rvm/gems/ruby-2.7.0/gems/cocoapods-1.9.3/lib/cocoapods/command/install.rb:52:in `run'
/Users/fa11ing1eaf/.rvm/gems/ruby-2.7.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/fa11ing1eaf/.rvm/gems/ruby-2.7.0/gems/cocoapods-1.9.3/lib/cocoapods/command.rb:52:in `run'
/Users/fa11ing1eaf/.rvm/gems/ruby-2.7.0/gems/cocoapods-1.9.3/bin/pod:55:in `<top (required)>'
/Users/fa11ing1eaf/.rvm/gems/ruby-2.7.0/bin/pod:23:in `load'
/Users/fa11ing1eaf/.rvm/gems/ruby-2.7.0/bin/pod:23:in `<main>'
/Users/fa11ing1eaf/.rvm/gems/ruby-2.7.0/bin/ruby_executable_hooks:24:in `eval'
/Users/fa11ing1eaf/.rvm/gems/ruby-2.7.0/bin/ruby_executable_hooks:24:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

**Comment by dnkoutso** [comment]
looks like a bug with `cocoapods-xcfilelist-patch-0.0.4` gem (cocoapods plugin) please file a bug at their repo.
