### ISSUE TITLE
'pod install' failed, for error see inside. <3 Thank you for helping me <3

### ISSUE THREAD

**Issue by eri47** [CocoaPods/CocoaPods#9991]
* [YES] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I ran `pod install`

## What did you expect to happen?

That pod would install correctly, because i had an other [issue with React Native](https://stackoverflow.com/questions/56916798/react-rctbridgedelegate-h-file-not-found), so i had to check all the dependencies...

## What happened instead?

I got this Error:
```
JSON::ParserError - 767: unexpected token at '{
  "name": "Flipper",
  "version": "0.41.2",
  "license": {
    "type": "MIT"
  },
  "homepage": "https://github.com/facebook/sonar",
  "summary": "SonarKit core cpp code with network implementation",
  "authors": "Facebook",
  "source": {
    "git": "https://github.com/facebook/Sonar.git",
    "tag": "v0.41.0"
  },
  "module_name": "Flipper",
  "public_header_files": [
    "xplat/Flipper/*.h",
    "xplat/utils/*.h"
  ],
  "source_files": [
    "xplat/Flipper/*.{h,cpp,m,mm}",
    "xplat/Flipper/utils/*.{h,cpp,m,mm}"
  ],
  "libraries": "stdc++",
  "dependencies": {
    "Flipper-Folly": [
      "~> 2.2"
    ],
    "Flipper-RSocket": [
      "~> 1.1"
    ]
  },
  "compiler_flags": "-DFLIP'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.3/lib/cocoapods-core/specification/json.rb:61:in `from_json'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.3/lib/cocoapods-core/specification.rb:742:in `from_string'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.3/lib/cocoapods-core/specification.rb:716:in `from_file'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.3/lib/cocoapods-core/source.rb:186:in `specification'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/resolver/lazy_specification.rb:37:in `specification'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:348:in `block in delegating_block'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:349:in `block in delegating_block'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/resolver.rb:178:in `dependencies_for'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:18:in `block in dependencies_for'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:70:in `with_no_such_dependency_error_handling'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:17:in `dependencies_for'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:807:in `block in group_possibilities'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:806:in `reverse_each'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:806:in `group_possibilities'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:778:in `possibilities_for_requirement'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:761:in `push_state_for_requirements'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:746:in `require_nested_dependencies_for'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:729:in `activate_new_spec'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:686:in `attempt_to_activate'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:254:in `process_topmost_state'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/resolver.rb:94:in `resolve'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer.rb:1065:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer.rb:1063:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:410:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:235:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:234:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:156:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

### Stack

```
   CocoaPods : 1.9.3
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.6 (19G2021)
       Xcode : 11.6 (11E708)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'GoethePlaner' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'GoethePlanerTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'GoethePlaner-tvOS' do
  # Pods for GoethePlaner-tvOS

  target 'GoethePlaner-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
```

I would appreciate any help with this, thank you <3

**Comment by dnkoutso** [comment]
Can you run `pod cache clean --all` and retry? Please also upload a sample app.

**Comment by eri47** [comment]
@dnkoutso What do you mean by sample app, i didnt do any coning yet, I was just setting up everything to work with React Native...

**Comment by eri47** [comment]
@dnkoutso I have also tried to set up a new environment now, but here i face the same issue...

### New try

```
(base) ***********@******* New folder % npx react-native init AwesomeProject
                                                          
               ######                ######               
             ###     ####        ####     ###             
            ##          ###    ###          ##            
            ##             ####             ##            
            ##             ####             ##            
            ##           ##    ##           ##            
            ##         ###      ###         ##            
             ##  ########################  ##             
          ######    ###            ###    ######          
      ###     ##    ##              ##    ##     ###      
   ###         ## ###      ####      ### ##         ###   
  ##           ####      ########      ####           ##  
 ##             ###     ##########     ###             ## 
  ##           ####      ########      ####           ##  
   ###         ## ###      ####      ### ##         ###   
      ###     ##    ##              ##    ##     ###      
          ######    ###            ###    ######          
             ##  ########################  ##             
            ##         ###      ###         ##            
            ##           ##    ##           ##            
            ##             ####             ##            
            ##             ####             ##            
            ##          ###    ###          ##            
             ###     ####        ####     ###             
               ######                ######               
                                                          

                  Welcome to React Native!                
                 Learn once, write anywhere               

✔ Downloading template
✔ Copying template
✔ Processing template
✖ Installing CocoaPods dependencies (this may take a few minutes)
✖ Installing CocoaPods dependencies (this may take a few minutes)
error Error: Failed to install CocoaPods dependencies for iOS project, which is required by this template.
Please try again manually: "cd ./AwesomeProject/ios && pod install".
CocoaPods documentation: https://cocoapods.org/

(base) ***********@******* New folder %
```

And when I try to install it manually, I get the same error as above...

**Comment by dnkoutso** [comment]
We are unable to diagnose or debug with a project in ReactNative. Please instead file an issue with them or remove ReactNative in a sample app and upload one that demonstrates your problem.

**Comment by dnkoutso** [comment]
Did you also try what I suggested? `pod cache clean --all`?

**Comment by eri47** [comment]
Yea, I have tried the cache clean and it still didn't work.
 I still think, that this Error has nothing to do with React Native, because it still pops up, when I try to do pod install anywhere, even in non-React Native environments...

**Comment by dnkoutso** [comment]
try `rm -rf ~/.cocoapods/repos` and then try `pod install` again.

**Comment by eri47** [comment]
Now it gives me this Error:

```
(base) **********@******* ios % pod install               

[!] Invalid `Podfile` file: [!] Unable to locate the executable `node`.

 #  from /Users/erikhaarlander/Desktop/Neuer Ordner/AwesomeProject/ios/Podfile:7
 #  -------------------------------------------
 #  target 'AwesomeProject' do
 >    config = use_native_modules!
 #  
 #  -------------------------------------------
```

I have now already tried to fix this issue by doing ```sudo gem install cocoapods``` and ```brew install node```again, but it still doesn't work. Maybe this is, because node 14.8.0 is not linked(as homebrew says)?!

**Comment by eri47** [comment]
btw thank you for all the quick help! <3

**Comment by dnkoutso** [comment]
``` >    config = use_native_modules!
```

That is not official CocoaPods DSL and most likely is ReactNative. Try `pod install` in a non react native project and if it works then I recommend filing an issue there.

**Comment by eri47** [comment]
kk, I'll go and file an issue there for now, as I can see, that this may have something to do with React Native, I'll close this Issue for now... Thanks for all the help and kindness <3

**Comment by dnkoutso** [comment]
yay!
