### ISSUE TITLE
 Expected target or target_proxy, from which to fetch a uuid for target

### ISSUE THREAD

**Issue by mycroftcanner** [CocoaPods/CocoaPods#9995]
### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

trying to add pods to a framework target

I want to use 3 dependencies in a framework and an app target... I don't want these dependencies into any other targets

* What did you expect to happen?

no error

* What happened instead?

pod install emitted an cryptic error 

### Stack

```
   CocoaPods : 1.9.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
    RubyGems : 3.0.6
        Host : macOS 11.0 (20A5323l)
       Xcode : 12.0 (12A8189h)
         Git : git version 2.28.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ 02efb967e6e1d4749320306522c11f28f3b71132

               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
ENV['COCOAPODS_DISABLE_STATS'] = "true"
use_frameworks!

platform :ios, '13.6'

abstract_target 'Texture' do
  pod 'Texture', :git => 'https://github.com/TextureGroup/Texture', :branch => 'master'
  pod 'PINRemoteImage', :git => 'https://github.com/zacwest/PINRemoteImage', :branch => 'fix-xcode-12.0b4'
  pod 'PINCache', :git => 'https://github.com/pinterest/PINCache', :branch => 'master'

  target 'Sample' do
  end

  target 'Style' do
  end
end

post_install do |pi|
    pi.pods_project.targets.each do |t|
      t.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.6'
      end
    end
end
```

### Error

```
RuntimeError - Expected target or target_proxy, from which to fetch a uuid for target ''.Find and clear the PBXTargetDependency entry with uuid '2310D37724EEA91000A2AB69' in your .xcodeproj.
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.16.0/lib/xcodeproj/project/object/target_dependency.rb:62:in `native_target_uuid'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.16.0/lib/xcodeproj/project.rb:609:in `map'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.16.0/lib/xcodeproj/project.rb:609:in `block in host_targets_for_embedded_target'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.16.0/lib/xcodeproj/project.rb:607:in `select'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.16.0/lib/xcodeproj/project.rb:607:in `host_targets_for_embedded_target'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:356:in `block (2 levels) in analyze_host_targets_in_podfile'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:355:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:355:in `flat_map'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:355:in `block in analyze_host_targets_in_podfile'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:354:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:354:in `analyze_host_targets_in_podfile'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:460:in `generate_targets'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:127:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:410:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:235:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:234:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:156:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=Expected+target+or+target_proxy%2C+from+which+to+fetch+a+uuid+for+target+%27%27.Find+and+clear+the+PBXTargetDependency+entry+with+uuid+%272310D37724EEA91000A2AB69%27+in+your+.xcodeproj.&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Found no similar issues. To create a new issue, please visit:
https://github.com/cocoapods/cocoapods/issues/new

**Comment by dnkoutso** [comment]
Please upload a sample app demonstrating the issue.
